### ISSUE TITLE
Support for markdown footnotes?

### ISSUE THREAD

**Issue by buntine** [thepracticaldev/dev.to#1]
I'm just moving my blog from another provider over to dev.to. It's super impressive, well done.

One thing I've noticed is that you don't seem to support "footnotes", which several other markdown dialects seem to support.

Are there any plans for that? I'm willing to help if necessary.

An example of the syntax is here: https://help.ghost.org/hc/en-us/articles/224410728-Markdown-Guide#footnotes

**Comment by benhalpern** [comment]
Yes, absolutely.

Sorry about not responding to this sooner. I didn't even know anybody knew about this repo, but thanks for the feedback. This is exactly the kind of feedback we are looking for.

I'll get on this shortly. I believe this is just a feature we can toggle on our Markdown processor https://github.com/vmg/redcarpet

Markdown processing will also likely be one of the first things we extract to open source.

**Comment by buntine** [comment]
Excellent, thanks! No problems about the delay.

**Comment by benhalpern** [comment]
Footnotes are now turned on for publishing. Still not showing up in the preview while editing, so they won't show up properly until you hit save, for now.
