### ISSUE TITLE
code block with html attributes

### ISSUE THREAD

**Issue by viebel** [thepracticaldev/dev.to#10]
Is there a way to have a block code that renders with html attributes to the `<code>` tag?

**Comment by benhalpern** [comment]
It depends, can you go into your usecase?

**Comment by viebel** [comment]
I'd like to generate the following html:

```html
<pre><code class="lang-js" data-loop-msec="1000">
[1,2,3].map((x) => x + 1)
</code></pre>
```

**Comment by viebel** [comment]
@benhalpern do you know how to do it?
