### ISSUE TITLE
Feature request: Publishing from multiple RSS feeds

### ISSUE THREAD

**Issue by szabgab** [thepracticaldev/dev.to#100]
I post on several web sites. It would be nice if I could publish from more than one RSS feed.

**Comment by ItsPugle** [comment]
Congratulations on the 100th issue/pull request! 🎉

**Comment by pkfrank** [comment]
Hey @szabgab thanks for the suggestion.  This isn't too difficult _technically_, but we don't want to cause confusion by adding multiple RSS feeds on that page right now.  We're going to put this in the backlog and give it fresh eyes soon.

In the meantime, you can simply "swap" your multiple feeds in/out occasionally.  Every time you add a feed we'll fetch the articles (ignoring duplicates), so this might be a stop-gap solution.  Apologies that it's a little bit of a pain at this point 🙏🏽
