### ISSUE TITLE
Upgrade to ruby 2.53 broke docker installation

### ISSUE THREAD

**Issue by edgnets** [thepracticaldev/dev.to#1007]
## Description

Following the docker installation instruction when I run the command **docker-compose build** the build does not finish with success and the following error is raised:

```
Your Ruby version is 2.5.1, but your Gemfile specified 2.5.3
ERROR: Service 'web' failed to build: The command '/bin/sh -c bundle install --jobs 20 --retry 5' returned a non-zero code: 18
```

## Possible cause

As shown on console I looked into the Gemfile and its specify the ruby version 2.5.3 due the changes made by #996. The pulled image from docker hub [starefossen/ruby-node:2-8-stretch](https://hub.docker.com/r/starefossen/ruby-node/) was created with ruby version 2.5.1 and this can be the cause of the error.

For test purpose only I commented the line **RUN bundle install --jobs 20 --retry 5** inside the **Dockerfile** and the build finished with success however I could not proceed with the initialization because the bundle installation is required.  

```
$ docker-compose run web rails db:setup
Starting devto_db_1 ... done
bundler: command not found: rails
Install missing gem executables with `bundle install`
```

 

## Full output console
```
$ docker-compose build
db uses an image, skipping
Building web
Step 1/10 : FROM starefossen/ruby-node:2-8-stretch
2-8-stretch: Pulling from starefossen/ruby-node
55cbf04beb70: Pull complete
1607093a898c: Pull complete
9a8ea045c926: Pull complete
d4eee24d4dac: Pull complete
b59856e9f0ab: Pull complete
c8e2cea26463: Pull complete
0dfbce878a1d: Pull complete
0ba3e917d2a3: Pull complete
60fc92cbea44: Pull complete
ea687728dc02: Pull complete
ba6dbb7a22b9: Pull complete
5d5ba28fb1b2: Pull complete
9b0aba4b9b76: Pull complete
Digest: sha256:f435d117760f551ac30e640fb2773018789ae6d3b8137a2bf338cf83ea38c9bc
Status: Downloaded newer image for starefossen/ruby-node:2-8-stretch
 ---> bd4319326850
Step 2/10 : WORKDIR /usr/src/app
 ---> a8dff7d2f815
Removing intermediate container d189a7882557
Step 3/10 : COPY Gemfile Gemfile.lock yarn.lock ./
 ---> e6bca56cf60a
Step 4/10 : RUN yarn install && yarn check --integrity
 ---> Running in 65f49061f7fa
yarn install v1.9.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 0.13s.
yarn check v1.9.4
success Folder in sync.
Done in 0.03s.
 ---> 44c4a8329275
Removing intermediate container 65f49061f7fa
Step 5/10 : ENV RAILS_ENV development
 ---> Running in ddace76e7d52
 ---> 9bd4e06d98ee
Removing intermediate container ddace76e7d52
Step 6/10 : ENV YARN_INTEGRITY_ENABLED "false"
 ---> Running in 424e1b737924
 ---> bea28042daff
Removing intermediate container 424e1b737924
Step 7/10 : RUN gem install bundler
 ---> Running in 9a81d8b7af35
Successfully installed bundler-1.17.0
1 gem installed
 ---> 6422c67be7b4
Removing intermediate container 9a81d8b7af35
Step 8/10 : RUN bundle install --jobs 20 --retry 5
 ---> Running in 6032d5cbbc30
Your Ruby version is 2.5.1, but your Gemfile specified 2.5.3
ERROR: Service 'web' failed to build: The command '/bin/sh -c bundle install --jobs 20 --retry 5' returned a non-zero code: 18
```

**Comment by rhymes** [comment]
I investigated a bit and:

* dev.to uses the image [ruby-node](https://hub.docker.com/r/starefossen/ruby-node/~/dockerfile/)  in it's Ruby 2 - Node 8 incarnation
* According to [ruby Docker](https://hub.docker.com/_/ruby/) `2-stretch` points to this [Dockerfile](https://github.com/docker-library/ruby/blob/0bdbbff7475155c90a5945f13daf7067a7bd9f11/2.5/stretch/Dockerfile), which sets:

```
ENV RUBY_MAJOR 2.5
ENV RUBY_VERSION 2.5.3
```

I suspect you have to destroy and rebuild the docker images/containers. I did just that and it worked.

**Comment by edgnets** [comment]
> 
> 
> I investigated a bit and:
> 
>     * dev.to uses the image [ruby-node](https://hub.docker.com/r/starefossen/ruby-node/~/dockerfile/)  in it's Ruby 2 - Node 8 incarnation
> 
>     * According to [ruby Docker](https://hub.docker.com/_/ruby/) `2-stretch` points to this [Dockerfile](https://github.com/docker-library/ruby/blob/0bdbbff7475155c90a5945f13daf7067a7bd9f11/2.5/stretch/Dockerfile), which sets:
> 
> 
> ```
> ENV RUBY_MAJOR 2.5
> ENV RUBY_VERSION 2.5.3
> ```
> 
> I suspect you have to destroy and rebuild the docker images/containers. I did just that and it worked.

**Comment by edgnets** [comment]
Thanks for your feedback @rhymes.  _(Sorry for close and reopen status, I made a mistake clicking on the wrong button :blush:)_

Before to open this issue I cleaned my images and containers with the command [docker system prune -a](http://docs.w3cub.com/docker~17/engine/reference/commandline/system_prune/) I will do it again just to double check. I´m running docker on Windows 10, but I think this is not a problem. 

In my current environment when I start the `starefossen/ruby-node:2-8-stretch` image with bash console and check the ruby version is shown `ruby 2.5.1p57`. 

Does the same happen in your environment ? or is shown `ruby 2.5.3`.

```
$ docker run --interactive --tty starefossen/ruby-node:2-8-stretch bash
root@7ed3a65ed535:/# ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
```

**Comment by mhobotpplnet** [comment]
I get same error, tried with just changing the gem file to 2.5.1 I get the build but I think the webpack fails because of it.

**Comment by rhymes** [comment]
@edgnets @mhobotpplnet my bad, I didn't update my local copy with the upstream version so I was effectively using Ruby 2.5.1

I re-created the images with Ruby 2.5.3 and yes, I have the same issue.

What do you suggest? Looking at the [Dockerfile](https://github.com/thepracticaldev/dev.to/blob/master/Dockerfile) I wonder if there's a way to tell it to use Ruby 2.5.3

I wonder if this could be solved by using a multi-stage build or if the only alternative right now is to revert https://github.com/thepracticaldev/dev.to/pull/996

Any ideas @maestromac  ?

**Comment by maestromac** [comment]
I moved off starefossen's to vanilla ruby package and it seems to be working. I'm going to open up a PR very soon for you folks to test it out.

**Comment by rhymes** [comment]
@maestromac ahahha I'm currently doing a similar thing. Switching from starefossen to vanilla ruby + starefossen's commands.

I'll let you do it :-)

**Comment by mhobotpplnet** [comment]
> I moved off starefossen's to vanilla ruby package and it seems to be working. I'm going to open up a PR very soon for you folks to test it out.

Can you point me to which one you are pointing your Dockerfile ? ty

**Comment by rhymes** [comment]
@maestromac @edgnets @mhobotpplnet 

This is what I came up with:

https://gist.github.com/rhymes/05a65868147cd45a6a3f0a0ad5c6d00c

and it seems to be working

I won't submit the PR because @maestromac is working on it as well

**Comment by mhobotpplnet** [comment]
Am testing @rhymes docker file

**Comment by mhobotpplnet** [comment]
Yeah I am ok now with 2.5.3 however am still getting this error (btw am on Mac) 
```
devto_db_1 is up-to-date
Creating devto_web_1 ...
Creating devto_jobs_1 ...
Creating devto_webpacker_1 ...
Creating devto_web_1
Creating devto_jobs_1
Creating devto_web_1 ... done
Attaching to devto_db_1, devto_webpacker_1, devto_jobs_1, devto_web_1
webpacker_1  | bundler: failed to load command: ./bin/webpack-dev-server (./bin/webpack-dev-server)
webpacker_1  | Errno::ENOENT: No such file or directory - /usr/src/app/node_modules/.bin/webpack-dev-server
webpacker_1  |   /usr/src/app/bin/webpack-dev-server:65:in `exec'
webpacker_1  |   /usr/src/app/bin/webpack-dev-server:65:in `block in <top (required)>'
webpacker_1  |   /usr/src/app/bin/webpack-dev-server:64:in `chdir'
webpacker_1  |   /usr/src/app/bin/webpack-dev-server:64:in `<top (required)>'
```

**Comment by rhymes** [comment]
@mhobotpplnet you could try to rollback your master copy to the commit before the Ruby 2.5.3 PR - this https://github.com/thepracticaldev/dev.to/commit/801043ab0d08f6a9c5f1a005e777d842d06d14cb - and see if you still have that error

**Comment by maestromac** [comment]
@mhobotpplnet I think your issue is related to something else. Let's move this conversation back to https://github.com/thepracticaldev/dev.to/issues/1001

**Comment by maestromac** [comment]
Thank you for reporting this @edgnets ! Please let us know if this issue still persists.

**Comment by rhymes** [comment]
Thank you @maestromac!

**Comment by edgnets** [comment]
> 
> 
> Thank you for reporting this @edgnets ! Please let us know if this issue still persists.

Thank you @maestromac the issue is fixed, I executed with success all steps described in "Docker installation". The server is up and running, I just had an error when access the `localhost:3000`, I will add more information on #1001 since I think it is related with that issue.

**Comment by tinhdang1115** [comment]
> @mhobotpplnet you could try to rollback your master copy to the commit before the Ruby 2.5.3 PR - this [801043a](https://github.com/thepracticaldev/dev.to/commit/801043ab0d08f6a9c5f1a005e777d842d06d14cb) - and see if you still have that error

I still has this issue after reset to the commit 801043a

![image](https://user-images.githubusercontent.com/2344080/48914295-199a8c80-eecf-11e8-9cc4-63f9d3a0b0a5.png)
