### ISSUE TITLE
Username runs into comment date (iPhone)

### ISSUE THREAD

**Issue by shimmoril** [thepracticaldev/dev.to#101]
# _BUG_
### Current Behavior
If a username + Twitter/Github icons is too long, it overlays the posted date of a comment. 

### Expected Behavior
Either wrap the username + icons to a new line, or push the date to a new line. 

### Additional Info (steps to replicate, device/browser, helpful links)
Saw on an iPhone 6s, iOS11, held vertically. 

### Screenshots
![image-1](https://user-images.githubusercontent.com/20954533/31724640-ec5705b4-b3e7-11e7-8a49-dfafa067108e.jpg)

**Comment by Zhao-Andy** [comment]
Ah, good catch. Thanks for that!

**Comment by benhalpern** [comment]
Fixed this. It will roll out gradually as caches expire.

Not without a bit of CSS heartache along the way 😄
