### ISSUE TITLE
Reading List tags should reflect what is available to display

### ISSUE THREAD

**Issue by ItsASine** [thepracticaldev/dev.to#1015]
**Is your feature request related to a problem? Please describe.**

Somewhat related to #708. Since all saved posts are not shown on the Reading List (just 45, which I assume is for performance), it doesn't make sense to show the list of tags for the entire reading list. The pain point here is that clicking `#career (60)` might only show 10 things since only 10 of the most recent 45 are tagged with career. Or worse, clicking `#portfolio (2)` will say there is nothing in the reading list to display.

**Describe the solution you'd like**

If 45 max are to be displayed at any given time, I would expect the tags list to only show the tags relevant to the 45 items I can see. Also, the counts should reflect the count within the available items not the entire reading list.

**Describe alternatives you've considered**

If #708 gets addressed, this is moot. Also, depending on why the 45 is how it is, it may be a nice alternative to have selecting the tag to requery the reading list and pull all the relevant ones under that tag. Like in the above example, `#portfolio (2)` has none originally but specifying that I want to read those ones makes it shown.

**Additional context**

![screen shot 2018-10-26 at 7 07 32 pm](https://user-images.githubusercontent.com/11020425/47596196-abf05480-d952-11e8-89d1-e572eedb5bcb.png)
A screenshot of the tags I'm talking about since the Reading List doesn't get much love so people may not be aware of the tags.

It's nice to see the tags I clearly want to read later, but the act of clicking them is utterly useless in its current state since it only filters the most recent articles.

**Comment by kiranjd** [comment]
Yes, I think this is useful

**Comment by jessleenyc** [comment]
It certainly seems like once #708 is taken care of, we'll be all good here. For anyone who wants to work on this, it would probably make sense to work on #708 first.

**Comment by lightalloy** [comment]
Probably this is fixed with #708

**Comment by ItsASine** [comment]
Confirmed #708 fixed this. Thanks, @lightalloy 😄
