### ISSUE TITLE
Can't save profile because the 'Twitter username has already been taken'

### ISSUE THREAD

**Issue by phansch** [thepracticaldev/dev.to#102]
# _BUG_
### Current Behavior
When I try to save my profile on https://dev.to/settings, it tells me that the 'Twitter username has already been taken' and the other changes I made were not persisted.

This is *probably* because I once signed up with Twitter, which created a different dev.to account. Unfortunately I could not find a way to delete that dev.to account. I also revoked access for the dev.to app on my twitter account, but that didn't help either.

### Expected Behavior
I would like to be able to save my profile, even if the twitter profile has already been taken, either by disconnecting the twitter identity from the profile or by deleting the other dev.to account.

### Additional Info (steps to replicate, device/browser, helpful links)

Browser: Firefox Nightly 58.0a1 (2017-10-13)

This happens also when I try it again in private browsing, so it's not related to caching, I guess.

1. Create a dev.to account with GitHub
2. Create a different dev.to account with Twitter
3. Login to dev.to with the GitHub account
4. Add the twitter account from step 2 in your profile settings (this works and it will show up in the profile)
5. Now edit the profile again, entering some extra information
6. Click the save button and notice the error message and that none of the changes from step 5 have been saved.

### Screenshots
![selection_001](https://user-images.githubusercontent.com/2042399/31785540-c0352ae6-b505-11e7-945c-c0d9f6cc667d.jpg)

**Comment by Zhao-Andy** [comment]
Hey @phansch, thanks for the heads up. We've fixed this for _most_ and new users, but some accounts still have this issue.

We'll be making improvements to the whole OAuth process soon, and this will be included in that. 

I've fixed your account now; you should have both your Twitter and GitHub identities attached to a single user.

**Comment by phansch** [comment]
Thank you for the quick response, it works now :+1:

**Comment by Hilbrand** [comment]
I have the same problem. It still seems not to have been fixed...It's really annoying because somehow I now get all notification e-mails that I can't disable, can't change the e-mail address and can't delete the account.. :disappointed:

**Comment by Zhao-Andy** [comment]
Hey @Hilbrand, sorry about that, you should be able to log in with either Twitter or GitHub. Let me know if you are still getting duplicate emails though; that should be fixed as well.
