### ISSUE TITLE
Twitter/GitHub account username setting is temporary and irreversible.

### ISSUE THREAD

**Issue by dpgowan** [thepracticaldev/dev.to#103]
# _BUG_
### Current Behavior
Twitter/GitHub account username setting is temporary and irreversible.
### Expected Behavior
The ability to unset/change Twitter and/or GitHub account usernames.
### Additional Info (steps to replicate, device/browser, helpful links)
Whoops! Verified the wrong Twitter account after signing up with an existing GitHub account and now it cant be changed.
- Signing out and signing in with Twitter, of course, creates a new account that won't let you link your existing GitHub account (due to being linked via another user).
- No ability to delete the account and start again.

**Comment by Zhao-Andy** [comment]
Hey @dpgowan, thanks for the heads up. We'll be making improvements to our OAuth system soon, and this is definitely on our to-do. 

I manually updated your account to have both your personal Twitter and your GitHub account; let me know there's still the wrong account linked to it.
