### ISSUE TITLE
Can't change Github username

### ISSUE THREAD

**Issue by meisekimiu** [thepracticaldev/dev.to#105]
# _BUG_
### Current Behavior
My dev.to profile currently has my old Github username attached to it, so clicking on it just links to a 404.
### Expected Behavior
There should be some method to update Github profile information.
### Additional Info (steps to replicate, device/browser, helpful links)
Repo info seems up to date which should make sense for Github API requests, but I assume the username is stored permanently as it ideally *shouldn't* change.
### Screenshots
Will a link do? https://dev.to/meisekimiu

**Comment by Zhao-Andy** [comment]
Sorry about that, that's a bug on our end. I've updated your dev.to account with your new GitHub username.
