### ISSUE TITLE
Impossible to login if you have an invalid RSS feed URL

### ISSUE THREAD

**Issue by franciscoj** [thepracticaldev/dev.to#1051]
**Describe the bug**

When the RSS feed url is wrong or not valid you can't sign in to your account and you see an error messages instead that reads: `Feed url is not a valid rss feed`

__EDIT__: I was still able to browse from my account on any device in which I had already logged in (In this case in my cell phone).

**To Reproduce**

I can't because once you fix the url, you can't set an invalid one anymore.

Reproduced login in with both Twitter and Github.

**Expected behavior**

You can login even when the RSS feed is invalid.

**Screenshots**

I couldn't take any and now I can't reproduce it anymore because I can't enter an invalid URL, sorry :(

**Desktop (please complete the following information):**

- OS: any
- Browser: managed to reproduce in FF 64.0b4, chromium  70.0.3538.77

**Smartphone (please complete the following information):**

- Device: OnePluse 3T
- OS: Android 8.0.0
- Browser: Firefox
- Version: 62.0.2 (latest as of Nov 2nd 2018)

**Additional context**

I suspect the issue is that I added a wrong RSS feed and a validation was added to it afterwards so that the next time I wanted to login writing to the relevant model was impossible because of that.

**Comment by maestromac** [comment]
Thank you for reporting this issue @franciscoj ! I believe your suspicion is correct.

cc @Zhao-Andy

**Comment by Zhao-Andy** [comment]
Hey @franciscoj, I've removed your feed URL for the time being. Thanks for bringing this up.

**Comment by Zhao-Andy** [comment]
Also meant to mention that @franciscoj you should be able to login now. Let us know if otherwise though.

**Comment by franciscoj** [comment]
Hi! Thanks! I was able to login on my desktop after I changed the URL myself from my cell phone, which was already logged in. So, no worries.

Let me know if I can help in any way!

**Comment by Zhao-Andy** [comment]
After some investigation, it seems like sometimes even `valid` users with RSS feed URLs attached can prevent sign ins. Will need to research some more.

Possibly related to #1223

**Comment by dmerejkowsky** [comment]
I *do* have a valid RSS url  (https://dmerej.info/blog/index.xml) but still can't log in on any new browser.

Any clues?

**Comment by jessleenyc** [comment]
@dmerejkowsky are you still experiencing this?

**Comment by dmerejkowsky** [comment]
Nope, the problem was resolved quite some time ago by performing a manual operation on the DB.

I forgot to update the issue there, sorry.

**Comment by jessleenyc** [comment]
Great! Closing this for now but will reopen if someone else experiences this issue.
