### ISSUE TITLE
Deny "http(s)://..." headlines automatically.

### ISSUE THREAD

**Issue by dertuxmalwieder** [thepracticaldev/dev.to#1058]
As most the ridiculous spambots flooding DEV lately usually only post one pointless "hi everyone" thread (nothing too bad) and then exactly two "postings" which have an URI as a headline, it might be worth to just deny new articles with a headline that matches an URI regex.

**Comment by benhalpern** [comment]
Good call. I think sometimes we get too caught up in working towards smart solutions instead of stamping out what we’re seeing now.

We should create an automatic denial condition which catches certain posts (like this one) possibly auto-suspending the authors.

**Comment by dertuxmalwieder** [comment]
... and retro-deleting their first pointless "welcome" thing! ;-)

**But** you should make it as modular as possible. You know, if some day URL-only articles have a reason (maybe for OEmbed?).

**Comment by jessleenyc** [comment]
We implemented a solution via our spam detection API so we shouldn't be seeing this anymore.
