### ISSUE TITLE
Problems hearting comments and posting replies

### ISSUE THREAD

**Issue by AnonJr** [thepracticaldev/dev.to#106]
# _BUG_
Probably not a high priority issue, and I'm not sure exactly when it started, but worth noting.

### Current Behavior
I'm not able to heart comments or post replies. The submission goes out, and that's about all that happens.

**Heart not working:**
![heartnotworking](https://user-images.githubusercontent.com/791516/32345605-1568c050-bfe1-11e7-895b-1842d4b2b793.gif)

**Comment not working**
![commentnotworking](https://user-images.githubusercontent.com/791516/32346027-5794ee44-bfe2-11e7-8650-3615815a84f3.gif)

### Additional Info
The most pertinent part is that this only happens when I try from my work PC, so it might be related to the browser restrictions and/or the company's content filtering.

We are on IE11 (yes, it's IE - but at least it's IE11?)
![ie_version_info](https://user-images.githubusercontent.com/791516/32344470-5b89e8a6-bfdd-11e7-870a-35cfcd02ef39.png)

I suspect that the issue is this request going out to Facebook, because Facebook is blocked here at work.
![f12_network_summary](https://user-images.githubusercontent.com/791516/32344469-5b6e2c9c-bfdd-11e7-95bd-69e40a2b4735.png)

I don't think these are related to this particular issue, but there are a few issues that showed up in the console as well. Reguardless of this issue, the extra tags in the rendered HTML are probably worth looking into. I'm fairly sure the JavaScript issues are more related to IE than anything else.
![f12_console_info](https://user-images.githubusercontent.com/791516/32344471-5b99b70e-bfdd-11e7-8bf2-76ccf9b01ace.png)

###### Side Notes
Screenshots were taken using [Greenshot](http://getgreenshot.org/) - a fabulous tool. The GIF was created using [ScreenToGif](http://www.screentogif.com/) - a sometimes frustrating, but useful tool. Both are free, and can be run off a thumb drive.

**Comment by jessleenyc** [comment]
Thanks for the detailed issue! We'll investigate.

**Comment by benhalpern** [comment]
This is part of a bigger issue of browser support and polyfills we need to work out, so I'm going to close this specific issue. Thanks for bringing this up and we're dealing with it via some big picture decisions.
