### ISSUE TITLE
View Stats not working 

### ISSUE THREAD

**Issue by aspittel** [thepracticaldev/dev.to#1060]
**Describe the bug**
My view data is constantly loading. Up until a week and a half ago or so it was working fine! I am getting a console error: 

<img width="1164" alt="screen shot 2018-11-04 at 8 20 46 pm" src="https://user-images.githubusercontent.com/12969662/47972969-4ea18500-e06f-11e8-84fe-8b469911425c.png">

I disabled my adblocker because I thought it might be the issue but it isn't.

**To Reproduce**

I just navigate to the `dashboard` view -- I think this happened right around hitting 300,000 views so maybe related to that?

**Expected behavior**

View data to show up!

**Screenshots**

Just getting the loading text and it never turns into the actual views, even minutes later.

**Desktop (please complete the following information):**

- OS: [e.g. iOS] iOS
- Browser [e.g. chrome, safari] chrome! the same thing happens on FireFox and the iOS app though.

**Additional context**

I'm not at all worried about this personally, just thought you all might want to know!

**Comment by jessleenyc** [comment]
hmm @benhalpern is this what you've seen on your own stats as well?

**Comment by aspittel** [comment]
They work again with the new update, thanks!!
