### ISSUE TITLE
Reading list is counting one article when there are none

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#1061]
**Describe the bug**

My reading list says "1" article but I have none in the list.

Could it be a caching issue?

I've also tried to remove local storage and cookies, then login again but it still says 1

**Expected behavior**

I expect the counter to be zero (unless there's a post that's not showing up for some reason)

**Screenshots**

![screenshot_2018-11-05 reading list - dev to - dev community](https://user-images.githubusercontent.com/146201/47989078-3e77bd00-e0e4-11e8-9189-08fdd806cc3b.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Firefox
- Version: 64

**Comment by rhymes** [comment]
@jessleenyc 

I think I found more clues.

My comment activity section is populated with the following comments from an older post:

![screenshot_2018-11-09 reading list - dev to](https://user-images.githubusercontent.com/146201/48280717-b6cbde80-e454-11e8-83e8-2e45835b7592.png)

Yet, when I click on the article to which the comments belong, I get a 404: https://dev.to/entrptaher/how-does-big-teams-share-secrets-in-their-repo-1d2f

**Comment by rhymes** [comment]
@maestromac yeah, my counter says 7 but I have only 6 articles saved

**Comment by maestromac** [comment]
Pretty certain this is fixed by https://github.com/thepracticaldev/dev.to/pull/1149 . Let us know if otherwise!

**Comment by rhymes** [comment]
@maestromac now I have 3 instead of 1 :-(

![screenshot_2018-12-10 reading list - dev to](https://user-images.githubusercontent.com/146201/49730765-ac7e4980-fc79-11e8-8876-7fc2ae7277a0.png)

**Comment by maestromac** [comment]
darn it.

**Comment by rhymes** [comment]
@maestromac could it be a caching problem?

I checked my local storage and in `reading_list_ids` I have other articles IDs

**Comment by maestromac** [comment]
@rhymes can you try removing/unregistering the service worker, reload the page, and check if you are still experiencing this?

**Comment by rhymes** [comment]
@maestromac yep, I deleted the sw on Firefox and reloaded and nothing changed. I've also tried using Safari in private mode, after resetting it (I don't use it as a browser) and I still get 4 in the count.

This is my reading list in the local storage object: `"reading_list_ids": [68069,66493,64755,54908]`

Maybe you can check it against the two articles I have saved:

* https://dev.to/vintharas/how-to-write-a-game-in-under-13-kb-while-taking-care-of-a-baby-4160
* https://dev.to/ben/will-java-trend-towards-obscurity-kke

**Comment by maestromac** [comment]
I believe this is because the list ids are out of sync with Algolia. Any thought on this @benhalpern ?

**Comment by jessleenyc** [comment]
This is correct! We'll need to look into algolia de-indexing or if they readling list reaction didn't get deleted.

**Comment by rhymes** [comment]
unstale

**Comment by thomasbnt** [comment]
A similar concern on this subject, I have 74 registered articles, only I did the cleanup a little while ago and I'm at 4. It always shows me the wrong number even after forcing the empty cache and a reconnection to my account.
![image](https://user-images.githubusercontent.com/14293805/74668232-11e69800-51a5-11ea-8ec3-2df3a8b383b6.png)

![image](https://user-images.githubusercontent.com/14293805/74668226-0c894d80-51a5-11ea-84f7-1eb81a2c660d.png)

**Comment by mstruve** [comment]
Since moving to Elasticsearch this problem should be fixed now. We were not updating reactions with article updates before.

**Comment by rhymes** [comment]
@mstruve did we also run a script for the backlog?

**Comment by mstruve** [comment]
Script run to cleanup stale data.
