### ISSUE TITLE
Can't use tag templates on v2 editor

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#1073]
**Describe the bug**
Only tags are coming through on templates on v2 of the editor. 

**To Reproduce**

On v2 editor, visit dev.to/new/icymi

![](https://cl.ly/597a8b4146ae/download/Image%202018-11-05%20at%206.56.48%20AM.png)

**Screenshots**

**Desktop (please complete the following information):**

**Comment by djhopper01** [comment]
Hi @jessleenyc I think I know where to fix this. I'll write a test for this and submit a fix at some point this weekend. It looks like [the only information being added to `@article` is the tag](https://github.com/thepracticaldev/dev.to/blob/b29a155eddcddf1ca379fb9526f5baba45d8b4fa/app/controllers/articles_controller.rb#L45).

**Comment by jessleenyc** [comment]
hey @djhopper01, are you still interested in working on this?

**Comment by djhopper01** [comment]
@jessleenyc Hey, thanks for reminding me about this. I started with a new company recently and lost track of this. I'd love to help, but if someone else wants to jump in sooner that's OK too. I may not have much bandwidth for a few weeks.
