### ISSUE TITLE
See text to 'Follow @user_username to see more...' when I am the author

### ISSUE THREAD

**Issue by davidjeddy** [thepracticaldev/dev.to#1079]
**Describe the bug**
Follow text displayed when I am the author of an article displayed in the "Class DEV Post from ..." card.

**To Reproduce**

1. Write an post
2. Have it appear in the 'Class DEV Post from ...' card at the bottom of an article
3. See text to 'Follow @user_username to see more...'

**Expected behavior**
Can not follow myself, text should not be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/6232455/48146329-baa80700-e282-11e8-8381-0be586a55afc.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- OS: Win10
- Browser Chrome 
- Version 

**Additional context**
I am @david_j_eddy on dev.to

**Comment by Zhao-Andy** [comment]
Hey @davidjeddy, thanks for the bug report. Think this is a pretty straightforward fix.

This line here is where the logic happens: https://github.com/thepracticaldev/dev.to/blob/76f6a8f9df8401a38abb7c6b1ba2c34caaec8235/app/views/additional_content_boxes/_article_followable_area.html.erb#L34

I _think_ this is the right logic for a one line fix:
```ruby
current_user == followable ? "" : (follow_cue&.html_safe || followable.summary)
```

There might be a cleaner way of solving this, but that's the first one I thought of.

**Comment by davidjeddy** [comment]
One day I'll learn Ruby...

**Comment by jessleenyc** [comment]
This is approved if anyone wants to work on it! There are some notes from @Zhao-Andy above on a potential fix.

**Comment by halfghaninne** [comment]
Hey @jessleenyc I'd love to work on this!

**Comment by jessleenyc** [comment]
@halfghaninne awesome!

**Comment by ashishg-qburst** [comment]
@jessleenyc Ben has removed the follow cue entirely with #1085.

@benhalpern Don't know if you intended this, but cues in this file will be hidden too.

https://github.com/thepracticaldev/dev.to/blob/master/app/views/additional_content_boxes/boxes.html.erb

**Comment by benhalpern** [comment]
Yes, @ashishg-qburst removed intentionally. I'll close this issue. Thanks for the input everyone.
