### ISSUE TITLE
why :thinking_face: is not be a 🤔 ?

### ISSUE THREAD

**Issue by naari3** [thepracticaldev/dev.to#108]
# Feature
### Request or User Story

`:thinking_face:` is must be a 🤔

### Definition of Done

When `:thinking_face:` became a 🤔

### Notes

Please

**Comment by Zhao-Andy** [comment]
Hey, thanks for the feature request. We'll put it in our backlog for now since we're ramping up to open source.

**Comment by jessleenyc** [comment]
Hey, we actually removed the thinking face from reactions so I'm closing this issue.
