### ISSUE TITLE
Add GitLab field to Profile

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/dev.to#1080]
**Is your feature request related to a problem? Please describe.**
Much like we have other links like Facebook, StackOverflow, LinkedIn, etc. we should add GitLab.

**Describe the solution you'd like**
We'll need to add:
- an additional column to user table/model.
- a Rails validation similar to the other validations, as seen in `app/model/user.rb`
- the field to the settings page `views/users/_profile.html.erb`
- the GitLab icon as an SVG into `app/assets/images`
- Make sure it works
- Add tests for it

**Comment by sidemt** [comment]
Can I try this?

**Comment by Zhao-Andy** [comment]
Go for it! Let us know if you have questions.

**Comment by sidemt** [comment]
@Zhao-Andy 
> the GitLab icon as an SVG into app/assets/images

Is it OK to download the SVG from Font Awesome? I referred to issue #901 and believe it's OK.

**Comment by sidemt** [comment]
@Zhao-Andy 
I wrote the code, but I can't find out how to sign in on the local environment. So cannot check the behavior. 

When I click the SIGN IN link, I get 404 Page not found for GitHub, 401 Authorization Required for Twitter.

I have set `GITHUB_KEY` `GITHUB_SECRET` `TWITTER_KEY` `TWITTER_SECRET` (And also `TWITTER_ACCESS_TOKEN` `TWITTER_ACCESS_TOKEN_SECRET`) according to this document https://docs.dev.to/get-api-keys-dev-env/

Am I missing some configurations?

**Comment by Zhao-Andy** [comment]
@sidemt Yeah, using the Font Awesome SVG is okay.

You should be able to login to the local environment if you've setup your API keys properly. Make sure your Twitter app's callback URL is ` http://localhost:3000/users/auth/twitter/callback` and your GitHub app's homepage URL is `http://localhost:3000`.

Also, you probably have this already, but make sure your keys should be set in `config/application.yml` and not `config/sample_application.yml`.

**Comment by Zhao-Andy** [comment]
Hm, not sure what else would be preventing it. Another general "oops" would be to restart your server, or if you're using Spring to run `spring stop`.

Let's continue this via email (I've sent an email to your dev.to account's email) since this is more of a development issue and not related to the GitLab issue.

**Comment by sidemt** [comment]
Thank you for your kind help @Zhao-Andy ! As I mentioned in the email I could successfully sign in by restarting the server. PR submitted.
