### ISSUE TITLE
Comment's cancel button always route back to article

### ISSUE THREAD

**Issue by maestromac** [thepracticaldev/dev.to#1081]
**Describe the bug**
We have a lovely cancel button that would allow the comment creator to change their mind on editing their comment. Ideally, it should bring the user back to where they were previously but it currently reroutes the user to the article of which the comment belongs to.

**To Reproduce**

0. Log in to https://dev.to
1. Navigate to your profile page (https://dev.to/[your-profile-name])
2. Select one of your comment on your profile.
3. Click edit button.
4. Click cancel.
5. Notice that instead of send you back to /dashboard, it sends you to the article link.

**Screenshots**
![](https://cl.ly/68d4855e5ca6/Image%202018-11-07%20at%2012.49.07%20PM.png)

**Comment by rodrigopdl** [comment]
Hi @maestromac !

I've been trying to reproduce this issue locally, so as to work on a fix, but wasn't able to mimic the described behavior.

I'm not seeing comments when I visit `/dashboard`, so I can't complete step 2.

![image](https://user-images.githubusercontent.com/3510791/48308002-72197380-e538-11e8-82da-cc9dcf6158f4.png)

I tried adding comments to different posts in the site, but still don't see them appear here.

Am I missing something?
Thank you!

**Comment by Link2Twenty** [comment]
You almost want the button to be a back button, currently, it's just an anchor that links to the main post.

https://github.com/thepracticaldev/dev.to/blob/908e82cf9efe37bc41f10eb54b3c1a8b42f18d95/app/views/comments/_form.html.erb#L51-L53

Perhaps changing the link to have `<%=commentable.path%>#comment-node-[comment_id]` would help make it feel.

Is there any reason we don't use a model popup for edit and delete?

**Comment by maestromac** [comment]
Hey @Link2Twenty, changing this to a model popup is nice to have but I figured updating the `cancel` functionality is a quicker fix. But you brought up a nice feature request!
