### ISSUE TITLE
Trap attempts to connect to an existing user's github account.

### ISSUE THREAD

**Issue by moopet** [thepracticaldev/dev.to#109]
### Current Behavior
Attempting to authorise the same github account on a second dev.to account makes the profile form (and all other settings which share the page) unsaveable with the error "Github username has already been taken". The profile's "Action" field still says "Connect github account". **This problem persists after leaving the page, and even after logging out and back in**

### Expected Behavior
Either the "Action" field should have a "disconnect" action or authorisation with an existing github account should be stopped before it gets to that point. 

### Additional Info
Duplicate accounts are all too easy when you can sign in using multiple authenticators (github and twitter in this case)

**Comment by Zhao-Andy** [comment]
Thanks for the feedback. Definitely something I've been meaning to work on.

**Comment by Zhao-Andy** [comment]
Hey, sorry for the incredibly late response. I've manually merged your two accounts together and you should be good. We'll be implementing better OAuth logic soon, too. Let me know if anything is still off.
