### ISSUE TITLE
Posts with long lines within `backticks` sometimes truncate on the right-hand side of the page.

### ISSUE THREAD

**Issue by zspencer** [thepracticaldev/dev.to#1090]
Long lines within paragraphs or list items with ``` ` ``` backticks around their content don't wrap.

**To Reproduce**
Given a post with a single, very long line enclosed in ``` ` ```'s (say 200 characters)
When I view the outputted post 
Then I do not see all the text, as the line did not break.
And I can not scroll to the right to see the rest of the text

**Expected behavior**
I would expect there to be some way to at least view the long line, if not allow it to word-wrap naturally.

**Screenshots**
<img width="881" alt="screen shot 2018-11-10 at 5 37 18 pm" src="https://user-images.githubusercontent.com/50284/48308061-decc4800-e50f-11e8-8b77-75e4b4ce4671.png">

**Desktop (please complete the following information):**

- OS: Mac OS 10.12?
- Browser: Safari
- Version: 12.0

**Comment by pkfrank** [comment]
@zspencer thanks for this detailed report!

**Comment by Zhao-Andy** [comment]
Hey @zspencer, I can't seem to reproduce this on Firefox or Safari. The text wraps properly for me. Here's an example article: https://dev.to/andy/afsfsfsafd-55do-temp-slug-8717693?preview=e9df2a0a3ca546bbe0852db1ada290745fac6fdd99b2d4ff12f41d35732cf879da186956a8d5b61d617ee0a06fc4056c89372579b2eefff568afca5f

Do you have some sample Markdown we could use to reproduce this?

**Comment by zspencer** [comment]
Interesttttiinnnnggggg. It doesn't happen on posts! Here is the comment where I noticed the bug initially - https://dev.to/zspencer/comment/6m9n

**Comment by zspencer** [comment]
I tried responding to your post to see if I can make it happen there as well, but I can't comment on a non-published post it seems.

**Comment by zspencer** [comment]
And here's a touch more useful information, it appears to not occur when *previewing* a comment, only when the comment is published.

Published comment:
<img width="894" alt="screen shot 2018-11-14 at 1 05 34 pm" src="https://user-images.githubusercontent.com/50284/48512313-0a9c4600-e80e-11e8-940c-1dade37f358d.png">

What Preview shows 
<img width="801" alt="screen shot 2018-11-14 at 1 05 23 pm" src="https://user-images.githubusercontent.com/50284/48512314-0a9c4600-e80e-11e8-97c2-b7da320631f1.png">

**Comment by Zhao-Andy** [comment]
Oh very interesting. Thanks for all the details! I'm going to add it to the recap :) https://dev.to/devteam/devto-repo-recap-of-the-past-week-13en

**Comment by maestromac** [comment]
not stale

**Comment by hakash** [comment]
![image](https://user-images.githubusercontent.com/8034094/66722695-605be280-ee11-11e9-8755-40ea615d932d.png)
Was looking into this, and in Chrome at least, it seems to have resolved itself. The screenshot is from the quoted comment.

**Comment by zspencer** [comment]
Closing as it appears to have been resolved
