### ISSUE TITLE
If the article title contains the # character, the tweet in the sharing dialog is cropped. 

### ISSUE THREAD

**Issue by thiodordelis** [thepracticaldev/dev.to#1091]
If an article title contains the '#' character, then when sharing to Twitter, the tweet content is cropped.

Steps to reproduce the behaviour:
1. View an article with the # character in the title.

- https://dev.to/essentialdeveloper/1-reason-why-you-dont-improve-as-a-software-developer-1mhk
- https://dev.to/kouna_to/update-2-just-a-prototype-game-133 

2. Click the Twitter share link
3. Tweet is cropped from the # character and after.

**Screenshots**
![screen shot 2018-11-11 at 14 21 37](https://user-images.githubusercontent.com/21237091/48312839-3f658e80-e5bd-11e8-8006-d221e1dfca73.png)

Mac OS 10.12
All browsers

**Comment by rhymes** [comment]
The weird thing is that it happens also if the "hashtag" is anywhere else in the string:

![untitled](https://user-images.githubusercontent.com/146201/48315203-7b0b5300-e5d3-11e8-8acb-9652eb14cb4f.gif)

**Comment by shindakun** [comment]
Looks like the title should be URL encoded in the share link.

**Comment by rhymes** [comment]
@shindakun exactly, if you URL encode it, it works

**Comment by maestromac** [comment]
Thank you for reporting this issue @thiodordelis !
