### ISSUE TITLE
Playing podcasts can be a hit-or-miss

### ISSUE THREAD

**Issue by jagtalon** [thepracticaldev/dev.to#110]
# _BUG_
### Current Behavior
It seems that sometimes I get an "error" message in the UI when trying to play a show but clicking on the player multiple times seems to make it work. This happens on all browsers it seems and sometimes the console does show an error message but I'm not sure if that's related. It seems to happen when I try to play any podcast.

<img width="1440" alt="screen shot 2017-11-16 at 10 20 41 am" src="https://user-images.githubusercontent.com/81969/32905869-7c6aefc6-cab8-11e7-9877-9202ff89e444.png">

### Expected Behavior
Should play once it's clicked and probably not say "error" in the UI.

**Comment by Zhao-Andy** [comment]
Thanks for the feedback! We'll let you know when it's fixed.

**Comment by Zhao-Andy** [comment]
There should be a much better response now when you first click the play button, and subsequent clicks shouldn't show the "error" message anymore. Sorry for the late, late fix... 🙈

**Comment by jagtalon** [comment]
Yuss thank you!!!
