### ISSUE TITLE
Search results returning unavailable users/articles

### ISSUE THREAD

**Issue by tone-dev** [thepracticaldev/dev.to#1102]
**Describe the bug**

404 error returned when clicking on search result. I've only been able to replicate this for the affected article and the user that created the article - I believe their account either doesn't exist any more or has had an alias change.

"The page you were looking for does not exist (404)" appears in the title. "You have lost your way." appears in the body, linking back to the home page.

[User](https://dev.to/kasperfred), [article](https://dev.to/kasperfred/how-to-securely-store-user-passwords-497a).

**To Reproduce**

1. Go to 'any functioning page within dev.to'
2. Click on the search bar and type in "python password"
3. Scroll down to "How To Securely Store User Passwords" by Kasper Fredenslund, posted on March 30th.

**Expected behavior**
Either for the post to display or for the search results not to return the article as no longer available. 

Sounds so harsh, sorry! Just raising as might be an unknown issue - couldn't find another example issue. 

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04, Windows 10
- Browser: Firefox, Chrome
- Version: Firefox 62.0.3, Chrome 69.0.3497.100

**Comment by pkfrank** [comment]
@tone-dev thanks for the detailed report.  I can [verify](https://dev.to/search?q=python%20password) this is a problem.

**Comment by jessleenyc** [comment]
https://github.com/thepracticaldev/dev.to/pull/1501 Should resolve this 🤞
