### ISSUE TITLE
Add informations in dashboard

### ISSUE THREAD

**Issue by GMartigny** [thepracticaldev/dev.to#1103]
**Is your feature request related to a problem? Please describe.**
I was trying to gain insight on what kind of article are more successful. In my Dashboard, I can see every articles I've made, but no infos at all. I have to open each which is more painful the more articles you have.

**Describe the solution you'd like**
There's space left on the right-side of the action bar. It could show "reactions" and "comments" count like on front-page.

**Describe alternatives you've considered**
Maybe an additional "Statistics" page which could show all of this and more ??

**Additional context**
The infos you can cram, the better:
 - Reaction and comments
 - Publish date
 - Tags used
 - Series
 - ...

Thanks

**Comment by jessleenyc** [comment]
Thanks for the request. 

@benhalpern i think this makes a lot of sense, in addition to incorporating analytics. what do you think?

**Comment by benhalpern** [comment]
Hey @GMartigny great timing. We just released a big part of this.

https://dev.to/devteam/changelog-post-analytics-available-for-all-5eb0

But you definitely bring up some good points about other stuff we can cram in. Will add some of what you brought up now.

**Comment by benhalpern** [comment]
Closed! #1118
