### ISSUE TITLE
When writing a post, text view doesn't follow cursor

### ISSUE THREAD

**Issue by trueneu** [thepracticaldev/dev.to#1109]
**Describe the bug**
When writing a new post, the text view doesn't follow the cursor.

**To Reproduce**

1. Go to https://dev.to/new
2. In the post text box, enter text large enough it doesn't fit to a single view without a scroll
3. Try to scroll back up with your arrow keys
4. See error and blinking header

**Expected behavior**
View port does follow the cursor. Header doesn't blink.

**Screenshots**
https://youtu.be/2ALeGuxrC7k . Watch the cursor. Each time the image twitches, an arrow key is pressed.

**Desktop**

- macOS 10.13.4
- Google Chrome
- v 70.0.3538.102
- Regular mode, Incognito mode (no extensions)

**Comment by jessleenyc** [comment]
Thanks for flagging! This is pretty annoying and should be fixed. Approved for anyone who might want to work on it.
