### ISSUE TITLE
Add "Share" button for mobile view

### ISSUE THREAD

**Issue by dvdmuckle** [thepracticaldev/dev.to#111]
#### Feature Request
When browsing dev.to on mobile, specifically reading a given post in the progressive web app, there is no way to easily grab the URL of the post to share it. It would be nice if there were a "share" button on every post page such that one could tap it for multiple option for sharing (Text message, social media, or copy the link to the post.). I know this is possibly with Android, and I'm fairly certain iOS has support for a similar feature.
#### Done condition
When one is able to tap a button on a post page and is given the ability to share the post using any of the above methods, or at the very least be able to copy the URL.

**Comment by Zhao-Andy** [comment]
Thanks for the feedback!

**Comment by philnash** [comment]
On Android, the [Web Share API](https://dev.to/philnash/the-web-share-api) is back in play and probably a good way to implement this.

**Comment by Zhao-Andy** [comment]
@benhalpern just pushed this up :) It's the button to the right of the reactions.

@philnash We didn't end up using the Web Share API, but we might add it in for the next iteration.

**Comment by philnash** [comment]
Great to see share added!

Maybe someone from the community can add the web share API when you open source the app :wink:

**Comment by dvdmuckle** [comment]
Awesome, looks good! 👍
