### ISSUE TITLE
Add a way to report a particuliar user

### ISSUE THREAD

**Issue by Puritanic** [thepracticaldev/dev.to#1112]
**Is your feature request related to a problem? Please describe.**
As I've heard you have a lot of spam accounts joining DEV.to lately, I guess that sometimes some accounts slips through your filters, and it would be helpful, in my opinion, if we have a way to report some users. Here's an example:
<img width="1250" alt="screen shot 2018-11-13 at 8 42 19 am" src="https://user-images.githubusercontent.com/25148427/48398198-68526480-e720-11e8-8541-c290afafd761.png">
I've been followed by this yesterday, looks like a spam account. I've seen several of those in previous weeks, but they seem to be banned now.

**Describe the solution you'd like**
Add Report link to the user page, where we can report spam accounts like this.

**Additional context**
Of course, there is an issue of using this in an unintended way, I guess that some troll users or users annoyed by a particular user could report him for something, which can cause some complications and maybe spam dev admins with bad reports 😕 Maybe hide report button in some drop-down context menu, as it's not a common action.

Thoughts?

**Comment by pkfrank** [comment]
Hey @Puritanic, thanks for the issue.  This relates to #398 and Ben's [comment in that issue](https://github.com/thepracticaldev/dev.to/issues/398#issuecomment-414873708).  But this is a great reminder about the need for this functionality.

In the meantime, please feel free to report this behavior directly at the [Abuse Report form](https://dev.to/report-abuse).

**Comment by Puritanic** [comment]
Whoops, missed that one 😕Great minds think alike 😄 
Joke aside didn't know about this report form until now, gonna use it to report bot/spam accounts, but still, not really intuitive UI. I'll go through the code and see if I can maybe help a bit with this a bit.
