### ISSUE TITLE
Settings do not scroll when opened from ⚡-menu

### ISSUE THREAD

**Issue by lmller** [thepracticaldev/dev.to#112]
Open the Settings on mobile from the "fill out your DEV profile link" that's hidden behind the ⚡

### Current Behavior
Scrolling down is not possible

### Expected Behavior
Scrolling down should be possible

### Additional Info (steps to replicate, device/browser, helpful links)
Android 6.0.1
Chrome 62.0.3202.84

**Comment by Zhao-Andy** [comment]
Had this bug, too. Thanks for reporting and confirming it.

**Comment by maestromac** [comment]
This should be working now. Let us know if otherwise!
