### ISSUE TITLE
Post Analytics Information is partially hiding Edit and Delete Button

### ISSUE THREAD

**Issue by bauripalash** [thepracticaldev/dev.to#1124]
## Problem
I was excited about new Post Analytics feature but while tried to experience this from mobile I noticed that  Post Analytics Information is partially hiding Edit and Delete Buttons.

## Screenshot
<img src="https://user-images.githubusercontent.com/16154204/48561216-7f0ddc80-e915-11e8-9a93-6488e2348a45.png" width="60%" height="auto">

## Possible Fix 
Add More Padding/Margin according necessity here https://github.com/thepracticaldev/dev.to/blob/4ab0a070ea7e661ad1947a082b152211589115a0/app/views/dashboards/_dashboard_article.html.erb#L26

**Comment by equiman** [comment]
It's already solved!

**Comment by bauripalash** [comment]
Thank You! Closing!
