### ISSUE TITLE
Python syntax highlighting doesn't take care of f-strings

### ISSUE THREAD

**Issue by Tadaboody** [thepracticaldev/dev.to#1127]
**Describe the bug**
Python 3.6 introduced [f-formatted strings](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498) 
I'd like the syntax highlighting to take in account the fact that expressions can appear in the middle of f-formatted string literals
**To Reproduce**

1. Create a post
2. Fill it with the following
```md
```py
a = 3
print(f'a={a}')
\```
```
(Last triple back-tick is escaped)
**Expected behavior**
The expression evaluated inside the squiggly brackets should be colored differently to indicate that it is an expression and not a literal string
```py
a = 3
print(f'a={a}')
```
**Screenshots**
The code snippet in VSCode
![image](https://user-images.githubusercontent.com/6463334/48580982-42e47700-e929-11e8-8894-5961eafccf75.png)
The code in Dev.to markdown preview
![image](https://user-images.githubusercontent.com/6463334/48581093-8808a900-e929-11e8-81f9-d91244b1c753.png)

**Desktop (please complete the following information):**

- OS: OS X
- Browser chrome 
- Version 69

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by benhalpern** [comment]
Hmmmmmm, this is the issue in Rouge

https://github.com/jneen/rouge/issues/937

Probably need to track/help with that. 🙂

**Comment by rhymes** [comment]
unstaling this, because the referred issue is still open

**Comment by maestromac** [comment]
not stale

**Comment by dvf** [comment]
🙏

**Comment by rhymes** [comment]
This has been fixed when we merged #7320 

I verified it in the editor:

![Screenshot_2020-04-19 New Post - DEV(local) Community 👩‍💻👨‍💻(2)](https://user-images.githubusercontent.com/146201/79683158-4ff54c00-8228-11ea-9ee6-2764163dc8e1.png)
