### ISSUE TITLE
RSS Feed: Populate category with post's tags

### ISSUE THREAD

**Issue by gabek** [thepracticaldev/dev.to#1128]
It seems like there's a request open for RSS feeds of individual tags, #201, but this is probably a faster way to get somewhat of the same outcome.

I use a RSS reader that allows me to filter based on tags, so it'd be nice to filter out certain topics I don't care about.  It's kind of the opposite of #201 where instead of a feed per tag, it would allow people to stay subscribed to the global feed but filter things out.

**Describe the solution you'd like**
In the RSS feed populate `category` for each post with tags assigned to that item.

https://www.w3schools.com/xml/rss_tag_category_item.asp

**Comment by jessleenyc** [comment]
I feel like that would get unwieldy since there are so many tags across site. It probably makes sense to eventually have both -- specific tags you want to subscribe to, and a global feed that will filter out tags you definitely don't want to see.

**Comment by jessleenyc** [comment]
I must not be understanding your request. Can you please rephrase what you're specifically looking for?

**Comment by gabek** [comment]
No problem!  An example would probably explain it better.  The RSS entry for the article at https://dev.to/msarit/migrating-rails-apps-to-vps---help-f68 currently looks like this:
```
  <title>Migrating Rails Apps to VPS - HELP!</title>
      <author>Arit Amana</author>
      <pubDate>Wed, 05 Dec 2018 01:48:18 +0000</pubDate>
      <link>https://dev.to/msarit/migrating-rails-apps-to-vps---help-f68</link>
      <guid>https://dev.to/msarit/migrating-rails-apps-to-vps---help-f68</guid>
...
```
And I propose it looks like this with the additional `<category>` tags.

```
  <title>Migrating Rails Apps to VPS - HELP!</title>
      <author>Arit Amana</author>
      <pubDate>Wed, 05 Dec 2018 01:48:18 +0000</pubDate>
      <link>https://dev.to/msarit/migrating-rails-apps-to-vps---help-f68</link>
      <guid>https://dev.to/msarit/migrating-rails-apps-to-vps---help-f68</guid>
      <category>help</category>
      <category>rails</category>
      <category>server</category>
      <category>migration</category>
...
```

**Comment by maestromac** [comment]
not stale

**Comment by dpshelio** [comment]
I'm an admin for one of Google's summer of code organisations - OpenAstronomy. As part of our internal rules, we request students to have a blog and post updates of their progress regularly. We aggregate summaries for all their posts on a single site that makes easier to our broad community to find what they are interested in (something like a homemade [planet](https://en.wikipedia.org/wiki/Planet_(software))). Most of the blogs students have used before can provide a feed for a particular tag or include the tags they've used between the post itself. For example, medium does as @gabek suggested but includes the tags as:
```xml
            <category><![CDATA[astronomy]]></category>
            <category><![CDATA[gsoc]]></category>
            <category><![CDATA[open-source]]></category>
            <category><![CDATA[python]]></category>
```
which if I [understood well](https://stackoverflow.com/a/2784200/1087595) is to allow some text that may conflict with the rest of the xml.

Now we've got our first student that's using dev.to, but I can't filter the blogposts this student is doing for the gsoc project or something else as I can't get their tags.

**Comment by rhymes** [comment]
@dpshelio it should be fine now, let us know if it doesn't work for you and thanks for the request!
