### ISSUE TITLE
Feature request - Public API for posts

### ISSUE THREAD

**Issue by codehakase** [thepracticaldev/dev.to#113]
# _TASK or Feature_
### Request or User Story
I want to work on a CLI Project that will enable me read/view latest posts on the dev.to homepage, and on various categories. 

An open api would be great for this.

**Comment by maestromac** [comment]
Thank you for your suggestion! We are planning to implement this in the near future.

**Comment by darol100** [comment]
I love to see this feature happens. I will be more than welcome to help contribute to the JSON schema of this READ API.

**Comment by son1112** [comment]
Yes, yes, YES. I would love to see this happen and would love to contribute to its development!

**Comment by green-coder** [comment]
How about using an [Atom feed](https://en.wikipedia.org/wiki/Atom_(Web_standard))?

**Comment by rhymes** [comment]
this shouldn't probably go stale

**Comment by khanhicetea** [comment]
yah, this should be top priority task because it's main way to import content from other platform. (In my case, I want to import my Hugo content to dev.to but current RSS importing really bad option)

**Comment by maestromac** [comment]
not stale!

**Comment by ameersami** [comment]
@maestromac is there a branch that this is being actively being worked on? I would love to contribute to this feature

**Comment by rhymes** [comment]
@ameersami @codehakase there's (since very recently) a beta API for articles/posts, you can find its documentation here https://dev.to/api/

**Comment by jessleenyc** [comment]
Closing this since we have the beta API now!
