### ISSUE TITLE
Incorrect language selection

### ISSUE THREAD

**Issue by shyazusa** [thepracticaldev/dev.to#114]
# _BUG_
### Current Behavior

The one below responds.

### Expected Behavior

A checkbox next to the selected language works.
Perhaps, the size of the area of the language name next to the checkbox gets bigger and I think that it is covered on the above word.

#### steps to replicate

1. Access to https://dev.to/settings/languages
2. Click language
3. The one below responds

#### device/browser

MBP 2016-13inch: macOS Sierra Version 10.12.6
Google Chrome: Version 62.0.3202.94 (Official Build) (64-bit)

### Screenshots

![gif image](https://user-images.githubusercontent.com/10899437/33251124-63062316-d378-11e7-89b6-3a3a72354b93.gif)

**Comment by benhalpern** [comment]
Ah thanks for this. The padding covered up the label above. Fix will be live shortly.
