### ISSUE TITLE
Can't update profile in Settings

### ISSUE THREAD

**Issue by crazko** [thepracticaldev/dev.to#115]
### Current Behavior
Saving changes in Settings via **submit** button is not possible due to an error _Github username has already been taken_.

### Expected Behavior
Saving is possible without any constraints.

### Additional Info (steps to replicate, device/browser, helpful links)
I tried to be logged in and make changes both via Github and Twitter, but this error remains.

### Screenshots
![screenshot at 2017-11-28 19-10-36](https://user-images.githubusercontent.com/1255989/33336510-764c1766-d470-11e7-91a2-9361446cb8f2.png)

**Comment by Zhao-Andy** [comment]
Hey there, sorry about that. We patched this up a while ago but there are some occasional legacy accounts that weren't fixed. You should be good now. Let me know if you run into any other issues.

**Comment by crazko** [comment]
Thanks a lot!
