### ISSUE TITLE
Translate comments

### ISSUE THREAD

**Issue by Link2Twenty** [thepracticaldev/dev.to#1150]
Users should be able to read and write comments, and posts(?), in their own language. This helps dev.to reach more people.

Similar to twitter comments could be checked, if they don't match the display language an option to translate should be offered.

I think we've reached a point now where translation software is so good there is no need to expect users to learn English.

**Twitter:**
![image](https://user-images.githubusercontent.com/3534427/48718375-29864800-ec13-11e8-98f1-9a2f081a5799.png)

**Dev.To:** [link to post](https://dev.to/wi45/comment/71io)
![image](https://user-images.githubusercontent.com/3534427/48718364-24c19400-ec13-11e8-98b1-f200a92d91dc.png)

**Comment by jessleenyc** [comment]
Pinging @benhalpern because he's given this a lot of thought.
