### ISSUE TITLE
500 error on https://dev.to/notifications

### ISSUE THREAD

**Issue by AgrimPrasad** [thepracticaldev/dev.to#1157]
Suddenly got notified that I have 27 notifications, on clicking the bell animation, was led to https://dev.to/notifications but it shows a 500 error.

Android phone, Opera browser, logged in user

**Comment by tristan957** [comment]
Can confirm the exact same issue although it is gone now

**Comment by jessleenyc** [comment]
@tristan957 @AgrimPrasad Thanks for flagging. We pushed a new way of handling notifications yesterday and it was a little buggy. Has since been fixed so I'm closing this issue!
