### ISSUE TITLE
Feature request: Enqueue post

### ISSUE THREAD

**Issue by mimimalizam** [thepracticaldev/dev.to#116]
# _TASK or Feature_

From time to time, when I want to save a dev.to post and read it later - I save it with [pocket](https://getpocket.com/a/). It would be awesome if there is a way to do this on dev.to.

**Comment by Zhao-Andy** [comment]
Hey Milana, thanks for the feedback. The idea has floated around before. We're going to backlog this for now, but will revisit soon.

**Comment by jessleenyc** [comment]
Hey! This is now live.
