### ISSUE TITLE
Runkit tag in comments - Broken

### ISSUE THREAD

**Issue by AntonyGarand** [thepracticaldev/dev.to#1163]
**Describe the bug**
Runkit tags are not working in comments.
Instead of a normal tag, they simply put the raw content into a code tag, which has bad formatting and no execution.

**To Reproduce**
Create a comment with a runkit tag
Preview or publish it

**Actual behavior**
We get content in a code tag, without the formatting or execution runkit should provide us.

**Expected behavior**
We get a correct runkit tag

**Screenshots**
![image](https://user-images.githubusercontent.com/9059487/48785588-03b08000-ecb3-11e8-9213-aff08eb6c4f3.png)
![image](https://user-images.githubusercontent.com/9059487/48785609-0ca15180-ecb3-11e8-8660-32234500be24.png)
![image](https://user-images.githubusercontent.com/9059487/48785755-5b4eeb80-ecb3-11e8-92ee-94911b5d2638.png)

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by jessleenyc** [comment]
Thanks for flagging! This issue is approved for anyone who wants to work on it.

**Comment by AntonyGarand** [comment]
Not stale!
