### ISSUE TITLE
Feature request: Add some form of post analytics

### ISSUE THREAD

**Issue by Booligoosh** [thepracticaldev/dev.to#117]
# _TASK or Feature_
### Request
While there are reactions at the bottom of posts, there is no way to see how many people have read each of your articles. It would be cool if you could add that feature!
### Definition of Done
So I can see the number of views/readers for each post would be enough. Further down the track it would be cool to add graphs etc. but the number of readers is the main priority.
### Notes
Thanks, I've only been on dev.to for a couple of hours and already I'm loving it!

**Comment by Zhao-Andy** [comment]
Hey Booligoosh, thanks for the feedback. We currently have this available in closed beta, but it's still pretty buggy. Our current focus is open sourcing the app, but we'll iron out analytics soon.

**Comment by jessleenyc** [comment]
Hey! We're closing this issue because a duplicate was created and there's a bit more discussion going on there: https://github.com/thepracticaldev/dev.to/issues/227
