### ISSUE TITLE
Feature Request - Duplicate Posts

### ISSUE THREAD

**Issue by RDumais** [thepracticaldev/dev.to#1170]
**Is your feature request related to a problem? Please describe.**
I have seen authors accidentally double post a topic on multiple occasions. I am not sure where the problem is stemming from.

**Describe the solution you'd like**
I believe the Dev.to team should implement some kind of buffer where authors are unable to post a second topic until x amount of minutes have passed since the first post (1-2 minutes).

**Describe alternatives you've considered**
I cannot really think of any alternatives. Maybe make it so topics cannot have identical names within x amount of minutes of posting?

**Additional context**
Here is an example I've seen with two different links:

https://dev.to/jeremyksutter/ultimate-guide-to-selling-your-product-online-25me
https://dev.to/jeremyksutter/ultimate-guide-to-selling-your-product-online-212d

![](https://i.imgur.com/o79YoqH.png)

**Comment by jessleenyc** [comment]
Thanks for the feature request! We see this more with spam accounts. Some of the features we're putting in place will definitely lower visibility on such accounts but this is a good thought.
