### ISSUE TITLE
Feature request - cached content for offline use

### ISSUE THREAD

**Issue by gurpritsingh** [thepracticaldev/dev.to#1171]
**Is your feature request related to a problem? Please describe.**
I love using dev.to whenever I am travelling but because I am in India and internet connection is not reliable I end up seeing the offline page with the drawing canvas which is cool but not helpful.

**Describe the solution you'd like**
Having a caching strategy so that user can see some of the articles when offline would be great.

**Additional context**
Dev.to is all about the community and knowledge sharing and I think if we can have access to some subset of that knowledge even when offline would be amazing

**Comment by Zhao-Andy** [comment]
Thanks for the issue @gurpritsingh. We do have some caching going on with service workers, but it's a bit half baked and could use some fresh eyes.

This might be out of scope of this particular issue, but I think we could add some functionality that lets you choose which articles you want to save in your cache. Or we could automatically save reading list items into the browser cache.
