### ISSUE TITLE
add a history of read articles

### ISSUE THREAD

**Issue by yafkari** [thepracticaldev/dev.to#1173]
### **Is your feature request related to a problem? Please describe.**
I'm always frustrated when I read an article the morning and I can't find it again the evening..

### **Describe the solution you'd like**
I thought it would be cool, if there is a history of read articles

### **Additional context**
That's all ^^

**Comment by moriczgergo** [comment]
Hey, you can use the bookmark reaction to save the article for reading later, but if get’s approved, I’d do a PR for this

**Comment by rhymes** [comment]
@yafkari in the meantime you can also use your browser's history, or... actual bookmarks

**Comment by benhalpern** [comment]
I agree with this feature. As others have pointed out, you can bookmark. But I think view history also makes sense.
