### ISSUE TITLE
UI header links - broken HTML

### ISSUE THREAD

**Issue by bgadrian** [thepracticaldev/dev.to#1176]
My article looks like this: 

![image](https://user-images.githubusercontent.com/830001/48904476-28e5ef80-ee67-11e8-8ac9-aaae82d25de3.png)

https://dev.to/bgadrian/from-monolith-to-cloud-auto-increment-to-uuid-10ki

It was fine until yesterday (21 nov), I guess it was an update today, maybe fighting spam? 

Tested on Chrome 70 and Firefox 63. 

I will return with more details, maybe I can figure it why, I guess that Having an URL in the `##` titles.

**Comment by bgadrian** [comment]
Ok I can reproduce the issue with a smaller snippet

1. Write new post

```markdown

## [TITLE](http://google.com)

Another [url](http://google.com) and 

> new [one](http://google.com)

Another [url](http://google.com) and 
```

2. Press Preview

**Comment by benhalpern** [comment]
Okay I'm on it.

**Comment by bgadrian** [comment]
The problem is gone, at least on my article.
