### ISSUE TITLE
Create liquid tag for medium.com articles 

### ISSUE THREAD

**Issue by SamWSoftware** [thepracticaldev/dev.to#118]
# _feature - liquid tag for medium.com articles_

Have a liquid tag that woks something like 
``` {% medium https://medium.com/article %} ``` 
To produce something similar to the link tag for dev.to articles

**Comment by Zhao-Andy** [comment]
Hey Sam, thanks for the feedback. We'll put it in our backlog for now.

**Comment by jessleenyc** [comment]
hey @SamWSoftware! we're open source now, so if this is an issue you feel like working on please go for it here's some more info on liquid tags: https://docs.dev.to/liquid-tags/

**Comment by jacobherrington** [comment]
Sounds like a good idea, I'm working on this!

**Comment by msarit** [comment]
@jacobherrington Hi there! whats's the status of this issue? 😄

**Comment by jacobherrington** [comment]
@msarit still going, but got a bit distracted. If you're looking to knock it out, go ahead!

**Comment by msarit** [comment]
@jacobherrington I'll try my hand at it and update you before creating a PR, so we don't duplicate efforts 👍

**Comment by theoutlander** [comment]
Issues that have been claimed should be assigned so it's easier to discover issues that need help.

**Comment by edisonywh** [comment]
Hey guys, since the last reply was about two months ago I decided to pick it up, hope its okay. Check it out here #1161 and happy to take any feedback!

**Comment by maestromac** [comment]
not stale

**Comment by Zhao-Andy** [comment]
Resolved by #1161

**Comment by jessleenyc** [comment]
Keeping this open bc we still need to make some design tweaks before making it available!

**Comment by jessleenyc** [comment]
Forgot to close this -- its available!
