### ISSUE TITLE
Empty notification not seen

### ISSUE THREAD

**Issue by bgadrian** [thepracticaldev/dev.to#1185]
**Describe the bug**
A blank notification was visible on my notifications page.

**To Reproduce**
I saw a notification alert, clicked on it.
The notification page opened but no new notifications were visible, except a border at top.
The blank div was still visible at the next visit.

**Expected behavior**
To see only notifications with title/body.

**Screenshots**
![screenshot from 2018-11-24 15-19-38](https://user-images.githubusercontent.com/830001/48968781-2fa66b00-effd-11e8-80db-0a2d7cd93c47.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 18
- Browser Chrome
- Version 70

**Comment by Zhao-Andy** [comment]
Hmm @benhalpern is this fixed too?

**Comment by jessleenyc** [comment]
pushed a fix
