### ISSUE TITLE
Emojis not appearing on sign up page

### ISSUE THREAD

**Issue by lianafelt** [thepracticaldev/dev.to#119]
# _BUG_
### Current Behavior
Emoji not showing up
### Expected Behavior
Emoji should show up
### Additional Info (steps to replicate, device/browser, helpful links)
![screen shot 2017-12-11 at 11 20 17 am](https://user-images.githubusercontent.com/34452847/33841458-c881f6d2-de65-11e7-8d39-776c21c8d618.png)

**Comment by lobo-tuerto** [comment]
There is also more places where this is happening, for example the About section on the Dashboard.

**Comment by Zhao-Andy** [comment]
Fixed, thanks for the report. 👍
