### ISSUE TITLE
Inefficient comments loading

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#1196]
**Is your feature request related to a problem? Please describe.**
For each comment `children` method is called, which makes an SQL query. It leads to a lot of SQL queries that could be avoided.

**Describe the solution you'd like**
Load all child comments of each of the root comment in one query.

**Comment by Link2Twenty** [comment]
Is there more to do for this?

**Comment by Zhao-Andy** [comment]
Nope, this is resolved via #1197
