### ISSUE TITLE
FEAT: Open images in lightbox or new tab, not current article tab.

### ISSUE THREAD

**Issue by davidjeddy** [thepracticaldev/dev.to#1198]
Clicking an image in an article should open the media in a lightbox.

**Describe the solution you'd like**
Open image media in a lightbox.

**Describe alternatives you've considered**
Open image in new browser tab and focus to that tab.

**Additional context**

Pre click on image:
![image_pre_lightbox](https://user-images.githubusercontent.com/6232455/49025415-9b0d4b80-f169-11e8-97fe-9161e6e15d6f.png)

Post click on image:
![image_lightbox](https://user-images.githubusercontent.com/6232455/49025317-5a153700-f169-11e8-80bd-7c851bd39ffb.png)

**Comment by jessleenyc** [comment]
Ah yes, this is a pretty popular request. We've approved it in https://github.com/thepracticaldev/dev.to/issues/413 so closing this one. I think whoever takes #413 can approach it a few different ways, including lightbox.
