### ISSUE TITLE
Replies not visible?

### ISSUE THREAD

**Issue by onejgordon** [thepracticaldev/dev.to#12]
Just submitted a reply to a comment on a post. From the post, I can now see the conversation count updated (view full discussion (2)), but the reply itself seems not to be visible. Perhaps it's awaiting moderation, but either way this makes for a confusing reply UX.

Post this was noted on: https://dev.to/onejgordon/action-potential---a-mini-app-for-real-time-distributed-decisions-and-a-2-day-learning-experiment-in-firebase/comments

**Comment by benhalpern** [comment]
I suspect this was a caching issue. There's a known race condition we sometimes hit when trying to clear the cache. Thanks for the heads up, I _believe_ that's the issue.
