### ISSUE TITLE
Can't edit twitter and github link

### ISSUE THREAD

**Issue by devamaz** [thepracticaldev/dev.to#120]
# _TASK or Feature_
### Request or User Story
For some reason I change my github and twitter username. I login to my dev.to profile to edit my twitter and github link and find out there is no way to do that. 

### Definition of Done
User should be able to update their twitter and github in case they change their username.

### Notes
Thanks, dev.to have been really helpful.

**Comment by Zhao-Andy** [comment]
Hey Ahmad, thanks for the feedback. We'll fix this soon.

**Comment by Zhao-Andy** [comment]
Hey Ahmad, your account should work with both Twitter and GitHub login. Sorry about that bug.

**Comment by DJ-Tai** [comment]
I too am having this issue. There is no way to edit my Twitter handle from my Dev.to account. Clicking the "Edit Profile" button has no affect.

**Comment by Zhao-Andy** [comment]
Hey @DJ-Tai, could you take a screenshot of the console errors when you click the "Edit Profile" button?

As for changing your Twitter handle, we'll have to do it manually on our end for now. Sorry about that. What's the new Twitter handle?

**Comment by Zhao-Andy** [comment]
Closing this for now; you can still reply whenever, David :)

**Comment by DJ-Tai** [comment]
@Zhao-Andy 
**Twitter handle:** _djtai
**Error:** I actually don't need to click anything - this happens upon the page loading. I hope I did this correctly, I've never attached a screenshot before. Thanks for all the help!
![editprofileerror](https://user-images.githubusercontent.com/24538473/34795738-1839ceca-f608-11e7-9ac7-45e8c8ef5e61.png)
