### ISSUE TITLE
Replace 'More from @...'

### ISSUE THREAD

**Issue by davidjeddy** [thepracticaldev/dev.to#1202]
**Is your feature request related to a problem? Please describe.**
No problem , verbiage update when viewing an article when user is the author.

**Describe the solution you'd like**
Either remove the 'More from @...' when user is the author or rephrase to something in the vein of 'Other posts by you.'

**Describe alternatives you've considered**
Not a critical issue, more a readability / consistency update.

**Additional context**
<img width="651" alt="dev to_verbiage_update" src="https://user-images.githubusercontent.com/6232455/49037882-5f827980-f189-11e8-9fa3-35cbf85ebb15.PNG">

Thank you; keep up the amazing effort!

**Comment by Link2Twenty** [comment]
It looks like this is the section that puts that bit in.

https://github.com/thepracticaldev/dev.to/blob/8b1755a2b3813224dfaeca68f209a0e21d1d76dc/app/views/articles/_sticky_nav.html.erb#L81-L104

I think you could either remove that section like so (L81)
```erb
<% if user_signed_in? && @user_stickies && @user_stickies.any? && current_user.username != @actor.username %>
```

Or change the text like this (L86 - L90)
```erb
<% if current_user.username == @actor.username %>
  More from <a href="<%= @actor.path %>">you</a>
<% elsif @actor.username.size < 18 %>
  More from <a href="<%= @actor.path %>">@<%= @actor.username %></a>
<% else %>
  More from<br/><a href="<%= @actor.path %>">@<%= @actor.username %></a>
<% end %>
```

**Comment by jessleenyc** [comment]
@Link2Twenty thanks for the additional info there! I think it makes sense to do this. @benhalpern any thoughts on copy there?

**Comment by ashishg-qburst** [comment]
Looks like a good first issue for me. @jessleenyc do you want that section removed for current_user or the header reworded?

'Other posts by you' sounds better to me than 'More posts from you'.

**Comment by jessleenyc** [comment]
@ashishg-qburst  let's remove the section for current user altogether!

**Comment by benhalpern** [comment]
Problem is that we don’t have access to `current_user` in this view due to edge caching. This would have to be loaded async.

So this is less trivial than it would appear.

But I think it’s reasonable that we could want to load this section async anyway.

I haven’t closely looked at the rest of the discussion yet but wanted to dip in to give this heads up.

**Comment by ashishg-qburst** [comment]
@jessleenyc PR raised - #1304 . Removed that section for current user.
