### ISSUE TITLE
Save button's contrast

### ISSUE THREAD

**Issue by Link2Twenty** [thepracticaldev/dev.to#1204]
**Describe the bug**
Currently, the article `save` buttons are calculated at #4a68ff and their text is #ffffff this leads to a contrast of 4.45 generally anything below contrast 7 is frowned upon.

This is calculated in the scss file here
https://github.com/thepracticaldev/dev.to/blob/master/app/assets/stylesheets/articles.scss
`background: darken($purple, 26%);`

**Side note:**
if you're going to use darken and lighten it's generally best to avoid absolutes (ff/00) as they're not really affected.

**Expected behavior**
Ideally if we could boost the contrast to above 7 that would be good for accessability. I've done some tests and changing the darken to 38% (#0d35ff) would have a contrast of 7.07 and changing the hover to 50% (#0022cf) would allow the affect to remain about the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/3534427/49090377-7bebe800-f255-11e8-892d-356326985a7a.png)
Left is with the change, right is without
Both top articles have the hover attribute.

**Additional context**
I would have just gone ahead and submitted a pull request but I thought this would be a better way to do it. Also, if the change is accepted, it would make a good first pull request.

**Comment by jessleenyc** [comment]
Cool, this is approved for anyone who wants to work on it.

**Comment by rozenraymond** [comment]
Hi, I'm happy to take on this issue.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/1261
