### ISSUE TITLE
Accessibility: Don't remove the focus outline

### ISSUE THREAD

**Issue by RyKilleen** [thepracticaldev/dev.to#121]
# _TASK_
### Request or User Story
The focus outline is critical for keyboard / accessibility users.

Some quick fixes are here: https://a11yproject.com/posts/never-remove-css-outlines/

The gist:

Leave the outline and style it 
-OR-
Remove the outline but style all types of elements based on focus 
-OR-
Remove it for mouse users only (really not recommended)

### Definition of Done

Keyboard and visual accessibility users will be able to tab around the site and know where the focus is.

### Notes

`outline: 0` is currently set on `body :focus`

**Comment by alexcarpenter** [comment]
Checkout https://github.com/WICG/focus-ring to help with removing the outline for mouse users while keeping it visible for keyboard users.

**Comment by RyKilleen** [comment]
@alexcarpenter that looks great, that wasn't on my radar. Seems like a best case scenario.

**Comment by benhalpern** [comment]
Thanks for the input. The current implementation was basically a hack on some functionality and I can't quite remember what the consequences of changing this are, but we'll look to deal with this as soon as possible.

**Comment by RyKilleen** [comment]
Hey @benhalpern, congrats on going for OSS! 

I'd love to revisit this issue.

Best case, I'd suggest enabling a sane default outline for everything that fits the aesthetic, and for any problematic elements, designing a different focus state for them! I'm happy to help tackle it.

**Comment by benhalpern** [comment]
That approach makes perfect sense @RyKilleen. Give me a day or two to examine the current state of things and make some basic changes and then follow up with some more guidance.

Thanks for following up on this, it means so much!

**Comment by benhalpern** [comment]
Hey sorry it's been three days since I said I'd examine this. I've been much more busy than anticipated. Will keep you posted.

**Comment by lkopacz** [comment]
@benhalpern I can also help with this if you'd like :) Not sure if it's approved to work on for hacktoberfest

**Comment by benhalpern** [comment]
Hey everybody, https://github.com/thepracticaldev/dev.to/pull/1132 resolves this (most of the way)

Closing this issue. Sorry it took so long!

**Comment by RyKilleen** [comment]
@benhalpern This is great, thanks for taking the time and caring!
