### ISSUE TITLE
Improve the comment thread

### ISSUE THREAD

**Issue by K20shores** [thepracticaldev/dev.to#1211]
I cannot tell where the root of a comment begins after reading past the first few comments. Could an indicator be added such that it is easy to tell when I am reading a new, root comment? If not, could a collapse function be built in such that all replies to a root comment are hidden?

**Comment by K20shores** [comment]
I like that. I'm only familiar with backend and systems level programming. If no one else wants to do this, I wouldn't mind trying to figure out how to write a collapse function to learn a little more about web stuff.

**Comment by jessleenyc** [comment]
Thanks for the issue. I'll circle back here after I've discussed w/ the team.

**Comment by jessleenyc** [comment]
Hey! Closing this issue since we added comment collapse :)
