### ISSUE TITLE
A11y: alt attributes for landing page picture

### ISSUE THREAD

**Issue by Link2Twenty** [thepracticaldev/dev.to#1212]
**Describe the bug**
On the landing page, there are 3 images that do not have `alt` tags associated with them this leads to lower accessibility score.

**nav-profile-image:**
https://github.com/thepracticaldev/dev.to/blob/65110550d8c2231f73ff99ae305a46b7b0bcb4f9/app/views/layouts/_top_bar.html.erb#L25
`alt="profile image"`

**sidebar-profile-pic:**
https://github.com/thepracticaldev/dev.to/blob/f744f43493ef4f90f5421665d0d393db03da052d/app/assets/javascripts/initializers/initializeBaseUserData.js#L36
`alt="profile image"`
**Side note:** I'm not sure editing the inner HTML directly is the best approach here.

**MY READING LIST:**
https://github.com/thepracticaldev/dev.to/blob/65110550d8c2231f73ff99ae305a46b7b0bcb4f9/app/views/articles/_sidebar_nav.html.erb#L20
`alt="Bookmarks"`

**Expected behaviour**
Alt tags are important for screen readers and for broken image links

**Additional context**
These will stop chrome audits flagging the issue but at some point, we need to do a scan through the entire site to find other images with the problem.

I think this will be a good first issue too, little changes like this are so important for usability.

**Comment by Zhao-Andy** [comment]
Hey @Link2Twenty, thanks for the issue. This all makes sense. I think we might want empty alt tags like `alt=""` for `nav-profile-image` and `sidebar-profile-pic` for screen readers to skip those.
