### ISSUE TITLE
Navbar height on avatar click

### ISSUE THREAD

**Issue by sabatesduran** [thepracticaldev/dev.to#1213]
**Describe the bug**
Don't know if it's on purpose but when I click on my avatar the navbar gets smaller on the sides (see screenshot) because the `top` property is not the same as the navbar height.

**To Reproduce**

1. Click on your avatar in the navbar.

**Expected behavior**
The `top` property` of the background should be the same as the the navbar height.

**Screenshots**
Before:
![screenshot from 2018-11-28 13-18-17](https://user-images.githubusercontent.com/5699145/49151607-c1b9b680-f310-11e8-86b9-adbcb35063a9.png)

After modifying class:
![screenshot from 2018-11-28 13-18-40](https://user-images.githubusercontent.com/5699145/49151621-cbdbb500-f310-11e8-9d3d-8ad09ef0ffd3.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04
- Chrome v.70.0.3538.110 (Official Build) (64-bit)

**How to fix it?**
The class `.menubg` needs to be changed to `top: 49px` in `app/assets/stylesheets/top-bar.scss`.
```css
.menubg {
    ...
    top: 49px;
   ...
}
```

**Comment by Link2Twenty** [comment]
Issues #1160 is the same and is approved if you want to make a pull request 🙂

**Comment by Link2Twenty** [comment]
This issue can be closed now.
