### ISSUE TITLE
Set Global box-sizing style

### ISSUE THREAD

**Issue by RyKilleen** [thepracticaldev/dev.to#122]
# _TASK_
### Recommendation
This will make dev life immeasurably better. Tired of padding messing up your `width: 100%`? Tired of having to absolutely position things because none of your calculations are working the way they should? 

Don't believe me but will trust Paul Irish?
> Ugh. If I say the width is 200px, gosh darn it, it’s gonna be a 200px wide box even if I have 20px of padding.

https://www.paulirish.com/2012/box-sizing-border-box-ftw/

```
* {
    box-sizing: border-box;
}
```

The effect of this can be seen on the `.sidebar-nav-link` elements, where they spill over a bit. Doesn't appear to mess anything noticeable up either.

**Comment by benhalpern** [comment]
Wow I cannot believe I didn't know about this. Thank you.

**Comment by alexcarpenter** [comment]
https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/

```
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}
```
