### ISSUE TITLE
Feature Request: featured profile posts

### ISSUE THREAD

**Issue by aspittel** [thepracticaldev/dev.to#1225]
**Is your feature request related to a problem? Please describe.**
I would love to be able to feature different posts on my profile page. I have a lot of discussion-based or re-occurring posts which are great from the community, but I would love for people to see my best writing work when they go to my profile instead of those posts. I think this is especially helpful for people trying to share their articles outside of the dev.to ecosystem (i.e. tweeting check out my blog or something along those lines).  Also, it would be helpful for job seekers who want to put their best content first. 

**Describe the solution you'd like**
I think there are a number of solutions to this:

* Something like "pinned repositories" on GitHub profiles (maybe these could use the `cover_image` too) -- I think this would be the best solution
* A "sort by reactions" view on profiles that is link-able
* One "pinned post" similar to a pinned tweet
* The ability for the user to decide how posts are sorted on their profile page
* A boolean on posts for whether they should appear on the person's profile or not

**Comment by pkfrank** [comment]
Hey @aspittel, thanks for the great feature suggestion.  This makes a lot of sense.  I'm sure @benhalpern and others on the team will have some additional thoughts.

**Comment by nestedsoftware** [comment]
A related thought I've had is to support a "portfolio page" feature on dev.to. It could replace the current profile or be a separate feature (e.g. _dev.to/user/folio_). The idea would be that the user would have some control to customize what's on this page, including maybe which blog posts and comments, if any, are displayed.

**Comment by ryanwhocodes** [comment]
This is a great idea - some people may use Dev.to mainly for reading and commenting on stories, but if you produce content then it would be preferable to be able to feature your best work and hide / deprioritise comments. It is unfortunate that when someone views your profile the first thing they see is your most recent post, when it may not be the work you most want to share with others.

**Comment by ryanwhocodes** [comment]
@aspittel were any features planned for dev profiles following the responses to your article https://dev.to/aspittel/what-would-you-like-to-see-on-your-dev-profile-31md?

**Comment by omenking** [comment]
## My Own Personal Complaint

The comment box pushes articles down, and I would like to create certain articles as close to the top of the fold as possible but this is just my own personal complaint.
<img width="1135" alt="Screen Shot 2019-04-09 at 3 58 35 PM" src="https://user-images.githubusercontent.com/7776/55831099-59f65200-5ae0-11e9-84a4-167c867afdf3.png">

## Concreate Suggestion for Implementation 

I would suggest for the scope of this ticket to be the ability to pin your articles to above the comment box. We can add an option in the markdown just as where you add  the cover_image.

eg. `pin: true`

By default the pinned articles would be sorted based on `published_at` date.

If @benhalpern or another core member approves I can have it PR'd lickity split.

**Comment by jessleenyc** [comment]
Pinned posts have been implemented!
