### ISSUE TITLE
Can install this on Shared Host

### ISSUE THREAD

**Issue by tanzaniatech** [thepracticaldev/dev.to#1226]
Hi am new here, i love this i will like to create community for dev in Africa can i install this on shared with ruby. If i can't install this on shared host what is a best open source code can i use to create community like dev.to (AM NEW HERE)

**Comment by pkfrank** [comment]
Hey @tanzaniatech — please [check out this page](https://docs.dev.to/dev-instance/) which has more information about eventually setting up your own DEV instance.
