### ISSUE TITLE
Graveyards tag should be graveyard

### ISSUE THREAD

**Issue by wolfhoundjesse** [thepracticaldev/dev.to#1235]
**Steps to Recreate**
1. Go to top 100 tags
2. Click on graveyards
3. Feel like there is a joke/Easter egg that you’ve stumbled on when the site comes up empty.

This would make a good first issue!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jessleenyc** [comment]
Hey @wolfhoundjesse! We actually have a simple way as site admins to make graveyards an alias for graveyard. Just made the update so closing this issue.
