### ISSUE TITLE
Notify author if someone replies to any comment on their post

### ISSUE THREAD

**Issue by rpalo** [thepracticaldev/dev.to#1238]
**Is your feature request related to a problem? Please describe.**

Currently, if someone comments on a comment on my post (replying to someone else), I don't get notified, so I end up either having to check in/refresh or miss a lot of conversations I didn't know were happening.

**Describe the solution you'd like**

It would be nice if I got notified anytime a comment happened on a thread on my articles.

**Describe alternatives you've considered**

Even if it was just a single bundled notification that said "You've had 10 new comments on your article today!" that would be nice.

**Additional context**

**Comment by maestromac** [comment]
Thank you for this feature request @rpalo . The current implementation was done to reduce unwanted notification but I can relate on why some author would like to be aware of all the comments. I think ultimately we might want to offer our authors the option to receive some or all.

@benhalpern / @jess do you have any thought on this?

**Comment by rpalo** [comment]
Another idea I just thought of, but haven't decided if it's better or worse: what if users had the ability to "subscribe" to a post, so they'd get notifications for all comments.  Then, authors could be automatically subscribed to their own posts?  Or not?  Or choose?

**Comment by Zhao-Andy** [comment]
@rpalo I'm in favor of having subscriptions to a post. Like you said, this would give authors the choice of whether or not they want to receive notifications for every comment or not. 

Related: #192

**Comment by Zhao-Andy** [comment]
Not stale

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/2233
