### ISSUE TITLE
New comment not showing up after I submit a comment and then refresh (shows up a few seconds later)

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/dev.to#1248]
I assume this is because we move a previously synchronous cache-busting action to be asynchronous, causing this issue.

I'd classify this as [a level 2 issue](https://docs.dev.to/vocabulary/). It's not going to ruin anyone's experience but could cause some confusion and should be addressed soon.

To be clear, _some_ cachebusting can/should be async. This should probably not be though.

**Comment by Zhao-Andy** [comment]
Resolved via #1275
