### ISSUE TITLE
Membership Link / Promo Code Incorrect

### ISSUE THREAD

**Issue by kyleboe** [thepracticaldev/dev.to#1249]
# Describe the bug
### Bug 1
Link to the membership sticker pack is incorrect.

--------------

### Bug 2
Promo code does not work when trying to purchase the membership sticker pack.

# To Reproduce

### Bug 1
1. Go to `/settings/membership`
2. Click on the link `THE MEMBERS-ONLY STICKER PACK`
4. Get sent to the [Women's Shirt Membership pack](https://shop.dev.to/collections/membership-rewards/products/rewards-only-heather-womens). 

![image](https://user-images.githubusercontent.com/4054771/49401682-bbef1700-f6fc-11e8-99d5-20123a4aee4d.png)

--------------

### Bug 2
1. Go to the correct store item (https://shop.dev.to/collections/membership-rewards/products/reward-only-sticker-pack)
2. Add to Cart
3. Go to checkout
4. Paste code from `/settings/membership` and click Apply
5. See error `Unable to find a valid discount matching the code entered`

![image](https://user-images.githubusercontent.com/4054771/49401920-52bbd380-f6fd-11e8-999d-7c21143839ff.png)

# Expected behavior
### Bug 1
Expect the link to direct to the sticker pack and not the Women's shirt pack.

--------------

### Bug 2
Expect the discount code to work 

# Desktop (please complete the following information):

- OS: macOS 10.14.1
- Browser: Chrome
- Version `70.0.3538.102`

**Comment by jessleenyc** [comment]
Thanks for flagging this @kyleboe. I suspect this is from some of the shop changes we made recently -- @lianafelt are there changes we need to make to those links & do you know if we need to generate new promo codes? cc: @Zhao-Andy

**Comment by Zhao-Andy** [comment]
Hey @kyleboe, sorry about that. We've generated your coupon and you should be able to check out properly now. Let us know if it's still an issue.

For anyone else experiencing this, feel free to email yo@dev.to and we'll sort it out for you.

**Comment by kyleboe** [comment]
Thanks! I was able to check out no problem 👍 I really appreciate the help. It looks like Bug 1 is still an issue though.
