### ISSUE TITLE
Accessibility: Profile dropdown needs to be a button

### ISSUE THREAD

**Issue by RyKilleen** [thepracticaldev/dev.to#125]
# _TASK_
### Request
The profile menu is completely inaccessible for keyboard / screen-reader users, as it's not an actionable element. 

Transforming it into a button will allow you to handle the focus in the same manner as a mouse hover. Things get trickier here as you have to allow for escaping the dropdown, typically with an escape key press.

### Definition of Done
A keyboard user is able to tap to the profile menu and navigate the dropdowns.

### Notes
We'll sometimes use hidden screen reader announcements to provide context for the programmatic change in focus to the dropdown, but that's getting more advanced.

**Comment by benhalpern** [comment]
Finally got to this, deploying now. Thanks so much for the help. Other stuff will follow.

**Comment by RyKilleen** [comment]
Thanks for being awesome and taking accessibility issues seriously!
