### ISSUE TITLE
Markup: Headers should contain headings

### ISSUE THREAD

**Issue by RyKilleen** [thepracticaldev/dev.to#127]
# _TASK_
### Request or User Story
As of now, any `<header>` without an `<h*>` in it isn't really semantic. The header indicates a section of content describing the rest, but still needs an `<h2>` or what have you.

**Comment by thomaslawton91** [comment]
I'd like to grab this but I'm a bit unsure as far as the scope here. I see quite a few instances of `<header>` in the repo but not sure whether they should be getting changed to `<h1>` etc. or if they need to have another `<h*>` included. Any further direction would be much appreciated!

**Comment by RyKilleen** [comment]
@thomaslawton91 This is something that is tied really closely to the nature of the content. 

Headings inside the `header` tags in the side bar can be whatever they need to be, if each widget is defined as a `section` instead of a `div`.

If styling of headers is tied tightly to the tag instead of a class, that introduces some complexity.

**Comment by thomaslawton91** [comment]
@ryklleen thank you for the further explanation! I'm going to look into this today or tomorrow.

**Comment by thomaslawton91** [comment]
@RyKilleen took a break and just getting back. As I read this the changes necessary are changing `header` tags to `section` tags and then adding the according `h*` tags within, is that correct? 

Just want to make sure I have a full grasp to move forward on.

**Comment by msarit** [comment]
@thomaslawton91 Hi there! Whats the status of this issue please?

**Comment by ashwinv11** [comment]
@msarit @thomaslawton91 I would love to work on this if development has been paused!

**Comment by msarit** [comment]
@ashwinv11 Go for it!! ⚡️

**Comment by lkopacz** [comment]
@ashwinv11 I'd recommend an h1 if this is the header of the page (like where the menu is), mostly for accessibility reasons.

**Comment by ashwinv11** [comment]
This is ready for review [here](https://github.com/thepracticaldev/dev.to/pull/1003)!
