### ISSUE TITLE
Vim-mode for Editing/Authoring Articles

### ISSUE THREAD

**Issue by petermbenjamin** [thepracticaldev/dev.to#1276]
I am a vim-addict and wanted to see if there are others like me in the Dev.to community who would be interested in vim-mode key bindings specifically for editing/authoring content?

I could possibly see this setting being toggleable via a setting (click on user avatar > settings).

Alternatively, I could possibly see it implemented as an integration with GitHub in such a way that I could author articles locally (which I already do as an alternative to authoring in the Dev.to editor) and push it to a GitHub repository which would result in the article showing up as a draft so I can review it and publish it on Dev.to (similar to how one would author interactive courses on [Katacoda](https://katacoda.com/docs/configure-git)).

**Comment by jessleenyc** [comment]
Hey @petermbenjamin! Thanks for the request. We're aiming to get an API out early next year. Once that happens, you are very welcomed to build something like this. I'm closing this issue but you can follow API progress here: https://github.com/thepracticaldev/dev.to/issues/911.

**Comment by gosukiwi** [comment]
I just was gonna suggest something like this, enabling some vim-bindings in the textarea in the new post page. Then I remembered [wasavi](https://chrome.google.com/webstore/detail/wasavi/dgogifpkoilgiofhhhodbodcfgomelhe/related) which is basically that as a Chrome extension. It's pretty cool!
