### ISSUE TITLE
A11y: Links must have discernible text

### ISSUE THREAD

**Issue by Link2Twenty** [thepracticaldev/dev.to#1278]
**Describe the issue**
Currently for `article-organization-headline` you have 2 links, one that is the `article-organization-headline-inner` and one for `org-headline-filler`, that has no content, this means that a keyboard user has to tab past this link and a user using a screen reader will not know what the second anchor is.

Having one achor that have a styled span would solve your ploblem you wouldn't even need to change any CSS.

**Current:**
```html
<div class="article-organization-headline">
  <a href="#" class="article-organization-headline-inner">
    <img src="#">
     Team name
  </a>
  <a class="org-headline-filler" href="#">&nbsp;</a>
</div>
```

**Proposed:**
```html
<div class="article-organization-headline">
  <a class="org-headline-filler" href="#">
    <span class="article-organization-headline-inner">
      <img alt="logo" src="#">
      Team name
    </span>
  </a>
</div>
```

This is another small thing that brings the Lighthouse score down.
https://dequeuniversity.com/rules/axe/2.2/link-name

**Comment by Link2Twenty** [comment]
The files that would need changing are

https://github.com/thepracticaldev/dev.to/blob/652ec00f73dff0ee9ab7d0733d7e024ed94d2203/app/views/articles/_single_story.html.erb#L8

https://github.com/thepracticaldev/dev.to/blob/8b1755a2b3813224dfaeca68f209a0e21d1d76dc/app/assets/javascripts/utilities/buildArticleHTML.js.erb#L52

**Comment by Zhao-Andy** [comment]
Still a valid a11y issue.
