### ISSUE TITLE
Overly aggressive service worker offline page

### ISSUE THREAD

**Issue by philnash** [thepracticaldev/dev.to#128]
# Overly aggressive service worker offline page

I love that there is a service worker that is ready to deal with offline issues. However...

### Current Behavior

When I click a link that leads off site and then press the back button to return to dev.to I receive the offline page instead of the page I was previously on. I have to hard refresh (cmd+shift+r) to see the page again).

### Expected Behavior

When you click back you see the previous page that you were on, on the dev.to site.

### Additional Info (steps to replicate, device/browser, helpful links)

Browser: Firefox 57 on Mac (just tested and this doesn't happen in Chrome on the Mac)

### Screenshots

![devtosw](https://user-images.githubusercontent.com/31462/34277379-8c7aeeea-e6f9-11e7-8461-16b33851c83d.gif)

**Comment by Zhao-Andy** [comment]
Hmm, interesting that it doesn't happen on Chrome. I had this experience on Chrome in our previous versions of our service workers.

@maestromac probably up your alley since you're our Firefox guy 😇

**Comment by Zhao-Andy** [comment]
Hey @philnash, @benhalpern pushed up some service worker changes that might have solved this. Let us know if it's still happening on Firefox.

**Comment by philnash** [comment]
Hmm. It's still happening. No idea why though, it's super weird.

**Comment by Zhao-Andy** [comment]
Someone suggested it might a VPN/Proxy issue. Any thoughts? 

I can't reproduce it unfortunately, and don't know much about VPNs or proxies. If they are related, I _think_ I have an idea of why it might be happening.

**Comment by philnash** [comment]
I get the same behaviour when I'm using a VPN and when I don't. I'm not using a proxy.

I have had another look through the code though. It's gone through your minifier, so it probably doesn't look the same on your end, but there's a part of your fetch handler that makes the request and returns to offline if it can't get the result.

```javascript
fetch(e.request).then(c || caches.match("/offline.html"))
```

In this case, the function `c` is the function that stores the page in a cache and returns the request).

What is weird to me is that the argument to `then` is an `||` expression which doesn't seem right to me.

I'd love to look at the original serviceworker.js if you wouldn't mind? You can drop it on email at philnash@twilio.com if you want.

**Comment by Zhao-Andy** [comment]
Yeah! That's the line of code that I thought was fishy, I wasn't too sure about my hunch though.

Here's more of that same code:
```javascript
     return fetch(event.request)
        .then(fetchedFromNetwork || caches.match("/offline.html")
        .catch(function fallback() {
           return cached || caches.match("/offline.html");
         })
```
I think we're on the same page now; we shouldn't be returning the offline page _before_ returning the cached page. It should therefore be:
```javascript
```

**Comment by philnash** [comment]
I definitely think that the `||` needs to be removed. If you give that a try, I'm happy to test!

**Comment by Zhao-Andy** [comment]
Sure! Might have to wait till tomorrow though for my PR to be approved and deployed. 😅

**Comment by Zhao-Andy** [comment]
Hey @philnash, latest build includes this fix. Let me know how it goes!

**Comment by philnash** [comment]
Ugh, still seems to be happening. When the site is open sourced, this is the first thing I'm going to dig into properly!

**Comment by hoelzro** [comment]
FWIW this happens with me pretty often - I'm on Firefox 61.  Interesting point about the VPN, though - maybe that's what's impacting me?

**Comment by Zhao-Andy** [comment]
Hey @hoelzro and @philnash, not sure if you have the Privacy Badger extension, but that might have been the issue. If you do, moving the slider to allow `dev.to` should work. See https://github.com/thepracticaldev/dev.to/issues/456 for more details.

**Comment by hoelzro** [comment]
@Zhao-Andy Thanks, I'll try that out!

**Comment by philnash** [comment]
OMG. Privacy Badger!

That's so weird, but it's sorted. I'm going to raise this with Privacy Badger too.
