### ISSUE TITLE
Input field strange behaviour in Firefox

### ISSUE THREAD

**Issue by FeruzOripov** [thepracticaldev/dev.to#1297]
I use Firefox, when I type something in search bar It appears in white text but background is also white so that's why I can't see what I'm typing 
Screenshot
![screenshot_2018-12-11 the dev community 1](https://user-images.githubusercontent.com/34165740/49755743-ee8ba780-fcda-11e8-9ad7-4cf582981cc0.png)

**Comment by rhymes** [comment]
@FeruzOripov can you add which version of Firefox and operating system you're using? It might help who's going to debug the issue

My Firefox is fine for example (I'm on Firefox 64 on macOS 10.14.1):

![screenshot_2018-12-10 the dev community](https://user-images.githubusercontent.com/146201/49756814-2256d500-fcbb-11e8-92a9-eaa2a9bb0bbf.png)

**Comment by FeruzOripov** [comment]
Mozilla Firefox 63.0.3, Ubuntu 18.10

**Comment by FeruzOripov** [comment]
I found problem. It is due to dark theme that I use.

**Comment by jessleenyc** [comment]
@FeruzOripov OK to close this issue then?

**Comment by FeruzOripov** [comment]
Yep. Thanks)
