### ISSUE TITLE
User bio displaying beyond div on articles

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#1298]
**Describe the bug**
Text is not wrapping properly

**To Reproduce**

1. Go to https://dev.to/imalittletester/style-beautiful-web-pages-without-writing-any-css-using-w3css-45ee

**Expected behavior**
Text should not overflow out of div.

**Screenshots**

**Desktop (please complete the following information):**
![](https://cl.ly/98f7eee8ff18/download/Image%202018-12-10%20at%2010.06.29%20AM.png)

- OS: macOS Mojave 10.14.1
- Browser: Chrome 70

**Comment by anant90** [comment]
Adding an `overflow-wrap: break-word` to the `.primary-sticky-nav-author-summary` CSS rule will fix this issue. In addition, I would add `overflow: hidden` and `text-overflow: ellipsis` to make the CSS more robust. Happy to send in a PR :)

<img width="317" alt="screen shot 2018-12-10 at 1 43 56 pm" src="https://user-images.githubusercontent.com/509059/49763534-c7ed5280-fc81-11e8-9be7-6ab71a496ecf.png">

**Comment by Zhao-Andy** [comment]
@anant90 Go for it! Here's the related file:
https://github.com/thepracticaldev/dev.to/blob/master/app/assets/stylesheets/sticky-nav.scss#L32-L38
