### ISSUE TITLE
Sidebar placed under articles list on wide screens

### ISSUE THREAD

**Issue by aboks** [thepracticaldev/dev.to#13]
Due to the `side-bar` growing with the viewport width, from 2537px onwards it becomes too wide to fit next to the `articles-list`, and is moved to the bottom of the page.

**Comment by benhalpern** [comment]
Ah, funky! This shouldn't be too tough to fix.

**Comment by benhalpern** [comment]
Fixed 👌

Thanks so much for the issue!
