### ISSUE TITLE
Notifications page no longer list hearts

### ISSUE THREAD

**Issue by alainvanhout** [thepracticaldev/dev.to#1305]
Since about a week ago, my notification panel only contains comment responses, while no heart responses are listed anymore (which includes heart responses that are more recent than the most recent comment responses). 

Potentially relevant context: I haven't yet made any posts on dev.to, only comments. So all hearts relate to comments of mine on other people's posts.

**Comment by jessleenyc** [comment]
Hey @alainvanhout - we recently made some changes to the way notifications are delivered but I can't seem to reproduce what you're describing. Is this still an issue?

**Comment by jessleenyc** [comment]
Ah sorry, didn't mean to close this. If it's still an issue please feel free to reopen!

**Comment by alainvanhout** [comment]
I'm still experiencing the issue, but it seems to be more nuanced: yesterday morning I had two new heart notifications, yesterday evening the oldest of them was gone and again, and this morning the newer one was gone as well. I'd made a point of remembering the comments in question, and was able to verify that the hearts themselves are still on those comments.

Could it be that heart notifications are only retained for a day, while comment notifications are retained longer?

**Comment by alainvanhout** [comment]
Just as an update, the behaviour seems to be consistent that the heart notifications stay there for about 24 hours. Whether that's also the case for unread heart notifications, that I'm not able to see.

**Comment by jessleenyc** [comment]
I think a good first step here is whether or not this is working as expected -- it's possible that we have reaction notifications expire after a certain amount of time, in which case, we'd have to decide whether or not that's what we want to continue doing.

**Comment by Schwad** [comment]
Hello @alainvanhout and @jessleenyc ! :) 👋 

Thank you for filing this, it gave me a fantastic opportunity to do a deep dive on the `dev.to` codebase which was a very enjoyable experience. Although I have a "contributor" badge, I'm just a member of the OSS community who loves Ruby/Rails/dev.to and am trying to pitch in a little bit.

I am pleased to report that:

1. Everything is behaving as anticipated from a code perspective 😄 
2. However, if hiding these notifications is a confusing element of the UX, it is easily reversible!

Notifications are rendered on the `notifications_list` view, and in the majority of cases are scoped off the user's `User.notifications` associations.

In the `NotificationsController` we can see that notifications and scopes are narrowed further with:

`@notifications = @notifications.includes(:notifiable).without_past_aggregations.order(notified_at: :desc)`

And that the `without_past_aggregations` scope is declared in`notifications.rb` as:

```ruby
scope :without_past_aggregations, lambda {
    where.not("notified_at < ? AND action IN ('Reaction', 'Follow')", 24.hours.ago)
  }
```

Which does, you guessed it, a scrub of all notifications that are follows and reactions (hearts) over 24 hours ago.  

Removing `without_past_aggregations` **should** show you all your hearts. However, I'm assuming that the core team built this out for a reason.

One possible solution might be a 'see all notifications' tab or filter which would pull in all the notifications. I'm happy to help out from a code perspective on whatever's decided 😊

**Comment by rhymes** [comment]
Adding another possible useful info here: notifications are now paginated (they weren't when this issue was opened), so we might not need this "24 hours" filter anymore.

Thank you for the analysis @Schwad!

**Comment by Schwad** [comment]
Thanks for the thoughts @rhymes ! :)

I've had a crack at this in #5314 - it's a very small PR but I believe addresses the heart of this issue here.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/5314
