### ISSUE TITLE
Posts with a "#" in the title are truncated

### ISSUE THREAD

**Issue by Nektro** [thepracticaldev/dev.to#131]
# _BUG_
### Current Behavior
In the [following post](https://dev.to/nektro/what-is-the-purpose-of-4a5k) the title currently displayed is "What is the purpose of"

### Expected Behavior
The title was input as "What is the purpose of #help?"

**Comment by Zhao-Andy** [comment]
Hey @Nektro, this is fixed and will be deployed soon. Thanks again for the heads up.
