### ISSUE TITLE
Add a "Copy" button next to Markdown Image URL code once upload completes

### ISSUE THREAD

**Issue by anant90** [thepracticaldev/dev.to#1313]
**Is your feature request related to a problem? Please describe.**
Double-clicking Markdown Image Code to select it, and then pressing Ctrl+C to copy it slows the user down.

**Describe the solution you'd like**
A `Copy` button next to the Markdown Image Code field below:

<img width="761" alt="screen shot 2018-12-11 at 1 18 09 pm" src="https://user-images.githubusercontent.com/509059/49831145-05b4ae80-fd48-11e8-9219-9ae1a429ef11.png">

**Describe alternatives you've considered**
1. Inserting the Markdown Image Code directly where the cursor was in the Markdown document. This may become a little confusing for the user, so it's better to not do this and instead just make the whole thing easier by giving them a copy button.
2. Github comment section style drag and drop image — once uploaded, the Markdown Image URL just appears next to the section the image was dropped.

**Additional context**

**Comment by Zhao-Andy** [comment]
@anant90, great point. Thanks for bringing it up!

**Comment by jessleenyc** [comment]
Thanks for the feature request. This is approved if anyone wants to jump on it!

**Comment by maestromac** [comment]
Let's be sure that the implementation works with major browsers and OS/mobile.

**Comment by Some-Dood** [comment]
https://github.com/thepracticaldev/dev.to/blob/359cc71b6472705975097240fc12e2a6afc81cf5/app/javascript/article-form/elements/imageManagement.jsx#L51-L62

For anyone who wants to tackle this feature request, I think it's a good place to start in this JSX file. MDN also has a [guide](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard) on how to write to the clipboard. We should use the [modern asynchronous Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API) as much as possible, but we can always fallback to the old synchronous [`Document.execCommand` API](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) in case the user's browser does not support it.

**Comment by rhymes** [comment]
unstale

**Comment by bolariin** [comment]
I would like to resolve this
