### ISSUE TITLE
Notify user immediately when messages arrive in DMs (Dev connect)

### ISSUE THREAD

**Issue by ShivamSinghania** [thepracticaldev/dev.to#1315]
I'm not recieving email notifications for messages in Dev connect. Using Dev.to from Chrome on Android. Mobile notifications from web app would be even better.

**Comment by jessleenyc** [comment]
@ShivamSinghania connect messages only send an email notification after a certain amount of time. if you visit the site regularly, you'll likely never hit that duration. let me know if that makes sense!
