### ISSUE TITLE
Autosaving drafts

### ISSUE THREAD

**Issue by simoroshka** [thepracticaldev/dev.to#1318]
**Is your feature request related to a problem? Please describe.**
I was writing a post, and needed some help with markdown. I click help button, read what I need and then automatically go back by pressing the back button in the browser (or close the tab). The post is lost forever. 

It seems there was an issue for this but it is closed: https://github.com/thepracticaldev/dev.to/issues/42

**Describe the solution you'd like**
I would like the draft to be saved automatically. At the very least in the local storage.

**Describe alternatives you've considered**
Another solution is to ask whether the user wants to leave the page with unsaved changes.
It also might be a good idea to open the help info in a separate tab.

**Comment by rhymes** [comment]
This probably has something in common with https://github.com/thepracticaldev/dev.to/issues/442 - as in once you have client side storage for the markdown you can also implement auto save

**Comment by Link2Twenty** [comment]
Perhaps using `beforeunload` would help in this instance?

https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload
https://dev.to/chromiumdev/sure-you-want-to-leavebrowser-beforeunload-event-4eg5

Do a check to see if there is a saved version if not ask the user to confirm.

**Comment by jessleenyc** [comment]
Drafts now autosave on v2 of the editor! To toggle that editor, visit dev.to/settings/misc.
