### ISSUE TITLE
Reducing the size of Docker development containers

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [thepracticaldev/dev.to#1319]
**Is your feature request related to a problem? Please describe.**

The development purpose container is heavy because of Debian (`ruby:2.5.3` 869 MB). Compilation time is 3 minutes and 14 seconds, and the result image size is 1.32GB

**Describe the solution you'd like**

The container could run with an Alpine Linux based `ruby` image, and also, on `docker-compose.yml`  has `postgres:alpine` (right now it is 11) which isn't a good practice to keep using PostgreSQL latest version. I think, you should keep that version same with production servers for compatibility.

> I don't know the architecture that you have. 

This approach will reduce the time of downloading and building.

**Additional context**

Tested on Intel i5-6300U @ 2.40GHz, 8GB RAM, Linux 4.15.0, Ubuntu 18.04, Docker CE 18.09.0, Compose 1.22.0

**Comment by rhymes** [comment]
> The development purpose container is heavy because of Debian (ruby:2.5.3 869 MB). Compilation time is 3 minutes and 14 seconds, and the result image size is 1.32GB

Docker images are big :D How smaller does it get with the Alpine?

**Comment by BerkhanBerkdemir** [comment]
I got 560 MB with `ruby:2.5.3-alpine` :boom:

**Comment by maestromac** [comment]
Thanks for the issue @BerkhanBerkdemir , yup locking postgres on a stable version would be a much better practice.

**Comment by BerkhanBerkdemir** [comment]
I'll submit the PR for yesterday, but for 4 days after I can reply to your questions.

Also, can somebody give me information about production PostgreSQL version?

**Comment by maestromac** [comment]
@BerkhanBerkdemir lets use PostgreSQL 9.6

**Comment by nikoheikkila** [comment]
I'm currently looking into making the Docker images smaller with Alpine. I'll make a pull request if everything works out unless you @BerkhanBerkdemir have accomplished this already?

**Comment by BerkhanBerkdemir** [comment]
I worked on that, but I didn't run a stable container because the monolith application requires (or depend) something that Alpine doesn't have

**Comment by PicoCreator** [comment]
Just notice this - while not a docker-compose. It is an alpine docker build.

Details of the alpine docker container : https://dev.to/uilicious/adopt-your-own-devto----with-a-single-command-almost-1c04

Pull request : https://github.com/thepracticaldev/dev.to/pull/1844

**Comment by PicoCreator** [comment]
Also side note - while I didnt do a side to side comparison with previous deployment. The whole dockerfile build + fetching dev.to dependencies + to actually running it - still takes 5+ minutes. So im not too sure if the smaller image has a large impact on the build/compile/run time. 

On the plus side it does get faster on repeated execution (dockerfile is already built, dependencies already pulled), but im guessing the debian build would be similar.

The dev image is now : 311MB (no dev.to source code)
The demo image is now : 522MB (source code + all dependencies)

**Comment by PicoCreator** [comment]
With #1844 merged, shall we /close this?

**Comment by maestromac** [comment]
Yep @PicoCreator . If it becomes a problem we can re-open this or create a new one.
