### ISSUE TITLE
I am unable to pin the majority of my GitHub repos to my profile

### ISSUE THREAD

**Issue by Nektro** [thepracticaldev/dev.to#132]
# _BUG_
### Current Behavior
On the majority of my GitHub repositories, I will click Select, the page will refresh, and nothing else will happen.

### Expected Behavior
I noticed it because I was not able to pin [this repo](https://github.com/Nektro/apps.nektro.net) or [this repo](https://github.com/Nektro/mantle.js) but after checking some more, many of my other repos had the same results

### Additional Info (steps to replicate, device/browser, helpful links)
On the https://dev.to/settings/integrations page

**Comment by flexdinesh** [comment]
I am facing the same issue. I am not able to pin any of my GitHub repos to my profile.

**Comment by maestromac** [comment]
Thanks for reporting this! We'll investigate.

**Comment by maestromac** [comment]
Hey @Nektro & @flexdinesh , I believe this is fixed. Can you guys give it a try and let me know?

**Comment by flexdinesh** [comment]
It's fixed. I am able to pin my GitHub repos again. Thanks much! You guys are awesome!

**Comment by Nektro** [comment]
Yup, all good for me. Thanks!
