### ISSUE TITLE
CodeSandbox Embed: Add Query String Options

### ISSUE THREAD

**Issue by davefollett** [thepracticaldev/dev.to#1321]
**Is your feature request related to a problem? Please describe.**
CodeSandbox.io's sharing dialog has many options that when configured are added as URL query strings.  Dev.to does not provide a way to use those.  In particular, I'd like to be able to use the "Project Initial Path" and "Default module to show" options as shown in this snippet:

![codesandboxio-share](https://user-images.githubusercontent.com/6683520/49914687-430c5f80-fe60-11e8-8e7a-7c5261c98537.jpg)

This would allow me to use one sandbox but be able to embed it such that I can control what part of the sandbox displays.  Here is the the matching iframe for the screen snippet:

```
<iframe src="https://codesandbox.io/embed/24qvv1wvxr?initialpath=06%20-%20Type%20Ahead%2Findex-VUE.html&module=%2F06%20-%20Type%20Ahead%2Findex-VUE.html" style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;" sandbox="allow-modals allow-forms allow-popups allow-scripts allow-same-origin"></iframe>
```

**Describe the solution you'd like**
It would be awesome if dev.to could expose control of the parameters mentioned above
* initialpath
* module

 or better yet, provide a way to control them all as a singe string provided after the id value:

`{% codesandbox ppxnl191zx QUERY-STRING %}`

**Comment by jessleenyc** [comment]
This should be similar to how we implemented liquid tags for glitch and codepen. This is approved for anyone who'd like to give it a go.
