### ISSUE TITLE
JSFiddle liquid tag

### ISSUE THREAD

**Issue by Link2Twenty** [thepracticaldev/dev.to#1323]
I'd love to be able to embed JSFiddle snippets into my code, in a similar way as codepen.

They offer an embedded solution which is something like this

https://jsfiddle.net/link2twenty/v2kx9jcd/embedded/js,html,css,result/"
https://{URL}/{User}/{Fiddle ID}/embedded/{@build_options}/

![image](https://user-images.githubusercontent.com/3534427/49947525-60d1d700-fee9-11e8-81ba-202bf3a05a8d.png)

**Comment by Zhao-Andy** [comment]
Thanks @Link2Twenty, this makes sense. If anyone wants to work on this, you can check out the CodePen and CodeSandbox Liquid tags as guiding examples:

https://github.com/thepracticaldev/dev.to/blob/master/app/liquid_tags/codepen_tag.rb
https://github.com/thepracticaldev/dev.to/blob/master/app/liquid_tags/codesandbox_tag.rb

**Comment by Link2Twenty** [comment]
We did it!
