### ISSUE TITLE
Quoted tweet not showing up in Liquid Tag

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/dev.to#1328]
In our rendered quote-tweet liquid tag, the body of the quoted tweet is not showing up.

This has been a longtime issue, to the point where members are sort of working around it:

![](https://cl.ly/af3425fee8ba/Image%202018-12-14%20at%201.54.28%20PM.png)

To reproduce: Post any quote-tweet as a liquid tag.

Every liquid tag creates a new tweet object, so in debugging it may need to be deleted each time to fix it. Just FYI.

**Comment by jessleenyc** [comment]
This is fixed!
