### ISSUE TITLE
Edit profile: Github username has already been taken

### ISSUE THREAD

**Issue by Einenlum** [thepracticaldev/dev.to#133]
### Current Behavior

Editing my profile (whatever I edit) and submitting it gives me a Github error: "Github username has already been taken".

### Expected Behavior

Being able to edit my profile without error.

### Screenshots

![devto](https://user-images.githubusercontent.com/5675200/34707493-1ef4cfc6-f50e-11e7-8186-5d0ae56c6da0.png)

**Comment by Einenlum** [comment]
Finally \o/ Wuhuuuu!

Thanks a lot for your help <3.

**Comment by kylestratis** [comment]
@Zhao-Andy Is it possible to reopen this? I'm having the same error trying to edit my profile.

**Comment by Zhao-Andy** [comment]
Hey @kylestratis, you should be good now. Let me know if otherwise.

Also, if anyone else comes across this; sorry the long standing bug. 🙈

**Comment by kylestratis** [comment]
Thanks @Zhao-Andy - works perfectly now

**Comment by guar47** [comment]
Hey @Zhao-Andy! Could you check my profile too, please?  I have the same problem.

**Comment by Zhao-Andy** [comment]
Hey @guar47, fixed :)

**Comment by guar47** [comment]
@Zhao-Andy Thank you, it's working!
