### ISSUE TITLE
Switch button to hide own post

### ISSUE THREAD

**Issue by yafkari** [thepracticaldev/dev.to#1331]
**Is your feature request related to a problem? Please describe.**
For someone who posts a lot of articles, his feed can quickly be cluttered with irrelevant posts, because he is the author.

**Describe the solution you'd like**
A simple but elegant switch button to hide/unhide own posts.

**Describe alternatives you've considered**
Hide automatically own posts, but I think giving people the choice is a better solution.

**Additional context**
The switch button could be here or here : 
![image](https://user-images.githubusercontent.com/41365655/50053036-45a3d900-012e-11e9-85d7-514893ec17b6.png)

**Comment by benhalpern** [comment]
Hey, this is an interesting idea, but I doubt we'd be able to add this as a feature any time soon based on where we're focused right now.

However, if you were interested in maybe implementing this sort of thing as a browser extension it might act as good food for thought if we were to add it in.

Definitely going to consider the problem in general, but will close the issue.
