### ISSUE TITLE
Feature Request: Night Mode

### ISSUE THREAD

**Issue by ghost** [thepracticaldev/dev.to#134]
# Feature Request

It would be awesome if there was a "night mode" which would switch the site's colors to a darker version which would look better under some conditions.

**Comment by Zhao-Andy** [comment]
Hey Mebin, thanks for bringing this up. We're gonna backlog this for now as we prepare to open source.

**Comment by CanNuhlar** [comment]
I've made a userstyle for myself recently, been using it for a while. Uploaded to userstyles.org now, nothing fancy but It'll do the job until we have a official night mode. https://userstyles.org/styles/163294/dev-to-night-mode

**Comment by maestromac** [comment]
@CanNuhlar Nice! I like what you did there.

**Comment by CanNuhlar** [comment]
Thanks, @maestromac ! I'd like to add this feature as a PR but it looks like a devious work and would require work from multiple people I guess, also I don't know if @benhalpern and his team would approve the color scheme and/or the feature itself.. The color scheme is _complete ripoff_ from Twitter's night mode.

**Comment by benhalpern** [comment]
@CanNuhlar super in favor of the color scheme. I think it needs to be refined, but we can do that.

What I care more about is how this will technically work.

We'll have a setting on the user's profile, but we don't render the page from origin based on the user. Basically we load straight from the CDN _and then_ load user data.

So I think this should be inserted at either:
- The CDN layer on Fastly via custom [VCL](https://docs.fastly.com/vcl/)
- Service worker layer.

I'd prefer service worker I think because it would be modestly more scalable. It's slightly less clear to me exactly how we'd do it but I'd love to go down that road and figure it out.

This is sort of separate from the concerns at the CSS layer. So we could start with just making this work some how with the CSS and go from there.

**Comment by dimensi0n** [comment]
What's the status of this feature ?

**Comment by maestromac** [comment]
Hey @dimensi0n , this issue is up for grab!

**Comment by joybhallaa** [comment]
Can I work on this?

**Comment by maestromac** [comment]
Hey @joybhallaa , someone already submitted a PR (https://github.com/thepracticaldev/dev.to/pull/1104)  for this issue. You are welcomed and encouraged to review it!

**Comment by Link2Twenty** [comment]
I like the colours `#303030` and `#424242` which would produce something like this

![image](https://user-images.githubusercontent.com/3534427/49724616-a1b7ba80-fc61-11e8-8b6f-e023672c40c5.png)


For the border I used `#1f1f1f` and the shadow is `#1d1d1d` and I inversed the colours of the selected `nav-chronofiter-link`

**Comment by Link2Twenty** [comment]
And for my 2 cents, I think we should use [CSS variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables) for themes, then load in a theme css file

```css
body {
  background: var(--theme-body-background, #FFFFFF)
}
```

```css
:root {
  --theme-body-background: #303030;
  --theme-container-background: #424242;
  --theme-container-color: #FFFFFF;
}
```

This would be a lot of effort to start with but it does mean we could offer many themes, down the line, or even let users come up with their own.

**Comment by abraham** [comment]
It would be neat if this could be automatically enabled for `@media (prefers-color-scheme: dark)`.

https://medium.freecodecamp.org/how-to-get-dark-mode-working-with-css-740ad31e22e

**Comment by Link2Twenty** [comment]
@abraham agreed, I think that's probably the path we'll take 😁

https://dev.to/link2twenty/future-of-css-color-scheme-10of

**Comment by Link2Twenty** [comment]
Speaking of how to do this, I think, as a default, we should have it change with the system theme but also let users pick a theme and stick with it.

I don't know much about ruby on rails but is it possible to generate a css file based on user preferences?

**Comment by maestromac** [comment]
I'm not familiar with that feature but i know it's possible to pass [instance variable](https://stackoverflow.com/a/47407355). I'm also wondering if edge caching might have an issue with this.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/2072
