### ISSUE TITLE
Broken navigation button in Firefox

### ISSUE THREAD

**Issue by jnv** [thepracticaldev/dev.to#135]
### Current Behavior

When I hover over the top-right navigation button `#navigation-butt` a menu appears. When I want to select an item from the menu, the menu disappears.

### Expected Behavior

The menu should not disappear and it should allow me to select a link from the menu.

### Additional Info (steps to replicate, device/browser, helpful links)

The issue happens in Firefox 57 on desktop, Chrome is fine. The issue is caused by menu being contained inside `<button>` element. Note that only phrasing content (i.e. not links) [is allowed inside a button](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button). 
Possible fix is to replace `<button>` by `<div>` (it seems that clicking the button does nothing on desktop).

### Screenshots

![](https://user-images.githubusercontent.com/616767/34878287-f22e4dde-f7a9-11e7-958e-999d8dd39166.gif)

**Comment by shindakun** [comment]
Looks like it was swapped to a button for accessibility reasons per #125 
The button should probably toggle the menu visibility, not a mouseover/mouseout.

**Comment by Zhao-Andy** [comment]
Ah, thanks for that. We'll take a look into it.

**Comment by jnv** [comment]
@shindakun Makes sense, though in that case the menu should not be nested inside the button.

**Comment by Zhao-Andy** [comment]
@benhalpern fixed this; let us know if it's still giving you trouble. :)

**Comment by jnv** [comment]
@Zhao-Andy Works fine now, thanks for a swift response! :smile:
