### ISSUE TITLE
Share my Development Setup

### ISSUE THREAD

**Issue by alextakitani** [thepracticaldev/dev.to#1353]
I was writing a blog post to share my dev setup with my colleagues so they can copy the parts that make sense to theirs. I like to read posts like that, always end up learning a thing or two.

I maintain a script on a gist that installs and configure my dev machine, and I try to keep it up to date, so I can always rebuild everything if needed.

So, while drafting that post, I through that I should build a website for people to share their setup, and while searching for a domain name that I liked I remembered of dev.to.  I think it should be the perfect home for it since is focused on devs, open source with a nice community.

So what I suggest is a page, for each user to share his setup. It should have tags so others could search for things like "rails" "ubuntu" "postgres" "vscode" etc.

Users should be encouraged to keep things easy to reproduce, either for they own use as for others as bash scripts, docker images, puppet recipes or something like.

It should be "likeable" so people can sort when searching for a setup. 

It also should be "followable" so people that like that setup get an notification when something changes.

Also, comments would allow others to contribute with tips for the user.

I think it would be a great thing for beginners to have a nice setup ready, and for experienced users to learn about new tools.

It would be great if any new setup or any big change into a existing one gets into the Feed.

**Comment by alextakitani** [comment]
Hi @jessleenyc  the problem with posts is that they become outdated.

What I've imagined is something structured with rules so it can be shared and easily reproduced.

Most people do that over github gists or repos, and that's fine, you can find lots and lots by searching for "my dev setup", but there's not an place ( that I know of at least ) to find those setups, compare etc.

**Comment by benhalpern** [comment]
Having been down this road a bit mentally before, or in terms of features we've attempted, it definitely seems like this still makes sense as a "type" of post.

But I agree with you here:

> the problem with posts is that they become outdated

Luckily, this is a use case we're looking to account for with posts. Ones that are more designed to last and be continually updated, as opposed to moment in time. And this is a great use case for this "type" of post.

Definitely like where your head is at with all of this.
