### ISSUE TITLE
messages and channels not showing unless you filter 

### ISSUE THREAD

**Issue by mariocsee** [thepracticaldev/dev.to#1357]
**Describe the bug**
In `/connect`, when clicking on the paper airplane icon to rerender chat, the chat channels (both direct and group) don't render until I start clicking on the direct or group buttons to filter. After filtering, the connect page behaves as it should. 

**To Reproduce**
1. Go to 'https://dev.to/connect/' 
2. Click on 'the paper airplane button' to rerender 'https://dev.to/connect/' (may take a few tries and multiple clicks)
3. Open browser console
5. But if you start filtering to direct or group, it behaves how it should again. 

**Expected behavior**
When rerendering chat, groups and messages should appear without filtering. 

**Screenshots**
Console error:
<img width="433" alt="screen shot 2018-12-18 at 12 21 01" src="https://user-images.githubusercontent.com/13403332/50177764-cef31100-02d0-11e9-8bb6-3b76e6b002a4.png">

Connect with error:
<img width="1280" alt="screen shot 2018-12-18 at 14 29 08" src="https://user-images.githubusercontent.com/13403332/50177987-5b053880-02d1-11e9-9f55-8b8dc41ce1bb.png">

Connect after filtering (expected behavior): 
<img width="1280" alt="screen shot 2018-12-18 at 14 29 21" src="https://user-images.githubusercontent.com/13403332/50178008-65bfcd80-02d1-11e9-96d7-14fae3fd5039.png">

**Desktop:**
- OS: macOS High Sierra 10.13.6
- Browser: Chrome 
- Version: 71.0.3578.98 (Official Build) (64-bit)

**Additional context**
Bug is similar to #755, but console errors point to different causes. This issue arose trying to investigate/recreate #755.

**Comment by Zhao-Andy** [comment]
Resolved via #1359
