### ISSUE TITLE
Schedule content for future publishing

### ISSUE THREAD

**Issue by bencodezen** [thepracticaldev/dev.to#1363]
## Problem

**I am unable to schedule content for future publishing**

In order to create a consistent flow of content for users, it is critical to have the ability to schedule posts since life often gets in the way. And to be honest, it's hard for the writing muse to strike with inspiration sometimes and it'd be nice to schedule out posts for a future date.

## Solution

**Utilize the frontmatter publish property to designate the publish time**

Currently the publish property takes a boolean of true or false, but it should also accept a date/time value in ISO-8601 format (which I assume most authors on dev.to are familiar with) that runs a script to set the  markdown property to true  after the given time.

## Alternatives

**Form inputs like WordPress for managing the properties of a post**

As someone who used to author content in WordPress, they had a section to manage the data state of a post (i.e., published or draft, time to publish, time updated, tags, etc.). However, while this seems straightforward, I know that this would put a fair amount of work on the team, so I'm suggesting the simplest solution in order to get the feature out sooner rather than later.

## Questions

If you have any questions or want to chat more about it, feel free to reach out to me!

**Comment by aspittel** [comment]
I love this idea, a lot of times I will want to finish writing something late at night and get all the publishing set up, then actually publish them the next morning when people in my time zone are looking at stuff! Think this is great. Would also be excellent for people crossposting so that people with a lot of posts can spread them out instead of posting all at once!

**Comment by pkfrank** [comment]
Thanks for the issue and the initial UX thoughts about how it would work.  This was requested in #230 but would be good to revisit.

**Comment by jessleenyc** [comment]
@bencodezen I'm closing this issue because we're about to make an API available soon so people can build these types of tools. It's possible in the future we'll build this right into the app but for now it's not on the roadmap.
