### ISSUE TITLE
No bullets in tag wiki markdown

### ISSUE THREAD

**Issue by CodeMouse92** [thepracticaldev/dev.to#1368]
Markdown bulleted lists (with a `*` at the start of each line) do not render in the tag wiki sections.

For example, this is the Markdown for the `#cpp` tag...

```
C++ is a compiled programming language developed by Bjarne Stroustrup in 1985. It offers features of imperative, object-oriented, and generic programming.

The current language standard is C++17.

## Documentation

* [cppreference.com](https://cppreference.com/)
* [CPlusPlus.com](http://cplusplus.com/)

## Compilers

* [Clang/LLVM](https://clang.llvm.org/)
* [GCC](https://gcc.gnu.org/)
* [Microsoft Visual C++](https://docs.microsoft.com/en-us/cpp/)

[Complete list...](http://www.stroustrup.com/compilers.html)
```

The output, however, does not put each bulleted item on a new line, nor render the bullets themselves. (See https://dev.to/t/cpp)

**Comment by pkfrank** [comment]
Thanks for the issue, and for getting the `#cpp` tag sidebar looking so good.

**Comment by Link2Twenty** [comment]
It's this section that prevents the bullets from appearing

https://github.com/thepracticaldev/dev.to/blob/fbdd80d5fc3734fc726707294940e20698728c31/app/assets/stylesheets/articles.scss#L1207-L1218

specifically L1208 and L1214
