### ISSUE TITLE
Organization settings page: link url label incorrectly states "Link text"

### ISSUE THREAD

**Issue by anant90** [thepracticaldev/dev.to#1370]
**Describe the bug**
The label above the url field in the "Call-to-action box" section on **Organization Settings** page should read "Link url", not "Link text"

**To Reproduce**

1. Scroll down all the way to the bottom of [Settings organization page](https://dev.to/settings/organization) to "Call-to-action box" section.

**Expected behavior**
The label above the url field should read "Link url", not "Link text"

**Screenshots**
![screen shot 2018-12-19 at 2 54 46 pm](https://user-images.githubusercontent.com/509059/50253268-80ac4380-039e-11e9-8451-0a61c5ae62c1.png)

**Desktop (please complete the following information):**

- OS: Mac OS 10.13,6
- Browser: Safari
- Version 11.1.2

**Comment by maestromac** [comment]
Resolved with #1371
