### ISSUE TITLE
The pulsating Sign-Up button makes it legit hard to read articles.

### ISSUE THREAD

**Issue by minimaxir** [thepracticaldev/dev.to#1372]
**Is your feature request related to a problem? Please describe.**
![ezgif-1-b3bfd4f1ce3d](https://user-images.githubusercontent.com/2179708/50259253-26b87780-03b8-11e9-9f84-2496da7311d7.gif)

This is [another case](https://github.com/thepracticaldev/dev.to/issues/858) where a CTA intended to entice users to register actually accomplishes the opposite goal; they'll just [bounce immediately](https://news.ycombinator.com/item?id=18563756) without reading the article at all due to the distraction.

<img width="470" alt="screen shot 2018-12-19 at 6 03 08 pm" src="https://user-images.githubusercontent.com/2179708/50259306-60897e00-03b8-11e9-8aec-caa3958ee480.png">

**Describe the solution you'd like**
Remove the animation. An alternative is a _single_ pulse on pageload, but that's still not user friendly.

**Comment by GeorgeNance** [comment]
What if we had it only pulse on hover?

**Comment by minimaxir** [comment]
That works.

**Comment by pkfrank** [comment]
Thanks for the issue.  This doesn't appear for _all_ logged out users, but it sometimes does, and makes sense that it could be distracting.  Looping in @benhalpern who might have additional thoughts.

**Comment by benhalpern** [comment]
Hey, getting around to this. We will remove this. It's only one of many variations we threw at the wall and we agree it is overly distracting. It will be removed shortly. Closing the issue.

**Comment by minimaxir** [comment]
👍
