### ISSUE TITLE
Inconsistent design on Sign Up call to action screens

### ISSUE THREAD

**Issue by shindakun** [thepracticaldev/dev.to#138]
### Current behavior:

Currently, when not logged in if you click on the + to follow a tag the user will see a large popup window (see the first screenshot) asking them to sign in. This popup isn't consistent with other sign up calls to action for instance when clicking "Write A Post" or "Ask For Help" (see the second screenshot).

### Expected Behavior

Sign up screens should be consistent on the site.

### Screenshots
![image](https://user-images.githubusercontent.com/319128/34882575-d5d7a83a-f76b-11e7-8684-80f83a954aba.png)

![image](https://user-images.githubusercontent.com/319128/34882768-6e11453e-f76c-11e7-94e6-10097cc1a514.png)

**Comment by jessleenyc** [comment]
Good call, will close the issue when it's fixed.
