### ISSUE TITLE
Comment Templates

### ISSUE THREAD

**Issue by lianafelt** [thepracticaldev/dev.to#1381]
Additional notes from @jessleenyc: 

# Feature Request
Allow authors to include a template for comments to their post. And example of this would be the [Who Is Hiring?](https://dev.to/t/whoishiring) posts that require people to respond with a specific format (see below example). 

-------------
Could the Who is Hiring post have the suggested template text included in the comment, so it would be easier for people to fill out. 

"Company Name | Job Title | Location | Remote or Onsite | (optional) Salary Range | Sponsor visa?

About the company — background, size, etc (1-3 sentences)

About the role(s) — languages, requirements, etc (1-3 sentences)

Do you sponsor visas?

How to Apply — email or application link"

**Comment by maestromac** [comment]
I really like this idea!

**Comment by jessleenyc** [comment]
Hey @lianafelt, this makes a lot of sense. I just updated the title and description of the issue to make it a little more generic since it's a feature we could use beyond the hiring post!
