### ISSUE TITLE
'More from ...' widget showing double articles

### ISSUE THREAD

**Issue by davidjeddy** [thepracticaldev/dev.to#1382]
**Describe the bug**
'More from ... sidebar widget showing two of the same article

**To Reproduce**
Change?

1. Go to https://dev.to/damnjan/when-php-framework-sucks-series-framework-topic-on-a-job-interview-2fjg
2. See duplicate articles in the sidebar 'More from ...'

**Expected behavior**
Not duplicate posts...

**Screenshots**
![image](https://user-images.githubusercontent.com/6232455/50311011-bd953a80-0471-11e9-8aa0-1e4eb73b134e.png)

**Desktop (please complete the following information):**

- OS: Win10
- Browser Chrome
- Version 71.0.3

**Comment by pkfrank** [comment]
Hey @davidjeddy — it looks like these are unique articles, albeit ones with very similar titles (part of the same series).  So I'm not sure this is in fact a bug.  Please let me know if we're on the same page here.

**Comment by davidjeddy** [comment]
@pkfrank You are correct. I didn't read the entire article :S. My bad. Closing this ticket.
