### ISSUE TITLE
Use the editor version set in settings for imported drafts

### ISSUE THREAD

**Issue by dance2die** [thepracticaldev/dev.to#1384]
# 🙏 Feature Request

After setting the editor version to `v2`, new posts can be written using `v2` editor.
But drafts imported from RSS uses `v1` editor.

_____

# 🏃‍♀️ Demo
1. Below shows that the editor is set to `v2`
1. Creating a new post uses `v2` editor
1. but clicking on `edit` for the imported draft uses `v1` editor.

![2018-12-20_18-08-19](https://user-images.githubusercontent.com/8465237/50315936-ab6fc800-0482-11e9-9567-dbffa2a1675f.gif)

_____

# 💭 Suggestion

New post & existing posts (I used the word `draft` above) should use the editor version set in the `Settings > Features`.

![chrome_2018-12-20_18-13-03](https://user-images.githubusercontent.com/8465237/50316017-f2f65400-0482-11e9-8b0e-d989e1a854d3.png)

_____

# 🔁 Alternative Solution

An alternative is to let authors choose an editor in the Edit page.

![chrome_2018-12-20_18-15-40](https://user-images.githubusercontent.com/8465237/50316153-84fe5c80-0483-11e9-987d-e2a70488b779.png)

_____

# ➕ Additional context

This feature was suggested by @maestromac in #1314

**Comment by maestromac** [comment]
Thanks for creating this feature request!

**Comment by maestromac** [comment]
not stale

**Comment by jessleenyc** [comment]
Hey @dance2die, we intentionally set it so that any older posts would continue using the original editor it had when the post was created. Is this still happening to new posts that come in through your feed?

**Comment by dance2die** [comment]
Thanks @jessleenyc for the review. 😄 
Newly imported posts use V1 but with the controls mentioned above sticky.

I wasn't aware this was already implemented so I will close the issue~
Sorry for not following up 😓 

![demo](https://user-images.githubusercontent.com/8465237/62664105-47820d00-b948-11e9-9a76-10a038acf3d4.png)
