### ISSUE TITLE
When podcast player is active offsite links should require confirmation.

### ISSUE THREAD

**Issue by shindakun** [thepracticaldev/dev.to#139]
# _BUG_
### Current Behavior

Currently, if you are listening to a podcast through the onsite player and you click an offsite link you will navigate away losing the podcast player and your progress in the podcast.

### Expected Behavior

While a podcast is playing offsite links should prompt the user, just in case they don't want the player to stop.

### Additional Info (steps to replicate, device/browser, helpful links)

Navigate to a podcast episode, https://dev.to/gotime/62-building-blocks-with-jeff-lindsay
Click to begin playing the episode.
Navigate back to index by clicking DEV logo on upper left.
Find an offsite link and click it, note that you are taken offsite and the podcast stops.

**Comment by jessleenyc** [comment]
Thanks for flagging this.

**Comment by Zhao-Andy** [comment]
We added some better functionality that should cover this. Let us know if otherwise though.

**Comment by shindakun** [comment]
Looks good! Thanks!
