### ISSUE TITLE
Images in emails are not responsive in Gmail

### ISSUE THREAD

**Issue by abraham** [thepracticaldev/dev.to#1393]
**Describe the bug**

Images in comment notification emails can be large and not display in a scaled manor.

**To Reproduce**

1. Comment on a post.
1. Have someone else reply to your comment with an embedded image.
1. Look at the comment notification email in Gmail on the web.

**Expected behavior**

I would expect that the image would be no wider than the width of the displayed email.

**Screenshots**

![screenshot from 2018-12-21 15-53-19](https://user-images.githubusercontent.com/3341/50365139-cf8de080-0538-11e9-85b9-12bf0f8d20f6.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.10
- Browser: Chrome
- Version: 71.0.3578.98 (Official Build) beta (64-bit)

**Additional context**

The particular comment I was notified about: https://dev.to/rhymes/comment/7kna

Potential solutions: https://stackoverflow.com/questions/10711638/how-to-dynamically-resize-an-image-inside-an-email-client

**Comment by pkfrank** [comment]
Thanks for the detailed issue!

**Comment by abraham** [comment]
I think this is still an issue.

**Comment by Shorpee** [comment]
i will like to work on this

**Comment by jessleenyc** [comment]
@Shorpee go for it!

**Comment by luchiago** [comment]
Hi, is this issue still need help?

**Comment by rhymes** [comment]
@luchiago if you want we can test it together: you need to leave a comment and I can reply to it with an image. You have to have email notifications enabled first of course. Let me know if you're willing to do this experiment. We can use one of my articles or yours so not to disturb others

**Comment by luchiago** [comment]
@rhymes I would like to do this test. Sorry for taking so long to answer.

**Comment by rhymes** [comment]
Replied with this https://dev.to/rhymes/comment/khga

**Comment by luchiago** [comment]
We do still have a problem. I'll work on that @rhymes 

![image](https://user-images.githubusercontent.com/30028621/72896991-afae8a80-3cff-11ea-8bb3-b9db69f6db8d.png)

**Comment by rhymes** [comment]
Thank you!

**Comment by luchiago** [comment]
@rhymes How can I test this locally?

**Comment by rhymes** [comment]
@luchiago not easily as development is not configured to deliver emails. We do use the following configuration in production:

https://github.com/thepracticaldev/dev.to/blob/d090ebf026bdedb0b052636d74f399cbc35a6c61/config/environments/production.rb#L110-L121

I think that if you want to test actual emails you'd have to subscribe to the free tier on Sendgrid - https://sendgrid.com/pricing/ - and copy such configuration in `config/development.rb` for your tests

**Comment by maestromac** [comment]
Actually @luchiago , you can preview emails. Check out the doc at https://docs.dev.to/backend/previewing-emails/. What you have to do is respond to a comment on your local setup and make sure your background job is running (your Redis instance) then head to the email preview link and you should see it.

**Comment by luchiago** [comment]
@maestromac Thanks for the tip. But I think shouldn't work when I reply to my own post. I've already made the changes but I can't test.

**Comment by maestromac** [comment]
@luchiago Try making a comment to any post. The preview page will show the latest comment that was emailed out.

**Comment by luchiago** [comment]
> @luchiago Try making a comment to any post. The preview page will show the latest comment that was emailed out.

@maestromac But the mail notification, in this case, is when somebody replies my post with an image and I receive the notification in my mail box

**Comment by maestromac** [comment]
@luchiago Oh I see now. try this.

1. create a comment one post other than your with an image on it.
2. Open up `NotifyMailerPreview` and make the following change on line 4, `NotifyMailer.new_reply_email(Comment.find(1))` to `NotifyMailer.new_reply_email(Comment.last)`
3. Navigate to http://localhost:3000/rails/mailers/notify_mailer/new_reply_email and you should see it now

**Comment by luchiago** [comment]
@maestromac @rhymes I'm not able to upload an image in the reply comment. All the tools are up (elastic, sidekiq, redis) and I have ImageMagick installed. Any ideas?

**Comment by maestromac** [comment]
@luchiago Hmm i'm not too sure. Have you tried using an image from elsewhere? Does that work for you?

**Comment by luchiago** [comment]
I will try with a `liquid_tag` @maestromac

**Comment by luchiago** [comment]
> @luchiago Hmm i'm not too sure. Have you tried using an image from elsewhere? Does that work for you?

Without uploading?

**Comment by maestromac** [comment]
@luchiago yup, because this bug can happen with any large images, or so I assume.
