### ISSUE TITLE
Bug with the save button in the reading list appears randomly

### ISSUE THREAD

**Issue by yafkari** [thepracticaldev/dev.to#1395]
**Describe the bug**
When you click on an article in the reading list and want to return to your list, the posts are marked as unsaved. (SAVE)

The problem appears only on mobile, with chrome but not every time.

It's a bit complicated to explain but I'll try.

**To Reproduce**

_To reproduce on smartphone_
- Start from your homepage.
- Click on the left icon to access the reading list
- Click on a random article in your reading list
- Click on the DEV button, to go back to your feed
- Click on the left icon to access the reading list again
- _if the bug didn't appear, scroll down to refresh (not the refresh chrome button)_

Normally the SAVED button will have become SAVE, otherwise try again, like I said the problem doesn't appear every time.

**Smartphone (please complete the following information):**

- Device: OnePlus 5T
- OS: OxygenOS 5.1.1
- Browser: Chrome
- Version: 71.0.3578.99

**Additional context**
Maybe the same problem as issue #1347

**Comment by pkfrank** [comment]
Hey @yafkari thanks for the detailed issue, and for tagging the potentially-related issue.

**Comment by maestromac** [comment]
I can't seem to reproduce this issue on my OnePlus 2's Chrome but I do see the `[SAVE]` button being briefly flashed to me before being updated to `[SAVED]`. Might have to do with internet speed?

**Comment by yafkari** [comment]
Yes, it happens too on my phone.

I don't think the problem comes from my connection, because it happens in wifi but also in 4G. The problem does not disappear even after a few minutes of waiting

But that's not a big deal, if I refresh the page one or two time, the problem disappear in general.

**Comment by jessleenyc** [comment]
![](https://cl.ly/3ab2ba750681/download/Image%202019-01-08%20at%209.58.22%20AM.png)

I'm actually seeing this bug on desktop chrome. Button doesn't work for me at all and always displays save.

**Comment by abraham** [comment]
I'm seeing the "save" buttons maybe every 10th refresh. Just about every refresh though flickers back and for between "saved" and "save" a couple of times before settling.
