### ISSUE TITLE
Canonical URLs?

### ISSUE THREAD

**Issue by nicolaiparlog** [thepracticaldev/dev.to#14]
Being able to add canonical URLs would allow cross-posting without the risk of a loss of traffic for the original author.

**Comment by benhalpern** [comment]
You can already do that, we just haven't documented it well 😊

Add this to the front matter:
canonical_url: https://example.com

**Comment by NullVoxPopuli** [comment]
I added this:
```
---
title: A general and flexible project structure that works for all projects in any ecosystem.
published: true
description: 
tags: javascript, project, architecture, frontend
canonical_url: https://nullvoxpopuli.com/2019-04-15-a-general-project-structure-that-works-in-any-ecosystem
---
```

but I'm not sure what adding `canonical_url` did. it looks like nothing changed?
