### ISSUE TITLE
All about dev.to link in drop down doesn't link to About page.

### ISSUE THREAD

**Issue by shindakun** [thepracticaldev/dev.to#140]
# _BUG_
### Current Behavior

Currently, the "All about dev.to" link in the profile drop-down menu does not link to the [About](https://dev.to/about) page. It instead leads to an intermediate [information](https://dev.to/p/information) page with additional links that can be found in the footer (except the bug bounty link).

### Expected Behavior

The "All about dev.to" link should link to the About page.

### Additional Info (steps to replicate, device/browser, helpful links)

Click on profile button on upper right of the homepage.
Click on "All about dev.to"

### Screenshots

![image](https://user-images.githubusercontent.com/319128/34883739-522cf93c-f76f-11e7-9687-4a0f9461dfeb.png)

**Comment by jessleenyc** [comment]
The dropdown link name has been updated for clarity.
