### ISSUE TITLE
Can not able to start Storybook 

### ISSUE THREAD

**Issue by yashwanth2804** [thepracticaldev/dev.to#1407]
**Describe the bug**
Unable to get storybook running, just outputting blank html on localhost:6006   

**To Reproduce**
build and run the storybook 

1. yarn run build-storybook
2. yarn run storybook
 
3. See error
```
Uncaught TypeError: Object(...) is not a function
    at Object.<anonymous> (core.browser.esm.js:15)
    at __webpack_require__ (bootstrap 1a97092c3a8a7d0c9de4:678)
    at fn (bootstrap 1a97092c3a8a7d0c9de4:88)
    at Object.defineProperty.value (index.js:20)
    at __webpack_require__ (bootstrap 1a97092c3a8a7d0c9de4:678)
    at fn (bootstrap 1a97092c3a8a7d0c9de4:88)
    at Object.module.exports (index.js:44)
    at __webpack_require__ (bootstrap 1a97092c3a8a7d0c9de4:678)
    at fn (bootstrap 1a97092c3a8a7d0c9de4:88)
    at Object.defineProperty.value (manager.js:14)
```

**Expected behavior**
working storybook url

**Screenshots**
![image](https://user-images.githubusercontent.com/8038593/50487222-5d7b3700-0a23-11e9-8ac0-0ece51df8628.png)

**Desktop (please complete the following information):**

- OS:ubuntu
- Browser chrome
 
 
**Additional context**

from this link from github issues of stoybook [storybook githublink](https://github.com/storybooks/storybook/issues/4796#issue-381363648) , they suggested to update react version,but i am not sure with the preact.

**Comment by nickytonline** [comment]
Maybe there were dependencies updated by dependabot that broke Storybook. Not sure. I don't think anyone else has worked in Storybook in the dev.to repo aside from me, so I will have to look into this, but in the meantime, feel free to keep digging.

**Comment by nickytonline** [comment]
I just looked at this and can replicate your error. It looks like the current version of Storybook isn't backwards compatible with older versions of React, which means Preact as well. I did try upgrading to `@storybook/react@4.14`, but it creates other errors.

I would suggest, for the time being, downgrading Storybook to the last known working version in the repo. Once we have this tied into CI, in the future, it'll break CI if there are breaking changes in deps, see #338.

**Comment by nickytonline** [comment]
@maestromac, I can look into this further, because now it's bugging me 😉

**Comment by maestromac** [comment]
Go ahead @nickytonline 😄 

Just tried it, I'm also experiencing this issue.

**Comment by nickytonline** [comment]
@maestromac, alright, so reverting to 3.4.11 for all the storybook dependencies gets us back up and running. I did however manage to get it running with the latest storybook. The only caveat is that I need to install React as a **dev** dependency. Not ideal, but it works.

I think for the time being, we should probably just go back to 3.4.11 unless the dev.to team is OK with React being in there as a **dev** dependency.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/1410
