### ISSUE TITLE
Content Security Policy on maintenance page results in Twitter link not loading.

### ISSUE THREAD

**Issue by shindakun** [thepracticaldev/dev.to#141]
# _BUG_
### Current Behavior

The maintenance page has a link to twitter but when clicked on in Chrome 63.0.3239.132 (Official Build) (64-bit) or Firefox 58.0b14 (64-bit) and Firefox 58.0b15 (64-bit) results in a CSP warning.

```
Refused to display 'https://twitter.com/thepracticaldev' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".
```

### Expected Behavior

Visitors should be able to click through to Twitter.

### Additional Info (steps to replicate, device/browser, helpful links)

Open site during maintenance and click on the @ThePracticalDev link.

Additionally, the background gif should be loaded over HTTPS not HTTP.

### Screenshots
![image](https://user-images.githubusercontent.com/319128/34896567-226b44da-f79f-11e7-92fd-55bcfb7fdb94.png)
![image](https://user-images.githubusercontent.com/319128/34896580-2f574018-f79f-11e7-84d5-26edcc08741f.png)

**Comment by jessleenyc** [comment]
Thanks for flagging this, putting it on our backlog.

**Comment by shindakun** [comment]
Forgot to ref this issue from the PR, https://github.com/thepracticaldev/dev.to/pull/983
Closing since that was merged.

**Comment by shindakun** [comment]
I can't read it seems lol. May still be stale though.

**Comment by Zhao-Andy** [comment]
I believe it's resolved right? https://dev.to/maintenance.html

**Comment by shindakun** [comment]
No, your right it's resolved. I need a nap lol.
