### ISSUE TITLE
Author article  lost after changing their handle

### ISSUE THREAD

**Issue by devamaz** [thepracticaldev/dev.to#142]
# _BUG_
### Current Behavior
I change my handle on twitter some times back and did same thing on dev.to remember I raise an issue #120 for that. But I just discover when a user changes it's handler the URL of their old posts doesn't change so you can't access them, which means everything is lost?

### Expected Behavior
When user can their handler the URL of the old post should also change so their old post could be link to them

### Screenshots
![dev to](https://user-images.githubusercontent.com/25336847/34910949-88a1d0f4-f8bf-11e7-9d1b-15333f9c3f34.PNG)

**Comment by azjezz** [comment]
i think that the URL is being saved in the database as well ? i don't think that's a good idea, i mean you could just save the user id and create the URL every-time but getting the handler ( you have the user id) and the post slug. saving the URL in the database is not a good practice , if the domain is changed or as above the user handler is changed , its not gonna work anymore. ( this assuming that you save URL in the database with the post )

**Comment by Zhao-Andy** [comment]
Hey, thanks for the heads up and sorry for the late response. I believe this is a caching issue with our search service.

@azjezz We're not saving the URL in our database so no worries there.

**Comment by Zhao-Andy** [comment]
@devamaz I think this solved itself (cache cleared) so should be good now. Let me know if otherwise.
