### ISSUE TITLE
Notifications are blank

### ISSUE THREAD

**Issue by cfjedimaster** [thepracticaldev/dev.to#1438]
**Describe the bug**
The first time I hit the site in a day, I'll see a notifications count. I click to load them, and I always get a blank page (to be clear, page UI is there, just no content). Example:

![image](https://user-images.githubusercontent.com/393660/50576004-5a3ecd00-0dce-11e9-82ac-c58371b9d68c.png)

If I get a notification while browsing the site though, it works correctly.

**To Reproduce**

1. Notice you have notifications waiting.
2. Click on the bell icon

**Expected behavior**
A list of notifications.

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows 10
- Browser Firefox
- Version 64

**Comment by cfjedimaster** [comment]
Yep, saw it yesterday.

**Comment by jessleenyc** [comment]
We've definitely made some changes since this was first reported. @cfjedimaster still an issue?

**Comment by cfjedimaster** [comment]
Haven't noticed the issue in a while.

**Comment by jessleenyc** [comment]
Great! I'm going to close this then.
