### ISSUE TITLE
RSS feed no longer working for new articles

### ISSUE THREAD

**Issue by cfjedimaster** [thepracticaldev/dev.to#1439]
**Describe the bug**
I have dev.to setup to suck new articles in from my feed (https://www.raymondcamden.com/feed_full.xml). At some point this stopped working and no longer picks up new articles. I also tried editing my settings and saving to force a refresh, but it didn't help.

**Comment by jessleenyc** [comment]
@cfjedimaster yeah, this is taking longer for a lot of people. We're looking into it.

**Comment by maestromac** [comment]
This should be resolved with https://github.com/thepracticaldev/dev.to/pull/1566 and https://github.com/thepracticaldev/dev.to/pull/1555

Please let us know if the issue persists!
