### ISSUE TITLE
text/html not properly escaped in code fences

### ISSUE THREAD

**Issue by autoferrit** [thepracticaldev/dev.to#144]
### Current Behavior
with this code fence in an article (stating `bash` syntax`)

```bash
GET / text/html:
    => Matched: GET /
    => Outcome: Success
    => Response succeeded.
```
I am unable to preview, or save my article.

### Expected Behavior
I should be able to save the post or preview the markdown

### Additional Info (steps to replicate, device/browser, helpful links)
changing `text/html` to `text/htma` fixes the problem

### Screenshots
![image](https://user-images.githubusercontent.com/89895/35085636-6d8589ec-fbde-11e7-8a3b-a1092e4f4826.png)

![image](https://user-images.githubusercontent.com/89895/35085670-91ee4d6e-fbde-11e7-9838-084494265f0c.png)

**Comment by Zhao-Andy** [comment]
This is fixed! Let us know if otherwise.

**Comment by autoferrit** [comment]
Works on my machine ! :+1:
