### ISSUE TITLE
Reading List Bug: I can't see my saved articles

### ISSUE THREAD

**Issue by tiagosoares94** [thepracticaldev/dev.to#145]
# _BUG_
### Current Behavior
When I click in "My Reading List" at Homepage of dev.to, it's sends me to a reading list page, but without articles.

### Expected Behavior
Click on Reading List and see all articles.

### Additional Info (steps to replicate, device/browser, helpful links)
I've tested in some browers and the error still the same.
* Firefox Quantum
* Microsoft Edge
* Google Chrome (mobile)

### Screenshots
![image](https://user-images.githubusercontent.com/28827228/35181154-d1dd3c7a-fda3-11e7-90a5-9f318bde938c.png)

**Comment by guidovizoso** [comment]
Desktop Chrome doesn't work either. I'm facing the same problem.

**Comment by Zhao-Andy** [comment]
Thanks for the report. Gonna take a look at it.

**Comment by guidovizoso** [comment]
For more information: This is my console's output:

![image](https://user-images.githubusercontent.com/27702539/35184926-816d1e22-fdda-11e7-8323-5b727b8e3f62.png)

**Comment by Zhao-Andy** [comment]
Hey, @benhalpern fixed this I believe. Let us know if it doesn't work again though.

**Comment by guidovizoso** [comment]
@Zhao-Andy Sorry for bothering again but I'm having a very strage behaviour. When I make a full refresh of the site (Ctrl + F5) I'm able to see the reading list. When I refresh the reading list (F5 only) the articles dissapear again. The site can be fully navigated now, just wanted to let you guys know this issue.

**Comment by Zhao-Andy** [comment]
Ah, that's because of our CDN caching. I just cleared it; let me know if you're still getting that issue.

**Comment by guidovizoso** [comment]
@Zhao-Andy Everything is working great now. Thanks!
