### ISSUE TITLE
Blank Mentor Descriptions

### ISSUE THREAD

**Issue by lianafelt** [thepracticaldev/dev.to#1454]
On https://dev.to/internal/users/unmatched_mentee, there are blank mentor descriptions showing up as potential mentors. Blank mentor fields should not be included as potential mentor matches. 

![image.png](https://images.zenhubusercontent.com/5a60cc5f4b5806bc2bc348c3/72e09904-1c89-4095-bee8-aa8a79319932)

**Comment by jessleenyc** [comment]
I'm guessing this is because they had previously filled out the form but then updated it to be blank.
