### ISSUE TITLE
Mentee Description is duplicated

### ISSUE THREAD

**Issue by lianafelt** [thepracticaldev/dev.to#1455]
On https://dev.to/internal/users/unmatched_mentee, mentee descriptions are duplicated in the description field. They should only be showing up once, not three times. 
![image.png](https://images.zenhubusercontent.com/5a60cc5f4b5806bc2bc348c3/87b8a144-5a3e-4412-8199-60ae9998efde)

**Comment by Zhao-Andy** [comment]
Resolved via https://github.com/thepracticaldev/dev.to/pull/1444
