### ISSUE TITLE
DEV-related Liquid tags improperly render text sometimes

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/dev.to#1459]
# Bug Report
`user`, `tag`, and `link` Liquid tags, when used in certain contexts, do not render text properly.

For example, with these two Markdown examples:
```markdown
Isn't {% tag discuss %} about that?
# or 
Isn't {% tag discuss %}
about that?
```

Will render something like:

![image](https://user-images.githubusercontent.com/17884966/50658933-e7b62480-0f68-11e9-9638-cb2a212d920f.png)

The issue is that the `about that?` is not being wrapped with a `<p>` tag, but has a line break `<br>` immediately after the Liquid tag `<div>`.

I tested this with the CodePen tag and that worked out okay.

A temporary fix is to add an additional line after using the DEV-related Liquid tag:
```markdown
Isn't {% tag discuss %}

about that?
```

**Comment by mariocsee** [comment]
Couldn't recreate issue in development and there's no more line break immediately after the Liquid Tag in development and production

**Comment by jessleenyc** [comment]
Going to close this since we couldn't recreate.
