### ISSUE TITLE
Change my Twitter user in dev.to profile

### ISSUE THREAD

**Issue by cmmata** [thepracticaldev/dev.to#146]
### Request or User Story
Like in #120, I want to use another twitter username in dev.to. I login to my profile to edit it but can't find the way to do it.
### Definition of Done
[My dev.to profile](https://dev.to/cmmata) should point to the Twitter username `cmmatam`.
### Notes
Continue with this great job! :D

**Comment by Zhao-Andy** [comment]
Gonna email you to follow up. Sorry about that issue.
