### ISSUE TITLE
Feature request: Open connect/inbox

### ISSUE THREAD

**Issue by bgadrian** [thepracticaldev/dev.to#1460]
**Is your feature request related to a problem? Please describe.**

I cannot be contacted using Dev.to Connect private messages. 

**Describe the solution you'd like**

I would like a checkbox to allow anyone from the community to contact me, similar with the open DM on twitter.

**Describe alternatives you've considered**

Larger emphasis on my email address on the profile page.

**Comment by benhalpern** [comment]
We agree that this should be a thing.

**Comment by mariocsee** [comment]
I can give it a shot if no one's working on this yet!
