### ISSUE TITLE
Export comments

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#1461]
**Is your feature request related to a problem? Please describe.**

Now that dev.to has the option to export posts I think it's time to think about adding comments to the zip file.

I'm opening this issue to see if comments should be added and if so, how and with which attributes

**Describe the solution you'd like**

Comments have their own attributes but they're also part of a tree structure. Should the notion of the parent be part of the export? In which way?

It should also be decided which attributes are part of the exported JSON.

These are the attributes of the comment:

```ruby
  create_table "comments", id: :serial, force: :cascade do |t|
    t.string "ancestry"
    t.text "body_html"
    t.text "body_markdown"
    t.integer "commentable_id"
    t.string "commentable_type"
    t.datetime "created_at", null: false
    t.boolean "deleted", default: false
    t.boolean "edited", default: false
    t.datetime "edited_at"
    t.string "id_code"
    t.integer "markdown_character_count"
    t.integer "positive_reactions_count", default: 0, null: false
    t.text "processed_html"
    t.integer "reactions_count", default: 0, null: false
    t.boolean "receive_notifications", default: true
    t.integer "score", default: 0
    t.integer "spaminess_rating", default: 0
    t.datetime "updated_at", null: false
    t.integer "user_id"
    t.index ["ancestry"], name: "index_comments_on_ancestry"
  end
```

**Comment by abraham** [comment]
What comments should be exported? Comments that the user had made? Comments on posts made by the user? If it's the later what are the expectations a user might have about their content being exported by somebody else. Are there UI affordances or documentation that needs to be updated to highlight this?

**Comment by rhymes** [comment]
Hi @abraham, you only export your own content, so it would be the comments of the user requesting the export. Same as with the articles.

The UI definitely needs to be updated:

![screenshot_2019-01-04 rhymes dev profile](https://user-images.githubusercontent.com/146201/50700312-7babed00-104a-11e9-95f3-a9b3c3db2d68.png)

**Comment by rhymes** [comment]
@benhalpern agreed, only one detail, the export for posts contains the reactions counts: 

https://github.com/thepracticaldev/dev.to/blob/master/app/services/exporter/articles.rb#L39 (and line 44)

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/1471
