### ISSUE TITLE
Add basic formatting for plain text podcast descriptions.

### ISSUE THREAD

**Issue by meredevelopment** [thepracticaldev/dev.to#147]
# _TASK or Feature_
### Request or User Story
Some podcast services do not allow HTML in the episode description. For example a podcast I host called Relative Paths is hosted on Soundcloud and they only allow plaintext descriptions. At present, when out episodes are displayed on dev.to/pod, they appear as one chunk of unformatted text. It would be good there was a way to mark a podcast that has plain text descriptions, and use some simple nl2br type functions to add some formatting. Maybe even some link detection. 

### Notes
Screeny of the unformatted description at present: 

![image](https://user-images.githubusercontent.com/3437528/35285303-ecb56802-0054-11e8-9512-ccb3497f1f75.png)

**Comment by Zhao-Andy** [comment]
Hey @meredevelopment, thanks for the heads up. We support plain text formatting now :) Here's an example:
https://dev.to/relativepaths/51-state-of-the-union

Also, I didn't see your note about link detection. I'll add that in soon.
