### ISSUE TITLE
UI contrast and drawing attention to the right places

### ISSUE THREAD

**Issue by savovs** [thepracticaldev/dev.to#1470]
**Is your feature request related to a problem? Please describe.**
The article view is hard to read because the UI makes you look to the right instead of at the article:
![example of box-shadow being too distracting](https://user-images.githubusercontent.com/1226564/50738262-cef87980-11c9-11e9-812c-c111ec1c0ed2.jpg)

Because dev.to is about reading articles, the article should attract the most attention. The box-shadows are very flavouful, but when there's a lot of text to read it quickly gets tiring to read.

**Describe the solution you'd like**
We can make it easy on the eyes by enforcing a visual hierarchy by tweaking color values, so that the user doesn't have to try hard to look away from the right (like I did). Basically the area of most importance (the article) would have the most contrast, the second area in importance would have less contrast (black would turn to gray), and so on...

Here's what I came up with in the browser inspector, I accidentally made the article text gray though, it should be black:
![reduced contrast of less important elements](https://user-images.githubusercontent.com/1226564/50738528-eab14f00-11cc-11e9-85b7-7126e8f5683a.png)

**Describe alternatives you've considered**
Could also reduce the color value of every less important element, like text, not just the box-shadows, so that the article font is blacker and hence have more contrast than the less important stuff.

**Additional context**
This reasoning is rooted in visual design principles, see section 3, titled Value, of this [style guide](https://nexus.leagueoflegends.com/wp-content/uploads/2017/10/VFX_Styleguide_final_public_hidpjqwx7lqyx0pjj3ss.pdf). 

Having a hierarchy of value ranges for specific elements can improve readability and accessibility. When I first saw dev.to I quite liked the bold box shadow, I think it adds personality. But with time I just naturally resort to the Firefox reader view because the article view is too straining for my eyes.

There is an issue related to this like #1273, but I think it doesn't make sense in the big picture. The overall experience should be non-straneous so that users can read more articles, only after this is accomplished should people think about how to get a better lighthouse score.

**Comment by Link2Twenty** [comment]
Currently, those drop shadow colours are set by the user.

I guess a question is, do we still want users to be able to colour that themselves?

**Comment by savovs** [comment]
Maybe we can still let them choose the colour but clamp the value?
