### ISSUE TITLE
High storage usage when signed in (with GitHub) using Chrome on Android

### ISSUE THREAD

**Issue by michaelneu** [thepracticaldev/dev.to#148]
# _BUG_ (?)
### Current Behavior

When signing in to dev.to using GitHub, Chrome on Android displays high storage usage (~187MB after a clean; when I noticed it, it was 2**G**B).

After clearing dev.to's storage and revisiting the site logged out, it uses about 400kB. Signing in, bumps up the storage usage to ~187MB again (it even went up to 387MB one time).

### Expected Behavior

Keeping a somewhat lower footprint would be desirable. I'm not quite sure what these 2GB of data were, but it seems like oddly much data compared to the 5MB other sites are using.

### Additional Info (steps to replicate, device/browser, helpful links)

Device: Nexus 5X (Android 8.1 - January patch level)
Browser: default Chrome

Steps to reproduce:

- clear site storage
- visit dev.to
- make sure you're *not* signed in
- check site storage (shouldn't be much, ~400kB on my device)
- sign in using GitHub
- check site storage again (187MB for me)

I'm not sure if it's linked to GitHub's sign in flow, but I guess this shouldn't affect dev.to's storage. Please note that this also doesn't seem to be cached data (like images), as clearing Chrome's cache didn't affect the 2GB/187MB.

**Comment by Zhao-Andy** [comment]
Hey Michael, thanks for the heads up. We're looking into this now.

**Comment by Zhao-Andy** [comment]
@benhalpern made a push and updated our service worker logic. Let us know if the amount stored is still super high.

**Comment by benhalpern** [comment]
Things are better now but we have our eyes on this. I'm going to close but we are going to keep monitoring this a lot closer and try to improve our understanding about the different things that could be contributing to issues. Thanks for bringing this to our attention.
