### ISSUE TITLE
Feature request: embedding SlideShare

### ISSUE THREAD

**Issue by ice-lenor** [thepracticaldev/dev.to#1483]
I don't seem to be able to embed a slide deck from Slideshare. I've tried the direct link to the slides (this works in WordPress) and the "embed" piece of html from slideshare. 

So I think it would be nice to have a possibility to insert a slide deck into a dev.to post.

Thanks a lot!

---

An example presentation I wanted to share: https://www.slideshare.net/ElenaNikolaeva9/geo-crash-course-127477385

**Comment by Link2Twenty** [comment]
To do this with an `iframe` we'd need the key

![Share button](https://user-images.githubusercontent.com/3534427/50825304-a0e17980-1330-11e9-8808-9146711de09b.png)

![image](https://user-images.githubusercontent.com/3534427/50825356-bb1b5780-1330-11e9-9a6e-4ec263354d6d.png)

You can see the URL in the `iframe` section
https://www.slideshare.net/slideshow/embed_code/key/EhDjrrN57Qwxwt

Then, in theory, we could impliment something like this.

`{% slideshare EhDjrrN57Qwxwt %}`

**Comment by Link2Twenty** [comment]
Let me preface this by saying my ruby experience is a little lacking.

@benhalpern is this the correct format?

```ruby
class SlideshareTag < LiquidTagBase
  def initialize(tag_name, key, tokens)
    super
    @key    = validate key
    @width  = 595
    @height = 485
  end

  def render(_context)
    finalize_html <<-HTML
      <iframe 
        src="//www.slideshare.net/slideshow/embed_code/key/#{@key}" 
        width="#{@width}"
        height="#{@height}"
        frameborder="0"
        scrolling="no"
        allowfullscreen> 
      </iframe>
    HTML
  end

  private
  
  def validate(key)
    if key =~ /[a-zA-Z0-9]{14}/
      key
    else
      raise StandardError, "Invalid Slideshare Key"
    end
  end
end

Liquid::Template.register_tag("slideshare", SlideshareTag)
```

**Comment by Link2Twenty** [comment]
I've done a pull request anyway if I've done something wrong feel free to tell me what.

Provided this is fine I'll add a few other tags.

**Comment by Link2Twenty** [comment]
@ice-lenor I think we can close this now 👍 

https://dev.to/link2twenty/changelog-new-slideshare-liquid-tag-d0i

**Comment by ice-lenor** [comment]
This is awesome. Thank you so much!
