### ISSUE TITLE
[Airbrake] [Production] Cannot read property 'reason' of null

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/dev.to#1486]
**Error type:** `TypeError`
**Error message:** `` Cannot read property 'reason' of null ``
**Occurred at:** Jan 08, 2019 16:19:43 UTC
**First seen at:** Jan 01, 2019 09:41:10 UTC
**Occurrences:** 37656 (6590 since last deploy on Jan 07, 2019 21:13:46 UTC)
**Severity:** `error`

Think we're looking for a `reason` column on the `notes` table in some file in `app/assets/javascript` on pages where it's not available.

**Comment by maestromac** [comment]
not stale

**Comment by rhymes** [comment]
As we don't have airbrake anymore, I think we can close this
