### ISSUE TITLE
Footer on front page is inaccessible

### ISSUE THREAD

**Issue by jannisfink** [thepracticaldev/dev.to#149]
# _BUG_
### Current Behavior
when scrolling down to the footer, new posts are being loaded and the footer jumps further down

### Expected Behavior
to be honest, I don't know 😄 

### Additional Info (steps to replicate, device/browser, helpful links)
just open https://dev.to/ and scroll all the way down

**Comment by Zhao-Andy** [comment]
Hey @jannisfink, thanks for the heads up. We actually know this is the case, and the Key Links sidebar has everything the footer has. The footer is meant
