### ISSUE TITLE
Paired underscores in a username prevents @-mention linking properly

### ISSUE THREAD

**Issue by pkfrank** [thepracticaldev/dev.to#1491]
**Describe the bug**
I tried to @-mention the user `_morgan_adams_` ([DEV profile](https://dev.to/_morgan_adams_)) and noticed this issue.  Instead of auto-linking to the DEV profile properly, it interprets the underscores as Markdown instructions to italicize.  This is an issue both in both comments and posts.

**To Reproduce**
See GIF below.

**Expected behavior**
The @-mentioned username should link to the DEV account properly.

**Screenshots**
![example GIF showing the issue in action](https://cl.ly/dbb3d7213162/Screen%20Recording%202019-01-08%20at%2001.07%20PM.gif)

**Comment by Defman21** [comment]
IIRC Redcarpet allows you to disable markdown inside words, e.g. `some_cool_stuff` will be some_cool_stuff, not some _cool_ stuff

**Comment by ilonacodes** [comment]
@pkfrank you can use backslash to escape underscore in markdown like `@\_morgan_adams_`. I just tried on dev.to and it seems to work.

**Comment by chase-stevens** [comment]
Backslash works for me as well per @ilonacodes comment. Is this a bug or expected behavior?

**Comment by maestromac** [comment]
We aren't expecting our users to have to manually escape those underscore so I'd say this is a bug.

**Comment by mariocsee** [comment]
If no one is working on this, I think I can take it.

My hunch is that there has to be a check disabling some markdown rules in `markdown_fixer.rb` for words that start with @ since it's used for mentioning, but will continue tomorrow.

**Comment by ClaraMorgen** [comment]
@mariocsee Are you still on it? I think I would like to have a look at it!

**Comment by mariocsee** [comment]
@ClaraMorgen I ended up working on something else then. Go for it!
