### ISSUE TITLE
Editor does not save draft when clicking on help (?) link at bottom.

### ISSUE THREAD

**Issue by julesmanson** [thepracticaldev/dev.to#1494]
When editing a new post every time I click (also when I right-click to open in new tab) the help link at bottom the editor loses everything I typed. It goes to that link from the same window or tab. When I back click on the browser it never returns me to the editor or the draft I was working on. It is completely lost. This issue should be at the very top of your to-do's.

I would like for the editor to auto-save drafts or at the very least open the help link in a new window or tab with `target="_blank"`. How hard can that be? Just edit a single line in the HTML or add a target attribute to the javascript that generates links.

**Comment by rhymes** [comment]
@julesmanson i know it's not very clear (sometimes I have to stop and think about it) but if you re-click the help button you'll see that your post is still there. It's just a div on top of the editor I think.

**Comment by Link2Twenty** [comment]
Instinctively, and I do this myself, you want to press the back button rather than toggling it.

Relates to #1318

**Comment by jessleenyc** [comment]
Hey, sorry for the delay here. Closing this issue because we have an autosave feature that's WIP that should help here. We'll also take some of the design feedback into consideration when we make changes in the future.
