### ISSUE TITLE
[UI] Collapsible comments on Mobile

### ISSUE THREAD

**Issue by Link2Twenty** [thepracticaldev/dev.to#1498]
On mobile, the collapsible comments arrow and summary are a little small.

![Screenshot](https://user-images.githubusercontent.com/3534427/50861979-47119b80-1392-11e9-8e26-abea89a78e6d.png)

Reddit, who also do collapsible comments, get around this by not having collapsible comments, on mobile, but rather only displaying base level comments with a button to reveal replies.

![Reddit](https://user-images.githubusercontent.com/3534427/50862375-63fa9e80-1393-11e9-937d-f9ca1a7221d5.png)

Once replies are revealed they can **not** be hidden away again.

This issue serves as a place to discuss the UI for mobile and any changes that may need to be made.

**Comment by Alcha** [comment]
I personally like how they look on replies to base level comments. Instead of the button being on top, having it on the left is much nicer.

When you press it and it goes to its collapsed state, I think it looks nice as is.

**Comment by benhalpern** [comment]
This specific issue was dealt with by _slightly adjusting_ the size and colors here. So will close this now as good enough for now.
