### ISSUE TITLE
A/B Testing for Headlines and Articles

### ISSUE THREAD

**Issue by tra38** [thepracticaldev/dev.to#15]
I've been thinking about A/B Testing for a while. While I don't actually *know* enough about A/B testing to feel confident in actually doing it yet, I do know that there's no way that I could do it on my own local blog (since I won't have enough traffic for it to matter). A/B Testing has to be done on a popular-enough website (such as dev.to) to gather a large enough sample size to be able to make any conclusions.

Headline A/B testing - write two headlines for your article, then test to see which one gets more clicks.
Article A/B testing - write two articles, and then test to see which one gets more *reads*. (This one I'm more intrigued by, since I like people to read my stuff, not click on them.)

Okay, article A/B testing is much rarer before (probably because rewriting the same article twice is boring and dull), but I think it's doable on a large scale thanks to [Prolefeed](https://github.com/tra38/Prolefeed). By writing out a bunch of paragraphs, you can then randomly order them in whatever way that works. Each random assortment of paragraphs is its own "article". You can generate two random articles and then test to see which one performs better.

I don't know any business use case for A/B testing on a website like dev.to, other than the fact that it's technically interesting. So I'm fine with this feature being postponed or rejected. I was just thinking of ways to optimize the content generation process (both manually and automated) to ensure that people read what is being writing.

**Comment by Zhao-Andy** [comment]
Hey @tra38, we're prioritizing other features like open sourcing the repo, but definitely a great suggestion.
