### ISSUE TITLE
Author article missing when saved via Pocket

### ISSUE THREAD

**Issue by andyw8** [thepracticaldev/dev.to#150]
### Request or User Story

As a reader who uses [Pocket](https://getpocket.com)
When I save an article to Pocket
Then the saved article should include the author's name.

### Definition of Done

Chose an article. Save it to Pocket. View it on Pocket and verify the author is shown at the top of the article.

### Notes

Pocket generally attempts to automatically determine the author, but this does not seem to work for articles on dev.to

**Comment by Zhao-Andy** [comment]
Fixed, thanks for the heads up!

**Comment by yafkari** [comment]
The issue has reappeared or has not been resolved :

![problem](https://user-images.githubusercontent.com/41365655/50084164-515ad280-01f6-11e9-8ba2-a2ac1283992b.png)

Here is an example of a site where the author appears :
![image](https://user-images.githubusercontent.com/41365655/50084233-8830e880-01f6-11e9-80a8-ad24978db476.png)

**Comment by yafkari** [comment]
In fact, the problem occurs when you want to read an article from getpocket.com and not when using the firefox read mode (pocket integrated with firefox).

getpocket.com :
![image](https://user-images.githubusercontent.com/41365655/50112498-a40cac80-023f-11e9-9328-311c1d354c0a.png)


Read mode in Firefox ( Developer Edition ) : 
![image](https://user-images.githubusercontent.com/41365655/50112533-b25ac880-023f-11e9-97fa-d73594245e64.png)

**Comment by Zhao-Andy** [comment]
Hey @yafkari, I resolved it previously for Reader Mode in Firefox, but not entirely sure what the Pocket app looks for. Do you have any ideas about how to resolve this?

**Comment by Zhao-Andy** [comment]
Thanks, I'll give that a try and if it doesn't work, I'll send an email.

**Comment by Zhao-Andy** [comment]
Unfortunately, add `rel="author"` to the `<a>` tag did not work (at least in development). I've emailed them and will see where it goes.

**Comment by Zhao-Andy** [comment]
Received a reply from Pocket Support. TLDR is that they said they'll look into it and fix it on their end. 

Email reply:
> I took a closer look and I was able to reproduce the same issue. It seems like the author's name is incorrect in Pocket's Article View. I've gone ahead and manually filed a bug report for this issue with our developers so they can start working on a fix. Also, I've tagged this conversation to get back to you as soon as we have an update.

**Comment by Zhao-Andy** [comment]
Pocket has responded and said it now works with dev.to! Not sure how to test it though since they seem to have a new UI.

**Comment by Zhao-Andy** [comment]
Ah never mind, I figured out 🙃
