### ISSUE TITLE
Add comment reaction count to dashboard

### ISSUE THREAD

**Issue by vinistock** [thepracticaldev/dev.to#1505]
**Is your feature request related to a problem? Please describe.**

Feature.

Dev already has a post reaction count in the dashboard page. I thought it would make sense (in my opinion, of course) to have a comment reaction count as well.

A lot of comments contribute significantly to the content present in articles so I believe it makes sense to include the count for them as well.

**Describe the solution you'd like**

Have the dashboard display the number of total comment reactions.

From a brief code analysis, it should be as simple as doing a sum over a user's comments' reaction count. The extensive part of the work is the design and the front end portion.

**Comment by pkfrank** [comment]
Thanks for the feature request.  This could be an interesting and fun statistic, especially for folks that tend to comment more than post.

**Comment by vinistock** [comment]
I can help put together a pull request for it if the feature is approved. Just let me know if you guys have a preferred design.
