### ISSUE TITLE
Not able to change Twitter handle

### ISSUE THREAD

**Issue by vishwan11** [thepracticaldev/dev.to#151]
# _TASK or Feature_
### Request or User Story
This is with reference to #120 . I recently changed my twitter handle and tried to update the same in my Dev.to profile. I don't find an option to edit my twitter handle anywhere. Could you help me change it?
### Notes

# _BUG_
### Screenshots

**Comment by Zhao-Andy** [comment]
Gonna email you for the fix since we have to do it manually on our end for now. Thanks for the heads up.

**Comment by raulsanchez1024** [comment]
> Gonna email you for the fix since we have to do it manually on our end for now. Thanks for the heads up.

Anyway you can change my twitter handle as well? I recently changed my twitter handle and Dev.to didn't update it
