### ISSUE TITLE
Twitter and Github links too big on safari reading view

### ISSUE THREAD

**Issue by Kurtz1993** [thepracticaldev/dev.to#1517]
I've always used the reading view in mobile safari to read articles in the webpage, but recently I found that Twitter and Github icons are being rendered at 100% of the viewport's width.

**To Reproduce**

1. Go to any article in dev.to using mobile safari
2. Click on reading view
3. See error

**Expected behavior**
The icons should be rendered at normal movile size.

**Screenshots**
![f2dc5134-9f10-4e0f-a432-126e85bf7043](https://user-images.githubusercontent.com/5412470/51014462-63960b00-152d-11e9-943d-b69d3e113335.png)

**Smartphone (please complete the following information):**

- Device: iPhone 7
- OS: iOS 12.1.2
- Browser: Safari

**Comment by jessleenyc** [comment]
Are you still seeing this bug?

**Comment by maestromac** [comment]
Looks like a case of [flash of unstyled content](https://en.wikipedia.org/wiki/Flash_of_unstyled_content). 

Please let us know if this issue persists. Closing.
