### ISSUE TITLE
Tag liquid tag overflowing comment box in notifications

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#1520]
**Describe the bug**
Styling of the tag liquid tag is getting cut off / not minimizing properly. 

**Screenshots**
![](https://cl.ly/0f2e16321171/download/Image%202019-01-11%20at%2012.42.54%20PM.png)

**Comment by grv19** [comment]
Can I take this up? @jessleenyc

**Comment by Zhao-Andy** [comment]
@grv19 go for it!

**Comment by grv19** [comment]
@Zhao-Andy Can you help reproduce this? I'm not able to reproduce.

**Comment by jessleenyc** [comment]
To reproduce you'll want to:

- Create two users (yours and another)
- Create a post under your account
- Make sure you're running delayed jobs: `rake jobs:work`
- Have the other account leave a comment with the tag liquid tag

As long as jobs are running you should be able to see a notification come in.

**Comment by coolbrg** [comment]
I am also not able to reproduce it.

I exactly followed the steps mentioned by @jessleenyc https://github.com/thepracticaldev/dev.to/issues/1520#issuecomment-517086573 . 

and added comment as
```
# contributorwanted

{% user jess %} some text
```

I am still able to reproduce it.
<img width="587" alt="Screenshot 2019-10-23 at 2 31 48 PM" src="https://user-images.githubusercontent.com/1132451/67375169-f3c7ad00-f5a1-11e9-9dd2-055b382d5d8f.png">

I will be working on it too :)

**Comment by coolbrg** [comment]
I found that the style in this line
https://github.com/thepracticaldev/dev.to/blob/c09a5c70f1d9989ec49b162bf59a3c8f594bd03b/app/views/tags/_liquid.html.erb#L1

need to be appended with `width: auto`.

However, on updating the file and reloading the server, it doesn't reflect the changes.

Is there anything I am missing here?

**Comment by maestromac** [comment]
Hello @coolbrg , each liquid tag are generated and saved as part of `body_markdown`. You'll need to create a new article and follow Jess's direction again to see the change.

**Comment by coolbrg** [comment]
Thanks @maestromac for the pointers. Appreciated.

**Comment by luchiago** [comment]
HI, does this problem still need help?

**Comment by coolbrg** [comment]
> HI, does this problem still need help?

@luchiago Yes, please go ahead as I am not getting much time to dig into it.

This is the last point where I could reach https://github.com/thepracticaldev/dev.to/issues/1520#issuecomment-545369557

**Comment by luchiago** [comment]
@coolbrg but could you reproduce the bug?

**Comment by coolbrg** [comment]
> @coolbrg but could you reproduce the bug?

@luchiago  Yes

**Comment by luchiago** [comment]
@coolbrg how can I use the users from seeds to make manual tests? Like, have my Github account logged and after that login with a user from database?

**Comment by maestromac** [comment]
@luchiago what would you like to accomplish? You could control seed db users via rails consoler to make. Commands like
```
that_user.follow(me)
me.follow(that_user)
```
should get you started with notifications. Be sure you have the background jobs running too `bin/rails jobs:work`

**Comment by luchiago** [comment]
@maestromac Yeah it's something like that I was searching for to reproduce the bug. Thank you.

**Comment by AlbertoPdRF** [comment]
> Hello @coolbrg , each liquid tag are generated and saved as part of `body_markdown`. You'll need to create a new article and follow Jess's direction again to see the change.

I'm working on this issue, and even after doing this I'm not able to see the change. Any clue of what may be going wrong?

**Comment by coolbrg** [comment]
> EDIT: it was a problem on my side, I'm seeing my changes applied now :)

Glad to hear and see it fixed 👍
