### ISSUE TITLE
Add Org mode syntax support for creating posts

### ISSUE THREAD

**Issue by avocadoras** [thepracticaldev/dev.to#1526]
I'm used to using Org mode syntax for writing text. The current way of editing posts right now is only with Markdown. I like that there is a button for help, since I do not know many of the syntax for markdown. 

So, I would like to add Org mode syntax as an option to edit text when writing new posts. Github currently supports this feature and can render Org mode texts.  This feature would be very helpful for those of us used to Org mode syntax.

**Comment by benhalpern** [comment]
Hmm, can you elaborate on exactly what GitHub does and what you're proposing here?

Sounds useful, and more clarification would be lovely.

**Comment by avocadoras** [comment]
My bad, I propose to support styling text with Org Mode.

Markdown
```
# h1
## h2
### h3
```

Org Mode 
```
* h1
** h2
*** h3
```

# Markdown
## h2 example

Org mode styling example not supported in comments
```
* Org mode equivalent
** h2 example
```
Should also support *bold* , =emphasis=, _underline_, -strikethrough-, ~code~

link to org mode guide: https://orgmode.org/guide/Emphasis-and-monospace.html

Does that make sense?

**Comment by abraham** [comment]
Maybe DEV should provide a set of simple APIs that browser extensions can leverage so the community can add features like this.
