### ISSUE TITLE
Refresh from canonical source automatically or on user demand

### ISSUE THREAD

**Issue by lobo-tuerto** [thepracticaldev/dev.to#153]
# Refresh from canonical source

### Request / User Story

I usually keep up to date any articles that I post to my blog, so I think it would be very cool to have a crossposted article to be automatically updated on http://dev.to. Or maybe updated on demand (on request by the user/post owner).

I ask about this because I continually revisit my posts and update them to reflect changes in new software versions, explain something a little bit better, etc.

* If automatically, it could be a feature that you enable on some posts (harder).
* If manually, then it's up to the user to indicate when he has updated his canonical source (easier).

Right now, whenever I fix something on my blog, I have to go and edit the one on dev.to to match the new content. I don't like my content on dev.to to get stale or deviate too much from the canonical source (my blog).

Thanks!

**Comment by philnash** [comment]
This would really need to be opt in or somewhat manual. Some of the things posted to my blog refer to "this site" meaning my blog, which have to be updated for dev.to to refer to "my site", and other similar problems.

I do agree that the site helping this along would be better as I've definitely updated the source and forgot about the dev.to version before!
