### ISSUE TITLE
Profile checkbox for "Allow edits to my articles" + musing on VC for articles

### ISSUE THREAD

**Issue by michael-tharrington** [thepracticaldev/dev.to#1539]
**Is your feature request related to a problem? Please describe.**
Not exactly. As DEV grows, we should continuously think of ways we can improve the platform for contributors and readers. Through providing efficient ways to clean up grammar on the site, we make articles on dev.to more easily readable and help to improve the writing of/teach the writer(s) of the post.

**Describe the solution you'd like**
In the short term, we should offer users the ability to check a box in their profile that says "Allow edits to my articles" which would then be displayed within the person's profile and viewable to admins only. The capability to edit articles is already available to admins, but this would just be a way for writer's to give the go ahead and say it's cool.

In the long term, I think it would be beneficial if we could open up the ability to edit articles to the community by creating a sort of version control system for writers and their writing. This way, any user could make a PR to fix a typo/wonky sentence structure/etc. in another user's post. (Perhaps, we'd only want to allow people that mutually follow each other to do this.) A writer could then view the edits made on their work and potentially okay them or not. This would be good because we'd be able to crowd source some of the work which would make the system more scalable. Basically, I'm imagining a system that would highlight any changes an editor were to make and then ask the author if they're okay with merging them.

**Describe alternatives you've considered**
As far as editing work goes, so long as someone has admin permissions, they're able to edit content. For instance, I have admin permissions and I've considered reaching out to authors via email and asking them if I can grammatically correct a few things in their work. I haven't really done this though because it seems like too much overhead. Admittedly, I've hopped in a post a few times just to clean up some blatant mistakes that I figured I was safe doing.

I'm also aware that some folks have requested mentors to help with their writing. This is another potential path to take for helping authors that need help with grammar. 

**Additional context**
Here's a screenshot of where I think the "Allow edits to my articles" checkbox might go:

https://cl.ly/053b8bb7d5bd/Image%202019-01-14%20at%202.31.17%20PM.png

... but, I'm totally open to other thoughts on that!

**Comment by cassiozen** [comment]
I think the a Pull Request mechanism would be awesome. Dev.to could even add a "contributors" button close to the "Author" to list everybody who got Pull Requests accepted by the author.
