### ISSUE TITLE
#codenewbie isnt working

### ISSUE THREAD

**Issue by sforce-dev** [thepracticaldev/dev.to#154]
# _BUG_
### Current Behavior

https://dev.to/t/codenewbie doesnt load

### Expected Behavior

https://dev.to/t/codenewbie loads

### Additional Info (steps to replicate, device/browser, helpful links)
Chrome Version 63.0.3239.132 

### Screenshots

![screen shot 2018-01-30 at 6 52 45 pm](https://user-images.githubusercontent.com/5073490/35562763-6752f24c-05ef-11e8-9d01-f652c82832a8.png)

**Comment by Zhao-Andy** [comment]
Woops, sorry about that. @jessleenyc fixed it :)
