### ISSUE TITLE
Spotify Liquid Tag

### ISSUE THREAD

**Issue by kyleboe** [thepracticaldev/dev.to#1546]
Basically just the title. Would be fun to be able to embed Spotify songs/albums/playlists/artists in the editor.

syntactically my thought is something like 
```
{% spotify SPOTIFY:URI:HERE %}
```
example with real data:
```
{% spotify spotify:track:0YchKPFRbVwwO4dH5hKrRi %}
```

**Comment by Link2Twenty** [comment]
Spotify do support embedding with iframes
https://developer.spotify.com/documentation/widgets/generate/play-button/

**Comment by kyleboe** [comment]
Got stuff working here: 5828997f53f574df43c6f9e722b01c52db3f98bc
Just need to tweak the display height settings here:
https://github.com/kyleboe/dev.to/blob/5c94d491b02c09b2807eedd13eb5e29dc29e2680/app/liquid_tags/spotify_tag.rb#L4-L9

But it is 3:30am where I am. That is a problem for future me.

**Comment by kyleboe** [comment]
Punchlist for when I get back around to this:

- [ ] Update documentation on help page to reflect the added functionality
- [ ] experiment with iframe embed sizing for different types of content

**Comment by Link2Twenty** [comment]
I would question if parse_link and embed_url are both required.

**Comment by kyleboe** [comment]
@Link2Twenty I agree, they look like they are doing the inverse of the other (I went back and forth on this while writing the code).

The tricky part is the pattern of the embed url vs the link url. 

When you click on `Copy Song Link` 
![image](https://user-images.githubusercontent.com/4054771/51196016-186c5700-18a3-11e9-88a6-503a765b6d6f.png)
It gives you a url like this: 
```
https://open.spotify.com/track/adsfasdfasdfasdfasdf?si=asdfasdfasdfasdfasdf
```

However when you click on `Copy Embed Code`
![image](https://user-images.githubusercontent.com/4054771/51196194-77ca6700-18a3-11e9-8d4e-b27663a1735c.png)
You get something like this:
```
<iframe src="https://open.spotify.com/embed/track/adsfasdfasdfasdfasdfasdf" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
```
The main thing to notice is the `embed` in the url in the iframe.

I figured doing a bit of extra work on the back-end allowing users to simply paste in either the song link or song URI without thinking about it would be worth the cost of a bit of code clarity.

**Comment by maestromac** [comment]
Resolved with #1573

**Comment by flrnprz** [comment]
I'm not sure if it is a bug or a problem in my side, but I'm having trouble trying to embed URIs like this one (the URI is copied directly from Spotify sharing option): 
```
{% spotify spotify:user:spotify:playlist:37i9dQZF1E36t2Deh8frhL %}
```
<img width="774" alt="Screenshot 2019-05-07 at 12 42 41" src="https://user-images.githubusercontent.com/659650/57293659-a6c04f00-70c5-11e9-8b63-49231189d173.png">

**Comment by rhymes** [comment]
@flrnprz yeah, I think it's a bug. The regexp here is a little conservative and doesn't support playlists outright:

https://github.com/thepracticaldev/dev.to/blob/436fa2788c58ce16df5853e4b9737d85a655e966/app/liquid_tags/spotify_tag.rb#L1-L2

You should open a bug issue :)

**Comment by flrnprz** [comment]
@rhymes I think you are right. Did a few test with the old regex and it didn't select all the URI. Bug issued.

**Comment by kyleboe** [comment]
Yeah it looks like they changed their URI pattern for sharing playlists 😕 the regex will need an update.
