### ISSUE TITLE
Extra "3 min read" on search page

### ISSUE THREAD

**Issue by Link2Twenty** [thepracticaldev/dev.to#1547]
**Describe the bug**
In Edge and Firefox, a user card on the search page has "3 min read" overlapping the follow button.

![image](https://user-images.githubusercontent.com/3534427/51182971-c2f67100-18c7-11e9-87be-c101d26283e9.png)

**To Reproduce**
In Firefox or edge browse to https://dev.to/search?q=Andrew%20Bone

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser firefox, edge
- Version 64, latest

**Comment by benhalpern** [comment]
Fixed
