### ISSUE TITLE
As a user of the dev.to community, I would like a call to action on the profile of someone I follow, to facilitate beginning/continuing a conversation with them.

### ISSUE THREAD

**Issue by nickytonline** [thepracticaldev/dev.to#1567]
**Is your feature request related to a problem? Please describe.**
As a user of the dev.to community, I would like a call to action on the profile of someone I follow, to facilitate beginning/continuing a conversation with them.

**Describe the solution you'd like**
The motivation for this is quick access to starting a conversation with someone if you follow them and happen to be on their profile. As well, someone with more than a handful of followers is currently unable to find a user easily in dev connect.

To compliment this story, consider a lookup field on the dev connect page so a user could filter who they're looking for quickly. Also, as shown in the picture, I'd make the "Following" button a less prominent action than the "Chat" button. Also, I'm not sure about the wording "Chat"

**Describe alternatives you've considered**
N/A

**Additional context**

![image](https://user-images.githubusercontent.com/833231/51224559-843ad800-1914-11e9-8d76-d0f655cfcc6a.png)

**Comment by benhalpern** [comment]
This makes sense. @mariocsee let's make this part of the new connect inbox stuff.

**Comment by benhalpern** [comment]
If anyone wants to jump in on this and maybe help out with it in coordination with #1563, we can all chat about it.

Since we edge-cache, the check for whether you can chat would be similar to how we fetch to check whether you follow.

**Comment by mariocsee** [comment]
Not stale! Will make PR with small changes that makes Open Inbox public.
