### ISSUE TITLE
Head of html imports ~200 google analytics meta tags

### ISSUE THREAD

**Issue by GonzalezAnguita** [thepracticaldev/dev.to#157]
# _BUG_
### Current Behavior
The <head> on the html layout imports about 200 google analytics meta tags.

### Screenshots
![View here](https://user-images.githubusercontent.com/22966862/35829880-19e44cfa-0aa3-11e8-8da3-8641cff1dbdb.png)

**Comment by Zhao-Andy** [comment]
Hmm that's not supposed to happen. Thanks for the heads up.

**Comment by maestromac** [comment]
Hey @GonzalezAnguita ! We believe this is fixed. Let us know if otherwise!
