### ISSUE TITLE
Fix tag typing in middle of word in v2 editor

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/dev.to#1574]
If you have a list of tags in the v2 editor and you put your cursor in the middle of the list to make an edit, we currently jump you to the end of the space.

This is not intended behavior.

Here is an example of what's going on:

![](https://cl.ly/d69f3a842090/Screen%20Recording%202019-01-16%20at%2005.12%20PM.gif)

Intended behavior is that you can type in the middle of the tag list without triggering any dropdown (at least as the simplest solution)

**Comment by arku** [comment]
@benhalpern Guess this can be closed as #1614 is merged.
