### ISSUE TITLE
Child Comments Are Missing From a Discussion on an Article

### ISSUE THREAD

**Issue by michael-tharrington** [thepracticaldev/dev.to#1587]
**I don't _easily_ see the child comments on a specific article.**

When viewing the article [TypeScript: JavaScript + Types = Awesome Developer Productivity](https://dev.to/vintharas/typescript-javascript--types--awesome-developer-productivity-1048) I see that there are 7 comments in the discussion. But, after scrolling down to view the comments, I only see 2 comments.

So, I investigated and found out that there are indeed more comments on the article if you look at the "full discussion" here: [https://dev.to/vintharas/typescript-javascript--types--awesome-developer-productivity-1048/comments](https://dev.to/vintharas/typescript-javascript--types--awesome-developer-productivity-1048/comments).

The only comments that aren't displaying are child comments.

**To Reproduce**

1. Go to [https://dev.to/vintharas/typescript-javascript--types--awesome-developer-productivity-1048](https://dev.to/vintharas/typescript-javascript--types--awesome-developer-productivity-1048)
2. Look at the number on the "Discussion (?)" tab in the sidebar
3. Click on the "Discussion" tab in the sidebar or scroll down to see the discussion
4. Add `/comments` to the article's URL or go here - [https://dev.to/vintharas/typescript-javascript--types--awesome-developer-productivity-1048/comments](https://dev.to/vintharas/typescript-javascript--types--awesome-developer-productivity-1048/comments) to confirm that the discussion is longer than what was originally displayed and notice that child comments were missing from the original. 

**Expected behavior**
I expected to see the child comments displayed on the original view here - [https://dev.to/vintharas/typescript-javascript--types--awesome-developer-productivity-1048](https://dev.to/vintharas/typescript-javascript--types--awesome-developer-productivity-1048) .

**Screenshots**
https://cl.ly/fe3d79fd7ad1/download/Screen%252520Recording%2525202019-01-18%252520at%25252009.23%252520AM.gif

**Desktop (please complete the following information):**

- OS: macOS Mojave
- Browser: Chrome 
- Version: 71.0.3578.98

**Comment by dechamp** [comment]
I came here to also report issues with comments. I replied to a bunch of comments on my article and when coming back later, all were gone.

**Comment by Zhao-Andy** [comment]
Thanks for the report; we're taking a look into it now and should have a fix up soon.

**Comment by Zhao-Andy** [comment]
This should be resolved now. Feel free to reopen it again if it's reappearing.
