### ISSUE TITLE
Saving or Previewing on a post times out with a 500

### ISSUE THREAD

**Issue by jckuhl** [thepracticaldev/dev.to#1591]
Dev.To is timing out with a 500 error in the editor when I click on either Preview or Save Post.

**To Reproduce**

1. Go to dashboard
2. Click on a post that isn't finished.
3. Click either save or preview
4. Wait for timeout and 500.  Message only says something went wrong, but not explicitly what.

**Expected behavior**
Preview should take me to preview, save should allow me to save my draft.

**Desktop (please complete the following information):**

- OS: [MacOS Mojave 10.14.2
- Browser Chrome
- Version  71.0.3578.98 (64 bit)

**Additional context**
It works fine if I open a new post.

**Comment by Zhao-Andy** [comment]
Hey @jckuhl, thanks for flagging this. We're currently resolving some server issues that are most likely related to the timeout issues you're experiencing. If this continues to happen in the future, feel free to reopen this issue.
