### ISSUE TITLE
Article Analytics Only Updates On Positive Reactions

### ISSUE THREAD

**Issue by chase-stevens** [thepracticaldev/dev.to#1600]
I recently had an article do well and get some exposure, which was nice.

I looked and found the method in the [Article Analytics Fetcher](https://github.com/thepracticaldev/dev.to/blob/master/app/labor/article_analytics_fetcher.rb) job -- your data on your posts is only fetched if the current number of positive reacts on your post is higher than it was previously (line 40).

This causes issues -- since only logged in users can positively react, a lot of the positive reactions occur during the early part of an article's life. Dev.to users are more likely to see an article early on, while lurkers are more likely to read it later, but these later views can go unreported. When I went and positively reacted to my own article from two months ago, I found that its views tripled on my dashboard.

Knowing the impact of our articles is helpful and can help showcase our knowledge and talent to employes. Could there be more regular jobs to fetch analytics on our articles to ensure that the views are accurate?

**Comment by benhalpern** [comment]
Hey, this makes sense. I made a quick patch which adds some periodic fetching to complement what we already do. And we'll have it on our radar to fiddle with this a bit more.

Thanks for bringing this up.
