### ISSUE TITLE
Codepen liquid tag is not parsing default-tab correctly

### ISSUE THREAD

**Issue by kenbellows** [thepracticaldev/dev.to#1608]
**Describe the bug**
The `default-tab=` option in `{% codepen %}` liquid tags is not parsing correctly.

**To Reproduce**

1. Create a new post.
2. Add the following liquid tag:
```
{% codepen https://codepen.io/kenbellows/pen/bzbQZB default-tab=css,result %}
```
3. Switch to the post preview (or save the post, if you want).
4. On the rendered page, note that the Codepen embed shows only the Result, not the CSS tab, as specified.
5. Inspect the page and note that the iframe's `src` is set to https://codepen.io/kenbellows/embed/bzbQZB?height=600&default-tab=c&embed-version=2. The important part is `default-tab=c`.

**Expected behavior**
The `src` of the iframe should be https://codepen.io/kenbellows/embed/bzbQZB?height=600&default-tab=css,result&embed-version=2 and the Codepen embed should show the CSS and Result tabs.

**Desktop (please complete the following information):**

I think this is a server-side issue, but in case it's not:

- OS: Windows 7
- Browser: Chrome
- Version: 71.0.3578.98

**Comment by kenbellows** [comment]
**Probable Solution**
I believe the problem is at [line 25 of `codepen_tag.rb`](https://github.com/thepracticaldev/dev.to/blob/6c571e8bcd6d63c52429fd19ff8a8d96876f090f/app/liquid_tags/codepen_tag.rb#L25) in the regular expression to parse the `default-tab` option. The regex is currently:

    /(default-tab\=\w(\,\w)?)/

I believe the problem is that the `\w`s are only matching a single character rather than the whole tab name, which is why the URL ends up with `default-tab=c`, with the single `c` character in there. I confirmed that reversing the order to `default-tab=result,css` results in a URL with `default-tab=r` in it.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/1609
