### ISSUE TITLE
Can't Update or Remove Twitter username

### ISSUE THREAD

**Issue by abdulmanan7** [thepracticaldev/dev.to#161]
I click on twitter link and it auto pick the current logged in twitter account . i want to change it but unable to change it.

**Comment by Zhao-Andy** [comment]
Hey @abdulmanan7, I sent you an email about this. Please reply there :)

**Comment by maksugr** [comment]
I have the same issue. I want to change twitter account.
@Zhao-Andy can you help me too?

**Comment by lkopacz** [comment]
@Zhao-Andy Hey there, I am having the same issue. I've been getting several DMs about it and I am unable to fix.

**Comment by Zhao-Andy** [comment]
Hey @lkopacz! Just made a PR for it here: https://github.com/thepracticaldev/dev.to/pull/2386

I can ping you once it's deployed, and you can [sign out of dev.to](https://dev.to/signout_confirm) and back in with Twitter to update it. If you want to update it sooner, let me know and I can do it manually.
