### ISSUE TITLE
Delayed Job Errors

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#1621]
**Describe the bug**

We're seeing this type of error pop up while executing delayed jobs. 

`Delayed::PerformableMethod (id=#####) FAILED permanently with Delayed::DeserializationError: ActiveRecord::RecordNotFound`

Can likely be recreated by deleting an article with lots of comments, anything that triggers a bunch of callbacks.

**Comment by maestromac** [comment]
There are three main DeserializationError I've seen.

- [x] Article (resolved with https://github.com/thepracticaldev/dev.to/pull/1699)
- [ ] Reaction
- [ ] Follow

**Comment by lightalloy** [comment]
Thanks, Mac. I'll return to this ticket soon.

**Comment by lightalloy** [comment]
I have found 2 situations when these errors may occur:
- follow created and immediately destroyed
- reaction created and immediately destroyed
These operations can be easily done through the interface. So the delayed job remains after the record is destroyed and fails with an error later.
I'm currently working on fixing these issues.

If you know other situations when the errors may occur, please share.

**Comment by lightalloy** [comment]
I decided to make separate pull requests for the Follows and Reactions not to make a pr huge. Here's the first pr - https://github.com/thepracticaldev/dev.to/pull/1835

**Comment by lightalloy** [comment]
@jessleenyc @maestromac Since delayed job web interface has been enabled for admins, could you provide me more information on the errors that occur?
It could also be beneficial at this point to keep failed jobs in the database, at least temporarily (I would suggest using an env variable, like 
```ruby
Delayed::Worker.destroy_failed_jobs = ENV.fetch("DESTROY_FAILED_DELAYED_JOBS", true)`
```
But if you have information on the failed jobs without it, I would like to examine it first.

**Comment by lightalloy** [comment]
As I see, most of the described ` Delayed::DeserializationError` are solved now. However, they could still appear in some cases, which are not so common.
I'm currently researching on and fixing other DJ errors that are occuring.

**Comment by lightalloy** [comment]
I'm closing this issue because the `DeserializationError`s are fixed (at least most of them).
I'll open other issues for other kinds of DJ errors if they appear.
