### ISSUE TITLE
Add email search functionality to /internal

### ISSUE THREAD

**Issue by pkfrank** [thepracticaldev/dev.to#1622]
**Is your feature request related to a problem? Please describe.**
As an admin, I want to be able to easily find matching DEV users by searching for an email.  This is the first step in a variety of support-related tasks.

**Describe the solution you'd like**
A search page somewhere in `/internal` where I can input an email and get any matching DEV accounts associated with that email.

**Comment by jessleenyc** [comment]
Let's use pg-search for internal (same thing administrate uses).

**Comment by benhalpern** [comment]
@jessleenyc 

So we probably don't need full-on "search" functionality if we typically know the email and then we're looking to find by that specific email.

An input that takes an email and then `find_by_email` on the server should be good enough.

The one thing to take note of here is that the form that takes this input should be a `GET` request, as opposed to the default `POST`, meaning when it's submitted, you'll see the parameters in the address bar.

**Comment by pkfrank** [comment]
@benhalpern as noted today, it might also be helpful to give admins the ability to search for GitHub and Twitter usernames in the same area.  Searching by those parameters (email, Twitter, GitHub) is helpful in identifying duplicate accounts.
