### ISSUE TITLE
page not loading error

### ISSUE THREAD

**Issue by newtstan** [thepracticaldev/dev.to#1629]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by Zhao-Andy** [comment]
Hey there, assuming you meant you were running into our server issues we had. We're back on now. Thanks for the issue and let us know if you run into this again!
