### ISSUE TITLE
500 Server Error when hitting Save Post

### ISSUE THREAD

**Issue by httpJunkie** [thepracticaldev/dev.to#1630]
Description: 
Getting a 500 Server Error when hitting Save Post

**To Reproduce**

1. Go to 'Write Article'
2. Write an Article
3. Click on SAVE POST

You will get a 500 error

![image](https://user-images.githubusercontent.com/4899480/51607582-ecb42700-1ec9-11e9-81de-30ac8d71d5a7.png)

- Windows 10

**Comment by mstruve** [comment]
I'm guessing my issues are related, I have been seeing the same 500 Error trying to load the dashboard and notifications. I also ran into this interesting error trying to save one of my articles
![screen shot 2019-01-23 at 8 03 08 am](https://user-images.githubusercontent.com/1813380/51608571-e7fd6c00-1ee5-11e9-9405-974a166c7125.png)

Please let me know if there is anything else you guys need!!! Happy to help in whatever way I can!

**Comment by Zhao-Andy** [comment]
Thanks for the heads up! We've resolved the server issues now. Let us know if you run into this again. :)

**Comment by antsanchez** [comment]
This is happening to me right now, exactly as described here:

> Description:
> Getting a 500 Server Error when hitting Save Post
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to 'Write Article'
> 2. Write an Article
> 3. Click on SAVE POST
> 
> You will get a 500 error
> 
> ![image](https://user-images.githubusercontent.com/4899480/51607582-ecb42700-1ec9-11e9-81de-30ac8d71d5a7.png)
> 
> * Windows 10

**Comment by Puritanic** [comment]
@Zhao-Andy I'm getting same error when I try to submit comment. Comment is submitted, but I have to refresh the page to be able to see it.

Description:
Getting a 500 Server Error when hitting Submit on a comment

Browser: Firefox Dev 68.0b6 (

**To Reproduce**
Steps to reproduce the behavior:

    Go to some post
    Write a comment
    Click on Submit

You will get a 500 error in network response:

```
Request URL:https://dev.to/comments
Request method:POST
Remote address:151.101.66.217:443
Status code:
500
```
<img width="548" alt="Screen Shot 2019-06-23 at 8 30 47 PM" src="https://user-images.githubusercontent.com/25148427/59980408-ccfa6980-95f5-11e9-9f8e-321323f26bea.png">

**Comment by maestromac** [comment]
This should be resolved now @Puritanic
