### ISSUE TITLE
Add views linter

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#1631]
**Is your feature request related to a problem? Please describe.**
I've noticed style problems in the templates files, like improper indentation, old hash syntax, trailing line/spaces, etc.

**Describe the solution you'd like**
Use a tool like [erb_lint](https://github.com/Shopify/erb-lint), add the corresponding script to the `lint-staged` config, so that it would run before committing like the other linters.

**Comment by aspittel** [comment]
Thanks for submitting this issue @lightalloy, that is a great idea. Will discuss further with the rest of the team!

**Comment by benhalpern** [comment]
This makes sense. @lightalloy want to get it set up?

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/1657
