### ISSUE TITLE
Saving post causes 500

### ISSUE THREAD

**Issue by spittet** [thepracticaldev/dev.to#1639]
**Describe the bug**
Hi, I tried posting a new article with my account today and it produced a 500.

Right before attempting to post I updated the organization details and change the org username from _squadlytics_ to _tability_. I've tried a few things without success:
- posting under the organization
- posting without an organization
- changing the org username back to _squadlytics_
- I tried saving a sample post with the bare minimum (as opposed to my original article).
- I tried editing old posts

None of these things worked and I'm unable to create new articles.

**To Reproduce**

1. Go to dev.to
2. Create a new post
3. Write content
4. Hit save

**Expected behavior**
The post is saved.

**Screenshots**
![image](https://user-images.githubusercontent.com/345089/51643761-d12c4780-1fc1-11e9-9d9b-1564545a8181.png)

**Desktop (please complete the following information):**

- OS: OSX 10.14.1
- Browser:  Chrome 71, Safari 12

**Comment by Zhao-Andy** [comment]
Hey @spittet, thanks for raising this. We'll take a look into it now and get back to you soon.

**Comment by CodeMouse92** [comment]
Confirmed from an Ubuntu 18.04 system, from both Firefox and Brave. :(

**Comment by Zhao-Andy** [comment]
@spittet  @CodeMouse92 Still investigating this but seems like the v2 editor works if you want to give that go. :)

**Comment by CodeMouse92** [comment]
@Zhao-Andy Unfortunately, even though I changed that, editor v2 only appears with new posts, not with editing a post.

**Comment by benhalpern** [comment]
So sorry about this bug folks. It has been fixed today.

**Comment by spittet** [comment]
The fast turnaround is impressive!

**Comment by rginfotechjpr** [comment]
I have tried both versions, but still the same 500 error.
