### ISSUE TITLE
Milestone notifications

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/dev.to#1647]
* Your post just reached 100 reactions!
* Your post just reached 1,000 views!
* Etc.

As a user I'd like to be notified at certain milestones. In terms of when to notify, I think it would be fun to do it in binary escalation.

Maybe start notifying people at 64 reactions and then 128, 256, 512, 1,024 etc.

For view counts, maybe start at 1,024 and work up from there.

If the odd numbers are too weird, I still think doubling makes sense in terms of frequency. 1000, 2000, 4000, 8000, 16000 etc.

This could be implemented as a script that gets run after reactions and/or page view update etc. and awards a milestone if the relevant one had rewards the relevant notification.

This would be a complement to badges, which you can receive once for certain achievements. But this would exist only as a notification.

**Comment by geoffdavis92** [comment]
I like this. In lieu of an analytics suite built into dev.to, this would be a great way to notify people of certain stats.

**Comment by Link2Twenty** [comment]
@geoffdavis92 do you know you can see post reactions and view count in the dashboard?

**Comment by BogDAAAMN** [comment]
@Zhao-Andy is that something that you are working on? I would love to give it a try

**Comment by Zhao-Andy** [comment]
Hey @BogDAAAMN, I'll be working on this soon, but you might be interested in this notification related issue: https://github.com/thepracticaldev/dev.to/issues/503 (Notify author if post/comment is embedded in another dev.to post)
