### ISSUE TITLE
 Grammer error on page: "10 Best Sublime Text Themes in 2018"

### ISSUE THREAD

**Issue by learning-more** [thepracticaldev/dev.to#1648]

**Comment by learning-more** [comment]
[This page](https://dev.to/kazup/10-best-sublime-text-themes-in-2018-53j5) seems to be missing a word: 

> This post is curated by IssueHunt that a issue-based bounty platform for open-source projects.

I assume the sentence should be:

> This post is curated by IssueHunt that **is** a issue-based bounty platform for open-source projects.

**Comment by Link2Twenty** [comment]
That is a user's post so they'll have to make any changes.
The best way to get their attention is to add a comment to the post.

**Comment by jessleenyc** [comment]
Yep, what @Link2Twenty said it correct. Thanks for flagging though, closing this issue.
