### ISSUE TITLE
Waiting for the source code

### ISSUE THREAD

**Issue by aissa-bouguern** [thepracticaldev/dev.to#165]
Hi,
We're waiting for dev.to source code,
When do you think it will be available ?

Thank you

**Comment by Zhao-Andy** [comment]
Hey @aissa-bouguern, glad you're interested. We're still ramping up to open source the project to the public. As our plan to do so, we'd like to invite a few people to look over the codebase before the full release. Would you like to be considered for our pre-release?

**Comment by aissa-bouguern** [comment]
Oh Yess @Zhao-Andy, i'm interested and i can't wait to see the source code behind this awesome masterpiece. I'd like to see and learn how did you implement the *server side rendering* feature.
Thank you so much for your fast feedback :)

**Comment by kenju** [comment]
Hi @Zhao-Andy, I am an server-sider engineer from Tokyo. Would you let me join the pre-release members, too? I am very interested in the server-side implementation, and it might have hints for what I have been struggle for for a while (kinda how to optimize ad-serving performances). Thanks ! :)

**Comment by DevsPen** [comment]
Yeah me too!

**Comment by webmaven** [comment]
@Zhao-Andy, I am also interested in the dev.to source, but that interest depends partly on what languages and frameworks the site is implemented in.

Python/Flask? Ruby/Rails? PHP? Nodejs? :geek:

Inquiring minds want to know! :curious:

**Comment by Zhao-Andy** [comment]
Hey y'all! @aissa-bouguern @kenju @DisnutBot @webmaven Sorry for the late reply. We'll be officially open sourcing on August 8th!

See Ben, Peter, and Jess's post for more details: https://dev.to/ben/the-devto-codebase-will-go-open-source-on-august-8-2kia

If you'd like to early access before we open source officially, please fill out this form:
https://thepracticaldev.typeform.com/to/HkjWky

@webmaven We ran mostly on Ruby and Rails and a bit of Preact sprinkled in on the front end. See Ben's post for more details: https://dev.to/ben/the-devto-tech-stack
