### ISSUE TITLE
Share on whatsapp for posts

### ISSUE THREAD

**Issue by itsjzt** [thepracticaldev/dev.to#1654]
Currently we can share posts on Twitter, Reddit, linkedin, Facebook.

Can we have a share on WhatsApp option, WhatsApp have billion users and there will be a lot of people sharing dev.to posts on WhatsApp.

I would love to make that feature myself.

**Comment by Link2Twenty** [comment]
Reference #1524

**Comment by abraham** [comment]
It seems like this would only work on mobile devices so #1524 would probably be a better solution.

https://stackoverflow.com/questions/21935149/sharing-link-on-whatsapp-from-mobile-website-not-application-for-android

**Comment by itsjzt** [comment]
@abraham #1524 looks like a better solution

**Comment by maestromac** [comment]
Resolved with #1524
