### ISSUE TITLE
New post default template can be improved 

### ISSUE THREAD

**Issue by pranayairan** [thepracticaldev/dev.to#1655]
**Is your feature request related to a problem? Please describe.**
I recently wanted to add a new post on dev.to, I went to https://dev.to/new and read the help section. I started with the title, tags etc. And I thought the description is the place to add details about my post. I added all details there. But when I clicked on Preview, I was able to see only the title of my post. 

I was not able to figure out after trying multiple times on what needs to be done. I reached out to Practical Dev on twitter and after chatting with him, It clicked my that I might need to add those details below the --- line and top section is just metadata and description is not the place to put all your content. 

**Describe the solution you'd like**
I can think of 2 things, that can help. 

1. Put a sample example in the help, with a hello world text and everything that is possible.
2. Change the default template of the new post to include hello world text below the --- line to let people know that content goes there. 

**Describe alternatives you've considered**
Nothing else, either of the above 2 options would work. 

**Additional context**
Example template : 
```
---
title: 
published: false
description: 
tags: 
---
Content goes here !! 

```

**Comment by Link2Twenty** [comment]
We're slowly moving over to a whole new editor. Here's the announcement post about it.
https://dev.to/devteam/changelog-we-have-a-new-beta-editor-you-can-try-4hl9

**Comment by pranayairan** [comment]
that looks nice thanks. Since we will be keeping the old editor, it might be good if we can change it a little bit.

**Comment by jessleenyc** [comment]
I think we could update the publishing guide to have an image of the editor (and where everything goes) for clarity.
