### ISSUE TITLE
Broken link to scholarship page

### ISSUE THREAD

**Issue by achasveachas** [thepracticaldev/dev.to#167]
# _BUG_
### Current Behavior
The link to the scholarship page on https://dev.to/events points to https://dev.to/p/scholarship which gives a 404 Page Not Found (sick animation btw)

### Expected Behavior
It should be pointing to the correct page at https://dev.to/p/scholarships

### Additional Info (steps to replicate, device/browser, helpful links)
Go to https://dev.to/events and click on the link in "please apply for a scholarship" in the last paragraph.

In lieu of a bug bounty, I would really appreciate it if you approved the scholarship application I was able to submit in spite of the broken link... 😜

**Comment by achasveachas** [comment]
Just noticed that the link to the live lectures is broken too. 

The text of the link says `dev.to/live` but it actually links to the dev.to homepage.

**Comment by Zhao-Andy** [comment]
Thanks for the heads up. All links fixed :)

**Comment by achasveachas** [comment]
@Zhao-Andy 
It looks like only the links to existing live events were fixed, but whatever is generating those links is still generating broken links. 
The link to the most recently added (the AMA with Tracy Lee) points to the homepage.
