### ISSUE TITLE
Add tag moderators to sidebar

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#1677]
**Describe the solution you'd like**
It would be nice for people to know who the tag moderator(s) of each tag is. We can probably find a place for this on one of the tag sidebars.

**Comment by pkfrank** [comment]
I think the left-hand sidebar makes most sense, it's where other information about the tag lives.  In terms of styling, I imagine we can follow what we've done for "Users to follow" on the tag page, or "Meet the Team" on organization pages.

**Comment by seanmfox** [comment]
@jessleenyc I'm up for working on this feature.  Any particular preference whether to go with "Users to follow" or "Meet the team"?  I'm thinking the latter may be a better route since the former style is already on the page for another set of content.

**Comment by seanmfox** [comment]
Sounds good!  Making the pull request now.

**Comment by maestromac** [comment]
resolved with https://github.com/thepracticaldev/dev.to/pull/1739
