### ISSUE TITLE
Post with multiple embedded gists have order mixed up

### ISSUE THREAD

**Issue by rasmusvhansen** [thepracticaldev/dev.to#1679]
**Describe the bug**
On my post https://dev.to/rasmusvhansen/rxjs-transducer---harness-the-power-of-rxjs-operators-1ai8
I have 5 gists embedded in the page. I noticed that the order of the gists is not fixed. On some reloads, the first and e.g third gists are swapped. 

Other users have also noticed this (see comments on post)

**To Reproduce**

Note: It is kind of hard to reproduce. I saw it twice but cannot consistently reproduce.

1. Go to https://dev.to/rasmusvhansen/rxjs-transducer---harness-the-power-of-rxjs-operators-1ai8
2. Check order of gists
3. Reload and check if order is the same
4. Repeat step 3 until error occurs

**Expected behavior**
Order of gists should be as specified in markdown, not random.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 71

**Smartphone (please complete the following information):**

- Device: iPhone 6.1
- OS: iOS 12.1
- Browser Safari

**Comment by qm3ster** [comment]
That's wild.
Not once did I get them in the correct order, even on a clean browser.

And you are saying you didn't mix them up first and then edit it changing only the order?
So it can't be a caching issue?

**Comment by rasmusvhansen** [comment]
Yes. I Saw they were out of order and then I verified the urls were correct but I did not update them

**Comment by benhalpern** [comment]
Hmmm I have not been able to reproduce this.

**Comment by qm3ster** [comment]
@benhalpern what is the top Gist for you? For me it's **arrayMethods.ts**.

**Comment by lachlan-eagling** [comment]
This, and another potentially related issue where the two gists in my post randomly both load the same gist. https://dev.to/lachlaneagling/a-peek-inside-python-the-how-what-and-why-of-bytecode-go1.

Refreshing the page a few times seems to trigger the problem, tested on multiple devices and browsers.

**Comment by qm3ster** [comment]
@jessleenyc you tagged this with `editor`, but editing the post shows the correct order again.
Only the rendered post is mixed up.

**Comment by maestromac** [comment]
@qm3ster for the time being we considered markdown/rendering errors as editor issues.

**Comment by cardoso** [comment]
I'm reproducing this in this blog post: https://dev.to/cardoso/how-to-build-a-twitch-clone-game-live-streaming-app-for-ios-5f0p

Even got a comment from a reader about it.
