### ISSUE TITLE
Improve accessibility of code snippets

### ISSUE THREAD

**Issue by jahirfiquitiva** [thepracticaldev/dev.to#1685]
**Describe the bug**
I find the code snippets slightly hard to read, and I, afaik, am not color-blind. I don't imagine how hard it could be for people who actually are.

**To Reproduce**
Basically check any code snippet

**Expected behavior**
Using colors that have a good contrast ratio.

**Screenshots**

**Code snippet**
![captura de pantalla 2019-01-29 a la s 9 39 41 a m](https://user-images.githubusercontent.com/10360816/51952849-f24cc800-2407-11e9-8abf-4b8afee6bb81.png)

![captura de pantalla 2019-01-29 a la s 9 42 28 a m](https://user-images.githubusercontent.com/10360816/51952845-f1b43180-2407-11e9-99b1-c8cc9e5cc290.png)
![captura de pantalla 2019-01-29 a la s 9 41 50 a m](https://user-images.githubusercontent.com/10360816/51952846-f1b43180-2407-11e9-99f9-2b76f65d2331.png)
![captura de pantalla 2019-01-29 a la s 9 41 27 a m](https://user-images.githubusercontent.com/10360816/51952848-f1b43180-2407-11e9-864b-f98f53da1e90.png)

**Desktop (please complete the following information):**

- OS: MacOS Mojave
- Browser: Chrome
- Version: 72.0.3626.81

**Comment by aspittel** [comment]
Thanks for pointing this out @jahirfiquitiva! Will discuss further with the team.

**Comment by jahirfiquitiva** [comment]
@jessleenyc it's not only about text size. And most importantly about colors

**Comment by jessleenyc** [comment]
@jahirfiquitiva yep, sorry I wasn't clear. I meant that this is approved for anyone who wants to work on the contrast and the text size. But when it comes to text size, we probably won't want to make it much bigger on mobile since that'll present another set of difficulties.

**Comment by IanKnighton** [comment]
I would like to take this on if no one else has.

**Comment by maestromac** [comment]
Give it a whirl @IanKnighton !

**Comment by IanKnighton** [comment]
Great!

**Comment by Math3v** [comment]
@maestromac I've tried to address this, please see my PR. 🙏
