### ISSUE TITLE
Husky Config Needs to Be Upgraded

### ISSUE THREAD

**Issue by nickytonline** [thepracticaldev/dev.to#1687]
**Is your feature request related to a problem? Please describe.**
Our pre-commit hooks will no longer work in the near future unless we upgrade the config for [Husky](https://github.com/typicode/husky).

**Describe the solution you'd like**
Simply update the config to the new format.

**Additional context**
I like turtles 🐢🐢🐢🐢

**Comment by maestromac** [comment]
Thanks for this nick!
