### ISSUE TITLE
Remove mentorship relationships when deleting user

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#1696]
**Describe the bug**
When a user is deleted, their mentor relationship needs to be deleted as well or it could cause issues w/ viewing info on whoever they're matched up with.

**Comment by jpac-run** [comment]
@jessleenyc is this still an issue? I would like to try adding this feature 👍

**Comment by jessleenyc** [comment]
@jpac-run cool, go for it -- `manage_activity_and_roles.rb` will prob be the best place to do it. You'll want to create a mentor relationship and make sure you're a super admin. lmk if you have any quqestions!

**Comment by jessleenyc** [comment]
Closing this since we no longer support the mentorship program.
