### ISSUE TITLE
Post itself appears as related post on the 4-post-related area

### ISSUE THREAD

**Issue by GiorgosK** [thepracticaldev/dev.to#1697]
**Describe the bug**
Its not a bug per se but I just noticed on [this post](https://dev.to/wolksoftware/why-typescript-is-a-better-option-than-javascript-when-it-comes-to-functional-programming-3mp0)  that the same post appears as a related post for itself.

**To Reproduce**
Try visiting the specific article using the URL above. Perhaps its not reproducible as the next time I visited the URL from a different browser the post was in a different position of the 4-post area.  

**Expected behavior**
Perhaps the space would be better used for actual related post

**Screenshots**
![4-post-area](https://user-images.githubusercontent.com/520704/52039345-f0385580-253c-11e9-8a4f-080c7883bfeb.png)

**Comment by aspittel** [comment]
Thanks for flagging this @GiorgosK!

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/1773
