### ISSUE TITLE
Comment takes 'undefined' after submit a comment

### ISSUE THREAD

**Issue by HZooly** [thepracticaldev/dev.to#1698]
**Describe the bug**
Just after submitting a comment on an post, text area is not blank, but takes `undefined` as text value.

**To Reproduce**

1. Go to a post
2. Submit a comment
3. Check comment textarea

**Expected behavior**
Expected to get a blank textarea with placeholder.

**Screenshots**
![image](https://user-images.githubusercontent.com/7328625/52040759-ae0d1500-2538-11e9-82ee-3768fa7f5bcf.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Brave 0.58.21 (Chromium 71)
- Version: Latest online at this date

**Comment by aligoren** [comment]
I faced the same issue with CTRL + Enter shortcut.

I'm not quite sure, but it could be a bug related to below function. Maybe `newComment` never returns `comment_template` property.



[https://github.com/thepracticaldev/dev.to/blob/d7665fcc3f7342e1f7de172397227a353b619044/app/assets/javascripts/initializers/initializeCommentsPage.js.erb#L220-L231](https://github.com/thepracticaldev/dev.to/blob/d7665fcc3f7342e1f7de172397227a353b619044/app/assets/javascripts/initializers/initializeCommentsPage.js.erb#L220-L231)

**Comment by rhymes** [comment]
@aligoren yeah I think is line 225, `comment_template` is a new feature and if that is undefined you would get `undefined` as the text instead of an empty string

**Comment by aligoren** [comment]
@rhymes So, should we check for undefined? For example;

```js
var newComment = {
}

var commentTemplate = newComment.comment_template || ''
```

In the above example, `newComment` don't have `comment_template`. Even doesn't have, will not return `undefined`.

**Comment by rhymes** [comment]
yeah, I'm submitting a fix exactly like that :D

**Comment by aligoren** [comment]
Do it! I can't do this now because of I'm at work. Thx.

**Comment by aspittel** [comment]
Thank you so much for catching this @HZooly, @aligoren, and @rhymes!

**Comment by HZooly** [comment]
Thanks you for fixing this so fast! 🚀
