### ISSUE TITLE
Can't reply to comment.

### ISSUE THREAD

**Issue by amueller** [thepracticaldev/dev.to#17]
I'm trying to reply on a message with a link that I got via email notification:
https://dev.to/yelluw/10-things-i-do-to-keep-open-source-projects-healthy-and-stress-free/comments/2ho#/yelluw/10-things-i-do-to-keep-open-source-projects-healthy-and-stress-free/comments/new/2ho

I click "reply" but nothing happens.
I tried to go to the article, but if I click reply there, nothing happens either.

**Comment by ziaa** [comment]
I have same problem on *Firefox* 51.0.1 (x64), but everything works fine on Chromium 55.0.2883 (x64). Seems that it's a **browser-related** issue.

**Comment by maestromac** [comment]
Hey guys, I'm pretty sure this is fixed so I'm closing it. Let me know otherwise!
