### ISSUE TITLE
Quotes (") had to be escaped with (\) for article to publish successfully

### ISSUE THREAD

**Issue by Nektro** [thepracticaldev/dev.to#170]

**Comment by Zhao-Andy** [comment]
Thanks for the heads up. We'll take a look into the bug.

**Comment by Nektro** [comment]
I forgot to note. This issue only occurred when quotes were used in header liquid tags (particularly in the title where I first noticed the issue)

**Comment by maestromac** [comment]
We fixed this. Let us know if otherwise!

By the way, the top portion surrounded by `---` is Front Matter not liquid tag 😉. Check it out [here](https://jekyllrb.com/docs/frontmatter/).
