### ISSUE TITLE
Additional tips for deployment to Heroku: invalid credentials

### ISSUE THREAD

**Issue by miguelcarvajal** [thepracticaldev/dev.to#1703]
**This is a small problem**. I am working with this wonderful code as a learning experience. I have already done most of the work setting up a "temporary and only for playing" instance of Dev in Heroku. But I'm frustrated because I can not register new users in with the deployed app. 

The Twitter and Github callbacks are correctly set, the app protocol (`https`) and the app domain (`myapp.herokuapp.com`) too: actually, it can bee seen that there is a  connection between myapp and their servers but, after a few seconds, `myapp.herokuapp.com` site raise a `Invalid Credentials` error. 

This app works perfectly in my local environment. It registers new users with both OmniAuth Twitter and Github to the development database, even to the Heroku database connected remotely. **Also the same users already registered can access to the app hosted in Heroku** (`https://myapp.herokuapp.com/`). SO the problem is with registering _new users_, no with _returning ones_.

Error info authenticating a new user with Github:

`omniauth: (github) Authentication failure! invalid_credentials: OAuth2::Error, bad_verification_code: The code passed is incorrect or expired.`

Error info authenticating a new user with Twitter:

`
2019-01-31T18:51:13.245126+00:00 app[web.1]: I, [2019-01-31T18:51:13.245038 #20]  INFO -- omniauth: (twitter) Callback phase initiated.
2019-01-31T18:51:13.447852+00:00 app[web.1]: E, [2019-01-31T18:51:13.447748 #20] ERROR -- omniauth: (twitter) Authentication failure! invalid_credentials: OAuth::Unauthorized, 401 Authorization Required
`

Please, could you guys help me out a little bit? I would love to solve this issue. 

My dream is that one day, maybe, customizing the design and the code, I could create a "dev.to sort" of community for journalists in Spain/Latinoamerica. 

<img width="1189" alt="captura de pantalla 2019-01-31 a las 21 25 29" src="https://user-images.githubusercontent.com/1652249/52083083-ca439d00-259e-11e9-9081-ccfe827c523c.png">

**Comment by benhalpern** [comment]
Do you have all the environment variables and GitHub app set up properly? Not sure that's the issue but it's a starting question.

One thing of note beside the point, but since you're standing up your own deployed version (congrats!) feel _more than welcome_ to modify anything that is hardcoded for dev.to and make PRs around that. Stuff like URLs which hardcode dev.to and the main site logo, etc. Anything that can be extracted to env variables is the direction we want to go in to make it feasible to stand up real alt versions.

Anyway, let us know if the heroku config env variables are set as they should. Could possibly also be related to this outstanding issue: https://github.com/thepracticaldev/dev.to/issues/1223

**Comment by miguelcarvajal** [comment]
Thanks a lot, Ben. The environment variables are properly set, and they are the same both in development and in production. I don't know if any of the `default` and `optional` env vars of the others providers are blocking the Oauth process for new users in production. 

Once I solve this `Invalid Credentials` issue that frustrates me, I will definitely work on clearing those few instances of dev.to in the source code to leave a more clean version to the community. I could also write some additional tips for deployment based on my experience working with the code.

**Comment by Zhao-Andy** [comment]
Hey @miguelcarvajal, I've never seen the GitHub error so I can't offer much advice on that. For the Twitter error, you'll want to make sure your Twitter OAuth app has additional callback URLs for your Heroku app's domain. For example, the additional callback should be something like:
```
https://myapp.herokuapp.com/users/auth/twitter/callback
```

You should be able to have multiple callback URLs, so you can keep your localhost URL.

**Comment by miguelcarvajal** [comment]
Thanks, @Zhao-Andy! Yes, I have it all set. The stranger thing is that the same callback URLs is working correctly when I _sign in_ with already registered users. The only thing that it doesn't work is creating new users.

So I will keep digging til I find the solution.

**Comment by miguelcarvajal** [comment]
Well, problem solved! Since Oauth in dev.to is configured to fetch profiles picture from new users when registering, the developer has to configure the AWS `environment vars` to his/her region. I was working with `us-west-1`, I've changed to `eu-west-1` and finally it is working.

This is the log error (by the way, thanks to Timber.io):

`Log in error: Expected(200) <=> Actual(400 Bad Request) excon.error.response :body => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'</Message><Region>eu-west-1</Region>`

Developers working with this code in production must set correctly a AWS instance with Access Key. 
There is more work to do in working with your own dev.to instance with images, since everything in production is linked to S3 bucket of _practicaldev_. But, hopefully, I found the solution.

So, this is not _Optional_ in production, like Algolia, Twitter, Github, Host, Protocol, Cloudinary env vars:

```
# AWS for images storages
AWS_ID: "..."
AWS_SECRET: "...."
AWS_BUCKET_NAME: "..."

# AWS SDK
AWS_DEFAULT_REGION: "..."
AWS_SDK_KEY: "..."
AWS_SDK_SECRET: "..."

``` 
Thanks guys!

**Comment by Zhao-Andy** [comment]
Awesome! Glad you got it figured out. Do you mind sharing how you configured your logs to output that error message? In #1223, we've been trying to log sign in errors but the errors we log are not as descriptive as yours.

**Comment by miguelcarvajal** [comment]
Sure, @Zhao-Andy! 

1. Go to _Timber.io_
2. Open _sources_ window
3. Click _add source_
4. Pick Heroku (I found it typing in the search bar)
5. Add source name
6. Set _environment_ to _production_
7. Configure Installation and, important: add that API Key to your source code in _config/production.rb_:
```
  # Timber.io logger
  log_device = Timber::LogDevices::HTTP.new('XXXXXXXXXX')
  logger = Timber::Logger.new(log_device)
  logger.level = config.log_level
  config.logger = ActiveSupport::TaggedLogging.new(logger)

```
Before that change, I had a wrong general API Key from Timber.

Once pushed those changes, I connected with a wonderful log console in Timber.io.

**Comment by Zhao-Andy** [comment]
Ah gotcha, that looks like the same configuration we have. I'm guessing you didn't add additional `logger.error`s anywhere to log the sign in failures right?

**Comment by miguelcarvajal** [comment]
Nop. This is the only different thing I did:

```
In your shell execute the following command to add the Timber log drain:

 heroku drains:add https://{{my-timber-api-key}}@logs.timber.io/frames -a myapp

```

**Comment by akhil-naidu** [comment]
> Well, problem solved! Since Oauth in dev.to is configured to fetch profiles picture from new users when registering, the developer has to configure the AWS `environment vars` to his/her region. I was working with `us-west-1`, I've changed to `eu-west-1` and finally it is working.
> 
> This is the log error (by the way, thanks to Timber.io):
> 
> `Log in error: Expected(200) <=> Actual(400 Bad Request) excon.error.response :body => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'</Message><Region>eu-west-1</Region>`
> 
> Developers working with this code in production must set correctly a AWS instance with Access Key.
> There is more work to do in working with your own dev.to instance with images, since everything in production is linked to S3 bucket of _practicaldev_. But, hopefully, I found the solution.
> 
> So, this is not _Optional_ in production, like Algolia, Twitter, Github, Host, Protocol, Cloudinary env vars:
> 
> ```
> # AWS for images storages
> AWS_ID: "..."
> AWS_SECRET: "...."
> AWS_BUCKET_NAME: "..."
> 
> # AWS SDK
> AWS_DEFAULT_REGION: "..."
> AWS_SDK_KEY: "..."
> AWS_SDK_SECRET: "..."
> ```
> 
> Thanks guys!

Hey, in a way do you mean, in order to host through heroku, I need to fill all the env variables and choose eu zone as preferred zone?
