### ISSUE TITLE
Post Preview not working, throws error

### ISSUE THREAD

**Issue by dechamp** [thepracticaldev/dev.to#1705]
**Describe the bug**
When creating a post or editing a post, click the 'Preview' button is not working.

**To Reproduce**

1. Create or edit a Post
2. Click on "Preview" 

**Expected behavior**
Should show the preview of the Markdown, but it does nothing. If you look in console it has an error.

**Screenshots**
console error > https://pasteboard.co/HZ3g4S3.png

**Desktop (please complete the following information):**
MacBook Pro, chrome Version 72.0.3626.81

**Additional context**
It seem to happen after I created an organization but may or may not be part of the issue.

**Comment by Zhao-Andy** [comment]
@dechamp I think this might be an issue with your organization not having either a background or text color. As a short term solution, do you mind updating that to see if that's the issue?

**Comment by dechamp** [comment]
I'll give that a try right now

**Comment by dechamp** [comment]
Yup that was it! @Zhao-Andy. Thank you, it was the background color

**Comment by Zhao-Andy** [comment]
Great!

Leaving a note for whoever works on this: we'll want to have proper error handling for this or enforce all organizations to have background and text colors.

**Comment by seanmfox** [comment]
@Zhao-Andy Let me know if this bug is ready to be worked on and I'll dive into it. :)  Thoughts on whether to error handle or require?  I'm thinking that it may be better to go with the latter and have the template load with some defaults for the background and text color fields.

**Comment by jessleenyc** [comment]
@seanmfox Go for it! Adding default colors make sense.

**Comment by maestromac** [comment]
@seanmfox black & white would be a good default for the time being.

**Comment by seanmfox** [comment]
Great!  Submitting the pull request now.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/1764
