### ISSUE TITLE
Dev.to better site ranking (SEO)?

### ISSUE THREAD

**Issue by Aracki** [thepracticaldev/dev.to#1707]
I notice dev.to is gaining more and more popularity for devs, but Medium articles still has a lot better rankings on search engines.  

What can be done in order to boost site ranking of dev.to?

**Comment by benhalpern** [comment]
Good question!

I think our SEO is _pretty good_ but will need to keep getting better and any contributions in this regard are super appreciated.

## Offsite SEO

Offsite SEO mostly means people linking to us. This seems to be climbing nicely in the right ways.
![screen shot 2019-02-01 at 1 15 49 pm](https://user-images.githubusercontent.com/3102842/52138459-92cb0400-2623-11e9-8874-e4f7ab50e591.png)

But it could be much better. I don't think we've ever had a good concerted effort in this way and there is lots the community can do to help in this regard.

If we can encourage more folks to link back to us on their personal sites, it will help everyone. One way they could do it is by adding the social icon

https://dev.to/p/badges

Improving the design of that page and encouraging folks to add it to their site more would help a lot here. Any company on the platform adding the badge would also be great.

One other thing:

Open source projects linking to the appropriate tag page for their project would be awesome. We have representation on some big one (reactjs.org has a DEV link in the footer).

Pull requests like this one are the way to make this happen:

https://github.com/nodejs/nodejs.org/pull/1739

We would be incredibly thankful for any PRs that get dev.to links onto the websites of big projects! It's also a pretty cool way to officially become a contributor to these projects.

## Onsite SEO

This is a matter of better internal linking to help search engines find dev.to content within the site. Smarter suggestions, etc. We always do things to try to improve the site in this way, I think we are on the right track and have some decent ideas to keep improving this, but if anyone spots any ways we are not doing a good job with stuff like rich snippet markup or doing anything less-than-ideally, an issue or PR is much appreciated!

Great discussion to be having.
