### ISSUE TITLE
Can't access the footer on the landing page

### ISSUE THREAD

**Issue by sfiquet** [thepracticaldev/dev.to#171]
# _TASK or Feature_
### Request or User Story
Hi, I just found your site through a link to an article. Went to the landing page and looked for an About link. Turns out it's in the footer at the bottom of the page but you can't access the footer because when you scroll down, new articles are constantly added.

### Definition of Done
User can access the links in the footer in spite of the infinite page (or the links are moved somewhere at the top).

### Notes
Maybe make the footer stick to the bottom of the viewport?

**Comment by Zhao-Andy** [comment]
Thanks for the feedback -- agreed it's pretty confusing to have a footer on an infinite scrolling home page.

As a short term solution, the footer links are also available on the left sidebar and in the navbar menu, where your profile image is.
