### ISSUE TITLE
Long text doesn't wrap on left hand sidebar descriptions

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#1710]
**Describe the bug**
Long lines are getting cut off on the left side bar for user profiles. 

![](https://cl.ly/bacf70242274/download/Image%202019-02-01%20at%206.13.27%20PM.png)

**Comment by aligoren** [comment]
@jessleenyc I think `widget-body` class should be like this;

```css
margin-top: 9px;
font-size: 0.9em;
line-height: 1.2em;
padding-bottom: 5px;
overflow-wrap: break-word;
```

I'm not sure what's difference between `overflow-wrap: break-word` and `word-wrap: break-word`.

Anyway, this should work as expected.
