### ISSUE TITLE
Article reaction data not consistent between feed and article

### ISSUE THREAD

**Issue by meloncatty** [thepracticaldev/dev.to#1719]
**Describe the bug**
Heart count is different on personal feed than what is displayed on the actual article page.

**To Reproduce**

1. Go to dev.to
2. Click on an article (and keep track of number of ❤'s for the clicked article)
3. Compare that initial ❤️number to the ❤️number displayed on article page

**Expected behavior**
Both feed and individual articles should be consistent

**Screenshots**
Article to click on:
![heartbug00](https://user-images.githubusercontent.com/11744547/52181713-61cd0980-27b2-11e9-8d27-dbca8fe573ad.png)

Article page:
![heartbug01](https://user-images.githubusercontent.com/11744547/52181720-77daca00-27b2-11e9-9752-5543ae7cf90e.png)

**Desktop (please complete the following information):**

- OS: iOS
- Browser Chrome
- Version 71.0.3578.98

**Smartphone (please complete the following information):**

- Device: Asus Zenphone3
- OS: Android
- Browser Chrome
- Version 72.0.3626.76

**Additional context**
Noticed this on both my desktop and my phone. I don't think this is a pressing issue but it's something I've noticed for a while, so I thought I'd document it ¯\_(ツ)_/¯

**Comment by Link2Twenty** [comment]
It's the sum of the hearts, unicorns and read lists

**Comment by meloncatty** [comment]
Ahh, alright! Thanks for clearing that up.

**Comment by aligoren** [comment]
I think there should be a feature. For example when user’ mouseover the reaction icon, should see all type of reactions.

**Comment by meloncatty** [comment]
Wonder how that would work for mobile. I like that the reactions are pooled together to promote the popularity of the article, just wasn't fully aware they used like that. Though I'm sure it's written somewhere or intuitive to most people 😅
