### ISSUE TITLE
Article URL is null

### ISSUE THREAD

**Issue by Nektro** [thepracticaldev/dev.to#172]
# _BUG_
### Current Behavior
When I try to read the below article in the provided screenshot, the URL is https://dev.to/null

### Expected Behavior
The URL would form correctly and I would be able to read the article

### Additional Info (steps to replicate, device/browser, helpful links)
Windows 10 1709 (Build 17074.1002)
Google Chrome 65.0.3325.106 (Official Build) beta (64-bit)
Incognito does not change the result
The article is from https://dev.to/dangolant

### Screenshots
![image](https://user-images.githubusercontent.com/5464072/36950509-cf68b990-1fc4-11e8-90a7-35487ccb11d8.png)

**Comment by Zhao-Andy** [comment]
Thanks for the heads up. We'll fix this soon.

**Comment by shobhitpuri** [comment]
+1. For any of the blogs on my profile (https://dev.to/shobhitpuri) as well, they are pointing to https://dev.to/null.

**Comment by Zhao-Andy** [comment]
@maestromac fixed this :) Let us know if you see any others in case we missed them.

**Comment by Nektro** [comment]
Looks good to me, I can see the article I mentioned and the ones from @shobhitpuri's profile
