### ISSUE TITLE
Editor switched versions and deleted text

### ISSUE THREAD

**Issue by kay-is** [thepracticaldev/dev.to#1733]
**Describe the bug**

I wrote an article and pressed preview and suddenly had a new version of the editor, but the top half of my article was gone.

I had the impression this was some UI glitch and pressed save draft, but this just persisted the missing content.  

It wasn't a long article and I just wrote it again, but it was kinda surprising behavior.

**To Reproduce**

I couldn't reproduce the issue, but this is what I did when it happened:

1. Wrote a new article with the old editor
2. Pressed did some previews and saves
3. Pressed preview and got a new editor with missing content

**Expected behavior**

dev.to shouldn't switch editor mid-edit.

**Desktop (please complete the following information):**

- OS: Windows 7
- Browser: Firefox Quantum 
- Version: 66.0b4 (64-bit)

**Smartphone (please complete the following information):**

**Comment by jessleenyc** [comment]
Sorry you lost part of your post @kay-is :/

Thanks for creating the issue -- we'll keep this on our radar.
