### ISSUE TITLE
Do not send email on /internal/reports with 'enter' button

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#1734]
**Is your feature request related to a problem? Please describe.**
I was adding a new note on a user profile in internal/reports and accidentally pressed enter. A reasonably expected behavior there would be for the note to publish but instead, the enter button sent out an email instead! 

**Describe the solution you'd like**
I think disabling the 'enter' button on internal/reports is probably the safest way to go here. 

**Describe alternatives you've considered**
Have the enter button submit a note instead.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/2816
