### ISSUE TITLE
Add webmention integration.

### ISSUE THREAD

**Issue by vorillaz** [thepracticaldev/dev.to#1736]
Hello there, great work and I instantly fell in love with the community and your efforts.
As a publisher myself to dev.to, I would love to have feedback on my content as it is cross-posted to dev.to. 

It would be great if you could integrate [webmention.io](https://webmention.io/). 
It requires as little as adding a tag to the HTML head and authenticate your authority using your twitter account. 
Thanks in advance for your efforts :)

**Comment by aciccarello** [comment]
I would love to see this feature as well.

**Comment by capjamesg** [comment]
I would love to see this feature too.
