### ISSUE TITLE
Styling of Edit Post button on your own post

### ISSUE THREAD

**Issue by sarthology** [thepracticaldev/dev.to#1740]
**Describe the bug**
In all the devices, below the size of *475px*, the *Edit Post" button have every small top margin.

**To Reproduce**

1. Go to your profile on mobile
2. Click on any of your posts 

**Expected behavior**
It should have more space than that.

**Screenshots**
![photo_2019-02-05_17-21-53](https://user-images.githubusercontent.com/3650216/52265289-aef5da80-296e-11e9-93eb-d8bdaef937eb.jpg)

**Comment by jessleenyc** [comment]
Thanks for flagging this. This is approved if anyone wants to jump on it!

**Comment by aligoren** [comment]
I think I or anyone is here can change margin. But what should be margin value? 10 pixels in general?

**Comment by sarthology** [comment]
Yeah 10px will do it.
