### ISSUE TITLE
Nonexistent podcast appears in the search results

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#1741]
**Describe the bug**
The first podcast on the [page](https://dev.to/search?q=books&filters=class_name:PodcastEpisode) returns 404.

**To Reproduce**

1. Go to the homepage
2. Type  "books" in the search input and submit
3. Select "Podcasts" in the left menu.
4. Click the first result (Episode 064 – Favorite Programming Books), see "Not Found"

**Screenshots**
![book_podcasts](https://user-images.githubusercontent.com/30115/52271558-0b4c0080-2955-11e9-95d4-d1d22f33bc52.png)

**Comment by lightalloy** [comment]
Could happen cause the episodes are not destroyed on podcast destroy.

**Comment by lightalloy** [comment]
I was able to find the podcast and the episode by [another url](https://dev.to/6figuredev/episode-064--favorite-programming-books), so maybe some cache cleaning issues cause the error.

**Comment by maestromac** [comment]
Is this happening to a lot of podcasts?

**Comment by lightalloy** [comment]
No, I was only able to find this issue with the older episodes of the [6figuredev podcast](https://dev.to/6figuredev/). I'm pretty sure this happens when the podcast slug is changed, as I specified in the previous comment, and I suppose it doesn't happen often.

**Comment by maestromac** [comment]
not stale

**Comment by rhymes** [comment]
Could this just be a question of re-building Algolia's podcasts index?

**Comment by maestromac** [comment]
Yep I feel like it definitely is. 

cc @benhalpern

**Comment by mstruve** [comment]
This should be resolved since moving to Elasticsearch.
