### ISSUE TITLE
Feature request - dev.to for Android / iOS

### ISSUE THREAD

**Issue by rnitame** [thepracticaldev/dev.to#176]
# _TASK or Feature_
### Request or User Story

I want an application that can read and post articles.

For example: Medium app
https://play.google.com/store/apps/details?id=com.medium.reader&hl=ja
https://itunes.apple.com/jp/app/medium/id828256236?mt=8

**Comment by Zhao-Andy** [comment]
@rnitame Thanks for the feedback. We don't have any official native mobile apps yet, but the web app is a PWA that you can download on Android, with Chrome or Firefox.

**Comment by rnitame** [comment]
OK, use PWA :)
