### ISSUE TITLE
Error Github PR Embed

### ISSUE THREAD

**Issue by Glennmen** [thepracticaldev/dev.to#1760]
**Is your feature request related to a problem? Please describe.**
When trying to embed a Github PR an error message is shown: `Invalid Github Repo link`

**Describe the solution you'd like**
Github Pull Requests should also be embedded correctly like Github Issues.

**Describe alternatives you've considered**
Replacing `pull` with `issues` in the url is a dirty workaround, I assume that adding `/pull/` to the Github link validator should be sufficient to add support for this.

**Additional context**
- Error with PR url:
![Error with PR url](https://user-images.githubusercontent.com/11406433/52442103-a3e3ab80-2b22-11e9-9ce5-5312197e42b4.png)

- No error when using workaround:
![No error when replaced with issues](https://user-images.githubusercontent.com/11406433/52442214-e0170c00-2b22-11e9-877a-67674f371e31.png)

- Correct result after applying workaround:
![Correct result after applying workaround](https://user-images.githubusercontent.com/11406433/52442295-0ccb2380-2b23-11e9-98f1-9d1dfa4ad9df.png)

**Comment by Zhao-Andy** [comment]
Hey @Glennmen, we technically don't have that feature yet. I believe GitHub treats issues and pulls as the same thing under the hood, which is why the workaround works.

This might be as simple as allowing our Liquid tag to look for `/pull/`. @maestromac might have more ideas on this.

**Comment by Glennmen** [comment]
Hmm might better have used the `Feature request` template then, if wanted I can change the issue to use the correct template.

**Comment by maestromac** [comment]
@Glennmen it's really fine but you are welcomed to edit your issue.

Yes, allow our liquid tag to look for `/pull/` would be enough for it to distinguish that the submitted link is a pull request.

**Comment by Glennmen** [comment]
Working on a PR for this, so don't steal my PR 😂
