### ISSUE TITLE
A spelling Mistake

### ISSUE THREAD

**Issue by mraza007** [thepracticaldev/dev.to#177]
### Issue
There is a spelling mistake it was supposed to be podcasts
### Screenshots
![image](https://user-images.githubusercontent.com/21070545/37262726-4310917c-257b-11e8-88e3-aa8abc538fee.png)

**Comment by Zhao-Andy** [comment]
Hey @mraza007, congrats on your first issue! Could you provide a link to where you found that?

**Comment by mraza007** [comment]
I think it's in the dev.to repo markdown

**Comment by mraza007** [comment]
https://github.com/thepracticaldev/dev.to

**Comment by Zhao-Andy** [comment]
Fixed 👍
