### ISSUE TITLE
Pressing publish multiple times creates dupe posts

### ISSUE THREAD

**Issue by whoisryosuke** [thepracticaldev/dev.to#1770]
**Describe the bug**
Pressing publish on a new post multiple times creates duplicates of the article.

**To Reproduce**

1. Write post
2. Press publish as many times as you can before the page refreshes. I pressed twice, got two articles in my dashboard.

**Expected behavior**
Publish one article. Maybe disable the button after the first press.

**Desktop (please complete the following information):**

- OS: MacOS 10.13
- Browser: Chrome 72

**Comment by jessleenyc** [comment]
Thanks for flagging! This issue is approved for anyone who might want to work on it.

**Comment by maestromac** [comment]
resolved with https://github.com/thepracticaldev/dev.to/pull/1791
