### ISSUE TITLE
Should dropdown be used for editor version selection?

### ISSUE THREAD

**Issue by aligoren** [thepracticaldev/dev.to#1775]
**Is your feature request related to a problem? Please describe.**

In my opinion, It's annoying always writing editor version. I'm not sure but if there is a version number 99, the user will have to write v99.

Instead of this, the `select` tag can be useful.

**Describe the solution you'd like**

I think we can change the input element with a select element like below:

```html
<label for="user_editor_version">Editor version: v1 or v2</label>
<select name="user[editor_version]" id="user_editor_version">
    <option value="v1">v1</option>
    <option value="v2">v2</option>
</select>
```

And css will be like that

```css
width: 650px;
max-width: calc(100% - 30px);
padding: 12px;
font-size: 19px;
border: 1px solid #dee6e9;
border-radius: 3px;
```

**Describe alternatives you've considered**

The other alternative is Radio Button if there are two versions.

**Additional context**

I changed input with the select tag using Chrome's Developer Tool.

It looks like below;

![image](https://user-images.githubusercontent.com/4205423/52548794-b3901800-2de0-11e9-91cf-480c44932e2e.png)

In this example, I changed my editor version using the select tag.

**Comment by jessleenyc** [comment]
Yeah, this makes sense to me. I haven't brought it up in meetings but I've been meaning to submit a PR that makes the change. If anyone else wants to, please go for it.

**Comment by venarius** [comment]
@benhalpern I guess this can be closed.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/2107
