### ISSUE TITLE
Allow jumping/linking to headings with a URL hash

### ISSUE THREAD

**Issue by charrondev** [thepracticaldev/dev.to#178]
# _TASK or Feature_
### Request or User Story

Many markdown based sites allow the linking to a certain heading in the page with a hash URL. Here is an example on [this github repo](https://github.com/thepracticaldev/dev.to#current-functionality) and on [a documentation site](https://docs.vanillaforums.com/developer/apiv2/resource-routing/#parameters). An example of the code that generating this type of heading can be found [here](https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/toc_filter.rb)

#### Example use case

I want to create a link at the top of the article to skip over the more general section and jump down to the technical part of the article.

### Definition of Done

A user can create a link in their own article to link to further down, or further up content.

### Notes

This does not necessarily need to be surfaced as a clickable icon to grab the link for the icon as the 2 examples I posted do, but that is also a pretty nice.

**Comment by Zhao-Andy** [comment]
Hey @charrondev, thanks for the feedback. We're going to backlog this for now. :)

**Comment by charrondev** [comment]
Great! It will be a nice addition once your team has time for it.

**Comment by maestromac** [comment]
https://github.com/thepracticaldev/dev.to/pull/713 would resolve this

**Comment by Link2Twenty** [comment]
#713 is merged, can we close this?

@maestromac

**Comment by Zhao-Andy** [comment]
Yep, resolved by #713.
