### ISSUE TITLE
Posts are SAVE instead of SAVED if you filter the Reading List

### ISSUE THREAD

**Issue by ItsASine** [thepracticaldev/dev.to#1785]
**Describe the bug**
I know there are other issues around SAVE/SAVED but this one seems unique enough for its own post. When filtering the Reading List, the buttons on posts are not in the SAVED state.

**To reproduce**: 
* Navigate to the Reading List
* Select one of the tags on the sidebar

**Expected**:
* Articles are marked as Saved as they are in the list of saved stuff

**Actual**:
* Article button is Save as if they are not in the Reading List

**Screenshots**
![image](https://user-images.githubusercontent.com/11020425/52607583-bd4b6700-2e44-11e9-8c9a-fbda80dc0724.png)

**Desktop (please complete the following information):**

- OS: Chrome OS
- Browser: Chrome
- Version:  71.0.3578.127

**Comment by jessleenyc** [comment]
Hmm yeah, this seems related with https://github.com/thepracticaldev/dev.to/issues/1395.

**Comment by jessleenyc** [comment]
@lightalloy I know you've been looking at reading list so wanted to get this on your radar too.

**Comment by ItsASine** [comment]
@jessleenyc I almost logged this s a comment on #1395 but that seemed more focused on the initial state being SAVE and not always toggling to SAVED, meanwhile, this is every time you try filtering the list, the button is in the wrong state for each article. Could be an issue with the initial state, but seemed more keen on being an issue with the filtering.

**Comment by lightalloy** [comment]
@jessleenyc I suppose it's related to the frontend side (but needs research). I'll look at this after the other tickets.

**Comment by lightalloy** [comment]
Currently working on this one. I can confirm that it's related to #1395 . On page load, the code which determines the button states runs several times and sometimes finishes with the wrong button state. 
On clicking the tag (as described in this issue) the code just doesn't run and all buttons remain with the "SAVE" label.

**Comment by lightalloy** [comment]
Closed by #1927
