### ISSUE TITLE
The page is not updated after submitting a podcast comment

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#1788]
**Describe the bug**

**To Reproduce**
1. Go to a [podcast episode page](https://dev.to/developertea/how-we-construct-software--part-two-beliefs-and-models-)
2. Fill the comment form
3. Click submit or press `Ctrl+Enter`
4. The "submit" button changes color and the form becomes blurred (as the comment is being submitted).
5. The form remains the same, the comment doesn't appear on the page.
6. After refresh, the comment appears on the page.

**Expected behavior**
After submitting, the comment appears on the page, the comment form returns to its "fresh" state (the submit button changes color back, the textarea is cleared)

**Screenshots**
![podcast_comment](https://user-images.githubusercontent.com/30115/52636586-1f0bdf80-2ede-11e9-834d-ff919fffc27c.png)

**Desktop (please complete the following information):**
I've checked in Firefox and Chrome, but suppose that the browser doesn't matter, cause the reason specified below:

**Additional context**
I've noticed this error in dev environment.
```
NoMethodError - undefined method `receive_notifications' for #<PodcastEpisode:0x00007fdc223ae340>:
  app/models/notification.rb:50:in `send_new_comment_notifications'
  app/controllers/comments_controller.rb:69:in `create'
```
So the code needs to be updated to be suitable for the `PodcastEpisode` comments.

**Comment by jessleenyc** [comment]
Thanks for flagging Anna. @Zhao-Andy is this related to some of the notification work you've been doing?

**Comment by Zhao-Andy** [comment]
Ah, this is because the `send_new_comment_notifications` doesn't handle commenting on podcasts right now. I think that's a discussion we'll want to have later.

For now, A one line guard statement should at least resolve that error:
```ruby
def send_new_comment_notification(comment)
  return if comment.commentable_type == "PodcastEpisode"
  # rest of the code
```

Anyone working on this should continue to see if the comment submits and appears properly on the podcast episode.
