### ISSUE TITLE
Two suggestions (Both from profile page)

### ISSUE THREAD

**Issue by solutweb** [thepracticaldev/dev.to#1789]
**Is your feature request related to a problem? Please describe.**

1. I think that it's unnecessary to show this kind of message:
![image](https://user-images.githubusercontent.com/28319535/52633231-e0106680-2eaa-11e9-968c-778ec1eec603.png)

2. Sorry if exists and I didn't find it, but would be nice if you could add a Twitter URL field in profile page (Links section). 

**Describe the solution you'd like**
1. Hide that message when a bio was not writed.
2. Add a Twitter URL field in profile page (Links section). 

**Describe alternatives you've considered**

**Additional context**

**Comment by jessleenyc** [comment]
hey @solutweb - your twitter profile link will automatically be added if you add if you authenticate here: https://dev.to/settings/account

**Comment by jessleenyc** [comment]
We'll reconsider the 404 message on our next redesign -- going to close this issue for now.
