### ISSUE TITLE
Preview does not show description on writing new post

### ISSUE THREAD

**Issue by zafar-saleem** [thepracticaldev/dev.to#1790]
**Describe the bug**
After writing the title and description of the new post and hit preview, it previews the title but does not preview description.

**To Reproduce**

1. Go to 'write a post'
2. Enter 'title and description'
3. Click on 'preview'
4. Only title and authors name is seeable but no description.

**Expected behavior**
It should preview both, title and description.

**Screenshots**
1.  Writing post image. https://pasteboard.co/I0Qrrkb.png
2. Preview image. https://pasteboard.co/I0QrJzB.png

**Desktop (please complete the following information):**
- Browser [e.g. chrome]

**Comment by jessleenyc** [comment]
Hey @zafar-saleem -- the description is actually for open graph cards. For example, on Twitter: ![](https://cl.ly/8d7125c5bb44/download/Image%202019-02-12%20at%201.25.03%20PM.png). Closing this issue since this is expected behavior.

**Comment by zafar-saleem** [comment]
I am not sure why would that preview be on there while writing your post. At the time of writing, I would  want to see the preview of my own post instead.

If this feature is for sharing on social media then it could be somewhere else IMHO.
