### ISSUE TITLE
Relative links instead of external ones

### ISSUE THREAD

**Issue by hdennen** [thepracticaldev/dev.to#180]
# _BUG_
### Current Behavior
Clicking link in article opens 404 on dev.to relative url

### Expected Behavior
link should go to external url

### Additional Info (steps to replicate, device/browser, helpful links)
I've seen this on a couple posts now where for whatever reason the link is becoming a relative link instead of an external one.

### Screenshots
This is meant to link to https://rkoutnik.com/2016/04/21/implementers-solvers-and-finders.html

![image](https://user-images.githubusercontent.com/1907088/37640128-dbdc3742-2c1c-11e8-8094-e2f076f83eb0.png)

**Comment by jessleenyc** [comment]
Thanks @hdennen -- should be fixed now.
