### ISSUE TITLE
close zoomed image

### ISSUE THREAD

**Issue by Saralkarki** [thepracticaldev/dev.to#1803]
**Is your feature request related to a problem? Please describe.**
Every time I zoom into an image, the image url is loaded. However, the problem is the lack of a close button, and I have to click the back button in my browser to go back to the post(article) that I was reading. 

**Describe the solution you'd like**
A close button to close the image, and get back to the post would be great. 

**Describe alternatives you've considered**

**Additional context**

**Comment by abraham** [comment]
It looks like #413 will cover this when implemented.

**Comment by Link2Twenty** [comment]
Clicking on an image doesn't actually zoom it in, it takes you to the images URL. Yes #413 will move over to a lightbox like model.

**Comment by aspittel** [comment]
Thanks for submitting this issue @Saralkarki! Will discuss further with the team!

**Comment by maestromac** [comment]
Thank you for this issue @Saralkarki !

As @Link2Twenty has mentioned, close button would be irrelevant because clicking on an image actually takes you to the url. #413 will be the solution going forward.

Closing.
