### ISSUE TITLE
broken url in the scholarships page.

### ISSUE THREAD

**Issue by Saralkarki** [thepracticaldev/dev.to#1804]
**Describe the bug**
Something seems to be wrong with the link in the https://dev.to/p/scholarships page. The sign in with google, linkedin and facebook options aren't working. 

**To Reproduce**

1. Go to 'https://dev.to/p/scholarships'

2. Scroll down to 'Sign in sections'
3. Click the sign in with google, facebook option

**Expected behavior**
I should be able to sign in using one of these accounts. 

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version 71.0.3578.98 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by aspittel** [comment]
Thanks for reporting this @Saralkarki -- looks like an issue on the typeform side. Will pass this along.

**Comment by pkfrank** [comment]
Hey @Saralkarki thanks for this report.  As @aspittel identified, this was indeed an issue on the Typeform side.  It's now been fixed and should be working properly.

I'm closing this issue, but please let me know if you have any other questions.  Really appreciate you taking the time to create this issue!
