### ISSUE TITLE
Separate Articles and Recent Comments in  Profile

### ISSUE THREAD

**Issue by nestedsoftware** [thepracticaldev/dev.to#181]
# Feature
### Separate Articles and Recent Comments in Profile
I would like there to be a separate section on a user's profile where all of their articles are listed, separately from comments they've made.

**Comment by Zhao-Andy** [comment]
Hey @nestedsoftware, thanks for the feedback. You can see the comments separated from the user by going to their profile and clicking "Last `x amount` of comments" (https://dev.to/`username`/comments).

I think that's a pretty good solution for filtering out a person's comments from their articles, and scrolling below the "Recent Comments" section will give you the rest of their articles. With those two options, we're going to backlog this for now.
