### ISSUE TITLE
Constantly seeing offline screen

### ISSUE THREAD

**Issue by stereobooster** [thepracticaldev/dev.to#1810]
**Describe the bug**

Opened direct link to dev.to article and saw offline screen. `Cmd` + `R` didn't help. I was online all the time. The only thing which is helped is to remove ServiceWorker completely and reload page.

**To Reproduce**

1. Open any link to dev.to post

**Expected behavior**
No offline screen if browser is online

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Mac OS X
- Browser Chrome
- Version Version 71.0.3578.98 (Official Build) (64-bit)

**Additional context**
N/A

**Comment by jessleenyc** [comment]
Thanks for flagging, we'll look into this.

**Comment by danielw93** [comment]
I'm experiencing the same problem with slightly different symptoms.

Test system: Firefox 66.0.2 on Ubuntu 18.04.2 LTS
*Using Chromium (build 73.0.3683.86) the below steps do not reproduce the problem.*

### To reproduce:
1. Open an article on dev.to
2. Follow a link or image that navigates away from dev.to
3. Use browser back to return to article
-> "It looks like you're offline" screen appears.

Simple reloading does nothing, however Ctrl + F5 resolves the issue.

**Comment by maestromac** [comment]
I've added additional logging to Service Worker. If anybody ever come across an aggressive offline page, please share the logging from your browser console.

**Comment by danielw93** [comment]
Hi! :)
I can still reproduce the behavior I described above with Firefox 67.0.1 on Ubuntu 18.04.2 LTS.

I went over to dev.to and opened the article [How to Be Great? Just Be Good, Repeatably ](https://dev.to/stephsmithio/how-to-be-great-just-be-good-repeatably-bk5), clicked on the link in the first line, navigating to the authors blog.
Hit browser back to go back to the dev.to article and got the "You're offline" page.

I have attached the console output starting from the time I first visited dev.to: [console.log](https://github.com/thepracticaldev/dev.to/files/3290293/console.log)

The relevant part of the log is probably this, right after I had hit browser back:
```
Navigated to https://dev.to/stephsmithio/how-to-be-great-just-be-good-repeatably-bk5
TypeError: NetworkError when attempting to fetch resource. serviceworker.js:1:3040
```

**Comment by maestromac** [comment]
Thanks for quick report @danielw93 . Are you using privacy badger or uMatrix by any chance? Is this reproducible in incognito?

**Comment by danielw93** [comment]
@maestromac Good call! 
It seems that Privacy Badger was indeed the problem. It showed dev.to as a potential tracker and had completely blocked the domain 🤦
After manually reenabling dev.to I can no longer reproduce the reported behavior.

**Comment by maestromac** [comment]
Yeah, Service Worker is still a bit wonky and is false positive to extensions like Privacy Badger. Thanks for checking!

Are you still experiencing this issue @stereobooster ?

**Comment by stereobooster** [comment]
Hey @maestromac. No it was one time thing if we talk about offline screen issue.

I wonder if there would be any issues with the size of data in the storage or is it just ok

<img width="450" alt="Screenshot 2019-06-17 at 17 42 50" src="https://user-images.githubusercontent.com/179534/59617905-74bff500-9127-11e9-9266-205354e14b6a.png">

**Comment by maestromac** [comment]
Alrighty, I'm assuming this issue is resolved. Please let me know if otherwise!!
