### ISSUE TITLE
Seeing error on Save Post, title can't be blank

### ISSUE THREAD

**Issue by zafar-saleem** [thepracticaldev/dev.to#1817]
After writing a post, when I press save post I get an error "title can't be blank". But the title of the post is there.

**To Reproduce**

1. Write post
2. Write your post and give title
3. Click on Save Post
4. You see error.

**Expected behavior**
It should save the post instead of showing error as the title is there.

**Screenshots**
https://imgur.com/a/bJYCIbw

**Desktop:**

- Browser chrome

**Comment by Glennmen** [comment]
@zafar-saleem I think it would also be helpful to include a screenshot of the markdown editor, in the provided screenshot I don't see any of the meta attributes (title, published, ...).

**Comment by zafar-saleem** [comment]
When I give the meta attributes the same error shows.

**Comment by Link2Twenty** [comment]
Your post should start like this

```
---
title: Some title
published: true
description: A description of the post
tags: tags, split. with, commas
---
```

Then you can add your post content.

**Comment by Glennmen** [comment]
@zafar-saleem With the info you provided now I think this is a user error and not a bug.

I don't see the Front Matter block in your editor so I assume that it isn't the first thing in your blog post. From the docs of [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/):

> The front matter must be the first thing in the file and must take the form of valid YAML set between triple-dashed lines.

**Comment by zafar-saleem** [comment]
@Link2Twenty That is exactly how it should but if I start my post your way or the way I did it looks the same in preview but I still see the same error I mentioned above. I am not sure why.

**Comment by Link2Twenty** [comment]
Can you try entering this as a new post and see if you still get the error?

```
---
title: Test post
published: false
description: A post for testing
---

This is a test post
```

**Comment by zafar-saleem** [comment]
@Glennmen and @Link2Twenty here is a screenshot with meta tag. [write post errors](https://imgur.com/a/ISus3Wq). As you can I get an additional error.

**Comment by Link2Twenty** [comment]
But you can't have that image in the header section.

**Comment by Link2Twenty** [comment]
If you want a cover image you need to add it like this

```
cover_image: https://image.address.co.uk/theimage.jpg
```

**Comment by zafar-saleem** [comment]
Even if I remove that image above 2 errors still exist.

**Comment by Link2Twenty** [comment]
Can you paste in the entire body text, I believe it must be a syntax error? 🙂

**Comment by jessleenyc** [comment]
Thanks for helping @Glennmen and @Link2Twenty! 

@zafar-saleem this does appear to be a syntax error based on your screenshot. If you have problems troubleshooting, you might want to try the v1 editor instead -- a bit more intuitive if you're unfamiliar with front matter. 

To toggle the v2 editor you can visit dev.to/settings/misc, type in 'v2', and save.
