### ISSUE TITLE
Remove rails-controller-testing gem

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#1827]
**Is your feature request related to a problem? Please describe.**

The [rails-controller-testing](https://github.com/rails/rails-controller-testing) gem is supposed to bring back two methods that have been deprecated in Rails: `assigns` and `assert_template` since when Rails started discouraging testing controller internals and views from the controller tests.

This gem though doesn't seem to be used by the app (I grepped for `assigns`, `assert_template` and `Rails::Controller::Testing`) and nothing popped up

**Describe the solution you'd like**

I suggest that it should be removed.

**Describe alternatives you've considered**

Well, no alternatives in this case, unless there's some other tool that's using it

**Comment by maestromac** [comment]
I ran the test suite without that gem and it failed a few spec.  ![](https://cl.ly/cd3d1bb68202/Image%202019-02-18%20at%205.16.46%20PM.png)

We can keep this issue open to help us finally move away from controller specs.

**Comment by rhymes** [comment]
Oooh, Rspec is magic, I didn't think about `render_template`. Thanks for the experiment
