### ISSUE TITLE
header tags should autogenerate anchor tags for Table of Contents usage

### ISSUE THREAD

**Issue by tsiq-swyx** [thepracticaldev/dev.to#183]
# _TASK or Feature_
### Request or User Story
Request
### Definition of Done
have anchor tags
### Notes

Markdown header tags should have anchor tags so that i can generate tables of contents.

see: https://dev.to/swyx/ocaml-speedrun-3f7g

see also anchor tags here https://github.com/adam-p/markdown-here/wiki/Markdown-Here-Cheatsheet#alt-h1

and for your docs you can add this handy TOC generator https://ecotrust-canada.github.io/markdown-toc/

if you want to encourage more longform posts on dev.to i think this is a must have.

thank you

**Comment by Zhao-Andy** [comment]
Hey @tsiq-swyx, thanks for the feedback. I think we have a pseudo-anchor available, but I could be wrong. We're going to backlog this for now. :)

**Comment by tsiq-swyx** [comment]
where? i couldnt find it. happy to close if anchor exists.

**Comment by Zhao-Andy** [comment]
Sorry, my mistake. Doesn't seem like we have it.

**Comment by igorsantos07** [comment]
This is not only useful to generate TOC, but also for the end-user: linking to a header is usually more useful than to the general article, when it's long and you must refer to a specific portion of it. I usually to that kind of thing when referring to readme-based documentation, for instance (on GitHub or whatever).

An addition to this feature is having the title being a hidden link to its own anchor (so one can right-click/copy link), and maybe even include that hidden :link: icon besides the header, on hover.

**Comment by glebec** [comment]
It looks to me like this is _might_ just be a matter of adding the `with_toc_data` option to each place the markdown renderer is instantiated, e.g. [here](https://github.com/thepracticaldev/dev.to/blob/78238cdc0f920676c6222fdbe77421805804b75d/app/labor/markdown_parser.rb#L15).

**Comment by bennypowers** [comment]
Is this deployed yet? Not seeing names in markup.

I got cache hits on some of my articles from Wed, 21 Nov 2018 09:37:25 GMT, maybe the cache needs to be invalidated?
