### ISSUE TITLE
CacheBuster#bust_comment may fail on banishing user

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#1831]
**Describe the bug**
`Commentable` is passed and referenced in the `CacheBuster#bust_comment`(https://github.com/thepracticaldev/dev.to/blob/master/app/labor/cache_buster.rb#L15) method, but sometimes `commentable` could be `nil`, because the comments are not destroyed on commentable (e.g. article) destroy. 

**To Reproduce**
- Destroy an article with comments
- Try to banish a user, who left of the comments on the destroyed article
- get `undefined method 'id' for nil:NilClass` error

**Expected behavior**
(assuming that we need to keep comments on the commentable destroy)
Don't try to bust cache of the nonexistent commentable/article.
At least add failing spec for the method and fix the code: check if commentable exists before referencing it.

**Comment by jessleenyc** [comment]
Thanks for creating the issue! Funny that I had submitted a separate PR for it without even realizing.
