### ISSUE TITLE
White text on white background

### ISSUE THREAD

**Issue by onderweg** [thepracticaldev/dev.to#184]
When logged in, text color in articles is white on a white background (so text is unreadable).
This happens only when logged in.

Tested in Chrome 65.

Not logged in:
![before](https://user-images.githubusercontent.com/588069/37894094-510b1898-30dd-11e8-8bec-c50a099be0db.png)

Logged in (with Github account):
![after](https://user-images.githubusercontent.com/588069/37894098-5b6f3c42-30dd-11e8-8400-ad791b7c4dba.png)

White text color seems to originate from style tag in div with id `additional-content-area`:

```
<style>
    body{
      text-align:center;
      color:white;
      background: #050505;
      font-size:calc(1em + 0.3vw);
    }

(...)
```

**Comment by Zhao-Andy** [comment]
Hey @onderweg, this is a weird edge case that happens when you don't have an email attached your account. If you go to https://dev.to/settings, add your email and confirm it, you should be able to view articles properly.

That said, we should fix this edge case. Thanks for the report!

**Comment by onderweg** [comment]
Hey @Zhao-Andy, thanks for the workaround, that works for now.

**Comment by Zhao-Andy** [comment]
Closing since this should be fixed. :)
