### ISSUE TITLE
Unable to post my article on Dev.to

### ISSUE THREAD

**Issue by ralphkalsi** [thepracticaldev/dev.to#1841]
**Describe the bug**
I am unable to add my article on Dev.to

**To Reproduce**

1. Go to 'Write a post'
2. Click on 'write to post'
4. See error - 500 Error and shows below given message
"500 Error
It's not you, it's me.
Sorry you're hitting this page. 
Please help us by submitting a bug report. 
Thank you!"

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/47516086/53149506-e3ef6780-35d3-11e9-94a7-fc0f77f00ea1.png)

**Comment by pkfrank** [comment]
Hi, this seems to be a specific issue with your account. Please email yo@dev.to for more help.
