### ISSUE TITLE
Small typo in Contact Page

### ISSUE THREAD

**Issue by clsource** [thepracticaldev/dev.to#185]
# Fix typo in Contact Page
### Request or User Story
Correct Typo in Contact Form

### Definition of Done
Change the word Pleaes to Please

### Notes

# _BUG_
### Current Behavior
Shows the word  `Pleaes`

### Expected Behavior
Should show the word `Please`

### Additional Info (steps to replicate, device/browser, helpful links)
Go to [https://dev.to/contact](https://dev.to/contact)

### Screenshots
![imagen](https://user-images.githubusercontent.com/292738/37916291-d8998c2c-30f1-11e8-8104-57317e125ece.png)

**Comment by Zhao-Andy** [comment]
Woops, we'll change that. Thanks for that!
