### ISSUE TITLE
Enable delayed job web for admins in production

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#1857]
**Is your feature request related to a problem? Please describe.**

I've noticed that [delayed job web](https://github.com/ejschmitt/delayed_job_web) was recently introduced by @lightalloy in #1835 which is a great addition because it helps knowing what's going on in the job queue. 

I'd like to propose extending the web interface not just for unauthenticated development usage but also for people with the correct credentials in production. 

**Describe the solution you'd like**

Delayed Job Web's [documentation suggests](https://github.com/ejschmitt/delayed_job_web#authenticating-with-devise-and-warden) using Devise's own guards to expose the endpoint accessible to admin users:

```ruby
authenticated :user, -> user { user.admin? }  do
  mount DelayedJobWeb, at: "/delayed_job"
end
```

I'm not 100% if the `user.admin?` test is sufficient to grant access to the queue or a different role should be used.

**Additional context**

Visibility in the job queue is likely welcome, especially if the code is slowly moving to separate queues for different types of work.

**Comment by benhalpern** [comment]
I'm in favor of this. We had this more or less in place in the past but ran into some issue and we took it out. I can't even remember what it was but I'm sure it's a small thing we can overcome with proper config.

Yeah, `admin?` is the proper user method for this.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/1967
