### ISSUE TITLE
Organise and group tags by topics and subtopics

### ISSUE THREAD

**Issue by JuliaTorrejon** [thepracticaldev/dev.to#1864]
**Is your feature request related to a problem? Please describe.**
The usability of the tags is not fully clear when searching for specific topics and/or subtopics.

**Describe the solution you'd like**
I think the functionality of the tags could be more valuable if they could be organised and grouped in a drop-down list by main topics such as Tools, Programming Languages, Tips, etc; and these, in turn, have detailed subtopics. For example:

![tags dropdown](https://user-images.githubusercontent.com/29682284/53303141-d8fc3780-385e-11e9-8cdf-5c34340d0751.png)

**Additional context**
Actual view of My Tags
![tags](https://user-images.githubusercontent.com/29682284/53299293-ffef4500-382f-11e9-864e-b45686c5fe4b.png)

**Comment by Link2Twenty** [comment]
Currently, this list is based on the tags the author add to their post.

How do you envisage an author getting their post under the "while statement" category?
```
tag: #python #statements #while
```
Something like that?

**Comment by jessleenyc** [comment]
I'm having a hard time thinking through how subcategories would work but in the past we've had discussions around adding a "type" to articles i.e. tutorial, course, personal essay, career.
