### ISSUE TITLE
[Feature request] github flavored markdown

### ISSUE THREAD

**Issue by sw-yx** [thepracticaldev/dev.to#1867]
**Is your feature request related to a problem? Please describe.**

I want to write github flavored markdown in dev.to, but it doesnt take it

**Describe the solution you'd like**

Parse github flavored markdown in dev.to

**Describe alternatives you've considered**

No change

**Additional context**

**Comment by Link2Twenty** [comment]
Which bits of markdown are you missing?

Here's GitHub's markdown https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf

and here is Dev.to's https://github.com/adam-p/markdown-here/wiki/Markdown-Here-Cheatsheet

I think a couple of things are missing, like checklists.

**Comment by sw-yx** [comment]
i like using `<details>/<summary>` tags with markdown inside them. https://github.github.com/gfm/#example-155

**Comment by Link2Twenty** [comment]
Reference: #947

**Comment by sw-yx** [comment]
ah. two sides of the same coin. better to stay as close to gh markdown as possible since that is what devs will mostly be used to.

**Comment by jessleenyc** [comment]
Hey all, I created a separate issue for the two specific tags @sw-yx was looking for: https://github.com/thepracticaldev/dev.to/issues/2045

We want to take as much of the good parts of github markdown as possible. I'm going to close this issue in favor of adding/updating as we go.
