### ISSUE TITLE
Consider adding support for the <mark> element

### ISSUE THREAD

**Issue by simevidas** [thepracticaldev/dev.to#1870]
The `<mark>` element is useful for highlighting certain words and phrases in text, which reduces the “wall of text” issue. Browsers already render this element using a yellow background.

I ask Dev.to to not strip the `<mark>` element from the HTML output of articles. Authors can use this element in Markdown normally.

An example of how `<mark>` improves the readability of content:

<img width="882" alt="screen shot 2019-02-24 at 9 31 23 pm" src="https://user-images.githubusercontent.com/716405/53314639-c6feb100-38bf-11e9-927d-9d35b7d34cdd.png">

**Comment by Link2Twenty** [comment]
It should be a simple as adding it to the `tags` list in the scrubber
https://github.com/thepracticaldev/dev.to/blob/master/app/sanitizers/rendered_markdown_scrubber.rb

Provided the team are ok with `<mark>` being included.

**Comment by jessleenyc** [comment]
Awesome. This is approved!

**Comment by bolariin** [comment]
I would like to try to resolve this.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/2089
