### ISSUE TITLE
No "Cancel" edit button on comments

### ISSUE THREAD

**Issue by nektro** [thepracticaldev/dev.to#188]
# _BUG_
### Current Behavior
When editing a comment, the only way to leave `/edit` is to navigate back to `dev.to` from the top nav or using one of the footer links.

### Expected Behavior
A "Cancel" button that brings you back to the article your comment was on.

### Screenshots
![image](https://user-images.githubusercontent.com/5464072/37983129-83e21378-31c0-11e8-80f0-4c03255246da.png)

**Comment by Zhao-Andy** [comment]
Hey @Nektro, thanks for the feedback. Should be a quick addition, but it'll be in the backlog for now.

**Comment by jessleenyc** [comment]
Might make more sense for editing not to direct to a new page.

**Comment by maestromac** [comment]
Not stale

**Comment by maestromac** [comment]
Resolved by https://github.com/thepracticaldev/dev.to/pull/331
