### ISSUE TITLE
Convert event time to local time

### ISSUE THREAD

**Issue by bigblind** [thepracticaldev/dev.to#189]
# _Feature Request_
### Request or User Story
As a user,
when I visit the Events page: https://dev.to/events,
I'd like the event's date and time to be displayed in my local time zone. 

### Definition of Done

Users see event dates in their local timezone

**Comment by Zhao-Andy** [comment]
Hey @bigblind, thanks for the feedback. We're going to backlog this for now.

**Comment by maestromac** [comment]
Sorry we didn't get back to this. It was resolved awhile ago.
