### ISSUE TITLE
Support webmentions on dev.to

### ISSUE THREAD

**Issue by bronzehedwick** [thepracticaldev/dev.to#1893]
I'd be great to send [webmentions](https://indieweb.org/Webmention) of comments/likes/etc on dev.to, to dovetail with the great RSS POSSE publishing feature.

**Comment by vorillaz** [comment]
There are two more issues open #1736  and #81. It would be really great if you could support web mentions. It will allow us, people that are crossposting content to dev.to to track down interactions and feedback for our work.

**Comment by bronzehedwick** [comment]
@vorillaz I didn't realize you already had an issue open explicitly for webmention support. My bad! I should have searched better. Going to close this issue as duplicate in favor of #1736.
