### ISSUE TITLE
Delete User / Repeat Usernames

### ISSUE THREAD

**Issue by dvdmuckle** [thepracticaldev/dev.to#19]
For whatever reason, I have two users on dev.to, one is dvdmuckle, the other dvdmuckle_51. When trying to link my Twitter and Github to the latter user, it seems to take but also errors out. It also errors out when trying to change my username to dvdmuckle, as the user also exists.

![](https://i.imgur.com/OKo69lG.png)

The only delta between the two is the email, which, because one user has one email and the other user has the other email, I can't change on either of the accounts.

**Comment by Sudiukil** [comment]
Same problem here, linking both Twitter and GitHub seems to create two different accounts conflicting with each other.

I can't update my profile at all, even when I completely change the "Username" field, I alway get the "Github username has already been taken" error message (and no input field is highlighted).

**Comment by Zhao-Andy** [comment]
Fixed, thanks for the heads up. Emailing you both to figure out which account you want to keep. :)
