### ISSUE TITLE
A few enhancements / suggestions when playing videos

### ISSUE THREAD

**Issue by joshi-chinmay** [thepracticaldev/dev.to#190]
# Feature or enhancement
### User Story
We can play multiple videos on a single page.
1. Users (like me, who fidget a lot with page scrolls) keep on scrolling the page, yet we want to stay put with the video.
2. Users (unlike me) may want the video to stop playing when they scroll the page.

### Definition of Done
1. Have a small pop-up where a user can control and see the current playing video. If he/she plays the other video from the page or closes the current one, then the pop-up should go away. <i>(like YouTube App)</i>
2. When a user scrolls the page, the video should stop playing. Also, it should start playing again when it comes to the focus <i>(Like Instagram)</i>.

**Comment by Zhao-Andy** [comment]
Hey @joshi-chinmay, thanks for the feedback. We're going to backlog this for now.
