### ISSUE TITLE
Option to share links natively in the PWA

### ISSUE THREAD

**Issue by aqeelsmith** [thepracticaldev/dev.to#191]
# _TASK or Feature_ 
### Request or User Story

I usually use Pocket to save articles of dev.to to read for later . When I access the webpage from my mobile browser , I usually share the link to Pocket . I am unable to do this using the PWA . Can you please add an option to natively share the links using the PWA. 

### Definition of Done
Share web link urls to another apps using PWA .

**Comment by Zhao-Andy** [comment]
Hey @aqeelsmith, we have a minor implementation of this. To the right of the reactions button, we have a button that lets you copy the link. It's not as full-fledged of a tool as using something like the Web Share API, but it does the job for now. See #111 for more info.

We'll be backlogging this for now. Thanks for the feedback!

**Comment by jessleenyc** [comment]
Hey @aqeelsmith! Does this help? It's an extension that lets you save to dev.to articles your reading list _and_ pocket. 

https://dev.to/scleriot/build-a-firefox-extension-step-by-step-5dbl

**Comment by aqeelsmith** [comment]
Ummm no.
I wanted this feature to be present in the PWA since once I open the PWA ,
I do not see any option to save the article to pocket .
Thanks for looking into this.  Would be great if you guys could implement
this.

**Comment by jessleenyc** [comment]
Hey @aqeelsmith, for now, you can copy the link to an article by clicking on the ellipses button next to the reactions. 

![screen shot 2018-04-10 at 11 01 15 am](https://user-images.githubusercontent.com/14931921/38565216-b8b75f24-3cae-11e8-9349-9956dcc85b20.png)
