### ISSUE TITLE
Add option to manually update analytics

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#1914]
**Is your feature request related to a problem? Please describe.**
Right now we rely on some randomness and interaction w/ reactions to fetch analytics for dashboards. I think we should add an option for people to click a button and have their data pulled. I also think we need to add a note that google analytics information has a reporting delay, even if we're manually fetching. 

**Describe the solution you'd like**
A button next to each article that updates the data for that article. And a timestamp for when info was last pulled. 

**Describe alternatives you've considered**
A button that updates all user analytics at once.

**Comment by Hamatti** [comment]
I like this one! @jessleenyc can you clarify how it happens currently? I feel like my analytics haven't updated in days and previously it has felt like they update all the time.

**Comment by jessleenyc** [comment]
We're actually going to go with a different direction for this so I'm closing the issue. 

@Hamatti I do think there's a bug within the current analytics and here's the issue for that if you'd like to follow along there: https://github.com/thepracticaldev/dev.to/issues/1765
