### ISSUE TITLE
modern editor?

### ISSUE THREAD

**Issue by Butonix** [thepracticaldev/dev.to#1918]
Do you have plans to add more modern editors?
such as
https://github.com/codex-team/editor.js
or
https://github.com/brijeshb42/medium-draft

**Comment by Glennmen** [comment]
There is a v2 editor currently in beta, you can enable it in your profile settings: https://dev.to/settings/misc

**Comment by Butonix** [comment]
> There is a v2 editor currently in beta, you can enable it in your profile settings: https://dev.to/settings/misc

I saw him, he's very uncomfortable. It's easier when you insert a link and the editor converts it to media. therefore I ASKED

**Comment by maestromac** [comment]
Thank you for the issue @Butonix . As @Glennmen has mentioned, we have a v2 editor that you can enable on your setting page. We do not currently plan to use a 3rd party WYSIWYG editor.
