### ISSUE TITLE
Allow subscribing to conversations

### ISSUE THREAD

**Issue by achasveachas** [thepracticaldev/dev.to#192]
# _TASK or Feature_
### Request or User Story
There are many posts on dev.to (especially under the #discuss tag) where the bulk of the conversation happens in the comments section. Currently the only way to follow them is by bookmarking the discussion and coming back every one in a while to see if any new comments were posted (made a little harder by the fact that comment order can change based on popularity).

It would be nice to have a way to "follow" or "subscribe" to a conversation so you get notified every time a new comment is posted, the way you get notified of someone comments on your own post.

### Definition of Done
Having a "Follow Conversation" button on each post and getting notifications every time a new comment is added to the conversations you are following.

**Comment by Zhao-Andy** [comment]
Definitely for this feature! We talked about it a few months ago as a team, and it's good to bring it up again. Thanks for mentioning it!

**Comment by jessleenyc** [comment]
Hey @achasveachas, in the mean time it might be helpful to keep an eye on the comments activity page. 
You can access that here: 

![](https://d2ffutrenqvap3.cloudfront.net/items/032n2s1G2Y213S2E2a3O/%5B5fee88ce9b7c2c9bccc4f3b222901333%5D_Image+2018-04-10+at+11.06.10+AM.png)

**Comment by achasveachas** [comment]
@jessleenyc that's a nice feature I haven't noticed!

At first glance, it seems to display users' comments as well as comments to the users content. Is there a way to follow a discussion other than commenting?

**Comment by jessleenyc** [comment]
I know this is closed but thought I'd leave a note that this functionality is now available: ![](https://cl.ly/79e20c418965/download/Image%202019-08-07%20at%205.49.42%20PM.png)

**Comment by achasveachas** [comment]
Awesome, thanks!
