### ISSUE TITLE
User karma

### ISSUE THREAD

**Issue by Butonix** [thepracticaldev/dev.to#1925]
Did you not consider the question of adding karma to your user profile?
For example, for each received like comment, the user will receive 0.5 points in karma, for each received like for an article, the user gets 1 point in karma. Also make a dislike, so that the article has a button like and dislike, oh the rating itself, depending on it karma will be formed.
On the basis of karma, you can make all sorts of features for users, for example, when reaching 1000 likes, he gets a medal in his profile and so on. I think I explained the meaning! thank

**Comment by aspittel** [comment]
Hey @Butonix, thanks for the feature suggestion! We do have profile badges, and we're working on milestone notifications for when you get to certain points on your posts. But, for now downvotes and public Karma aren't part of the feature road map. Thanks again for filling out this issue!
