### ISSUE TITLE
Add tags automatically to posts

### ISSUE THREAD

**Issue by mrm8488** [thepracticaldev/dev.to#1934]
I was thinking about the feature of **tag the posts "level"** (beginner, intermediate, pro and so on). I thought it could be confusing for the user to determine which "level" is his/her post.

Fortunately, Nowadays, **we can use Machine Learning and last NLP methods to do that kind of tasks automatically.**

On the other hand, we could use this techniques even for tag posts categories, not friendly comments and so on.

**What we need?**
We would need a big dataset of labelled posts to start working on it.

**Comment by maestromac** [comment]
Thank you for this issue @mrm8488 . This is a nice to have and it could be on our future roadmap.

**Comment by bigblind** [comment]
I think this could work for topics in general, similar to how Github tags repositories, or we could suggest tags based on keywords in the text similar to the StackOverflow question editor.
