### ISSUE TITLE
Runkit regression error: double-quotes now disallowed in preamble

### ISSUE THREAD

**Issue by glebec** [thepracticaldev/dev.to#1937]
**Describe the bug**

Double quotes in runkit tag preambles now cause errors ("Runkit tag is invalid") when trying to preview (and maybe other contexts).

The runkit tag on dev.to used to allow double-quoted strings in the preamble. Minimal Example:

```
{% runkit "" %}
{% endrunkit %}
```

Realistic example:

```
{% runkit
const str = "hello"
%}
console.log(str)
{% endrunkit %}
```

As of #1808, this has now regressed without any clear documentation explicitly disallowing double quotes. It looks like that PR was seeking to make sanitization of `">` sequences more aggressive, but it either accidentally deleted the `>` character or else overlooked that double quotes are a normal token for JS source code.

When an article containing runkit tags with double quotes in the preamble is previewed, an error message saying the tag is invalid is now displayed.

**To Reproduce**

Attempt to preview an article containing this minimal example:

```
{% runkit "" %}
{% endrunkit %}
```

The "Runkit tag is invalid" error is displayed to the user.

**Expected behavior**

- Runkit preambles may contain double-quotes (ideal), OR
- Explicit and obvious documentation that double-quoted strings may not be used in runkit preambles is displayed (workaround / hack / less ideal)

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version 72.0.3626.119

**Additional context**

- This is an issue version of [this PR comment](https://github.com/thepracticaldev/dev.to/pull/1808/files#r261752521).

This can be fixed via:

```diff
-raise StandardError, "Runkit tag is invalid" if markup.include? "\""
+raise StandardError, "Runkit tag is invalid" if markup.include? "\">"
```

But it should first be verified that the latter addresses whatever security concerns motivated the original change.

**Comment by Zhao-Andy** [comment]
Hey @glebec, thanks for the issue. I think we'll have to revisit the implementation of the Runkit tag since it's a bit insecure as well as faulty in general.
