### ISSUE TITLE
RSS feed loading incorrect authors

### ISSUE THREAD

**Issue by Link2Twenty** [thepracticaldev/dev.to#1940]
**Describe the bug**
The RSS feed is loading in everyone's posts rather than the specified users

**To Reproduce**

1. Go to https://dev.to/feed/link2twenty
2. See error

**Expected behavior**
Posts should all have the correct author

**Additional context**
I use the feed on my website https://link2twenty.github.io/ and it looks like I'm stealing peoples posts 😅

**Comment by vizvamitra** [comment]
same here with [evilmartians feed](https://dev.to/feed/evilmartians). First wrong records got into feed at 2019-03-01T18:16:44+00:00
