### ISSUE TITLE
RSS Link and GUID URL have an extra slash in the URL

### ISSUE THREAD

**Issue by shindakun** [thepracticaldev/dev.to#1942]
**Describe the bug**

- URLs in the Link and GUID field in RSS have an extra slash, `https://dev.to//simo97/djangos-world-cms-1aec`

**To Reproduce**

1. Go to https://dev.to/feed/shindakun
2. Notice the GUID and Link for each RSS entry (see screenshot)

**Expected behavior**

Slash should not be there.

**Screenshots**

![screen shot 2019-03-01 at 2 56 59 pm](https://user-images.githubusercontent.com/319128/53671290-922d8980-3c32-11e9-8337-daa410e9fc3f.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version 72.0.3626.119

**Suspected Cause**

- Looks like it's caused by an extra slash in feed.rss.builder.

https://github.com/thepracticaldev/dev.to/blob/7d6c85a29490cab49558ea03a5669eea2f0f458c/app/views/articles/feed.rss.builder#L17-L18

Will try to test locally once I'm home this evening, can have a PR up as soon as it's confirmed and approved.

**Comment by Zhao-Andy** [comment]
Hit the nail on the head there! ✅ Yep, there's an extra slash since the first character of `article.path` is `/`.
