### ISSUE TITLE
500 on dashboard

### ISSUE THREAD

**Issue by chinchang** [thepracticaldev/dev.to#1946]
**Describe the bug**
Getting 500 on dashboard

**To Reproduce**
1. Visit https://dev.to/dashboard

**Expected behavior**

Dashboard should open.

**Screenshots**
![screenshot 2019-03-02 19 07 35](https://user-images.githubusercontent.com/379918/53682746-ae0e5980-3d1e-11e9-8719-ac4d314c67c4.png)

**Desktop (please complete the following information):**

- OS: Mojave
- Browser: Chrome
- Version: 72

**Comment by jessleenyc** [comment]
@chinchang are you still experiencing this?

**Comment by chinchang** [comment]
nope. working now :)
