### ISSUE TITLE
No text in follow button

### ISSUE THREAD

**Issue by thomasbnt** [thepracticaldev/dev.to#1948]
**Describe the bug**
The button to follow has no writing and therefore in this case we can neither follow/no longer follow, nor see if this person is in our subscriptions.

**To Reproduce**
See any post on dev.to.

**Expected behavior**
See the writing as before.

**Screenshots**

![bugdevto_3456765432345678](https://user-images.githubusercontent.com/14293805/53683375-68429880-3d00-11e9-81ae-78c042053124.gif)

**Desktop**

- OS: Ubuntu 16 04
- Browser : Google Chrome
- Version : Version 72.0.3626.119 (Official Build) (64 bits)

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by bigblind** [comment]
That's odd. In Chrome on macOS, the button has text. I went to Damien cosset's profile to make sure it wasn't a text color issue, but that doesn't seem to be the case.

Could this be an Ubuntu+chrome specific bug?

**Comment by thomasbnt** [comment]
Hmmm.. I just looked right now and apparently it was either on my side or on the server side but then you would have to know what was blocking it...
![devto_bug_23456765432345678](https://user-images.githubusercontent.com/14293805/53699060-94cfe080-3de4-11e9-8ad8-2b5b76594128.gif)

**Comment by Glennmen** [comment]
Not sure if this is related but DEV was having some server issues yesterday.

**Comment by thomasbnt** [comment]
@Glennmen I also noticed the dev.to server problem, after as long as it is now fixed, it's fine!

**Comment by jessleenyc** [comment]
I'm going to close this since you're not experiencing the issue anymore! If anyone else sees no text on follow buttons, please open a new issue. Thanks!
