### ISSUE TITLE
Post related content appears twice after comments of post

### ISSUE THREAD

**Issue by GiorgosK** [thepracticaldev/dev.to#1949]
A related post appears twice after post and comments 

**To Reproduce**
Have seen it on this post https://dev.to/psnebc/install-drupal-console-536g 
and the double post is the "101 Bash Commands and Tips for Beginners to Experts" that appears on 2 different place.  Have a look at screenshot but perhaps you can see it visiting the URL

NOTE: both times I tried to visit the URL I got first a "500 Error" and then on the 2nd attempt I would get the actual content.  Perhaps its coincidental though.

**Expected behavior**
Perhaps this space should be given to another post 

**Screenshots**
![double related](https://user-images.githubusercontent.com/520704/53683668-3c2d1480-3d0c-11e9-80a3-b80faba4cdab.png)

**Comment by jessleenyc** [comment]
Ah thanks, I can see why that'd be a bit strange. I don't think we currently check articles against what's displayed in either of those sections.
