### ISSUE TITLE
Markdown not working properly?

### ISSUE THREAD

**Issue by antsanchez** [thepracticaldev/dev.to#1950]
**Describe the bug**
The titles 4, 5 and 6 of this article: https://dev.to/asanchez/from-php-to-go-arrays-3cfg are not being represented as titles. The markdown, however, is correct. On my website (Hugo), it is working properly:https://asanchez.dev/blog/from-php-to-go-arrays/

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser: Chrome, Safari, Firefox

**Smartphone (please complete the following information):**

- Device: iPhone, Sony Xperia
- OS: iOS, Android
- Browser: Chrome, Safari, Firefox

**Comment by Glennmen** [comment]
I think you need a tab between the code block and the title in order for it to work correctly.

**Comment by antsanchez** [comment]
I fixed it putting the Fixed</pre> tag of the code blog before in another line as the opening <pre> tag. I don't know why, but it is working like this. This must be a bug anyway, in some other markdown editors, it is working properly.

**Comment by Zhao-Andy** [comment]
Hey @antsanchez, you already know this but I left a comment in the post. :)

For anyone else seeing this, we recommend using code blocks like you would with Markdown (using triple backticks), since writing direct HTML into your post works but is not supported nor recommended.
