### ISSUE TITLE
Quotation marks around titles when sharing on Twitter

### ISSUE THREAD

**Issue by benjaminmodayil** [thepracticaldev/dev.to#197]
# _Feature_

### Request

Addition of quotation marks around titles for Twitter-sharing.

### Definition of Done

When Twitter-shared articles have quotations around their titles.

### Screenshots

![screen shot 2018-04-15 at 9 38 33 am](https://user-images.githubusercontent.com/12306850/38779053-0bdb38de-4091-11e8-96ea-e479a029baaf.png)

![screen shot 2018-04-15 at 9 40 04 am](https://user-images.githubusercontent.com/12306850/38779054-0be71cda-4091-11e8-9b11-df3cfd10d19b.png)

### Notes

By default, there is a title and link shared when clicking the share to Twitter button in dev.to. It's more of an enhancement to add the quotation marks to the title so the slight confusion of the linked Kent C. Dodds's (attached) tweet doesn't make you think that he is the maintainer of Babel. Or, when sharing another article with a personal pronoun, it's not assumed the article is talking about the person that shared it.

**Comment by jessleenyc** [comment]
@benjaminmodayil thanks for the request -- we've updated!
