### ISSUE TITLE
(github tag) broken relative links in anchor tags

### ISSUE THREAD

**Issue by leonardosnt** [thepracticaldev/dev.to#1976]
**Describe the bug**
Relative links in **a**nchor tags doesn't get replaced by absolute links...

**To Reproduce**

1. Go to https://dev.to/mkrl/atomic-powered-fibonacci-indentation-2cpb
2. Click on **the gif in the github tag**
3. Get 404

**Expected behavior**
It should replace the relative (anchor/etc) links with the absolute link, like it does with images.

**Screenshots**

**Cursor hovering the image:**
![](https://user-images.githubusercontent.com/13869336/53768494-c5347f00-3eb7-11e9-813d-cdde103f72c9.png)

![](https://user-images.githubusercontent.com/13869336/53768495-c665ac00-3eb7-11e9-9bea-897b62685520.png)

**Additional context**
I guess this https://github.com/thepracticaldev/dev.to/blob/b271e969653d96c3a4ab111e9c1c931583285cc4/app/liquid_tags/github_tag/github_readme_tag.rb#L47-L56 should be applied to all "links", no only images.

**Comment by Zhao-Andy** [comment]
Thanks for the bug report and details! This is approved if anyone wants to work on it.
