### ISSUE TITLE
Can't save post with published: true

### ISSUE THREAD

**Issue by LaundroMat** [thepracticaldev/dev.to#1978]
**Describe the bug**
Can't publish previously saved draft.

Error:

> Error 503 first byte timeout
> first byte timeout
> 
> Guru Mediation:
> Details: cache-den19638-DEN 1551785830 3263568485
> 
> Varnish cache server
> 

**To Reproduce**

1. Go to https://dev.to/kanochart/embedding-a-survey-into-app-or-website-5blh-temp-slug-302596/edit
2. Change publised from false to true
3. Save post

**Expected behavior**
That there's no error 

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome, latest version

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by aexol** [comment]
mee to

**Comment by Glennmen** [comment]
I think DEV is having server issues again. I am getting 500 errors on different pages.

**Comment by mstruve** [comment]
Same, getting 500 errors. This happened to me yesterday as well around the same time. Maybe a cache expires causing extra load on the servers right around now. Let me know if you guys need help with anything!

**Comment by benhalpern** [comment]
Hi everyone. We had an app-wide slow down this morning. Sorry for the problems. It settled down, we'll work to make sure it doesn't happen again.
