### ISSUE TITLE
500 errors and slow responses

### ISSUE THREAD

**Issue by johnpapa** [thepracticaldev/dev.to#1979]
This morning the dev.to site is very slow to respond and often I get 500 server errors. 

I tried on laptop in chrome and in iOS chrome and safari. 

Not sure what else to provide.

**Comment by benhalpern** [comment]
Hey John, we had a site-wide issue with database connection timeouts affecting origin server traffic. It largely affected backend traffic like dashboard/editor etc. Not reader traffic. We'll work to make sure this doesn't happen very often.

**Comment by johnpapa** [comment]
Thanks for the details. 

I added an issue because the 500 error had a link for creating one. In future should we do that?

**Comment by benhalpern** [comment]
We're pretty aware of 500s. The issue is a nice-to-have. We'd never complain about it but it's a very optional thing. It's most helpful if there is a specific action that is serving an unhandled error but don't sweat it in general. We may remove that link or make it more clear.

**Comment by johnpapa** [comment]
No worries. Glad it worked out.
