### ISSUE TITLE
Create links for tags  everywhere they appear

### ISSUE THREAD

**Issue by johnpapa** [thepracticaldev/dev.to#1991]
When I look at a post, in the many places that we can, I'd like to be able to click on the tags to see more like this. A consistent UX would be helpful on this, too.

Here is a summary view of a post in my dashboard where the tags are not links today

![image](https://user-images.githubusercontent.com/1202528/53888047-860a4900-3ff1-11e9-9c96-644076b23328.png)

Here they are links, with underlines in the page https://dev.to/t/webdev

![image](https://user-images.githubusercontent.com/1202528/53888098-a5a17180-3ff1-11e9-8c74-2e75fedd1c19.png)

Here they are links with a color in the post itself

![image](https://user-images.githubusercontent.com/1202528/53888145-beaa2280-3ff1-11e9-8090-89ce970f6b50.png)

**Comment by jessleenyc** [comment]
Yeah that makes sense. I think the colors would be too distracting on the indexes but this is approved for anyone who wants to add tag links to the dashboard!

**Comment by bolariin** [comment]
Hi @jessleenyc, I would love try to resolve the issue.

**Comment by jessleenyc** [comment]
@bolariin go for it!

**Comment by bolariin** [comment]
@jessleenyc I have a question about other locations where tags are used without links. I found the file responsible for tags on the dasboard but I can't find any other locations where tags don't have links.

**Comment by jessleenyc** [comment]
@bolariin adding it to the dashboard for now makes sense. I noticed you had opened/closed a PR. Everything OK?

**Comment by bolariin** [comment]
@jessleenyc Yeah, I didn't know renaming a branch deleted the old branch.

**Comment by johnpapa** [comment]
excellent! thanks!

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/2088 . If we overlooked something or there's other part of the site that need this feature, please let us know!
