### ISSUE TITLE
About page is out of date

### ISSUE THREAD

**Issue by JoshCheek** [thepracticaldev/dev.to#1992]
The [about](https://dev.to/about) page is not up to date with the [Readme](https://github.com/thepracticaldev/dev.to/tree/a17cfe7d335cbf15fd70208e9cb6e3904cfe0a20#core-team)

![screen shot 2019-03-06 at 11 14 35 am](https://user-images.githubusercontent.com/77495/53900373-09cc3180-4002-11e9-9847-9ac688918df1.png)

**Comment by jessleenyc** [comment]
Oh yeah! We should add the whole team...maybe we can make that as part of the onboarding process in the future.

**Comment by Glennmen** [comment]
Maybe also worth mentioning that not every team member is in [The DEV Team](https://dev.to/devteam) organisation.

![image](https://user-images.githubusercontent.com/11406433/54160881-f8938280-4450-11e9-8645-eee016e51b4b.png)

**Comment by jessleenyc** [comment]
Ah, @aspittel isn't on there because we don't have a way for one person to be part of multiple orgs yet...and she's the org admin for https://dev.to/learncodefromus!

**Comment by Glennmen** [comment]
Isn't @lightalloy also not part of the team?

**Comment by desirottman** [comment]
@jessleenyc since members can be part of multiple teams now, is this one good to take a crack at?

**Comment by jessleenyc** [comment]
Going to close this since the DEV Team organization reflects our current team (have also added this step to our internal onboarding), as does the readme. For now, we're only including leadership on the about page.
