### ISSUE TITLE
Changing your username leads to 503 "First byte timeout"

### ISSUE THREAD

**Issue by twhite96** [thepracticaldev/dev.to#1994]
**Describe the bug**
Varnish cache first byte timeout error when changing username

**To Reproduce**
1. Go to profile
2. Click on username
3. Type new username
4. Press submit
5. 503 first bytes timeout Guru Mediation

**Expected behavior**
Expected to change my username after hitting submit

**Screenshots**

![image](https://cl.ly/294cd1039c9a/Screen%252520Recording%2525202019-03-06%252520at%25252005.43%252520PM.gif)

**Smartphone (please complete the following information):**
 - Device: 2015 iMac 5k 27"
 - OS: macOS 10.14.4

**Additional context**

I've done everything I could on my end but this seems to be a server problem.

**Comment by twhite96** [comment]
This is the same problem I hit in issue https://github.com/thepracticaldev/DEV-ios/issues/132#issue-417052656

**Comment by Zhao-Andy** [comment]
Hey @twhite96, do you mind trying again? If it errors out, we'll follow the backtrace and see where it leads us 🕵️

**Comment by twhite96** [comment]
@Zhao-Andy sure. Give me a minute.

**Comment by twhite96** [comment]
@Zhao-Andy still getting the error.

**Comment by Zhao-Andy** [comment]
Looks like this timed out:
```ruby
def check_for_username_change
    if username_changed?
      self.old_old_username = old_username
      self.old_username = username_was
      chat_channels.find_each do |c|
        c.slug = c.slug.gsub(username_was, username)
        c.save
      end
      articles.find_each do |a|
        a.path = a.path.gsub(username_was, username)
        a.save
      end
    end
  end
```

This should probably be run asynchronously, or combined into the next method:
```ruby
def conditionally_resave_articles
    if core_profile_details_changed? && !user.banned
      delay.resave_articles
    end
  end
```

I think we might want to revisit all of the callbacks in `user.rb`, since it seems like these two methods are too related.

**Comment by twhite96** [comment]
I may be able to look at this. I finally got my machine fixed and Ruby installed. Lmk if you think this is something I could do skill wise 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by setevoy2** [comment]
Got the same error today trying to save a draft (a big one).

> Chromium
> Version 72.0.3626.121 (Official Build) Arch Linux (64-bit)

**Comment by Zhao-Andy** [comment]
@twhite96 sorry for the late reply. I'll raise this to discuss this week to see if you can take it on, or at least labeled approved in general.

**Comment by gugadev** [comment]
@Zhao-Andy Can users requests to be changed "manually"?

**Comment by jessleenyc** [comment]
@twhite96 feel free to give this a go - first thought is we'll want to add some async jobs here.

**Comment by twhite96** [comment]
Okay. Will work on this some this weekend.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Zhao-Andy** [comment]
Hey @twhite96, we made some changes that should lower the time it takes to update a user. It wasn't directly related to this issue though so this issue might still be outstanding. If you'd like to try updating your username again, let us know how it goes!

If you successfully update your username, I think it's best to close this issue and I can write up a new one describing refactoring the code we detailed above. If it doesn't work, we can keep this issue open in case other people are having this issue and want to chime in.

**Comment by twhite96** [comment]
>Hey @twhite96, we made some changes that should lower the time it takes to update a user. It wasn't directly related to this issue though so this issue might still be outstanding. If you'd like to try updating your username again, let us know how it goes! ...

@Zhao-Andy getting a 500 error.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by twhite96** [comment]
![GitHawk Upload by twhite96](https://i.imgur.com/ZRzBii2.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by twhite96** [comment]
Seems to be fixed! It says this issue is still open though.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rhymes** [comment]
@twhite96 I think you can close the issue being the original author, sometimes it happens that issues get solved but not closed :)
