### ISSUE TITLE
Post date is suffixed with undefined when date is more than a year ago

### ISSUE THREAD

**Issue by haved** [thepracticaldev/dev.to#1995]
**Describe the bug**
When seeing a "card" for a post, the date is suffixed with undefined if the post is older than a year.
This "card" is seen both on a user page and in your reading list if you save an old post.

**To Reproduce**

1. Go to dev.to/ben
3. Scroll down to a post from before March 7
4. See "undefined"

**Expected behavior**
Not seeing undefined

**Screenshots**
![image](https://user-images.githubusercontent.com/3748845/53943618-bcad9580-40bd-11e9-8c44-d5876346a2a1.png)

**Desktop (please complete the following information):**

- OS: Manjaro Linux 64 bit
- Browser: Firefox & Chromium
- Version: 65 & 72 respectivly

**Additional context**
I'm going to have a go at fixing this

**Comment by haved** [comment]
It all comes down to `timeAgo()` in `/app/assets/javascrips/utilities/timeAgo.js`.
It is possible for the function to not return anything, when the time ago is more than the highest value in the `times` array, which is a year.
A simple fix is to add `return '';` to the last line.

I am curious, though, if the time returned from `new Date() / 1000` is in the same timezone as `article.published_at_int` in `buildArticleHTML.js.erb`. Otherwise time ago would be wrong.
The time ago string is not included either way, it seems, as I don't see it on any posts.

Also, are we sure we want to assume every month and year is the same length?

I'll write one that takes these things into considerations

**Comment by haved** [comment]
So I'd like to maybe have some / write some documentation for how time is handled.
Is the `article.published_as_int` in the time zone of the server, author or reader?
Is the actual user-facing date string in their time zone, the server time zone or the authors time zone?
If it's not the server time, is the time zone of a post stored in some variable?
Pinging @benhalpern, seeing as he is the author of `timeAgo.js`.
I now see that the last change to that file was two days ago. I'll wait for confirmation before doing more.

**Comment by haved** [comment]
I now see in article.rb that `published_at` is set to `Time.current` (server time). Therefore I suggest replacing `published_as_int` with `seconds_since_published`, with `Time.current` subtracted on the server.

**Comment by haved** [comment]
Also, the `readable_publish_date` is based on the "relevant time", either `published_at` or `crossposted_at`. [See here](https://github.com/thepracticaldev/dev.to/blob/5c116c48812d884454908d055b2b1c5d0eef5864/app/models/article.rb#L358)

The same should be used for `published_as_int`, and the proposed `seconds_since_published`
[Here](https://github.com/thepracticaldev/dev.to/blob/5c116c48812d884454908d055b2b1c5d0eef5864/app/models/article.rb#L145)

**Comment by lightalloy** [comment]
Hi, @haved. Thanks for submitting the bug.
Both `published_at_int` and `new Date() / 1000` will return unix time in seconds, without any timezone information. 
As for the same length of the months and years, in my opinion, it's good enough to provide information about how long ago an article was posted. It isn't really important if it's a month or a month + 1 day.
I would go with just fixing the `undefined` label.

**Comment by haved** [comment]
Ok, thanks for the reply.
I now understand that timezones aren't an issue, but I'm still worried about `relevant_time` not being accounted for in `published_in_seconds`.
Also, when a unix time is formatted into a date on the server, what timezone is used? Should this be in the users time?

Unrelated, I could write a fix for the timeAgo() function, but I'm not sure I'll open a pull request when Ben last modified the file three days ago, and it seems like a work in progress.

**Comment by rhymes** [comment]
@haved the server runs on UTC, the time is sent to the client and the client should do the calculation to adapt it to ts own zone. This avoids the need to store on the server a setting with the user's timezone

BTW I think you should totally send a PR if you found a bug :)

**Comment by maestromac** [comment]
Thanks for chiming in @rhymes @lightalloy . Resolved with https://github.com/thepracticaldev/dev.to/pull/2002
