### ISSUE TITLE
Sporadic 404's when editing unpublshed posts

### ISSUE THREAD

**Issue by buntine** [thepracticaldev/dev.to#2]
I've had this a bunch of times when I am viewing an unpublished post. I click "save", view the unpublished preview, and then press "edit".

About 40% - 50% of the time I get a 404. The problem persists if I reload the page. It tends to last a for several minutes.

It's potentially an issue with trying to load mixed content as I can see there is an error in console about blocked content from "http://dev.to/enter". More info: https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content

I wish I could find the pattern for this, but maybe the server side logs can help. For reference, I am seeing the issue right now.

**Comment by benhalpern** [comment]
Thanks for this report. I'm investigating.

**Comment by benhalpern** [comment]
I'm going to close this because I think I fixed it in general. The underlying caching issue remains but this should be way less common and is a known thing we're working on internally to fix once and for all.
