### ISSUE TITLE
menu is broken

### ISSUE THREAD

**Issue by jannisfink** [thepracticaldev/dev.to#20]
I've attached a screenshot. Somehow, parts of the menu are hidden. I have not selected anything, the selection happens just when I click on the menu button. I've tried the homepage and some other pages, behavior is the same.

- Nexus 5X (Display & Screen size both set to small)
- Firefox 51.0.3

![tmp_19044-screenshot_20170222-223428460354380](https://cloud.githubusercontent.com/assets/17259088/23233434/22ae9626-f94f-11e6-90a4-763a70338999.png)

**Comment by jannisfink** [comment]
Okay, I've done some digging. Happens the same way in Chrome (current version: 56.0.2924.87).
Open devtools, press `Toggle device toolbar` (`ctrl+shift+m`) and choose a device. I could reproduce it with Nexus 5X and Galaxy S5 settings.

Then reload the page (maybe empty cache first) and you should see something like that in the console:

```
Uncaught TypeError: Cannot read property 'isPreloadable' of null
    at XMLHttpRequest.e.onreadystatechange (base-ec2ac98….js:1)
```

links to [this script](https://practicaldev-herokuapp-com.global.ssl.fastly.net/assets/base-ec2ac9845d485fa3328d1c3883ef56f7a00fdfac6c360e0bd4f39947b5187db2.js), line 1, column 18422

Somehow, the variable `InstantClick` seems to be `null`. But I'm not really sure why. The js file is the first and only js file loaded in both success and error case. And it seems to be random, I was not able to recognize a pattern of why it works some times and some other times not. But it seems like you have to be logged in for this to happen.

I have recorded and saved the HAR for the erroneous case, but are not allowed to upload it here, even if I put it in a ZIP-archive first. If you need it, I can put a link in here from where to download it.

**Comment by gleeds** [comment]
Not sure if it's the same issue, but the menu dropdown is also broken on a 4k monitor :raised_hands:  since you can't mouse over it. 
<img width="2243" alt="screen shot 2017-05-22 at 5 44 06 pm" src="https://cloud.githubusercontent.com/assets/1095404/26331487/c3ed4110-3f16-11e7-83df-18802da39d5a.png">

**Comment by maestromac** [comment]
Hey @jannisfink, sorry we didn't reply sooner. That should be resolved. Can you please help us verify that it's working now on firefox?. 

Hello @gleeds, that is also resolved. Thank you for alerting us!

**Comment by jannisfink** [comment]
Jup, works just fine. No problems with current Firefox. Thank you!
