### ISSUE TITLE
[Feature Request] Prepopulate tag removal textbox

### ISSUE THREAD

**Issue by davefollett** [thepracticaldev/dev.to#2001]
It might be handy to include a block of default text into the tag removal's reason box.  This could help ensure the tone is kept nice and the messages be consistent.

**Describe the solution you'd like**
This could be an example of what the text box could be pre-populated with:

> Hi. In an effort to keep dev.to's tag system as accurate as possible, I'm removing the **< TAG >** tag from your post.   **< Reason for removal - be super kind >**
>
> If you disagree regarding your tag removal, please contact yo@dev.to and explain why.
>
> 🙏 Thank you for your contribution to dev.to and I look forward to reading more articles from you.

**Comment by maestromac** [comment]
Thank you for this feature request @davefollett . We should definitely have this for our moderators.

**Comment by jessleenyc** [comment]
Oh yeah, great call and love the copy. This is approved for anyone who wants to grab it!

**Comment by Zhao-Andy** [comment]
Resolved by #2063
