### ISSUE TITLE
Issue Uploading a Cover Image on Safari

### ISSUE THREAD

**Issue by michael-tharrington** [thepracticaldev/dev.to#2008]
A user reported having troubles uploading their cover image in Safari:

"Hey hey team!

Just wanted to reach out cause I think I found an issue with image uploading for Safari.

I was trying to upload a cover image for my post https://dev.to/michael/silencing-the-lizard-brain-4leg but every time I hit done, nothing would show up.

Finally thought to look the console window and saw this on Safari..."

<img width="1412" alt="Screen Shot 2019-03-07 at 3 32 43 PM" src="https://user-images.githubusercontent.com/16007075/54051952-0fb44500-41b1-11e9-9f14-834c539248c0.png">

**Additional context**
- They were using our v2 editor.
- Here's a link to the image too if it helps - https://unsplash.com/photos/RxZUEaa4fik

**Comment by jessleenyc** [comment]
@michaellee i think this might have been because the file size was too large. I just downloaded the exact file and the same thing happened to me, but when I uploaded it as a smaller file it worked fine. We should have better error messaging there.

**Comment by rhymes** [comment]
@jessleenyc I guess the PR - #2018 - I sent for #936 should catch this as well 🥳😂

**Comment by michaellee** [comment]
Thanks for the feedback @jessleenyc @rhymes @michael-tharrington! I resized and it worked. Would be great to have even just a little blurb to indicate the max for the image.
