### ISSUE TITLE
Error when attempting to access unfinished/unpublished post

### ISSUE THREAD

**Issue by joshuaalm** [thepracticaldev/dev.to#2014]
**Describe the bug**
Going in to attempt to finish a long-neglected unfinished post, I get an error 500.

**To Reproduce**

1. Go to my Dashboard
2. Click on the title or Edit button of any one of the last three of four unpublished posts
3. See error

**Expected behavior**
View and/or edit post

**Desktop (please complete the following information):**

- OS: Windows 10 1809
- Browser Mozilla 
- Version 66.0b12

It may be relevant that I originally signed up with an account linked to my Twitter handle, then started using my GitHub account, and after submitting an issue relating to that, my account was fixed.  Possibly the latter posts were created after my GitHub account became my primary means of logging onto dev.to.

**Comment by jessleenyc** [comment]
Hm, ok. Thanks for reporting and the detailed notes on your account history -- we'll take a look at this.

**Comment by jessleenyc** [comment]
@joshuaalm are you still receiving this issue? I think this might have occurred during some downtime we had over the weekend.

**Comment by joshuaalm** [comment]
Jess,

Thank you for reaching out. Yes, I get “You have lost your way” when I
click the link to the post, and “500 Error It’s not you, it’s me.” (Kudos
to the team member(s) behind these error pages; they’re somewhat
entertaining)

**Comment by Zhao-Andy** [comment]
Hey @joshuaalm, sorry about that bug. I think somewhere along the way your posts' `path` columns did not update properly to account for your new dev.to username. We've manually updated them, and you should be able to edit and view your drafts now.

**Comment by jessleenyc** [comment]
Seems like this has been resolved so I'm going to close the issue. Feel free to ping me if that's not the case and I'll reopen. Thanks!
