### ISSUE TITLE
Impossible to update an already published article

### ISSUE THREAD

**Issue by pauloxnet** [thepracticaldev/dev.to#2016]
**Describe the bug**
Impossible to update an already published article because an unclear error message.

**To Reproduce**

1. Go to 'https://dev.to/articles/2883'
2. Click on 'Save post'
3. Scroll down to 'Top of the page'
4. See error: "1 error prohibited this article from being saved: Main image background hex color is invalid"

**Expected behavior**
I expected to view my article correctly saved with my updates.

**Desktop (please complete the following information):**

- OS: Ubuntu GNU/Linux 18.10 64bit
- Browser: Chromium
- Version: 72.0.3626.121
- Extensions: No extensions installed

**Additional context**
I can correctly edit and save my other articles in the same OS/Browser/Session.

I tried also to remove all the content from the article and the cover image from the metadata but the error persist and I can't update my published article.

**Comment by jessleenyc** [comment]
@pauloxnet  I believe I fixed the error you were receiving, can you try editing the post again now?

**Comment by pauloxnet** [comment]
@jessleenyc It works now thanks for fixing the bug

**Comment by rpalo** [comment]
I'm seeing this same issue.  I'm trying to add a canonical_url and series fields to the metadata for [this post](https://dev.to/rpalo/vue-on-django-part-2/), but it won't let me save for the same error message.  Would you prefer I open a fresh issue?

**Comment by maestromac** [comment]
@rpalo does it still fail when you only update the `series` field?

yes, please create a new issue. Thank you!
