### ISSUE TITLE
Varnish cache server 503 first byte timeout

### ISSUE THREAD

**Issue by setevoy2** [thepracticaldev/dev.to#2017]
**Describe the bug**

Not able to save a long-read post (48462 symbols) - after pressing the "SAVE POST" button - got 503 error (from Varnish?)

**To Reproduce**

1. Go to 'dashboard'
2. Click on a post's 'Edit' button
3. Click on a post's 'Save Post' button
4. See the "**Error 503 first byte timeout**"

**Expected behavior**
Post be saved.

**Screenshots**
![Screenshot_20190310_105036](https://user-images.githubusercontent.com/7965314/54084064-b5dc8800-4334-11e9-9c3e-0940cbd52364.png)

**Desktop (please complete the following information):**

- OS: Arch Linux (64-bit)
- Browser Chromium
- VersionVersion 72.0.3626.121 (Official Build)
- Browser Firefox Quantum
- VersionVersion 65.02

**Additional context**
Full error's text returned:

> Error 503 first byte timeout
> first byte timeout
> 
> Guru Mediation:
> Details: cache-den19623-DEN 1552213081 3641372492
> 
> Varnish cache server

Draft's URL: https://dev.to/setevoy/prometheus-rtfm-blog-monitoring-set-up-with-ansible--grafana-loki-and-promtail-38kb-temp-slug-7212106/edit

**Comment by jessleenyc** [comment]
Hey @setevoy2 sorry about that.  Looks like that post is published now? Did you change the post or did it eventually work?

**Comment by setevoy2** [comment]
Hi, @jessleenyc 
Well - I just removed 2/3 of the text :-|

**Comment by jessleenyc** [comment]
Hmm ok. We were experiencing some issues over the weekend so it could have been from that, or what you're suggesting with process that amount of content and timing out. Would you mind trying again?

**Comment by setevoy2** [comment]
Yeah - it works now, thanks. Posted full content without any issues.

**Comment by maestromac** [comment]
Awesome to hear that @setevoy2 ! Closing

**Comment by takeabug** [comment]
@jessleenyc @maestromac This happens too when I try to change my username. There is no way to change it.

**Comment by setevoy2** [comment]
@takeabug Dev.to seems had the same issue today with its server(s) so your issue might happen because of this. 
I saw 503 couple of times today, also the site was working a bit slow sometimes.
Just my guess.

**Comment by Zhao-Andy** [comment]
@takeabug changing your username is currently a known issue: https://github.com/thepracticaldev/dev.to/issues/1994
