### ISSUE TITLE
new post

### ISSUE THREAD

**Issue by devtox** [thepracticaldev/dev.to#2019]
**Describe the bug**
Cant post new post

**To Reproduce**

1. Go to 'New Post'
2. See error

**Expected behavior**

500 Error
It's not you, it's me.

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser Firefox

**Comment by Nilkamal** [comment]
Does this required to reproduce on firefox only? And to reproduce this on "dev.to" right?

**Comment by devtox** [comment]
Only on "dev.to". The same in other browser (Falkon)

**Comment by maestromac** [comment]
Hey @devtox , this seems to be a specific issue with your account. Please email yo@dev.to for more help.
