### ISSUE TITLE
Unable to log in when using iOS PWA

### ISSUE THREAD

**Issue by acflint** [thepracticaldev/dev.to#202]
### Current Behavior
When you save the website to the home screen of an iOS device running 11.3+, the app behaves as a Progress Web App, and does not open in Safari. When you try to log in with GitHub or Twitter, it opens Safari, where you can log in, but PWAs on iOS are sandboxed and don't share sessions with Safari so the login session does not carry over to the PWA.

### Expected Behavior
Either you can log in to Github\Twitter within the PWA, but I'm not sure if that's possible. Alternatively, there's an email\password login option.

### Additional Info (steps to replicate, device/browser, helpful links)
1. Add dev.to to an iOS 11.3 device home screen
2. Open dev.to from the new home screen icon
3. Try to login with github.

Keep up the great work, dev.to team!

**Comment by Zhao-Andy** [comment]
Hey @acflint, thanks for the heads up! To be clear, does logging in via the PWA fail completely, or does it do some strange redirect after logging in? Also I'm guessing it's the same behavior whether it's Twitter or GitHub right?

**Comment by acflint** [comment]
@Zhao-Andy the login is successful, but it's in Mobile Safari, and the login session isn't carried back over to the PWA, so when you return to the PWA it's still logged out. I don't have a Twitter account to confirm that behaviour, but since iOS PWAs don't share Safari session data, I assume it's the same. Thanks!

**Comment by JanDeDobbeleer** [comment]
Same happens when using the Twitter login. I did however find it seems to a bug on iOS rather than something to be fixed in the PWA.

**Comment by acflint** [comment]
The “fix” would be to allow username + password login instead of relying completely on oauth.

**Comment by JanDeDobbeleer** [comment]
If I look at app development, it's not an issue to use oauth when you're using a URI scheme to redirect to the app instead or an URL.

There doesn't seem to be a straightforward solution here, but this issue points to a possibility workaround: https://github.com/nolanlawson/pinafore/issues/45

**Comment by acflint** [comment]
Just as an FYI, I've tested this again iOS 12.1 and it's still an issue. Damn you, Apple!

**Comment by mornir** [comment]
I was going to open an issue on that exact topic. On iOS 12 I can't use dev.to in PWA mode while being authenticated via Twitter. It's a pity since dev.to looks great as a PWA 😃
After reading this thread, I now understand that this is a webkit issue. Apple is really not eager to fully support PWAs 😕

**Comment by jessleenyc** [comment]
From @l579:

https://medium.com/@jonnykalambay/progressive-web-apps-with-oauth-dont-repeat-my-mistake-16a4063ce113

**Comment by alireza267** [comment]
this solved my problem, hope to be useful
https://github.com/GoogleChromeLabs/pwacompat/issues/15

**Comment by mornir** [comment]
It seems that this issue will be fixed in iOS 12.2 :
https://twitter.com/mhartington/status/1089292031548145666

**Comment by giclo** [comment]
Now they made sure no one's using PWA in 12.2 - it's stateless - switch to another app and lose your cookie

**Comment by VyasPrachi** [comment]
Hello,
I have used PWA in my previously working asp.net mvc application. It is working fine in android and desktop. But in ios every time it shows my login page even though I have stored session. Please help me in IOS.

**Comment by mornir** [comment]
Auth redirect is working for me on iOS 12.2🥳

**Comment by jessleenyc** [comment]
Closing this since it's working on iOS 12.2!
