### ISSUE TITLE
Enable rubocop cops

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#2021]
**Is your feature request related to a problem? Please describe.**
Currently, many `rubocop` cops are disabled (see `.rubocop.yml`), I think it would be beneficial to enable most of them. In such a way at least the new code will follow the guidelines.

**Describe the solution you'd like**
I like the way how we dealt with the views linting problems (#1842) 
The similar approach is possible for the ruby code & the rubocop

The workflow I suggest:
- enable 1 cop from the `.rubocop.yml`
- fix related issues if possible
- if it's not possible (or optimal), add exceptions to the `.rubocop_todo.yml` (there're already some examples)
- make a pull request

For some cops, there are no violations in the code, so they could just be enabled.
I can prepare a list of cops to enable if this issue gets approved.

**Comment by keshavbiswa** [comment]
Can I work on this issue?

**Comment by JoppeDC** [comment]
Also interested!

**Comment by lightalloy** [comment]
@keshavbiswa @JoppeDC you're welcome.
I'll be posting lists of the cops you can work on.

**Comment by lightalloy** [comment]
- [ ] Style/Alias
- [ ] Style/ArrayJoin
- [ ] Style/Attr
- [ ] Style/CaseEquality
- [ ] Style/CharacterLiteral
- [ ] Style/ColonMethodCall
- [ ] Style/CommentAnnotation
- [ ] Style/PreferredHashMethods
- [ ] Style/DoubleNegation
- [ ] Style/EachWithObject
- [ ] Style/EmptyLiteral
- [ ] Style/EvenOdd
- [ ] Style/GuardClause
- [ ] Style/IfUnlessModifier
- [ ] Style/IfWithSemicolon
- [ ] Style/Lambda
- [ ] Style/LambdaCall
- [ ] Style/LineEndConcatenation
- [ ] Style/ModuleFunction
- [ ] Style/NegatedIf
- [ ] Style/NegatedWhile
- [ ] Style/NilComparison
- [ ] Style/Not
- [ ] Style/NumericLiterals
- [ ] Style/OneLineConditional
- [ ] Style/PercentLiteralDelimiters
- [ ] Style/PerlBackrefs
- [ ] Style/Proc
- [ ] Style/RaiseArgs
- [ ] Style/SelfAssignment
- [ ] Style/SingleLineMethods
- [ ] Style/SpecialGlobalVars
- [ ] Style/VariableInterpolation
- [ ] Style/WhenThen
- [ ] Style/WhileUntilModifier
- [ ] Style/WordArray

**Comment by lightalloy** [comment]
I suppose there're no violations to these cops, so they can just be enabled:

- [ ] Naming/AsciiIdentifiers
- [ ] Naming/FileName

**Comment by lightalloy** [comment]
- [ ] Rails/Delegate
- [ ] Rails/ActionFilter
- [ ] Rails/FindBy
- [ ] Rails/FindEach
- [ ] Rails/Output
- [ ] Rails/ReadWriteAttribute
- [ ] Rails/ScopeArgs
- [ ] Rails/Validation

**Comment by lightalloy** [comment]
- [ ] Performance/CaseWhenSplat
- [ ] Performance/Count
- [ ] Performance/Detect
- [ ] Performance/FlatMap
- [ ] Performance/ReverseEach
- [ ] Performance/Sample
- [ ] Performance/Size
- [ ] Performance/StringReplacement

**Comment by lightalloy** [comment]
- [ ] Layout/AlignParameters
- [ ] Layout/ConditionPosition
- [ ] Layout/InitialIndentation

**Comment by lightalloy** [comment]
- [ ] Lint/AmbiguousOperator
- [ ] Lint/AmbiguousRegexpLiteral
- [ ] Lint/AssignmentInCondition
- [ ] Lint/CircularArgumentReference
- [ ] Lint/DeprecatedClassMethods
- [ ] Lint/DuplicatedKey
- [ ] Lint/EachWithObjectArgument
- [ ] Lint/ElseLayout
- [ ] Lint/FormatParameterMismatch
- [ ] Lint/LiteralAsCondition
- [ ] Lint/LiteralInInterpolation
- [ ] Lint/Loop
- [ ] Lint/NestedMethodDefinition
- [ ] Lint/ParenthesesAsGroupedExpression
- [ ] Lint/RequireParentheses
- [ ] Lint/UnderscorePrefixedVariableName
- [ ] Lint/UnneededCopDisableDirective
- [ ] Lint/Void

**Comment by lightalloy** [comment]
Please, notify about the cops you're working on in this thread.
If you have any problems or questions, feel free to ask them in this thread or in your (draft) pull request.

**Comment by keshavbiswa** [comment]
Okay sure thanks :)

**Comment by cyrillefr** [comment]
Hello, I would like to participate too.
Is it too late to do the Performance cops ?

**Comment by Zhao-Andy** [comment]
I believe not, go for it!

**Comment by JoppeDC** [comment]
Havent gotten to it yet. So go ahead :)

**Comment by keshavbiswa** [comment]
@cyrillefr Go for it! I will work on Layout Cops :smile:

**Comment by venarius** [comment]
Will work on the Lint ones

**Comment by lightalloy** [comment]
Cops left to be fixed (from the `rubocop_todo`):
- [ ] Rails/HasManyOrHasOneDependent
- [ ] Rails/SkipsModelValidations
- [ ] Style/FormatString
- [ ] Style/TrivialAccessors
- [ ] Layout/AlignParameters
- [ ] Layout/ConditionPosition
- [ ] Layout/InitialIndentation

**Comment by lightalloy** [comment]
I think these cops should be enabled + exclude files that contain violations + configure max values where applicable:

- Metrics/ClassLength
- Metrics/ModuleLength
- Metrics/AbcSize
- Metrics/CyclomaticComplexity
- Style/GlobalVars
- Metrics/MethodLength
- Metrics/ParameterLists

**Comment by cyrillefr** [comment]
Hello,

I would like to take care of the first group of cops(rubocop_todo).
But before proceeding, I would like to put what I intend to do:

Rails/HasManyOrHasOneDependent
|→ 28 offenses for not specifying a :dependent option. To discard these offenses, I can add a :dependent :nullify(default value for :dependent).

Rails/SkipsModelValidations
|→ 45 offenses on spec files because update_column skips validation. I can change to update.
|→ 104 offenses on other files
- update_column skips validation: same as above
- touch skips validation: no other solution here than adding touch method to the whitelist (the docs indicates so).
- update_all skips validation: I can use the batch mode and update each objects rather than whitelisting update_all(I lack the functional knowledge to choose the best option). 

Layout: 177 offenses: I can fix with the automatic fix option of rubocop.

NB: I may be behind a few commits, so the number might be a little bit inaccurate, but of same order.
I did not ran any tests, so I have got no idea of new errors that may arise from these changes.

So, tell me if I may proceed this way.

**Comment by lightalloy** [comment]
Hey @cyrillefr 
I revised the cops list, and think that I should first discuss enabling and fixing `Rails/HasManyOrHasOneDependent` with the team.
As for the `Rails/SkipsModelValidations` now I think it shouldn't be enabled. Running some validations need running SQL-queries which will affect performance. `update_all` and `update_column` are fine if we use them consciously.
Fixing `Layout` cops should be straightforward, so feel free to fix them.

**Comment by lightalloy** [comment]
I made small updates to the config.
For now:
- `Rails/HasManyOrHasOneDependent` should be safe to be enabled, ` :dependent ` should be set to `:nullify` (as @cyrillefr suggested). I suggest making a separate pr for this fix.
- ` Layout/InitialIndentation` is still available to be fixed
- this comment is also relevant https://github.com/thepracticaldev/dev.to/issues/2021#issuecomment-477983728
