### ISSUE TITLE
Github-like :emoji:

### ISSUE THREAD

**Issue by Defman21** [thepracticaldev/dev.to#203]
# _TASK or Feature_
### Request or User Story
I'd like to type emojis using `:smiley:` for example.

### Definition of Done
* [ ] `:heart:` is ❤️ , not `:heart:`
* [ ] OPTIONAL: auto-complete popup

**Comment by Zhao-Andy** [comment]
Hey @Defman21, definitely a good feature. We'll be backlogging it for now. :)

**Comment by Defman21** [comment]
1. I think yes.
2. github-like (imho).

**Comment by Defman21** [comment]
un-stale.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/1653
