### ISSUE TITLE
Data export is not working

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#2031]
**Describe the bug**

A couple of days ago I requested the export of my content on dev.to, the requeste generated the notice message but then I've never received the email.

I went back to check https://dev.to/settings/misc and noticed that the feature is still disabled:

![Screenshot_2019-03-11 Settings - DEV Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/54131796-5d2fec80-4413-11e9-92ee-d62aacfa42ed.png)

which means that the async job in charge of exporting has not completed. It's either stuck or has died. That's also probably why I haven't received the email. 

**To Reproduce**

1. Go to https://dev.to/settings/misc
2. Scroll down to "Export content"
3. Request an export
4. Wait

**Expected behavior**

I'd expect the job to complete in a timely fashion, the email to be delivered and the feature to be re-enabled.

**Desktop (please complete the following information):**

- OS: macOS 10.14
- Browser: Firefox
- Version: 66

**Comment by rhymes** [comment]
I've received the email with the export around an hour ago, I've created another request to make sure that it's still working. I'll let you know if and when I receive it. 

I wonder if there's an issue with the queue...

**Comment by maestromac** [comment]
Thanks for the follow up @rhymes . Definitely sounds like a background job is backlogged.

**Comment by rhymes** [comment]
@maestromac well, it means the site is so popular that Delayed job is having troubles keeping up 😄

**Comment by rhymes** [comment]
unfortunately I'm in the same predicament. I tried again a few days ago but still... I reckon there's an issue with job prioritization in delayed job or something

**Comment by lightalloy** [comment]
Export should work now. Described in #2580 , fixed by #2612

**Comment by rhymes** [comment]
@lightalloy I still have my export disabled on the website :( I think it's because the job failed and my `export_requested` field has not been restored to `false`...

**Comment by maestromac** [comment]
Hey @rhymes , can you double check again to see if exporting is still disabled for you?

**Comment by rhymes** [comment]
@maestromac it was enabled, I requested a new export, it arrived quicker than the speed of light in my inbox, it's enabled again. It works 🎉 Thank you!
