### ISSUE TITLE
babel-preset-preact

### ISSUE THREAD

**Issue by Glennmen** [thepracticaldev/dev.to#2033]
I see @maestromac keeps closing jest update PR's because of `babel-preset-preact` not supporting babel 7.
https://github.com/thepracticaldev/dev.to/pull/2032#issuecomment-471581564

I found this new NPM package that I think is based on `babel-preset-preact`, it is only a week old though. 

`@henrikjoreteg/babel-preset-preact`
NPM link: https://www.npmjs.com/package/@henrikjoreteg/babel-preset-preact
Github link: https://github.com/HenrikJoreteg/preset-preact

I can easily make a PR with this new dependency, only don't know if there are any tests I can run to make sure everything still works correctly. Will running the pre-commit hook be enough?

**Comment by maestromac** [comment]
Thanks for suggestion @Glennmen . 
I've forked [babel-preset-preact](https://github.com/thepracticaldev/babel-preset-preact) and applied the babel 7 support to it so this will be taken cared of here https://github.com/thepracticaldev/dev.to/pull/2034

**Comment by Glennmen** [comment]
That is probably the best option for this library. 👍

**Comment by jessleenyc** [comment]
Awesome. Closing this!
