### ISSUE TITLE
Right hand side bar wraps below main content on wider screens

### ISSUE THREAD

**Issue by ptasker** [thepracticaldev/dev.to#204]
# _BUG_
### Current Behavior

On wider screens the right sidebar gets placed below the centre column, on the left.

### Expected Behavior

For the right sidebar to, you know, stay on the right :)

### Screenshots

<img width="2973" alt="monosnap 2018-04-27 14-54-30" src="https://user-images.githubusercontent.com/535651/39379982-f5401e0c-4a2a-11e8-8a17-9980c42328af.png">
<img width="2511" alt="monosnap 2018-04-27 14-55-22" src="https://user-images.githubusercontent.com/535651/39380006-091a8f66-4a2b-11e8-9efc-5443feebd1e1.png">

**Comment by ptasker** [comment]
For reference the browser width I noticed this is 2700px+

**Comment by Zhao-Andy** [comment]
Hey @ptasker, thanks for the heads up! We'll fix it soon.

**Comment by Zhao-Andy** [comment]
Believe this is fixed :) @ptasker let me know if otherwise.
