### ISSUE TITLE
Eternally pulsing animations make it impossible to actually read an article.

### ISSUE THREAD

**Issue by icefoxen** [thepracticaldev/dev.to#2042]
**Describe the bug**

![image](https://user-images.githubusercontent.com/1335133/54200362-99aa2980-44a1-11e9-9984-ceffa7461303.png)

This thing pulses, very prettily with nice CSS animations, once per second.  Forever.  Congratulations, you've re-invented the blink tag.

I'm sorry for being grumpy, but please stop.  :cry: 

Oh, this is a duplicate of #1372.  Except that one is closed and apparently not actually fixed.

**To Reproduce**

1. Go to https://dev.to/winduptoy/a-javascript-free-frontend-2d3e
2. Try to read the article
**Expected behavior**

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Firefox
- Version: 65

**Additional context**

Haven't had coffee yet, which apparently makes me nitpick.

**Comment by jessleenyc** [comment]
Hey! Thanks for raising this again. We apparently missed one when we removed the others. This one should be removed now.
