### ISSUE TITLE
Support <details>/<summary> tags in markdown

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#2045]
**Is your feature request related to a problem? Please describe.**
<details>/<summary> tags are support in github markdown and I'd like to use them on DEV as well.

**Comment by mariocsee** [comment]
should these tags be supported in all or certain parts of the site that support markdown? (i.e articles, comments, chat messages)

**Comment by Link2Twenty** [comment]
Will a polyfill be used for IE11 and Edge?

**Comment by maestromac** [comment]
[Seems necessary](https://caniuse.com/#feat=details) to use polyfill

**Comment by rhymes** [comment]
Threaded comments were implemented with details/summary and IIRC Ben didn't use polyfills because they just look expanded in IE11. On this note, can't we just leave it as it is and people with IE11/Edge will get the spoilers 😅 ?

**Comment by Link2Twenty** [comment]
Slightly different I think, that being said we don't support IE and edge is moving to blink soon so will then support everything 😁

**Comment by sw-yx** [comment]
yea hello i was the original suggester of this issue, and i only really care about this in posts. i do pretty longform posts :)

**Comment by aspittel** [comment]
This is super helpful for having course and workshop material -- I use these all the time on GitHub in lesson plans! +1 for this feature!

**Comment by AlbertoPdRF** [comment]
I think this issue is a duplicate of #947.

**Comment by rhymes** [comment]
Good call @AlbertoPdRF, going to close it as such!
