### ISSUE TITLE
found a bug, couldnt write a post, 

### ISSUE THREAD

**Issue by Haman001** [thepracticaldev/dev.to#2049]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by rhymes** [comment]
I think you forgot to fill the bug report 😁 can you provide more information? (you can just edit your post and replace the template text with the info)

Thank you!

**Comment by maestromac** [comment]
Hello @Haman001 , this looks an issue specific to your account. Please email yo@dev.to for more help.
