### ISSUE TITLE
Trying to reach a nonexistent badge returns 500

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#2051]
**Describe the bug**
Trying to reach a nonexistent badge returns 500 error instead of 404

**To Reproduce**

1. Try to reach a badge page with an incorrect slug, e.g. [this url](https://dev.to/badge/random)
2. Get 500 error

**Expected behavior**
Get 404 error

**Comment by edisonywh** [comment]
I've fixed it over at #2066, feel free to review :)

**Comment by lightalloy** [comment]
@edisonywh thanks! Will look at that.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/2066
