### ISSUE TITLE
Footer on homepage never reachable

### ISSUE THREAD

**Issue by isaac-martin** [thepracticaldev/dev.to#2054]
**Describe the bug**
Footer On homepage is never clickable due to infinite scroll, however regularly it will be shown depending on the speed of the scroll. See attached GIF

**To Reproduce**
Go to homepage, scroll down. 

**Expected behavior**
Footer would be able to be clicked on, or not shown at all. 

**Screenshots**

![dev to](https://user-images.githubusercontent.com/8649366/54287896-e7e02b00-457c-11e9-9f2c-c8710aaee0fa.gif)

**Desktop (please complete the following information):**

- OS: Mac OSX
- Browser: Chrome
- Version: 72.0.3626.119

**Additional context**
We can either remove - or make fixed on homepage

**Comment by isaac-martin** [comment]
I'll take this on, but @benhalpern what behaviour do we want for the footer on that page?

**Comment by Glennmen** [comment]
I think there already is a discussion about this: https://github.com/thepracticaldev/dev.to/issues/266

**Comment by isaac-martin** [comment]
Thanks @Glennmen - I should have searched better, will close this.
