### ISSUE TITLE
Feature Request: Stackblitz Embed using SDK

### ISSUE THREAD

**Issue by carloslfu** [thepracticaldev/dev.to#206]
# Stackblitz Embed

[Stackblitz](https://stackblitz.com/) provides an awesome environment for prototyping and sharing working code, would be nice to have it into Dev.to as well. There are other tools such as Codesandbox but Stackblitz SDK will allow writers to create frontend code on demand while writting a post, something like the runkit embed.

### Request or User Story

As writer I want to embed an Stackblitz Environment into my post for showing live code to my readers

### Definition of Done

A writer can embed an Stackblitz Environment in his posts

### Notes

Stackblitz provides an easy to use SDK I have used it and it is trivial to make an integration with it. See:

Article: [StackBlitz SDK: Instantly Add Live Environments to Your Docs, Blogs, & more](https://medium.com/@ericsimons/stackblitz-sdk-instantly-add-live-environments-to-your-docs-blogs-more-73dab05c51ae)
Documentation: [SDK](https://stackblitz.com/docs#javascript-sdk)

**Comment by Zhao-Andy** [comment]
Hey @carloslfu, looks pretty neat! We right now support [repl.it](https://repl.it) and [RunKit](https://runkit.com/home) embeds, but it's not exactly widely known. We'll consider adding StackBlitz. Thanks for the heads up!
