### ISSUE TITLE
Lower amount of SQL queries used for signing in

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/dev.to#2061]
Currently, some people (myself included) are experiencing long sign in times, which usually end up timing out, thus preventing people from signing in.

Looking at [Skylight](https://oss.skylight.io/app/applications/K9H5IV3RqKGu/recent/6h/endpoints?query=omniauthcallbackscontroller) we can see that the requests take on average 2.7 seconds. Looking deeper in the `#github` or `#twitter` actions we can see that there are a lot of repeated queries:
![Screenshot of requests](https://user-images.githubusercontent.com/17884966/54316514-593ccf80-45b7-11e9-9c7b-0474d7697589.png)

This can definitely be refactored and the amount of queries can be reduced. The main -- and probably only -- file that needs to be refactored is the [authorization_service.rb file](https://github.com/thepracticaldev/dev.to/blob/master/app/services/authorization_service.rb).

Of course, this should be approached with care, as this affects how people authorize themselves into the app. The sign in process should still work, and refactoring shouldn't cause any weird data leakage (probably hard to accomplish, but good to keep it in mind).

**Comment by lightalloy** [comment]
I did research on this issue and found out that most of these queries are for validations (e.g. uniqueness validations) and callbacks. I think we could optimize it by only performing validations when the corresponding field was changed + adding unique indexes to the database if they are missing.
There were even attempts to bring such behavior into rails, but there's no visible result:
https://github.com/rails/rails/pull/30988
https://github.com/rails/rails/issues/34281

**Comment by Zhao-Andy** [comment]
Did a little investigation with this when trying to solve something else. Turns out `user.remember_me!` runs `user.save` in the background (therefore another query).

**Comment by benhalpern** [comment]
The existence of the the `remember_me!` and the `remember_me = true` and the multiple saves are all symptoms of hacked on functionality to make sure users stay signed in appropriately.

I eventually left this in and moved on.

So this can definitely be replaced by alternate functionality to keep the session "remembered".
