### ISSUE TITLE
Singular comments and reactions get s-ending

### ISSUE THREAD

**Issue by selbekk** [thepracticaldev/dev.to#2067]
**Describe the bug**
When I go visit my dashboard, I notice a typo. When I have 1 comment on one of my articles, it says "1 comments" (plural). The same goes for reactions.

**To Reproduce**

1. Go to https://dev.to/dashboard
2. Have an article with 1 reaction or 1 comment (or both) and notice the plural `s` at the end.

**Expected behavior**
If I have 1 comment, it should say 1 comment. Same for 1 reaction.

**Screenshots**
![Screenshot of the issue at hand](https://user-images.githubusercontent.com/1307267/54435425-bc9e3d00-4730-11e9-8768-a081e0c955ab.png)

**Additional context**
I'm providing a PR to fix this

**Comment by maestromac** [comment]
Thanks for this @selbekk ! 
Resolved with https://github.com/thepracticaldev/dev.to/pull/2069
