### ISSUE TITLE
Jump to comments

### ISSUE THREAD

**Issue by Defman21** [thepracticaldev/dev.to#207]
# _TASK or Feature_
### Request or User Story

I often read articles but they don't have any comments at the moment of reading. Next time I'm scrolling my feed, I see the comment count increased. I have to scroll the whole article again (and some of them are pretty big) to see the comments.

### Definition of Done

* [ ] ![image](https://user-images.githubusercontent.com/7100645/39409143-7d5ce142-4bea-11e8-8833-3d97e3f6ea15.png): Make this counter clickable
* [ ] Add a "Jump to comments" button in the article view (or something like that)

**Comment by Zhao-Andy** [comment]
Hey @Defman21, thanks for the feedback! We're going to consider some design aspects first. 👍

**Comment by hoelzro** [comment]
Now that dev.to is open source, is there any chance the design discussion could continue here or somewhere else public?  I've thought about working on this as my first PR for dev.to, but I would want to make sure I follow proper design conventions before laying code down!

**Comment by maestromac** [comment]
Hey @hoelzro ! if you wish to take a jab at it, try to get the functionality working first and don't worry about the design decision just yet. @benhalpern can you give more feedback on the design.

**Comment by hoelzro** [comment]
@maestromac I'll give it a shot if I have time!

**Comment by hoelzro** [comment]
With the advent of the sticky buttons announced on https://dev.to/ben/changelog-sticky-post-actions-ui-change-3i00, my use for this is fulfilled!

**Comment by benhalpern** [comment]
Hey sorry I never took part in this convo, but yes. Feature implemented 😄

This was one of those things I had a vision for with the product but I wasn't quite sure until I broke out the ole editor.
