### ISSUE TITLE
500 error occurred Sometimes.

### ISSUE THREAD

**Issue by manprajapat** [thepracticaldev/dev.to#2079]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by benhalpern** [comment]
This may be related to #2080. Without more info I'll have to close this, but re-open if it is still occurring.
