### ISSUE TITLE
NaN in heart/unicorn/bookmark count in a post

### ISSUE THREAD

**Issue by flexdinesh** [thepracticaldev/dev.to#208]
# _BUG_

### Current Behavior

When I click heart/unicorn/bookmark repeatedly(laggy internet connection), I get NaN in the counts.

### Expected Behavior

When I click heart/unicorn/bookmark repeatedly, number should increase and decrease by 1 alternately.

### Additional Info (steps to replicate, device/browser, helpful links)

Probably this happens, when the user clicks the icon again before the async request returns for each click (can happen with slow internet).

### Screenshots

![NaN in all](https://image.ibb.co/hNqQPH/devto_Na_N.jpg)

**Comment by Zhao-Andy** [comment]
Hey @flexdinesh, thanks for the heads up. We'll fix that bug soon!

**Comment by benhalpern** [comment]
I believe this is actually a couple bugs. On the frontend we just don't properly handle errors, so the "value" of the error is the 500 message, aka NaN. On the backend we also have issues with the reaction counts getting out of order with repeated clicking. I think we could rate limit this somehow. Whoever takes this check with me about how you plan to do it.

**Comment by nickyhajal** [comment]
@benhalpern Seems like on the frontend, adding a `debounce` should effectively rate-limit the requests: https://lodash.com/docs/4.17.10#debounce

Ideally, the UI would update optimistically and just the request to the server is debounced so it only sends with the final value.

**Comment by gatlee** [comment]
My [pull request](https://github.com/thepracticaldev/dev.to/pull/681) implements optimistic rendering and addresses the visual aspect of the bug. NaNs won't be shown to the user on error. 

I'm currently working on migrating the actions bar to react but if this is enough of a priority I could work on implementing @nickyhajal 's suggestion. 

Any thoughts @benhalpern?

**Comment by maestromac** [comment]
Resolved with #681 and #989
