### ISSUE TITLE
The page doesn't render, it gives off a 500 error, https://dev.to/softchris/dockerfrom-the-beginning-part-v-n2c

### ISSUE THREAD

**Issue by softchris** [thepracticaldev/dev.to#2080]
**Describe the bug**
page doesn't render, gives 500 error
https://dev.to/softchris/dockerfrom-the-beginning-part-v-n2c

**To Reproduce**

**Expected behavior**
page doesn't render

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by benhalpern** [comment]
Sorry about this. The fix has been merged and everything is working as expected. There was a mistake in the most recent deployment that did not cause the CI to fail.

Thank you so much for alerting us to this.
