### ISSUE TITLE
page should load, https://dev.to/softchris/docker-from-the-beginningpart-iii-2h51 500 error

### ISSUE THREAD

**Issue by softchris** [thepracticaldev/dev.to#2082]
**Describe the bug**
trying to load this page https://dev.to/softchris/docker-from-the-beginningpart-iii-2h51
get 500 error instead

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by benhalpern** [comment]
Sorry about this. The fix has been merged and everything is working as expected. There was a mistake in the most recent deployment that did not cause the CI to fail.

Thank you so much for alerting us to this.
