### ISSUE TITLE
Bug(Night Mode): Visibility issues with Search in Night Mode

### ISSUE THREAD

**Issue by co16353sidak** [thepracticaldev/dev.to#2086]
**Describe the bug**
In the night mode, the search bar seems to blend in with the top Navbar.
What I have noticed is that while we do change the colouring of the text from black (in default mode) to white (in night mode), the `search` placeholder seems to persist with the same `font-color` nevertheless, causing 2 problems:

1. Breaks from the consistency of the whole UI, where in we are using bright whites for text or for outlines but then the search bar still persists with the same grey coloured placeholder.
2. Decreases visibility, users (like me) had to squint or had to concentrate very hard to see the search bar and the search keyword, dark greys (like the default placeholder text) just doesn't work with dark backgrounds

**To Reproduce**

1. Open an article or any dev.to page in default mode
2. Open the settings in another tab and make the change to night mode.
3. Click on the `dev` icon in the Navbar on the settings page.
4. Compare and observe the two search bars on different modes

**Expected behavior**
1. Instead of having simple grey text, maybe have a bring white text or something similar so as to make the search bar pop-out or not blend in become hard to see.
 2. Add some sort of outline to the search-bar so as to make it separable and distinguishable from the rest of the Navbar.

**Screenshots**
<img width="691" alt="Search Bar in day mode" src="https://user-images.githubusercontent.com/35738138/54493377-69c1b280-48f5-11e9-9145-8362bc63a588.png">

<img width="892" alt="Search Bar in night mode" src="https://user-images.githubusercontent.com/35738138/54493355-16e7fb00-48f5-11e9-97ca-ee8354336b42.png">

**Desktop (please complete the following information):**
Adding specifications as per my machine, but I feel this problem is universal and not browser/OS specific.

- OS: MacOS 
- Browser: Safari
- Version: 12.0.3 (14606.4.5)

**Smartphone (please complete the following information):**
Same with mobile versions and apps, adding the details about my device.

- Device: iPhone 6s
- OS: iOS 12
- Browser Safari/iOS Application

**Additional context**
a hopeful simple method to implement this: https://www.w3schools.com/howto/howto_css_placeholder.asp

I would like to work on this as my first contribution here 🥇

**Comment by jessleenyc** [comment]
Hey @co16353sidak feel free to work on this but please share a quick mockup of your design so we are on the same page before you dive into it :)

**Comment by Link2Twenty** [comment]
The implementation of night mode is a little different now than it was when you took that screenshot. Here is the new header nav.

![image](https://user-images.githubusercontent.com/3534427/54612873-a7d3e900-4a51-11e9-8da0-1702544baa57.png)

If the style hasn't changed you might need to clear your cache.

**Comment by co16353sidak** [comment]
@Link2Twenty @jessleenyc  didn't need to clear the cache, got the new dark mode and it looks much better than the previous iteration, I feel that my 2nd suggestion seems out of date now seeing as there is now a clear differentiation of the search bar from the navbar now.

I am still wondering if there Is a need to discuss on the colour of the `search` placeholder, I still feel that it would look much good with a lighter colour, maybe white ?

**Comment by Link2Twenty** [comment]
Currently, the placeholder is top bar colour but with an opacity of 50%

https://github.com/thepracticaldev/dev.to/blob/2b2ecaa1158332f6aa0edcfe5ae81811bd0fb4b0/app/assets/stylesheets/top-bar.scss#L348-L352

Perhaps we should increase the opacity?

**Comment by co16353sidak** [comment]
@jessleenyc @Link2Twenty
Here are some mockups for this:
1. Opacity at 1.0 (100%)
<img width="680" alt="Screenshot 2019-03-19 at 11 16 28 PM" src="https://user-images.githubusercontent.com/35738138/54629267-36ba2300-4a9d-11e9-92e1-0c1db3c06de0.png">

2. Opacity at 0.9 (90%)
<img width="576" alt="Screenshot 2019-03-19 at 11 16 38 PM" src="https://user-images.githubusercontent.com/35738138/54629287-42a5e500-4a9d-11e9-8e09-692425232910.png">

3. Opacity at 0.7 (70%)
<img width="602" alt="Screenshot 2019-03-19 at 11 16 51 PM" src="https://user-images.githubusercontent.com/35738138/54629302-4c2f4d00-4a9d-11e9-94b6-dbd4c817274a.png">

4. Original - Opacity at 0.5 (50%)
<img width="618" alt="Screenshot 2019-03-19 at 11 16 58 PM" src="https://user-images.githubusercontent.com/35738138/54629344-6537fe00-4a9d-11e9-99bd-bffe22f69109.png">

**Comment by co16353sidak** [comment]
I personally feel that opacity from 0.9 leading to 1 is the best option for this, as you can see the search keyword is clearly visible and the user pays attention to it instead of skipping it

**Comment by Link2Twenty** [comment]
@benhalpern thoughts?

I think there should be a clear difference between the placeholder text and user input. I'm not sure 90% offers that distinction but that's just my opinion.

**Comment by jessleenyc** [comment]
Like @Link2Twenty, I also prefer the lower opacity so there's a distinction between placeholder text and user input.

**Comment by jessleenyc** [comment]
Since the original issue has been resolved, I'm going to go ahead and close this one. @co16353sidak thanks for creating the mockup for us to see the difference but I think as is works for now.
