### ISSUE TITLE
Feature request: delete or merge accounts

### ISSUE THREAD

**Issue by krantzinator** [thepracticaldev/dev.to#209]
### Request or User Story
delete old account, or merge an old account with a new one

### Definition of Done
I want to be able to delete my account from dev.to, or merge an old account with a new one.

### Notes
I realize this is technically two features, but as both would solve my current problem equally I'm listing them together. I could not find a `Help` section on the dev.to site, so if there is already info about how to delete an old account please let me know!

#### Current problem/more info
I created an account a long time ago with twitter, then when i came to login i couldn't remember if i had used twitter or github, so i used github this time, and now i have two accounts and i can't connect my twitter to my new/active account.

**Comment by Zhao-Andy** [comment]
Hey @krantzinator, thanks for the feature request and bug report. The duplicate account and inability to merge/delete an account a known issue that we've been meaning to fix; sorry that you ran into it! I'll follow up with you via email about your specific case.

**Comment by jessleenyc** [comment]
@krantzinator closing this because andy fixed your account!
