### ISSUE TITLE
Post edit text is same color as background

### ISSUE THREAD

**Issue by ghost** [thepracticaldev/dev.to#21]
When I try to write a post, the text shows up white like the background.

I am using Firefox in Manjaro Linux.

![Invisible text](https://cloud.githubusercontent.com/assets/20386192/23362680/8ed0d324-fcff-11e6-87dd-acc468d56049.png)

**Comment by benhalpern** [comment]
Weird! Thanks for the heads up.

**Comment by bottitytto** [comment]
You're welcome!

**Comment by maestromac** [comment]
Hello @ghost, are you still running into this issue?

**Comment by jessleenyc** [comment]
Unable to replicate, need more info.
