### ISSUE TITLE
Deleted a thread comment, but it didn't disappear and got into a broken state

### ISSUE THREAD

**Issue by brunolemos** [thepracticaldev/dev.to#2106]
**Describe the bug**
After deleting my own comment, it got into a broken state. The deleted comment is still there, and I can't remove it again (get the "You have lost your way" message) and can't reply to the thread anymore (get an endless loading indicator).

**To Reproduce**

1. Go to a comment thread
2. Reply
3. Delete your reply
4. Get to the broken state

I'm actually not sure the steps above will reproduce the issue every time, but this is how I got to this state.

**Expected behavior**
My deleted comment should have disappeared and I should be able to reply to the thread.

**Screenshots**

![gif](https://user-images.githubusercontent.com/619186/54558839-71d52d00-499d-11e9-9ad5-6ea89250b75f.gif)

_The gif also shows another bug at the end but that's unrelated. After tapping "Cancel" the "Delete" and "Edit" buttons disappeared, only showed "Reply"._

**Desktop (please complete the following information):**

- OS: macOS Mojave
- Browser: Chrome and Safari
- Version Latest

**Additional context**
It's not a  client-side cache issue. It's something in the server probably. Tried on another browser and using incognito mode, same thing.

Thread link: https://dev.to/rynatk/comment/9ec3
Deleted comment: https://dev.to/brunolemos/comment/9fej (link won't show it)

**Comment by maestromac** [comment]
Hey @brunolemos , can you check if you are still experiencing this error?

**Comment by brunolemos** [comment]
It's fixed now, thanks!
