### ISSUE TITLE
Why you should Open Source the project today...

### ISSUE THREAD

**Issue by eddiejaoude** [thepracticaldev/dev.to#211]
## Open Source FTW

> This repo will evolve to host our codebase once it is ready

Great you want the project to be **Open Source**, but don't wait until its _ready_! For multiple reasons...

1. Sorry but, it will never be ready, a project is never ready or finished
2. We (the Open Source community) miss out on being part of the project's journey 🤓 
3. We can help with getting the project ready 😉 
4. ...
_the list goes on, I can talk about this forever, but you get the picture_

**Comment by DevsPen** [comment]
+1

**Comment by benhalpern** [comment]
![](https://cl.ly/3Q3o1M3i011f/Image%202018-05-08%20at%2011.25.42%20AM.png)

I agree. Moved this to priority. We had a couple months of having to deal with other biz stuff but we're now back on the wagon.

**Comment by TheCodersHangout** [comment]
Can't Wait

**Comment by Zhao-Andy** [comment]
Hey y'all, we're officially open sourcing August 8th! See this post for more details:
https://dev.to/ben/the-devto-codebase-will-go-open-source-on-august-8-2kia

**Comment by eddiejaoude** [comment]
Awesome 👍 🎉 🤓
