### ISSUE TITLE
Bug(Night Mode):- Hover Issues on Reading List Section

### ISSUE THREAD

**Issue by co16353sidak** [thepracticaldev/dev.to#2121]
**Describe the bug**
In the night mode, there seems to be some problems with the hover on the reading list section of the page.
Shown below. when out cursor moves into the Reading List section, the background colour of the lower section containing the buttons `saved posts` and `comment activity` unexpectedly changes colour to merge with that of the background.
If we continue over to actually hovering over the buttons, then the whole section completely changes it's background colour to merge with the page.

I have included a gif to help understand this.
![Mar-20-2019 11-45-37(1)](https://user-images.githubusercontent.com/35738138/54663208-7832e880-4b06-11e9-8d76-4f598aa34d47.gif)

Also if we compare with the functioning of the default mode, we can see the difference and how this is supposed to work.
![Mar-20-2019 11-46-40](https://user-images.githubusercontent.com/35738138/54663344-f5f6f400-4b06-11e9-899a-bb7913ffe6df.gif)

**To Reproduce**

1. Enable Dark Mode 
2. Goto the main `dev.to` homepage
3. try hovering over the elements mentioned (the `reading-list` section) to see the described error

**Expected behavior**
I believe it should work similarly like the default mode, but with different colour variables depending on the mode selected, I have included a gif for the same on default mode.

**Screenshots**
Linked above.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Safari and Firefox
- Version: 12.0.3 (14606.4.5)[latest] and 67.0b3 (64-bit)[latest developer edition] 

**Smartphone (please complete the following information):**

(Not Tested)

**Comment by Link2Twenty** [comment]
It's this section of the code
https://github.com/thepracticaldev/dev.to/blob/master/app/assets/stylesheets/articles.scss#L940-L973

**Comment by rhymes** [comment]
@co16353sidak I'm going ahead and close this now that the reading list UI has changed and the hover issue is not present anymore.
