### ISSUE TITLE
Dev logo switched with larger logo after visiting 8-week-streak badge page

### ISSUE THREAD

**Issue by bolariin** [thepracticaldev/dev.to#2129]
**Describe the bug**
On visiting `https://dev.to/badge/8-week-streak`, the logo switches with a larger dev logo. The larger logo stays even after switching to the home page using the logo.

**To Reproduce**

1. Visit 'https://dev.to/badge/8-week-streak'
2. You should see the logo change

**Expected behavior**
I expect the dev logo to remain the same.

**Screenshots**
<img width="960" alt="dev logo changed" src="https://user-images.githubusercontent.com/24629960/54706195-af0ffb00-4b14-11e9-8c16-7916ee6db455.PNG">

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version: 73.0.3683.75

**Additional context**
I noticed I didn't have the same issue on Firefox and Edge

**Comment by rhymes** [comment]
I just noticed it stays like that even when you navigate from there to other pages

**Comment by benhalpern** [comment]
Yeah, we uploaded a version that was wrong. @rhymes is correct.

This is lingering because it got cached before we changed back. I'm loathe to do a site-wide cache purge but it might be necessary if there are lingering pages with the mistake.

**Comment by rhymes** [comment]
> Yeah, we uploaded a version that was wrong. @rhymes is correct.
> 
> This is lingering because it got cached before we changed back. I'm loathe to do a site-wide cache purge but it might be necessary if there are lingering pages with the mistake.

site wide purges are the worst 😭
brace yourselves heehhe

**Comment by maestromac** [comment]
I believe this resolved itself. Let me know if otherwise!

**Comment by rhymes** [comment]
@maestromac love the new logo!
