### ISSUE TITLE
Dialogue Confirmation when leaving editor

### ISSUE THREAD

**Issue by andredublin** [thepracticaldev/dev.to#213]
# Feature
### Request

Warn the user if they have made changes to a draft when they try to navigate away from the page.

### Definition of Done

If the user types in the markdown editor and attempts to navigate away other then using the editor menu should be issued a warning that they will lose their changes.

**Comment by Zhao-Andy** [comment]
Hey @andredublin, thanks for the feature request! We actually have this in, but it's a bit broken right now. We'll add this to our bug-fix list.

**Comment by jessleenyc** [comment]
We'll be fixing this within a separate issue so closing this one.
