### ISSUE TITLE
Add ability to sort articles on dashboard by views/reactions

### ISSUE THREAD

**Issue by pkfrank** [thepracticaldev/dev.to#2134]
**Is your feature request related to a problem? Please describe.**
As an author, I'd like to be able to sort my posts by criteria such as views / engagement / comments count, instead of strictly viewing in chronological order.

**Describe the solution you'd like**
An option on the dashboard which allows me to filter by certain criteria (views, reactions, comments).

**Comment by maestromac** [comment]
Slightly related to https://github.com/thepracticaldev/dev.to/issues/1837

**Comment by mariocsee** [comment]
Is this resolved by PR #2337?

**Comment by pkfrank** [comment]
@mariocsee Yup, it is.  Good call.
