### ISSUE TITLE
Preview notifications as a floating dialog

### ISSUE THREAD

**Issue by ioprotium** [thepracticaldev/dev.to#2138]
**Is your feature request related to a problem? Please describe.**
Is not related to any problem. Every time I click on the notification icon it goes to **https://dev.to/notifications**. Then I have to press the back button to come back to the article I was reading.

**Describe the solution you'd like**
When clicking the notification icon I'd like to see just a container positioned under the icon in desktop or a popup in mobile with a preview of my latest notifications. Just like the profile button. The preview should contain the title of the notification. E.g. 
> <user_icon> <user_name> liked your post

**Describe alternatives you've considered**
I don't think there are another alternatives for this request.

**Comment by Zhao-Andy** [comment]
Hey @ioprotium, thanks for the feature request! Certainly something to consider and discuss. Feel free to drop any design ideas if you have something you were thinking of.

**Comment by Glennmen** [comment]
Isn't that the same as this issue: #968

**Comment by Zhao-Andy** [comment]
@Glennmen oh yeah, good catch. @ioprotium we're going to close this one and reopen #968. Feel free to add a comment there if you'd like!

**Comment by ioprotium** [comment]
@Glennmen yes! I wasn't able to find a similar request but I was sure somebody must have already asked for. 

I forked the repo, I will try to study it and maybe drop a PR.
