### ISSUE TITLE
The share cards on Facebook/LinkedIn don't show the author name.

### ISSUE THREAD

**Issue by abhnvkmr** [thepracticaldev/dev.to#214]
# _TASK or Feature_
### Request or User Story
After publishing the post, when I share it on FB and LinkedIn, the card just has the post title and "dev.to" in the second line. It should show the author name or the first few lines of the post at least.

No issues with Twitter since, the share widget injects the author name in the tweet,

### Definition of Done
The first line should be 'Post title - Post author'
The second line could be '{first line of post}' or left as it is.

**Comment by Zhao-Andy** [comment]
Hey @abhnvkmr, thanks for the heads up! We'll take a look into it.

**Comment by jessleenyc** [comment]
Hey @abhnvkmr!

- If you add a `description` to the post, text should appear on both facebook and twitter. I see the issue with Linkedin and we'll investigate that.
- Any post that does not have an image will display the author name on the social card, like the Linkedin example below. 
- Is there a specific post you're referring to?

LinkedIn:
![](https://cl.ly/2N2N0P442l40/download/Image%202018-05-22%20at%2010.51.14%20AM.png)

Facebook:
![](https://cl.ly/2z0z3U2I1d3g/download/Image%202018-05-22%20at%2010.52.35%20AM.png)

Twitter:
![](https://cl.ly/2m0M0Z1h2C0O/download/Image%202018-05-22%20at%2010.53.12%20AM.png)

**Comment by abhnvkmr** [comment]
Yeah, it's a problem with LinkedIn specifically. The 'description' or first line of the post if there's no description, appears in the Facebook/Twitter share cards.

Regarding the author: In my post, a random (although it's pretty contextual) image was chosen even though I didn't have any image in my post.

Link in question: https://dev.to/abhinav/rest-in-peace-grep-19h9
![image](https://user-images.githubusercontent.com/1756451/40394266-5faa9df2-5e40-11e8-8c34-a7deb055a527.png)
