### ISSUE TITLE
Cannot upate profile

### ISSUE THREAD

**Issue by brandizzi** [thepracticaldev/dev.to#215]
# _BUG_
### Current Behavior

I cannot update [my profile](https://dev.to/adambrandizzi). When I try, I get this error:

> 2 errors prohibited this article from being saved:
> 
>     Twitter username has already been taken
>     Github username has already been taken

### Expected Behavior

My profile would be updated.

### Additional Info (steps to replicate, device/browser, helpful links)

I used to have two accounts (because in the early days I logged once with GitHub and later with Twitter). I had problems due to that before, but they were fixed.

**Comment by Zhao-Andy** [comment]
Hey @brandizzi , sorry about that; that's an occasional edge case we have. I've merged your two dev.to accounts. You should be able to update your profile now. Feel free to change your email as necessary.

Let me know if you have any other issues!
