### ISSUE TITLE
[Discussion] Theme selector

### ISSUE THREAD

**Issue by Link2Twenty** [thepracticaldev/dev.to#2158]
At some point we'll have to talk about theme selection, I find a graphic is better than a name as it gives the user an idea of what to expect.

I made a quick mock-up.
https://jsfiddle.net/link2twenty/3pmtew1f/

**Comment by aspittel** [comment]
Woah, very cool! I'm super impressed by the mockup. I think that could be great UX, though can also see some other roads that we could take here. Definitely a great community discussion to have!

**Comment by rhymes** [comment]
Such a cool mockup!

**Comment by Link2Twenty** [comment]
Thank you both 🙂

**Comment by Link2Twenty** [comment]
not stale

**Comment by jessleenyc** [comment]
Just wanted to leave a note here that we'd welcome any contributions for a theme selector :)
