### ISSUE TITLE
Can't remove Twitter link.

### ISSUE THREAD

**Issue by erhankilic** [thepracticaldev/dev.to#216]
# _BUG_
### Current Behavior
I remember that I added my twitter username at "edit profile" page. Right now there is no way to enter or remove it.

### Expected Behavior
There must be a way to remove twitter link from profile.

**Comment by Zhao-Andy** [comment]
Hey @erhankilic, sorry about that bug. I followed up via email to clarify :)

Also, if anyone else has this, feel free to email yo@dev.to.
