### ISSUE TITLE
External Links In Posts Are Difficult To See In Dark Mode

### ISSUE THREAD

**Issue by aturingmachine** [thepracticaldev/dev.to#2163]
**Describe the bug**
Links are only marginally different in color than the post's text. Coupled with the dark background changing the overall contrast of the page, this makes them difficult to see. 

**To Reproduce**
1. Log in with Dark Mode Enabled
2. Click on any post including external links.
3. Observe link text color.

**Expected behavior**
The link text to be more easily differentiated than the post's main body text.

- OS: MacOS
- Browser Chrome
- Version N/A

**Comment by aspittel** [comment]
Hey @aturingmachine! Thanks for reporting this, I could definitely see integrating this into the new theming functionality.

**Comment by venarius** [comment]
@maestromac  This can also be closed as this got fixed in #2243
