### ISSUE TITLE
dark mode: need contrast in dashboard

### ISSUE THREAD

**Issue by johnpapa** [thepracticaldev/dev.to#2167]
Notice we can barely see the black text in dark mode.

![image](https://user-images.githubusercontent.com/1202528/54790235-cf6eb100-4c0b-11e9-8f4f-1f5f4f1820df.png)

And the light gray bubble highlight

![image](https://user-images.githubusercontent.com/1202528/54790286-f62ce780-4c0b-11e9-953a-b2ee1669cc3e.png)

**Comment by aspittel** [comment]
Hey @johnpapa, thanks for pointing this out. We're making a lot of improvements to theming and dashboard right now and will be sure to fit this into the pipeline.
