### ISSUE TITLE
need contrast in dark theme for admin page for an org

### ISSUE THREAD

**Issue by johnpapa** [thepracticaldev/dev.to#2172]
Notice the two spots here both need some more contrast.

![image](https://user-images.githubusercontent.com/1202528/54830639-3c775a80-4c8f-11e9-93b6-160c69ca74a4.png)

**Comment by venarius** [comment]
@jessleenyc  I guess this can be closed as this has already been fixed

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/2105
