### ISSUE TITLE
Org analytics page needs contrast in dark mode

### ISSUE THREAD

**Issue by johnpapa** [thepracticaldev/dev.to#2177]
![9026D23E-A048-4242-B780-6D63B8849016](https://user-images.githubusercontent.com/1202528/54848573-03071500-4cb8-11e9-8574-adb7d73217e2.png)
Y

**Comment by aspittel** [comment]
Great catch, thanks https://github.com/thepracticaldev/dev.to/pull/2178 should fix this!

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/2178. If otherwise, please let us know!
