### ISSUE TITLE
Broken link on milestone notification gif

### ISSUE THREAD

**Issue by kuhnertdm** [thepracticaldev/dev.to#2179]
**Describe the bug**
Link on milestone notification gif incorrectly links to internal page

**To Reproduce**

1. Write a post about Beto O'Rourke's history in the cDc

2. Get several comments from Trump/Sanders supporters saying how wrong you are

3. Get a milestone notification anyway

4. Click gif, observe incorrect link destination

**Expected behavior**
Link goes to Giphy page for the gif

**Desktop (please complete the following information):**

- OS: Win7
- Browser Firefox
- Version 66.0

**Additional context**
Problem line located here: https://github.com/thepracticaldev/dev.to/blob/1a10a344f312aa68519a9dce528e9519e23a9a0b/app/views/notifications/_milestone.html.erb#L9

href attribute should contain two slashes after the https: and only contains one, causing it to be interpreted as an internal link by the browser. Verified by changing the HTML in-browser to add the slash, which made it work. CBA to make a pull request, not a web dev and not worth setting up any sort of environment for that. sorry ben

**Comment by Glennmen** [comment]
I will make a PR for that 😉

**Comment by SamCreamer** [comment]
This is hilarious
