### ISSUE TITLE
Feature Request: Have a plugin for automatic publishing of Wordpress articles to dev.to 

### ISSUE THREAD

**Issue by fatosmorina** [thepracticaldev/dev.to#218]
# _TASK or Feature_
### Request or User Story

I am a regular blogger, and I use Wordpress as a blogging platform, and have a [plugin](https://wordpress.org/plugins/medium/) that allows me to also automatically publish my articles in Medium.com. I wanted to propose a similar plugin of publishing posts from Wordpress to dev.to, without having to do it manually for each post. I believe this could be valuable for many developers who use Wordpress for their own blogs, and that also want to reach the audience of dev.to.

### Definition of Done

A Wordpress plugin that helps authors automatically publish their articles directly to dev.to

**Comment by Zhao-Andy** [comment]
Hey @fatosmorina, thanks for the feature request! It's definitely something to consider. For now, we're going to put it in our backlog.

We also have an RSS reader than imports from an RSS feed if you'd like try that: https://dev.to/settings/publishing-from-rss
