### ISSUE TITLE
Social icon in profile on Night mode

### ISSUE THREAD

**Issue by equiman** [thepracticaldev/dev.to#2183]
Social icons in profile have a different color.

![IMG_20190323_192118](https://user-images.githubusercontent.com/933393/54873270-fe6a5b80-4da0-11e9-8827-90b246a6cb5d.jpg)

**Comment by mariocsee** [comment]
With night mode, icon images are inverted through the line `filter: invert(95%)` so removing that should make social icons the same color as the chosen `background color` in `/settings`.

**Comment by twhite96** [comment]
This has been driving me bananas. I'll work on this. Gitpod has made contributing much easier.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
