### ISSUE TITLE
Suggestion: label issues with area of focus

### ISSUE THREAD

**Issue by edisonywh** [thepracticaldev/dev.to#2185]
**Is your feature request related to a problem? Please describe.**
I'm usually trying to contribute on the Ruby side of things, not as much as frontend. 

**Describe the solution you'd like**
Would be nice if there are tags associated with them, like: `App: JS`, `App: Ruby`, `App: CSS` etc., might also be good if there are level tags - `beginner`, `intermediate`, `advanced`.

**Additional context**
Can refer to how Elixir does their issue tracking: https://github.com/elixir-lang/elixir/issues

**Comment by jessleenyc** [comment]
Ha, I actually just suggested changing up our label system with the team before I saw this issue. What I'm proposing is a bit different from what you're suggesting, here's what I was thinking: 

category/area (we can be more liberal here and they will shift as our priorities shift): dx, internal, editor, notifications, home page, profile, night mode, pro, dependencies, for iOS, accessibility

status: triage, approved, blocked

type: bug, feature, community discussion

Level: entry level (new devs), good first issue (new to our repo)

**Comment by edisonywh** [comment]
Awesome that you guys are looking into this 🎉

Yup, I don't think I've fully thought out all labels that'd make sense for `dev`, just thought I'd bring a conversation up and see what other people think. You guys would have better context! :)

`status` and `type` (maybe add refactor & chore under `type`) have already been running in the repo, and I think `level` is a _great_ idea to welcome newcomers.

But as for `category/area`, I'm not so sure about the examples you've listed. Seems like these are very business focused labels, which might not give me much incentives to work on (specifically for myself, I'd like to work on Ruby)

**Comment by jessleenyc** [comment]
Yeah, I definitely see your point there. My thought behind the different areas is that it might be helpful to have a sense of what else is 'going on' in an area that you're interested in or are working on. For example, there could be multiple issues on supporting different tags in markdown that could be worked on at the same time. 

@lightalloy also suggested adding 'refactor' and 'optimization' under types which makes sense to me.

I think we could probably find room for ruby and js tags as well, I just have minor concerns of overcluttering each issue. Will chat with the team about some of this today!

**Comment by jessleenyc** [comment]
@edisonywh going to close this because we just added a bunch of labels. we'll try to remember to tag issues w/ JS and Ruby as well. there's a big backlog to go through but hopefully we'll get in the habit of it all going forward!
