### ISSUE TITLE
Unable to post article/blog/topic

### ISSUE THREAD

**Issue by skathurwar** [thepracticaldev/dev.to#2189]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by skathurwar** [comment]
505 error when i opened https://dev.to/new

**Comment by maestromac** [comment]
Hello @skathurwar , this looks an issue specific to your account. Please email yo@dev.to for more help.

**Comment by seorakesh** [comment]
Unable to write a new post
