### ISSUE TITLE
Feature Request: Backup/Export all my Posts to zip

### ISSUE THREAD

**Issue by c33s** [thepracticaldev/dev.to#219]
# _TASK or Feature_
### Request or User Story
i would <3 to download/backup all my post. would like to have a download button somewhere where i will get a zip file containing all my posts and all the cover_images uploaded to dev.to

**Comment by Zhao-Andy** [comment]
Hey @c33s, thanks for the feature request! We're going to backlog it for now.

Personally think it's pretty cool idea. 👍

**Comment by thomasbnt** [comment]
it could be useful

**Comment by justinjstark** [comment]
I personally will not use dev.to without export-all-posts functionality. I'm not willing to publish my content where it is not easily transferable.

**Comment by jessleenyc** [comment]
We're definitely on board with this. Whoever takes this on can add the functionality to the 'misc' section on profile settings!
