### ISSUE TITLE
Saving favorite articles

### ISSUE THREAD

**Issue by ghost** [thepracticaldev/dev.to#22]
Will there be a way to be able to favorite/bookmark/otherwise save an article for easy reference, within a dev.to account?

**Comment by benhalpern** [comment]
That should be available soon.

**Comment by jessleenyc** [comment]
If you 'react' to an article, it'll now appear on your profile for easy reference.

**Comment by AggressiveSneeze** [comment]
Hmmm. I think explicit saving/starring would be a nice feature. There's an article on top 10 coding inspiration movies that came up, and it's not mega intuitive that I should react to it so I can reference it later. 

Happy to give it a crack implementing as soon as you make the repo open source. :)
