### ISSUE TITLE
There is an user with a null username

### ISSUE THREAD

**Issue by alfredosalzillo** [thepracticaldev/dev.to#2205]
Hi,

playing with the dev.to api i found that there are some user with a null username.

I'm using the https://dev.to/api/users/by_username api.
The api response is an user with a null username.

```json
{"type_of":"user","id":149157,"username":null,"name":"Trek Glowacki","summary":null,"twitter_username":"trek","github_username":null,"website_url":null,"location":null,"joined_at":"Mar 25, 2019","profile_image":"https://res.cloudinary.com/practicaldev/image/fetch/s--YzYyG5Gd--/c_fill,f_auto,fl_progressive,h_320,q_auto,w_320/https://thepracticaldev.s3.amazonaws.com/uploads/user/profile_image/149157/5cabaced-3c52-43d0-bc82-d40dfce52ac2.jpg"}
```
The user in the response is not always the same.

**Comment by Zhao-Andy** [comment]
Thanks for the catch @alfredosalzillo! We'll take a look into it.

**Comment by jessleenyc** [comment]
Leaving a note here that I took care of this specific account.

**Comment by Zhao-Andy** [comment]
Going to close this in favor of #2207
