### ISSUE TITLE
Deleted pinned GitHub repositorys still show on profile

### ISSUE THREAD

**Issue by DontBelieveMe** [thepracticaldev/dev.to#221]
# _BUG_
### Current Behavior
I pinned a repository to my profile (`Settings -> Integrations`).
Later I deleted that repository.
Now I cannot unpin it via `Settings -> Integrations`, but it still appears on my profile.

### Expected Behavior
It should either automatically unpin, or still show in the `Settings -> Integrations` and show a `Deleted` button or something :man_shrugging: 

### Additional Info (steps to replicate, device/browser, helpful links)
Profile: https://dev.to/barney_wilks
### Screenshots
![screenshot from 2018-05-26 12-04-27](https://user-images.githubusercontent.com/10855194/40575459-307d9b16-60dd-11e8-8030-d9e822ab69b0.png)
![screenshot from 2018-05-26 12-05-30](https://user-images.githubusercontent.com/10855194/40575462-3523381a-60dd-11e8-8d17-4be3ae9835a7.png)
![screenshot from 2018-05-26 12-05-05](https://user-images.githubusercontent.com/10855194/40575464-372bb7cc-60dd-11e8-8e09-396bd643b65f.png)

**Comment by jessleenyc** [comment]
Thanks for flagging, we'll look into it.
