### ISSUE TITLE
dark mode - draft posts need contrast

### ISSUE THREAD

**Issue by johnpapa** [thepracticaldev/dev.to#2211]
see below

![image](https://user-images.githubusercontent.com/1202528/54965690-09132500-4f48-11e9-8b5b-9749ae08eb9c.png)

**Comment by rhymes** [comment]
I think there's a duplicate here https://github.com/thepracticaldev/dev.to/issues/2182

**Comment by jessleenyc** [comment]
Yep, thanks for the flag @johnpapa. Closing since it's a duplicate!

**Comment by johnpapa** [comment]
thanks. i hope its ok that I am opening these as i run across them. i didnt see the dupe (sorry).

**Comment by jessleenyc** [comment]
@johnpapa 100% ok! no need to apologize at all. I was just doing some spring cleaning 😬
