### ISSUE TITLE
Code block with string containing :o: gets changed to ⭕️

### ISSUE THREAD

**Issue by learnbyexample** [thepracticaldev/dev.to#2216]
**Describe the bug**

Code block with string containing `:o:` (lowercase letter that comes after `n` surrounded by colons) gets changed to `⭕️` (perhaps an emoji?)

**To Reproduce**

Using any of these code blocks in a post/comment and previewing it shows the issue. Having any other characters around this sequence doesn't matter as far as I've checked.

````
```
:o:
```

```python
':o:'
```

```ruby
':o:'
":o:"
```
````

**Expected behavior**

Within code blocks, I do not expect any string combination (that I know of) to be interpreted and converted to another string. `:o:` should just be `:o:` not `⭕️`

**Screenshots**

The above code blocks produces this output:

![code_block_issue](https://user-images.githubusercontent.com/17766317/54998185-85167700-4ff3-11e9-9f3c-3f2d5cd8b9c1.png)

**Comment by benhalpern** [comment]
😮 

Yes, this is being caught by the markdown emoji converter. We should not run this parser within code blocks.
