### ISSUE TITLE
I cannot update my Dev.to profile.

### ISSUE THREAD

**Issue by darol100** [thepracticaldev/dev.to#222]
# _BUG_
### Current Behavior
I am trying to update my Dev.to profile and whenever I click submit to save the changes. I get an error saying. I am not changing the Github username, and BTW that is my GitHub username.

I signup/sign in using Twitter, which is the same username as my GitHub.

> 1 error prohibited this article from being saved:
Github username has already been taken

### Expected Behavior
This type of validation should not be done at the profile level. Base on the message it looks like this should be only done at the article level.  If a similar validation should be done at the profile level, we should consider changing the wording to do not say "article."

### Additional Info (steps to replicate, device/browser, helpful links)
- Create an account and save your profile
- Sign in and logout.
- Sign in and go to your profile.
- Click submit, and you should get that error.

### Screenshots

![screen shot 2018-05-28 at 10 31 42 am](https://user-images.githubusercontent.com/6808460/40624614-6c4daae2-6262-11e8-9eef-a1a153d384b8.png)

**Comment by Zhao-Andy** [comment]
Hey @darol100, sorry for the late response. I've merged your two accounts together; you should be good now!
