### ISSUE TITLE
Bug(Night Mode): Embedded comments are hard to read

### ISSUE THREAD

**Issue by healeycodes** [thepracticaldev/dev.to#2221]
**Describe the bug**
With Night Mode enabled, embedded comments in articles are hard to read.

They show up as black text against a dark blue background.

**To Reproduce**
With Night Mode enabled, go to an article that embeds comments.

Such as https://dev.to/devteam/top-5-dev-comments-from-the-past-week-gia

**Screenshots**

![An embedded comment](https://user-images.githubusercontent.com/34559231/55022288-2b617d00-4ff2-11e9-8471-4d6996801291.png)

**Desktop:**

- OS: Windows 10 OS Build 17134.648
- Browser: Chrome
- Version: 73.0.3683.86 (Official Build) (64-bit) (cohort: Stable)

**Comment by co16353sidak** [comment]
I am able to reproduce this issue on both Safari and Firefox.

@healeycodes @jessleenyc I would like to take up this issue and work on it

**Comment by healeycodes** [comment]
Feel free @co16353sidak! I claim no ownership :smile:

**Comment by co16353sidak** [comment]
I have implemented some designs which I think should be sufficient for the embedded code blocks.
<img width="822" alt="Screenshot 2019-03-31 at 1 51 46 PM" src="https://user-images.githubusercontent.com/35738138/55286665-59f9a200-53bc-11e9-9be0-f63880d9d6ba.png">

Following the style followed in the default mode, I made the changes accordingly in the night mode as:

<img width="825" alt="Screenshot 2019-03-31 at 1 51 39 PM" src="https://user-images.githubusercontent.com/35738138/55286677-7bf32480-53bc-11e9-88ad-44e7ff98560c.png">

Would love it if someone had a look at this firs before I submit a PR for the same.
@jessleenyc @benhalpern
