### ISSUE TITLE
Wrong new followers count in notifications

### ISSUE THREAD

**Issue by abhnvkmr** [thepracticaldev/dev.to#223]
# _BUG_
### Current Behavior
The new followers notifications page show wrong count. For e.g. If I have 5 new followers, it reads as "UserA and 5 others followed you".

### Expected Behavior
It should read "UserA and 4 others followed you."

### Screenshots
In the screenshot below, after Ben's post, my actual follower count increased by 5 but the notification tells me the increase is 6.
![pracdev](https://user-images.githubusercontent.com/1756451/40718240-f9d34810-642c-11e8-9898-fe13f24c47a1.png)

**Comment by Zhao-Andy** [comment]
@abhnvkmr Thanks for the heads up! We'll fix that.

**Comment by Zhao-Andy** [comment]
Hey @abhnvkmr, we've fixed it; let us know if otherwise. :)

**Comment by abhnvkmr** [comment]
Thanks guys!
