### ISSUE TITLE
Merging user accounts should be done in a transaction

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#2230]
I think that for a safer merge at least some of the actions should be done inside a db transaction.

https://github.com/thepracticaldev/dev.to/blob/7c1418a87c654c2feb56124c2f750ee5a8455f12/app/services/moderator/merge_user.rb#L15-L26

**Comment by maestromac** [comment]
Really good idea @lightalloy

**Comment by ConSou** [comment]
Hello, I can work on this if its still up for grabs.

**Comment by rhymes** [comment]
@lightalloy I think this can be closed 🎉

**Comment by lightalloy** [comment]
Done in #2281
