### ISSUE TITLE
Toggle plain frontmatter editor within v2

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/dev.to#2234]
**Is your feature request related to a problem? Please describe.**
Currently if you want to write "simple" markdown, you do so with the original editor, which is fine, but has always been a bit weird and occasionally buggy.

The new editor has rich UI controls, but some folks still want the markdown pasting experience (for a lot of valid reasons beyond just taste!)

It would be nice if "v2" (the preact-built editor) supported our whole range of use cases and we could sunset the old code (perhaps to be maintained by the community)

**Describe the solution you'd like**

Any area to toggle between editor types would be great. Users could have a default editor type but easily switch when needed.

**Comment by jessleenyc** [comment]
Believe this is done
