### ISSUE TITLE
Upload Video Section Needs to Be Adjusted to the Night Mode Theme

### ISSUE THREAD

**Issue by mjraadi** [thepracticaldev/dev.to#2245]
**Describe the bug**
"Upload Video" box needs to be adjusted to night mode color theme.

**To Reproduce**

1. Make sure night mode is enabled
2. You need to be signed in to be able to upload a video
3. Go to [video upload section](https://dev.to/videos/new)
4. See the behavior 

**Expected behavior**
Upload container should be adjusted to the night mode theme.

**Screenshots**
![Screenshot_20190331_015753](https://user-images.githubusercontent.com/20579660/55281931-94c9ee80-5358-11e9-97cd-42c17302e50a.png)

**Desktop (please complete the following information):**

- OS: Arch Linux Manjaro
- Browser Chrome

**Comment by mjraadi** [comment]
I will submit a PR to patch the issue as soon as it's labeled and approved.

**Comment by jessleenyc** [comment]
Sounds great @mjraadi

**Comment by mjraadi** [comment]
For some reason I can't view the "upload video" section and I'm getting this error:
![Screenshot_20190402_121604](https://user-images.githubusercontent.com/20579660/55384923-3ad84d00-5541-11e9-93b5-72bae83640f3.png)

But anyway I think I can fix the issue without running it locally. Here's what the page will look like:
![Screenshot_20190402_121830](https://user-images.githubusercontent.com/20579660/55385095-99053000-5541-11e9-9c39-25aa55662c42.png)
If you approve of the new look, I'll commit my fix.

**Comment by jessleenyc** [comment]
@mjraadi I think this is because your local account is 'new'. Can you go into console and update the user created_at time so it's more than 2 weeks ago?

**Comment by mjraadi** [comment]
I tried `currentUser` in the console and here's what it returned:
```
{
  checked_code_of_conduct: false,
  config_body_class: "night-theme default-article-body",
  display_sponsors: true,
  experience_level: null,
  followed_organization_ids: [],
  followed_tag_names: [],
  followed_tags: "[]",
  followed_user_ids: [],
  id: 11,
  name: "Mohammadjavad Raadi",
  number_of_comments: 1,
  profile_image_90: "/uploads/user/profile_image/11/4c68c1d7-6af3-4968-ae63-9d3bb92421ca.jpeg",
  reading_list_ids: [],
  saw_onboarding: true,
  trusted: false,
  username: "mjraadi",
  __proto__: Object
}
``` 

I also tried `currentUser.created_at = 1552595400`  and change the path, but still didn't see the link.

**Comment by mjraadi** [comment]
At first I thought you meant browser console, then I tried to update the user record from PostgreSQL users table and it worked.
