### ISSUE TITLE
API: can't get comments belonging to an article

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#2250]
**Describe the bug**

I can't seem to be able to retrieve articles comments from the DEV API.
It works on my local installation but not using the live API.

Given the article API response https://dev.to/api/articles/95907 - https://dev.to/kathyra_/what-security-through-obscurity-is-and-why-it-s-evil-47d5 - I tried to retrieve its comments using https://dev.to/api/comments?a_id=95907 but the server returns `HTTP 404`.

At a first glance it should work, according to the code:

https://github.com/thepracticaldev/dev.to/blob/54ccef47669759b060370c1cde8f527ce6d39333/app/controllers/api/v0/comments_controller.rb#L15-L18

The odd thing is that such call works correctly on a local installation. 

I'm probably doing something wrong on my end.

**To Reproduce**

1. Go to https://dev.to/api/comments?a_id=95907

**Expected behavior**

I'd expect this endpoint to return all the comments of the article with id `95907` which should be the following: https://dev.to/kathyra_/what-security-through-obscurity-is-and-why-it-s-evil-47d5

**Screenshots**

![Screenshot 2019-03-31 at 6 50 42 PM](https://user-images.githubusercontent.com/146201/55292018-f1271f80-53e5-11e9-81be-d8954c52ead6.png)

**Comment by maestromac** [comment]
Thanks for reporting this @rhymes . This is indeed interesting, I also can't access that endpoint.

**Comment by rhymes** [comment]
@maestromac could it have something to do with the cache that's setup in the controller?

https://github.com/thepracticaldev/dev.to/blob/54ccef47669759b060370c1cde8f527ce6d39333/app/controllers/api/v0/comments_controller.rb#L5-L8

**Comment by gajus** [comment]
Is there any workaround in the mean time?

**Comment by gajus** [comment]
Currently https://dev.to/api/comments?a_id=95907 just returns 404.

Did the API change?

**Comment by rhymes** [comment]
Hi @gajus, no it didn't change. The bug is still in there, we need to merge this and clear out the cache: https://github.com/thepracticaldev/dev.to/pull/4744

**Comment by yashwanth2804** [comment]
Any Progress ? , Still getting the same

**Comment by rhymes** [comment]
Hi @yashwanth2804, thanks for the patience and sorry for the bug you're encountering. I'm working on hopefully getting this fixed with https://github.com/thepracticaldev/dev.to/pull/4744

**Comment by rhymes** [comment]
@gajus @yashwanth2804 can you verify it's working? Thanks again for the patience!

**Comment by gajus** [comment]
Working. Thank you

**Comment by yashwanth2804** [comment]
> @gajus @yashwanth2804 can you verify it's working? Thanks again for the patience!

great thanks

**Comment by gajus** [comment]
Is the current behaviour to return all comments no matter how many there are or is there some sort of pagination?

**Comment by rhymes** [comment]
Hi @gajus, comments are not paginated, we return the entire tree of comments threads
