### ISSUE TITLE
The url https://dev.to/aspittel/css-from-zero-to-hero-3o16 doesent work

### ISSUE THREAD

**Issue by cosimochellini** [thepracticaldev/dev.to#2258]
**Describe the bug**
this link is broken
https://dev.to/aspittel/css-from-zero-to-hero-3o16

**To Reproduce**
cmd/ctrl + t , 
GOTO => https://dev.to/aspittel/css-from-zero-to-hero-3o16

**Comment by ajruckman** [comment]
This one either: [https://dev.to/azure/creating-the-simplest-possible-aspnet-core-form-with-a-post-method-416g](https://dev.to/azure/creating-the-simplest-possible-aspnet-core-form-with-a-post-method-416g)

**Comment by rhymes** [comment]
I think the entire website is unfortunately experiencing an outage, not just that URL

**Comment by jessleenyc** [comment]
Yep, thanks @rhymes. We're currently experiencing some server issues right now and will get back up as soon as possible. Thanks for your patience!

**Comment by mariocsee** [comment]
Good news! We're back up and running, so you should have no problem visiting that article and other pages on dev.to. I'm going to close this issue, but if you're still experiencing this, please let us know.
