### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ivan12339** [thepracticaldev/dev.to#2259]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by rhymes** [comment]
@ivan12339 hahaah I think you forgot to fill in the bug description, or any field actually :D

**Comment by mariocsee** [comment]
Good news! We're back up and running, so you should have no problem visiting pages on dev.to. I'm going to close this issue for now assuming it's related to the recent downtime.

If this is unrelated to the recent trouble we've experienced with our servers, please provide a description of the issue you've encountered so we can take a look.
