### ISSUE TITLE
Rewrite search as a preact component

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#226]
# _TASK or Feature_
### Request or User Story
First replicate the exact functionality and then we can add new filtering features.

**Comment by pkfrank** [comment]
Connected to #1337

**Comment by jessleenyc** [comment]
Issue moved to [thepracticaldev/dev.to_core #388](https://github.com/thepracticaldev/dev.to_core/issues/388) via [**ZenHub**](https://www.zenhub.com/)
