### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by jamiemccarville** [thepracticaldev/dev.to#2263]
Tried to follow a link to an article from Twitter, got a 500 error.

**Comment by jessleenyc** [comment]
Hey there, we’re currently experiencing some server issues right now and will get back up as soon as possible. Thanks for your patience!

**Comment by mariocsee** [comment]
Good news! We're back up and running, so you should have no problem visiting pages on dev.to. I'm going to close this issue, but if you're still experiencing this, please let us know.
