### ISSUE TITLE
Get "Error: URI Too Long" when editing post

### ISSUE THREAD

**Issue by erwald** [thepracticaldev/dev.to#2264]
**Describe the bug**

When editing an unpublished blog post, I get a bare HTML page stating "Error: URI Too Long".

**To Reproduce**

1. Go to [my unpublished blog post](https://dev.to/erwald/bach-to-the-future-or-humanising-music-with-neural-nets-3f03-temp-slug-7319634?preview=e5a256660db1e441b2c88150a4598cd8fb0e5226a6f425df16a60828ddd8f5b5f52b95c813f7f80932f67b29cacbaafdd8af16412359cd1700419aae)
2. Click "Click to edit." on the red top banner
3. Click "Save Draft"
4. Get error described above. It seems it puts the whole text of the blog post in the URL, which starts like so: https://dev.to/erwald/bach-to-the-future-or-humanising-music-with-neural-nets-3f03-temp-slug-7319634/edit?body_markdown=Many+companies+have+different+perks+and+benefits+for+their+employees%2C+but+when+I+tell+my+friends+and+acquaintances+about+ and then goes on to contain the whole content of the post.

**Expected behavior**

That it successfully applies any changes I did or did not make.

**Desktop (please complete the following information):**

- OS: macOS Mojave
- Browser: Chrome
- Version: 73.0.3683.86

**Additional context**

I tried disabling all browser extensions, but no luck.

**Comment by jessleenyc** [comment]
@erwald are you still experiencing this? I just tried reproducing but didn't get the error. We had some server issues earlier and I'm wondering if this could have possibly been related.

**Comment by erwald** [comment]
Nope, fixed now! Weird manifestation of a server issue, but I guess it must've been it. Thanks @jessleenyc !
