### ISSUE TITLE
Links are not working.. showing 500 error. Plaease fix it.

### ISSUE THREAD

**Issue by goutam4000ad** [thepracticaldev/dev.to#2265]
All links in the site are showing 500 error. Unable to load the pages.

**Comment by Zhao-Andy** [comment]
Hey @goutam4000ad, we're currently experiencing some server issues right now and will get back up as soon as possible! Thanks for your patience!

**Comment by goutam4000ad** [comment]
Hi @Zhao-Andy , please let me know when it is done. Thanks!

**Comment by mariocsee** [comment]
Hey @goutam4000ad! We're back up and running, so you should have no problem visiting different pages on dev.to. I'm going to close this issue, but if you're still experiencing this, please let us know.
