### ISSUE TITLE
Articles gives 500 - 503 today

### ISSUE THREAD

**Issue by senpl** [thepracticaldev/dev.to#2266]
reproduced in private window. Most articles got 50* errors today

**Describe the bug**
Just entering https://dev.to/ganderzz/introduction-to-functional-programming-598e gives 500 internal error with rounding lego picture
**To Reproduce**

1. Go to 'https://dev.to/ganderzz/introduction-to-functional-programming-598e'
2. See error 500 Error
It's not you, it's me.

**Expected behavior**
article content

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser Vivaldi
- Version 2.3.1440.61 (Stable channel) (64-bit)

also affected:
https://dev.to/raddevon/where-do-web-development-project-ideas-come-from-lfa

**Comment by Zhao-Andy** [comment]
Hey @senpl, we're currently experiencing some server issues right now and will get back up as soon as possible! Thanks for your patience!

**Comment by mariocsee** [comment]
Good news! We're back up and running, so you should have no problem visiting that article and other pages on dev.to. I'm going to close this issue, but if you're still experiencing this, please let us know.
