### ISSUE TITLE
Not being able to access articles.

### ISSUE THREAD

**Issue by fdevinar** [thepracticaldev/dev.to#2267]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by jessleenyc** [comment]
We’re currently experiencing some server issues right now and will get back up as soon as possible. Thanks for your patience!

**Comment by mariocsee** [comment]
Good news! We're back up and running, so you should have no problem visiting articles and other pages on dev.to. I'm going to close this issue, but if you're still experiencing this, please let us know.
