### ISSUE TITLE
Notification Error

### ISSUE THREAD

**Issue by stroudn1** [thepracticaldev/dev.to#2268]
**Describe the bug**
Tried to click on a comment someone had 'liked' and I received a page with a '500 Error'

**To Reproduce**

1. Go to 'notification button at top right corner (image of bell)'
2. Click on 'Nicole Archambault reacted to (comment) with (heart)'
3. See error

**Expected behavior**
I expected to see the comment and initial post that I had commented on.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 7 Professional
- Browser Chrome
- Version 73.0.3683.86 (Official Build) (64-bit)

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by jessleenyc** [comment]
Hey there, we’re currently experiencing some server issues right now and will get back up as soon as possible! Thanks for your patience!

**Comment by mariocsee** [comment]
Good news! We're back up and running, so everything should be back to normal. I'm going to close this issue, but if you're still experiencing this, please let us know.
