### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nouman66** [thepracticaldev/dev.to#2269]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by mariocsee** [comment]
Good news! We're back up and running, so you shouldn't be running into 500 errors on dev.to. I'm going to close this issue, but if you're still experiencing this, please let us know.

**Comment by mariocsee** [comment]
If this is unrelated to the recent trouble we've experienced with our servers, please provide a description of the issue you've encountered so we can take a look.
