### ISSUE TITLE
Number of Views (Counter)

### ISSUE THREAD

**Issue by gregoryhammond** [thepracticaldev/dev.to#227]
### Request or User Story
Would really like to see how many people have read my posts (maybe either in the dashboard or on the post itself). I had one of my most [recent posts](https://dev.to/gregory/why-i-dont-like-that-microsoft-has-acquired-github-368k) with a ton of comments / likes and it would be nice to know how many people actually read the post (since I can only count how many people came to my site).

### Definition of Done
When there is a read count somewhere on the site (which applies to each post).

### Notes
Very much enjoy the site. Thanks to everyone who has continued to create the awesome site.
P.S. I know it's funny how I wrote a post about how I will not be on github because of the acquisition yet here I am making a issue.

**Comment by Zhao-Andy** [comment]
Hey @gregoryhammond, thanks for the request! This is currently a beta feature right now, but there's a lot that has to be fixed first before we make it available to everyone. We're going to backlog this for now as we ramp up for open source.

**Comment by indy-singh** [comment]
@Zhao-Andy can we apply to be in the beta?

Thanks,
Indy

**Comment by gregoryhammond** [comment]
@indy-singh you are part of the beta when you get a [membership](https://dev.to/membership) (starts at $1/month)

**Comment by indy-singh** [comment]
Yes. I realised that shortly after commenting here. Subscribed!

Apologies for my brevity. Replying via email on my phone.

Regards,
Indy

**Comment by Booligoosh** [comment]
Would also love to see a big 'total all-time post views' number on the dashboard!

**Comment by darol100** [comment]
@gregoryhammond, What is the definition of a `view`? A count base on each page load or a view is considered whenever the user at least when to the end of the article and finished reading it?

If the number count is base on page load and the same user reloads the page 3 times would that be considered as three views?

**Comment by Zhao-Andy** [comment]
This is now live in your dashboard: https://dev.to/dashboard 👍
