### ISSUE TITLE
Cant save post

### ISSUE THREAD

**Issue by shameemreza** [thepracticaldev/dev.to#2271]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by jessleenyc** [comment]
Hey there, we’re currently experiencing some server issues right now. Sorry for the inconvenience and thanks for your patience.

**Comment by shameemreza** [comment]
Its ok, I am just reporting the issue.

**Comment by mariocsee** [comment]
Good news! We're back up and running, so you should be able to save your post and visit other pages on dev.to. I'm going to close this issue, but if you're still experiencing this, please let us know and we will look into it.
