### ISSUE TITLE
Error 500 trying to go to : https://dev.to/johannesvollmer/dont-be-a-bracist-2on

### ISSUE THREAD

**Issue by codethought** [thepracticaldev/dev.to#2272]
**Describe the bug**
Error 500 trying to go to : https://dev.to/johannesvollmer/dont-be-a-bracist-2on

**To Reproduce**

1. Go to https://dev.to/johannesvollmer/dont-be-a-bracist-2on
2. See error

**Expected behavior**
I get to see a nice webpage.

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS Mojave
- Chrome
- Version 72

- Safari 12.0.3

**Comment by jessleenyc** [comment]
Hey there, we’re currently experiencing some server issues right now and will get back up as soon as possible! Thanks for your patience!

**Comment by mariocsee** [comment]
Good news! We're back up and running, so you should have no problem visiting that article and other pages on dev.to. I'm going to close this issue, but if you're still experiencing this, please let us know.
