### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by 3l1s3** [thepracticaldev/dev.to#2274]
**Describe the bug**
Previously viewable article link, now generates 500 error

**To Reproduce**

1. Go to 
https://dev.to/ayrtonvwf/a-useful-progress-bar-fallback-to-ie9-css-only-14o0

2. See error

**Expected behavior**
Article should be viewable.

**Comment by mariocsee** [comment]
Hey there, we’re currently experiencing some server issues right now and will get back up as soon as possible! Thanks for your patience!

**Comment by mariocsee** [comment]
Good news! We're back up and running, so you should have no problem visiting that article and other pages on dev.to. I'm going to close this issue, but if you're still experiencing this, please let us know.
