### ISSUE TITLE
Page not loading

### ISSUE THREAD

**Issue by PratikTheGameDever** [thepracticaldev/dev.to#2275]
No Extensions

**Describe the bug**
https://dev.to/blueturtle/modular-front-end-development-23ej : page not loading

**Expected behavior**

- OS: Android latest
- Browser : chrome
- Version : latest

**Smartphone

- Device: pixel 3xl
- OS: Android latest
- Browser : chrome
- Version : latest

**Additional context**
Just clicked in Google suggested article

**Comment by mariocsee** [comment]
Hey there, we’re currently experiencing some server issues right now and will get back up as soon as possible! Thanks for your patience!

**Comment by mariocsee** [comment]
Good news! We're back up and running, so you should have no problem visiting that article and other pages on dev.to. I'm going to close this issue, but if you're still experiencing this, please let us know.
