### ISSUE TITLE
Save a post error 500 and unable to login

### ISSUE THREAD

**Issue by thetealpickle** [thepracticaldev/dev.to#2276]
I am having issues saving my posts, I persistently receive a error code 500.
Started to debug by opening dev.to in an incognito tab and I was unable to login.

When I attempted to log in with twitter I received the following error
![er2](https://user-images.githubusercontent.com/10859803/55339216-427bf100-5470-11e9-9c50-96c06900276f.jpg)

When I attempted to log in with Github I received the following error
![er1](https://user-images.githubusercontent.com/10859803/55339292-66d7cd80-5470-11e9-9de1-e7e5f48a88c2.jpg)

In addition I was also having issues with accessing my profile in general, I would receive a 500 error code.

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version 73 (chrome version)

**Comment by mariocsee** [comment]
Hey there, we’re currently experiencing some server issues right now and will get back up as soon as possible! Thanks for your patience!

If this persists once the server is back to normal, we will investigate it soon.

**Comment by mariocsee** [comment]
Good news! We're back up and running, so you should have no problem visiting that article and other pages on dev.to. I'm going to close this issue, but if you're still experiencing this, please let us know and we will look into it.
