### ISSUE TITLE
500 error when trying to update default reading font

### ISSUE THREAD

**Issue by john-angel** [thepracticaldev/dev.to#2277]
Hi there,

I´m getting a 500 error page when I try to set the font to Comic Sans. 

1. Go to 'https://dev.to/settings/misc'
2. Scroll down to 'Style customization'
3. Select "comic sans" from the Base Post Font dropdown.
4. Click Submit

**Screenshots**
![image](https://user-images.githubusercontent.com/18643893/55339550-823eda80-5468-11e9-870c-465d47aa4e94.png)

**Desktop (please complete the following information):**

- OS: Windows 7 Professional 64 bits English
- Browser: Chrome
- Version  73.0.3683.86 (Build oficial) (64 bits)

**Comment by mariocsee** [comment]
Hey there, we’re currently experiencing some server issues right now and will get back up as soon as possible! Thanks for your patience!

If this persists once the server is back to normal, we will investigate it soon.

**Comment by mariocsee** [comment]
Good news! We're back up and running, so you should have no problem visiting that article and other pages on dev.to. I'm going to close this issue, but if you're still experiencing this, please let us know and we will look into it.
