### ISSUE TITLE
Some dev.to pages are timing out

### ISSUE THREAD

**Issue by Stargator** [thepracticaldev/dev.to#2278]
**Describe the bug**
I can only access selective dev.to pages/posts.

For the web pages that I cannot access, I get a timeout error page with a Guru Mediation error code:
<img width="408" alt="Screen Shot 2019-04-01 at 11 59 07 AM" src="https://user-images.githubusercontent.com/7527155/55341957-9fc67100-5475-11e9-8e54-95893b423ee3.png">

**To Reproduce**

1. Go to either of the following links:
[Link 1](https://dev.to/raddevon/where-do-web-development-project-ideas-come-from-lfa)
[Link 2](https://dev.to/carlillo/part-8-clock-in-out-system-deploy-frontend-angular-6-using-environments-nog)
[Link 3](https://dev.to/thetealpickle/engineering-brunch-03-30-19-4h7o)
1. See error

**Expected behavior**
I expected for the links listed above to result in rendering of a post on dev.to.

**Desktop (please complete the following information):**

- OS: Mac OS 10.14.3
- Browser: Chrome
- Version: 73.0.3683.86

**Smartphone (please complete the following information):**

- Device: Google Pixel 3
- OS: Android Pie
- Browser: Chrome
- Version: 73.0.3683.90

**Comment by mariocsee** [comment]
Good news! We're back up and running, so you should have no problem visiting that article and other pages on dev.to. I'm going to close this issue, but if you're still experiencing this, please let us know.
