### ISSUE TITLE
Article does not load

### ISSUE THREAD

**Issue by almereyda** [thepracticaldev/dev.to#2279]
**Describe the bug**

Opening https://dev.to/david_j_eddy/opinion-architect-vs-engineer-vs-developer-5n0 fails with a 500 error message, and asks to submit here.

Before it showed a 503 Varnish cache error.

**To Reproduce**

1. Go to 'https://dev.to/david_j_eddy/opinion-architect-vs-engineer-vs-developer-5n0'
2. See error

**Expected behavior**

I'm expecting to see the article as of http://web.archive.org/web/20190325140955/https://dev.to/david_j_eddy/opinion-architect-vs-engineer-vs-developer-5n0

**Desktop:**

- OS: Fedora 29
- Browser Firefox 66

**Comment by mariocsee** [comment]
Hey there, we’re currently experiencing some server issues right now and will get back up as soon as possible! Thanks for your patience!

**Comment by abevoelker** [comment]
Seems to be happening to a lot of (all?) articles right now

**Comment by mariocsee** [comment]
Good news! We're back up and running, so you should have no problem visiting that article and other pages on dev.to. I'm going to close this issue, but if you're still experiencing this, please let us know.
