### ISSUE TITLE
The "add to reading list" buttons are inconsistent in the home page view and the single post view

### ISSUE THREAD

**Issue by sebacruz** [thepracticaldev/dev.to#228]
# _BUG_

### Current Behavior

The "add to reading list" button on home page view says "SAVE" and in the single post view it is an icon that looks like a "tags" icon with a number.

### Expected Behavior

The "add to reading list" button should be the same in the home page view and the single post view.

### Screenshots

| Home page View                                                                                                                                     | Single Post View                                                                                                                                   | 
|----------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------| 
| ![captura-de-pantalla-2018-06-08-a-las-3 10 46](https://user-images.githubusercontent.com/58810/41142509-51a1dee4-6acc-11e8-8d32-2f86758f51dd.png) | ![captura-de-pantalla-2018-06-08-a-las-3 10 57](https://user-images.githubusercontent.com/58810/41142508-51825ca4-6acc-11e8-97c6-b8d51f1ce162.png) |

**Comment by Zhao-Andy** [comment]
Hey @sebacruz, thanks for the design consideration :)

**Comment by wuz** [comment]
Some consideration for this: https://dev.to/jeancarl/can-i-save-a-single-article-to-my-reading-list-4epg/comments
