### ISSUE TITLE
Fallen Robot

### ISSUE THREAD

**Issue by rambotech** [thepracticaldev/dev.to#2280]
This link returns a 5xx page (fallen robot), and reported a 503 (first byte timeout) on the first refresh.

https://dev.to/azure/how-do-you-structure-your-code-when-moving-your-api-from-express-to-serverless-functions-30bc

**Comment by mariocsee** [comment]
Hey there, we’re currently experiencing some server issues right now and will get back up as soon as possible! Thanks for your patience!

**Comment by nickytonline** [comment]
It appears to be back on the East coast at least.

**Comment by mariocsee** [comment]
Good news! We're back up and running, so you should have no problem visiting that article and other pages on dev.to. I'm going to close this issue, but if you're still experiencing this, please let us know.
