### ISSUE TITLE
Add Markdown for descriptions of profiles

### ISSUE THREAD

**Issue by thomasbnt** [thepracticaldev/dev.to#229]
# _Feature_
**Add Markdown syntax for descriptions on profiles.**

Inserting links is not practical and is not clickable. Bold can be useful for importants words.

**Comment by Zhao-Andy** [comment]
Hey @thomasbnt, thanks for the feature request! We're going to consider doing this and put it in the backlog for now.

**Comment by thomasbnt** [comment]
Hey, this is always an open request 🐅

**Comment by jessleenyc** [comment]
We don't want to support links quite yet but this is approved for inline markdown (italics, bold, etc.) for anyone who wants to grab it!

**Comment by thomasbnt** [comment]
Why no links?

**Comment by thomasbnt** [comment]
Why no links?

>

**Comment by bolariin** [comment]
https://github.com/thepracticaldev/dev.to/blob/419ee348669c4dfcbad0d1b6f667dbbb45ba6888/app/labor/markdown_parser.rb#L49-L58

I found this function in `markdown-parser`. Are there more tags that should be allowed besides those present in `allowed_tags`?

**Comment by maestromac** [comment]
He @bolariin you can use those are a starting point. If more come to mind we'll suggest changes in the PR.

**Comment by rhymes** [comment]
Closing this because we're not going to proceed on markdown in the profiles description for the time being
