### ISSUE TITLE
Code sandbox liquid tag w/ focus input causes scrolling on page load

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#2290]
**Describe the bug**
Reported by a user trying to embed a codesandbox that focuses an input. The page 'jumps'/scrolls to the embed when it loads.

**To Reproduce**
Create a new post w/ this liquid tag: `{% codesandbox pyqq0o9mk7 %}`. Make sure it appears below the fold so you can see the jump.

**Expected behavior**
Liquid Tag shouldn't cause scrolling on page load.

**Comment by benhalpern** [comment]
Is there anything we can do with iframe attributes to turn this off?

**Comment by mariocsee** [comment]
In the (CodeSandbox documentation)[https://codesandbox.io/docs/embedding#embed-options], there's an option `runonclick` that the user will have to add to prevent the jump (by not loading the codesandbox until the article reader decides to). 

The codesandbox liquid tag doesn't support `runonclick`, but extending the regex query to accept `runonclick` in the `valid_option` method in `codesandbox_tag.rb` should do the trick. How does this workaround sound?

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/2381
