### ISSUE TITLE
Website Domain validation with '-' considered invalid. i.e "www.test-example.com"

### ISSUE THREAD

**Issue by isthiiii** [thepracticaldev/dev.to#2294]
**Describe the bug**
Validation for websites in the update profile page considers a website with a '-' dash symbol inbetween as invalid.

**To Reproduce**

1. Go to https://dev.to/settings once logged in
2. Click on 'update website url field'
3. Enter invalid url i.e www.test-example.com

**Expected behavior**
Should be accepted as a valid domain.

**Comment by rhymes** [comment]
@isthiiii I think that's because it's missing the protol, hence it's not a full URL. Add it as `http://www.test-example.com/` instead of `www.test-example.com` and it should work

**Comment by isthiiii** [comment]
> http://www.test-example.com/

Yep Works :)
