### ISSUE TITLE
Drag and drop images

### ISSUE THREAD

**Issue by jorgeRafaelSJ** [thepracticaldev/dev.to#23]
Hi Jess! <3

So, I was trying to drag and drop the humor section image that appears on the home page to share with a friend via iMessage. Appears that the image is being stored on github so the link doesn't actually preview the image, it shows the logo. So I had to go to the github file and then drag and drop the image file from there. Would expedite sharing.

**Comment by benhalpern** [comment]
Good call. Been meaning to make this more of a feature in general. I'd say it's a half-done feature at most right now.

**Comment by jessleenyc** [comment]
@jorgerafaelsj -- you can now upload images, but it's not drag and drop.
