### ISSUE TITLE
API Analytics Bug Thread

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/dev.to#2307]
This is mostly a note for myself, but maybe other contributors will have some thoughts on this. 

Some current bugs we have:
- requesting data for more than two weeks usually times out
- the last day of data always has nothing for some reason (probably a weird time issue)

The main issue is that there's a lot of loops being used to organize the data over time (see [`analytics_service.rb#stats_grouped_by_day`](https://github.com/thepracticaldev/dev.to/blob/master/app/services/analytics_service.rb)). We can probably solve the time out issue by caching the data somehow, but I'm not sure how to do that.

**Comment by rhymes** [comment]
Hi Andy! I think the main issue is that you're loading everything in memory and for big organizations or popular users that might be a lot of data. I was coincidentally working on refactoring the code, I'll upload the branch shortly and we can look at it together?

**Comment by Zhao-Andy** [comment]
Hey @rhymes, that would be great! Feel free to ping me whenever. Appreciate all the help!
