### ISSUE TITLE
Feature Request: Lightbox images on posts

### ISSUE THREAD

**Issue by basteez** [thepracticaldev/dev.to#231]
# Lightbox images on posts
It would be **awesome** to have a [lightbox](http://lokeshdhakar.com/projects/lightbox2/) mode for the images in the posts: current behavior is a redirect to the image's link location, so if I click on an image to see it better then I have to go back in browser history in order to keep on reading the post.

**Comment by Zhao-Andy** [comment]
Hey @basteez, thanks for the feature request. We're going to backlog this for now as we ramp up to open source.

**Comment by jessleenyc** [comment]
A similar issue came in that's a little more broad, so closing this one. 
We'll start the discussion here: https://github.com/thepracticaldev/dev.to/issues/413
