### ISSUE TITLE
Change color background of the .top-bar and delete border-bottom

### ISSUE THREAD

**Issue by thomasbnt** [thepracticaldev/dev.to#232]
# _Feature_
### Request 

Change the color background of the `top-bar` class and nav.

```css
background: #ffffff;
```
Also for submenus when logged in for `.top-bar nav .menu` : 
```css
background: #ffffff;
```

Delete border-bottom for `.top-bar`  :

```css
border-bottom: 1px solid rgba(0,0,0,0.33); 
```

It's clearer and more refreshing

### Screenshot

![tgfdssdfgtrd](https://user-images.githubusercontent.com/14293805/41257714-29bd8590-6dce-11e8-915b-a3663e7495ee.png)

**Comment by Zhao-Andy** [comment]
Hey @thomasbnt, thanks for the design consideration :)

**Comment by thomasbnt** [comment]
Good idea! :D
