### ISSUE TITLE
After trying to login(Github via 2fa w/google authenticator ) so I could reply to an article I got the screen saying to email you as the email im trying to login with is already taken. Then I try it logging in via twitter and it the error screen i get says "something went wrong it's our fault not yours" and asks if I would like to submit a report....... so here i am. I like the content this site offers and I remember running in to this some time back preventing me from participating in the community. Hopefully you can get'er fixed or make the error screens more informative to help me fix the issue myself . Cheers 

### ISSUE THREAD

**Issue by Marshallsbest** [thepracticaldev/dev.to#2323]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by Zhao-Andy** [comment]
Hey @Marshallsbest, this should be an issue with your specific account. If you could send an email to yo@dev.to we'll help you resolve it from there.
