### ISSUE TITLE
Feature Request: Turning off notifications

### ISSUE THREAD

**Issue by amy** [thepracticaldev/dev.to#234]
# Feature

### Request or User Story
I would like to be able to turn off specific categories of notifications. Or for instance unsubscribing from notifications coming from one post. 

### Definition of Done
Being able to opt out of select post notifications

### Notes
Thanks!

**Comment by Zhao-Andy** [comment]
Thanks for the issue @amy!

**Comment by jessleenyc** [comment]
Let's start with adding the ability to mute comments from a specific article.
