### ISSUE TITLE
Add phpc.social to Mastodon whitelist

### ISSUE THREAD

**Issue by ramsey** [thepracticaldev/dev.to#2345]
**Describe the bug**
I am unable to add my Mastodon URL since it is not whitelisted.

**To Reproduce**

1. Go to https://dev.to/settings
2. Enter `https://phpc.social/@ramsey` in the Mastodon URL field
3. Click Submit
4. See the error in the attached screenshot

**Expected behavior**
Saving settings succeeds when using my Mastodon URL.

**Screenshots**
<img width="872" alt="Screen Shot 2019-04-08 at 17 35 41" src="https://user-images.githubusercontent.com/42941/55761520-2a364400-5a25-11e9-8aab-62b8c88e58f1.png">

**Comment by mariocsee** [comment]
Just added "phpc.social" to the list of accepted Mastodon links in PR above!
