### ISSUE TITLE
GDPR compliance: ability to request data export and permanently delete personal account

### ISSUE THREAD

**Issue by 0x13a** [thepracticaldev/dev.to#235]
### Ability to request data export and permanently delete personal account

Only mandatory for EU citizens

### Definition of Done
- A user must be able to request a data export in machine readable format https://advisera.com/eugdpracademy/gdpr/right-of-access-by-the-data-subject/

- A user must be able to request the permanent deletion of all his personal data https://advisera.com/eugdpracademy/gdpr/right-to-erasure-right-to-be-forgotten/

**Comment by Zhao-Andy** [comment]
Hey @0x13a, any account deletion requests or data export requests can be sent to: privacy@dev.to

For more information, please see our privacy page: https://dev.to/privacy
