### ISSUE TITLE
🌱More Seed Data

### ISSUE THREAD

**Issue by omenking** [thepracticaldev/dev.to#2356]
**Is your feature request related to a problem? Please describe.**

Working on this ticket I don't have sufficient seed data.
https://github.com/thepracticaldev/dev.to/issues/258

**Describe the solution you'd like**

* I am going to bring in more tags
* I am going to generate some fake organizations if this does not already exist in the seed data
*  I am going to create a new user outside the random users.
*  For this new user, I am going to randomly generate data so they have more in their dashboard.
*  I am going to add an endpoint that will only work in development for an easy way to log in as this user

**Describe alternatives you've considered**
Nada.

**Additional context**
Nada.

**Comment by omenking** [comment]
<img width="1277" alt="Screen Shot 2019-04-09 at 10 47 18 PM" src="https://user-images.githubusercontent.com/7776/55847972-79f63780-5b19-11e9-9a10-2d4db1253b24.png">

**Comment by omenking** [comment]
@Zhao-Andy brought in the quick login for development you saw in a previous ticket I documented.
I am waiting for the approval for this ticket so I may complete:
https://github.com/thepracticaldev/dev.to/issues/258

**Comment by Zhao-Andy** [comment]
@omenking approved, thanks!

**Comment by rhymes** [comment]
Even though usually older issues are favored over newer duplicated ones, I feel the topic and scope are slightly different from this previous issue. We've also let this one and its related PR sit in the backburner for a very long time without making any progress. Hence I'm closing this one in favor of https://github.com/thepracticaldev/dev.to/issues/4149
