### ISSUE TITLE
Dark mode & comments preview

### ISSUE THREAD

**Issue by rogovdm** [thepracticaldev/dev.to#2359]
![image](https://user-images.githubusercontent.com/1548235/55879225-c50a5c00-5ba6-11e9-9ab8-734b229256f5.png)

**Comment by venarius** [comment]
This has already been fixed in https://github.com/thepracticaldev/dev.to/pull/2363. But I have noticed that the loading animation on swap between preview and markdown also looks weird on dark mode. Will investigate.
