### ISSUE TITLE
Estimating user default language job fails when the corresponding language field doesn't exist

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#2369]
**Describe the bug**
Delayed jobs fail with errors like `unknown attribute 'prefer_language_vi' for User`

**To Reproduce**
Login via twitter as a user who has their language set other than `en`, `ja`, `es`, `fr`, `it`.
Delayed job for `estimate_default_language!` will fail.

**Expected behavior**
Don't try to update the `language_settings` with invalid attributes.

**Comment by benhalpern** [comment]
I feel like the current implementation is a bit silly to limit default languages. We should probably modify this somehow to allow many more languages to be chosen from.

**Comment by lightalloy** [comment]
Closed by #2496
