### ISSUE TITLE
Literal `---` inside Markdown block renders as `--------`

### ISSUE THREAD

**Issue by cjbrooks12** [thepracticaldev/dev.to#237]
# _BUG_
### Current Behavior

Part of an article I'm writing includes code snippets which include their own Front Matter snippets, such as:

```markdown
---
title: Page Title
---
```

These are currently being rendered such that these snippets cannot be copy-and-pasted because they display as:

```markdown
--------
title: Page Title
--------
```

### Expected Behavior

Literal `---` should not be expanded into `--------` but stay as `---` when inside a multiline code block.

### Additional Info (steps to replicate, device/browser, helpful links)

Two consecutive dashes (`--`) renders fine.
A space followed by three consecutive dashes (`---`) renders as three dashes, but still cannot be copy-pasted because now the line starts with a space.

### Screenshots

<img width="254" alt="screen shot 2018-06-18 at 20 22 21" src="https://user-images.githubusercontent.com/6157866/41570663-5bc2fc20-7335-11e8-8178-5b69b9d202b6.png">
<img width="279" alt="screen shot 2018-06-18 at 20 21 09" src="https://user-images.githubusercontent.com/6157866/41570662-5bb0b902-7335-11e8-9f1c-7162139db348.png">

**Comment by Zhao-Andy** [comment]
Ah, thanks for the heads up. Leaving a note to fix this too, since they're related issues:
https://dev.to/jwoertink/a-bug-in-this-site-3jdm/comments

**Comment by Zhao-Andy** [comment]
Fixed thanks to @maestromac :)
