### ISSUE TITLE
Feature Request: Article complexity

### ISSUE THREAD

**Issue by GMartigny** [thepracticaldev/dev.to#2371]
**Is your feature request related to a problem? Please describe.**
I often have a hard time finding article at the right level of complexity. Reading a very long article barely scratching the surface of a subject can be frustrating. Also, needing a beginner guide and only finding in-depth of specific subject is demotivating.

**Describe the solution you'd like**
The new `Time to read` feature is a good step, but I would like to see a complexity meter. I'm not sure about the exact nomenclature, but it can be a simple (beginner, advanced or master) drop-down in the editor.

**Describe alternatives you've considered**
I can't see one.

**Additional context**
example:
![image](https://user-images.githubusercontent.com/2543511/55947298-787a5b80-5c4e-11e9-938e-970b220beedc.png)
Setting any value for this by default is not a good idea, unknowing writer should not have their post set to any complexity.

**Comment by rhymes** [comment]
Hi @GMartigny you're likely going to be interested in this PR that was merged in February and the discussion that ensued https://github.com/thepracticaldev/dev.to/pull/1922

Basically there's a way to vote required the estimated experience level for articles, currently available only to moderators, it's not open to the article's author yet either.

**Comment by aspittel** [comment]
Thanks @rhymes for the explanation and @GMartigny for the feature request! @benhalpern is working on a similar idea!

**Comment by jessleenyc** [comment]
The function to add an experience level to your own posts is also available by clicking 'manage' in your dashboard. Is your request to display a complexity meter next to each post or for the feed to be smart enough to surface the right types of posts for you? If the latter, I think we're on our way. If the prior, we'll have to discuss whether or not we'd want something like that publicly displayed.

**Comment by GMartigny** [comment]
@jessleenyc It would be awesome to be able to have an idea of any article's complexity. So mainly, I was thinking about the "prior".

But if at least, the feed is giving me mostly the right types of articles, it's already cool.
