### ISSUE TITLE
unable to write post

### ISSUE THREAD

**Issue by jaswantkaur** [thepracticaldev/dev.to#2375]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by aspittel** [comment]
Hey @jaswantkaur do you have any more context for this issue? Right now, I'm just seeing the issue template! What steps did you take to create the post and what error were you seeing?

**Comment by maestromac** [comment]
Hello @jaswantkaur , this looks an issue specific to your account. Please email yo@dev.to for more help.
