### ISSUE TITLE
Setting Integration: github code of emoji in description

### ISSUE THREAD

**Issue by ptkdev** [thepracticaldev/dev.to#238]
# _BUG_
### Current Behavior
1. Go to dev.to --> settings --> integration --> add reposioty github to your profile with emoji in description example: `:robot:`
2. I See github code of emoji

### Expected Behavior
1. Image of emoji

### Additional Info (steps to replicate, device/browser, helpful links)
If i copy emoji ascii code, and paste in description that work

### Screenshots
<img src="https://image.ibb.co/gEubUd/Schermata_2018_06_19_alle_11_19_28.png">

**Comment by maestromac** [comment]
Sorry this missed me. I think is a nice to have feature so the issue should be reopened.

**Comment by Zhao-Andy** [comment]
This should remain open.

We now use GitHub's [gemoji gem](https://github.com/github/gemoji), so we can probably use this and the `emoji_converter.rb` file to update GitHub repo names before saving them:
https://github.com/thepracticaldev/dev.to/blob/master/app/labor/emoji_converter.rb

**Comment by maestromac** [comment]
not stale
