### ISSUE TITLE
Consider using Gitpod prebuilds

### ISSUE THREAD

**Issue by jankeromnes** [thepracticaldev/dev.to#2380]
**Is your feature request related to a problem? Please describe.**

It's frustrating to wait while dependencies are being installed.

**Describe the solution you'd like**

Gitpod is able to detect changes in this repository, and automatically prepare new workspaces by checking out the new code and installing dependencies ahead of time. That way, when a developer starts a new DEV workspace, they don't have to wait for dependencies to be installed -- everything will already be checked out and good to go.

To enable prebuilt workspaces, please follow these steps:

1. Go to the [gitpod-io GitHub app](https://github.com/apps/gitpod-io) and click `Configure`
2. Please select this org (`thepracticaldev`) and repo (`dev.to`), and click `Install`
3. You will be forwarded to Gitpod to confirm the installation

**Describe alternatives you've considered**

The current setup already saves time by installing dependencies automatically (just not ahead of time).

The dependencies themselves could be made to install faster, but that's not easy.

**Additional context**

More info on Gitpod prebuilt workspaces & their configuration:
https://www.gitpod.io/docs/46_Prebuilds/

Blog post: Waiting for code to build is like watching paint dry:
https://www.gitpod.io/blog/prebuilds/

**Comment by maestromac** [comment]
Thank you for the suggestion! Resolved via 05b7208

**Comment by jankeromnes** [comment]
Hi @maestromac, thank you for the update!

The configuration you added looks great, but it may get a bit noisy (because it makes Gitpod add a check + a comment + a label). It's also missing:

```yaml
    # add a check to pull requests (defaults to true)
    addCheck: true
```

but that's ok if you want the default value.

**Comment by maestromac** [comment]
Oh good point. Went ahead and made the update  4b5622f

**Comment by jankeromnes** [comment]
That's perfect, thanks! You now have all the [prebuild options](https://www.gitpod.io/docs/46_Prebuilds/#configure-prebuilds) listed explicitly in `.gitpod.yml`. 👍

Note: If PR reviewers don't see the Checks, you might consider re-enabling Comments as well (I personally like Checks + Comments, but find Labels a bit too noisy).

I think Comments is what @benhalpern suggested in https://github.com/thepracticaldev/dev.to/pull/2379#issuecomment-482191030.
