### ISSUE TITLE
Error 503 first byte timeout

### ISSUE THREAD

**Issue by rapulu** [thepracticaldev/dev.to#2387]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by Zhao-Andy** [comment]
Thanks for the issue. We're experiencing some server issues right now and will get back live as soon as possible!

**Comment by jessleenyc** [comment]
Things should be resolved now but please feel free to open a new issue if you're still experiencing errors.
