### ISSUE TITLE
Bug design on DevConnect with code embed

### ISSUE THREAD

**Issue by thomasbnt** [thepracticaldev/dev.to#239]
# _BUG_
### Current Behavior
Hi ! I report a bug design in devConnect, when i click on a link of post, the scroll horizontal show when an code embed. 

### Screenshots
![image](https://user-images.githubusercontent.com/14293805/41995727-04a28800-7a53-11e8-8f44-339c40ce23c6.png)

**Comment by jessleenyc** [comment]
@thomasbnt any chance you still remember which article that is? I can't seem to recreate the issue. More info on browser would be helpful too.

**Comment by thomasbnt** [comment]
@jessleenyc  I can't reproduce it anymore, but it was in the 'Connect' part, we could click on the links of the articles and it metais on the side

**Comment by jessleenyc** [comment]
Ah okay. We've made a few changes overall that may have fixed it. Closing for now.
