### ISSUE TITLE
DEV tag liquid tag

### ISSUE THREAD

**Issue by mariocsee** [thepracticaldev/dev.to#2397]
**Describe the bug**
In dark mode, dev.to tag liquid tags i.e. `{% tag discuss %}` doesn't have proper contrast. Title text is hard to read. Also, `{% tag javascript %}` seems to almost take other subsequent tags inside it when viewing in preview. Bug also persists for when the post is published.

So almost two issues here: text contrast in dark mode and maybe something specific to javascript tag.

**To Reproduce**

1. Make sure you're on v2 editor
2. Write a new post
3. Create some tag liquid tags such as {% tag career %} and try {% tag javascript %} in particular
4. Click preview and see error
5. Publish and the error persists on the article page

**Expected behavior**
The tag text on the liquid tag should be adjusted for dark mode, and liquid tag shouldn't encase another.

**Screenshots**
### Draft
<img width="720" alt="Screen Shot 2019-04-11 at 17 56 35" src="https://user-images.githubusercontent.com/13403332/55996111-7501c700-5c84-11e9-9c12-0fbb767818cf.png">

### Preview
<img width="720" alt="Screen Shot 2019-04-11 at 17 56 24" src="https://user-images.githubusercontent.com/13403332/55996122-7b903e80-5c84-11e9-8694-70421035366c.png">

### Article 
<img width="721" alt="Screen Shot 2019-04-11 at 18 10 29" src="https://user-images.githubusercontent.com/13403332/55996357-26086180-5c85-11e9-9e68-d1cf741e0d95.png">

**Desktop (please complete the following information):**

- OS: MacOS 10.14.3
- Browser: Chrome 
- Version: 73

**Additional context**
N/A so far.

**Comment by venarius** [comment]
Will work on it 🙂

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/2459
