### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by Gherciu** [thepracticaldev/dev.to#2398]
1. Go to 'https://dev.to/sunnysingh/writing-code-for-your-future-self-3da2?utm_source=additional_box&utm_medium=internal&utm_campaign=regular&booster_org='
2. See error

- OS: [windows]
- Browser [chrome,]
- Version [70]

**Comment by jessleenyc** [comment]
Thanks for the issue. We're experiencing some server issues right now and will get back up as soon as possible!

**Comment by JacobMGEvans** [comment]
Anything we can help with?

**Comment by mindsers** [comment]
Same. I get this error on every single page of dev.to right now.

**Comment by jessleenyc** [comment]
Hey all - thanks for flagging. Things should be resolved now but please feel free to open a new issue if you're still experiencing errors.
