### ISSUE TITLE
Dev.to Livestream not loading

### ISSUE THREAD

**Issue by FRosner** [thepracticaldev/dev.to#240]
# _BUG_
### Current Behavior

https://dev.to/live not working. The video is not loading.

### Expected Behavior

The video is loading.

### Additional Info (steps to replicate, device/browser, helpful links)

- Version 67.0.3396.99 (Official Build) (64-bit)
- ABP plugin enabled
- Ghostery plugin enabled
- Didn't work after multiple refreshes

### Screenshots

![image](https://user-images.githubusercontent.com/3427394/42055766-5cdd2e60-7b18-11e8-8d25-81e6bef54283.png)

**Comment by Zhao-Andy** [comment]
Hey Frank, thanks for the heads up. It's most likely an issue where cookies are being blocked from iframes, which prevents the stream from loading. My guess is that Ghostery/ABP/both might have prevented the video from loading.
