### ISSUE TITLE
Bug: Single article unpublished should have dark background under dark mode.

### ISSUE THREAD

**Issue by wgao19** [thepracticaldev/dev.to#2400]
**Describe the bug**
The night mode is awesome! However, unpublished posts got wrong background now. See screenshots.

**To Reproduce**

1. Go to 'Dashboard'

**Expected behavior**
Expect a dark background but different from other blog posts' background.

**Screenshots**

Current:
![](https://i.imgur.com/gnTmjev.png)

My imaginary expected behavior:
![](https://i.imgur.com/Px3rk1T.png)

**Desktop (please complete the following information):**

- OS: [macOS Mojave 10.14.3]
- Browsers: Chrome, Safari, Firefox Nightly
- Versions: 73.0.3683.86 (Official Build) (64-bit), 12.0.3 (14606.4.5), 68.0a1 (2019-04-10) (64-bit)

**Smartphone (please complete the following information):**

NA

**Additional context**

I have [a fix using mix-blend-mode](https://github.com/wgao19/dev.to/commit/4c8b87b1960cc858209f48a82bc3bf105fd3178c) (will compute from the light and the dark background and yield a matching color). I'd like to pull up PR for this fix if accepted.
However, due to the [lack of support of mix-blend-mode](https://caniuse.com/#search=background-blend-mode), would like to figure out other fixes as well if it's not acceptable.

**Comment by Glennmen** [comment]
Thanks for reporting this issue, but there already is an open issue for this: #2182

**Comment by wgao19** [comment]
Hi @Glennmen seems there's already a fix for it. Feel free to close this one :]

**Comment by jessleenyc** [comment]
Thanks @wgao19, closing bc of the above reasons!
