### ISSUE TITLE
I'm not updating my profile social links

### ISSUE THREAD

**Issue by cnviradiya** [thepracticaldev/dev.to#2405]
I'm updating my profile social links
Linked-in, facebook, mediam

After Inserting links I pressed the submit button and error is appear at moment

**Describe the bug**
Error is 500 Error

**To Reproduce**

1. Go to 'My profile'
2. Click on 'setting'
3. Scroll down to 'social links and update those links'
4. See error 500 after submit the form

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by Zhao-Andy** [comment]
Hey @cnviradiya, thanks for the report. We were having server issues before and you should be able to update your links again. Feel free to reopen this issue if you're still experiencing errors.
