### ISSUE TITLE
I can not post my blogs

### ISSUE THREAD

**Issue by softwarefirms** [thepracticaldev/dev.to#2406]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by softwarefirms** [comment]
Please resolve it soon

**Comment by jessleenyc** [comment]
Things should be resolved now but please feel free to open a new issue or email yo@dev.to if you're still experiencing errors.

**Comment by muctim** [comment]
what happened to my blog in here? dev.to/muctim I cannot post why?

**Comment by jessleenyc** [comment]
@muctimThis looks like an individual account issue. Please email yo@dev.to.
