### ISSUE TITLE
500 error for the blog post and when hitting save post

### ISSUE THREAD

**Issue by Param-Harrison** [thepracticaldev/dev.to#2407]
Describe the bug
Previously viewable article link, now generates 500 error

To Reproduce

Go to
https://dev.to/paramharrison/different-types-of-routers-in-react-router-1j6k

See error

Expected behavior
Article should be viewable.

**Comment by SantiMA10** [comment]
+1

With this link: https://dev.to/svenefftinge/introducing-gitpod-frictionless-coding-on-github-397g

**Comment by oninross** [comment]
+1

With this link: [https://dev.to/oninross/the-art-of-minimalism-with-ux-4ppd](https://dev.to/oninross/the-art-of-minimalism-with-ux-4ppd)

**Comment by Zhao-Andy** [comment]
Thanks for the heads up! We were experiencing server issues and those links should be working again.
