### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by bhajko** [thepracticaldev/dev.to#2408]
**Describe the bug**
HTTP 500 Server Error

**To Reproduce**

1. Go to 'dev.to'
2. Click on '...'

**Expected behavior**
Page does not load after

**Screenshots**

**Desktop (please complete the following information):**

- OS: [Windows 10]
- Browser [chrome]
- Version [Version 73.0.3683.103 (Official Build) (64-bit)]

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by jessleenyc** [comment]
Thanks for flagging --- we were experiencing some server errors but things should be resolved now. Please feel free to re-open if you're still experiencing issues.
