### ISSUE TITLE
Can't leave comments on posts

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#2409]
**Describe the bug**

I opened a post like https://dev.to/mpermar/how-to-create-effective-pull-requests-2m8e to leave a comment but I couldn't complete the operation.

I opened the Firefox developer tools and noticed the following messages:

```
Error while fetching an original source: TypeError: NetworkError when attempting to fetch resource.
Source URL: webpack:///app/javascript/chat/util.js
SyntaxError: expected expression, got '<'
```

then if I try to add a comment anyway, it results ina 500 error:

![Screenshot 2019-04-12 at 10 12 56 AM](https://user-images.githubusercontent.com/146201/56022291-9ce83d80-5d0b-11e9-8380-7c7cfd2e71bd.png)

**To Reproduce**

1. Go to 'https://dev.to/mpermar/how-to-create-effective-pull-requests-2m8e'
2. Click on 'discuss'
3. Leave a comment
4. Open the console and then network tab, see the errors

**Expected behavior**

I'd expect the comment to be added to the page

**Desktop (please complete the following information):**

- OS: macOS 10.14.4
- Browser: Firefox
- Version: 67.0b9

**Additional context**

I'm sure it's related to the other 500 errors that have been popping up today/yesterday.
Thanks for the dedication!

**Comment by Zhao-Andy** [comment]
Closing since we had server issues and should be back up!
