### ISSUE TITLE
Article URL is far longer than it should be

### ISSUE THREAD

**Issue by nektro** [thepracticaldev/dev.to#241]
# _BUG_
### Current Behavior
https://dev.to/alexgwartney/my-7-month-update-of-my-programming-journey---------------------------------21i9

### Expected Behavior
https://dev.to/alexgwartney/my-7-month-update-of-my-programming-journey-21i9

**Comment by Zhao-Andy** [comment]
Ah, looks like there were a bunch of additional spaces after the title. Thanks for the heads up!
