### ISSUE TITLE
Removing an article from the reading list leads to an error (but not always)

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#2410]
**Describe the bug**

I've tried to remove an article - https://dev.to/mpermar/how-to-create-effective-pull-requests-2m8e - from the reading list but after a few seconds the icon returned to be blue.

![remove_from_reading_list](https://user-images.githubusercontent.com/146201/56022711-9b6b4500-5d0c-11e9-8db0-6037d2fb5488.gif)

I've pressed the button a second time and it worked.

I tried again, re-saving the article (went through) and then re-removing the save and it triggered a 500 error, undoing the operation, defaulting back to a saved article:

![Screenshot 2019-04-12 at 10 23 58 AM](https://user-images.githubusercontent.com/146201/56023014-40861d80-5d0d-11e9-8866-c4ee7db45f9a.png)

As you notice it took also quite a while 17 seconds to save, 26 to try to remove the save.

**To Reproduce**

1. Go to 'https://dev.to/mpermar/how-to-create-effective-pull-requests-2m8e'
2. Click on save a few times keeping the network tab of the developer tools open

**Expected behavior**

I'd expect the save/unsave operations to work in a timely fashion.

**Desktop (please complete the following information):**

- OS: macOS 10.14
- Browser: Firefox
- Version: 67.0b9

**Additional context**

It is probably related to #2411

**Comment by Zhao-Andy** [comment]
Closing since we had server issues and should be back up!
