### ISSUE TITLE
Error getting user and CSRF Token Error when opening an article

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#2411]
**Describe the bug**

The following bug appears if you keep the developer tools open when you open an article like https://dev.to/mpermar/how-to-create-effective-pull-requests-2m8e 

```text
 Error getting user and CSRF Token Error: "Couldn't find user data on page."
    e util.js:15
base-1e388e9a79b68fbf3ddd81e4219703e733bdbe6743cf1bb492d6420f878efde1.js:70:3632
    o base-1e388e9a79b68fbf3ddd81e4219703e733bdbe6743cf1bb492d6420f878efde1.js:70
    153 Onboarding.jsx:51
```

**To Reproduce**

1. Open a new tab, open the developer tools on the console
2. Go to Go to 'https://dev.to/mpermar/how-to-create-effective-pull-requests-2m8e'
3. See error

**Expected behavior**

I'd expect the error not to happen

**Desktop (please complete the following information):**

- OS: macOS 10.14
- Browser: Firefox
- Version: 67.0b9

**Comment by Zhao-Andy** [comment]
Hey @rhymes, thanks for the heads up. We think this is probably because of the server issues we had. Going to close this issue as well as #2410 and #2409 since we should be back up. :)
