### ISSUE TITLE
og:site_name meta tag is broken

### ISSUE THREAD

**Issue by nepeckman** [thepracticaldev/dev.to#2414]
**Describe the bug**
The site name appears as "The #{ApplicationConfig['COMMUNITY_NAME']} Community" (no text substitution is occurring).

**To Reproduce**

1. Go to the main page of Dev.to
2. Inspect the meta tags in the HTML
3. See the tag 
```html
<meta property="og:site_name" content="The #{ApplicationConfig['COMMUNITY_NAME']} Community">
```

**Expected behavior**
String substitution should occur, replacing #{ApplicationConfig['COMMUNITY_NAME']} with the actual name of the community.

**Additional context**
It seems like the string is lacking the `<%=` tag needed for the erb template. [See here.](https://github.com/thepracticaldev/dev.to/blob/c68228cda6d619dbb69936f33bdf7ceb1d29cbdf/app/views/articles/index.html.erb#L17) Git blame says its @benhalpern's fault 😉

**Comment by rhymes** [comment]
I'll be taking this on if no one's working on it :)
