### ISSUE TITLE
DEV Connect Night Mode

### ISSUE THREAD

**Issue by mariocsee** [thepracticaldev/dev.to#2417]
**Describe the bug**
Night mode on `/connect` is inconsistent with night mode with the rest of dev.to.

**To Reproduce**

1. Change your settings to dark/night mode
2. Navigate to `/connect`
3. Explore group chats, direct messages, user profiles, article previews, etc.

**Expected behavior**
Styles need to be updated for better readability/contrast and consistency in theme.

**Screenshots**
<img width="1280" alt="Screen Shot 2019-04-12 at 14 05 18" src="https://user-images.githubusercontent.com/13403332/56057286-7090e900-5d2c-11e9-95d4-c7e6a11111ba.png">

<img width="1280" alt="Screen Shot 2019-04-12 at 13 58 44" src="https://user-images.githubusercontent.com/13403332/56057006-cc0ea700-5d2b-11e9-9705-31d755d8da81.png">

<img width="1030" alt="Screen Shot 2019-04-12 at 13 59 22" src="https://user-images.githubusercontent.com/13403332/56056991-c1eca880-5d2b-11e9-8b37-25631c57ca4c.png">

**Desktop (please complete the following information):**

- OS: MacOS 10.14.3
- Browser: Chrome
- Version: 73

**Additional context**
Check other issues and PRs labeled nightmode, perhaps those merged to see how to go about tackling this issue.

**Comment by venarius** [comment]
Will work on it 🙂

**Comment by mariocsee** [comment]
Thanks @venarius! Really appreciate your contributions towards night mode as someone who always keeps it on. 😄
