### ISSUE TITLE
Underscore "_" in Title Blocks User From Posting Articles

### ISSUE THREAD

**Issue by michael-tharrington** [thepracticaldev/dev.to#2418]
**Describe the bug**
Including underscores in titles blocks users from posting articles. They receive the error message: `Slug is Invalid`.

**To Reproduce**

1. Go to https://dev.to/new
2. Write a post with a title that includes an underscore "_"
3. Set published to trure
4. Save the post

**Expected behavior**
Articles should be able to save with titles including underscores.

**Screenshots**

![](https://cl.ly/5122790cb48e/Image%2525202019-04-12%252520at%2525203.12.30%252520PM.png)

**Comment by mbifulco** [comment]
I ran into this with a post recently - I got around it by creating the post initially _without_ an underscore in the title, and then immediately re-saving it with an underscore.

Thanks for looking into this. It'll make it lots easier to wax philosophical about `node_modules` in the future ;)

**Comment by Zhao-Andy** [comment]
Resolved by #2472
