### ISSUE TITLE
Feature Request: comment streak badges

### ISSUE THREAD

**Issue by desirottman** [thepracticaldev/dev.to#2419]
**Is your feature request related to a problem? Please describe.**
Inspired by [this blog post](https://dev.to/mortoray/how-do-you-feel-about-chasing-internet-points-badges-and-the-gamification-of-everything-1l56) about writing streak badges and gamification, it might also be fun to offer 4-week and 8-week comment streak badges. It's another way to encourage interaction, and a low-stakes way for people to "bling" their profile if they're uncomfortable writing their own posts.

**Describe the solution you'd like**
Fun comment streak badges to live along with writing streak badges

**Additional context**
Just a gif of how I feel about the dev.to community
![masked wrestler applauding](https://media.giphy.com/media/46zvwjl2uznNQwemrW/giphy.gif)

**Comment by jessleenyc** [comment]
Love this idea!

**Comment by jessleenyc** [comment]
We should do this but I don't think it should be the same frequency as the article streak badges. Any thoughts here?

**Comment by jessleenyc** [comment]
We ended up rolling out 'the big thread badge' so I'm going to close this for now, though it's possible we'll want a comment streak one in the future!
