### ISSUE TITLE
night mode DEV badge

### ISSUE THREAD

**Issue by mariocsee** [thepracticaldev/dev.to#2420]
**Describe the bug**
In `/settings`, the DEV badge is hard to see when in night mode. 

**To Reproduce**

1. Make sure you have night mode on
2. Navigate to `/settings`
3. See above the Email section that the DEV badge is hard to see

**Expected behavior**
The contrast needs improvement so people can easily see it. Not sure if there should be a light colored version of DEV badge?

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/13403332/56062287-ddf74680-5d39-11e9-828e-db97b6a366b6.png)

**Desktop (please complete the following information):**

- OS: MacOS 10.14.3
- Browser Chrome
- Version 73

**Comment by venarius** [comment]
Will work on it 🙂
