### ISSUE TITLE
Hidden text in embedded tweet with Night Mode

### ISSUE THREAD

**Issue by healeycodes** [thepracticaldev/dev.to#2435]
**Describe the bug**
The embedded tweet element doesn't display correctly with Night Mode.

Some of the element's text is hidden (white on white).

**To Reproduce**

1. Toggle on Night Mode.
2. Visit [this article](https://dev.to/kylegalbraith/technical-skills-are-great-but-communication-and-curiosity-are-better-471j).
3. Look at the embedded tweet after the first sentence.

**Expected behavior**
Some of the tweet's text will appear invisible due to it being styled white with a white background. Highlighting the text will show that it is still present.

**Screenshots**
Here I show how the tweet displays in my browser and also how it looks when I highlight the hidden text.

![embeded-tweet](https://user-images.githubusercontent.com/34559231/56090560-9be61600-5e9b-11e9-8a01-84e1314d1821.png)

**Desktop:**

- OS: Windows 10
- Browser Chrome
- Version 73

**Additional context**
Thanks again for Night Mode!

![bart-hiding-from-sunlight](https://user-images.githubusercontent.com/34559231/56090589-f7180880-5e9b-11e9-987c-b7e8e8c77cf7.gif)

**Comment by maestromac** [comment]
Thank you for reporting this @healeycodes !
