### ISSUE TITLE
Read articles offline

### ISSUE THREAD

**Issue by atefBB** [thepracticaldev/dev.to#244]
# Read articles offline
Sometimes, I have not an Internet connection and I want to enjoy reading some articles in the site but I suck with the `service worker` page! 
Any plan for offline reading?

**Comment by pkfrank** [comment]
Hey @atefBB, thanks for the issue.  We'll investigate and try to implement a fix.  It's definitely our goal to provide a smooth offline reading experience via service workers.

**Comment by atefBB** [comment]
Thank you!

**Comment by atefBB** [comment]
@agonzalez0515 Nice to do! Thx.

**Comment by maestromac** [comment]
unstable

**Comment by atefBB** [comment]
This issue still requires attention and work
