### ISSUE TITLE
Reading List Comment view: Clicking heart does not trigger a like

### ISSUE THREAD

**Issue by bnb** [thepracticaldev/dev.to#2445]
**Describe the bug**
It appears that trying to ❤️ a comment on [the Reading List comments view](https://dev.to/readinglist?v=comments) currently does not actually ❤️ the comment – instead, it simply selects it.

**To Reproduce**

1. Go to 'https://dev.to/readinglist?v=comments'
2. Click on the ❤️ icon on any comment.
3. You will see that it is highlighted.

**Expected behavior**
A new like should be added.

**Screenshots**
![image](https://user-images.githubusercontent.com/502396/56132575-55a2bc80-5f58-11e9-8785-883b720226d5.png)

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version 73.0.3683.103

**Comment by Zhao-Andy** [comment]
Hey @bnb, thanks for the bug report! We'll take a look into it.

**Comment by mariocsee** [comment]
The click EventListener is missing from all hearts in the comments reading list. Will investigate further and open a PR to work on a fix. 

Also (styling wise) noticed that `.comments-container` should be a parent class to `.comment-view-parent`, but instead the parent is `.articles-container`, which results in the lack of styling for title "Re: How I Write..." in the comment. Dynamically changing class to `.comments-container` should fix scss selector, and updates need to be done to the styling as well.
