### ISSUE TITLE
Critical error: Variables in dashboard are not resolving, for example, article.page_views_count views

### ISSUE THREAD

**Issue by softchris** [thepracticaldev/dev.to#2448]
**Describe the bug**
Variables in dashboard are not resolving, for example, article.page_views_count views

should show actual numbers, not a variable

**To Reproduce**
Look at any dashboard

**Expected behavior**
That views on an article is a number and not a variable

**Comment by bnb** [comment]
+1, also seeing this: 

![image](https://user-images.githubusercontent.com/502396/56140068-1f6d3900-5f68-11e9-9b5b-e51c19a18302.png)

**Comment by Zhao-Andy** [comment]
Thanks for the heads up! Resolved by #2449. Deploy will be live soon.
