### ISSUE TITLE
Certain GitHub Repo liquid tags cause failure in preview/save

### ISSUE THREAD

**Issue by JeremyLikness** [thepracticaldev/dev.to#2452]
**Bug Description**
Liquid tags referencing certain GitHub repositories cause the editor to fail in both preview and save. It's not clear what the difference is, except possibly the length of the repo name. 

**To Reproduce**

1. Create a new article
2. Include the tag `{% github https://github.com/JeremyLikness/azure-fn-file-process-hol %}` (same thing happens whether you use the full link or the relative)
3. On preview or save, receive this error: 
![error_full_url](https://user-images.githubusercontent.com/5479675/56141412-9e0aac00-5f51-11e9-958c-4e4e6a8312b8.png)
4. Change the tag to use the repository id: `{% github 113606975 %}`  
5. On preview or save, receive the error: 
![error_repo_id](https://user-images.githubusercontent.com/5479675/56141439-a662e700-5f51-11e9-82b5-9de2df37c4de.png)

**Expected behavior**
The preview shows the summary card for the repo, and the save persists it.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 73.0.3683.103 (Official Build) (64-bit)

**Comment by Zhao-Andy** [comment]
Thanks for the report! We'll take a look.

**Comment by Zhao-Andy** [comment]
Hey @JeremyLikness, once the fix is deployed, this should work. Using the GitHub Liquid tag like so should work:
```
{% github https://github.com/JeremyLikness/azure-fn-file-process-hol %} 
// or
{% github JeremyLikness/azure-fn-file-process-hol %}
```

We currently don't support using repo IDs for the GitHub tag, but you can open a new issue and request the feature if you'd like.
