### ISSUE TITLE
View count is shown as "article.page_views_count"

### ISSUE THREAD

**Issue by dance2die** [thepracticaldev/dev.to#2453]
**Describe the bug**

Instead of view count, template string `article.page_views_count` is shown on the [dashboard](https://dev.to/dashboard).

**To Reproduce**
Go to https://dev.to/dashboard and see the views

![error](https://user-images.githubusercontent.com/8465237/56142512-cb188800-5f6c-11e9-95dc-f0450d319fb2.png)

**Expected behavior**
`article.page_views_count` should be displayed as a number.

**Desktop (please complete the following information):**

| Software         | Name/Version|
| ---------------- | ---------- |
| Chrome | 73.0.3683.103 (Official Build) (64-bit)
| FireFox Quantum | 66.0.2 (64-bit)
| Edge |  42.17134.1.0
| Windows 10 | Version 1803 (OS Build 17134.706)
| Ubuntu | 18.10

**Smartphone (please complete the following information):**

- Device: iPhone 7
- OS: iOS 12.2
- Browser Chrome
- Version 73.0.36383.68

**Additional context**
Occurs on Windows, Ubuntu, and on iPhone

**Comment by Zhao-Andy** [comment]
Thanks @dance2die! This should be resolved via #2449, which will be live soon.

**Comment by dance2die** [comment]
Thanks @Zhao-Andy ~~ I can see the count now
