### ISSUE TITLE
Editing profile displays that my twitter account is already taken (Logging in through twitter)

### ISSUE THREAD

**Issue by Eros** [thepracticaldev/dev.to#246]
# _BUG_
### Current Behavior
With any setting edited I receive the error provided in the screenshots tab. This happens when editing anything in my profile, I am currently logged in through twitter integration
### Expected Behavior
Be able to edit without having this error (Settings do not save)
### Additional Info (steps to replicate, device/browser, helpful links)

1. Go to profile settings
2. Edit any of them
3. Click save
4. Error shows up

### Screenshots
https://imgur.com/a/fBmC1Ke

**Comment by jessleenyc** [comment]
Hey @Eros - can you should us an email at yo@dev.to with your dev.to username?

**Comment by Eros** [comment]
Sure thing!

**Comment by Hazz223** [comment]
I'm having the same issue. Is there a fix for this?

**Comment by Eros** [comment]
@Hazz223 I sent them an email with the information posted above, they came back with a fix on my account within a couple of hours. Sure if you email them to address listed above they'd be able to help you.

**Comment by Zhao-Andy** [comment]
@Hazz223 and anyone else in the future with this issue: send an email yo@dev.to with your dev.to username and we'll take care of it. We'll have a better way of handling this in the future. :)
