### ISSUE TITLE
Articles missing content and HTTP 500 when tyring to edit

### ISSUE THREAD

**Issue by buntine** [thepracticaldev/dev.to#2464]
**Describe the bug**
About half of my article are affected. For example, if you go here, you will get an empty article: https://dev.to/buntine/the-balanced-ternary-machines-of-soviet-russia

If I try to edit this article, I get a 500.

**To Reproduce**
View or edit the article.

**Desktop (please complete the following information):**

- Linux (Manjaro)
- Firefox

**Comment by Zhao-Andy** [comment]
Hey, sorry about that. The content is missing, but the data is safe and still available. We'll fix that for you.

**Comment by benhalpern** [comment]
Hey Andrew, sorry about this. It appears that when we changed the way some of the data was stored, this article failed validation and it slipped through the crack. I fixed it for this post, but need to also go and do the same for a couple of your other older posts.

Thanks for bringing this up, this appears to affect a few dozen of the oldest posts on the platform, and we certainly want to preserve the reading and editing of all posts.

**Comment by benhalpern** [comment]
Okay, I fixed the problems with display. Issues with /edit could be an edge case that's not as apparent. Let me know if you have additional problems.

**Comment by buntine** [comment]
Hey, thanks for that guys.

I have noticed that it seems a new character set is being used. One of my older articles that uses some non-ascii charcters is now showing up pretty strangely: https://dev.to/buntine/p---the-original-brainfck-and-mother-of-the-turing-tarpits.
That is supposed to be ```P`````

I will close this issue now because the character issue is separate. If I cannot manually fix it I wlll open a new issue. Thanks agian.
