### ISSUE TITLE
Cannot post any comment, giving "Not authorized to change"

### ISSUE THREAD

**Issue by IvanDelsinne** [thepracticaldev/dev.to#248]
### Current Behavior

When I try to post a comment, I get the error shown in the image below.

!["The change you wanted was rejected"](https://pix.watch/gSuyl4/Ysltly.png)

### Expected Behavior

It should post the comment

### Additional Info (steps to replicate, device/browser, helpful links)

I encountered the problem on the [following post](https://dev.to/sadarshannaiynar/linux-distro-you-are-using-for-development-6fi).

**Comment by maestromac** [comment]
Hello @IvanDelsinne . While it may be unrelated, we had a site-wide memory issue 3 days ago. Can you verify if this is still happening to you?

**Comment by IvanDelsinne** [comment]
Tried again and it seems to be working fine now. I guess the problem was either this memory issue or a cache issue on my side.

**Comment by maestromac** [comment]
@IvanDelsinne Our guess is that memory issue caused everything else to timeout. Thanks for checking!
