### ISSUE TITLE
Load a specific page with Glitch embed

### ISSUE THREAD

**Issue by genemars** [thepracticaldev/dev.to#249]
# _TASK or Feature_
### Request or User Story

When writing a tutorial it could be useful to load a specific page from a glitch project. 
Currently the starting page is always `index.html`.

### Definition of Done

It will be done when `{% glitch imageticker /test.html %}` will open Glitch embed with the `test.html` page instead of returning `Project not found`.

**Comment by benhalpern** [comment]
Cool, I agree with this. In terms of the implementation, right we've only had "single argument tags", but second args separated by spaces seems good. This could be done without spaces, like `{% glitch imageticker/test.html %}` but separate args seems like a clean approach. @maestromac can you be in charge of thinking this through and/or implementing?

**Comment by maestromac** [comment]
Not stale

**Comment by maestromac** [comment]
still not stale

**Comment by bolariin** [comment]
I think this might have been resolved with #680

**Comment by maestromac** [comment]
Thanks @bolariin . Resolved with https://github.com/thepracticaldev/dev.to/pull/680
