### ISSUE TITLE
Edit buttons should be fixed

### ISSUE THREAD

**Issue by rugk** [thepracticaldev/dev.to#2490]
**Is your feature request related to a problem? Please describe.**
I am frustrated if I re-read my text and quickly want to change anything, I have to scroll uüp and click on "edit". Similarly, I likely want to read the text in the preview (too), and there I also have to scroll up all the way…

**Describe the solution you'd like**
Make the buttons fixed, so I can always click on them and _stay at the current position_ (page scroll)!

**Describe alternatives you've considered**
N/A

**Additional context**
Seems obvious.

**Comment by jessleenyc** [comment]
Thanks for the request. We actually have these buttons fixed in the v2 version of the editor -- you can toggle by going to dev.to/settings/misc and selecting v2. The biggest difference is that frontmatter is not supported in v2 yet, but we plan to add it soon.

**Comment by jessleenyc** [comment]
Buttons are fixed in both editors.
