### ISSUE TITLE
Move asynchronous methods to Active Jobs

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#2497]
Currently, most of the asynchronous methods use `DelayedJob` directly. 
It would be nice to use ActiveJob instead of `DelayedJob` for several reasons:

- it'll be easier to migrate to another queue backend, like sidekiq
- it's easier to specify a queue and set a priority of the specific kind of job
- often moving logic to a separate job requires refactoring and the resulting code has a better design
- easier to avoid deserialization errors (#1621)

There are [2 kinds of methods](https://github.com/collectiveidea/delayed_job#queuing-jobs) that are run by DelayedJob:
- `handle_asynchronously`
- `delay`

There's a ticket for Notifications ActiveJobs already: #1996

**Comment by lightalloy** [comment]
The list of the methods that are specified as async by `handle_asynchronously`

`labor/rate_limit_checker.rb`
- ping_admins

`models/article.rb`
- update_main_image_background_hex
- detect_human_language
- async_bust

`models/badge_achievement.rb`
- send_email_notification

`models/comment.rb`
- calculate_score
- create_id_code
- touch_user

`models/mention.rb`
- create_all
- send_email_notification

`models/organization.rb`
- bust_cache

`models/podcast.rb`
- pull_all_episodes

`models/user.rb`
- subscribe_to_mailchimp_newsletter
- bust_cache

`services/moderation_service.rb`
- send_moderation_notification

**Comment by maestromac** [comment]
For anyone who would like to contribute to this, a delayed job method should be split up to the following
- a job class under the proper module + spec 
- a service object under the proper module + spec
- change how the method is evoked at the source.

You can check Anna's work here for inspiration https://github.com/thepracticaldev/dev.to/pull/2373

**Comment by lightalloy** [comment]
An approximate list of actions to change async method to use Active Job:

- Inspect the method you're going to make asynchronous, look at the tests if it has them, understand what it does. 
- If the method contains more than a couple of lines of code, create a service object to contain the method's logic.
- Namespace the service object appropriately.
- Write the tests for the service object.
- Replace the method body with the service object call. It's a temporary action, but this way you can check if everything works fine.
Run the related tests at this point (I prefer to run the whole test suite).

If everything works fine:
- create a corresponding ActiveJob. Namespace it properly and specify the queue.
- write tests for the job. The job shouldn't accept ActiveRecord objects to avoid `DeserializationError`s (#1621)
Pass record/object `id` instead and use `find_by(id:)` inside the job to avoid exceptions raised.
The job tests shouldn't test much since the logic is tested in the service object specs.
- write the code of the job
You can look at the jobs and specs examples in the `app/jobs` and `spec/jobs`

Now you need to actually schedule the job in the calling code:
- in the initial method: replace the call to the service object with the job `perform_later`
- remove `handle_asynchronously` call with the initial method name

DelayedJob creates and uses a method like `%method_name%_without_delay` internally, so we need to keep these methods at least for a while (as the jobs that use this method can still exist at the moment of deploy):
- create a method `%initial_method_name%_without_delay` and call `YourJobName.perform_now` inside of it
- sometimes `%initial_method_name%_without_delay` are used in the codebase explicitly, so search through the codebase for them
If there are no such calls, please, add a comment that the method should be removed later.
[Example from the @rhymes pr](https://github.com/thepracticaldev/dev.to/blob/62ad148e0bfeb093eecaf1563cd6923e02f5032b/app/models/notification.rb#L73-L75)

You may also need to modify existing tests that call the async method if they use `run_background_jobs_immediately {}`. With Active Job, another method `perform_enqueued_jobs {}` should be used.

**Comment by lightalloy** [comment]
You can explore these prs for more information: #2373, #2299, and those attached to issue #1996

**Comment by tannakartikey** [comment]
@lightalloy I would like to help with this.

**Comment by lightalloy** [comment]
@tannakartikey , great! I've updated the list, you can take any of the unchecked ones. Please, make a comment about the items you will be working on.

**Comment by tannakartikey** [comment]
Thanks @lightalloy 
I am thinking to start from the beginning of the list so the first will be `ping_admins` and then further down the list.

**Comment by tannakartikey** [comment]
@lightalloy can I work next on `send_email_notification`?

**Comment by lightalloy** [comment]
@tannakartikey yep, it's free :+1:

**Comment by tannakartikey** [comment]
@lightalloy can I work next on `models/mention.rb`?

**Comment by lightalloy** [comment]
@tannakartikey sure :+1:

**Comment by cyrillefr** [comment]
Hello, @lightalloy , I'd like to work on bust_cache for models/organization.rb.

**Comment by lightalloy** [comment]
I'll move `Podcast#pull_all_episodes` to ActiveJob while working on improving podcasts fetching #2952

**Comment by lightalloy** [comment]
I have created another issue for this task in case anyone one wants to continue or start contributing:
https://github.com/thepracticaldev/dev.to/issues/3136

**Comment by lightalloy** [comment]
Done.

**Comment by rhymes** [comment]
Great job so far @lightalloy! I've noticed there are still a few ".delay" around the code, I'd say those too should be converted to jobs. We should aim at not calling DelayedJob directly

**Comment by lightalloy** [comment]
@rhymes, yep, `delay`s are in a separate issue #3136
