### ISSUE TITLE
Write abstraction layer over Algolia

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/dev.to#2499]
We currently use [Algolia](https://www.algolia.com/) for several features in order to provide low latency indexed data for searching and otherwise serving.

But we're highly coupled to Algolia in ways that are not ideal. It would be nice if we could work locally without the Algolia dependency. It would also be nice if we could move certain features on or off of Algolia for different purposes. I could see a time where Algolia handles certain things and a similar service handles others.

Being vendor agnostic in general would be great in terms of our open source future.

There are two components to this project: client side and server side.

On the server, we'd want to decouple Algolia from the Rails lifecycle and write custom wrappers for the behavior of indexing and de-indexing. Currently we use Algolia-Rails, but could move to Algolia-Ruby and wrap that functionality in our own interface.

On the client, we import the Algolia library, which again, we could wrap. Frankly, I think the lib includes a lot of functionality we don't necessarily need because the crux of what we need to do with Algolia is just hitting a single endpoint.

We make use of certain authorization logic in order to provide public and private indexes for Algolia data and all that would need to be worked out.

This is not urgent, but I could see this decoupling being very liberating for local development.

One additional related nicety which we could possibly tackle before or during this project is to optionally do batch writes to Algolia instead of a bunch of individual insertions in some cases. The case that comes to mind for me is when we run our seed file, we create a bunch of objects which are then each indexed to Algolia in a time-consuming way. If we did this in batching, it could smooth out this process for the developer. [Algolia batch API](https://www.algolia.com/doc/api-reference/api-methods/batch/?language=ruby)

I could see this being a big all at once task to pull off or something folks did in bits and pieces.

**Comment by omenking** [comment]
It would be nice if we could be utilizing ElasticSearch since its core is open source.
All three major cloud providers (AWS, Azure, GCP) have managed ElasticSearch services.

To simplify the codebase further I wonder if Postgres Full-Text search could be utilized. There would be a compromise in the rich search functionality but would make the codebase simple overall.

I know this not a discussion to change full-text search solution and it's about going agnostic but putting my two cents on these search alternatives.

**Comment by pandeybk** [comment]
Since this project is open source so utilizing any open source technology like ElasticSearch will be a huge plus.

**Comment by mstruve** [comment]
> Since this project is open source so utilizing any open source technology like ElasticSearch will be a huge plus.

The people ask, we deliver! No more Algolia, no problem! 😉
