### ISSUE TITLE
Add icon for iOS save to Homr Screen for dev.to

### ISSUE THREAD

**Issue by kkpoon** [thepracticaldev/dev.to#25]
Follow this  guide to add an icon for iOS device save to home screen 😄https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

**Comment by jessleenyc** [comment]
@kkpoon  This is done! You can save dev.to to your home screen now :)

**Comment by kkpoon** [comment]
Great. Thanks
