### ISSUE TITLE
Vivaldi: small images are fail to load because of service worker

### ISSUE THREAD

**Issue by powerman** [thepracticaldev/dev.to#250]
### Current Behavior
Small images are load in Chromium, but not in Vivaldi.

### Expected Behavior
Small images should load in Vivaldi.

### Additional Info (steps to replicate, device/browser, helpful links)
With open Inspector and switched on `Application → Service Workers → [✓] Bypass for network` these images loads fine.
Vivaldi version: 1.15.1147.52 / Linux

### Screenshots
![image](https://user-images.githubusercontent.com/1354301/43034311-e7ce3880-8ce2-11e8-9b13-2e5d1f90eb39.png)

**Comment by powerman** [comment]
It's not fixed. Current Vivaldi 2.0.1309.42 still has this issue. Chromium/Firefox are okay. But if you don't care then I don't care too, feel free to close it.

**Comment by jessleenyc** [comment]
Keeping this open and approving the issue for anyone who wants to tackle it. Thanks for reporting in the first place @powerman!

**Comment by maestromac** [comment]
not stale

**Comment by maestromac** [comment]
Are you still experiencing this issue @powerman ? I've tried browsing dev.to on Vivaldi 2.5 MacOS Mojave and it seems to be working normally.

**Comment by powerman** [comment]
Right now this issue has something with conflict between dev.to serviceworker and my uMatrix plugin.

Looks like uMatrix notice requests to most 3rd-party resources (including cloudinary) only when serviceworker is not registered when loading website. After that these requests probably done by serviceworker in some way which makes them invisible to uMatrix. Which in turn means I don't see requests to these resources in uMatrix UI and can't enable them ⇒ have missing images as result.

The workaround is:
1. Unregister serviceworker.
2. Reload website.
3. Enable cloudinary and some other 3rd-party resources just in case in uMatrix before reloading website once again.

In Firefox there is no such issue: uMatrix is able to notice requests to these 3rd-party resources all of time, not only when website loads for the first time without serviceworker installed.

**Comment by maestromac** [comment]
Thanks for that feedback @powerman . Sorry to let this sit around for awhile.

Since we don't officially support Vivaldi and this issue seems to be caused by an extension, this is out of our hand.
