### ISSUE TITLE
[Dashboard UI]: "Upload a Video" button & "Recently Created" Select Positioning Needs to be Fixed

### ISSUE THREAD

**Issue by mjraadi** [thepracticaldev/dev.to#2506]
**Describe the bug**
Positioning of "Upload a Video" button and "Recently Created" select doesn't look good on small screen devices.

**To Reproduce**

1. Make sure you are logged in
2. Go to your [Dashboard](https://dev.to/dashboard)
3. See the behavior

**Screenshots**
![Screenshot_20190421-191917](https://user-images.githubusercontent.com/20579660/56471708-9f186d80-646a-11e9-961b-2f7518b58924.jpg)

**Expected behavior**
Better inline and centered positioning for large screen devices and stack positioning for small screen devices. Here's what I propose:
![Screenshot_20190421_190612](https://user-images.githubusercontent.com/20579660/56471763-56ad7f80-646b-11e9-8ade-9470b1808dc8.png)
![Screenshot_20190421_190751](https://user-images.githubusercontent.com/20579660/56471764-56ad7f80-646b-11e9-98dc-608852eb42f6.png)

**Desktop (please complete the following information):**
- OS: Arch Linux Manjaro
- Browser Chrome

**Comment by mjraadi** [comment]
I will make a PR to fix this issue if you approve it. Thanks

**Comment by Link2Twenty** [comment]
Would you be moving it to flex box?

**Comment by mjraadi** [comment]
That's right. I tired fixing it with Flexbox in Chrome Dev Tools and you can see the result.

**Comment by maestromac** [comment]
Give it a go @mjraadi !
