### ISSUE TITLE
Save Changes text spills out of button in v2

### ISSUE THREAD

**Issue by bolariin** [thepracticaldev/dev.to#2521]
**Describe the bug**
When editing a post within the v2 editor, the text within the save changes button spills out of the button.

**To Reproduce**

1. Switch to v2 editor
2. Click Edit for an existing post or publish a post and then click edit
3. You will notice the save changes button below has the 'S' completely out of the button

**Expected behavior**
Expected the save changes text wrapped within the button.

**Screenshots**
![Save Changes text spills](https://user-images.githubusercontent.com/24629960/56554164-c9e3ee00-655e-11e9-9360-d8888d3b7825.png)

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: Chrome
- Version 73.0.3683.103

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by jessleenyc** [comment]
I'm not able to reproduce this on Mac/Chrome but will see if I can via Browserstack. Approving for anyone who might want to take a look.

**Comment by bolariin** [comment]
https://github.com/thepracticaldev/dev.to/blob/b0ad7f8c74b09ca55a80e64ff69d122ad6de0655/app/assets/stylesheets/preact/article-form.scss#L397-L399

It looks like I can get the text to fit within the button if I change the width. I wanted to know If it's fine to increase the width or remove the width so the button isn't too wide for text with fewer characters?

**Comment by maestromac** [comment]
@bolariin you can remove the width if necessary as long as it's consistent between browsers. Dynamic width is probably the best solution.
