### ISSUE TITLE
Some of the Notifications::NewReactionJobs fail with "Validation failed" on save!

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#2525]
Some of the `Notifications::NewReactionJobs` fail with `Validation failed: User has already been taken` on `save!` in the `Notifications::Reactions::Send#call`

Maybe it happens when a user creates several reactions on an article, several jobs are created, and those jobs run simultaneously.

**Comment by lightalloy** [comment]
I have made the research on the topic and still suppose that this error happens when 2 reaction notification jobs run simultaneously. 2 notifications with the same attributes are initialized, then. on `save!` one of them is not saved because the user validation fails.
However, it's not clear why this job doesn't succeed on retry. On retry, the `find_or_initialize` should be executed again, so it should find the existing notification, update it and the job should succeed. 
It's hard to do further research w/o access to the console, so I suggest one of the 2 options:
- pass this issue to someone who has this access
- just replace `save!` with `save`. It's not a big deal if the notification is not updated once - it'll be updated when the next reaction will be created or deleted

**Comment by maestromac** [comment]
I feel like I've heard of this race condition before. Definitely one of of DHH's video and maybe the reason why `create_or_find_by` will be added to Rails 6.

I agree with switching to `save`. Shouldn't be too big of a deal.

**Comment by lightalloy** [comment]
The solutions could be:
- `create_or_find_by` instead of `find_or_initialize_by` + second `save` (after assigning other attributes) inside a transaction (on Rails 6)
or
- use Postgres "upsert" (`INSERT ... ON CONFLICT UPDATE`). There's also a gem for that: https://github.com/jesjos/active_record_upsert
If we use the second option, we have to l avoid unique validation on `user` and rely on database constraint. 
While this is doable, I think it's an overkill for this specific issue, but can be used in the future if we have similar problems.

**Comment by rhymes** [comment]
Upsert support is also coming in Rails 6 fortunately. That could be a valid way. I don't know well the status on foreign keys between table but IIRC there are some relations that are only enforced on the Rails level and not by the DB, which could complicate things down the line.

Another possibility could be to use pessimistick locking: the first job acquires the lock on the notification row if found and does the update. It's builtin in Rails: https://api.rubyonrails.org/classes/ActiveRecord/Locking/Pessimistic.html (see also https://www.peterdebelak.com/blog/pessimistic-locking-in-rails-by-example/)

**Comment by lightalloy** [comment]
@rhymes thanks for the links! It's an interesting read. I knew about the locks, but havent considered them in this situation.

In this case, the error appears on create (not update) so to be able to lock it we have to create it first.
E.g. we replace `find_or_initialize` + `save!` (the current implementation) with `find_or_create_by` +`lock!` + `save!` inside a transaction.
`lock!` will be executed after the `find_or_create_by`, so `find_or_create_by` will be executed before it.
On first transaction the record will be create, and on second one it will fail because of the failed validation on `find_or_create_by` and the transaction will be rolled back. The outcome will be the same as if we just change `save!` to `save`. As for the table lock, I think it's too expensive, so I don't consider this.
Maybe, I'm missing something?

**Comment by rhymes** [comment]
I think you're right, thanks for the detailed explanation. Record locking won't work because of the `create`, and table look on the notification table is definitely a no :D I vote for UPSERT. Let's use the DB for what was made for 🥳

**Comment by lightalloy** [comment]
Still happening when calling `save!` on some of the persisted notifications.

**Comment by lightalloy** [comment]
I found out that duplicate notifications can be created in spite of the unique index. Probably, it's something wrong with it, I'll continue to investigate.

**Comment by lightalloy** [comment]
Fixed by #3012
