### ISSUE TITLE
Glitch embed: full screen button not working

### ISSUE THREAD

**Issue by genemars** [thepracticaldev/dev.to#253]
# _BUG_ (minor)

### Current Behavior
Click or tap over the Glitch embed full-screen button does nothing.

### Expected Behavior
Open the full-screen Glitch.

**Comment by jessleenyc** [comment]
Thanks for the flag @genemars. Approving this for anyone who wants to work on it!

**Comment by maestromac** [comment]
Just want to point out that this is resolved in Chrome.

**Comment by Zhao-Andy** [comment]
This is still a valid issue/bug.
