### ISSUE TITLE
sponsor image in night theme

### ISSUE THREAD

**Issue by mariocsee** [thepracticaldev/dev.to#2535]
**Describe the bug**
Some sponsor images have a white background, which clashes with night theme and possible future themes. Viewers who use night theme to browse in darker environments may be bothered by the white background.

Though you can hide sponsors in `settings/misc`, I imagine that sponsor messaging fitting well with the styling would allow for a smooth experience while supporting the organizations that help DEV. 

**To Reproduce**

1. Set your settings/misc to night theme
2. Go to the home page
3. Look at sponsors portion

**Expected behavior**
If the sponsors have them, ask for additional images (clear background or light text/dark background) that fits with night theme page (and other themes on the darker side). Swap sponsor images based on theme.

**Screenshots**

**Desktop (please complete the following information):**
### Sponsor image with white backgrounds stand out. 
<img width="1264" alt="Screen Shot 2019-04-23 at 13 32 34" src="https://user-images.githubusercontent.com/13403332/56603628-14e91a00-65ce-11e9-9a9f-309b336ea8d2.png">

- OS: MacOS
- Browser Chrome
- Version 73

**Comment by Glennmen** [comment]
Go by ThoughtWorks has transparent black and white svg: https://brandfolder.com/twproducts

Can't find a brand page on scout website.

**Comment by jessleenyc** [comment]
@pkfrank headsup we should ask for versions w/ a transparent background for future sponsors.

**Comment by jessleenyc** [comment]
Let's add some logic that accepts two images for the sponsor (light/dark) and shows the right version depending on what theme the user uses.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/2640
