### ISSUE TITLE
500 Internal Server Error when accessing article via API

### ISSUE THREAD

**Issue by gajus** [thepracticaldev/dev.to#2536]
e.g.

```bash
$ curl https://dev.to/api/articles/101813
{"status":500,"error":"Internal Server Error"}

```

It is not clear whether this indicates that the content will be accessible later or if there is a genuine server error.

**Comment by maestromac** [comment]
I believe the vagueness is by-design but we could make the adjustment for this case.

**Comment by rhymes** [comment]
Closing this because it's working: `curl https://dev.to/api/articles/101813`
