### ISSUE TITLE
Article sidebar in Safari inconsistent with other browsers

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/dev.to#2537]
In Safari desktop (13 inches or greater, not sure what the pixel limit is) the article sidebar looks a bit off:

### Safari
![Sidebar in Safari](https://user-images.githubusercontent.com/17884966/56606401-1f0e1700-65d4-11e9-8cc6-27425f5e25ed.png)

### Chrome / Firefox
 
![Sidebar in Chrome or Firefox](https://user-images.githubusercontent.com/17884966/56606420-2c2b0600-65d4-11e9-9ad3-a906c6df2710.png)

The most notable issues are that the buttons are less wide and the menu pops out further than Chrome / Firefox.

**Comment by zxlee618** [comment]
I would like to work on this

**Comment by maestromac** [comment]
go ahead @zxlee618 !

**Comment by zxlee618** [comment]
Just wondering, how it is supposed to look like?

**Comment by rhymes** [comment]
@zxlee618 I think the reference is the Chrome/Firefox image. 

Nothing:

![Screenshot_2019-04-27 The DEV Community](https://user-images.githubusercontent.com/146201/56848357-50465a00-68e8-11e9-8214-754b5d7231da.png)

Something:

![Screenshot_2019-04-27 The DEV Community(1)](https://user-images.githubusercontent.com/146201/56848358-55a3a480-68e8-11e9-803c-db033c4e3ceb.png)

**Comment by zxlee618** [comment]
But it looks similar to Chrome on my Safari (15inch mac). The buttons would become smaller when the window is smaller and this behaviour is similar to chrome and firefox, so I'm a bit confused now

**Comment by thamaraiselvam** [comment]
@zxlee618  yes it shrinks on window resizing.

**Comment by k88manish** [comment]
It looks same on chrome and safari (mac, 15inch)

![Screenshot 2019-05-15 at 3 05 26 PM](https://user-images.githubusercontent.com/19614770/57765406-fe446780-7722-11e9-8415-6ef030b9ae4e.png)

**Comment by fedeagripa** [comment]
@Zhao-Andy may this be solved by this: https://github.com/thepracticaldev/dev.to/commit/b0ad7f8c74b09ca55a80e64ff69d122ad6de0655#diff-0037c2206a5866179ceaf9a0ffc72eec ?

**Comment by maestromac** [comment]
Yup this looks resolved. Thanks all!
