### ISSUE TITLE
Recent comment activity styling is a bit off

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#2546]
**Describe the bug**

I think the "recent comment activity" styling is a little off

**To Reproduce**

1. Save an article with comments
2. Go to 'https://dev.to/readinglist?v=comments'
4. See the problem

**Expected behavior**

I think some spacing between the post title, the "VIEW COMMENT TREE" section and the actual comment is needed. 

**Screenshots**

![Screenshot_2019-04-24 The DEV Community](https://user-images.githubusercontent.com/146201/56692772-3ab41300-66e3-11e9-9d9a-f734c3d0ac8b.png)

(Ignore the search bar in the middle, it's just an issue with the screenshotting tool)

**Desktop (please complete the following information):**

- OS: macOS 10.14.4
- Browser Firefox
- Version 67.0b12

**Comment by maestromac** [comment]
Thanks for reporting this @rhymes . My first hunch it could be because of this PR https://github.com/thepracticaldev/dev.to/pull/2166

**Comment by mariocsee** [comment]
hey @rhymes, I can't replicate this on web or mobile anymore, but I may have caught it when my PR #2493 addressing another reading list comments issue was merged. Are you still experiencing this?

**Comment by rhymes** [comment]
@mariocsee no, it's fine now! Closing this issue, thanks!
