### ISSUE TITLE
/video timestamps don't appear after scrolling

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#2549]
**Describe the bug**
Looks like timestamps aren't loading for videos that appear after the initial page load. 

**To Reproduce**

1. Go to '/videos
2. Scroll past initial page load

**Expected behavior**
Timestamps should appear on all video thumbnails.

**Screenshots**
![](https://cl.ly/730ce6898b73/download/Image%202019-04-24%20at%205.24.59%20PM.png)

**Comment by Zhao-Andy** [comment]
Resolved by #2551 I believe.
