### ISSUE TITLE
Browser scrolls to the bottom of the page

### ISSUE THREAD

**Issue by kay-is** [thepracticaldev/dev.to#255]
# _BUG_
### Current Behavior

When I try to write a new article, the browser always scrolls the page all the way down, but only when I type something after the `description: ` line.

### Expected Behavior

I can write normally without any broken auto-scrolling to the bottom.

### Additional Info (steps to replicate, device/browser, helpful links)

I'm using _Version 68.0.3440.75 (Offizieller Build) (64-Bit)_ on macOS.

**Comment by Zhao-Andy** [comment]
@kay-is Fixed :)
