### ISSUE TITLE
Make Series Articles Useful

### ISSUE THREAD

**Issue by omenking** [thepracticaldev/dev.to#2558]
**Is your feature request related to a problem? Please describe.**

This is how series work, they are a series of dots. 
<img width="727" alt="Screen Shot 2019-04-25 at 3 42 39 PM" src="https://user-images.githubusercontent.com/7776/56763585-cb850000-6770-11e9-8a56-c09b8aaaaa11.png">

**Describe the solution you'd like**
see on the left-hand side where I highlight in red. This would be more ideal because than I can publish a full course exclusively on DEV.to
<img width="1389" alt="Screen Shot 2019-04-25 at 3 40 41 PM" src="https://user-images.githubusercontent.com/7776/56763633-e192c080-6770-11e9-993d-2682e4ba9adc.png">

**Describe alternatives you've considered**

**Additional context**

**Comment by mjraadi** [comment]
I looked at the code and I think we could use sidebar functionality for this feature. Currently, there are left and right sidebars on the home page. It's visible on large screen devices and disappears on small screen devices and user can swipe in to see the sidebar. We could use the left sidebar for post series list on the post view page and the right sidebar for author info and related articles. Related articles are completely hidden on small screen devices.
What do you think?

**Comment by omenking** [comment]
I think recently the article area increased so I don't know if they'd want a new bar to appear reducing the space.

Here is a suggestion for placement.

![put-here](https://user-images.githubusercontent.com/7776/57195563-36c59380-6f22-11e9-9a56-629a2d89e30c.jpg)

**Comment by Link2Twenty** [comment]
I have wondered about having a, possibly autogenerated, series cover page.

**Comment by mjraadi** [comment]
@omenking that's a good idea but that area is only visible on large screen devices. I think we should come up with an approach which is suitable on both desktop and mobile devices and has a solid UX.

**Comment by jessleenyc** [comment]
Similar but different issue: https://github.com/thepracticaldev/dev.to/issues/2424

**Comment by jessleenyc** [comment]
Hey all - we just redesigned series a bit, there are no longer dots! Here's an example of it in action: https://dev.to/devteam/daily-challenge-43-boardgame-fight-resolver-53e3

@omenking not your exact proposal but similar. I'm going to close this issue for now but ping me here if you want me to keep it open.

**Comment by omenking** [comment]
I had just spotted it today on Helen's post.
A liquid tag is a much better implementation since its decouple from the main layout 👍
So I would agree this ticket is now defunct.
