### ISSUE TITLE
Can't access settings in Dev app

### ISSUE THREAD

**Issue by larssonted86** [thepracticaldev/dev.to#2560]
**Describe the bug**
Tried to access settings in the app.

**To Reproduce**

1. Go to 'app'
2. Click on 'settings'

**Expected behavior**
Get to settings in the app

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: [Google pixel (1 gen)]
- OS: [Android Q, beta]
- Browser ]
- Version []

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by jessleenyc** [comment]
@larssonted86 I can't seem to recreate this issue. Would you mind sending an email to yo@dev.to with your email address? I think it could be specific to your account. Thanks!
