### ISSUE TITLE
500 Error After Credit Purchase

### ISSUE THREAD

**Issue by toeknee123** [thepracticaldev/dev.to#2564]
**Describe the bug**
Tried buying Credits but after entering in credit card information, throws 500 error. 

**To Reproduce**

1) Enter in CC information to buy credit
2) Click purchase
3) 500 error

**Expected behavior**
Credit purchased

**Screenshots**
<img width="769" alt="Screenshot 2019-04-25 21 12 53" src="https://user-images.githubusercontent.com/2038322/56779130-26355080-679f-11e9-9df0-70cfc499f7a9.png">

**Desktop (please complete the following information):**

Chrome

**Comment by maestromac** [comment]
Thank you for reporting this issue. I believe this has already been addressed. Please let us know if otherwise!
