### ISSUE TITLE
Send message to a group of people

### ISSUE THREAD

**Issue by aershov24** [thepracticaldev/dev.to#257]
# _TASK or Feature_
### Request or User Story
In connect section there are three tabs:
* all 
* direct
* group

It's not clear how to create a group (is it even possible?) and add people into it.

### Definition of Done
New group could be created, people (mutually followed) could be added into the group, message could be send to anyone in the group.

**Comment by jessleenyc** [comment]
Yeah, this is something we still need to incorporate. @benhalpern what's the latest with this?
