### ISSUE TITLE
Misspelled "Portuguese" Under Language Selection in /settings/misc

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#2582]
@michael-tharrington commented on [Thu Apr 25 2019](https://github.com/thepracticaldev/team/issues/123)

A user pointed out that we made a typo on the word Portuguese here:

![](https://cl.ly/a9e99ffff59b/download/Image%202019-04-25%20at%2010.50.16%20AM.png) 

under https://dev.to/settings/misc.

**Comment by lightalloy** [comment]
I fixed that in #2496

**Comment by lightalloy** [comment]
Fixed by #2496
