### ISSUE TITLE
Add Ruby source code documentation to docs.dev.to

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#2587]
**Is your feature request related to a problem? Please describe.**

In the effort of lowering the bar for contribution, but also to help current contributors navigate the code, I believe it would be nice to have a place online where to consult the Ruby API (as in the interface of the Ruby code base), something like various gems docs.

This should also encourage a process of standardized documentation that we're not adding to methods, mostly relying on method and parameters names. Since, according to `rails stats`, the codebase (including tests) is around 25000 lines of Ruby code, I believe an overview of the classes and their methods could help either way.

**Describe the solution you'd like**

The solution I would like is to be able to go to https://docs.dev.to/ruby-doc or something like that and be able to see the YARD documentation of the code. 

I've uploaded [an example build](https://priceless-lewin-766be7.netlify.com), built with the params of this [commit](https://github.com/rhymes/dev.to/commit/9f6b97872ec6213889b6a32e715d63fd463d2521), to https://priceless-lewin-766be7.netlify.com so that you can have an idea of what the final result would be like.

If this is approved what is missing to the [branch](https://github.com/rhymes/dev.to/commit/9f6b97872ec6213889b6a32e715d63fd463d2521) is figuring out how to have Travis build and upload to DEV's Netlify the documentation at the end of the CI build.

It takes around 45-48 seconds to build the full website including `protected` and `private` methods, it takes around 37 seconds to build the full website including only `public` methods.

**Describe alternatives you've considered**

The alternative is to just add the YARD configuration you can see in https://github.com/rhymes/dev.to/commit/9f6b97872ec6213889b6a32e715d63fd463d2521 and let the programmer generate it locally if they need to.

**Additional context**

* [Documentation example that can be navigated](https://priceless-lewin-766be7.netlify.com/)

![Screenshot_2019-04-27 File README — Documentation by YARD 0 9 19](https://user-images.githubusercontent.com/146201/56850487-d02ded80-6903-11e9-8f5b-ff3bb0989b6a.png)

![Screenshot_2019-04-27 Class Article — Documentation by YARD 0 9 19](https://user-images.githubusercontent.com/146201/56850489-da4fec00-6903-11e9-88dc-99b7b8feeaf2.png)

![Screenshot_2019-04-27 Class GithubReposController — Documentation by YARD 0 9 19](https://user-images.githubusercontent.com/146201/56850488-d328de00-6903-11e9-8d7a-f7096073eef3.png)

**Comment by omenking** [comment]
Since our current documentation on dev.docs is incomplete this just looks like more docs to burden developers with busy work because then they'll be obligated to fully document their methods.

If we want to **lower the bar** we need to make the codebase more vanilla since there is so many abstractions and configurations that are not necessary.

Instead of adding more documentation lets make the app self-documenting by sticking rails conventions. Then they can rely on existing Rails documentation.

**Comment by rhymes** [comment]
I don't think this adds burden to the developer, since it's auto generated. 

I'm not advocating to document all methods either, just to have a place where a person can quickly navigate the source code by module/class. Since a Ruby module can span multiple files, I think it'd be nice to have an API doc.

Method documentation is not currently enforced, it will remain an opt-in AFAIK.

**Comment by jessleenyc** [comment]
Hey @rhymes -- we're all for this. Since it's auto-generated, we don't think it'll add any burden either. And like you suggested, we'll keep it opt-in and no one will be 'required' to document (but hopefully we will!).
