### ISSUE TITLE
Can't disconnect twitter

### ISSUE THREAD

**Issue by Deanveloper** [thepracticaldev/dev.to#26]
I accidentally was signed into my old twitter account when I connected my twitter without realizing it. Now, I can't disconnect it. (Username deanveloper)

**Comment by Zhao-Andy** [comment]
Hey there, sorry for the late response. Right now we don't have a way of doing this through our app, but you can disconnect it via Twitter if you go to "Settings and privacy" -> Apps -> Revoke Access for our app. I've also deleted your Twitter username on your account so it won't appear on your dev.to profile. Let me know if that works :)

**Comment by Deanveloper** [comment]
Yup! I noticed it was fixed when I made my post about Go Interfaces. Thank you very much!!

- Dean Bassett
