### ISSUE TITLE
[podcast-widget] markup/render error?

### ISSUE THREAD

**Issue by genemars** [thepracticaldev/dev.to#261]
![schermata da 2018-08-02 14-10-06](https://user-images.githubusercontent.com/6654265/43582879-1ace2aa4-965e-11e8-8b5b-17ef79ead3ce.png)

**Comment by Zhao-Andy** [comment]
Hey @genemars, sorry not sure what I'm looking for here; could you explain a bit what happened exactly?

**Comment by genemars** [comment]
Nothing happened. Everything is cool and working but doing a "View page source" I noticed that the markup is a bit screwed. Do not use the DOM inspector as the inspector will automatically fix inconsistent tags. Or perhaps am I missing something? =)

**Comment by Zhao-Andy** [comment]
Fixed by @benhalpern via https://github.com/thepracticaldev/dev.to/commit/524d8a8aea57ec1f2cca3da537a7c3d4592f9ed7#diff-85f5aec8268e9700c652b1eac88c418dR210
