### ISSUE TITLE
Unable to embed speakerdeck slides

### ISSUE THREAD

**Issue by wahibhaq** [thepracticaldev/dev.to#262]
# _TASK or Feature_
### Request or User Story

Request for the possibility to embed speakerdeck slides inside the post.

### Notes

# _BUG_
### Current Behavior
Nothing shows up if I add the embed code snippet like this one. 

```
<script async class="speakerdeck-embed" data-id="f819ae07935a475c82c3f71d578e9e12" data-ratio="1.77777777777778" src="//speakerdeck.com/assets/embed.js"></script>
```

### Expected Behavior
Slides show up

### Additional Info (steps to replicate, device/browser, helpful links)
Chrome

**Comment by benhalpern** [comment]
We user our own embed syntax. 

`{% speakerdeck f819ae07935a475c82c3f71d578e9e12 %}`

This should work.

We're working to make this clearer within the UI.
