### ISSUE TITLE
Quota Exceeded error in serviceworker.js

### ISSUE THREAD

**Issue by ItsASine** [thepracticaldev/dev.to#263]
# _BUG_
### Current Behavior

```
serviceworker.js:1 Uncaught (in promise) DOMException: Quota exceeded.
```

This console error occurs approx 1-24 times on each page navigation until eventually the site comes to a crawl and I have to empty cache and hard reload.

### Expected Behavior

Navigating amongst the application without performance issues :)

### Additional Info (steps to replicate, device/browser, helpful links)

I do not know anything about service worker technology to know what could be causing this.

This occurs to me in both Chrome for macOS and Chrome for Chromebook. 

I navigate the site multiple times throughout the day and refresh often, but otherwise, nothing of note occurs beyond the site slowing up. As stated previously, an empty cache and hard reload temporarily fixes it.

### Screenshots

![screenshot 2018-08-05 at 9 28 09 pm](https://user-images.githubusercontent.com/11020425/43692586-b0c3cb0a-98f6-11e8-8d55-4ad8e319daf3.png)

After scrolling the lazy loading homepage:
![screenshot 2018-08-05 at 9 31 44 pm](https://user-images.githubusercontent.com/11020425/43692624-11b16c2e-98f7-11e8-982c-659237a4a72a.png)

**Comment by ItsASine** [comment]
Never knew that existed. That's fun!

Looks like I have a v2.6.0 and a v2.6.1 of sw-cache
![screenshot 2018-08-06 at 1 19 33 pm](https://user-images.githubusercontent.com/11020425/43731112-7a8a0e7a-997b-11e8-9ad0-39e43280b046.png)

* Deleting all three and reloading gave me v2.6.0 only of sw-cache and v2.6.1 of sw-cache::pages
* I also updated the service worker since that was a button in Application tab -> Application -> Service Worker. 

None of this fixed the Quota Exceeded errors, for what it's worth. I was just clicking buttons.

**Comment by ItsASine** [comment]
Further playing around with that tab you showed seems to have fixed it, actually. At least on this Chromebook.

Under "Status", it had 2. 1 was running and 1 was ready and waiting, but I could overwrite that and select "skip waiting". I clicked that, which resulted in the two messages in the logs in the low part of the attached screenshot. This got me to 2.6.1 for both sw-cache and sw-cache::pages.

![screenshot 2018-08-06 at 1 38 51 pm](https://user-images.githubusercontent.com/11020425/43732072-8a97d8da-997e-11e8-9682-52ad461c69d9.png)

After opening multiple tabs and refreshing/scrolling the homepage a while, this seems to have fixed it :+1: That doesn't solve why it needed manually updated, but I suppose that's a turn it off and turn it back on again scenario.

**Comment by callmemagnus** [comment]
You'll need to close the tab and open it again to have "activate" event in the serviceworker because the previous one is still in use by the currently opened tab.

See https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers
