### ISSUE TITLE
Received the "you are offline" page randomly

### ISSUE THREAD

**Issue by drazisil** [thepracticaldev/dev.to#2638]
**Describe the bug**
Received the "you are offline" page randomly today. Seemed a little odd, since I could access all other sites. Sent a tweet https://twitter.com/drazisil/status/1123613291174084609 and was directed to try deleting service worker cache and posting here.

Visited `about:debugging#workers` and attempted to unregister the "running" worker, was unable to. Closed the page and it disappeared. Have not got it since, but it was random

**To Reproduce**

1. Go to Any dev.to page
2. Get unlucky
3. See the "you are offline" page

**Expected behavior**
Not be told I'm offline when I'm not?

**Screenshots**
I didn't take any before it went away, sorry.

**Desktop (please complete the following information):**

- OS: [e.g. iOS]: Debian 9
- Browser [e.g. chrome, safari] Firefox
- Version [e.g. 22] 66.0.3 (64-bit)

**Additional context**
This is an awful bug report, I'm sorry. I'm only creating it because @benhalpern suggested it.

**Comment by kenbellows** [comment]
If you want some more unhelpful input, I'm not sure how to reproduce it either, but I've seen it happen a few times myself, especially in the new Android app. It seems to occur most often when I do too much navigating backwards through the history, that sort of thing, so I have a (largely unfounded) suspicion that it's related to routing

**Comment by Zhao-Andy** [comment]
The offline page is served by service workers. I think our implementation of service workers doesn't seem to work well with Firefox's service workers.

The Android app uses web views so if you're using Firefox as your default Android browser, it'll have a similar experience as if you were browsing on the Firefox app.

Related issue: #1810 and #128

**Comment by kenbellows** [comment]
For more context, I have Chrome for Android set as my default browser, and I actually don't think I have Firefox installed currently.

**Comment by Zhao-Andy** [comment]
@kenbellows Ah okay, good to know, thanks!

**Comment by lukas-derksen** [comment]
I have experienced this issue as well. At first it seemed random to me, but I've started seeing a pattern. It appears to happen every time I open a dev.to article from google.com. 

**To reproduce**
1. Go to google.com
2. Search for dev.to articles (search query I used: site:"dev.to")
3. Click a random result

**Expected behaviour**
Seeing the article you clicked on

**Desktop**
- OS: Windows 10
- Browser: Firefox
- Version: 67.0 (64 bits)

**Additional context**
I have also tried this approach on chrome, but it did not trigger the bug. My Linux machine (Manjaro Linux) with firefox also does not trigger the bug.

**Comment by jessleenyc** [comment]
cc @maestromac 

Latest update on this issue are actually here: #1810

**Comment by maestromac** [comment]
If you happen to experience this issue on desktop, please kindly share your browser's log here. Privacy Badger and uMatrix are known to be the cause of this issue.

On android, it's not very clear to us right now what's causing it but we are actively trying to resolve it.

**Comment by jessleenyc** [comment]
Happening to someone else on Android/DuckDuckGo.

**Comment by s1037989** [comment]
Thanks for posting for me @jessleenyc !
It is happening with 100% consistency for me on Android/DDG (my default browser).  I cleared all tabs and cache and it persists.  I restarted my Android and it persists.
I copy the link from the DDG URL bar and paste it into Chrome and it's successful.
I switch my default browser to Chrome and it's successful.
@jessleenyc What kind of an error am I getting with the draw a picture error?  4xx?  5xx?  If it's a 5xx, can you look up from the logs what error the server is reporting when DDG tries to view the page?

**Comment by lukas-derksen** [comment]
> If you happen to experience this issue on desktop, please kindly share your browser's log here. Privacy Badger and uMatrix are known to be the cause of this issue.

This was indeed my problem, Privacy Badger blocked the website. Makes me wonder why it only occasionally does so, though.

**Comment by maestromac** [comment]
Hello @drazisil , @s1037989 can you verify if are you still experiencing this issue?

**Comment by s1037989** [comment]
I viewed the first dev.to post in my twitter feed using my default DDG browser and it was a success!!  Looks like you got the bug!!

**Comment by maestromac** [comment]
I didn't 😛 , [Chromium team did](https://github.com/thepracticaldev/DEV-Android/issues/36#issuecomment-506372524).

**Comment by maestromac** [comment]
If anybody still experience this issue, please let us know!
