### ISSUE TITLE
Add support for a call to action form for newsletters

### ISSUE THREAD

**Issue by autoferrit** [thepracticaldev/dev.to#264]
# Add support for call to action forms
The idea here, would be that at the bottom of a post, there could be a form with a message defined by the author, to join their newsletter by entering in their email into a form. To handle this, they would need to provide tokens to their own account at a provider such as mail chimp that can handle the submission forms. So dev.to wouldn't have to do anything on the back end as that request can be done entirely through js on the client site. Mail chimp has sample forms to accomplish this.

### Definition of Done
I have CTA's on the bottom of my posts in which I would like a CTA to be. Possibly a checkbox to enable it. and when submitted, that form submits to my configured endpoint over on mail chimps website.

**Comment by jessleenyc** [comment]
We don't have any integration like this in the works right now, but we have been thinking about adding a dedicate call to action area for posts. @benhalpern's given this a lot more thought.
