### ISSUE TITLE
clicking manage button in unpublished post returns 404

### ISSUE THREAD

**Issue by mariocsee** [thepracticaldev/dev.to#2642]
**Describe the bug**
The manage button in an unpublished post leads to a 404.

**To Reproduce**

1. Go to 'dev.to'
2. Create an a post and save the draft
3. View the unpublished post and click manage

**Expected behavior**
The manage button should not be displayed in an unpublished post. Though I would imagine users might want to set the "level" of the post before publishing? 

**Screenshots**
![Uploading Screen Shot 2019-05-01 at 17.20.04.png…]()

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version 73

**Comment by KDRaypole** [comment]
Quick and easy fix 😁Gotta love Pundit!

**Comment by benhalpern** [comment]
> Though I would imagine users might want to set the "level" of the post before publishing?

We can talk about this, but I feel like this is info that can be dealt with post-publish. But I could be swayed here. For now I think it's fine.

**Comment by maestromac** [comment]
Should be resolved with https://github.com/thepracticaldev/dev.to/pull/2643
