### ISSUE TITLE
Preview not working for Gist Tag

### ISSUE THREAD

**Issue by bolariin** [thepracticaldev/dev.to#2648]
**Describe the bug**
Trying to preview the gist tag doesn't seem to work on the v2 editor.

**To Reproduce**

1. Click on `WRITE A POST` or `EDIT` for an existing post
2. Type or paste in an example of the gist tag
3. Click on Preview
4. A preview of the expected gist embed does not appear

**Expected behavior**
I expected to see a preview of the gist embed

**Desktop (please complete the following information):**
- OS: Ubuntu
- Browser Chrome
- Version 74.0.3729.108

**Comment by rhymes** [comment]
I've explored this a bit but I've got stuck at some point.

The main issue is that a gist embed like

```liquid
{% gist https://gist.github.com/CristinaSolana/1885435 %}
```

results in the following script tag:

```html
<script id="gist-ltag" src="https://gist.github.com/CristinaSolana/1885435.js"></script>
```

but [dangerouslySetInnerHTML](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml) won't execute script tags.

The alternative I tried was to use a React HTML parser, I tried [html-react-parser](https://github.com/remarkablemark/html-react-parser) which has a an example that has [an example](https://jsfiddle.net/remarkablemark/3h8ejw9n/) of how to execute script tags during transformation but it doesn't seem to work with Preact.

I then tried to find a Preact version and I stumbled on https://github.com/developit/preact-markup which led to the following code:

```jsx
    <div
      className="body"
      style={{ width: '90%' }}
    >
      {<Markup markup={previewResponse.processed_html} type="html" allow-scripts />}
    </div>
```

which seems to parse correctly the script tag. Unfortunately for obvious security reasons browsers don't allow `document.write` statements in scripts loaded asynchronously:

> Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.

 This is what I've found so far. Apparently there's no alternative way to embed gists either.

**Comment by maestromac** [comment]
Sorry I missed this.
In editor v1, `GistTag::special_script` uses [postscribe](https://github.com/krux/postscribe)  to resolve this issue. Other area this is used at is series; because the page does not fully reload whenever user navigate between series the page, postscribe resolves the script loading issue. It does however causes a weird issue where certain gist get loaded in multiple time.

ref: https://github.com/thepracticaldev/dev.to/issues/1679
