### ISSUE TITLE
Not able to post on dev.to

### ISSUE THREAD

**Issue by kalsiralph** [thepracticaldev/dev.to#2651]
I am not able to post on dev.to. Here is my profile link: https://dev.to/ralphkalsi

Here is the screen I am getting when tried to post content:

![image](https://user-images.githubusercontent.com/50197378/57064825-2aa0c280-6ce5-11e9-884a-072e9b7190d2.png)

Please help me as I really want to upload some content here.

Regards

**Comment by maestromac** [comment]
Hello @kalsiralph , this looks an issue specific to your account. Please email yo@dev.to for more help.
