### ISSUE TITLE
Match timeframe links with tag colors

### ISSUE THREAD

**Issue by KDRaypole** [thepracticaldev/dev.to#2666]
**Is your feature request related to a problem? Please describe.**
This is more of a problem of consistency. The timeframe links on a tag's page have a style that matches the tag theme when the class `.selected` is applied. But when hovering over the other timeframe links the default hover is shown.

**Describe the solution you'd like**
The timeframe links hover should reflect the tag theme if there is one.

**Describe alternatives you've considered**
This could be intentional. I'm not sure if this is part of the design. In that case, do nothing.

**Additional context**
What it looks like now.
![hover_selected](https://user-images.githubusercontent.com/25459752/57116007-57260000-6d20-11e9-9c33-21871097cbe8.gif)

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/2757
