### ISSUE TITLE
Reaction Buttons Works Inconsistent

### ISSUE THREAD

**Issue by aligoren** [thepracticaldev/dev.to#2668]
**Describe the bug**

Hi, I was found an interesting bug. While I was reading an article, I clicked heart button by mistake. It removed the article from likes list. I tried to click it again to like again, it didn't work for the first time.

**To Reproduce**

1. Go to any article
2. Click on "heart" button'
3. Click on the "heart" button again
4. See bug.

**Expected behavior**
It should work for each click. But because of this bug, you need to click twice when you click the second time.

**Screenshots**
![screencast-dev to-2019 05 03-10-00-06](https://user-images.githubusercontent.com/4205423/57123419-6c377900-6d8a-11e9-8c67-5a5f38ef70e8.gif)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 74.0.3729.108

**Additional context**

I didn't try on any mobile browser and I didn't try on FireFox.

Thanks.

**Comment by jessleenyc** [comment]
Thanks for the issue. @aligoren we intentionally add a little delay so people can't mash on the button. Is this bug still present if you wait a moment between liking and unliking?

**Comment by aligoren** [comment]
@jessleenyc I tried now, I think I misunderstood. There is a delay. I closed this issue, I didn't know delay. Thanks :)
