### ISSUE TITLE
Frequent 500 errors today

### ISSUE THREAD

**Issue by genemars** [thepracticaldev/dev.to#267]
# _BUG_
### Current Behavior
Really hard time writing a post.
"500 Error: It's not you, it's me."
It's happening very often today, I lost twice part of the content I was writing.
Not even pressing the "back" button will save the lost work. So upsetting =/
I also noticed that at least with FireFox there is a serious caching issue. 
For instance opening a post from the dashboard it often happen to render an old cached version which does not reflect the actual post text.

### Expected Behavior
Find a way to keep work of DEV.To users **safe** even in presence of internal errors.
Pressing the back button should route to the very last version of the post, the one before pressing the "SAVE" button.

**Comment by jessleenyc** [comment]
@genemars thanks for the report and suggestion. 
Were you eventually able to publish? If not, we can likely recover your work. Let us know!

**Comment by genemars** [comment]
@jessleenyc from last accident I only lost few changes that I've been able to recover from my mind =)
That's ok. I've learned the lesson and I'm using *gedit* as a safe place to backup article while writing/previewing.
I'll publish it later when done with it. Thanks!

**Comment by michaelgv** [comment]
Just a thought, maybe worth implementing client-side storage in the event 500’s are thrown while autosaving attempts? @jessleenyc

**Comment by Zhao-Andy** [comment]
Hey @michaelgv, it's an idea worth considering; there are some design choices we would have to think through first. I created a new issue for us to discuss: https://github.com/thepracticaldev/dev.to/issues/442

@genemars Going to close this since the 500s are probably gone by now. :)
