### ISSUE TITLE
Liquid tag for twitter video needs to allow video control

### ISSUE THREAD

**Issue by mjraadi** [thepracticaldev/dev.to#2673]
**Describe the bug**
There is no way to stop or mute an embedded twitter video on a post. The only way I was able to stop a video was to reload the page.

**To Reproduce**

1. Go to [this post](https://dev.to/areknawo/7-adorable-web-development-tricks-2of8)
2. Scroll down all the way down to `styled styles`
3. Play the video
4. Try to mute or stop it

**Expected behavior**
I should be able to stop or mute the video once I play it. 

**Additional context**
Since it's an HTML `video` tag, we can leverage `controls` attribute to let the user control the video playback.

**Comment by mjraadi** [comment]
I will submit a PR if you approve it. Thanks

**Comment by mariocsee** [comment]
@mjraadi, just a heads up that we're refactoring how liquid tags are rendered when you fix this in your PR. I just opened the PR that refactors the twitter tag #2721 and you should be all set to go when its merged.

**Comment by mariocsee** [comment]
Hey @mjraadi, just a heads up that liquid tag refactoring is done. Feel free to submit a PR for the issue.

**Comment by mjraadi** [comment]
Hey @mariocsee, thank you for your effort and contribution. I was actually reviewing the changes today but haven't gotten around to work on this bug yet. You're welcome to tackle this if you want to.
