### ISSUE TITLE
Award contributor badge to DEV Android contributors

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#2685]
**Is your feature request related to a problem? Please describe.**
Right now we only award the contributor badge to people who contribute to the web and iOS app. We should get Android users in there.

**Comment by Glennmen** [comment]
I would like to take this one. I assume it is only adding the new repo, there is no new badge for this right?

**Comment by jessleenyc** [comment]
@Glennmen yep!
