### ISSUE TITLE
Post stats

### ISSUE THREAD

**Issue by philnash** [thepracticaldev/dev.to#27]
It would be really great to be able to see stats for posts on how many people read the post. Mainly to  judge whether I am writing about the right things.

**Comment by jessleenyc** [comment]
Hey @philnash -- this is on the roadmap and will keep you posted on when it's available.

**Comment by benhalpern** [comment]
Hey @philnash put you in the beta for this. Might be janky, but it's on https://dev.to/dashboard

**Comment by philnash** [comment]
Ooh, fancy! Nice to see some numbers, thanks!

**Comment by dlebrero** [comment]
I can see just a "Loading Analytics..." banner. Is still in beta?

**Comment by Zhao-Andy** [comment]
Sorry, that was a mistake that you were seeing it without being in the beta, but I've added you in. Like Ben said it's still in beta so it might be buggy.

**Comment by dlebrero** [comment]
Thanks a lot Zhao. I see some numbers now. Very useful. 

Thanks again,

Dan

**Comment by maxpou** [comment]
Hi @Zhao-Andy, any chances to be in this beta group?

Thanks
Max

**Comment by sreisner** [comment]
Just checking on the status of this - if it's still in beta I'd love to be added as well!

**Comment by orgoldfus** [comment]
Hi, any plans to release this feature?

**Comment by shanalikhan** [comment]
@jessleenyc can you add me in beta as well?
Looking forward to improve dev.to

**Comment by equiman** [comment]
@jessleenyc or @benhalpern can you add me as beta user?

**Comment by arximughal** [comment]
Can you guys add me in the beta? @jessleenyc
