### ISSUE TITLE
Unable to Embed a single file from Github Gist

### ISSUE THREAD

**Issue by mdemblani** [thepracticaldev/dev.to#270]
# _BUG_
### Current Behavior
Special Liquid tags for embedding gists have been provided. But these tags, let you embed the complete gist with all the files present in the gist. Currently, there is no way to embed just a single file from a gist containing multiple files. Github also provides you with a way to fetch only a single file from the gist using the following link: 

```
https://gist.github.com/username/gistId.js?file=file-name.ext
```

### Expected Behavior
Using the `gist` liquid tag provided as follows:
```
{% gist https://gist.github.com/username/gistId.js?file=file-name.ext %}
```

The gist does not get rendered, although the link is completely valid. While seeing the browsers rendered HTML, the final link generated via the liquid tag is appended with the `.js` extension, thereby resulting in an invalid link

For example:
 Consider the gist at: [https://gist.github.com/amochohan/8cb599ee5dc0af5f4246](https://gist.github.com/amochohan/8cb599ee5dc0af5f4246). This gist has a total of 8 files.

To embed all the files:

```
{% gist https://gist.github.com/amochohan/8cb599ee5dc0af5f4246 %}
```

To embed a single file:

```
{% gist https://gist.github.com/amochohan/8cb599ee5dc0af5f4246.js?file=01_Laravel 5 Simple ACL manager_Readme.md %}
```

Should render the single gist file. You can check the link, which is a valid link.

PLEASE NOTE THAT AT THE END OF THE GIST-ID THE `.js` EXTENSION  IS NEEDED. THE WHOLE ISSUE TAKES PLACE SIMPLY DUE TO THE WRONG PLACEMENT OF THE `.JS` EXTENSION IN THE RENDERED HTML

**Comment by maestromac** [comment]
not stale

**Comment by lorezyra** [comment]
Is this still a problem? Doesn't seem to work as described above.

**Comment by masquerade817** [comment]
@lorezyra It doesn't work as described above. But support for embedding a single file has indeed been added.
You do that by adding a `file` attribute to the gist embed.
```
{% gist https://gist.github.com/username/gistId file=file-name.ext %}
```
Notice no `.js` extension after the gistId.
