### ISSUE TITLE
Can't delete draft post

### ISSUE THREAD

**Issue by Turnerj** [thepracticaldev/dev.to#2733]
**Describe the bug**
With the change for #2627, it is no longer possible to delete draft posts as the "Manage" section for posts is only available for published posts. Previous this was possible when the "Delete" button was accessible directly from the Dashboard.

**To Reproduce**

1. Create a draft post
2. Try to delete the post (without just publishing the post, going to "Manage", then pressing "Delete")

**Expected behavior**
Some method of being able to delete a post. Whether that is the whole "Manage" section being available for draft posts or just another "Delete" button being available when previewing a draft post.

Personally, it might be both better and easier that the "Manage" section be available for unpublished posts.

**Comment by bolariin** [comment]
To address this issue, would it be okay to add a delete button for draft posts?

**Comment by Turnerj** [comment]
From my point-of-view, I think it would be better to just have the "Manage" section available. If I have a draft post, it is reasonable to think that I should be able to set the experience level of the post or too change the author of the post - both features are behind the "Manage" section.

Additionally, if there were future features like (for example) automatic publishing at a certain day/time, I would image those being in the "Manage" section for draft posts.

The only concern I would have with the "Manage" section is the "suggest a tweet" section. If that is just stored against the post, that isn't an issue however if it is sent through to someone on submission, that feature probably shouldn't be accessible unless the post is published.

**Comment by jessleenyc** [comment]
Looks like a delete button was snuck back in with a recent PR. Going to close this for now since the primary issue has been addressed!
