### ISSUE TITLE
Wrong message empty Archive

### ISSUE THREAD

**Issue by Glennmen** [thepracticaldev/dev.to#2734]
**Describe the bug**
When viewing your Archive and it is empty it is showing an incorrect message. Probably the default empty Reading List message.

**To Reproduce**

1. Go to 'Reading List'
2. Click on 'View Archive'
3. See error

**Expected behavior**
A correct message should be shown: "Your Archive is Lonely"
Don't know what the second line should say.

**Screenshots**
![image](https://user-images.githubusercontent.com/11406433/57278791-bdf04400-70a7-11e9-99ac-bdb6ac0ad38e.png)

**Comment by jessleenyc** [comment]
Maybe we should remove the archive link if nothing is archived?
Or we can just have 'Your Archive List is Lonely' and no second line.
