### ISSUE TITLE
Internal events controller improperly parsing checkbox boolean input

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#275]
@benhalpern commented on [Wed Jul 11 2018](https://github.com/thepracticaldev/dev.to_core/issues/565)

The "live now" functionality was messed up because past events marked as not live now were not actually getting marked that way. Something was wrong. Could be a situation with how a parameter is passed and actually treated on the back end.

I know in some contexts we parse things like this:

```ruby
article_params[:publish_under_org].to_i == 1
```

In order to get the proper outcome. Not quite sure, but good candidate to be TDD'd with request specs.

**Comment by rodrigo-puente** [comment]
I'd like to take care of this one. I would only need a little more info on how to approach this "TDD'd with request specs."

**Comment by djhopper01** [comment]
I started working on understanding the code around this last night. @jessleenyc is this something that was broken previously, but now fixed? But now you'd like to add the tests?

I ask because I wrote a request spec and a feature spec around this, but couldn't produce a failing result. Maybe I'm missing something though - just wanted to get some additional clarity for the issue.

By the way, congrats on open sourcing! This is great.

**Comment by djhopper01** [comment]
Hey, yes I can push those and make a PR. @rodrigo-puente did you still want to take this one? I don't want to jump in if you've already got something here.

**Comment by rodrigo-puente** [comment]
@djhopper01 go ahead, I don't have much experience writing request specs and feature specs. I'll take a look at yours and hunt for another good first issue 🙂

**Comment by djhopper01** [comment]
Is there possibly a workflow that's known to reproduce this? I tried a few more things and couldn't reproduce this, so I think I must be testing the wrong thing.

Is the behavior supposed to closely follow the [`Internal::ArticlesController#update` action](https://github.com/thepracticaldev/dev.to/blob/7760a8d196207b76c26e3ddc6ef0d5574e645879/app/controllers/internal/articles_controller.rb#L122..L124)? Thanks!

**Comment by TakaakiFuruse** [comment]
Hi, I'd like to challenge this issue. Could I make some questions?

1) What is "live now", how it does work, and what's the purpose? (I can't read @benhalpern 's comment which @jessleenyc  quoted.)

2) Would you tell me how could I make Articles "live now" on dev environment? I could understand that an Article model has live_now property and some controllers are related to the "live", but cannot find out how to turn it on.

**Comment by maestromac** [comment]
not stale
