### ISSUE TITLE
Algolia creds doc URL displayed in Gitpod workspace console doesn't work

### ISSUE THREAD

**Issue by derekenos** [thepracticaldev/dev.to#2765]
# Issue

The URL to the doc that tells you how to get Algolia creds displayed in the Gitpod workspace console (if that's what it's called) doesn't work.

# Repro

1. [Launch the dev.to Gitpod](https://gitpod.io/#https://github.com/thepracticaldev/dev.to)

2. The workspace console at the bottom displays:

![Screenshot_2019-05-08_10-20-38](https://user-images.githubusercontent.com/585182/57382667-599eb480-717b-11e9-8546-9842011067ee.png)

3. :surfing_man: to https://docs.dev.to/get-api-keys-dev-env/#algolia

4. You get:

![Screenshot_2019-05-08_10-25-42](https://user-images.githubusercontent.com/585182/57382838-a97d7b80-717b-11e9-947b-6ec01b561f34.png)

# Maybe the solution

Change this URL to: https://docs.dev.to/backend/algolia/#get-api-keys

**Comment by maestromac** [comment]
Thanks for reporting this @derekenos !

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/2766
