### ISSUE TITLE
Saving Post Causes 500 error (bug)

### ISSUE THREAD

**Issue by rginfotechjpr** [thepracticaldev/dev.to#2779]
**Describe the bug**
Hi, I tried posting a new article with my account today and it produced a 500.

Right before attempting to post I updated the organization details and change the org username. I've tried a few things without success:

- posting under the organization
- posting without an organization
- I tried saving a sample post with the bare minimum (as opposed to my original article).
- I tried editing old posts

None of these things worked and I'm unable to create new articles. I also tried to write content through changing versions, but same thing happened.

**To Reproduce**

1. Logged in to dev.to
2. Clicked on Write Post
3. Got 500 error

then tried,
1. Create Video Post
2. Upload Video
3. Write Content
4. Hit save
5. Got 500 error

**Expected behavior**
The post should be saved.

**Screenshots**
<img src="https://user-images.githubusercontent.com/345089/51643761-d12c4780-1fc1-11e9-9d9b-1564545a8181.png">

**Desktop (please complete the following information):**
- Device: Desktop
- OS: Windows 10
- Browser: Chrome, Mozilla

**Comment by maestromac** [comment]
Hello @rginfotechjpr , this looks an issue specific to your account. Please email yo@dev.to for more help.
