### ISSUE TITLE
500 error when we try to write a post

### ISSUE THREAD

**Issue by stasstukanov** [thepracticaldev/dev.to#2783]
**Describe the bug**
Hello! We can't write a new post. When we try to push btn "Write a post" or try to edit our previous posts, we see 500 page. Profile - https://dev.to/lightit_global

**To Reproduce**

1. Go to 'profile or home page'
2. Click on 'btn - write a post'
3. See  500 error

**Expected behavior**
Write new post :)

**Screenshots**
https://take.ms/pvQ0f

**Desktop (please complete the following information):**

- OS: [macOS Mojave 10.14.4]
- Browser [safari]
- Version [12.1]
or
- Browser [chrome]
- Version [74.0.3729.131]

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by maestromac** [comment]
Hello @stasstukanov , this looks an issue specific to your account. Please email yo@dev.to for more help.
