### ISSUE TITLE
Signed in using Twitter - JS failed to load

### ISSUE THREAD

**Issue by remy** [thepracticaldev/dev.to#2790]
**Describe the bug**

I sign in using Twitter, and the JavaScript breaks causing a partially usable site:

<img width="1440" alt="Screen Shot 2019-05-10 at 19 26 20" src="https://user-images.githubusercontent.com/13700/57548814-d091a400-7359-11e9-9d04-d127032636ab.png">

**To Reproduce**

Steps *for me* to reproduce the behavior:

1. Go to incognito window
2. Click on twitter sign in
3. See screenshot / `Error getting user and CSRF Token Error: Couldn't find user data on page.`

I strongly doubt if you can replicate using a typical account, and I suspect it's something to do with my twitter account sign in.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mac High Sierra
- Browser: Chrome Stable
- Version: 74.0.3729.131

**Additional context**

I appear to have linked my @remy github account already, but I thought I had previous linked using '@rem' from Twitter - but seeing as I could replicate in an incognito browser (only 1password extension runs) - I don't think it was local to my browser.

**Comment by jessleenyc** [comment]
Hmm strange. We'll look into this -- it does sound account specific.

**Comment by ThomasTheSpaceFox** [comment]
I'm seeing the same sort of CSRF error message, only im on linux seamonkey (latest), and I'm signed in via github. with the same result as in the screenshot above.
![devtoerror](https://user-images.githubusercontent.com/13690135/57873498-6a36d680-77dc-11e9-92f7-715077e05785.png)

**Comment by hwolfe71** [comment]
This may be the same issue I've been having. I initially signed up using Twitter, but then linked my Github account, and used it to sign in at work.

I'm using Palemoon on Windows 7, 64-bit at work, and Palemoon on PCLinuxOS, 64-bit at home.

**Comment by phlash** [comment]
same (or similar) here, I tweeted first, then remembered I can post a bug report :)
https://twitter.com/PhlashGBG/status/1129332311995179009

On FF 60.6.3esr, Debian 9.9 (stable) fully patched. I log in with Twitter.
![Screenshot from 2019-05-17 21-36-50](https://user-images.githubusercontent.com/649715/57956712-e0792d00-78f1-11e9-828f-d91473396bab.png)

**Comment by phlash** [comment]
@jessleenyc  Sorry to bug you on this, but I have been unable interact with anything on dev.to (posts, people, my profile) for over a week now due to this regression. For me dev.to is now useless in Firefox, it of course works in Chromium (which I would rather not use thanks).

**Comment by jessleenyc** [comment]
Hey @phlash -- I'm going to send you a quick email. Wondering if you can help me troubleshoot on your end.

**Comment by jessleenyc** [comment]
Also, for everyone who's experiencing this: do you have any extensions installed that could be affecting this?

**Comment by jessleenyc** [comment]
@phlash did you change your github username recently? I'm wondering if this may be the cause. I can't find a DEV profile that matches your exact github username right now, so I'm actually unable to email you. Mind emailing me directly at jess@dev.to?

**Comment by ThomasTheSpaceFox** [comment]
@jessleenyc The only browser extension i use (aside from chatzilla and the DOM inspector which ship with seamonkey) is a gopher protocol plugin.

**Comment by remy** [comment]
I ran my original test and reproduction in an incognito window with extensions disabled.

**Comment by choroba** [comment]
I'm experiencing the same problem in Firefox, logging in via Github. The page works OK in other browsers (Opera, Chromium). Safe mode in Firefox didn't help.
Interestingly, visiting the page in a Private Browsing window displays everything while I'm not logged in, but after logging in, the problem reappears.
The console shows the following 3 errors:
```
TypeError: p is null[Learn More]
base-711d367ffa140cda926fa9865d39820c884beb6955454abd65a03cc3a101786e.js:13:1766
<anonymous>
https://practicaldev-herokuapp-com.freetls.fastly.net/assets/base-711d367ffa140cda926fa9865d39820c884beb6955454abd65a03cc3a101786e.js:13:1766
<anonymous>
https://practicaldev-herokuapp-com.freetls.fastly.net/assets/base-711d367ffa140cda926fa9865d39820c884beb6955454abd65a03cc3a101786e.js:13:1
TypeError: InstantClick is undefined[Learn More]
search.js:75:2
l
search.js:75:2
value/<
Search.jsx:32:12
A
preact.mjs:607
O
preact.mjs:471
x/<
preact.mjs:637
x
preact.mjs:611
w
preact.mjs:209
E
preact.mjs:704
[167]/<
Search.jsx:8:2
Error getting user and CSRF Token 
Error: Couldn't find user data on page.
Stack trace:
e@https://practicaldev-herokuapp-com.freetls.fastly.net/packs/Onboarding-90c696173ee5ca4c2bbf.js:1:9528
Onboarding.jsx:51:6
[160]/<
Onboarding.jsx:51:6
```
See also [this post](https://dev.to/choroba/dev-to-not-working-in-firefox-592).

**Comment by maestromac** [comment]
Hello @phlash & @choroba , can you check if you can access dev.to now?

**Comment by phlash** [comment]
Works for me :)

**Comment by ThomasTheSpaceFox** [comment]
@maestromac I can confirm its working on my end too.

**Comment by choroba** [comment]
Yes, it's back!

**Comment by maestromac** [comment]
Seems like this is resolved. Please let me know if otherwise!!
