### ISSUE TITLE
Did not allow me to post after multiple attempts. 

### ISSUE THREAD

**Issue by Siddhant-Misra** [thepracticaldev/dev.to#2794]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by jessleenyc** [comment]
@Siddhant-Misra this sounds like an issue related to your individual account. Can you send an email to yo@dev.to
