### ISSUE TITLE
RSS feeds?

### ISSUE THREAD

**Issue by P-Krebs** [thepracticaldev/dev.to#28]
Hello! 

I am one of the six people left in the world who uses RSS to keep up with articles and blogs. I was wondering if there is currently a way to get RSS feeds for either the master feed of articles, or on a per-user basis? And if not, is RSS in the roadmap in any form? 

For reference and as weak justification, Medium has the ability to prefix a username with /feed/ to get the RSS feed for that user's stories. I would love to be able to do something similar on dev.to.

(FWIW, if/when the site goes open source, I would be willing/able to help implement this :) )

**Comment by jessleenyc** [comment]
Hey @P-Krebs! We have a RSS feed for the featured articles but not per user. We can put this on our backlog, thanks for the request. 

Here's the link for main feed: https://dev.to/feed

**Comment by beejhuff** [comment]
I'm not sure if perhaps this is the best place to chime in (vs, perhaps a new feature request) but in addition to  user feeds and the main feed, I can see that topic-specific feeds would be incredibly useful, especially as the amount of original content on the site grows.

Not to suggest copying this implementation by any means, but as a reference, Medium has implemented a standard mechanism (more or less) for extracting feeds (even before they aquired superfeedr) - and they're supported as [first class attributes of the following objects](https://help.medium.com/hc/en-us/articles/214874118-RSS-feeds):

 - User Profiles: [an example from my profile](https://medium.com/feed/@beejhuff)
 - Publications: [an example from the Founding Publication](https://medium.com/feed/@founding/)
 - Custom Domains: [an example using Hacker Noon](https://hackernoon.com/feed)

They also support [truncating the feed](https://help.medium.com/hc/en-us/articles/225170228-Truncated-RSS-feeds-for-publications) to limit the items included in the endpoints (which is handy for usage in systems like inoreader.com or other places where you may want to write code to parse your feed and syndicate the content via social channels or perform other processing).

**Comment by benhalpern** [comment]
_Finally_ did this. Should be live soon.

**Comment by beejhuff** [comment]
Awesome, thanks for the effort Ben! I'll give it a whirl later this evening and will open an new issue if I run into any issues while testing.  

Again, my genuine thanks for this and all the work you've put into dev.to!!!$


Sincerely,

Bryan "BJ" Hoffpauir, Jr.
beejhuff@gmail.com(mailto:beejhuff@gmail.com)  

+1 (337) 366-0726(tel:+1%20(337)%20366-0726)  

LinkedIn: https://linkedin.com/in/bjhofpauir  

GPG Key: http://bit.ly/beejhuff-pgp  
GPG Fingerprint: 5CAF226B52B003F811DA47D653117C1A8673E297

Google Calendar: https://bit.ly/beejhuff-gcal

**Comment by dploeger** [comment]
@benhalpern Great. Can I find any docs about that? I can not find a feed of my published posts. I'd like to use that to post them on twitter.

**Comment by Zhao-Andy** [comment]
@dploeger You can find it via `https://dev.to/feed/username`, for example: https://dev.to/feed/andy

**Comment by dploeger** [comment]
Great. Thanks

**Comment by Nakilon** [comment]
Am I blind or there is no feed per topic? Like for https://dev.to/t/ruby
Subscribing to just exact posters, not topics, is pointless and ineffective.

**Comment by maestromac** [comment]
Hello @Nakilon , that feature is currently not available. The feature request for it is [here](https://github.com/thepracticaldev/dev.to/issues/201).

**Comment by theonelucas** [comment]
I had to duck it ("Google it", but with duckduckgo) the term "dev.to rss" to know how to subscribe to the RSS feed of dev.to. Couldn't find any link/mention to the RSS feed on the dev.to site.

**Comment by maestromac** [comment]
Thanks for pointing that out @theonelucas . We should have a page dedicated RSS FAQs.

**Comment by helmutgranda** [comment]
@theonelucas, same here. FAQ still not up to date.

https://dev.to/faq

**Comment by maestromac** [comment]
Hello @theonelucas , we just updated it

**Comment by JamoCA** [comment]
Are there any issues with adding an RSS Link tag to pages for the purpose of autodiscovery?  I still heavily depend on RSS to consume news & information.  I wasn't able to determine the RSS feed for my new blog until I viewed this reported issue.

### Example HTML Source

```
<link rel="alternate" type="application/rss+xml"
    title="I'm a ColdFusion web application developer..."
   href="https://dev.to/feed/gamesover" />

**Comment by maestromac** [comment]
That's a great suggestion @JamoCA . Would you mind creating an issue to surface this?

**Comment by JamoCA** [comment]
Done.  I've submitted a [feature request](https://github.com/thepracticaldev/dev.to/issues/28).

**Comment by lucamauri** [comment]
> Done. I've submitted a [feature request](https://github.com/thepracticaldev/dev.to/issues/28).

It seems the link is directing back to this issue, I believe the right page you wanted to link is [Issue 6368](https://github.com/thepracticaldev/dev.to/issues/6368)

**Comment by kucukti** [comment]
Is it possible to get rss feed for top of week or month

**Comment by rhymes** [comment]
Hi @kucukti, would it be possible for you to open a [feature request](https://github.com/thepracticaldev/dev.to/issues/new?template=feature_request.md) so this doesn't get buried in a closed issue?

Thank you!

**Comment by jonrandy** [comment]
What posts appear in the personal feed? It certainly doesn't appear to be all my posts
