### ISSUE TITLE
500 error on edit and remove canonical url

### ISSUE THREAD

**Issue by equiman** [thepracticaldev/dev.to#2818]
**Describe the bug**
When edit a post and remove canonical url, show error 500 on save. Now i try load my post and always show 500 error.

Start with this post:
https://dev.to/equiman/my-devtech-podcast-subscription-1kb7
And I do the same steps and happen with
https://dev.to/equiman/iterm2--oh-my-zsh--powerlevel9k-best-terminal-combination-for-geeks-58l5

Both of this post can't be loaded any more :'(

**To Reproduce**

1. Go to dash board
2. Open post
3. Click on edit
4. Click on ... (tree dots) button (Additional Configuration)
5. Select URL on canonical URL
6. Delete value
7. Click on Done button
7. Click on Save button

**Expected behavior**
Remove canonical URL and show post

**Desktop (please complete the following information):**
- OS: MacOS
- Browser Chrome
- Version Version 74.0.3729.131 (Official Build) (64-bit)

**Additional context**
Start happen after editor changelog upgrade
https://dev.to/devteam/changelog-upgraded-editor-45mk

**Comment by equiman** [comment]
Not always happen. With this post:
https://dev.to/deinsoftware/run-a-command-in-external-terminal-with-net-core-d4l

I'm doing same steps, and don't show error 500.
But if edit again the post, I see the canonical url again on this post. It was not deleted.

**Comment by benhalpern** [comment]
Okay sorry about this. I have fixed your articles and issued this patch:

#2821

It seems like this form submits an empty string and it gets set instead of blank, and then that caused a runtime error. Fix is on its way up shortly.
