### ISSUE TITLE
Listings Dashboard

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#2825]
**Is your feature request related to a problem? Please describe.**
Add an area to the dashboard to manage listings quickly.

**Describe the solution you'd like**
An index view of all user listings w/ a button that sends them to the listings edit page.

**Comment by jessleenyc** [comment]
I think what I described above is the quickest start. Would be nice to eventually:
- publish / bump directly from this view

Right now the biggest pain point is that you need to search for listings in order to edit one and if that listing has expired...it won't show up and you can't republish it easily.

**Comment by mariocsee** [comment]
Resolved via #3014
