### ISSUE TITLE
Add dropdown to listings

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#2826]
**Is your feature request related to a problem? Please describe.**
Add a dropdown to each listing to access edit and report abuse report buttons

**Describe the solution you'd like**
A similar design to the dropdown/ellipses we have for comments would probably make sense here.

**Comment by silvererudite** [comment]
Hi..can you pls explain the problem a bit more. As in there's already an option in each listing called report abuse which maybe takes you to a link. So I'm confused what exactly to do here.

**Comment by jessleenyc** [comment]
Hey @silvererudite! Instead of having the report abuse and edit button on the listings card, we want to move it over as a drop down. For example, similar to how we organization additional actions for comments. 

![Screen Shot 2019-08-12 at 2 32 56 PM](https://user-images.githubusercontent.com/14931921/62888823-1c176d80-bd0e-11e9-9b9a-9304850b2f27.png)

I think for listings we'd want three vertical dots instead of horizontal, but we can handle any last minute design stuff if you want to get the dropdown working.

**Comment by silvererudite** [comment]
@jessleenyc Cool ! I would like to work on this.  can u pls point me to the files related to this issue ?

**Comment by mariocsee** [comment]
Hey @silvererudite, the file responsible for showing each listing is `app/javascript/listings/singleListing.jsx`. Currently, `const editButton` displays the edit and report abuse buttons. Hope this is helpful, and let us know if you have any other questions we can help with! 😄

**Comment by silvererudite** [comment]
Hi @mariocsee...can you pls help me with how to run bin/setup on Windows as per the last step in the docs here 
https://docs.dev.to/installation/windows/ 
this is what I get after I double click the setup file
![Screenshot (16)](https://user-images.githubusercontent.com/24827548/63710272-a3122d00-c85a-11e9-88e0-234173bfc6e8.png)

**Comment by silvererudite** [comment]
@mariocsee ...it says setup is not recognized as an internal or external command. i know I should run the run with file extension but as u can see it shows no extension :( the file type is just FILE ! I tried running with setup.exe and setup.rb also it doesnt work. 
As far as I see, It is a ruby script but seems like my system can't run it even though Ruby is installed !

**Comment by silvererudite** [comment]
Hi @mariocsee ...I was able to run bin/setup this this time (had some dependency missing). But the setup fails with this error. Any ideas how to solve this?
![Screenshot (17)](https://user-images.githubusercontent.com/24827548/63871197-4723e180-c9dd-11e9-863e-7cbe81b8d3a7.png)

**Comment by silvererudite** [comment]
hey @jessleenyc I set up the api keys in cnfig/application.yml from algolia but now i'm getting this error. pls help
![Screenshot (18)](https://user-images.githubusercontent.com/24827548/63881528-dcc96c00-c9f1-11e9-900d-37ff43821cef.png)

**Comment by mariocsee** [comment]
Hi @silvererudite, based on the error message `Algolia::AlgoliaProtocolError: Cannot reach any host: execution expired...` and the line the error was raised `User.clear_index!`, it seems like the issue stems from improper Algolia key setup. Checkout our [installation docs for Algolia](https://docs.dev.to/backend/algolia/) just to double check your `application.yml` file. Hope this helps!

**Comment by zachdixon** [comment]
Hi, looks like it's been a while since the last activity on this ticket and I'd like the pick it up if the feature is still needed, @jessleenyc. I started last night and should be able to have a PR in tomorrow, but let me know if any requirements have changed on this please.

**Comment by zachdixon** [comment]
Finished implementing this feature but running into a couple linting issues. One that I'm not sure how to fix is it complaining about an unresolved import for an image.
`import ThreeDotsSrc from 'images/three-dots.svg'`
This is working and how I see it being done elsewhere in the repo so not sure what the solution is.
