### ISSUE TITLE
Inconsistent HTML structure for input fields & labels

### ISSUE THREAD

**Issue by evanwinter** [thepracticaldev/dev.to#2834]
**Describe the bug**
The labels for input fields found under the "Danger Zone" section of https://dev.to/settings/account are lacking proper spacing, due to their lack of `label` elements (using `b`'s instead). 

**To Reproduce**

1. Go to https://dev.to/settings/account
2. Scroll down to "Danger Zone"
4. Look at the appearance of the input fields and their labels. There's no vertical spacing between label and input, whereas it's present on all other input fields on the page (and throughout the site it seems).

**Expected behavior**
Expected these inputs to look like the other inputs on the page.

**Screenshots**

Not using `label`:
![Screen Shot 2019-05-14 at 1 26 59 PM](https://user-images.githubusercontent.com/19195468/57722426-0382b300-764c-11e9-88b6-8668e4112ef6.png)

Using `label`:
![Screen Shot 2019-05-14 at 1 27 08 PM](https://user-images.githubusercontent.com/19195468/57722458-14cbbf80-764c-11e9-8bed-ec456958e293.png)

**Desktop (please complete the following information):**

- OS: OSX 10.14.4
- Browser: Latest Chrome, latest Safari

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/2835
