### ISSUE TITLE
Listing spacing inconsistency

### ISSUE THREAD

**Issue by mariocsee** [thepracticaldev/dev.to#2846]
**Describe the bug**
With listings so new, there's some details to iron out in terms of spacing and window resizing.

**To Reproduce**

1. Go to 'dev.to/listings'
2. Observe that some listings have ample space between the name of the listing poster and the bottom border while others are squeezed together.
3. Resize your window and see that listing container sizes are not adjusting to the content lengthwise until you hit a certain screen size such as the standard tablet dimensions.
4. Information on some listings cannot be seen on certain screen sizes or there is an abundance of space.

**Expected behavior**
The information on the listing should be shown and accessible at all times and the spacing/styles should be more consistent. 

**Screenshots**
![2019-05-15 15 54 40](https://user-images.githubusercontent.com/13403332/57805348-b7f30680-772a-11e9-92ed-2399bf680d4b.gif)

**Desktop (please complete the following information):**

- OS: MacOS Mojave
- Browser Chrome
- Version 73

**Comment by mjraadi** [comment]
@mariocsee Thanks for reporting this issue. 
My understanding is that they used CSS grid system to build a masonry style layout to display all the listing items. To make each listing container tall enough based on their content, they used a JavaScript function which will go through each individual item and set the number of grid rows that it should span to. This function is triggered for different events but it won't for window resize event. 
I think adding bellow code to the `componentWillMount` function will attach the appropriate event handler:
```js
window.addEventListener("resize", resizeAllMasonryItems);
```
However, I don't it's necessary. Take a look at this:

![Peek 2019-05-24 14-28](https://user-images.githubusercontent.com/20579660/58320241-794b0380-7e30-11e9-829a-1d77fab4836b.gif)
For the most part, the device of the end user is a fixed width and I don't think we should attach an expensive function(`resizeAllMasonryItems`) to the window resize event. 
What do you think?

**Comment by mariocsee** [comment]
Hey @mjraadi! Wish I had gotten back to you sooner. Yeah, there's a resize masonry function in JS that recalculates the heights, but it's definitely triggered less often that if you use an event listener. From your screenshot, it definitely looks a lot better with the resize, but your concerns are valid when it comes to performance and triggering this function.

I would think resizing will mostly affect dev.to users on desktop browsers rather than mobile devices, and that resizing windows isn't done often anyways (at least in my personal experience) and is preferred over reloading the page. It's worth opening a PR for considering this will stay within listings world anyways.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/3011
