### ISSUE TITLE
Reading List: Add the reading time

### ISSUE THREAD

**Issue by giventofly** [thepracticaldev/dev.to#2862]
**Is your feature request related to a problem? Please describe.**
Reading time for articles are important to be seen in the reading list to manage the time to read, or to just know if I have enough time to read this article on my break.

**Describe the solution you'd like**
Appear the reading time without opening the article.

**Comment by aspittel** [comment]
Hey @giventofly that sounds like a good idea! Thanks for posting it! We'll discuss and get back to you!

**Comment by jessleenyc** [comment]
@giventofly definitely agree with this. Approved this issue for anyone who wants to work on it.

**Comment by jessleenyc** [comment]
@mariocsee sorry totally didn't see that you already submitted a PR for this. Was just updating some issues with yesterday's notes!

**Comment by mariocsee** [comment]
all good, @jessleenyc 👍
