### ISSUE TITLE
Improper Error Messaging in our Editor when Exceeding Max Tag Limit

### ISSUE THREAD

**Issue by michael-tharrington** [thepracticaldev/dev.to#2868]
**Describe the bug**
We received 2 separate reports that users received `status:422` `error:Unprocessable Entity` messages when trying to post their articles.

From an image one of the users shared, I could tell they were using more tags than is allowed.

I created a test post and used too many tags (7 — the limit is 4) and received the same error message when trying to post.  

**To Reproduce**

1. Go to [post an article](https://dev.to/new)
2. Write a title
3. Write more than 4 tags 
4. Write something in the body
5. Save the article

**Expected behavior**
Instead of receiving the `status:422` `error:Unprocessable Entity` messages, the user should receive a clear error message indicating that the maximum number of tags is 4 and they've exceeded the limit.

**Screenshots**

Here's what I see in my test

![](https://cl.ly/8f7ff4eee7c1/download/Image%202019-05-17%20at%2012.13.51%20PM.png)

**Desktop (please complete the following information):**

- OS: macOS Mojave 10.14.4 
- Browser: Chrome
- Version 73.0.3683.86

**Comment by jessleenyc** [comment]
Let's update the error message for clarity.
