### ISSUE TITLE
Lost an article after changing author on a organisation post

### ISSUE THREAD

**Issue by philnash** [thepracticaldev/dev.to#2871]
**Describe the bug**
One user in our organisation imports the RSS feed for new articles. I was going to publish the imported version of [this article](https://www.twilio.com/blog/serverless-ruby-on-aws-lambda-with-the-jets-framework) and I started by changing the author to myself.

I submitted the form and rather than an HTML page I received a short JSON document describing a couple of attributes of the article. Returning to the list of draft articles, the article was no longer in the organisation list or in my list. It seems to be completely gone.

**To Reproduce**

1. Setup an organisation to import articles from RSS and import some draft articles
2. Go to the organisation drafts as an organisation admin
3. Choose an article, select a different author and submit the change
4. See JSON document
5. Return to organisation drafts and see that the article is gone

**Expected behavior**
I expected the author to be changed and the article remain in the organisation drafts as well as appearing in my own.

**Desktop (please complete the following information):**

- OS: MacOS Mojave
- Browser: Firefox
- Version: 66

**Additional context**
This has worked before and this is the first time I have experienced this bug.

**Comment by Zhao-Andy** [comment]
Hey @philnash, what was the article title? Or if you'd rather keep it private, feel free to [DM me via Connect](https://dev.to/connect/@andy) or send an email to yo@dev.to.

**Comment by Zhao-Andy** [comment]
@philnash I've manually updated the article and it should appear in your organization's dashboard now. Let us know if otherwise though!

As for the bug itself, we'll take a look into it.

**Comment by omenking** [comment]
I have a similar issue. I went to edit my post and its completely empty.
This is a major bug

**Comment by rhymes** [comment]
Hi @omenking thanks for the reporting this issue, was your post originally imported with the RSS feed as well?

@Zhao-Andy I tried to reproduce this by creating a post and then editing changing the body locally with both editors but failed. It's probably tied with the RSS logic somehow. I'll keep digging

**Comment by omenking** [comment]
I don't utilize RSS feed import.
I had written and saved the article. 
In a new browser session when I returned to edit the body was completely blank.

**Comment by Zhao-Andy** [comment]
Hey @omenking, so to clarify you:
1. went to `/new`
2. wrote an article and submitted it to save as a draft
3. started a new and different browser session
4. went to your dashboard and clicked "edit" on your article
5. the article's body was blank.

If so, I think what you're describing is a different issue than Phil's issue. Were you writing an article under an organization?

If you'd like to [DM me on Connect](https://dev.to/connect/@andy) the title of your article, I can look at our logs to try and see what's going on.

**Comment by Zhao-Andy** [comment]
@philnash after investigating, I think the issue came up after we updated how our `articles_controller` handles updates. TL;DR - if you need to change the authors of one of your organization's posts, feel free to DM me and we can change it for you until the bug is fixed.

### Bug findings:
Right now, if you change the article's author via your organization dashboard, it'll send a `PUT /articles/:id` that doesn't handle keeping the article's `organization_id` and changes it to `nil`. It also renders a JSON response incorrectly. We recently made changes to `articles_controller` which removed the previous author change functionality.

**Comment by omenking** [comment]
It was an organization article for myself.
