### ISSUE TITLE
Reaction panel on mobile

### ISSUE THREAD

**Issue by Link2Twenty** [thepracticaldev/dev.to#2877]
The reaction panel looks a little top heavy to me. Would it look better to centralise the buttons within it?

I would propose changing the padding here
https://github.com/thepracticaldev/dev.to/blob/e7306d2e63ae4247b6dc484b9a3ca0d14a467d1f/app/assets/stylesheets/article-show.scss#L849-L856

to

```css
padding: 8px 0;
```

Before:
![image](https://user-images.githubusercontent.com/3534427/57968451-c1ff4a00-7962-11e9-8dd8-a6ddb71de519.png)

After:
![image](https://user-images.githubusercontent.com/3534427/57968446-b4e25b00-7962-11e9-87e2-cec8dc076c4f.png)

The bar loses 1px in height but, I feel, looks more balanced?
Thought?

If approved it would make a good first issue.

**Comment by theghostyced** [comment]
Hi @maestromac. if this issue has not been taken up, can I work on it?

**Comment by maestromac** [comment]
Yep go ahead @theghostyced !

**Comment by mstruve** [comment]
Hey @Link2Twenty, thanks so much for bringing this to our attention. Given we are now in the middle of site redesign we will definitely take this into consideration. In the meantime, I am going to close the issue as we will work to address it with the redesign.

Thanks for being a great active community member!
