### ISSUE TITLE
Poor contrast on badge notification

### ISSUE THREAD

**Issue by M0nica** [thepracticaldev/dev.to#2883]
**Describe the bug**
There is low contrast on the badge text in the notifications screen

**To Reproduce**
Steps to reproduce the b

ehavior:

1. Go to 'https://dev.to/notifications'
2. Scroll down to badge
3: See poor contrast 

**Expected behavior**
Higher contrast text for "Happy DEV birthday! Can you believe it's been 2 years already?!" 

**Screenshots**
<img width="1440" alt="Screen Shot 2019-05-19 at 7 29 43 PM" src="https://user-images.githubusercontent.com/6998954/57989689-910b3c00-7a6c-11e9-80f0-883291951a85.png">

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser [e.g. chrome, safari] Chrome

**Additional context**
Add any other context about the problem or helpful links here.

Higher contrast between text and foreground makes a website more accessible. The screenshot above shows how the text in question failed the Google Lighthouse audit. The Lighthouse audit tool can be accessed in Chrome developer tools in the 'Audit' tab.

**Comment by M0nica** [comment]
I opened a PR to address this but I am not sure how to trigger a test notification in dev. 

I tried updating `badge_rewarder.rb` the 24 to 0 and -1 after leaving a reaction on a comment and running `bin/rails jobs:work` after running`bin/rails jobs:clear`

`  def self.award_beloved_comment_badges
    Comment.where("positive_reactions_count >= ?", 24).find_each do |comment|` .

Any recommendations for test badge notifications locally would be greatly appreciated.

**Comment by Zhao-Andy** [comment]
Hey @M0nica, you should be able run this script in `rails console` to send yourself a badge notification:
```ruby
me = User.last # or whatever your ID is
ba = BadgeAchievement.create!(user_id: me.id, badge_id: Badge.first, rewarding_context_message_markdown: "Happy DEV Birthday! Can you believe it's been 2 years already?!")
Notification.send_new_badge_notification_without_delay(ba)
```

**Comment by M0nica** [comment]
Thank you @Zhao-Andy for the script. It was super valuable as I am new to Ruby and still getting familar with the dev.to codebase.  I was able to run it and trigger a test notification with slight modification after setting up the database.

```
me = User.last.id 
ba = BadgeAchievement.create!(user_id: me.id, badge_id: Badge.first.id, rewarding_context_message_markdown: "Happy DEV Birthday! Can you believe it's been 2 years already?!")
Notification.send_new_badge_notification_without_delay(ba)
```

**Comment by M0nica** [comment]
This issue should be resolved now as https://github.com/thepracticaldev/dev.to/pull/2909 was merged.
