### ISSUE TITLE
Problem signing into dev.to

### ISSUE THREAD

**Issue by Adam24** [thepracticaldev/dev.to#2885]
**Describe the bug**
Attempting to sign in with both authentication methods causes the page to endlessly load

**To Reproduce**

Try to sign in on iPad safari private mode on iOS 12.3 public beta

**Expected behavior**
I expected to successfully sign into the site.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: iPad 2017 model
- OS: iOS 12.3 public beta
- Browser Safari

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by Adam24** [comment]
This occurs off and on.

**Comment by jessleenyc** [comment]
Closing this because I believe it's account-specific. Please email yo@dev.to with the email address associated with your DEV account and our support team can look into it!

**Comment by codePerfectPlus** [comment]
I am facing the issue for 2 accounts for 2 differnet devices. 
something is wrong.
