### ISSUE TITLE
Got wrong post on editing

### ISSUE THREAD

**Issue by shapoglyk** [thepracticaldev/dev.to#29]
Just wrote an [introducing post](https://dev.to/shapoglyk/hi/)

But when I click on edit button from dashboard page I got other's post to edit.

Interesting is that url looks like my post is being edited: https://dev.to/shapoglyk/hi/edit, but in fact I see [this post](https://dev.to/tooringtest/hi). And when I click on Save Post I got 500 error.

And if I click Edit button from my posts page everything works fine.

**Comment by jessleenyc** [comment]
Thanks for flagging this @shapoglyk -- it was a caching bug -- should be fixed now.
