### ISSUE TITLE
status:422  – error:Unprocessable Entity

### ISSUE THREAD

**Issue by rugk** [thepracticaldev/dev.to#2916]
**Describe the bug**
When i try to save my post, it shows me an error.

**To Reproduce**

1. Copy the raw text from https://gist.github.com/rugk/a5725a7c40e9dd8dc95da2c4062f317d.
2. Try to save it as a new post.

**Expected behavior**
Should work.

**Screenshots**
![image](https://user-images.githubusercontent.com/11966684/58109009-16b5f580-7bed-11e9-9a96-eaae50701aa4.png)

Network response:
![image](https://user-images.githubusercontent.com/11966684/58109041-2af9f280-7bed-11e9-8e7e-5f05f583077b.png)

**Desktop (please complete the following information):**

- OS: Linux/Fedora 30
- Browser: Firefox
- Version: v66 and v68

**Additional context**

I've tried to remove stuff/text, but I have not yet noticed which character or so causes this issue.

**Comment by rhymes** [comment]
Hi @rugk I think it's because you're beyond the limit of tags (max 4)

Sorry if the error message is misleading, it'll get updated soon

**Comment by rugk** [comment]
Yeah, seems to work now though…

Published: https://dev.to/rugk/dyk-your-website-can-get-a-dark-mode-toggled-by-your-operating-system-inl
