### ISSUE TITLE
Provide test coverage for PingAdmins service

### ISSUE THREAD

**Issue by tannakartikey** [thepracticaldev/dev.to#2917]
The [`PingAdmins`](https://github.com/thepracticaldev/dev.to/tree/master/app/services/ping_admins.rb) service is not covered by specs. The code needs to be refactored to remove [`Rails.env.production?`](https://github.com/thepracticaldev/dev.to/blob/master/config/initializers/slack_notifier.rb#L29) check from [SlackBot](https://github.com/thepracticaldev/dev.to/blob/master/config/initializers/slack_notifier.rb) or the specs need to be written without stubbing the production environment.

The initial discussion about the same can be found [here](https://github.com/thepracticaldev/dev.to/pull/2878#pullrequestreview-239542155).

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/4169
