### ISSUE TITLE
Error when trying to save an invalid post

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#2933]
**Describe the bug**
The user gets a "stuck" screen instead of error messages when the post is not saved

**To Reproduce**

1. Go to the '/new' page (new post form)
2. Fill in the post title and description
3. Write a long tag in the tags input (e.g. "mysuperlongtaghelloworld", which is > 20 symbols long)
4. Click "save draft" or "publish"
5. See "Saving Draft" at the bottom of the page for a long time

Errors from the console:
```
ActiveRecord::RecordInvalid (Validation failed: Tag "mysuperlongtaghelloworld" is too long (maximum is 20 characters)) [error]

ActiveRecord::RecordInvalid - Validation failed: Tag "mysuperlongtaghelloworld" is too long (maximum is 20 characters):
  app/services/article_creation_service.rb:29:in `create!'
  app/controllers/articles_controller.rb:126:in `create'
```

**Expected behavior**
User is notified that the post wasn't saved because of the validation errors.

**Screenshots**
![изображение](https://user-images.githubusercontent.com/30115/58168848-e8412480-7c97-11e9-8964-7f1a7585b5e4.png)

**Suggested solution**
`ArticleCreationService` should do `save` instead of `save!` and return errors if they occur.
The code in the controller should handle those errors and display them to the user.

**Comment by rhymes** [comment]
Hi @lightalloy, I believe this was solved by https://github.com/thepracticaldev/dev.to/pull/2922 - try rebasing the code. If you're still experiencing it with the latest master, it might be something else going on.
