### ISSUE TITLE
Recent change takes up more screen space on smaller screens

### ISSUE THREAD

**Issue by sivaraam** [thepracticaldev/dev.to#2942]
**Describe the bug**
I recently noticed that the bottom bar which has the 'Heart', 'Unicorn', etc., icons seems to be taking more space than it did some time ago. It's height is twice as it was some time (probably a month) ago. As a consequence, it's taking up more space on my small screen and the space for content has reduced. It would be nice if this issue could be fixed by making it take up only half the height it now requires. That would save me some space. The worst consequence is there's barely space for me to see the contents of the comment box as the device keyboard also takes up about 40% of the screen space leaving very less space for the comment box. See screen shots below for reference.

FWIW, the dimension reported by the ["how big is my browser"](http://howbigismybrowser.com/) for my device is 320x452.

**To Reproduce**

1. Go to a 'dev.to post' ([example link](https://dev.to/ronsoak/the-lies-and-lack-of-self-respect-that-lead-to-burnout-5007)) on a small screen device (e.g., Samsung SM-J111F and possibly the iPhone SE)
2. Observe the bottom bar

**Expected behavior**
All icons in the bottom bar are present in one row.

**Actual behavior**
The bottom bar seems to require two rows of space thus eating up more space and leaving less space for the content. This is particularly frustrating when trying to comment.

**Screenshots**
![Screenshot_2019-05-22-11-21-19](https://user-images.githubusercontent.com/12448084/58224886-1a589200-7d3d-11e9-98a5-aa35b5af8d78.png)
![Screenshot_2019-05-21-11-16-33](https://user-images.githubusercontent.com/12448084/58224887-1af12880-7d3d-11e9-9a51-750016711fb4.png)

**Smartphone (please complete the following information):**
- Device: [Samsung SM-J111F
- OS: Android 5.1.1
- Browser: Firefox 66.0.5

**Comment by jessleenyc** [comment]
I'm going to close this issue since the solution would be a similar solution to whatever we implement here, and there's also been more conversation in this thread: https://github.com/thepracticaldev/dev.to/issues/3324
