### ISSUE TITLE
How to cross-posting?

### ISSUE THREAD

**Issue by pldg** [thepracticaldev/dev.to#2944]
I'm trying to cross-post from a gist containing a single markdown file. I set `canonical_url: https://gist.github.com/{my_gist}`, then I check the post preview, but nothing happen. I've tried on both the v1 and v2 editors.  Anyone can help?

**Comment by Zhao-Andy** [comment]
Hi @pldg, we currently only support crossposting via RSS. If you're transferring from markdown to our editors, the best way would be to copy and paste. If you have a lot of posts, then you might want to setup an RSS feed. Not sure if GitHub gists have an RSS feed that you might be able to use.

To crosspost via RSS, you can follow the steps in your RSS settings on dev.to: https://dev.to/settings/publishing-from-rss
