### ISSUE TITLE
Dev.to website  doesn't open in Safari

### ISSUE THREAD

**Issue by marcidenmark** [thepracticaldev/dev.to#2949]
I am on Mac on Mojave iOS on a laptop.

Site does open in Chrome.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by maestromac** [comment]
Hello @marcidenmark . What do you see when you navigate to `Dev.to`? Can you please share a screenshot with us?

**Comment by marcidenmark** [comment]
Hi maestromac. It is now working again.

**Comment by maestromac** [comment]
Glad to hear that!
