### ISSUE TITLE
Remove unused `_without_delay` methods

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#2950]
While asynchronous methods are being moved to separate Active Jobs (#1996, #2497), we keep `_without_delay` methods for a while, because the jobs that use this method can still exist at the moment of deploy.
But eventually, we need to delete them to declutter because most of them are not actively used in the codebase.
Some of these methods are used in the codebase explicitly. I suppose that it's worth to replace such calls with the `perform_now` job calls. But at least we should delete the unused methods.

**Comment by lightalloy** [comment]
This ticket is partially "blocked" by #1996, #2497 since they are not finished, but this work can be done gradually.

**Comment by donquxiote** [comment]
Hi! I see that the blocking issues have been closed out and would like to take this one if it's still available.

**Comment by lightalloy** [comment]
@donquxiote feel free to take it, it's available.

**Comment by araslanov-e** [comment]
@lightalloy Look it please https://github.com/thepracticaldev/dev.to/pull/4366

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/4366
