### ISSUE TITLE
Crtl + click should open a new browser tab on podcast page.

### ISSUE THREAD

**Issue by mandaputtra** [thepracticaldev/dev.to#2958]
**Describe the bug**
CTRL + Click should open a new tab on the browser, instead of stopping podcast first and then goes to the links.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'Podcast Page'
2. Play any podcast
3. If there any external links `crtl + click` (I use Linux and Windows I dunno what shortcut on Mac)

**Expected behaviour**
It should open a new browser tab, not an alert box

**Screenshots**
![this is what it looks like](https://user-images.githubusercontent.com/23342943/58371338-f797ca80-7f42-11e9-8a69-060171873786.png)

**Desktop (please complete the following information):**

- OS: Windows/Linux
- Browser: Chrome/Edge(the chromium version)/Firefox
- Version: Latest

**Additional context**
Actually, I still can right-click and go to open a new browser tab...

**Comment by jessleenyc** [comment]
@lightalloy just wanted to bring this to your attention!

**Comment by lightalloy** [comment]
Fixed by #3499
