### ISSUE TITLE
ctrl+0 on windows, hide the top menu bar instead of resuming windows to original zoom

### ISSUE THREAD

**Issue by andreanidouglas** [thepracticaldev/dev.to#2968]
**Describe the bug**
When trying to reset the page zoom level to 100%, the page hides the topmost taskbar instead of zooming in/out

**To Reproduce**
apply a different zoom level (ctrl+scroll wheel)
click ctrl+0 to return to zoom level 100%

**Screenshots**
![image](https://user-images.githubusercontent.com/684650/58418429-1ccd2b80-805e-11e9-8493-53352746b6b6.png)
![image](https://user-images.githubusercontent.com/684650/58418442-28b8ed80-805e-11e9-970d-241aa9703802.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 74

**Comment by rhymes** [comment]
Thanks for the bug report, solid find!

I think this has to with `0` that has been added as a global key to hide the topbar. It probably doesn't distinguish in the case of a modifier being present.

**Comment by nickytonline** [comment]
You'll probably need to check if the [event.metaKey](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey) is being pressed as well.

```
document.body.addEventListener('keydown', (event) => {
  console.log(`charCode = ${event.which} metaKey =  ${event.metaKey}`);
});
```

**Comment by nickytonline** [comment]
@rhymes, this would probably be a great first issue for someone looking to start contributing to the frontend codebase.

**Comment by rhymes** [comment]
@nickytonline my bad, I went ahead and fixed it :(
