### ISSUE TITLE
Can't install dependencies(Timber)

### ISSUE THREAD

**Issue by Nirajn2311** [thepracticaldev/dev.to#298]
### Current Behavior
When I run `bundle install` it installs all dependencies but it can't install msgpack 1.2.2(timber depends on it) as it says that msgpack require ruby version to be <2.5 and >=1.9 but in README we're supposed to install 2.5.1 . 
Could someone resolve this issue quickly as I am hyped and ready to solve issues for this repo.

### Mobile & Desktop Screenshots/Recordings
![screenshot 7](https://user-images.githubusercontent.com/36357875/43885039-ceef2f3c-9bc8-11e8-8175-5a9e5e30903d.png)

### Additional Info (device/browser, helpful links)
OS: Windows 10 1803(17134.191)
Ruby: ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]

**Comment by Zhao-Andy** [comment]
Hey there, looks like the error is saying `The current Ruby version is 2.5.0`, which doesn't match your `ruby -v` version. Are you using a Ruby manager like `rbenv` or `rvm`? If so, could you grab the Ruby version that your Ruby manager is using?

I _think_ what's happening is that `Ruby 2.5.0` is being used, and that's conflicting with the `msgpack` gem Ruby version requirements.

**Comment by Nirajn2311** [comment]
I am in Windows and I didn’t use rbenv and rvm.

**Comment by Zhao-Andy** [comment]
Gotcha, I'm not too familiar with Windows development. How did you install Ruby from the start? I'm guessing you used a Ruby version manager, but I could be wrong. 

I think what's happening is your `bundle` gem is running from a different Ruby version than the one your environment is using. See this thread for a related issue on macOS: https://dev.to/andy/comment/4icc

**Comment by rhymes** [comment]
@Nirajn2311 try `bundle update msgpack`, according to the Changelog msgpack to work on Ruby 2.5 in Windows needs to be at least at 1.2.3: https://github.com/msgpack/msgpack-ruby/blob/master/ChangeLog

**Comment by Nirajn2311** [comment]
@rhymes but the bundle will check it against the gemfile(msgpack version is 1.2.2 in the gemfile) and it won't allow it to pass.

**Comment by rhymes** [comment]
@Nirajn2311 not really, msgpack is only specified in the [Gemfile.lock](https://github.com/thepracticaldev/dev.to/blob/master/Gemfile.lock#L847) as `msgpack (~> 1.0)` which means that you can update it to anything with 1 as major version.

If I issue:

```shell
bundle update msgpack
```
it updates the Gemfile.lock like this:

```patch
diff --git a/Gemfile.lock b/Gemfile.lock
index 6746e84..73a8e8b 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -569,7 +569,7 @@ GEM
     minitest (5.11.3)
     momentjs-rails (2.17.1)
       railties (>= 3.1)
-    msgpack (1.2.2)
+    msgpack (1.2.4)
     multi_json (1.13.1)
     multi_xml (0.6.0)
     multipart-post (2.0.0)
```
You should do it and test if it works, then you can submit the PR ;-)

**Comment by Nirajn2311** [comment]
@rhymes well along with it even pg has same issue so if I run the above command it stops at pg.

**Comment by rhymes** [comment]
@Nirajn2311 unfortunately I don't have Windows so I can't help you bit I'm sure you can solve the installing issue! For every gem that blocks `bundle install` you can go to the website and check if there's a new version that fixes things, iterate until `bundle install` works.

For example, with `pg`, unfortunately the Gemfile is stuck to 0.21 and Ruby 2.5 + Windows is not supported with that version. If you look at the [Changelog](https://bitbucket.org/ged/ruby-pg/src/default/History.rdoc) you can see that there's a clear support for it at version 1.0: `Update Windows binary gems to Ruby-2.5`

So this time you should edit the Gemfile, put `~> 1.0` where pg is and update the gem.

It would be nice if you could work on all these issues until the app starts and then submit a PR to fix Windows + Ruby 2.5 installation issues.

**Comment by Nirajn2311** [comment]
UPDATE: stackprof won't install in windows so I commented it out in the gemfile.

**Comment by rhymes** [comment]
@Nirajn2311 use the latest one, 10.5 I think, you can use the installer from PostgreSQL website: https://www.postgresql.org/download/windows/

I opened an issue about specifying the version in the README https://github.com/thepracticaldev/dev.to/issues/319

stackprof won't definitely work on Windows, I think you can fix it by specifying the platform for which it works, bundler will ignore it if it's not the correct platform.

For example:

```ruby
gem "stackprof", "~> 0.2", require: false, platforms: :ruby
```

this should ignore Windows, check here for more details: https://bundler.io/man/gemfile.5.html#PLATFORMS

**Comment by Nirajn2311** [comment]
@rhymes Thx for your help, I got the gems installed but now I can't setup the db by bin/setup.
