### ISSUE TITLE
Invalid CodePen URL for usernames containing an underscore

### ISSUE THREAD

**Issue by GeorgeColdham** [thepracticaldev/dev.to#2981]
**Describe the bug**
When trying to create a new post which contains a CodePen link, the editor will state that the CodePen link is invalid if the username within the CodePen url provided contains an underscore.

**To Reproduce**

_Example users with underscores:_
https://codepen.io/George_1/
https://codepen.io/cobra_winfrey/

_Example urls with underscores:_
https://codepen.io/George_1/pen/jrBXPA
https://codepen.io/cobra_winfrey/pen/yXVMJP

_Example CodePen Dev.To links with underscores:_
`{% codepen https://codepen.io/cobra_winfrey/pen/yXVMJP %}`
`{% codepen https://codepen.io/George_1/pen/jrBXPA %}`

1. Create a new post
2. Populate the post as you would expect
3. Add a CodePen link to the post containing one of the example urls provided above or any pen from a user on CodePen with an underscore in the name
4. Try and preview the post
5. Try and save changes

**Expected behavior**
Upon preview I would expect to see a working preview of the post with a working CodePen.
Upon save changes I would expect my post to be saved as normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/21260083/58437696-04dbc300-80c3-11e9-8e57-2eab87d3d6b9.png)

**Desktop (please complete the following information):**

- OS: Arch Linux, up to date as of time of posting
- Browser: Chrome 
- Version: 73

**Comment by GeorgeColdham** [comment]
A quick hunt through the repo makes it seem like the issue is in [dev.to/app/liquid_tags/codepen_tag.rb : Line 50](https://github.com/thepracticaldev/dev.to/blob/b16fa4f8cc9f269a75751fc4379abf6ae92e5017/app/liquid_tags/codepen_tag.rb#L50)

**Comment by shindakun** [comment]
Yup should probably be `[a-zA-Z0-9_-]` to catch the underscore.

**Comment by GeorgeColdham** [comment]
Apologies, I’m on mobile and not in a position to make any changes. Thanks for confirming.

**Comment by Zhao-Andy** [comment]
Yep, as @shindakun said the regex prevents underscores. This is a great first issue for anyone interested in jumping on this.

**Comment by aturingmachine** [comment]
Hello, is it Ok if I pick this up?
