### ISSUE TITLE
Clipboard icon out of place

### ISSUE THREAD

**Issue by bolariin** [thepracticaldev/dev.to#2982]
**Describe the bug**
The clipboard icon used to copy an article link is below the input field in the dropdown share menu.

**To Reproduce**

1. Go to any article
2. Click on an dropdown-icon
3. See error

**Expected behavior**
I expected the clipboard icon to be on the same line as the input field with the link.

**Screenshots**
![Clipboard button displaced](https://user-images.githubusercontent.com/24629960/58441743-66476600-80b2-11e9-82a7-0004369bee07.png)

**Desktop (please complete the following information):**

- OS: Ubuntu (Elementary)
- Browser Chrome
- Version 74.0.3729.169

**Additional context**
I did not have this issue when I tried on firefox.

**Comment by felicianotech** [comment]
I'm seeing the reverse. On Ubuntu 19.04, in Chrome (v75) and Chromium (v74) the icon is in the correct place. On FireFox (v67) it's on the second line.
