### ISSUE TITLE
 my login page seems to be broken on and off

### ISSUE THREAD

**Issue by melezhik** [thepracticaldev/dev.to#2983]
Hi dev.to devs! my login page seems to be broken on and off, see the screen attached. I can see a black circle in the right upper corner, but it's not clickable, in normal state it should be clickable and shows me submenu with login/logout options.

Regards

![Снимок экрана от 2019-05-27 19-07-50](https://user-images.githubusercontent.com/988105/58442776-246aef80-80b3-11e9-9e46-c0f45dff6844.png)

**To Reproduce**

1. Open dev.to site in firefox browser
2. Try to log in
3. I can't log in because upper right menu is disabled for me. Just a black none clickable circle.

**Expected behavior**

There should be a circle which one if pressed shows submenu with login ( via github/twitter/ ... )

**Screenshots**

See the screenshot in the bug description in the beginning.

- OS: Centos7
- Browser firefox
- Version 60.6.0esr (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
I am not sure, but this happens on and off

**Comment by jessleenyc** [comment]
Thanks for flagging. I think you might be experiencing the same issue here: https://github.com/thepracticaldev/dev.to/issues/2790

Will keep you posted when it's fixed.

**Comment by jessleenyc** [comment]
@melezhik are you still experiencing this? the other issue is fixed.

**Comment by melezhik** [comment]
Hi Jess. I believe it's fixed now. Thank you!


On Aug 7, 2019 7:11 PM, "Jess Lee" <notifications@github.com> wrote:

@melezhik <https://github.com/melezhik> are you still experiencing this?
the other issue is fixed.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/thepracticaldev/dev.to/issues/2983?email_source=notifications&email_token=AAHRHSLU2RTDP3J2WW3NSV3QDNQDZA5CNFSM4HP63PM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD32BNTI#issuecomment-519313101>,
or mute the thread

**Comment by jessleenyc** [comment]
Great! Closing.

**Comment by melezhik** [comment]
Issue appeared again, few days ago, the same symptoms, the same environment

**Comment by melezhik** [comment]
https://github.com/thepracticaldev/dev.to/issues/4280
