### ISSUE TITLE
Podcast is not playing in the browser 

### ISSUE THREAD

**Issue by amirition** [thepracticaldev/dev.to#2986]
**Describe the bug**
The podcasts are not playing in the browser. When I click on the play button of the podcast, nothing happens and it shows a console error. 

**To Reproduce**

1. Go to a single podcast page like this: https://dev.to/freelancers/tfs-329-career-development
2. Click on the play section of the podcast
3. Open your developer tools and its console. 
4. See 2 errors with same message: Uncaught ReferenceError: initializePodcastPlayback is not defined

**Desktop:**

- OS: Windows 10 
- Browser Chrome 
- Version 74

**Comment by jessleenyc** [comment]
Thanks for flagging this - we're working to improve the podcast section overall. https://github.com/thepracticaldev/dev.to/issues/2952

cc @lightalloy

**Comment by lightalloy** [comment]
@amirition I've made several changes to the podcasts fetching logic. Could you check if the problem persists?

**Comment by lightalloy** [comment]
This should work, I'm closing the issue for now. Please, reopen if the problem persists.
