### ISSUE TITLE
Progress Bar in PWA

### ISSUE THREAD

**Issue by RJ-1998** [thepracticaldev/dev.to#2987]
**Problem**
When we click a link on Dev.to PWA on Android smartphone the requested link loads without showing any kind of loading animation (Spinner or Progress Bar etc.) which results in a bad user experience. Similar is the case with Deaktop application.

**Solution**
Use [NProgress](https://github.com/rstacruz/nprogress) library to resolve such kind of issue. NProgress greatly blends with React applications.

**Comment by jessleenyc** [comment]
We're open to ideas here if anyone wants to submit something for this.

**Comment by maestromac** [comment]
It's been a minute but we have a progress bar now that works on the PWA and desktop.
