### ISSUE TITLE
Add Dockerfile 

### ISSUE THREAD

**Issue by domcorvasce** [thepracticaldev/dev.to#299]
## Feature Request or Task

Add a Dockerfile (and maybe a docker-compose.yml) to allow contributors to set up a development environment using Docker.

### User Story / Description

It'd be useful to have a Dockerfile ready-to-use on the repository for contributors, especially for early contributors who needs to set-up not only Ruby, but also PostgreSQL, NodeJS and all the required dependencies.

### Definition of Done

The repo includes a Dockerfile (and maybe a docker-compose.yml) so contributors can easily set-up their development environment using Docker.

### Update

Looks like someone is working on it:  see #296.

**Comment by bdod** [comment]
Take this ! ))

**Comment by bdod** [comment]
Maybe ) I'm look at this after finishing with this ... I'm always glad add something to docker )

**Comment by bdod** [comment]
@rhymes  hmm i'm look at his MR and don't know , I'm trying to do my MR without interfering with the code or settings but he take some another way ... i'm already did my MR, check it
