### ISSUE TITLE
Inconsistent API usage of "tags" and "tag_list"

### ISSUE THREAD

**Issue by Turnerj** [thepracticaldev/dev.to#2996]
In #2844, `tags` was added as a property to the Articles API when requesting an individual article to rectify a problem I raised in #2040 however while this change looks right, it actually made the API just as inconsistent (I didn't notice this when I commented on that PR).

When you request an article directly (https://dev.to/api/articles/5) you have `tag_list` (which is a comma-separated string) and `tags` which is an array. When you request articles (https://dev.to/api/articles), `tag_list` is an array and `tags` is no where to be found.

Can the API be updated to standardise these like my previous PR in #2040?

**Comment by rhymes** [comment]
Great catch @Turnerj - I'll discuss it with the team and let you know. I agree that there should be consistency between the two representation as in there should be just one type of representation for the article resource

**Comment by Turnerj** [comment]
No problem - I just merged a change in my API client for C# and realised it didn't work after your PR went through. I dug around to realise what happened. 🙂

**Comment by jessleenyc** [comment]
@rhymes since you're on vaca, just wanted to give you a heads up that we briefly chatted about this in tech meeting and concluded that you and ben should just sync on this together.

**Comment by rhymes** [comment]
Hi @Turnerj, we've decided to table this for a while because we don't necessarily want to break client code (which might also be the DEV website). Since changing the data type is indeed a breaking change, we might postpone this to a future API v1. 

In the meantime we could make a note of all incosistencies to at least have them documented :-)

**Comment by Turnerj** [comment]
If it helps, I did actually look into this previously for #2040 ([comment](https://github.com/thepracticaldev/dev.to/pull/2040#issuecomment-472238352)) where I found only one reference used in chat.

The API call
https://github.com/thepracticaldev/dev.to/blob/a9254eac407baf71a781fb94759b296f2fdedcdd/app/javascript/chat/chat.jsx#L527-L535

The control it seems to render
https://github.com/thepracticaldev/dev.to/blob/60d38ef787b45b8bc7404927879d9561229818ab/app/javascript/chat/article.jsx

**Comment by Turnerj** [comment]
I'm not sure if it is worth adding to this (as it is an inconsistency, just not specific to tags) or filing it separately but there seems to be even a greater drift between the data returned for the two different article APIs (whether you request a single article or view the list).

"ArticleShow" includes the following which don't match up to "ArticleIndex":
- readable_publish_date
- social_image
- the "tags" vs "tag_list" stuff I mentioned in this issue
- comments_count
- created_at
- edited_at
- crossposted_at
- last_comment_at
- body_html
- body_markdown

"ArticleIndex" includes the following which don't match up to "ArticleShow":
- published_timestamp (Note: Technically this field should the "crossposted_at" OR "published_at" if the API doc is right though still redundant if "crossposted_at" was there instead)
- organization
- flare_tag

I could completely understand the "body_html" and "body_markdown" fields wouldn't be on the "ArticleIndex" endpoint as that could be a ton of unnecessary data transferred though every other field feels like fair game to be in both APIs.

I know the last time we talked about just the tag stuff, there is concern with breaking existing functionality and that is a fair point. I feel though the longer these inconsistencies exist, the higher the chance that more code will depend on the inconsistencies.

I'm happy to help do this and raise a PR with the various changes etc happening (though not being a Ruby developer, I'd still be winging it quite a bit). I personally just want to get the ball rolling to remove this technical debt sooner rather than later.

**Comment by rhymes** [comment]
@Turnerj I've upgraded it to an issue https://github.com/thepracticaldev/dev.to/issues/4206 :-)

**Comment by rhymes** [comment]
@Turnerj I'm also going to close this because the Articles API is currently documented at https://docs.dev.to/api/ and we don't plan to change the format of either `tags` or `tag_list` anytime soon (it's always unfortunate when a bug becomes a feature). 

Thanks for refreshing our memory about this and we'll definitely keep it in mind.
