### ISSUE TITLE
Update timestamp on notifications

### ISSUE THREAD

**Issue by ClaraMorgen** [thepracticaldev/dev.to#2997]
**Describe the bug**
I openend my notifications this morning and found a post which apparently was created just 8 minutes ago, but know it's older, because I read it yesterday night already.
When I click on the post it also says it's from yesterday.

**To Reproduce**

1. Go to https://dev.to/notifications
2. See post with timestamp "xx made a new post 6 minutes ago"
3. Go to the post and see that it is older.

**Expected behavior**
It should put the duration from when it was actually created.

**Screenshots**
<img width="628" alt="Screenshot 2019-05-29 at 08 39 41" src="https://user-images.githubusercontent.com/29435293/58532295-c0991180-81ed-11e9-8ec8-e7f3d50ec2f4.png">
I looked at it at 29.05.2019 08:43 (GMT+3)
However on the post is says it was created on 28.05.2019.

**Desktop (please complete the following information):**

- OS: MacOS Mojave
- Browser: firefox 
- Version: 67

**Comment by Glennmen** [comment]
That is not the time that the article is created but when the notification was created 😉

https://github.com/thepracticaldev/dev.to/blob/879864a9bb8757dfa6a3c91a14a82156fee43436/app/views/notifications/_article.html.erb#L34

**Comment by ClaraMorgen** [comment]
@Glennmen I guessed so, but is this the expected behaviour? I found it confusing...

**Comment by Glennmen** [comment]
@ClaraMorgen I understand what you are saying and indeed directly like that under stand the first sentence it is confusing.
Here is the original issue discussion about adding the time on notifications: https://github.com/thepracticaldev/dev.to/issues/2010
Looking at the comments there wasn't a discussion about style/placement, but only about the functionality.

**Comment by aspittel** [comment]
Hey @ClaraMorgen, thanks for bringing this up! We'll discuss as a team and get back to you!

**Comment by jessleenyc** [comment]
Hey all -- just updated the title of this issue.  Instead of showing when the notification was created, we should show when the item was published.

**Comment by ClaraMorgen** [comment]
Cool :) I can have a look and change it :)

**Comment by jessleenyc** [comment]
@ClaraMorgen awesome!
