### ISSUE TITLE
Localised Date formats needed

### ISSUE THREAD

**Issue by RossWilliams** [thepracticaldev/dev.to#3]
The podcast page uses a short date string. The short date string is not formatted for my locale. I am sending "Accept-Language:en-GB,en;q=0.8" as a header, but the dates returned are "12/09/2016" for the date 09 December 2016.

Date formatting should be localised to avoid confusion.

**Comment by benhalpern** [comment]
Thanks a lot for bringing this to our attention.

**Comment by jessleenyc** [comment]
Talk to fastly so it runs through the cdn
