### ISSUE TITLE
Horizontal Lines will not render - content above is hidden

### ISSUE THREAD

**Issue by Administrate-GregBrimble** [thepracticaldev/dev.to#30]
Any post with a `---` in the content will not generate a horizontal line

---

when published.

It is rendered fine in the "Preview", but when saved and viewed natively, any content above the `---` is hidden from view.

**Comment by jessleenyc** [comment]
@Administrate-GregBrimble thanks for the heads up -- closing issue because it's a duplicate of https://github.com/thepracticaldev/dev.to/issues/5
