### ISSUE TITLE
Ensure each post in a series reflects latest changes

### ISSUE THREAD

**Issue by pkfrank** [thepracticaldev/dev.to#3003]
**Describe the bug**
After adding a new post to the series, a previous post has not updated the "index" of the series at the top of the article.  Probably caching related.

**Expected behavior**
All posts in a series are in sync as it relates to the navigation at the top.

**Screenshots**
![example of issue](https://cl.ly/159e587c68ca/Screen%20Recording%202019-05-29%20at%2011.44%20AM.gif)

**Comment by edisonywh** [comment]
I have a "fix" for this, putting it in quotation mark because I don't really know how to test it, and also a couple of notes/caveats there. Would appreciate pointers!
