### ISSUE TITLE
Unable to upload profile image in android mobile app

### ISSUE THREAD

**Issue by dev-arjunan** [thepracticaldev/dev.to#3013]
**Describe the bug**
I'm unable to upload new profile image from android app.

**To Reproduce**

1. Go to 'top right corner and tap on profile'
2. Click on 'settings'
3. Scroll down to 'Profile Image section'
4. Tap on "Upload" button

**Expected behavior**
It should open up window to choose image from gallery

**Screenshots**
![Screenshot_2019-05-31-19-29-41-697_to dev dev_android](https://user-images.githubusercontent.com/50161510/58711178-8c834380-83db-11e9-9bae-c61f09280740.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: [Redmi note 6 pro]
- OS: [Android Oreo 8.1.0]
- App: Latest version

**Additional context**
Add any other context about the problem or helpful links here.

**Comment by maestromac** [comment]
Issue moved to [thepracticaldev/DEV-Android #32](https://github.com/thepracticaldev/DEV-Android/issues/32) via [**ZenHub**](https://www.zenhub.com/)

**Comment by maestromac** [comment]
Issue moved to [thepracticaldev/DEV-Android #31](https://github.com/thepracticaldev/DEV-Android/issues/31) via [**ZenHub**](https://www.zenhub.com/)
