### ISSUE TITLE
Reading time estimate does not match for a particular post

### ISSUE THREAD

**Issue by ayush-sharma** [thepracticaldev/dev.to#3024]
Reading time estimate for a post insert does not match the one in the main post.

1. Go to https://dev.to/devteam/medium-was-never-meant-to-be-a-part-of-the-developer-ecosystem-25a0.
2. Scroll down to insert for "What are you "old enough to remember" in software development?"
3. It says "0 min read."
4. On main page of that post, it says "1 min read".
5. Both should be "1 min read".

- OS: Windows 10
- Browser: Firefox
- Version: 67 (64-bit)

![Annotation 2019-06-03 200334](https://user-images.githubusercontent.com/9398523/58810514-b470e200-863b-11e9-9354-99036f58f895.jpg)
![Annotation 2019-06-03 200353](https://user-images.githubusercontent.com/9398523/58810516-b470e200-863b-11e9-818c-61d2a244180c.jpg)

**Comment by jessleenyc** [comment]
This is likely because we have a minimum reading time of 1 minute on articles but not on the article liquid tag.

**Comment by jrsam** [comment]
Hi, I would like to work on this.

**Comment by jessleenyc** [comment]
@jrsam go for it!

**Comment by akshayymahajan** [comment]
Fixes issue #3217
