### ISSUE TITLE
Reading List - time appear only for the first 3 items

### ISSUE THREAD

**Issue by giventofly** [thepracticaldev/dev.to#3025]
**Describe the bug**
On the reading list page after the first 3 items the reading doesn't appear.

**To Reproduce**
https://dev.to/readinglist

**Expected behavior**
Appear the reading time on all items

**Screenshots**
![Screenshot_2019-06-03 Reading List - The DEV Community](https://user-images.githubusercontent.com/6298937/58814437-9b593880-861d-11e9-90e5-3dc04e0d88fd.png)

**Comment by benhalpern** [comment]
Reading list items need to be re-indexed. I think I made a mistake with this that I didn't realize. Will resolve today.

**Comment by maestromac** [comment]
Resolved. We've re-indexed all those article's read time.
