### ISSUE TITLE
Increase tag length limit from 20 to 30 characters

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/dev.to#3035]
As requested in this thread:

https://dev.to/rodolfomendes/could-dev-to-allow-larger-tag-names-3p2e

I think we limit the length for aesthetic purposes but it isn't that important. The freedom of more characters would trip people up less often.

Find this line and change the number, and adjust the adjacent spec:

```ruby
      errors.add(:tag, "\"#{tag}\" is too long (maximum is 20 characters)") if tag.length > 20
```

Et voila!

**Comment by brunotoral** [comment]
@benhalpern  I would like to git this one a try.

**Comment by jessleenyc** [comment]
@brunotoral go for it!

**Comment by tannakartikey** [comment]
@benhalpern can we please have a `ruby` label here? There are hardly any tickets appear when the tag is searched although there are many tickets which include the back-end related work.

**Comment by jeduardo824** [comment]
@brunotoral Are you working on this? I want to take it if you don't.

**Comment by jeduardo824** [comment]
@benhalpern I'm not able to find any specs which test the tag length. Can you give me a clue?

**Comment by rhymes** [comment]
@jeduardo824 I don't think there's a specific test for the length, but you can add it here:

https://github.com/thepracticaldev/dev.to/blob/e46bd26223847e35b9de2cd57380bad12a97286f/spec/models/article_spec.rb#L172-L185

You might want to also increase the `cached_tag_list` length a bit: https://github.com/thepracticaldev/dev.to/blob/master/spec/models/article_spec.rb#L19

**Comment by jeduardo824** [comment]
> @jeduardo824 I don't think there's a specific test for the length, but you can add it here:
> 
> https://github.com/thepracticaldev/dev.to/blob/e46bd26223847e35b9de2cd57380bad12a97286f/spec/models/article_spec.rb#L172-L185
> 
> You might want to also increase the `cached_tag_list` length a bit: https://github.com/thepracticaldev/dev.to/blob/master/spec/models/article_spec.rb#L19

Awesome. I will send a PR until tomorrow.

**Comment by jeduardo824** [comment]
> @jeduardo824 I don't think there's a specific test for the length, but you can add it here:
> 
> https://github.com/thepracticaldev/dev.to/blob/e46bd26223847e35b9de2cd57380bad12a97286f/spec/models/article_spec.rb#L172-L185
> 
> You might want to also increase the `cached_tag_list` length a bit: https://github.com/thepracticaldev/dev.to/blob/master/spec/models/article_spec.rb#L19

What do you think about 126 characters for the `cached_tag_list`?

**Comment by rhymes** [comment]
@jeduardo824 I don't know exactly how the arbitrary length was set in the original version, so I think it should be fine, especially if we have a maximum of 4 tags that could potentially all be 30 chars long. Worst case scenario should be: 30x4 plus 3 commas and 3 spaces. So 126 ;-)

**Comment by jeduardo824** [comment]
Ok, I'll send a PR soon.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/3299
