### ISSUE TITLE
Add Bug Bounty / Security into to readme + console

### ISSUE THREAD

**Issue by pkfrank** [thepracticaldev/dev.to#3042]
**Is your feature request related to a problem? Please describe.**
As an admin, I want to ensure that the community knows how to ethically report bugs and security vulnerabilities.  Basically, I want everyone to know about https://dev.to/security

**Describe the solution you'd like**
Add this information to:
- The Repo Readme
- The docs.dev.to page
- Console

**Additional context**
h/t @Zhao-Andy who originally brought this up.

**Comment by desirottman** [comment]
@pkfrank hey! where in the console were you looking at adding it? I was thinking on the contact page of the site? let me know, I'd like to give it a try!

**Comment by Zhao-Andy** [comment]
Hey @desirottman, you can tack it onto: https://github.com/thepracticaldev/dev.to/blob/master/app/assets/javascripts/hello-dev.js :)

The contact page is probably a good spot to add it, too!

**Comment by pkfrank** [comment]
Yup, totally agreed with @Zhao-Andy 👍

**Comment by maestromac** [comment]
Resolved!
