### ISSUE TITLE
Fastly 502 errors

### ISSUE THREAD

**Issue by shindakun** [thepracticaldev/dev.to#3047]
**Describe the bug**
Currently, I'm seeing a few images not load due to Fastly 502's.

**To Reproduce**

1. Go to https://dev.to/shindakun/working-on-a-new-flow-1akn ;)
2. Note that some icons/images don't load, see the image below.

![Screen Shot 2019-06-04 at 10 23 51 PM](https://user-images.githubusercontent.com/319128/58932256-e9eafd80-8717-11e9-9fe7-71ad7f8a5bce.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by maestromac** [comment]
Thanks for reporting this @shindakun . Are you still seeing this?

**Comment by shindakun** [comment]
@maestromac nope all looks good now. I'm gonna chalk it up to a temporarily fastly issue. 🤷‍♂️
