### ISSUE TITLE
Action space buttons "manage" and "edit"  not inline on mobile

### ISSUE THREAD

**Issue by ikey2244** [thepracticaldev/dev.to#3061]
**Describe the bug**
The action space buttons "manage" and "edit" would work better if they were inline on mobile.

**To Reproduce**

1. Open dev.to in safari
2. Click user picture
3. Click "dashboard"
4. Click on one of your posts
5. See the action buttons at the top

**Expected behavior**
The action buttons would drop under the username and would be inline.

**Screenshots**
![image](https://user-images.githubusercontent.com/18132846/59044663-29166d00-8844-11e9-885e-e3c7d3655d01.png)

- Device: Iphone XS
- OS: iOS12.3.1
- Browser safari
- Version 12

**Comment by Zhao-Andy** [comment]
Thanks for the heads up! This is approved if anyone wants to work on it. The two buttons are wrapped in a `<span>` already, and adding `display: inline-block` to the relevant CSS should fix it.

**Comment by bdlb77** [comment]
Hey @Zhao-Andy ! Do you mind if I take this issue? :)

**Comment by Zhao-Andy** [comment]
@bdlb77 all yours!

**Comment by bdlb77** [comment]
yay! thank you! I'll be back at it after the holiday 😎

**Comment by ikey2244** [comment]
I don’t think it’s as simple as just setting displaying: inline-block. The Elements don’t have enough room to drop to the next line. So I think you could change the padding and that might fix it.
