### ISSUE TITLE
Editing older post metadata won't allow save.

### ISSUE THREAD

**Issue by rpalo** [thepracticaldev/dev.to#3073]
**Describe the bug**

I am trying to update the metadata for [one of my older posts](https://dev.to/rpalo/vue-on-django-part-2).  Trying to add `series: Vue on Django` and `canonical_url: https://www.assertnotmagic.com/2017/06/24/vue-on-django-part-2/`.  The edit page won't allow a save and shows this error message:

![image](https://user-images.githubusercontent.com/14909201/59116579-c0d99100-8900-11e9-8de1-6a36a7d426b4.png)

**To Reproduce**

1. Go to post page.
2. Click edit post. (V1 editor.  I love plain text files editing too much to use the V2 editor.)
3. Add `canonical_url: https://www.assertnotmagic.com/2017/06/24/vue-on-django-part-2/` to metadata.
4. Click save.
5. ERROR.
6. Remove `canonical_url` line.
7. Add `series: Vue on Django` to metadata.
8. Click save.
9. ERROR.
10. Remove `series` line.  File is now exactly the same as it was when I started.
11. Click save.
12. ERROR.

**Expected behavior**

I expect to edit the metadata, save, and have it update.  Weirdly, it worked OK on Vue on Django Part 1 (and all my posts older than that) just fine.
**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Google Chrome
- Version: Version 74.0.3729.169

**Additional context**

**Comment by Zhao-Andy** [comment]
Hmm that's a pretty strange bug. I'm not really sure what's going on there. For now, I updated your post's `main_image_background_hex_color` to `#dddddd` (like a light gray) which is our default.

For whatever reason, it was `#100100100`, which I have no idea what that's about.

**Comment by rpalo** [comment]
Cool, thanks!  I went through and added canonicals to all of my posts, and the only other posts that bonked were the other Vue on Django posts (from the same series).  Everything else, older and newer, worked just fine.

**Comment by jessleenyc** [comment]
Going to close this since Andy was able to update manually. Can open back up if there are more reports.

**Comment by michaelneu** [comment]
I just ran into this with my [first post](https://dev.to/michaelneu/to-vba-and-beyond---building-a-restful-backend-using-plain-microsoft-excel-macros-76n). Any chance you could fix it there, too? I wanted to add `series: Webxcel`, but since I can't save it, it won't be picked up (repro steps are the same as for @rpalo).

**Comment by maestromac** [comment]
Hello @michaelneu 

I just updated your article's `main_image_background_hex_color` to `#dddddd`. Let me know if you are still experiencing the issue
