### ISSUE TITLE
Settings ➔ Organization shows "500 error"

### ISSUE THREAD

**Issue by darrarski** [thepracticaldev/dev.to#3077]
**Describe the bug**

When I am logged in and go to [Settings ➔ Organization](https://dev.to/settings/organization) I get "500 error" page.

**To Reproduce**

Not sure what caused the problem. I recently became an admin of an organization. Then, the previous admin was removed from this organization. Now, I am the only admin of the organization. Unfortunately, the bug making it not possible to manage the organization members, admins or other settings.

**Expected behavior**

As an admin, I should be able to manage the organization, its members and other settings.

**Screenshots**

![Screenshot 2019-06-08 at 14 36 02](https://user-images.githubusercontent.com/1384684/59147371-d7641300-89fa-11e9-9fc7-99a115a54004.png)

**Desktop:**

- OS: macOS 10.14.5
- Browser: Safari 12.1.1

**Additional context**

My account on dev.to: https://dev.to/darrarski
The organization on dev.to: https://dev.to/elpassion

**Comment by jessleenyc** [comment]
Thanks for flagging, we'll take a look at this ASAP.

**Comment by Zhao-Andy** [comment]
Hey @darrarski, could you try visiting your organization settings now? Looks like it was a run time error.

**Comment by darrarski** [comment]
Yes! It works! Thanks for your support. I am closing the issue.
