### ISSUE TITLE
Bug: revoking an acess token resulting in a 404

### ISSUE THREAD

**Issue by timdeschryver** [thepracticaldev/dev.to#3079]
**Describe the bug**

Revoking an access token results in a 404

**To Reproduce**

1. Create an access token on https://dev.to/settings/account
2. Revoke the token 

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/28659384/59150574-05ab1800-8a26-11e9-80f8-d2e5acafae9a.png)

**Desktop (please complete the following information):**

- OS:Windows 10
- Browser: Chrome
- Version: Canary

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

Thanks for the great platform

**Comment by rhymes** [comment]
@timdeschryver the issue should be fixed now, I tested it on my account as well. Let me know if it doesn't work for you. Thanks!

**Comment by timdeschryver** [comment]
I verified that this does indeed work now, thanks!
