### ISSUE TITLE
Dark and Pink 

### ISSUE THREAD

**Issue by ShalokShalom** [thepracticaldev/dev.to#3080]
Currently, the selection between the dark and the pink mode is switched. 
This happens on my Firefox at the desktop. 
Pink leads into dark, dark into pink. How evil :stuck_out_tongue_winking_eye:

**Comment by maestromac** [comment]
Thanks for this issue @ShalokShalom . Can you verify that it is still happening? I can't seem to reproduce it on FF 68.0b9.

**Comment by ShalokShalom** [comment]
Works with a private window. So potentially an add on issue.

**Comment by maestromac** [comment]
Thanks for verifying @ShalokShalom !
