### ISSUE TITLE
Site broken on waterfox

### ISSUE THREAD

**Issue by c33s** [thepracticaldev/dev.to#3081]
**Describe the bug**
- timeline is not loaded
- "my account" button is not accessible (clicking on it does nothing)
- "my account" image is not shown
- connect page is empty

**To Reproduce**
1. install waterfox https://www.waterfox.net/
2. go to dev.to
3. login
4. press on your account image

**Expected behavior**

**Screenshots**
![2019-06-09 00_38_34- #  DEV Community 👩‍💻👨‍💻 - Waterfox  #](https://user-images.githubusercontent.com/649209/59152958-6438bc00-8a4f-11e9-8491-dbcbb7a4384e.png)

**Desktop (please complete the following information):**

- OS: win7
- Browser: waterfox
- Version: version (56.2.10.1)

**Additional context**
- created a new profile with no addons

**Comment by maestromac** [comment]
Thanks for reporting this! Looks like our `Webcomponent-loader.js` is the cause of this error

**Comment by maestromac** [comment]
Hello @c33s can you help me check if this is resolved?

**Comment by maestromac** [comment]
I've tested this thoroughly and it seems to be working now. Let me know if otherwise!!

**Comment by c33s** [comment]
@maestromac yes it works again. thanks
