### ISSUE TITLE
Image uploader button on comment forms jumps up once a file is selected

### ISSUE THREAD

**Issue by nickytonline** [thepracticaldev/dev.to#3085]
**Describe the bug**

The UI moves or covers other UI (in the case of mobile) when an image is selected to be added to a comment.

**To Reproduce**

1. Go to any post and click on the image upload button of a comment.
1. Select a file for upload.
1. The file gets uploaded.
1. The text input that contains the URL of the newly uploaded image appears causing the image upload button to move up (desktop) or covers other UI (mobile).

**Expected behavior**

The UI should not shift or cover other UI.

**Screenshots**

![bug_image_upload](https://user-images.githubusercontent.com/833231/59158795-f2cc2e00-8a8d-11e9-985e-40547aea514d.png)

![mobile_image_upload_error](https://user-images.githubusercontent.com/833231/59158834-8271dc80-8a8e-11e9-8fc8-9317921f2212.png)

**Desktop (please complete the following information):**

- OS: macOS 10.14.5
- Browser: FireFox, Chrome, Safari
- Version: latest

**Smartphone (please complete the following information):**

- Device: iPhone 6 SE
- OS: iOS
- Browser: Brave
- Version: not sure

**Additional context**

**Comment by nickytonline** [comment]
I have a PR coming up later today tomorrow for this that fixes the desktop issue, but I still need to look into the mobile issue. The refactor in #3082 came about because of this issue.

**Comment by nickytonline** [comment]
Although it looks like an easy fix, it was a little more complicated. A lot ofthe comment form had elements using `position: absolute` with a lot of `calc(...)` in the CSS. I opted to go for Flexbox, that ends up reducing the amount of CSS and makes it easier to make changes to the form.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/3086
