### ISSUE TITLE
Reading list: add pagination or infinite scroll

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#3122]
**Is your feature request related to a problem? Please describe.**

Right now the reading list only displays the latest 64 items. If a user has more they can't access the other items until they've unsaved or archived "N - 64" articles.

See https://github.com/thepracticaldev/dev.to/blob/master/app/javascript/readingList/readingList.jsx#L24

**Describe the solution you'd like**

Either have a "Load more" button like listings have to load other items, or have infinite scrolling based pagination

**Comment by jessleenyc** [comment]
Notes from tech meeting:
- A 'load more' button will be easier than pagination int his context because the way we navigate within pages makes it complicated to reset listeners.

**Comment by bellsenawat** [comment]
Can I work on it :)

**Comment by rhymes** [comment]
Hi @bellsenawat it's all yours, thank you! Please provide screenshots along with the code

**Comment by bellsenawat** [comment]
I have a question 
"Load More" button should apply to only Reading list or including Archive page
@rhymes

**Comment by rhymes** [comment]
@bellsenawat it should actually apply to any view, tags filters included

**Comment by bolariin** [comment]
I think this issue has been resolved

**Comment by rhymes** [comment]
Closed by https://github.com/thepracticaldev/dev.to/pull/3221
