### ISSUE TITLE
Reading list: add number of items in the header

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#3124]
**Is your feature request related to a problem? Please describe.**

From the homepage it is possible to see how many items there are in the reading list.
Once inside https://dev.to/readinglist that information is not accessible

**Describe the solution you'd like**

Add the number of articles in the title.

From the current

![Screenshot_2019-06-11 Reading List - The DEV Community](https://user-images.githubusercontent.com/146201/59270499-eb558200-8c51-11e9-8f57-f8b04962fdfc.png)

to something like 

![Screenshot_2019-06-11 Reading List - The DEV Community copy](https://user-images.githubusercontent.com/146201/59270511-f14b6300-8c51-11e9-8ae1-4e1cc77da8fd.png)

**Additional context**

This number has to update anytime an item is removed or archived I guess

**Comment by andrewrod33** [comment]
Currently, the home page shows the total amount of all articles (including Archived). Would this show that number or only the non-archived count?

**Comment by rhymes** [comment]
@andrewrod33 good point, I think it should list the number of non archived, and then in the https://dev.to/readinglist/archive page it should show the number of archived posts

**Comment by bolariin** [comment]
if there are no items in the reading list would the count be absent or zero?

**Comment by rhymes** [comment]
@bolariin good question. I'd replicate the logic for the reading list count of the homepage:

https://github.com/thepracticaldev/dev.to/blob/7f2045b25004e771e26112e9b3d08992b3af3245/app/assets/javascripts/initializers/initializeReadingListIcons.js#L32-L43

which seems to be: `(empty)` or `(15)` for example
