### ISSUE TITLE
Hot key toggle for article preview

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#3129]
**Is your feature request related to a problem? Please describe.**
As a user, I'd like a hotkey that toggles the article preview when I'm writing a post so I don't have to manually click back and forth.

**Comment by sashadev-sky** [comment]
@jessleenyc can I work on this one? :)

**Comment by jessleenyc** [comment]
@sashadev-sky go for it!

**Comment by Elecweb** [comment]
@jessleenyc Could I implement this one ? which key you prefer for switching ? maybe <kbd>⌘</kbd> + <kbd>p</kbd> ?

**Comment by maestromac** [comment]
Yeah that's a good idea @Elecweb .
