### ISSUE TITLE
Provide Ability to Opt Out of Displaying GitHub or Twitter icon on Profile/Name/Comments

### ISSUE THREAD

**Issue by michael-tharrington** [thepracticaldev/dev.to#3134]
**Is your feature request related to a problem? Please describe.**
A user wrote in asking if it was possible to opt out of having their GitHub link shown up next to their comments. They signed up via GitHub, but don't necessarily want their GitHub shown publicly. This option would give them more privacy.

**Describe the solution you'd like**
We could add inputs specific to Twitter and GitHub under "Links" in the profile section of [https://dev.to/settings](https://dev.to/settings). I'm thinking it'd be good to fill these in by default if the user signs up via one or both. However, the user could then easily visit their settings and remove what links are visible so that GH and Twitter icons could be removed.

**Describe alternatives you've considered**
We could do the same as above but not fill in the GitHub/Twitter inputs by default. However, I think that generally these are quite nice to have, so I prefer the idea of filling them in by default.

**Comment by jessleenyc** [comment]
One of the reasons why we require twitter or github auth (and don't support email login) is to prevent anonymity and increase accountability. Always happy to (and think we should) re-visit this idea.

**Comment by jessleenyc** [comment]
We're still holding this perspective so I'm going to close this issue for now.
