### ISSUE TITLE
Ability to moderate users from their profile page

### ISSUE THREAD

**Issue by noahsscott** [thepracticaldev/dev.to#3137]
**Is your feature request related to a problem? Please describe.**
With the recent occurrence of spam (see [issue #3091](https://github.com/thepracticaldev/dev.to/issues/3091)) it would be useful to have the ability to flag or ban users from their profile page. This would save time marking individual posts if an account is responsible for more than one spam-like post and/or is clearly a spam account. 

**Describe the solution you'd like**
A button or icon to flag an account - visible to everyone, and another to ban - visible for moderators and above (depending on how people feel about moderators having this ability). Once marked, the user would choose a reason for why the account has been flagged or banned, with a field to provide further context for admins similar to the [report page](https://dev.to/report-abuse) but perhaps wrapped in a modal? I can provide a mock-up  if helpful. 

**Describe alternatives you've considered**
None, as the described actions of flagging or banning users are common-place among online communities.

**Additional context**
After finding many spam posts on the latest feed I sent a list of the offending accounts to a dev.to admin, Michael, who pointed me to [issue #3091](https://github.com/thepracticaldev/dev.to/issues/3091) and the suggested improvements seem like they would prevent similar activity in the future. But in the case that spam accounts still get through it would save time if all users could flag accounts, and moderators could ban these accounts. I'm aware of the report page as I mentioned above, but having direct options of flagging or banning users from the profile page feels more appropriate given the actions that would be required anyway to moderate an account once it had started posting spam.

**Comment by michael-tharrington** [comment]
Just to point out that this issue here seems quite similar to this issue - https://github.com/thepracticaldev/dev.to/issues/398. Sorry I didn't notice this when I was speaking with you previously @noahsscott!

**Comment by jessleenyc** [comment]
I'm actually going to close this one in favor of the original issue since that one has some more detail on it. You can follow along here: https://github.com/thepracticaldev/dev.to/issues/398
