### ISSUE TITLE
The editor removes meta upon booting

### ISSUE THREAD

**Issue by Merri** [thepracticaldev/dev.to#3138]
**Describe the bug**
I've been working with one article for about a week now. Yesterday I added an organization and moved the article to the organization. Later on I noticed upon loading the article for editing that it was missing all the meta information. The editor only contains the article text. I can see the metadata flashing before the editor boots, but it disappears after boot (as buttons appear in bottom). In addition to this the editor shows **New changes (clear)** in the bottom all the time.

Also if I go to settings and change between v1 and v2 version of the editor I see no change happening to the editor. I never touched the setting before but the editor changed to something visually different on it's own a week or two ago.

So far I've noticed that if I open private (Firefox or Chrome) and login there the editor works as it should, so it also seems to be linked to session somehow.

**To Reproduce**

I have not seen the trouble to see if this duplicates, but these are roughly the steps that have happened during the history of writing the article:

1. Login
2. Create a new unpublished article under your own name (no organization)
3. Edit the article text also on another machine or browser
4. Edit the article in the first machine/browser: swap it to organization and also change some of the meta like the title
5. Now each time you load the editor for this article it removes the meta

**Expected behavior**

Editor should never remove metadata for any reason.

**Screenshots**

Here I'm reloading the page and you can see how meta gets removed when the editor has booted:

![test4](https://user-images.githubusercontent.com/976619/59343992-b874c200-8d15-11e9-93e6-ef1015b6ee98.gif)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox
- Version: 67.0.1

**Comment by maestromac** [comment]
Thank you for this bug issue @Merri . 

Sorry we didn't get to you sooner. We did release a new editor recently and it may have caused you to experience this issue. It also may have been a glitch with the localStorage, since that is used to save your work incase you accidentally closed the page. 

I investigated it and I am having trouble reproducing this issue. Are you still experiencing this issue?

**Comment by Merri** [comment]
No, I cleared all the caches and also did change the editor version to v2 in the settings before doing that, and since then it has been working. So there probably has been some data that has been cached in one of the previous editor formats (v1 or an earlier v2; the editor switched with no action by me at some point) and that data then glitched it in that one particular article.

Clearing all the storage and cookies solved the issue so that is a workaround if someone else happens to get similar kind of weird issue :)

Potential learning/actions from this:

1. Ensure when providing a new feature to work alongside an older one that features don't mix (article that was written with old editor may glitch if forced to use a new editor with it)
2. Make sure when forcing a new version that all old data can be fully adapted to new data format
3. Add client side error tracker if you don't have one

I'm closing this one as the bug itself is hard to track and replicate, like all caching related bugs are :)
