### ISSUE TITLE
Consider adding a "bump" mechanism

### ISSUE THREAD

**Issue by rylandg** [thepracticaldev/dev.to#3153]
**Is your feature request related to a problem? Please describe.**
After a post is published, it's often necessary to make drastic changes/corrections if something was missed in the initial editing process. Un-publishing the post is perfect for this, but when you re-publish the post it goes back to the exact same place in the "queue" (latest queue for example). Dev.to does not have a simple/clear discovery mechanism or visible persistency for content, this means the updated version of the post is unlikely to be seen. 

Just yesterday I made a post with a bad title. 10 minutes later I realized, changed it and got 0 views or traction because it's window had passed. I ended up deleting, and then recreating the post which felt borderline abusive. Within minutes of reposting it ended up becoming my most well received post of all time. If I had not deleted it I would have lost out on that content.

I know it was partially discussed here https://github.com/thepracticaldev/dev.to/issues/3062. But that didn't feel entirely focused around the bump aspect.

**Describe the solution you'd like**
Add a mechanism that allows you to bump/retweet/refresh existing content so it has another discovery window.

**Describe alternatives you've considered**
Reverse bump (users positively receiving content causes it to move up the queue) might be possible, but not great if your content is already undiscoverable.

**Comment by edisonywh** [comment]
I feel like a mechanism like this is very easily abusable - now anyone can artificially bump their contents.

This becomes an unfair game for genuine users who aren't doing the same

**Comment by rylandg** [comment]
@edisonywh I agree there is potential for abuse. I think it can be done correctly and would punish authors less when they mess up their initial post.

**Comment by maestromac** [comment]
Note from team meeting:
> This would definitely be cool and it's not too dissimilar from retweeting your own tweet. This could abused so let's give this some thought and get it right.
