### ISSUE TITLE
"Follow Back" button on each of Followers in the list IF you are not followed to them yet

### ISSUE THREAD

**Issue by kensixx** [thepracticaldev/dev.to#3169]
**Is your feature request related to a problem? Please describe.**

I just noticed that when you view your Followers list, currently there's no "Follow Back" option next to the follower's name. 

Currently you would have to click the profile of the follower, then that's the time you can follow him/her back.

**Describe the solution you'd like**

It would be nice if there's a "Follow Back" button next to the follower's name, or at the far right of each div (if it's a div) if you're not currently followed to him/her yet. This makes following back more quicker and more nicer, to me I guess =)

And if you're already followed to him / her, a "Followed" icon would show up I suppose. =)

Added an image to show what I currently have in mind, I added blue squares at the end of each follower =)

![image](https://user-images.githubusercontent.com/24205790/59545795-aa61b400-8f56-11e9-8926-fa39086801c5.png)

**Comment by jeduardo824** [comment]
I would like to work on this

**Comment by bolariin** [comment]
I would like to work on this
