### ISSUE TITLE
[Feature Suggestion] User Spaces

### ISSUE THREAD

**Issue by michaelgv** [thepracticaldev/dev.to#318]
### User Story / Description
As a user of Dev, I find the profile pages of users very informative, and I see many users using the dev platform as their `blog` platform. This presents an opportunity to give the dev profiles some love. Much like how Reddit's done their own "self posting" on profiles, I think it would be nice to see something similar on Dev. Here's a high-level workflow chart I've created to help explain this thought:

https://www.lucidchart.com/documents/view/39d02abf-303c-4d95-9cf3-3409660a9c42/0

As you can see, the user profile would transform into a "space" - a customizable page where the user can add sidebars, add useful resources, as well as post on their own profile, and have an open AMA-style question box for users to ask questions on.

### Definition of Done

- Q&A box implemented, if selected for development
- User customization options are available, allowing them to morph the shape of their profile (ie, change where content is, add "important links" to header, sidebar, or floating content [ consider this a FAB-like interaction where you can click the FAB and content should float depending on your viewport, and screen orientation])

**Comment by pkfrank** [comment]
Hey @michaelgv, thanks for this issue, and sorry for the delay.

We're definitely in agreement that the user profile page could use some love and improvements from a design and functionality perspective.

I personally think that the Q&A section could be really cool.  It harkens back to the old forum style where you could "leave a message" publicly on someone else's profile.  Sort of like the "wall" context on MySpace / FB.  That said, there are also probably permissions / abuse issues to think about and debate.  

The other components of this issue — sprucing up the user profile page, making it easier and more flexible to add sections, and ensuring that the whole process is a bit more ergonomic, definitely makes 100% sense.

I think @benhalpern will jump in with a few additional thoughts.  Thanks for starting this convo and getting us going!
