### ISSUE TITLE
Specifying PostgreSQL minimum required version

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#319]
## Feature Request or Task

The README should be a little more explicit about which version of PostgreSQL is required.

What version is dev.to running on production? 

I would set that as the minimum required version.
I thought about this while investigating `pg`'s [Changelog](https://bitbucket.org/ged/ruby-pg/src/default/History.rdoc) for this conversation about the issues of installing dev.to on Windows: https://github.com/thepracticaldev/dev.to/issues/298#issuecomment-412060296

Version 1.0 drops support for PostgreSQL < 9.2 for example...

### User Story / Description

As a reader of the README I would like to know which is the minimum required version of PostgreSQL I have to install to be sure that the web app works.

### Definition of Done

Adding the min PostgreSQL's version to the README

**Comment by maestromac** [comment]
Hey @rhymes. Yeah, this is definitely a detail we've missed. I'm going to expand our `prerequisites` section.
