### ISSUE TITLE
Wrong algolia logo

### ISSUE THREAD

**Issue by LukyVj** [thepracticaldev/dev.to#320]
Hey! Lucas here, working at algolia! 

What a cool website & community you've got here! 

I'm just writing this small issue to let you know that you're using a slightly "old" logo! 
![](https://puu.sh/BbXzl/f516cbbd64.png)

Here is a ![link to the new one!](https://www.algolia.com/static_assets/images/v3/shared/logos/algolia/logo-algolia-nebula-blue-whitespaces-bf76438c.svg)

**Comment by Zhao-Andy** [comment]
Hey @LukyVj, thanks for the heads up! We'll update it accordingly. 👍

**Comment by benhalpern** [comment]
Hey @LukyVj this wound up being sort of counter-productive to the cause, as it kind of forced us to do what we were supposed to do, which was remove the logo. My comment from the PR:

> I actually think we should remove this altogether. We had tossed this in as part of Algolia's sponsorship and no longer have an obligation to it.

> We are friendly with the company. They're super great and I have no problem with the fact that we gave them some free advertising, but I feel like we can just get around to removing it as a matter of process.

We do ❤️ Algolia and will be adding more autocomplete stuff into the app to show off the wonderful low-latency features, and there will be more chances for things like this in the future.

If you or anyone from the Algolia team is interested in helping with some of the Algolia-centric features (most notably the search autocomplete suggestions we'd like to build), let us know via a new issue and we'll make it happen!
