### ISSUE TITLE
Improve documentation of RSS cross-publication feature

### ISSUE THREAD

**Issue by florimondmanca** [thepracticaldev/dev.to#321]
Hi! Thanks for the RSS cross-publish feature. Just had a suggestion related to its documentation in the website.

### User Story / Description

As a user wanting to cross-publish on DEV, I would like to have a description of how a draft is created from an RSS item so that I can decide whether my feed is correctly formatted for cross-publication.

### Definition of Done

- The tags used to build the draft are documented on the cross publication page in the user settings/profile.
- If multiple tags are used/tried to pull the content (eg content, summary...), their priority order is documented.
- Whether drafts support content with markdown content is documented.

### Additional Info (device/browser, helpful links)

From Twitter discussion with DEV:

> Hey there! Yep, if you put your Markdown as in the <description> tag, it should properly pull in. Alternatively, if you don't want to change your description tag, we look for the content and summary (and description, in that order respectively) tags to pull the body text.

**Comment by jessleenyc** [comment]
Let's create a new page dedicated to explaining the RSS feature and link to the page on /settings/publishing-from-rss

**Comment by stephaniekyyip** [comment]
@jessleenyc Hi! Can I work on this?

**Comment by jessleenyc** [comment]
@stephaniekyyip yes! since copy is a little tricky, we'll probably make some adjustments but would be awesome to get this information up.

**Comment by stephaniekyyip** [comment]
@jessleenyc What's the best way to better understand how the RSS feature works? Is there a particular part of the code I should look at?

**Comment by maestromac** [comment]
Hey @stephaniekyyip , `RssReader.rb` is the main source of our RSS feature. You can run `RssReader.get_all_articles` in rails console, after giving your account in development a feed_url, to manually fill all the feed down. Hope that helps!

**Comment by moriczgergo** [comment]
Hiya! I also added a guide #1151 since #1037 has seems to have gone inactive? /shrug
