### ISSUE TITLE
Can't remove the article from reading list

### ISSUE THREAD

**Issue by rafalpienkowski** [thepracticaldev/dev.to#3217]
**Describe the bug**

I can't remove some articles from my reading list. Additionally, they have reading time equal to 0 min.

**To Reproduce**

1. Go to the Reading list
2. Try to archive article which has been moved/deleted
3. Archived article is still present after the page refresh

**Expected behavior**
Moved/deleted articles should be removed from my reading list because they are no longer available.  

**Screenshots**
![sreenshot](https://raw.githubusercontent.com/rafalpienkowski/resources/master/other/screenshot.png)

**Desktop (please complete the following information):**

- OS: Linux/Windows
- Browser: Firefox
- Version: 67

**Smartphone (please complete the following information):**

- Device: iPhone 8
- Browser: Safari

**Additional context**
Broken articles have reading time: 0 min.

**Comment by jessleenyc** [comment]
Thanks for flagging. You can follow along the deletion issue here: #1641. For anyone who wants to tackle the reading time issue showing 0 min, I think we need to add a condition for short articles to default to one minute. Here's an example of another area where we already fixed this: #3024

**Comment by Danielshow** [comment]
Hey @jessleenyc, can I tackle this?

**Comment by maestromac** [comment]
Give it a go @Danielshow !

**Comment by Danielshow** [comment]
Thanks, I will @maestromac

**Comment by raxetul** [comment]
It will be better to have direct deletion button without archiving the article.

**Comment by akshayymahajan** [comment]
Worked on the 0 min read problem. #3927 fixes the issue.

**Comment by jacobherrington** [comment]
I'm able to reproduce this bug, so I'll go ahead and knock it out 🤠

**Comment by jacobherrington** [comment]
I've actually had my priorities shift a bit, so dropping this issue. It's up for grabs 😄

**Comment by thomasstep** [comment]
@jacobherrington Do you have any insight into this? It looks to me like it might be a reloading issue within the `ReadingList` component. Am I on the right track? I have been trying to debug a similar issue with archiving not updating lists until you refresh the page.

**Comment by ektaarora3501** [comment]
Hey can I take this issue ?

**Comment by mstruve** [comment]
Now that we are on Elasticsearch this issue has been resolved!
