### ISSUE TITLE
Also display the help, markdown, preview and save post buttons at the bottom of the edit post page

### ISSUE THREAD

**Issue by CzechsMix** [thepracticaldev/dev.to#322]
### User Story / Description

As a: Post Author

I need: The help, markdown, preview and save buttons to also appear at the bottom of the screen after the post textbox.

So that: I don't have to scroll all the way back to the top of the article to preview my post and get back to editing.

### Definition of Done

Given: the edit/new post page
When: It is rendered
Then: The help, markdown, preview, and save buttons should appear at both the top and the bottom of the post body textbox

---

Been a while since I've dance with Rails, but I would be more than happy to take a crack at this myself.

**Comment by benhalpern** [comment]
We actually have a new V2 editor in the works. It's pretty close to being done, so immediate improvements should go there. And it happens to solve this issue. The old one will still be supported, but we should put our efforts on the new version out the door.

https://github.com/thepracticaldev/dev.to/issues/272

Someone from our team will pick this up if nobody else does, but this is a great community issue if you want to dive into front-end JS land.

**Comment by CzechsMix** [comment]
Thanks! I'll check it out the v2 editor.
