### ISSUE TITLE
Posts counted as -1

### ISSUE THREAD

**Issue by andrasbacsai** [thepracticaldev/dev.to#3223]
**Describe the bug**
My dashboard looks like this at the moment:

![image](https://user-images.githubusercontent.com/5845193/59697449-1e69b980-91ee-11e9-90d8-b9493c8b7989.png)

I had a post in the past, which I've deleted, because I was not totally fine with it. 

Now my posts counted as -1 instead of 0.

**To Reproduce**
1. Create post
2. Delete it

I did not test it, to be honest.

**Expected behavior**
Posts counted as 0.

**Desktop:**

- OS: Mac & Linux
- Browser: Firefox & Chrome & Safari
- Version: N/A

**Comment by maestromac** [comment]
Hello @andrasbacsai , do you still see your posts count as -1 ?

**Comment by andrasbacsai** [comment]
Yep, still the same.

**Comment by andrasbacsai** [comment]
A small update, if I create a draft post it turnes to 0, but when I delete it, it turns back to -1 again.

**Comment by Zhao-Andy** [comment]
Hi @andrasbacsai, this should be fixed. Sorry about that bug!
