### ISSUE TITLE
Add more than 1 image at a time

### ISSUE THREAD

**Issue by rylandg** [thepracticaldev/dev.to#3227]
**Is your feature request related to a problem? Please describe.**
You currently cannot add more than 1 image at a time. This amongst other issues with the image uploading process causes it to be incredibly tedious.

**Describe the solution you'd like**
Allow me to upload all the images at once. Generate sequential uuids for the URI's so addressability isn't an issue.

**Comment by bolariin** [comment]
I was wondering the expectation for handling multiple image upload. Currently, there is an input field cause it only allows a single image upload. How would this change for multi image upload?

**Comment by maestromac** [comment]
The file_field helper tag have a [multiple option](https://apidock.com/rails/ActionView/Helpers/FormHelper/file_field). The backend upload feature will also have to be updated to account for this, along with how the multiple links are returned to the user.
