### ISSUE TITLE
change image preview

### ISSUE THREAD

**Issue by decadef20** [thepracticaldev/dev.to#3256]
**Is your feature request related to a problem? Please describe.**

When clicking an image to preview, it will redirect to the image URL, The article is lost. We have to click the back button.

**Describe the solution you'd like**

add a previewer to handle image, like modal or something else

**Comment by rhymes** [comment]
Hi @decadef20, thanks for taking the time. 

I'm going to close this as a duplicate of an older ticket https://github.com/thepracticaldev/dev.to/issues/413
