### ISSUE TITLE
Notifications Page needs pagination

### ISSUE THREAD

**Issue by Stargator** [thepracticaldev/dev.to#3259]
**Describe the bug**
I saw I had 138 notifications, I went to the page, but it only listed 53 items on the page and offered no way to see the other unseen notifications.

Additionally, the notifications that I **did not see** have been marked as seen once I went to the Notification page.

**The issues are**:
* Not all notifications are displayed.
* Notifications not displayed are marked as seen.

**To Reproduce**

1. Do not go to your Notification page until you have over 53 notifications. So 55-60 should suffice.
2. Click on Notification Icon from Home page
3. Count the number of notifications on the page, should max out to 53 items.
4. Go back to the home page and note that it no longer shows 55-60 notifications even though you only saw 53.

**Expected behavior**
I would expect notifications not the marked as seen until they each appear in the active view of the browser. So when the Notifications page renders, only the initial notifications seen in the first view should be marked as seen.

Additionally, I expect that I can scroll down or page over to view all my notifications.

**Screenshots**
<img width="57" alt="Screen Shot 2019-06-21 at 11 16 33 AM" src="https://user-images.githubusercontent.com/7527155/59932951-610dda80-9416-11e9-8d32-3ff6e87441e6.png">

**Desktop (please complete the following information):**

- OS: Mac 10.14.5
- Browser: Chrome
- Version: 75.0.3770.100

**Comment by maestromac** [comment]
Thanks for this issue @Stargator .

Yep the notification page could use pagination. A `Load more` button at the bottom of the page would be a good MVP. I think it would make more sense to re-word this bug report to a feature request, if that's alright with you.

**Comment by Stargator** [comment]
@maestromac I'm fine with that, but it is a bug as it doesn't behave as a user would otherwise expect. But you are correct that Dev.to doesn't have the functionality and thus nothing is broken.

So I'm fine with whatever changes you make.

**Comment by theaupoulat** [comment]
Possible to take it ?

**Comment by rhymes** [comment]
@theaupoulat please do, thank you!

**Comment by rhymes** [comment]
@theaupoulat just checking in, are you working on this? Thanks!
