### ISSUE TITLE
Extend moderator options?

### ISSUE THREAD

**Issue by monkeywithacupcake** [thepracticaldev/dev.to#326]
## Feature Request or Task
Let moderators give positive feedback
### User Story / Description
Moderators can currently identify items that are inappropriate. They cannot applaud good posts or helpful comments.
### Definition of Done
When moderators have a button or choice to flag especially well written and helpful posts.

**Comment by michaelgv** [comment]
By using existing public rating system they can. I’m not a big fan of this suggestion, as it’s unclear the intent:

When I for example hit thumbs down, it’s very clear it’s intent same with vomit.

Now if I were to press this theoretical “thumbs up” button, would it make it a pinned post? Would it merely push it up one ranking?

If the answer is to make it pinned, I’m not a fan - we’re inadvertently biasing what members are seeing, however I am all for a “suggest email shoutout” for the next digest system, I think it would be great for resourceful posts that should land a spot in the emails

**Comment by monkeywithacupcake** [comment]
No I don't think a pinned post would be helpful either. I like the "suggest email shoutout" kinda thing.

**Comment by jessleenyc** [comment]
Right now moderators have two ways of moderating -- there's the button on each article and the dropdown on comments that lead to /moderate (which is @monkeywithacupcake is describing), but we also have a 'round robin' style system where mods will occasionally receive notifications to check on random comments posted by new users. We haven't been consistent with the moderation choices across these two features, so whatever consensus we land on here should be taken account when approaching this issue as well: https://github.com/thepracticaldev/dev.to/issues/412. We'll also work on making it more clear on what each button does. 

What's a 'suggest email shoutout'?

**Comment by michaelgv** [comment]
@jessleenyc a ‘suggest email shoutout’ is essentially a button where you can send a notification to admin about posts that could be featured in the emails sent out? Ie, currently we go most popular, but it’d be nice to have ‘community recommended’ posts that may not be the most popular, but still have good information and deserving of an email “shoutout” in a “community recommended” category?
