### ISSUE TITLE
Android App Says I'm offline

### ISSUE THREAD

**Issue by mdarrik** [thepracticaldev/dev.to#3260]
**Describe the bug**

When I open the Dev.To app installed from Google play, it says I'm offline. I'm authed with Twitter, which has caused issues for other people on their browser (#2919)
**To Reproduce**

1. Open the Dev.To app
2. Says I'm offline

**Expected behavior**

Should open feed/whatever article I clicked to open the app.
**Screenshots**

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy S6
- OS: Android 7.0
- Browser: Dev Community App
- Version: 1.2

**Additional context**

Tried force stopping, did not work. 
Will consider uninstalling and reinstalling if necessary.

**Comment by neex-io** [comment]
I have been having this issue for a few days now (~under a week).
Everything is the same as above but my phone. Here are the specs:

**Smartphone (please complete the following information):**

- Device: Moto X4
- OS: Android 9
- Browser: Dev Community App
- Version: 1.2

**Comment by maestromac** [comment]
Thank you for this issue, please continue this conversation over at https://github.com/thepracticaldev/dev.to/issues/3260 as we are compiling all the reports.
