### ISSUE TITLE
Link to a specific gist version in dev.to

### ISSUE THREAD

**Issue by suntong** [thepracticaldev/dev.to#3267]
**Is your feature request related to a problem? Please describe.**

The syntax to link to a specific gist file from `dev.to` is:

```
{% gist https://gist.github.com/CristinaSolana/1885435 file=gistfile1.md %}
```

but it is impossible to link to a specific gist version of that file -- I tried to replace the above url with url to that specific version, but got `500 Internal` error when publishing it. 

**Describe the solution you'd like**

Fix this line 
https://github.com/thepracticaldev/dev.to/blob/master/app/liquid_tags/gist_tag.rb#L64
and allow link to a specific gist version.

**Comment by maestromac** [comment]
Thank you for this issue @suntong . Just to be sure, what does the gist embed of a specific revision looks like?

**Comment by suntong** [comment]
link to a specific gist file for the latest version:
https://gist.github.com/suntong/3a31faf8129d3d7a380122d5a6d48ff6#file-images-tmpl

link to a specific gist file of a specific revision:
https://gist.github.com/suntong/3a31faf8129d3d7a380122d5a6d48ff6/**44c4e7fa81592f917fffacf689dd76f469ca954c**#file-images-tmpl


https://gist.github.com/suntong/3a31faf8129d3d7a380122d5a6d48ff6/44c4e7fa81592f917fffacf689dd76f469ca954c

**Comment by GarrickBee** [comment]
Hi Team, 

Issue seems rise again,

https://gist.github.com/GarrickBee/aa8d07ee07796ab51509887993016788#file-gitlab-react-page-react-default-home-tsx

![image](https://user-images.githubusercontent.com/49749581/205334164-26a56c8b-6942-4980-b72d-82ff5ce44dd4.png)
