### ISSUE TITLE
Restructure files/folders of new front-end code

### ISSUE THREAD

**Issue by maestromac** [thepracticaldev/dev.to#327]
@nickytonline commented on [Thu Aug 02 2018](https://github.com/thepracticaldev/dev.to_core/issues/654)

# _TASK_
Just some housekeeping...

We're not a full blown SPA. We have components sprinkled into the site, e.g. Chat, Search (soon to be expanded on).

Initially, there was only on-boarding code in the new front-end code base. Since other things are there now, e.g. Search, chat etc., here's what I propose:

* files/folders for new front-end stuff should either all be moved under `./app/javascript/src`. or `./app/javascript`. I'm used to a `src` folder, but given that we're already a couple levels deep in the folder structure, the `javascript` folder may make sense as the root.
* on-boarding components should be under an `Onboarding` folder.
* rename `./app/javascript/packs/pack.js` to `./app/javascript/packs/Onboarding.jsx` as it really is the entry point file for on-boarding.
* Have a components folder for common components
* Have a views folder which have subfolders that are full-blown features, e.g. Chat. In those folders, there'd be a `components` folder for all the pieces of that particular feature.

Thoughts @benhalpern, @maestromac? Just trying to get things tidied up before the world sees everything ;)

### Screenshots

Current folder structure

![image](https://user-images.githubusercontent.com/833231/43621984-eea6989a-96a7-11e8-96b2-3e62bc871da3.png)

Potential new folder structure

![image](https://user-images.githubusercontent.com/833231/43622667-62dd16d2-96ab-11e8-9d40-b287a5120add.png)

---

@nickytonline commented on [Fri Aug 10 2018](https://github.com/thepracticaldev/dev.to_core/issues/654#issuecomment-412139543)

I know this issue will be moved to the new repo, so I'll fork and branch, but just wondering if you're OK with me going ahead with this change @maestromac and @benhalpern. I wanted to get this in before the OSS release, but the beach was calling. 😉🐚🌴

**Comment by maestromac** [comment]
Hey @nickytonline , @benhalpern and I are 100% onboard with this proposal. Our original plan was to follow [webpacker's suggestion](https://github.com/rails/webpacker#usage) but we may have strayed away from that line. This looks super neat 👍

**Comment by nickytonline** [comment]
Cool thanks Mac.

**Comment by maestromac** [comment]
unstale
