### ISSUE TITLE
Add max file size limit to profile images

### ISSUE THREAD

**Issue by tcdowney** [thepracticaldev/dev.to#3271]
**Is your feature request related to a problem? Please describe.**
One thing I really enjoy about dev.to is about how snappy the pages load. However, I've noticed that sometimes particular profile images were taking _forever_ to load. I dug some digging and found that some images were just really large (the one I checked was over 5 MB) which is why they were slow to load.

I was initially concerned because I do a lot of browsing from metered connections (like my phone), but in my browser dev tools it looked like you were using a service to resize on the fly server-side (Cloudinary?) so this point might not actually matter for the smaller thumbnails. On pages with larger versions of the profile images (like profile pages) I was still downloading ~1.5 MB images in this case.

Regardless, it still _feels_ slow. 😛 

**Describe the solution you'd like**
I saw in the `ProfileImageUploader` https://github.com/thepracticaldev/dev.to/blob/d48ad63aea38bb9e0bb01a7e9a58434c1ee947f6/app/uploaders/profile_image_uploader.rb#L3 that y'all had some file type and dimension limits in place. I think this gets you most of the way there, but a 4096x4096 gif can still have a really big file size. Not sure if `CarrierWave::BombShelter` can do it, but a file size limit would be nice as well.

**Describe alternatives you've considered**
You could also limit the file types for profile images to just `jpeg` and `png`. These are compressed better. I was pretty surprised to see `dng` as an option to be honest since those are RAW and can be really huge. 🙀 

Just thought I'd let you know and would be happy to help contribute something when I get some free time again. Thanks!

**Comment by maestromac** [comment]
Thank you for this issue @tcdowney !

Size limit would be super useful. We think 2mb should be reasonable.

**Comment by bolariin** [comment]
I have been able to make the change to limit the file size for profile images. I was wondering how I would go about setting up a test for this?

**Comment by rhymes** [comment]
@bolariin 

you could write specs in `spec/requests/user_settings_spec.rb` that update the user passing the `profile_image` parameter with the image. You can use [file_fixture](https://relishapp.com/rspec/rspec-rails/docs/file-fixture) to read the image in testing mode. The file pointed by `file_fixture` should go here https://github.com/thepracticaldev/dev.to/tree/master/spec/fixtures/files
