### ISSUE TITLE
Cannot post comments anymore

### ISSUE THREAD

**Issue by IvanDelsinne** [thepracticaldev/dev.to#3272]
**Describe the bug**

#2409 is the *exact* same issue I'm encountering, using Firefox Quantum 64.0.4 (64-b)

**To Reproduce**

Except for the article's URL, I followed the *exact* same steps.

Targeted article is [this one](https://dev.to/helenanders26/what-advice-would-you-give-your-20-year-old-self-33o1)

**Comment by IvanDelsinne** [comment]
Edit: submitting causes a 500 error without any additional context.

![image](https://user-images.githubusercontent.com/23583792/59981854-f7562200-9609-11e9-92e7-d57625d5fa47.png)

**Comment by pacoita** [comment]
I had the same issue for the [welcome page](https://dev.to/thepracticaldev/welcome-thread-v34-1b44).

It seems that `comments` API has problems and return 500:
```
POST https://dev.to/comments
```
