### ISSUE TITLE
Add "Date Created" and "Date Modified" to Article Dashboard items

### ISSUE THREAD

**Issue by seangwright** [thepracticaldev/dev.to#3274]
**Is your feature request related to a problem? Please describe.**
I usually have several Drafts of in-progress posts at any given point.

Sometimes they are published in an order different than when I started working on them so organizing can become tricky.

**Describe the solution you'd like**
Add the "Date Published" and "Date Modified" to the articles on the dashboard.

![dev-to-dashboard-item](https://user-images.githubusercontent.com/1382768/59986151-709e4680-9603-11e9-9ec6-d2157101718d.jpg)

Or ... allow me to filter by "Draft" and "Published" so I can get a good look at my work-in-progress independent of my completed and published stuff.

**Describe alternatives you've considered**
I don't think this information is currently available?

**Additional context**
There is more metadata around posts that might be helpful to surface to authors? These dates seem like a nice place to start.

**Comment by maestromac** [comment]
Make sense. Definitely a useful feature to have. I think having it right below the title is good start.

Some quick and dirty mockup
```
SOME TITLE HERE
Published: Jun 1, Updated: Jun 20, #csharp #dotnet #dotnetcore
(EDIT)   (MANAGE)   (....)
```
