### ISSUE TITLE
Bugs related with cookies disabled

### ISSUE THREAD

**Issue by eusonlito** [thepracticaldev/dev.to#3298]
**Describe the bug**
My default configuration on Chrome is cookies disabled. And with cookies disabled, I have some issues with articles detail:

* No reactions loaded
* Nothing occurs when relations click
* Navigation menu does not do nothing
* Follow button with strange behaviour
* Footer load with some css issues
* Console log error: `ServiceWorker registration failed:  DOMException`

**To Reproduce**

1. Disable cookies on dev.to with some chrome extension like https://chrome.google.com/webstore/detail/disable-cookies/lkmjmficaoifggpfapbffkggecbleang/related
2. Navigate and check errors.

**Expected behavior**
Navigation should load related contents with and without cookies (except user session).

**Screenshots**

![dev-to-no-cookies-1](https://user-images.githubusercontent.com/644551/60032777-8f561900-96a7-11e9-948a-89e265c47dfa.jpg)

![dev-to-no-cookies-2](https://user-images.githubusercontent.com/644551/60032808-9bda7180-96a7-11e9-947d-da1a734e926f.jpg)

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: Chrome
- Version: 76.0.3809.36 (Official Build) beta (64-bit)

**Comment by maestromac** [comment]
Thank you for this issue @eusonlito . My guess is that the JS isn't handling the lack of cookie well. A proper rescue would fix this.
