### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by ramlmn** [thepracticaldev/dev.to#33]
Please consider adding features like:
* [ ]  'date and time' info to the search results and for posts on the homepage.
* [ ] Filtering results using tags, username and date.

And consider:
* Avoid horizontal margins wherever possible.
* Avoid absolute positioning to use flex or floats for layout.

_Sorry if it feels like asking too much, we actually ❤ dev.to, we already think dev.to is a great place but we want to make it better._

**Comment by ganeshtata** [comment]
Hi @ghost! I would also love the filtering results to be implemented. dev.to is an amazing platform, and I have been learning so much from its posts. Recently, I was searching for the **_Who's looking for open source contributors?_** posts, and I was trying to sort the posts by date. But, unfortunately, I wasn't able to do so. It would be awesome if the filtering / sort by feature could be incorporated!
Again, thank for the wonderful community!
