### ISSUE TITLE
Notifications showing incorrect "Posted X days ago"

### ISSUE THREAD

**Issue by 12vanblart** [thepracticaldev/dev.to#3300]
**Describe the bug**
On the notification page, some posts are showing "Posted {x} days ago" when they should show a few minutes ago (shows correctly on Latest listings).

**To Reproduce**

1. Go to Notifications
2. Scroll through recent notifications looking for an item that is part of a series (the 2 I found were both series. Might be coincidence)
3. Note the "days ago" timing
4. Navigate to the post to see when the post was published. 

We found this in this twitter exchange: https://twitter.com/PichuPlayer/status/1143504346279272450

**Expected behavior**
It looks like the draft date is being used in place of the publish date for the notification calculations.

**Screenshots**
Notification - 
![Laurie's post notification indicating it was posted 4 days ago](https://user-images.githubusercontent.com/16465776/60101380-a9384000-9729-11e9-85c9-351bec7bd043.png)

Latest Feed -
![Laurie's post in the Latest feed indicating it was posted less than 1 hour ago.](https://user-images.githubusercontent.com/16465776/60101414-b9501f80-9729-11e9-8182-534cd56f6c74.png)

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser: Firefox
- Version: 68.0b12 (64-bit)

**Comment by rhymes** [comment]
Hi @12vanblart, thanks for raising this issue

This tweet by Laurie probably explains what it's happening: https://twitter.com/laurieontech/status/1143505792181657600

Indeed I can already see the problem: 

https://github.com/thepracticaldev/dev.to/blob/8afb797ec979fd7c7ceb31b8b642a12d59ca4cf2/app/views/notifications/_article.html.erb#L33-L35

It should count from the date of publishing, not the date of creation.
