### ISSUE TITLE
Exit Listings modal by pressing Escape

### ISSUE THREAD

**Issue by pkfrank** [thepracticaldev/dev.to#3303]
**Is your feature request related to a problem? Please describe.**
As a user navigating listings, I'd like the `Escape` key to close a Listings modal.

**Additional context**
As a user I can currently click outside of the modal, but pressing the Escape key seems like a pretty common pattern we should follow.

**Comment by Zhao-Andy** [comment]
Hm I think we had this functionality before, but it seems to not work anymore.
