### ISSUE TITLE
Image upload dialog overlaps editor/help page

### ISSUE THREAD

**Issue by protium-dev** [thepracticaldev/dev.to#3316]
**Describe the bug**
When I click "upload image" the upload dialog shows up but if then I click the "Preview" or "?" buttons, it stays and overlaps the preview as you can see in the images below. 

**To Reproduce**
Click "upload image", then click either "preview" or "?" button.

**Expected behavior**
Upload dialog should close

**Screenshots**
![image1](https://user-images.githubusercontent.com/43855513/60227782-ef46ee00-9866-11e9-9c5a-fd127d79fd5e.png)
![image2](https://user-images.githubusercontent.com/43855513/60227791-f7069280-9866-11e9-95f6-309de52d79d5.png)

**Desktop (please complete the following information):**
- OS: Arch Linux x64
- Browser: Chrome 
- Version: 75

**Additional context**
Same and worst in mobile

**Comment by ioprotium** [comment]
Update: same behavior with "menu" button.
![image](https://user-images.githubusercontent.com/43855513/60282640-d0377300-98dd-11e9-8f25-0a7119f10e9e.png)
