### ISSUE TITLE
Haml or Slim

### ISSUE THREAD

**Issue by araslanov-e** [thepracticaldev/dev.to#333]
Why you don't use Haml or Slim?

**Comment by koheisg** [comment]
I think the charm of dev.to is the speed of response. So, I think that you should use erb with the most speed.

**Comment by araslanov-e** [comment]
@koheisg https://sephinrothcn.wordpress.com/2014/04/14/slim-vs-haml-performance-perspective/ (see also first comment)

**Comment by araslanov-e** [comment]
May be hamlit? https://github.com/k0kubun/hamlit

**Comment by simonini** [comment]
Performance of hamlit and slim are improved a lot in last years and now are very near to erb.. sometimes also better  .. first source that i found with some data 
about it: “Partial rendering performance in Rails” https://medium.com/@coorasse/partial-rendering-performance-in-rails-101fdfb6ffb9

**Comment by koheisg** [comment]
thanks a lot info.
I should  take benchmark on dev.to and comment.

**Comment by rhymes** [comment]
But if the performance is the same, what's the real gain on rewriting all templates with haml or slim?

**Comment by araslanov-e** [comment]
@rhymes less code - fewer errors
For example - partial app/views/articles/_sidebar.html.erb 272 lines -> 178 lines

**Comment by simonini** [comment]
@rhymes and the syntax with this tool is awesome.. gain in readability and clarity..

**Comment by araslanov-e** [comment]
https://github.com/haml/html2haml
