### ISSUE TITLE
Code block overflows preview

### ISSUE THREAD

**Issue by cbrintnall** [thepracticaldev/dev.to#3331]
**Describe the bug**

Surrounding longer text in a "code" snippet (single ticks ``) can cause it to over flow the input box in preview mode.

**To Reproduce**

Heres a link I used: `https://docs.python.org/3/library/functools.html#functools.lru_cache`

Enter that with \`https://docs.python.org/3/library/functools.html#functools.lru_cache` in the text box, and then preview it, it should over flow. For reference I'm on a 4k monitor so that may be effecting it.

**Expected behavior**

This block should wrap to the next line.

**Screenshots**

![](https://i.imgur.com/JJ63nPO.png)

**Comment by Zhao-Andy** [comment]
Thanks @cbrintnall for the report! This is approved if anyone wants to work on this CSS related issue.

**Comment by cbrintnall** [comment]
Thanks @Zhao-Andy, I'd do it, but I haven't touched a ruby code base in my life :laughing:. Might I suggest adding the `good first issue` tag? Seems pretty beginner friendly.

**Comment by bbenefield89** [comment]
@Zhao-Andy If this is still up for grabs I wouldn't mind taking this up. Seems like a good first issue to dive into the codebase.

**Comment by maestromac** [comment]
go ahead @bbenefield89 !
