### ISSUE TITLE
Unable to login with details

### ISSUE THREAD

**Issue by JaybeeClassical** [thepracticaldev/dev.to#3364]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by JaybeeClassical** [comment]
[image: Dev to error.JPG]
Windows 7 operating system
Chrome browser
Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by maestromac** [comment]
Please kindly fill out the issue detail @JaybeeClassical 

What is happening to your account exactly? What is your username?
