### ISSUE TITLE
Notifications on comments of deleted posts should disappear

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#3365]
**Describe the bug**

I have a notification about someone liking a comment I made, but if I click on the notification I end up on a 404 page for the comment. The article the comments belongs to has been removed, thus the notification should be removed as well.

The comment ID is `ch1a`

**To Reproduce**

1. write a post
2. write a comment
3. have someone like that comment
4. verify the notification has been generated
5. delete the post 
6. the notification does not disappear

**Expected behavior**

I'm not 100% if comments get deleted if the article gets deleted, but I do get a 404 and I'm sure I haven't deleted the comment., which brings me to assume that the comment is deleted when the post disappears, thus the notifications tied to each comment deleted comment should go as well

**Screenshots**

![notifications](https://user-images.githubusercontent.com/146201/60518508-f4ca8b00-9ce1-11e9-8ee7-48d51de17a14.gif)

**Comment by Zhao-Andy** [comment]
Ah @maestromac we discussed this yesterday. I'll update my PR with a fix for this too.

**Comment by notapatch** [comment]
Before the 'fix' when the article is deleted the article's Notifications, NotificationSubscriptions are also removed from the database. However the comment associated with the article was not deleted having the  knock-on effect of Notifications, NotificationSubscriptions, Reactions associated with the orphaned comment also remaining in the database.

This feels inconsistent and the fix makes it so they are all deleted.

I have searched through the git reposisitory to try to find out why:

`
git log -L 16,40:app/models/article.rb
`

All I can be sure of is that Comments have never been `dependent :destroy` - I think this is an oversight.

**Comment by Zhao-Andy** [comment]
Resolved via #3570
