### ISSUE TITLE
Video Times aren't Displaying the hours in embeds

### ISSUE THREAD

**Issue by aspittel** [thepracticaldev/dev.to#3375]
**Describe the bug**

When you do embeds of video DEV posts, the time on the video cuts off any hours for the displayed time.

**To Reproduce**

Embed a longer video post within another post, ex. https://dev.to/aspittel/learning-css-through-creating-art-54c0

**Screenshots**
![Screen Shot 2019-07-03 at 8 07 34 AM](https://user-images.githubusercontent.com/12969662/60590475-11aaa100-9d6a-11e9-8c2a-62344e1e43e9.png)

This video is an hour and 18 mins long!

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser: Chrome
- Version: 75.0.3770.100

**Comment by rhymes** [comment]
For whomever is going to take a look at this: currently the system only extracts minutes and seconds from the duration. So if the video, like this one, clocks at 4688 seconds, which is 1h18m08s, the server will only display the minutes and seconds part.

See https://github.com/thepracticaldev/dev.to/blob/6d800da4d4e7cf94ad255c3a96908c98e185ff57/app/models/article.rb#L428-L433

unfortunately this field is indexed within search results, which means that to be totally fixed would also require a reindex, at least of those articles that have a video: https://github.com/thepracticaldev/dev.to/blob/6d800da4d4e7cf94ad255c3a96908c98e185ff57/app/models/article.rb#L171

**Comment by brarnaudovski** [comment]
Does it make sense for the seconds not to be rounded at 60? For example, the display time for the bug example, would be presented as `78:08`
