### ISSUE TITLE
Add a "post" alias for the "link" liquid tag

### ISSUE THREAD

**Issue by aspittel** [thepracticaldev/dev.to#3376]
**Is your feature request related to a problem? Please describe.**

Right now, to link a DEV post within another using a liquid tag, you use `link`. I always try write `post` first since it's a DEV post.

**Describe the solution you'd like**

 It would be awesome to add an alias so that a few terms work!

**Comment by maestromac** [comment]
For anyone who wishes to take this, it can be done very similarly to tweet tag https://github.com/thepracticaldev/dev.to/blob/3d8175328502c1f666f2c2ac99db50f6305e63d8/app/liquid_tags/tweet_tag.rb#L61
Also be sure to include test to cover this alias!

**Comment by thewhitewolf17** [comment]
I'm a beginner dev, and I'd love to take this issue!

**Comment by maestromac** [comment]
Go ahead @thewhitewolf17 !

**Comment by luke-jones-1** [comment]
Hi, im an apprentice software dev, is this issue available. if so id like to take it up and have a go.

**Comment by rhymes** [comment]
@luke-jones-1 I believe @cyberShaw is not working on it anymore, please go ahead!

**Comment by luke-jones-1** [comment]
thank you very much, ill give it a go then

**Comment by luke-jones-1** [comment]
i was just setting up an algolia account. when it asks which data centre i want to use should i just use the one with the lowest ping?

**Comment by rhymes** [comment]
@luke-jones-1 you need to create a `config/application.yml` file, not edit the `Envfile` directly. Take a look at the installation instructions: https://docs.dev.to/installation/mac/#installing-dev

**Comment by luke-jones-1** [comment]
thank you very much

**Comment by luke-jones-1** [comment]
@rhymes when trying to run ```bundle install``` it keeps failing when trying to install the 'pg version 1.1.4' gem and giving me this error message:
```
    current directory: /Users/Student/.rvm/gems/ruby-2.6.3/gems/pg-1.1.4/ext
/Users/Student/.rvm/rubies/ruby-2.6.3/bin/ruby -I /Users/Student/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0 -r ./siteconf20191010-13000-1d0be2w.rb extconf.rb
No pg_config... trying anyway. If building fails, please try again with
 --with-pg-config=/path/to/pg_config
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
```
i wanted to try running gem install with the ```--with-pg-config=/path/to/pg_config``` switch but i couldnt find where pg_config was. 
can you offer assistance?

**Comment by luke-jones-1** [comment]
Just submitted a pull request, I think I did it!
Just let me know if there's anything that needs fixing/changing.
