### ISSUE TITLE
No front matter, but also no title field

### ISSUE THREAD

**Issue by bigblind** [thepracticaldev/dev.to#3381]
**Describe the bug**
When I click the "write post" button in the top right, I get an editor with no pre-filled front matter, but it seems I also don't see a field to enter the title or tags. I'm sorry, I don't have time to investigate much further and write a further repro. Feel free to bug me about it, and I'll try again when I have time.

**To Reproduce**

In chrome, click the "write post" button.
Write some text, and try to find out where to write the title, then save.

**Expected behavior**
I should get pre-filled front matter, or a form element to enter details

**Screenshots**
Remind me later
I'm just wrtiging this as quickly as possible to report this. Will update later

**Desktop (please complete the following information):**

- OS:        macOS high sierra
- Browser: Chrome
- Version: 75.something

**Comment by Zhao-Andy** [comment]
Hmm that's strange. Let us know if you're still experiencing this. I can't reproduce on mobile currently.

My first guess is that:
- you are using the v1 editor
- somehow the front matter was deleted and saved into local storage for your `/new`
- you therefore have a blank text area

This can be confirmed on your end if you check your local storage -- I'd offer steps but I'm currently on mobile.

Anyway, if you are on the v1 editor here's the front matter that you could copy and paste in:
```
---
title: 
published: false
description: 
tags: 
---
```

**Comment by bigblind** [comment]
Yep, somehow my localStorage state got messed up.
