### ISSUE TITLE
Managing series with a git repository

### ISSUE THREAD

**Issue by kodaman2** [thepracticaldev/dev.to#3382]
**Is your feature request related to a problem? Please describe.**

Managing series with a git repo

**Describe the solution you'd like**

I'd like to create a repo with folders per article in the series, and be able to use that to publish a series in dev.to and on dev.to series have a button to pull latest changes on the series. Having a series in a a repo might be easier to manage especially if is a long series.

**Describe alternatives you've considered**

None

**Additional context**

**Comment by bigblind** [comment]
I think the best way to do this at the moment is to set up your own static site with Jekyll or Hugo, and in your dev.to settings, have it import your posts from there. You can then manage your static site using git, and as an added bonus, **your content is hosted on your own domain!*. DEV will even link to the original, ans set it as the cannonical url in the meta tags.

 I think this is something we should encourage in general, people having their own independant place on the web. So, I'd rather see improvements on that front.

I know they're not mutually exclusive, but the more features you add to dev.to that aren't available for RSS imported blogs, the less likely it is that people will host their blog elsewhere and syndicate it to dev.to.

**Comment by kodaman2** [comment]
Thanks @bigblind I hadn't thought of that. So let me make sure I understand your solution. 
- Create an RSS feed with Jekyll.
- Update RSS settings on dev.to

Two questions:

Is content published automatically?
Is content updated automatically?

**Comment by Zhao-Andy** [comment]
Thanks for responding @bigblind!

@kodaman2, once your RSS feed is updated, your posts will land into your dev.to dashboard (https://dev.to/dashboard) as drafts. We periodically pull in new posts so long as your RSS feed is continuously up-to-date. Content written on dev.to and separately from your blog will still work as intended. You can find more details in your RSS settings: https://dev.to/settings/publishing-from-rss

**Comment by kodaman2** [comment]
Thank you guys! Will get my rss feed up and running and go that route.
