### ISSUE TITLE
Broken markup on /readinglist page

### ISSUE THREAD

**Issue by alex-bender** [thepracticaldev/dev.to#339]
## Bug Report
Broken markup on page `https://dev.to/readinglist`
### Current Behavior
Footer is overlapping left navigation column on page `https://dev.to/readinglist`
### Expected Behavior
Footer should not overlap any part of the site
### Mobile & Desktop Screenshots/Recordings
![image](https://user-images.githubusercontent.com/3628862/44025407-bd4fa094-9ef8-11e8-9856-b21548710b41.png)
### Additional Info (device/browser, helpful links)
Browser: Firefox Quantum 61.0.1 (64-bit)
OS: Ubuntu 18.10

**Comment by markfrst** [comment]
Hi, i can fix it 🤓

**Comment by pkfrank** [comment]
Great, this is good to go. 👍

**Comment by markfrst** [comment]
@pkfrank Help me pls :)
I can not run correctly application at development environment

I don't display "reading list"

i get response from algolia `{"results":[null,null,null,null,null,null,null], "message":"ObjectID articles-10 does not exist. ObjectID articles-9 does not exist. ObjectID articles-8 does not exist. ObjectID articles-7 does not exist. ObjectID articles-45 does not exist. ObjectID articles-3 does not exist. ObjectID articles-1 does not exist. "}
`
and catch error
`base.js:1963 Uncaught TypeError: Cannot read property 'results' of undefined
    at Object.callback (base.js:1963)
    at base.js:6354`

**Comment by pkfrank** [comment]
Pinging @maestromac and @Zhao-Andy — one of these two fine folks will jump in with a response to help you out here.

**Comment by Zhao-Andy** [comment]
Hey @markfrst, do you have your own Algolia API keys? If not, you'll need to get that first -- [instructions here.](https://docs.dev.to/get-api-keys-dev-env/)

If you do have them, you might need to index your articles:
```ruby
Article.reindex
```

Let me know how that goes!

**Comment by markfrst** [comment]
@Zhao-Andy yes, i did set all api keys

Thanks, i will try it

**Comment by markfrst** [comment]
@Zhao-Andy thanks, it's works

**Comment by markfrst** [comment]
@Zhao-Andy maybe make non-fixed sidebar on the reading page as on home page?

**Comment by Zhao-Andy** [comment]
@markfrst Hmm, not sure what you mean; are you thinking the home page sidebar should also be in the reading list page? Or are you talking about making the current existing footer a right-side sidebar in the reading list page?

I think the simplest solution would be to move the footer down a bit on that page specifically, when there are no reading list items saved. @benhalpern might have some additional thoughts.

**Comment by markfrst** [comment]
@Zhao-Andy Okay, I did as you suggested.
before fix:
![image](https://user-images.githubusercontent.com/4071096/44616377-06443a80-a868-11e8-8759-a0fa3e3e1759.png)

after fix (don't pay attention on broken images 😸): 
![image](https://user-images.githubusercontent.com/4071096/44616324-5ff83500-a867-11e8-8b6d-96a1630178d8.png)

**Comment by alex-bender** [comment]
Hey guys! Seems that issue is resolved by @markfrst but the issue still remains

**Comment by alex-bender** [comment]
Thank you guys for fixing that!

**Comment by maestromac** [comment]
Still experiencing this issue on smaller screens 😞 

![image](https://user-images.githubusercontent.com/15793250/50524906-66611c80-0aa6-11e9-91f1-064f5e50492d.png)

**Comment by Zhao-Andy** [comment]
Still an issue

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/2166
