### ISSUE TITLE
Rename Reply in mail

### ISSUE THREAD

**Issue by jvanbruegge** [thepracticaldev/dev.to#34]
I would rename the Reply link in the mail to "View post" because that is what it does.
If it should open a reply box and I'm victim to #17 (i use firefox mobile) then you should add a view-only button

**Comment by jessleenyc** [comment]
Hey @jvanbruegge - we added a "reply" link and a "read original post" link in the email notification.

**Comment by jvanbruegge** [comment]
:+1:
