### ISSUE TITLE
Enh: 404 page performance 

### ISSUE THREAD

**Issue by davidjeddy** [thepracticaldev/dev.to#341]
## Feature Request or Task
Enhance the performance of the 404 page, either by removing the animated 404 image or animating it via different methods. (SVG+CSS?)

### User Story / Description
On slow connections the 404 page can take a significant time to load as well as undue loarge about of data in due largely to the animated image.

### Definition of Done
404 page load performance < 250ms

-------
### Current Behavior
`> 3s` load time
`> 400kb` data payload

### Expected Behavior
`< 250ms` load time
`< 100kb` data payload

### Mobile & Desktop Screenshots/Recordings
Tested pageload (forced fresh):
![image](https://user-images.githubusercontent.com/6232455/44038914-d8231c60-9ee5-11e8-9297-f4355a432387.png)

Speedtest due to VPN:
![image](https://user-images.githubusercontent.com/6232455/44039106-5595eda8-9ee6-11e8-93a0-27157955be7c.png)

### Additional Info (device/browser, helpful links)
Win10, Chrome, VPN network connection (that's the real kicker: 2.5Mb download speed)

**Comment by benhalpern** [comment]
Love this issue. I'd be in favor of a more useful redesign. It could still be fun, but minimizing the resources on a page like this makes sense to me. We could also add more useful links on the page. Possible places you may want to navigate to, as well as a link to report bugs, in case the 404 is indeed a bug.

Meta question:

At this point, do we close this issue and create a new one called "redesign 404 page" with specific guidance based on the decision I described just now? I don't think we've officially settled on what our best practice should be. Input here is super appreciated.

**Comment by davidjeddy** [comment]
Glad you enjoy the issue. I find pictures really are worth 1000s of words...and I am a terrible writer.

That being said; thank you for the quick response @benhalpern. I am open to either refocusing this issue or creating a new on to redesign the 404 page. For me it is a coin flip decision.

As for specific for a redesign. The following are purely opinion based on personal preference.
 - As a user I typically know where I want to go, the target of the link. Rarely has 'you might also like' type links been useful to me when I get the 4xx error.
 - I agree it should be entertaining, temper the disappointment with humor. :D
 - The view should confirm to the 'less is more' when it comes to loading speed and data transfer
 - 'Report this error' smacks of lack of monitoring and metrics from the operators. True or not; errors should not be displayed to the end user in production OR if it is present it is abused and the operators get flooded with to many noise tickets VS real issues.

**Comment by benhalpern** [comment]
Cool, I can get down with all those bullet points. I'm happy to think of this as the canonical issue for a 404 page redesign. In terms of links, I think the nav bar links make sense so you don't lose context and can navigate elsewhere as you normally would. Currently 404 pages are static as the Rails default, but we could make them dynamic.

From what I gather, this is the directive:

> Minimal, humorous, not trying to do to much.

**Comment by davidjeddy** [comment]
**404 Page Iteration Goals**

Design Goals:
 - Minimal, humorous, not trying to do to much
 - Include site header / footer as appropriate
 - 'less is more' when it comes to loading speed and data transfer (see engineering goals)

Engineering Goals:
 - `< 250 ms` load time on a 3G connection
 - `< 100 kb` data payload
 - Log and Monitor 404 error rate in metrics systems

**Comment by AgrimPrasad** [comment]
@davidjeddy After further investigation, it actually seems like `gifv` has been deprecated in favour of `mp4` by imgur. So loading a `gifv` link just loads the `gif` through some ajax voodoo.

Instead, the correct link should be https://i.imgur.com/Vyyjycv.mp4 which is 182486 bytes (182.5 kb). That is still a 57% reduction over the initial 423kb gif

Could do something like the following (with appropriate fallback to a still image on older browsers as you suggested) See https://jsfiddle.net/7t1e9mha/26/ for a full demo.

```html
<div class="tv__outer">
  <div class="tv__middle">
    <video class="tv__inner--special" alt="404" muted="muted" loop="loop" style="max-width: 90%; height: auto;">
              <source src="https://i.imgur.com/Vyyjycv.mp4" type="video/mp4">
                </video>
    <img class="tv__inner" src="https://i.imgur.com/3v0LCiP.jpg" alt="404 DEV" />
    <br />
    <p class="tv__inner--text">You have lost your way. <br> <a href="https://dev.to/">Return to Home Page</a></p>
  </div>
</div>
```

**Comment by davidjeddy** [comment]
@AgrimPrasad Aww man. That is a bummer gifv is deprecated. It is so compact!

182k over a 3G connection lands at around 2 seconds of load time; that is an ideal `perfect` fast 3G connection at that. Is that enough to provide an enjoyable experience only to see an animated 404 video? That question, I think, is best answered by @benhalpern .
