### ISSUE TITLE
Article API documentation missing changes with multiple organisations

### ISSUE THREAD

**Issue by Turnerj** [thepracticaldev/dev.to#3412]
Currently [in the API documentation](https://dev.to/api/), it states that an article can be published under an organisation by setting the `publish_under_org` to true or false.

With [support for being in multiple organisations](https://dev.to/devteam/changelog-join-multiple-organizations-2ma8) being added, the documentation seems to be incorrect.

**Comment by Zhao-Andy** [comment]
Resolved via #3539
