### ISSUE TITLE
Twitter login not working

### ISSUE THREAD

**Issue by ytjohn** [thepracticaldev/dev.to#3420]
**Describe the bug**
Clicking "Sign in with Twitter" returns a 500 error. I have the same result in Firefox, Chrome, and Chrome Icognito.

**To Reproduce**

Either click "Log In with Twitter" on the homepage or [go to]( https://dev.to/users/auth/twitter?callback_url=http%3A%2F%2Fdev.to%2Fusers%2Fauth%2Ftwitter%2Fcallback).

**Expected behavior**

Taken to twitter login or authorization page.

**Screenshots**

![image](https://user-images.githubusercontent.com/163156/60849651-bb9a8b00-a1b9-11e9-92ea-90530be1f4d4.png)

**Desktop (please complete the following information):**

- OS:MacOS
- Browser: Firefox, Chrome
- Version: Chrome 75, Firefox 67

**Comment by maestromac** [comment]
Thanks for this issue @ytjohn . It's being fixed right now

**Comment by maestromac** [comment]
This is resolved!
