### ISSUE TITLE
Adding location to listings

### ISSUE THREAD

**Issue by mariocsee** [thepracticaldev/dev.to#3425]
**Is your feature request related to a problem? Please describe.**
Some listings such as conferences, job openings, etc. could use context on location.

**Describe the solution you'd like**
Add an optional location field when creating a new listing that is searchable

**Describe alternatives you've considered**
Open to alternative ideas!

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/3370
