### ISSUE TITLE
URL validation does not accept all valid TLDs

### ISSUE THREAD

**Issue by Gredelston** [thepracticaldev/dev.to#3429]
**URL validation does not accept all valid TLDs**

I would like to add my personal website, www.gredelston.cool, to my profile. However, when I attempt to do so, the system forbids me to save my changes: it raises an error by the "Website url" field which reads, "Please enter a URL."

**To Reproduce**

1. Go to the "Settings" page.
2. In the field labeled "Website url", enter the valid URL "www.gredelston.cool".
3. Scroll down to the bottom.
4. Click "SUBMIT".
5. See the error that appears: "Please enter a URL."

**Expected behavior**

The system should recognize this URL as valid, and save the website to my profile.

**Screenshots**

![image](https://user-images.githubusercontent.com/1417909/60922373-c86ebb80-a259-11e9-8a3c-0c2830ef442d.png)

**Desktop:**

- OS: ChromeOS
- Browser: Google Chrome
- Version: 75.0.3770.102 (Official Build) (64-bit)

**Comment by rhymes** [comment]
Try to add the protocol: https://gredelston.cool

**Comment by Gredelston** [comment]
That works. Thank you!

It might be helpful to include a more descriptive error message.

**Comment by TekGadgt** [comment]
That appears to be a standard HTML URL field validation message.  I am not sure how one would go about changing it.

**Comment by rhymes** [comment]
@TekGadgt well, to be honest the builtin message is correct. A URL isn't valid without the protocol :D
But it can be changed with a little bit of JS: https://www.html5rocks.com/en/tutorials/forms/constraintvalidation/
