### ISSUE TITLE
Cannot add mx.linkedin.com URLs to my profile

### ISSUE THREAD

**Issue by Kurtz1993** [thepracticaldev/dev.to#343]
## Bug Report
My LinkedIn profile is in the subdomain mx.linkedin.com, seems that Dev.to doesn't like subdomains :/
### Current Behavior
Profile is saved successfully.
### Expected Behavior
Cannot save profile and says URL is not valid.
### Mobile & Desktop Screenshots/Recordings
![image](https://user-images.githubusercontent.com/5412470/44042237-5f7c80e4-9ee5-11e8-97b8-7ce73dbf1a91.png)
![image](https://user-images.githubusercontent.com/5412470/44042253-6956a126-9ee5-11e8-8d36-300d14e8f40d.png)

### Additional Info (device/browser, helpful links)
I also tried without the **https://**, and it also tells me that the URL is not valid.

**Comment by benhalpern** [comment]
`/\A(http|https):\/\/(www.linkedin.com|linkedin.com).*\z/m`

Looks like that `www` should be a wildcard.

This is ready for a fix.
