### ISSUE TITLE
Post views count not updated for not logged in users

### ISSUE THREAD

**Issue by pacoita** [thepracticaldev/dev.to#3436]
**Describe the bug**
Looking at the source code it seems that the Posts view count is increased only if the visiting user is logged in ( I might be mistaking though, as I am not a Ruby developer).

**To Reproduce**
Access your post with another machine/device without being logged.

**Expected behavior**
The post views would be increased for each unique visitor, even if he/she is not logged in.

**Additional considerations**
If it is the designed behaviour, this logic reduces the author visibility about all people's visits that are not members of Devto. Not giving an overall realistic view about the article impact. 
In many cases it can be a relevant amount (eg. no views at all would be count when the post link is referred from social media or other websites).

**Comment by pacoita** [comment]
Any feedback whether this is the expected behaviour or whether an improvement/fix is needed?
Thanks

**Comment by mmaia** [comment]
For me, it looks, in general, the count under the dashboard and in some posts is just not counting at all. Getting views, likes and bookmarks(reactions) but in the Dashboard, the "Total Post Reactions" and "Total Post Views" don't change at all.

**Comment by pacoita** [comment]
I had the same experience with *reactions*: I get notified of bookmarks/likes but even at the end of the day the amount of Views is the same. The totalViews seem to have a periodic "refresh", meaning that its value is not up to date all the date (even with the sum of articles views).

However my concern (reason of this issue entry) is that, looking from the source code, it seems that only Dev.to members' visits count against the total views. Making this way lose all the visits from non Dev.to users that land on the portal via external referrer (eg. Twitter links and so on)

**Comment by jessleenyc** [comment]
Hey everyone, all the page view logic is in the pageview controller. Pageviews should be updated every few page views and we check for that in a few different areas. We also fetch from google analytics periodically as a fallback. I believe everything here is expected behavior so I'm going to close this issue.

**Comment by pacoita** [comment]
Are page views counted only for Dev.to users or also for users without account?

**Comment by jessleenyc** [comment]
@pacoita when any user (with or without a DEV account) visits a post, the page view count for that post will update (just not necessarily _immediately_).
