### ISSUE TITLE
Cannot create tag from admin panel

### ISSUE THREAD

**Issue by damechen** [thepracticaldev/dev.to#3441]
**Describe the bug**
I am trying to create a new tag via admin panel, but hit error like following:

NoMethodError at /admin/tags/new

undefined method `sponsorship_organization_id' for #<Tag:0x00007febe2029740>
Did you mean?  sponsor_organization_id
               sponsor_organization_id?
               sponsor_organization_id=
               sponsor_organization
               sponsor_organization=

**To Reproduce**
Log in as admin, in the page: http://localhost:3000/admin/tags, as long as clicking "New tag" button, it will hit such error.

**Expected behavior**
We should allow to create new tags

**Screenshots**
Please see attachment.
<img width="1440" alt="Screen Shot 2019-07-10 at 11 47 33 AM" src="https://user-images.githubusercontent.com/5185979/60996013-a5e7ab80-a308-11e9-84ca-1b7a6fde114d.png">

**Desktop (please complete the following information):**

- OS: macos
- Browser: firefox
- Version:

**Comment by rhymes** [comment]
I've noticed this also, this should be solved by https://github.com/thepracticaldev/dev.to/pull/3438 :)

**Comment by damechen** [comment]
> I've noticed this also, this should be solved by #3438 :)
> 
> In the meantime you can replace `sponsorship_organization_id` with `sponsor_organization_id` in https://github.com/thepracticaldev/dev.to/blob/master/app/dashboards/tag_dashboard.rb

Thank you for prompt reply. I will give it a try. Thanks!

**Comment by damechen** [comment]
I've verified. The fix worked like a charm. Thanks!
