### ISSUE TITLE
Integrations: unable to pin repositories when filed under an organization

### ISSUE THREAD

**Issue by genemars** [thepracticaldev/dev.to#345]
## Feature Request or Task

Ability to select repositories from owned organizations.

### User Story / Description

I have many repositories which I own but that were created within an organization (of which I am admin).
I cannot pin those repositories because they are not even shown in the *Integrations* list.

### Definition of Done

Allow select owned repositories not just from the profile but also from linked organizations.

**Comment by maestromac** [comment]
Hey @genemars this is an existing issue on this.

Closing in favor of https://github.com/thepracticaldev/dev.to/issues/243
