### ISSUE TITLE
Clicking 'Purchase credits' after creating a listing will lose your draft

### ISSUE THREAD

**Issue by alexandersandberg** [thepracticaldev/dev.to#3454]
**Is your feature request related to a problem? Please describe.**
When creating a new listing without sufficient credits, the link at the bottom of the page—"Purchase credits now"—will take you to the credit purchasing page, in the same tab. This means that **any information that you've filled in for your listing will now be gone**.

**Describe the solution you'd like**
There are a few solutions for this
1. Automatically save a draft of your new listing on input change, so that you can go back to it later after you've purchased your credits.
2. Prompt a warning when clicking the button, saying that any content will be lost if you leave the page.
3. (Possibly the best and easiest solution) Open up the credits purchasing page in a new tab.

**Comment by jessleenyc** [comment]
Yeah, we should definitely figure it out. @mariocsee wanted to get this on your radar -- adding a prompt is a good in-between solution for now but auto-saving drafts will be the most useful.
