### ISSUE TITLE
can't write post and it'shows me error

### ISSUE THREAD

**Issue by yagnikgurutechnolabs** [thepracticaldev/dev.to#3462]
http://prntscr.com/oe3xrn

Please check the link and give me reply ASAP.

**Comment by rhymes** [comment]
Hi @yagnikgurutechnolabs, that's not an error, it just says that your post is unpublished, you need to publish it. If you're using the editor v1 you need to set `published: true` in the frontmatter:

```markdown
---
title: 
published: true
description: 
tags: 
---
```

and click "SAVE CHANGES"

If you're using the editor v2 you'll see a "PUBLISH" button at the bottom.

Let me know if that works for you

**Comment by yagnikgurutechnolabs** [comment]
Thanks for your response.

But I can't post a new write story.

http://prntscr.com/oe4jsy

please check this SS

**Comment by Zhao-Andy** [comment]
Hi @yagnikgurutechnolabs, this might an issue with your account. Please email yo@dev.to for more assistance.
