### ISSUE TITLE
Listings: location link is broken

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#3463]
**Describe the bug**

Given a listing with a location set, clicking on the link brings to a URL that doesn't show anything. Example: https://dev.to/listings/Colorado

The URL should be https://dev.to/listings/?q=Colorado

**To Reproduce**

1. Go to https://dev.to/listings
2. Click on the location name of a listing with a location
3. End up in an empty view

**Expected behavior**

1. Go to https://dev.to/listings
2. Click on the location name of a listing with a location
3. End up in a view with all listings with match that location

**Comment by Zhao-Andy** [comment]
Resolved via #3464
