### ISSUE TITLE
Too long markdown comment breaks code blocks

### ISSUE THREAD

**Issue by IvanDelsinne** [thepracticaldev/dev.to#3469]
**Describe the bug**

As seen on [this comment](https://dev.to/artemix/comment/d0ph), the last code block is not rendered as such, and seems to only be wrapped by 1 backtick per line.

**Expected behavior**

I'd expect every code block to behave the same, no matter the length.

**Screenshots**

![image](https://user-images.githubusercontent.com/23583792/61155913-65e41c80-a4f2-11e9-81e4-6304f09c5697.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox 67.0.4

**Comment by IvanDelsinne** [comment]
I'm sincerely sorry, as I just noticed that there was a rogue unclosed backtick in the middle of the document, which I probably put by accident, so now it's edited and there's no real bug.

**Comment by Zhao-Andy** [comment]
My (personal) hope is that we have cool syntax highlighting that can display things like rogue backticks in the future. :)

**Comment by IvanDelsinne** [comment]
That's definitely a fair point.
