### ISSUE TITLE
Scraping with Medium Liquid tag no longer works

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/dev.to#3485]
Looks like Medium has obscured their HTML and are using unintelligible classes now. This unfortunately breaks out Medium Liquid tag, which relies on scraping for the correct information.

**Comment by jessleenyc** [comment]
It would be great if we could have a general error message for when certain liquid tags no longer work, so they don't appear totally broken on articles that have been using the tag.

We should also try and figure out if we can get this working again 😅

**Comment by theKashey** [comment]
It took some time to find a single liquid tag I have to remove to be able to save my post. Then found that `MediumArticleRetrievalService` is broken, and this issue.

In short - please stop scraping page content. It does not work - there are __standard__ ways to gather information - `meta` tags including `og` and `twitter` ones.
- `og:title` for title
- `og:description` for description
- `og:image` for the image
- with fail-back to _non-og_ back.

And that would work for almost every site, so should sounds quite interesting.
