### ISSUE TITLE
CodePen Liquid tag username regex allows only 20 characters

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/dev.to#3487]
Based on this comment, there are CodePen usernames that are over the 20 character limit: https://github.com/thepracticaldev/dev.to/pull/2985#discussion_r303446301

This should be a one character fix to adjust our limit from `20` to `30` in our current regex checker:
https://github.com/thepracticaldev/dev.to/blob/47eaa9ece11fd5e748cf53af6bccde7929d00686/app/liquid_tags/codepen_tag.rb#L50

**Comment by bolariin** [comment]
I think this issue was resolved

**Comment by maestromac** [comment]
I don't think this is. https://github.com/JoelMontano/dev.to/pull/1 isn't merged to this project, but to the fork.

**Comment by bolariin** [comment]
Oh my bad! I didn't notice that.

**Comment by raquelcps** [comment]
I'm working on this right now!
