### ISSUE TITLE
I am not able to write new story on dev

### ISSUE THREAD

**Issue by amit58843** [thepracticaldev/dev.to#3497]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by maestromac** [comment]
Hello @amit58843 , this looks an issue specific to your account. Please email yo@dev.to for more help.
