### ISSUE TITLE
Display podcast episode's published_at date

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#3498]
I would like to see `published_at` date of an episode on its page, in the podcasts feed and on the podcast's episodes list.
It would allow me to understand if the episode is fresh and if the podcast is active.

**Comment by KaraAJC** [comment]
I'm gonna try to tackle this issue!

**Comment by jessleenyc** [comment]
Awesome, @KaraAJC!

For the index view, I imagine the date can be placed and look similar to what we do for articles: ![](https://cl.ly/2f505d10086e/download/Image%202019-07-31%20at%209.07.03%20PM.png)

Not sure where it should go on the podcast show page but look forward to your ideas.

**Comment by Jngai** [comment]
@KaraAJC are you still working on this? I am interested in it.

**Comment by araslanov-e** [comment]
@lightalloy 
![image](https://user-images.githubusercontent.com/1290711/66109568-64e8f580-e5de-11e9-94a2-623c3d127e7e.png) norm?

**Comment by araslanov-e** [comment]
@lightalloy and 
![image](https://user-images.githubusercontent.com/1290711/66109711-b2fdf900-e5de-11e9-8a71-e73f9cecb6a6.png) ?

**Comment by lightalloy** [comment]
@araslanov-e What do you think about doing it similar to the post's date? Smth like:
![изображение](https://user-images.githubusercontent.com/30115/66117580-8e555180-e5dd-11e9-9ada-d39616323e56.png)

**Comment by araslanov-e** [comment]
@lightalloy You're right, it’s necessary by analogy.

**Comment by araslanov-e** [comment]
@lightalloy what about show episode?

**Comment by lightalloy** [comment]
It looks ok to me, maybe I would make the date font a bit larger.

**Comment by vanduc1102** [comment]
Hi @lightalloy , I just created a PR for the issue : https://github.com/thepracticaldev/dev.to/pull/4272
thanks

**Comment by rhymes** [comment]
@vanduc1102 thanks for your PR! We'll take a look promply. One info: if you think you're done with the PR, please remove the `WIP` (work in progress), so that we can know when a PR is ready for review. Since you've left this comment I'm assuming yours is

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/4272
