### ISSUE TITLE
Edit profile link broken?

### ISSUE THREAD

**Issue by onejgordon** [thepracticaldev/dev.to#35]
For me, redirects to `https://dev.to/?signed-in-already`, and renders the main page.

I signed in with Github.

**Comment by MattBidewell** [comment]
Works for me. Signed in via GH.

Assuming its solved (April 1st). If not can you provide some more details, what page you was on etc.

**Comment by onejgordon** [comment]
Looks like the 'edit profile' link is now the settings page, and the link is working as expected.

**Comment by jessleenyc** [comment]
Great! Thanks @onejgordon for flagging and @MattBidewell for jumping in :)
