### ISSUE TITLE
Add ability to get user's unpublished posts via API

### ISSUE THREAD

**Issue by toddanglin** [thepracticaldev/dev.to#3502]
I'm digging-in to the new API with the goal of providing authors a simple to way to schedule the date and time their posts are published.

A lot of what's required seems to be in the API, but there does not appear to be an ability to get an user's _unpublished_ posts...even if the user provides their API Key secret. Ideally, a scheduling tool would fetch an user's unpublished drafts and allow them to specify a date/time to update the posts as published.

At a minimum, the API should allow `GET` requests to `/api/articles?username=#name` to return unpublished posts IF the provided API Key matches provided username.

What do you think?

**Comment by andrewrod33** [comment]
Looks like this can now be done after https://github.com/thepracticaldev/dev.to/pull/3644. If you use the `/api/articles/me` route with your access token it will return all of your articles.

**Comment by jessleenyc** [comment]
Going to close this issue since all articles are now available!

**Comment by toddanglin** [comment]
Great! Thanks for the update. Will check it out.
