### ISSUE TITLE
Link liquid tag's title is not correctly escaped

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#3508]
**Describe the bug**

If the title of the article contains an ampersand `&`, it will appear as `&amp;`

**To Reproduce**

1. Go to https://dev.to/devteam/the-7-most-popular-dev-posts-from-the-past-week-5f80
2. Scroll and check entries number 1 and 4

**Expected behavior**

`&` should remain `&` as it is in the single article page

**Screenshots**

![Screenshot_2019-07-21 The 7 Most Popular DEV Posts from the Past Week](https://user-images.githubusercontent.com/146201/61588829-0fd24180-aba2-11e9-8575-01abb6675d3e.png)

This doesn't happen in the article page:

![Screenshot_2019-07-21 101 Tips For Being A Great Programmer ( Human)](https://user-images.githubusercontent.com/146201/61588836-27a9c580-aba2-11e9-9686-aa593b6d0362.png)

![Screenshot_2019-07-21 Ultimate Short Guide to Stop Procrastinating](https://user-images.githubusercontent.com/146201/61588837-2bd5e300-aba2-11e9-9bab-fde86f32375c.png)

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Firefox 
- Version: 69.0b6

**Comment by haved** [comment]
I will have a stab at fixing this
