### ISSUE TITLE
Allow posts to be marked as discussions

### ISSUE THREAD

**Issue by bdbch** [thepracticaldev/dev.to#3509]
**Is your feature request related to a problem? Please describe.**
I think Kent C. Dodds has a really [good point](https://mobile.twitter.com/kentcdodds/status/1152942560865923072). I also believe dev.to can be a way better discussion platform than Twitter.

**Describe the solution you'd like**
The problem is, that I'd also like to use dev.to as my blog instead of Medium which I will use on my website. It would be great if a post could be either a post or a discussion which can be excluded when fetching posts via the endpoints so I don't have discussion posts on my websites blog page.

**Describe alternatives you've considered**
Maybe allow filtering out tags from the articles endpoint so I can tag my discussion posts as #discussion and exclude them when I fetch them.

Thank you very much!

**Comment by jessleenyc** [comment]
Hey @bdbch, thanks for the request. Just made this issue that should address the problem you're describing: https://github.com/thepracticaldev/dev.to/issues/3654
