### ISSUE TITLE
Http 500 Error when malformed github repo links inserted

### ISSUE THREAD

**Issue by Slashgear** [thepracticaldev/dev.to#3511]
**Describe the bug**

When a user want to add a github repository link in a post. If their is a `/` at the beginning

**To Reproduce**

 
- Goto post creation page
 
- Paste `{% github /thepracticaldev/dev.to %}`

- Try to save
 
- You will receive a 500 HTTP error

**Expected behavior**

It should at least send a 400 error.
It should help user with a specific message.

**Screenshots**

<img width="1043" alt="Capture d’écran 2019-07-21 à 20 13 20" src="https://user-images.githubusercontent.com/6263857/61595167-040f6b00-abf4-11e9-801b-746efff4bf79.png">
**Desktop (please complete the following information):**

- OS: MacOS Mojave
- Browser: Chrome 
- Version: 75

**Comment by jessleenyc** [comment]
Agreed, let's send a better error message for this.
