### ISSUE TITLE
The 'article-reaction-actions' div doesn't show while using ublock origin

### ISSUE THREAD

**Issue by eBourgess** [thepracticaldev/dev.to#3512]
**Describe the bug**
While browsing dev.to on my Firefox browser with my `ublock origin` extension being active, the `article-reaction-actions` div doesn't show. Meaning I can no longer give my reactions to a post, share it on social media easily. etc.

**To Reproduce**

1. Turn on ublock origin
2. Go to any article, e.g [this](https://dev.to/lampewebdev/my-web-development-vs-code-settings-theme-extensions-tips-and-tricks-1324)

**Expected behavior**

1. The div should be shown

**Screenshots**

With uBlock Origin on:
![Screenshot from 2019-07-21 22-22-34](https://user-images.githubusercontent.com/19877979/61595964-40e45d80-ac06-11e9-8e89-f44da1c3b313.png)

With uBlock Origin off
![Screenshot from 2019-07-21 22-24-36](https://user-images.githubusercontent.com/19877979/61595999-83a63580-ac06-11e9-8531-74ff864516d0.png)

**Desktop (please complete the following information):**

- OS: Fedora 30 Workstation Edition
- Browser: Mozilla Firefox
- Version: 68.0

**Additional context**

After going to my browser's console the following error 
![Screenshot from 2019-07-21 22-29-21](https://user-images.githubusercontent.com/19877979/61596044-147d1100-ac07-11e9-9412-0287c769cc22.png)

And after clicking on the Syntax error this was shown

`Pusher.ScriptReceivers[1](null, { host: 'timeline49-clientstats1.pusher.com' });`

**Comment by rhymes** [comment]
I do have uBlock Origin on but I see the bar. I see the syntax error you mention but I don't think they are related.

Can you provide a screenshot of what uBlock is blocking? Maybe you need to turn something on.

Click on the uBlock icon and take a screenshot :)

**Comment by eBourgess** [comment]
Hey @rhymes here is the log for my blocks in ublock origin 
![Screen Shot 2019-07-23 at 10 26 12 AM](https://user-images.githubusercontent.com/19877979/61691507-61123a80-ad34-11e9-82e1-2db977fefc4a.png)

**Comment by rhymes** [comment]
I think it's those two dom rules, especially the second one, it's literally blocking the article actions to appear. Did you manually zap the element? Are you using too strict filters? Do you have advanced mode activated?

Check in the uBlock dashboard in the "my filters" and "my rules" if there's anything related to those two blocks. 

I think your only chance is to undo what's going on right now for those two dom blocks.

This is my configuration and I have no dom block rules activated.

![Screenshot 2019-07-23 at 9 53 21 AM](https://user-images.githubusercontent.com/146201/61693384-c9aae880-ad2f-11e9-9256-fa93bb37dd1c.png)

**Comment by eBourgess** [comment]
I have really strict filters on my ublock origin yes, so the solution for me is to disable uBlock Origin while scrolling through dev.to

**Comment by rhymes** [comment]
I'm going to close this because I don't think there's anything to be done on our side.
