### ISSUE TITLE
Number of views inconsistent in Notifications and Dashboard

### ISSUE THREAD

**Issue by haseebelahi** [thepracticaldev/dev.to#3520]
**Describe the bug**
Congratulations GIF notification shows a different number of views than the dashboard.

**To Reproduce**
1. Post by a user reaches more than 20k followers
2. User gets notified of the views
3. Number of views in Notifications is different from the number of views shown on Dashboard for that post.

**Expected behavior**
The number of views in Notifications and on Dashboard for a post should be the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/13603051/61646684-6b94eb80-acc4-11e9-9e4f-a4ac00e41a49.png)
![image](https://user-images.githubusercontent.com/13603051/61646700-7b143480-acc4-11e9-9901-b7cb161b1f76.png)
Both screenshots are from the time of notification recieved.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome 
- Version: 75.0.3770.142 (Official Build) (64-bit)

**Additional context**

**Comment by rhymes** [comment]
Hi @haseebelahi, it's not exactly inconsistent, it's a combination of how the message is phrased and async. Basically when your post is detected to have passed 16384 views the notification is queued. 

The moment your post is detected is not in realtime and the queued also adds time in between.

If you read the message doesn't say "you have 16k views" but "you passed 16k views", in that sense, it's correct :) In the dashboard you see the actual count.

If at some point you pass 32768 you'll receive another notification :)

Hope the mechanism is clearer

**Comment by haseebelahi** [comment]
Oh, thanks for the clarification @rhymes. I think we could then remove the word 'just' in 'Your post **** just passed x views' to make it more clear?

**Comment by rhymes** [comment]
that makes sense!

**Comment by haseebelahi** [comment]
I'm going to pick this one up.
