### ISSUE TITLE
Feature request: ordering the search results

### ISSUE THREAD

**Issue by THausherr** [thepracticaldev/dev.to#3530]
**Is your feature request related to a problem? Please describe.**
Yesterday I wanted to search that recent post about a bad day at stackoverflow, I found only posts from 2018. (However today, I did the search again and it was right at the top)

**Describe the solution you'd like**
I'd like a way to sort the results by date, relevance (how good the match is) or times viewed / liked.

**Describe alternatives you've considered**
Can't think on any right now. (I did search on the issue list here and didn't find this request, which surprises me)

**Comment by danascheider** [comment]
Is this issue up for grabs still? I'm happy to take a crack at it.

**Comment by rhymes** [comment]
@danascheider yeah, please go ahead.
