### ISSUE TITLE
I can't  comment in any post and also don't allow to post anything.

### ISSUE THREAD

**Issue by jaysauh** [thepracticaldev/dev.to#3535]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by maestromac** [comment]
Hello @jaysauh , this looks an issue specific to your account. Please email yo@dev.to for more help.
