### ISSUE TITLE
Fuzzy timestamps on notifications become stale

### ISSUE THREAD

**Issue by kaspermeyer** [thepracticaldev/dev.to#3548]
**Describe the bug**

The publication timestamps on articles in the notifications view aren't updated when time passes.

I dug a bit in the template and the bug seems to be caused by a hardcoded fuzzy timestamp inside a view cache:

https://github.com/thepracticaldev/dev.to/blob/6cc0d125b5e9dac010080ffca408ce23e7d59f0c/app/views/notifications/_article.html.erb#L34-L38

This causes the cache to become stale almost instantly.

A possible solution could be to store the publication date in an attribute on the element and use JavaScript to render and update the fuzzy timestamps dynamically.

I'd be more than happy to take on this issue. It'd be my first contribution to dev.to 🍻   

**To Reproduce**

1. Click the "Notifications" bell in the navigation menu
2. Inspect the timestamp below the header _"[author] made a new post:"_

**Expected behavior**

The timestamp should reflect the actual publication date.

**Screenshots**
<img width="634" alt="Screenshot 2019-07-26 at 18 16 01" src="https://user-images.githubusercontent.com/18333420/61973738-13702900-afe5-11e9-9292-095d8a6f5e24.png">

**Desktop:**
- OS: macOS (10.14.4)
- Browser: Safari
- Version: 12.1 (14607.1.40.1.4)

**Additional context**

There seem to be other issues closely related to this. @ClaraMorgen made an excellent solution to a related problem in the PR #3076 to which issue #2997 and #3183 were both closed — even though this issue remains. 

Please let me know if I'm missing something 🙏

**Comment by kaspermeyer** [comment]
I’d love to give this a shot 👋

**Comment by rhymes** [comment]
I'm closing this because by removing the cache in https://github.com/thepracticaldev/dev.to/pull/4122 the behavior should have disappeared, maybe in the future we could switch to client side rendering (which has to take into account pagination and eventually i18n)
