### ISSUE TITLE
Github Bots

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#355]
### User Story / Description
Specifically, we'd like to create an automated github response after a contributor's first PR is merged. We'll probably have other scenarios we'll want a bot for, but this is the use case that comes to mind. 

### Definition of Done
Ping me after we know how to create the bot and I'll send over copy!

**Comment by nickytonline** [comment]
I've never used it, but I think this is a good use case for [probot](https://github.com/probot/probot).

**Comment by connorshea** [comment]
I'd personally recommend Danger: https://github.com/danger/danger

**Comment by nickytonline** [comment]
Ah yeah, I've heard Max Stoiber talk about that before for either the Styled Components repo or the Spectrum one.

**Comment by benhalpern** [comment]
I'm cool with either of these. One use case outside of enforcing rules is a follow-up message after a PR that has some "next steps" info.

Basically we want to inform folks that they've earned [the badge](https://dev.to/badge/dev-contributor) and it will be reflected on their DEV profile in a few days. Whatever the simplest way to get that going works for me.

**Comment by michaelgv** [comment]
@benhalpern I’ll do this, want to chat on dev about the requirements and I’ll submit it in a PR?

**Comment by maestromac** [comment]
Resolved by https://github.com/thepracticaldev/dev.to/pull/1016
