### ISSUE TITLE
Cannot copy organization secret from mobile phone

### ISSUE THREAD

**Issue by shushugah** [thepracticaldev/dev.to#3568]
**Describe the bug**
As an admin, I cannot copy or select the generated secret to add someone to my organization account on dev.to from safari browser of my iOS 12 iPhone 6S device 

**Smartphone (please complete the following information):**

- Device: iPhone 6S
- OS: iOS 12.4
- Browser: Safari
- Version: 12.4

**Comment by maestromac** [comment]
For anybody that would like to pick this up, the easiest solution would be to add click-to-copy to that field, similar to how it's done here https://github.com/thepracticaldev/dev.to/pull/2957
