### ISSUE TITLE
Notifications are not reflected in emails

### ISSUE THREAD

**Issue by axtens** [thepracticaldev/dev.to#3573]
At last look I've got 480 followers (wow, how did that happen?!). However, I don't have 480 emails to back that up. I have 19 emails. 

Am I supposed to get one email per follower or just a once-per-day when the total changes?

**Comment by rhymes** [comment]
Hi @axtens, thanks for bringing this up, I checked the logic and no, it doesn't send an email for everything single follower:

https://github.com/thepracticaldev/dev.to/blob/710c1d9e7b24a3e0b144bec6b3f22d2835cf4c4e/app/jobs/follows/send_email_notification_job.rb#L5-L13

It's going to skip the sending if there are any messages for new followers sent any time between 15 to 35 hours before (at random).

**Comment by axtens** [comment]
So it's not a bug, it's a feature?

**Comment by rhymes** [comment]
@axtens at present I think so, maybe @benhalpern has more insight on this choice

**Comment by Zhao-Andy** [comment]
I believe the idea was to prevent sending out too many emails about new followers. The logic could probably be updated to send daily, for example.

My personal take is that daily emails still kind of spammy though.

**Comment by axtens** [comment]
Yes, and what am i going to do with 720 emails anyway? Maybe update the notifications page list to say that particular notification occurs daily or something to that effect
