### ISSUE TITLE
Feature Request: photo credit

### ISSUE THREAD

**Issue by bdmorin** [thepracticaldev/dev.to#358]
## Feature Request
photo credit badge template
### User Story / Description
I've been using unsplash on some of my posts, and I like to credit the photographer. It seems like I never use the same format, and i like uniformity. It would be nice to have a {% photocredit photoname artist url %} tag or something
### Definition of Done
Using a single tag to attribute photos for a single look on all posts

**Comment by benhalpern** [comment]
I'm in favor of this. I hadn't even thought of doing it via liquid tag. But that works!

If someone wants to claim this I could help with next steps.

**Comment by GuitarKat** [comment]
Thanks for being cool on copyright and attribution.  I like this feature. I feel it's important that people attribute and we should encourage and make it easy for contributors to do so.

**Comment by bdmorin** [comment]
I'll give it a shot, thanks for encouragment!

**Comment by GuitarKat** [comment]
If it's cool for me to contribute for any screens or ideas, I'd be happy to contribute to this feature.

**Comment by benhalpern** [comment]
Hey @bdmorin @GuitarKat I added some quick docs for liquid tags:

https://docs.dev.to/liquid-tags/

Right now we don't really have the details in place for "multiple args" like this, but if you want to work the implementation of this, that would be great! Myself and @maestromac will be available to talk through details and ideas at any time.

**Comment by GuitarKat** [comment]
Sorry for my delay in commenting, but this looks great. I approve of this too. Thanks for picking this up!

**Comment by jessleenyc** [comment]
Since figcaption works pretty well, we're closing this issue. Still open to the liquid tag if anyone wants to submit a PR for that.
