### ISSUE TITLE
Duplicate notifications

### ISSUE THREAD

**Issue by shushugah** [thepracticaldev/dev.to#3583]
**Describe the bug**

When someone tags me in a comment while replying to me, I get notified twice. 

**To Reproduce**
It occurs in this url, https://dev.to/notifications/comments see image below

**Expected behavior**
Should be one notification

**Screenshots**

![Screen Shot 2019-07-30 at 20 56 57](https://user-images.githubusercontent.com/7111514/62157220-f4d3a000-b30c-11e9-9684-105e11c51804.png)

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser: Chrome

**Comment by Zhao-Andy** [comment]
Thanks for the report! My first guess is that we can prevent mention notifications from firing if the person mentioned is receiving notifications for a post or comment thread already.

**Comment by jessleenyc** [comment]
Once #3672 is complete there should be better documentation on how to set up notifications locally. There's already some info in that issue for reference.

**Comment by Janglee123** [comment]
I want to work on this issue for hacktoberfest. But dont know where to start.

**Comment by blunket** [comment]
Hey @Janglee123, check out these files! Maybe this will help you a bit?

- [app/services/mentions/create_all.rb](https://github.com/thepracticaldev/dev.to/blob/master/app/services/mentions/create_all.rb)
- [spec/services/mentions/create_all_spec.rb](https://github.com/thepracticaldev/dev.to/blob/master/spec/services/mentions/create_all_spec.rb)
- [app/views/notifications/_mention.html.erb](https://github.com/thepracticaldev/dev.to/blob/master/app/views/notifications/_mention.html.erb)
- [spec/requests/notifications_spec.rb](https://github.com/thepracticaldev/dev.to/blob/master/spec/requests/notifications_spec.rb#L349)

**Comment by benhalpern** [comment]
Yup @blunket you're onto it correctly. @Janglee123 This is going to be a matter of adding some conditional in the logic where the `mention` is created so that it checks whether the mentioned user will not get a notification by other logic.

**Comment by blunket** [comment]
@Janglee123 If you check out the Comments controller, you can find where the NotificationSubscription and Notification are both created.

https://github.com/thepracticaldev/dev.to/blob/master/app/controllers/comments_controller.rb#L59

Maybe that helps more?

**Comment by ledestin** [comment]
I understand that if a notification is present for the comment and the user, mention shouldn't be created. Correct?

I'm trying to write a comment request spec, and notification isn't being created when another user replies to my article:
```
 it "creates comment notifications, but not mention" do
    Sidekiq::Testing.inline! do
      sign_in commenter
      post comments_path, params: comment_params
      p Notification.count
    end
  end
```
https://github.com/ledestin/dev.to/blob/ledestin/duplicate-notifications-3583/spec/requests/comments_create_spec.rb#L98

Is that a problem with the test setup or there is no notification in this case at all? If there's no notification, what should I use to create a notification?

**Comment by rhymes** [comment]
@ledestin have you tried to see what happens in `CommentsController#create` ? there can be any number of reasons why the notification is not sent. See https://github.com/thepracticaldev/dev.to/blob/c23c4fbb2d5ad331bfc61f8fba1644568e4a806c/app/controllers/comments_controller.rb#L54

I'd put a `binding.pry` there and see what happens

**Comment by ledestin** [comment]
@rhymes thanks, figured that out.

Another question. Can mentions even be created by moderators, given that moderators just choose a response template and the comment text is taken wholly from the response template?
https://github.com/thepracticaldev/dev.to/blob/master/app/controllers/comments_controller.rb#L131

**Comment by ledestin** [comment]
@rhymes seems that mentions by moderators are an edge case. As I understand, response templates aren't modified on each use, and so, if a user was mentioned in the template, and the reply was to that user, this edge case would happen.

**Comment by Zhao-Andy** [comment]
> Can mentions even be created moderators
@ledestin Moderators can submit comments as themselves or as [Sloan](https://dev.to/sloan) (our mascot and generic moderator of sorts). When they're submitting comments as themselves, they can modify the response template.

If they're submitting the comment as Sloan, then they can't modify the response template. Those are templates the DEV team has made. If there was a mention in that made-by-us response template, then a mention would be created.

Given that those moderator response templates are for generic use, I'm doubtful there would be a response template with a mention in it.

Hope that helps!
