### ISSUE TITLE
Organization comments and posts

### ISSUE THREAD

**Issue by shushugah** [thepracticaldev/dev.to#3584]
**Describe the bug**
Despite being in two different URL's, the behaviour is exactly the same, in contrast with individual accounts. 

**To Reproduce**

Create an organisation and go your notifications page. You can select "All" which will generate a URL like this https://dev.to/notifications/org/984, and if you select just the "comments", it will select a URL like https://dev.to/notifications/comments/984 but nothing different will happen. 

**Expected behavior**
It mimics individual account behaviours at the url of https://dev.to/notifications and https://dev.to/notifications/comments

**Screenshots**

![Screen Shot 2019-07-30 at 21 07 23](https://user-images.githubusercontent.com/7111514/62157692-0cf7ef00-b30e-11e9-8bee-8166f762ab35.png)

**Comment by Zhao-Andy** [comment]
Hmm, not sure why that's the case. The URLs are working for me. Could you post a screenshot of `/notifications/comments/984`? Or feel free to email me andy@dev.to if you'd rather keep it private.

**Comment by shushugah** [comment]
screenshot when I visit `/notifications/comments/984`
![Screen Shot 2019-07-30 at 21 24 33](https://user-images.githubusercontent.com/7111514/62158739-7842c080-b310-11e9-9c4d-7fe7e2fa0e60.png)

**Comment by Zhao-Andy** [comment]
Oh, I see the issue now. It's because the code relies on a deprecated way of checking for permissions. Thanks for the report!

**Comment by shushugah** [comment]
This would be my suggested change, I notice there are absolutely no tests for organization notifications, am having a look 
```ruby
  def allowed_user?
    organization = Organization.find(params[:organization_id].to_i)

    @user.org_member?(organization) || @user.admin?
  end
```

**Comment by vaibhavsingh97** [comment]
can i take this up?

**Comment by shushugah** [comment]
Please do!
