### ISSUE TITLE
View reply notifications within the web app

### ISSUE THREAD

**Issue by ShaydeNofziger** [thepracticaldev/dev.to#36]
Currently, users are only notified of replies to their comments/posts via email. It would be useful if there were a feature to view these notifications on the website itself.

**Comment by jessleenyc** [comment]
Hey @ShaydeNofziger! We're in the process of building out notifications -- will keep you posted when it's ready!

**Comment by jessleenyc** [comment]
Hey @ShaydeNofziger! We just added notifications to the site!
