### ISSUE TITLE
Banishing accounts should remove all related data

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/dev.to#3601]
Right now, banishing accounts will remove their chat channel memberships but not their chat channels. Usually banished accounts don't have any chat channels, but if they do their chat channels persist.

We'll want to delete their DM chat channels, as well as any other chat channel memberships related to that. We'll also need to remove them from Algolia before deleting them:
```ruby
banished_account.chat_channels.each do |chat_channel|
  chat_channel.remove_from_index!
  chat_channel.chat_channel_memberships.each do |ccm|
    ccm.remove_from_index!
    ccm.destroy!
  end
  chat_channel.destroy!
end
```

We should also update the `delete_user_activity` method to account for the index removal of the banished account's chat channel memberships:
https://github.com/thepracticaldev/dev.to/blob/9a2c856dd41f6c2370bec0d12c034cdbf3137b1e/app/services/moderator/manage_activity_and_roles.rb#L54

One last thing to remove is the banished account's `BufferUpdate` instances. This is also rare, but can cause issues if they happened to create a suggested tweet.

**Comment by citizen428** [comment]
I'll have a look at this one.

**Comment by citizen428** [comment]
`user.chat_channel_memberships.delete_all ` is already called from [app/services/users/delete_activity.rb:11](https://github.com/thepracticaldev/dev.to/blob/071ec03a3cb9963b38afd84926396ba835e3a55e/app/services/users/delete_activity.rb#L11), so that part is taken care of.
