### ISSUE TITLE
Make Onboarding Compatible With All Themes

### ISSUE THREAD

**Issue by jabawack81** [thepracticaldev/dev.to#3604]
**Describe the bug**
Visiting the onboarding page while logged in and the dark theme makes it unreadable because the text is white on white background

**To Reproduce**
1. Login with a user with dark theme
2. Go to https://dev.to/onboarding

**Expected behaviour**

text is still black

**Screenshots**

<img width="1145" alt="Screenshot 2019-08-02 at 12 28 41" src="https://user-images.githubusercontent.com/432450/62367363-5704ee80-b521-11e9-8fdd-1c95a61b860a.png">

**Desktop (please complete the following information):**

- OS: Mac os
- Browser: Firefox
- Version: 68.0.1

**Comment by jessleenyc** [comment]
Hmm - how did you toggle dark theme before going through onboarding? or how did you trigger onboarding after you've already adjusted your settings? I'm wondering if I'm missing a flow here. We didn't account for the different themes for onboarding because we assumed no one would be on anything but the default thing while they're going through it.

**Comment by jabawack81** [comment]
I already had an account on det.to ([jabawack81](https://dev.to/jabawack81)) and I had a tab open on an article for a couple of days ([Manage your dev.to blog posts from a GIT repo and use continuous deployment to auto publish/update them](https://dev.to/maxime1992/manage-your-dev-to-blog-posts-from-a-git-repo-and-use-continuous-deployment-to-auto-publish-update-them-143j?utm_source=digest_mailer&utm_medium=email&utm_campaign=digest_email)) and when I visited it I've been redirected to the onboarding page.

**Comment by jessleenyc** [comment]
Interesting. This is definitely an edge case but if someone wants to make all themes work with onboarding, that would be much appreciated.

**Comment by jessleenyc** [comment]
In order to toggle onboarding when you're not a first time user, all you have to do is visit dev.to/onboarding!

**Comment by jessleenyc** [comment]
Updated the title for clarity, btw.

**Comment by sgbj** [comment]
I'd like to work on this if no one else is.

**Comment by coolshaurya** [comment]
Or maybe we could remove all theme stylesheets from the onboarding page ?

**Comment by jacobherrington** [comment]
This is something I've found before, I think it'd be great to fix the styles for it to work with all themes.

Go for it @sgbj 😉

There is no harm in fixing this, but for the future, maybe we should discuss if people should be able to go through onboarding again @jessleenyc? I think there is an argument that people might want to change the choices they made during that process.

**Comment by maestromac** [comment]
resolved with https://github.com/thepracticaldev/dev.to/pull/4198
