### ISSUE TITLE
Some deleted posts still exists in api

### ISSUE THREAD

**Issue by emilpriverrc** [thepracticaldev/dev.to#3611]
Hi,

I have som problem with your api. 

I created 1 post which was added to the api. After that did I create 1 more which was not added to the api ( so still 1 post is showing ).
I also added cover_image to the first post which haven’t been added to the post in the api.

The link to my posts: https://dev.to/api/articles?username=emilpriver&page=1

After I have don’t everything did I remove the post as thoose we’re only for testing. And the first 1 post is still in the api. 

Only the first post have been in the api. Never the 2 and the cover_image change.

Love your site 😍

**Comment by talentlessguy** [comment]
I have the same issue. It is because of GitHub cache invalidation, see [this comment](https://dev.to/ben/comment/dl6n)

**Comment by emilpriverrc** [comment]
@talentlessguy does dev.to use github pages?

**Comment by talentlessguy** [comment]
> @talentlessguy does dev.to use github pages?

No, it doesn't. I think this is because I logon using GitHub. My friend who logon with Twitter doesn't experience such bug.

**Comment by emilpriverrc** [comment]
Aha, I logged on with github aswell

**Comment by rhymes** [comment]
Definitely a caching problem.

I took a quick glance and right now we're using Fastly's edge caching on the index (which is where https://dev.to/api/articles?username=emilpriver goes).

This means that the index API is cached for a a while, which is 1 day according to the [fastly initializer](https://github.com/thepracticaldev/dev.to/blob/master/config/initializers/fastly.rb)

**Comment by CodeSpent** [comment]
Is there anything that can be done in the meantime to counter this caching?

**Comment by rhymes** [comment]
@CodeSpent are you still experiencing deleted posts to be present in the API?

**Comment by CodeSpent** [comment]
@rhymes yeah I am seeing changes take ~24 hours to reflect on any client I use (site, rest client, browser).

**Comment by rhymes** [comment]
@CodeSpent FYI now this should be fixed, thanks for the patience!
