### ISSUE TITLE
find_by_* methods are deprecated

### ISSUE THREAD

**Issue by araslanov-e** [thepracticaldev/dev.to#364]
By code is often used find_by* methods, they are deprecated
https://edgeguides.rubyonrails.org/4_0_release_notes.html#active-record-deprecations

**Comment by araslanov-e** [comment]
@benhalpern https://www.quora.com/Why-is-find_by_attributes-deprecated-from-rails, https://stackoverflow.com/questions/23921780/in-rails-4-find-by-is-deprecated-so-how-do-you-cope-with

**Comment by Zhao-Andy** [comment]
@araslanov-e I think based on what you linked though, the exceptions are `find_by_*`:
> All dynamic methods **except** for find_by_... and find_by_...! are deprecated.

**Comment by rhymes** [comment]
Yep, just those two forms are deprecated. 

I grepped through the source code and there are no instances of deprecated dynamic methods in usage... I think this can safely be closed

**Comment by araslanov-e** [comment]
Oops
