### ISSUE TITLE
For series with several entries, horizontal-scroll entry dots 

### ISSUE THREAD

**Issue by msarit** [thepracticaldev/dev.to#3643]
**Is your feature request related to a problem? Please describe.**
While I *love* the "Series" feature on Dev.To, for series with a lot of entries (eg Daily Algorithm Challenge), the circles indicating each series entry take up considerable space, and become overwhelming to navigate.

**Describe the solution you'd like**
I think that, for series with a number of entries above a certain threshold (like 10), the circles become horizontally scrollable, conserving space.

**Describe alternatives you've considered**
An alternative solution would be to display the circles for the most recent 10 series entries, then display a link to a page that displays every entry as a list.

**Additional context**
This is a depiction of my proposed solution. Clicking the arrows scrolls the set of circles to the left or to the right.

![Untitled design (1)](https://user-images.githubusercontent.com/32520970/62553887-2b924480-b83e-11e9-9dd8-115830443880.png)

**Comment by jessleenyc** [comment]
I think we need to redesign series in general and will take this into consideration when we do so. Leaving the issue open to welcome more discussion/suggestions!

**Comment by jessleenyc** [comment]
Hey @msarit! Thanks again for the issue. We just did a redesign for series and are no longer using dots, so I'm going to close this issue. Here's an example of it in action: https://dev.to/devteam/daily-challenge-43-boardgame-fight-resolver-53e3
