### ISSUE TITLE
DEV, are you drunk? Website is unresponsive...

### ISSUE THREAD

**Issue by CalinZBaenen** [thepracticaldev/dev.to#3647]
I am using dev.to but when I try to write a new post it gives me errors, same thing when I try to chat with someone, I can't even like someone's post... When I open the console I get errors similar to this:
```
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure resource '<URL>'. This request has been blocked; the content must be served over HTTPS.
```
this:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
```
and this:
```
Failed to load resource: the server responded with a status of 500 ()
```

**To Reproduce**
Click "Write A Post"

I expected the "New Post" area, to write a post. But got errors instead.

![2019-08-06_18-45-20](https://user-images.githubusercontent.com/50878485/62584732-6ff00580-b87b-11e9-84be-0c39d26c1d34.png)

**Desktop (please complete the following information):**

- OS: Windows 10 (Home / Business)
- Browser: Google Chrome
- Version: 76.0.3809.100 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: N/A
- OS: N/A
- Browser: N/A
- Version: N/A

https://dev.to/new

**Comment by jessleenyc** [comment]
Hi, this seems like an individual account issue - can you please email yo@dev.to from the email your DEV account is associated with?
