### ISSUE TITLE
Markdown not rendering backticks correctly

### ISSUE THREAD

**Issue by achasveachas** [thepracticaldev/dev.to#3648]
**Describe the bug**

There seems to be an issue with displaying backtick literals in code blocks.

I'm writing a blog post with markdown tips so naturally I would like to include examples that inclde backticks and none of the recommended ways of displaying backticks seem to work.

I tried following the recommendations provided [here](https://meta.stackexchange.com/questions/82718/how-do-i-escape-a-backtick-within-in-line-code-in-markdown) and [here](https://meta.stackexchange.com/questions/82718/how-do-i-escape-a-backtick-within-in-line-code-in-markdown), but I can't get the behavior they are describing.

Specifically, trying to render three backticks in inline code seems to be broken:
```` Something like: (`` ``` ``)```` I would expect to render like: Something like (`` ``` ``) but in the DEV editor it comes out like: Something like (` ` `).

Similarly when trying to display three backticks insode a code block things break down.

The following markdown:
`````
````
```
//some code goes here
```
````
`````
I'd expect to render like:

````
```
//some code goes here
```
````

But instead it renders on DEV like:
```
```
//some code goes here
```
```

**To Reproduce**
Open the new post editor (I tried it both in v2 and v1 of the editor) and paste in the markdown examples I provided above. 

Press "Preview".

**Expected behavior**

I expect the markdown to display per the specifications mentioned above with the backticks rendering as expected.

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: Firefox
- Version: 68.0.1

**Additional context**

It seems like an issue was already opened for this (https://github.com/thepracticaldev/dev.to/issues/1284). The last comment there seems to indicate that the issue was fixed, but I'm still encountering it now. I don't know if tis is a regression or perhaps my examples are a bit different than the one they provided.

**Comment by kingthorin** [comment]
Backslash backtick seems to escape: &#92;&#96; ex: \` 

Or you could use the HTML entity? `&#96;`  ex:  &#96;

**Comment by achasveachas** [comment]
I'm not at my computer, but I tried both of those on DEV and they didn't work. I think the backslash worked for one backtick, but not when I wanted to do three, and the HTML entity just rendered as it...

**Comment by jbristow** [comment]
Posting my more complicated examples that break formatting from #1284 for aids in testing:

### Single Deep
````markdown
Hello, I am `` `__` `` and I am happy to meet you!

My friend `` `foo` `` is also here!

Watch out! `` `bar`.explosion() ``

Oh no! `` chunk(`baz`) ``

And now for some more code!
```prolog
parent(charles1, james1).
parent(elizabeth, james1).
```
Some closing remarks.
````

### Recursive
`````markdown
````markdown
Hello, I am `` `__` `` and I am happy to meet you!

My friend `` `foo` `` is also here!

Watch out! `` `bar`.explosion() ``

Oh no! `` chunk(`baz`) ``

And now for some more code!
```prolog
parent(charles1, james1).
parent(elizabeth, james1).
```

Some closing remarks.
````
`````

**Comment by katestud** [comment]
👋 I have a possible fix here, but would love to hear whether this seems like the right approach!
