### ISSUE TITLE
 Command ["bin/rails db:setup"] failed

### ISSUE THREAD

**Issue by rehmatworks** [thepracticaldev/dev.to#3657]
When I attempt to install the dev.to on my Ubuntu 18 server, everything works fine until the database setup:

```bash
== Preparing database ==
rails aborted!
NoMethodError: undefined method `reject' for #<String:0x0000564117260b70>
/root/dev.to/config/application.rb:22:in `<module:PracticalDeveloper>'
/root/dev.to/config/application.rb:21:in `<main>'
/root/dev.to/Rakefile:4:in `<main>'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)

== Command ["bin/rails db:setup"] failed ==
```

Can anyone please help me out?

**Comment by rhymes** [comment]
What version of Ruby are you using? 

Also, keep in mind that DEV is not completely ready for self installation yet, even if we're working towards that.

The `db:setup` step should work nonetheless.

**Comment by rehmatworks** [comment]
@rhymes Ruby version is `ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]`

**Comment by maestromac** [comment]
Hello @rehmatworks , did you follow the steps outlined in this doc https://docs.dev.to/installation/linux/ ?

**Comment by rehmatworks** [comment]
@maestromac Yep, I followed each and every step precisely.

**Comment by rhymes** [comment]
@rehmatworks what version of PostgreSQL are you using? Can you check if your `DATABASE_URL` is correctly configured? https://docs.dev.to/installation/postgresql/

**Comment by rehmatworks** [comment]
@rhymes Yep, I re-did the install and followed every step precisely but again the same issue.

**Comment by rhymes** [comment]
@rehmatworks what version of PostgreSQL are you using? What is contained in the `DATABASE_URL`?

**Comment by rehmatworks** [comment]
@rhymes it was postgres 10.x and the database URL contained the username and password along with the database host. BTW I deleted the VPS. I'll wait for a bug-free and stable release of DEV. Currently, it is a nightmare to get this working.

**Comment by rhymes** [comment]
@rehmatworks there are kinks on self hosting yes. It's also [not supported right now](https://docs.dev.to/self-hosting/).

In the meantime you might want to try GitPod if you'd like to play with the code but don't want to install anything: https://docs.dev.to/installation/gitpod/

Thanks for the patience!

**Comment by rehmatworks** [comment]
@rhymes Thank you for your support. I'll give GitPod a try. I'm not a Ruby developer and I only know PHP (fluent) and Python. I wanted to use this for my programming-related blog. Love the CMS. Waiting for it's stable release.

**Comment by maestromac** [comment]
Best of luck with Gitpod!

Closing.
