### ISSUE TITLE
Icon too square on PWA 

### ISSUE THREAD

**Issue by thomasbnt** [thepracticaldev/dev.to#3658]
**Is your feature request related to a problem? Please describe.**
Icon square on PWA is too square. 
![image](https://user-images.githubusercontent.com/14293805/62713064-63df8180-b9fc-11e9-8c7f-c14f3e213745.png)

**Describe the solution you'd like**
Add `border-radius` to make him fit in better?

Have a good day, and good dev!

**Comment by jessleenyc** [comment]
heh yep, thanks for flagging! closing this issue in favor of the previously reported on 😅  https://github.com/thepracticaldev/dev.to/issues/1999

**Comment by thomasbnt** [comment]
oh sorry, I didn't read this report. Thanks!
