### ISSUE TITLE
Account for different themes with sponsor logos

### ISSUE THREAD

**Issue by pkfrank** [thepracticaldev/dev.to#3662]
**Is your feature request related to a problem? Please describe.**
As a user, I'd like to see all sponsor logos displayed properly regardless of theme.

**Describe the solution you'd like**
On `/sponsors` and elsewhere (homepage, tag pages), the logos display properly no matter which theme the end-user has chosen.

**Additional context**
I believe we already have a `dark nav image` for Gold sponsors, but we'll need to add this for all sponsor types.

**Comment by jessleenyc** [comment]
If anyone wants to get to this before the core team does, please share what your plan is!

**Comment by jessleenyc** [comment]
I believe this was fixed in #3719
