### ISSUE TITLE
Support Webhooks Integration

### ISSUE THREAD

**Issue by maestromac** [thepracticaldev/dev.to#3665]
**Is your feature request related to a problem? Please describe.**

Having Webhooks would be a simple way to support external integration. The possibilities are endless!

**Describe the solution you'd like**

Rough thoughts: Webhook model should associated with user and maybe Doorkeeper's application.

- User's settings page should have a Webhooks section, listing all the registered Webhooks.
- Webhooks should have exponential backoff when dealing with failures.
- ???

Please let me know if there's a detail I've missed.

**Describe alternatives you've considered**

a gem ? I can't seem to find any though.

**Additional context**

n/a

**Comment by rhymes** [comment]
Closing this in favor of https://github.com/thepracticaldev/dev.to/issues/3715
