### ISSUE TITLE
Querying /api/articles for actual articles and not discussions, or specific collections of articles

### ISSUE THREAD

**Issue by cdvillard** [thepracticaldev/dev.to#3668]
**Is your feature request related to a problem? Please describe.**

When querying the DEV Articles API, if someone wants to display just articles without the `#discuss` tag, it involves extra work to filter out just the wanted data. For example, in [writing a GraphQL data source for a Gridsome project][1], I resorted to tagging myself in the articles I wanted to bring into GraphQL so I wouldn't have to filter through the articles on build. This may feel inconsequential, but given retrieving each article's content requires an individual GET request from `/api/articles/${id}`, it's an implicit quality-of-life benefit to not have to do that.

**Describe the solution you'd like**

An ideal solution would be to be able to query for just articles, so potentially an optional flag in the query string returning all articles without the `#discuss` tag, or an optional flag of `nottagged` to ignore articles with specific tags. This would move the work of filtering out and sending only the desired data to DEV's server instead of placing the burden on the developer.

**Describe alternatives you've considered**

While I can't imagine it would be exponential, it's understandable that the desired solution will likely come with extra cost to server resources. An acceptable alternative would be the ability to filter or even query using the `series` property. This is already a property exposed by the DEV API's create functionality, so it would make sense to be able to query against it as well.

**Additional context**
1. https://github.com/cdvillard/cdvillard/blob/master/gridsome.server.js

[1]:    https://github.com/cdvillard/cdvillard/blob/master/gridsome.server.js

**Comment by rhymes** [comment]
Thanks @cdvillard - I think you're bringing up an interesting point. Right now you can only filter by tag, but not exclude tags. 

Let me know if your issue is would consistute a duplicate of https://github.com/thepracticaldev/dev.to/issues/3654 - if so it'd be great if we could move your comment there and keep up the other discussion.

Thank you!

**Comment by cdvillard** [comment]
@rhymes, you're correct, for the most part. I do feel though that the series property should also be exposed as an endpoint somehow, so I'll look into an individual issue for that.
