### ISSUE TITLE
Locally-cached draft supercedes more recent drafts from other devices

### ISSUE THREAD

**Issue by thepeoplesbourgeois** [thepracticaldev/dev.to#3670]
## Description

When working on a draft, locally-cached changes can fall out of sync if a user makes edits from a different device. I'm unsure if the issue is present when working through the API, but it would most likely depend on how the client handles refreshing its cache.

## To Reproduce

1. Begin a new post on the dev.to website and add some content
1. Click/tap `save draft`
1. Close the browser, go have a coffee or something
1. Open the draft within dev.to on another device and make some changes, possibly while drinking your coffee
1. Click/tap `save draft`
1. Return to dev.to on the first device
1. From your dashboard, click/tap `edit`

### Expected behavior

Changes made on the second device should appear within `textarea.articleform__body`.

### Actual behavior

`textarea.articleform__body` retains the earlier version of the post content.

**Desktop (please complete the following information):**
no u

**Smartphone (please complete the following information):**
still not a fan of this idea

## Additional Context

- This bug can erase a good amount of work if the user has substantially updated the draft from device no. 2, then makes a change back on device no. 1
- The rendered version of the draft will reflect the most recent updates, only the `edit` page is affected
- Clearing the cache for dev.to within the browser, logging back in, and then navigating back to the `edit` page will fetch the latest version of the plaintext

**Comment by thepeoplesbourgeois** [comment]
Oh, flerf me to flerfing h*ck and back again, you don't even need to go to a second device as long as you have two _**tabs**_ open and accidentally make a change to the earlier version of the draft

**Comment by thepeoplesbourgeois** [comment]
Thank gosh I was able to recover my edits with good ol' copy pasta >_>

**Comment by jessleenyc** [comment]
Ah shoot. That's frustrating, thanks for flagging this issue.

**Comment by thepeoplesbourgeois** [comment]
Thank you as well! I'm very grateful for your sympathy 😌

**Comment by Almenon** [comment]
Just ran into this problem - I was writing an article on my laptop, saved it, closed the tab, went over to my desktop, added some notes to the same article, then realized my desktop had an outdated version that I just saved over the laptop version. Luckily even though I closed the tab I control-shift-t'd to reopen it and it still had my changed content.

Ideally if this is fixed a banner would be displayed saying the local version is different than the saved version. And what would be _really_ cool is if a package like https://praneshravi.in/react-diff-viewer/ was used to display the difference.

**Comment by jpeg729** [comment]
I even tried deleting all site data in the Chrome devtools Application tab, and it still didn't help.
Then I tried leaving devtools open and ticking "Disable cache" in the network tab, and that helped, a bit. I get a flash of the up-to-date content, then the old draft replaces it.

## Further investigation

* The request to /{user}/{slug}/edit url contains the right data, and when I reload the edit page.
* The old draft is stored in localstorage under the key "editor-v2-https://dev.to/{user}/{slug}/edit".
