### ISSUE TITLE
Post series icons are not well visible on dark mode

### ISSUE THREAD

**Issue by Kurtz1993** [thepracticaldev/dev.to#3674]
Today, I was reading an article that is part of a series. I've found that the circles uses to represent the series are not very accessible in dark mode. The circle that corresponds to the current post, is too dark (see screenshot below)

![F95EA833-349F-4B41-9D0A-EA438D597B14](https://user-images.githubusercontent.com/5412470/62817914-367dfb00-bb04-11e9-87bc-ece541284402.png)

This is only happening in dark mode

**Comment by jessleenyc** [comment]
Thanks for flagging. Whoever takes this, let's make sure the button colors are updated so they work well for all themes.

**Comment by Kurtz1993** [comment]
I can take this issue, but which colour will be the right to use?

**Comment by jessleenyc** [comment]
@Kurtz1993 here's some info on theming: https://docs.dev.to/design/theming/

As for which color, do you want to make a suggestion? I'd think we'd want the 'unselected' series dots to be darker, closer to the background, and then the 'selected' dot to be brighter, like a light gray. I'd try to use colors already used in the codebase. You'll find some in `variables.scss`

**Comment by Kurtz1993** [comment]
What do you think about these colours?
I'm just tweaking the current styles by changing the current variable.
![ezgif-2-b6b022304262](https://user-images.githubusercontent.com/5412470/63062545-fda4a400-bebe-11e9-8cd2-2f89060132d8.gif)

**Comment by jessleenyc** [comment]
@Kurtz1993 looks good to me!

**Comment by Kurtz1993** [comment]
The PR is merged now. I think we can close the issue 😃
