### ISSUE TITLE
Unable to archive or delete because page is missing

### ISSUE THREAD

**Issue by livanjimenez** [thepracticaldev/dev.to#3677]
**When trying to click on the link the post was removed or deleted yet stayed on my reading list.**

![1](https://user-images.githubusercontent.com/28581256/62823884-71b01680-bb64-11e9-8192-51aa446c7a17.PNG)

**After clicking to check if post is available:**

![4](https://user-images.githubusercontent.com/28581256/62823899-ade37700-bb64-11e9-8736-13d28ac508e9.PNG)

**Then I tried to archive the post, it disappears and reappears afterwards.**

![2](https://user-images.githubusercontent.com/28581256/62823887-74ab0700-bb64-11e9-9078-e25a417b6b01.PNG)

![3](https://user-images.githubusercontent.com/28581256/62823935-234f4780-bb65-11e9-9e1c-1ab8942ceaab.PNG)

**Comment by rhymes** [comment]
This is probably related to #1641 

I too have posts I can't remove from my reading list because they have been deleted afterwards

**Comment by livanjimenez** [comment]
> 
> 
> This is probably related to #1641
> 
> I too have posts I can't remove from my reading list because they have been deleted afterwards

Definitely!
I was trying to find a way to fix it in the source code but I didn't want to go in blind,
thanks for the link

**Comment by jessleenyc** [comment]
Ah yeah, this does seem like the same issue as #1641. I'm going to close this one in favor of the original. I'll leave a note that this is also affecting the archive functionality. Thanks @livanjimenez!
