### ISSUE TITLE
Chat - Be able to load previous chat history

### ISSUE THREAD

**Issue by omenking** [thepracticaldev/dev.to#3684]
**Is your feature request related to a problem? Please describe.**

When using the chat history there is a limit on the shown messages. So when I scroll back to get information such as contact details I can no longer access it.

**Describe the solution you'd like**

- [ ] A button that loads the last 100 messages or load 100 more messages on infinite scroll

**Describe alternatives you've considered**

**Additional context**

**Comment by jessleenyc** [comment]
Let's go the button route for now instead of listening for infinite scroll.

**Comment by pchpsky** [comment]
can I take this issue?

**Comment by jessleenyc** [comment]
@pchpsky sure can!

**Comment by JSSaini07** [comment]
@pchpsky I'd like to pick this up if you are not working on it :) cc: @jessleenyc

**Comment by pchpsky** [comment]
@JSSaini07 take it

**Comment by artoodeeto** [comment]
@JSSaini07 yow my dude you still working on this one bro?

**Comment by JSSaini07** [comment]
@artoodeeto nope, couldn't get the time. Feel free to pick it up!

**Comment by manan30** [comment]
@artoodeeto Are you working on this?

**Comment by artoodeeto** [comment]
@manan30 sorry dude just notice this today. you can work on this. I working on something else.

**Comment by manan30** [comment]
@artoodeeto Cool. @jessleenyc Can I work on this?

**Comment by maestromac** [comment]
go ahead @manan30 !

**Comment by manan30** [comment]
Am I reading this wrong or should the **project is running** line in the picture be `localhost:3000`?
![logs](https://user-images.githubusercontent.com/12088143/68829137-d7390500-0675-11ea-8430-d10cc9ca094e.png)

**Comment by rhymes** [comment]
@manan30 that's the port webpacker runs on, check the lines with `web.1`, you'll eventually see one with Rails saying it's running on port 3000

**Comment by manan30** [comment]
@rhymes Gotcha. Thanks a lot

**Comment by artoodeeto** [comment]
@manan30 hello. whats terminal are you using? or is that a shell? is that ohmyzsh?

**Comment by manan30** [comment]
@artoodeeto I am using **iTerm2** and it is running **Z Shell**. And I use `antibody` to load all the plugins.

**Comment by Mourtadah** [comment]
hey, @manan30 are you still working on this? I would love to give it a shot.

**Comment by maestromac** [comment]
We appreciate your enthusiasm @Mourtadah but this was just resolved.

Resolved with https://github.com/thepracticaldev/dev.to/pull/4903
