### ISSUE TITLE
As a new user, I want to read the CoC and ToU without completing the onboarding.

### ISSUE THREAD

**Issue by jwfuller** [thepracticaldev/dev.to#37]
Steps to reproduce:
1. Create new account by linking to GH.
2. Do not complete the onboarding.
3. Visit the homepage.
4. Click 'Code of Conduct'

Expected
See CoC

Actual
Redirect to form prompting for email and bio.

**Comment by jessleenyc** [comment]
Hi @jwfuller! This issue is fixed, thanks for flagging :)
