### ISSUE TITLE
Feature Request: night mode

### ISSUE THREAD

**Issue by yassinebridi** [thepracticaldev/dev.to#372]
## Feature Request
A dark theme.
### User Story / Description
I mostly visit your website during the night, and as you may know, reading in the night with a light theme can be agonizing, it would be really great to have a night mode feature like Reddit has.
### Definition of Done
I don't know what that means actually 🤣 .
-------

**Comment by benhalpern** [comment]
Thanks @diogomqbm, we'll close the issue in favor of the other one.
