### ISSUE TITLE
Onboarding: can't toggle the email options by clicking the label

### ISSUE THREAD

**Issue by revolter** [thepracticaldev/dev.to#3720]
**Describe the bug**

Clicking the texts of the email preferences options doesn't toggle the corresponding checkboxes, while doing the same for the first 2 options does work.

**To Reproduce**

**Expected behavior**

Clicking any text next to a checkbox should toggle it.

**Screenshots**

<img width="783" alt="image" src="https://user-images.githubusercontent.com/5748627/63045537-3d788500-bed9-11e9-89b3-c2c48509f347.png">

**Desktop (please complete the following information):**

- OS: macOS 10.14.5 (18F203)
- Browser: Safari
- Version: 12.1.1 (14607.2.6.1.1)

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by jessleenyc** [comment]
Yeah, that makes sense!

**Comment by rhymes** [comment]
For whomever takes this, the code is likely in https://github.com/thepracticaldev/dev.to/blob/master/app/javascript/onboarding/components/EmailListTermsConditionsForm.jsx

**Comment by theaupoulat** [comment]
Hey, can I take it ?

**Comment by rhymes** [comment]
@theaupoulat go ahead and thank you!
