### ISSUE TITLE
Blank space in badge section on Profile

### ISSUE THREAD

**Issue by PJijin** [thepracticaldev/dev.to#3724]
**Describe the bug**

Badge not placed properly in the account page. Looks like the badge image width cause the issue. The whitespace is show in some account only.

<img src="https://i.imgur.com/bbpLlfa.png" />

**To Reproduce**

 
 1. Go to https://dev.to/ben
 2. Check the badges widget

**Expected behavior**

<img src="https://i.imgur.com/JUUD4qO.png" />

**Desktop (please complete the following information):**

- OS: MacOs
- Browser: Chrome 
- Version: 76.0.3809.100
 
**Additional context**

The space issue is on the mobile version too.

**Comment by jessleenyc** [comment]
I actually think this is intentional but I'll triple check with the rest of the team at our next meeting.

**Comment by jessleenyc** [comment]
Hey all - so this is behaving as expected but we're open to adjustments if someone wants to contribute a PR that loses the spacing here. The goal was for this to look a bit random/uneven, as you'd see in a real 'sticker book' so as long as the stickers don't end up uniform, we'd welcome any PRs.
