### ISSUE TITLE
Missing menu border

### ISSUE THREAD

**Issue by Amorpheuz** [thepracticaldev/dev.to#3726]
**Describe the bug**

Menu in night theme looks like it has a missing border to it's right. It works correctly in mobile, tablets and low resolution screen scenario where the menu hugs the top-right corner and hence border being cut-off is consistent with the other themes, but looks bad on a desktop where it is abruptly cut-off.

A similar issue is also present in pink, but it only becomes clearly visible when you click on the menu, which probably most won't do unless they are using a touchscreen device. All themes do have an inconsistent border-radius though... which again isn't that easily visible unless you actually click.

**To Reproduce**

1. Go to dev.to
2. Log into the website. (Not sure whether we can switch to dark theme without logging in)
3. Click on your profile picture to open menu.

**Expected behavior**

The white border consistently travels from top-left -> bottom -> top-right while having rounded bottom corners.

**Screenshots**

- night theme
![test](https://user-images.githubusercontent.com/22113778/63109686-67987880-bfa7-11e9-9008-d59785ebad4d.png)

- default theme
![image](https://user-images.githubusercontent.com/22113778/63109460-e8a34000-bfa6-11e9-99a0-80bd2cfca8d9.png)

- pink theme
![test2](https://user-images.githubusercontent.com/22113778/63110601-74b66700-bfa9-11e9-9fc4-8e5fa75b2e48.png)

- minimal while theme
![image](https://user-images.githubusercontent.com/22113778/63110762-c65ef180-bfa9-11e9-9afe-23b54fd3e5b2.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version:  76.0.3809.100

**Smartphone (please complete the following information):**

- Device: Nokia 6.1
- OS: Android 9
- Browser: Chrome
- Version: 76.0.3809

**Additional context**

**Comment by jessleenyc** [comment]
Here's the docs on theming for anyone who wants to work on this issue: https://docs.dev.to/design/theming/

**Comment by Amorpheuz** [comment]
Great, its a good first issue! I think this shouldn't take much know-how, if any, in ruby department. I am faily confident in my front-end skills... mind if I take it up?

**Comment by jessleenyc** [comment]
@Amorpheuz go for it!
