### ISSUE TITLE
Print layout/button

### ISSUE THREAD

**Issue by dEhiN** [thepracticaldev/dev.to#3728]
**Is your feature request related to a problem? Please describe.**
I recently read an article on dev.to and when I tried to print it, in the print preview I saw that article content was being cut off due to the persistent header and footer. I don't even mind that a page's header/footer get printed, but for some reason, the header and footer was cutting off some article content on every single page! I tried printing from my Android phone using the share button on Google Chrome and selecting my printer print service app/plugin, and I also tried printing from my Windows 10 laptop using Google Chrome. Both print previews showed the same problem. This could possibly be a problem with Google Chrome, but I have never had this issue arise on any other website, including other sites with header and/or footers.

**Describe the solution you'd like**
I think having a specific print button along the footer (similar to the Twitter, reading list, unicorn and heart buttons) that generates a simplified print layout would be a good solution. To me, a simplified print layout would be one that contains the article title, content and graphics, but leaves out the page header and footer and also skips any article comment.

**Describe alternatives you've considered**
I didn't consider any alternatives because the only other alternative would've been to select and copy all the article content (including title) and paste it into a text editor of some sort, and print it that way. However, that is too much work and unnecessary in my opinion.

**Additional context**
No additional context.

**Comment by rhymes** [comment]
Hi @dEhiN, you make a good point about printing. 

I wonder if instead of having a button, we should aim at having a print stylesheet for the article page.

This way we can control via CSS what appears in the print, remove unnecessary boxes and even possibly stylize the print.

This should also work on all devices automatically.

**Comment by Link2Twenty** [comment]
Adding a style sheet for printing isn't a bad idea, there'd need to be a discussion about which part to keep and which bits to remove. Like do we need the series list, maybe? Also comments? There might be several pages of comments which the user may or may not want.

[print example](https://github.com/thepracticaldev/dev.to/files/3590502/Native.HTML_.Lazyloading.Revisited.-.DEV.Community._._.pdf)

**Comment by Yiddishe-Kop** [comment]
One thing that is really important & easy to fix:
When printing dev.to articles - the header & footer appear on every page, & obstruct the body text.
See screenshot of print preview:
<img width="476" alt="Screenshot 2019-10-05 at 8 33 07 pm" src="https://user-images.githubusercontent.com/36875437/66258576-851bde80-e7af-11e9-8048-0589cda9facf.png">

An easy fix would be something like this in the css:
```css
@media print {
   .top-bar, .article-actions {
      display: none;
   }
}
```
This is such an easy fix to such an annoying problem...
I wanted to do a pull-request myself, but the installation steps look too intimidating 😷...

**Comment by nickytonline** [comment]
Check out docs.dev.to for installing things. You can also install it via gitpod, https://dev.to/ben/spin-up-a-local-instance-of-dev-in-the-cloud-with-gitpod-it-s-incredibly-simple-pij, which does all the heavy lifting for you.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/4249
