### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by enjoyindonesiadotcom** [thepracticaldev/dev.to#3735]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by jessleenyc** [comment]
Seeing as there's no information on this issue, I'm going to close it.
