### ISSUE TITLE
Image Upload On Comments Throwing 500 Error

### ISSUE THREAD

**Issue by omenking** [thepracticaldev/dev.to#3769]
**Describe the bug**

Uploading any image results in 500 error. Here is the image in question I was attempting, but it doesn't work for any images:

This is the image in question you can test with:

![health-check](https://user-images.githubusercontent.com/7776/63293682-9d36ad80-c296-11e9-9f65-4d0e63fb52d8.png)

Here you can see 500 errors, nothing super exciting or informative.

![Screen Shot 2019-08-19 at 3 32 18 PM](https://user-images.githubusercontent.com/7776/63293710-af185080-c296-11e9-9848-caaf98c8bcf4.png)

![Screen Shot 2019-08-19 at 3 32 21 PM](https://user-images.githubusercontent.com/7776/63293716-b2abd780-c296-11e9-9faa-53faccbe9caa.png)

**To Reproduce**

Upload an image

**Expected behavior**

Should upload an image

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by Zhao-Andy** [comment]
Thanks for the heads up, we'll look into it now.

I uploaded via the article editor and it worked, so it seems the comment upload itself is broken. Here's the markdown for your image in case you wanted to post your comment: `![Alt Text](https://thepracticaldev.s3.amazonaws.com/i/mdrjk3fvicyvks734o0l.png)`

**Comment by Zhao-Andy** [comment]
Resolved via #3771 :) Thanks again for the report!
