### ISSUE TITLE
Feature Reqeust: Make series Title linkable to a "Series" langing page.

### ISSUE THREAD

**Issue by seangwright** [thepracticaldev/dev.to#3772]
**Is your feature request related to a problem? Please describe.**

### Feature Request

I really appreciate the [new UX that was added](https://github.com/thepracticaldev/dev.to/pull/3768) for showing series at the top and bottom of series posts.

Thanks @benhalpern 🙏.

This is really great on series with a bunch of posts (I currently have a series with 11 entries).

Since these longer series abbreviate the list to fit the content, it would be awesome of the Title of the series at the top of the list linked to a "Series" landing page which listed all the series out with a bit.

**Describe the solution you'd like**

Maybe this landing page could look like the post list on the homepage?

**Describe alternatives you've considered**

I know this is going to be a niche request since it doesn't seem like most authors write series or if they do the series have fewer posts.

I also realize the Series list at the top of a post can be expanded, but date published, tags, summary are not listed.

There's also my feature request (linked below) to have a Series Liquid Tag - this tag would probably need a place to link to?

**Additional context**

Link location:
![dev-to-series-link-request](https://user-images.githubusercontent.com/1382768/63300326-f528e080-c2a5-11e9-9d7d-6997caadfcde.jpg)

### Related issues

https://github.com/thepracticaldev/dev.to/issues/3046

**Comment by jessleenyc** [comment]
Hey @seangwright - thanks for this request! We actually already have an issue about this so I'm going to close this one in favor of the original: https://github.com/thepracticaldev/dev.to/issues/2424
