### ISSUE TITLE
I cannot update my Dev.to profile.

### ISSUE THREAD

**Issue by sarah-alfred** [thepracticaldev/dev.to#3775]
I am trying to update my Dev.to profile and whenever I click submit to save the changes. I get an error saying. I am not changing the Github username, and BTW that is my GitHub username.

I signup/sign in using Twitter, which is the same username as my GitHub.

**Comment by jessleenyc** [comment]
Hi @sarah-alfred, sorry your experiencing this. Since this seems like a specific account issue, can you email yo@dev.to from the email associated with your DEV Profile? Thanks!
