### ISSUE TITLE
I can't write a new Post

### ISSUE THREAD

**Issue by Edge-Developer** [thepracticaldev/dev.to#3791]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by jessleenyc** [comment]
Hi @Edge-Developer - please email yo@dev.to with the email address associated with your DEV account. This seems like an individual account issue that our support team can help you with.
