### ISSUE TITLE
GitPod: Webpacker::Manifest::MissingEntryError in Stories#index

### ISSUE THREAD

**Issue by jankeromnes** [thepracticaldev/dev.to#3795]
**Describe the bug**

Hello! 👋 When I open Dev.to in Gitpod; enter my Algolia credentials; and hit Enter, the web app shows this error:

```
Webpacker::Manifest::MissingEntryError in Stories#index
```

But after trying again / refreshing for about 2 minutes, it starts working.

**To Reproduce**

1. Open [Dev.to in Gitpod](https://gitpod.io/#https://github.com/thepracticaldev/dev.to)
2. When prompted, enter your Algolia credentials into the config file; save; and hit enter in the console to continue
3. The web preview opens, but shows the aforementioned error, instead of the Dev.to app

**Expected behavior**

The Dev.to app should be displayed properly

**Screenshots**

Here is a screencast showing the problem: https://www.youtube.com/watch?v=hw98A_4Xu88

**Desktop (please complete the following information):**

- OS: Ubuntu Disco 19.04
- Browser: Firefox
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hi @jankeromnes, can you try again to see if the error persists? I've just tried with Firefox 69 on macOS and after adding my credentials everything worked smoothly. It might have been a GitPod bug, let me know.

Thank you!

**Comment by rhymes** [comment]
Closing this because I'm quite sure Gitpod has been working for months since this one was opened
