### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Angelgeo** [thepracticaldev/dev.to#3796]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by jessleenyc** [comment]
Closing this because there's no information in the issue.
