### ISSUE TITLE
Change in Algolia under DEV docs > Backend Guide > Algolia

### ISSUE THREAD

**Issue by dhanoz** [thepracticaldev/dev.to#3799]
### Description
Recently I was setting up my development environment so I can help to contribute. While setting up my environment I got a different webpage rather than the screenshot which is mentioned under DEV docs > Backend Guide >Algolia on step 7.
### Issue
![Screenshot from 2019-08-22 19-30-41](https://user-images.githubusercontent.com/51912296/63521067-615c4c00-c513-11e9-9e31-a2a66c8b07d0.png)

### Needs to get updated
The screenshot of the webpage that needs to get changed under step 7.
 
![Screenshot from 2019-08-22 16-31-35](https://user-images.githubusercontent.com/51912296/63521078-67eac380-c513-11e9-9d1c-3d13b2b866e1.png)

**Comment by jessleenyc** [comment]
Cool, thanks for the heads up. Feel free to submit a PR if you'd like!

**Comment by dhanoz** [comment]
**Updated image**
![Git](https://user-images.githubusercontent.com/51912296/63767468-5f1b3880-c8eb-11e9-88c3-7b14774b684d.png)
