### ISSUE TITLE
As a new user, I would like to get a sense of what content is available on the site

### ISSUE THREAD

**Issue by jwfuller** [thepracticaldev/dev.to#38]
Given the fuzziness of terms in our industry (Is it Angular, AngularJS, or Angular2?), I would like to browse a list of tags that are in use.

It would be nice to sort alpha, use count, 'hotness'

**Comment by jessleenyc** [comment]
Hey @jwfuller! Thanks for the feedback. We updated the site to show a list of trending tags on the home feed.
