### ISSUE TITLE
Dashboard for authors to create their own "series"

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/dev.to#380]
## Feature Request or Task
A dashboard for creating and modifying "series". In the dashboard or edit views, there should be an "add to series" button that brings you to the view. Under the hood we already have this capability but we don't yet have a user interface.
### User Story / Description
As a user I might want to create a series of posts that go together. In fact a lot of folks are already doing this.

We already have this functionality but it's only been for admins to do and we've sort of fallen off with scale. It needs to be a user feature:
https://dev.to/raulavila/multithreading-in-java-for-dummies-part-1
(I think the design on the article page should be updated but that's a separate, simpler issue)
### Definition of Done
When I, as a user, can create series and add articles to them. Under the hood, this is the "collection" model. And a "series" would be a "type" of collection. There's more to it in terms of a potential list view for a series, but for now let's just get this dashboard to be a thing.

Happy to guide anyone who wants to take this on.

**Comment by Adjoa** [comment]
I'm interested. Is this a good first issue?

**Comment by pkfrank** [comment]
As @cjbrooks12 mentioned in this [DEV comment](https://dev.to/cjbrooks12/comment/47b0), the "UI" for this feature could potentially live directly in the editor.  If it was in the Front Matter, it could be something like:

```
title: Intro to Vim, Part 1
series: Intro to Vim
series-part: 1
```

Upon publishing the article, it would create a dynamic "Table of Contents" at the top of the article.  It would also need to check to make sure that all other articles in the series are sync'd up properly in case a position was added or adjusted.

Another idea is to have this feature live exclusively in the dashboard:
![series dashboard mockup](https://cl.ly/0879d9b7db9a/Image%202018-08-22%20at%2010.28.36%20AM.png)

The dashboard view seems a bit more intuitive to me.

What do other people think?  cc @benhalpern

**Comment by AntonyGarand** [comment]
I would actually have the series in a new section, not within the article editor.

On the dashboard or in the menu, you could have a `Manage your series` area
![image](https://user-images.githubusercontent.com/9059487/44959090-67e35500-aeb7-11e8-92ee-c0593b8f2ccf.png)
Where you could create a serie and add, move or remove articles from them.

This would have the benefits of being able to modify and reorder series without going in each article, as well as have a better overview of these.
