### ISSUE TITLE
Make It Easier To Adjust Notification Subscriptions on Articles

### ISSUE THREAD

**Issue by omenking** [thepracticaldev/dev.to#3800]
I wanted to contribute to welcoming people to DEV.to once in a while so I turned on Top Level Comments. I did that for a bit and then turned off Top Level Comments, but I was still getting notifications. 

I checked and see that All Comments was now checked. When I click All Comments it will superficially uncheck but it's not persisting on refresh and its staying checked. 

<img width="330" alt="Screen Shot 2019-08-22 at 10 39 05 AM" src="https://user-images.githubusercontent.com/7776/63524081-57156000-c4c9-11e9-9ecc-ee98c9ef1217.png">

Here's the url
<img width="503" alt="Screen Shot 2019-08-22 at 10 39 41 AM" src="https://user-images.githubusercontent.com/7776/63524236-a52a6380-c4c9-11e9-87a2-27f034a7f1f1.png">

This is the payload
<img width="260" alt="Screen Shot 2019-08-22 at 10 39 32 AM" src="https://user-images.githubusercontent.com/7776/63524245-a9568100-c4c9-11e9-9dde-df22cc6245e0.png">

The response returns `true`.

So the problem is my Notification feed is flooded with comments and I cannot discern from my own content and the Welcome thread, making it hard for me to respond to people in a timely manner or at all to my own content.

**Comment by jessleenyc** [comment]
@omenking thanks for the reporting the bug. 

Have you tried clicking the 'unsubscribe' button? I think that should work even if the individual 'all comment' button didn't.

**Comment by omenking** [comment]
@jessleenyc your suggestion worked.

**Comment by jessleenyc** [comment]
FYI just updated the title of the article for clarity.

**Comment by johncurcio** [comment]
I'd like to work on this issue. It seems like I need to adjust ``notificationSubscriptionHandler.js`` to work with this case. 

I'll submit a pull request once I'm done :)
