### ISSUE TITLE
reading list bug and search result empty, also I cannot send and receive any messages!

### ISSUE THREAD

**Issue by Mdhesari** [thepracticaldev/dev.to#3805]
**Describe the bug**
I save my favourite articles and then when I go to my reading list there's nothing to appear, also there is a bug when I search a key word for an article and nothing appeared.
The same problem with my direct messages, recently I was able to send and receive messages but now there is no result when I try to get messages...

**To Reproduce**

**Expected behavior**

1. Go to my profile
2. click on reading list
3. nothing appear and empty section, although I had saved lots of articles before.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version: 76

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by Mdhesari** [comment]
![image](https://user-images.githubusercontent.com/28428724/63551746-27a73780-c54b-11e9-8dbf-35fa83eb927f.png)

**Comment by Zhao-Andy** [comment]
Hi @Mdhesari, do you see any errors in your browser's console? My first guess is that you might have some JavaScript disabled, either because of an extension or some other external factor.

**Comment by Mdhesari** [comment]
![image](https://user-images.githubusercontent.com/28428724/63551792-4dccd780-c54b-11e9-92f9-34bae4f98d21.png)

**Comment by Mdhesari** [comment]
this is my console after searching...
![image](https://user-images.githubusercontent.com/28428724/63551871-82409380-c54b-11e9-92e7-a75150e82be4.png)

**Comment by Mdhesari** [comment]
> Hi @Mdhesari, do you see any errors in your browser's console? My first guess is that you might have some JavaScript disabled, either because of an extension or some other external factor.

No there is no problem with javascript because I've tried various devices and also browsers...

**Comment by mstruve** [comment]
No longer a problem since moving to Elasticsearch
