### ISSUE TITLE
GIFs dont seem to be working for my posts

### ISSUE THREAD

**Issue by procyclinsur** [thepracticaldev/dev.to#3810]
**Describe the bug**

Utilizing GIFS does not seem to work for my posts.. I can still view others posts and view my GIF on other Markdown based sites.

**To Reproduce**

I created [this](https://dev.to/procyclinsur/golang-dynamic-logging-3p7k) post that contains the following image import.

```
![APP_GIF](https://i.imgur.com/iHNIhOF.gif)
```

This exact same image import works in [hackmd](https://hackmd.io/fkDZNiXnSFC7ffKF1AgB_w)

**Expected behavior**

Markdown image import should work for GIFs

![image](https://user-images.githubusercontent.com/34673206/63589644-a69c7e80-c5e4-11e9-93db-4c9544646a00.png)

**Desktop (please complete the following information):**

- OS: Fedora 30
- Browser: Firefox
- Version: 68.0.2

**Comment by Glennmen** [comment]
Looking in the network tab in the browser console it seems that the gif is too big.
`Maximum total number of pixels in all frames/pages is 200 Megapixels. Requested 286.27 Megapixels`

**Comment by procyclinsur** [comment]
> Looking in the network tab in the browser console it seems that the gif is too big.
> `Maximum total number of pixels in all frames/pages is 200 Megapixels. Requested 286.27 Megapixels`

Thats probably the issue! 
Should this be added to the site FAQ?
