### ISSUE TITLE
Reading list: Add clear filter button/icon

### ISSUE THREAD

**Issue by idris-rampurawala** [thepracticaldev/dev.to#3819]
**Is your feature request related to a problem? Please describe.**
In the `Reading List` page of the profile, please add a clear filter button or icon to reset the filters that have been applied via selected tags/search text. 

**Describe the solution you'd like**

If I enter some text in the `search your list` textbox, there should be an icon (close icon - :negative_squared_cross_mark:) to clear the text and reset the reading list clearing the filters. It would help to also minimize calling the filter list on every backspace key stroke applied when a user clears the textbox. Also the same mechanism can be applied the clear out the selected tags in the reading list.

**Describe alternatives you've considered**
None

**Additional context**
Though it is not a show stopper, but good to have to minimize the usability issues.

**Comment by jessleenyc** [comment]
For anyone who wants to take on this issue, please share more details on implementation and design before you get in too deep!

**Comment by FultonBrowne** [comment]
Do you plan to implement this across web, ios, and android?

**Comment by benhalpern** [comment]
@mvasigh It's a good look. Go with it!
