### ISSUE TITLE
Add GIF limits to the FAQ

### ISSUE THREAD

**Issue by procyclinsur** [thepracticaldev/dev.to#3828]
I don't know if I would call this a feature request, but since there is a limitation on the size of GIFs uploaded to the site, I think there should be some mention of this limitation somewhere in the FAQs.

Error as found in the dev console network tab..

`Maximum total number of pixels in all frames/pages is 200 Megapixels. Requested 286.27 Megapixels`

**Comment by jessleenyc** [comment]
We should probably also have this appear as an error message for both the editor and comment box but adding it to the editor guide makes sense as a first step!
