### ISSUE TITLE
Tags are not being applied to my Video Post

### ISSUE THREAD

**Issue by omenking** [thepracticaldev/dev.to#3846]
So here I published a post with tags:
![Screen Shot 2019-08-26 at 4 08 36 PM](https://user-images.githubusercontent.com/7776/63719887-f618bf80-c81b-11e9-9b09-cfc320c9ce25.png)

Here no tags appear:
![Screen Shot 2019-08-26 at 4 08 41 PM](https://user-images.githubusercontent.com/7776/63719892-f87b1980-c81b-11e9-9747-af12056c2870.png)

Editing does not remedy the missing tags

**Comment by Zhao-Andy** [comment]
Sorry, just seeing this now! I switched the `description` and `tags` position and it seemed to work. Might be a weird front matter parsing issue.

**Comment by omenking** [comment]
No worries. What a funny fix. But if its works can't complain eh.

**Comment by araslanov-e** [comment]
@Zhao-Andy Is the problem relevant?
Now a new form 
![image](https://user-images.githubusercontent.com/1290711/66226339-fac27480-e6f3-11e9-878d-6a6989c61542.png)

**Comment by Zhao-Andy** [comment]
@araslanov-e I believe it is still an issue. To clarify, we have two versions of the editors:
- v1 which is the editor that uses front matter, and I think the default editor for video uploads
- v2 editor which is the editor you posted a screenshot of

If you're trying to reproduce this, I think you can simply try to reproduce in development with the v1 editor, and don't need to attempt a video upload in development. To change your editor settings, visit `/settings/misc` and update your editor version to `v1`.

**Comment by araslanov-e** [comment]
@Zhao-Andy 
Problem №1 - after description space is lost
For example 
```
"body_markdown":"---\ntitle: Unpublished Video ~ 3djn\npublished: false\ndescription:\ntags:\n---\n\n"
```
Problem  №2 - https://github.com/thepracticaldev/dev.to/blob/master/app/labor/markdown_fixer.rb#L58 invalid regexp https://rubular.com/r/d48NKsmxIWml6B

I'm trying to solve the second

**Comment by araslanov-e** [comment]
@Zhao-Andy solved №1 - https://github.com/thepracticaldev/dev.to/pull/4258

**Comment by araslanov-e** [comment]
@Zhao-Andy solved №2 - https://github.com/thepracticaldev/dev.to/pull/4265 (I hope)

**Comment by maestromac** [comment]
Resolved with combination of https://github.com/thepracticaldev/dev.to/pull/4258 and https://github.com/thepracticaldev/dev.to/pull/4265
