### ISSUE TITLE
Email markup for 16 week streak badge - broken URLs

### ISSUE THREAD

**Issue by seangwright** [thepracticaldev/dev.to#3848]
**Describe the bug**

I received the 16 week streak badge (Yay!) and the links at the bottom of the email are broken.

**To Reproduce**

Open the "You just got a badge" email for 16 week streak.

**Expected behavior**

Links work for the following paragraph:

<blockquote>
 You also get 5 new credits to use for community listings
if you have anything you'd like to promote. 🎉

More information about listings
</blockquote>

**Source**

Below is the rendered markup in the email (re-formatted by me):

```html
<p>
  You also get
  <strong>
    <a
      href="http:///credits"
      target="_blank"
      data-saferedirecturl="https://www.google.com/url?q=http:///credits&amp;source=gmail&amp;ust=1566950903593000&amp;usg=AFQjCNGsteDwXS5PwMsK7tKFK85NiwAetw"
      >5 new credits</a
    >
  </strong>
  to use for
  <strong>
    <a
      href="http:///listings"
      target="_blank"
      data-saferedirecturl="https://www.google.com/url?q=http:///listings&amp;source=gmail&amp;ust=1566950903593000&amp;usg=AFQjCNGW4kc9Hnq_EcxQ9W8-akpLWQnAwQ"
      >community listings</a
    >
  </strong>
  <br />

  if you have anything you'd like to promote.
  <img
    goomoji="1f389"
    data-goomoji="1f389"
    style="margin:0 0.2ex;vertical-align:middle;max-height:24px"
    alt="🎉"
    src="https://mail.google.com/mail/e/1f389"
    data-image-whitelisted=""
    class="CToWUd"
  />
</p>

```

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox
- Version: 68.0.2
- Email Client (GMail)

**Comment by rbrishabh** [comment]
Hey! Can I take this up?
