### ISSUE TITLE
Add images for other tags

### ISSUE THREAD

**Issue by micahlt** [thepracticaldev/dev.to#3874]
I’ve noticed that around DEV there are certain tags (for example, #javascript) that have logos or images beside them when you click on the them.  There are also other tags that don’t have logos.  

![41415838-EB4E-4CF1-9A6F-55D575833778](https://user-images.githubusercontent.com/28816297/63945840-b2030600-ca39-11e9-8aeb-2dd4678533cf.jpeg)

Why can’t all tags have custom images, submitted by moderators or the community?

**Comment by Glennmen** [comment]
I am not 100% sure but I think tag moderators can add images (called badges) to tags that they have permission for. Not sure if mods can add images are only link existing badges that team DEV team has made.
Here is the PR made by @benhalpern https://github.com/thepracticaldev/dev.to/pull/3074

If you would like to apply to be a tag mod you can contact the DEV team: https://dev.to/mod

**Comment by jessleenyc** [comment]
You can also suggest an image for a tag by emailing yo@dev.to (which is what tag mods still have to do)! 

Closing the issue since this would be an admin task!
