### ISSUE TITLE
Side-by-side editing or Edit-here

### ISSUE THREAD

**Issue by tmr232** [thepracticaldev/dev.to#39]
When editing large posts, every transition from preview to markdown makes me go and look for the same paragraph I was in.
Being able to edit the markdown side-by-side with the preview would make it a lot easier.
Another approach that will make editing easier is an "edit here" option, that will switch from preview to markdown, but keep my position in the text.

**Comment by pkfrank** [comment]
Hey @tmr232 — thanks for the suggestion.  We'll definitely be giving the markdown editor a lot more love in the coming months.  I've also experienced that frustration of flipping between `Preview` and `Markdown` and having to go find my spot again.

The suggestion is definitely not falling on deaf ears, we just want to be strategic about improving the whole editing experience when we're at a point to give it a focused and major investment of our time and energy.  Hopefully that'll be soon.

Thanks again for the thought 👍 !

**Comment by pbnj** [comment]
I would like to re-raise this issue 4 years later.

As a platform for developers to write technical articles and blog posts, the editor/writer experience is as important as reader experience.

Having a side-by-side markdown editor and preview window would be a great feature to have in forem.
