### ISSUE TITLE
Removing an article from the reading list doesn't remove the list entry right away

### ISSUE THREAD

**Issue by wrldwzrd89** [thepracticaldev/dev.to#3925]
**Describe the bug**

When a previously added reading list article is removed, the state within the article updates as expected. However, navigating to the main page to check how many items are in your list still shows the old count. Furthermore, navigating to the reading list itself shows the old article still there. Repeating the last 2 steps and refreshing several times eventually cleared things up. Only tested with Safari 12.1.2 on macOS Mojave 10.14.6.

**To Reproduce**

**Expected behavior**

The article should be removed from the reading list list, and the count of articles decreased by one.

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS 10.14.6 (with both Supplemental Updates)
- Browser: Safari
- Version: 12.1.2 (14607.3.9)

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by mstruve** [comment]
No longer a problem since moving to Elasticsearch
