### ISSUE TITLE
Integrate with https://getstack.app/

### ISSUE THREAD

**Issue by reyesvicente** [thepracticaldev/dev.to#3926]
**Is your feature request related to a problem? Please describe.**

 The problem is I always have to type dev.to on the browser or open the DEV desktop app for mac which takes time since I only have 8GB of RAM.

**Describe the solution you'd like**

I recently discovered https://getstack.app/ which is a desktop app that has one screen with these apps: 
![Screen Shot 2019-09-03 at 4 32 50 PM](https://user-images.githubusercontent.com/45283313/64157061-9ac47e00-ce68-11e9-9b17-67e0cebcd626.png)
![Screen Shot 2019-09-03 at 4 33 14 PM](https://user-images.githubusercontent.com/45283313/64157065-9bf5ab00-ce68-11e9-8e42-e8009424527b.png)

That's it. I just want to open Stack and have all the everyday apps I use like DEV.

**Describe alternatives you've considered**

**Additional context**

**Comment by Glennmen** [comment]
Not sure what you are asking, but you can add custom URLs in Stack.
If you are asking about an integration into the Stack application you should contact the Stack team. DEV.to can't add themselves in the application.

**Comment by reyesvicente** [comment]
> Not sure what you are asking, but you can add custom URLs in Stack.
> If you are asking about an integration into the Stack application you should contact the Stack team. DEV.to can't add themselves in the application.

Right, I just figured that out now.
