### ISSUE TITLE
Dev.to using outdated version of the react

### ISSUE THREAD

**Issue by Puritanic** [thepracticaldev/dev.to#393]
### Feature Request or Task
No particular reason to update, but it is nice to be up to date with the latest versions of libraries.

### Definition of Done
Update to latest React (16.4.2 currently), refactor outdated code and maybe take advantage of the new React API methods (`getDerivedStateFromProps`, `createRef` etc.).

-------

**Comment by nickytonline** [comment]
Thanks for raising this @Puritanic.

There's an issue open to get Greenkeeper incorporated into the workflow to handle package updates, but it's still in the private repository. It will probably be migrated by @maestromac at some point.

Having said that, we don't use React in the dev.to codebase, it's Preact 😉

**Comment by maestromac** [comment]
Hey @Puritanic . Nicks's right, we are using Preact 😁

Closing this since we don't use React.

**Comment by Puritanic** [comment]
Sure :D 
Didn't know about Preact, I have that annoying React devtool msg that React version is outdated.
