### ISSUE TITLE
Bug when making changes to a post on 2 different devices

### ISSUE THREAD

**Issue by anquangman** [thepracticaldev/dev.to#3932]
I logged in and edited my post on my laptop and save all my changes. But after a few hours I logged in to my account again using my desktop then something wierd happends. So if I click on Draft button. I can get my lastest work, but if I click edit to modify the content I will get an very old version of my content which I have already updated.

First device:
- Device: Laptop
- OS: MacOS
- Browser: Firefox
- Version: 68.0.2 64bit

Second device:
- Device: Desktop
- OS: Windows 10
- Browser: Firefox
- Version: 68.0.2 64bit

**Comment by maestromac** [comment]
Thank you for this issue @anquangman 

This sounds like https://github.com/thepracticaldev/dev.to/issues/3670. Please continue the conversation there.
