### ISSUE TITLE
Moving "Banish" and "Delete Account" actions into background jobs

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/dev.to#3941]
Sometimes when we banish an account, the process will timeout with a 503. After investigating, this usually happens because there is a chain of HTTP calls sent to Fastly in order to bust the caches of related content -- usually comment thread chains.

Busting related content doesn't have to be completely instant though, and we might want to consider moving it into a background job.

As for deleting a person's account, I think we can move the entire process into a background job, and then once the job is complete, it automatically fires an email confirming the account has been deleted.

**Comment by artfullyContrived** [comment]
@Zhao-Andy I'm interested in tackling this. A few questions

1. Why not have the entire banish process in a background job?
2. To whom do we send the email confirming user account deletion?

**Comment by artfullyContrived** [comment]
@Zhao-Andy I have investigated the problem and concluded that the `CacheBuster.bust` call is redundant.

I'm now moving on to the `DeleteUser` job. The email will be sent to the admin initiating the deletion.

**Comment by mstruve** [comment]
Banishing a user has since been moved into the `Moderator::BanishUserWorker` so this can be closed.
