### ISSUE TITLE
Incorrect awarding of writing streak badge

### ISSUE THREAD

**Issue by foo-dogsquared** [thepracticaldev/dev.to#3949]
**Describe the bug**

Hello! I just got the [4 Week Streak badge](https://dev.to/badge/4-week-streak) for some reason. I did recently got active but I didn't publish them on dev.to yet. Only one of them is recently published. 

If you also look at my post history, I only published a total of **two** which are months far from each other to be awarded with this. 

This is just wrong in my opinion to have it awarded on the platform itself while you (READ: me) don't have any content freely published on it. 

**To Reproduce** 

IDK but I do have a theory that this is caused by fetching posts from my RSS feed. 
I think the platform also counts unpublished posts for the badge. 

 

**Expected behavior**

Errr... Not getting the badge.

**Screenshots**

Here's my profile with the unexpected badge.

![My profile with the unexpected badge ](https://user-images.githubusercontent.com/34962634/64359243-89cb6680-d03a-11e9-94aa-d9c6c730d6b1.png)

**Desktop (please complete the following information):**

- OS: Arch Linux ~~(did i mention i use arch)~~
- Browser: Firefox
- Version: 69.0 (*insert lenny face*)

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

I do have my posts from my blog being fetched here through an RSS feed.

**Comment by jessleenyc** [comment]
Oh interesting, thanks for flagging.

**Comment by jacobherrington** [comment]
I believe I have seen this too. I think I got this badge a few months ago, and I remember thinking it didn't seem right.
