### ISSUE TITLE
Dashboard view is missing posts

### ISSUE THREAD

**Issue by kylegalbraith** [thepracticaldev/dev.to#395]
## Bug Report
Dashboard isn't showing all of my posts.

### Current Behavior
Dashboard appears to be broken in terms of paging and is missing my earlier articles.

### Expected Behavior
Dashboard should show all my current and draft articles.

### Mobile & Desktop Screenshots/Recordings
![image](https://user-images.githubusercontent.com/1869717/44292943-b3053300-a23c-11e8-93d9-98d1ef73e073.png)

### Additional Info (device/browser, helpful links)
Chrome Version 68.0.3440.106

**Comment by Zhao-Andy** [comment]
Hmm strange. That looks like Windows 10 right? Any console errors?

**Comment by kylegalbraith** [comment]
Figured it out. It was a rogue Chrome extension I had installed. Removed that and all is right in the world.
