### ISSUE TITLE
Tag Edit button for Moderator

### ISSUE THREAD

**Issue by omenking** [thepracticaldev/dev.to#3950]
When I am a moderator and I am on the tags page.
I should see an edit button so I can easily edit the moderator tags.

**Comment by matisnape** [comment]
@omenking So you would be able to edit tags from main page additionally to admin panel? Or the button should be redirecting to the edit tag page in admin panel?

**Comment by jessleenyc** [comment]
We added this a little while ago - it's a redirect:

![edit-mod-button](https://p193.p3.n0.cdn.getcloudapp.com/items/9ZuNee5g/Image+2019-12-02+at+8.14.50+PM.png?v=63d8869a3bc225f5a71fd077b28674b4)
