### ISSUE TITLE
Improve the tag edit pages

### ISSUE THREAD

**Issue by omenking** [thepracticaldev/dev.to#3953]
This form can use some styling love. 
For a moderator who wants to fill in a considerable amount of markup, it is a bit cumbersome.

<img width="566" alt="Screen Shot 2019-09-05 at 2 47 10 PM" src="https://user-images.githubusercontent.com/7776/64370248-14d14000-cfec-11e9-9115-20c7fcd9c52a.png">

**Comment by timrodz** [comment]
Hi @omenking, I'd be interested in helping out with this. 

Are there any specific features you'd like to use as a moderator? This would help me craft a better implementation.

**Comment by omenking** [comment]
I can't think of any additional features.
Colour pickers would be nice for the coloured boxes.
A popup which displays markdown rules would be useful.
Larger boxes. For bonus points create a tab which can switch from markdown to preview.
And if you really want to go for it do it in preact.

Again you can just adjust the styling, but just some more ideas you can run with.

**Comment by timrodz** [comment]
Thanks for the suggestions!

As I haven't used Ruby (yet), I'll be looking at completing the basics first (Styling -> Colour pickers -> Markdown syntax popup)

**Comment by timrodz** [comment]
Hi @omenking, I've just had a chance to touch this now. How does someone navigate to this page? I might need access to mod priviledges so I can test this in my own setup.

**Comment by omenking** [comment]
So the page you're looking at is this url:
```
https://dev.to/t/rails/edit
```

If the app is following convention then it would be in `views/tags/edit.html.erb` and the controller responsible should be TasksController.

How someone gets to set as an admin could be a column on the users table or a join table called moderators. A good place to look is the `schema.rb` to get hints. Probably checking the `user.rb` and search moderator will help.

**Comment by omenking** [comment]
Moderators might be set via a role:

```
  create_table "users_roles", id: false, force: :cascade do |t|
    t.integer "role_id"
    t.integer "user_id"
    t.index ["user_id", "role_id"], name: "index_users_roles_on_user_id_and_role_id"
  end
```

**Comment by timrodz** [comment]
Thanks! I was able to authenticate and can now see the tag page.

**Comment by timrodz** [comment]
I have noticed there's a basic colour picker implemented for the boxes - It pops up when you click on the text field: 
<img width="363" alt="Screen Shot 2019-09-29 at 4 12 04 PM" src="https://user-images.githubusercontent.com/7434353/65825485-f05b4180-e2d3-11e9-92f3-363171da811f.png">

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/4137
