### ISSUE TITLE
Tag Rules should find its way infront of users before posting

### ISSUE THREAD

**Issue by omenking** [thepracticaldev/dev.to#3954]
When I am a new user and not familiar with tagging rules.
I should see during my journey to creating an article that rules so I don't have a poor experience if my tags become moderator due to being unaware of tag rules

**Comment by jessleenyc** [comment]
Thanks Andrew. I'm going to close this issue in favor of an older one that addresses the same concern: https://github.com/thepracticaldev/dev.to/issues/3051
