### ISSUE TITLE
Follower List on Main Profile Page

### ISSUE THREAD

**Issue by donita** [thepracticaldev/dev.to#396]
### Feature Request or Task:

Request or User Story:
It seems there isn't an easy way to see who's following who to build a network. It would be nice to see a "Following/Followers" section on a users main profile. 

Similar to this:
![screen shot 2018-08-17 at 11 52 16 pm](https://user-images.githubusercontent.com/17953363/44295530-9dadfa00-a278-11e8-8343-f4ba3df6c8d7.png)

Definition of Done:
A follower list that will show on your main profile, maybe in this area or it's own personal section on a users profile. 

![screen shot 2018-08-17 at 11 46 35 pm](https://user-images.githubusercontent.com/17953363/44295488-d8fbf900-a277-11e8-84e8-5ee782373d73.png)

**Comment by rhymes** [comment]
I don't know if this is a bug or a feature but not knowing how popular other people are is one of the things I like about devto. Zero social network-like anxiety. 

Maybe there is a better way to achieve the goal beside this. Help from a UX designer is definitely needed on this because I'm not knowledgeable on the topic. What if we there was no count and just the list, there may be less of an impact like this...

I suspect the lack of this info to be by design though.

**Comment by rhymes** [comment]
@donita I'm glad you did, I'm sorry if I sounded dismissive. I was thinking about the ramifications of this feature.

I agree with you that we see this feature with two different perspectives. Yours is definitely a valid one and can create value. 

It's just that personally I found it refreshing not to have this counters around devto.

I'm sure people far more expert than I am can weigh in, the ability to check who follows who can be a useful one. While I'm writing this I'm thinking that it could be implemented in a slightly different way; you only get to see the list of people anyone follow not the followers. This way you can still check who follows who and find interesting people.

What do you think? Thanks for starting this conversation

**Comment by donita** [comment]
No need to apologize, it’s fine. I didn’t feel that you felt my opinion wasn’t valued. :) I was just sharing my thought process. 

But I agree, but one thing you pointed out is that I never saw it from that perspective of how people may have felt when it comes to follower count. I never thought about although we are on social media sites, some don’t like the social media feel. I think I was in my own bubble, so thank you for actually enlightening me. 

I’m not really stuck on a design because I’m
not a designer. I do think it can be implemented in a slight differently way or even people can be catergorized based off their programming languages, without having their follower count shown. What do you think? This might not be a passion point for you, but if approved I would love to work with you on this type of contribution. :)

**Comment by rhymes** [comment]
@donita count me in and thanks for the conversation :-) 

Let's wait what the core team says about it and proceed from there.

**Comment by donita** [comment]
@rhymes no prob! :)

**Comment by benhalpern** [comment]
I only skimmed this convo so sorry if I missed something, but yeah, this is considered a feature for the reasons @Rhymes discussed.

It's crossed my mind that we may want to do something so it doesn't seem like it's just plain missing. But have no real ideas on this front.

Great issue either way @donita, I'll keep this open for further discussion, and so I can come back and read the convo more closely.
