### ISSUE TITLE
Error in Writing post

### ISSUE THREAD

**Issue by shivanisinghss** [thepracticaldev/dev.to#3961]
I am not able to create new post. Getting error "500 Error
It's not you, it's me."

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by maestromac** [comment]
Hello @shivanisinghss , this looks an issue specific to your account. Please email yo@dev.to for more help.
