### ISSUE TITLE
No link from the Dev Digest email works

### ISSUE THREAD

**Issue by tqa236** [thepracticaldev/dev.to#3963]
**Describe the bug**

No link from the Dev Digest works
**To Reproduce**

Click to a link in the Dev Digest email

I paste a [link](https://dev.to/ahoy/messages/putZR1MiqGauscmFswM8UvG6np6ZSmuJ/click?signature=ddd907ebfd7e29a5ea9c36a09a6e21f1033bf394&url=https%3A%2F%2Fdev.to%2Fmohanarpit%2F5-tips-for-beginners-to-learn-better-stay-motivated-1gha%3Futm_source%3Ddigest_mailer%26utm_medium%3Demail%26utm_campaign%3Ddigest_email) here just for you to test faster.

**Expected behavior**

The link works

**Screenshots**
![image](https://user-images.githubusercontent.com/25203655/64438751-f2612480-d0c8-11e9-949e-c00536af9fff.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Google Chrome
- Version: 76.0.3809.132 (Official Build) (64-bit)

**Comment by jessleenyc** [comment]
Thanks for flagging. We're taking a look at it now.

**Comment by jessleenyc** [comment]
Resolved with #3964
