### ISSUE TITLE
Listing shakes

### ISSUE THREAD

**Issue by auvansang** [thepracticaldev/dev.to#3969]
**Listing Shakes**

**Expected Behaviors**
No Shake any more.

**Screenshots**

![Listing](https://user-images.githubusercontent.com/20507461/64483758-78e54580-d232-11e9-8f15-69f988d2a763.gif)

**Desktop:**

- OS: Windows 10 May Update
- Browser: Chrome
- Version: 76.0.3809.132 (Official Build) (64-bit)

**Comment by rhymes** [comment]
Hi @auvansang thanks for the issue! I tried both with Firefox and Chrome on macOS as a way to narrow down the scope and can't reproduce, so it might be a Windows only issue. Do you have Firefox installed? Can you check if you have the same issue? Just to narrow it down even further...

**Comment by auvansang** [comment]
Hi @rhymes, I had to test again under Firefox, everything works fine, but I also double check on chrome, and under Incognito mode, the issue still happens

**Comment by Link2Twenty** [comment]
Hmm, I can't reproduce the issue either. Have you got any plugs that run even in incognito?

**Comment by Link2Twenty** [comment]
Right, simple solution.

Something like.
```css
.listings__container {
  margin-left: 1em;
}

.listing-content {
  width: 100%;
}
```

I think there might be some breakpoints in there somewhere which will prevent the left margin always being there but I'm not sure.

**Comment by FultonBrowne** [comment]
where should I look for this bug?

**Comment by Zhao-Andy** [comment]
@FultonBrowne The relevant CSS should be in [`/app/assets/stylesheets/classified_listings.scss`](https://github.com/thepracticaldev/dev.to/blob/master/app/assets/stylesheets/classified_listings.scss).

**Comment by FultonBrowne** [comment]
thank you! I will do what I can.

**Comment by FultonBrowne** [comment]
hey @Link2Twenty , how did you reproduce the bug?

**Comment by Link2Twenty** [comment]
@FultonBrowne try setting the window width to 1125px

**Comment by FultonBrowne** [comment]
@auvansang go to this address and tell me if it works [https://3000-f496067b-0c59-4fbc-8be7-973b3b24bd05.ws-us1.gitpod.io/](url)

**Comment by FultonBrowne** [comment]
thanks @Link2Twenty will try as soon as my work space loads.

**Comment by FultonBrowne** [comment]
@Zhao-Andy how do you add tags to the listings in the local dev.to (gitpod)

**Comment by auvansang** [comment]
Sorry but the link was died.

**Comment by Link2Twenty** [comment]
I think they meant this link

https://3000-f496067b-0c59-4fbc-8be7-973b3b24bd05.ws-us1.gitpod.io/listings

**Comment by FultonBrowne** [comment]
I may have a solution but now the dev server thing wont start :(

**Comment by auvansang** [comment]
Sorry, But how can I test this?

**Comment by auvansang** [comment]
Look like the issue was fixed
