### ISSUE TITLE
API: Dashboard

### ISSUE THREAD

**Issue by simov** [thepracticaldev/dev.to#3970]
:wave: I saw you're working on a REST API, but I'm seeing only Articles and Webhooks there, so my question is: Is Dashboard support planned?

I wanted to show the view counts for my articles on dev.to on my personal website, that's being generated by a cronjob, so I ended up creating [this little script](https://gist.github.com/simov/8bffb278db0c0ba99b6fab0ca4d5fc96) that returns the data from my Dashboard in the following format:

```js
[ { id: 73551,
    title: 'OAuth Like a BOSS',
    url: 'https://dev.to/simov/oauth-like-a-boss-2m3b',
    published: '2019-01-07T12:16:05Z',
    tags: [ 'oauth', 'node', 'javascript', 'authentication' ],
    views: 4030,
    reactions: 117,
    comments: 0 },
  { id: 67681,
    title: 'OAuth Simplified',
    url: 'https://dev.to/simov/oauth-simplified-2pbd',
    published: '2018-12-10T12:01:03Z',
    tags: [ 'oauth', 'node', 'javascript', 'authentication' ],
    views: 3901,
    reactions: 117,
    comments: 12 },
  { id: 51157,
    title: 'Composable HTTP Client for NodeJS',
    url: 'https://dev.to/simov/composable-http-client-for-nodejs-83f',
    published: '2018-09-24T13:03:44Z',
    tags: [ 'functional', 'javascript', 'fp', 'node' ],
    views: 3220,
    reactions: 48,
    comments: 4 },
  { id: 6592,
    title: 'Anonymous Recursion in JavaScript',
    url: 'https://dev.to/simov/anonymous-recursion-in-javascript',
    published: '2017-08-06T10:46:09Z',
    tags: [ 'recursion', 'javascript', 'closures' ],
    views: 8479,
    reactions: 42,
    comments: 12 } ]
```

As you can imagine this is quite hacky and I'm still hesitant on adding this to my cronjob. The first issue is that I'm relying on the session cookie token, and second is that I'm parsing the HTML page.

**Comment by simov** [comment]
Wait just saw that the API article endpoints contain most of this data, but I'm not seeing the view count. So I guess the question is: Is `views` count returned by the API?

**Comment by rhymes** [comment]
Hi @simov, sorry we haven't replied to this sooner. The article endpoint doesn't return view counts for public and that's by design, though you can get your own articles's page views by using the https://docs.dev.to/api/#operation/getUserArticles endpoint, with:

```shell
curl -H "api-key: API_KEY" https://dev.to/api/articles/me
```
