### ISSUE TITLE
A path to reporting user profiles

### ISSUE THREAD

**Issue by michaelgv** [thepracticaldev/dev.to#398]
### User Story / Description
As a user, I think we should be able to report any inappropriate profiles with a button, or hyperlink, and be able to specify a reason for said report. There should be a list of categories that come with a priority attached. For example, see below:

*Report* (red button?) -> open modal/dialog, or redirect to report page:

"You are reporting #{USERNAME}, what is the category of this report?"

*Select dialog, list of categories:* Inappropriate Content, Inappropriate Posts, Inappropriate Username or Profile Picture, Inappropriate Biography, etc

"Additional information (optional?):" plain textfield

Priorties being username/profile picture, biography - as per content/posts it may classify under the existing report functionality of posts?

### Definition of Done

We can report profiles that are inappropriate

**Comment by benhalpern** [comment]
This should be a link to the usual "report" flow.

I think it's also worth noting that this probably isn't a main action and should probably be behind a menu. Only one of 1000 profile visits would be this action so I don't think it needs to be in your face for most users.

Example on Twitter: ![](https://cl.ly/ca66f4c7fe3c/Image%202018-08-21%20at%209.13.47%20PM.png)

Clicking the three dots reveals further actions. Now we just need some more further actions.

**Comment by davealbert** [comment]
With existing profile issues should we send an email to "yo" or is some other process a better solution?

**Comment by Zhao-Andy** [comment]
Hey @davealbert, sorry for the late reply. Yep, best bet is to report by sending an email to yo@dev.to.

FWIW https://dev.to/report-abuse lets you put any link in the "Reported URL" field if you find that to be more useful/ergonomic.

**Comment by davealbert** [comment]
Perfect thanks.
