### ISSUE TITLE
Native Sharing with the new Web Sharing API

### ISSUE THREAD

**Issue by edisonywh** [thepracticaldev/dev.to#399]
## Feature Request or Task
Sharing to other applications on the phone. **I want to work on it if possible!**

### User Story / Description
As a user, I'd want to share an article with my friends/colleagues if I think it's useful/interesting.

Right now, the implementation to share is just to copy a link, like so:
<img width="371" alt="08-19-1228am" src="https://user-images.githubusercontent.com/20277437/44301299-22ffe000-a347-11e8-8ffc-8a34d06b6e2f.png">

I share a lot, so I've personally done this multiple times, but it was super clunky for me (on my Android, the native action pop-up persists until I restart the PWA).

I'm currently working on my side project and came across this **new experimental API** -[Web Share](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share), basically providing it with a native sharing capability.

Now, it's still classified as an experimental API, so the support isn't very wide (starting from Chrome v61). However I've implemented it in my own project, and it was relatively easy, so I would definitely recommend it. I think the benefit is huge for such small changes :)

### Definition of Done

- User should be able to invoke a native sharing sheet (only supported on Android for now)
- For non-supported devices, share action would not show

## ------
So! I'd love to work on it, but I've never contributed to an open source project before and don't really have an idea where to start/who do I ask to see if this feature is approved, so do guide me!

**Comment by bigblind** [comment]
Since the web API is experimental, it may be changed or removed. Do we want to take on the burden to keep track of that?

**Comment by Zhao-Andy** [comment]
Hey @edisonywh, thanks for the feature request. This is definitely the next iteration of the share button, and using the Web Share API is moving in the right direction. We'll have to consider some design choices with this, like whether we should replace the "Share to Twitter" button or the URL entirely.

@bigblind I think it's mostly okay to give it a try. @benhalpern any thoughts on whether or not this is too experimental?

For everything else that's not Android and Chrome, we'd probably want something like a one-tap copy in order to share easily. Hopefully the API is supported by other browsers and operating systems.

**Comment by edisonywh** [comment]
@bigblind Yup, that's a valid concern. Like @Zhao-Andy said though, I think it's okay to give it a try. If it's indeed deprecated/changed in some other ways, it shouldn't break anything because we'll be checking for `navigator.share` first anyway.

@Zhao-Andy Agree on the fallback one-tap copying, I can also work on that!

**Comment by edisonywh** [comment]
Hey guys! this issue had been sitting idle for a few days, I thought while we're still deciding whether or not we should do away with an experimental API, I could implement the one-tap copy link that @Zhao-Andy mentioned.

I have made a PR here GH-484 which does that exact thing: copy to clipboard when tapped on. As it's not exactly officially signed off as an approved feature, I understand if it's not gonna get merged, but would appreciate a look regardless!

That'd be my first ever PR to an open source community (and hope for a lot more!), so would appreciate any feedback! I'm not sure about coding style/ES6 compatibility/where to put javascript, so do guide, thanks!

**Comment by benhalpern** [comment]
Cool! Thanks so much @edisonywh. Congrats on your first PR.

Snackbar functionality should be useful going forward. I feel like right now we are missing that as a re-usable design pattern.

Despite @philnash's [great posts on the Web Share API](https://dev.to/philnash/the-web-share-api), I haven't fully wrapped my head around it. I'd love to see a sensible PR implementing it in a safe way for browsers that support it. I think we'd probably be able to merge it.

Thanks a lot either way y'all.

**Comment by edisonywh** [comment]
@benhalpern That was a good read indeed! Not sure how I missed that while I was researching, haha.

Here are the bits of code I'm using in my own side project. It's less than 10 lines!

```
if (navigator.share) {
      navigator.share({
        title: 'Nibble',
        text: 'Check out this article I read on Nibble!',
        url: this.state.article.url #or window.location.href in dev.to's case
      })
    }
```

In my `render()` method I check for browser compatibility again, so I only render a share button if it's feature detected.

In `dev.to`'s case, I think it'd make sense if we just have an action called `Share link`, and invoke either one tap copying or Web Share API if it's available. One interesting thing I found out from the article you just shared is the `Promise` bits. Not sure if we have polyfill for that!

**Comment by philnash** [comment]
I am bad at GitHub notifications, but I noticed the stale bot closed this.

However, I'd argue that it's not stale and maybe we can re-visit this.

I see, @benhalpern, that you're looking for a safe way to use the web share API. Can I suggest using the [web component that I wrote](https://dev.to/philnash/use-the-web-share-api-easily-with-web-components-ido). You can wrap it around your existing share buttons and it will take over only in the case that web share (and web components) are supported.

What do you think?

**Comment by Link2Twenty** [comment]
Initially, we'd only gain Blink browsers on Android, which to give the PWA a 'native' like experience isn't a bad idea.

I also guess there's no need to polyfill web components so it's not adding much bulk.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/1524
