### ISSUE TITLE
Direct Links to Comments Should Include Comment-specific Metadata

### ISSUE THREAD

**Issue by justuseapen** [thepracticaldev/dev.to#3990]
![image](https://user-images.githubusercontent.com/4587141/64556442-67bd3700-d30d-11e9-89dd-8d20d0c31ecd.png)

**Is your feature request related to a problem? Please describe.**

Not really just an enhancement.

**Describe the solution you'd like**

When I share a link to a comment it should include comment-specific data in the embed metadata. So when the embed appears in slack/twitter, it could show the headline of the article and the comment itself (truncated if necessary).

**Describe alternatives you've considered**

None.

**Additional context**

I'm pretty sure this is possible.

**Comment by maestromac** [comment]
Thank you for this feature request @justuseapen !

We think this is a great idea! For anyone to wishes to tackle this, take a look inside [SocialPreviewsController](https://github.com/thepracticaldev/dev.to/blob/master/app/controllers/social_previews_controller.rb) and [HtmlCssToImage](https://github.com/thepracticaldev/dev.to/blob/master/app/lib/html_css_to_image.rb).

**Comment by timrodz** [comment]
Hi @maestromac - I might give this a go. 

My background is Python/JS. I haven't used Ruby before, but the two scripts you provided seem understandable enough. 

Is there a recommended way to test this e.g. Sending myself messages over slack to see how the preview links get built?

**Comment by reginaalyssa01809** [comment]
If I may, I'd also like to take a shot at this. :)

I have the same question as to how to test the preview links while in development mode.
