### ISSUE TITLE
Drafts with code blocks not appearing on dashboard from hexo generated atom feed.

### ISSUE THREAD

**Issue by Kritner** [thepracticaldev/dev.to#3995]
**Describe the bug**

Draft not appearing on dashboard.  Draft not appearing should be showing up from this URL:
https://blog.kritner.com/2019/08/25/python-flask-with-heroku/
from this feed:
https://blog.kritner.com/atom.xml
for this user:
https://dev.to/kritner

**To Reproduce**

Not really sure how to reproduce, it's only impacting one particular draft, as I've had drafts come in from this RSS feed prior to *and* after the problem post.  It's only the problem post not showing up.

**Expected behavior**

All posts should appear as drafts on dashboard

**Screenshots**

![image](https://user-images.githubusercontent.com/8814983/64567017-3cdedd00-d325-11e9-8845-6f39dd38090c.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: Version 76.0.3809.132 (Official Build) (64-bit)

**Additional context**

I confirmed this is the case from the edge browser as well.

**Comment by maestromac** [comment]
Thanks for raising this @Kritner 

This an RSS processing issue. It seems like your feed [isn't valid](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fblog.kritner.com%2Fatom.xml) but I'll pinpoint exactly what's causing the error for that particular article.

**Comment by Kritner** [comment]
Oooh, i like that feed validator link, never seen it before :D

and sounds good! I'll probably have to go back and try to fix up the other issues in there at some point

**Comment by maestromac** [comment]
Our RSS reader is having trouble parsing your code blocks since they are in a table. Are you using CodeRay for your syntax highlighting?

**Comment by Kritner** [comment]
Hmm... I'm not sure actually, The blog is built with [hexo](https://hexo.io/).  And yeah I've noticed other imports with code need slight modification prior to being postable, but I've not yet had the issue of the post just not hitting the draft state.  Are you able to narrow it down to a specific code block?

**Comment by maestromac** [comment]
I believe it's all the code-blocks with line numbers. 
![Screen Shot 2019-09-19 at 10 20 16 AM](https://user-images.githubusercontent.com/15793250/65252547-22e08f80-dac7-11e9-8844-8df777db710c.png)
We use ReverseMarkdown gem but the result above from [Turndown](https://domchristie.github.io/turndown/) is the same. The line numbers are completely separated from code blocks. 🤔

**Comment by Kritner** [comment]
yeah that is unfortunately one of the things i've had to modify with each draft that's come in since moving to hexo, i wonder if there's a different plugin i could use for doing code blocks... (what i was using comes built in with the engine)

even still though, these blocks have imported ok in the past, there's gotta be something specific about this post and what's in the blocks that's just completely blocking it right?

**Comment by maestromac** [comment]
Has the line number always been enabled in the past?

**Comment by Kritner** [comment]
I haven't changed any settings recently I don't believe, though I did update some packages (including the hexo version) maybe that broke something... it always imported the code a little weirdly, though I guess now it's not working at all :(

I added this minimal post for testing, it has not yet hit my dashboard either https://blog.kritner.com/2019/09/20/test-post-with-code/

Well, this is no fun

**Comment by Kritner** [comment]
I spent some time fixing some of the issues from the [validator](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fblog.kritner.com%2Fatom.xml) posted above, additionally I updated all my packages, especially around the feed generation based ones, with the hopes that it would correct the issue.  Unfortunately it does not appear to have done so.

Interestingly enough, here is another post that has code blocks in it that has successfully hit my dashboard, from my atom feed.  https://dev.to/kritner/getting-started-with-mongodb-with-net-core-jnk-temp-slug-7458776/edit I'm not sure what's different between the two.

**Comment by Kritner** [comment]
As an update, I wrote this post https://blog.kritner.com/2019/09/20/test-post-with-code/ hoping with its minimal amount of code, would appear on my feed, but no luck.

I guess I could go back to dev.to pulling from my medium feed, since I can at least import the stories by direct URL there, then perhaps massage them a bit more once they hit my dev.to dashboard... just not sure what it was that caused the different behavior in comparison to the past posts.

**Comment by Kritner** [comment]
@maestromac can you provide sample HTML of what a code snippet *should* look like for pasting into such a tool like mentioned previously (like [Turndown](https://domchristie.github.io/turndown/)? 

I'm wondering if I could update the feed generator plugin to do a transformation like that rather than the way its doing it, but I don't know what it's *supposed* to look like.  I was hoping to grab the information from one of my successfully imported medium articles, but at a glance I wasn't able to locate the full "html" of the RSS feed from medium.

**Comment by Kritner** [comment]
As per https://github.com/hexojs/hexo/issues/3766#issuecomment-543449250, the dev.to import was correct by adding `hljs: true` under my _config.yml in the following block:

```
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: true
  hljs: true
```

This removed the table from the code block, which sounded like it was the issue from https://github.com/thepracticaldev/dev.to/issues/3995#issuecomment-532911749.  Still unclear why this suddenly stopped working (at least I think it was sudden...), but this seems to have corrected the issue with dev.to! Now how to go about finding out why the posts still aren't importing via medium...

**Comment by maestromac** [comment]
Sorry for the silence @Kritner . Happy to hear that you figured out a solution.
