### ISSUE TITLE
Uploading images

### ISSUE THREAD

**Issue by JoshCheek** [thepracticaldev/dev.to#4]
Am I able to upload images, or do I host them myself? This was the only obvious thing to me (eg it's how I uploaded the screenshot to this issue)

![upload-images](https://cloud.githubusercontent.com/assets/77495/21090042/9e28a6e2-c002-11e6-8581-7baf106d777b.gif)

**Comment by benhalpern** [comment]
For now, our users have just hosted their images elsewhere. Our CDN *ultimately* hosts them dynamically once the article is actually processed and served.

We have image upload/hosting on the feature timeline and I'll bump it on the TODOs. Should be available soon. Thanks for the feedback.

**Comment by jessleenyc** [comment]
hey @JoshCheek -- it's not drag & drop but we have an upload feature on the editor now.
