### ISSUE TITLE
Reading time of post

### ISSUE THREAD

**Issue by joeberetta** [thepracticaldev/dev.to#400]
## Feature Request or Task

As a user, I read dev.to posts everyday and it would be better if in the top of the post to see the reading time like in medium. I think its useful for readers.
What do you think @benhalpern?

**Comment by spinualexandru** [comment]
If this gets approved, I would like to work on it.

**Comment by jessleenyc** [comment]
This might be a helpful article - https://blog.medium.com/read-time-and-you-bc2048ab620c

**Comment by joeberetta** [comment]
Thank you, @jessleenyc it's helpful for me

**Comment by jessleenyc** [comment]
@joeberetta is this something you want to work on?

**Comment by joeberetta** [comment]
@jessleenyc I would try to do this. I'll be glad to contribute

**Comment by joeberetta** [comment]
Hi, @jessleenyc what do you think about script below?
```javascript
function readingTime(article) {
	var counter = 0; //words counter
	var ArrayOfWords = article.innerText.split(' ');
	var quotedText = '"'+article.innerText+'"'; // just for .match() by RegExp
	var embedRegEx = /\{\% [\s\w\d\-\+\!\?\@\`\~\.\,\:\;\/]+ \%\}/gi; //for embeds parcing
	var imageRegEx = /!\[[\s\w\d\-\+\!\?\@\`\~\.\,\:\;\/]+\]\([\s\w\d\-\+\!\?\@\`\~\.\,\:\;\/]+\)/gi; //for images parcing
	var embedCount = quotedText.match(embedRegEx).length;
	var imageCount = quotedText.match(imageRegEx).length;
	var wordsOnly = ArrayOfWords.length - embedCount - imageCount;

	for(let i = 0; i < wordsOnly; i++) //words counter++ if word is longer then 2 letters!
		if(ArrayOfWords[i].length > 2) counter++;

	var readTime = ( counter * 0.3 + embedCount * 10 + imageCount * 10 ) / 60; //200 words per minute + 10 sec for every embed/image

	if(readTime < 1) return '<1 min';
	else return '~' + Math.round(readTime) + ' min';
}
document.getElementById('rt').innerText = readingTime(document.getElementById('article'));
```

I've made it based on dev.to markdown editor.
**But** I couldn't find the right .erb/.html file where it would be inserted.
Hope, you can help with this.

**Comment by jessleenyc** [comment]
Hey @joeberetta, I think this should actually be done on the server side in the `MarkdownParser` Controller. You can add a `calculate_reading_time` method that saves the time to a new `reading_time` column on the Articles table. This would enable us to filter on reading time in the future, if we chose to and use `Article.reading_time` wherever we'd need.

**Comment by JibranKalia** [comment]
@joeberetta @jessleenyc I was wondering if I can start tackling this issue if there have been no further developments.

**Comment by joeberetta** [comment]
Hi, @JibranKalia Yes of course, I'll be glad if you will help with this task. I've started it but now I have no time for this. Hope to see the improved code from you 🍭

**Comment by Dorni2** [comment]
@benhalpern @JibranKalia Hello, this is my first time working on issues and I would like to contribute to this issue since I find it very intersting.
Is there a space for me?
Thanks.

**Comment by JibranKalia** [comment]
@Dorni2 sure. I had one pull request open #618 but that didn't go anywhere. So if you want to give it a shot

**Comment by benhalpern** [comment]
Hey @JibranKalia sorry we let your PR get lost in the shuffle. It's a good implementation. If you can re-open it and possibly fix any conflicts that may have arisen since it was last modified, we would be glad to merge it.

**Comment by maestromac** [comment]
This is partially complete. Articles now store reading time but it isn't being displayed.

**Comment by JibranKalia** [comment]
The other two things that #1283 does not address in addition to displaying the information in the front end. 

- Going back and adding the reading time for existing articles. I would imagine that would be something like a runonce rake task. But I am not sure if that is the best way. Especially if we come up with better reading time calculation methods.

- Secondly, coming up with a more complex time calculation function that takes into consideration: images and code snippets. Dividing the text between code snippets/images shouldn't be too difficult. What I am not sure of is how they are going to affect the WPM. 

I would love to work on all 3 things above. But will need some direction if possible.
