### ISSUE TITLE
Add Badges Page

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#4001]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It would be cool to see all available badges on a dedicated page for people to know which badges they can collect. There should be an indicator on whether or not a user already has a badge (i.e. all badges are grayed out but the ones they've collected are in color). Design-wise this can feel like a sticker book, maybe similar to the background on dev.to/onboarding? (you can only see that page if you're on the default color theme right now).

We'll also want to figure out how we'd display badges that are no longer available for collecting.

**Comment by benhalpern** [comment]
I think this should be `/badges`.

It should be a list of badge "shapes", e.g. empty images created with css filters.

It would look like a "sticker page", if that makes sense, like a grid of unfilled images if you don't have them.
