### ISSUE TITLE
I  can´t write a post, help me pls

### ISSUE THREAD

**Issue by jhonijlm** [thepracticaldev/dev.to#4005]
Hi, I have a problem when want to write a post  , help me pls
![image](https://user-images.githubusercontent.com/29264001/64663553-e26f7a80-d411-11e9-9215-9f76768b61a1.png)

**Comment by Bhupesh-V** [comment]
> Hi, I have a problem when want to write a post , help me pls
> ![image](https://user-images.githubusercontent.com/29264001/64663553-e26f7a80-d411-11e9-9215-9f76768b61a1.png)

Have you tried logging in again ?

**Comment by maestromac** [comment]
Hello @jhonijlm , this looks an issue specific to your account. Please email yo@dev.to for more help.

**Comment by jhonijlm** [comment]
HI, I had to delete, and register again
