### ISSUE TITLE
Cannot authenticate via Github

### ISSUE THREAD

**Issue by dakahn** [thepracticaldev/dev.to#401]
## Bug Report

When I attempt to sign up for Dev.to by OAuthing with my Github account I'm seeing this error message: _"The change you wanted was rejected. Maybe you tried to change something you didn't have access to. 
If you are the application owner check the logs for more information."_

When I check my Github account it does show that Dev.to was added to my OAuth account list. Though. Attempting to login through Dev.to after the failed OAuth still only leads me to said error page.

**Comment by Zhao-Andy** [comment]
Hey @dakahn, seems like an odd authentication bug that might be an edge case. Did you revoke access of our app from GitHub at any time? That usually seems to be an issue.

I emailed you about this to see if we can get it working.

**Comment by dakahn** [comment]
So I used to have _another_ Github account that I authed in with a long time ago. When I tried to auth with this newer one it errored. I never revoked access to the _other_ Github account.

**Comment by Zhao-Andy** [comment]
Closing since this is sorted out. :)
