### ISSUE TITLE
Follow button text missing on my profile

### ISSUE THREAD

**Issue by simplytammy** [thepracticaldev/dev.to#4010]
**Describe the bug**

a

The follow button seems to have its text missing on my profile

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device: Tecno
- OS: Android
- Browser: Chrome
- Version:

**Additional context**

**Comment by maestromac** [comment]
Thanks for helping @simplytammy  resolve this, @nickytonline !

Closing
