### ISSUE TITLE
Set maximum width on images within the chat.

### ISSUE THREAD

**Issue by omenking** [thepracticaldev/dev.to#4015]
```
When I am using chat
And I supply an image in the chat
And the image is large because I use retina display
Then the image should have a maximum width to ensure it doesn't overwhelm the page
```

<img width="1106" alt="Screen Shot 2019-09-12 at 4 37 45 PM" src="https://user-images.githubusercontent.com/7776/64819285-e3242000-d57b-11e9-9a28-6c1132ad9983.png">

**Comment by omenking** [comment]
I can't guarantee future formating. I have two babies here on my end, so many a time I am just trying to get the ticket in, otherwise, I'll just forget and not submit.

**Comment by rhymes** [comment]
@omenking eheh they definitely take priority, thanks for the issues! Keep sending them over!
