### ISSUE TITLE
Markdown processor not rendering italics / asterisks and underscores properly

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/dev.to#4021]
@remotesynth wrote:
> Just noticing that there is some weirdness around the Markdown processing of pages. I can't seem to easily get it to do things like bold only part of a word. So let's say I was wanted to emphasize the script part of JavaScript I might do Java*Script* but the markdown processor turns that into single asterisks rather than bolding. Same happens with underscores. Maybe there's something I am missing, but that works in Kramdown and in my Macdown but not in my post.

Examples:
```
Java_script_
#=> Java_script_ and not Java<i>script</i>
Java*script*
#=> Java*script* and not Java<b>script</b>
```

**Comment by araslanov-e** [comment]
This is not a bug, this is a feature https://github.com/vmg/redcarpet/blob/master/README.markdown (see no_intra_emphasis) https://github.com/thepracticaldev/dev.to/blob/master/config/initializers/redcarpet.rb

**Comment by araslanov-e** [comment]
It can be set to false, but then it is recommended that words of the form foo_bar_baz be wrapped as code
example:
```
`foo_bar_baz`
```
Otherwise, we get foo _bar_ baz (only without spaces, in Github, apparently, it’s also impossible)

**Comment by maestromac** [comment]
Thank you for putting in the research @araslanov-e !

After some discussion, we decided to stick with our current configuration to maintain the similarity between our markdown and GHFM.

**Comment by araslanov-e** [comment]
:+1:
