### ISSUE TITLE
Add a short version of a Github embed block

### ISSUE THREAD

**Issue by rumkin** [thepracticaldev/dev.to#4029]
**Is your feature request related to a problem? Please describe.**

Currently, embedding of Github repository takes very much page height. I'm usually importing a repository with some context so user don't need to view readme. It's especially actual when you import several repos in a row. Even short article became too long to scroll.

**Describe the solution you'd like**

I'd like to have a solution which allows to hide readme in a liquid tag. It could be a flag `readme`: 
```
{% github author/some-repo readme=no %}
```

**Describe alternatives you've considered**

Alternative solution is to make readme block collapsible. And add an option to manage default state collapsed/uncollapsed.

**Additional context**

What it is now:
<img width="688" alt="Screen Shot 2019-09-15 at 08 37 29" src="https://user-images.githubusercontent.com/609373/64917100-2e654b00-d795-11e9-8ecd-24a2958e597f.png">

What I'd expect it to be alike:
<img width="706" alt="Screen Shot 2019-09-15 at 08 38 24" src="https://user-images.githubusercontent.com/609373/64917105-3b823a00-d795-11e9-9604-1d4a4788fc5a.png">

**Comment by rhymes** [comment]
Love this idea!

**Comment by johncurcio** [comment]
I'd love to work on this issue. I'm gonna go with hiding the readme part if ``readme=no``. 

Are we set on this syntax (``option=value``) for the options part of the liquid tag? Because it would be nice to document this so that we stay consistent if any other tags need these types of options.

**Comment by rhymes** [comment]
Yeah, that's the format, see some tags that already support options in the [editor guide](https://dev.to/p/editor_guide) (glitch and codesandbox for example)

**Comment by rumkin** [comment]
I've checked and it seems `no-readme` will be more correct. For example glitch has url option `attributionHidden=true` which presented as `no-attribution` in liquid tags parser: [/app/liquid_tags/glitch_tag.rb:50](https://github.com/thepracticaldev/dev.to/blob/099b1885305d245f0e278c005cc3d0883e2510a3/app/liquid_tags/glitch_tag.rb#L50).
