### ISSUE TITLE
Highlight original poster

### ISSUE THREAD

**Issue by adhocore** [thepracticaldev/dev.to#403]
## Feature Request or Task

Currently in a long thread (or even long post), the discussions (comments / replies etc) doesn't visibly distinguish the original poster. Different color name, **bold**ed name, or even simple badge would be very helpful.

Thank you

-------

### Current Behavior
> OP is undistinguishable from rest of the participants

### Expected Behavior
> OP should be distinguishable from rest of the participants

### Mobile & Desktop Screenshots/Recordings
> n/a (please check any long thread)

**Comment by rhymes** [comment]
I would love this, maybe something like the AMA indicator that says something like "original poster" or "author of the article" :D 

![screenshot_2018-08-19 the dev community](https://user-images.githubusercontent.com/146201/44306864-c7aa0e00-a397-11e8-8b98-44017bffa493.png)

**Comment by BornStellarMakesEternalLasting** [comment]
The OP's reply box could also be a different color, green perhaps, to further quickly distinguish them from other posters.

**Comment by jessleenyc** [comment]
This makes sense and we should use the same format for the ask me anything. We'll have to decide on the actual word/color to use, but anyone can get started.

**Comment by sadarshannaiynar** [comment]
Ignore the reference typo occurred while writing the commit message

**Comment by sadarshannaiynar** [comment]
@jessleenyc @rhymes I have created a pull for displaying in desktops and tablets. However I have a doubt regarding the op-marker class is disabled for screens below 500px. Can I modify this rule to include screens below that width?

**Comment by Zhao-Andy** [comment]
Not stale, PR is still currently open: https://github.com/thepracticaldev/dev.to/pull/461

**Comment by maestromac** [comment]
Implemented with https://github.com/thepracticaldev/dev.to/pull/461
