### ISSUE TITLE
Reading time for posts in Feed

### ISSUE THREAD

**Issue by dzhavat** [thepracticaldev/dev.to#4047]
**Describe the bug**
The reading time for all posts but the topmost (the featured one) is 1 min.

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/1096332/65039431-8dbc8a00-d952-11e9-8351-383f9495ca28.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox (stable)
- Version: 69

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Thanks @dzhavat, great catch! It appears that all posts on the homepage, except the first one, as you noticed are indeed reset at 1 minute: https://dev.to/
