### ISSUE TITLE
[Discussion] Image Viewer

### ISSUE THREAD

**Issue by karx** [thepracticaldev/dev.to#4052]
This is in response to https://github.com/thepracticaldev/dev.to/pull/3859, which is PR adding a image viewer (luminous-lightbox).

* Do we need such a viewer?
* UI commits if needed.
* Choice of library if any.

**Comment by maestromac** [comment]
Thanks for raising this @karx 

There's already an issue on this topic at https://github.com/thepracticaldev/dev.to/issues/413 . You are encouraged to continue the discussion there

Closing.
