### ISSUE TITLE
Deleted App from keybase problems re installing due to understanding of verification

### ISSUE THREAD

**Issue by DavidRaw** [thepracticaldev/dev.to#4061]
I logged in to keybase on my PC and can see I have 2 devices. Home PC and Phone. Also have various keys. Needed to reinstall keybase app on phone as had deleted it.

On phone I choose log in, enter my user name. I then get a message 'For security reasons, you need to authorise with an existing device. Which of your existing devices would you like to choose'

I have option of Phone or Home Computer. As I am on my phone I choose home computer. It then asks I set a public name for this phone: pick a device name. I pick phone 2.

I then get a screen saying 'On home computer, go to Devices Add Device New Phone.

Here I am stuck ? I proceeded by trying to connect my phone to my PC via bluetooth? but no luck. I then tried my laptop instead and logged in to key base repeated whole process again and linked my phone to Laptop via bluetooth but again nothing on the PC happens I have a barcode on phone or a secret phrase option but nothing going on on the PC or Laptop.

Can anyone help?
Thanks

**Comment by Zhao-Andy** [comment]
Don't think I understand your comment. Is this about Keybase? As of writing, we don't have any integrations with Keybase.

Since it's not apparent that this is about dev.to, I'll be closing this issue.

**Comment by DavidRaw** [comment]
So Sorry posted in the wrong place
