### ISSUE TITLE
Notifications "Load More" button is unreadable in the night theme

### ISSUE THREAD

**Issue by kenbellows** [thepracticaldev/dev.to#4068]
**Describe the bug**

When using Dev.to's night theme, the "Load More" button in [the Notifications page](https://dev.to/notifications), seen when you scroll all the way to the bottom of the page or hit the <kbd>End</kbd> key, appears with black text (at least with default system settings; see Additional Context section below). This makes the text unreadable on the night theme's dark background.

**To Reproduce**

1. If not already using dark theme, enable it in settings:
  a. Navigate to https://dev.to/settings.
  b. Select "Misc" in the nav menu.
  c. Locate the "Site Theme" option under the "Style Customization" heading and change its value to "night theme".
  d. Click the "Submit" button at the end of the "Style Customization" section.
2. Go to https://dev.to/notifications.
3. Scroll to the bottom of the page or hit the <kbd>End</kbd> key (Windows, Linux) or <kbd>Fn</kbd>+<kbd>&rarr;</kbd> keys (Mac) to jump to the bottom of the page.
4. Observe that there is a rounded button with a white border, but apparently no content; click and drag your mouse across the button (e.g. from above it to below it) to highlight and reveal the text in the button, reading "Load More".

**Expected behavior**

In the night theme, the text of the Load More button should match the light color of all other text on the page, including other buttons (e.g., the "Write a Post" button in the site header, the "Save" button below posts).

**Screenshots**

![Load More button is unreadable in the night theme](https://user-images.githubusercontent.com/657118/65257874-f2512380-dacf-11e9-9f32-6650e5c4d637.png)

!["Load More" text becomes visible when the button is highlighted](https://user-images.githubusercontent.com/657118/65258126-5bd13200-dad0-11e9-8007-3844dfbaf0d9.png)

**Desktop**

- OS: Windows 10
- Browser: Chrome
- Version: 76.0.3809.132

**Additional context**

I inspected the button using browser dev tools and found that the button's color is never specified in CSS. As such, the user agent stylesheet takes over. Buttons are special, in that they don't inherit the `color` property from their surrounding context like other teelements do. Instead, at least in Chrome, they default to using a system defined `buttontext` color value, which defaults to black unless the user changes some OS settings. 

The solution should be as simple as adding a `color` rule to the button's CSS. It looks like this could be done under the `.notifications-index .load-more-wrapper button` selector, where the button's border and background color styles are defined. I would recommend setting its value to either `var(--theme-color)` or `var(--theme-container-color)`. Another option would be to use the `currentColor` keyword to simply inherit the color of the surrounding context, which should give the desired result.

**Comment by jessleenyc** [comment]
Fixed with #4077
