### ISSUE TITLE
Api doc not accurate with tags

### ISSUE THREAD

**Issue by cyrillefr** [thepracticaldev/dev.to#4073]
**Describe the bug**
I am working on the listing api and noticed when testing that documention for an article creation was not accurate in regards to the `tags` parameter.

**To Reproduce**
See at : [https://docs.dev.to/api/#tag/articles/paths/~1articles/post](url)

**Expected behavior**
An array should be used instead of a string (which would be tag_list)

**Screenshots**
`"article": {`
`    "title": "Hello, World!",`
`    "published": true,`
`    "body_markdown": "Hello DEV, this is my first post",`
`    "tags": "discuss, help"` <- should be "tags": ["discuss", "help"]}`

**Additional context**
Furthermore, in the Response samples, this is displayed: 
`"tag_list": "computerscience, graphtheory, bytesized, history",`
`"tags":` 
`[`
`    "computerscience",`
`    "graphtheory",`
`    "bytesized",`
`    "history"`
`]`

**Comment by rhymes** [comment]
@cyrillefr thanks for catching this!
