### ISSUE TITLE
Notification Subscriptions cut off

### ISSUE THREAD

**Issue by dzhavat** [thepracticaldev/dev.to#4097]
**Describe the bug**
When I open the "Notification Subscriptions" modal inside a post, its header gets hidden behind the top bar.

**To Reproduce**
* Open a post
* Click on the three dots in the left sidebar

**Expected behavior**

The header should be visible at all times.

**Screenshots**

![image](https://user-images.githubusercontent.com/1096332/65463464-0e4e1f80-de58-11e9-9f94-0d7dc83c2db2.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox
- Version: 69
- Screen resolution: 1366x768

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by mahamshahid18** [comment]
Hello. I would like to take a look at this issue :)

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/4167
