### ISSUE TITLE
404 page should use HTTPS image src

### ISSUE THREAD

**Issue by amdelamar** [thepracticaldev/dev.to#41]
⚠️ **Problem:**
The current 404 page ([Example here](https://dev.to/badlink)) when viewed in HTTPS shows an orange warning icon in the web browser, that HTTPS is not secure.

![image](https://cloud.githubusercontent.com/assets/18532924/26505923/93a71c42-4218-11e7-8172-d52db2975f88.png)

☑️ **Expected:**
An HTTPS page should have secure content and images.

✅ **Solution:**
Replace the HTTP links...
```html
<img class="tv__inner--special"
          src="http://i.imgur.com/Vyyjycv.gif" />
<img class="tv__inner"
          src="http://i.imgur.com/3v0LCiP.jpg" />
```
...with the HTTPS links instead.
```html
<img class="tv__inner--special"
          src="https://i.imgur.com/Vyyjycv.gif" />
<img class="tv__inner"
          src="https://i.imgur.com/3v0LCiP.jpg" />
```

**Comment by Zhao-Andy** [comment]
On it, thanks!

**Comment by jessleenyc** [comment]
Fixed
