### ISSUE TITLE
Images are neat - where are they from?

### ISSUE THREAD

**Issue by schollz** [thepracticaldev/dev.to#410]
I was looking through your image assets: https://github.com/thepracticaldev/dev.to/tree/master/app/assets/images

They are really cool. Do they have an attribution? I'd like to know more about them.

**Comment by Zhao-Andy** [comment]
Hey @schollz, that folder is sort of a random collection of various images used around the site.

The numbered images `1-40.png` are used in the parody [O RLY Cover Generator](https://dev.to/rly), and are from the [USF ClipArt ETC library](https://etc.usf.edu/clipart/).  We haven't looked at this page in a while, and just realized we should add an acknowledgment about the image source.  We're doing so in PR #432.

Most other images are just a scattered collection, but some are more important.  For instance, Sloan (`sloan.png`) is the DEV Mascot, and should only be used with our express permission (as outlined in our Trademarks and Logos Policy on the [Terms](https://dev.to/terms) page).

Please let us know if you have any other questions!

**Comment by schollz** [comment]
@Zhao-Andy Thanks a lot for the details! Its really helpful and I appreciate it!
