### ISSUE TITLE
Links in Comments get appended by dev.to's URL

### ISSUE THREAD

**Issue by Amorpheuz** [thepracticaldev/dev.to#4101]
**Describe the bug**
When I clicked on the link to the leanpub in the comment of article [Your First Year In Code: Now Available In Print!](https://dev.to/devteam/your-first-year-in-code-now-available-in-print-3pai) by [Issac](https://dev.to/isaacdlyman/comment/flcd) it redirected me to [https://dev.to/isaacdlyman/comment/leanpub.com/firstyearincode](https://dev.to/isaacdlyman/comment/leanpub.com/firstyearincode) instead of [https://leanpub.com/firstyearincode](https://leanpub.com/firstyearincode). Just to confirm also created a test article [here](https://dev.to/amorpheuz/test-post-508b) with a test comment which seems to be having the same issue! 

Getting hit by dev.to's 404 Page instead.
``` 
base-21348764b2d6ec27daf94a953246cd11e24aac20da16f75fca16b9ff96b994a8.js:70 GET https://dev.to/amorpheuz/github.com/amorpheuz?i=i 404
XMLHttpRequest.send @ base-21348764b2d6ec27daf94a953246cd11e24aac20da16f75fca16b9ff96b994a8.js:70
w @ base-21348764b2d6ec27daf94a953246cd11e24aac20da16f75fca16b9ff96b994a8.js:111
m @ base-21348764b2d6ec27daf94a953246cd11e24aac20da16f75fca16b9ff96b994a8.js:111 
```

The element seems to be coded correctly 
`<a href="github.com/amorpheuz" rel="nofollow">github.com/amorpheuz</a>`

![image](https://user-images.githubusercontent.com/22113778/65528914-dfe14a80-df12-11e9-9e23-4e4959c1e7e2.png)

**To Reproduce**
1. Go to [here](https://dev.to/amorpheuz/test-post-508b) 
2. Click on the test link in the [comment](https://dev.to/amorpheuz/comment/fled).
3. Hit by 404 Page.

**Expected behavior**
Should open the link correctly without appending dev.to.

**Screenshots**
![image](https://user-images.githubusercontent.com/22113778/65529320-8af20400-df13-11e9-899e-b7519c6db524.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Google Chrome 
- Version: 77.0.3865.90 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: Nokia 6.1
- OS: Android 9
- Browser: Google Chrome
- Version: 77.0.3865.90 

**Additional context**

**Comment by akshayymahajan** [comment]
Looks like the href attribute is missing the protocol (`http://` or `https://`). That is causing the page to be redirected to the current url appended with the href attribute..

**Comment by Amorpheuz** [comment]
Yup, that seems to be case! Would love to tackle this issue 😃

**Comment by maestromac** [comment]
go ahead @Amorpheuz !

**Comment by Amorpheuz** [comment]
So, did some digging around, If the article author creates the link markdown with the `http://` or `https://` so issue comes up. But if he directly does it without them, i.e. `[github](github.com)` then the issue comes up! 

Adding `//` before the issue resolves the issue and also makes it behave like a normal link, i.e. not append and redirects to `https://` if the site enforces it or `http://`. Are there multiple places where the link markdown is processed for each form; i.e. Article, comment, etc or a single place?

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/4155
