### ISSUE TITLE
Bad coloring on follow button

### ISSUE THREAD

**Issue by sierisimo** [thepracticaldev/dev.to#4106]
**Describe the bug**

When reading an article, sometimes the button is not clear on what it says given the colors.

**To Reproduce**

I found it on this article: https://dev.to/jmfayard/how-kotlin-makes-editing-your-gradle-build-less-frustrating-232l

Just going there, without dark mode or anything, I'm not sure if I'm following or not this particular user.

**Expected behavior**

Text with the follow status for this user should be visible or selectable

**Screenshots**

<img width="282" alt="image" src="https://user-images.githubusercontent.com/1699877/65620722-f4135f00-df87-11e9-935d-cfc1694bdc20.png">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Firefox
- Version: 69.0.1

**Comment by Amorpheuz** [comment]
Looks similar to #3968 with it occuring only on article pages.

**Comment by jessleenyc** [comment]
@sierisimo I think the issue here is that the user chose the same background and text color for the button.

**Comment by saurabhdaware** [comment]
How about having a DEV logo in edit profile that changes color as you change background color and color? This can help you tell if background color and color match properly.
something like:
<img src="https://user-images.githubusercontent.com/30949385/65887188-28897f80-e3bb-11e9-90f6-452d6b2f28c6.jpeg" width=300>
(Sorry for my drawing skills I edited in instagram stories :sob: :rofl: )

**Comment by jessleenyc** [comment]
WOW, I love that idea.

**Comment by jessleenyc** [comment]
Also want to point out that #1774 offers another solution

**Comment by saurabhdaware** [comment]
Cool, Can I give it a try?

**Comment by saurabhdaware** [comment]
I loved the idea of input type=color. How about having a button beside textbox and user can either type color code in textbox or he can tap the button and select the color and that color code will appear in textbox. 

This will make it easy to select 

and we can keep that DEV logo preview beside for better understanding of contrast.

**Comment by saurabhdaware** [comment]
![image](https://user-images.githubusercontent.com/30949385/65890195-1eb64b00-e3c0-11e9-975b-70e40d796715.png)
Did a quick inspect

**Comment by jessleenyc** [comment]
@saurabhdaware go for it!

**Comment by saurabhdaware** [comment]
Thanks @jessleenyc I'll start working on it then! :sunflower:
