### ISSUE TITLE
TIL tag in post title

### ISSUE THREAD

**Issue by dzhavat** [thepracticaldev/dev.to#4110]
**Is your feature request related to a problem? Please describe.**

I just thought of an idea for a new title tag - TIL (short for "Today I Learned"). This can be used for short posts where people share stuff they have learned recently.

**Describe the solution you'd like**

Here's how that might look like:

![image](https://user-images.githubusercontent.com/1096332/65640475-bbf13800-dfea-11e9-9178-ed5ad559749b.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by cesc1989** [comment]
How would it be different than using a normal tag? 🤔

**Comment by dzhavat** [comment]
The only difference will be the presence of `#til` tag in the post title. And the tag itself will be colored.

**Comment by cesc1989** [comment]
@dzhavat I see your point after seeing this

![image](https://user-images.githubusercontent.com/1375981/65775891-a5400380-e106-11e9-81cc-987b847c20ba.png)

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/4370
