### ISSUE TITLE
Iam unable to post anything

### ISSUE THREAD

**Issue by leesadaisy** [thepracticaldev/dev.to#4117]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by nathanheffley** [comment]
Do you have any additional information? A screenshot of what happens when you try to post?

**Comment by maestromac** [comment]
Hello @leesadaisy , this looks an issue specific to your account. Please email yo@dev.to for more help.
