### ISSUE TITLE
Listings API index: category and per_page parameters are not working

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#4125]
**Describe the bug**

The new listings API - https://dev.to/api/listings - is not respecting parameters `category` and `per_page`

I believe it has something to do with caching and this line: 

https://github.com/thepracticaldev/dev.to/blob/8a5fb233355f36dd1f4dbc6fbee54ebf937a701e/app/controllers/api/v0/classified_listings_controller.rb#L24-L25

I don't think edge caching is configured correctly here

**To Reproduce**

- https://dev.to/api/listings?category=misc should only return `misc` listings, instead it returns the result of https://dev.to/api/listings (without any filtering)
- https://dev.to/api/listings?per_page=1 should return only 1 listing, instead it returns the same result of https://dev.to/api/listings

https://dev.to/api/listings?page=2 is the only one working

**Expected behavior**

I expect parameters to work like they do locally without edge caching

**Comment by benhalpern** [comment]
I adjusted the Fastly config and this might be working now. Haven't confirmed.

**Comment by rhymes** [comment]
I just tried the following:

```shell
➜  ~ curl https://dev.to/api/listings\?category\=misc | jq '. | map(.category)'
[
  "misc",
  "misc",
  "misc",
  "misc",
  "misc",
  "misc",
  "misc",
  "misc"
]

➜  ~ curl https://dev.to/api/listings\?per_page\=1 | jq '. | length'
1
```

So it looks like it's working, thank you, I'm going to close this!
