### ISSUE TITLE
Reduce Docker image build time for dev

### ISSUE THREAD

**Issue by BobbyMcWho** [thepracticaldev/dev.to#4129]
Ideally we would not need to go through every single one of these multi-build steps every time we want to build the container. It looks like each step of the build could potentially be its own image, stored in a separate folder or repo and released to docker hub and pulled in instead of being built.

**Comment by sebach1** [comment]
Agree. I'm on it :)

**Comment by abenettt** [comment]
This would reduce build time, not only for dev, but I wonder why we have to build ruby and node ourselves instead of using the respective docker images for them. We could still use a multistage builds to install necessary dependencies but it would reduce the build time significantly.

**Comment by hecbuma** [comment]
Hi, I'd like to give a hand, seems the Dockerfile needs some love, a first step to do a clean up will be great then see which parts can be moved to its own image.

**Comment by BobbyMcWho** [comment]
I agree, I haven't had the time to do an audit of what the current Dockerfile installs vs what comes in a base image of various already available containers
