### ISSUE TITLE
Author notes feature

### ISSUE THREAD

**Issue by Almenon** [thepracticaldev/dev.to#4130]
**Is your feature request related to a problem? Please describe.**

I have personal notes in the article that I need to take out and store someplace else before I publish it.

**Describe the solution you'd like**

A section for author notes that won't appear in the preview or published article.
For example, 

> {% beginNotes %} notes {% endNotes %}

**Describe alternatives you've considered**

I just realized this feature sort of already exists in that I could wrap my notes in a html comment `<!-- notes -->`. I didn't think of doing this untill I wrote this issue - maybe it should be included in the ? help section?

**Additional context**

**Comment by kay-is** [comment]
I tried to find out where to add this, but it seems all files I found aren't really used (different emojis, and texts etc.)

There is just one `editor_guide_text` erb code-snipped, but I can't find out where it leads to.

**Comment by Zhao-Andy** [comment]
`_editor_guide_text.html.erb` is a good place to put it! That's the same text that corresponds to `/p/editor_guide` and the editor guide in the article editor.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/4178
