### ISSUE TITLE
Asciinema Liquid tag

### ISSUE THREAD

**Issue by foo-dogsquared** [thepracticaldev/dev.to#4135]
**Is your feature request related to a problem? Please describe.**

It would be cool if we can view [Asciinema](https://asciinema.org/) recordings while viewing an article inside dev.to. 

Asciinema does provide a way to embed the video player. 
You can see it [in the respective doc page](https://asciinema.org/docs/embedding). 

**Describe the solution you'd like**

A simple Liquid tag implementation that quickly provides a template for embedding Asciinema recordings. 

The Liquid tag would accept an ID of the recording. 
The ID is basically the number at the end of the URL of the recording (if the link is `https://asciinema.org/a/239367` then the ID is `239367`). 

Using the Liquid tag would look like this: `{% asciinema <ID> %}`.  
Then it would have the equivalent HTML output in the following code listing. 

```
<script id="asciicast-<ID>" src="https://asciinema.org/a/<ID>.js" async></script>
``` 

EDIT as of 2019-09-30: @Glennmen suggested on embedding through an iframe which is a better option, IMO. 
The equivalent HTML output is also simpler. 

```
<iframe src="https://asciinema.org/a/<ID>/iframe"></iframe>
```

**Comment by Glennmen** [comment]
Not sure if I like to embed a JS script directly in the page, an iframe would be a much better option.

Strange that the docs don't mention this but you can use an iframe:
```html
<iframe src="https://asciinema.org/a/239367/iframe">
</iframe>
```

**Comment by foo-dogsquared** [comment]
I knew it! There is an iframe embed! 

I have the same sentiments when it comes to embedding with `<script>`. 
That is a better way of embedding it. 
It has simpler HTML output, too. 

Thanks for letting me know.
