### ISSUE TITLE
Use concerns to extract common code from models

### ISSUE THREAD

**Issue by amrrbakry** [thepracticaldev/dev.to#415]
## Feature Request or Task
Hey guys, I noticed that you're not using concerns in models or controllers. I think it would improve the readability and maintainability of the code if we extracted common or context-specific code into a concern and included it in all the models that need it. 

I can help with that if it's approved. What do you guys think?

**Comment by benhalpern** [comment]
I've never been crazy about concerns, but I could be convinced otherwise.

I agree with anything we can do to improve things along these lines, so open to suggestions.

**Comment by amrrbakry** [comment]
Well, I believe that concerns could be very useful for any of these cases: caching, soft deletion, or localization.

consider this:

```ruby
module SoftDeletion
  extend ActiveSupport::Concern

  included do
    acts_as_paranoid column: :deleted_at

    def delete
      raise 'Use destroy instead so that dependent objects get soft deleted as well'
    end
  end
end
```
now our models simply gain soft deletion functionality by including this concern. it's clean and reusable across projects. 

I've been reading the code but i'm not really sure where this applies; you guys probably have a better idea about this. what do you think?
