### ISSUE TITLE
Organization name does update when changing the `name` field.

### ISSUE THREAD

**Issue by autoferrit** [thepracticaldev/dev.to#417]
### Current Behavior
On the [/organization](https://dev.to/settings/organization) page, changing the `name` field to change the name of my organization, will save. But does not actually change the name of the organization.

### Expected Behavior
Changing the `name` field in an organization, changes the actual name of the organization at the top of the page.

### Additional Info (device/browser, helpful links)
Chrome `69.0.3497.42` on linux

#### Note: previously also mentioned the url not changing, moved to #462

**Comment by jessleenyc** [comment]
Hey @autoferrit! It's definitely a bug that the name is not updating, but right now it is expected behavior for the url not to update. Would you mind creating a separate feature request for that?

**Comment by autoferrit** [comment]
Done #462. I updated the description here to just reflect the title.

**Comment by autoferrit** [comment]
I just went to my organization page, and tried changing the name, in this image, you can see i just saved it and it shows the old name.
![devtoorg](https://user-images.githubusercontent.com/89895/45918646-fad03900-be3e-11e8-96c0-c5ab8d2a625f.png)

**Comment by autoferrit** [comment]
I dont even see where your screenshot of the name would come from.

**Comment by djhopper01** [comment]
@autoferrit Sorry about that. I should've been more clear in my steps. What you said is what I was seeing as well. The name changes on the public organization page.

**Comment by Zhao-Andy** [comment]
Not stale; we'll check to see if this is still an issue after the holidays.
