### ISSUE TITLE
Docker gem install issues on a mac host

### ISSUE THREAD

**Issue by negue** [thepracticaldev/dev.to#4179]
**Describe the bug**

When I wanted to try out the docker dev environment, I always got this error:

```
../libev/ev.c:1620:73: fatal error: linux/aio_abi.h: No such file or directory  # include <linux/aio_abi.h> /* probably only needed for aio_context_t */
```

Even though `linux-headers` are installed in the Dockerfile, I still had to execute `apk add linux-headers` inside my container, in-order to be able to execute `devto-setup`

**To Reproduce**

1. `./docker-run.sh DEV` on a mac host
2. call `devto-setup``
3. get the error above

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mac
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by sebach1** [comment]
The trouble isn't your OS, I'm getting the same err in Ubuntu 18.04.
It became from the gem nio4r, and it's corrected in the patch https://github.com/socketry/nio4r/commit/0e820966453acff44a0e5763224ae91008a43306.

submitted a PR

**Comment by negue** [comment]
Oh, I see, thanks for clearing that its not because of the Mac ^^

**Comment by rhymes** [comment]
@negue if you can confirm that now, after such patch, it works, let me know so I can safely close this issue.

Thanks!

**Comment by maestromac** [comment]
Can you verify that this issue is resolved @negue ?

**Comment by negue** [comment]
I pulled the repo, removed all docker images / containers and re-run `docker-compose build`. The issue is resolved :tada:
