### ISSUE TITLE
Support for non english characters in tags

### ISSUE THREAD

**Issue by yorodm** [thepracticaldev/dev.to#419]
### Current Behavior
When you add a tag name with a non english charactes (i.e. español) it doesn't show in the tag name after saving your post
### Expected Behavior
Be able to tag my posts as #español ;D

**Comment by benhalpern** [comment]
Hmmm this is an interesting discussion. We definitely want to make #español and #espanol equivalent for the purpose. I'm not sure what the ultimate decision here is.

On this note, we do have a "language" column on posts. I'm not sure it actively works. It sort of rescues failures and there may be hidden issues here. It needs more focus in general, how all this fits together re: language.
