### ISSUE TITLE
Autosave, not only Save Post

### ISSUE THREAD

**Issue by danielsto** [thepracticaldev/dev.to#42]
It would be a great feature to avoid having to save manually. It's easy to forget about it and close tab/browser and lose everything since the last save.

**Comment by Zhao-Andy** [comment]
Hey @danielsto, thanks for the feedback. We're going to do major updates to the editor in the future and this will definitely be a part of that overhaul.

**Comment by tomer-ben-david** [comment]
is it already autosaving? i don't see it is.
