### ISSUE TITLE
API inconsistencies between articles "index" and "show"

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#4206]
*I'm promoting an issue comment to a separate issue to avoid losing the conversation inside a separate thread.*

_Originally posted by @Turnerj in https://github.com/thepracticaldev/dev.to/issues/2996#issuecomment-537825737_

I'm not sure if it is worth adding to this (as it is an inconsistency, just not specific to tags) or filing it separately but there seems to be even a greater drift between the data returned for the two different article APIs (whether you request a single article or view the list).

"ArticleShow" includes the following which don't match up to "ArticleIndex":
- readable_publish_date
- social_image
- the "tags" vs "tag_list" stuff I mentioned in [this issue](https://github.com/thepracticaldev/dev.to/issues/2996)
- comments_count
- created_at
- edited_at
- crossposted_at
- last_comment_at
- body_html
- body_markdown

"ArticleIndex" includes the following which don't match up to "ArticleShow":
- published_timestamp (Note: Technically this field should the "crossposted_at" OR "published_at" if the API doc is right though still redundant if "crossposted_at" was there instead)
- organization
- flare_tag

I could completely understand the "body_html" and "body_markdown" fields wouldn't be on the "ArticleIndex" endpoint as that could be a ton of unnecessary data transferred though every other field feels like fair game to be in both APIs.

I know the last time we talked about just the tag stuff, there is concern with breaking existing functionality and that is a fair point. I feel though the longer these inconsistencies exist, the higher the chance that more code will depend on the inconsistencies.

I'm happy to help do this and raise a PR with the various changes etc happening (though not being a Ruby developer, I'd still be winging it quite a bit). I personally just want to get the ball rolling to remove this technical debt sooner rather than later.

_Originally posted by @Turnerj in https://github.com/thepracticaldev/dev.to/issues/2996#issuecomment-537825737_

**Comment by rhymes** [comment]
@Turnerj I went ahead and promoted your comment to an issue, hope you don't mind, so to separate the two discussions.

My answer: generally speaking there are inconsistencies in the API v0, some of them we might be able to solve, some probably won't until we decide to redesign the API for a v1 and/or setup a deprecation plan for far in the future.

The reason being that the API has been public knowledge (both the part that is documented and the part that is not), various integrations and even public projects using the API are in production and and we can't go ahead and easily break the interface.

What we can consider is adding fields when missing, not easily remove or change their format.

I fear the `tags` and `tag_list` will likely be like that for the foreseeable future though, not to break any consuming clients.

**Comment by Turnerj** [comment]
Don't mind at all with the comment being promoted to an issue - it probably was a bit of a stretch for me to tie it to the issue with tags. Will be great to see uniformity between the endpoints - would you still want a PR potentially with the missing fields being added to each other's API or would you rather discuss internally what you want to do first (and/or handle it internally)?

Just an aside to the tags stuff, while I do understand what you're saying about various integrations and even public projects using the API, the API is pre-v1 and marked as beta - I would have considered the API to be usable but functionally unstable. Depending on an API prior to its v1 is a risky move. Sure you don't want to change it every other day but if in the course of several months go "hey, we should really change that", it is great having the agility to do that prior to "stable" launch.

It also wouldn't be the first breaking change either with multiple organisation support breaking how creating articles worked for the API in June or the whole "onboarding" endpoint being removed in August (I admit that last example is probably more fair - how many people actually used that endpoint besides the DEV website itself).

If a line needs to be drawn though with how likely a specific part of an API should change though and that line is stuff like title, user, tags and main article body, I understand. 🙂

**Comment by rhymes** [comment]
@Turnerj, you make compelling arguments, I'm going to raise the topic internally and get back to you. We should definitely make a concerted decision on how to proceed regarding the mere addition of new fields but on deprecation and changes in a more ample view of the API evolution.

Thanks a lot, really :)

**Comment by jessleenyc** [comment]
Totally forgot to respond here! Sorry for the delay. We talked about this internally and decided we should, for now, address the inconsistencies by adding any fields that were missing from articles#index to articles#show and vice versa.

**Comment by nadiyaka** [comment]
Hi @jessleenyc! Is this issue available or somebody else is currently working on it?

**Comment by rhymes** [comment]
@nadiyaka no one is working on it as far as we know. What would be your plan of action?

**Comment by nadiyaka** [comment]
As @jessleenyc wrote above, the decorator fields for index and show should be the same. So I was planning to check what fields were missing on each request and add them. Is this correct?

**Comment by rhymes** [comment]
@nadiyaka perfect! Remember that the bodies of the articles shouldn't appear in the index

Thank you!

**Comment by nadiyaka** [comment]
@rhymes, you mean "body_html" and "body_markdown", right?

**Comment by rhymes** [comment]
@nadiyaka exactly!
