### ISSUE TITLE
Can't disable community-success notifications

### ISSUE THREAD

**Issue by Turnerj** [thepracticaldev/dev.to#4210]
**Describe the bug**

On the [`Settings -> Notifications`](https://dev.to/settings/notifications) page, when you uncheck the "community-success" notifications checkbox and submit, the page says it has saved but the checkbox is still checked.

**To Reproduce**

1. Go to: https://dev.to/settings/notifications
2. Uncheck the "community-success" notifications checkbox at the bottom
3. Submit
4. See that the page says it is saved but the checkbox is still checked

-----

I'm no Ruby developer but I did some digging myself, comparing that specific checkbox to the other checkboxes on the page in the codebase. One similarity between say "mobile_comment_notifications"/"email_unread_notifications" and "mod_roundrobin_notifications" is that the latter doesn't appear in the permitted attributes list on the UserPolicy:

https://github.com/thepracticaldev/dev.to/blob/c8abbe9d609298b8c2ef99185dc1061c21003b27/app/policies/user_policy.rb#L54-L116

Would love to know (when this is fixed) whether that is actually all you needed to do to fix the problem.

**Comment by akshayymahajan** [comment]
I would like to work on this but can't seem to find the checkbox on my notification settings page..

![image](https://user-images.githubusercontent.com/8535863/66186387-c1601980-e69f-11e9-8acd-a6528b72f777.png)

**Comment by akshayymahajan** [comment]
After looking at the code, it looks like the checkbox is rendered with name `mod_roundrobin_notifications` and the premitted attributes contain `email_community_mod_newsletter` for the community-success newsletter..

**Comment by akshayymahajan** [comment]
Looks like it is conditionally rendered..

**Comment by jessleenyc** [comment]
@akshayymahajan if you assign yourself a trusted role in development, it'll pop up for you. to do that, you can go into the rails console and add the role `User.find(#).add_role :trusted`

**Comment by akshayymahajan** [comment]
Thanks @jessleenyc, that worked!
