### ISSUE TITLE
numeric characters in tags

### ISSUE THREAD

**Issue by awwsmm** [thepracticaldev/dev.to#4211]
This might be related to other tag issues, but it looks like numeric characters are completely blocked from appearing in tags at the moment. This makes it impossible to type out common post tags like `a11y` and `k8s`.

**To Reproduce**

1. Log in to Dev.To.
2. Click on "WRITE A POST" in the upper-right corner of the screen
3. Attempt to add a tag which contains a number to the post

The number will not appear in the text input box. It looks like there's some kind of filtering happening to remove special characters, but it has the effect of disallowing numbers, as well.

**Desktop:**

- OS: macOS Mojave v10.14.6
- Browser: Google Chrome
- Version: 76.0.3809.132 (Official Build) (64-bit)

**Comment by caleb15** [comment]
Our company is called 15Five ...... yeah. Can't tag my own company :(
