### ISSUE TITLE
Request to support JSitor Embeddable

### ISSUE THREAD

**Issue by ashvin777** [thepracticaldev/dev.to#4214]
Hi Dev.to Team,

This is a feature request to support JSitor as embeddable content on Dev.to article sites. I have seen that JSFiddle and Codepen are supported in Dev.to which is great and same way we would like to add the support for JSitor as well.

The pattern followed for Codepen is as such
{% codepen https://codepen.io/twhite96/pen/XKqrJX %}

We would like to use the same pattern. JSitor already supports oembed protocol if that is the integration required. If not, the main site generally is loaded with below URL
https://jsitor.com/IfRnIEscb

and embeddable formats can be loaded with 
https://jsitor.com/embed/IfRnIEscb

So I would like to have this support as such
{% jsitor https://jsitor.com/embed/IfRnIEscb %}

**Comment by jessleenyc** [comment]
Cool, this is approved for anyone that'd like to take it on. Here's some documentation on liquid tags: https://docs.dev.to/frontend/liquid-tags/

**Comment by sagarchoudhary96** [comment]
@jessleenyc  can i take it up?

**Comment by jessleenyc** [comment]
@sagarchoudhary96 go for it!

**Comment by sagarchoudhary96** [comment]
will try it, saw it later that code is in ruby mostly and I haven't worked with ruby before.

**Comment by ashvin777** [comment]
Hey @sagarchoudhary96 and @jessleenyc , Thanks for taking this up. 

Is it possible to do a minor change here, is it possile to resolve 
{% jsitor https://jsitor.com/IfRnIEscb %} to {% jsitor https://jsitor.com/embed/IfRnIEscb %} ?

Also, I would like to show the fullscreen page view as well which has /p/ in the middle of the path
{% jsitor  https://jsitor.com/p/IfRnIEscb %}, let me know if this will need any additional work from my side.

**Comment by ashvin777** [comment]
Any updates?

**Comment by sagarchoudhary96** [comment]
@ashvin777  I haven't taken this up as i don't have experience with ruby and  currently not able to put in time.

**Comment by ashvin777** [comment]
Thanks @sagarchoudhary96 . 

@jessleenyc , can anyone else take this up?

**Comment by rhymes** [comment]
@ashvin777 sure, you can go ahead if you feel like it! In the meantime we'll leave the issue open for hacktoberfest!

**Comment by artoodeeto** [comment]
@ashvin777 @rhymes yow this is cool. let me do it on Saturday or after this pr #4456 is merge. Ill just do what codepen does using iFrame.

**Comment by artoodeeto** [comment]
@ashvin777 sorry. just read about your requirements. so basically you want this to render as is or like a code snippet? what I mean about code snippet is when we render this `{% jsitor https://jsitor.com/embed/IfRnIEscb %} ?` part of the code will be like `code snippet`?

**Comment by ashvin777** [comment]
Hi @artoodeeto ,  

So its should always load the embedded code snippet using URL `https://jsitor.com/embed/${snippetId}`. 

Also this 
`{% jsitor https://jsitor.com/IfRnIEscb %}` -- should change to(or load embed path)--> `{% jsitor https://jsitor.com/embed/IfRnIEscb %}`.

**Comment by artoodeeto** [comment]
@ashvin777 alright. so iframe will just do it fine then since it will just render like codepen. btw the path with the `embed` is the one should be embeddable?  I was thinking any jsitor will do.

**Comment by ashvin777** [comment]
For now just the URL with `embed` should be embeddable. 
Thanks

**Comment by artoodeeto** [comment]
@ashvin777 gotcha. :) I havent started yet though. im gonna start it today. :)

**Comment by ashvin777** [comment]
Awesome thanks @artoodeeto .

**Comment by artoodeeto** [comment]
@rhymes @Zhao-Andy  hello may I ask how do you setup debugger on ruby? I followed [this](https://dev.to/dnamsons/ruby-debugging-in-vscode-3bkj) and [this](https://github.com/Microsoft/vscode-recipes/blob/2174a750102a76142378ea08dbbb4a576dc6d1d5/debugging-Ruby-on-Rails/README.md) I think its different from your setup.

**Comment by rhymes** [comment]
Hi @artoodeeto, I'm not familiar with the interactive debugger of VSCode with Ruby. What kind of error did you have?

I usually add the `binding.pry` to the line before I need to inspect, that acts as a breakpoint, for example:

```ruby
def hello():
   binding.pry
   return "hello"
```

When `hello()` gets invoked you'll see the Rails process pause and step into a debugging session in that line. Typing `help` will give you all the commands you need to step, add further breakpoints and so on.

**Comment by artoodeeto** [comment]
@rhymes i was trying to do it on vscode. I use `binding.pry` on spec files, but i guess this will work. let me try to change the launch files too and maybe add it on dev documentation.

**Comment by artoodeeto** [comment]
**UPDATE**

*MOBILE* 📱 
<img width="388" alt="Screen Shot 2019-10-26 at 5 01 05 PM" src="https://user-images.githubusercontent.com/19770382/67627535-e2d1a280-f812-11e9-97b0-123742bca0e6.png">


*TABLET* :tablet
<img width="624" alt="Screen Shot 2019-10-26 at 5 01 17 PM" src="https://user-images.githubusercontent.com/19770382/67627548-07c61580-f813-11e9-8263-0da71fd41597.png">


*DESKTOP* 🖥 
<img width="1196" alt="Screen Shot 2019-10-26 at 5 01 50 PM" src="https://user-images.githubusercontent.com/19770382/67627555-288e6b00-f813-11e9-91e3-3f22f0aee05f.png">

*ERROR* without **embed** link
<img width="936" alt="Screen Shot 2019-10-26 at 5 03 36 PM" src="https://user-images.githubusercontent.com/19770382/67627559-452aa300-f813-11e9-89b2-febe7458ca03.png">

@ashvin777 watcha think my dude? I also think you need a separate link as embeddable instead of this. 
```
<iframe width="100%" height="400" src="https://jsitor.com/embed/1QgJVmCam" frameborder="0"></iframe>
``` 

maybe you could add just a like `https://jsitor.com/embed/1QgJVmCam` or do you have it already and im being blind. and sorry it took too long I had to bring some work from home. ✌️ 

I just to add some test

**Comment by artoodeeto** [comment]
@ashvin777 hey sir I made a pr for this. heres the pr #4657 let me know if you want me to add more.

**Comment by ashvin777** [comment]
This looks super awesome @artoodeeto. Thank you so much for implementing this feature. Yes, the embed link is separate. 

Just one comment, is it possible to improve the error message?
 Instead of just saying "Make sure its embeddable link", we can be more specific say include "/embed/" in the link, Example - https://jsitor.com/embed/1QgJVmCam
