### ISSUE TITLE
Articles API: using collection_id does not return the correct results

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#4234]
**Describe the bug**

https://dev.to/api/articles?collection_id=1693 should return articles belonging to that collection, instead it's returning returning articles that do not belong to any collection.

This does not happen in development mode, which makes me think it's a caching issue.

The articles index has a weird caching surrogate key, I think we should consider following the instructions set by fastly and use a regular caching key: https://github.com/fastly/fastly-rails#headers 

**To Reproduce**

1. Go to https://dev.to/api/articles?collection_id=1693 
2. Verify that instead of articles of collection 1693 (which is "Byte sized", you can verify by getting the JSON of an article in that collection: https://dev.to/api/articles/150589), the system is indeed returning articles with no collection

Any other collection id gives the same sets of results, which is a strong indication it might be a caching issue

**Expected behavior**

I expect to be returned only articles belonging to the requested collection

**Screenshots**

![Screenshot 2019-10-04 at 6 08 50 PM](https://user-images.githubusercontent.com/146201/66222788-3b10fb00-e6d2-11e9-84d7-67e468a1bfac.png)

**Comment by rhymes** [comment]
@benhalpern could you check also this in fastly?

**Comment by benhalpern** [comment]
@rhymes yes, this was resolved by adding `collection_id` to the list of allowed params.

**Comment by rhymes** [comment]
Verified it works, closing this now.

Thanks Ben!
