### ISSUE TITLE
I received multiple "confirm email address" emails when I signed up

### ISSUE THREAD

**Issue by AndrewPetz** [thepracticaldev/dev.to#424]
### Current Behavior
Upon signup, I received 15 "confirm email address" emails.

### Expected Behavior
I should only have received one email.

### Mobile & Desktop Screenshots/Recordings
![chrome_2018-08-21_12-31-40](https://user-images.githubusercontent.com/7032619/44420095-a46f9200-a542-11e8-83d5-f2557d61e820.png)

### Additional Info (device/browser, helpful links)
Only the final email sent (the top one in the screenshot) had the correct link. All others led me to a page with this error message:

![chrome_2018-08-21_13-06-30](https://user-images.githubusercontent.com/7032619/44420252-11832780-a543-11e8-9f3f-896da89a6af4.png)

**Comment by Zhao-Andy** [comment]
Hey @Nannooskeeska, thanks for the bug report. We'll investigate and see what's going on there.

**Comment by Zhao-Andy** [comment]
I believe this is fixed, but not sure. @jessleenyc I think you looked into this?
