### ISSUE TITLE
Get views count for authenticated users published articles

### ISSUE THREAD

**Issue by sandordargo** [thepracticaldev/dev.to#4250]
Hello,

I'm preparing some analytics for my articles (I also plan to publish the script). Scarping my dashboard to get the data is not convenient and will break fast.

Then I found the [DEV API](https://docs.dev.to/api/#tag/articles/paths/~1articles~1me~1published/get). I understand why we cannot get just for anyone the views count, but I'd like to get it for the authenticated user's published articles.

I'm happy to work on the feature myself, if I receive some guidenance where to look for the data/API.

Cheers,

Sandor

**Comment by matisnape** [comment]
I would like to try this :)

**Comment by CharlesStover** [comment]
Was opening an issue for this, but will merge it here:

**Is your feature request related to a problem? Please describe.**

I want to be able to display the page views of my articles on my portfolio.

**Describe the solution you'd like**

I would like the `GET /articles?username=CharlesStover` endpoint to return page views in addition to other metadata.

**Comment by matisnape** [comment]
@CharlesStover This issue specifically mentioned page views of authenticated authors. I don't think page views are visible in the app for anyone except the article author (but maybe I'm mistaken)

**Comment by rhymes** [comment]
@matisnape you're correct, page views should only appear to yourself when you're authenticated.

Once #4393 is merged, you'll be able to fetch `GET /articles/me` as an authenticated user and find the page views inside. Would that work for you?

**Comment by sandordargo** [comment]
@rhymes @matisnape #4393  looks great to me, thanks

**Comment by CharlesStover** [comment]
My use case is just to display views on my portfolio. While it would be easiest to do this unauthenticated so that the front end app can hit dev.to directly without the need for a back end, I am capable of having a back end authenticate first in order to get the page view count. My ultimate request is just to have access to my own page view counts, and I can understand not having those be public, though my preference is them being public to avoid the hassle of authentication.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/4393

**Comment by sandordargo** [comment]
Thanks a lot!
