### ISSUE TITLE
Some job tests are not being executed and they do not fail

### ISSUE THREAD

**Issue by johncurcio** [thepracticaldev/dev.to#4269]
**Describe the bug**

Tests inside a ``perform_now`` scope are never executed. Take, for example, ``bust_cache_job_spec.rb``:

https://github.com/thepracticaldev/dev.to/blob/66faaccdd894a75887e6e3dfad30a3152e18a4fb/spec/jobs/articles/bust_cache_job_spec.rb#L20-L22

This line has a typo. It's supposed to be have_receive**d**, and yet the test passes. The reason for that is because the test is inside a ``describled_class.perform_now`` scope, which is never executed. 

**To Reproduce**

Change the test to:

```ruby
it "async busts cache" do
  cache_buster = double
  allow(cache_buster).to receive(:bust_article)

  described_class.perform_now(article.id, cache_buster)
  expect(cache_buster).to have_receive(:bust_article).with(article)
end
```
and it will fail because of the typo in ``have_receive``.

Another way to see that this is never executed is using ``pry``. Add a ``binding.pry`` inside the ``perform_now`` scope and run the test - the ``pry`` is never reached. 

**Expected behavior**

There should not be any ``perform_now`` scopes in tests, because nothing inside those get executed. 

**Additional context**

These are the tests that contain a scope like that:

- [ ] articles/bust_cache_job_spec.rb
- [ ] detect_human_language_job_spec.rb
- [ ] score_calc_job_spec.rb
- [ ] update_main_image_background_hex_job_spec.rb
- [ ] calculate_score_job_spec.rb
- [ ] create_id_code_job_spec.rb
- [ ] send_email_notification_job_spec.rb
- [ ] touch_user_job_spec.rb
- [ ] populate_history_job_spec.rb
- [ ] users/bust_cache_job_spec.rb
- [ ] resave_articles_job_spec.rb

**Comment by rhymes** [comment]
Hi @johncurcio, first and foremost: thank you! This is a great catch! I have the feeling this is the result of an error introduced in one of these files and copy and pasting to follow the same pattern after that.

This is definitely approved :-)
