### ISSUE TITLE
See the number of comments

### ISSUE THREAD

**Issue by BornStellarMakesEternalLasting** [thepracticaldev/dev.to#427]
### Feature Request or Task
Add a counter that shows the number of comments on a post.

### User Story / Description
When I scroll towards the bottom of a post I like to preview the comment section by knowing how many comments there are. Just knowing approximately how many comments I can read makes me happy. 

### Definition of Done
When there is a counter that accurately displays the total number of comments. 
-------
### Current Behavior
There is no counter, visible to an end-user, that shows how many comments a post has. 
### Mobile & Desktop Screenshots/Recordings
![nocommentaccmulator](https://user-images.githubusercontent.com/40554549/44420665-8dce3880-a54c-11e8-94ab-ae697747e906.png)

**Comment by markfrst** [comment]
Where exactly should be placed the counter?

**Comment by BornStellarMakesEternalLasting** [comment]
Maybe it could go above the `Add to the discussion` box like on the OMG Ubuntu website. Or maybe it would make more sense to have it next to the heart, unicorn, and book marks buttons. Here's a picture for reference.

![commentaccmulatoromg_ubuntu](https://user-images.githubusercontent.com/40554549/44599287-cddb2880-a7a3-11e8-8665-79f5815dda1a.png)

**Comment by markfrst** [comment]
@jessleenyc i can make it, what you think about this feature?

**Comment by maestromac** [comment]
This was implemented. Closing.
