### ISSUE TITLE
Link liquid tag: error message is not informative or not showing the right error

### ISSUE THREAD

**Issue by artoodeeto** [thepracticaldev/dev.to#4271]
**Describe the bug**
when using the liquid link tag it shows an error message that is not informative

if you put this in the liquid link tag `{% link https://blog.smartcodehub.com/node-image-upload-api/ %}` error message is `base:  undefined method `[]' for nil:NilClass` this should be caught and return an appropriate error message

**To Reproduce**

1. create a new post 
2. use liquid link tag and give it a incorrect link sample `{% link https://blog.smartcodehub.com/node-image-upload-api/ %}`
3. hit preview
4. check the error message

**Expected behavior**

**Screenshots**
![Screen Shot 2019-10-06 at 1 49 54 PM](https://user-images.githubusercontent.com/19770382/66275837-754cda80-e841-11e9-8c41-55d4b8345ff1.png)

**Desktop (please complete the following information):**

- OS:  macOS 
- Browser: Chrome Version 77.0.3865.90 (Official Build) (64-bit)
- Version: Mojave 10.14.6 18G95 x86_64

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by danhuynhdev** [comment]
Is anybody taking this? I might be able to help.

**Comment by artoodeeto** [comment]
@danhuynhdev I was thinking about it but im still at work you can have this one :)

**Comment by artoodeeto** [comment]
@danhuynhdev hello do you want to work on this?

**Comment by danhuynhdev** [comment]
Sure, I'll take it

**Comment by danhuynhdev** [comment]
Just create a PR and link it to this issue. Not sure who I should ping to review it :thinking:

**Comment by Link2Twenty** [comment]
Ping: @rhymes

**Comment by rhymes** [comment]
@Link2Twenty the PR already has a review by https://github.com/thepracticaldev/dev.to/pull/4341#pullrequestreview-299625738 😅

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/4341
