### ISSUE TITLE
Small nags in text area of /internal/articles

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#4276]
Two nits that I imagine are quick fixes:

## Inconsistent "space" characters
**Twitter Main** has some extra characters after the author name.  **Twitter Satellite** has some extra characters before the author name.

## Different width for Facebook
The text area for the FB/LinkedIn box is a little narrower

![](https://cl.ly/e7c03926cb2c/Image%202019-10-06%20at%209.52.17%20PM.png)
![](https://cl.ly/325ba5aa87e4/Image%202019-10-06%20at%209.52.22%20PM.png)

**Comment by iam-abbas** [comment]
I would like to take this up

**Comment by jessleenyc** [comment]
awesome, go for it @iam-abbas

**Comment by iam-abbas** [comment]
May I know where I can find this page on the website? @jessleenyc

**Comment by johncurcio** [comment]
@iam-abbas You can only access this page locally with admin privileges ([see here how to configure admin for you](https://docs.dev.to/backend/admin/)). You can find the textareas at http://localhost:3000/internal/articles after you click on ``Share to Buffer`` in any article.

**Comment by iam-abbas** [comment]
Ok I will do that

**Comment by guar47** [comment]
@iam-abbas I hope you don't mind I've created PR for that.
