### ISSUE TITLE
Badges overlap on the badge index page!

### ISSUE THREAD

**Issue by jacobherrington** [thepracticaldev/dev.to#4277]
**Describe the bug**

**To Reproduce**

1. Go to dev.to/badges
2. The pusher badges overlap

**Expected behavior**

Badges shouldn't overlap!

**Screenshots**

![image](https://user-images.githubusercontent.com/11466782/66323954-3e7ecf00-e8ea-11e9-8d37-3041ecc1614a.png)

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Firefox (should be in all browsers)

**Additional context**

This seems to be due to a 250px fixed height on the anchor tag that is enclosing these images.

**Comment by iam-abbas** [comment]
May I work on this?

**Comment by n8chz** [comment]
The <a> elements around the badges are 200x200, the badges inside these are larger.

**Comment by rhymes** [comment]
@iam-abbas sure, go ahead... and thank you!
