### ISSUE TITLE
Prepend non-url paths with https://dev.to instead of just https

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/dev.to#4284]
**Is your feature request related to a problem? Please describe.**

[This PR](https://github.com/thepracticaldev/dev.to/pull/4155) made it so `[github](github.com)` will work, but also that [dev.to](/) will no longer point to the dev.to root, which I think it should. Linking to `[career tag](/t/career)` also should work to prepend `https://dev.to` to the link.

**Describe the solution you'd like**

I'd like to see the regex only switch links that are shaped like URLs, so `/t/career` should not link to `https:///t/career` as it would now.

**Comment by ruan-brandao** [comment]
I'm gonna try to implement this one o/

**Comment by alebruck** [comment]
I'm also working on this one @ruan-brandao, I hope it's fine for you :)
