### ISSUE TITLE
Allow other users to read unpublished articles

### ISSUE THREAD

**Issue by lmller** [thepracticaldev/dev.to#43]
It would be really nice if we could do "beta testing" for articles. 
I'm the kind of person who want's people I trust to read my stuff to find some major flaws or spelling mistakes. 

I see two options (maybe there are more?):
1. Google drive like public link, anybody who got this link can see the article, even if its not published.
2. I can add invite proof readers to my account/article (that have to be part of the `dev.to()` community).

The first option is easier, while the second option allows for more follow-up features (e.g. inline comments)

**Comment by lmller** [comment]
I just noticed that option 1 **already works**, however there is no hint that this is officially supported. (I opened a preview-link without being logged-in, might be a bug as well ;-))

**Comment by jessleenyc** [comment]
Hey @lmller! Thanks for sharing your ideas! --- # 2 is something we're actually working on implementing. In the meantime, someone on the dev.to team can proofread your article if you'd like! All you need to do is give me the OK to leave commented out notes within your article.

**Comment by benhalpern** [comment]
Changed the copy to to make it more clear that the link is shareable. Definitely taking the rest of this into account. Thanks a lot.
