### ISSUE TITLE
Not loading my pen project

### ISSUE THREAD

**Issue by CalvinTaylor40** [thepracticaldev/dev.to#4304]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hi @CalvinTaylor40 can you add more details? It's unclear what the issue is about. Thanks!

**Comment by jessleenyc** [comment]
Hey @CalvinTaylor40 I'm going to close this issue for now since we don't have enough information. Feel free to open a new one with more info!

**Comment by CalvinTaylor40** [comment]
Sorry the issues was sharing from codpen to here mulitpul times i wouldbtry to share what i put together and share it here and a error page came up
