### ISSUE TITLE
Handle Net::HTTPGone 410 errors when pushing messages 

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#4308]
These errors regularly appear in the DJ web interface.
I started working on it in the pr #4232, but with @rhymes' help, I realized that we need a better solution. 
I suppose we should delete the subscription when it happens.
I may be also worth to send each message in its own job to handle the errors easier.

**Comment by benhalpern** [comment]
This is functionality that is not currently used widely. It's able to toggle on but has never been fully implemented.

The logic is in `Messages::SendPush` and I agree with the approach of at least explring deleting the subscriptions when this fails in this way. That seems like a good way to handle this.

This could be a chance to address how this feature works in general (from the client side subscription flow to the backend publication functionality).

**Comment by kirylpl** [comment]
https://github.com/thepracticaldev/dev.to/pull/4883

**Comment by rhymes** [comment]
Thanks for notifying us about this @kirylpl, this issue can be closed!
