### ISSUE TITLE
Add tracking for live events

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#431]
### User Story / Description
Ever since we launched dev live, we haven't had an accurate way to tell how engaged people are with our live workshops. We can see how many people visit, but no sense of how long they stick around unless they're actively chatting. This info would help us determine which types of workshops are more interesting to the community. 

### Definition of Done
A google analytics ping on /live would be a good start.

**Comment by benhalpern** [comment]
We implemented a general-purpose "still-on-site" ping but it really threw off our apples-to-apples data, so removed it.

You can find it in old code from a couple weeks in base.js.erb

That general approach, but only for /live would probably makes sense. Could probably edit the old code and then check for window location, or we could take a totally different approach.
