### ISSUE TITLE
Cannot change/update my profile, or write posts/replies

### ISSUE THREAD

**Issue by jerryhopper** [thepracticaldev/dev.to#4310]
I just cannot change my profile.  Whatever i do, i get a 500Error.

My git/twitter account is connected, and my profile-email adress is correct. ( hopper.jerry@gmail.com )
But my  name & username is stuck on:  spam_2391  ( see: https://dev.to/spam_2391 )
Any submit-action results in a 500 error.

Help?

**Comment by jessleenyc** [comment]
Hi @jerryhopper, this looks like an individual account issue -- can you email yo@dev.to with the email associated with your account (hopper.jerry@gmail.com)?

**Comment by jerryhopper** [comment]
i did,  and nothing happened.   im still looking at the same 500 errors

**Comment by jerryhopper** [comment]
The profile shows this : 

![image](https://user-images.githubusercontent.com/1160857/66475387-83923500-ea93-11e9-9e28-e06c964237ed.png)

**Comment by jerryhopper** [comment]
My settings page looks like this.
![image](https://user-images.githubusercontent.com/1160857/66475491-b1777980-ea93-11e9-9b93-b4d38c94baa5.png)

What i noticed is the inconsistent username/name   two different ones?
