### ISSUE TITLE
Only the first feed loads on the homepage. The rest of the content loads only when I scroll down.

### ISSUE THREAD

**Issue by kvharish** [thepracticaldev/dev.to#4314]
**Describe the bug**
Only the first feed loads on the homepage. The rest of the content loads only when I scroll down.

**To Reproduce**
Go to homepage, select 'Feed' and refresh the page. You should see the first feed loads but not the ones below it.

**Expected behavior**
All the feeds visible on the screen should load.

**Screenshots**

Initial feed
![Screen Shot 2019-10-08 at 10 35 05 PM](https://user-images.githubusercontent.com/21171081/66416772-4343a000-ea1c-11e9-847a-7fa09944174b.png)

On scrolling a bit
![Screen Shot 2019-10-08 at 10 35 24 PM](https://user-images.githubusercontent.com/21171081/66416777-4474cd00-ea1c-11e9-8872-5c9a2de26439.png)

Further scrolling
![Screen Shot 2019-10-08 at 10 35 36 PM](https://user-images.githubusercontent.com/21171081/66416784-476fbd80-ea1c-11e9-9ab7-c022f4ad37d3.png)

**Desktop (please complete the following information):**

- OS: macOS High Sierra Version 10.13.6
- Browser: Google Chrome
- Version: 77.0.3865.90

**Comment by rhymes** [comment]
@kvharish could this have something to do with this other issue? https://github.com/thepracticaldev/dev.to/issues/1805

**Comment by kvharish** [comment]
Yes @rhymes you are correct. I will close this one and I could see a PR has been raised already for the same. I will follow up on that. Thanks.
