### ISSUE TITLE
❤️ Reaction to our own comment

### ISSUE THREAD

**Issue by kvharish** [thepracticaldev/dev.to#4315]
**Describe the bug**
When we comment on any post our post gets self reacted by default. Not sure if this has been done intentionally but thought of registering it here.

**To Reproduce**
1. Go to any post
2. Scroll bottom to the comment section
3. Comment something
4. You should see your comment with the ❤️ reaction as 1 by default

**Expected behavior**
 Comment should be posted and the ❤️ reaction should be 0

**Screenshots**
![Screen Shot 2019-10-08 at 10 58 32 PM](https://user-images.githubusercontent.com/21171081/66418502-df22db00-ea1f-11e9-8a8f-20aec6660638.png)

**Desktop (please complete the following information):**

- OS: macOS High Sierra Version 10.13.6
- Browser: Google Chrome
- Version: 77.0.3865.90

**Additional context**
The same does not happen while creating a new post

![Screen Shot 2019-10-08 at 10 58 04 PM](https://user-images.githubusercontent.com/21171081/66418599-11343d00-ea20-11e9-95b2-efd0edeefd2c.png)

**Comment by nickytonline** [comment]
This is probably related to #4262.

**Comment by alebruck** [comment]
Looks like this behavior was built intentionally for new comments as verified [here](https://github.com/thepracticaldev/dev.to/blob/master/app/assets/javascripts/utilities/buildCommentHTML.js.erb#L97) and [here](https://github.com/thepracticaldev/dev.to/blob/master/app/controllers/comments_controller.rb#L79).

**Comment by kvharish** [comment]
Thought so. Thanks, @alebruck, and @nickytonline. I was wondering why no one reported this issue 😛.  May I know the purpose behind it? I couldn't notice it in the commit message. Just curious. I will close this afterward.

**Comment by kvharish** [comment]
@jessleenyc Just curious. If you can give more insight into this behaviour it would be appreciated.

**Comment by vigzmv** [comment]
@kvharish This behaviour is present on reddit too
https://www.reddit.com/r/NoStupidQuestions/comments/4s3oaj/why_do_you_automatically_upvote_your_own_posts_on/

**Comment by kvharish** [comment]
Thanks for the info @vigzmv. I do not want to keep this issue open still to quench my curiosity.
