### ISSUE TITLE
Add color preview to organization settings

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#4321]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A color preview was added to a user's profile settings -- we should make this feature available for organization settings as well. 

**Additional context**
Here's the color preview PR for reference: https://github.com/thepracticaldev/dev.to/pull/4212
![](https://user-images.githubusercontent.com/30949385/66120518-a8505d80-e5f8-11e9-875d-ebe1b01e597e.png)

Let's add it to dev.to/settings/organization: 
![](https://cl.ly/5d06ee371a2b/download/Image%202019-10-08%20at%203.42.19%20PM.png)

In order to work on this, you'll want to create an org account in development to see these fields.

**Comment by nickytonline** [comment]
If someone needs some inspiration for this, I wrote a post about this and it has a demo doing pretty much what this issue is looking to do, at least on the frontend, https://dev.to/nickytonline/css-mask-property-2d42 .

**Comment by nickytonline** [comment]
I misread the initial comment. Didn't realize it existed already. 🙃

**Comment by n8chz** [comment]
Would that be `admin/organizations/new`? What view generates that?

    $ find app | grep organization
    app/observers/organization_observer.rb
    app/controllers/admin/.organizations_controller.rb.swp
    app/controllers/admin/organizations_controller.rb
    app/controllers/internal/organization_memberships_controller.rb
    app/controllers/organizations_controller.rb
    app/decorators/organization_decorator.rb
    app/assets/images/organization.svg
    app/liquid_tags/organization_tag.rb
    app/views/users/_organization.html.erb
    app/views/api/v0/shared/_organization.json.jbuilder
    app/views/organizations
    app/views/organizations/_main_feed.html.erb
    app/views/organizations/_sidebar.html.erb
    app/views/organizations/show.html.erb
    app/views/organizations/_liquid.html.erb
    app/views/organizations/_sidebar_additional.html.erb
    app/views/internal/users/_user_organizations.html.erb
    app/models/organization.rb
    app/models/organization_membership.rb
    app/policies/organization_policy.rb
    app/jobs/organizations
    app/jobs/organizations/bust_cache_job.rb
    app/dashboards/organization_dashboard.rb

**Comment by artoodeeto** [comment]
@jessleenyc can I take this please? this looks interesting. ei yow dude @n8chz you takin this? can I help?

**Comment by artoodeeto** [comment]
Hello, I'm taking this. currently working on this one. thanks. 😄

**Comment by n8chz** [comment]
Please do. I can't even figure out where in the code it happens.

**Comment by artoodeeto** [comment]
@n8chz all good my dude. this is fixed. if you want to check heres the pr #4347. just copy-pasted the code. lols

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/4347
