### ISSUE TITLE
Sign in with Twitter on Edge Dev redirects to a 404 page

### ISSUE THREAD

**Issue by saneld27** [thepracticaldev/dev.to#4325]
Hi, there is an issue on Microsoft Edge Dev while trying to sign in with Twitter to dev.to, it redirects me to the 404 page showing an error message indicating that I am "offline". I have managed to sign in with Twitter using Opera and Chrome. I have also tried to login in incognito on Edge Dev, without extensions, but the same bug appeared. 

To Reproduce

1. Open dev.to on Microsoft Edge Dev
2. Click on Sign in with Twitter
3. It will redirect you to a 404 page showing an error message indicating that you are "offline"

Expected behavior:

- If you have already been signed in with Twitter it should sign you in and redirect to home page
- If you haven't been signed in it should open the authorization page and/or Twitter login

Screenshot
- URL it tried to get while showing 404 page
http://prntscr.com/pgrqeh

Desktop:
- OS: Windows 10
- Browser: Microsoft Edge Dev
- Version: 79.0.287.3

**Comment by saneld27** [comment]
The issue might be related to Edge Dev and not to dev.to. I've spent some time testing various versions and builds of the browser and it appears that in some of them it works while on others it doesn't so my conclusion is that it is not dev.to issue.

**Comment by rhymes** [comment]
@saneld27 can you please check if there's anything written in the console that might be related to us?

thanks!
