### ISSUE TITLE
Cannot change/update my profile, or write posts/replies

### ISSUE THREAD

**Issue by jerryhopper** [thepracticaldev/dev.to#4327]
This is a duplicate of #4310,  as it got closed and im still in the same situation.

https://github.com/thepracticaldev/dev.to/issues/4310

**Comment by jerryhopper** [comment]
![image](https://user-images.githubusercontent.com/1160857/66475752-3febfb00-ea94-11e9-94f5-ff3faac1682b.png)


![image](https://user-images.githubusercontent.com/1160857/66475781-509c7100-ea94-11e9-8e37-79ba8d3b603b.png)

**Comment by jessleenyc** [comment]
Pinging @michael-tharrington as a heads up here -- looks like @jerryhopper is having issues with their account, please follow up with them via yo@dev.to!
