### ISSUE TITLE
Moderation dashboard - Jump to next post

### ISSUE THREAD

**Issue by GeorgeColdham** [thepracticaldev/dev.to#4330]
# Moderation dashboard - Jump to next post
When moderating I would like a way to jump between posts without having to scroll.

(When using `dev.to/mod`)

## Suggested solution

I would like `next` and `previous` buttons to jump to the next post to be moderated and back to the last.

It could use anchor tags in the title of each post to scroll that post to the top of the display. There is a collection called `document.anchors` which provides all anchor tags on the page which could be iterated over and set the href of a button or link to jump to that location.
At a glance, we would need to add anchors to headers.

**Comment by jessleenyc** [comment]
Cool, this is approved for anyone who wants to work on it! I think it would be nice to give people the option to choose which view they would prefer.

**Comment by rhymes** [comment]
I'm closing this as dev.to/mod has totally changed since October and I feel like this request doesn't apply as the div is closable
