### ISSUE TITLE
"Contact via Connect" in listings form cannot be unchecked

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/dev.to#4336]
The button in the main listings form does not change when the checkbox is clicked...

![](https://cl.ly/7c5f53213221/Image%202019-10-09%20at%2011.53.08%20AM.png)

Expected behavior:

The checkbox changes and the appropriate preact state is altered.

**Comment by mahamshahid18** [comment]
Hey @benhalpern. I'd love to take a look at this. Can you add more context? Where can this checkbox be found, and what is the required state for when the checkbox value changes?

**Comment by rhymes** [comment]
Hi @mahamshahid18 I think @KattyaCuevas submit a PR to fix this issue: https://github.com/thepracticaldev/dev.to/pull/4343

**Comment by rhymes** [comment]
@mahamshahid18 most issues are by area, not by language, that's true. 

Aside from writing "javascript" in the issue search box, you can take a look at these two results organized by labels: https://github.com/thepracticaldev/dev.to/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Ajavascript+ - https://github.com/thepracticaldev/dev.to/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22tech%3A+javascript%22+

Thanks for volunteering!

**Comment by mahamshahid18** [comment]
Thanks for the links, will take a look 👍
