### ISSUE TITLE
Anchored links get prefixed with "//"

### ISSUE THREAD

**Issue by michelc** [thepracticaldev/dev.to#4338]
**Describe the bug**

When creating a Table of Content with anchored links, links are generated with "//" before the anchor name.

```
* [Chapter 1](#chapter-1)
```

Will generate:

```
<li><a href="//#chapter-1">Chapter 1</a></li>
```

**To Reproduce**

1. Go to '[here](https://dev.to/michelc/crud-application-with-express-and-sqlite-in-10-steps-me0)'
2. Click on '3. Create the Express application.' in the Table of Contents
3. Browser navigate to 'about:blank#blocked'

**Expected behavior**

Generate the link without "//".

**Additional context**

Problem seems occur since this commit: https://github.com/thepracticaldev/dev.to/commit/328d27ff41ee30c869c3131dc702b03693f6fdd8

**Comment by michelc** [comment]
**Update to  app/lib/redcarpet/render/html_rouge.rb**

```
    if (/\A(https?:\/\/)/.match? link) || link.nil?
      %(<a href="#{link}"#{link_attributes}>#{content}</a>)
++  elsif link.start_with?("#")
++    %(<a href="#{link}"#{link_attributes}>#{content}</a>)
    else
      %(<a href="//#{link}"#{link_attributes}>#{content}</a>)
    end
```

**Update to spec/labor/markdown_parser_spec.rb**

```
    context "when rendering links markdown" do
      ...
++    it "renders properly anchored links" do
++      code_span = "[Chapter 1](#chapter-1)"
++      test = generate_and_parse_markdown(code_span)
++      expect(test).to eq("<p><a href=\"#chapter-1\">Chapter 1</a></p>\n\n")
++    end
    end
```

**Comment by rhymes** [comment]
Closed by https://github.com/thepracticaldev/dev.to/pull/4340
