### ISSUE TITLE
Gist liquid tag including jupyter notebooks shows spinner forever

### ISSUE THREAD

**Issue by parente** [thepracticaldev/dev.to#434]
### Current Behavior

1. Add `{% gist https://gist.github.com/parente/8932dac5a430dba4c17f49af16568da7 %}` to a post
2. Preview or save the post.
3. See the github spinners for the ipynb files in the gist forever

Example draft post showing the problem (scroll down past the README.md which is fine): https://dev.to/parente/test-4h0-temp-slug-4214860?preview=3d6bceae28f78e084355693b8f17c0a0120ea23bc460fb22495f9a0d49514b507da2e5b3fc3c278e779e4207410526e1cc5379eddb77059069fa305c

Comparison with the rendering on github itself: https://gist.github.com/parente/8932dac5a430dba4c17f49af16568da7

### Expected Behavior

The spinners go away when the notebook finishes rendering.

### Additional Info (device/browser, helpful links)

The problem with the ever present spinners does not occur with GitHub's own "embed gist" script tag: https://codepen.io/anon/pen/LJEmVR

**Comment by benhalpern** [comment]
Hmm looks like the spinner is outside the iframe. Not sure what the cause of this is, but I guess it might be affected by some kind of image style override.

We could probably hide it with a CSS adjustment, possibly needing an `!important`
