### ISSUE TITLE
Access to unique user id from liquid tag

### ISSUE THREAD

**Issue by AndrewSverdrup** [thepracticaldev/dev.to#4342]
I'm working on a PR to add a liquid tag for code sandboxes on https://next.tech.  To provide a better experience for the user, we'd like to be able to load the same sandbox each time a user views a particular liquid tag embed (so the user's changes are persisted in the sandbox).  Is it possible to access a unique user id from a liquid tag (in the `app/liquid_tags` folder)?

**Comment by jessleenyc** [comment]
@AndrewSverdrup can you expand further on what you're hoping to accomplish with this? Not sure we totally understand how this will be used.

In terms of implementation, can we do this through local storage?

**Comment by AndrewSverdrup** [comment]
Hey sorry for the delayed response. We've discussed this on our end and have decided to implement the embeds in a way that won't require access to a user id. We're all set for now.
