### ISSUE TITLE
Getting "undefined method `id' for nil:NilClass" on rspec spec/system

### ISSUE THREAD

**Issue by coolbrg** [thepracticaldev/dev.to#4349]
**Describe the bug**
`bundle exec rspec spec/system` failed with error `undefined method `id' for nil:NilClass`.

**To Reproduce**

1. Run `bundle exec rspec spec/system`.

**Expected behavior**

The command to test system specs should pass.

**Desktop (please complete the following information):**

- OS: macOS

**Additional context**

I am getting the error repeatedly(4 times).

#### Failed examples:
```
rspec ./spec/system/user_views_a_reading_list_spec.rb:14 # Reading list without tags when large readinglist shows the large reading list
```

#### Brief Error:
```
  1) Reading list without tags when large readinglist shows the large reading list
     Failure/Error: params = { filters: "viewable_by:#{current_user.id}" }

     NoMethodError:
       undefined method `id' for nil:NilClass



     # ./app/controllers/reading_list_items_controller.rb:20:in `generate_algolia_search_key'
     # ./app/controllers/reading_list_items_controller.rb:5:in `index'
```

**Comment by coolbrg** [comment]
Updated @rhymes . I should have done before. Thanks

**Comment by Amorpheuz** [comment]
I do get the same error too when running the tests locally, on a random basis, but they seem to always pass when I run them on Travis.

**Comment by rhymes** [comment]
@coolbrg @Amorpheuz I was going to ask you for the seed number to replicate the randomization but then I remembered our tests are not randomized yet. 

@Amorpheuz does it happen to you also when you run the entire `system` folder or just the single file?

**Comment by lightalloy** [comment]
I have reproduced this just by running `bundle exec rspec spec/system` as specified in the description.
This failure disappears if I move the `sign_in user` into the inner context like this:
```ruby

RSpec.describe "Reading list", type: :system do
  let!(:user) { create(:user) }

  context "without tags" do
    context "when large readinglist" do
      before do
        sign_in user
        create_list(:reading_reaction, 46, user: user)
      end

      it "shows the large reading list" do
        visit "/readinglist"
        expect(page).to have_selector("#reading-list", visible: true)
      end
    end
  end
end

```

**Comment by maestromac** [comment]
This is rather weird, I can't seem to reproduce this at all.

**Comment by Zhao-Andy** [comment]
I have had a similar issue before, and I think I used the same solution as @lightalloy to solve it locally. I didn't think much of it at the time though. Thanks for reporting the issue @coolbrg.

**Comment by Amorpheuz** [comment]
@rhymes Yup, it occurs when I run the entire `system` folder. I haven't tried running that spec individually as of yet. Will try that out along with the solution suggested by @lightalloy and report back tomorrow!

**Comment by Amorpheuz** [comment]
> @rhymes Yup, it occurs when I run the entire `system` folder. I haven't tried running that spec individually as of yet. Will try that out along with the solution suggested by @lightalloy and report back tomorrow!

I tried it out by individually running `bundle exec rspec spec/system/user_views_a_reading_list_spec.rb` but didn't see the error pop up during any of the multiple runs. The error still occurred when I tried out lightalloy's solution though, again on a random basis.

**Comment by lightalloy** [comment]
I have checked several times, but probably it was a coincidence then. We need to investigate further.

**Comment by mstruve** [comment]
Given we now implement this differently with Elasticsearch I am going to assume the issue has been resolved.
