### ISSUE TITLE
Likes number in feed doesnt match the number inside the post

### ISSUE THREAD

**Issue by pavelloz** [thepracticaldev/dev.to#4367]
I saw an interesting article and there was 5 <3 next to it. I opened it, it had only one.

Article: https://dev.to/stephencweiss/web-safe-fonts-and-font-fallbacks-4noi

**Expected**

They should match more or less :)

**Screenshots**

Feed view
<img width="625" alt="image" src="https://user-images.githubusercontent.com/546845/66647633-b4a46e00-ec29-11e9-8420-aac66d73363a.png">

---

Post view
<img width="785" alt="image" src="https://user-images.githubusercontent.com/546845/66647643-bcfca900-ec29-11e9-92aa-3a47e65afef7.png">

**Comment by Glennmen** [comment]
❤️, 🦄 and 🔖 are added together.

**Comment by pavelloz** [comment]
Ouh.
