### ISSUE TITLE
Add link to /community-moderation on all /mod pages

### ISSUE THREAD

**Issue by michael-tharrington** [thepracticaldev/dev.to#4369]
It's difficult to find links to the community moderation guide ([dev.to/community-moderation](https://dev.to/community-moderation)), so it'd be valuable to add this link to various relevant pages.

We should add this link - https://dev.to/community-moderation to any `/mod` page: 
1. [https://dev.to/mod](https://dev.to/mod)
2. https://dev.to/dev-username/article-title/mod

**Additional context**

1. Suggestion on where to put link on `/mod`:

![image](https://user-images.githubusercontent.com/16007075/66656883-d4796900-ec0c-11e9-8ed8-dc099de47f17.png)

2. Suggestion on where to put link on `/dev-username/article-title/mod`:

![image](https://user-images.githubusercontent.com/16007075/66656637-62a11f80-ec0c-11e9-9b54-e1de492f0a59.png)

**Comment by VoxSecundus** [comment]
Hi, I'm taking a look at this!

**Comment by juliegoat** [comment]
I would love to take on this one! Working on it now :)
