### ISSUE TITLE
Allow orgs to have an org RSS that is accessible to all org members

### ISSUE THREAD

**Issue by michael-tharrington** [thepracticaldev/dev.to#4373]
Currently, if a user wants to load in all of their articles from another blog to repost on DEV, they can go here in their settings - https://dev.to/settings/publishing-from-rss and input the RSS feed of the blog, which will then load posts into their [dashboard](https://dev.to/dashboard) as drafts.

A current limitation here is that 2 users can't load in the same RSS feed. This limit assumes that only one writer should have ownership over a single feed and is a safeguard against folks trying to load in others' posts. But, it doesn't take into account that we may have organizations with multiple authors writing on the same feed who want to repost via RSS.

It would be helpful to provide organization admins the ability to load in an RSS feed particular to their org. These posts would then fall into a collective org dashboard that all org members could access, assign themselves as writers, and then have ability to edit/post individual articles.

**Describe alternatives you've considered**

1. I thought about the possibility of having the org posts fall into each user's individual dashboard rather than a collective org dashboard. But, I liked the idea of a collective dashboard where folks would take ownership over posting the posts that are theirs, because otherwise we'd end up duplicating an org's entire backlog of posts several times in each individual's dashboard — posts that don't belong to that individual would sit as drafts or need to be deleted.

2. Instead of authors assigning themselves as writers, it could just be org admins who are only allowed to do this.

**Additional context**

I like the idea of an org dashboard because then org users can leave https://dev.to/settings/publishing-from-rss for their personal blog. It creates a nice separation between their org and their personal blog.

**Comment by michael-tharrington** [comment]
This is a related request - https://github.com/thepracticaldev/dev.to/issues/100 ... just figured I should drop it here in case.

**Comment by jessleenyc** [comment]
I think this might be a duplicate or enhancement of https://github.com/thepracticaldev/dev.to/issues/4373? I'm going to close this and reference your issue in the other one.
