### ISSUE TITLE
JavaScript Console Errors on Comments subpage of a Post

### ISSUE THREAD

**Issue by Amorpheuz** [thepracticaldev/dev.to#4377]
**Describe the bug**
https://github.com/thepracticaldev/dev.to/blob/fbbda3ed822a3e7c7d718ad979998ab23ae2a607/app/assets/javascripts/initializers/initializeCommentDropdown.js#L86-L111

This function is responsible for initializing a part of the dropdown generation process. The `isIOSDevice` and similar functions meant to only work on Article Pages where the `click-to-copy` #1579 functionality is present are causing the issue since the element they refer to is not present on this page.

**To Reproduce**
1. Open an article with comments, say [What was your win this week?](https://dev.to/jess/what-was-your-win-this-week-dch)
2. Go to comments sub-page by appending `/comments` to the end of the URL of the article
3. Open respective debugging/dev tools window in the browser (F12 in Chrome).
4. Click on the dropdown button (3 dots in the top right of a comment).
5. Check the JavaScript Console.

**Expected behavior**

No errors should be printed in Console.

**Screenshots**
![Image](https://im.ezgif.com/tmp/ezgif-1-4efff48cc7eb.gif)
![image](https://user-images.githubusercontent.com/22113778/66670194-ce1fd700-ec76-11e9-9e0a-30c9ee67f1db.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 77.0.3865.90

**Comment by Amorpheuz** [comment]
I would like to take up this issue if possible 😄

**Comment by rhymes** [comment]
@Amorpheuz sure, go ahead and thanks!

**Comment by Amorpheuz** [comment]
Fixed by #4446
