### ISSUE TITLE
If the post title is too long then it goes outside the box

### ISSUE THREAD

**Issue by joshi-chinmay** [thepracticaldev/dev.to#4383]
**Describe the bug**
If the words in the title of the blog title are too long then it goes outside the box.

**To Reproduce**
Have a word in the title with many letters in it.

**Expected behavior**

**Screenshots**
<img width="1680" alt="Screenshot 2019-10-11 at 5 20 20 PM" src="https://user-images.githubusercontent.com/16207311/66685980-f514e380-ec4b-11e9-959c-8f5cc013e1e0.png">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Google Chrome
- Version: -

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by fllprbt** [comment]
You are talking about what is happening at the post with name "_Dockerized..._"

I am up for this issue so if you could assign <3.

Expected behaviour? What about single super long words? Trim maybe?

**Comment by carlan** [comment]
I can have a look at this one if still not fixed.

Though to apply the same solution of #4392.

**Comment by rhymes** [comment]
@carlan sorry I didn't understand one thing, isn't this covered by https://github.com/thepracticaldev/dev.to/pull/4392 ?
