### ISSUE TITLE
500 Error On Creating Article

### ISSUE THREAD

**Issue by PeterDavidCarter** [thepracticaldev/dev.to#4384]
**Describe the bug**

**To Reproduce**

**Expected behavior**

Not:

![image](https://user-images.githubusercontent.com/23146481/66690135-0844a500-ec86-11e9-8066-88b241dda0f4.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/23146481/66690138-0b3f9580-ec86-11e9-8067-151a7aa3d299.png)

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by jerryhopper** [comment]
i have the same problems  ( #4327 )... i wonder - can you edit your profile?
it seems any HTTP_POST is producing 500 errors for me.

**Comment by jessleenyc** [comment]
@PeterDavidCarter thanks for the report -- this looks like an individual account issue. Can you please email yo@dev.to from the email address associated with your DEV account? Thanks!
