### ISSUE TITLE
Leave Organization isn't working

### ISSUE THREAD

**Issue by iAnkurBiswas** [thepracticaldev/dev.to#4387]
**Bug**

Leave Organization doen't work properly.

In Settings, on [Organization tab](https://dev.to/settings/organization) to leave the organization when I'm trying to click the _Leave Organization_ button it's showing me a alert box for confirmation. When I click _Ok_ to confirm that, it's redirect me to this [page](https://dev.to/users/leave_org) showing error.

**To Reproduce**

1. Go to [Settings](https://dev.to/settings/).
2. Select [Organization](https://dev.to/settings/organization).
3. Scroll down to _Danger zone_.
4. Click _Leave Organization_ button.
5. Confirm the popup.
6. See Error.

**Screenshots**

![Organization Page](https://i.imgur.com/pOZQolZ.png)

![Error](https://i.imgur.com/L6gAHjK.png)

**Desktop (please complete the following information):**

- OS: macOS High Sierra (version 10.13.6)
- Browser: Safari
- Version: 12.1.2 (13607.3.10)

**Comment by whyakshay** [comment]
I would like to take this one please!

**Comment by Zhao-Andy** [comment]
@whyakshay go for it! Let us know if you have questions.
