### ISSUE TITLE
Improve usability of image upload

### ISSUE THREAD

**Issue by bharatdwarkani** [thepracticaldev/dev.to#4395]
Today while posting in Dev.to I felt a usability issue in including the image in my article. One thing is dev.to follows Markdown editor, In your editor, I just cannot take a snapshot and past images directly. This is supported by an editor like Medium or any RTE. Due to this, I have to save some 14 images related to the article in system and then manually upload each which is time-consuming. Since I have already written same post in the medium was posting in dev.to.

Solution: 
Ability to paste the image directly in editor / Html Support / Improve ease of access to image upload option.

**Comment by bharatdwarkani** [comment]
@rhymes  - Can implement a drag and drop. As like GitHub editor. Pasting an image or dragging and dropping a file uploads image automatically and adds the reference where the cursor is at present.

![image](https://user-images.githubusercontent.com/12810605/67066159-db652600-f18e-11e9-85d9-829b8bf28823.png)

**Comment by rhymes** [comment]
@bharatdwarkani that would be cool, though I think we should have a discussion involving other people in https://github.com/thepracticaldev/dev.to/issues/4126 about the UI and usability of this feature, before you go diving into the code. 

I'll close this one in the meantime. Could you duplicate your comment over there? Thanks!
