### ISSUE TITLE
Option to import a story from medium

### ISSUE THREAD

**Issue by bharatdwarkani** [thepracticaldev/dev.to#4396]
Provide an option for importing a story from medium through URL. Due to markdown editor, it is time-consuming to post a story written in medium to dev.to

**Comment by rhymes** [comment]
@bharatdwarkani have you tried to use RSS to import the articles? See https://dev.to/settings/publishing-from-rss

**Comment by maestromac** [comment]
As @rhymes mention,ed the current method for achieving that is to add your medium RSS feed to DEV. Let us know if you run into any issues! 

Closing
