### ISSUE TITLE
bug 500 errors report

### ISSUE THREAD

**Issue by synarion258** [thepracticaldev/dev.to#4397]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
@synarion258 can you provide some details about this error?

**Comment by jessleenyc** [comment]
@synarion258 I'm actually going to close this issue for now but feel free to open a new issue if you have more info. Thanks!
