### ISSUE TITLE
Number allowed in tags via v1 editor

### ISSUE THREAD

**Issue by bolariin** [thepracticaldev/dev.to#4401]
**Describe the bug**

While working to resolve #4116, @rhymes informed me that numbers are not allowed in tags. It looks like this was not enforced with the v1 editor. After making my change in #4239, I enforced no non-alphabet characters directly in the model, `tags.rb` but it looks like some tests allowed numbers in tags and my change causes a lot of tests to fail.  

I noticed that a pull request was made to allow numbers in the v2 editor so I’m not sure if the next step would be editing the test cases.

**To Reproduce**

1. Go to settings and switch editor to v1
2. Try and create an article with a tag that contains a number 
3. There are no error messages 

**Expected behavior**

An error message regarding the number in the tag.

**Comment by rhymes** [comment]
Hi @bolariin, would https://github.com/thepracticaldev/dev.to/pull/4283 cover this use case?

**Comment by bolariin** [comment]
@rhymes Yes, if numbers should be allowed in tags then we have consistency between both editors. If numbers are not allowed in tags then no. It looks like #4283 is permitting numeric characters in tags for the v2 editor.

**Comment by jessleenyc** [comment]
Spoke to the team about this and we've decided that we can allow numbers in tags but no special characters. With that said, should we close this issue?

**Comment by bolariin** [comment]
Yes, thanks @jessleenyc
