### ISSUE TITLE
500 bug report

### ISSUE THREAD

**Issue by synarion258** [thepracticaldev/dev.to#4407]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by synarion258** [comment]
> **Describe the bug**
> 
> **To Reproduce**
> 
> **Expected behavior**
> 
> **Screenshots**
> 
> **Desktop (please complete the following information):**
> 
> * OS:
> * Browser:
> * Version:
> 
> **Smartphone (please complete the following information):**
> 
> * Device:
> * OS:
> * Browser:
> * Version:
> 
> **Additional context**

**Comment by jessleenyc** [comment]
Sorry you hit the 500 page! I'm going to close this issue since the form is not filled out but feel free to open a new issue with more information if it happens again.
