### ISSUE TITLE
Lazy Loading works not as expected.

### ISSUE THREAD

**Issue by DonkeyKongJr** [thepracticaldev/dev.to#4408]
**Describe the bug**

The lazy loading feature on the front page is not working as expected. It should already reload new articles when the `loading...` message is visible. However, right now you have to move all skeletons out of the viewport to start reloading articles. I find this behavior a bit frustrating, especially when all major platforms start their reloading immediately. 

**To Reproduce**

1. Go to 'dev.to' frontpage.
2. Start scrolling down on the frontpage.
3. The reload kicks in too late.

**Expected behavior**

I would expect that the reloading starts immediately after the `loading...` message is visible.

**Screenshots**
![](https://media.giphy.com/media/hU3QO66MkbvsuvPYf3/giphy.gif)

**Desktop:**

- OS: Windows 10
- Browser: Chrome 
- Version: 77

**Comment by Glennmen** [comment]
I think this is the same issue as described in issue #1805

**Comment by DonkeyKongJr** [comment]
@Glennmen it is! I will close this for now.
