### ISSUE TITLE
Add Optimistic Rendering to /mod buttons

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/dev.to#443]
## Feature Request or Task
Undoing a thumbsdown or vomit reaction can sometimes take a while and/or show a slow response. We should add some optimistic rendering in.

### Definition of Done
We have a more responsive reaction button. We should also try to refactor the code there if necessary.

**Comment by maxcell** [comment]
I don't mind taking this on!

**Comment by Zhao-Andy** [comment]
Hey @maxcell, sorry just seeing this now! Go for it if you're still up for it. :)

To reproduce this is development, you'll have to give yourself the `trusted` role, and then visit `/mod` on any comment or article, like so: 
```ruby
me = User.last
me.add_role :trusted
# then visit a comment or article
```
