### ISSUE TITLE
I cannot write new post

### ISSUE THREAD

**Issue by martin-nextcart** [thepracticaldev/dev.to#4441]
**Describe the bug**

I get this error message when trying to create a new post: **500 Error. It's not you, it's me.**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 77.0.3865.90 (Official Build) (64-bit)

**Comment by jessleenyc** [comment]
Hi @martin-nextcart! Sorry you're experiencing this. Seems like it's an issue with your individual account -- can you send an email to yo@dev.to with the address associated with your DEV account?
