### ISSUE TITLE
Ember badge in badges list shows description of GraphQL badge

### ISSUE THREAD

**Issue by arximughal** [thepracticaldev/dev.to#4449]
**Describe the bug**
[Ember badge](https://dev.to/badge/ember) in the [list of dev.to badges](https://dev.to/badges) shows the description of [GraphQL badge](https://dev.to/badge/graphql). 

**To Reproduce**
1. Go to the badges [list page](https://dev.to/badges)
2. Click on [Ember Badge](https://dev.to/badge/ember) and read description
3. Now, Go back to the [badges list page](https://dev.to/badges) and check [GraphQL Badge](https://dev.to/badge/graphql)'s description
They are amazing. 

**Expected behavior**
Should show an appropriate description for each badge.

**Screenshots**
![ember-badge](https://user-images.githubusercontent.com/8762441/66841253-d895e580-ef82-11e9-98ef-7f335e21b0eb.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 19.04
- Browser: Google Chrome 
- Version: 77.0.3865.90 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by thackley** [comment]
can i try this?

**Comment by Glennmen** [comment]
@thackley I am not 100% sure but isn't this information retrieved from the database directly and not hardcoded?

**Comment by Zhao-Andy** [comment]
Hi @thackley, sorry but as @Glennmen mentioned this was an issue with the wrong description in the database. We've fixed it now.

Any issue tagged with `help-wanted` is up for grabs; let us know if you have questions!
