### ISSUE TITLE
Events page: error on display in development mode

### ISSUE THREAD

**Issue by netochaves** [thepracticaldev/dev.to#4455]
**Describe the bug**

**This error occurs only in Development.**
When getting the cover images of events the page will crash with a error, check bellow.
![image](https://user-images.githubusercontent.com/19830660/66866127-0f620080-ef6f-11e9-9d98-34a7392dd68f.png)

**To Reproduce**
- Go to `/internal/events`
- Upload a cover image
- Mark the publish checkbox and create the event
- Go to `/events` and you'll see the error.

**Expected behavior**
Should load the events page

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Opera developer
- Version: 64.0.3409.0

**Additional context**
I will open a PR to fix this.

**Comment by netochaves** [comment]
I've made some research and I think the problem is because is being pass a cover_image object and not a url string.
https://github.com/thepracticaldev/dev.to/blob/7de692156cd6254bc74c3e145415f7f47207fa47/app/views/events/_event.html.erb#L59 
This only fail on development because here some strings methods are being execute over the url wich is an object, so it will return undefined for these methods.
https://github.com/thepracticaldev/dev.to/blob/c9c86a44ea42dc656019ba3cc1a931dbbbc6f739/app/helpers/application_helper.rb#L93-L94

**Comment by rhymes** [comment]
hi @netochaves, the error is not so much on upload, but on display. I'm going to change the title of the issue to make it clearer.

I also left you a note in the time fixer PR about how to fix this one as well https://github.com/thepracticaldev/dev.to/pull/4416#pullrequestreview-302388676
