### ISSUE TITLE
Articles API index: per_page parameter not working

### ISSUE THREAD

**Issue by miku86** [thepracticaldev/dev.to#4463]
**Describe the bug**

I copied @rhymes text, because it's the same issue like [this issue](https://github.com/thepracticaldev/dev.to/issues/4125#issue-499526267) about the listings API:

The articles API - [dev.to/api/articles](https://dev.to/api/articles) - is not respecting the parameter `per_page`.

**To Reproduce**

* [dev.to/api/articles?per_page=1](https://dev.to/api/articles?per_page=1) should return only 1 listing, instead it returns the same result of [dev.to/api/articles](https://dev.to/api/articles)

**Expected behavior**

I expect the parameter `per_page` returns the desired number of articles.

**Comment by rhymes** [comment]
@nadiyaka sure, go ahead! and thank you!

**Comment by miku86** [comment]
Awesome, @nadiyaka,

thanks a lot!
