### ISSUE TITLE
The Offline Page loses state on  window resize/zoom in-out

### ISSUE THREAD

**Issue by vidhibagadia** [thepracticaldev/dev.to#4471]
**Describe the bug**

The offline page loses the drawn information and selected colour when the window is resized or a zooming operation is performed.

**To Reproduce**

1. Go to the offline page: [DEV Offline Page](https://dev.to/offline.html)
2. Draw on the page
3. Zoom in/ resize window
4. The canvas and the preferences reset

**Expected behavior**

On window resizing/zooming operation, the canvas state should persist (in high quality) and the drawing colour selected should also persist over resizing and not default to the first colour.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Google Chrome
- Version: 77.0.3865.120 (Official Build) (64-bit)
- Browser: Firefox
- Version: 69.0.3 (64-bit)

**Smartphone (please complete the following information):**

- Device: Lenovo K8 Plus
- OS: Android 8.0.0
- Browser: Google Chrome
- Version: 73.0.3683.90
- Browser: Firefox
- Version: 66.0.2

**Additional context**

I've worked on the code to fix this issue if required. This is my first attempt at opening an issue, and a corresponding technical PR, so let me know if I'm missing something. I'll be glad to make the modifications.

**Comment by rhymes** [comment]
@vidhibagadia thanks for the find, if you already know how to fix it, please go ahead! Thank you very much!
