### ISSUE TITLE
API docs: add OpenAPI documentation to undocumented routes

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#4474]
**Is your feature request related to a problem? Please describe.**

The [API docs](https://docs.dev.to/api/) are incomplete. Right now they only document endpoints under `/articles` and `/webhooks`

**Describe the solution you'd like**

Many different endpoints, resources and responses are missing, the goal is to arrive to a documentation as complete as possible.

The documentation file is https://github.com/thepracticaldev/dev.to/blob/master/docs/api_v0.yml

There are a couple of requirements if we want to complete this documentation effort: knowledge of OpenAPI and coordination. 

To get acquainted with OpenAPI I suggest two resources: [the official OpenAPI 3 spec](http://spec.openapis.org/oas/v3.0.2) and the [OpenAPI guide by Swagger.io](https://swagger.io/docs/specification/about/). The first one contains all the info, the second one is helpful when in doubt about how to do things.

Also read the [Contributing to the API spec docs](https://docs.dev.to/contributing_api/) page, in there you can find information about Visual Studio Code extensions that can help and how to serve the API docs locally for testing (remember to refresh the browser page at each change :)).

To coordinate I'm going to leave here the list of missing endpoints and then I'll explain where to find their code and their tests:

### Endpoints to document

- [x] `GET      /api/comments                       api/v0/comments#index`
- [x] `GET      /api/comments/:id                   api/v0/comments#show`
- [x] `GET      /api/followers/users                api/v0/followers#users`
- [x] `GET      /api/listings                       api/v0/classified_listings#index`
- [x] `POST     /api/listings                       api/v0/classified_listings#create`
- [x] `GET      /api/listings/:id                   api/v0/classified_listings#show`
- [x] `PUT      /api/listings/:id                   api/v0/classified_listings#update`
- [x] `GET      /api/listings/category/:category    api/v0/classified_listings#index`
- [x] `GET      /api/podcast_episodes               api/v0/podcast_episodes#index`
- [x] `GET      /api/tags                           api/v0/tags#index`
- [x] `GET      /api/users/:id                      api/v0/users#show`
- [x] `GET      /api/users/me                       api/v0/users#me`
- [x] `GET      /api/videos                         api/v0/videos#index`

For example, you can find the code for `GET /api/comments` inside the file https://github.com/thepracticaldev/dev.to/blob/master/app/controllers/api/v0/comments_controller.rb in the action `index`. Its test would be in https://github.com/thepracticaldev/dev.to/blob/master/spec/requests/api/v0/comments_spec.rb 

I also suggest to scan the API doc file to understand how is it structured and play around with `curl` or other tools like [Postwoman](https://postwoman.io/), so you can see how the responses are, for example: `curl https://dev.to/api/comments/gi9b` ([jq](https://stedolan.github.io/jq/) is a great companion if you use the command line)

Don't forget to bump the [version](https://github.com/thepracticaldev/dev.to/blob/master/docs/api_v0.yml#L5) in your PR.

Please declare which endpoint(s) you're going to document, we have to be extra careful to avoid having conflicts in the documentation effort.

**Additional context**

A couple of tips: you'll probably find bugs or inconsistencies while documenting, please open separate issues for those, keeping in mind that the policy we have is:

- inconsistencies that don't break the API can be fixed, please open issues and separate PRs for those, PRs tied to this ticket are only about documentation
- any inconsistencies that you think should be known by the API docs reader can be documented
- possible caching bugs, or other bugs, are hiding around the API, please open separate issues for those as well. There are already some documented cases of API bugs here: https://github.com/thepracticaldev/dev.to/issues?q=is%3Aissue+is%3Aopen+label%3A%22area%3A+api-v0%22

Don't forget to read the [contributing guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md) and please use the following schema for your PRs: `USERNAME/DESCRIPTION-4474` (4474 is the ID of this very issue, it makes the reviewer's job easier to know which branch belongs to whom and to which issues refers to)

We could also integrate a validator like [speccy](https://github.com/wework/speccy) to make sure that the API doc file gets validated at each commit.

**Comment by matisnape** [comment]
👀 will take this on next week, I think . I'll add a note which ones I'm taking.

**Comment by rhymes** [comment]
Another task: we should make clear, in the API docs, that an article created with the front matter can't have its properties, like `title`, updated with just the `title` attribute for example, because the title inside the front matter will take precedence on the `title` in the JSON attributes. See https://github.com/thepracticaldev/dev.to/issues/4000#issuecomment-530158610

**Comment by rhymes** [comment]
We've documented all publicly available APIs, added a validator and fixed some bugs in the process.

I'm closing this!
