### ISSUE TITLE
Welcome page: CSS bug on mobile

### ISSUE THREAD

**Issue by BrooklynP** [thepracticaldev/dev.to#4485]
The welcome page when you create an account seems to have buggy CSS when viewed on mobile as the continue button covers up some of the wording. This was viewed on a pixel 3.

![Screenshot_20191016-225433](https://user-images.githubusercontent.com/20336127/67044821-0450d100-f125-11e9-9ca1-565ad3d0686b.png)

In reply to: 
https://github.com/thepracticaldev/dev.to/issues/4485#issuecomment-543579603

This is on Android version 10. Google Chrome version 77.0.3865.116

**Comment by rhymes** [comment]
@BrooklynP can you provide more info about the software? which browser and which version of the browser? Thank you!

**Comment by samrae7** [comment]
@rhymes I just replicated this with chrome desktop Version 77.0.3865.90 (Official Build) (64-bit), switch to mobile view via devtools, with GalaxyS5 selected as the simulated device

<img width="509" alt="Screenshot 2019-10-19 at 11 40 25" src="https://user-images.githubusercontent.com/4126146/67143662-9e1f9780-f265-11e9-834d-379513081319.png">

I would like to fix this

**Comment by Amorpheuz** [comment]
Also tested it out with Firefox Developer Edition, does occur! Saw it occurring till it switches to the Card/Modal like view at `>800px` width. Relevant for both Cat and Skull variants.

**Comment by samrae7** [comment]
sorry for delay on this. I will do my PR changes in next 2 days
