### ISSUE TITLE
Loads of work lost

### ISSUE THREAD

**Issue by joeyhub** [thepracticaldev/dev.to#4488]
My post we reverted to a version from days and days ago. Why?

**Comment by jessleenyc** [comment]
@joeyhub can you expand more on this and send an email to yo@dev.to? Our support team can help you handle specific account issues. Was it a saved draft or published post that got reverted?

**Comment by joeyhub** [comment]
I pulled it off as a backup from somewhere else. Potential causes:

* Lack of cache busting (could be failing to bust the browser's form cache in all cases).
* Poor reaction (or lack off) on eventual consistency.
* Some issues to do with if you edit on one device one day then another the other day.
