### ISSUE TITLE
Question: What does the deployment process look like?

### ISSUE THREAD

**Issue by rpalo** [thepracticaldev/dev.to#4494]
@benhalpern recommended that a good spot for me to help out might be in the effort to generalize things so people could stand up their own custom instances.  To start with that, it seemed like a good idea to stand up my own instance, but I'm having trouble locating deployment docs.

What does the DEV deployment process look like?  Any tips on how I could attempt to deploy my own instance to start hunting for hard-coded pieces?  Or just point me at the config/build files to read through.  I looked through as much as I could, but they were mostly for deploying a development environment.  

Thank you! 😄

**Comment by maestromac** [comment]
Hello @rpalo ! I can create a deployment doc that will give you a good overview of the process and requirements.

**Comment by rpalo** [comment]
Thank you!  I'll get reading 😄
