### ISSUE TITLE
Tables on blogs do not look good

### ISSUE THREAD

**Issue by dlebrero** [thepracticaldev/dev.to#45]
For example:

     | Availability / MTTR |  1h | 4h | 24h |
     | -------------    |-------------| ----- | -----|
     | 90 % | 9h | 1d 12h | 9d |
     | 95 % | 19h | 3d 4h | 19d |  
     | 99 % |  4d 3h | 2w | 3.5mo |

Should look like:

| Availability / MTTR |  1h | 4h | 24h |
| -------------    |-------------| ----- | -----|
| 90 % | 9h | 1d 12h | 9d |
| 95 % | 19h | 3d 4h | 19d |
| 99 % |  4d 3h | 2w | 3.5mo |

But looks like:

<img width="1280" alt="screen shot 2017-06-09 at 18 44 14" src="https://user-images.githubusercontent.com/2147539/26985523-179c9262-4d44-11e7-9f6a-d7105aeb9635.png">

**Comment by benhalpern** [comment]
Thanks. I'm on it.

**Comment by benhalpern** [comment]
This is fixed. I went with "full-width" tables no matter what. If you think that wasn't the right look, let me know. But either way, it's better now if you re-save an article.

**Comment by jessleenyc** [comment]
Hey @dlebrero - closing this for now but feel free to reopen if you have suggestions or opinions on style.
