### ISSUE TITLE
Why my post duplicate when i edit it?

### ISSUE THREAD

**Issue by cedonhub** [thepracticaldev/dev.to#4501]
**Describe the bug**

**To Reproduce**

 Dashboard
 Post> Edit> Save Changes
 Dashboard
 Duplicates posts

**Expected behavior**

Se a unique updated post
**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOs Mojave
- Browser: Google Chrome
- Version: 61.0.3163.91

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by benhalpern** [comment]
I'm sorry about this, it has been resolved as discussed here...

https://github.com/thepracticaldev/dev.to/issues/4502
