### ISSUE TITLE
Seeing a 500 error when attempting to create an article

### ISSUE THREAD

**Issue by PeterDavidCarter** [thepracticaldev/dev.to#4503]
**Describe the bug**

When I attempt to create a post, the webpage shows a 500 error, which refers to this github page and instructs to raise a bug report here.

**To Reproduce**

Login to my account. Click the 'write a post' button.

**Expected behavior**

Expected to be able to post.

**Screenshots**

![image](https://user-images.githubusercontent.com/23146481/67156785-1300d900-f31b-11e9-8a59-149c54fdd9e1.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: Version 77.0.3865.120 (Official Build) (64-bit)

**Additional context**

n/a

**Comment by jessleenyc** [comment]
Hey @PeterDavidCarter, this looks like an individual account issue. Please email yo@dev.to and someone from our support team will help you!
