### ISSUE TITLE
I got problem install many gem like approvals

### ISSUE THREAD

**Issue by jeann2013** [thepracticaldev/dev.to#451]
current directory: /var/lib/gems/2.5.0/gems/approvals-0.0.24/ext /usr/bin/ruby2.5 mkrf_conf.rb Building native extensions. This could take a while...

current directory: /var/lib/gems/2.5.0/gems/approvals-0.0.24/ext /usr/bin/ruby2.5 -rrubygems /usr/share/rubygems-integration/all/gems/rake-12.3.1/exe/rake RUBYARCHDIR=/var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/approvals-0.0.24 RUBYLIBDIR=/var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/approvals-0.0.24 /usr/bin/ruby2.5: No such file or directory -- /usr/share/rubygems-integration/all/gems/rake-12.3.1/exe/rake (LoadError)

rake failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.5.0/gems/approvals-0.0.24 for inspection. Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/approvals-0.0.24/gem_make.out

An error occurred while installing approvals (0.0.24), and Bundler cannot continue. Make sure that gem install approvals -v '0.0.24' succeeds before bundling.

Many problems

**Comment by Zhao-Andy** [comment]
Hey @jeann2013, could you share your operating system? From a preliminary check it looks like your gems are installed in version 2.5.0; we're running version 2.5.1. Also, knowing your Ruby version, how you installed Ruby, and your Ruby manager (if you're using one) will help.

If you haven't you checked out our installation guide, see it here for more general help:
https://docs.dev.to/installation/mac-os/

**Comment by jeann2013** [comment]
Look:

## Environment

```
Bundler             1.16.4
  Platforms         ruby, x86_64-linux
Ruby                2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
  Full Path         /home/jeann/.rbenv/versions/2.5.1/bin/ruby
  Config Dir        /home/jeann/.rbenv/versions/2.5.1/etc
RubyGems            2.7.6
  Gem Home          /home/jeann/.rvm/gems/ruby-2.5.1
  Gem Path          /home/jeann/.rvm/gems/ruby-2.5.1:/home/jeann/.rvm/gems/ruby-2.5.1@global
  User Path         /home/jeann/.gem/ruby/2.5.0
  Bin Dir           /home/jeann/.rvm/gems/ruby-2.5.1/bin
Tools
  Git               2.18.0
  RVM               1.29.4 (manual)
  rbenv             rbenv 1.1.1-39-g59785f6

  chruby            not installed
  rubygems-bundler  (1.4.4)
```

## Bundler Build Metadata

```
Built At          2018-08-20
Git SHA           a356d8cf9
Released Version  true

**Comment by rhymes** [comment]
Can you post somewhere the output of the error?

If you read the error message towards the end, the output has been saved in `/var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/approvals-0.0.24/gem_make.out`

BTW there's something weird with your installation because you're trying to build an extension using Ruby 2.5.1 on a 2.5.0 folder. 

Do you have both rbenv and rvm installed at the same time?

**Comment by rhymes** [comment]
@jeann2013 how did you solve it? It might help other people in the future :-)

**Comment by maestromac** [comment]
Closing this since it's solved.
