### ISSUE TITLE
Error Setup dev.to

### ISSUE THREAD

**Issue by jeann2013** [thepracticaldev/dev.to#452]
My env variables:

## Environment

```
Bundler             1.16.4
  Platforms         ruby, x86_64-linux
Ruby                2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
  Full Path         /home/jeann/.rbenv/versions/2.5.1/bin/ruby
  Config Dir        /home/jeann/.rbenv/versions/2.5.1/etc
RubyGems            2.7.6
  Gem Home          /home/jeann/.rvm/gems/ruby-2.5.1
  Gem Path          /home/jeann/.rvm/gems/ruby-2.5.1:/home/jeann/.rvm/gems/ruby-2.5.1@global
  User Path         /home/jeann/.gem/ruby/2.5.0
  Bin Dir           /home/jeann/.rvm/gems/ruby-2.5.1/bin
Tools
  Git               2.18.0
  RVM               1.29.4 (manual)
  rbenv             rbenv 1.1.1-39-g59785f6

  chruby            not installed
  rubygems-bundler  (1.4.4)
```

## Bundler Build Metadata

```
Built At          2018-08-20
Git SHA           a356d8cf9
Released Version  true
```
**error:** 
./setup 
== Installing dependencies ==
Ignoring executable-hooks-1.4.2 because its extensions are not built. Try: gem pristine executable-hooks --version 1.4.2
Ignoring gem-wrappers-1.4.0 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.4.0
Ignoring gem-wrappers-1.3.2 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.3.2
Error loading RubyGems plugin "/home/jeann/.rvm/gems/ruby-2.5.1@global/gems/executable-hooks-1.4.2/lib/rubygems_plugin.rb": cannot load such file -- executable-hooks/wrapper (LoadError)
Error loading RubyGems plugin "/home/jeann/.rvm/gems/ruby-2.5.1@global/gems/gem-wrappers-1.4.0/lib/rubygems_plugin.rb": cannot load such file -- gem-wrappers (LoadError)
Ignoring executable-hooks-1.4.2 because its extensions are not built. Try: gem pristine executable-hooks --version 1.4.2
Ignoring gem-wrappers-1.4.0 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.4.0
Ignoring gem-wrappers-1.3.2 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.3.2
The Gemfile's dependencies are satisfied
yarn install v1.9.4
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.59s.

== Preparing database ==
rails aborted!
Psych::SyntaxError: (<unknown>): could not find expected ':' while scanning a simple key at line 3 column 1
/home/jeann/.rvm/gems/ruby-2.5.1/gems/figaro-1.1.1/lib/figaro/application.rb:60:in `parse'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/figaro-1.1.1/lib/figaro/application.rb:56:in `block in raw_configuration'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/figaro-1.1.1/lib/figaro/application.rb:56:in `raw_configuration'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/figaro-1.1.1/lib/figaro/application.rb:64:in `global_configuration'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/figaro-1.1.1/lib/figaro/application.rb:32:in `configuration'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/figaro-1.1.1/lib/figaro/application.rb:42:in `each'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/figaro-1.1.1/lib/figaro/application.rb:36:in `load'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/figaro-1.1.1/lib/figaro.rb:23:in `load'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/figaro-1.1.1/lib/figaro/rails/railtie.rb:5:in `block in <class:Railtie>'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:67:in `block in execute_hook'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:49:in `each'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/railties-5.1.6/lib/rails/application.rb:91:in `inherited'
/home/jeann/dev.to/config/application.rb:14:in `<module:PracticalDeveloper>'
/home/jeann/dev.to/config/application.rb:13:in `<top (required)>'
/home/jeann/dev.to/Rakefile:4:in `require'
/home/jeann/dev.to/Rakefile:4:in `<top (required)>'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/railties-5.1.6/lib/rails/command.rb:46:in `invoke'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
/home/jeann/dev.to/bin/rails:9:in `require'
/home/jeann/dev.to/bin/rails:9:in `<top (required)>'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/home/jeann/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/home/jeann/dev.to/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
(See full trace by running task with --trace)

== Command ["bin/rails db:setup"] failed ==

**Comment by rhymes** [comment]
Can you post your application.yml ?

**Comment by jeann2013** [comment]
Sure, there here:

GITHUB_KEY:
GITHUB_SECRET:
GITHUB_TOKEN:utyiouetorutreutoureotuuor

TWITTER_ACCESS_TOKEN:
TWITTER_ACCESS_TOKEN_SECRET:
TWITTER_KEY:
TWITTER_SECRET:

STREAM_RAILS_KEY:
STREAM_RAILS_SECRET:

ALGOLIASEARCH_API_KEY:sdhfksjdhfkhsdkfhkdshkfh
ALGOLIASEARCH_APPLICATION_ID:JRB13sdlkfdsl;f
ALGOLIASEARCH_SEARCH_ONLY_KEY:88113bbc14b95dfjklsdjfljdsljfsd

**Comment by rhymes** [comment]
You need to add a space between the colon of the variable and the value.

`GITHUB_TOKEN: value`

not 

`GITHUB_TOKEN:value`

the same goes for the others.

**Comment by jeann2013** [comment]
But right now give me this error:

== Preparing database ==
PG::QueryCanceled: ERROR:  canceling statement due to statement timeout
: CREATE DATABASE "PracticalDeveloper_development" ENCODING = 'unicode'
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "connect_timeout"=>2, "checkout_timeout"=>2, "variables"=>{"statement_timeout"=>2500}, "database"=>"PracticalDeveloper_development"}
rails aborted!
ActiveRecord::StatementInvalid: PG::QueryCanceled: ERROR:  canceling statement due to statement timeout
: CREATE DATABASE "PracticalDeveloper_development" ENCODING = 'unicode'


why?...I got install postgresql and setup my user

**Comment by rhymes** [comment]
Follow the white rabbit ;-)

If you read the error it says "canceling statement due to statement timeout" which means that the statement `CREATE DATABASE` timed out.

What happens if you try do it manually?

```shell
➜  ~ psql -U YOUR_USERNAME test
psql (10.5)
Type "help" for help.

test=# CREATE DATABASE foobar;
CREATE DATABASE
test=# DROP DATABASE foobar;
DROP DATABASE
```

Does this work?

**Comment by Zhao-Andy** [comment]
Try our guide on this as well:
https://docs.dev.to/additional-postgres-setup/
> While running test cases, if you get an error message postgresql connection timeout. Go to your spec/support/database_cleaner.rb file. And rename :truncation with :deletion.

**Comment by jeann2013** [comment]
I fixed the problem, just set password and username in database.yml.

Thank Guys!!!

**Comment by Zhao-Andy** [comment]
Feel free to write a post about the errors you wrote! It'll be really helpful for us and anyone else going through it. :)

**Comment by jeann2013** [comment]
Where they need more help in this cool project?
