### ISSUE TITLE
Articles API: state=all by itself results in a 500 error

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#4522]
**Describe the bug**

Calling `curl https://dev.to/api/articles?state=all` results in a 500 error.

Although, according to the documentation, that specific parameter is only to be used in conjunction with `username`, used by itself shouldn't result in a 500 error, instead it should return an empty result set.

**To Reproduce**

1. Type `curl https://dev.to/api/articles?state=all` or `curl http://localhost:3000/api/articles?state=all` in your local development environment
2. see error

**Expected behavior**

Calling `curl https://dev.to/api/articles?state=all` should return an empty JSON array

**Additional context**

The issue is likely the missing `else` condition here:

https://github.com/thepracticaldev/dev.to/blob/0d2506f9ef79a32f7474001337161314d1062134/app/services/article_api_index_service.rb#L77-L85

**Comment by tudorpavel** [comment]
I can take a look at this. :slightly_smiling_face:

**Comment by sabunt** [comment]
@rhymes  pls merge

**Comment by rhymes** [comment]
@tudorpavel just FYI, @sabunt submit a PR for this
