### ISSUE TITLE
Rubocop detects offenses in code

### ISSUE THREAD

**Issue by johncurcio** [thepracticaldev/dev.to#4528]
**Describe the bug**

This is more a refactor request than a bug.

When you run Rubocop with dev.to config file, it detects a few (56) offenses in the formatting of the code, most of which is a lack of an empty line after an example:

 https://github.com/thepracticaldev/dev.to/blob/0d2506f9ef79a32f7474001337161314d1062134/spec/system/user/user_edits_integrations_spec.rb#L35-L36

There's also a block with a typo - ``xit`` instead of ``it``:

https://github.com/thepracticaldev/dev.to/blob/0d2506f9ef79a32f7474001337161314d1062134/spec/system/user/user_edits_integrations_spec.rb#L22

**To Reproduce**

Run in the main folder:

```sh
rubocop
```

**Expected behavior**

Rubocop should not detect offenses/warnings.

**Screenshots**

![rubocop](https://user-images.githubusercontent.com/9089551/67230468-bcc39100-f413-11e9-8223-443655bba809.png)

**Additional comments:**

```
1063 files inspected, 56 offenses detected

49  RSpec/EmptyLineAfterExample
5   Style/StringLiterals
1   Lint/UnneededCopDisableDirective
1   RSpec/NestedGroups
--
56  Total
```

I can definitely fix these later, but I think it would be a good first issue if anyone wants to contribute.

**Comment by rhymes** [comment]
Thanks for the catch @johncurcio!

For whomever takes this on:

. `rubocop -a` will autocorrect what's possible to autocorrect and display what's missing, run it twice if you have too much output, the second time will only display what's left to correct
. `rubocop --auto-gen-config` should be run at the end so to regenerate the TODO file

Thank you!

**Comment by jabawack81** [comment]
I can work on this

**Comment by rhymes** [comment]
@jabawack81 thank you and go ahead!
