### ISSUE TITLE
Retry attempt is not respected in docker-run.sh

### ISSUE THREAD

**Issue by worldofprasanna** [thepracticaldev/dev.to#4536]
**Describe the bug**

I tried to set up the application in my local and used docker-run.sh script. To start the application, even if it crosses the specified number of retry attempts, the process is not stopped.

I checked the code and found that `RETRIES` are not decremented for each loop. (docker-run.sh:483) Is this intended behavior or a bug?

**To Reproduce**

Run `./docker-run.sh INTERACTIVE-DEMO`

**Expected behavior**

At some point in time, it should stop saying the max retry has reached.

**Screenshots**

<img width="1437" alt="Screenshot 2019-10-22 at 12 44 26 PM" src="https://user-images.githubusercontent.com/1291984/67265117-944a9e00-f4ca-11e9-8b33-f9a2f907c45d.png">
<img width="1428" alt="Screenshot 2019-10-22 at 12 44 13 PM" src="https://user-images.githubusercontent.com/1291984/67265139-a0cef680-f4ca-11e9-96f7-1d02404e832e.png">

**Desktop (please complete the following information):**

- OS: macOS Mojave

**Additional context**

This is an issue in setting up the application using docker-run.sh

**Comment by tudorpavel** [comment]
I can take a look at this. :slightly_smiling_face:

**Comment by tudorpavel** [comment]
Or not. :slightly_smiling_face:

**Comment by worldofprasanna** [comment]
> Or not. 🙂

Sorry @tudorpavel, I have raised a PR for this ... I already made those changes in my local.

**Comment by tudorpavel** [comment]
No worries, are you also looking into why that `docker exec dev-to-app curl` retry loop never succeeds?

**Comment by worldofprasanna** [comment]
@tudorpavel No I am looking at that issue. You can try that one 👍
