### ISSUE TITLE
facing 500 error

### ISSUE THREAD

**Issue by octalitsolution** [thepracticaldev/dev.to#4540]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by jessleenyc** [comment]
@octalitsolution since there is no context for this issue, I'll have to close it. Feel free to re-open if you have more information. If this is for an individual account concern, please email yo@dev.to instead. Thanks!
