### ISSUE TITLE
facing 500 error

### ISSUE THREAD

**Issue by octalitsolution** [thepracticaldev/dev.to#4541]
**Describe the bug**
on a profile section, I
![Capture](https://user-images.githubusercontent.com/56387985/67278958-b30b5d80-f4e7-11e9-910e-b2c341e8a161.PNG)
 am seeing 500 error 

**Screenshots**

**Comment by rclanan** [comment]
Any additional information you can provide on this? What are the steps to get to the profile section that is causing the 500 error?

**Comment by jessleenyc** [comment]
Hey @octalitsolution! Thanks for the report. This is likely an individual account issue -- please email yo@dev.to for support.
