### ISSUE TITLE
Add the hyperlink target _blank option.

### ISSUE THREAD

**Issue by codder404** [thepracticaldev/dev.to#4542]
**Is your feature request related to a problem? Please describe.**
When I am using Dev.to and want to access an external link, the link loads on the same page. I would like you to solve that.

**Describe the solution you'd like**
The solution to this problem is by adding the hyperlink target _blank.

**Describe alternatives you've considered**
The alternative I've been using is right-clicking to go to the link destination.

Thanks
Fernando

**Comment by rhymes** [comment]
Hi @codder404, thanks for raising this!

I personally am not in favor of having all links have a `target="_blank"` for reasons you can find in [this article](https://css-tricks.com/use-target_blank/). If you use a keyboard you can also open external links with META-click, it's faster than right clicking.

Said that, probably the best compromise is to keep the status quo and have a user option that can enable such feature. 

We had a discussion about this in this issue: https://github.com/thepracticaldev/dev.to/issues/1716 

If you're okay with it I'd close this in favor of the other one :)

**Comment by rclanan** [comment]
> Hi @codder404, thanks for raising this!
> 
> I personally am not in favor of having all links have a `target="_blank"` for reasons you can find in [this article](https://css-tricks.com/use-target_blank/) (forcing the target means that all links always open in another tab, removing the default behavior). If you use a keyboard you can also open external links with META-click, it's faster than right clicking.
> 
> Said that, probably the best compromise is to keep the status quo and have a user option that can enable such feature.
> 
> We had a discussion about this in this issue: #1716
> 
> If you're okay with it I'd close this in favor of the other one :)

I think the idea of it being controlled by a user setting is great! Satisfies both parties.

**Comment by codder404** [comment]
Copy that!
