### ISSUE TITLE
Implementing native copy-to-clipboard functions for Android app.

### ISSUE THREAD

**Issue by VarunBarad** [thepracticaldev/dev.to#4543]
**Is your feature request related to a problem? Please describe.**

The copy-post-url feature doesn't work on the Android app (most probably because it is rendering the website in an Android `WebView`). The solution requires changes to be made both in the app code and on the website code. I have already created a [PR](https://github.com/thepracticaldev/DEV-Android/pull/60) on the app's repository with the changes that need to be made on the native side. The changes for website are described below.

**Describe the solution you'd like**

As mentioned in #4399 I have added a bridge in the android app code which helps to invoke native functions from JavaScript on the website. To invoke the native copy-to-clipboard code, all that is required to do is to call the method `copyToClipboard(postUrl)` on `androidWebViewBridge`.

The code for it looks like below:

```javascript
// Existing code might be something like this
existingCopyPostUrlToClipboardFunction(postUrl);
```

```javascript
// That line gets replaced with this
if (((typeof androidWebViewBridge) !== 'undefined') && (androidWebViewBridge !== null)) { // this checks if the site is being run inside an android webview
  androidWebViewBridge.copyToClipboard(postUrl); // This invokes the native method for copying the link to clipboard
  androidWebViewBridge.showToast('Link copied to clipboard!'); // This shows a toast-message to user
} else {
  // Your existing code would go here since execution will reach here in all the cases when this is not being run inside the DEV android app
  existingCopyPostUrlToClipboardFunction(postUrl);
}
```

**Additional context**

This would be a part of the shift towards including more native-code and functionalities in the Android app.

I tried setting-up my environment for working on this repository locally but the ruby installation was giving me some problems so I can't create a PR for this.

**Comment by VarunBarad** [comment]
@maestromac any help required?

**Comment by dhruvin2910** [comment]
[@github/clipboard-copy-element](https://github.com/github/clipboard-copy-element) is used [here](https://github.com/thepracticaldev/dev.to/blob/64c9b36a40853f604932839201c2011934fa9f96/app/views/articles/_actions.html.erb#L54-L58) to provide clipboard support.

Similar problem might have occurred [here](https://github.com/thepracticaldev/dev.to/blob/61494d23432371805a084d96a16d9efc335ce5a0/app/javascript/article-form/elements/imageManagement.jsx#L133-L151), as we are using an additional ([onClick](https://github.com/thepracticaldev/dev.to/blob/61494d23432371805a084d96a16d9efc335ce5a0/app/javascript/article-form/elements/imageManagement.jsx#L69-L96)) callback. Maybe @bolariin can confirm this.

clipboard-copy emits [a custom event](https://github.com/github/clipboard-copy-element/blob/master/src/clipboard-copy-element.js#L10). But it does not provide what gets copied in `event.details`. Hence, I have created an [issue](https://github.com/github/clipboard-copy-element/issues/23) (soon PR) there. Once we have it, we can add an event listener to document with the code suggested by @VarunBarad.

**Comment by maestromac** [comment]
Sorry for the late response. Thank you for the extensive work you've put into this @VarunBarad and Thank you for creating an issue and PR @dhruvin2910 

I understand the native approach would be a solid choice but the code is not structured in the manner that you would've expected (ie `existingCopyPostUrlToClipboardFunction(postUrl)`). Following what @dhruvin2910 has done, I've looked into what the maintainer of `@github/clipboard-copy-element` suggested and they were correct. A combination of adding a [polyfill](https://github.com/lgarron/clipboard-polyfill) and rearranging the HTML element so that it isn't one big custom element solved this issue. I'll go ahead and do that

ref: initial feature PR is https://github.com/thepracticaldev/dev.to/pull/1579/files
