### ISSUE TITLE
bug issue

### ISSUE THREAD

**Issue by twinztech** [thepracticaldev/dev.to#4547]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

![image](https://user-images.githubusercontent.com/44340621/67294485-8402e500-f503-11e9-90cd-2aaf759388c4.png)

**Comment by twinztech** [comment]
![image](https://user-images.githubusercontent.com/44340621/67294397-646bbc80-f503-11e9-982a-5892d9608284.png)

**Comment by rclanan** [comment]
Is there any additional information on how to reproduce this error? I have tried it from my machine, signed in and signed out and the url that is in your screenshot is working fine on my windows machine.

**Comment by jessleenyc** [comment]
@twinztech this looks like an issue with an individual account - please email yo@dev.to for support. Thank you!
