### ISSUE TITLE
PR CI failing because of incompatible Chrome version

### ISSUE THREAD

**Issue by tudorpavel** [thepracticaldev/dev.to#4553]
**Describe the bug**

The PR builds started failing since 22nd of Oct: https://travis-ci.com/thepracticaldev/dev.to/pull_requests.

**To Reproduce**

Any new PR will show the following error:

```
session not created: This version of ChromeDriver only supports Chrome version 76
```

For the [last passing build](https://travis-ci.com/thepracticaldev/dev.to/builds/133058167) Travis is installing Chrome 77:

```
Preparing to unpack .../google-chrome-stable_current_amd64.deb ...

Unpacking google-chrome-stable (77.0.3865.120-1) over (73.0.3683.86-1) ...

Setting up google-chrome-stable (77.0.3865.120-1) ...
```

But for [failing builds](https://travis-ci.com/thepracticaldev/dev.to/builds/133078537) Travis is installing Chrome 78:

```
Preparing to unpack .../google-chrome-stable_current_amd64.deb ...

Unpacking google-chrome-stable (78.0.3904.70-1) over (73.0.3683.86-1) ...

Setting up google-chrome-stable (78.0.3904.70-1) ...
```

**Expected behavior**

The builds should not fail because of Chrome Driver version. The version that Travis installs should probably match the one [required by webdrivers here](https://github.com/thepracticaldev/dev.to/blob/master/spec/support/initializers/capybara.rb#L5).

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by tudorpavel** [comment]
I'm looking into this.

**Comment by rhymes** [comment]
Closed by https://github.com/thepracticaldev/dev.to/pull/4554
