### ISSUE TITLE
Firefox tab switch results in offline page when online

### ISSUE THREAD

**Issue by mattwaler** [thepracticaldev/dev.to#456]
## Bug Report
Every time I navigate to the site from a Firefox tab on another site, I get redirected to the offline page.

### Additional Info (device/browser, helpful links)
Link to device/browser info:
[Stuffs.zip](https://github.com/thepracticaldev/dev.to/files/2318515/Stuffs.zip)

**Comment by benhalpern** [comment]
Is this new behavior or has it always been the case for you?

**Comment by mattwaler** [comment]
This has always been the case, I am a new user of the site.

Thanks,

—

Matthew Waler
Web Developer

Phone: 	(440) 829-5806 <tel:440-829-5806>
Web:	https://mattwaler.com <https://mattwaler.com/>

**Comment by GAumala** [comment]
This has always happened on Firefox. I read an article, click a link that takes me to other domain and when I press back to return to the article I get this message that "there's no internet connection". If I open a new tab to the homepage I get the same message.

Maybe there's something weird going on with the service worker?

**Comment by Zhao-Andy** [comment]
There might be something related to our implementation of service workers that affects Firefox specifically. It might also be related to the `waitUntil()` event @robx mentioned.

A related issue was made previously: https://github.com/thepracticaldev/dev.to/issues/128

If anyone wants to take a look at it, feel free to look at our service worker files: `serviceworker.js.erb` and `serviceworker-companion.js`. As we're not experts on service workers, any help with this will be warmly welcomed and appreciated!

**Comment by nickytonline** [comment]
Happy to take this on, but I followed the steps to reproduce that @GAumala provided and I'm unable to reproduce. 

I'm running FF 61 on macOS.

![error](https://user-images.githubusercontent.com/833231/44760474-ec775180-ab0c-11e8-8db0-ff6a8580039a.gif)

**Comment by nickytonline** [comment]
I'm also unable to reproduce it with @mattwaler's instructions.

![error](https://user-images.githubusercontent.com/833231/44760625-b5557000-ab0d-11e8-8c35-7ef63b264295.gif)

**Comment by mattwaler** [comment]
I think I may have figured it out. Judging from @GAumala's video and my own experience, the only thing in common between us and nobody else is the privacy badger extension. I've disabled it on the dev.to domain and so far so good, but I will continue to test to be sure.

**Comment by GAumala** [comment]
Disabling Privacy Badger for dev.to using the extension's "Disable Privacy Badger for This Site" button did not fix the issue. But, if I completely disable it from the add-on's manager, then it finally works.

**Comment by mattwaler** [comment]
100% confirmed. When navigating from the site to another and back, privacy badger detects the entire site (for reasons unknown) as a tracker and blocks it completely. To fix, when the bug presents itself, simply open the extension and allow dev.to through.

Sorry for taking up everybody's time!

**Comment by nickytonline** [comment]
Nice! I was going to mention extensions causing issues, but I didn't want to mention it too early before doing some more tests.

**Comment by mattwaler** [comment]
@GAumala per my previous comment, I was only able to fix this by causing the bug, then opening the extension options and changing "dev.to" from red to green in the extension. I have yet to see the bug after doing this.

**Comment by GAumala** [comment]
Yes that did fix it for me too. Thanks!

**Comment by ghostwords** [comment]
I think this is some sort of bug in the interaction between Service Workers and WebExtensions APIs in Firefox. See https://github.com/EFForg/privacybadger/issues/1144 for the root Privacy Badger issue tracking this problem. There is also a bit of analysis in https://github.com/EFForg/privacybadger/issues/2062#issuecomment-397002340. I would love help in narrowing down the exact cause and filing a [Mozilla Bugzilla](https://bugzilla.mozilla.org/) issue.
