### ISSUE TITLE
reducing pack size under .git/objects/pack dir?

### ISSUE THREAD

**Issue by ekremkaraca** [thepracticaldev/dev.to#4565]
Hey guys,

Today I've cloned the repo and when I check its files (using `ncdu`), folders and their size, I noticed that size of pack files under `.git/objects/pack` folder is about 40MiB. Is it possible to reduce its size?

```
--- /tmp/dev.to
---------------------------------------
   42.1 MiB [##########] /.git                                                                                            
   12.2 MiB [##        ] /app
    8.2 MiB [#         ] /spec
    1.5 MiB [          ] /db
```

```
--- /tmp/dev.to/.git/objects/pack -----------------------------------------
   40.7 MiB [##########]  pack-cac67e9a87dbe8ca891da18d1f1a5e1b85852ab0.pack                                              
  968.0 KiB [          ]  pack-cac67e9a87dbe8ca891da18d1f1a5e1b85852ab0.idx
```

**Comment by rhymes** [comment]
Hi @ekremkaraca, not really I think.

The git pack folder contains all the history of the repo :)

You might be able to reduce the size on your copy with `git gc` and `git prune` for example.

I'm closing this because it's not exactly an issue of the DEV app!
