### ISSUE TITLE
Profile Menu does not open at some certain situations

### ISSUE THREAD

**Issue by saurabhdaware** [thepracticaldev/dev.to#4571]
**Describe the bug**
When you navigate to page from a profile menu it works correctly the first time but when you try to navigate again the menu does not open.
(Sorry this is kind of difficult to explain I've attached a video below to explain better)

I've described it better below in steps to reproduce and the video

**To Reproduce**
(I've also attached a video below to explain this)

1. Open main page (https://dev.to) 
2. Click profile picture
3. Select your username from navigation
4. Now If you try to click on your profile picture again it will not open the navigation.

**Expected behavior**

**Screenshots**
![GIF Explaining the Menu Bug](https://user-images.githubusercontent.com/30949385/67477924-b08c3d80-f678-11e9-917d-62d16252841b.gif)

**Desktop (please complete the following information):**

- OS: Ubuntu 19
- Browser: Chrome
- Version: 77.0.3865.120 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: Motorola One Power
- OS: Android Pie
- Browser: Chrome
- Version: 77.0.3865.116

**Additional context**
I've tried this on both Android and Desktop and even on the Android App and the results were same. There weren't any additional errors in the console.

**Comment by jennapederson** [comment]
I can grab this one.

Reproducible on touch devices.

**Comment by Clarity-89** [comment]
@jennapederson how far you with this? Was just about to submit a PR and noticed your message :D

**Comment by jennapederson** [comment]
I have a fix and am just wrapping up testing.
