### ISSUE TITLE
CSS code styling in dark mode

### ISSUE THREAD

**Issue by GarethTF** [thepracticaldev/dev.to#4577]
![dev-error](https://user-images.githubusercontent.com/56965213/67487263-867d5000-f665-11e9-9f74-d678501c0bd0.png)

As per the screenshot, the .err css class is very hard to read when in dark mode.

The code to look for is ".highlight .err"

**Comment by joaoskr** [comment]
Just changed the colors with the dark background, this way appears to be better ?

![Captura de Tela 2019-10-28 às 16 28 51](https://user-images.githubusercontent.com/17601527/67711240-5523bd80-f9a0-11e9-9053-e48015f2aa2d.png)

**Comment by GarethTF** [comment]
Prefer the first, white on red is much easier to read than pink on black
