### ISSUE TITLE
Remove Climate Strike related code

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/dev.to#4580]
Now that the Climate Strike is officially over, please remove the following lines from the following file:

https://github.com/thepracticaldev/dev.to/blob/7423d05af62b58fde4e73e34152e065b3403b9ea/app/views/articles/index.html.erb#L27-L38

Easy pick up for Hacktoberfest!

**Comment by btn0s** [comment]
https://github.com/thepracticaldev/dev.to/pull/4581 :)

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/4581
