### ISSUE TITLE
Self-Report on DEV Connect

### ISSUE THREAD

**Issue by dev-encourt** [thepracticaldev/dev.to#4589]
**Describe the bug**
Users are able to report themselves for abuse in DEV Connect. Clicking the button will lead to a report for the user on the other end of the chat. 

**To Reproduce**
1. Enter a private message with another user in DEV Connect. 
2. Click on your own username to open the profile sidebar. 
3. Click on the report button. 

**Expected behavior**
Users should not have a report button in their own profile sidebar, just like they don't have a block button. 

**Screenshots**
![selfreport1](https://user-images.githubusercontent.com/51792350/67577463-7f5e4c80-f70e-11e9-8c1c-84c8caf60c14.png)
![selfreport2](https://user-images.githubusercontent.com/51792350/67577695-fdbaee80-f70e-11e9-9da6-eb9f1e2a018b.png)
When you do report yourself for abuse, it will link the user or group you were speaking to. In this case, I was speaking to Michael when I found the bug so it linked to him. 

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome 
- Version: 77.0.3865.120

**Comment by ashwinv11** [comment]
I can pick this one up!
