### ISSUE TITLE
Show recent comments even if the user does not have any articles

### ISSUE THREAD

**Issue by Defman21** [thepracticaldev/dev.to#46]
title. I don't have any articles published on dev.to and my profile page does not show any comments I wrote. It just shows me an empty div with a border. Those who have at least one article, have their comments on their page.

**Comment by benhalpern** [comment]
Good call. This should be fast and easy.

**Comment by benhalpern** [comment]
Okay fixed this. Thanks for the heads up. We knew about this issue but were being lazy.

**Comment by Defman21** [comment]
>were being lazy.

😛
