### ISSUE TITLE
"This content is not available" for a gif-file in the Notifications area

### ISSUE THREAD

**Issue by setevoy2** [thepracticaldev/dev.to#4606]
**Describe the bug**
On the notifications page, a gif wasn't loaded saying "_This content is not available_", but this gif can be accessed by clicking the image (see a screenshot below).

The URL to the Gif is https://giphy.com/gifs/hallmarkmovie-hallmark-movies-and-mysteries-garage-sale-mystery-sleuthers-82lalqBsmW56Z6E2oV

**To Reproduce**

1. create a post
2. wait for a notification about <LIMIT> reached to get congrats in the Notifications
3. check the Gif there

**Expected behavior**

1. a Gif is played

**Screenshots**

![Screenshot_20191026_171700](https://user-images.githubusercontent.com/7965314/67620934-aa32c880-f814-11e9-898a-bd864acba19f.png)

- OS: Arch Linux
- Browser: Chromium
- Version: Version 77.0.3865.120 (Official Build) Arch Linux (64-bit)

**Comment by jessleenyc** [comment]
Hm, maybe the gif was down temporarily and this got cached somehow. Can you still see this in your notifications? To be safe, I think we should probably remove this one from the rotation if someone wants to submit a PR.

**Comment by daolf** [comment]
Did it here: https://github.com/thepracticaldev/dev.to/pull/6168
