### ISSUE TITLE
Empty State for Badges Panel

### ISSUE THREAD

**Issue by jayehernandez** [thepracticaldev/dev.to#4610]
**Is your feature request related to a problem? Please describe.**

The empty state for the badges panel (on mobile) when a user has no badges / repos linked is plain white.

![94046D77-A633-4E08-8A98-6C4739446A62](https://user-images.githubusercontent.com/13959651/67624066-f145ab80-f85e-11e9-80aa-a7052c7f6fc6.jpeg)

**Describe the solution you'd like**

Add a little something to the section like “This is where all the badges you’ve collected go!” to motivate people to write and contribute more! (You guys can definitely think of a better copy for this!)

Let me know if I missed something. If ever, I’d love to take this on as well!

**Comment by jessleenyc** [comment]
Good call. Let's add a conditional to show some copy if the sidebar for users that don't have activity there. For now, placeholder lorem ipsum will work and we can needle on the copy on our end. Let's have the copy only appear for mobile views because having it blank looks fine on desktop.

**Comment by cesc1989** [comment]
👋 @jessleenyc submitted a PR for this. I followed your suggestion for the text placing a lorem ipsum 😄
