### ISSUE TITLE
Posts imported via RSS are not having their images uploaded/updated within the post body.

### ISSUE THREAD

**Issue by Kritner** [thepracticaldev/dev.to#4619]
**Describe the bug**

Posts imported via RSS feed keep their relative links to images, rather than having them auto-uploaded and renamed using cloudinary hosting.

**To Reproduce**

Not sure what originally caused it, though I did recently have this issue #3995, not sure if it's related to these posts "existing" prior to resolving the problem on my end or not.

I tried deleting the posts, and waiting for the new time the RSS feed gets loaded, but this did not help.

**Expected behavior**

When posts are put on my dashboard when being imported via RSS, their images should be uploaded the to dev.to image store, and the local, relative link updated accordingly.

**Screenshots**

![image](https://user-images.githubusercontent.com/8814983/67639295-74e5b380-f8c4-11e9-9644-634806411f80.png)
![image](https://user-images.githubusercontent.com/8814983/67639308-9cd51700-f8c4-11e9-901a-7e717043ed66.png)

**Desktop (please complete the following information):**

- OS: windows 10
- Browser: chrome
- Version: Version 77.0.3865.120 (Official Build) (64-bit)

**Comment by maestromac** [comment]
Hello @Kritner , we use the image src provide by rss feed. Often time those image source is a full complete link and sometime it is is relative link. If it happens to be a relative link, we will attempt to complete it by prepending the feed source link (ie, `yourfeed.com` + `/some-image.jpeg`) similar to how it is done with github's markdown.  The logic of that can be seen here https://github.com/thepracticaldev/dev.to/blob/961bef01737d76da4ce0c4c11443c7a6f4d9e0e3/app/services/rss_reader/assembler.rb#L125



I'm looked in your feed and I see the post in question has it's image source stating the file name. 
![Screen Shot 2019-11-04 at 4 26 33 PM](https://user-images.githubusercontent.com/15793250/68161843-b6113f80-ff24-11e9-99ee-35be9b6142d5.png)

The most foolproof method would be to provide a full link for image source. Providing a referential link is usually safe too but the image from that particular post does not have it's source on the root (`https://blog.kritner.com/2019/10/27/test-post-with-image/output.PNG`) . Let me know if that clear things up a bit.

**Comment by Kritner** [comment]
dang... this is what i get for updating npm packages just cuz there are updates :D 

thanks! I'll figure something out to fix this... hopefully
