### ISSUE TITLE
Organization URL does update when changing the name field.

### ISSUE THREAD

**Issue by autoferrit** [thepracticaldev/dev.to#462]
### Current Behavior
On the [/organization](https://dev.to/settings/organization) page, changing the `name` field to change the name of my organization, will save. But does not actually change the associated URL

### Expected Behavior
Changing the `name` field in an organization, changes the actual URL of the organization.

### Additional Info (device/browser, helpful links)
Chrome `69.0.3497.42` on linux

related to #417

**Comment by craigbrad** [comment]
Is this issue still available? I'd love to take a look.

**Comment by jessleenyc** [comment]
@craigbrad go for it!
