### ISSUE TITLE
Add rate limiting to prevent mass following of users

### ISSUE THREAD

**Issue by pkfrank** [thepracticaldev/dev.to#4640]
**Is your feature request related to a problem? Please describe.**
In order to prevent spam/abuse, we should rate-limit the number of users that an account can follow.

**Describe the solution you'd like**
A system that rate limits the number of accounts that an individual user account can follow.

**Additional context**
The functionality for this sort of stuff is currently driven by the `RateLimitChecker` class.

Likely in the range of 500 new accounts per day, but potentially way lower for a _newer_ account.  This point might add more complexity than we need initially, though.

**Comment by obahareth** [comment]
Hi, I would like to work on this!

**Comment by obahareth** [comment]
Just so I don't make the specs really slow, is there a recommended way to make 500 follows?

**Comment by rhymes** [comment]
Do you think you could use mocks to set a lower limit in the setup of the test?

Something like (copied from a different test):

```ruby
allow(User).to receive(:find_by).and_return(user)
```

**Comment by benhalpern** [comment]
@obahareth @rhymes I think the number could be an ENV variable (cleaner anyway) and then we could test with a lower number in the test/local environments.

**Comment by obahareth** [comment]
@benhalpern I updated my PR to use an environment variable `DAILY_ACCOUNT_FOLLOW_LIMIT` or `500` if it hasn't been set.

**Comment by rhymes** [comment]
Closed by https://github.com/thepracticaldev/dev.to/pull/4647 and https://github.com/thepracticaldev/dev.to/pull/4738
