### ISSUE TITLE
HTML Character References shown in "who to follow"

### ISSUE THREAD

**Issue by edent** [thepracticaldev/dev.to#4650]
**Describe the bug**
The "Who to follow" box displays escaped HTML character references.

**To Reproduce**

1. Sign up for a new account
2. Agree to the T&Cs
3. Scroll through the list of people to follow.

**Expected behavior**
Instead of `&#39;` display the apostrophe symbol. Instead of `&quot;,` show the quote symbol.

**Screenshots**
![Screen Shot 2019-10-29 at 16 37 12](https://user-images.githubusercontent.com/837136/67788985-27f01180-fa6b-11e9-889c-302cbdd2b900.png)
![Screen Shot 2019-10-29 at 16 36 38](https://user-images.githubusercontent.com/837136/67788986-27f01180-fa6b-11e9-9544-47f01d41ae5f.png)

**Desktop (please complete the following information):**

- OS: OSX
- Browser: Chrome
- Version: 78

**Comment by ShraddhaAg** [comment]
Hi. I'm new to the community and would like to start contributing. Is this up for grabs?

**Comment by rhymes** [comment]
@ShraddhaAg go ahead! and thank you!! :-)

**Comment by luchiago** [comment]
Hi, this issue still need help?

**Comment by ShraddhaAg** [comment]
Hi @luchiago! I'm still working on this one. Could you please pick up another issue? :)

**Comment by luchiago** [comment]
@ShraddhaAg of course, no problem!

**Comment by korczynsk1** [comment]
Hi @ShraddhaAg here is solution: https://github.com/thepracticaldev/dev.to/pull/4656. 
But tests are still undone if you would help with it :)

**Comment by citizen428** [comment]
Hi @ShraddhaAg, just checking in to see if you're still working on this? If yes, is there any help you need from us?

**Comment by ShraddhaAg** [comment]
Hi @citizen428. I'm having trouble writing the tests for it. Could you please point me to an example? I'm sorry about taking so long with this.

**Comment by citizen428** [comment]
No need to be sorry at all @ShraddhaAg, thanks for contributing! 😃

Regarding the spec, have a look at `spec/system/` for inspiration. These pretty much follow the user's journey through the app. You can also just open a work in progress PR (prefix the title with `[WIP]`) with what you have so far and we can look at it in more detail there.
