### ISSUE TITLE
Security issue - use SubResource Integrity on external Javascript

### ISSUE THREAD

**Issue by edent** [thepracticaldev/dev.to#4652]
**Is your feature request related to a problem? Please describe.**

External Javascript is subject to manipulation by hostile actors.

SRI is a new W3C specification that allows web developers to ensure that resources hosted on third-party servers have not been tampered with. Use of SRI is recommended as a best-practice, whenever libraries are loaded from a third-party source.

**Describe the solution you'd like**
Use SubResource Integrity to ensure that a compromised 3rd party can't affect users of the website.

In this case, the only external code seems to be `https://unpkg.com/@webcomponents/webcomponentsjs@2.2.10/webcomponents-loader.js`

This should be loaded using

```
<script
   src="https://unpkg.com/@webcomponents/webcomponentsjs@2.2.10/webcomponents-loader.js" 
   integrity="sha384-3HK5hxQbkFqOIxMbpROlRmRtYl2LBZ52t+tqcjzsmr9NJuOWQxl8RgQSyFvq2lhy"
   crossorigin="anonymous"></script>
```

**Describe alternatives you've considered**

Self-host the external JavaScript. If unpkg.com is compromised, it will not affect the local copy of the webcomponents-loader.

**Additional context**

This appears to only impact 4 files - https://github.com/thepracticaldev/dev.to/search?q=https%3A%2F%2Funpkg.com%2F%40webcomponents%2Fwebcomponentsjs%402.2.10%2Fwebcomponents-loader.js&unscoped_q=https%3A%2F%2Funpkg.com%2F%40webcomponents%2Fwebcomponentsjs%402.2.10%2Fwebcomponents-loader.js - but my Ruby isn't good enough to know how to fix it.

**Comment by nickytonline** [comment]
Adding the integrity attribute is a good idea for third party scripts. Thanks for bringing this up. 👏

Just adding the link to those unfamiliar with this, https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by rhymes** [comment]
Definitely agree! @edent would you be willing to contribute a PR for this?

**Comment by edent** [comment]
@rhymes I've done a basic PR. Please bear in mind...

1. I don't know Ruby
2. I don't have a build system
3. I don't know Ruby
4. I realise points (1) and (3) are the same - but I thought it so important that it was worth mentioning twice.

**Comment by rhymes** [comment]
ahahah @edent, you've been the most kind! I'll review it promptly
