### ISSUE TITLE
Coverage report not being generated

### ISSUE THREAD

**Issue by jameslvdb** [thepracticaldev/dev.to#4653]
**Describe the bug**

SimpleCov does not generate a coverage report after running tests locally.

**To Reproduce**

Run tests normally: `bundle exec rspec` or `bin/rspec`.

**Expected behavior**

A coverage report is generated in `coverage/index.html`.

**Additional context**

I was hoping to help increase test coverage and saw in the [docs](https://docs.dev.to/tests/code-coverage/) that a coverage report should be generated after running tests, but I don't see any report generated. I checked the `.simplecov` file and saw that SimpleCov is only run when the project is being run in the "COVERAGE" environment. Should SimpleCov be generating reports for development/test? Or were the docs not updated when a change was made to SimpleCov's environments?

**Comment by rhymes** [comment]
Weird! I have a `coverage` folder from the 15th of October 2019. I deleted it and re-ran the specs and the folder doesn't appear anymore.

This sounds like a bug or something we messed up in some configuration

**Comment by nadiyaka** [comment]
I found out that the issue is with this line `if ENV["COVERAGE"]` in `.simplecov` file.
Should I remove this check or do something else? @rhymes, please help  🙂

**Comment by nadiyaka** [comment]
@maestromac, can I open a pull request for these changes?

**Comment by maestromac** [comment]
yes please go ahead @nadiyaka !
