### ISSUE TITLE
Add ability to set favicon through environment variable

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/dev.to#4659]
For generalization of the platform, technical administrators should be able to provide a URL to a custom favicon of their choice.

We currently use `favicon_link_tag` with no arguments, meaning it defaults to this...

`<link href="/assets/favicon.ico" rel="shortcut icon" type="image/x-icon" />`

That method can take an argument and we should change this so it takes a URL (and we don't need to use the helper if it's at all difficult.)

This is similar to how we allow the site's `<%= ApplicationConfig["MAIN_SOCIAL_IMAGE"] %>` to be set via environment variable.

**Comment by nadiyaka** [comment]
I would like to work on this issue, but have some questions:
1) Where exactly do I need to change `favicon_link_tag`? I found it in 3 files: `layouts/application.html.erb`, `layouts/internal.html.erb` and `pages/shecoded.html.erb`. Should I change it in all 3 of them?
2) Is it correct that I have to add ENV variable (`ApplicationConfig["FAVICON_URL"]` for example) and add it as an argument to favicon_link_tag?

**Comment by benhalpern** [comment]
@nadiyaka yes and yes.
