### ISSUE TITLE
Add ability to set the app site email through environment variable.

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/dev.to#4660]
Currently `yo@dev.to` is hardcoded into the app a bunch. We should change this to an environment variable such as `DEFAULT_SITE_EMAIL`.

This is for app generalization and this should likely _not_ be changed anywhere where the email should logically go to the dev.to staff itself—most notably bug bounties. But anything related to the administration of an alternate hypothetical community should be set at the app level.

**Comment by benhalpern** [comment]
@MohabMohamed wonderful

**Comment by rhymes** [comment]
ah! we have two PRs for this issue :)
