### ISSUE TITLE
Add loading="lazy" to all liquid iframes

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/dev.to#4671]
[Native lazy loading](https://dev.to/yashints/native-lazy-loading-is-landed-in-chrome-2kli) is a thing for iframes and images. We went in and added it to a bunch of images, but not yet for iframes.

Any iframes we use should have this attribute added, as all of them qualify as valid for lazy loading in order to help the user experience.

Some tests may need to be updated.

**Comment by rhymes** [comment]
+1

hopefully this gets added to Firefox as well [soon](https://bugzilla.mozilla.org/show_bug.cgi?id=1542784)

**Comment by nickytonline** [comment]
Just popping this here for reference for whoever comes to grab this. https://addyosmani.com/blog/lazy-loading/
