### ISSUE TITLE
Less tedious way to unfollow tags from Dashboard > Following

### ISSUE THREAD

**Issue by vgrovestine** [thepracticaldev/dev.to#4674]
**Is your feature request related to a problem? Please describe.**

The present workflow for unfollowing tags via Dashboard > Following is tedious. 

1. Click tag keyword (Link, but looks like regular text. If not for the cursor change, one would never know this text can be clicked.)
2. View tag's thread page.
3. Click "Following" button at top of the page. (It's not clear that this is an actionable item.)
4. Go back to Dashboard > Following.
5. Rinse & repeat.

**Describe the solution you'd like**

Consider adding an "Unfollow" button to each tag listed on the Dashboard > Following page. (Yes, one can use negative weights to bury unwanted tags; however, this isn't the same as unfollowing.)

**Describe alternatives you've considered**

Similar to #1856 re ignoring/blacklisting tags.

**Additional context**

n/a

**Comment by jessleenyc** [comment]
Thanks for the request, this makes a lot of sense. I know someone was working mass unfollow for users shown on the dashboard as well (https://github.com/thepracticaldev/dev.to/issues/3305)
