### ISSUE TITLE
Like value decreases on multiple clicks can go to negative

### ISSUE THREAD

**Issue by RAJAT--PALIWAL** [thepracticaldev/dev.to#4680]
**Clicking multiple time on like button can lead to decreasing number of likes**

Like button, if pressed multiple times continuously, decreases number of likes in view (On reload correct value is displayed). 

**To Reproduce**

 1. Go to 'welcome thread' 
 2. Click on 'like button' multiple time 
 3. Look at value of likes, it keeps decreasing goes to negative too.

**Expected behavior**

Like value should not go below 0, Each click should only increase or decrease value. 

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version: 78.0.3904.70 (Official Build) (64-bit)
![issue_1](https://user-images.githubusercontent.com/8525934/68006220-df6c6a00-fc9d-11e9-887a-bdae2c57d946.png)
![issue_2](https://user-images.githubusercontent.com/8525934/68006221-df6c6a00-fc9d-11e9-8fad-bb73c372850d.png)

**Comment by rhymes** [comment]
@RAJAT--PALIWAL thanks for this! Definitely a bug. 

Can you sistematically reproduce it? If so, could you share a screen recording?

**Comment by RAJAT--PALIWAL** [comment]
[Like_bug.zip](https://github.com/thepracticaldev/dev.to/files/3797589/Like_bug.zip)

**Comment by rhymes** [comment]
Thank you very much for the video, I watched it and yeah, that shouldn't happen! Very helpful

**Comment by shaneblackburn** [comment]
@rhymes Is this issue still up for grabs? I believe I have a fix

**Comment by rhymes** [comment]
@shaneblackburn definitely! Thank you!
