### ISSUE TITLE
Profile showcased repository stars not updating

### ISSUE THREAD

**Issue by AlbertoMontalesi** [thepracticaldev/dev.to#4698]
I've added two repos to my profile but they don't get updated. The number if stars remains the same as when I've added them. Might be worth refreshing the number of stars once a week or something.

**Comment by rhymes** [comment]
Hi @AlbertoMontalesi, unfortunately it's a known issue, there's an older one here: https://github.com/thepracticaldev/dev.to/issues/212

I'm going to close this as a duplicate.
