### ISSUE TITLE
Feed should sort by the newest article first, always

### ISSUE THREAD

**Issue by dennislwm** [thepracticaldev/dev.to#4702]
**Describe the bug**

Feed can sometimes place the a newer article later than older articles. 

It is quite inconvenient to scroll past some older articles to find newer articles.

**To Reproduce**

1. Go to Feed
2. Scroll down to see some articles that have newer dates appearing after older articles.

**Expected behavior**

The newest article should always be at the top of the user feed.

**Screenshots**

Screenshot: (Nov 3rd article appears after Nov 2nd article)
https://snipboard.io/9XZBT2.jpg

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- Browser: Chrome
- Version: 78.0.3904.70 (Official Build) (64-bit)

**Additional context**

An added feature, that could be useful between visits, is to place a horizontal line divider after the latest articles (not seen since the last user visit).

**Comment by rhymes** [comment]
Why not use https://dev.to/latest to access articles in a chronological order?

**Comment by dennislwm** [comment]
> Why not use https://dev.to/latest to access articles in a chronological order?

My assumption is that unlike your Feed, Latest will show you all articles, which may not be in your tagged follows. Maybe someone can confirm this?

**Comment by rhymes** [comment]
@dennislwm yeah, latest is all articles ordered by publication date. This the [algorithm behind the feed](https://docs.dev.to/getting-started/architecture/#the-algorithm-behind-the-feed):

> The home feed is based on a combination of collective recent posts that are cached and delivered the same to everyone in the HTML, and additional articles fetched from an Algolia index after page load. To determine which posts a user sees, they are ranked based on the user's followed tags, followed users, and relative weights for each tag. Additional fetched articles also follow this general pattern.

> Currently, the top post on the home feed, which must have a cover image, is shared among all users.

**Comment by mstruve** [comment]
Since we have a way to sort by latest articles I am going to close this for now. As we add more advanced filter capabilities I think this will become a non-issue as people will be able to search for articles in published at ranges.
