### ISSUE TITLE
GitPod states Ruby version is out of date even though repo has been updated

### ISSUE THREAD

**Issue by sau226** [thepracticaldev/dev.to#4703]
**Describe the bug**
GitPod is using an outdated version of Ruby even though .ruby.version has been bumped

**To Reproduce**

1. Go to https://docs.dev.to/installation/gitpod
2. Click on the GitPod open button to open up a new workspace
3. Fill out your development keys and press a random key when prompted

**Expected behavior**

Packages set up and Gitpod dev.to instance appears

**Problem behavior**

Error is displayed about Ruby version being out of date (version 2.6.3 is used but 2.6.5 is defined in the Gemfile)

**Desktop:**

N/A

**Smartphone:**

N/A

**Additional context**

According to https://www.gitpod.io/docs/42_config_docker, GitPod only rebuilds images on a Dockerfile change.

**Comment by nickytonline** [comment]
Running `rvm install 2.6.5` from the command line in GitPod should fix the issue. I had to do this the other day. There were some other steps to get it to take v. 2.6.5 which I don’t remember, but I basically followed the messages from rvm to get it to take it.

It would be nice if it was automatic.

**Comment by rhymes** [comment]
@sau226 would your proposed solution mean that each time we make a change we have to bump the date in the GitPod dockerfile? Isn't there a more permament option?

**Comment by sau226** [comment]
@rhymes 

1. The date would not have to be bumped each time a change would be made (unless the contributor wanted it to be reflected immediately in GitPod). Say every week or so, as part of other changes the date gets bumped in order for the changes to be reflected in GitPod.

2. From my understanding of the GitPod docs, the only option appears to be to change the Dockerfile. Unless there's a solution I'm unaware of, changing a date once per week or so to reflect that week's changes and provide a way for users to check which week's code they are running is the only option.

**Comment by maestromac** [comment]
Thank you for pointing this out and submitting a fix @sau226 

Cc @jankeromnes do you have a recommended course of action for this issue?

**Comment by 32leaves** [comment]
There was an issue with the `gitpod/workspace-full` where we wouldn't pull the right environment variables. This is fixed in the meantime. We'll trigger image re-builds tomorrow.

Alternatively, you could also trigger an image rebuild by modifying the [.gitpod.dockerfile](https://github.com/thepracticaldev/dev.to/blob/master/.gitpod.dockerfile).

**Comment by maestromac** [comment]
Ah I see. Thanks @32leaves !
