### ISSUE TITLE
500 Error It's not you, it's me.

### ISSUE THREAD

**Issue by dharmiktank** [thepracticaldev/dev.to#4717]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
@dharmiktank what led you to a 500 error? which page? what action were you trying to do?

**Comment by maestromac** [comment]
Hello @dharmiktank , this looks an issue specific to your account. Please email yo@dev.to for more help.
