### ISSUE TITLE
Add global DB settings in addition to environment variables

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#4718]
**Is your feature request related to a problem? Please describe.**

Right now we have a growing set of environment variables that will likely increase over time for each step of generalization we make on the platform.

My proposal is to introduce the concept of "database backed setting".

The advantage of a setting over an env variable is that it doesn't require to restart the application processes/servers for a setting to go into effect. 

It would also open the door to feature flagging.

An example of a parameter that should be in the DB instead of in the environment, is the recently proposed [daily rate for following users](https://github.com/thepracticaldev/dev.to/pull/4647). By moving that in the DB, we enable people to change it dynamically and we remove the requirement of having access to the web app servers to change it (in addition to removing the restart requirement)

**Describe the solution you'd like**

1. we add settings in a DB, for example with a `settings` table that has a `name`, `value` and so on.
1. we clearly define (and document) how to decide if a parameterized value should be an environment variable or a DB setting
1. we add both variables and settings to an `/internal` dashboard, viewable to the site admins
1. We remove `sail` from the gem list and its table, that in the current state are both unused

**Describe alternatives you've considered**

We could also use [sail](https://rubygems.org/gems/sail) for this, but we probably don't need an entire gem for a simple feature like this, though we can look at it for inspiration.

**Comment by benhalpern** [comment]
I'd be in favor of this. It seems like where we'd inevitably go for configuration of generalized instances.

I think the big question for me is how do we do this in a way that ensures the best performance. Could we, perhaps, cache the entire serialized config behind one redis key?

Or perhaps even set environment variables themselves upon the changing of this data?

I don't want to overcomplicate this, but this will be an _every request_ query so we might as well try and save those milliseconds.

I've been loyal to the idea of getting Sail in because it does have a good approach and it's built by a community member, but I agree we might want to favor building it ourselves because the initial use case is so basic and it will also give us full control to change it to fit the app's needs in the future.

**Comment by rhymes** [comment]
> I think the big question for me is how do we do this in a way that ensures the best performance. Could we, perhaps, cache the entire serialized config behind one redis key?

@benhalpern that's a possiblity, serialize the table in a JSON blob in redis and rebuild it each time anything gets changed. 

The question is: will it be faster to do the HTTP call to Redis or to read a small table from PostgreSQL? Redis might not be worth it since there's nothing to actually compute in this case, contrary to other reasons why one would cache values. We have to test this.

> the initial use case is so basic and it will also give us full control to change it to fit the app's needs in the future

yeah, that's logic behind the idea of removing the gem. I discussed it a bit with @mstruve and @maestromac 

Building a dashboard to display the various settings and the environment variables shouldn't be too much of an effort as well

**Comment by mstruve** [comment]
100% support this and I think it will make the platform more reproducible and flexible for new communities that may have different uses and settings associated with them.

**Comment by rhymes** [comment]
I know we are leaning towards building this totally in house but I still went ahead and checked if there was a simple solution readily available (also to see if my ideas on how to implement this efficiently had any real world counterpart) and I found one: [rails-settings-cached](https://rubygems.org/gems/rails-settings-cached).

Contrary to [sail](https://rubygems.org/gems/sail) it has 1.5 million downloads and it's openly declared as a [dependency by 1.1k projects on Github](https://github.com/huacnlee/rails-settings-cached/network/dependents?package_id=UGFja2FnZS0xNDA0MDM%3D), among them [helpy](https://github.com/helpyio/helpy) and [mastodon](https://github.com/tootsuite/mastodon).

Aside from its popularity the reasons why I'm considering this gem are the following:

- it's more or less implemented like I would have done it:
  - a basic key/value table
  - some Ruby magic to define global fields (allowing the user to do stuff like `Setting.rate_limit_daily_follow_count = 500`)
  - a double layer of caching like we discussed: it reads from the DB only once, stores the settings in the Rails cache and in thread safe object in memory. When accessed it looks in memory, otherwise in the cache
- the implementation is contained in one file of 130 lines: https://github.com/huacnlee/rails-settings-cached/blob/master/lib/rails-settings/base.rb - as a model base object our model will inherit from
- it doesn't try to be anything else: no feature flags, no A/B testing, no tracking of settings usage frequency or a full fledged admin panel like `sail` does

The only thing I would have done differently is I would I have used a JSONB column in PostgreSQL to contain the values, instead of a string serialized with YAML but I don't see it as a blocker.

This is an example session with it:

```ruby
[1] pry(main)> Rails.cache.read(Setting.cache_key) 
=> nil
[2] pry(main)> RequestStore.store[:rails_settings_all_settings] # the thread safe object in memory
=> nil
[3] pry(main)> Setting.notification_options # the first time you load any setting, it reads them all in memory
  Setting Load (3.9ms)  SELECT var, value FROM "settings"
=> {"this"=>true, "that"=>false, "any"=>"thing"}
[4] pry(main)> RequestStore.store[:rails_settings_all_settings] # now the memory cache contains the settings
=> {"host"=>"foobar", "default_locale"=>"it", "notification_options"=>{"this"=>true, "that"=>false, "any"=>"thing"}}
[5] pry(main)> Rails.cache.read(Setting.cache_key) # also the Rails cache contains the settings
=> {"host"=>"foobar", "default_locale"=>"it", "notification_options"=>{"this"=>true, "that"=>false, "any"=>"thing"}}
[6] pry(main)> Setting.notification_options # the second time it reads from memory, bypassing the DB
=> {"this"=>true, "that"=>false, "any"=>"thing"}
```

and when you modify the setting:

```ruby
[17] pry(main)> Setting.notification_options = {"yo": "raps"} # updates the DB with the new setting
  Setting Load (1.1ms)  SELECT  "settings".* FROM "settings" WHERE "settings"."var" = $1 LIMIT $2  [["var", "notification_options"], ["LIMIT", 1]]
   (0.1ms)  BEGIN
  Setting Update (0.4ms)  UPDATE "settings" SET "value" = $1, "updated_at" = $2 WHERE "settings"."id" = $3  [["value", "---\n:yo: raps\n"], ["updated_at", "2019-11-05 12:21:41.594388"], ["id", 3]]
   (0.4ms)  COMMIT
=> {:yo=>"raps"}
[18] pry(main)> RequestStore.store[:rails_settings_all_settings] # memory cache is emptied
=> nil
[19] pry(main)> Rails.cache.read(Setting.cache_key) # rails cache is emptied
=> nil
[20] pry(main)> Setting.host # load a totally different setting
  Setting Load (0.6ms)  SELECT var, value FROM "settings"
=> "foobar"
[21] pry(main)> RequestStore.store[:rails_settings_all_settings] # memory cache contains all settings
=> {"host"=>"foobar", "default_locale"=>"it", "notification_options"=>{"yo"=>"raps"}}
[22] pry(main)> Rails.cache.read(Setting.cache_key) # same as the rails cache
=> {"host"=>"foobar", "default_locale"=>"it", "notification_options"=>{"yo"=>"raps"}}
```

This is how the model allowing me the above session is configured:

```ruby
class Setting < RailsSettings::Base
  cache_prefix { "v1" }

  # Define your fields
  field :host, type: :string, default: "http://localhost:3000"
  field :default_locale, default: "en", type: :string
  field :notification_options, type: :hash, default: { "this": true, that: false, any: "thing" }
end
```

For this reason I'm considering using this gem, if we ever need to diverge wildly from how it works we would still have options and in the worst case scenario we can just stop using the gem and incorporate the base model

Let me know what you all think about this idea, or if it's better I reimplement it internally from scratch

**Comment by benhalpern** [comment]
@rhymes I agree with all this logic. Looks great to me. I definitely trust your judgment if you want to go down this path.

**Comment by jessleenyc** [comment]
Done!
