### ISSUE TITLE
Mod tooling: add tags via /mod

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#4720]
**Is your feature request related to a problem? Please describe.**
As a mod, I'd like to be able to add appropriate tags to a post.

**Describe the solution you'd like**
Via `/mod`, near the "remove tag" functionality, a new area where I can **add** tags.  The author should get a (kind) notification explaining what happened.

**Additional context**
This will help with proper tagging throughout the site.

Might be some considerations around people re-tagging previously removed tags, but that could be a complication not worth thinking about.

**Comment by twinsfan421** [comment]
I can work on this.

**Comment by twinsfan421** [comment]
#4750
