### ISSUE TITLE
Allow JSitor Tag to accept Full URL and parameters

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/dev.to#4734]
Continuing the conversation from #4657, we'd like the JSitor Liquid tag to be able to accept the full URL, as well as any additional URL parameters. For example: `https://jsitor.com/embed/1QgJVmCam?html&js&css&result&light&consoleOnly&`

We'll need to extract the ID from that link, as well as the `html`, `js`, `css`, `result`, `light` and `consoleOnly` parameters. Once extracted, the HTML file should have those parameters inserted back in. Alternatively, we can simply validate the given URL and its parameters and place it back in, but we'll need to watch out for any sanitization that might happen in the process.

I think we'll want the final use case look like this:
```
{% jsitor https://jsitor.com/embed/1QgJVmCam?html&js&css&result&light&consoleOnly& %}
#=> renders the liquid tag properly
```

**Comment by Zhao-Andy** [comment]
@artoodeeto here's the issue. :)

**Comment by artoodeeto** [comment]
@Zhao-Andy  thank you for this. I'll work on this maybe this weekend, but ill let you know how would I approach this. 

Im tagging @ashvin777 so he can participate and check. :smile:

**Comment by ashvin777** [comment]
Either the whole URL
{% jsitor https://jsitor.com/embed/1QgJVmCam?html&js&css&result&light&consoleOnly& %}

 or just 

{% jsitor 1QgJVmCam?html&js&css&result&light&consoleOnly& %}

or maybe

{% jsitor 1QgJVmCam html&js&css&result&light&consoleOnly& %}

**Comment by artoodeeto** [comment]
@ashvin777 I was thinking of the second one so I could just check if theres an `http` or other links being embedded.

**Comment by Zhao-Andy** [comment]
@artoodeeto actually if you could change it so it can accept a full URL that'd be great. We're looking to eventually make this change on every Liquid tag that can accept a link, and this will be the first step of that process. :)

**Comment by artoodeeto** [comment]
@Zhao-Andy okies. no problem. will be working on this right now. :)
