### ISSUE TITLE
i cant share a new post im getting 500 err.

### ISSUE THREAD

**Issue by omgbbqhaxx** [thepracticaldev/dev.to#4760]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by jessleenyc** [comment]
Sorry about that! This seems like an individual account issue. Can you please send an email from the address associated with your DEV account to yo@dev.to?
