### ISSUE TITLE
GitPitch Liquid Tags

### ISSUE THREAD

**Issue by JaredHarbison** [thepracticaldev/dev.to#4761]
**Is your feature request related to a problem? Please describe.**

No, not necessarily a problem... but I'd like to be able to more easily embed slideshow presentations in my DEV posts through liquid tags for GitPitch. Currently liquid tags are available for SpeakerDeck but you have to create the presentation through powerpoint or google docs, upload it to SpeakerDeck, then embed that into DEV with the liquid tag.

**Describe the solution you'd like**

Since nearly all of us use Github I think the following would be ideal...
- create the slideshow with GitPitch using markdown, etc
- embed the slideshow with the liquid tag

**Describe alternatives you've considered**

Embedding from google would work... 
Perhaps straight from Microsofts online apps... 
... but GitPitch would be ideal.

**Additional context**

**Comment by jessleenyc** [comment]
Cool, this is approved for anyone that wants to take it on. Here's the documentation on liquid tags: https://docs.dev.to/frontend/liquid-tags/

**Comment by Aswathprabhu** [comment]
Can I take this? @jessleenyc

**Comment by JaredHarbison** [comment]
Hi Jess!

I submitted the resolution for this last week. I'm happy to take another
pass at it if you like. But it worked on my machine! 😂

Best,
Jared Harbison

**Comment by maestromac** [comment]
Ah we missed it, thanks for pointing that out @JaredHarbison

**Comment by JaredHarbison** [comment]
NP! I did notice the Travis CI check failed, but seemed unrelated.

For ref => Add GitPitchTag resolves #4761 #4942

Best, Jared Harbison
