### ISSUE TITLE
Broken layout while editing post in "Additional Config/Settings" section

### ISSUE THREAD

**Issue by anuraghazra** [thepracticaldev/dev.to#4764]
**Describe the bug**
When editing the "Additional Config/Settings" section, clicking the "preview" button breaks the layout.

**To Reproduce**

1. Go to any of your post and hit edit 
2. Go to "Additional Config/Settings"
3. Click the "preview" button

**Expected behavior**
Layout should not break.

**Screenshots (video)**

**Here's the Youtube video** : https://youtu.be/-hQNb5Soumk

In chrome:

![image](https://user-images.githubusercontent.com/35374649/68540497-1a1a8480-03b9-11ea-94c7-148f8073f5c9.png)

In firefox:

![image](https://user-images.githubusercontent.com/35374649/68540517-741b4a00-03b9-11ea-8863-e667fa275882.png)

**Desktop (please complete the following information):**

- OS: windows 7 64bit
- Browser: Chrome 
- Version: Latest

**Smartphone (please complete the following information):**

- Device: N/A
- OS: N/A
- Browser: N/A
- Version: N/A

**Additional context**

**Comment by jessleenyc** [comment]
Good catch. If someone clicks the preview button, we should probably show the preview and close the settings overlay/modal. Similarly to how the editor guide button behaves in that scenario.
