### ISSUE TITLE
Footer not centered in podcasts

### ISSUE THREAD

**Issue by charbelsako** [thepracticaldev/dev.to#4768]
**Describe the bug**
When you are on the page of any podcast episode the footer is aligned to the left.

**To Reproduce**
Just go to any podcast episode and look at the footer

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: kde neon
- Browser: firefox
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Added a screenshot to help whomever takes this issue:

from https://dev.to/cynicaldeveloper/episode-127-automation-leading-us-astray-percona-live-europer-2019

![Screenshot_2019-11-11 Podcasts on The Practical Dev](https://user-images.githubusercontent.com/146201/68579902-86f35480-0475-11ea-8309-a1b68db99608.png)

**Comment by JacobMGEvans** [comment]
This might be a good place to start poking around as well https://github.com/thepracticaldev/dev.to/tree/master/app/views/podcast_episodes

**Comment by aligoren** [comment]
I think the problem is caused by I think the problem cause of **inner-footer-container**;

```css
footer .container .inner-footer-container {
  margin-left: 0;
}
```

If I remove `margin-left:0`, it works as expected.

**Comment by lornatumuhairwe** [comment]
Let me dig in and open a PR for this. 👍

**Comment by aligoren** [comment]
You can open a pr. If you want to. Btw, be careful because probably it will not work well on article pages.

**Comment by lornatumuhairwe** [comment]
@aligoren thanks for the heads up. I had opened a PR but will add a WIP to get that fixed first.

**Comment by lornatumuhairwe** [comment]
@aligoren all done. Thank you. Now awaiting review.

**Comment by aligoren** [comment]
@lornatumuhairwe 

Congrats :) I hope we will see you much.
