### ISSUE TITLE
Feature Request: How about Adding database.yml to .gitignore ?

### ISSUE THREAD

**Issue by TakaakiFuruse** [thepracticaldev/dev.to#478]
## Feature Request or Task
Adding database.yml to .gitignore and make database.yml.sample.

### User Story / Description
I just set up my own dev.to environment on my PC.

During the setup, I had to edit database.yml to connect to my DB, and now the files is on git diff.
This requires me to be a little bit careful so as not to include database.yml to my commit when I tackle issues. 

So, why not adding the file to gitignore and rename it as database.yml.sample? Volunteer devs might be required to rename a sample file when they setup, but be freed from annoyance of committing database.yml.

### Definition of Done
1) rename database.yml as database.yml.sample
2) add datase.yml to gitgnore
3) rewrite documents

**Comment by rhymes** [comment]
Hi @TakaakiFuruse, that might be an option, but there's another one:

try bypassing `database.yml` with an environment variable, `DATABASE_URL`, inside application.yml (which is already ignored). 

This way you can setup the DB however you wish and leave the default setup as is.

The doc doesn't mention it yet but I know @maestromac is aware of this issue and thinking about the proper solution.

In the meantime I can refer you to this comment I made with the how to: https://github.com/thepracticaldev/dev.to/issues/289#issuecomment-413505561

This will allow the app to stick to using env variables and to you to manage your setup without having a git diff.

**Comment by TakaakiFuruse** [comment]
Thanks @rhymes, 

As you mentioned, I have added

```
DATABASE_URL: postgresql://localhost/PracticalDeveloper_development
```

to my application.yml and seems everything is fine.

**Comment by maestromac** [comment]
This might be the one-size-fit-all solution we need to account for different dev machines. 

@lightalloy will be implementing this.
