### ISSUE TITLE
I am not able to Create New POst

### ISSUE THREAD

**Issue by abhigyan709** [thepracticaldev/dev.to#4792]
[

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

[GoApti](https://goapti.in/interview-question-and-answers/)

**Comment by maestromac** [comment]
Hello @abhigyan709 , this looks an issue specific to your account. Please email yo@dev.to for more help.
