### ISSUE TITLE
Make links more distinguishable on "Ten X Hacker" theme

### ISSUE THREAD

**Issue by tcdowney** [thepracticaldev/dev.to#4794]
**Is your feature request related to a problem? Please describe.**

It's currently pretty difficult to tell what is and isn't a link on the "Ten X Hacker" theme.

![Screen Shot 2019-11-11 at 10 30 53 PM](https://user-images.githubusercontent.com/2096955/68647634-3f031a80-04d3-11ea-80e8-a5da03f611c5.png)

There are four links in the text above!

**Describe the solution you'd like**

It would be nice if the links were easier to spot. I made them hacker pink for the heck of it here, but really any color (I noticed that some links are white in this theme, that could work) that is sufficiently different would be appreciated.

![Screen Shot 2019-11-11 at 10 30 35 PM](https://user-images.githubusercontent.com/2096955/68647533-f3507100-04d2-11ea-8af8-cce0ddd3b94e.png)

**Describe alternatives you've considered**

You could also tack on a link icon or something to help signify them.
* https://fontawesome.com/icons/external-link?style=solid
* https://fontawesome.com/icons/link?style=solid

I think just a different color would be fine, though.

**Additional context**
I like this theme. 😌🤙

![Hack the planet!](https://media.giphy.com/media/3FQ87l4tXAZWGvV3yY/giphy.gif)

**Comment by ndom91** [comment]
+1 love this theme, however links are usually indistinguishable which is annoying.. 

I'll take a look at this when i get home tonight and try to make a PR 👍🏾

**Comment by jessleenyc** [comment]
I like the pink!

**Comment by ndom91** [comment]
Okay so I made a basic PR, just changing the css custom property for `--theme-anchor-color` to a pink hue like the one the OP requested (`#e24ec1`). 

If you'd like another pink or want to expand upon the anchor styling, i.e. not just color change, but also maybe underline on hover, etc., etc. - feel free to edit the PR!

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/4836
