### ISSUE TITLE
Write tests for Users::DeleteActivity

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#4795]
As @mstruve  described in her comment https://github.com/thepracticaldev/dev.to/pull/4480#discussion_r344764065 , it would be nice to have a test that would validate that every related record is deleted when a user record is deleted.
If we add other relations to the `User` model it will be easy to forget to add a step to delete it. Having such a test would prevent it.

**Comment by artfullyContrived** [comment]
@lightalloy Is this what we want to achieve?

```
User.has_many_relationships.each do |association|
  associated_object = association.create(user: user)
  Users::DeleteActivity.call(user)
  expect_associated_object_to_have_been_deleted
end
```

**Comment by rhymes** [comment]
Adding this info for whomever take this on: 

```ruby
> User.reflect_on_all_associations
...
 #<ActiveRecord::Reflection::HasManyReflection:0x00007fb4eb5af2d8
  @active_record=User (call 'User.connection' to establish a connection),
  @association_scope_cache=#<Concurrent::Map:0x00007fb4eb5b7e38 entries=0 default_proc=nil>,
  @constructable=true,
  @foreign_type=nil,
  @klass=nil,
  @name=:user_blocks,
  @options={},
  @plural_name="user_blocks",
  @scope=nil,
  @type=nil>,
 #<ActiveRecord::Reflection::HasOneReflection:0x00007fb4ec4bf228
  @active_record=User (call 'User.connection' to establish a connection),
  @association_scope_cache=#<Concurrent::Map:0x00007fb4ec4bf098 entries=0 default_proc=nil>,
  @constructable=true,
  @foreign_type=nil,
  @klass=nil,
  @name=:pro_membership,
  @options={:dependent=>:destroy},
  @plural_name="pro_memberships",
  @scope=nil,
  @type=nil>]
```

from https://api.rubyonrails.org/classes/ActiveRecord/Reflection/ClassMethods.html

this and other "reflection" methods should help :)

**Comment by lightalloy** [comment]
@artfullyContrived something similar to that. I would probably call deletion once to make the test faster.

**Comment by artfullyContrived** [comment]
@lightalloy I'm not sure how this test would be structured since not all related objects are deleted by this service. Additionally, 2/3 callers of this method eventually call `user.delete` which ends up deleting all `dependent: :destroy` relationships

**Comment by lightalloy** [comment]
I worked for a while on this issue and created a related pr #5624 
@anthonyms you made a valid point that not all deleted by `DeleteActivity`. I ended up writing a more general test for `Users::Delete` to achieve a similar goal. The task overall turned out more challenging than I initially thought, I described steps that I need to take to write it and related issues in the attached pr.

**Comment by lightalloy** [comment]
Though the tests for exactly `Users::DeleteActivity` were not written the goal was achieved by writing a more high-level test in #5624, so I'm closing this one.
