### ISSUE TITLE
Improve javascript in app/views/users/_account.html.erb 

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#4796]
Possible improvements are listed in the comments to this pr:
https://github.com/thepracticaldev/dev.to/pull/4480#discussion_r343698671

**Comment by sai-chai** [comment]
I'll take this one. 🙋🏽‍♂️

**Comment by rhymes** [comment]
Go ahead @sai-chai, thank you!

**Comment by sai-chai** [comment]
Sorry I got busy recently and wasn't able to follow through, but it looks like this issue can now be closed. It seems like all the issues pointed out in #4480 have been addressed in the code (it's now been broken out into app/views/users/confirm_destroy.html.erb @ line 35).

**Comment by rhymes** [comment]
Correct! thanks for the heads up @sai-chai!
