### ISSUE TITLE
Markdown Preview for Comments

### ISSUE THREAD

**Issue by elijah-schow** [thepracticaldev/dev.to#48]
As someone writing a comment, I would like to see a preview of my comment before posting.

#### Side-by-side Live Preview
![dev to-comment-preview_side by side](https://user-images.githubusercontent.com/17830432/27138977-69c7e784-50e7-11e7-9088-dd5b2293230f.png)

#### Tabs
![dev to-comment-preview_tabbed](https://user-images.githubusercontent.com/17830432/27138978-69c95dc6-50e7-11e7-9cea-701c7ff86889.png)

#### Button
![dev to-comment-preview_button](https://user-images.githubusercontent.com/17830432/27138976-69c5808e-50e7-11e7-9012-910f65429646.png)

**Comment by benhalpern** [comment]
Good suggestion, thanks!

**Comment by GonzalezAnguita** [comment]
I would say that the **Side-by-side Live Preview** is a more usable approach. The only problem there would be on mobile, but i believe content-makers don't write much using their phones so for mobile should be hidden.

**Comment by Zhao-Andy** [comment]
Hey y'all! We have this live now :) We decided to go with a button.

See this post for more details: [dev.to #changelog - Comment Preview](https://dev.to/devteam/changelog-comment-preview-2jgj)
