### ISSUE TITLE
Supply Password Error while running bin/setup

### ISSUE THREAD

**Issue by atithiapp** [thepracticaldev/dev.to#480]
## Feature Request or Task
run repository locally
### User Story / Description
Could not locate Gemfile
### Definition of Done

installed  all the pre-requisites
```
> Ruby: we recommend using rbenv to install the Ruby version listed on the badge.
> Yarn: please refer to their installation guide.
> PostgreSQL 9.4 or higher.
```
foked the repo the ran command like this
```
gem install bundler
gem install foreman
bundle install

```
it returned   `Could not locate Gemfile`
![screenshot from 2018-08-25 18-24-32](https://user-images.githubusercontent.com/42513360/44618480-3acdeb80-a894-11e8-9870-b51c2ec91879.png)
![screenshot from 2018-08-25 18-22-58](https://user-images.githubusercontent.com/42513360/44618483-41f4f980-a894-11e8-8b75-6f745a3e59be.png)

**Comment by rhymes** [comment]
You're running `bundle install` from a folder named `rubygems-2.7.7` not dev.to's checkout folder.

Also: you don't need to `sudo` gem install bundler and foreman. A normal gem install will do just find.

Just go to your dev.to checkout folder and retry

**Comment by atithiapp** [comment]
Matter resolved. Thank you for swift reply rhymes.

**Comment by atithiapp** [comment]
@rhymes 

We did resolve that matter now, trying to locate where we need to supply password for 'root' so that it write and create database. Error is explained below:
Note: This error occurred while running  **bin/setup**

```
Created database 'PracticalDeveloper_development'
fe_sendauth: no password supplied
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "connect_timeout"=>2, "checkout_timeout"=>2, "variables"=>{"statement_timeout"=>2500}, "host"=>"localhost", "database"=>"PracticalDeveloper_test"}
rails aborted!

```

![screenshot from 2018-08-25 19-45-04](https://user-images.githubusercontent.com/42513360/44619144-64404480-a89f-11e8-8c0d-b7423353adc3.png)

**Comment by Zhao-Andy** [comment]
Hey @atithiapp, please see our docs for more info:
https://docs.dev.to/additional-postgres-setup/

More specifically:
> If your Rails app is unable to connect to the PostgreSQL, then update your database.yml file with `username` and `password`.

I think the solution posted there should solve your issues. Let us know how it goes!

**Comment by atithiapp** [comment]
Thank you. What are the prerequisites for the deployment on the server? Is there any automated process? Or do we need to repeat the processes preformed on local host server ?

**Comment by Zhao-Andy** [comment]
@atithiapp Not exactly sure what you're asking, but if you mean running the localhost server you should be able to run `bin/rails server` after installing all prerequisites. See out installation guide for more detailed steps:
https://docs.dev.to/installation/linux/

**Comment by atithiapp** [comment]
i have ran the dev.to repo successfully in my local machine. now i want to run it to my cloud server?
1. do i need to repeat the exact process in my cloud server as i have done in my local ?.
2.  or there is any command like bin/deploy to automatically deploy the production version in the cloud sever.
3. OR if you could help me with deployment guide.
4. if i do some local changes so how to update in my production server?

**Comment by atithiapp** [comment]
Sir ?

**Comment by msarit** [comment]
Could this issue be closed then? 😄

**Comment by atithiapp** [comment]
no i am getting this error in production
when i ran
RAILS_ENV=production bin/setup --trace
```
== Preparing database ==
rails aborted!
NoMethodError: undefined method `reject' for #<String:0x000055b6012d9cb0>
/root/dev.to/config/application.rb:14:in `<module:PracticalDeveloper>'
/root/dev.to/config/application.rb:13:in `<top (required)>'
/root/dev.to/Rakefile:4:in `require'
/root/dev.to/Rakefile:4:in `<top (required)>'
/root/dev.to/bin/rails:9:in `require'
/root/dev.to/bin/rails:9:in `<top (required)>'
/root/dev.to/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
(See full trace by running task with --trace)

== Command ["bin/rails db:setup"] failed ==
root@forum-rizwan:~/dev.to# 
```

**Comment by rhymes** [comment]
@atithiapp this sounds like a diffent issue, you should close this one and then open a different one :D

**Comment by Zhao-Andy** [comment]
Closing since @atithiapp made a new issue.
