### ISSUE TITLE
JSitor liquid tag does not support id with '-' character

### ISSUE THREAD

**Issue by ashvin777** [thepracticaldev/dev.to#4823]
**Describe the bug**
This `{% jsitor 2o-syYxmi %}` is a valid id `https://jsitor.com/2o-syYxmi` and should embed the content. However while adding that in blog, it throws the below error -
![image](https://user-images.githubusercontent.com/8143154/68889678-66601e80-0743-11ea-881f-ceb934566f7d.png)

**To Reproduce**
Try `{% jsitor 2o-syYxmi %}`

**Expected behavior**

It should allow id with '-'

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by Zhao-Andy** [comment]
I believe we'll want to update the regex to allow the dash `-`:

https://github.com/thepracticaldev/dev.to/blob/2ca23c89831726c721b11c2ca863699fbe3014f4/app/liquid_tags/jsitor_tag.rb#L3-L4

**Comment by helmihidzir** [comment]
Hello @Zhao-Andy , I would like to try this one.
