### ISSUE TITLE
500 Error It's not you, it's me.

### ISSUE THREAD

**Issue by decipherzonesoft** [thepracticaldev/dev.to#4835]
500 Error
It's not you, it's me.

Sorry, you're hitting this page.
Please help us by submitting a bug report.
Thank you!

I am trying to write a new post.

![dev](https://user-images.githubusercontent.com/57699686/68992174-1a6dc080-088e-11ea-9782-0be8c71194c2.jpeg)

**Comment by jessleenyc** [comment]
Hi @decipherzonesoft! This looks like an individual account issue. Please email yo@dev.to with the email address associated with your DEV account and our support team will get back to you.
