### ISSUE TITLE
Unable to change twitter handle

### ISSUE THREAD

**Issue by bobbyiliev** [thepracticaldev/dev.to#4837]
**Describe the bug**
I signed up with Twitter, but I changed my twitter handled, now my twitter handled in dev.to is wrong

**To Reproduce**

1. Sign up with Twitter
2. Change your twitter handle
3. The change is not reflected on the dev.to site and you can not change your twitter handle via settings

**Expected behavior**
I think that it would be good to allow people to change twitter handle

**Comment by jessleenyc** [comment]
@bobbyiliev sorry about this -- can you email yo@dev.to with the email address associated with your DEV account? Our support team should be able to update this for you.
