### ISSUE TITLE
https://www.youtube.com/watch?v=TG6Qw7PnYCE

### ISSUE THREAD

**Issue by siddharth018** [thepracticaldev/dev.to#4840]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
closing for spam
