### ISSUE TITLE
My account marked as Spam

### ISSUE THREAD

**Issue by theeducationmag** [thepracticaldev/dev.to#4855]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by jessleenyc** [comment]
Hey! Sorry about that, can you email yo@dev.to from the email address associated with your DEV account? Someone from our support team can help you there. Thank you!

**Comment by empeje** [comment]
Hi @jessleenyc, I have encountered the same problem here, already contacted the team but no answer so far. Could you please help?
