### ISSUE TITLE
Signed in as ppezaris, I receive a 500 server error when clicking Organization

### ISSUE THREAD

**Issue by ppezaris** [thepracticaldev/dev.to#4857]
Signed in as ppezaris, I receive a 500 server error when clicking Organization

1. Sign in as ppezaris
2. Click headshot in top right corner, select Settings
3. Click Organization

To see a web page

![image](https://user-images.githubusercontent.com/1483024/69081772-b6253b00-0a0c-11ea-891b-decdea606bdc.png)

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by Zhao-Andy** [comment]
Hey @ppezaris, sorry about that issue! I believe I fixed this for your specific case. Could you confirm if this still happens for you?

**Comment by ppezaris** [comment]
Yes, it's fixed. Thank you!
