### ISSUE TITLE
Consider adding social share links to the Events page

### ISSUE THREAD

**Issue by nickytonline** [thepracticaldev/dev.to#486]
### User Story / Description

As a user, I want to have social share link buttons on the Events page, so that I can share an event more easily. Currently, it involves copying the event's page link and then pasting it in a Tweet.

### Definition of Done

When a user navigates to an events page, there should be social share links like on blog posts on dev.to. (The report abuse link would not be present as the events are sanctioned by dev.to staff)

![image](https://user-images.githubusercontent.com/833231/44637116-6547a380-a97d-11e8-90b9-3a417b674935.png)

-------

### Mobile & Desktop Screenshots/Recordings

![image](https://user-images.githubusercontent.com/833231/44637099-5103a680-a97d-11e8-9d1d-2dfff9882f5a.png)

**Comment by jessleenyc** [comment]
This makes sense. We never went past the MVP version of /events and we'll def want something like this when we revisit the way it's designed. Any additional thoughts on events is super welcomed.
