### ISSUE TITLE
500 error when creating a post

### ISSUE THREAD

**Issue by hsnamr** [thepracticaldev/dev.to#4860]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device: iPhone SE
- OS: iOS 13.3 public beta
- Browser: Safari
- Version:

**Additional context**

**Comment by maestromac** [comment]
Hello @hsnamr , this looks an issue specific to your account. Please email yo@dev.to for more help.
