### ISSUE TITLE
Refactor raise_error expectations

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#4862]
There are several expectations in tests like this, which leads to warnings:
`expect { }.not_to raise_error(SpecificErrorClass)` risks false positives, since literally any other error would cause the expectation to pass, including those raised by Ruby (e.g. NoMethodError, NameError and ArgumentError), meaning the code you are intending to test may not even get reached. Instead consider using `expect { }.not_to raise_error` or `expect { }.to raise_error(DifferentSpecificErrorClass)`.
These warnings should be fixed accordingly to the message.

**Comment by sibis** [comment]
@lightalloy I would like to work on this issue.

**Comment by lightalloy** [comment]
All the cases like these were fixed, so I'm closing the issue.
