### ISSUE TITLE
Add to Calendar Bug

### ISSUE THREAD

**Issue by spkjess** [thepracticaldev/dev.to#487]
### Current Behavior
1. Click "Add to calendar" on  https://dev.to/events/24-workshop-engineering-diversity-08-28-2018
2. Choose Google
3. Display error "429. Plan Exceeded.", "The referring website using the "Add to Calendar" service is related to a free Hobby account which has exceeded its monthly limits."

### Expected Behavior
Add to calendar

### Mobile & Desktop Screenshots/Recordings
<img width="1440" alt="screen shot 2018-08-27 at 10 21 40 am" src="https://user-images.githubusercontent.com/13111709/44637343-319f6480-a9e3-11e8-8229-614799754e43.png">

**Comment by Zhao-Andy** [comment]
Hey @spkjess, thanks for the heads up! We'll take a look into it.

**Comment by benhalpern** [comment]
Thanks! Just upgraded our plan.
