### ISSUE TITLE
Consider removing --coverage parameter npm script test:watch

### ISSUE THREAD

**Issue by nickytonline** [thepracticaldev/dev.to#488]
### Description

Currently when running `yarn test:watch`, everytime tests complete, a coverage report is shown. The coverage report is fine when just running `yarn test`, but when writing tests with watch mode, it's a bit annoying because if a test fails, you have to scroll back up pretty far in the terminal.

This is by no means a showstopper, but DX wise, an improvement.

### Definition of Done

The `--coverage` parameter is removed from the `test:watch` npm script.

### Mobile & Desktop Screenshots/Recordings

![debug-annoyance](https://user-images.githubusercontent.com/833231/44637430-100c9180-a97f-11e8-9f70-4ac6146628bc.gif)

**Comment by maestromac** [comment]
That does get pretty annoying. Thanks for bringing this up and changing it!

#489 resolved this.
