### ISSUE TITLE
Flaky user_visits_articles_by_tag_spec 

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#4890]
Related to #4884 

```
1) User visits articles by tag when user has logged in shows the following button
     Failure/Error: within("h1") { expect(page).to have_button("✓ FOLLOWING") }
       expected to find button "✓ FOLLOWING" that is not disabled within #<Capybara::Node::Element tag="h1" path="/HTML/BODY[1]/DIV[6]/DIV[1]/DIV[1]/DIV[1]/H1[1]"> but there were no matches
     
     [Screenshot]: tmp/screenshots/failures_r_spec_example_groups_user_visits_articles_by_tag_when_user_has_logged_in_shows_the_following_button_735.png
     
     # ./spec/system/articles/user_visits_articles_by_tag_spec.rb:73:in `block (4 levels) in <top (required)>'
     # ./spec/system/articles/user_visits_articles_by_tag_spec.rb:73:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (2 levels) in <top (required)>'
     # ./spec/support/initializers/rspec_retry.rb:8:in `block (2 levels) in <top (required)>'

rspec ./spec/system/comments/user_delete_a_comment_spec.rb:15 # Deleting Comment works
```

**Comment by thealiilman** [comment]
I'd like to tackle this! 🤓

**Comment by mstruve** [comment]
That would be awesome! THANK YOU!!!

**Comment by thealiilman** [comment]
I've not had the time to look into this due to my schedule at the moment.
If anyone else wants to take it, feel free. 🙂

**Comment by imrishabh18** [comment]
Hey, i would like to work on the issue.

**Comment by rhymes** [comment]
@imrishabh18 thank you! I'm going to assign you to the issue :)

**Comment by imrishabh18** [comment]
@rhymes Can you brief me what do i have to do to fix this issue ?

**Comment by rhymes** [comment]
@imrishabh18 the problem with this issue is that it doesn't always happen so I'm not sure how one would go about to fix it either. Were you able to reproduce it?

**Comment by imrishabh18** [comment]
No , i am not able to reproduce it.

**Comment by rhymes** [comment]
I'm going to remove the `good first issue` label but keep it open. Sorry for the confusion @imrishabh18! If you're interested we have a few issues [labeled bug and goog first issue](https://github.com/thepracticaldev/dev.to/issues?q=is%3Aopen+label%3A%22good+first+issue%22+label%3A%22type%3A+bug%22) .

Let us know if you need assistance!

**Comment by rhymes** [comment]
To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by mstruve** [comment]
We have not seen this spec fail for quite a while so we are closing this issue. Will reopen if it pops up again but hopefully, it's been unknowingly fixed 😄
