### ISSUE TITLE
E-mail link is not visible in profile page for night theme

### ISSUE THREAD

**Issue by andreybleme** [thepracticaldev/dev.to#4892]
**Describe the bug**

When using the night mode, my profile e-mail is not visible (poorly visible).

**To Reproduce**

1. Go to Profile
2. Click to edit profile
3. Add an e-mail address
4. Mark the checkbox "Display email on profile"
5. Go to your profile
6. See the almost invisible e-mail link in the header.

**Expected behavior**

E-mail link should be visible.

**Screenshots**

![image](https://user-images.githubusercontent.com/5385383/69470458-88762400-0d75-11ea-9b3a-8df55f936992.png)

**Desktop (please complete the following information):**

- OS:Linux (Ubuntu 16.04)
- Browser: Google Chromium
- Version: 78.0.3904.108

**Additional context**

backgound color: #000000
text color: #ffffff

**Comment by SBagaria2710** [comment]
https://github.com/thepracticaldev/dev.to/issues/4892

**Comment by SBagaria2710** [comment]
I can work on that.

**Comment by rhymes** [comment]
Thanks @SBagaria2710, go ahead! :)

**Comment by abdellani** [comment]
Hi @andreybleme , @jessleenyc 
Is this problem solved? because I'm not getting the same view localy.
![Screenshot_2019-11-28 Mohamed ABDELLANI - DEV(local) Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/16113997/69825426-8eee1b00-120f-11ea-91d6-bcdeca6e9437.png)

**Comment by andreybleme** [comment]
Hi @abdellani, I think this is because of your theme. Good point...

When I reported this issue I haven't realized that it was dark because my theme colors are:

backgound color: #000000
text color: #ffffff

**Comment by rhymes** [comment]
yeah, I didn't notice that either. I think it's safe to be closed, the issue of being able to select personalized colors that are too dark for the theme is a separate one. 

I'm going to close this
