### ISSUE TITLE
bundle install failed.

### ISSUE THREAD

**Issue by rattanakchea** [thepracticaldev/dev.to#490]
## Installation issue
I am using MacOS High Sierra, and follow instruction to setup dev.to locally. When I ran `bundle install`, I got the following error. Any one have the same issue?

```
To see why this extension failed to compile, please check the mkmf.log which can be found here:

/Users/rattanakchea/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-17/2.5.0-static/pg-1.0.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/Users/rattanakchea/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pg-1.0.0 for inspection.
Results logged to
/Users/rattanakchea/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-17/2.5.0-static/pg-1.0.0/gem_make.out

An error occurred while installing pg (1.0.0), and Bundler cannot continue.
Make sure that `gem install pg -v '1.0.0'` succeeds before bundling.
````

**Comment by markfrst** [comment]
@rattanakchea you have installed postgresql ?

**Comment by rattanakchea** [comment]
I installed postgres.app.

What is the recommended way to install pg?

**Comment by markfrst** [comment]
@rattanakchea try it https://medium.com/@Umesh_Kafle/postgresql-and-postgis-installation-in-mac-os-87fa98a6814d

**Comment by rhymes** [comment]
@rattanakchea can you post the log?

**Comment by Zhao-Andy** [comment]
Hey @rattanakchea, be sure to check out our docs for more info:
https://docs.dev.to/installation/mac-os/

We recommend Postgres.app, which you did. Also as Rhymes said, seeing the logs will help.

**Comment by rattanakchea** [comment]
@markfrst it is working now after I did: `brew uninstall --force postgresql` and reinstall it back. It seems that Postgress.app only does not for my system.
