### ISSUE TITLE
Add button for copying code snippet at once

### ISSUE THREAD

**Issue by razaanstha** [thepracticaldev/dev.to#4904]
Whenever copying code; Its too long process and so uncomfortable feeling of highlighting each line and copying the code snippet. So instead of this long process dev.to team's ferocious developers need to add copy button in the top of the code snippet so it would be easier for developers to try them.

**Demo for the Copy Button**
![image](https://user-images.githubusercontent.com/25036593/69498063-eb012880-0f0b-11ea-9bd2-0bc8c6226f28.png)
_some thing like this_

**Comment by jessleenyc** [comment]
Hey @razaanstha! This is a duplicate issue of a request we already approved: https://github.com/thepracticaldev/dev.to/issues/4686

Closing this so the conversation is consolidated in one issue. Thanks!
