### ISSUE TITLE
Facing issues while posting on this site

### ISSUE THREAD

**Issue by GetMyLeather1** [thepracticaldev/dev.to#4910]
Unable to post any new post on this site. I face the error of "It was not you, its me" and guide me to submit a report. 

Allow me to post something on this site. I have attached the screenshot of the error.
![Capture1](https://user-images.githubusercontent.com/57987119/69533825-64475c80-0f9a-11ea-9738-63934c86585d.JPG)

**Comment by jessleenyc** [comment]
Hey, this looks like an individual account issue. Please email yo@dev.to for support. Thanks!
