### ISSUE TITLE
The Android Security Bug could let anyone hack your phone camera

### ISSUE THREAD

**Issue by GetMyLeather1** [thepracticaldev/dev.to#4911]
After a detailed analysis of the Google Camera app, our team found that by manipulating specific actions and intents, an attacker can control the app to take photos and/or record videos through a rogue application that has no permissions to do so.

Additionally, we found that certain attack scenarios enable malicious actors to circumvent various storage permission policies, giving them access to stored videos and photos, as well as GPS metadata embedded in photos, to locate the user by taking a photo or video and parsing the proper EXIF data. This same technique also applied to Samsung’s Camera app.

![8eNjPiJTRi72AXggVqB5YN-970-80](https://user-images.githubusercontent.com/57987119/69534178-13843380-0f9b-11ea-94ca-8eeaf6150fa2.jpg)

**Comment by rhymes** [comment]
Closing this on terms of relevance to the DEV. Let me know if I was wrong @GetMyLeather1!
