### ISSUE TITLE
Flaky Views an article shows an article

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#4929]
Related to #4884 

```ruby
  1) Views an article shows an article
     Failure/Error: @article = Article.find(article_ids[0])
     
     ActiveRecord::RecordNotFound:
       Couldn't find Article with 'id'=1050
     
     
     
     # ./app/controllers/additional_content_boxes_controller.rb:8:in `index'
     # ------------------
     # Capybara::CapybaraError:
     #   Your application server raised an error - It has been raised in your test code because Capybara.raise_server_errors == true
     #   ./spec/rails_helper.rb:89:in `block (3 levels) in <top (required)>'
Finished in 9 minutes 57 seconds (files took 9.83 seconds to load)
3067 examples, 1 failure, 3 pending
Failed examples:
rspec ./spec/system/articles/user_visits_an_article_spec.rb:12 # Views an article shows an article
```

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by mstruve** [comment]
We have not seen this spec fail for quite a while so we are closing this issue. Will reopen if it pops up again but hopefully, it's been unknowingly fixed 😄
