### ISSUE TITLE
Flaky user_edits_an_article_spec.rb

### ISSUE THREAD

**Issue by johncurcio** [thepracticaldev/dev.to#4931]
Related to #4884

Sometimes when I run ``bundle exec rspec spec/system``, ``user_edits_an_article_spec.rb`` fails. 

```sh
Failures:

  1) Editing with an editor user unpublishes their post
     Failure/Error: fill_in "article_body_markdown", with: template.gsub("true", "false")
     
     Capybara::ElementNotFound:
       Unable to find field "article_body_markdown" that is not disabled
     
     [Screenshot]: tmp/screenshots/failures_r_spec_example_groups_editing_with_an_editor_user_unpublishes_their_post_836.png

     
     # ./spec/system/articles/user_edits_an_article_spec.rb:36:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (2 levels) in <top (required)>'
     # ./spec/support/initializers/rspec_retry.rb:8:in `block (2 levels) in <top (required)>'

```

This is the generated screenshot if it helps:

![failures_r_spec_example_groups_editing_with_an_editor_user_unpublishes_their_post_836](https://user-images.githubusercontent.com/9089551/69585348-3542e200-0fbe-11ea-9a80-26af26b6c196.png)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by mstruve** [comment]
We have not seen this spec fail for quite a while so we are closing this issue. Will reopen if it pops up again but hopefully, it's been unknowingly fixed 😄
