### ISSUE TITLE
Flaky user_leaves_an_organization_spec.rb

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#4934]
Related to #4884 
 
```ruby
Failures:
  1) User leaves an organization when user leaves member organization leaves organization and shows confirmation
     Failure/Error: click_button("Leave Organization")
     
     Capybara::ElementNotFound:
       Unable to find button "Leave Organization" that is not disabled
     
     
     
     # ./spec/system/organization/user_leaves_an_organization_spec.rb:20:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (2 levels) in <top (required)>'
Finished in 9 minutes 46 seconds (files took 9.58 seconds to load)
3067 examples, 1 failure, 3 pending
Failed examples:
rspec ./spec/system/organization/user_leaves_an_organization_spec.rb:19 # User leaves an organization when user leaves member organization leaves organization and shows confirmation
```

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by mstruve** [comment]
We have not seen this spec fail for quite a while so we are closing this issue. Will reopen if it pops up again but hopefully, it's been unknowingly fixed 😄
