### ISSUE TITLE
BUG Reading List isn't updating when Archiving articles

### ISSUE THREAD

**Issue by GuriGhumanLive** [thepracticaldev/dev.to#4953]
So I saved couple of articles to read later, and when I archive them, they get removed from reading List page https://dev.to/readinglist, but the number of articles I saved remains on main page as Reading List (3)
![image](https://user-images.githubusercontent.com/39106243/69750654-258bef00-11b2-11ea-8d7a-339713c46c64.png)

![image](https://user-images.githubusercontent.com/39106243/69750685-38062880-11b2-11ea-8e64-0adc6d6b586e.png)

I see you can Unsave them, but if you archive them technically speaking they should be removed from my reading list or provide user with UNSAVE option along with ARCHIVE.
Thanks

**Comment by CristinaRuth** [comment]
This has been driving me crazy for a while. So much so that I actually tried to get the site running locally but ran into issues and I ran out of time. 😕

**Comment by osde8info** [comment]
may be related

goto https://dev.to/readinglist
click archive
click https://dev.to/readinglist/archive
latest archive doesnt appear on list until you manually re-enter https://dev.to/readinglist/archive into browser nav

**Comment by rhymes** [comment]
@osde8info I think that's a separate issue, as you noticed you'll see the item in the archive eventually, it's just not instantaneous unfortunately. Could you open an issue about it?

**Comment by osde8info** [comment]
ok thanks i will

**Comment by mstruve** [comment]
No longer a problem since moving to Elasticsearch
