### ISSUE TITLE
Add publication date to Medium liquid tag

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#4961]
**Is your feature request related to a problem? Please describe.**

The Medium liquid tag contains lots of useful information but it would be nice if it could also display what's the publication date of the article:

![Screenshot_2019-11-28 A Developer's Guide to Flutter](https://user-images.githubusercontent.com/146201/69807562-e6779100-11e5-11ea-9857-b091e788cdae.png)

Look how the original article has "Mar 5" indicated

![Screenshot_2019-11-28 Google Launched Flutter SDK 1 2 and Dart Programming Language 2 2](https://user-images.githubusercontent.com/146201/69807565-e8415480-11e5-11ea-89bc-31bd7e572f16.png)

**Describe the solution you'd like**

Add publication date to the liquid tag

**Comment by johncurcio** [comment]
I'd love to work on this issue later today. Should the publication date be formatted like in the medium article? Something like this but with less padding:

**Author Name**
<h6>Nov 8, 2017  ・ 10 min read</h6>

**Comment by maestromac** [comment]
@johncurcio it doesn't have to be exact. It could even be squeezed right between the author and the read time.
