### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by manoj10101996** [thepracticaldev/dev.to#4964]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by jessleenyc** [comment]
Hey, since this issue is blank we are going to close it. Feel free to open a new issue if you have more info. If you're encountering issues with your individual account, please email yo@dev.to for support. Thank you!
