### ISSUE TITLE
HTML <button> allowed in markdown parsing

### ISSUE THREAD

**Issue by DevFelixDorn** [thepracticaldev/dev.to#4970]
**Describe the bug**

I decided to write an article, and in the body, i wrote
```markdown
```html <button>Button</button>
`` ` (without the space between `)
```
and a HTML button appear, i tried some XSS combinations, none of them work, but i'm not an expert.

**To Reproduce**
* Create a new Post
* Copy the following snippet https://hastebin.com/oluxipivuz.js
* Preview it

**Expected behavior**

A HTML button appear.

**Screenshots**

![image](https://user-images.githubusercontent.com/47077927/69916424-22fff280-145b-11ea-81d5-76391b44c86b.png)

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Firefox
- Version: 71.0b12

**Comment by Zhao-Andy** [comment]
Yep, we allow some HTML to go through but not all. Worth reconsidering the `<button>` tag though.

I'm going to change the title of this issue so we don't see "XSS" and panic a bit. 😅

**Comment by jessleenyc** [comment]
I believe we allow the button tag because some folks use it as a nicer way to create links? There shouldn't be an XSS issue here so I'm going to close this issue.
