### ISSUE TITLE
Preview after clicking "save post" is incorrect

### ISSUE THREAD

**Issue by JoshCheek** [thepracticaldev/dev.to#5]
When I click "Preview" the preview looks correct, but when I click "Save Post", the unpublished preview has omitted a large amount of the content.

![dev to-save-has-broken-preview](https://cloud.githubusercontent.com/assets/77495/21111602/ded31456-c067-11e6-920e-229a614cdb98.gif)

This is the contents of the post, as of the time I recorded the screenshot:

```markdown
---
title:       Write a REPL in Ruby
published:   false
description: Lets build a REPL!
cover_image: 
tags: 
---

<style>
.step:after {
  display: block;
  clear:   both;
  content: "";
}
.step > * {
  width:   48%;
  display: block;
}
.step img {
  float: left;
}
.step p {
  float: right;
  padding-top: 0;
}
</style>


Write a REPL in Ruby
====================

[Pry](http://pryrepl.org/), [IRB](http://ruby-doc.org/stdlib-2.3.1/libdoc/irb/rdoc/IRB.html), and [RIPL](https://rubygems.org/gems/ripl) are popular Ruby REPLs, but, just for funsies, lets see what it takes to build our own! Code snippets are [here](https://gist.github.com/JoshCheek/baab86f3258ff98c468f3dbc032dc9c5).

---

Simple beginnings
-----------------

<div class="step">
  <img alt="screenshot" src="https://cdn-images-1.medium.com/max/600/1*qWygoGudYFcFuPVMDUDKFw.png">
  <p>
    A **REPL** must "**R**ead" input from the user, "**E**val"uate that input as code, "**P**rint" the result, and "**L**oop" back to the first step to do it all over again. So, lets start with those four steps.
  </p>
</div>


Persist local variables
-----------------------

<div class="step">
  <img alt="screenshot" src="https://cdn-images-1.medium.com/max/600/1*XxwgW544hDGlwXRTJ17pHQ.png">
  <p>
    The problem with our REPL at present is it forgets local variables 😝 That’s because local variables are stored in "bindings" on the callstack. When we call `eval`, it makes a new binding to evaluate the code in, and when `eval` is finished, it pops that binding off the callstack discarding our variables. To retain the variables between invocations, we need to evaluate them in the same binding every time.
  </p>
</div>


Readline input
--------------

<div class="step">
  <img alt="animated screenshot" src="https://cdn-images-1.medium.com/max/600/1*hy59uAXv3wTGRhQMPQ8Eqw.gif">
  <p>
    Our input is... not good 😜 But, Ruby ships with [`Readline`](https://ruby-doc.org/stdlib-2.3.3/libdoc/readline/rdoc/Readline.html), which is like `gets`, but adds a prompt, kill ring, fancy movement/editing, cycling through previous inputs, etc.
  </p>
</div>


Highlight output
----------------

<div class="step">
  <img alt="screenshot" src="https://cdn-images-1.medium.com/max/600/1*SH_f_Dg9qTCtzNuBcN3mHg.png">
  <p>
    Looks good, lets syntax highlight our output. [Rouge](https://rubygems.org/gems/rouge) is the way to go these days, but [CodeRay](https://rubygems.org/gems/coderay) has a simpler interface. We just pass it through CodeRay between inspecting and printing.
  </p>
</div>


Handle EOF
----------

<div class="step">
  <img alt="screenshot" src="https://cdn-images-1.medium.com/max/600/1*BuCkA9WP0_gePukpFDM8dA.png">
  <p>
    Currently, if we hit the end of the input stream (eg user presses `control-d`), we explode in `eval`. This is because `input` is `nil`. Lets stop the loop in this situation.
  </p>
</div>


Handle Errors
-------------

<div class="step">
  <img alt="screenshot" src="https://cdn-images-1.medium.com/max/600/1*eAJf1FkG56qilcqkuI-40w.png">

  <p>
    It would also be nice to handle errors in the input, so lets rescue and display them! The `\e[31m` is the [ANSI escape code](https://en.wikipedia.org/wiki/ANSI_escape_code) to turn the foreground red and the `\e[0m` will turn off the red. Note that, while common, these codes aren’t portable.
  </p>
</div>

---


Where to go from here?
----------------------

So, in 10 lines of code, we’ve constructed a fairly respectable REPL! If you found that fun, try adding some additional functionality:

* Save the previous result in `_` (probably `Binding#local_variable_set`)
* Handle large objects better, eg `{foo: 42, bar: {baz: 1, buz: 2, fuz: 3}, wibble: {magic_word: "sha"+"z"*20+"am"}}}` could get formatted very nicely if, you replace `inspect` with [`pretty_inspect`](http://www.rubydoc.info/stdlib/pp/Kernel#pretty_inspect-instance_method) from `pp.rb`, in the standard library.
* Remember history across invocations (check the [Readline](https://ruby-doc.org/stdlib-2.3.3/libdoc/readline/rdoc/Readline.html) docs)
* Syntax highlight the input (there’s probably a [Readline](https://ruby-doc.org/stdlib-2.3.3/libdoc/readline/rdoc/Readline.html) method to let you swap it out after it’s been entered)
* Add some commands like pry’s `ls` (search around for a list of reflection methods in order to get the information) and show-source (check these humans’ gems: [bannister](https://rubygems.org/profiles/banister), [ConradIrwin](https://rubygems.org/profiles/ConradIrwin), [ryanf](https://rubygems.org/profiles/ryanf), [kyrylo](https://rubygems.org/profiles/kyrylo))
* Separate the REPL’s variables from the user’s. Enter `local_variables`, and you’ll see you’re sharing them with the program. You’ll have to get a binding that doesn’t come from that context. Possibly useful: `TOPLEVEL_BINDING`, `eval` on a string, define a method on the singleton class then remove it, `Kernel#load`, and that JavaScript idiom of defining a lambda you immediately call.
* What would it take to make this testable? You’d probably want to be able to pass it the binding and IO streams. Readline looks plainful, IDK how it’s storing its state, but it’s going to be fragile or broken. You’ll want to segregate it from the rest of your program as much as possible, and if you want 100% coverage, you may need [PTY](http://www.rubydoc.info/stdlib/pty/PTY)s
```

**Comment by benhalpern** [comment]
I'm hesitant to allow arbitrary styles into the final post because of how easy it would be for publishers to create articles that look bad, especially across platforms and screen sizes and future site-wide design changes.

Under this current system of sanitizing styles, it's the client side preview that is wrong.

But, of course, the style of your post, in that exact format, is not possible. We could implement some custom classes that map to style adjustments. It might even make sense to use known classes from a popular library like bootstrap to dictate this.

**Comment by JoshCheek** [comment]
> But, of course, the style of your post, in that exact format, is not possible.

Not sure I understand.


> Under this current system of sanitizing styles, it's the client side preview that is wrong.

Given the non-standardness of Markdown, it might make sense to use the same lib for both server-side and client-side rendering, or always delegate to the client, or settle on a given specification such as common markdown (though even that could be fragile).


> It might even make sense to use known classes from a popular library like bootstrap to dictate this.

Prob best to avoid anything externally specified, otherwise we couple the content to some version of some CSS framework, and then changing anything becomes difficult (ie all content from all time has to continue working, so if the framework releases a new version that is not backwards compatible, then we have to continue using the old version or perform some error-prone content transformation or record which version to serve with each post)


> We could implement some custom classes that map to style adjustments.

That could work. Generally, I'm fine with letting the site control styling, I mostly expect it to do a better job than I will, and that decreases fragility as the site changes over time.  In this case, it's not styling I'm trying to change so much as layout. If I had a way to specify this layout, I'd have no need to try manually styling:

![screenshot 2016-12-12 14 08 06](https://cloud.githubusercontent.com/assets/77495/21114908/70a25ef8-c074-11e6-9a1d-9680a3c9e736.png)

Though it's worth noting that I have a sample point of 1 (just me, only one post), so this shouldn't be considered a comprehensive analysis. Eg it could be that I want to do something fancy at some point (Medium accommodates this with "embeds", I haven't explored their flexibility).

---

FWIW, I do like the idea of tracking the stylesheet with the content, then we could provide users with several stylesheet options, and they could choose the one that best matches their content (eg prose tends to go well with serif fonts, and technical content tends to go best with sans-serif fonts).

Given that authors are writing dev-based content, it seems reasonable to expect them to have content whose presentation requires more control. Eg is it be possible to write a post like [this](http://ncase.me/ballot/) or [this](http://worrydream.com/LadderOfAbstraction/) without sacrificing convenience in the common cases?

**Comment by benhalpern** [comment]
Yeah, right now we use [showdown](https://github.com/showdownjs/showdown) on the client preview and [redcarpet](https://github.com/vmg/redcarpet) on the server. It's been good enough so far, but since this is pretty core to what we're doing it will be a focus to improve this.

That's why our first open source extraction project is [around the markdown](https://github.com/thepracticaldev/super-markdown). Depending on where this conversation goes, may make sense to break things up and discuss in that project space.

Wholeheartedly agree with the idea that devs creating and consuming dev-oriented content can guide a lot of our decisions and assumptions and is why I want to make it possible to build richer content, I still want to ensure we do it safely and steadily and not rush into any assumptions about usability and compatibility.

**Comment by JoshCheek** [comment]
I still have this issue after updating the post to remove all the HTML except a few strong tags (b/c they weren't highlighting correctly in Atom Editor, and that worried me that they were ambiguous, the `<strong>` seemed less ambiguous) 

Further, when I published it and went to the page, it was displaying only the summary. ie the renderer for published posts is showdown, the incorrect one. Note that when I entere the content into the showdown demo, and it [works][showdown-demo] correctly.

```markdown
---
title:       Write a REPL in Ruby
published:   false
description: Lets build a REPL!
cover_image: 
tags: 
---

[Pry](http://pryrepl.org/), [IRB](http://ruby-doc.org/stdlib-2.3.1/libdoc/irb/rdoc/IRB.html),
and [RIPL](https://rubygems.org/gems/ripl) are popular Ruby REPLs, but, just for funsies,
lets see what it takes to build our own! Code snippets are
[here](https://gist.github.com/JoshCheek/baab86f3258ff98c468f3dbc032dc9c5).

---

Simple beginnings
-----------------

A <strong>REPL</strong> must "<strong>R</strong>ead" input from the user,
"<strong>E</strong>val"uate that input as code, "<strong>P</strong>rint"
the result, and "<strong>L</strong>oop" back to the first step to do it
all over again. So, lets start with those four steps.

![screenshot](https://cdn-images-1.medium.com/max/600/1*qWygoGudYFcFuPVMDUDKFw.png)


---


Persist local variables
-----------------------

The problem with our REPL at present is it forgets local variables 😝 That’s because
local variables are stored in "bindings" on the callstack. When we call `eval`,
it makes a new binding to evaluate the code in, and when `eval` is finished,
it pops that binding off the callstack discarding our variables. To retain the
variables between invocations, we need to evaluate them in the same binding every time.

![screenshot](https://cdn-images-1.medium.com/max/600/1*XxwgW544hDGlwXRTJ17pHQ.png)


---


Readline input
--------------

Our input is... not good 😜 But, Ruby ships with [`Readline`](https://ruby-doc.org/stdlib-2.3.3/libdoc/readline/rdoc/Readline.html),
which is like `gets`, but adds a prompt, kill ring, fancy movement/editing, cycling through previous inputs, etc.

![animated screenshot](https://cdn-images-1.medium.com/max/600/1*hy59uAXv3wTGRhQMPQ8Eqw.gif)


---


Highlight output
----------------

Looks good, lets syntax highlight our output. [Rouge](https://rubygems.org/gems/rouge)
is the way to go these days, but [CodeRay](https://rubygems.org/gems/coderay)
has a simpler interface. We just pass it through CodeRay between inspecting and printing.

![screenshot](https://cdn-images-1.medium.com/max/600/1*SH_f_Dg9qTCtzNuBcN3mHg.png)


---


Handle EOF
----------

Currently, if we hit the end of the input stream (eg user presses `control-d`),
we explode in `eval`. This is because `input` is `nil`.
Lets stop the loop in this situation.

![screenshot](https://cdn-images-1.medium.com/max/600/1*BuCkA9WP0_gePukpFDM8dA.png)


---


Handle Errors
-------------

It would also be nice to handle errors in the input, so lets rescue and display
them! The `\e[31m` is the [ANSI escape code](https://en.wikipedia.org/wiki/ANSI_escape_code)
to turn the foreground red and the `\e[0m` will turn off the red. Note that,
while common, these codes aren’t portable.

![screenshot](https://cdn-images-1.medium.com/max/600/1*eAJf1FkG56qilcqkuI-40w.png)


---


Where to go from here?
----------------------

So, in 10 lines of code, we’ve constructed a fairly respectable REPL! If you found that fun, try adding some additional functionality:

* Save the previous result in `_` (probably `Binding#local_variable_set`)
* Handle large objects better, eg `{foo: 42, bar: {baz: 1, buz: 2, fuz: 3}, wibble: {magic_word: "sha"+"z"*20+"am"}}}` could get formatted very nicely if, you replace `inspect` with [`pretty_inspect`](http://www.rubydoc.info/stdlib/pp/Kernel#pretty_inspect-instance_method) from `pp.rb`, in the standard library.
* Remember history across invocations (check the [Readline](https://ruby-doc.org/stdlib-2.3.3/libdoc/readline/rdoc/Readline.html) docs)
* Syntax highlight the input (there’s probably a [Readline](https://ruby-doc.org/stdlib-2.3.3/libdoc/readline/rdoc/Readline.html) method to let you swap it out after it’s been entered)
* Add some commands like pry’s `ls` (search around for a list of reflection methods in order to get the information) and show-source (check these humans’ gems: [bannister](https://rubygems.org/profiles/banister), [ConradIrwin](https://rubygems.org/profiles/ConradIrwin), [ryanf](https://rubygems.org/profiles/ryanf), [kyrylo](https://rubygems.org/profiles/kyrylo))
* Separate the REPL’s variables from the user’s. Enter `local_variables`, and you’ll see you’re sharing them with the program. You’ll have to get a binding that doesn’t come from that context. Possibly useful: `TOPLEVEL_BINDING`, `eval` on a string, define a method on the singleton class then remove it, `Kernel#load`, and that JavaScript idiom of defining a lambda you immediately call.
* What would it take to make this testable? You’d probably want to be able to pass it the binding and IO streams. Readline looks plainful, IDK how it’s storing its state, but it’s going to be fragile or broken. You’ll want to segregate it from the rest of your program as much as possible, and if you want 100% coverage, you may need [PTY](http://www.rubydoc.info/stdlib/pty/PTY)s
```


[showdown-demo]: http://showdownjs.github.io/demo/#/%5BPry%5D(http%3A%2F%2Fpryrepl.org%2F)%2C%20%5BIRB%5D(http%3A%2F%2Fruby-doc.org%2Fstdlib-2.3.1%2Flibdoc%2Firb%2Frdoc%2FIRB.html)%2C%0Aand%20%5BRIPL%5D(https%3A%2F%2Frubygems.org%2Fgems%2Fripl)%20are%20popular%20Ruby%20REPLs%2C%20but%2C%20just%20for%20funsies%2C%0Alets%20see%20what%20it%20takes%20to%20build%20our%20own!%20Code%20snippets%20are%0A%5Bhere%5D(https%3A%2F%2Fgist.github.com%2FJoshCheek%2Fbaab86f3258ff98c468f3dbc032dc9c5).%0A%0A---%0A%0ASimple%20beginnings%0A-----------------%0A%0AA%20%3Cstrong%3EREPL%3C%2Fstrong%3E%20must%20%22%3Cstrong%3ER%3C%2Fstrong%3Eead%22%20input%20from%20the%20user%2C%0A%22%3Cstrong%3EE%3C%2Fstrong%3Eval%22uate%20that%20input%20as%20code%2C%20%22%3Cstrong%3EP%3C%2Fstrong%3Erint%22%0Athe%20result%2C%20and%20%22%3Cstrong%3EL%3C%2Fstrong%3Eoop%22%20back%20to%20the%20first%20step%20to%20do%20it%0Aall%20over%20again.%20So%2C%20lets%20start%20with%20those%20four%20steps.%0A%0A!%5Bscreenshot%5D(https%3A%2F%2Fcdn-images-1.medium.com%2Fmax%2F600%2F1*qWygoGudYFcFuPVMDUDKFw.png)%0A%0A%0A---%0A%0A%0APersist%20local%20variables%0A-----------------------%0A%0AThe%20problem%20with%20our%20REPL%20at%20present%20is%20it%20forgets%20local%20variables%20%F0%9F%98%9D%20That%E2%80%99s%20because%0Alocal%20variables%20are%20stored%20in%20%22bindings%22%20on%20the%20callstack.%20When%20we%20call%20%60eval%60%2C%0Ait%20makes%20a%20new%20binding%20to%20evaluate%20the%20code%20in%2C%20and%20when%20%60eval%60%20is%20finished%2C%0Ait%20pops%20that%20binding%20off%20the%20callstack%20discarding%20our%20variables.%20To%20retain%20the%0Avariables%20between%20invocations%2C%20we%20need%20to%20evaluate%20them%20in%20the%20same%20binding%20every%20time.%0A%0A!%5Bscreenshot%5D(https%3A%2F%2Fcdn-images-1.medium.com%2Fmax%2F600%2F1*XxwgW544hDGlwXRTJ17pHQ.png)%0A%0A%0A---%0A%0A%0AReadline%20input%0A--------------%0A%0AOur%20input%20is...%20not%20good%20%F0%9F%98%9C%20But%2C%20Ruby%20ships%20with%20%5B%60Readline%60%5D(https%3A%2F%2Fruby-doc.org%2Fstdlib-2.3.3%2Flibdoc%2Freadline%2Frdoc%2FReadline.html)%2C%0Awhich%20is%20like%20%60gets%60%2C%20but%20adds%20a%20prompt%2C%20kill%20ring%2C%20fancy%20movement%2Fediting%2C%20cycling%20through%20previous%20inputs%2C%20etc.%0A%0A!%5Banimated%20screenshot%5D(https%3A%2F%2Fcdn-images-1.medium.com%2Fmax%2F600%2F1*hy59uAXv3wTGRhQMPQ8Eqw.gif)%0A%0A%0A---%0A%0A%0AHighlight%20output%0A----------------%0A%0ALooks%20good%2C%20lets%20syntax%20highlight%20our%20output.%20%5BRouge%5D(https%3A%2F%2Frubygems.org%2Fgems%2Frouge)%0Ais%20the%20way%20to%20go%20these%20days%2C%20but%20%5BCodeRay%5D(https%3A%2F%2Frubygems.org%2Fgems%2Fcoderay)%0Ahas%20a%20simpler%20interface.%20We%20just%20pass%20it%20through%20CodeRay%20between%20inspecting%20and%20printing.%0A%0A!%5Bscreenshot%5D(https%3A%2F%2Fcdn-images-1.medium.com%2Fmax%2F600%2F1*SH_f_Dg9qTCtzNuBcN3mHg.png)%0A%0A%0A---%0A%0A%0AHandle%20EOF%0A----------%0A%0ACurrently%2C%20if%20we%20hit%20the%20end%20of%20the%20input%20stream%20(eg%20user%20presses%20%60control-d%60)%2C%0Awe%20explode%20in%20%60eval%60.%20This%20is%20because%20%60input%60%20is%20%60nil%60.%0ALets%20stop%20the%20loop%20in%20this%20situation.%0A%0A!%5Bscreenshot%5D(https%3A%2F%2Fcdn-images-1.medium.com%2Fmax%2F600%2F1*BuCkA9WP0_gePukpFDM8dA.png)%0A%0A%0A---%0A%0A%0AHandle%20Errors%0A-------------%0A%0AIt%20would%20also%20be%20nice%20to%20handle%20errors%20in%20the%20input%2C%20so%20lets%20rescue%20and%20display%0Athem!%20The%20%60%5Ce%5B31m%60%20is%20the%20%5BANSI%20escape%20code%5D(https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FANSI_escape_code)%0Ato%20turn%20the%20foreground%20red%20and%20the%20%60%5Ce%5B0m%60%20will%20turn%20off%20the%20red.%20Note%20that%2C%0Awhile%20common%2C%20these%20codes%20aren%E2%80%99t%20portable.%0A%0A!%5Bscreenshot%5D(https%3A%2F%2Fcdn-images-1.medium.com%2Fmax%2F600%2F1*eAJf1FkG56qilcqkuI-40w.png)%0A%0A%0A---%0A%0A%0AWhere%20to%20go%20from%20here%3F%0A----------------------%0A%0ASo%2C%20in%2010%20lines%20of%20code%2C%20we%E2%80%99ve%20constructed%20a%20fairly%20respectable%20REPL!%20If%20you%20found%20that%20fun%2C%20try%20adding%20some%20additional%20functionality%3A%0A%0A*%20Save%20the%20previous%20result%20in%20%60_%60%20(probably%20%60Binding%23local_variable_set%60)%0A*%20Handle%20large%20objects%20better%2C%20eg%20%60%7Bfoo%3A%2042%2C%20bar%3A%20%7Bbaz%3A%201%2C%20buz%3A%202%2C%20fuz%3A%203%7D%2C%20wibble%3A%20%7Bmagic_word%3A%20%22sha%22%2B%22z%22*20%2B%22am%22%7D%7D%7D%60%20could%20get%20formatted%20very%20nicely%20if%2C%20you%20replace%20%60inspect%60%20with%20%5B%60pretty_inspect%60%5D(http%3A%2F%2Fwww.rubydoc.info%2Fstdlib%2Fpp%2FKernel%23pretty_inspect-instance_method)%20from%20%60pp.rb%60%2C%20in%20the%20standard%20library.%0A*%20Remember%20history%20across%20invocations%20(check%20the%20%5BReadline%5D(https%3A%2F%2Fruby-doc.org%2Fstdlib-2.3.3%2Flibdoc%2Freadline%2Frdoc%2FReadline.html)%20docs)%0A*%20Syntax%20highlight%20the%20input%20(there%E2%80%99s%20probably%20a%20%5BReadline%5D(https%3A%2F%2Fruby-doc.org%2Fstdlib-2.3.3%2Flibdoc%2Freadline%2Frdoc%2FReadline.html)%20method%20to%20let%20you%20swap%20it%20out%20after%20it%E2%80%99s%20been%20entered)%0A*%20Add%20some%20commands%20like%20pry%E2%80%99s%20%60ls%60%20(search%20around%20for%20a%20list%20of%20reflection%20methods%20in%20order%20to%20get%20the%20information)%20and%20show-source%20(check%20these%20humans%E2%80%99%20gems%3A%20%5Bbannister%5D(https%3A%2F%2Frubygems.org%2Fprofiles%2Fbanister)%2C%20%5BConradIrwin%5D(https%3A%2F%2Frubygems.org%2Fprofiles%2FConradIrwin)%2C%20%5Bryanf%5D(https%3A%2F%2Frubygems.org%2Fprofiles%2Fryanf)%2C%20%5Bkyrylo%5D(https%3A%2F%2Frubygems.org%2Fprofiles%2Fkyrylo))%0A*%20Separate%20the%20REPL%E2%80%99s%20variables%20from%20the%20user%E2%80%99s.%20Enter%20%60local_variables%60%2C%20and%20you%E2%80%99ll%20see%20you%E2%80%99re%20sharing%20them%20with%20the%20program.%20You%E2%80%99ll%20have%20to%20get%20a%20binding%20that%20doesn%E2%80%99t%20come%20from%20that%20context.%20Possibly%20useful%3A%20%60TOPLEVEL_BINDING%60%2C%20%60eval%60%20on%20a%20string%2C%20define%20a%20method%20on%20the%20singleton%20class%20then%20remove%20it%2C%20%60Kernel%23load%60%2C%20and%20that%20JavaScript%20idiom%20of%20defining%20a%20lambda%20you%20immediately%20call.%0A*%20What%20would%20it%20take%20to%20make%20this%20testable%3F%20You%E2%80%99d%20probably%20want%20to%20be%20able%20to%20pass%20it%20the%20binding%20and%20IO%20streams.%20Readline%20looks%20plainful%2C%20IDK%20how%20it%E2%80%99s%20storing%20its%20state%2C%20but%20it%E2%80%99s%20going%20to%20be%20fragile%20or%20broken.%20You%E2%80%99ll%20want%20to%20segregate%20it%20from%20the%20rest%20of%20your%20program%20as%20much%20as%20possible%2C%20and%20if%20you%20want%20100%25%20coverage%2C%20you%20may%20need%20%5BPTY%5D(http%3A%2F%2Fwww.rubydoc.info%2Fstdlib%2Fpty%2FPTY)s

**Comment by JoshCheek** [comment]
Oh, I just realized what the issue is. Three dashes in Markdown is a `<hr>` tag, but that's also what the frontmatter is using as a delimiter. It's probably pulling all the content up to the last `---` as frontmatter (if it were a regex, it's the difference between `*` and `*?`)

**Comment by jessleenyc** [comment]
@JoshCheek we made some changes on our end to make sure preview & saved posts are the same. I'm closing this but moving your multiple stylesheet suggestion to our private repo for some internal discussion. Thanks for being awesome and giving feedback, we really appreciate it.

**Comment by JoshCheek** [comment]
^_^ awesome, ty!
