### ISSUE TITLE
Labels on reaction buttons

### ISSUE THREAD

**Issue by bigblind** [thepracticaldev/dev.to#50]
I was reading an article on dev.to using VoiceOver on my iPhone, an discovered the new reactions. They look great, but I couldn't make sense of them using VoiceOver. Also, on desktop, when I hover over the icons, I'd love to see a label explaining what the icon means.

If it's useful to you, I can update a video of trying to use these buttons using VO, some time tomorrow.

**Comment by jessleenyc** [comment]
Hey @bigblind, thanks for flagging this. I'll look into and keep you posted.

**Comment by benhalpern** [comment]
@bigblind when you say "label" what exactly do you mean? Like a tooltip or a title attribute?

**Comment by bigblind** [comment]
For me, the title attribute works find, but the W3C [warns against relying on it](https://www.w3.org/TR/html5/single-page.html#the-title-attribute):

>  &#9888; **Warning!** Relying on the title attribute is currently discouraged as many user agents do not expose the attribute in an accessible manner as required by this specification (e.g. requiring a pointing device such as a mouse to cause a tooltip to appear, which excludes keyboard-only users and touch-only users, such as anyone with a modern phone or tablet).

**Comment by benhalpern** [comment]
@bigblind thanks for the heads up.

**Comment by jessleenyc** [comment]
We added alt tags to the images, so closing this for now.
