### ISSUE TITLE
Add filtering options to /internal/reports dashboard

### ISSUE THREAD

**Issue by pkfrank** [thepracticaldev/dev.to#5012]
**Is your feature request related to a problem? Please describe.**
As an admin, when spending time at `/internal/reports`, I am sometimes left to deal with multiple reports of the same URL, and/or multiple reports by the same reporter.

This creates complexity (and adds time) in dealing with the report and replying to the reporters.

**Describe the solution you'd like**
An option on this page to filter reports by: `reported url` and `reporter`.  This would allow me to batch my actions and responses in a more efficient manner.

**Additional context**
If as a result of the implementation all "Anonymous" reports are batched together, I think that's a feature, and not a bug.

**Comment by benhalpern** [comment]
So after discussing this further with @pkfrank, I believe what we really could use here is _sorting_, which for all intents and purposes takes care of the clustering we're looking for.

I think this could pair well with the filtering in #5396 and could be used in conjunction with one another depending on user needs.

I see this as a row of links (button styled probably) to sort by either reporter or URL or the default of date/time submitted. I don't think we necessarily need to be able to toggle sort direction as we probably always want that to be the same (either alphabetical or reverse chronological?)

Let me know if that makes sense.

**Comment by jacobherrington** [comment]
@benhalpern Yeah, that makes sense. I'll work on that in a follow-up PR for #5396

**Comment by benhalpern** [comment]
@jacobherrington fabulous

**Comment by jacobherrington** [comment]
@pkfrank Can we consider this issue resolved, or are there additional features that need to be knocked out before we close it?

**Comment by pkfrank** [comment]
@jacobherrington I think we are all good.  @michael-tharrington any comments as the most frequent user of this area of the site?

**Comment by michael-tharrington** [comment]
I think we're good here too!
