### ISSUE TITLE
why not change android api(android studio)/iso

### ISSUE THREAD

**Issue by kavindyasinthasilva** [thepracticaldev/dev.to#5013]
add new flutter or android studio project(repo) .we can develop it .good ui/ux and best performance include it . if you have make this project and we can fork it.

**Comment by Glennmen** [comment]
@kavindyasinthasilva You mean this repo? https://github.com/thepracticaldev/DEV-Android

**Comment by kavindyasinthasilva** [comment]
ok brother . i am contribute above link .thank you

**Comment by rhymes** [comment]
Closing this as it seems @kavindyasinthasilva was looking for the Android's app repo

**Comment by kavindyasinthasilva** [comment]
### ok thank you
