### ISSUE TITLE
Feature request- allow for multiple draft posts

### ISSUE THREAD

**Issue by nhidtran** [thepracticaldev/dev.to#5019]
Today- you can only work/save one draft at a time. I'm sure to mimic the behavior like Twitter
Request - would like to have multiple saved posts. Sometimes I'm not done with one idea but would like to start another

**Comment by maestromac** [comment]
Hello @nhidtran , you certainly can create multiple draft post by clicking `save draft` on /new. Is something preventing you from saving? Is it an error you're encountering?

![Screen Shot 2019-12-06 at 9 05 07 AM](https://user-images.githubusercontent.com/15793250/70328638-86957180-1807-11ea-976a-0240a7af433d.png)

**Comment by nhidtran** [comment]
there was a bug when saving a draft. Would 500 - I thought my post didn't actually save. When that error does show up, the one with the gif, whatever routing package is being used is preventing the user to "go back" but the post actually does save when you go into your dashboard, but doesn't show it like the above. If I can recreate, i'll add a images

**Comment by nhidtran** [comment]
if the bug happens again, i'll create a new issue. Thank you for getting back to me!

**Comment by maestromac** [comment]
Do let me know 👍
