### ISSUE TITLE
Test run time in a docker container

### ISSUE THREAD

**Issue by Schwad** [thepracticaldev/dev.to#5025]
Hello 👋 ,

I am working on getting the `dev.to` development environment setup on my machine, so that I may get familiar with the codebase and hopefully start being able to chip in the odd contribution (because I love what you're doing!).

Firstly, the documentation has been __fantastic__ and I've been able to get a Docker container locally setup with an instance of the application same-day.

However, in getting set up, I am running into some issues with the speed of the tests. For example, I picked one innocuous test to run, and after it took a while, attempted to run it with Spring, with the following results (full output stripped for brevity):

```
$ docker-compose run web bundle exec bin/spring rspec -e "checks that the user is banned and has note"
Starting devto_db_1 ... done
Starting devto_redis_1 ... done
Running via Spring preloader in process 17
Run options: include {:full_description=>/checks\ that\ the\ user\ is\ banned\ and\ has\ note/}
.

Finished in 5 minutes 14 seconds (files took 24.14 seconds to load)
1 example, 0 failures
```

I then ran it a second time, considering that maybe Spring's internals or caches needed warming up, with the following result:

```
$ docker-compose run web bundle exec bin/spring rspec -e "checks that the user is banned and has note"
Starting devto_db_1 ... done
Starting devto_redis_1 ... done
Running via Spring preloader in process 17
Run options: include {:full_description=>/checks\ that\ the\ user\ is\ banned\ and\ has\ note/}
.

Finished in 7 minutes 1 second (files took 24.14 seconds to load)
1 example, 0 failures
```

Not to be outdone, I went back to the drawing board and then attempted to run things completely locally, uncontainerized. (My uncontainerized setup is stiill in the works at time of writing)

Surely I am missing something here? Is there anyone else contributing to the repo working via a Docker setup, and if so, how are you running your specs locally? To be workable I think it would be desirable to get this loading a spec in under a minute, or even two minutes if possible.

Also - would most of you develop wholly on your machine instead of via Docker, and what's your mileage with that setup? Should I be just trying to run this manually on my machine to speed up time?

Further - if this is an inappropriate issue for the repository, I'm happy to be redirected to a more appropriate Slack instance or forum.

**Comment by jessleenyc** [comment]
Our specs _do_ take a while. @maestromac does this seem expected?

**Comment by Schwad** [comment]
Thanks @jessleenyc :) 

Maybe something in my setup is making things slow with initial page load/lazy loading/etc. 

It appears the spec in the container *does* actually load in a normal-ish (10-20 second) time frame but wondering if I'm missing something for the test run time. (How fast does that test run on your machine? It seems to just load a page and do one action so I didn't think it would be too bad)

Also today I'm doing some system-wide upgrades and cleaning, so will attempt this exact step again later and let you know what I find. :) Will also attempt to reproduce this in a non-containerized setup (which may take longer to get set up, but more than happy if I can get this working non-Docker).


Cheers!

**Comment by rhymes** [comment]
@Schwad what operating system are you using? Mac is extremely slow with Docker, in that case it might also because of this

**Comment by Schwad** [comment]
@rhymes  - I am using MacOS, but am currently going through the whole "Catalina" upgrade and all that fun today to see if that speeds things up. 

Thank you for the information! I'm a bit more comfortable developing in a fully native setup (instead of Docker, even though it takes longer to get working) so if that's the case I don't mind trying to setup without Docker then report back here with speed/times.

If it's a lot faster, then I'll close this out.

**Comment by Schwad** [comment]
Good news! It is much, much faster to run in the native (non-docker) setup for the tests (again, with the *on my machine* caveat :) )

```

Finished in 12.97 seconds (files took 19.93 seconds to load)
1 example, 0 failures

```

Same spec. I will close this issue and put a note at the top. Thank you so much for your help! :)
