### ISSUE TITLE
fonts: add OpenDyslexic as an option.

### ISSUE THREAD

**Issue by bnb** [thepracticaldev/dev.to#5036]
**Is your feature request related to a problem? Please describe.**

I am personally dyslexic. This handily slows down my ability to parse text when reading. Implementing an option to use the OpenDyslexic font would help me (and other with Dyslexia) parse text better on dev.to.

**Describe the solution you'd like**

Similar to the comic sans font option, add an option to use OpenDyslexic for body text.

**Describe alternatives you've considered**

I could implement this personally on my computers, but I figure having it be a feature of the platform would be more impactful and help in terms of a11y for others with dyslexia.

There are other paid options for Dyslexia-supporting fonts but the cost and redistribution would likely be prohibitive.

**Additional context**

None.

**Comment by benhalpern** [comment]
Really great to see the quick turnaround by @codebytere here. There will need to be a bit of additional thought given to how this goes down technically but I think we're pretty close.

**Comment by Almenon** [comment]
Didn't know that font existed, that's pretty cool 👍
