### ISSUE TITLE
Display Badge Title when hovering over badges on badges page

### ISSUE THREAD

**Issue by bolariin** [thepracticaldev/dev.to#5040]
**Is your feature request related to a problem? Please describe.**

I was scrolling through the badges page and had to switch to different page to learn more about a badge. A decent amount of the badges have pretty descriptive titles so I think it would be nice to only switch when you need more information about a badge.

**Describe the solution you'd like**

It would be nice to be able to hover over a badge and have the badge title appear. This can be similar to how it currently works with badges on the profile page. It would be useful for users that want to get information about a badge but don't want to be switching back and forth between pages

**Describe alternatives you've considered**

Maybe a view that allows users to see all the badges and respective descriptions all on the same page.

**Comment by christyram99** [comment]
Hi @jessleenyc, Can I contribute to this issue.

**Comment by maestromac** [comment]
Go ahead @christyram99 !

**Comment by christyram99** [comment]
Ok @jessleenyc

**Comment by dinesh1995** [comment]
Hey @jessleenyc  @christyram99 I'm a newbie here. Can i take this up?

**Comment by worst-developer** [comment]
Looks like it can be closed

**Comment by rhymes** [comment]
Thanks @worst-developer!
