### ISSUE TITLE
Difference in code highlight depending on url

### ISSUE THREAD

**Issue by karfau** [thepracticaldev/dev.to#5041]
**Describe the bug**

When viewing [my comment as part of a post](https://dev.to/nombrekeff/what-would-you-call-this-function-3kbg#ijn0) the code blocks look great:
![image](https://user-images.githubusercontent.com/135657/70418455-b80a7900-1a63-11ea-9497-d7709f5d7427.png)

but when using [the deeplink that the comment offers](https://dev.to/karfau/comment/ijn0):
![image](https://user-images.githubusercontent.com/135657/70418581-f738ca00-1a63-11ea-82a5-14b0b560b341.png)

or when previewing markdown while adding a comment:
![image](https://user-images.githubusercontent.com/135657/70418431-a88b3000-1a63-11ea-94ba-cb1152c1b081.png)

it's really hard to spot the code blocks.

**To Reproduce**

1. Example string to add to comment box:
```
Let's check what `code` looks like in a preview on the post page
```
2. Click the "preview" button

**Expected behavior**

Code blocks look the same everywhere, hopefully the way they look in posts.

**Desktop (please complete the following information):**

- OS: Manjaro
- Browser: Chromium
- Version: 78.0.3904.97 (Official Build) Arch Linux (64-bit)

**Comment by ChintuKarthi** [comment]
Hi @jessleenyc  I would like to pick up this issue

**Comment by ChintuKarthi** [comment]
@karfau  Can I pick this one up?

**Comment by karfau** [comment]
I just reported it and have no intention/capacity/experience to work on it.
So no objections from my side.

I would understand the labels that have been added in a way that a fix would be welcomed by the dev.to-team.

**Comment by rhymes** [comment]
@ChintuKarthi yeah, thank you! Sorry for the delayed response. I'm going to assign you to the issue

**Comment by ChintuKarthi** [comment]
@rhymes  I have raised a [PR](https://github.com/thepracticaldev/dev.to/pull/7103).

**Comment by karfau** [comment]
Thank you for this! :tada:
