### ISSUE TITLE
On dashboard follower number is breaking to a new line

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/dev.to#505]
@lianafelt commented on [Mon Jul 23 2018](https://github.com/thepracticaldev/dev.to_core/issues/618)

On dev.to/dashboard Follower Number is breaking to new line.

This was on last version of chrome on windows 10

![devBugScreen.png](https://images.zenhubusercontent.com/5a60cc5f4b5806bc2bc348c3/f16f5c58-6db2-4510-be23-64b435cf1239)

---

@nickytonline commented on [Tue Jul 24 2018](https://github.com/thepracticaldev/dev.to_core/issues/618#issuecomment-407420200)

Whoever tackles this, if you're not on a Windows machine, you can [grab free VMs here](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) and install Chrome 67 for Windows in the VM to test/fix the issue.

---

@joshi-chinmay commented on [Mon Jul 30 2018](https://github.com/thepracticaldev/dev.to_core/issues/618#issuecomment-408876408)

@nickytonline I can take this ahead! Is that okay?

---

@nickytonline commented on [Mon Jul 30 2018](https://github.com/thepracticaldev/dev.to_core/issues/618#issuecomment-408881750)

Sounds good. Go for it 😉

---

@joshi-chinmay commented on [Mon Jul 30 2018](https://github.com/thepracticaldev/dev.to_core/issues/618#issuecomment-408902575)

@nickytonline Either we can increase the width of `.actions` or we can manipulate numbers as (999+).
<br /> Or we can reduce the `font-size` of `.actions` by `0.2em`.

I chose the second option, and now it's looking like this,
<b>1. Minimum count -</b>
![dashboard](https://user-images.githubusercontent.com/16207311/43406248-6ad1c0e0-944e-11e8-929e-3b192fd0389b.png)
<br />

<b>2. Extreme count -</b> (after `999999999` we can add `999999999+`. Just to make it full-proof.)
![extremes](https://user-images.githubusercontent.com/16207311/43406428-c7f8e352-944e-11e8-8b33-2bb56980da56.png)

---

@nickytonline commented on [Mon Jul 30 2018](https://github.com/thepracticaldev/dev.to_core/issues/618#issuecomment-409010158)

I haven't loaded this on a Windows machine yet, but the fact that it loads fine on other OSes leads me to believe it's not a width issue. What differences do see in the style rendered in Windows Chrome 67 vs. Ubuntu? On Mac it's fine, even with 4 digits for followers.

---

@nickytonline commented on [Mon Jul 30 2018](https://github.com/thepracticaldev/dev.to_core/issues/618#issuecomment-409013142)

For large numbers, probably 5 or 6 digits and up it makes sense to have a different format, e.g. 10K+. Thoughts @maestromac @benhalpern?

---

@joshi-chinmay commented on [Mon Aug 27 2018](https://github.com/thepracticaldev/dev.to_core/issues/618#issuecomment-416214733)

This issue is still happening on dev.to. Are we moving this to the public repo?

---

@nickytonline commented on [Mon Aug 27 2018](https://github.com/thepracticaldev/dev.to_core/issues/618#issuecomment-416222497)

@maestromac, can you move this to the public repo? Thanks.

**Comment by joshi-chinmay** [comment]
@Zhao-Andy Thanks for moving the issue.
I am working on it. Will discuss more with @nickytonline.

**Comment by joshi-chinmay** [comment]
Hey, @nickytonline this is how the styles are looking on Ubuntu Machine (which is as same as Windows).
What do you think might be causing the issue? Also, let me know if you need anything else.

![screenshot from 2018-09-03 11-22-53](https://user-images.githubusercontent.com/16207311/44966198-5f992180-af6c-11e8-9f3f-a03e0bd429d2.png)

**Comment by nickytonline** [comment]
@joshi-chinmay, I haven't had a chance to look into this yet. I wonder if it's related to https://github.com/thepracticaldev/dev.to/issues/523 ?

**Comment by joshi-chinmay** [comment]
@nickytonline, I think it is... :+1:

**Comment by nickytonline** [comment]
@joshi-chinmay, if you can confirm this is just a side effect of #523, we can close this one. cc: @Zhao-Andy
