### ISSUE TITLE
Add helper script to reset fork / sync fork

### ISSUE THREAD

**Issue by DarkSmile92** [thepracticaldev/dev.to#5053]
Add a helper shell script to reset the forked repository to the same state as the upstream.

This helps to start over with your own fork if you messed up or to get the latest from upstream and merge it to your fork.

Also a script to sync the fork with upstream to get the latest changes is helpful.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/5055
