### ISSUE TITLE
Reaction Creation Fails due to missing Reactable ID

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#5072]
**Describe the bug**
There is some spot in the codebase(pretty sure its in the front end javascript) where we are attempting to update a Reaction record but we do not send sufficient data and we end up with this error. 
```
ActiveRecord::RecordInvalid: Validation failed: Reactable must exist, Reactable is not valid.
```
This error is raised on line 58 of the reactions controller and is due to the following params being sent.
```ruby
# Line number: /app/controllers/reactions_controller.rb:58:in `create'
# Params: {
#  "reactable_type" => "Article",
#  "reactable_id" => "undefined",
#  "category" => "readinglist"
# }
reaction = Reaction.create!(
        user_id: current_user.id,
        reactable_id: params[:reactable_id],
        reactable_type: params[:reactable_type],
        category: category,
      )
```
**To Reproduce**

Not sure. The referrer url from all the Honeybadgers we are seeing is a search url like `https://dev.to/search?q=something`

**Expected behavior**

We should either populate the reactable_id correctly or not send the request at all if the field is not populated

**Comment by matheusazzi** [comment]
I'll work on that.

**Comment by mstruve** [comment]
That would be fantastic! Thank you!!!!

**Comment by matheusazzi** [comment]
@mstruve I could reproduce the error and have a fix for it https://github.com/thepracticaldev/dev.to/pull/5122
