### ISSUE TITLE
Requesting XML from articles/feed endpoint Should Not Raise an Error

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#5073]
**Describe the bug**
When the `articles/feed` endpoint is hit and the format requested is xml we end up throwing an error
```
ActionView::MissingTemplate: Missing template articles/feed, application/feed with {:locale=>[:en], :formats=>[:xml], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}. Searched in:
  * "/app/app/views"
  * "/app/vendor/bundle/ruby/2.6.0/gems/doorkeeper-5.2.2/app/views"
  * "/app/vendor/bundle/ruby/2.6.0/gems/devise-4.7.1/app/views"
  * "/app/vendor/bundle/ruby/2.6.0/gems/administrate-0.12.0/app/views"
  * "/app/vendor/bundle/ruby/2.6.0/gems/kaminari-core-1.1.1/app/views"
```

**To Reproduce**
Request xml from the feed endpoint with one of the following paths `/feed.xml` or `/rss.xml`
```
{
  "format" => "xml",
  "controller" => "articles",
  "action" => "feed"
}
```

**Expected behavior**
Requesting an xml should either return a valid xml response without any error being raised or return an error response saying the endpoint does not support the xml format.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/5077
