### ISSUE TITLE
Using API to request published articles from a specific user without need of api-key

### ISSUE THREAD

**Issue by JRSofty** [thepracticaldev/dev.to#5075]
**Is your feature request related to a problem? Please describe.**
When using the API to display my published articles I'm forced to use the `api/articles/me/published` endpoint. This endpoint requires the use of the api-key. While this would make sense if I were using the API to create my own editor, I only want to display links to my articles on my website, and I'm forced to try to keep my api-key secret. This requires me to do a bit of backend work to make things safe.
**Describe the solution you'd like**
As a Dev.to API user and a developer, I would like to have an endpoint that allows me to request X number of published articles by a user's name, without needing to authenticate my account. This would allow visitors to my personal website to see links of the content I've posted and visit Dev.to to read the articles.
**Describe alternatives you've considered**
The other option would have been to perform a call to the `api/articles` endpoint and then go through the pages of information (possibly with multiple calls to the endpoint), to find my last 4 articles. This would cause a lot of resource use on the API, as well as slowing my own website down considerably. 
**Additional context**
This functionality could also help organizations that want to display links to articles that their members have written.

**Comment by Zhao-Andy** [comment]
I think you could try `https://dev.to/api/articles?username=yourusername`?

Looking at our documentation now, it probably makes more sense to update "User's articles" to "Your own articles" or some similar language. I eventually found it under "Published articles" and checking for the available parameters. :)

Hope that answers your question!

**Comment by JRSofty** [comment]
Hi,

Ah, I somehow missed that. That works and then we can close this issue.
