### ISSUE TITLE
I can't delete my account...

### ISSUE THREAD

**Issue by lartpang** [thepracticaldev/dev.to#5085]
**Describe the bug**

I can't delete my account...

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/26847524/70692499-747b6d80-1cf6-11ea-8ada-a49ec9abbd5e.png)

![image](https://user-images.githubusercontent.com/26847524/70692641-b99f9f80-1cf6-11ea-8b15-e53a312b600b.png)

**Desktop (please complete the following information):**

- OS: ubuntu 18.04
- Browser: chrome
- Version: Version 78.0

**Additional context**

**Comment by jessleenyc** [comment]
Sorry about that @lartpang. We'll take a look to see if this is a bug affecting more people. In the meantime, if you email yo@dev.to from the email address associated with your dev account, we can help you delete your account.

**Comment by maestromac** [comment]
Consolidating this report with https://github.com/thepracticaldev/dev.to/issues/4608 . If you have any additional info you would like to provide, please continue the conversation there. Thank you!
