### ISSUE TITLE
Medium RSS feed fails to import all stories

### ISSUE THREAD

**Issue by DeJaVoo** [thepracticaldev/dev.to#5086]
**Describe the bug**

**To Reproduce**

1. Generate you medium rss feed ttps://medium.com/feed/@username
 2. Go to settings, choose Publishing from RSS
3. In the rss feed url , set your medium rss feed 
a. Mark the RSS source as canonical URL by default
b.  Replace self-referential links with DEV-specific links
4. Click on update and wait import process to finish
5. **Error:** Not all stories were imported to dev.to draft dashboard , I've 18 stories ,only 9 of them were imported and others were not imported. the rss feed of Medium is partial too but if you'll use medium API key you'll have access to all the stories

**Expected behavior**

All stories were imported to draft dashboard

**Desktop (please complete the following information):**

- OS: Window 10
- Browser: Chrome 
- Version: Version 79.0.3945.79 (Official Build) beta (64-bit)
Also reproduced on stable version too.

**Smartphone (please complete the following information):**

- Device: OnePlus 3
- OS: Android 9
- Browser: Chrome
- Version: Version 79.0.3945.79 (Official Build) beta

**Comment by maestromac** [comment]
Sorry for the late response @DeJaVoo .

Medium's API endpoints are only for creating posts and not for retrieving. And like you pointed out, Medium's RSS include at most 10 recent posts (which includes comments).  Unfortunately, there's no straight forward way to obtain all the posts aside from scraping 🙁

**Comment by DeJaVoo** [comment]
Thank you for your reply.
Can you provide anyway to easily scrap Medium.com?

**Comment by rhymes** [comment]
@DeJaVoo the main issue with scraping is that it violates terms of services with Medium, so it wouldn't be great to add code for that:

> Crawling the Services is allowed if done in accordance with the provisions of our robots.txt file, but scraping the Services is prohibited.

from https://medium.com/policy/medium-terms-of-service-9db0094a1e0f

**Comment by maestromac** [comment]
@DeJaVoo It is also possible to grab each post one by one with https://github.com/ericclemmons/medium-to-markdown but that site can be a bit slow. 

Hope our answer was helpful and please let us know if there's anything else.
