### ISSUE TITLE
Write a post error

### ISSUE THREAD

**Issue by alishahenderson** [thepracticaldev/dev.to#5087]
Hi Tea,

I am not able to post nay article on https://dev.to/.

Please reolve this asap.

here is the snapshot: 
![image](https://user-images.githubusercontent.com/56536629/70705010-316ec980-1cf9-11ea-8242-fd5818436cb1.png)

**Comment by maestromac** [comment]
Hello @alishahenderson , this looks an issue specific to your account. Please email yo@dev.to for more help.
