### ISSUE TITLE
Resolve Rubocop Rails.root.join complaints

### ISSUE THREAD

**Issue by keithrbennett** [thepracticaldev/dev.to#5088]
When I run rubocop on the latest master I get several complaints like this one:

```
config/environments/development.rb:23:6: C: Rails/FilePath: Please use Rails.root.join('path/to') instead.
  if Rails.root.join("tmp", "caching-dev.txt").exist?
```

Contrary to popular belief, Ruby will join the path components with a forward slash even when running in Windows:

```
Microsoft Windows [Version 10.0.17763.503]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>ruby -v
ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]

C:\WINDOWS\system32>ruby -e "puts File.join('foo', 'bar')"
foo/bar
```

This is usually not a problem in Windows, because the Ruby runtime will translate the directory separators as needed to perform any operations. However, if the filespec is being passed on a command line, or passed elsewhere outside the Ruby runtime, that would be a problem; but both forms would share that problem.

That said, my only interest is to remove these complaints, and another way to do that would be to change the Rubocop rule.

I can do either; which would be best?

**Comment by maestromac** [comment]
Let's follow Rubocop's suggestion @keithrbennett

**Comment by keithrbennett** [comment]
@maestromac Thanks for that guidance. I've made those changes. I decided to make it a separate PR (#5114).

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/5114
