### ISSUE TITLE
Users covered up on DEV Connect screen

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/dev.to#509]
@brian-kephart commented on [Fri Aug 03 2018](https://github.com/thepracticaldev/dev.to_core/issues/658)

# _BUG_
### Current/Expected Behavior
On the DEV Connect screen, when the list of users on the left is scrolled to the bottom, the last item is mostly hidden. If I shrink the screen, the last two entries are covered up completely.

### Additional Info (steps to replicate, device/browser, helpful links)
Only applies when the list on the left fills up the viewport height.
Safari desktop

### Screenshots
<img width="363" alt="screen shot 2018-08-03 at 1 56 46 pm" src="https://user-images.githubusercontent.com/21235090/43661463-fbd568c2-9727-11e8-883f-71315e6d4e2f.png">

**Comment by edisonywh** [comment]
Can I work on this?

**Comment by jessleenyc** [comment]
Looks like this is done!

**Comment by imone1onlyD** [comment]
No
