### ISSUE TITLE
Users receiving error message in notifications that won't go away.

### ISSUE THREAD

**Issue by michael-tharrington** [thepracticaldev/dev.to#5099]
Various users have reported receiving the following error message from Sloan in their [notifications](https://dev.to/notifications):

![https://p78.f0.n0.cdn.getcloudapp.com/items/WnuEEOGO/Image+2019-12-12+at+5.42.02+PM.png?v=298a721104c8130825d81169de61fc70](https://p78.f0.n0.cdn.getcloudapp.com/items/WnuEEOGO/Image+2019-12-12+at+5.42.02+PM.png?v=298a721104c8130825d81169de61fc70)

The error doesn't seem to go away. At least one user (1 of 3) reported that they seemed to stop getting new notifications for their latest article after the error message appeared, but they _did_ continue to see new follower notifications.

It's unclear how to reproduce this.

**Expected behavior**

Generally, an error message should disappear. It's possible these folks aren't receiving some notifications, but the message doesn't full explain what error occurred.

**Comment by mstruve** [comment]
Likely fixed by:
https://github.com/thepracticaldev/dev.to/pull/5103
or by
https://github.com/thepracticaldev/dev.to/pull/5083.

Do we want to check back with the users and see if they are good now before we close this?
