### ISSUE TITLE
Getting page with error code 500 when clicking WRITE A POST

### ISSUE THREAD

**Issue by liviulupei** [thepracticaldev/dev.to#5137]
**Describe the bug**

I'm getting sent to a page with a 500 error code after I click on the WRITE A POST button from the header. 

**To Reproduce**

1. Log into DEV.TO
2. Click on the WRITE A POST button from the header.

**Expected behavior**
The editor should open.

**Actual behavior**
Getting page with error code 500.

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS Mojave
- Browser: Chrome
- Version: 79 

**Additional context**

I also can't add any comments or reply to any comments.

Did I get shadow banned?

**Comment by maestromac** [comment]
Hello @liviulupei , this looks an issue specific to your account. Please email yo@dev.to for more help.
