### ISSUE TITLE
Feedback Page Bugs

### ISSUE THREAD

**Issue by itsHall** [thepracticaldev/dev.to#5143]
**Describe the bug**

When reporting a comment for abuse, the form would not send and returned no error messages. Once I clicked in each field (the link to the comment was auto-generated) the form finally went through. The styles for the confirmation page are not set, so the confirmation message is left-aligned in the window with the `<h2>` tag sitting behind the top nav bar.

**To Reproduce**

1. Go to any post with comments.
2. Click the ellipses button, select Report Abuse from the dropdown.
3. Select the offense.
4. Submit the form.

Note: I only attempted to reproduce the issue a few times as I don't want to send a large amount of spam reports. It is possible the form submission bug was a local issue instead of something each user will experience. I apologize if that is the case.

**Expected behavior**

I expected the form to be sent the first time, having entered information in all required fields. I also expected the confirmation page to have a center-aligned container for the confirmation message (following the design of the rest of the site).

**Screenshots**

Feedback Confirmation Page
![dev to bug report](https://user-images.githubusercontent.com/31418688/70939802-03e69080-2017-11ea-822e-ed3b1e35c0f8.jpg)

**Desktop (please complete the following information):**

- OS: MacOS Catalina
- Browser: Vivaldi (Chromium)
- Version: 2.9.1705.41

**Comment by benhalpern** [comment]
Thanks for this. #5147 should fix it!
