### ISSUE TITLE
I cannot create new articles using curl with front matter

### ISSUE THREAD

**Issue by ninankara** [thepracticaldev/dev.to#5154]
**Describe the bug**
I want to POST new articles using API. I was using CURL to post the request.
At first I tried to post using normal curl (without using front matter), it was success.
Then I tried to post using front matter. I followed the documentation exactly, but failed.

`{"error":"(\u003cunknown\u003e): could not find expected ':' while scanning a simple key at line 3 column 1","status":422}`

I read that 422 means I am missing some parameters. But I don't know what is that because I just follow what its written in the docs.

**To Reproduce**

1. Open Bash Terminal or any terminal
2. `curl -X POST -H "Content-Type: application/json" -H "api-key: my-key" -d '{"article":{"body_markdown":"---\ntitle:This is test\npublished:true\n---\ntes..."}}' https://dev.to/api/articles`
3. An error occurred `{"error":"(\u003cunknown\u003e): could not find expected ':' while scanning a simple key at line 3 column 1, Title can't be blank","status":422}`
4. I added the title in the articles body .  `curl -X POST -H "Content-Type: application/json" -H "api-key: my-key" -d '{"article":{"title":"This is test no2","body_markdown":"---\ntitle:This is test\npublished:true\n---\ntes..."}}' https://dev.to/api/articles`
5. An error occurred `{"error":"(\u003cunknown\u003e): could not find expected ':' while scanning a simple key at line 3 column 1","status":422}`

**Expected behavior**

It has no problem if I post using curl without front matter, 
`url -X POST -H "Content-Type: application/json" -H "api-key: my-key"  -d '{"article":{"title":"Test from API","body_markdown":"This is test","published":"true"}}' 
 https://dev.to/api/articles`

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 Home
- Browser: Chrome
- Version: 78.0.3904.108

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**
I run the CURL in BASH Terminal of VS CODE

**Comment by gvpmahesh** [comment]
```
curl -X POST \
  https://dev.to/api/articles \
  -H 'Content-Type: application/json' \
  -H 'api-key: <replace your api key>' \
  -d '{
	"article": {
		"body_markdown": "dufbkurbfekrubfdjdkbfferukfberiufg",
		"title": "dfhguebfedfjkdbfrigberiufg",
		"tag_list": "yo"
	}
}'
```

@ninankara This seemed to work for me .. when in doubt use postman :D

I referred this file to understand what params i need to send to make an article

**Comment by ninankara** [comment]
> ```
> curl -X POST \
>   https://dev.to/api/articles \
>   -H 'Content-Type: application/json' \
>   -H 'api-key: <replace your api key>' \
>   -d '{
> 	"article": {
> 		"body_markdown": "dufbkurbfekrubfdjdkbfferukfberiufg",
> 		"title": "dfhguebfedfjkdbfrigberiufg",
> 		"tag_list": "yo"
> 	}
> }'
> ```
> 
> @ninankara This seemed to work for me .. when in doubt use postman :D
> 
> I referred this file to understand what params I need to send to make an article
> https://github.com/thepracticaldev/dev.to/blob/master/spec/requests/articles/articles_create_spec.rb

this one is without front matter. have you tried adding front matter. from the link you've written, this part.
```
it "creates series when series is created with frontmatter" do
    new_title = "NEW TITLE #{rand(100)}"
    post "/articles", params: {
      article: {
        title: new_title,
        body_markdown: "---\ntitle: hey hey hahuu\npublished: false\nseries: helloyo\n---\nYo ho ho#{rand(100)}"
      }
    }
    expect(Collection.last.slug).to eq("helloyo")
  end
```
