### ISSUE TITLE
canonical_url for posts not working properly anymore

### ISSUE THREAD

**Issue by marcobehler** [thepracticaldev/dev.to#5156]
Hi guys,
I tried adding canonical_url in my frontmatter or even in the code editor directly, but when I have a look at https://dev.to/marcobehler/java-microservices-a-practical-guide-29kn (for example), the rel=canonical tag is missing.

Others seems to have the same issue https://dev.to/marcobehler/canonicalurl-for-posts-not-working-properly-3l8p .

THanks

**Comment by Arteneko** [comment]
Can second that, another example of article without the canonical is [this one](https://dev.to/artemis/rust-is-fun-5gcb) (or pretty much every article I published).

**Comment by CristinaRuth** [comment]
Third Ed. Noticed this too

**Comment by OmisNomis** [comment]
I don't see the `rel=canonical` but Moz is telling me my newest cross-post does have it, so 🤷‍♂

**Comment by benhalpern** [comment]
Ah I get it. The canonical URL is not showing up because of the serviceworker migration. So this only affects the human browser of the page. If they go into dev tools and turn off serviceworkers by clicking “bypass for network”, it will show up just fine.

We can adjust the serviceworker version to also include this in some way to ease worries, but the machine-readable version of the page will always include that. The serviceworker version is for humans.

Hope that makes sense :slightly_smiling_face:

**Comment by marcobehler** [comment]
Ah, thanks! Makes sense. For me that's good enough.

**Comment by Mrc0113** [comment]
This still doesn't seem to be working for me. I added a canonical_url to this post and it isn't showing up. https://dev.to/mrc0113/reflecting-on-my-first-hackathon-4g9g

It's included in the front matter as follows:
`canonical_url: https://www.marcd.dev/articles/2020-02/hackathon-reflections
`

**Comment by maestromac** [comment]
Hello @Mrc0113 , I just double checked and I do see your canonical_url listed out

![Screen Shot 2020-02-20 at 5 42 21 PM](https://user-images.githubusercontent.com/15793250/74987102-6f2e5380-5408-11ea-94cd-15ffd285a42c.png)

**Comment by Mrc0113** [comment]
Maybe I'm misunderstanding. Shouldn't it show up at the top of the blog as "originally published at <url>" ?
Like this one did: 
![image](https://user-images.githubusercontent.com/1815312/74987374-0abfc400-5409-11ea-8c5f-c6d8291978c0.png)

**Comment by maestromac** [comment]
`Originally published at....` will only appear on Posts that are imported via RSS. But since you did provide canonical_url, it will still serve its SEO purpose

**Comment by Mrc0113** [comment]
Okay thanks for the clarification. Sorry for the confusion.
