### ISSUE TITLE
Edge navigation issues

### ISSUE THREAD

**Issue by kasuken** [thepracticaldev/dev.to#5163]
Content is not loaded and your are not able to navigate on the site
**To Reproduce**

1. Login on dev.to
2. navigate on the homepage
**Screenshots**

![image](https://user-images.githubusercontent.com/2757486/71066612-41603080-2173-11ea-84b0-b92636e67fd7.png)

**Desktop:**

- OS: Windows 10
- Browser: Edge

**Comment by mike-healy** [comment]
At least one of those console errors seems to be because Edge does not support the JS spread operator for object literals.

The error points to this part of the bundled JS:
`headers:{"X-CSRF-Token":i,...t}`

**Comment by maestromac** [comment]
Sorry for the late response @kasuken but are you still experiencing this issue?

**Comment by ackava** [comment]
@maestromac Still same issue,

![image](https://user-images.githubusercontent.com/39438041/75244030-ff95db00-57f0-11ea-9304-9eb44d48f91f.png)

Edge Version
Microsoft Edge 44.17763.831.0
Microsoft EdgeHTML 18.17763

**Comment by rhymes** [comment]
@ackava would it be possible for your to upgrade to the new Edge? https://support.microsoft.com/en-us/help/4501095/download-the-new-microsoft-edge-based-on-chromium

**Comment by ackava** [comment]
@rhymes I did upgrade and it is working correctly now.

**Comment by rhymes** [comment]
I am going to close this as it's unlikely that we're going to fix issues affecting Edge 44 and below (EdgeHTML). We do however support Edge Chromium
