### ISSUE TITLE
Allow Comments From Deleted Articles To Be Viewed

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#5170]
Currently, we do not remove comments when an article is deleted. The idea behind this is that if a user created a really nice, thorough comment they want to share with others, they can still do that even if the related article is deleted. In this sense, the comment belongs to the user more so than the article. However, currently viewing a comment that has no article is not possible [because we return a not_found response if `@commentable` is not present](https://github.com/thepracticaldev/dev.to/blob/master/app/controllers/comments_controller.rb#L24).
```ruby
@commentable = @root_comment&.commentable || @user.articles.find_by(slug: params[:slug]) || not_found
```

We want comments to be able to be viewed as a standalone entity. In order to accomplish this not only will the endpoint need to be updated but the view as well since that expects `@commentable` to be set.

**Comment by twinsfan421** [comment]
@mstruve Hi, I can work on this.

**Comment by mstruve** [comment]
That would be fabulous! THANK YOU!!! 

Please let us know if you have any questions.

**Comment by twinsfan421** [comment]
@mstruve Do you want the deleted article comment to be read only? A simple display of the comment with maybe the reaction count total? Or do you want some of the same functionality of comments like editing, deleting, replying, liking, moderating, etc...?
I think the best option might be to create a separate deleted article comment view or partial view and render it if there is no commentable.  Let me know what you think.

**Comment by mstruve** [comment]
@twinsfan421 great question! Yes, let's go with a simple read-only view that shows the reaction count. In the future, if we want to make it more dynamic we can. Thank you!
