### ISSUE TITLE
Hello Team, i am unable to create new post dev.to account. Please rectify this issue ASAP.

### ISSUE THREAD

**Issue by AntoniaDavis** [thepracticaldev/dev.to#5175]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by maestromac** [comment]
Hello @AntoniaDavis , this looks an issue specific to your account. Please email yo@dev.to for more help.
