### ISSUE TITLE
Generalisation: Convert app/models/tag.rb list of suggested tags for onboarding to variable.

### ISSUE THREAD

**Issue by leewynne** [thepracticaldev/dev.to#5177]
**Is your feature request related to a problem? Please describe.**

Hardcoded tag list, needs to be converted to variable to support new communities.

**Describe the solution you'd like**

New env variable to be created and added to internal dashboard.

**Describe alternatives you've considered**

n/a

**Additional context**

Initially suggested by Ben
<img width="670" alt="Screenshot 2019-12-18 at 18 12 34" src="https://user-images.githubusercontent.com/12694270/71169461-ddac3500-2250-11ea-9ccf-e765773a1206.png">

**Comment by rhymes** [comment]
a note: instead of using an env variable the ideal solution would use the site configuration
