### ISSUE TITLE
Generalisation: Convert all assets in app/views to use env variables for meta content. Generate new env variable for general meta keywords.

### ISSUE THREAD

**Issue by leewynne** [thepracticaldev/dev.to#5178]
**Is your feature request related to a problem? Please describe.**

Some of this is completed already, see app/views/pages/about.html.erb as an example but is missing variables for keywords.

**Describe the solution you'd like**

All meta content to be variable based and a potential solutions for page specific meta keywords for pages (new and existing)

**Additional context**

See example screenshot from about.html.erb and code_of_conduct.html.erb

<img width="664" alt="Screenshot 2019-12-19 at 11 36 15" src="https://user-images.githubusercontent.com/12694270/71171040-b8212a80-2254-11ea-99f0-75a8d6367c9b.png">
<img width="796" alt="Screenshot 2019-12-19 at 11 36 25" src="https://user-images.githubusercontent.com/12694270/71171041-b8212a80-2254-11ea-8c11-fbf3b35eb8f1.png">

**Comment by rhymes** [comment]
a note: all of these should be part of the site configuration

**Comment by rhymes** [comment]
This PR might be related to this https://github.com/thepracticaldev/dev.to/pull/5829

**Comment by Ridhwana** [comment]
> This PR might be related to this #5829
> 
> The PR is ready, we're trying to understand if there are any issues with the configuration before it's merged

Thanks Rhymes, let me check it out!
