### ISSUE TITLE
Dev.to not responding properly

### ISSUE THREAD

**Issue by fl-y** [thepracticaldev/dev.to#5186]
**Describe the bug**
[Symptoms]
- The profile picture is black
- Loading widget won't go away
- Anything after the first component is waiting to be loaded(Only the placeholder is apparent)
- Cannot click on the profile picture
- Messages cannot be viewed
- Overall, the website itself feels very broken
- dev.to showed the normal logged off state when accessed via incognito mode.
- 'Empty cache and hard reload' on developer mode had no effect
- Closing chrome and reopening had no effect

**To Reproduce**
[What occurred right before]
I never logged off or cleared my cache/google account etc. but for some reason, dev.to prompted me to log in. So I logged into my Github account and that is when the symptoms began.

**Expected behavior**
dev.to responding properly?..

**Screenshots**
(A video of recording the screen when this occurred. (Sorry for the low quality, in hindsight I definitely should have used a screen capture program instead of my camera)
[DevToError.mov.zip](https://github.com/thepracticaldev/dev.to/files/3986195/DevToError.mov.zip)

**Desktop (please complete the following information):**
- macOS Catalina(10.15.1)
- Chrome Version 78.0.3904.108 (Official Build) (64-bit)
- I have Chrome beta and DEV version installed as well on my machine.

**Additional context**
If there is any more information that feels needed even at the barest minimum - feel free to ask anytime, I will attempt to supply said information with the best of my abilities.

Thank you profusely for maintaining this amazing community and platform :)

**Comment by jessleenyc** [comment]
@fl-y are you still experiencing this issue? 

@maestromac heads up here.

**Comment by fl-y** [comment]
> @fl-y are you still experiencing this issue?
> 
> @maestromac heads up here.

Nope, it was an experience that occurred once, which did not occur again.

**Comment by maestromac** [comment]
Thanks for the follow-up @fl-y . This might be an effect of recent service worker migration that resolved itself. Please let us know if this issue appears again.
