### ISSUE TITLE
"Vomits" Stuck in internal/reports

### ISSUE THREAD

**Issue by michael-tharrington** [thepracticaldev/dev.to#5191]
In [internal/reports](https://dev.to/internal/reports) there is a section for "Abuse Reports" where admin can mark "vomits" (🤢) as valid or invalid. Vomits are a feature that mods have access to for marking problem content (articles and comments), but an admin ultimately must verify these actions in [internal/reports](https://dev.to/internal/reports) by marking the 🤢 as "confirmed" or "invalid". When doing so, the item is removed from the list.

Occasionally, a "vomit" will get stuck in the list if an article has been un-published or the ID changes for some reason. Marking "confirmed" or "invalid" has no effect at this point and the 🤢 stays in the list.

**To Reproduce**

1. Go to https://dev.to/new.
2. Write a new post and publish it.
3. Type in the article URL and append `/mod` to it. (e.g. `dev.to/username/articlename/mod`), then go to the page.
4. Click on the "vomit" icon (🤢)
5. Type in the article URL and append `/edit` to it, then go to the page.
6. Unpublish the article.
7. Go to https://dev.to/internal/reports
8. When trying to mark the vomit as "confirmed" or "invalid" it won't remove the 🤢 from the list.

**Expected behavior**

Marking a vomit as "confirmed" or "invalid" should always remove "vomits" 🤢 from the report list. It doesn't matter if the article has been unpublished.

**Screenshots**

Here's what the UI looks like. Each time after confirming or marking invalid vomits the vomit is removed from the list and the page refreshes. 

![Image 2019-12-20 at 12 09 39 PM](https://user-images.githubusercontent.com/16007075/71275856-89718580-2322-11ea-98c8-d45b83850a67.png)

**Comment by jacobherrington** [comment]
@michael-tharrington Is this issue resolved? I think #5392 closed it, but I want to make sure. :smile:

**Comment by michael-tharrington** [comment]
Good call, @jacobherrington! This one is indeed good to close. 👍
