### ISSUE TITLE
Seeing duplicate messages in direct chat

### ISSUE THREAD

**Issue by 12vanblart** [thepracticaldev/dev.to#5196]
**Describe the bug**

When swapping between conversations with 2 users in Direct Chat, I'm seeing multiples of one of the chats. Every so often it resets back to a single copy of the conversation. 

**To Reproduce**

1. Have a conversation started with 2 users in Dev direct (1-1 conversations with each)
2. Open direct messaging with the paper airplane link
3. click between the 2 conversations
4. The second (and beyond) time opening you should see duplicates of the conversation "stacked" on top of each other - almost as if the first time it grabbed the conversation it didn't release it from memory, then re-opening the conversation showed the old copy + new copy

**Expected behavior**

Only one instance of the conversation should be displayed.

**Screenshots**

![duplicated conversation with another DEV user](https://user-images.githubusercontent.com/16465776/71285423-1fada780-2333-11ea-88ea-1e016b723a7b.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Edge (Chromium) & Firefox (Developer) -- confirmed issue on both
- Version: Edge - 79.0.309.54 && Firefox - 72.0b9

**Comment by jessleenyc** [comment]
Thanks for flagging, I believe @sarthology is looking into it!

**Comment by sarthology** [comment]
@jessleenyc Yes, @jessleenyc I'm on it.

**Comment by benhalpern** [comment]
🤦‍♂ Sorry this had to do with a production-only configuration of our edge cache. I fixed it and I believe things are better.

**Comment by rhymes** [comment]
@12vanblart can you still reproduce this?

**Comment by 12vanblart** [comment]
Nope! Looks better now 😀
