### ISSUE TITLE
Unknown characters leading profile page H2 and About Me items

### ISSUE THREAD

**Issue by vgrovestine** [thepracticaldev/dev.to#52]
Unknown characters preceding H2 "Recent Comments" (hex 01F4CD) and pseudo-list items in "About Me" (hex 01F4AC) cannot be rendered by the browser.

Latest versions of both Chrome and Firefox running in Linux Mint 18.1 exhibit this behaviour. Overriding the CSS for these elements to try a different font-family makes no difference.

![screenshot from 2017-06-22 15-50-03](https://user-images.githubusercontent.com/11873315/27450758-1b79938e-5763-11e7-9c98-64c3913f06a4.png)

**Comment by vgrovestine** [comment]
Just noticed the same thing happening in the footer immediately following "copyright 2017"; unknown character, hex 01F525

![screenshot from 2017-06-22 16-01-39](https://user-images.githubusercontent.com/11873315/27451020-1c1f1f56-5764-11e7-853b-f25863391f82.png)

**Comment by benhalpern** [comment]
Yeah these are emojis we used because we are lazy. They should really be replaced with images. Thanks for the heads up.

**Comment by benhalpern** [comment]
A couple instances of this issue have been fixed and other outstanding parts have been noted internally, so I'm closing the issue. Thanks a lot.
