### ISSUE TITLE
Add following count and followers count within profile of users

### ISSUE THREAD

**Issue by learttmorina** [thepracticaldev/dev.to#5204]
It will be nice to know how many followers and following has my friend.

By now I can't know how many followers he got, only if he screenshots his profile.

**Comment by Glennmen** [comment]
The DEV team has decided that this is something they don't want because it causes people to compare their profiles and gives a false sense of success.

https://github.com/thepracticaldev/dev.to/issues/3639#issuecomment-531361524

https://github.com/thepracticaldev/dev.to/issues/2778

**Comment by fayazara** [comment]
Can we at least get the follower count in the api, on `/users/me` endpoint or the `/followers/users` endpoint.?
