### ISSUE TITLE
Cannot read the privacy policy during onboarding

### ISSUE THREAD

**Issue by cxw42** [thepracticaldev/dev.to#5205]
Submitted as kindly suggested by @michael-tharrington via email 2019-11-27 (US Eastern time).

**Describe the bug**

During onboarding, I cannot access the privacy policy.  When I try to do so, I am redirected back to the onboarding page.

**To Reproduce**

- Start the onboarding process as a new user
- Click "Continue" below the cat animgif on `dev.to/onboarding`
- Click the link for the Terms and Conditions next to the checkbox labeled "You agree to our Terms and Conditions"
- In the "1. Terms" section, click the link for "Privacy Policy"

**Expected behavior**

The privacy policy appears so I can read it before clicking the checkbox indicating I agree to it.

**Observed behavior**

I am taken to `dev.to/privacy`, then immediately redirected back to `dev.to/onboarding` (with the animgif).

**Workaround**

The only workaround I know of is to read the privacy policy in an incognito tab.

**Platform**

I observed the same with Opera on Android and WIth Chromium on Ubuntu.
- Browser: Opera
- Version:

Thank you for considering this bug report!

**Comment by cxw42** [comment]
@Zhao-Andy Thanks for taking a look at this!  I have not yet finished the onboarding.  I am waiting in case you need me to run any tests.  Would you please let me know whether or not you think you might want more data from me?  If not, I will go ahead and finish the onboarding.  Much appreciated!

**Comment by narender2031** [comment]
@cxw42   Can I take this one?

**Comment by cxw42** [comment]
@narender2031 Please! :D 

I'm just a user.  I can still reproduce this issue --- just tested with Chrome 80.0.3987.132 (Official Build) snap (64-bit) on Lubuntu 19.10.  Let me know if there's anything you'd like me to test.

Thank you!!!!

**Comment by narender2031** [comment]
@cxw42 I created a PR for this issue.  You can check my PR.

**Comment by cxw42** [comment]
Looks reasonable to me!  I do not have a local test environment set up --- @michael-tharrington ?

**Comment by michael-tharrington** [comment]
Hey there, I've pinged the team to check this out when they have a moment! Thanks to both of you — @cxw42 and @narender2031 — for reporting and working on this!

**Comment by benhalpern** [comment]
The @narender2031 fix has been merged

https://github.com/thepracticaldev/dev.to/pull/6636

**Comment by cxw42** [comment]
@benhalpern @michael-tharrington @narender2031 Thank you!  I confirm I was able to read the privacy policy during onboarding, so the issue I experienced is fixed.

I have also now completed onboarding ;) .
