### ISSUE TITLE
Chat: UI tweak for delete and edit buttons for messages

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#5222]
**Is your feature request related to a problem? Please describe.**

I think we should tweak/enhance the UI/positioning of the `Delete` and `Edit` buttons that appear on hover on chat messages. 

It's weird that Delete is so easily accessible and it's the first item from left to right

**Describe the solution you'd like**

Since `Delete` and `Edit` shouldn't be features that are used all the time we might want to hide them in a dropdown menu.

It'd be nice to add a shortcut to help delete the last written message, like "arrow up" in Slack that lets people edit their own latest message

**Describe alternatives you've considered**

1. swap `Edit` and `Delete`
2. only put `Delete` in a dropdown

**Additional context**

![Screenshot 2019-12-23 at 4 07 53 PM](https://user-images.githubusercontent.com/146201/71365429-440dbc00-259f-11ea-8fce-43d4b6101e28.png)

**Comment by worst-developer** [comment]
Hey! I'd like to join open source contribution. I really enjoying reading dev.to and really want to make this resource better. I have some ideas regarding UX/UI messages 

- WDY to add a small edit icon to the right?
- WDY on select show on the top edit/delete buttons?

Both examples are from vk.com UI:
https://gyazo.com/7e4b3a1fc12136d3fbe5f8a708d3c49e

https://gyazo.com/939941c571d09f933d70609dadcaabf8

**Comment by rhymes** [comment]
Hi @worst-developer, I think the plan here is to move those two entries in the "usual" dropdown menu you can find around DEV:

![](https://user-images.githubusercontent.com/146201/71659994-e4a36f00-2d49-11ea-9b12-3ff3c0999754.png)
![](https://user-images.githubusercontent.com/146201/71659996-e4a36f00-2d49-11ea-8b5f-f9cf72bb8624.png)
![](https://user-images.githubusercontent.com/146201/71659997-e53c0580-2d49-11ea-92f9-2beeef5d11ad.png)
