### ISSUE TITLE
Add a web font for consistent, readable viewing across all platforms

### ISSUE THREAD

**Issue by gytdau** [thepracticaldev/dev.to#523]
## Feature Request or Task
Use a font hosted on the web so that all devices can display one known font.
### User Story / Description
Right now, the CSS references built-in system fonts, hoping that a device would have one of them to display. I think we could improve by instead using a web font because:

1. It would ensure a consistent experience for people switching from one platform to the other, such as reading on the go
2. It would help create a more memorable branding of dev.to by associating a particular font with the brand's image
3. It would prevent the possibility of some fonts that are ugly being rendered if there are no better fonts on the system

Although the page weight will increase, the increase would barely be noticeable, as some font faces can weigh as little as 15kb, and the site already automatically loads assets such as images and profile icons which are considerably heavier.

### Definition of Done
The site renders with a consistent typeface hosted on the internet.

**Comment by benhalpern** [comment]
> as some font faces can weigh as little as 15kb

I'm in favor of this exploration. And I support the purpose of the ticket. Happy to examine some specific proposals.
