### ISSUE TITLE
Update the Issue Template to Mention Browser Extensions

### ISSUE THREAD

**Issue by nickytonline** [thepracticaldev/dev.to#524]
## Task

Update the issue template with appropriate text to mention testing the issue with browser extensions disabled before submitting the issue.

### Additional Info (device/browser, helpful links)

See https://github.com/thepracticaldev/dev.to/issues/456#issuecomment-416805509

**Comment by jessleenyc** [comment]
Might make sense for us to leave a note telling folks to email us directly if they have a duplicate account/merging issue too.

**Comment by maestromac** [comment]
Resolved with #617 . If this can be done better, let us know!
