### ISSUE TITLE
Bug after editing a post

### ISSUE THREAD

**Issue by JoshCheek** [thepracticaldev/dev.to#526]
## Bug Report

Total guess (I haven't looked at code, I'm just thinking about what would make sense with what I observed): there is JavaScript modifying the page in a way that is not compatible with the backend web app.

### Current Behavior

* When I edit a comment and submit it, the post-submission page does not reflect the edit.
* When I refresh the page (thinking maybe it's a caching issue), I get a 404

Example:

* I was on this comment: https://dev.to/joshcheek/comment/54on
* I wanted to improve it, so I clicked "edit", which took me to this page:
https://dev.to/renannobile/explain-webassembly-like-im-five--3ofe/comments/54on/edit
* I edited it and submitted it, which took me to this page: https://dev.to/comments/91231
* When I refreshed that page, it 404'd

### Expected Behavior

* After submitting the edit, I should see it in the comment
* When refreshing, I should be on the same page I started on

### Additional Info (device/browser, helpful links)

The post-edit page had a path of `comments/91231`, the pre-edit page had a path of `joshcheek/comment/54on` Ignoring that one had my username in it, take note of the IDs. Assuming the bug isn't really crazy, there's probably a relationship between them. A couple of guesses later and we discover what it is:

```ruby
91231.to_s 26 # => "54on"
```

Maybe an additional point of interest (just an observation, not directly relevant): `Integer#to_s(26)` means there will be 10 digits and 16 letters (after it gets to 9, it begins counting in letters). Going to 36 would represent 10 digits and 26 characters, so it would grow slower than the current algorithm (relevant b/c it means smaller slugs). If you write your own, you could differentiate uppercase and lowercase for another 26 letters. And there's probably an established conclusion about the best way to balance these two requirements. I don't know what it is, but playing around a bit I found [this](https://gist.github.com/JoshCheek/c25b12ac3d188cfac4f5f480c02da19f), which grows very slowly (base of 64).

**Comment by JoshCheek** [comment]
Is this still broken? I'm pretty sure I went through the same process yesterday and did not hit it, so I was assuming that it had been fixed.

**Comment by Zhao-Andy** [comment]
I believe so, we haven't made any pushes to resolve it.

**Comment by Zhao-Andy** [comment]
Hm I think this is resolved. Closing.
