### ISSUE TITLE
Not able to edit my profile. It keeps showing spam_

### ISSUE THREAD

**Issue by paulann1** [thepracticaldev/dev.to#5271]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by maestromac** [comment]
Hello @paulann1 , this looks an issue specific to your account. Please email yo@dev.to for more help.
