### ISSUE TITLE
Reading list count becomes "empty" when selecting a tag

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#5272]
**Describe the bug**

This is probably a regression because I know it used to work, but apparently the count of articles in the reading list takes the value `empty` when selecting a tag. The same happens when unselecting the tag or going to the archive. The only way to restore the count is to do a full refresh of the page

**To Reproduce**

1. Go to https://dev.to/readinglist - verify the count in parenthesis is an actual number
2. select a tag on the left sidebar
3. See that the count instead becomes `empty` even if the tag itself has items

**Expected behavior**

I'd expect the count to reflect the number of items tagged with the selected tag

**Screenshots**

![reading list](https://user-images.githubusercontent.com/146201/71541898-db885b80-295f-11ea-86bd-08ea43cf139b.gif)

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Firefox
- Version: 71

**Comment by mvasigh** [comment]
I can work on this, I worked on the reading list a couple of months ago and wondering if I introduced a bug.

**Comment by rhymes** [comment]
Go ahead @mvasigh, thank you!
