### ISSUE TITLE
ListingDashboard JS test fails in certain time zones.

### ISSUE THREAD

**Issue by keithrbennett** [thepracticaldev/dev.to#5279]
I am in the Indochina time zone (ICT, which is UTC+7). The "ListingDashboard should load listing dashboard" test fails because the date in local time is not equal to the date in UTC time.

**To Reproduce**

1. Set system time zone (or test time zone) to UTC+7 (or above).
2. Run `yarn test`.

**Expected behavior**

This test passes in most time zones. This is expected. However, in UTC+7 it fails (see screenshot
 below).

**Screenshots**

![time-zone-test-error](https://user-images.githubusercontent.com/28410/71570258-c0a41b80-2b06-11ea-923f-7312849eb66d.png)

**Desktop (please complete the following information):**

- OS: Mac OS Mojave
- Browser: N/A
- Version: N/A

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).
