### ISSUE TITLE
Multiple footers within the dashboard

### ISSUE THREAD

**Issue by developius** [thepracticaldev/dev.to#5295]
**Describe the bug**

Multiple instances of the site footer show up in the dashboard 👀 

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to https://dev.to/dashboard
2. Scroll down to bottom of page
3. Notice two footers

**Expected behavior**

There is only one footer.

**Screenshots**

<img width="810" alt="Screen Shot 2019-12-31 at 1 34 54 AM" src="https://user-images.githubusercontent.com/5836587/71582161-cc76f880-2b6d-11ea-91ae-95beb6742c0e.png">

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser: Chrome
- Version: 78.0.3904.108

**Comment by ludwiczakpawel** [comment]
I've noticed similar thing after onboarding steps after signup process on `/welcome` page:

![image](https://user-images.githubusercontent.com/108287/72430586-0e6d8480-3793-11ea-906f-58a819107771.png)

I'm not a developer so don't trust me on that but it looks to me like some issue with serviceworkers and loading footer (`shell_bottom`)..

**Comment by maestromac** [comment]
Hello @developius , can you double check if this is still an issue?

**Comment by developius** [comment]
@maestromac nope, appears fixed! 🎉

**Comment by rhymes** [comment]
Thanks @developius!
