### ISSUE TITLE
Accept both language- and highlight- when generating markdown from HTML

### ISSUE THREAD

**Issue by AaronMoat** [thepracticaldev/dev.to#5298]
Gatsby code blocks are usually wrapped in `<pre class="language-js">` or whatever the language may be. It seems `dev.to` only parses `highlight-` when importing from RSS. This mean syntax highlighting does not occur automatically when importing.

A solution would be to accept both `highlight-` and `language-`.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/5299
