### ISSUE TITLE
Feature request: Ability to disconnect Twitter and Git accounts from profile

### ISSUE THREAD

**Issue by vgrovestine** [thepracticaldev/dev.to#53]
It'd be great if one could disconnect the third-party authentication providers. Or at the very least, hide the Twitter and/or Git links from one's profile.

**Comment by pkfrank** [comment]
Hey @vgrovestine thanks for the suggestion.  This is something we've considered, but we're in favor of keeping it as-is _for the time being_.  That might definitely change in the near-future, but we want to give this decision a lot of thought before rolling out the option to hide those fields.

We think that connecting dev.to profiles with user's _real identities_ (meaning Twitter/Github, if not necessarily their _actual name_), is a fairly important characteristic of the platform.  

We recognize there are totally legitimate reasons for wanting to hide those fields, so we'll continue to give this thought and will hopefully have something available eventually.  Thanks again for the suggestion!
