### ISSUE TITLE
Invalid CERT from cloudinary

### ISSUE THREAD

**Issue by tool3** [thepracticaldev/dev.to#5323]
**Describe the bug**

Invalid certificate coming from cloudinary.com

**To Reproduce**

Go to dev.to

**Expected behavior**

a working UI ?

**Screenshots**
![](https://snipboard.io/HWDIVZ.jpg)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome/Safari
- Version: latest

**Additional context**

Failed to load resource: net::ERR_CERT_INVALID

**Comment by rhymes** [comment]
I check the website and it seems fine, could it have been a temporary issue? Can you reproduce it still?

**Comment by tool3** [comment]
Swear it happened 😳

I did check again and indeed everything seems fine now. Sorry for the false alarm 🚨😇
