### ISSUE TITLE
Publishing from RSS via Github Pages: Code blocks in numbered lists

### ISSUE THREAD

**Issue by jeikabu** [thepracticaldev/dev.to#5350]
Same problem as #1855, but when publishing from RSS where the feed is github pages.

Understand it's a problem with an upstream package, but for content pulled from elsewhere can the "hack" described in #1855 just be applied?  I've been manually fixing up posts for over a year, and doing it with the web-based text editor has gotten... old.

**Comment by rhymes** [comment]
Hi @jeikabu, sorry for the delay in the answer, if I understood correctly solving #1855 would solve this as well, so I'm going to close this in favor of the other and copy over your comment.

Thanks for the patience!
