### ISSUE TITLE
Can't see the like (heart) counter number of the comments with the dark theme applied

### ISSUE THREAD

**Issue by mdamaceno** [thepracticaldev/dev.to#5389]
I've been using the dark theme and recently I notice the like (heart) counter in the comment section is hard to see the number. The background has almost the same color of the number. This doesn't happen with the light theme.

Here are some screenshots:

Light theme:

![Screenshot_2020-01-07 Why You Shouldn't Use A Web Framework](https://user-images.githubusercontent.com/4340542/71913184-9f21e000-3155-11ea-8d96-965d8e200ba1.png)

Dark theme:

![Screenshot_2020-01-07 Why You Shouldn't Use A Web Framework - DEV Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/4340542/71913197-a5b05780-3155-11ea-97e7-1b358055acee.png)

This problem doesn't happen with the mobile version.

- OS: Manjaro Linux
- Browser: Firefox
- Version: 71.0 (64-bit)

**Comment by maestromac** [comment]
Hello @mdamaceno . Are you still experiencing this issue? I was unable to reproduce it

![image](https://user-images.githubusercontent.com/15793250/74702244-66a30680-51d7-11ea-9459-eda42ad7d251.png)

**Comment by mdamaceno** [comment]
@maestromac Yes, I am. Opening the Inspect Element in Firefox, I notice the background element is #f5f6f7.

![devto-bug](https://user-images.githubusercontent.com/4340542/74770456-0fe70c80-526b-11ea-9b15-4b0e56b357a0.png)

Is this element programmed to get the background color from OS?

**Comment by maestromac** [comment]
No, it's not based on your OS's background color. The font there has `color: $black;` hardcoded to it so I wonder if this is particular to your system. If you don't mind trying, are you able to reproduce this error on Chrome? can you also swap back and forth between theme to see if that makes a difference?

**Comment by mdamaceno** [comment]
@maestromac You're right! I've found the reason for the problem. It was an extension https://addons.mozilla.org/en-US/firefox/addon/fix-dark-theme-input-boxes/?src=search. Disabling it, the number appears normally. Thanks for your help and time!

**Comment by maestromac** [comment]
Happy to help 😄 . Let us know if this ever comes up again.
