### ISSUE TITLE
Add "refresh now" for RSS feed publishing

### ISSUE THREAD

**Issue by danieljsummers** [thepracticaldev/dev.to#539]
### User Story / Description

When publishing from an RSS feed, we pretty much have to wait until it is refreshed. When I write, sometimes I have a finite period of time I can devote to it; if I could force a refresh of posts via RSS, I could cross-publish on DEV in the same session, rather than coming back every few hours to see if the draft has made it there yet.

### Definition of Done

There is a way (possibly on the Dashboard, but wherever it would fit best) for a user to kick off a refresh of their published-from RSS feed.

**Comment by jessleenyc** [comment]
Yeah, great issue. Definitely makes sense to have a refresh button right on settings/publishing-from-rss.

**Comment by Zerquix18** [comment]
In the RSS settings form, it says that "Your feed will be fetched every time you submit this form". If that's the case, then this is already fixed :smile:

**Comment by maestromac** [comment]
Hey @Zerquix18 ! while the Submit button is already doing the job, it makes more sense to have a "Fetch Now" button that could also be located else where on the dashboard; achieving the same functionality without sending a form update request.

**Comment by maestromac** [comment]
not stale

**Comment by pkfrank** [comment]
This is referenced in #1833 (now closed, due to duplicate), but I wanted to mention that I think adding a "last updated" or a status indicator in the UI would really help add clarity:

> 🔄Re-Fetch Articles
> _last updated on Feb 19, 4:57pm_

**Comment by bolariin** [comment]
I have some questions what is needed to resolve this issue
- Is there a preferred location on the dashboard for the "Fetch Now" button? 
- Regarding the "Fetch Now" button on the dashboard, would this only be visible to users with a RSS Feed URL?
- would the 'last updated' status indicator be located in `/settings/publishing-from-rss`?
- Is it still okay to change the button from 'submit' to 'update' as suggested in #1833?

**Comment by maestromac** [comment]
@bolariin as a start
- the button can be in `https://dev.to/settings/publishing-from-rss`
- It should only be visible to folks with RSS Feed URL
- `last updated` status can also be located said tab.
- Yeah the `submit` button can serve dual functionality.
