### ISSUE TITLE
Confirmation instructions link for e-mail change is broken.

### ISSUE THREAD

**Issue by neex-io** [thepracticaldev/dev.to#54]
I am getting an error when clicking on the link from confirmation e-mail.
![008d7aab-b79a-4ecd-b4ea-14f790d3242d](https://user-images.githubusercontent.com/27299612/27557287-e1f79f76-5a6d-11e7-8b81-e5c6dd43dfda.png)

**Comment by jessleenyc** [comment]
Thanks for the flag!

**Comment by Zhao-Andy** [comment]
Fixed, thanks for the heads up :)

**Comment by neex-io** [comment]
Works. Thanks for fixing it so fast.
