### ISSUE TITLE
Give users easier access to MY READING LIST

### ISSUE THREAD

**Issue by BassemMohamed** [thepracticaldev/dev.to#542]
### Description

I dont know about every user, but i find myself doing the following senairo most of my time surfing dev.to. What i do is : 

1. Scroll through the feed
2. Save every article i find interesting to my reading list
3. Go through my reading list
4. Read every article

With this approach i go from any random post to my reading list many times. As of now, there is no easy way to do this. You have to go to homepage then click on stacks icon to open the menu then choose MY READING LIST

I just wish there is an easier way. Maybe: 

1. Having the side menu open from somewhere in the post
2. Having the reading list open from somewhere in the post 
3. Add a link in the drop-down menu when you click on the profile icon in the header ( Proposed by @edisonywh )

NP: I am using dev.to on mobile device, Most users will be too i guess. 

### Definition of Done

Having the reading list 1 click away from any post or article.

**Comment by edisonywh** [comment]
I can think of one way where we add a link in the drop-down menu when you click on the profile icon in the header?

**Comment by maestromac** [comment]
Resolved with #570
