### ISSUE TITLE
Why heart count on post list isn't the same as heart count on page?

### ISSUE THREAD

**Issue by user753** [thepracticaldev/dev.to#5432]
They have different icons. Does it mean they are different thing? If so it isn't clear what is the difference.
For example https://dev.to/top/year top post has **6456** hearts but on post page https://dev.to/simonholdorf/9-projects-you-can-do-to-become-a-frontend-master-in-2020-n2h it has **1995**.

**Comment by miku86** [comment]
If you have a close look at your first link, you can see, that the heart icon has two small things behind it.

If you then go to your second link and sum all three icon numbers, you can see, that they sum to the number from your first link.

**Comment by user753** [comment]
@miku86 Thanks. It reminds me of this image https://i.redd.it/1hgm77vrme841.png

I think hover like `heart + unicorn + reading list` would be helpful.

**Comment by rhymes** [comment]
Closing this, glad someone already answered with the explanation. 

@user753 if you would like to suggest adding the hover, please open a separate PR

Let me know if you further questions about this
