### ISSUE TITLE
Cannot create Stackbit integration

### ISSUE THREAD

**Issue by fyodorio** [thepracticaldev/dev.to#5440]
**Describe the bug**

I want to create a static site using dev.to->Stackbit integration from dev.to settings, but fail at the step of connecting dev.to (at Stackbit wizard)

**To Reproduce**

1. Go to [https://dev.to/settings/integrations](https://dev.to/settings/integrations)
2. Connect to Stackbit
3. Return to p.1 destination, click `Create New Stackbit Site`
4. Choose Ampersand theme, Jekyll generator, proceed to integrations
5. Click `Connect` on dev.to card
6. After some time a browser window emerges with dev.to offline interface (loader animation blinks for some time in the middle of the screen)

**Expected behavior**

Static site is successfully created (*I had succeeded with Stackbit when did the same flow but without dev.to integration/connection - just [simple Jekyll site](https://github.com/fyodorio/dev-to-to-not-dev-to) with Ampersand theme deployed to netlify*)

**Screenshots**

![](https://raw.githubusercontent.com/fyodorio/file-storage/master/devto-issue.png)

**Desktop:**

- OS: macOS Catalina
- Browser: Chrome, Safari
- Version: 79.0.3945.117 (Chrome), 13.0.4 (Safari)

**Smartphone:**

Didn't try

**Comment by benhalpern** [comment]
Sorry about that. I believe we found the fix.

**Comment by fyodorio** [comment]
The issue persists, for me at least

**Comment by benhalpern** [comment]
Hey, this was merged but the server-side cache hadn't cleared. Did that now. It still won't work for _everyone_ yet because browsers recycle serviceworkers on a periodic basis I believe.

If you update or unregister your serviceworkers from browser tools it should work. And it should work for everyone once local caches recycle.

**Comment by fyodorio** [comment]
Yay! Success! Thanks a lot, Ben! 👍
I want to mention that this integration is awesome, and I like Stackbit very much, their Live Site widget is so handy!
