### ISSUE TITLE
Allow "authorization services" to be defined by a site config.

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/dev.to#5445]
**Is your feature request related to a problem? Please describe.**

As a future user of a generalized version of the site, I'd want to be able to offer other auth paths, such as Facebook or Google or straight email.

We hold dear the notion of reducing spam and abuse through authorization restriction, but we can come up with additional ways to do this in the future. I don't think we should create _new_ auth that doesn't bring with it some help verifying bot/abuse issues, but we can at least offer `twitter` and `github` as config to remove one or the other depending on people's use cases. (e.g. if my use case is not dev-related, GitHub will only confuse folks).

**Describe the solution you'd like**

A `SiteConfig` array of auth providers, e.g. `["twitter", "github"], and then subsequent UI adjustments where we list both auth links.

The default should be `twitter,github` and we should verify to disallow other providers before the functionality is built into the site.

**How to go about this**

See other site config PRs like this:

#5426 

For example of how to do this. The PR should include adjustment to `site_config.rb` and the internal config UI and controller, alongside the user-facing adjustments that the config applies.

**Comment by majakomel** [comment]
I'll work on this one 🙋🏼‍♀️

**Comment by rhymes** [comment]
@majakomel since this one is a major issue I think it warrants a discussion before you dive into the PR. 

Sorry if we haven't made it clear before.

How would you approach this? Unfortunately some parts of our code are tied to having either twitter or github as authentication sources

**Comment by majakomel** [comment]
ah, my bad @rhymes, I underestimated scope of this one. since I'm not that familiar with the code I'll stick with good first issues for now. sorry!

**Comment by rhymes** [comment]
Solved by https://github.com/thepracticaldev/dev.to/pull/7259 and https://github.com/thepracticaldev/dev.to/pull/7505
