### ISSUE TITLE
Problem with seeds when try to setup the project

### ISSUE THREAD

**Issue by luchiago** [thepracticaldev/dev.to#5450]
**Describe the bug**
I was trying to setup the project again because I removed it from my machine. I dropped the databases that were generated in the last install. However, when I run `bin/setup`, I was unable to complete the installation

**To Reproduce**
Run `bin/setup`

**Expected behavior**
Be able to finish the setup of the project

**Screenshots**
![failure](https://user-images.githubusercontent.com/30028621/72197958-fe0d8080-3405-11ea-89bb-95a41de0e2f1.png)

**Desktop (please complete the following information):**

- OS: Manjaro Linux 18.1.5 "Juhraya"

**Additional context**
If this a real problem, that happened with other people, I have the solution implemented on my machine and I can open a PR to correct.

**Comment by Zhao-Andy** [comment]
Huh, that's a funny bug. Thanks for raising it. Feel free to make a PR!
