### ISSUE TITLE
Blank "Report vulnerabilities" page

### ISSUE THREAD

**Issue by sivaraam** [thepracticaldev/dev.to#5456]
**Describe the bug**
When I try to visit the ["Report vulnerabilities"](https://dev.to/security) page in Chrome I only see a blank page. I am not able to see the content. The content seems to be present but invisible as I am able to scroll the page and am able I am able to see the actual content of the page if I remove the `visibility: hidden;` CSS property from `div#page-content` via developer tools.

This does not seem to be happening in Firefox though.

**To Reproduce**
1. Visit https://dev.to/security using Chrome

**Expected behavior**
I am able to see the contents of the page.

**Screenshots**
Screen cast showing the blank page behaviour in Chrome:
https://youtu.be/O8ZuvG_obo8

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser: Chrome
- Version: 79.0.3945.117

**Comment by rhymes** [comment]
Great catch @sivaraam. I have the same issue with Chrome 79 on macOS 10.14.6

**Comment by abdellani** [comment]
Hi,
I'm not having that problem in my google chrome under Ubuntu 18.04
```
user@u758:~$ cat /etc/issue
Ubuntu 18.04.3 LTS \n \l

user@u758:~$ google-chrome --version
Google Chrome 76.0.3809.132 
```
![Screenshot from 2020-01-13 16-12-13](https://user-images.githubusercontent.com/16113997/72266912-8155ee80-361f-11ea-947d-4428c7ca21f4.png)

**Comment by sivaraam** [comment]
It looks like this is fixed now!

**Comment by rhymes** [comment]
Tried with Chrome 79 and Microsoft Edge 79 and they both work. @abdellani, I'm going to close this now.
