### ISSUE TITLE
Can't post comments

### ISSUE THREAD

**Issue by MarkoShiva** [thepracticaldev/dev.to#5459]
**Describe the bug**
Can't post any comments to dev.to community and cannot save posts to reading list or like them.
The UI show saved post but after I refresh the page its not saved. 
The same error is on the android app. 
When I try to post comment I get three dots.

**To Reproduce**
login open any post try to like it and save it to reading list. 
refresh the page the likes are gone. 
try posting a comment. it doesnt.

**Expected behavior**

I should be able to add posts to my reading list and to like posts as well as comment.
The problem appeared 2 months ago and I stopped using dev.to.

**Screenshots**

 
![dev to error](https://user-images.githubusercontent.com/993923/72210885-3a061b80-34c2-11ea-9d73-fe0042d80beb.png)

**Desktop (please complete the following information):**

- OS: ArchLinux - Linux x86_64
- Browser: Chrome-dev, Firefox Nightly, Firefox developer
- Version:

**Smartphone (please complete the following information):**

- Device: Nexus 5X
- OS: Android
- Browser: Dev application
- Version: Current and current beta tested.

**Additional context**
This are the links that appear in the chrome development tools when I try to like or post. 

```
Unchecked runtime.lastError: The message port closed before a response was received.
3base-86524fdcd13e5f8668ca3d5d2e86e80b98dbf573b9301f1892d291d461153f83.js:3 POST https://dev.to/reactions 404
(anonymous) @ base-86524fdcd13e5f8668ca3d5d2e86e80b98dbf573b9301f1892d291d461153f83.js:3
Promise.then (async)
reactToArticle @ base-86524fdcd13e5f8668ca3d5d2e86e80b98dbf573b9301f1892d291d461153f83.js:1
t.<computed>.onclick @ base-86524fdcd13e5f8668ca3d5d2e86e80b98dbf573b9301f1892d291d461153f83.js:1
base-86524fdcd13e5f8668ca3d5d2e86e80b98dbf573b9301f1892d291d461153f83.js:3 POST https://dev.to/comments 404
(anonymous) @ base-86524fdcd13e5f8668ca3d5d2e86e80b98dbf573b9301f1892d291d461153f83.js:3
Promise.then (async)
handleCommentSubmit @ base-86524fdcd13e5f8668ca3d5d2e86e80b98dbf573b9301f1892d291d461153f83.js:2
```

**Comment by MarkoShiva** [comment]
@benhalpern @jessleenyc  Can anyone review the issue? I can't use dev.to for a months.

**Comment by jessleenyc** [comment]
Hey, it looks like you're experiencing an individual account issue. If you haven't already, please email yo@dev.to for support and we will handle it from there.

**Comment by MarkoShiva** [comment]
Thanks it's solved.
