### ISSUE TITLE
Editor guide: update documentation to reflect the newer editor settings

### ISSUE THREAD

**Issue by osde8info** [thepracticaldev/dev.to#5461]
using windows10 ff72

on page https://dev.to/new in "Editor Guide 🤓" it says "We have two editor versions. If you prefer Jekyll-style "frontmatter", switch to "v1" in /settings/misc."

there is no such option on the https://dev.to/settings/misc page or https://dev.to/settings/ux page

UNLESS 

"basic markdown" means "jekyll"

**Comment by rhymes** [comment]
Yep, we need to update the docs.

basic markdown is the jekyll style front matter, formerly v1
rich + markdown is the newer editor, formerly v2

you can find them in https://dev.to/settings/ux
