### ISSUE TITLE
Not able to finish setup on gitpod

### ISSUE THREAD

**Issue by luchiago** [thepracticaldev/dev.to#5464]
**Describe the bug**
I'm not able to finish the setup on gitpod bc redis installation is missing or isn't running at all.

**To Reproduce**
Try to start a fresh workspace on gitpod with branch master in dev.to repository.

**Expected behavior**
It's expected that gitpod could finish the setup.

**Screenshots**
![image](https://user-images.githubusercontent.com/30028621/72218214-2f29a600-3517-11ea-9c35-1f7ddace937e.png)

**Desktop (please complete the following information):**

- Browser: Chromium
- Version: 79.0.3945.88

**Comment by rhymes** [comment]
It looks like we're missing Redis in the GitPod's configuration. I found this on how to add it: https://www.gitpod.io/blog/gitpodify/#redis

**Comment by luchiago** [comment]
@rhymes So, can I open the PR to fix?

**Comment by citizen428** [comment]
@luchiago Yes, please open a PR, thank you 😃

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/5528
