### ISSUE TITLE
where can i see a list of all my liked articles ?

### ISSUE THREAD

**Issue by osde8info** [thepracticaldev/dev.to#5470]
or do i need to like AND add to reading list ?

the problem is ive liked about 100 articles and cant find them again

**Comment by rhymes** [comment]
Hi @osde8info, there's no list of liked articles presently

Could you adhere to the "feature request" template format in the future? 

Thank you!

**Comment by osde8info** [comment]
sorry i clicked feature request in github but it lost it

incidentally github have this exact feature 

https://github.com/osde8info?tab=stars

**Comment by osde8info** [comment]
thanks ive refound the link

https://github.com/thepracticaldev/dev.to/blob/master/.github/ISSUE_TEMPLATE/feature_request.md

i assumed clicking github feature request would insert it automatically

**Comment by osde8info** [comment]
> Hi @osde8info, there's no list of liked articles presently
> 
> Could you adhere to the "feature request" template format in the future?
> 
> Thank you!

@rhymes i think i understand how templates work now 

does this bug match the bug template ?

https://github.com/thepracticaldev/dev.to/issues/5499

**Comment by johncurcio** [comment]
There's an open request to implement this feature at #1806, so I think this issue can be closed. As of now, adding to your reading list is the only way to save the article.

**Comment by rhymes** [comment]
Thank you @johncurcio for digging it out, I'm closing this in favor of https://github.com/thepracticaldev/dev.to/issues/1806
