### ISSUE TITLE
Write a post in error show

### ISSUE THREAD

**Issue by LenaCharles** [thepracticaldev/dev.to#5497]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hi @LenaCharles, can you explain a bit more what happened?

**Comment by rhymes** [comment]
Closing this as the user hasn't provided any info!
