### ISSUE TITLE
Return a 429 Too Many Requests Error When Comment Creation Rate Limit Exceeded

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#5503]
When a user exceeds the rate limit set for comment creation we raise a [RuntimeError](https://app.honeybadger.io/projects/66984/faults/59496497) which is not very helpful for those monitoring errors or the user creating the comments. 
```
comments_controller.rb  50 create(...)
[PROJECT_ROOT]/app/controllers/comments_controller.rb:50:in `create'
48   # POST /comments.json
49   def create
50     raise if RateLimitChecker.new(current_user).limit_by_action("comment_creation")
51 
52     @comment = Comment.new(permitted_attributes(Comment))
```

Instead of raising a generic RuntimeError we should be raising/returning a 429 Too Many Requests status. We can then ignore this error in Honeybadger and simply track it passively in Datadog and Honeycomb.

Honeybadger: https://app.honeybadger.io/fault/66984/4962bbd77a4f5b3d19bed3e23e420d16

**Comment by citizen428** [comment]
This has been taken care of in #5504
