### ISSUE TITLE
Handle Reactions Without Users When Sending Notifications

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#5508]
Honeybadger: https://app.honeybadger.io/fault/66984/bb6f187a11866cd6a2b3e8990dc3f238
```
NoMethodError: undefined method `id' for nil:NilClass
notifications.rb  4 user_data(...)
[PROJECT_ROOT]/app/services/notifications.rb:4:in `user_data'
2   def self.user_data(user)
3     {
4       id: user.id,
5       class: { name: "User" },
6       name: user.name,
```
We currently have 3 Sidekiq jobs that hit this error while trying to send reaction notifications. We do not delete reactions when users are removed so we need to be able to handle those during processing. [Here is where we are making the call to get the user data](https://github.com/thepracticaldev/dev.to/blob/master/app/services/notifications/reactions/send.rb#L30) that is causing the error. I think ideally we would scope out reactions without users when we gather the siblings in the line above but when I tried to do that I got some eager loading errors.

**Comment by abdellani** [comment]
Hi @mstruve 
I will work on it :)

**Comment by mstruve** [comment]
@abdellani Thank you!!!!

**Comment by abdellani** [comment]
Hi,
I know that I'm moving too slow. Sorry about that, I'm still exploring the project.

Here is a summary of what I understood. 
* When a user reacts to a reactable ( Comment or Article),  ReactionsController searches then destroys or creates a reaction that has the following attributes:
  * user_id
  * reactable_id
  * reactable_type
  * category
* After that, it sends a notification using `Notification.send_reaction_notification` with two arguments : `reaction` and `react.reactable.user` (the owner of the comment/article).
* At the `notification` model, if the two checks are not passed `react.skip_notification_for?` and `UserBlock.blocking?`, a worker will be called with two arguments `reaction` and `receiver`
  * `receiver_data` will be the owner ( and in some cases the organization)
  *  `reaction_data` will store `reactable_id`, `reactable_type` and `reactable_user_id`
* The worker `NewReactionWorker` will call the service `Notifications::Reactions::Send.call`

At the service level, I'm confused. I'm not sure that I understand `where.not` part in the following code. Is it trying to avoid sending a notification in case the user likes his own reactable? 

```Ruby
        reaction_siblings = Reaction.where(reactable_id: reaction.reactable_id, reactable_type: reaction.reactable_type).
          where.not(reactions: { user_id: reaction.reactable_user_id }).
          includes(:reactable, :user).
          order("created_at DESC")
```

**Comment by lightalloy** [comment]
I believe it is to avoid including the user's own reactions to a notification (so you are right).

**Comment by abdellani** [comment]
Hi @mstruve 
I was able to trigger the same error by following these steps: 
1- Create one account using Github
2- Create a post using that account 
3- Delete the account using `User.last.delete`
4- The post is showing in `top/week`
5- When I click  on save without logging in, I get the following exception 
```ruby
ActiveRecord::RecordNotFound (Not Found)

ActiveRecord::RecordNotFound - Not Found:
  app/controllers/application_controller.rb:17:in `not_found'
  app/controllers/stories_controller.rb:226:in `assign_user_and_org'
  app/controllers/stories_controller.rb:214:in `assign_article_show_variables'
  app/controllers/stories_controller.rb:203:in `handle_article_show'
  app/controllers/stories_controller.rb:22:in `show'
```   
5- Log in from another account (I created a new account using the same github account)
6- Access the post
7- The following error shows up
```Ruby
NoMethodError - undefined method `username' for nil:NilClass:
  app/models/article.rb:15:in `user_username'
  app/models/reaction.rb:119:in `reactable_user'
  app/models/reaction.rb:41:in `index_to_algolia'
  app/controllers/reactions_controller.rb:58:in `create'
``` 

Also, I noticed that when an account is deleted using "delete", all the comments, posts and reactions related to that account disappear. Even if they are still present in the database. Is that expected behavior? if the answer is yes, so there is a problem in `top/week` that is causing this bug.
