### ISSUE TITLE
Allow Comments Without a Commentable to be Edited and Destroyed

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#5511]
Honeybadger: https://app.honeybadger.io/fault/66984/7ab3e6451868d27d1c907d27a97726e9
```
ActionView::Template::Error: undefined method `id' for nil:NilClass
edit.html.erb  4 _app_views_comments_edit_html_erb___1931409136324096493_70244115644840(...)
[PROJECT_ROOT]/app/views/comments/edit.html.erb:4:in `_app_views_comments_edit_html_erb___1931409136324096493_70244115644840'
2   class="comments-container"
3   id="comments-container"
4   data-commentable-id="<%= @commentable.id %>"
5   data-commentable-type="<%= @commentable.class.name %>">
6   <h1 style="padding-top:8%;text-align:center">Editing comment</h1>
```

When an article gets destroyed we do not destroy its comments. We believe that comments belong to the individual that wrote them and that they might want to share them in the future regardless of the Article. However, there are a few places in our code where we don't handle the missing commentable(for example article) well and this is one of them.

**Comment by m0rozov** [comment]
Hi @mstruve! How can I repeat this error locally?

**Comment by mstruve** [comment]
- Create an article
- Add a comment to it
- Copy the comment Permalink
- Delete the article
- visit the comment permalink
- Hit edit

**Comment by twinsfan421** [comment]
@mstruve this one is related to issue #5170 and PR #5199  Allow Comments From Deleted Articles To Be Viewed.  You will also have the same problem if you try to delete a comment without a commentable. The error will happen in the destroy action of the comments_controller when you set the `@commentable_path = @comment.commentable.path` instance variable.  You could redirect to home if there is no commentable.

**Comment by mstruve** [comment]
Well this is embarrassing, that PR (#5199)  should have been merged ages ago! Going to look at it myself and re-request a review from @rhymes.  

Yeah, I would suspect destroy is likely broken as well. I only saw a Honeybadger for the edit path being broken which is what spurred the creation of this issue.

**Comment by mstruve** [comment]
And sure enough we hit the destroy error: https://app.honeybadger.io/fault/66984/09f8a3a5a3a4295ed3c16fc5abccbc62

**Comment by twinsfan421** [comment]
@mstruve Is someone working on this?  I am happy to knock this out since it's related to the 5199. It could be a good first issue though if someone else want's to complete it.

**Comment by mstruve** [comment]
@twinsfan421 go for it! I have been making lots of Issues lately from Honeybadgers so there are plenty of good little first issues to go around 😉

**Comment by brobertsaz** [comment]
@mstruve Should this be closed seeing as PR was merged?
