### ISSUE TITLE
Badly formed social media cards

### ISSUE THREAD

**Issue by aaronpowell** [thepracticaldev/dev.to#5516]
After a recent update to my website the RSS import doesn't parse my code blocks properly and results in a `Liquid syntax error`. This is an easy fix for me by just editing the markdown and correcting the code blocks, but I noticed another side effect, the Twitter social media cards are appearing with the `Liquid syntax error` still:

![image](https://user-images.githubusercontent.com/434140/72382751-15ce6700-376e-11ea-8a82-fd73911b73fd.png)

[Here's the tweet in question](https://twitter.com/Azure/status/1217179830426488832) and [this is the DEV post](https://dev.to/azure/generating-images-with-azure-functions-5a49).

If I was to take a guess it'd be that the `og:description` meta tag is still using the original corrupt content. which is obviously incorrect.

**Comment by Zhao-Andy** [comment]
Hey @aaronpowell, sorry about that issue! Looks like the description didn't update itself properly. I've updated manually for now.

Using the Twitter card validator, it looks like it works properly now: https://cards-dev.twitter.com/validator

Not sure if Twitter clears the caches of old cards though, so the Azure tweet's description might linger.

As for the bug itself, I think we'll want to make sure description updates whenever there are changes to the markdown. I would guess that's already the case, but seems like there's a bug.

**Comment by guivinicius** [comment]
Is this still an issue? If so I could take some time to investigate that.

**Comment by aaronpowell** [comment]
Nope.
