### ISSUE TITLE
Make RateLimitChecker configurable

### ISSUE THREAD

**Issue by citizen428** [thepracticaldev/dev.to#5520]
Based on a [comment](https://github.com/thepracticaldev/dev.to/pull/5504#discussion_r366442986) by @rhymes in #5504:

> In an ideal situation `RateLimitChecker` would be configurable, I really don't like that limits are hardcoded but we aren't there yet. Maybe we can do that in a separate PR? 

**Is your feature request related to a problem? Please describe.**

`RateLimitChecker` currently hard-codes the different rate limits, which makes it less flexible than it could and probably should be.

**Describe the solution you'd like**

Store configuration options for `RateLimitChecker` in the DB instead of hardcoding them in `app/labor/rate_limit_checker.rb`.

**Describe alternatives you've considered**

Leave as is.

**Additional context**

The main discussion we still need to have around this is wether or not we want to add these new options to `SiteConfig` or introduce a new `RateLimit` model. 

We currently already store on rate limit in `SiteConfig`, namely `rate_limit_follow_count_daily`. However, we need to add at least 5 more and potentially additional ones in the future:

*  `comment_creation`
* `published_article_creation`
* `image_upload`
* `follow_account`
* `limit_by_email_recipient_address`

**Comment by rhymes** [comment]
We could also build a global RateLimitChecker global object in an initializer that's built on boot using values in `SiteConfig`.

I'm proposing this because it might make sense to require a restart to change rate limits, maybe or maybe not.

Anyway I'm +1 on moving them to `SiteConfig` and we can always complicate things later if we need to

**Comment by citizen428** [comment]
Ok, let me clarify: when i say "model", I don't necessarily mean Rails model, but domain model. Unfortunately we pretty much overloaded every single term in our profession at this point, but what I had in mind was close to what you're suggestion here.

**Comment by citizen428** [comment]
Closed via https://github.com/thepracticaldev/dev.to/pull/5521
