### ISSUE TITLE
Rich Wikipedia liquid tag

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/dev.to#5526]
It would be great if we could take a wikipedia page (or section of a page) and render it as a liquid tag that expands the content for display within a post, similar to how we do with GitHub repos etc.

https://stackoverflow.com/questions/7185288/how-to-get-wikipedia-content-using-wikipedias-api

Liquid tag docs: https://docs.dev.to/frontend/liquid-tags/

**Comment by luchiago** [comment]
Hi, can I work on this?

**Comment by maestromac** [comment]
go ahead @luchiago !

**Comment by majakomel** [comment]
Hey @luchiago, are you still planning to work on this? If not, I'd like to take it.

**Comment by luchiago** [comment]
@majakomel You can work on that. I did not have time to do it, so you can grab it

**Comment by rhymes** [comment]
Going to change the assigned person, thanks @luchiago for the update and @majakomel for offering!

**Comment by guivinicius** [comment]
Hey @majakomel are you working on this?

**Comment by majakomel** [comment]
Hey @guivinicius, I do! I got carried away a bit with other work, will try to open a PR today or tomorrow.

**Comment by guivinicius** [comment]
Cool. :)
