### ISSUE TITLE
Git commit fails because of rubocop errors in unstaged files

### ISSUE THREAD

**Issue by VegaFromLyra** [thepracticaldev/dev.to#5530]
**Describe the bug**

I set up the project recently following the clear and concise instructions [here](https://docs.dev.to/installation/docker/). But once I was ready to commit changes for my first PR, I ran into this message:

```
ashab@Ashas-MacBook-Pro dev.to (ab_test_2) $ git commit
husky > pre-commit (node v12.14.0)
  ↓ Stashing changes... [skipped]
    → No partially staged files found...
  ❯ Running tasks...
    ↓ Running tasks for *.{js,jsx} [skipped]
      → No staged files match *.{js,jsx}
    ❯ Running tasks for {app,spec,config,lib}/**/*.rb
      ✖ bundle exec rubocop --require rubocop-rspec --safe-auto-correct
        git add
    ↓ Running tasks for Gemfile [skipped]
      → No staged files match Gemfile
    ↓ Running tasks for app/**/*.html.erb [skipped]
      → No staged files match app/**/*.html.erb
    ↓ Running tasks for *.json [skipped]
      → No staged files match *.json
    ↓ Running tasks for *.md [skipped]
      → No staged files match *.md



✖ bundle exec rubocop --require rubocop-rspec --safe-auto-correct found some errors. Please fix them and try committing again.
```

I figured I had some linting errors with the staged changes so I ran the following based on the error message above:

```
docker-compose run web bundle exec rubocop --require rubocop-rspec --safe-auto-correct
```

But that ran rubocop on seemingly all the spec files and more importantly completely unrelated to my changes. I end up using the `--no-verify` flag to bypass husky ever since.

**To Reproduce**

1. Set up the `dev.to` repo using the [installation](https://docs.dev.to/installation/) steps
2. Create a new branch
3. Make a small change in one of the (non spec) ruby files (any change, like renaming a variable for instance)
4. `git add -A`
5. `git commit`

**Expected behavior**

The husky pre-commit hooks should list linting violations in the _staged_ files (not in unrelated files).

**Additional context**

```
docker-compose run web bundle exec rubocop --require rubocop-rspec --safe-auto-correct
```

Running the above gives the following results:

```
Inspecting 1143 files
..............
1143 files inspected, 27 offenses detected, 12 offenses corrected
```

**Comment by rhymes** [comment]
Doesn't `git add -A` add files to the staged area?

**Comment by VegaFromLyra** [comment]
Yep it does, what I was trying to convey is that the rubocop pre-commit hook seemingly fails regardless of which files have been staged and displays offenses in unrelated spec files. 

(Also updated the error message, realized I missed a part of the snippet)

**Comment by rhymes** [comment]
Mmm interesting

**Comment by maestromac** [comment]
Thanks for the descriptive issue @VegaFromLyra . Which lint exactly did the pre-commit hook catch? I assumed it has to be RSpec related based on your code block. 

For example, here I purposely duplicated a example spec
![Screen Shot 2020-01-16 at 3 49 21 PM](https://user-images.githubusercontent.com/15793250/72561837-0afff900-3878-11ea-8a82-66e16b1302fc.png)

**Comment by VegaFromLyra** [comment]
Sigh, my bad y'all - since I was using the docker version for everything except the pre-commit hooks, I did not have ruby 2.6.5 installed locally so rubocop was failing because of that (I resolved this so don't have the exact error message, and also I missed adding this info to the snippet above since I didn't think that was the cause the first time around).

After installing said version and bundling the app, it works as expected, sorry for the false alarm!

**Comment by maestromac** [comment]
All good @VegaFromLyra 😃
