### ISSUE TITLE
When clicking on link on mail, profile nav menu is not clickable and it has no image.

### ISSUE THREAD

**Issue by nombrekeff** [thepracticaldev/dev.to#5546]
**Description**
When I click on the **dev.to** link on the new followers mail, the profile navigation menu in not interactable, and does not contain an image. It has also happened to me a couple of times in the past.

**Steps to reproduce**
1. Click on the **dev.to** link on the new followers mail:

<img width="678" alt="Captura de pantalla 2020-01-16 a las 21 03 57" src="https://user-images.githubusercontent.com/17043260/72558849-d30eab00-38a3-11ea-887a-ab9b057865ff.png">

2. When dev.to is loaded in this url: `https://dev.to/ahoy/messages/.../click?signature=...&url=https%3A%2F%2Fdev.to%3Futm_source%3Dnotify_mailer%26utm_medium%3Demail%26utm_campaign%3Dnew_follower_email` the site renders correctly, but the profile navigation menu apears without an image and is not hoverable nor clickable, as shown in the following image:

<img width="1426" alt="Captura de pantalla 2020-01-16 a las 21 01 15" src="https://user-images.githubusercontent.com/17043260/72559047-3b5d8c80-38a4-11ea-92a3-262d61c1e1a6.png">
 
**Desktop info**
- OS: MacOS `10.15.2`
- Browser: Chrome
- Version: `79.0.3945.117`

> This also happened in the last 2 versions of chrome.

**Comment by maestromac** [comment]
Hello @nombrekeff . If this happens again, can you please share us your browser console's logs?

**Comment by nombrekeff** [comment]
Yup, here it is, it happens each time I click the link, i can easily replicate it if you need to
 <img width="1440" alt="Captura de pantalla 2020-01-16 a las 23 15 40" src="https://user-images.githubusercontent.com/17043260/72567465-3b668800-38b6-11ea-926e-8bfabf1cff1b.png">

**Comment by nombrekeff** [comment]
It also happens on the app, once it's blacked out, you must close and open the app.

Aman Kumar also came across this bug, but in another way, mentioned [here](https://dev.to/aman83770/welcome-thread-bug-in-dev-to-3fi0)

Pasting original post:
> I recently joined Dev and I was writing my introduction in the welcome thread. I wrote it and went to the home page. Again when I clicked on Dashboard in the dropdown on my profile, it was showing me you wrote nothing, write your introduction. I wrote it again and it was showing me the same. And I found there was not my post in the welcome thread. But I got a notification that someone liked my post. I am attaching some screenshots. And I found my profile dropdown was not working at that time too, It got black and was not clickable
> **Aman Kumar** in [Welcome Thread Bug in Dev.to](https://dev.to/aman83770/welcome-thread-bug-in-dev-to-3fi0)

**Comment by abrain** [comment]
This also just happened to me on the Welcome page. My browser console shows these errors:
```
11:38:29.300 SyntaxError: expected expression, got '&' welcome:5577:56
11:38:30.066 SyntaxError: redeclaration of const fetchCallback base-8ec2ef2bd76a9423d1a48f18ce87b528610167e08fd8283b72e07be20d7985db.js:1:1
11:38:30.083 NotSupportedError: 'web-share-wrapper' has already been defined as a custom element vendor-9efa27bc2ea3a11ce094.js:1
```

The SyntaxError in the welcome script should be unrelated. It got introduced with #6422 and should be fixed with #6473. The second and third error seem to be directly related to the bug, as they coincide and do not show up when the bug doesn't happen.

This bug only occurs on the https://dev.to/welcome shortcut, displaying [the post itself](https://dev.to/thepracticaldev/welcome-thread-v63-2j4p) does not show this behaviour. It also occurs when you follow the `/ahoy/` type links as described in the initial report above.

Whenever the bug with the blacked out profile nav item happens, the footer is shown twice:

![Screenshot_2020-03-07 Welcome Thread - v63](https://user-images.githubusercontent.com/1263052/76142331-11874180-606d-11ea-8ee8-d27593b6afe0.png)

**Comment by maestromac** [comment]
Hey @nombrekeff & @abrain , this issue should be resolved now. Please give those links another try and let me know if the issue still persists.

**Comment by nombrekeff** [comment]
@maestromac in my case I can confirm it is solved!
Thanks, and great work!

**Comment by abrain** [comment]
@maestromac Also works for me. Thanks :)
