### ISSUE TITLE
I can't comment not even make a post

### ISSUE THREAD

**Issue by MangaRed** [thepracticaldev/dev.to#5573]
When I try to comment in a post in the dev tools the url to comment https://dev.to/comments responds with a status of 404 and also when i click on write a post button it shows Oooops... you have encountered an error.

My browser is chrome 79 and windows 10

**Comment by rhymes** [comment]
Hello @MangaRed, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
