### ISSUE TITLE
Don't Raise Standard Error for Invalid Liquid Tags

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#5608]
There are two more places where we are raising a generic Standard Error if a liquid tag is invalid. We should update this flow so that those errors are only shown to the user and don't bubble up and break the page. 
```ruby
def parse_link(link)
    input_no_space = link.delete(" ").gsub(".js", "")
    if valid_link?(input_no_space)
      input_no_space
    else
      raise StandardError,
            "Invalid Gist link: #{link} Links must follow this format: https://gist.github.com/username/gist_id"
    end
  end

  def build_options(option)
    option_no_space = option.strip
    return "?#{option_no_space}" if valid_option?(option_no_space)

    raise StandardError, "Invalid Filename"
  end
```

Honeybadger: https://app.honeybadger.io/fault/66984/6b348042b61c88825e56b6362a3ae2f7
Related PR that Fixed YouTube Tags: https://github.com/thepracticaldev/dev.to/pull/5485

**Comment by citizen428** [comment]
This could make a good first issue for a new contributor. If you want to take this please let me know and request my review on the PR.

**Comment by majakomel** [comment]
I'd like to work on this @citizen428

**Comment by citizen428** [comment]
Great @majakomel, thanks for this! Please add me as reviewer to your PR. If you feel like you need help along the way, just open the PR and prefix the title with `[WIP]`, then ping me from a comment 😃

**Comment by rhymes** [comment]
Closed by https://github.com/thepracticaldev/dev.to/pull/5694
