### ISSUE TITLE
Stuck on Publishing even after post published

### ISSUE THREAD

**Issue by crimson-med** [thepracticaldev/dev.to#5623]
**Description**

I created a new post,  hit publish, and it was stuck on `Publishing...` evven after it had actually created the post.

**Screenshots**

<img width="1262" alt="Screenshot 2020-01-21 at 2 38 23 PM" src="https://user-images.githubusercontent.com/28290546/72781357-082c4c00-3c5c-11ea-94a2-8f62b5211fb6.png">

<img width="966" alt="Screenshot 2020-01-21 at 2 41 28 PM" src="https://user-images.githubusercontent.com/28290546/72781391-19755880-3c5c-11ea-8a05-bd3ad8771028.png">

**Desktop (please complete the following information):**

- OS: Macos
- Browser: Firefox
- Version:72.0.1

**Comment by rhymes** [comment]
Hi @crimson-med, thanks for the report! have you noticed any errors in the JavaScript console?

**Comment by crimson-med** [comment]
@rhymes yes something about r not being defined.
Is it maybe because I have other dev.to tabs open?
<img width="1264" alt="Screenshot 2020-01-21 at 7 08 32 PM" src="https://user-images.githubusercontent.com/28290546/72800131-95ce6280-3c81-11ea-8ce1-e188b3fbba31.png">

**Comment by rhymes** [comment]
Mmm do you have any extensions that might be related? As far as I know we don't have a `backend.js` file in our code base and I use the same browser as you without issue, so it might be a bug on our end or it might not be.

If you blick on the file name, where do the dev tools take you?
