### ISSUE TITLE
Cannot remove a `cover_image` from a post

### ISSUE THREAD

**Issue by vaidehijoshi** [thepracticaldev/dev.to#5630]
**Describe the bug**

When editing a post, a user is able to upload an image and use the URL provided by the image uploader to add a cover image (by including `cover_image` in the post's front matter. However, if the user decides that they don't want that cover image anymore and wishes to remove it, removing the `cover_image` option from the front matter does not remove the cover image from the post or its preview.

**To Reproduce**

1. Create a post.
2. Upload an image, and copy the provided URL.
3. Go to the post's editor. In the front matter for the post, add a `cover_url:` option, and set the value as the copied link.
4. Save the post. You should see the cover image that you just added in the post's preview.
5. Now, go back to the post's editor, and remove the `cover_url:` option entirely, including the URL you pasted earlier.
6. Click on "preview" and look at the post; it will _still_ contain the cover image, even though you removed the option.
7. You can also test that the cover image was not removed by closing the tab and navigating back to the post (the cover image will still be there, even though the front matter will not contain a `cover_url` option).

**Expected behavior**

I would expect that once the `cover_url:` option is removed from the frontmatter, the post should no longer have a cover image.

**Screenshots**

As you can see from the screenshots, once you remove the `cover_url` option from the frontmatter, the image still remains on the post, but interestingly, its resolution/size seems to change... 🤔

_Preview of initial post, without a cover image:_
<img width="1552" alt="Screen Shot 2020-01-21 at 11 11 52 AM" src="https://user-images.githubusercontent.com/6921610/72836189-fdb08900-3c40-11ea-81e9-b7b15bfcb27a.png">

_Preview of the post with a cover image added:_
<img width="1552" alt="Screen Shot 2020-01-21 at 11 12 09 AM" src="https://user-images.githubusercontent.com/6921610/72836279-20db3880-3c41-11ea-9271-c1258019a8f1.png">

_Preview of the post in editor mode, after the `cover_url` option has been explicitly removed:_
<img width="1552" alt="Screen Shot 2020-01-21 at 11 12 30 AM" src="https://user-images.githubusercontent.com/6921610/72836333-37818f80-3c41-11ea-9dcd-b3f940ac82a2.png">

_Preview of the post, with a stretched cover image, even though there is no option for it in the front matter:_
<img width="1552" alt="Screen Shot 2020-01-21 at 11 12 36 AM" src="https://user-images.githubusercontent.com/6921610/72836375-52ec9a80-3c41-11ea-9ef6-ea56bc794f6e.png">

**Desktop (please complete the following information):**

OS: Mac Mojave 10.14.5
Browser: Chrome
Version: 79.0.3945.130 (Official Build) (64-bit)

**Additional context**

I tested this repro by creating a draft post of my own [here](https://dev.to/vaidehijoshi/testing-a-post-for-cover-images-512i-temp-slug-1465493?preview=f852633c2eee97d53c07a17e5422cd64999b971b9360ab8d9f91e967ae104dfd1d4856ad6e5acbf542d06b1043cd25f58486d172de4b7bfec6b23633).

**Comment by vaidehijoshi** [comment]
I'm investigating this! It appears to be a JS issue, since we definitely don't appear to be serializing the `cover_image` property in the front matter if it doesn't exist on the backend.

**Comment by vaidehijoshi** [comment]
Woops, this got closed because i used "fixes" in my commit message. Reopening because there is still another issue (on the Rails side) that @rhymes pointed out to me [here](https://github.com/thepracticaldev/dev.to/pull/5660#pullrequestreview-347173956). I've already started investigating that, and will PR it separately.

**Comment by vaidehijoshi** [comment]
Sigh...looks like the same issue occurs with `canonical_url` as well 😞

I have [a PR to fix this issue](https://github.com/thepracticaldev/dev.to/pull/5687), and if folks are cool with my approach there, I can fix the same issue for canonical url. I just don't want to fix it yet in case others want to solve this a different way! :)

**Comment by dabrady** [comment]
FYI this issue seems to apply to the "V2" editor as well, so I presume they use the same underlying mechanism for working with cover images:

![Jan-25-2020 18-10-29](https://user-images.githubusercontent.com/2475919/73125376-0507c780-3f9e-11ea-80e6-6fbcb9177119.gif)

**Comment by vaidehijoshi** [comment]
@dabrady Thanks for bringing that up! I just closed this since it should be fixed now by #5687 :) Let me know if you're still seeing this issue, though!
