### ISSUE TITLE
is our website a joke?

### ISSUE THREAD

**Issue by textita** [thepracticaldev/dev.to#5636]
I tried your website months ago and again today

I cant post a dam thing.......

either as a twiter user or githib

your website is too buggy

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by textita** [comment]
[disposable phone numbers](http://textita.com)

**Comment by rhymes** [comment]
Hello @textita, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
