### ISSUE TITLE
please add follow back buttons to https://dev.to/dashboard/user_followers

### ISSUE THREAD

**Issue by osde8info** [thepracticaldev/dev.to#5640]
**Is your feature request related to a problem? Please describe.**

please add follow back buttons to https://dev.to/dashboard/user_followers

**Describe the solution you'd like**

please add follow back buttons to https://dev.to/dashboard/user_followers

**Describe alternatives you've considered**

none

**Additional context**

please add follow back buttons to https://dev.to/dashboard/user_followers

**Comment by rhymes** [comment]
Hi @osde8info, thanks for the feature request! 

I'm going to close this as a duplicate of https://github.com/thepracticaldev/dev.to/issues/3169 which has a related PR in https://github.com/thepracticaldev/dev.to/pull/3294 but was eventually abandoned.

Anyway, the feature request is sound.

Thank you!
