### ISSUE TITLE
Create a not english tag

### ISSUE THREAD

**Issue by rodolphonetto** [thepracticaldev/dev.to#5644]
**Is your feature request related to a problem? Please describe.**

It is not a real problem but sometimes I would like to search articles on pt-br to se what people from my country are writting about.

**Describe the solution you'd like**

When writting a post it would have a combo-box or something to specify what language I'm writting (if I dont chosse it assumes en-us) So then it is filterble on searchs

**Comment by rhymes** [comment]
Hi @rodolphonetto, thanks a lot for this feature request!

I am closing yours in favor of https://github.com/thepracticaldev/dev.to/issues/4168 - let me know if I am mistaken and you're indeed proposing something different.
