### ISSUE TITLE
Liquid tags generated as Iframe in StackBit posts are broken

### ISSUE THREAD

**Issue by deepu105** [thepracticaldev/dev.to#5648]
**Describe the bug**

The Iframe content from Dev liquid tags contains Header and footer in the StackBit posts. See below from https://royal-lime-c9165.netlify.com/

It seems like the problem happens only on Chrome in non incognito mode, so I disable all the extensions to see if that was an issue but that didn't help

**To Reproduce**

Not quite sure as it seems to be only in Chrome when you are not in private mode
**Expected behavior**

Liquid tag content should not have header/footer

**Screenshots**

![image](https://user-images.githubusercontent.com/1107223/72909210-ece23f00-3d36-11ea-9ad9-5c53e55b9e2a.png)

**Desktop (please complete the following information):**

- OS: Linux (Fedora 31)
- Browser: Chrome
- Version: Version 79

**Comment by maestromac** [comment]
This was resolved with https://github.com/thepracticaldev/dev.to/pull/6019
