### ISSUE TITLE
Updating A Reaction That is Not Yours Should Result in an Unauthorized Error

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#5656]
If a user tries to update a reaction that is not theirs that should result in an Unauthorized http status code 401. Instead, we currently raise a Runtime error with no information.
```ruby
RuntimeError:
reading_list_items_controller.rb  10 update(...)
[PROJECT_ROOT]/app/controllers/reading_list_items_controller.rb:10:in `update'
 8   def update
 9     @reaction = Reaction.find(params[:id])
10     raise if @reaction.user_id != session_current_user_id # Lazy but I'm tired. HACK
11 
12     @reaction.status = params[:current_status] == "archived" ? "valid" : "archived"
```
 In the application controller, we have a not_authorized method which would probably be ideal to use here. Also make sure to add a spec for it!
```ruby
  def not_authorized
    render json: "Error: not authorized", status: :unauthorized
    raise NotAuthorizedError, "Unauthorized"
  end
```

Honeybadger: https://app.honeybadger.io/fault/66984/f528c8177977449c28b728af479486e5

**Comment by sunny-b** [comment]
I can take this one

**Comment by citizen428** [comment]
Thank you @sunny-b! 🎉 If you need any help, feel free to open a PR with a "[WIP]" prefix in the title and ping @mstruve or me in a comment.

**Comment by sunny-b** [comment]
@citizen428 @mstruve Not sure if you want to test my PR merge in prod first. Otherwise, this issue can probably be closed.

**Comment by maestromac** [comment]
Build has been deployed. Resolved with https://github.com/thepracticaldev/dev.to/pull/5658
