### ISSUE TITLE
I was getting error 

### ISSUE THREAD

**Issue by SahilPanchal** [thepracticaldev/dev.to#5691]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hi @SahilPanchal, can you elaborate? What kind of error? What were you trying to do?

**Comment by rhymes** [comment]
This looks an issue specific to your account.

Please email yo@dev.to for more help.

Thank you again :)
