### ISSUE TITLE
Request to activate my account

### ISSUE THREAD

**Issue by Ernalottie** [thepracticaldev/dev.to#5696]
Recently my profile on Dev moved into the spam. Even though I didn't spam they moved my profile into spam, what should I do for getting back my account.

**Comment by rhymes** [comment]
Hello @Ernalottie, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.

**Comment by Ernalottie** [comment]
I contact them through mail but I didn't reply from them, what should I do now? I got mail from dev.to like one of your article is related to this beritaini.net website.

But actually my content is 100% unique and also I didn't take information from them, Just because we both related to Casino and they informed its related to their website. This is totally injustice. If they do manual check, They will know the truth. and also I'm ready to modify my article incase if their is an issues. For your reference i have mention the details.

my profile url: https://dev.to/ernalottie/
Article URl: https://dev.to/ernalottie/casino-game-development-the-current-industry-and-key-pointers-to-follow-5clo
Complained Url: beritaini.net 

By chance if you guys can help, Please do it needfully 

Thanks, 
Erna
