### ISSUE TITLE
Campaign concept and settings for "Shecoded"

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#5702]
We need to create a campaign concept in the app. First, we'll use it for Shecoded and later for the other campaigns.
The campaign should have its own settings in `/internal` and be related to concepts like full-screen (#5703 ) and sidebar (#5701)

**Comment by Ridhwana** [comment]
<img width="1189" alt="Screenshot 2020-02-18 at 15 14 05" src="https://user-images.githubusercontent.com/2786819/74739369-5899c800-5261-11ea-9079-ac33aee83232.png">

**Comment by lightalloy** [comment]
Closing as done.
