### ISSUE TITLE
Handle Pundit::AuthorizationNotPerformedError From Comments Create Action

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#5717]
Honeybadger: https://app.honeybadger.io/fault/66984/9508988843fe9435805fbb822bbe8242
At some point in the comment create action we are not properly authorizing anything and I think then when we run the `after_action :verify_authorized` we end up with this error.
```
Pundit::AuthorizationNotPerformedError: CommentsController
pundit.rb  192 verify_authorized(...)
[GEM_ROOT]/gems/pundit-2.1.0/lib/pundit.rb:192:in `verify_authorized'
190   # @return [void]
191   def verify_authorized
192     raise AuthorizationNotPerformedError, self.class unless pundit_policy_authorized?
193   end
```

I am not sure what path leads to this scenario but if someone could take this issue, figure out the path that causes it and then fix it by either 
1) properly skipping the auth OR 
2) actually authenticate properly like it is supposed to

**Comment by sunny-b** [comment]
I can take a stab at this one.
