### ISSUE TITLE
I can not write content.

### ISSUE THREAD

**Issue by techmahedy** [thepracticaldev/dev.to#5727]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hello @techmahedy, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
