### ISSUE TITLE
Random twitter address in my profile

### ISSUE THREAD

**Issue by BBasile** [thepracticaldev/dev.to#573]
At the bottom of my posts, for example [this one](https://dev.to/bbasile/lessons-learnt-about-d-const-function-attribute-lac) there's a twitter address displayed. It's not mine since i don't even use Twitter and i have no idea how this has been associated to my account (registered in 2016 but started using it only 2 weeks ago)

![screenshot_20180901_140215](https://user-images.githubusercontent.com/16154339/44945778-b7f6e480-adef-11e8-9aba-f11cd68a5a35.png)

This is a bit embarassing, can you remove this _Lou********on thing?

**Comment by benhalpern** [comment]
Hey! You are user number 278 all-time. Some of our very early accounts have random bugs from this being a side project with plenty of my personal mistakes.

Just removed the Twitter handle there. If you experience other issues, let me know.

**Comment by BBasile** [comment]
thanks.
