### ISSUE TITLE
Code snippet rendering issue related to underscore

### ISSUE THREAD

**Issue by JuanitoFatas** [thepracticaldev/dev.to#5739]
Hey dev 👋 

Reporting a bug.

**Describe the bug**

There is `\` present in rendered code block.

**To Reproduce**

Have this code snippet in your post

```ruby
def init_internals
  @primary_key              = self.class.primary_key
  @readonly                 = false
  @destroyed                = false
  @marked_for_destruction   = false
  @destroyed_by_association = nil
  @_start_transaction_state = nil
  @transaction_state        = nil

  self.class.define_attribute_methods
end
```

**Expected behavior**

As GitHub renders above. Without seeing `\` in rendered code block. 

**Screenshots**

<img width="516" alt="スクリーンショット 2020-01-27 17 37 20" src="https://user-images.githubusercontent.com/1000669/73160364-21396f00-412c-11ea-9164-8c737a0a0c49.png">

Best,
Juanito

**Comment by citizen428** [comment]
@JuanitoFatas I hope you don't mind, but I just assigned you this issue so it's obvious to other that it's already being worked on.
