### ISSUE TITLE
Footer in `shecoded` rendered twice

### ISSUE THREAD

**Issue by abenettt** [thepracticaldev/dev.to#5741]
**Describe the bug**
The footer in the `shecoded` page is being rendered twice

**To Reproduce**

* Go to https://dev.to/shecoded
* Scroll down to the bottom
* Look at footer

**Expected behavior**
Only one footer to be rendered

**Screenshots**
![image](https://user-images.githubusercontent.com/7523903/73167448-2aa8e400-40f8-11ea-95f3-3073f8c6a019.png)

**Desktop (please complete the following information):**

- OS: macOS Catalina
- Browser: Chrome
- Version: Version 79.0.3945.130 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by bhanuone** [comment]
I observed this weird behaviour of showing two footers at the bottom. If I visit `https://dev.to/shecoded?signin=true`, I see no footer at all.
