### ISSUE TITLE
Offline page persisting on an article link

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#5775]
**Describe the bug**
1) I searched for 'dev.to stop donating your customer data to google' in google search. 
2) When I clicked on the first result, this article: https://dev.to/goatandsheep/stop-donating-your-customers-data-to-google-analytics-191 
3) I was hit with the offline page.

I was only able to see the article if I did a hard refresh on Chrome. When the article appeared, if I hit the regular refresh button, it would show me the offline page again.

This is the only article that I'm experiencing this with, that I'm aware of.

**Expected behavior**
I shouldn't hit the offline page!

**Screenshots**
Errr here is probably more info than you need:

![](https://p193.p3.n0.cdn.getcloudapp.com/items/YEudY7q5/Image+2020-01-27+at+4.11.02+PM.png?v=263c6671e83e8bbd36ee0bc115d7690d)

![](https://p193.p3.n0.cdn.getcloudapp.com/items/4guxv6A1/Image+2020-01-27+at+4.12.12+PM.png?v=ed7f8fe513816abc88d08fa8ea9d0c5f)

Sources tab:
![](https://p193.p3.n0.cdn.getcloudapp.com/items/v1umzJl2/Image+2020-01-27+at+4.13.42+PM.png?v=00f44b66e3eaa6ee9da88add6720a43e)

Memory tab:
![](https://p193.p3.n0.cdn.getcloudapp.com/items/v1umzJyP/Image+2020-01-27+at+4.14.47+PM.png?v=c81e32be8ab0eacd4ed53999b72245c9)

**Desktop (please complete the following information):**
- OS: macOS Catalina
- Browser: Chrome Version 79.0.3945.130

**Comment by bhanuone** [comment]
Followed the steps mentioned above. Not facing the same issue. @jessleenyc

**Comment by rhymes** [comment]
I get the offline page even just by clicking on the link. I use Firefox 73:

![Screenshot_2020-01-28 Looks like you've lost your Internet connection](https://user-images.githubusercontent.com/146201/73252141-8cca1d80-41ba-11ea-9583-c4d3646eb385.png)

hard refresh then shows me the article

**Comment by maestromac** [comment]
I think this is no longer an issue. Let's record this as a one-off and re-open the issue if it ever comes up again.
