### ISSUE TITLE
Return 404 NotFound error if ChatChannelMembership is not found

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#5790]
In our chat_channel_memberships_controller.rb are look for a membership and then attempt to authorize it. In the event that the membership is missing we end up with the following error. 
Honeybadger: https://app.honeybadger.io/fault/66984/aa161bc85a5f59b582b7949c2a14d83c
Error: 
```
Pundit::NotDefinedError: unable to find policy `NilClassPolicy` for `nil`
chat_channel_memberships_controller.rb  6 find_by_chat_channel_id(...)
[PROJECT_ROOT]/app/controllers/chat_channel_memberships_controller.rb:6:in `find_by_chat_channel_id'
4   def find_by_chat_channel_id
5     @membership = ChatChannelMembership.where(chat_channel_id: params[:chat_channel_id], user_id: current_user.id).first
6     authorize @membership
7     render json: @membership.to_json(
8       only: %i[id status viewable_by chat_channel_id last_opened_at],
```

Rather than raising `Pundit::NotDefinedError` here we should be returning a 404, not_found status. ApplicationController has a handy `not_found` method that you can use to do this. I think you will want to implement a solution similar [to this one](https://github.com/thepracticaldev/dev.to/pull/5646/files#diff-cae59de326d9d5bfb471bb23bbd25c1fR62).

**Comment by majakomel** [comment]
I'll work on this 🙋🏼‍♀️
