### ISSUE TITLE
Return 404 NotFound error if @moderatable Is Not Found

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#5791]
In the event that an article can't be found, we should exit this action early and return a 404 not found error rather than trying and failing to continue to load necessary models. 
Honeybadger: https://app.honeybadger.io/fault/66984/184d0d115e69e18889765fd6ffd15d6a
Error:
```
NoMethodError: undefined method `id' for nil:NilClass
moderations_controller.rb  22 article(...)
[PROJECT_ROOT]/app/controllers/moderations_controller.rb:22:in `article'
20     @moderatable = Article.find_by(slug: params[:slug])
21     @tag_moderator_tags = Tag.with_role(:tag_moderator, current_user)
22     @adjustments = TagAdjustment.where(article_id: @moderatable.id)
23     @already_adjusted_tags = @adjustments.map(&:tag_name).join(", ")
24     @allowed_to_adjust = @moderatable.class.name == "Article" && (current_user.has_role?(:super_admin) || @tag_moderator_tags.any
```

ApplicationController has a handy `not_found` method that you can use to do this. I think you will want to implement a solution similar [to this one](https://github.com/thepracticaldev/dev.to/pull/5646/files#diff-cae59de326d9d5bfb471bb23bbd25c1fR62).

**Comment by citizen428** [comment]
Closed via #5999
