### ISSUE TITLE
Avoid Raising NoMethodError in chat_channels with other_user is not Present

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#5792]
There are times when a ChatChannel is opened via the controller that a `other_user` for that chat channel is not present. This causes the below error to be raised when we try to index that chat channel membership and attempt to fetch the `channel_image`
Honeybadger: https://app.honeybadger.io/fault/66984/f79138e2afe22c7a949dc283ec6beec8
Error:
```
NoMethodError: undefined method `profile_image_url' for nil:NilClass
profile_image.rb  7 initialize(...)
[PROJECT_ROOT]/app/labor/profile_image.rb:7:in `initialize'
5   def initialize(resource)
6     @resource = resource
7     @image_link = resource.profile_image_url
8     @backup_link = "https://thepracticaldev.s3.amazonaws.com/i/99mvlsfu5tfj9m7ku25d.png"
9   end
```

I don't think we should ever be initializing the `ProfileImage` class with a nil resource so one fix might be to add a guard clause to check for that before initializing the class. It appears we have a lot of safety operators (`.&`) all over the ChatChannelMembership ActiveRecord model class which would indicate that we don't always expect to find an `other_user` so this appears to just be a case we forgot to handle.

**Comment by anubhav8421** [comment]
@mstruve I would like to work on this issue

**Comment by rhymes** [comment]
@anubhav8421 go ahead and thank you!

**Comment by anubhav8421** [comment]
It is my first time exploring the dev.to codebase. I was able to setup the environment as defined in the documentation. I have read through the honeybadger issue plus details provided by @mstruve . I understood that we should not initialize the `ProfileImage` object when the `resource` passed is `nil`. 

So if we just use safety operator in `resource&.profile_image_url` should suffice.

**Comment by anubhav8421** [comment]
@rhymes @mstruve can you please provide your feed back on the above comment

**Comment by mstruve** [comment]
> So if we just use safety operator in resource&.profile_image_url should suffice.

That would probably work, or it might cause other issues when loading the page. I would suggest writing a test to find out.

**Comment by rhymes** [comment]
hi @anubhav8421, as @mstruve mentioned, the best way to find out for sure is to write a spec about it. 

As `app/labor/profile_image.rb` doesn't have an explicit spec file, you could setup something similar to https://github.com/thepracticaldev/dev.to/blob/master/spec/labor/twilio_token_spec.rb
to test it, for example: `spec/labor/profile_image_spec.rb` and add a test to see what happens if you pass a user that has no `profile_image_url`

Let me know if you need further info!

**Comment by anubhav8421** [comment]
Thanks for the response @mstruve @rhymes I will create a PR soon.

**Comment by mstruve** [comment]
Fixed by preventing a channel from being created for a single user https://github.com/thepracticaldev/dev.to/pull/7773
