### ISSUE TITLE
Return "followed" result if Followable already Exists Instead of Raising a Validation Error

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#5793]
In the follows controller when we try to create a follow, sometimes the validation fails bc it already exists. This is a pretty common occurrence and likely due to hitting the button twice or some front end race condition. 
Honeybadger: https://app.honeybadger.io/fault/66984/b9e5567612f10d6a9413da94444f6458
Error:
```
ActiveRecord::RecordInvalid: Validation failed: Followable has already been taken
monitor.rb  235 mon_synchronize(...)
[PROJECT_ROOT]/vendor/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
233     Thread.handle_interrupt(EXCEPTION_NEVER){ mon_enter }
234     begin
235       yield
236     ensure
237       Thread.handle_interrupt(EXCEPTION_NEVER){ mon_exit }
```

I believe, in the event that a follow already exists, we should exit early and return the result "followed".  If anyone has other thoughts on that approach let me know!

**Comment by gonzar11** [comment]
Hey @mstruve , I'd like to work with this issue.

**Comment by mstruve** [comment]
Hey @gonzar11, that would be awesome! Thanks for offering to work on this! I like that idea of a db constraint but I don't think we can do it at the db level for this since Followable is polymorphic. Since the validation is already in place I think its more about handling the validation failure in a better way
