### ISSUE TITLE
Return a 404 response If @event is Not Found

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#5795]
In the events controller we lookup the requested event. However, since we are using `find_by` if the event is not found we simply try to load the view with a nil `@event` which leads to the error below
```ruby
def show
  @event = Event.find_by(slug: params[:id])
end
```
Honeybadger: https://app.honeybadger.io/fault/66984/b5b494606dbf78f0e09c009ea5e1e627
Error:
```
ActionView::Template::Error: undefined method `title' for nil:NilClass
show.html.erb  2 block in _app_views_events_show_html_erb__3248125032052569105_140759860(...)
[PROJECT_ROOT]/app/views/events/show.html.erb:2:in `block in _app_views_events_show_html_erb__3248125032052569105_140759860'
1 <%= content_for :page_meta do %>
2   <% title "#{@event.title} - DEV" %>
3   <link rel="canonical" href="https://dev.to/<%= @event.slug %>" />
4   <meta name="description" content="dev.to | Events">
```

In the event that an `@event` is not found we should return a `not_found` status. ApplicationController has a handy `not_found` method that you can use to do this. I think you will want to implement a solution similar [to this one](https://github.com/thepracticaldev/dev.to/pull/5646/files#diff-cae59de326d9d5bfb471bb23bbd25c1fR62).

**Comment by Zeko369** [comment]
Hey, I'd like to work on this.

**Comment by mstruve** [comment]
Sounds great! Thank you!!!
