### ISSUE TITLE
Prevent Invalid canonical_url's or feed_source_urls from Breaking Article Show Page

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#5808]
When an Article has an invalid canonical_url and we try to load the Article show page we end up breaking the page trying to parse the invalid URL. 
Honeybadger: https://app.honeybadger.io/fault/66984/677f8c91c2875be2a735b7cb64e8e5ab
Error:
```
ActionView::Template::Error: bad URI(is not URI?): "https://www.positronx.io/angular radio-buttons-example/"
[PROJECT_ROOT]/vendor/ruby-2.6.5/lib/ruby/2.6.0/uri/rfc3986_parser.rb:67 :in `split`
65         ]
66       else
67         raise InvalidURIError, "bad URI(is not URI?): #{uri.inspect}"
68       end
69     end
[PROJECT_ROOT]/vendor/ruby-2.6.5/lib/ruby/2.6.0/uri/rfc3986_parser.rb:73 :in `parse`
[PROJECT_ROOT]/vendor/ruby-2.6.5/lib/ruby/2.6.0/uri/common.rb:234 :in `parse`
[PROJECT_ROOT]/app/helpers/articles_helper.rb:52 :in `get_host_without_www`
```

To Reproduce: 
* Create an article and save an invalid canonical_url on it. 
* update the article and set all of these values so the partial that fails renders
```
your_article_with_invalid_canonical_url.update_attributes(crossposted_at: Time.now, published_from_feed: true, published: true, published_at: Time.now, feed_source_url: "www.mollystruve.com")
```
Load the article show page and it should break. The invalid URL we are seeing that caused this error had a space in it. 

In order to fix this we either need to handle the invalid urls in the view or better yet, prevent invalid urls from being saved at all.

**Comment by JuanVqz** [comment]
Hi @mstruve! I would like to contribute!

I entered an invalid canonical URL 
<img width="711" alt="Screen Shot 2020-02-03 at 1 28 59 AM" src="https://user-images.githubusercontent.com/7331511/73633594-adfc9500-4624-11ea-953d-8c564eb9862a.png">

then I saved the article (**SAVE CHANGES** button)
then I expected to see the error but I saw a message error
and I couldn't save the article.

<img width="749" alt="Screen Shot 2020-02-03 at 1 27 52 AM" src="https://user-images.githubusercontent.com/7331511/73633659-da181600-4624-11ea-85c7-22e20e7eaaaf.png">

Is solved the issue? 👍

**Comment by mstruve** [comment]
I would suggest trying something that is close to valid like the URL that is shown in the error `https://www.positronx.io/angular radio-buttons-example/` I was able to save that one locally however it did not break the page like I was expecting.

**Comment by JuanVqz** [comment]
@mstruve I already copied the url `https://www.positronx.io/angular radio-buttons-example/` and saved the article when it is published where should I go to click the canonical url? because I entered to read article and I can see all working...

thanks!


<img width="1214" alt="Screen Shot 2020-02-03 at 8 38 23 PM" src="https://user-images.githubusercontent.com/7331511/73709073-b953cd00-46c5-11ea-9d60-6b8ef390776b.png">
<img width="926" alt="Screen Shot 2020-02-03 at 8 42 16 PM" src="https://user-images.githubusercontent.com/7331511/73709074-b953cd00-46c5-11ea-87cd-ae31627b9241.png">

**Comment by mstruve** [comment]
Read the updated the steps to reproduce. In order to get the partial to render that is breaking you have to set some additional values

To Reproduce: 
* Create an article and save an invalid canonical_url on it. 
* update the article and set all of these values so the partial that fails renders
```
your_article_with_invalid_canonical_url.update_attributes(crossposted_at: Time.now, published_from_feed: true, published: true, published_at: Time.now, feed_source_url: "www.mollystruve.com")
```
Load the article show page and it should break. The invalid URL we are seeing that caused this error had a space in it.

**Comment by JuanVqz** [comment]
I followed your steps and it works, thanks!

Would I take this issue?

I have a question, What do you prefer?before saving erase spaces and join

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/6093
