### ISSUE TITLE
The image can not be displayed because it contains errors.

### ISSUE THREAD

**Issue by AlexLakatos** [thepracticaldev/dev.to#5813]
Cloudinary is having issues with one of the GIFs in my latest blog post - https://dev.to/nexmo/how-to-send-and-receive-sms-messages-with-node-js-and-azure-functions-310i

This is the original GIF that renders just fine in the browser on it's own: https://www.nexmo.com/wp-content/uploads/2020/01/create-azure-function.gif

But when I added to a blog post and it gets passed through Cloudinary, I get that error message. I've also tried adding it direct to DEV, no luck, I get the same error message.

https://res.cloudinary.com/practicaldev/image/fetch/s--641tJBA9--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_66%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/i/ouop3tmorw7je1spoz3r.gif

All the gifs in that blog post are created exactly the same way (Quicktime Record -> Gif Brewery) but they display just fine, so it leads me to believe it's Cloudinary that's failing here.

**Comment by citizen428** [comment]
Thanks for the report @AlexLakatos !

You hit the Cloudinary size limit. Inspecting the response headers reveals a better error message:

```
X-Cld-Error: Maximum total number of pixels in all frames/pages is 200 Megapixels. Requested 354.77 Megapixels
```

I'm afraid this means you'll have to find a way to make this animated GIF smaller, nothing we can do about this on our end.
