### ISSUE TITLE
Old posts appear even after deleting the database.

### ISSUE THREAD

**Issue by abdellani** [thepracticaldev/dev.to#5817]
**Describe the bug**
While I was working on #5508, I face the following problem:
In the beginning, the database is empty and nothing is listed when I check  FEED, WEEK, MONTH, YEAR, INFINITY and LATEST.
When I create the first account and write a post, a list of posts shows up. I think they are coming from Algolia, as both Postgres and Redis are empty.

**To Reproduce**

The video gives the details about the problem https://youtu.be/kFHqEH0BHlM 
Later, the same posts appear in week, month, year and infinity. ~~I noticed also that if someone likes my post, I don't receive a notification.
I also tried the example from [documentation](https://docs.dev.to/backend/notification/) and I didn't get any notifications:~~

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hi @abdellani, it's an odd situation, why are you starting with an empty DB? 

Also, how did you empty it? Because if you truncate the tables directly it won't queue the jobs to remove objects from the indices, thus keeping stuff around.

**Comment by abdellani** [comment]
Hi @rhymes 
To be honest, I was lost while working on  #5508, then I decided to reset everything. I'm not sure about what I did, but I remember that I stopped the server and removed the volume that I mounted to the Postgres container. Maybe the jobs that you are talking about were not created.

**Comment by rhymes** [comment]
I usually use `rails db:reset` when I want to start from scratch. Don't forget to startup both delayed job and sidekiq, you can use `bin/startup`

**Comment by abdellani** [comment]
I cleared the indices manually from the Algolia's dashboard. I  tried `rails db:reset` and `bin/startup` and It works perfectly now.
Is there a shortcut to empty both of Algolia and the database?

**Comment by rhymes** [comment]
I'm not sure, I think you can just call `.clear_index!` on the models you want to clear from the index, for example: `Article.clear_index!`:

```ruby
[11] pry(main)> Article.algolia_search("cover").size
  Article Load (0.7ms)  SELECT "articles".* FROM "articles" WHERE "articles"."id" = $1  [["id", 26]]
=> 1
[12] pry(main)> Article.clear_index!
=> nil
[13] pry(main)> Article.algolia_search("cover").size
  Article Load (0.8ms)  SELECT "articles".* FROM "articles" WHERE 1=0
=> 0
[14] pry(main)> Article.reindex!
[15] pry(main)> Article.algolia_search("cover").size
  Article Load (0.9ms)  SELECT "articles".* FROM "articles" WHERE "articles"."id" = $1  [["id", 26]]
=> 1
```

this with an article that contains the word `cover` in its title

I'm going to close this in the meantime, let me know if you have other questions!
