### ISSUE TITLE
I can't write or publish post

### ISSUE THREAD

**Issue by zakirsajib** [thepracticaldev/dev.to#5824]
**Describe the bug**

**To Reproduce**

**Expected behavior**

After I click on write post, it shows error.

**Screenshots**

**Desktop (please complete the following information):**

- OS: MAC OSX
- Browser: Chrome
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hello @zakirsajib, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
