### ISSUE TITLE
Show entire "Suggested Tweet" in /internal/articles

### ISSUE THREAD

**Issue by pkfrank** [thepracticaldev/dev.to#5831]
**Is your feature request related to a problem? Please describe.**
As a DEV staff member that reviews "suggested tweets, I would like to be able to see the entire tweet without manually expanding the text area.

**Describe the solution you'd like**
The suggested tweet area shows the entire message by default.  Alternatively it is just vertically taller so that it _almost always_ shows the entire tweets.

**Additional context**
- This page is on `/internal/articles` after someone has suggested a tweet, usually via `/manage` on one of their own posts.
- More details on [reaching the page](https://github.com/thepracticaldev/dev.to/issues/4276#issuecomment-539179806) from a related issue

### Current
![current suggested tweet area](https://cl.ly/d6b3a122fdda/Image%202020-02-01%20at%2012.21.59%20PM.png)
### Desired
![desired suggested tweet area](https://cl.ly/b3f1c94e5439/Image%202020-02-01%20at%2012.22.12%20PM.png)

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/6056
