### ISSUE TITLE
Adding RSS support to personal feed and tags

### ISSUE THREAD

**Issue by MarkoShiva** [thepracticaldev/dev.to#5837]
**Is your feature request related to a problem? Please describe.**

I would like to have a RSS feed from dev.to website and dev.to tags.

**Describe the solution you'd like**

As the login in case of RSS is sort of impossible the fetch could have only most popular articles not related to tags in case of dev.to home page. In case of tags there should be ability to add tags via for exmple `https://dev.to/t/feed/python` that would fetch the most recent high upvoted posts. 
It would be very nice way to check what is happening out of your followed and weighted tags.

**Describe alternatives you've considered**
There are really no alternative solutions alternative is opening logged out session and exploring the tags and home page.
**Additional context**
None as RSS is standard there shouldn't be problem in implementation of the feature.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: please wait until we add a `help-wanted` label to the issue before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @maestromac or @rhymes or @citizen428 from the DEV team and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @MarkoShiva, 

would these cover your needs?

- https://dev.to/feed is the main RSS feed
- https://dev.to/feed/rhymes is my feed for example (you can replace the username with another one)
- https://dev.to/feed/tag/python contains the feed for the `python` tag

though the tag feed does not take weight or popularity in consideration

**Comment by MarkoShiva** [comment]
Yes definitely that is what I had in mind. 
- [ ] RSS main feed
- [x] RSS feed for user profiles # already exist
- [ ] RSS feed for tag # bringing the latest posts related to that tag sorted or not

**Comment by citizen428** [comment]
@MarkoShiva If the feed @rhymes mentioned serves your need, can this issue be closed now?

**Comment by MarkoShiva** [comment]
yes of course I didn't noticed that those two feeds have been implemented. :)
