### ISSUE TITLE
Create liquid tag for linking to a tag page on dev.to

### ISSUE THREAD

**Issue by jonathan-irvin** [thepracticaldev/dev.to#586]
## Feature Request and Bug
I love that we can link to dev.to users, articles, but for my case (and I imagine others in the future) the ability to show a series of articles within an article will promote SEO and also help others discover new content.

-------

### Current Behavior

Adding a tag of `{% link https://dev.to/t/jellyfin %}` causes an error shown below

![screen shot 2018-09-04 at 10 00 46 am](https://user-images.githubusercontent.com/2481437/45039544-718cca00-b029-11e8-97de-f4f9fc069152.png)

### Expected Behavior

The site should link to the page.

Additionally, the new functionality would be to show a placard with 3 other links to articles within the selected tag.  We could show the 3 latest, the 3 most popular, or 3 algorithmically selected.

### Additional Benefit

When I'm writing an article about a topic and add in multiple related tags, but primarily I'm writing about `#git`, I can recommend other articles along the same topic for the reader to explore after reading the authored article.

**Comment by jessleenyc** [comment]
This makes sense -- not sure how the additional articles part of the embed would look. Do you have any thoughts on design? cc @benhalpern

**Comment by jonathan-irvin** [comment]
It could follow this model that you're already using, but instead of individual blocks, it could be 1 single block with multiple entries.

![screen shot 2018-09-04 at 1 35 56 pm](https://user-images.githubusercontent.com/2481437/45050698-a0199d80-b047-11e8-8ac0-1857a5001687.png)

Instead of `More from`, it could be a call-to-action such as `Read more from #tag_name#`.

You could include a follow button, _maybe_ the description (if it's not too long), and some sample articles.

@jessleenyc Keep in mind, this is also a bug because just linking to a tag using the {% %} tag above doesn't work.
