### ISSUE TITLE
Add blank placeholder to "Badges" dropdown in /internal/badges

### ISSUE THREAD

**Issue by michael-tharrington** [thepracticaldev/dev.to#5876]
**Problem**

Twice now, I've awarded the incorrect badge to contributors via https://dev.to/internal/badges. This is mostly because I'm moving to quick and being careless 🙃 but I think a simple fix will stop it from happening again.

**Proposed Solution**

We should make a blank placeholder for the "Badges" dropdown so that the person awarding badges must actively choose which badge to award.

**Additional Info**

Because this page is accessed via /internal/, it is restricted to DEV Staff with elevated permissions. You may want to [note this page from the DEV docs](https://docs.dev.to/backend/admin/) if you intend to take on this issue.

Here's an image that shows how the dropdown on https://dev.to/internal/badges is set by default.

![Image 2020-02-03 at 2 53 29 PM](https://user-images.githubusercontent.com/16007075/73685977-256a0d00-4695-11ea-8f3d-25f4677f66af.png)

**Comment by vaidehijoshi** [comment]
@michael-tharrington Good point! I can fix this for you; it's a good excuse to look at another part of the codebase 😸

**Comment by vaidehijoshi** [comment]
@michael-tharrington just deployed this! should be on production soon for ya :)
