### ISSUE TITLE
Not able to Share

### ISSUE THREAD

**Issue by manoj10101996** [thepracticaldev/dev.to#5883]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by citizen428** [comment]
HI @manoj10101996, thanks for your report! Please provide more details regarding what you were trying to share, what you expected to happen and what happened instead, otherwise we don't have enough information to investigate and will have to close this issue.

**Comment by maestromac** [comment]
Closing due to lack of info. Please feel to add/update to this issue and we'll promptly reopen this.
