### ISSUE TITLE
Describe the bug

### ISSUE THREAD

**Issue by farzalivand** [thepracticaldev/dev.to#5927]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hello @farzalivand, there's no information related to what bug you encountered, please open a detailed bug report. I'm going to close this in the meantime
