### ISSUE TITLE
Trailing slashes in profile links cause a validation failure

### ISSUE THREAD

**Issue by timorthi** [thepracticaldev/dev.to#595]
### Current Behavior
For all links under the "Links" profile section (Facebook, StackOverflow, LinkedIn, Behance, Dribbble), a trailing slash will cause a validation failure, preventing a save. 

### Expected Behavior  
Trailing slashes in any of the above mentioned links should not cause a validation failure because these are all valid URLs. In fact, LinkedIn forces a trailing slash on all their routes.  

### Mobile & Desktop Screenshots/Recordings
**Validation fails with trailing slash**
<img width="876" alt="screen shot 2018-09-04 at 4 25 18 pm" src="https://user-images.githubusercontent.com/5664347/45062845-b3386780-b05f-11e8-90c9-5204331cbe80.png">
<img width="616" alt="screen shot 2018-09-04 at 4 25 24 pm" src="https://user-images.githubusercontent.com/5664347/45062851-b6335800-b05f-11e8-865f-66948fe0fd08.png">

### Additional Info (device/browser, helpful links)  
You can test the following links with trailing slashes to verify that they're working:
https://www.facebook.com/zuck/
https://stackoverflow.com/users/8413636/zzxyz/
https://www.linkedin.com/in/williamhgates/
https://www.behance.net/alexmbernsteinb62a/
https://dribbble.com/KEVINGAUTIER/

**Comment by timorthi** [comment]
I'd like to work on this one if it's approved! 😄

**Comment by rusith** [comment]
Facebook URLs with a dot in it also causes a validation error. for an example , 
`https://www.facebook.com/shanaka.rusith` causes a validation error
And this `https://www.facebook.com/shanakarusith` works fine

**Comment by Zhao-Andy** [comment]
Hey @timorthi, we added some stricter validations to the URLs recently. Feel free to work on this! I'd recommend making the trailing slash optional with regex.

@rusith Thanks for the heads up. I didn't account for dots in Facebook usernames. @timorthi if you do work on this, I would recommend adding this to the current regex as well.

**Comment by timorthi** [comment]
@Zhao-Andy Gladly! For the Facebook username, should I account for dots only being allowed as word separators (i.e. not at the start/end, and no consecutive dots), or will `[a-zA-Z0-9.]` be good enough?

**Comment by Zhao-Andy** [comment]
Yeah, go for the word separation solution! 👍

**Comment by timorthi** [comment]
I have everything else done but I'm having trouble with the FB regex -- if anyone can help out with this one, that'd be great:  

For the username, Facebook allows dots (`.`) in between characters (never at the start or end of the string) and never consecutively. Interestingly enough, for the 5 character minimum that they set, dots don't count toward this minimum (try it yourself at http://facebook.com/username).  

Because of this, I'm having trouble with setting a quantifier on my regex (`{5, 50}` is the one currently being used). I've arrived at `([a-zA-Z0-9]+(\.[a-zA-Z0-9]+)*)` but adding a `{5,50}` to the end of it does not seem to work as intended.  

The related PR is here: https://github.com/thepracticaldev/dev.to/pull/614

Does anyone have any ideas? 😄

**Comment by AntonyGarand** [comment]
The dots can be among any other characters, so facebook.com/.a and facebook.com/a. are both valid.
What you could do is remove all dots in the URL then pass the regular regex, or add them everywhere instead of the word separator.

**Comment by timorthi** [comment]
Hey @AntonyGarand , the leading and trailing periods are not valid usernames based my testing (see screenshots) - unless there's something I'm missing here?

<img width="587" alt="screen shot 2018-09-07 at 10 20 41 am" src="https://user-images.githubusercontent.com/5664347/45233676-54096b80-b288-11e8-8d55-0718b6933f3f.png">
<img width="576" alt="screen shot 2018-09-07 at 10 20 47 am" src="https://user-images.githubusercontent.com/5664347/45233677-54096b80-b288-11e8-8d13-269d62a0a87b.png">
<img width="534" alt="screen shot 2018-09-07 at 10 21 48 am" src="https://user-images.githubusercontent.com/5664347/45233679-54096b80-b288-11e8-9496-fc55e51217f1.png">
<img width="503" alt="screen shot 2018-09-07 at 10 21 57 am" src="https://user-images.githubusercontent.com/5664347/45233680-54096b80-b288-11e8-808c-05dd8351e9ad.png">

**Comment by AntonyGarand** [comment]
They might not be valid for new names, but hey are in existing ones:
[facebook.com/a.](//facebook.com/a.) and [facebook.com/.a](//facebook.com/.a) are working

**Comment by AntonyGarand** [comment]
Well, actually, the dots are ignored when resolving a URL, so it's pretty much the same as removing those.

**Comment by arunsathiya** [comment]
Noting that I saw a similar issue with LinkedIn URL even without a trailing slash.

<img width="1007" alt="screenshot 2018-10-13 at 21 10 05" src="https://user-images.githubusercontent.com/18581859/46907202-be1ecb80-cf2c-11e8-80b0-0588ecaf0db8.png">
<img width="751" alt="screenshot 2018-10-13 at 21 10 17" src="https://user-images.githubusercontent.com/18581859/46907203-be1ecb80-cf2c-11e8-9c1f-46fc436cfbab.png">

Upon trying to save again though, without modifying the contents of that field, it worked.

**Comment by Zhao-Andy** [comment]
Hm, not sure what happened there. We'll take a look though, thanks for the heads up @arunsathiya.
