### ISSUE TITLE
Validate That API Article Params are Hash, If not return helpful error message

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#5957]
Sometimes people hit the API with invalid params such as 
```
{ "article" => "body_markdown" }
```
however, we are expecting that the article is going to be a hash of params itself. When a string is passed we end up with this error.
Honeybadger: https://app.honeybadger.io/fault/66984/c7fc185e853bf779e3bfc58c6edd0208
```
TypeError: String does not have #dig method
articles_controller.rb  106 article_params(...)
[PROJECT_ROOT]/app/controllers/api/v0/articles_controller.rb:106:in `article_params'
104           :main_image, :canonical_url, :description, tags: []
105         ]
106         allowed_params << :organization_id if params.dig("article", "organization_id") && allowed_to_change_org_id?
107         params.require(:article).permit(allowed_params)
108       end
```

Solution: We should fail gracefully when this happens and return an unprocessable entity error with a helpful error message to the user. Make sure to include a couple of tests with your fix! 

Steps to Reproduce:
Make a request to the API Articles create endpoint with the params
```
{
  "article" => "body_markdown",
  "published" => "False",
  "description" => "test description",
  "format" => "json",
  "controller" => "api/v0/articles",
  "action" => "create"
}
```

**Comment by atsmith813** [comment]
I'll take this one 🙋‍♂️
