### ISSUE TITLE
Don't Allow Users To React to Unpublished Posts

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#5959]
When a user attempts to reaction to an unpublished post we end up with this error
Honeybadger: https://app.honeybadger.io/fault/66984/960bfd4e2872007d5267d0a0bbaf1660
Error:
```
ActiveRecord::RecordInvalid: Validation failed: Reactable is not valid.
[PROJECT_ROOT]/vendor/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235 :in `mon_synchronize`
233     Thread.handle_interrupt(EXCEPTION_NEVER){ mon_enter }
234     begin
235       yield
236     ensure
237       Thread.handle_interrupt(EXCEPTION_NEVER){ mon_exit }
[PROJECT_ROOT]/app/controllers/reactions_controller.rb:58 :in `create`
```

Possible Solutions: Rather than throwing an error and having it logged in Honeybadger we should not allow the user to click on those reaction buttons until the post is published. OR we check to see if the post is published prior to attempting to make the reaction. I think the first option is the way to go but feel free to poke around and see if you find something better! 

Steps to reproduce: 
Create a draft of an article. View the draft and click on any of the reaction buttons. You will see the error pop up in your logs.

**Comment by abdellani** [comment]
Hi
I'll work on it :)

**Comment by mstruve** [comment]
Fantastic! Thank you!!!
