### ISSUE TITLE
Nil body_markdown Breaks Article Show Page

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#5965]
This issue is going to require a bit of investigation as I am not sure what causes this to happen but at some point we attempt to render the article show page when the article has a nil `body_markdown`
Honeybadger: https://app.honeybadger.io/fault/66984/93ad9d25eff7baa256b9595ae539dbd0
```
ActionView::Template::Error: undefined method `size' for nil:NilClass
 _actions.html.erb  94 _app_views_articles__actions_html_erb(...)
[PROJECT_ROOT]/app/views/articles/_actions.html.erb:94:in `_app_views_articles__actions_html_erb'
92   </div>
93 </div>
94 <% if @variant_number.to_i == 0 && !user_signed_in? && @article.body_markdown.size > 900 %>
95   <% cache("below-article-html-variant-#{rand(20)}", expires_in: 8.hours) do %>
96     <% @html_variant = HtmlVariant.find_for_test(@article.cached_tag_list_array, "article_show_below_article_cta") %>
```

We should use a safety operator to prevent this from happening or figure out what scenario causes this to happen in the first place and prevent that. 

Additional Errors:
https://app.honeybadger.io/fault/66984/648293b74cbb33fba6e6784c374df50d

**Comment by abdellani** [comment]
Hi
When I tried to create a post with an empty body, the result was `body_markdown` containing an empty string and not nil.
I tried to call the `Articles::Creator` with `body_markdown= nil` , the article was created without any problem.
```ruby
article_params_json={"title"=>"test1", "body_markdown"=>nil, "main_image"=>nil, "published"=>true, "description"=>"", "tag_list"=>"", "canonical_url"=>"", "series"=>"", "collection_id"=>nil}
user=User.last
Articles::Creator.call(user, article_params_json)
```
So, I was thinking about adding a new validation "presence: true" to `:body_markdown`.

**Comment by citizen428** [comment]
@abdellani Great, thanks for offering to help. If you decide to tackle this issue, please assign it to yourself so other potential contributors won't pick it up and duplicate efforts.

**Comment by abdellani** [comment]
Hi @citizen428 
I'll work on it.

**Comment by abdellani** [comment]
Hi @mstruve 

Can you please review my pull request in order to know what to do next :pray:?

**Comment by rhymes** [comment]
@mstruve do we have any articles in the DB that have `body_markdown IS NULL` ? Because they might become invalid when we merge https://github.com/thepracticaldev/dev.to/pull/5982

**Comment by mstruve** [comment]
We HAD 11 of them, I just updated them all to have blank strings.
