### ISSUE TITLE
I am unable to write a post

### ISSUE THREAD

**Issue by RitikaRS** [thepracticaldev/dev.to#5966]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by andrasbacsai** [comment]
I think a bit more details are necessary to work with this issue, as I'm able to write a new post at the moment.

Could you please retry now? Maybe it was just a temporary error. Thanks!

**Comment by citizen428** [comment]
Hello @RitikaRS,. thanks for notifying us of this problem, this looks like an issue specific to your account.

Please email yo@dev.to for more help.
