### ISSUE TITLE
Running DEV in Docker fails with .ruby-version error

### ISSUE THREAD

**Issue by andrasbacsai** [thepracticaldev/dev.to#5967]
**Describe the bug**

I forked this repository & would like to run it in Docker. Followed the [docker installation docs](https://docs.dev.to/installation/docker/), but got the following error:
```sh
➜  dev.to git:(master) ✗ docker-compose build
db uses an image, skipping
redis uses an image, skipping
Building webpacker
Step 1/20 : FROM ruby:2.6.5-alpine3.10
 ---> 284974df8f82
Step 2/20 : RUN apk update -qq && apk add git nodejs postgresql-client ruby-dev build-base   less libxml2-dev libxslt-dev pcre-dev libffi-dev postgresql-dev tzdata imagemagick
 ---> Using cache
 ---> 24acc61c2e72
Step 3/20 : RUN gem install bundler:2.0.2
 ---> Using cache
 ---> 3567decde84b
Step 4/20 : ENV PATH=/root/.yarn/bin:$PATH
 ---> Using cache
 ---> c5c2b280251c
Step 5/20 : RUN apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community         yarn
 ---> Using cache
 ---> 9b223fc4f49d
Step 6/20 : WORKDIR /usr/src/app
 ---> Using cache
 ---> a995ef8964dc
Step 7/20 : COPY Gemfile /usr/src/app/Gemfile
 ---> Using cache
 ---> 0af2a90f41ee
Step 8/20 : COPY ./Gemfile ./Gemfile.lock ./
 ---> Using cache
 ---> 72ad206e839e
Step 9/20 : RUN bundle install --jobs 20 --retry 5
 ---> Running in 6aad4b525adb

[!] There was an error parsing `Gemfile`: No such file or directory @ rb_sysopen - .ruby-version. Bundler cannot continue.

 #  from /usr/src/app/Gemfile:5
 #  -------------------------------------------
 #  source "https://rubygems.org"
 >  ruby File.read(".ruby-version").strip
 #  
 #  -------------------------------------------
ERROR: Service 'webpacker' failed to build: The command '/bin/sh -c bundle install --jobs 20 --retry 5' returned a non-zero code: 4
```

I'm able to correct it by adding the following line to the `Dockerfile`:

```
COPY .ruby-version /usr/src/app/.ruby-version
```
Between the following lines:

```
#------------------------------------------------------------------------------
#
# Copy Gemfile and run bundle install
#
#------------------------------------------------------------------------------
COPY Gemfile /usr/src/app/Gemfile
COPY .ruby-version /usr/src/app/.ruby-version
COPY ./Gemfile ./Gemfile.lock ./
RUN bundle install --jobs 20 --retry 5
```

**To Reproduce**

Follow the docker [installation guide](https://docs.dev.to/installation/docker/)

**Expected behavior**

Able to start dev.to locally in docker.

**Desktop (please complete the following information):**

- OS: Ubuntu 19.10
- Browser: Firefox - but it's not important
- Docker: Docker version 19.03.3, build a872fc2f86
- Docker-compose: docker-compose version 1.24.1, build 4667896b

**Additional context**

I can submit a PR.

**Comment by tomalexhughes** [comment]
Can vouch that I experienced the same issue with the following versions and the solution above from @andrasbacsai solved it for me.

OS:  macOS Catalina 10.15.2 (19C57)
Docker: Docker version 19.03.5, build 633a0ea
docker-compose: docker-compose version 1.25.2, build 698e2846

**Comment by citizen428** [comment]
Thanks for reporting for reporting this @andrasbacsai, seems like a result of #5780. As I was going to work on the Dockerfile today anyway, I'll quickly fix this too, but thanks for offering!
