### ISSUE TITLE
Youtube Link Feature

### ISSUE THREAD

**Issue by oliver-gomes** [thepracticaldev/dev.to#5973]
**Is your feature request related to a problem? Please describe.**

It's a bit of a downer when you have profile link for all kinds of socials but not Youtube 🤷‍♀️

**Describe the solution you'd like**

Definitely add Youtube Link in user's profile

**Describe alternatives you've considered**

**Additional context**

**Comment by Computer-Man497** [comment]
That's a great idea, a lot of members on DEV have youtube tutorials.

**Comment by santoshyadav198613** [comment]
Hi Team,
I am planning to make my first contribution, can i take this issue?

**Comment by rhymes** [comment]
@santoshyadav198613 thanks for volounteering but as this is a feature request and yet unapproved I would suggest working on already approved features, those that are labeled [ready for dev](https://github.com/thepracticaldev/dev.to/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22ready+for+dev%22+) are up for grabs

**Comment by bhavaniravi** [comment]
+1 for this feature

**Comment by simo97** [comment]
+1 for this one

**Comment by Rafi993** [comment]
> @santoshyadav198613 thanks for volunteering!
> 
> As this is a feature request and not yet approved I would suggest trying to contribute to already approved features, those that are labeled [ready for dev](https://github.com/thepracticaldev/dev.to/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22ready+for+dev%22+) are up for grabs

My bad I just read this comment now after creating the PR :facepalm:

**Comment by luis-novoa** [comment]
Good morning,
is this issue available? May I work on it?

**Comment by luis-novoa** [comment]
Good morning

This issue is open, but the feature is already added. What is the work needed, and how can I contribute?

Best regards,
Luis Novoa

**Comment by rhymes** [comment]
@luis-novoa, sorry, we forgot to close this issue after https://github.com/thepracticaldev/dev.to/pull/7516 was merged!

Feel free to pick any of [ready for dev issues](https://github.com/thepracticaldev/dev.to/labels/ready%20for%20dev) or any of the [bugs](https://github.com/thepracticaldev/dev.to/labels/type%3A%20bug)

Thanks :-)
