### ISSUE TITLE
Styles for Code and URL do not compose

### ISSUE THREAD

**Issue by JoshCheek** [thepracticaldev/dev.to#6]
Consider this markdown:

```markdown
1. `code` code on its own
2. [desc](url) url on its own
3. [`code`](url) code inside url
4. `[code](url)` url inside code
```

Github renders it like this:

1. `code` code on its own
2. [desc](url) url on its own
3. [`code`](url) code inside url
4. `[code](url)` url inside code

dev.to renders it like this:

![screenshot 2016-12-12 13 11 49](https://cloud.githubusercontent.com/assets/77495/21112772/995b8c6e-c06c-11e6-9ca4-409fd4de250a.png)

We can see Github styles **3** by composing styles from both **1** and **2** (ie it is code that you can click to be taken to docs or smth). Dev.to styles it **3** the same as **1**, so there is no visual indication that it is a link.

Looks like it comes from the `color` attribute in the `.container .body code` rule:

```
$ curl -sL https://practicaldev-herokuapp-com.global.ssl.fastly.net/assets/minimal-37d562af811431609c8ba472099c4730008144d440edf33bf1126fdc0099f64a.css | ruby -pe 'gsub /(?<=[{};])|(?=[}])/, "\n"' | sed -n -e '/[^{}]$/s/^/  /' -e '/.container .body code/,/}/p'
.container .body code{
  margin:auto;
  white-space:nowrap;
  background:#f2f2f2;
  padding:2px 5px 0px;
  border-radius:2px;
  color:#333842;
  font-size:15px;
  display:inline-block;
  vertical-align:0.1em;
  max-width:100%;
  line-height:1.6em
}
```

**Comment by benhalpern** [comment]
Fixed this. Will be live shortly.
