### ISSUE TITLE
Add fields for nav images to organization settings

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#6016]
Organizations have `nav_image_url` and `dark_nav_image_url` in the database which are used for the light or dark themes accordingly when displaying sponsors.
We need to add fields for them to the org settings (`/settings/organization`) so that org admins could add backgrounds by themselves.

**Comment by Math3v** [comment]
@lightalloy Close? :)

**Comment by rhymes** [comment]
Thanks for the catch @Math3v!
