### ISSUE TITLE
Fix sponsoring a tag when an expired sponsorship for this tag exists

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#6017]
If there is an inactive sponsorship for the tag, it's not possible to create a new sponsorship on this tag.
This is caused by validation which doesn't pay attention to expiration date:
https://github.com/thepracticaldev/dev.to/blob/4fe4c4d791f3e911371767d8c1b867bb280a117e/app/models/sponsorship.rb#L28-L33

**Comment by rhymes** [comment]
Closed by https://github.com/thepracticaldev/dev.to/pull/6276
