### ISSUE TITLE
Expiration date should be considered when displaying sponsorship info

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#6018]
If there is an organization sponsorship of a certain type, a user sees information like this:
![изображение](https://user-images.githubusercontent.com/30115/74229158-dd6d6a80-4cd2-11ea-9ee3-17e9598cd3b6.png)
But if the sponsorship is expired, it doesn't affect the information.
Also, the user is not able to manually renew the subscription in this case because:
- for the tag sponsorship, this tag doesn't exist in the select
- for the bronze sponsorship, the form doesn't appear (if there is already an expired sponsorship of this level)

We need to:
- display information that the sponsorship is expired (if it is)
- allow renewing the subscription manually in this case

**Comment by rhymes** [comment]
Solved by https://github.com/thepracticaldev/dev.to/pull/6308
