### ISSUE TITLE
Image not being uploaded into the site

### ISSUE THREAD

**Issue by joro550** [thepracticaldev/dev.to#6077]
**Describe the bug**
When trying to upload an image, I choose the file I want to upload and click the choose file button, choose my image and click done, where it would normally give a link to my new image it closes the black dialogue box without any error or message as to whether it was successful or has errored?

**To Reproduce**
Write a post
click image button
choose image
click done 

**Expected behavior**
dialogue closes and gives a link to where my new image is stored so I can use it as part of my blog

- OS: Windows
- Browser: Chrome 
- Version: 79.0.3945.130

**Additional context**
I have 4 other images on the blog page, I'm not sure if that has anything to do with it? Maybe there's a limit that is being hit? (it's in preview but if necessary I cna provide a link to the preview)

**Comment by rhymes** [comment]
Hi @joro550, could it be that the image is too big? 

Before clicking done it should transform the black overlay like this:

![Screenshot_2020-02-14 New Post - DEV Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/74541774-8e2d7100-4f42-11ea-8fd4-6ffef50ffcd6.png)

Do you get any particular errors in the console?

**Comment by joro550** [comment]
So memory wise the image is 63.3KB 

all thoughtthe dimentions are 1920 x 1030, maybe that is the issue?

the overlay just hangs after choosing the file: 
![image](https://user-images.githubusercontent.com/1705979/74543801-f168d480-4f3d-11ea-9313-49912850cac5.png)

no errors in the console that I can see

**Comment by rhymes** [comment]
> all thoughtthe dimentions are 1920 x 1030, maybe that is the issue?

no, we have a file size limit but not on dimensions, I just tried with https://dummyimage.com/1920x1030.jpg and it worked :/

Can you try with disabled extensions? Or with a different browser?

**Comment by joro550** [comment]
Oh hey, it just worked in firefox 😄 

![image](https://user-images.githubusercontent.com/1705979/74544616-553fcd00-4f3f-11ea-918e-9b15324a19ca.png)

**Comment by joro550** [comment]
okay I just deleted my browser data through chrome settings and it is now working on Chrome, browsers are super weird. 

Thanks for being with me through ths venture, I'll close the issue 😢
