### ISSUE TITLE
List of events in api docs

### ISSUE THREAD

**Issue by teaglebuilt** [thepracticaldev/dev.to#6092]
My issue is not related to a problem. I have a question about the list of possible events in creating a webhook.

In the documentation I only found three events. Article updated, destroyed, or created. Are there any other possible events?

I would like to create a webhook for comments. I would like to create a webhook that triggers a netlify build upon certain comments. Like a code challenge solution. This issue is only just a question with brainstorming. Please forgive me if I missed any steps.

**Comment by rhymes** [comment]
Hi @teaglebuilt! At the moment there are only those events that are emitted to trusted applications that connect to the API through OAuth.

[They were added](https://github.com/thepracticaldev/dev.to/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Alightalloy+webhooks+is%3Aclosed+) as part of a project for the Stackbit integration.

Right now it's not possible to get notified about a comment on a specific article.

**Comment by teaglebuilt** [comment]
ok thanks
