### ISSUE TITLE
What is the hash used for the IDs?

### ISSUE THREAD

**Issue by gajus** [thepracticaldev/dev.to#6096]
dev.to API describes this post ID https://dev.to/gajus/ultimate-guide-to-concurrent-logging-in-node-js-18h7 as `252491`, but the ID used in the URL is `18h7`. How is `18h7` derived from `252491`?

**Comment by citizen428** [comment]
Hi @gajus, next time you have a question like this, please feel free to create a post on DEV instead, the issue tracker is not really the place for this. However. to answer your question, it's nothing sophisticated, just 

```ruby
rand(100_000).to_s(26)
```

The relevant code can be found in [`Article#title_to_slug](https://github.com/thepracticaldev/dev.to/blob/3a46635c343ffeab5abc553e95bc6d800e615282/app/models/article.rb#L647-L649).

**Comment by gajus** [comment]
> Hi @gajus, next time you have a question like this, please feel free to create a post on DEV instead, the issue tracker is not really the place for this. However. to answer your question, it's not a hash function, just

To avoid this in future, I suggest adding an issue template for a question and use it to explain where questions should be asked. Will prevent these interactions.

**Comment by citizen428** [comment]
We do have issue templates for bugs and feature requests:

<img width="942" alt="Screen Shot 2020-02-17 at 11 44 36" src="https://user-images.githubusercontent.com/47985/74624433-fb2b4b80-517a-11ea-99f8-1463562cbf45.png">

We generally don't receive many issues of other types, but we'll take your consideration into account, thank you.
