### ISSUE TITLE
Broken markup for "Like" action

### ISSUE THREAD

**Issue by toolateitsme** [thepracticaldev/dev.to#61]
Reproduced in Safari, but dunno about other browsers
![some bug](https://user-images.githubusercontent.com/6512625/27673190-84689fbe-5cc9-11e7-8dd6-9cb60c1e6c33.png)

**Comment by jessleenyc** [comment]
Thanks for flagging!

**Comment by toolateitsme** [comment]
@jessleenyc It's okay. It's my job :)
