### ISSUE TITLE
Import Post from Jekyll Blog or Medium

### ISSUE THREAD

**Issue by shanalikhan** [thepracticaldev/dev.to#610]
There should be a feature to import the post from Jekyll Blogs or pages or from the Medium.
the user should enter the link and all the post with images should be imported

**Comment by rhymes** [comment]
@shanalikhan I'm fairly sure people can import posts from Medium, using the RSS, see here https://dev.to/settings/publishing-from-rss

**Comment by maestromac** [comment]
Thanks for this issue @shanalikhan . As per @rhymes, yup, this feature exists via RSS import. 

Closing
