### ISSUE TITLE
Return a Unauthorized Error from API when Current User is Not Found

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#6119]
There are a couple of endpoints in our API where we require a current_user to be present but we are not ensuring that it exists during our authentication. The two endpoints we have seen errors from because of this are below:
Honeybadgers and Errors:
https://app.honeybadger.io/fault/66984/029a751b03584e85380d5f6b69de050f
```
NoMethodError: undefined method `follows_by_type' for nil:NilClass
followings_controller.rb  8 users(...)
[PROJECT_ROOT]/app/controllers/api/v0/followings_controller.rb:8:in `users'
 6 
 7       def users
 8         relation = current_user.follows_by_type("User").
 9           select(ATTRIBUTES_FOR_SERIALIZATION).
10           order(created_at: :desc)
```
https://app.honeybadger.io/fault/66984/ea66d2941c66d56887febf955a5e16e3
```
NoMethodError: undefined method `id' for nil:NilClass
github_repos_controller.rb  43 create_octokit_client(...)
[PROJECT_ROOT]/app/controllers/api/v0/github_repos_controller.rb:43:in `create_octokit_client'
41 
42       def create_octokit_client
43         current_user_token = Identity.find_by(provider: "github", user_id: current_user.id).token
44         Octokit::Client.new(access_token: current_user_token)
```

**Desired Behavior** 
In these situations, we should be requiring that a `current_user` be present before attempting to perform the action. If current_user is not present we should return a 401, unauthorized status which we have a helper method for in the ApiController
```ruby
  def error_unauthorized
    render json: { error: "unauthorized", status: 401 }, status: :unauthorized
  end
```

**Comment by rhymes** [comment]
> https://app.honeybadger.io/fault/66984/029a751b03584e85380d5f6b69de050f

this is a bit odd as the endpoint is protected with `authenticate_with_api_key_or_current_user!` 

it should never get inside the actual method if the user is not authorized:

https://github.com/thepracticaldev/dev.to/blob/b126326728bd30830f7f7a3ce55caebd10f88783/app/controllers/api/v0/followings_controller.rb#L4

> https://app.honeybadger.io/fault/66984/ea66d2941c66d56887febf955a5e16e3

yeah, we should definitely force authentication in a before action here, as it's not protected
