### ISSUE TITLE
Featured repos don't support emojis 

### ISSUE THREAD

**Issue by Eros** [thepracticaldev/dev.to#612]
### Current Behavior
The description of the bug displays as normal, however anything with an emoji displays as the text
### Expected Behavior
Displays them pretty emojis
### Mobile & Desktop Screenshots/Recordings
https://imgur.com/a/RCwisRo
emoji list https://gist.github.com/rxaviers/7360908
### Additional Info (device/browser, helpful links)
All

**Comment by maestromac** [comment]
Thanks for this issue, @Eros . This looks like a duplicate of #238 .

Closing
