### ISSUE TITLE
only one post loading

### ISSUE THREAD

**Issue by FultonBrowne** [thepracticaldev/dev.to#6120]
**Describe the bug**

only one post loading

**To Reproduce**

go to home page

**Expected behavior**

**Screenshots**

![Screenshot from 2020-02-17 07-59-17](https://user-images.githubusercontent.com/50185337/74669260-a4624980-515b-11ea-9e7a-86c494853ae7.png)
![Screenshot from 2020-02-17 07-59-20](https://user-images.githubusercontent.com/50185337/74669264-a62c0d00-515b-11ea-8a22-980dec9ccace.png)
![Screenshot from 2020-02-17 07-59-24](https://user-images.githubusercontent.com/50185337/74669267-a7f5d080-515b-11ea-888e-6eaf045574f6.png)

**Desktop (please complete the following information):**

- OS: ubuntu
- Browser: firefox
- Version: latest

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hi @FultonBrowne, do you have any errors in the console?

**Comment by FultonBrowne** [comment]
sorry @rhymes i am no web developer. 
here it is 

`Error getting user and CSRF Token Error: "Couldn't find user data on page."
    e util.js:14
    ___hb base-665b4421d83bba059c63b2630d8c0b5ba407d782d7a12114e7085c855c1e4b2a.js:4
    e base-665b4421d83bba059c63b2630d8c0b5ba407d782d7a12114e7085c855c1e4b2a.js:4
base-665b4421d83bba059c63b2630d8c0b5ba407d782d7a12114e7085c855c1e4b2a.js:4:14120
`

**Comment by FultonBrowne** [comment]
this is also happening on my phone

**Comment by thomasledoux1** [comment]
I'm also getting this problem.
base-665b4421d83bba059c63b2630d8c0b5ba407d782d7a12114e7085c855c1e4b2a.js:formatted:1578 Uncaught TypeError: Cannot read property 'concat' of undefined
Hope this helps!

**Comment by brandinchiu** [comment]
Ran into this this morning too.  It also looks like it's creating some issues with creating posts. I've been working on a draft for the last couple of days, including today.

I saved the draft by accident, and my changes were visible in the preview, but if I went to edit the draft, those changes were no longer there.  Tried logging out and then back in, and now those changes are no where to be found.  About an hour's worth of work just _poofed_.

**Comment by FultonBrowne** [comment]
@rhymes it does work if no user is logged in

**Comment by JesseSingleton** [comment]
Same problem here.

OS: windows
Browser: chrome
Version: latest

Other notes:
* I'm using Ublock origin.
* The problem does not affect incognito browsing when not signed in
* Signing out and signing in again seems to work, until you refresh or navigate and then only one post loads.

Chrome dev tool warnings:
![image](https://user-images.githubusercontent.com/17176370/74670545-52dcad80-51a1-11ea-8fcc-0c82dbb87251.png)

As a guess - perhaps something to do with the latest breaking chrome changes around cookies?

**Comment by drebits** [comment]
Same issue:
![pic](https://i.ibb.co/LYyZdB1/deverror.png)

**Comment by FultonBrowne** [comment]
well I guess its not a firefox issue (I get those a lot)

**Comment by maestromac** [comment]
Thank you all for reporting and submitting those helpful console logs!

We just pushed some changes and it should resolve this issue. Please let us know right away if this issue persists!
