### ISSUE TITLE
Add Thumbsdown Reaction an Image For View

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#6140]
When we try to load the reaction partial for a notification and the reaction is the "thumbsdown" category, the view breaks bc we don't have an Image for that. 
Honeybadger: https://app.honeybadger.io/fault/66984/d4b4628080a41228eea5314b40dd1275
```
ActionView::Template::Error: Nil location provided. Can't build URI.
_reaction.html.erb  21 _app_views_notifications__reaction_html_erb___9934663118133686_74010520(...)
[PROJECT_ROOT]/app/views/notifications/_reaction.html.erb:21:in `_app_views_notifications__reaction_html_erb___9934663118133686_74010520'
19     <span class="reaction-images">
20         <% category = notification.json_data["reaction"]["category"] %>
21         with <%= image_tag(ReactionImage.new(category).path, class: "reaction-image", alt: "a #{category.humanize}") %>
22       </span>
23   </div>
```

Here is where we load our paths from and as you can see there is no "thumbsdown" image
```ruby
class ReactionImage
  attr_accessor :category

  def initialize(category)
    @category = category
  end

  def path
    images = {
      "like" => "emoji/emoji-one-heart.png",
      "unicorn" => "emoji/emoji-one-unicorn.png",
      "hands" => "emoji/emoji-one-hands.png",
      "thinking" => "emoji/emoji-one-thinking.png",
      "readinglist" => "emoji/emoji-one-bookmark.png"
    }.freeze
    images[category]
  end
end
```

We should add an image for "thumbsdown" and ensure the view doesn't break. Another way we could fix this is have a catchall image that shows if we dont recognize the reaction category.

**Comment by JuanVqz** [comment]
Would you like I take it? I'll add an image for "thumbs down" like this one 👎 . it's ok?

**Comment by rhymes** [comment]
@JuanVqz go a head! we do have a thumbs down image here: `app/assets/images/emoji/emoji-one-thumbs-down.png`

**Comment by JuanVqz** [comment]
Just a question, I already added thumbs down

How can I ensure the view doesn't break?

**Comment by rhymes** [comment]
Hi @JuanVqz I think the best shot is to add a test case to this section: https://github.com/thepracticaldev/dev.to/blob/master/spec/requests/notifications_spec.rb#L157

If you look at the examples they all test either `like` or `unicorn`, adding a case for the thumbs down (you can verify if it breaks by commenting the new line you added in the PR) is probably the best way to test this:

https://github.com/thepracticaldev/dev.to/blob/9fd55657d0c68f4e83332b7761283b65bb611326/spec/requests/notifications_spec.rb#L178-L182

**Comment by JuanVqz** [comment]
Hi, Thanks for the suggestion @rhymes.
I tested and I noticed about thumbs down is not a valid category but it is in categories array,
can you help me, please?

![image](https://user-images.githubusercontent.com/7331511/74778031-5f740b00-5260-11ea-98ee-202fe48a5763.png)

**Comment by rhymes** [comment]
Sure! If you open `app/models/reaction.rb` you'll see where the error comes from:

https://github.com/thepracticaldev/dev.to/blob/d05ceb4d983fbc7d4d7006de616694444acf8423/app/models/reaction.rb#L161-L162

Basically we don't allow `thumbsdown` reactions from untrusted users, same for `vomit`.
The spec should help you understand how to get that to pass:

https://github.com/thepracticaldev/dev.to/blob/d05ceb4d983fbc7d4d7006de616694444acf8423/spec/models/reaction_spec.rb#L56-L69

**Comment by citizen428** [comment]
@JuanVqz You have to make sure the user is trusted (`user.add_role(:trusted)`) for it to work. The errors gets added by the following validation:

```ruby
errors.add(:category, "is not valid.") if negative_reaction_from_untrusted_user?
```

**Comment by JuanVqz** [comment]
Hi! again me!
I solved a trusted user with your help but now the test passes with and without reaction image "thumbsdown".

Do I need to do something else?
Thanks!

![image](https://user-images.githubusercontent.com/7331511/74885943-72f4a400-533c-11ea-8ef1-fb4a5a89e686.png)

**Comment by rhymes** [comment]
No, I think you're ready to submit a draft PR, check the build passes and then mark it as ready to review🔥

Thank you @JuanVqz

**Comment by JuanVqz** [comment]
I did! 🤩
@rhymes @citizen428 Thank you!

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/6151
