### ISSUE TITLE
I can't use "copy to clipboard" in add image in new post

### ISSUE THREAD

**Issue by mzaini30** [thepracticaldev/dev.to#6169]
![Alt Text](https://dev-to-uploads.s3.amazonaws.com/i/4akj8q75xgj51q0408zk.jpg)

![Alt Text](https://dev-to-uploads.s3.amazonaws.com/i/1oz46jworez9ncjdsieb.jpg)

My device: Realme C2 - details https://www.gsmarena.com/realme_c2-9670.php
Operating system: Android 9.0 (Pie); ColorOS 6 Lite
My browser: Via Browser

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).
