### ISSUE TITLE
Gitpod missing ElasticSearch

### ISSUE THREAD

**Issue by joshpuetz** [thepracticaldev/dev.to#6173]
Gitpod is missing ElasticSearch in it's setup, resulting in the project failing to complete setup and start a Rails server:

![image](https://user-images.githubusercontent.com/37842/74845716-0609eb80-52f5-11ea-91fb-da462f2f9a90.jpg)

**Comment by rhymes** [comment]
Closed by https://github.com/thepracticaldev/dev.to/pull/6198
