### ISSUE TITLE
Syntax highlighting for Pug/Jade

### ISSUE THREAD

**Issue by mzaini30** [thepracticaldev/dev.to#6187]
Is there syntax highliting for Pug?

![Alt Text](https://dev-to-uploads.s3.amazonaws.com/i/w4yql59i9lnjswchsa9h.png)

![Alt Text](https://dev-to-uploads.s3.amazonaws.com/i/8m64var1s42dtwjxl9oo.png)

**Comment by citizen428** [comment]
Thanks for the issue @mzaini30. We use [Rouge](https://github.com/rouge-ruby/rouge) for syntax highlighting, which does not yet have support for Pug/Jade ([issue 1](https://github.com/rouge-ruby/rouge/issues/273), [issue 2](https://github.com/rouge-ruby/rouge/issues/953)).

I will close this issue for now, as it's dependent on upstream changes.
