### ISSUE TITLE
Canonical URL is not getting updated in posts

### ISSUE THREAD

**Issue by Mokkapps** [thepracticaldev/dev.to#619]
### Current Behavior

I configured my account to publish blog posts to dev.to from my RSS.

Unfortunately, the imported blog post draft did include the wrong canonical URL but I had it already published.

I edited the post again on dev.to and changed the `canonical_url` value to the correct one. The published post still shows the old incorrect URL. 

### Expected Behavior

I can edit the `canonical_url` and the new URL is shown in the published post.

### Mobile & Desktop Screenshots/Recordings
<img width="1389" alt="screen shot 2018-09-07 at 08 39 13" src="https://user-images.githubusercontent.com/3127210/45202596-d179af80-b279-11e8-913c-0a0a3ea1bfaa.png">
<img width="866" alt="screen shot 2018-09-07 at 08 39 24" src="https://user-images.githubusercontent.com/3127210/45202597-d2124600-b279-11e8-8f2d-9e64c0460a4e.png">

### Additional Info (device/browser, helpful links)
[This is the corresponding post](https://dev.to/mokkapps/run-automated-electron-app-tests-using-travis-ci-10b2)

**Comment by Zhao-Andy** [comment]
Hey @Mokkapps, thanks for the heads up! We'll take a look and see what's going on there.

Leaving a note that we'll have to have this reflect in the v2 editor, too.

**Comment by maestromac** [comment]
Resolved with #632. Let us know if otherwise!
