### ISSUE TITLE
Can't save my profile

### ISSUE THREAD

**Issue by Jontem** [thepracticaldev/dev.to#62]
Hi!

I first tried to register with github but got stuck in a loop that always told me to register my email when visiting the site. 

I then tried to register with twitter and it worked. But now when i'm trying to update my profile i get the error message that the github username is already taken

![image](https://user-images.githubusercontent.com/4803402/27862173-4f998edc-6184-11e7-8ccb-c44e2a5c6fec.png)

**Comment by Zhao-Andy** [comment]
Fixed, thanks for the heads up. Let us know if you run into other bugs :)

**Comment by maxx1128** [comment]
Don't think it's fixed, I'm encountering this same issue.

**Comment by Zhao-Andy** [comment]
Hey Max, should be fixed now.

**Comment by maxx1128** [comment]
It is indeed, thank you!
