### ISSUE TITLE
Social preview link of article is breaking

### ISSUE THREAD

**Issue by awebartisan** [thepracticaldev/dev.to#6206]
**Describe the bug**
When sharing to any social platform, preview card is not being generated

**To Reproduce**
Social preview link is broken as can be seen in screenshot below.

**Screenshots**

![image](https://user-images.githubusercontent.com/29105478/74934476-21195000-5408-11ea-979a-e292ae7e4fb8.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 80

**Additional context**

I have gone ahead and inspected this on few other articles too written by different authors 🤷🏻‍♂️
For example this post: [https://dev.to/napicella/linux-terminals-tty-pty-and-shell-192e](https://dev.to/napicella/linux-terminals-tty-pty-and-shell-192e). Its social preview url is also broken.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Thanks for the issue @awebartisan, I'm going to look into it right away!
