### ISSUE TITLE
Track tests and overall builds time over time

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#6232]
**Is your feature request related to a problem? Please describe.**

It'd be great if we get to a point where we can have a neat dashboard that tells us the two following info:

- how long does it take for `bundle exec rspec` to run in CI ?
- how long does the overall build take?

As the code grows and tests grow it's easy to forget about this and end up with a super slow test suite.

Having a place where we can check the overall trend would be awesome. 

**Describe the solution you'd like**

I think we can use Datadog to send these events at build start, rspec start, rspec end, build end, maybe we can separate merge builds from deploy builds in two different categories

We can track time and travis build id/PR name.

**Describe alternatives you've considered**

Keep checking it manually but it doesn't scale :D

**Comment by maestromac** [comment]
I believe we are already keeping track of how long the whole Travis build takes but it currently doesn't differentiate between deploy and non-deploy build.  cc @mstruve 

here are some of the metrics that are currently available to us.
![image](https://user-images.githubusercontent.com/15793250/75050102-57eb7680-5499-11ea-9637-5cba8fb93d2a.png)

**Comment by rhymes** [comment]
Oooh! didn't find any info about those in the code so I opened the feature request, magic of DD I guess

**Comment by benhalpern** [comment]
Close the issue?

**Comment by maestromac** [comment]
@rhymes Yeah no code on that, just [direct integration](https://docs.datadoghq.com/integrations/travis_ci/)

@benhalpern We can still address the `how long does it take for bundle exec rspec to run in CI ?` portion.

**Comment by rhymes** [comment]
Closing in favor of https://github.com/thepracticaldev/dev.to/issues/7830
