### ISSUE TITLE
Prevent Invalid Article Url Characters From Breaking Article Show Action

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#6245]
When a user tries to view an Article with a slug that contains invalid characters, we break trying to lookup the article. For example, say you attempt to visit this blog post https://dev.to/devteam/call-for-contributions-move-all-delayedjobs-to-sidekiq-246k BUT instead, you replace some characters with invalid ones, https://dev.to/devteam/call-for-contributions-move-all-%delayedjobs-to-sidekiq-246k The second URL will give us this error:
Honeybadger: https://app.honeybadger.io/fault/66984/2eb393354a8c34bb594b71ba905d2b69
```
ArgumentError: string contains null byte
stories_controller.rb  36 show(...)
[PROJECT_ROOT]/app/controllers/stories_controller.rb:36:in `show'
34   def show
35     @story_show = true
36     if (@article = Article.find_by(path: "/#{params[:username].downcase}/#{params[:slug]}")&.decorate)
37       handle_article_show
38     elsif (@article = Article.find_by(slug: params[:slug])&.decorate)
```

When this happens we should rescue the error and return a 404 OR prevent the error from ever occurring and return a 400 Bad Request if we detect invalid characters.

**Comment by Math3v** [comment]
@mstruve Hello 👋 . I'm new to dev.to and I tried to fix this issue. I was hoping to get a review, if someone has time. Thank you!
