### ISSUE TITLE
Colon in description text does not have proper error handling

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/dev.to#625]
## Bug Report
Leaving a colon in description text of the front matter does not have proper error handling. 

### Current Behavior
In this example:
```
---
title: Minimal bug example 
published: false
description: this is: okay
tags: 
---
```
Clicking "Preview" or "Save" will cause the page to 500 instead of having a proper error message.

### Expected Behavior
We give a proper error message and not have the page hit a 500 error.

### Related Files
See `markdown_parser.rb`.

Thanks @nestedsoftware for reporting this!

**Comment by nestedsoftware** [comment]
Note: This seems to only happen when you update an existing article. If you have a brand new article and you try to save it with a colon in the description, the app actually displays a proper validation error message.

**Comment by bennypowers** [comment]
I tried with a brand-new article and got this error:

```
uncaught exception: YAMLException: incomplete explicit mapping pair; a key node is missed at line 3, column 98:
     ... th the OG web-components library: Polymer.
```

**Comment by gokul0** [comment]
Hi,

I would like to contribute to this.
Can you please tell me the directions?

**Comment by maestromac** [comment]
Reopening this to really make sure this is no longer an issue
