### ISSUE TITLE
Ooooops... You have encountered an error

### ISSUE THREAD

**Issue by Rahul626** [thepracticaldev/dev.to#6252]
**Describe the bug**

when I try to write a post I face the same issue reinstall my browser and tried different desktop but i getting  same bug!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: windows10
- Browser: Google chrome
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hello @username, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @Rahul626, can you please describe what you're doing? Does it log anything in the browser's console?

**Comment by Rahul626** [comment]
On console log
"​Failed to load resource: the server responded with a status of 500 "
every time I am getting the same  issue 
Ooooops...
You have encountered an error.
Our team has been notified. Please feel welcome to also submit a public bug report.
We apologize for any inconvenience.
![image](https://user-images.githubusercontent.com/42401032/75506671-bc13ba80-5a04-11ea-8464-d9957cec915a.png)

**Comment by rhymes** [comment]
It might be only related to your account @Rahul626.

Please email yo@dev.to for more help.

**Comment by slatewala** [comment]
I am facing the same issue pls help

**Comment by rhymes** [comment]
@slatewala please email yo@dev.to for more help, thank you!

**Comment by burakakca** [comment]
i deploy to heroku. i get same secreen. the log error message is below.  help pls.

2021-07-03T07:24:02.505116+00:00 app[web.1]: F, [2021-07-03T07:24:02.504983 #35] FATAL -- : [22f1c5b8-f38b-4222-b1e2-950af625a67f]   
2021-07-03T07:24:02.505129+00:00 app[web.1]: [22f1c5b8-f38b-4222-b1e2-950af625a67f] ActiveRecord::StatementInvalid (PG::DuplicatePstatement: ERROR:  prepared statement "a13" already exists

**Comment by ellativity** [comment]
@burakakca For support and assistance with your Forem installation, please join the Forem Creators and Builders Forem at forem.dev. We recommend you begin by checking out [Akhil's series on deploying Forem to Heroku](https://forem.dev/akhil/brief-introduction-to-this-guide-12dc).

**Comment by web3dev-admin** [comment]
> i deploy to heroku. i get same secreen. the log error message is below. help pls.
> 
> 2021-07-03T07:24:02.505116+00:00 app[web.1]: F, [2021-07-03T07:24:02.504983 #35] FATAL -- : [22f1c5b8-f38b-4222-b1e2-950af625a67f] 2021-07-03T07:24:02.505129+00:00 app[web.1]: [22f1c5b8-f38b-4222-b1e2-950af625a67f] ActiveRecord::StatementInvalid (PG::DuplicatePstatement: ERROR: prepared statement "a13" already exists

Did you manage to solve that?

**Comment by burakakca** [comment]
No I couldn't figure it out, forem.dev didn't help!!. I installed it on digitalocean.
