### ISSUE TITLE
Bug encountered! same error for long time :(When try to write post)

### ISSUE THREAD

**Issue by Rahul626** [thepracticaldev/dev.to#6253]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

![image](https://user-images.githubusercontent.com/42401032/75115560-8747e200-5657-11ea-9dd9-5ad254507d2f.png)

**Comment by rhymes** [comment]
Closed in favor or https://github.com/thepracticaldev/dev.to/issues/6252
