### ISSUE TITLE
Reorganize internal and public API controllers.

### ISSUE THREAD

**Issue by citizen428** [thepracticaldev/dev.to#6255]
During the discussions in #6136 it became clear that not all controllers currently residing in `app/controllers/api/v0` are meant for the public API, some are used by the DEV website itself. Since we use slightly different authorization methods and checks this can lead to subtle bugs, so we should move things that aren't mean for public consumption to a different namespace or to a `responds_to block` in their "main" controller.

Todo:

- [x] `POST     /api/reactions/onboarding           api/v0/reactions#onboarding`
- [x] `POST     /api/reactions                      api/v0/reactions#create`
- [x] `POST     /api/github_repos/update_or_create  api/v0/github_repos#update_or_create`
- [x] `GET      /api/github_repos                   api/v0/github_repos#index`
- [X] `GET      /api/tags/onboarding                api/v0/tags#onboarding`
- [x] `Api::V0::FollowingsController`
- [x] `Api::V0::ChatChannelsController`
- [x] `Api::V0::UsersController#index`

**Comment by rhymes** [comment]
Adding a note here as the API docs are not the correct metric of evaluation since they are largely incomplete, see https://github.com/thepracticaldev/dev.to/issues/4474

I think we can only move those controllers that do not currently require an API key or OAuth as auth

**Comment by citizen428** [comment]
Thanks @rhymes, description updated.

**Comment by citizen428** [comment]
@rhymes Going through #4474 it looks like it just includes everything that's in `api/v0/controllers`, including things like Github repos that started the whole conversation in #6136. So I think step 1 would be to clean up that issue and you definitely have more context on the API than I do.

**Comment by rhymes** [comment]
Updated the list there, thanks @citizen428!

These are those that should be moved:

```text
- [ ] `POST     /api/reactions/onboarding           api/v0/reactions#onboarding`
- [ ] `POST     /api/reactions                      api/v0/reactions#create`
- [ ] `GET      /api/tags/onboarding                api/v0/tags#onboarding`
- [ ] `POST     /api/github_repos/update_or_create  api/v0/github_repos#update_or_create`
- [ ] `GET      /api/github_repos                   api/v0/github_repos#index`
```

There's also this:

```text
- [ ] `POST     /api/follows                        api/v0/follows#create`
```

this shouldn't be part of the public API but it currently is, it uses `authenticate_with_api_key_or_current_user`, so we we might have to investigate into Datadog to see if anybody other than us is using it or just leave it there.

**Comment by citizen428** [comment]
Awesome, thanks for the list @rhymes, I'll get started on this tomorrow.

**Comment by rhymes** [comment]
I added `Api::V0::ChatChannelsController` to the list as it currently works only if the `current_user` is authenticated and part of the channel. Definitely not public API materrial

**Comment by citizen428** [comment]
Noted @rhymes, thanks!

**Comment by rhymes** [comment]
I think I found another endpoint to move, `Api::V0::UsersController#index` - https://dev.to/api/users

A few reasons why:

- currently it only works if `current_user` is present
- it's only used internally to show suggested users in sidebars
- it returns an empty array for authenticated users if they are not asking for suggested users

I think it shall be moved in the `UsersController` and I think we can remove the `!user_signed_in?` condition as well.

The implementation is here https://github.com/thepracticaldev/dev.to/blob/master/app/controllers/api/v0/users_controller.rb#L7

**Comment by citizen428** [comment]
The task that gives on giving 🤣 Thanks @rhymes!

**Comment by citizen428** [comment]
@benhalpern Regarding `POST /api/reactions api/v0/reactions#create`, is this still used? I can't seem to find it:

```
$ rg '/api/reactions'
spec/requests/api/v0/reactions_spec.rb
16:  describe "POST /api/reactions" do
40:  describe "POST /api/reactions - articles" do
97:  describe "POST /api/reactions - comments" do
```

Looking at the JS code, reactions seem to get invoked via `sendFetch` in `app/assets/javascripts/utilities/sendFetch.js`, but that posts to `/reactions`, which is also a JSON endpoint, not `/api/reactions`.

**Comment by rhymes** [comment]
According to

https://github.com/thepracticaldev/dev.to/blob/3161c9d901c8d14877db13c3647d6be7e7b277f1/app/controllers/api/v0/reactions_controller.rb#L6-L11

https://github.com/thepracticaldev/dev.to/blob/3161c9d901c8d14877db13c3647d6be7e7b277f1/app/controllers/api/v0/reactions_controller.rb#L30-L34

only super admins can invoke that endpoint. 

The problem as you mentioned is that we can't find out where it is used. Datadog clearly shows a lot of traffic to it:

![Screenshot_2020-03-12 practical… (env production) Datadog(1)](https://user-images.githubusercontent.com/146201/76502049-a1e5cd80-6443-11ea-8b69-202404c7c648.png)

**Comment by citizen428** [comment]
@benhalpern @maestromac Any insights on this? We are still wondering where the calls to `pi/v0/reactions#create` originate.

**Comment by maestromac** [comment]
@citizen428 🤔 I've also looked and I have no idea where this is being used.

**Comment by benhalpern** [comment]
Hey folks @citizen428 sorry for not seeing this.

Yeah, traffic here is basically exclusively as part of a personal automated moderation/postive react to new content that's been in place for a while. Now that we have so many site mods and overall activity it's no longer really needed. I've been meaning to wind it down.

We can do whatever we want with this endpoint. I'm the only user.

**Comment by citizen428** [comment]
Thank you @benhalpern! 🎉 I'll put up the PR for removing this endpoint then and you can merge it whenever you have given your script the Viking funeral it deserves.
