### ISSUE TITLE
Resolve text contrast for the .dashboard-top-pill

### ISSUE THREAD

**Issue by 5t3ph** [thepracticaldev/dev.to#6285]
I'm a series writer, and the contrast right now for the `.dashboard-top-pill` which encloses the series title on the Dashboard view has very poor contrast - white over light grey.

The current `color` value is `var(--theme-container-background, #fff)` and I would suggest updating to `var(--theme-container-color, #0a0a0a)` or considering an altered design that improves the contrast of this text.

I would love to submit this PR if you agree this is an acceptable fix! Thanks!

**Comment by citizen428** [comment]
Thanks for the issue @5t3ph! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by ludwiczakpawel** [comment]
Hey @5t3ph and thanks for reporting!

Fix for this is coming: #6288 and should be soon up on DEV 🙌
