### ISSUE TITLE
Draft vs Edit pages for post drafts displaying different content

### ISSUE THREAD

**Issue by brandinchiu** [thepracticaldev/dev.to#6298]
**Describe the bug**

I have a draft post I have been working on off and on for the last few weeks. If I navigate to the preview, I see the content as expected with my latest changes.  If I move to the edit view, I see content from before my most recent changes, that is totally different from the preview.

**To Reproduce**

1. Go to profile
2. View unpublished draft
3. Click edit
4. Post content is different in edit view

**Expected behavior**

Preview and edit views should display the same content.

**Screenshots**
Proper content in initial preview:
![ss1](https://i.imgur.com/C381xj4.png)

Totally different content in edit:
![ss1](https://i.imgur.com/VdJWqrc.png)

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Chrome
- Version: 79.0.3945.123

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by maestromac** [comment]
Hello @brandinchiu , does the issue you are experiencing sound similar to https://github.com/thepracticaldev/dev.to/issues/3670 ?

**Comment by brandinchiu** [comment]
It does! I suspect these are the sam.

**Comment by maestromac** [comment]
Since that is the case, I'm going to mark this as duplicate and close the issue. Please share your feedback and continue the conversation over at https://github.com/thepracticaldev/dev.to/issues/3670 🙂
