### ISSUE TITLE
can't sign in  to my account

### ISSUE THREAD

**Issue by afreen23** [thepracticaldev/dev.to#63]
I have signed up through my github account but now it is asking again and again for those small details and I am unable to go into my account.

**Comment by SH128** [comment]
Same problem here, signed up using github and now the application keeps asking for my email address an the short biography.

**Comment by Zhao-Andy** [comment]
Hey there, this issue should be fixed. Just react to this comment with a thumbs up if it works, or reply if it doesn't work.

**Comment by afreen23** [comment]
It's not working as I am signing in for my GitHub account and it is showing up the same page again.

**Comment by Zhao-Andy** [comment]
Oh I see, you have to submit an email address with the form. After that, verify your email and you should be able to get out of that page.

**Comment by afreen23** [comment]
I am getting the same page even by clicking on the "confirmation link" in the email.

**Comment by afreen23** [comment]
I am getting that page again even after clicking on the "confirmation link" in the email. Moreover, it is leading me to the same page after clicking any item on the page.

**Comment by Zhao-Andy** [comment]
Hmm, I'm getting the same thing, too. I'll get back to you when I figured it out. Sorry about that!

**Comment by Zhao-Andy** [comment]
Hey there, it's been fixed now. If you go to dev.to/settings type in your email in the email field, and hit submit, you should get a new confirmation link via email. Once you click that it should work.
