### ISSUE TITLE
Why is dev.to so fast?

### ISSUE THREAD

**Issue by dominikbraun** [thepracticaldev/dev.to#6305]
This isn't a bug report or feature request, just a question.

I'm impressed by the pure performance of dev.to, especially when it comes to loading a long article page. It rather feels like navigating around in static HTML files than in a dynamic website.

Is this performance granted by a good caching strategy or by efficient coding? Are there any key features or technologies that lead to that speed?

Thanks in advance :)

**Comment by rhymes** [comment]
Hi @dominikbraun, this is probably a topic better raised on the website itself as it would allow other people to join in the conversation.

I think these posts and their conversations might help you:

- [Making dev.to Incredibly fast](https://dev.to/ben/making-devto-insanely-fast)
- [ What technology is used to make dev.to so fast ?](https://dev.to/ako302/what-technology-is-used-to-make-devto-so-fast--50d)
- [Instant Webpages and Terabytes of Data Savings Through the Magic of Service Workers](https://dev.to/devteam/instant-webpages-and-terabytes-of-data-savings-through-the-magic-of-service-workers-1mkc)

We use a combination of frontend performance tricks, edge caching, best practices on the backend and... magic :D It's also a good testament that monoliths can be fast ;)

I'm going to close this but I hope I at least partially answered your question!

**Comment by dominikbraun** [comment]
Thanks for linking to that posts, this answers my question perfectly.
