### ISSUE TITLE
[Night Mode] Difficult to See Social Icons on Profile Page

### ISSUE THREAD

**Issue by dstarner** [thepracticaldev/dev.to#6310]
**Describe the bug**

Using the Night Mode Theme, it is incredibly difficult to see the profile social icons due to their low contrast with the background. I'm not sure where else (if anywhere) this problem exists.

**To Reproduce**

1. Enter nightmode
1. View a profile
1. Note that the social icons are difficult to see

**Expected behavior**

A high contrast color, such as what is used for the Profile Info or Badges button (seen below). These are set using the following CSS

```
-webkit-filter: invert(95%);
filter: invert(95%);
```

![Screen Shot 2020-02-26 at 11 21 31 AM](https://user-images.githubusercontent.com/10478871/75364793-484da280-588a-11ea-9fed-65b166f28545.png)

So it would be nice if the social icons followed the same color or inversion scheme.

**Screenshots**

![dev_social_icons](https://user-images.githubusercontent.com/10478871/75364499-d5442c00-5889-11ea-8564-dbd89766665a.png)

**Desktop (please complete the following information):**

- OS: MacOS Mojave 10.14.6
- Browser: Firefox 72.0.2

**Additional context**
 
NA

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by akshayymahajan** [comment]
I would like to fix this..

**Comment by rhymes** [comment]
Thank you @akshayymahajan, go ahead! I've assigned you to the issue.
