### ISSUE TITLE
Seeing an internal error screen after clicking "write post"

### ISSUE THREAD

**Issue by jamesShelburne** [thepracticaldev/dev.to#6326]
**Describe the bug**

Seeing an internal error screen when trying to add a new post.

**To Reproduce**

1. Click Write Post
2. See Internal Error screen (attached) at the URL https://dev.to/new  
3. Unable to write new posts

**Expected behavior**

Expected to see the post authoring screen.
**Screenshots**

<img width="1057" alt="Screen Shot 2020-02-26 at 2 49 43 PM" src="https://user-images.githubusercontent.com/10519371/75395434-46dea300-58a7-11ea-8a4c-1496887d3c83.png">

**Desktop (please complete the following information):**

- OS: MacOS 10.14.6
- Browser: Chrome
- Version: 80.0.3987.116 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: 
- OS:
- Browser:
- Version:

**Additional context**

**Comment by citizen428** [comment]
Hello @jamesShelburne, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
