### ISSUE TITLE
`.base-article-show-sidebar-variant` div variants out of alignment

### ISSUE THREAD

**Issue by Amorpheuz** [thepracticaldev/dev.to#6331]
**Describe the bug**
A variant of the particular class's div is aligned out of position in the sidebar. Refer Screenshots for more info.

**To Reproduce**
1. Open dev.to in a private window or don't be logged in.
2. Open various articles to see different variants. (Need to set up the repo again to reproduce in the codebase)
3. Look for `base-article-show-sidebar-variant` class.

**Expected behavior**
Correctly sized and aligned div on the sidebar, I presume from the name.

**Screenshots**
- Current alignment on Page
![image](https://user-images.githubusercontent.com/22113778/75439562-069f2380-5980-11ea-9708-09d38f283107.png)
![image](https://user-images.githubusercontent.com/22113778/75440095-1f5c0900-5981-11ea-909f-be2e29574201.png)
![image](https://user-images.githubusercontent.com/22113778/75440222-5c280000-5981-11ea-94f6-776c49335390.png)

- Another Variant not located in sidebar despite the name, but correctly aligned
![image](https://user-images.githubusercontent.com/22113778/75439809-83320200-5980-11ea-976c-d65c54b86ef3.png)

**Desktop (please complete the following information):**

- OS: Windows 10 [Version 10.0.19041.84]
- Browser & Version: Firefox Nightly 75.0a1 (2020-02-26) (64-bit) and Edge(Chromium) 80.0.361.62
- Device Screen Size: 1920 x 1080 

**Additional context**
Happy to help resolve this issue!

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).
