### ISSUE TITLE
Add feature to remove article from homepage content boxes

### ISSUE THREAD

**Issue by pkfrank** [thepracticaldev/dev.to#634]
## Feature Request or Task
Articles submitted to certain tags show up on the homepage by default.  However, sometimes there are instances where an admin would like to remove it from showing up.  Here's an example:

![example of erroneous article on homepage sidebar box](https://cl.ly/045ff1d87d44/Image%202018-09-11%20at%205.57.43%20PM.png)

### User Story / Description
As an admin, I want to remove articles from appearing in the homepage "tag boxes."

### Definition of Done
Lowering the `featured_number` below `1500000000` will prevent that article from showing up in that sidebar box.  And will bust the cache to remove it if necessary.

**Comment by Moonlight56** [comment]
hallo every all

**Comment by Moonlight56** [comment]
sorry

**Comment by Moonlight56** [comment]
😊😊😊

**Comment by Moonlight56** [comment]
thanks

**Comment by Moonlight56** [comment]
pl help me

**Comment by Moonlight56** [comment]
😊😊

**Comment by benhalpern** [comment]
I remove the improper tag when I see this. I could see the ideal way of doing this is adding an anti-tag.

It probably makes sense that this could be a task for the mods of individual tags.

**Comment by Zhao-Andy** [comment]
My experience with this was removing the improper tag took a little while to remove it from the sidebar. Not sure if it was a caching issue or not.
