### ISSUE TITLE
Duplicate footer 

### ISSUE THREAD

**Issue by ioana-chiorean** [thepracticaldev/dev.to#6347]
**Describe the bug**

**To Reproduce**
- Just opened the link from the dark theme announcement.
- I get the same all times if I visit https://dev.to/enter

**Expected behavior**

A single entry of the footer should be displayed

**Screenshots**

<img width="1280" alt="Screen Shot 2020-02-27 at 21 47 57" src="https://user-images.githubusercontent.com/1391451/75483374-5f39e500-59af-11ea-83f3-3773f0dde571.png">
<img width="1072" alt="Screen Shot 2020-02-27 at 21 46 16" src="https://user-images.githubusercontent.com/1391451/75483377-6103a880-59af-11ea-9f5a-dd951389313f.png">

**Desktop (please complete the following information):**

- OS: Mac OS Mojave
- Browser: Firefox 73.0
- Version: Release

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).
