### ISSUE TITLE
Add a shortcut to an individual comment in the admin panel

### ISSUE THREAD

**Issue by pkfrank** [thepracticaldev/dev.to#635]
## Feature Request or Task
To support the admin workflow, we have the following shortcut: `dev.to/ben/admin` forwards to `https://dev.to/admin/users/1`.  This allows us to quickly and ergonomically navigate to a user's admin page if we have to make an adjustment to their account.

As part of our admin/moderation duties, we occasionally have to manually delete comments.  This currently involves taking the comment `id_code`, searching it in `dev.to/admin/comments`, and clicking into the proper comment.  I think this can be improved.

### User Story / Description
As an admin, I want to be able to navigate to an individual comment in the admin panel as quickly/easily as possible.

### Definition of Done
Appending `/admin` to an individual comment URL will redirect to the comment in the admin panel.

For example:
`dev.to/ben/comment/5d9p` will forward to `dev.to/admin/comments/{comment-id}`

**Comment by iamlatin** [comment]
admin if its numbres 777 if its words tapmi

**Comment by Zhao-Andy** [comment]
Done by @benhalpern
