### ISSUE TITLE
unable update profile :(while updating profile on save its encountering an error)

### ISSUE THREAD

**Issue by Rahul626** [thepracticaldev/dev.to#6351]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 
- Browser: Google chrome
- Version:

**Smartphone (please complete the following information):**

- Device: Xiaomi Redmi Note 5 Pro
- OS: Android 9
- Browser: Google chrome
- Version: 

**Additional context**

![image](https://user-images.githubusercontent.com/42401032/75516820-49660780-5a23-11ea-8396-d7f5db4362b4.png)

**Comment by rhymes** [comment]
Hello @Rahul626, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
