### ISSUE TITLE
Error 404 : Profile not show correctly

### ISSUE THREAD

**Issue by thomasbnt** [thepracticaldev/dev.to#6373]
**Describe the bug**

Your profile picture is hidden by this background colored in blue.

**To Reproduce**
Visit a 404 error page : **https://dev.to/404**

**Screenshots**

![image](https://user-images.githubusercontent.com/14293805/75597045-8ec21d80-5a93-11ea-8e22-28c8f9bcccc8.png)

**Desktop (please complete the following information):**

- OS: **Manjaro**
- Browser: **Brave**
- Version: **Version 1.4.95 Chromium: 80.0.3987.122 (Official Build) unknown (64-bit)**

Good day!

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Can reproduce it on Firefox 74 navigating to https://dev.to/dashboard2

**Comment by michelc** [comment]
I think I can fix it this weekend.
