### ISSUE TITLE
Variant not displaying in sidebar properly

### ISSUE THREAD

**Issue by pkfrank** [thepracticaldev/dev.to#6376]
**Describe the bug**
At 100% Zoom on Chrome, Macbook Pro 15" (default resolution) I'm seeing this issue.

**Screenshots**
![example of issue](https://cl.ly/0fcea88a3fb1/Screen%20Recording%202020-02-29%20at%2010.41%20AM.gif)

**Additional context**
![variant id](https://cl.ly/4b3619c2ddb7/Image%202020-02-29%20at%2010.43.06%20AM.png)

`data-variant-id="214"`

**Comment by rhymes** [comment]
To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by maestromac** [comment]
I believe this was resolved with https://github.com/thepracticaldev/dev.to/pull/6378
