### ISSUE TITLE
GitHub tag fails if no readme

### ISSUE THREAD

**Issue by b3u** [thepracticaldev/dev.to#6382]
**Describe the bug**
When I try to create a GitHub repo embed of a repo without a readme, the tag errors with a 404 (see image below).

**To Reproduce**

1. Find a repo with no readme (I used b3u/chordy, but subsequently added a readme)
2. Create a new post or comment containing `{% github :user/:repo %}`
3. Preview, and see the error

**Expected behavior**

Possible solutions include displaying "readme not found" in place of the readme itself, and simply defaulting to the `no-readme` option.

**Screenshots**
![image](https://user-images.githubusercontent.com/39805353/75630779-764d2280-5bbb-11ea-8c39-924ed78b8e84.png)

**Desktop (please complete the following information):**
- OS: Ubuntu 18.04 (Elementary OS v5.1)
- Browser: chrome
- Version: 80

**Additional context**

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
PR is open if you wanna check it out @b3u
