### ISSUE TITLE
Can't write a new article - see screenshot

### ISSUE THREAD

**Issue by AlbertoMontalesi** [thepracticaldev/dev.to#6386]
MacOS, Chrome 80.

When i press 'write a post'  this is what i see, no submit buttons, no scrollbar

![image](https://user-images.githubusercontent.com/23130353/75636505-f1f9ae80-5c51-11ea-894a-087bff99aa42.png)

Update: trying again and now it works, not sure what happened earlier.

**Comment by rhymes** [comment]
@AlbertoMontalesi odd! Maybe some extension has blocked the retrieval of resources?

I'm going to close this as it seems to be resolved. Usually the console tab in the developer tools have some hints about what's going on that might be helpful.

Let us know if you encounter this problem again and we'll reopen this.
