### ISSUE TITLE
Code fence not rendering properly

### ISSUE THREAD

**Issue by aaronpowell** [thepracticaldev/dev.to#6390]
I just posted an article with a code fence for JSON, but even though I've put the code fence like I normally use it's rendering in a broken way.

![image](https://user-images.githubusercontent.com/434140/75679796-a556b780-5cd3-11ea-9460-832b0b17ec8f.png)

 I also tried removing the language flag but it didn't fix it.

The article is [here](https://dev.to/aaronpowell/making-it-easier-to-work-with-local-npm-packages-64g).

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @aaronpowell 

would you be able to take a screenshot of the markdown instead of the rendered page? You can also post the markdown itself to a https://gist.github.com/ 

Thank you!

**Comment by aaronpowell** [comment]
@rhymes whoops, that was the screenshot I meant to include

![image](https://user-images.githubusercontent.com/434140/75724895-ac58e680-5d22-11ea-905d-4306ed2466ea.png)

And here's the gist: https://gist.github.com/aaronpowell/789740050e1153a6ba5edb4838478596

**Comment by rhymes** [comment]
I think I found the issue, before the code fence, there's a sentence that contains the word `dependencies`, that word has a trailing apostrophe, that should be a backtick. By fixing that you get correct rendering:

![Screenshot_2020-03-03 New Post - DEV Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/75751456-d44a4900-5d26-11ea-831e-b3fc95d24845.png)

Going to close this, thanks again for raising the issue, it might have been a bug!
