### ISSUE TITLE
Can't update profile page

### ISSUE THREAD

**Issue by jonathanyeong** [thepracticaldev/dev.to#64]
Hey, I just started using Dev.to and I'm loving the site. I was trying to update my profile page and I'm running into a bug. I'm not entirely sure who to tell about these issues. Let me know if this is a known problem or if it's just me! 

**Error:** Github username has already been taken

**How to recreate:** 
Connect github account to dev.to account.
Open up Settings for your dev.to account.
Change something and press "Submit". You should see a error below:

<img width="899" alt="screen shot 2017-07-13 at 8 46 25 am" src="https://user-images.githubusercontent.com/3861088/28169384-c80282d8-67a7-11e7-8872-33d4c6473698.png">

**Comment by jessleenyc** [comment]
Hey @jonathanyeong! Looks like we had two accounts for you and they weren't linked -- you should now be able to login with either twitter or github authentication :)

**Comment by jonathanyeong** [comment]
👏 👏 👏 👏  Thank you @jessleenyc!!
