### ISSUE TITLE
Tag input deletes user input

### ISSUE THREAD

**Issue by jjant** [thepracticaldev/dev.to#6436]
Input field for selecting tags in the "create post" section arbitrarily deletes/messes with user input.
I suspect there's a badly setup debouncing handling or something like that. 

**To Reproduce**

1. Go to dev.to
2. Click on create new post
3. Quickly type and many characters and hit delete a bunch of times, you'll see your input suddenly changing in unexpected ways

**Expected behavior**

The field doesn't mess with user input

**Desktop (please complete the following information):**

- OS: OSX Catalina
- Browser: Brave
- Version: 1.4.95

**Comment by citizen428** [comment]
Thanks for the issue @jjant! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by maestromac** [comment]
Hello @jjant , would you mind sharing an image/gif of this bug?

**Comment by rhymes** [comment]
I recorded a GIF with both listing and article editor, they use the same component AFAIK:

![tagsflicker](https://user-images.githubusercontent.com/146201/75891706-7570f680-5e30-11ea-957b-79388937971d.gif)

![tagsflicker2](https://user-images.githubusercontent.com/146201/75891708-76a22380-5e30-11ea-8814-549ea62de1bf.gif)

I'm going to work on a solution as I think I know what's going on :)
