### ISSUE TITLE
Cannot click notification in notifications page

### ISSUE THREAD

**Issue by JuanitoFatas** [thepracticaldev/dev.to#6438]
**Describe the bug**

Cannot click Notifications in Notification page.

**To Reproduce**

Use a user with not much notifications and visit `/notifications` page.

**Expected behavior**

Can click notification in notifications page.

**Screenshots**
<img width="1440" alt="スクリーンショット 2020-03-04 13 02 30" src="https://user-images.githubusercontent.com/1000669/75844116-7138df00-5e18-11ea-9783-f0e01bcfe8ea.png">

**Desktop (please complete the following information):**

- OS:
- Browser: Firefox 73.0.1 (64-bit)
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by citizen428** [comment]
Thanks, @JuanitoFatas! Since you already opened a PR I assigned you this issue and requested some reviews.

**Comment by rhymes** [comment]
@JuanitoFatas can you describe the issue a bit? I can't seem to reproduce it. What happens? What version of Firefox have you tried with?

**Comment by JuanitoFatas** [comment]
@rhymes I‘m using Firefox 73. Latest Chrome works fine. Below Gif I was trying to click, then I opens up console to show the element is blocking the clicks:

![cannot-click-notification-on-firefox-73](https://user-images.githubusercontent.com/1000669/75882729-18dbfe80-5e65-11ea-988e-8f147ca62606.gif)

cc @ludwiczakpawel
