### ISSUE TITLE
RunKit liquid blocks incorrectly passing escaped HTML entities

### ISSUE THREAD

**Issue by KrofDrakula** [thepracticaldev/dev.to#645]
## Bug Report

The following document creates an invalid RunKit embed on a page:

```
---
title: 
published: false
description: 
tags: 
---

{% runkit %}
const a = b => 3;
{% endrunkit %}
```

### Current Behavior

The `>` character is escaped into `&gt;`, which breaks the source code.

### Expected Behavior

Code should not have escaped HTML entities when passed to the embed code.

### Mobile & Desktop Screenshots/Recordings

![image](https://user-images.githubusercontent.com/112161/45475268-be605700-b733-11e8-9da8-2153b3ac8bc5.png)

### Additional Info (device/browser, helpful links)

Tested in Chrome – Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by Zhao-Andy** [comment]
Hey @KrofDrakula, thanks for the heads up. I have a work in progress PR here related to this issue: https://github.com/thepracticaldev/dev.to/pull/438

My PR would fix it for most cases, but you can't use backticks (and therefore string literals), which is a bit of a pain. We might have to revisit how we parse Markdown as a whole since there could be other similar errors with other Liquid tags.

**Comment by Zhao-Andy** [comment]
Hey @KrofDrakula, this is fixed 👍 via #438. Heads up that there's still an issue with using backticks though (see #694 for more info).

**Comment by KrofDrakula** [comment]
Thanks! I've already made extensive use of it in the latest article, except that runkit seems to be having some embedding issue due to hash integrity, but that's purely an issue on their end.

Also, is there a way to expose more configuration for runkit? Currently it defaults to node v8, is there a way to pass arguments to the embedded widget?

**Comment by Zhao-Andy** [comment]
Based on [their embed page](https://runkit.com/docs/embed#creation-options) we can add some more configuration for the embed. We currently support adding a preamble, but that's about it.

Not sure if the Notebook API section on that same page is what you were looking for in terms of node configuration.

**Comment by KrofDrakula** [comment]
OK, I'll have a look at that and file another issue if I find anything that might be interesting to other users too. 👍
