### ISSUE TITLE
Replace perform_enqueued_jobs with sidekiq_perform_enqueued_jobs

### ISSUE THREAD

**Issue by juliannatetreault** [thepracticaldev/dev.to#6452]
**Describe the issue**
There are a handful of specs that use `perform_enqueued_jobs` in place of `sidekiq_perform_enqueued_jobs` (and at times both within the same spec), which can be confusing. Removing all instances of `perform_enqueued_jobs` in favor of `sidekiq_perform_enqueued_jobs` will both alleviate confusion and establish a convention going forward.

Further context can be found here: [#6221 (comment)](https://github.com/thepracticaldev/dev.to/pull/6221#discussion_r387646723)

**Comment by rhymes** [comment]
Thanks for catching this! 

It's weird they are still there as we're using Sidekiq for jobs, and not ActiveJob anymore

I'm not sure why tests are passing 👀

Probably because they aren't needed at all?

**Comment by vaidehijoshi** [comment]
@rhymes more context on that here: https://github.com/thepracticaldev/dev.to/pull/6221#discussion_r387646723

**Comment by rhymes** [comment]
Emails! Right! :)
