### ISSUE TITLE
Runkit is rendering as plain text when published

### ISSUE THREAD

**Issue by joelnet** [thepracticaldev/dev.to#6460]
**Describe the bug**

Runkit embeds are rendering as plain text.

**To Reproduce**

https://dev.to/joelnet/creating-a-linked-list-using-only-function-combinators-5hhk

Scroll to the section with this text:

```
/////////////////////////////////////////////////////////////////
//// 📌 ATTENTION: You can modify and run these code blocks! ////
/////////////////////////////////////////////////////////////////
```

**Expected behavior**

It should be rendered with runkit, instead it is plain text

**Screenshots**

![image](https://user-images.githubusercontent.com/742630/75917850-878e6d00-5e0f-11ea-8810-9d392d8f1f64.png)

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome / Brave / Safari
- Version: Latest

**Additional context**

Runkit renders correctly when in preview mode. If I click [edit] then [preview] I can see Runkit has rendered correctly

![image](https://user-images.githubusercontent.com/742630/75917972-bd335600-5e0f-11ea-9a6e-905adf08dc98.png)

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by maestromac** [comment]
Hello @joelnet , I was unable to reproduce this. Can you help me do a sanity check and attempt to preview/resave your article and see if the issue persists?

**Comment by joelnet** [comment]
I just hit edit and then save and there was no effect. Maybe there is an issue with the content of the article itself? Maybe unicode characters (emojis)?

Here's the full content of the article to see if it can be replicated in another account:

https://gist.github.com/joelnet/5a464c9ed5f1d4e5fb3342652dfe1e04

I am also seeing this error in the console on all article pages on dev.to:

```
Uncaught SyntaxError: Unexpected token '&' creating-a-linked-list-using-only-function-combinators-5hhk:2376

var videoPreviews = document.getElementsByClassName(&quot;ltag__twitter-tweet__media__video-wrapper&quot;);
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I don't know if it is related. I filed a separate bug #6485 for it.

**Comment by rhymes** [comment]
Hi @joelnet, I checked https://dev.to/joelnet/creating-a-linked-list-using-only-function-combinators-5hhk and it seems to be fixed, let us know if you are still experiencing the issue :)

**Comment by joelnet** [comment]
Yep. It is fixed! I did have to edit the article to "refresh" it. But once I did that it all started working again.

I thought about posting this update in here, but then didn't want to cause noise. But thanks for checking in.

And thanks everyone for being awesome! 👍

Cheers! 🍻
