### ISSUE TITLE
500 error when navigating to https://dev.to/settings/organization

### ISSUE THREAD

**Issue by piannaf** [thepracticaldev/dev.to#6462]
**Describe the bug**

Getting error when navigating to https://dev.to/settings/organization

**To Reproduce**

1. Go to https://dev.to/settings/organization
2. See error "We're sorry, but something went wrong (500)"

**Expected behavior**

Expect to be able to edit organization settings

**Screenshots**

![image](https://user-images.githubusercontent.com/70764/75924724-748e9380-5e35-11ea-9e92-782c261170f0.png)

**Desktop (please complete the following information):**

- OS: macOS 10.14.6
- Browser: Chrome 
- Version: 80.0.3987.116

**Comment by citizen428** [comment]
Hello @piannaf, thanks for notifying us of this problem, this looks an issue specific to your account, as it works fine for me both in development as well as on the live site.

Please email yo@dev.to for more help.

**Comment by maestromac** [comment]
Upon investigation, I think this might be related to one of your org members. Is the rest of your team also having an issue accessing  https://dev.to/settings/organization ?

**Comment by piannaf** [comment]
I asked other people in the org to log in. We tried Twitter and Github logins.

The pattern we noticed

* non-admins did not see the issue in either case
* admins got the 500 error in both cases

**Comment by benhalpern** [comment]
Looks like this is the error...

```
ActionView::Template::Error: undefined method `path' for nil:NilClass

    _org_admin.html.erb 24 block in _app_views_users__org_admin_html_erb(...)
    [PROJECT_ROOT]/app/views/users/_org_admin.html.erb:24:in `block in _app_views_users__org_admin_html_erb'

    22   <% @org_organization_memberships.each do |org_membership| %>
    23     <div class="settings-org-member-row <%= "settings-org-admin-row" if org_membership.type_of_user == "admin" %>">
    24       <a href="<%= org_membership.user.path %>"><%= org_membership.user.name %></a>
    25       <div class="settings-org-member-actions">
    26         <% if org_membership.user == @user && org_membership.type_of_user == "admin" %>
```

Looks like there's an `org_membership` belonging to the org that doesn't have a `user`.

**Comment by maestromac** [comment]
Hey @piannaf , I believe I resolved this. Can you go ahead and try to access your https://dev.to/settings/organization again?

**Comment by piannaf** [comment]
Yup, working now! Thank you!
