### ISSUE TITLE
Profile dropdown doesn't open when coming from a mail link

### ISSUE THREAD

**Issue by awebartisan** [thepracticaldev/dev.to#6468]
**Describe the bug**
We receive email notifications like new followers etc. When I click on any link on email, it redirects me to DEV website but the profile dropdown doesn't work and also thumbnail disappears. Therefore can't visit Dashboard and other important links.

**To Reproduce**

1. Make sure you are signed into DEV
2. Go to an email of New follower on DEV
3. Click on any link and be redirected to DEV
4. Watch out for Profile thumbnail in navigations right corner

**Expected behavior**

Dropdown is supposed to work.

**Screenshots**

![dev-to-profile-dropdown](https://user-images.githubusercontent.com/29105478/75949496-3ee6ba80-5ec8-11ea-9234-12a6f2fe68b3.png)

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version: 80.0.3987.122 (Official Build) (64-bit)

**Additional context**

A video link explaining the problem:
[https://www.loom.com/share/9ad70239264a4abaa68314ae13b2afe9](https://www.loom.com/share/9ad70239264a4abaa68314ae13b2afe9)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Thanks a lot for the video @awebartisan, it's mighty helpful.

I noticed something odd thanks to it, the landing URL points to the message, and not to https://dev.to/dashboard/user_followers where you should see your new followers

**Comment by maestromac** [comment]
I was able to reproduce this issue on Safari, Chrome, and Firefox. Each has their own similar error
```
Firefox -> SyntaxError: redeclaration of const sponsorClickHandler
Safari -> SyntaxError: Can't create duplicate variable: 'sponsorClickHandler' 
Chrome -> Uncaught SyntaxError: Identifier 'sponsorClickHandler' has already been declared
```
I am uncertain if that is what's causing the exception errors that broke profile drop-down. I do see my profile brief flash before overwritten by a black image but I'm uncertain what that really means. I also can't reproduce this in development. I'm going to submit a PR to attempt to solve it.
