### ISSUE TITLE
Glitch when typing on #tag post 

### ISSUE THREAD

**Issue by mandaputtra** [thepracticaldev/dev.to#6478]
**Describe the bug**

When I want to write tags sometimes space will delete my char and search for common tags, this bug happening when you write uncommon tag, here the [video](https://youtu.be/FWcIuG7AEzg) 

**To Reproduce**

1. Write post.
2. Write uncommon tag
3. Tag form start making glitch.

**Expected behavior**

Flawless experience when writing tags

**Screenshots**

No screenshoot, here 1 minute [video](https://youtu.be/FWcIuG7AEzg)

**Desktop (please complete the following information):**

- OS: Ubuntu 19.10
- Browser: Chrome 
- Version: latest

**Additional context**

No. But I think its because the search of tag.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by mandaputtra** [comment]
Thanks, I'll tackle this issue and work on it in weekend.

**Comment by mandaputtra** [comment]
Hello @thepracticaldev/oss, its my first timers looking on Ruby codebases, could you point me where are the script for searching tag?

**Comment by rhymes** [comment]
Hi @mandaputtra! 

So, the code that contains the tags component is here: https://github.com/thepracticaldev/dev.to/blob/master/app/javascript/shared/components/tags.jsx

Tags are fetched from the search index so you'll need to have Elasticsearch running, see the [installation guide](https://docs.dev.to/installation/) for your operating system, and indexed with tags.

Once all is installed and you ran `bin/setup`, tou can open the console to index the tags by issuing: `Tag.find_each(&:index_to_elasticsearch_inline)`. After that all your tags will be available as results locally.

Let me know if you need further help, and thank you!

**Comment by iamjoross** [comment]
@mandaputtra : I have experienced the same bug. I can help you out if you're stuck.

**Comment by mandaputtra** [comment]
@rhymes @iamjoross thanks, how do you login on local? I'm stuck on this step for now :thinking: is there any secrets should I use to go to writing-page?

![Login page on writings](https://user-images.githubusercontent.com/23342943/76407994-d95e6680-63be-11ea-8f3a-844d96be3084.png)

**Comment by rhymes** [comment]
You need to sign up wither with Twitter or Github, but first you need to configure either.

See https://docs.dev.to/backend/authentication/

You'll need to add the `GITHUB_KEY`/`GITHUB_SECRET` or `TWITTER_KEY`/`TWITTER_SECRET` or both to your local `application.yml`

Then you can login :)

Let me know if you have further questions!

**Comment by mandaputtra** [comment]
Done, one line fix :lollipop:

**Comment by rhymes** [comment]
Closed by https://github.com/thepracticaldev/dev.to/pull/6598
