### ISSUE TITLE
Github handle changes

### ISSUE THREAD

**Issue by johnlukeG** [thepracticaldev/dev.to#65]
This is just a thought and probably not a very common problem. I signed up for the site and then changed my Github name a few weeks later. There's no way to edit that handle on the site and if any users click through to my github profile, they'll find a broken link. I'd be happy to help to take a look at it if no one has time but I didn't realize that the project wasn't completely open source. Thanks for the help in advance and for your work on the site, it's great!

**Comment by Zhao-Andy** [comment]
Hey, thanks for the heads up! It's a slight problem that some users have and it's currently on our roadmap. I just updated your account to "johnlukeG". :)

**Comment by johnlukeG** [comment]
You are the man! Thank you for the quick response and action, Andy. Once it's open sourced, I'll hop on an issue/feature to pay it forward.
