### ISSUE TITLE
Can't update my profile info.

### ISSUE THREAD

**Issue by cascadebuildtech** [thepracticaldev/dev.to#6518]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hello @cascadebuildtech, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
