### ISSUE TITLE
Can't highlight old chat text

### ISSUE THREAD

**Issue by samuraiseoul** [thepracticaldev/dev.to#654]
### Current Behavior
Can't highlight previous chat text so that you can copy/right click

### Expected Behavior
Being able to highlight previous text in chat in order to copy/right click
 
### Mobile & Desktop Screenshots/Recordings
Can't really capture it as I don't have video recording set up/a still image won't work. 

### Additional Info (device/browser, helpful links)
Kubuntu 16 on Chrome

**Comment by Zhao-Andy** [comment]
Hey @samuraiseoul, thanks for the report. This is a known bug and we'll work on fixing it. 👍

**Comment by jessleenyc** [comment]
Hey @samuraiseoul! Closing this because I just realized this is a duplicate and that there's more discussion in the other issue: https://github.com/thepracticaldev/dev.to/issues/568

**Comment by samuraiseoul** [comment]
No worries, thanks for linking me!
