### ISSUE TITLE
Typo on badge page

### ISSUE THREAD

**Issue by RDIL** [thepracticaldev/dev.to#6542]
On https://dev.to/badge/beloved-comment there is a spacing typo, I would be glad to fix it, but I can't seem to find where it is defined.

**Comment by rhymes** [comment]
Hi @RDIL, badges are stored in the DB, I'm going to forward this internally, thank you a lot for catching this! I'll report back when it's fixed

**Comment by rhymes** [comment]
Hi @RDIL - I believe the spacing issue has been fixed https://dev.to/badge/beloved-comment - let me know if that wasn't the full scope of the typo.

Thanks again!

**Comment by RDIL** [comment]
Its good now 👍
