### ISSUE TITLE
[P2] Implement progress stepper + skip/continue

### ISSUE THREAD

**Issue by lisasy** [thepracticaldev/dev.to#6544]
### Description
- Implement a **progress stepper** that orients people on which step they're on during onboarding.
- Implement updates to modal navigation so that people can "skip for now" (if they haven't filled out anything) or "Continue".

### F.A.Q's

**For which steps do we apply the `Skip/Continue` functionality?**
- Step 1. Suggested Topics
- Step 2. Build Your Profile
- Step 3. Suggested People

**What happens if a user goes back or clicks on skip/continue? Does it take them to the end of the flow?**
- ◀️ When people go back, it takes them to the previous step.
- ▶️ When people skip/continue, it takes them to the next step.

### Design Assets

![# 6544 Progress Stepper + Skip](https://user-images.githubusercontent.com/816402/76904961-3a25ed00-685e-11ea-93d6-eb915d0bbadc.png)

[✨ Figma URL ✨](https://www.figma.com/file/fQthjjBLgDLRaHmpIwlhdS/Onboarding?node-id=539%3A0)

**Comment by vaidehijoshi** [comment]
This should be fairly straightforward to implement and add into `Onboarding.jsx`. We already have access to `currentSlide` and the list of slides; we should be able to derive which slide of the entire list we're currently on by checking the index of `currentSlide`.

**Comment by lisasy** [comment]
Heads-up: Crayon styles are now in the `master` code base, and I've begun to use bits of it in my P1 PR. I'm going to check in with Paweł to get his further recommendations on how to begin bringing Crayons styles in since we don't have too much docs for that yet.
