### ISSUE TITLE
[P2] Move TOC/COC to first intro slide

### ISSUE THREAD

**Issue by lisasy** [thepracticaldev/dev.to#6545]
![Intro Slide](https://user-images.githubusercontent.com/816402/76819914-e0beaf00-67c6-11ea-88e1-e1c372e00d8c.png)

[✨ See Figma URL ✨](https://www.figma.com/file/fQthjjBLgDLRaHmpIwlhdS/Onboarding?node-id=536%3A200)

**Comment by vaidehijoshi** [comment]
This task will involve the following: 
- [ ] Extract "Terms & Conditions" and "Code of Conduct" out of `EmailListTermsConditionsForm` component, and move it into a new component, `TermsConditionsForm`.
- [ ] Create a new component for "Terms & Conditions" and "Code of Conduct", and ensure that it is the first slide visible within the Onboarding flow.

**Comment by lisasy** [comment]
In the existing flow, there is an error notice that triggers when the user attempts to progress to the next step without selecting the fields. However, based on the way we've designed users progress, the "Get Started" CTA is not clickable/tappable *until* they select the fields.

Would this mean you remove this error notice functionality, as well?

<img width="758" alt="Screenshot 2020-03-16 20 46 08" src="https://user-images.githubusercontent.com/816402/76820088-4f037180-67c7-11ea-966b-74be4ed575c3.png">

**Comment by vaidehijoshi** [comment]
@lisasy It depends on what kind of flow you'd like the users to have while progressing through these forms.

I've worked with designers who wanted the button to be clickable (and _not_ be disabled), and then let the users click the button, and see an error message that showed them the problems with the form.

Personally, I've always liked the approach of disabling the button and not letting it be submitted until all the fields were filled out (and then only showing the error if something was invalid). In this case, there isn't an input or field, it's just checkboxes, so there isn't any "invalid" state, just a checkbox that needs to be checked for us to progress forward. If we took this approach, I'd say that we just don't allow the button to be clicked and then we don't need to show a red error state.

**Comment by lisasy** [comment]
@vaidehijoshi 

Based on the proposed mocks, the button won't be clickable until both fields are completed; there would be no need to have an error because the disabled buttons would itself signify that they cannot proceed forward. It looks like we're thinking the same thing! :)

**Comment by vaidehijoshi** [comment]
@lisasy Just realized that in the figma designs provided here, we also include the user's name in the heading (ex.: `Maria - Welcome to DEV!`). Looks like we don't have that on production yet, would you like me to include that change as part of this ticket?

**Comment by lisasy** [comment]
@vaidehijoshi Yes, we want to include their name :) It makes this more personable!
