### ISSUE TITLE
[P2] Combine profile slides

### ISSUE THREAD

**Issue by lisasy** [thepracticaldev/dev.to#6546]
### Design assets
![#6546 build your profile](https://user-images.githubusercontent.com/816402/76923262-301ce200-6890-11ea-8ee3-a2c8da462697.png)

**✨ [Figma URL](https://www.figma.com/file/fQthjjBLgDLRaHmpIwlhdS/Onboarding?node-id=547%3A0) ✨**

Questions:
- Can we pull in user image, name from auth source?

**Comment by vaidehijoshi** [comment]
This data already exists on `window.userData()`, so we should be able to use it directly or pass it in as the `props` of the `BioForm` component.
