### ISSUE TITLE
[P2] Add footer toggle & animation for "Suggested Topics"

### ISSUE THREAD

**Issue by lisasy** [thepracticaldev/dev.to#6548]
### Description
Create a modal footer that lets people know the # of topics they've selected.

Two-states:
- `0 topics selected` - font-weight is medium
- `1+ topics selected` - font-weight is bold

### Design assets
![#6548 suggested topics](https://user-images.githubusercontent.com/816402/76999539-04434000-6914-11ea-865a-a5db4663f31b.png)

[✨ Figma URL ✨](https://www.figma.com/file/fQthjjBLgDLRaHmpIwlhdS/Onboarding?node-id=551%3A21375)

**Comment by vaidehijoshi** [comment]
We already have access to `selectedTags` in the `FollowTags` component. We should be able to access the `length` of the `selectedTags` and render that at the bottom of the jsx.
