### ISSUE TITLE
[P2] Add footer toggle & animation for "Suggested People"

### ISSUE THREAD

**Issue by lisasy** [thepracticaldev/dev.to#6549]
### Description
Create a modal footer that lets people know the # of people they're following

States:
| States    | CTA | 
| :---        |    :----:   | 
| Following nobody      | Select all [x] people       | 
| Following someone   | Select all [x] people        |
| Following everyone   | Deselect all        |

### Design assets
![#6549 suggested people](https://user-images.githubusercontent.com/816402/77004453-58522280-691c-11ea-86cf-ab13b5d2154d.png)

[✨ Figma URL ✨](https://www.figma.com/file/fQthjjBLgDLRaHmpIwlhdS/Onboarding?node-id=551%3A22332)

**Comment by vaidehijoshi** [comment]
This will involve more css work than anything else. We already have access to `selectedUsers` in the `followUsers` component, and we can logic similar to what we'll do in addressing #6548 to render the selected user count in the footer of this modal view.
