### ISSUE TITLE
[P2] Move email preferences to last slide

### ISSUE THREAD

**Issue by lisasy** [thepracticaldev/dev.to#6550]
[✨ Figma URL ✨](https://www.figma.com/file/fQthjjBLgDLRaHmpIwlhdS/Onboarding?node-id=345%3A11128)

**Comment by vaidehijoshi** [comment]
This will involve pulling out the email preferences out of the `EmailTermsConditionsForm` and into a new slide (the last one) in the Onboarding modal.
