### ISSUE TITLE
<FEED> not displaying on Firefox when logged in

### ISSUE THREAD

**Issue by phlash** [thepracticaldev/dev.to#6559]
What happens:
 * Request front page (dev.to), defaulting to &lt;FEED&gt; display
 * Everything loads except the post feed
 * Browser console error:
  > TypeError: a.find is not a function Feed.jsx:16:38

My info:
 * Browser: Firefox 68.5.0esr, on Debian 10 stable, uBlock origin installed
 * Network: PiHole DNS blacklist enabled

Tests conducted:
 * disable uBlock origin - no change
 * browse from outside my PiHole'd network (via SOCKS5 tunnel including DNS) - no change
 * select different display, eg: &lt;LATEST&gt; - all ok
 * open private browsing window (so logged out), navigate to dev.to front page - all ok on &lt;FEED&gt;

Possibly related: https://dev.to/dcruz1990/i-have-a-infinite-loading-dev-to-index-on-my-android-app-why-507p

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @philnash! Thanks for the report.

Does it happen to you with other browsers as well? Can you try and report back?

**Comment by phlash** [comment]
Not sure if anyone changed anything, but it's all ok today (no JS error and renders correctly).
