### ISSUE TITLE
Docker with non default Postgres requires set password

### ISSUE THREAD

**Issue by abenettt** [thepracticaldev/dev.to#6563]
**Describe the bug**
When starting the postgres docker container with a version that is higher than the default it crashes saying the super user password is unset.
```bash
Attaching to devto_db_1
db_1             | Error: Database is uninitialized and superuser password is not specified.
db_1             |        You must specify POSTGRES_PASSWORD to a non-empty value for the
db_1             |        superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
db_1             |
db_1             |        You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
db_1             |        connections without a password. This is *not* recommended.
db_1             |
db_1             |        See PostgreSQL documentation about "trust":
db_1             |        https://www.postgresql.org/docs/current/auth-trust.html
```

**To Reproduce**
Run:
```bash
POSTGRES_VERSION=11.6-alpine docker-compose up db
```

**Expected behavior**
The container to start properly

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @abenettt, I edited the title a bit to make it clearer that this happens with a non default version. Though it's definitely a bug, as we use PostgreSQL 11 in production and I use PosgreSQL 12 locally.

Were you able to boot it up with PostgreSQL 10? Trying to understand if something changed in PostgreSQL 11 related to this...

**Comment by abenettt** [comment]
I was unable to start it with PostgreSQL 10 too.

**Comment by abenettt** [comment]
I added a PR and tried it out locally and everything seems to work there.

**Comment by amitatpug** [comment]
I had similar problem.
I found the solution at below link
http://support.divio.com/en/articles/3719228-database-is-uninitialized-and-superuser-password-is-not-specified

**Comment by Oleg-levwa** [comment]
Hello! I'm a beginner. I can not enter the arcadeanalytics / postgres-dvdrental database. Error: You must specify POSTGRES_PASSWORD to a non-empty value for the

superuser. For example, "-e POSTGRES_PASSWORD = password" on "docker run".

You may also use "POSTGRES_HOST_AUTH_METHOD = trust" to allow all

connections without a password. This is * not * recommended.
I use docker and kitematic Windows 10. And the program "DBeaver" for working with databases. Tell me, how can I fix the error and get access to the database?

**Comment by fagbolaoluwagbenga** [comment]
try running the following command in your cli 
$ docker run -e POSTGRES_PASSWORD=yourPassword container-id

**Comment by henrynguyen6677** [comment]
```
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
```
You **need config environment variables** ex: **POSTGRES_PASSWORD=postgres** at file docker-compose.yml
Link guide at https://docs.docker.com/compose/environment-variables/

**Comment by HafidElhafa** [comment]
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD to a non-empty value for the
       superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".

       You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
       connections without a password. This is *not* recommended.

       See PostgreSQL documentation about "trust":
       https://www.postgresql.org/docs/current/auth-trust.html
i have this error how can i solve it?
