### ISSUE TITLE
Cannot remove pinned GitHub repositories from profile.

### ISSUE THREAD

**Issue by leonardosnt** [thepracticaldev/dev.to#6571]
**Describe the bug**

Clicking in the Remove button in the "Pin a few of your GitHub repos to your profile" section does not remove the repository from your Pinned repositories.

Observing the network activity we can see that a POST request is sent to https://dev.to/github_repos/update_or_create with `featured` set to `false`

```
------WebKitFormBoundaryJSPfqsd1l1CtbXst
Content-Disposition: form-data; name="github_repo"

{"github_id_code":92339815,"featured":false}
------WebKitFormBoundaryJSPfqsd1l1CtbXst--
```

but the response returns

```json
{"featured":true}
```

**To Reproduce**
1. Go to https://dev.to/settings/integrations
2. Try to remove a pinned repository.
4. It won't work

![dev-to--bug](https://user-images.githubusercontent.com/13869336/76338477-7d6ce280-62d7-11ea-96d9-895a162a0b53.gif)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
I think I found the reason why, working on a PR, thanks for raising this issue @leonardosnt!

**Comment by rhymes** [comment]
@leonardosnt this should be all right on dev.to right now. I tested with my profile and it worked, let me know if it works for you too. 

Thanks!

**Comment by leonardosnt** [comment]
@rhymes It's working for me. Thanks!
