### ISSUE TITLE
You get notified if you reply to your reply

### ISSUE THREAD

**Issue by bgadrian** [thepracticaldev/dev.to#658]
Hello,

I noticed a small problem today. Repro:

Write a reply to a post
Within few minutes write a reply to that reply
Must be the first reply of the reply I think.
I received an email notification.

I smell some lack of defensive prog 😀

**Comment by Zhao-Andy** [comment]
Hey @bgadrian, thanks for the report. We'll take a look into it.

**Comment by maestromac** [comment]
Should be resolved with #699. Let us know if otherwise!
