### ISSUE TITLE
Is there any centering kind of thing for post content?

### ISSUE THREAD

**Issue by ankitkanojia** [thepracticaldev/dev.to#6590]
Greetings dev.to developers,

Actually when I'm trying to post an article on Dev.To I need to make centering the sentence for better display purpose, but somehow I can't make it center.

Is there anything similar to centering the text on posting the article?

**Comment by maestromac** [comment]
Hey @ankitkanojia , you can use the `<center>` tag to center texts. Give it a try and let us know if that fits your needs.

**Comment by ankitkanojia** [comment]
Hello @maestromac, Perfect !!!

It work as expected. Thank you so much for your time.

**Comment by ankitkanojia** [comment]
I know it a silly question but @maestromac, why there is no editor such kind of thing for design post content. We need to read the instruction to make it proper. I think you should develop an editor for content drafting. Don't you think? Please advice

**Comment by maestromac** [comment]
@ankitkanojia Happy to hear that solved it for you. If you are referring to a WYSIWYG editor, we currently don't have any plan for that yet.

**Comment by ankitkanojia** [comment]
Great !!!... Thank you so much @maestromac ... Your Team(Dev.To) Rocks!!!!!
