### ISSUE TITLE
Some GIFs do not render

### ISSUE THREAD

**Issue by 2color** [thepracticaldev/dev.to#6595]
**Describe the bug**

Some GIFs don't render when embedded with `![]()`. Both when uploaded to imgur or as body images to `dev.to`. 

The problem seems to relate to the size of the Gif. When the Gif is under 1.1MB, it's fine. However, if it's bigger you see the following:

<img width="786" alt="Screenshot 2020-03-11 at 19 17 23" src="https://user-images.githubusercontent.com/1992255/76449794-fa2db880-63cc-11ea-9e2c-6a46cacafec4.png">

The URL which fails to fetch in the developer tools network tab is: https://res.cloudinary.com/practicaldev/image/fetch/s--YEtScEyS--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_66%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/i/ruuqyho8i2ddv5kmy6fj.gif

The gifs were recorded with https://gifox.io/. 

**To Reproduce**

1. Record a gif with gifox
2. Upload as a body image
3. Embed with the markdown link

**Expected behavior**

Render the Gif correctly

**Additional context**

Doesn't seem to be related to device, but rather network or backend.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Ok, so it might be an issue with Cloudinary.

The original uploaded gif works: https://dev-to-uploads.s3.amazonaws.com/i/ruuqyho8i2ddv5kmy6fj.gif

The cloudinary URL doesn't: https://res.cloudinary.com/practicaldev/image/fetch/s--YEtScEyS--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_66%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/i/ruuqyho8i2ddv5kmy6fj.gif
