### ISSUE TITLE
Twitter link missing from commenting users' identities

### ISSUE THREAD

**Issue by vgrovestine** [thepracticaldev/dev.to#66]
As the original poster of an article, links to that user's Dev.to, Github and Twitter profiles are visible.

As a commenting user, however, the Twitter link is missing; only Dev.to and Github are present.

See screenshot: I have both my Twitter and Github accounts linked to Dev.to; however, the Twitter icon is clearly missing from comments I posted.

![screenshot from 2017-08-01 09-39-52](https://user-images.githubusercontent.com/11873315/28825627-677e81aa-769d-11e7-90c3-6497f6c5197d.png)

**Comment by jessleenyc** [comment]
Hmm, strange. Doesn't seem to be an issue for me. 
![image](https://user-images.githubusercontent.com/14931921/28831370-600b8788-76a7-11e7-8d66-23cf989d0590.png)

Can you tell me if it's still happening? If so, what browser/device you're viewing from?

**Comment by vgrovestine** [comment]
I found the culprit. The Twitter icon is being forced "display: none !important" by the AdBlock plugin for Chrome. Screenshot of all blocked assets attached.

![screenshot from 2017-08-01 13-07-54](https://user-images.githubusercontent.com/11873315/28835114-b99009f6-76ba-11e7-91fa-8222ba6d930d.png)

**Comment by vgrovestine** [comment]
Quick update: Twitter icon still not showing in Chrome (v62). I've whitelisted Dev.to in both AdBlock and Ghostery which are the only blocking/tracking addons I have installed. Chrome continues to block the Twitter logo, however. No such issue with Firefox (v56) though.

![screenshot from 2017-10-25 09-37-30](https://user-images.githubusercontent.com/11873315/31999180-cfd38d28-b968-11e7-832f-c59a798d4efc.png)

![screenshot from 2017-10-25 09-41-44](https://user-images.githubusercontent.com/11873315/31999194-da267858-b968-11e7-9bde-8cbd8e904e4d.png)

**Comment by Zhao-Andy** [comment]
Hmm interesting, I have uBlock Origin and it doesn't block for that. Thanks for more info.

**Comment by Link2Twenty** [comment]
I've had a play with adblocker for chrome if you have "Antisocial filter list" enabled it will remove anything that links to a social network. 

Though that checkbox is off by default and the twitter icons didn't vanish until I turned it on.

**Comment by Link2Twenty** [comment]
@vgrovestine can you check to see if you have "Antisocial filter list" enabled, please?

@Zhao-Andy @benhalpern @jessleenyc I think this issue can probably be closed while we wait for Vincent's reply, it has been inactive for over a year.

**Comment by jessleenyc** [comment]
@Link2Twenty good call. @vgrovestine feel free to reopen if it's still an issue but closing for now.
