### ISSUE TITLE
Ooooops... You have encountered an error.

### ISSUE THREAD

**Issue by bestwaye** [thepracticaldev/dev.to#6605]
Our team has been notified. Please feel welcome to also submit a public bug report. We apologize for any inconvenience.

anyone, please tell me why this type error on dev.to

**Comment by maestromac** [comment]
Hello @bestwaye , where are you seeing this error? can you kindly provide a screenshot?

**Comment by Harsha-Ambati** [comment]
iam getting this error when iam writing a new post

**Comment by rhymes** [comment]
Hello @Harsha-Ambati, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.

**Comment by slatewala** [comment]
Hi

I am also facing the same problem .. if some one can help me about the same. 
https://dev.to/saifuddinss

**Comment by slatewala** [comment]
pls someone help
