### ISSUE TITLE
Inline LaTeX (KaTeX) is forced to be block-level.

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [thepracticaldev/dev.to#6627]
**Describe the bug**

Authors cannot use LaTeX inline, like so:

```
The function {% katex %}f(x){% endkatex %} maps an input {% katex %}x{% endkatex %} to an output {% katex %}y{% endkatex %}.
```

**To Reproduce**

1. Draft a new post.
2. Copy the above example into the body.
3. Observe that the KaTeX tags are forced to render at a block level:

**Expected behavior**

Users should be able to create both inline and block-level code.

**Screenshots**

![image](https://user-images.githubusercontent.com/19352442/76624388-93fb7f80-650b-11ea-9c55-8dfbe3ca5210.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**

I'm able to render both inline and block-level LaTeX on my blog using KaTeX. Here's an example:

https://aleksandrhovhannisyan.github.io/blog/cs101/least-squares-method-explained-part-1-mastering-least-squares-theory/

To get this to work, I followed an [excellent tutorial from Cheng Xu](https://xuc.me/blog/katex-and-jekyll/). It requires adding jQuery and replacing all default-rendered Mathjax with KaTeX. The code can be found here:

https://gist.github.com/xu-cheng/cb91d3284971250cb14e#file-katex_render-js

To avoid loading jQuery unless it's truly necessary, you could do what I do and add a front-matter variable called `needsLatex` or something like that to serve as a gatekeeper. Only posts that need it will then import jQuery and the KaTeX scripts and stylesheets.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by maestromac** [comment]
So our Katex was implemented with Liquid Block instead of Liquid tag. See the distinction below.

```md
# tag
{% katex f(x) %}

# block
{% katex %}
  f(x)
{% endkatex %}
```

The current katex block is also defaulting `display_mode: true`(which center aligns)  and wrapping the whole rendered item in a div, making inline possible.

I would say ideally we have both forms of implementation under the same name so our users can use whatever fits them but that wouldn't be possible because we can't register two tag/block under the same name, ie: one will have to be `{% ktx %}` for the inline tag and the `{% katex %}` full block.

It's not clear to me yet what's the best direction for this. I welcome any suggestion

**Comment by citizen428** [comment]
@maestromac Would it be possible to add an option like `block: true` to the tag and then update the code to something like this?

```ruby
Katex.render(block, display_mode: block)
```

It would then be called like `{% katex block: false %}f(x){% endkatex %}` (syntax may be off, just trying to outline the idea). Then in the template we could probably use a `span` and use an inline `display` attribute to switch it between `inline` and `block`.

**Comment by citizen428** [comment]
I spiked it, it works:

<img width="483" alt="Screen Shot 2020-03-17 at 11 11 56" src="https://user-images.githubusercontent.com/47985/76821490-a691f380-6840-11ea-9f97-28313309cdc8.png">

Will open a PR in a bit when I polished this off.

**Comment by AleksandrHovhannisyan** [comment]
Nice, thanks!

**Comment by ZenulAbidin** [comment]
I'd also like support for inline KaTeX tags, they would be very useful in long paragraphs so as to not break the flow.

**Comment by citizen428** [comment]
No problem @ZenulAbidin, hope the inline tags work well for you 😃
