### ISSUE TITLE
Bug encountered! Please  help me to fix this ..from long back i am facing this issue

### ISSUE THREAD

**Issue by Rahul626** [thepracticaldev/dev.to#6630]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Every Browser
- Version:

**Smartphone (please complete the following information):**

- Device: 
- OS:
- Browser:
- Version:

**Additional context**
![image](https://user-images.githubusercontent.com/42401032/76646868-be881f80-6581-11ea-81c2-9510c4aeb29d.png)

**Comment by citizen428** [comment]
Hello @Rahul626, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help. Make sure to include as much information as possible, so we are able to help you better.
