### ISSUE TITLE
[suggestion] - Search filter for Reading List

### ISSUE THREAD

**Issue by Olyno** [thepracticaldev/dev.to#6644]
**Is your feature request related to a problem? Please describe.**

I added a lot of articles in my Reading List. Problem: it's really hard to find any article I want.

**Describe the solution you'd like**

A simple search bar on the right of the header, that should filter reading list on keyup. Should not be hard to implement, and could be really usefull.

**Describe alternatives you've considered**

I don't see any other way to find faster what I'm searching.

**Additional context**

/

**Comment by citizen428** [comment]
Thanks for the issue @Olyno! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
@Olyno Do you think your issue is covered by #709? In that case, could you maybe just post a comment there and we close this issue to avoid duplicates? Thanks!

**Comment by Olyno** [comment]
Hi @citizen428, thanks for you reply. Indeed I didn't see this issue, my bad. I close this one to add my idea in this already existing issue 😄
