### ISSUE TITLE
Missing foreman gem, when running bin/startup 

### ISSUE THREAD

**Issue by ledestin** [thepracticaldev/dev.to#6646]
**Describe the bug**

Running ./bin/startup yields `rbenv: foreman: command not found`. Foreman gem is not in Gemfile either.

**To Reproduce**

1. Install dev.to locally as per docs. I ran `bundle` and `yarn` and `rake db:setup`.
2. Run ./bin/startup and get:
```
$./bin/startup
== STARTING UP ==
rbenv: foreman: command not found

The `foreman' command exists in these Ruby versions:
  2.3.3
  2.3.8
  2.4.1
  2.4.4
  2.4.5
  2.5.0
  2.5.1
  2.5.3
  2.5.4
  2.5.7
  2.6.1
```

**Expected behavior**

Foreman gem would be installed as a dev dependency and ./bin/startup would work.

- OS: Debian Linux 9.12
- Browser:
- Version:

**Comment by rhymes** [comment]
Hi @ledestin, according to the message, you're missing `foreman`, as you indicated in step 1 you haven't run `bin/setup` but only `rails db:setup`, please run `bin/setup` as indicated in the [linux installation guide](https://docs.dev.to/installation/linux/).

I'm going to close this, let me know if you're still encountering issues!
