### ISSUE TITLE
Document the maintainer workflow (where is the list of labels, which ones to use)

### ISSUE THREAD

**Issue by Ridhwana** [thepracticaldev/dev.to#6663]
https://www.notion.so/devto/Workflow-Documentation-Draft-4daedb0551e141f2ac2f3fd5f8aa6d94

1. Where is the list of labels,
2. Which labels to use

**Comment by Ridhwana** [comment]
1. Where is the list of labels, 
2. Which labels to use

**Comment by citizen428** [comment]
To our awesome contributors: please note that issues labelled `DEV team` will be worked on by a core team member, so they are not up for grabs.

**Comment by Ridhwana** [comment]
Done, if you are a DEV team member, please ping Team OSS for a link to the document 😊
