### ISSUE TITLE
Address /internal performance issues

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/dev.to#6674]
Some pages on `/internal` have performance issues which we haven't addressed because they just don't get hit very often, but I think we'd probably use them more if they were addressed.

Some pages are just not built for the amount of prod data they have.

I suspect it's likely n+1 issues but haven't fully examined. Since some types of data don't always show we won't have the same n+1 on every version.

`https://dev.to/internal/users/1` is an example. That's my user profile internally and due to activity or whatever it just can't load.

`https://dev.to/internal/mods?state=potential` is another page which no longer works. I believe this is because of a semi-recent PR that made it not show existing mods, but I actually think the original way it was built was because the other query was more efficient.

`https://dev.to/internal/reports` is somewhat slow, not so slow that it doesn't load, but I think if we sped it up we'd see much better use. I set out to deal with this a little while back but never fully closed the loop. We could address it by having different tabs so we don't load everything on the one page load, or we could load segments asynchronously, either on the frontend or via threads on the backend?

Some of these issues can likely be fixed within the path itself, others may benefit from some more structural adjustments, such as perhaps a `cached_roles` column or something to alleviate the weight of checking for role relationships. This could become helpful across a bunch of parts of the site similar to how we use `cached_tag_list` on articles.

Anyway, this is just a bunch of examples, folks with the right admin access can see for themselves. We just haven't prioritized dealing with these issues but a sweep of fixes would go a long way.

**Comment by guivinicius** [comment]
Hey @benhalpern,

I just spent some time looking at some of those pages, and here are my suggestions:

`https://dev.to/internal/users/{id}`

The **Activity** section is counting at least 4 different relationships, which we could avoid with some counter caches on user model for example.

The **Credits** section is listing and building a form for every organization the user belongs to. Maybe those forms could live on another page like `/users/1/organizations`? or change the form to a select element for organizations.

The **Notes** section also loads all notes, maybe we could just show the last 20 notes.

The **User Organizations** section also loads and builds a form for every user organization., we could also change into another nested user page, or create a new single form to update/remove user permissions from organizations.

WDYT?

I can take a look into the other pages as well, but I prefer to start discussing the user page first.
