### ISSUE TITLE
Show accurate count when the article has less than 100 views

### ISSUE THREAD

**Issue by krishnadevz** [thepracticaldev/dev.to#6679]
**Dev.to should have stats(how many views/visitors) option for articles. 
means when a user publish any article after that he can able to see how many views he/she got**

**This Same thing Medium is having in their stories/stats section**

>  After publishing story user can able to see how many views he got and lifetime views to all stories and profile visits(like stackoverflow) and github also having same thing in their traffic section how many clones we have that can we see.because of this feature lots people can discover their interests in dev.to and users can spend more time/active users can increased that's all😊🐱‍👤

**Comment by citizen428** [comment]
Thanks for the issue @krishnadevz! Are you aware that view, reaction and comment counts are already available on your [dasahboard](https://dev.to/dashboard))? Here's an example:

<img width="843" alt="Screen Shot 2020-03-18 at 11 36 11" src="https://user-images.githubusercontent.com/47985/76925811-43ba5e00-690d-11ea-8cc3-2efc6d1189ac.png">

**Comment by krishnadevz** [comment]
@citizen428 thanks for the reply yes that thing is available but only showing under 500views but dev.to developers team can show exact views that can be a good feature for knowing exact view count /how many people reach and that's it.🐱‍👤😊

**Comment by citizen428** [comment]
I'm not sure I understand @krishnadevz, what do you mean by "under 500 views"? There are exact view counts on the dashboard, like 641, 372, and 993 here:

<img width="843" alt="Screen Shot 2020-03-18 at 11 36 11" src="https://user-images.githubusercontent.com/47985/76926730-a9a7e500-690f-11ea-8a2f-342d34d44582.png">

**Comment by krishnadevz** [comment]
![Screenshot (73)](https://user-images.githubusercontent.com/42638797/76929601-a0684980-690a-11ea-9d3e-24120d92608a.png)
**i hope you got my point now**🔼✔

**Comment by rhymes** [comment]
Hi @krishnadevz, I updated the title to make it clearer, thanks a lot for this feature request!

**Comment by krishnadevz** [comment]
@rhymes welcome stay safe&clean looking forward for more feature requests/PR's/Contributions ✔🐱‍💻

**Comment by DouglasLutz** [comment]
Can I do this?

**Comment by citizen428** [comment]
@DouglasLutz For feature requests, please wait until we add a `ready for dev` label before starting to work on it. I'll see if we can fast-track the decision on this one though 😃 

Once we added the label, you can claim the issue by assigning yourself. If you need any help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by benhalpern** [comment]
The reason we didn't show under 100 is because our pageviews are not accurate down to the one, so you could have 15 views and show zero based on how we tally.

However, I could see lowering the number for the minumum, maybe 25?

**Comment by benhalpern** [comment]
I'd sign off on moving this to 25 and will mark ready for dev on that.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/6728
