### ISSUE TITLE
Emails double-up when you change your email adress

### ISSUE THREAD

**Issue by ItsPugle** [thepracticaldev/dev.to#67]
When you sign up with Twitter and set your email, but change it before you verify/confirm it, you are sent a news/update email to each address, not just your current.

I had this issue for a while, then something happened (I honestly don't know what), and the old emails for the old email stopped coming in. Might have just been an update to the database or something, but they stopped regardless.

Sorry if this is really poorly written up; I'm not the best at these.

**Comment by jessleenyc** [comment]
Don't investigate for over an hour. Create issues when you figure out whats going on.

**Comment by Zhao-Andy** [comment]
@ItsPugle sent you an email! We'll continue there.

**Comment by Zhao-Andy** [comment]
Fixed 👍
