### ISSUE TITLE
Add welcome thread welcome notification

### ISSUE THREAD

**Issue by vaidehijoshi** [thepracticaldev/dev.to#6700]
We want to add a welcome notification prompting users to comment on a welcome thread. This should only be sent if a user hasn't already received this notification, and only should be sent 3 hours after the user is created (we don't want to bombard the user with too many notifications!).

The copy should read: "Sloan here again! 👋 DEV is a friendly community! Why not introduce yourself by leaving a comment in the Welcome Thread?"

**Comment by Ridhwana** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.
