### ISSUE TITLE
Allow welcome threads to be scoped

### ISSUE THREAD

**Issue by vaidehijoshi** [thepracticaldev/dev.to#6702]
Currently, we query for welcome threads by reusing the same logic when necessary:
```
def latest_published_thread(tag_name)
  Article.published.
          order("published_at ASC").
          cached_tagged_with(tag_name).last
end
```

We should pull this out into a scope so that anyone can find the most recent welcome thread like so: `Article.latest_welcome_thread`.

**Comment by Ridhwana** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.

**Comment by maestromac** [comment]
Is this still necessary after my suggestion here? https://github.com/thepracticaldev/dev.to/pull/6221#discussion_r394666967

**Comment by vaidehijoshi** [comment]
@maestromac You're right, we don't need to do as much heavy-lifting here since we have the logic already.

I've updated the issue description with this; I think we should just pull this into a scope on the `Article` class so that we don't need to have the same method in various different controllers. It might be a little early to do that (given the rule of threes!), but in this case, I don't think it hurts and will follow Rails' conventions
