### ISSUE TITLE
Add an authentication welcome notification

### ISSUE THREAD

**Issue by vaidehijoshi** [thepracticaldev/dev.to#6703]
We want to add a welcome notification prompting users to to authenticate with the service that they have _not_ yet authenticated with. This is to prevent authentication bugs where duplicate accounts can sometimes be created.

Based on how the user authenticated when they initially signed up, the copy will be slightly different.
- If the user authenticated with GitHub on signup, the copy should read: "You're on a roll! 🎉 Let's connect your Twitter account to complete your identity so that we know you're not a robot. 🤖"
- If the user authenticated with Twitter on signup, the copy should read: "You're on a roll! 🎉 Let's connect your GitHub account to complete your identity so that we know you're not a robot. 🤖"

This should only be sent if a user hasn't already authenticated with _both_ services, and only should be sent 1 day after the user is created (we don't want to bombard the user with too many notifications!).

**Please be sure to add the appropriate `Broadcast` to production via `/internal/broadcasts` before closing this issue!**

**Comment by Ridhwana** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.
