### ISSUE TITLE
Add feed customization welcome notification

### ISSUE THREAD

**Issue by vaidehijoshi** [thepracticaldev/dev.to#6706]
We want to prompt new users to follow some tags once they have signed up in order to help customize their DEV feed.

Users should only receive this notification if they haven't already followed a few tags or community members (maybe less than 2?). This notification should be sent out 3 days after signing up.

Suggested copy for this notification: "Hi, it's me again! 👋Now that you're a part of the DEV community, let's focus on personalizing your content. You can start by following some [tags](https://dev.to/tags) to help customize your feed!  🎉"

**Please be sure to add the appropriate `Broadcast` to production via `/internal/broadcasts` before closing this issue!**

**Comment by vaidehijoshi** [comment]
@maestromac I'm thinking a bit more about where we should send folks to when we tell them to "follow some community members". Linking to `/tags` seems like the obvious, straightforward choice here, but as far as community members, I haven't found a great place to send people to via this notification. Curious to hear your thoughts here!

**Comment by maestromac** [comment]
@vaidehijoshi my immediate thought is also the `/tags` page. We could show them our [top 7 posts](https://dev.to/devteam/the-7-most-popular-dev-posts-from-the-past-week-2jdh) to recommend authors but feels a bit in-direct. Maybe what we're really missing is a `Discover an author` page.

I also wonder if this is necessary though, because even if a user blaze through our onboarding flow the `Ok, here are some people we picked for you` page pre-select all the recommended author.

**Comment by vaidehijoshi** [comment]
@maestromac Based on the new onboarding designs, I'd say that we can't rely on the onboarding flow to pre-select all recommended authors; instead, we're pivoting to defaulting to no users being selected, and allowing them to select one, many, or all users with the [new designs](https://github.com/thepracticaldev/dev.to/issues/6549).

I don't love using the top 7 posts for this, and this make me wonder if we should have something like a `/top-people` page, similar to `/tags`. Curious to hear whether @lisasy knows if this is on the roadmap at all. I'd say that we either add a specific page for this (but that seems _very_ out of scope here), or skip the "follow some community members" copy here, and maybe add it down the road when we iterate on welcome notifications in a future cycle.

**Comment by Ridhwana** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.

**Comment by maestromac** [comment]
@vaidehijoshi Ah I see, I think we'll just have to stick with using `/tags` for the time being then.

**Comment by vaidehijoshi** [comment]
@maestromac Sounds good, and agreed :)

I've added [this card](https://github.com/thepracticaldev/dev.to/projects/7#card-34850618) to our stretch goals, so that we have the option of revisiting it in the future.
