### ISSUE TITLE
Add experience customization welcome notification

### ISSUE THREAD

**Issue by vaidehijoshi** [thepracticaldev/dev.to#6707]
Since DEV's UX experience is fairly customizable, we should point new users to this feature, especially in light of the fact that some users may want to make use of accessibility features.

We should send this notification out 5 days after a user has signed up.

Suggested copy: "Sloan here! 👋 Did you know that that you can customize your DEV experience? Try changing your font and theme to find the best style for you!"

**Please be sure to add the appropriate `Broadcast` to production via `/internal/broadcasts` before closing this issue!**

**Comment by Ridhwana** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.
