### ISSUE TITLE
Add a discuss/ask welcome notification

### ISSUE THREAD

**Issue by vaidehijoshi** [thepracticaldev/dev.to#6708]
We want to ensure that our users are engaging with the platform soon after they've signed up. To that end, we want to prompt them to start a discussion (if they haven't), or ask a question (if they haven't).

We should send this notification out 6 days after sign up. This should be the last notification that users receive within the welcome notification flow.

The copy for this notification should take into account whether or not a user has already started a discussion or asked a question. We might want to have three different copy formats for this:
- If a user has asked a question but not started a discussion: "Sloan here! 👋 I noticed that you haven't [started a discussion](https://dev.to/t/discuss) yet. Starting a discussion is easy to do; just click on "Write a Post" in the sidebar of the tag page to get started!"
- If a user has started a discussion but not asked a question: "Sloan here! 👋 I noticed that you haven't [asked a question](https://dev.to/t/explainlikeimfive) yet. Asking a question is easy to do; just click on "Write a Post" in the sidebar of the tag page to get started!"
- If a user has neither asked a question nor started a discussion: "Sloan here! 👋 I noticed that you haven't [asked a question](https://dev.to/t/explainlikeimfive) or [started a discussion](https://dev.to/t/discuss) yet. It's easy to do both of these; just click on "Write a Post" in the sidebar of the tag page to get started!"

**Please be sure to add the appropriate `Broadcast`s to production via `/internal/broadcasts` before closing this issue!**

**Comment by Ridhwana** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.
