### ISSUE TITLE
Clean up duplicated broadcast code

### ISSUE THREAD

**Issue by vaidehijoshi** [thepracticaldev/dev.to#6709]
Once welcome notifications have been shipped, we should refactor our broadcast code such that we only have a concept of generic Broadcasts or Welcome Broadcasts. This will involve removing any instances of `Onboarding` Broadcasts.

We'll want to grep the codebase can clean up any pending `# TODO: [@thepracticaldev/delightful]` tasks as part of this, too.

**Comment by Ridhwana** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.
