### ISSUE TITLE
Add a reoccurring task to send welcome notifications

### ISSUE THREAD

**Issue by vaidehijoshi** [thepracticaldev/dev.to#6710]
We'll need to create a rake task that handles the work of running the `Broadcasts::WelcomeNotification::Generator`, which will send out welcome notifications.

We should run this task on only the recent signups (a subset of users who have signed up from the last 7 days).

**Comment by Ridhwana** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.

**Comment by vaidehijoshi** [comment]
Middle-of-the-night thought: in order to set this feature "live" safely, perhaps we can just create a timestamp for the time that we disable the welcome drip emails. Any user created after that timestamp should receive the welcome notifications, and we can have the rake task check for that.

```
NOTIFICATIONS_SET_LIVE_DATE = 1585576450

# Rake task can batch and fetch users with a `created_at` after the NOTIFICATIONS_SET_LIVE_DATE.
```
