### ISSUE TITLE
Remove variants from onboarding

### ISSUE THREAD

**Issue by vaidehijoshi** [thepracticaldev/dev.to#6714]
We currently have a concept of "variants" in the frontend and backend portions of the onboarding feature. However, we don't really use these at the moment, and we plan to have only one main form of onboarding with these revamped designs (for now, at least!). We also have a newer way of running variants against features: `field_test`, which is what we use on the feed currently.

Given all of this, we can remove our custom implementation of variants, `onboarding_variant_version`, from the backend and any notion of `variant` from the frontend entirely. Later on, if we decide to add variants to onboarding, we can use `field_test` to do so.

**Comment by Ridhwana** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.
