### ISSUE TITLE
CSS Issue on Mod dashboard

### ISSUE THREAD

**Issue by reyesvicente** [thepracticaldev/dev.to#6725]
**Describe the bug**

CSS issue on the experience level on a post

**To Reproduce**

1. Go to '...' -> https://dev.to/{user}/{title}
2. Click on '....' -> moderate post
3. Scroll down to '....' -> Experience Level of Post

**Expected behavior**
Numbers shouldnt cover the string "Experience Level of Post"

**Screenshots**
Firefox Dev Edition
![firefox](https://user-images.githubusercontent.com/45283313/77072070-13b3ad80-6a28-11ea-9c13-cb63bdaf9636.png)
Brave
![brave](https://user-images.githubusercontent.com/45283313/77072079-1910f800-6a28-11ea-8134-667483ea9d26.png)

**Desktop (please complete the following information):**

- OS: MacOS Catalina 10.15.3
- Browser: Brave / Firefox Developer Edition
- Version: Version 1.5.112 Chromium: 80.0.3987.132 (Official Build) (64-bit) / 75.0b5 (64-bit)

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by nickytonline** [comment]
This is most likely related to some global CSS changes that were merged into the code base within the past couple of weeks. Probably another `line-height` issue.

**Comment by benhalpern** [comment]
#6713 has been shipped. Closing this.
