### ISSUE TITLE
Listings tags are not being rendered

### ISSUE THREAD

**Issue by ludwiczakpawel** [thepracticaldev/dev.to#6726]
**Describe the bug**

When creating a listing, user can specify tags. But they are not being rendered anywhere. There's a code that supposed to print them: https://github.com/thepracticaldev/dev.to/blob/master/app/views/classified_listings/_liquid.html.erb#L26
but it always returns empty container.
(example above is actually listing injected by liquid in article, but I can't see listing's tags ANYWHERE, not only in liquids).

**To Reproduce**

1. Go to Listings `/listings`
2. Click "Create a listing" `/listings/new`
3. Create a listing, make sure you add some tags.
4. Go to that listing on `/listings` page or anywhere else.
5. BOOM! NO TAGS!! 🤯

**Expected behavior**

Tags being rendered.

**Screenshots**

![image](https://user-images.githubusercontent.com/108287/77078619-1ea21a00-69f7-11ea-8006-fd5c89de61c9.png)

**Desktop (please complete the following information):**

- OS: macOS 10.15.3
- Browser: Chrome 80.0.3987.132

**Comment by citizen428** [comment]
I played around with this a bit, I'm not sure if this is actually a good first issue @rhymes, as there may be something more complicated going on: when you inspect the classified listings page, you'll see that listings have divs with class `single-classified-listing-tags`. I then used Blazer to check them, and while those listings do have taggings, they don't render their tags. I think I have an idea what's going on, so I'll probably take this over myself.

**Comment by citizen428** [comment]
As you can see here, the tags actually briefly appear, then flash out of existence again:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/47985/77137020-adb63d00-6a9e-11ea-9397-26a8362f84f9.gif)

The video was recorded on my local environment, but I see the same in production.

**Comment by rhymes** [comment]
oooh, this is scary, thanks for the PR! Going to remove the label :D
