### ISSUE TITLE
Not able to open https://dev.to/settings

### ISSUE THREAD

**Issue by bhageena** [thepracticaldev/dev.to#6730]
**Not able to open https://dev.to/settings**

**Try to open settings by any means** Every single time I am greeted with same error.

![Screenshot from 2020-03-19 23-16-50](https://user-images.githubusercontent.com/14236753/77098048-c17a8880-6a37-11ea-978a-290b643c0e86.png)

**Desktop:**

- OS: Ubuntu
- Browser: Chrome, Brave
- Version: Version 79.0.3945.130 (Official Build) (64-bit), Version 1.5.112 Chromium: 80.0.3987.132

**Comment by maestromac** [comment]
Hello @bhageena , this looks an issue specific to your account. Please email yo@dev.to for more help.

**Comment by maestromac** [comment]
I've made a mistake. This is not an account related error. I'm looking into this now.

**Comment by maestromac** [comment]
@bhageena can you give it a try again to verify that this is resolved?

**Comment by securibee** [comment]
I wrote an email as I was experiencing a similar problem and was asked to respond to this issue.

Whatever was done after sending the email resolved the issue for me.

**Comment by f2r** [comment]
I had the same problem today, but it's solved now.

**Comment by bhageena** [comment]
Thanks, it's working for me as well.
