### ISSUE TITLE
User's draft post reverting to older version when trying to edit

### ISSUE THREAD

**Issue by michael-tharrington** [thepracticaldev/dev.to#6733]
**Describe the bug**

A DEV user ([Rich](https://dev.to/ellisium)) wrote in to let us know that their unpublished [draft post](https://dev.to/ellisium/oh-look-it-s-the-orm-good-bad-thread-again-14jn-temp-slug-6674265?preview=3bae497ea15134d922ea1473db460bd7f5bec9085c2a3e3e818bb84a1c0ee6319ad6ef0daab4d1959dda50ece15b93e53252f4bda3b100f049342b4c) keeps reverting to an older version without any of their latest revisions.

The draft view is correct, but when they click to edit, they don't see their most recent edits.

Editing on another device (their iPad) works as expected (edits are consistent for their draft and the editing page).

**Expected behavior**

The content on the draft page and in the edit view should be the same regardless of what device they're using.

**Additional context**

This DEV user said it was fine if I included their information in this issue.

While they mentioned that editing on another device works as expected, they said they didn't think that they switched devices during the editing process.

**Comment by nickytonline** [comment]
@maestromac, is this related to local storage for keeping edits? It would make sense on one device it's using the local storage and the other where they haven't as they're editing the draft for the first time on the other device.

**Comment by rellis-of-rhindleton** [comment]
I’m pretty sure it is. I checked local storage and the edit response in the console. The response contained the right content, but local storage did not. 

Deleting the item from local storage (if I got the right one) didn’t help.

**Comment by maestromac** [comment]
Thank you all for reporting this. As this was already reported on https://github.com/thepracticaldev/dev.to/issues/6692, I'm going to close this in the effort to keep the discussion in the same thread.
