### ISSUE TITLE
error is coming when i writing a blog.

### ISSUE THREAD

**Issue by Applikeuber** [thepracticaldev/dev.to#6742]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by Ridhwana** [comment]
Hi @Applikeuber can you please fill out the details for the form above so that we can attempt to replicate the bug.

**Comment by rhymes** [comment]
Closing this for the lack of details
