### ISSUE TITLE
Not letting me post or comment

### ISSUE THREAD

**Issue by rohanThegreaTT** [thepracticaldev/dev.to#6749]
I have

**Describe the bug**
i cannot post, comment or PM, when i try to make a post it gives me an error: Ooooops...
You have encountered an error.
Our team has been notified. Please feel welcome to also submit a public bug report.

We apologize for any inconvenience. When i comment nothing happens and the same when i try to PM people

**To Reproduce**
I dont know as i am asking you how to prevent it

**Expected behavior**
To let me post, comment and PM

**Screenshots**

**Desktop (please complete the following information):**

- OS: mac OS Catalina version 10.15.3
- Browser: google chrome
- Version: 80.0.3987.122

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hello @rohanThegreaTT, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.

**Comment by rohanThegreaTT** [comment]
ok

**Comment by zeeshanhshaheen** [comment]
Getting the same issue, informed on yo@dev.to buy didn't get any response. Can you help me in that m

Profile: https://dev.to/zeeshanhshaheen

Thanks
