### ISSUE TITLE
Series: Sort order of a mix of native/imported posts can be unexpected

### ISSUE THREAD

**Issue by jhermann** [thepracticaldev/dev.to#6758]
**Describe the bug**

Surprising order (on a timeline) in a series, when a post is published at a different date originally (that is the assumption of the cause).

**To Reproduce**

See metadata of [Blogging About My Repositories to Guide Interest](https://dev.to/jhermann/blogging-about-my-repositories-to-guide-interest-gm7) and other post in the series.

**Expected behavior**

1. Allow **explicit ordering** (series: #«PRIO» «TITLE», with prio defaulting to the UNIX timestamp used currently).
1. Or sort by **order of publishing on dev.to** instead of any sources.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Thank you @jhermann, as I mentioned on the website, I'm going to take a look at this as this is clearly a bug :)

**Comment by rhymes** [comment]
@jhermann thanks again for this issue ticket! 

I think we fixed it:

![Screenshot_2020-03-23 Blogging About My Repositories to Guide Interest](https://user-images.githubusercontent.com/146201/77333815-44dff680-6d24-11ea-9d13-9db05ec94070.png)

If it doesn't appear for you try force refreshing as it was recently deployed and it might be still cached somewhere.

Also let us know if you encounter other issues with collections or anything else.
