### ISSUE TITLE
Receiving nil object in notify_mailer

### ISSUE THREAD

**Issue by luchiago** [thepracticaldev/dev.to#6761]
**Describe the bug**

I was using the [Preview Emails](https://docs.dev.to/backend/previewing-emails/) in localhost to see some changes in mail sending when I bumped in a bug in one method of this endpoint

**To Reproduce**

1. Go to [http://localhost:3000/rails/mailers/notify_mailer/new_message_email](http://localhost:3000/rails/mailers/notify_mailer/new_message_email)
2. See the bug

**Expected behavior**

See the new message email preview

**Screenshots**

![image](https://user-images.githubusercontent.com/30028621/77236444-55199980-6b9d-11ea-96bd-69fc8990bfe7.png)

**Desktop (please complete the following information):**

- OS: Manjaro 19.0.2 Kyria
- Browser: Chromium
- Version: 80.0.3987.132

**Additional context**

**Comment by citizen428** [comment]
Thanks for the report @luchiago! Do you have any message locally? If you look at the logs, the first thing this tries to do is load a message to use in the preview:

```
Message Load (7.9ms)  SELECT  "messages".* FROM "messages" ORDER BY "messages"."id" DESC LIMIT $1  [["LIMIT", 1]]
```

If there are none `@messages` will be `nil` and you'll see this error. By using our seeds you'll have messages and this should work. 

Can you please confirm and close this issue if what I wrote above works? Thank you!

**Comment by luchiago** [comment]
@citizen428 It works!. Thank you
