### ISSUE TITLE
some bugs showing

### ISSUE THREAD

**Issue by freyariki** [thepracticaldev/dev.to#6776]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hi @freyariki, could you fill in the bug report? Without information is hard to be of help. What errors are you experiencing?

**Comment by rhymes** [comment]
Closing this for the lack of details
