### ISSUE TITLE
i can't write a new post. Please help

### ISSUE THREAD

**Issue by techmahedy** [thepracticaldev/dev.to#6779]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by Ridhwana** [comment]
Hi @techmahedy, could you please fill in the bug report? Without information is hard to be of help. What errors are you experiencing?

**Comment by rhymes** [comment]
Hello @techmahedy, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
