### ISSUE TITLE
Feature request: Show date & time of comments

### ISSUE THREAD

**Issue by vgrovestine** [thepracticaldev/dev.to#68]
Please consider adding the posting date and time of individual article comments and/or add an option to toggle between threaded and chronological views.

Especially while keeping an eye on the responses to a discussion, one can see the comment count increase; however, there's no way to tell which comments are new since one last visited the page. Simply adding the comment post date and time would solve this nuisance issue.

**Comment by Zhao-Andy** [comment]
Thanks for the feedback. We'll put this in our backlog.

**Comment by benhalpern** [comment]
Finally added. Will be live soon.
