### ISSUE TITLE
Docker: webpacker can't find homePage.js

### ISSUE THREAD

**Issue by bravemaster619** [thepracticaldev/dev.to#6817]
Finished docker install in Windows 10. Have run dev sever with the following command:

```console
docker-composer up
```

However, I cannot access the home page. It shows the following error:
```
Webpacker::Manifest::MissingEntryError at /
Webpacker can't find homePage.js in /usr/src/app/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}
```
![image](https://user-images.githubusercontent.com/50212003/77456292-02a6da00-6e36-11ea-8925-62f5567eafe4.png)

I've looked into the console and found the following message:
```
devto_webpacker_1 exited with code 127
```
Is it related to webpacker update? [https://github.com/thepracticaldev/dev.to/pull/6664](https://github.com/thepracticaldev/dev.to/pull/6664)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @bravemaster619, thanks a lot for the issue ticket! I updated the title to make it easier to identify at first glance.

**Comment by bravemaster619** [comment]
Thanks @rhymes. Of course, I've seen issue templates but I wonder my problem was really a bug. I'm kinda new to dev.to project and I'm not sure this is a bug. Maybe I've done wrong in the installation process. For example, I changed yarn version to `>=1.21.x` in `package.json`. Because you guys didn't merge the pull request https://github.com/thepracticaldev/dev.to/pull/6803. (Now you've merged.) 🍭🍭🍭

**Comment by citizen428** [comment]
@bravemaster619 Now that we merged #6803, is this working for you?

**Comment by bravemaster619** [comment]
> @bravemaster619 Now that we merged #6803, is this working for you?

I used #6803 code before merging and it didn't work.

**Comment by bravemaster619** [comment]
I'm updating the error messages:

```console
docker-compose up
```

```console
Starting elasticsearch     ... done
Starting devto_db_1        ... done
Starting devto_webpacker_1 ... done
Starting devto_redis_1     ... done
Starting devto_sidekiq_1   ... done
Starting devto_web_1       ... done
Attaching to devto_db_1, devto_webpacker_1, devto_redis_1, elasticsearch, devto_sidekiq_1, devto_web_1
db_1             | LOG:  database system was shut down at 2020-03-24 17:19:31 UTC
db_1             | LOG:  MultiXact member wraparound protections are now enabled
db_1             | LOG:  database system is ready to accept connections
db_1             | LOG:  autovacuum launcher started
redis_1          | 1:C 25 Mar 2020 11:43:14.513 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1          | 1:C 25 Mar 2020 11:43:14.513 # Redis version=5.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1          | 1:C 25 Mar 2020 11:43:14.513 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1          | 1:M 25 Mar 2020 11:43:14.517 * Running mode=standalone, port=6379.
redis_1          | 1:M 25 Mar 2020 11:43:14.517 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1          | 1:M 25 Mar 2020 11:43:14.517 # Server initialized
redis_1          | 1:M 25 Mar 2020 11:43:14.517 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is 
disabled.
redis_1          | 1:M 25 Mar 2020 11:43:14.521 * DB loaded from disk: 0.004 seconds
redis_1          | 1:M 25 Mar 2020 11:43:14.521 * Ready to accept connections
': No such file or directoryt execute 'ruby
devto_webpacker_1 exited with code 127
```

**Comment by briwa** [comment]
@bravemaster619 This might be a dumb question from me, but have you tried running `yarn install` before starting up the containers? I had this exact same error but as it turns out I forgot to do that, and it was fine afterwards.

**Comment by bravemaster619** [comment]
@briwa Hi, thank you for your tip. I believe `yarn install` is included in Dockerfile:
```
RUN yarn install && yarn check --integrity
```
Can you explain a little bit more how you did?

Where should I run that command?

**Comment by briwa** [comment]
@bravemaster619 in my case, I'm using the `docker-compose` approach and there was some unrelated error happened on my end when building the container which might or might not have something to do with the error we're both facing. So what I did was to re-run the `yarn install` with `docker-compose run web yarn install` (or just `yarn`) and it seems to fix the issue.

**Comment by citizen428** [comment]
Note that it may be necessary to run `yarn install` when JS dependencies have changed since the container was built, i.e. by checking out a different branch, since we are mounting the current volume. The following command does the trick:

```
$ docker-compose run web yarn install 
```

As per the Docker [documentation](https://docs.docker.com/compose/rails/#rebuild-the-application):

> If you make changes to the Gemfile or the Compose file to try out some different configurations, you need to rebuild. Some changes require only docker-compose up --build, but a full rebuild requires a re-run of docker-compose run web bundle install to sync changes in the Gemfile.lock to the host, followed by docker-compose up --build

I'll try to make the process a bit smoother.

**Comment by JuanVqz** [comment]
Hi! what was the solution of this issue? I've been having this problem for 3 days
![Screen Shot 2020-04-17 at 18 09 10](https://user-images.githubusercontent.com/7331511/79670280-626b7900-8187-11ea-9c2a-3d787a9ebd29.png)
![Screen Shot 2020-04-17 at 18 16 45](https://user-images.githubusercontent.com/7331511/79670282-65666980-8187-11ea-82ae-4dda8b899747.png)

**Comment by lightalloy** [comment]
@JuanitoFatas have you tried @citizen428 's suggestion ?
```
$ docker-compose run web yarn install 
```
