### ISSUE TITLE
Markdown Headers Should Have IDs for Linking

### ISSUE THREAD

**Issue by bennypowers** [thepracticaldev/dev.to#682]
## Feature Request or Task

When users create headings in markdown, the headings should have ids added to enable linking throughout the document

```markdown

[tl;dr](#tl-dr)
[The History](#the-history)
[Transpiling](#transpiling)
[The Problem](#the-problem)
[`esm`: A Better Solution](#esm-a-better-solution)
[Summary](#summary)

## tl;dr:
...

## The History
...

## Transpiling
...

## The Problem
...

### The Cost of Transpiling
...

### Principles and Cognitive Load
...

## `esm`: A Simple Solution
...

## Summary
...


```

### User Story / Description

Users with medium-to-long-form content might want to add a table of contents, or a link to a summary or tl;dr.

### Definition of Done
When the links in the above snippet work as expected: clicking on one scrolls to the relevant header.

**Comment by jessleenyc** [comment]
@Zhao-Andy I believe you were in the process of working on this?

**Comment by glebec** [comment]
Duplicate of #183

**Comment by bennypowers** [comment]
Closing as dupe. Thanks!
