### ISSUE TITLE
In "Suggested Topics", lets users select tags using their keyboard

### ISSUE THREAD

**Issue by lisasy** [thepracticaldev/dev.to#6843]
This is an a11y-based bug based on P1's onboarding flow.

**Comment by vaidehijoshi** [comment]
Here's what currently renders when trying to tab through the selected tags on the keyboard:

<img width="821" alt="Screen Shot 2020-04-23 at 3 53 52 PM" src="https://user-images.githubusercontent.com/6921610/80157277-a93be300-857a-11ea-9605-1530c412083e.png">
