### ISSUE TITLE
Update to current yarn version to 1.22.4

### ISSUE THREAD

**Issue by abenettt** [thepracticaldev/dev.to#6856]
**Is your feature request related to a problem? Please describe.**
Not a problem perse but as we set the yarn version explicitly via `yarn policies set-version x.x.x` we also have to update the version manually. 

**Describe the solution you'd like**
Update yarn version via command

**Describe alternatives you've considered**

**Additional context**

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Great catch!
