### ISSUE TITLE
Replace Flipflop with Sail

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/dev.to#686]
It may be silly to replace a tried-and-tested gem with a newer one, but conceptually I think this approach will work. Read on. Please mention if this would be a terrible idea.

## Feature Request or Task
Sail is a new gem from a dev.to community member
https://github.com/vinistock/sail

It adds app-wide settings/config in a way I like more than Flipflop. I feel like feature flags should live alongside other settings we might want to use. A unified site-wide admin config. This could also be a destination for a lot of features folks could use for [self-hosted instances of the app](https://docs.dev.to/dev-instance/).
### User Story / Description
As an admin, I'd like to adjust a site-wide configuration.
### Definition of Done
All current flipflop features are replaced by Sail, then we can add more as we go

**Comment by vinistock** [comment]
Hey, folks. Not sure if you had the time to play around a little bit. Please, let me know if you have feedback on the gem and if you'd like to have anything added to it.

Also, please do tell if you don't wish to add it at this time and we can drop the PR.

**Comment by jessleenyc** [comment]
Hey @vinistock, sorry for the delay. We'll try and push this through by the end of the week

**Comment by vinistock** [comment]
@jessleenyc Awesome. Let me know if I can somehow assist.
