### ISSUE TITLE
Fix horizontal black bar showing up while scrolling on smaller viewports.

### ISSUE THREAD

**Issue by lisasy** [thepracticaldev/dev.to#6886]
Related comment: https://github.com/thepracticaldev/dev.to/pull/6842#issuecomment-604457093

On the "suggested people" page, a weird horizontal black bar shows up when the viewport is smaller.

![Screenshot 2020-03-26 07 41 47](https://user-images.githubusercontent.com/816402/77660641-d2933000-6f36-11ea-974c-17f8ed415de4.png)

**Comment by vaidehijoshi** [comment]
Hm, I'm having trouble reproducing this on production. It looks like the original issue was caught by @benhalpern, so I'm wondering if he remembers what device/size he was on to cause this? That way I can try to investigate it 😄 

I'm pretty sure this is related to a `border-bottom` style, but I'm not seeing it show up the way that it does in the screenshot 🤷

**Comment by lisasy** [comment]
![Screenshot 2020-04-27 10 24 31](https://user-images.githubusercontent.com/816402/80401531-5790a280-8871-11ea-9372-3c53a57f8b08.png)

This issue does not seem to exist, so we can close this issue.
