### ISSUE TITLE
Keeping up with new comments in discussions on posts is difficult

### ISSUE THREAD

**Issue by hoelzro** [thepracticaldev/dev.to#689]
## Feature Request or Task

When a discussion reaches a certain point (I would say around 15 comments or so?), it's really hard to know which comments are new to the discussion.  Could be related to #192.

### User Story / Description

I would like to be able to revisit a discussion I've looked at earlier and have some way of identifiying new comments.

### Definition of Done

I'm not 100% sure how this would work, and I was hoping to start discussion on whether others would find this useful and what an implementation of this would look like.  I have two ideas currently:

  * Offer visual indicators on comments that are new since last time.  One could highlight the post date in red or something (like Lobsters does - you see "17 minutes ago" or whatever it is in red), lighten the text on older comments, etc.
    * One problem with this is if you accidentally navigate away from the page, you've reset your state and now nothing looks new.
  * Offer an alternative ordering for comments (kind of like Reddit's "newest" view) - this can be tricky too, since you want to make sure a new reply to a comment a few levels down is easy to access but also comes with the appropriate context.

**Comment by glebec** [comment]
Re: the first strategy, Reddit Enhancement Suite (or is it Reddit Gold?) highlights posts which are new since your last visit by making their background color a different shade. I find that a pretty effective way at focusing my attention.
