### ISSUE TITLE
Cannot uncheck the  'Send me occasional reminders' checkbox in Notification Settings

### ISSUE THREAD

**Issue by brthanmathwoag** [thepracticaldev/dev.to#69]
It seems you can't turn off the 'Send me occasional reminders that I have unread notifications on dev.to' option in Notification Settings. After clicking submit and reloading the page the checkbox is still checked.

**Comment by jessleenyc** [comment]
Thanks for flagging!

**Comment by Zhao-Andy** [comment]
Hey there, we've fixed this. :)
