### ISSUE TITLE
Article link in notifications is black

### ISSUE THREAD

**Issue by catalinpit** [thepracticaldev/dev.to#6907]
# **Describe the bug**

When the dark theme is enabled, the article link is black. 

I suppose the link should be white for better visibility and aesthetics. 

See the picture.

# **To Reproduce**

1. Log into your account.
2. Enable the dark theme
3. Go to the notifications

# **Expected behavior**

When the dark theme is enabled, the link should be white. 

# **Screenshots**

![notification-preview](https://i.imgur.com/szeY9DW.png)

**Comment by catalinpit** [comment]
Can I also pick it, please?

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
@catalinpit yes, go ahead, and thank you!

**Comment by catalinpit** [comment]
Thank you!

What is the time required to finish this?

**Comment by rhymes** [comment]
@catalinpit you can take as much time as you'd like, if we deem an issue urgent we might nudge the contributor after a while in case they abandon a PR.

Let us know if you need help with anything!
