### ISSUE TITLE
Notification text is not visible in the Ten X Hacker theme

### ISSUE THREAD

**Issue by bernardbaker** [thepracticaldev/dev.to#6911]
**Is your feature request related to a problem? Please describe.**

I'm frustrated when I look at my notifications and the text in the box which has the post written inside it is the same colour as th background.

I'm using the green and black theme.

**Describe the solution you'd like**

I want to be able to read the name of the post that has received a heart or a unicorn.

**Describe alternatives you've considered**

I haven't considered any alternatives.

**Additional context**

![Screenshot_20200327-124002](https://user-images.githubusercontent.com/13556172/77772902-c1cee100-7040-11ea-8a9f-01aa56c78aae.png)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).
