### ISSUE TITLE
New notifications is tough to see on pink mode

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#6919]
**Describe the bug**
I'm finding the new red notification dots really difficult on the eyes in the pink theme!

![](https://p193.p3.n0.cdn.getcloudapp.com/items/wbumdOvv/Image%202020-03-27%20at%204.26.13%20PM.png?v=c58fa775d5c17d11aeef58f248f55322)

**Additional context**

Are the notification dot colors something we can adjust in the custom themes?

**Comment by catalinpit** [comment]
Did anyone pick this? 

If not, I'd like to pick it. :-)

**Comment by jessleenyc** [comment]
@catalinpit go for it!

**Comment by catalinpit** [comment]
!(notifs)[https://i.imgur.com/UpBtGUw.png] 

Seems like someone fixed it, or?

**Comment by rhymes** [comment]
Oh nice! Didn't notice. It looks like it was fixed in #6957

Closing this, thanks @catalinpit for checking!
