### ISSUE TITLE
Hide API keys by default when in Dashboard

### ISSUE THREAD

**Issue by sw-yx** [thepracticaldev/dev.to#6930]
**Is your feature request related to a problem? Please describe.**

by default, api keys are visible when you visit the dashboard. this goes against security best practice for example when you are in a livestream or screenshare or simply using the computer with someone standing behind you. 

**Describe the solution you'd like**

it should be visually hidden as a password field by default and then exposed only when needed.

**Describe alternatives you've considered**

api key chaos

**Comment by sw-yx** [comment]
if you will accept a PR from me, i would be happy to contribute.

We could edit this line with a little bit of javascript to make it password field

https://github.com/thepracticaldev/dev.to/blob/379aa4d1ece8b2e587966e3abf21175f7ac23c38/app/views/users/_account.html.erb#L27

and then switch the field type when we click "Show" or something.

alternatively , instead of switching it to an input, we can just use css colors to make it not show up until we highlight it. but it may look bad.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @sw-yx, great idea! 

What about simply using  the [details](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) HTML element, to hide the section?

**Comment by citizen428** [comment]
Thanks for the suggestion @sw-yx! We'd be happy to accept your contribution, I'll assign you the issue 😃

FWIW I agree with @rhymes, using the `details` element could work very nicely for this use case.

**Comment by sw-yx** [comment]
oh of course. :)
