### ISSUE TITLE
From long back for same issue i am unable to write any post. Same old bug.

### ISSUE THREAD

**Issue by devjamal** [thepracticaldev/dev.to#6943]
**Describe the bug*
My git repository have some random bugs like minor security and versions 
so feel nothing to do with that.

**To Reproduce**

**Expected behavior**

**Screenshots**
I already Shared a screenshot please resolve this before closing.

**Desktop (please complete the following information):**

- OS: Windows10, android
- Browser: Google Chrome, Brave, Mozilla
- Version:

**Smartphone (please complete the following information):**

- Device: Redmi Note 5 Pro
- OS: Miui 10
- Browser:  Google Chrome
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hi @Rahul626, the screenshots you shared in the past unfortunately don't contain any useful information. Could you please share your DEV username?
