### ISSUE TITLE
Can't see onboarding form "continue" button on small screens

### ISSUE THREAD

**Issue by DestyNova** [thepracticaldev/dev.to#6962]
**Describe the bug**

The onboarding forms (where you're invited to follow topics and people from lists) are laid out slightly too large for low-resolution screens, such that you can't see the "Continue" button which is at the top of the form. It's not possible to scroll up, either.

Screenshot from my 1366x768 laptop (cropped to the visible area in Firefox; the rest is taken up with title bar, address bar, bookmarks bar and system menu area):

![Screenshot from 2020-03-31 01-03-54](https://user-images.githubusercontent.com/1646628/77973664-c28b9f80-72ec-11ea-8f66-ff8ea0cfca18.png)

**To Reproduce**

1. Start registering a test account
2. Make the viewport small (maybe by resizing the browser window, or using responsive design mode to enter 1366x768 display)
3. Go through the onboarding form.

**Expected behavior**

Back / Continue buttons can be seen.

**Workaround**

Use responsive design mode to change viewport resolution, or zoom out temporarily.

**Desktop (please complete the following information):**

- OS: Ubuntu 19.10
- Browser: Firefox
- Version: 74.0

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by maestromac** [comment]
This should be resolved now. Let us know if otherwise!
