### ISSUE TITLE
Copy to clipboard button quite not see clearly in dark mode

### ISSUE THREAD

**Issue by blacksourcez** [thepracticaldev/dev.to#6967]
**Describe the bug**

It's a cosmetic issue.

**To Reproduce**

1. Go to Profile.
2. Settings
3. Set theme to dark.
4. Go to home page
5. Open an article (any article).
6. At the bottom of the screen click the button '...'. (in this case I use the PWA installed with Chrome) the desktop version might be on the left-hand side.
7. You'll see the copy icon (back icon in the dark mode which quite not quite visible)

**Expected behavior**

The copy to clipboard button should be able to easier to see in the dark mode.

**Screenshots**

![image](https://user-images.githubusercontent.com/6449655/77989308-9e5dac00-7348-11ea-86a4-765475c50dee.png)

**Desktop (please complete the following information):**

- OS: macOS Catalina (10.15.4)
- Browser: Google Chrome
- Version: Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).
