### ISSUE TITLE
Avoid clobbering user attributes with empty params during onboarding

### ISSUE THREAD

**Issue by vaidehijoshi** [thepracticaldev/dev.to#6985]
**Describe the bug**

In the `onboarding_update` endpoint, we currently override the attributes on a user with any params that are sent through via onboarding. This is usually fine if a new user wants to update their (otherwise blank) information when joining the platform. But, this also means that pre-existing users can never go to this page without accidentally overriding their own attributes, since we currently just update the attributes on the user with _whatever_ comes through in the `permitted_params`.

```
# app/controllers/users_controller.rb

def onboarding_update
    if params[:user]
      permitted_params = %i[summary location employment_title employer_name last_onboarding_page]
      current_user.assign_attributes(params[:user].permit(permitted_params))
      current_user.profile_updated_at = Time.current
    end
    
   # more stuff here...
  end
```

However, we probably don't want to `assign_attributes` to a user blindly: for example, if all the attributes are blank, we don't need to update them on the user. We should probably ignore any blank attributes and only update attributes on the user if the incoming param is empty.

**Comment by rhymes** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.
