### ISSUE TITLE
Badge Notification Error

### ISSUE THREAD

**Issue by catalinpit** [thepracticaldev/dev.to#6995]
**Describe the bug**

When you enable dark themes, the text from the last paragraph is unreadable.

It works fine on light themes, but not on dark themes.

**To Reproduce**

1. Set to a dark theme
2. Go to the notifications
3. Look at the last paragraph

**Expected behavior**

The text should be white on dark themes, and black on light themes.

**Screenshots**

![img-1](https://i.imgur.com/CbJvd9K.png)
![img-2](https://i.imgur.com/OnjERre.png)

**Additional context**

Can I pick this one, please?

**Comment by lightalloy** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled "type: bug" are always up for grabs, but for feature requests, please wait until we add a ready for dev before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our contributors' guide.

**Comment by lightalloy** [comment]
@catalinpit fell free to work on this one :+1:
