### ISSUE TITLE
Preview renderer treats newlines differently from published renderer

### ISSUE THREAD

**Issue by JoshCheek** [thepracticaldev/dev.to#7]
The preview renderer does not break newlines within paragraphs, the published renderer does.

---

# This paragraph of markdown

```markdown
[Pry](http://pryrepl.org/), [IRB](http://ruby-doc.org/stdlib-2.3.1/libdoc/irb/rdoc/IRB.html),
and [RIPL](https://rubygems.org/gems/ripl) are popular Ruby REPLs, but, just for funsies,
lets see what it takes to build our own! Code snippets are
[here](https://gist.github.com/JoshCheek/baab86f3258ff98c468f3dbc032dc9c5).
```

<br /><br />

# Renders like this in the preview tab:

![screenshot 2016-12-13 11 11 04](https://cloud.githubusercontent.com/assets/77495/21150586/231bf2a0-c125-11e6-9373-75ccb917857e.png)

<br /><br />

# But it renders like this when published / when using "published preview":

Note the line break after "IRB"

![screenshot 2016-12-13 11 10 41](https://cloud.githubusercontent.com/assets/77495/21150602/370ff48c-c125-11e6-978f-888f8fd49836.png)

**Comment by benhalpern** [comment]
Fixed, live soon.
