### ISSUE TITLE
Not able to focus user menu and other accessibility stuff

### ISSUE THREAD

**Issue by elnawe** [thepracticaldev/dev.to#70]
Please consider adding some accessibility features to the site. I don't use mouse (most of the time, anyway) and I'm not able to focus the user menu nor see the focus outline of most elements in the site.

I'm running Chrome with cVim.

I know that it's not a problem for me because I can use mouse but we should support these features that also boost accessibility.

Thank you!

**Comment by jessleenyc** [comment]
Absolutely. Thanks for flagging this -- we'll run another accessibility audit and make some enhancements.

**Comment by NikoLewis** [comment]
This is really useful feedback, thanks Elnawe. I think an accessibility audit to incorporate enhancements like this is a great idea @jessleenyc.

**Comment by benhalpern** [comment]
Finally fixed this, thanks.
