### ISSUE TITLE
Generalize pages logic

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#7021]
- remove unused pages routes
- remove outdated `Pages` actions, create dynamic versions where needed
- it may be worth to move some functionality from the controller action to be a `Page` (e.g. `/downloads`)

**Comment by lightalloy** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.

I plan to add a more clear description in the process of working on this task. I marked the issue as "DEV team" for now, but parts of it could become available for the contributors in the future.

**Comment by lightalloy** [comment]
I replaced several pages with the dynamic ones, and cleaned up the codebase where needed. There are still some pages left where we need to replace DEV-specific strings (e.g. "The Practical Dev" or "dev.to") with the configurable options:

- [ ] `/information`
- [ ] `/sponsors`
- [ ] `/code_of_conduct`
- [ ] `/editor_guide_text`
- [ ] `/publishing_from_rss_guide`
- [ ] `/contact`

Technically, these are parts of the #6858 which @Ridhwana was working on. @Ridhwana , are you still working on it? Or it could be a convenient task for our contributors.

**Comment by Ridhwana** [comment]
@lightalloy I've already cleaned up a lot of them this morning, I'll try and send out the next PR tonight and then I'll confirm which aren't done for the contributors to work on

**Comment by Ridhwana** [comment]
@lightalloy The above is complete in https://github.com/thepracticaldev/dev.to/pull/7263 (PR still in draft)

**Comment by lightalloy** [comment]
Closing as done with the attached prs. We may need further generalization for some of the pages, but let it be separate features.
