### ISSUE TITLE
Safari on iPad does not load dev.to

### ISSUE THREAD

**Issue by stltt** [thepracticaldev/dev.to#7057]
**Bug Description**
Starting from either an empty page (such as when opening a new tab) or from any previous page, inputting a dev.to url address or selecting a dev.to bookmark results in the browser indicating ~10% loaded. At that point the load stops. The browser neither displays any content from dev.to nor times out. The browser remains responsive to further input.

This problem started ca. 26-March

The problem does not manifest on Chrome or Firefox

- OS: IOS 13.4
- Browser: Safari
- Version: N/a
- non-default Safari settings: DuckDuckGo search

**To Reproduce**

1. open Safari on iPad
2. input dev.to into address bar or select a dev.to bookmark
3. tap "Return"

**Screenshots**

*Safari*
![httpsdev to](https://user-images.githubusercontent.com/509567/78309711-66ee2b80-7511-11ea-9c5f-3c7417952bb9.png)

*Firefox*
![Screenshot 2020-04-02 at 6 16 23 PM](https://user-images.githubusercontent.com/509567/78309832-bdf40080-7511-11ea-88dd-a75a05d68b04.png)

**Comment by citizen428** [comment]
Thanks for the bug report @stltt. We are already tracking Safari issues in https://github.com/thepracticaldev/dev.to/issues/6902, can you please add another comment there (someone already brought up Safari on iPad) and then close this issue here when you're done? Thank you!

**Comment by stltt** [comment]
Closing is issue with pointer to tracked issue [#6902](https://github.com/thepracticaldev/dev.to/issues/6902)
