### ISSUE TITLE
Reaction buttons don't communicate their "checked" status to screen readers.

### ISSUE THREAD

**Issue by bigblind** [thepracticaldev/dev.to#7058]
**Describe the bug**

When reading an article using IOS's VoiceOver screen reader, the heart, unicorn and reading list icons don't indicate whether they're checked or not. The same is probably true for other screen readers.

I think this could be solved with `aria-role="checkbox" aria-checked="true"` on the element. 

** steps to reproduce **

1. Open an article in Safari
2. Enable VoiceOver.
3. Move your finger to one of the icons

**Expected behavior**

It says something lik "heart, checked"

**Screenshots**

**Smartphone (please complete the following information):**

- Device: iPhone 11
- OS: IOS 13.4
- Browser: Safari
- Version: 13

**Additional context**

If I get to it, I'd be interested in contributing a fix, but feel free to do this if you have time.

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
Thank you @bigblind! I labelled this as bug since I think we should take accessibility issues seriously and unlike feature requests they don't have to go through an approval process.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/7100
