### ISSUE TITLE
Support `<abbr>` tags in markdown

### ISSUE THREAD

**Issue by bennypowers** [thepracticaldev/dev.to#706]
## Feature Request
Please support `<abbr>` tags in markdown for posts and comments.

### User Story / Description

It's nice and conscientious to use the abbr tag in posts:

```markdown
## Loading the Polyfills
For most users, the easiest thing to do is pop in a script tag sourcing the
`webcomponents-loader` script. This script will check the users browser's 
<abbr title="user agent">UA</abbr> string, and loads only the polyfill or
set of polyfills that are needed.
```

### Definition of Done
When users submit md content that contains abbr tags, the tags are rendered appropriately.

**Comment by maestromac** [comment]
Hey @bennypowers , was #818 meant to implement this feature? or was it just a step of the implementation?

**Comment by bennypowers** [comment]
Was intended to solve, but I don't think it did the job, since I have some posts and drafts that use `<abbr>` that don't show markup.

**Comment by maestromac** [comment]
No worries. MarkdownParser definitely remove the tag during one of the rendering steps. It can be pretty tricky to get right.

**Comment by bennypowers** [comment]
Did a little testing and the `sanitize_rendered_markdown`function is to blame.
