### ISSUE TITLE
You have encounter an error! .Unable to write post!

### ISSUE THREAD

**Issue by devjamal** [thepracticaldev/dev.to#7073]
Bug encounter!! while updating profile and writing post!

**Describe the bug**
I am facing this issue long back, It's occurring especially on my account as tried multiple devices and browsers but the same.
I guess my git repo has some security bugs , please help me out!
I am writing this report for 5th time never resolve this you can see my last post date for verifying the age of this problem

![image](https://user-images.githubusercontent.com/42401032/78387932-c590d380-75fd-11ea-952c-7df100cf6e9d.png)

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/42401032/78388560-d55ce780-75fe-11ea-81a3-b76d3236b0f4.png)

**Desktop (please complete the following information):**

- OS:  Windows 10
- Browser: Google chrome
- Version:

**Smartphone (please complete the following information):**

- Device: Redmi note 5 pro
- OS: MIUI, android 8
- Browser:
- Version:

**Additional context**

**Comment by michael-tharrington** [comment]
Hey!

We've messaged the email connected to your DEV account via yo@dev.to to discuss what is happening here. If you can please communicate with us via this email, that will be the preferred medium to talk about this issue going forward.

Thanks!
