### ISSUE TITLE
Sidebar profile name color does not change when on Night Theme

### ISSUE THREAD

**Issue by creativenobu** [thepracticaldev/dev.to#7074]
**Describe the bug**
The profile name does not change to a light color when on Night Theme. Seems like it uses the fallback feature of css var so it would load the default color `rgba(10,10,10,0.9)` before loading the `--theme-color` variable.

![Annotation 2020-04-03 134508](https://user-images.githubusercontent.com/3767728/78389790-5f7e5f00-75b1-11ea-8024-5b0926dccaa1.png)

**To Reproduce**

1. Login
2. Go to Settings -> UX -> Choose Night Theme
3. Submit to save changes

**Expected behavior**
Should use the theme color css variable `--theme-color`, to make it look like the following.

![Annotation 2020-04-03 135256](https://user-images.githubusercontent.com/3767728/78390424-89845100-75b2-11ea-84a4-9e26a8965f8e.png)

**Desktop (Tested on):**

- OS: Windows 10
- Browser: Chrome
- Version: 80.0.3987.162

**Smartphone (Tested on):**

- Device: OnePlus 7T
- OS: Android 10
- Browser: Chrome
- Version: 80.0.3987.149

**Comment by pedrowindisch** [comment]
The same happens with the hacker theme. I think I found a way to fix it (it's only a matter of adding a SASS variable) and I'd more than happy to work on this issue.
