### ISSUE TITLE
Show all Saved Posts in the Reading List

### ISSUE THREAD

**Issue by Stargator** [thepracticaldev/dev.to#708]
### Current Behavior
Currently, the Reading List only shows at max 45 saved posts (in order of most recently saved). Even though my reading list is currently sitting at over 600 posts.

Even if I click on a tag associated with one article, if that article is not in the group of 45, but in my Reading List, it will not display. I would have to remove as many articles as I added **after** I added that article, before it would show up in the Reading List.

### Expected Behavior
I expect the Reading List to be able to retrieve any article that I saved depending on the filtered settings.

### Additional Info (device/browser, helpful links)
MacOs 10.13.1 Laptop, Chrome 69

**Comment by lightalloy** [comment]
I'm working on this issue.
