### ISSUE TITLE
Unexpected redirect to "https://dev.to/serviceworker.js" page

### ISSUE THREAD

**Issue by c0d3b0t** [thepracticaldev/dev.to#7081]
**Describe the bug**

Unexpected redirect to "https://dev.to/serviceworker.js" URL.

**To Reproduce**

1. Go to your own comment under some post.
2. Click the "DELETE" link.
3. Click the "EDIT" link In the opened dialog where it says "You cannot undo this action, perhaps you just want to EDIT instead?".
4. Click the red "CANCEL" button in the bottom of "Editing comment" text area.

**Expected behavior**

"Editing comment" dialog closed, redirected to the post page.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux Mint 19.3 (Tricia)
- Browser: Google Chrome
- Version: 79.0.3945.130 (Official Build) (64-bit)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Thanks @c0d3b0t for raising this issue!

I traced the bug to 

https://github.com/thepracticaldev/dev.to/blob/2a80b2a7d9e456c8ca8838382163282ee1b9ae59/app/views/comments/_form.html.erb#L58

it looks like since the page itself is loaded from the server worker, the first condition matches, not 100% sure but that's probably a clue
