### ISSUE TITLE
Telegram Instant View

### ISSUE THREAD

**Issue by allytiago** [thepracticaldev/dev.to#7088]
I don't know if you already know, but I believe so. Telegram a long time ago brought a tool called Instant View that intends to show an article without consuming a lot of internet data and show only the essentials. I believe it would be nice to create a template for posts on the telegram and maybe even a channel so that you can have the option of related posts.

If it was possible for the dev.to to have the IV, the users of the telegram would read the content published here more easily.

**Comment by macarie** [comment]
I tried to create a template... it's not finished and has some bugs, e.g. `/about`, `/contact`, `/privacy`, but it's still something 😄

This should be a link with an Instant View enabled: https://t.me/iv?url=https%3a%2f%2fdev.to%2fmonicafidalgo%2fjavascript-primitive-vs-reference-types-45eb&rhash=f5594021a5b301

I think you have to message it to yourself on Telegram otherwise it won't work 😕

**Comment by allytiago** [comment]
> Eu tentei criar um modelo... não está terminado e tem alguns bugs, por exemplo, mas ainda é algo `/about``/contact``/privacy`
> 
> Este deve ser um link com uma visualização instantânea ativada: https://t.me/iv?url=https%3a%2f%2fdev.to%2fmonicafidalgo%2fjavascript-primitive-vs-reference-types-45eb&rhash=f5594021a5b301
> 
> Eu acho que você tem que mensagem para si mesmo no Telegram caso contrário, não vai funcionar

**Comment by allytiago** [comment]
> I tried to create a template... it's not finished and has some bugs, e.g. `/about`, `/contact`, `/privacy`, but it's still something 
> 
> This should be a link with an Instant View enabled: https://t.me/iv?url=https%3a%2f%2fdev.to%2fmonicafidalgo%2fjavascript-primitive-vs-reference-types-45eb&rhash=f5594021a5b301
> 
> I think you have to message it to yourself on Telegram otherwise it won't work

I also created a template for dev.to but ended up leaving it a little aside.
