### ISSUE TITLE
Your profile was successfully updated message is kinda broken

### ISSUE THREAD

**Issue by Defman21** [thepracticaldev/dev.to#71]
I wish I could give this issue a better title but I'm not sure how to describe what I see (I don't know English that good atm). Just look at the picture.
![image](https://user-images.githubusercontent.com/7100645/29097190-31da7c0c-7ca1-11e7-8919-64b9f7407238.png)

**Comment by jessleenyc** [comment]
Thanks for bringing this to our attention, we'll put it on the backlog!

**Comment by Zhao-Andy** [comment]
We made it look a bit cleaner. :)
