### ISSUE TITLE
Improve editor typography

### ISSUE THREAD

**Issue by glebec** [thepracticaldev/dev.to#711]
## Feature Request or Task

The current editor is very cramped. There is no line-height applied and the default appears to be excessively tight (OS X / Chrome); the padding is minimal, meaning the text feels like it is pushing up against the sides of the editor. The line length is also _okay_ but on the long side; 2.5 alphabets is considered generally pleasing, and currently we're over 3 alphabets long. Allowances can be made for the fact that sometimes the author may want more horizontal space for easier editing of e.g. markdown tables, but all of this adds up to a typographic experience that feels dense & tiring.

![screen shot 2018-09-21 at 14 14 45](https://user-images.githubusercontent.com/7230206/45898903-636cd680-bda9-11e8-9b43-65c4d71f1835.jpg)

Loosening up the line height & increasing the padding results in a much more relaxed, restful, balanced, and legible appearance. Here is a quick demo, though these precise numbers are not necessarily what I would propose as a final choice:

![screen shot 2018-09-21 at 14 14 09](https://user-images.githubusercontent.com/7230206/45898928-77b0d380-bda9-11e8-80f3-526189214055.jpg)

### User Story / Description

As an author, I expect:

- For the editor to be pleasing & easy to read
  - To have a reasonable amount of line-height, so ascenders and descenders are not crowded
  - To have a reasonable amount of padding, so text does not feel jammed against the editor sides
  - To have a reasonable line length, so the eye doesn't have to scan quite so far across the page

### Definition of Done

- Satisfactory values for line length & padding have been chosen by PR assignee & approved by project maintainers
- Related CSS & JS values / functions have been modified to account for the changed layout
  - Textarea height calculation still works correctly
  - Other layout rules are not affected
- Layout has been properly tested in multiple clients and user agents, including font fallbacks

**Comment by jessleenyc** [comment]
Hey @glebec, sorry for the delay. We're currently working on a new version of the editor which you can toggle in our settings/misc. Closing this for now since we're making these changes. Feel free to open a new issue about the new editor.
