### ISSUE TITLE
you encounter  a error!..please help me out!

### ISSUE THREAD

**Issue by devjamal** [thepracticaldev/dev.to#7114]
**Describe the bug**
when I try to write something for post or updating profile then i face this issue!

I guess due to having bugs like security bug on my repos .  please remove my GitHub account 
**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/42401032/78599437-c2504e80-786e-11ea-94f2-a1989505918d.png)

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**
I already mentioned this bug before!
- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by citizen428** [comment]
Hello @devjamal, thanks for notifying us of this problem, this looks like an issue specific to your account.

Please email yo@dev.to for more help.
