### ISSUE TITLE
Shorter <title>

### ISSUE THREAD

**Issue by pr0nbaer** [thepracticaldev/dev.to#715]
This may be a personal opinion, but I think the <title> should be much simpler.

**Homepage**

Before: ```DEV Community  👩‍💻👨‍💻 - Where software engineers connect, build their resumes, and grow.```
After: ```DEV Community```

For SEO purposes I would suggest adding the "Where software engineers connect, build their resumes, and grow." to the description tag.

**Article pages**

Before: ```<title of the article> - DEV Community 👩‍💻👨‍💻```
After: ```<title of the article> - DEV Community```

**Comment by nektro** [comment]
I agree with removing `- Where software engineers connect, build their resumes, and grow.` but I think getting rid of `👩‍💻👨‍💻` may be a bit much
