### ISSUE TITLE
Effective profile with a fix but

### ISSUE THREAD

**Issue by AVDHES** [thepracticaldev/dev.to#7160]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

<//"Add a fix bug report about account and other Creativity[{(fixbug)]}>>//

**Comment by Ridhwana** [comment]
Hi @AVDHES thank you for opening an issue. However, could you please fill out the template and update the heading to be more clear, and the DEV team will try and reproduce your issue.

**Comment by AVDHES** [comment]
> I have no issue with extra time,I work do in part-time for personal issues.

**Comment by rhymes** [comment]
Hello @AVDHES, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
