### ISSUE TITLE
HTML entities on feed page

### ISSUE THREAD

**Issue by mahalde** [thepracticaldev/dev.to#7175]
**Describe the bug**
On the feed page, an article title shows an HTML entity, where as when I click on the article, the title is correctly shown.

**To Reproduce**
Find a post with an HTML entity in your feed.

**Expected behavior**
The article title should show the decoded HTML entity.

**Screenshots**
![image](https://user-images.githubusercontent.com/39100405/78890202-7adfe300-7a65-11ea-9cf5-e1fd1fde5fe2.png)
On the feed

![image](https://user-images.githubusercontent.com/39100405/78890240-89c69580-7a65-11ea-85b2-71fefa63c229.png)
As a standalone article title

**Desktop:**

Brave | 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)
-- | --
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987
OS | Windows 10 OS Version 1809 (Build 17763.1039)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Thanks @mahalde! Adding the link of the article for easier access: https://dev.to/calin92540842/what-s-so-special-about-doctype-html-3cd6

Also, I just noticed it looks okay in the user's profile page too, same in the title of the comments (but not if it's in the comment itself):

![Screenshot_2020-04-09 PDS OWNER CALIN (Calin Baenen) - DEV Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/78893508-c09faa00-7a6b-11ea-9212-9ed8bbff6eab.png)


(the comment that's rendered incorrectly is https://dev.to/calin92540842/comment/ngpm)

**Comment by tannakartikey** [comment]
@rhymes can I take this one?

**Comment by rhymes** [comment]
@tannakartikey sure, thank you! You should be able to reproduce by creating locally an article with that title

**Comment by tannakartikey** [comment]
@rhymes I am not able to reproduce this issue. Nor I see the incorrect heading in the post

**Comment by Rafi993** [comment]
It is visible here https://dev.to/search?q=what%27s%20so%20special%20about scroll down to see the article in the bug description.

**Comment by Rafi993** [comment]
I was able to see this bug but after refreshing I cannot see it anymore :(

**Comment by Rafi993** [comment]
I'll try it in my local

**Comment by rhymes** [comment]
@tannakartikey ok. let's keep this open, I'm going to unassign you in case anyone else feels like trying their luck :D

**Comment by Rafi993** [comment]
I just realised the comments that I made here is not visible anymore :|

**Comment by Rafi993** [comment]
Hi there I was able to reproduce this in local I would like to help if this bug is not taken
![html_entity](https://user-images.githubusercontent.com/8092120/80588896-d08d2700-8a36-11ea-9fde-de5ae6985587.png)

**Comment by rhymes** [comment]
@Rafi993 although technically this is related to the feed page, please go ahead :D

**Comment by Rafi993** [comment]
The same bug also seems to happen in the dashboard
![dashboard](https://user-images.githubusercontent.com/8092120/80590216-26fb6500-8a39-11ea-9015-328c1568892e.png)

**Comment by Rafi993** [comment]
> @Rafi993 although technically this is related to the feed page, please go ahead :D

Thank you :)

**Comment by Rafi993** [comment]
I was able to notice this issue in feed page today.

![feed](https://user-images.githubusercontent.com/8092120/84412071-57374580-ac2c-11ea-81c1-182a1674473c.png)

But it does not happen anymore in other places due to the above fix

## Search

![search](https://user-images.githubusercontent.com/8092120/84412144-7209ba00-ac2c-11ea-8cbb-245df111cb8d.png)

## Main article

![content](https://user-images.githubusercontent.com/8092120/84412230-91084c00-ac2c-11ea-95d8-75e1f83c0a39.png)

## Reading list

![reading_list](https://user-images.githubusercontent.com/8092120/84412299-abdac080-ac2c-11ea-9e0a-af297e9ae630.png)

**Comment by Rafi993** [comment]
I would like to help with this issue if it is re-opened.

**Comment by rhymes** [comment]
@Rafi993 could you open a new one related to only just that? thank you!

**Comment by Rafi993** [comment]
ok

**Comment by CalinZBaenen** [comment]
@mahalde, awww.... Did I miss the party that happened here...? \:p
