### ISSUE TITLE
Following page does not show tags

### ISSUE THREAD

**Issue by Defman21** [thepracticaldev/dev.to#72]
The dashboard says I'm following 11 "things". But it only shows me what people I follow.
![image](https://user-images.githubusercontent.com/7100645/29133653-d98f1d04-7d3c-11e7-9028-55a533f62db7.png)
(11 following)
![image](https://user-images.githubusercontent.com/7100645/29133675-ebea340c-7d3c-11e7-93c9-1899fd1357b0.png)
(2 following? ehh?)

**Comment by jessleenyc** [comment]
Thanks for flagging, we'll look into it.

**Comment by Zhao-Andy** [comment]
Hey @Defman21, this is fixed now. Thanks for the heads up. :)
