### ISSUE TITLE
base: Invalid Github issue link

### ISSUE THREAD

**Issue by shreya-gr** [thepracticaldev/dev.to#7214]
**base:  Invalid Github issue link**

At the time of embedding GitHub comment inside the blog post. I'm facing the issue. Though, I've write the syntax properly.

![image](https://user-images.githubusercontent.com/21064733/78994793-8d8a1300-7b5e-11ea-9c93-cd174732f901.png)

> I'm trying to add this {% github https://github.com//prisma-labs/graphql-playground/issues/6#issue-245764378 %}
as per written in the guide 
![image](https://user-images.githubusercontent.com/21064733/78995164-6122c680-7b5f-11ea-955d-50d6a357591d.png)

Let me know any other information I can provide.

**Comment by rhymes** [comment]
Hi @shreya-gr!

There's a double forward slash between github.com and prisma-labs, if you use:

```liquid
{% github https://github.com/prisma-labs/graphql-playground/issues/6#issue-245764378 %}
```

it'll work!

**Comment by shreya-gr** [comment]
@rhymes thanks for drawing my attention. It works well.
