### ISSUE TITLE
Actions Menu: Panel Layout (UI/Visual)

### ISSUE THREAD

**Issue by lisasy** [thepracticaldev/dev.to#7222]
### Design assets
- [UI specs + states (Figma)](https://www.figma.com/file/Jgq2Qg3MqmjQ4uVdJtyAsS/Moderation?node-id=419%3A8264)
- [High-level flow (Figma)](https://www.figma.com/file/Jgq2Qg3MqmjQ4uVdJtyAsS/Moderation?node-id=470%3A0)

**Comment by lisasy** [comment]
![Screenshot 2020-04-15 15 14 37](https://user-images.githubusercontent.com/816402/79592631-176e3a80-808f-11ea-93f0-1d9dcf60deb6.png)

@jacobherrington @Zhao-Andy I've updated the Figma specs with the most updated version of the actions panel with the "thumbs up thumbs down" modification, so I hope this unblocks any unknowns you had here. Let me know if you have any q's/comments.

**Comment by jacobherrington** [comment]
This can be closed :) It was shipped out with the mod actions improvements!
