### ISSUE TITLE
Ensure Cover Images Use Image Tags and Adhere to the 16:9 Ratio

### ISSUE THREAD

**Issue by juliannatetreault** [thepracticaldev/dev.to#7228]
We currently use `<div>`s with an `image` class and a `background-image:url` for cover images on DEV. However, there is a better solution which is to replace the `<div>`s with `<img>` tags. In addition to this, it is imperative that we ensure that cover images adhere to the 16:9 ratio, with a width of around 1200px for SEO purposes. To improve DEV's overall SEO, it is important that we optimize cover images within the existing JSON-LD data structure.

**This issue represents an overarching task that is made up of three discrete parts.** The discrete parts are represented by the following open issues:
- Part One: Issue #7289 (Done ✔️ )
- Part Two: Issue #7290 (Done ✔️ )
- Part Three: Issue #7291 

✨ **A note to our amazing contributors: this issue will be worked on by a DEV team member and is not up for grabs!** ✨

**Comment by rhymes** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.
