### ISSUE TITLE
Markdown code not formatting correctly

### ISSUE THREAD

**Issue by Kvaibhav01** [thepracticaldev/dev.to#7236]
**Describe the bug**
When I write some code block in the editor like in JSX, it won't render it as formatted. It just shows up as a single line code block.

**To Reproduce**

1. Go to 'Write a post' button to open the editor.
2. Write some code block in the body like this in JSX:

```jsx
function HOC(WrappedComponent) {
  return class Test extends Component {
    render() {
      const newProps = {
        title: 'New Header',
        footer: false,
        showFeatureX: false,
        showFeatureY: true
      };
      return <WrappedComponent {...this.props} {...newProps} />
    }
  }
}
```

3. Hit the 'Preview' or 'Save draft' button you will see the code block isn't formatted as expected.

**Expected behavior**
The code block should have rendered in a proper JSX formatting.

**Screenshots**

Code I wrote in the editor (in JSX):

![JSX editor code](https://user-images.githubusercontent.com/11731837/79043350-4c583880-7c1c-11ea-9912-6f00f5d744f2.png)

Output as seen in 'Preview' page:

![JSX output](https://user-images.githubusercontent.com/11731837/79043400-94775b00-7c1c-11ea-8d6a-ba73c0f0b696.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Build 1903 Version 
- Browser: Google Chrome Version 80.0.3987.163 (Official Build) (64-bit)

**Additional context**
What's strange is this that in some of the other JSX code blocks above this it worked perfectly but after this none of them are rendered as expected. Here's the first JSX code I wrote:

![S code editor](https://user-images.githubusercontent.com/11731837/79043438-cb4d7100-7c1c-11ea-98af-2049dcf9b17c.png)

And it rendered correctly!

![S code output](https://user-images.githubusercontent.com/11731837/79043448-daccba00-7c1c-11ea-8e5f-f5e98568f81b.png)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
@Kvaibhav01 thanks for the report!

I initially thought it was an issue of backticks in the template string, but I tested with the following:

"""
const name = "Bob";

function HOC(WrappedComponent) {
  return class Test extends Component {
    render() {
      const newProps = {
        title: 'New Header for `${name}`',
        footer: false,
        showFeatureX: false,
        showFeatureY: true
      };
      return <WrappedComponent {...this.props} {...newProps} />
    }
  }
}
"""

and it works:

![Screenshot_2020-04-11 New Post - DEV Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/79046447-53c61480-7c11-11ea-8573-4b526dce47cd.png)

Could you paste the article's markdown somewhere? A [gist](https://gist.github.com/) for example.

**Comment by Kvaibhav01** [comment]
Hi @rhymes, here's the Gist for the article:

https://gist.github.com/Kvaibhav01/78912ad247356feabd698967e5d8b6a5

As you can see it's rendering properly on GitHub but it's not working for code examples from point no. _8. What's the difference between `createElement` and `cloneElement`?_

**Comment by rhymes** [comment]
Found the problem, is the backtick at the end here:

![Screenshot 2020-04-11 at 4 58 10 PM](https://user-images.githubusercontent.com/146201/79047233-aa355200-7c15-11ea-9236-7b6084b7e9fc.png)

Since it's not closed it throws out the whole parser. If you remove it or replace it with another char, the article will render correctly.

Let me know if that works for you

**Comment by Kvaibhav01** [comment]
Yes, it works! So stupid of me. I was finding the problem to this all day long. 

I'm closing the issue, thank you 😄
