### ISSUE TITLE
Cannot access Publish RSS Page from Settings

### ISSUE THREAD

**Issue by sksiyer** [thepracticaldev/dev.to#7237]
**Describe the bug**
The publish rss page is not found

The publish rss page is not found
**To Reproduce**
Go to settings then click Publish from RSS from navigation bar on left
https://dev.to/settings/publishing-from-rss

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).
