### ISSUE TITLE
Docker Installation fails on gemfile install

### ISSUE THREAD

**Issue by JuanVqz** [thepracticaldev/dev.to#7240]
**Describe the bug**

I got the error executing **./docker-run.sh INTERACTIVE-DEMO** then put the env variables
while Gemfile is installing gems I found this error

**Expected behavior**

Run dev.to in local dev XD

**Screenshots**
<img width="665" alt="Screen Shot 2020-04-12 at 1 45 33" src="https://user-images.githubusercontent.com/7331511/79062400-ad553000-7c5f-11ea-92ae-710df7ac54c6.png">
<img width="701" alt="Screen Shot 2020-04-12 at 1 45 52" src="https://user-images.githubusercontent.com/7331511/79062401-b0502080-7c5f-11ea-96b6-8d85e149e5b3.png">

- OS: macOS Catalina 10.15.4
- Browser:
- Version:

**Additional context**

I was able to solve the error, installing **libcurl** and **curl-dev** packages.

**Comment by JuanVqz** [comment]
Can I open a PR?

**Comment by rhymes** [comment]
@JuanVqz 

> Can I open a PR?

Sure, thank you! 

ps. does it work with the recommended method through `docker-compose`?

**Comment by JuanVqz** [comment]
@rhymes I don't know, Trying **docker-run.sh** was my first thought but let me try it...

**Comment by zakirkun** [comment]
thats my problem . hufttt

**Comment by amrdruid** [comment]
Thanks @JuanVqz for the fix 🎉 Think this issue can be closed now

**Comment by maestromac** [comment]
This sound fixed. Closing
