### ISSUE TITLE
Can't create webhooks

### ISSUE THREAD

**Issue by muety** [thepracticaldev/dev.to#7242]
Hi all! I was trying to use the API to create a webook, by `POST`ing to `dev.to/api/webhook` with the following body:

```json
{
  "webhook_endpoint": {
    "target_url": "https://my.server/webhook1",
    "source": "DEV",
    "events": [
      "article_created",
      "article_updated"
    ]
  }
}
```

I get a `200` response, however, with an empty array of webhook. When `GET`ting `/api/webook`, an empty array is returned as well.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @muety, how did you send the request? could you share the full back and forth from the client and the server?

I tried with curl and it worked correctly: 

```shell
➜  curl -v -X POST -H "Content-Type: application/json" \
  -H "api-key: API_KEY" \
  -d '{"webhook_endpoint":{"target_url":"https://example.org/webhooks/webhook1","source":"rhymes","events":["article_created"]}}' \
  https://dev.to/api/webhooks

> POST /api/webhooks HTTP/1.1
> Host: dev.to
> User-Agent: curl/7.69.1
> Accept: */*
> Content-Type: application/json
> api-key: API_KEY
> Content-Length: 119
>
* upload completely sent off: 119 out of 119 bytes
< ....
<
* Connection #0 to host dev.to left intact
{"type_of":"webhook_endpoint","id":844,"source":"rhymes","target_url":"https://example.org/webhooks/webhook1","events":["article_created"],"created_at":"2020-04-12T21:12:00Z","user":{...}}
```

**Comment by muety** [comment]
That's interesting, the problem occurs when using `dev.to` as URL, but when prefixing it with `https` it works. However, without `https`, I'm still getting a `200`. Anyway, issue solved, thanks! 🙂
