### ISSUE TITLE
C# badge detail page display the details of C badge.

### ISSUE THREAD

**Issue by 99darshan** [thepracticaldev/dev.to#7248]
**Describe the bug**
Clicking on details of C# badge display the details for C badge.

**To Reproduce**
Head on to /badges page, clicking on both the C# badge and C badge redirects to the same /badge/c page. I guess the C# and C badge should have different description and should redirect to their own details page.

**Comment by citizen428** [comment]
Thanks for the issue @99darshan! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
Context: the correct tag is `csharp`, not `c#`. Article pages etc. link correctly, but the `/badges` page does not.

**Comment by Pau1fitz** [comment]
this is a database issue, and will need to be updated there to be `csharp`. Based on the resolution for this issue it looks as if it will need to be resolved internally #6542
