### ISSUE TITLE
Potentional XSS in Notifications

### ISSUE THREAD

**Issue by Defman21** [thepracticaldev/dev.to#7249]
**Describe the bug**

Sometimes, I have a notification from DEV that looks like this:

```
$someusername just left a comment. Since they are new to the community, could you leave a nice reply to help them feel welcome? Thank you!

<comment>
```

Today I noticed a weird behavior of it. I got a notification with a link, but when I opened it, there's actually no link! https://dev.to/mintplayer/comment/nk2p However, there's an `<a href>` tag in the comment which got HTML-escaped and displayed properly. That did not happen in the Notifications page, though. 

![image](https://user-images.githubusercontent.com/7100645/79099508-f9da6180-7d6c-11ea-93a0-7cb4f1e2aa08.png)

I'm not sure if someone might be able to inject a `<script>` tag using that, but it looks like it can be done.

**To Reproduce**

1. Receive a notification about a comment from a new DEV user.
2. The comment should contain an html tag.

**Expected behavior**

HTML-escaped comment would be displayed in the Notifications.

**Desktop (please complete the following information):**

- OS: Win 10
- Browser: Firefox
- Version: 75.0

**Comment by citizen428** [comment]
Thanks for the report @Defman21. Would you like to submit this via our bug bounty program? https://dev.to/page/security

**Comment by Defman21** [comment]
Sure.

**Comment by Defman21** [comment]
Done. I'm not sure if we should keep this issue open, unless there's a way to hide it from everybody except contributors?

**Comment by rhymes** [comment]
@Defman21 thanks for sending it through the bug bounty, I'm going to close this and scrap the description content so at least it won't appear by default to onlookers

**Comment by Defman21** [comment]
It is possible to delete an issue completely?
