### ISSUE TITLE
Replace hardcoded shop links with a configurable option

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#7252]
To achieve this:
- create a `SiteConfig` option for the shop url
- make it configurable via `/internal/config`
- replace hardcoded links "shop.dev.to" with a configurable option (e.g. `SiteConfig.shop_url`)
- if there are link texts like "DEV Shop", replace it with `<%= community_name %> Shop`

It also makes sense to check if the shop url is configured, and not show the link if it isn't.

**Comment by lightalloy** [comment]
To our amazing contributors: This issue is labeled as `ready for dev`, so it's up for grabs.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

**Comment by jitendra1998** [comment]
Hi @lightalloy, I am interested in working on this issue.
