### ISSUE TITLE
Add a twitter hashtag as a configurable option

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#7254]
- create a `SiteConfig` option for twitter hastag, e.g. `SiteConfig.twitter_hashtag`
- make it configurable via `/internal/config`
- replace hardcoded twitter hashtag references with a configurable option (not complete)

**Comment by lightalloy** [comment]
To our amazing contributors: This issue is labeled as ready for dev, so it's up for grabs.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

**Comment by JuanVqz** [comment]
@lightalloy May I take it? Please

**Comment by lightalloy** [comment]
@JuanVqz feel free to take it :+1:

**Comment by JuanVqz** [comment]
Sorry for the time I took for making changes on this issue but I wasn't able to run the dev.to project on Docker containers, actually I'm going to open an issue for that

**Comment by Ridhwana** [comment]
To tackle `replace hardcoded twitter hashtag references with a configurable option` in [a separate issue](https://github.com/thepracticaldev/dev.to/issues/7835)

**Comment by lightalloy** [comment]
Closing as done with #7573
