### ISSUE TITLE
Comment text includes an entire HTML document inside

### ISSUE THREAD

**Issue by aaronpk** [thepracticaldev/dev.to#7271]
**Describe the bug**

When a comment is rendered on the comment permalink, it includes an entire HTML document header in it as well. For example:

```
...
      <div class="body ">
        <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body>
<p>Test comment</p>

</body></html>
...
```

Notice the new `DOCTYPE` and open and closing `<html><body>` tags.

**To Reproduce**

* Visit a post on dev.to
* Leave a comment with the text "Test comment"
* Visit the permalink of that comment
* View the source and search for the comment text

**Expected behavior**

The comment text should not be enclosed in a DOCTYPE and html element, it should include only the HTML of the text typed in.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 80.0.3987.163

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Great catch @aaronpk, this is likely from these lines:

https://github.com/thepracticaldev/dev.to/blob/ea1c27f6befe103a5fb547984b927318422afd5d/app/models/comment.rb#L146-L149
