### ISSUE TITLE
UI page for new developers

### ISSUE THREAD

**Issue by infinityrun** [thepracticaldev/dev.to#7278]
when some new developer joins dev.to community and lands on the initial page, there is a bug. Soon after I did a login by GitHub, I was redirected to build your profile page see the image attached with this, there is no scrolling option for this page and it is also not complete. There is a difficulty in navigate to the end of this page.
![Screenshot (129)](https://user-images.githubusercontent.com/26693197/79236376-7dd63b80-7e8a-11ea-9ca5-b860dc2d6182.png)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
@infinityrun can you share which browser you're using and which size and resolution has your monitor?

**Comment by infinityrun** [comment]
I am chrome. 

Screen Size | 39.62 cm (15.6 inch)

Screen Resolution | 1366 x 768 pixels

**Comment by infinityrun** [comment]
I am using chrome.

Screen Size | 39.62 cm (15.6 inch)

Screen Resolution | 1366 x 768 pixels

**Comment by maestromac** [comment]
Should be resolved with https://github.com/thepracticaldev/dev.to/pull/7269
