### ISSUE TITLE
Make dev digest template configurable

### ISSUE THREAD

**Issue by Ridhwana** [thepracticaldev/dev.to#7280]
- [x] `app/views/mailers/digest_email.html.erb` contains dev-specific texts like "Hiring developers?" or "our community of developers", we should make community_member_label configurable.

- [x] Make the email dynamic based on the domain

**Comment by Ridhwana** [comment]
<img width="1088" alt="Screenshot 2020-04-14 at 20 16 30" src="https://user-images.githubusercontent.com/2786819/79259384-eaead080-7e8c-11ea-9f69-be40ed1e8089.png">

There's a couple of things to change here:
```

**Comment by citizen428** [comment]
> We use this language in multiple places, so we can add field to site config to capture it.

That's how Meetup does it. When you start a new meetup they ask you what members will be called, e.g. for our functional programming meetup we put "Lambdaphiles", so that's the wording they use in emails, like "You and X more Lambdaphiles will attend this event."

**Comment by lightalloy** [comment]
I like the idea of configuring how the members will be called. But it could be not enough for the digest because it's likely not all communities will offer work and hiring, so I agree that we could have both settings.

**Comment by Ridhwana** [comment]
On further Investigation of the digest email, I decided to make the email dynamic using language prompts from the Site Config, instead of allowing the user to add custom html at the end of the email. 

I think for now this works based on looking at thismmalife as an example. If we decide later on it needs to be more configurable, we can tackle it then.
