### ISSUE TITLE
Replace Cover Image <div> Tags with <img> Tags

### ISSUE THREAD

**Issue by juliannatetreault** [thepracticaldev/dev.to#7289]
We currently use `<div>`s with an `image` class and a `background-image:url` for cover images in place of `<img>` tags, which is not semantic. The solution here is to replace all of the `<div>` tags with `<img>` tags to make things more semantic in addition to boosting DEV's SEO. **This issue is a discrete part of issue #7228 and represents the initial work that needs to be done.**

Cover Image Files to Change:
- [x] `articles/show.html.erb`
- [x] `stories/_main_stories_feed.html.erb`

Other Non-Semantic Files:
- `comments/index.html.erb`
- `articles/_bottom_content.html.erb` (questionable)

✨ **A note to our amazing contributors: this issue will be worked on by a DEV team member and is not up for grabs!** ✨

**Comment by rhymes** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.
