### ISSUE TITLE
Add Structured Data for SEO-Optimized Images

### ISSUE THREAD

**Issue by juliannatetreault** [thepracticaldev/dev.to#7291]
Once we have replaced `<div>` tags with `<img>` tags ( issue #7289 ) and have SEO-optimized cover images ( issue #7290 ), it is important that we add the SEO-optimized images to the JSON-LD within `articles/show.html.erb`. The hope is that by adding the images to the data structure, DEV's overall SEO will improve.  **This issue is a discrete part of issue #7228 and represents the final piece of the work that needs to be done.**

Changes to Make:
- [x] Enforce the 1:1 ratio for cover images via `articles/show.html.erb`'s JSON-LD
- [x] Enforce the 4:3 ratio for cover images via `articles/show.html.erb`'s JSON-LD
- [x] Enforce the 16:9 ratio for cover images via `articles/show.html.erb`'s JSON-LD

✨ **A note to our amazing contributors: this issue will be worked on by a DEV team member and is not up for grabs!** ✨

**Comment by rhymes** [comment]
Adding a note to coordinate with @thepracticaldev/oss on this as we are planning to implement a redesign of the article editor's UI in this cycle
