### ISSUE TITLE
`.base-article-show-sidebar-variant` p tag doesn't have any margin

### ISSUE THREAD

**Issue by kohgpat** [thepracticaldev/dev.to#7298]
Hi!

**Describe the bug**

I've recently read an article and sticky sidebar shows up with css class '.base-article-show-sidebar-variant' and data-id=99. The issue is that paragraph tag and a link next to it have no any margin between them and it looks a little bit weird.

I've found it on the page: `https://dev.to/mandiwise/getting-started-with-apollo-federation-and-gateway-4739` but if I understand the code correctly, html comes from the HtmlVariant model with id = 99.

**To Reproduce**

Visit a page with html variant id = 99.

**Expected behavior**

I believe there should be a margin after paragraph.

**Screenshots**

Please take a look at 'Get Started' link and a paragraph before it.

<img width="1273" alt="base-article-show-sidebar-variant" src="https://user-images.githubusercontent.com/555811/79347652-80a65e80-7f66-11ea-83f9-b3b75da1dc61.png">

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Safari/Chrome
- Version: Latest

**Additional context**

At first I thought I could fix it this but I've no found related styles. I'm not sure that the related styles are in stylesheets and not in the database.

Love the dev.to platform. You're great.

Sincerely, Nikolay.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by adfaris** [comment]
Can I start working on this? @jacobherrington

**Comment by citizen428** [comment]
You can, I assigned you the issue now @adfaris 😃

**Comment by adfaris** [comment]
@citizen428 Looks like  #8040 have removed the sidebar variant and this issue is already resolved.

**Comment by citizen428** [comment]
Ok, closing the issue now, thanks for offering help and taking the time to report back here @adfaris!
