### ISSUE TITLE
Add functionality to import single articles from Medium to publish on Dev.to

### ISSUE THREAD

**Issue by ghost** [thepracticaldev/dev.to#730]
## Feature Request or Task

Like with the RSS feed imports, it would be so convenient to import single articles from Medium into Dev.to with a reference to the original published source.

### User Story / Description

- As a blogger I would like to import single posts that I have written on Medium as markdown so that I can publish them on Dev.to
- As a blogger I would like to see the link to the original published source so that readers can visit the original webpage
- As a blogger I would like to have the option to set the canonical url HTML tag for the page on Dev.to to reference the original article

### Definition of Done

A user would be able to import a single article from a Medium post, it convert to markdown, then be able to publish it on Dev.to with a link to the original article and perhaps an option to set the canonical url.

**Comment by softchris** [comment]
seriously I need this.. It's costing me so much extra time when I have to rewrite it in markdown..

**Comment by rhymes** [comment]
@softchris can't you use the RSS feed in the meantime? Doesn't Medium have one?

**Comment by ryanwhocodes** [comment]
@rhymes a couple of reasons are:
1. rss imports all your recent posts whereas you may just want 1 imported
2. you might have an old post that you wan to import

**Comment by rhymes** [comment]
@ryanwhocodes got it, I think the feature should be more general though (not just for Medium). I'd improve the RSS import by allowing the selection of which posts to import and if the RSS feed contains all posts you might use that to import old posts as well. Like a RSS manager 😆

**Comment by softchris** [comment]
RSS feed on Medium is really limited in how much it contains. IMO it's better to be able to select a URL and have what's in there imported

**Comment by jovanshernandez** [comment]
Would love an update on this thread. I have a handful of Medium posts I'd like to move to Dev.To and going through all the markdown is not something I want to have to deal with...

**Comment by ryanwhocodes** [comment]
It would be amazing to have a tool that could be used in the dev.to codebase but also used elsewhere to take a Medium webpage and convert it to markdown, which could then be added as a draft article in the dev.to editor. 

A Ruby gem would integrate into the Ruby on Rails codebase easily, while having potential to be an open source project that could be used outside of the dev.to codebase too. An example could be someone who might want to use it for a personal blog as well as posting to dev.to. I'd be happy to contribute to this, but wouldn't have time to write the whole thing myself. 

@jessleenyc you were assigned to this, any thoughts on this thread or suggestions raised in this thread?

**Comment by jessleenyc** [comment]
@pkfrank I think this makes more sense as a third party tool that can be created through the API, then brought into the app natively. What do you think?

**Comment by jessleenyc** [comment]
Didn't mean to close it!!

**Comment by pkfrank** [comment]
@jessleenyc that makes sense to me.  I think that [this post](https://dev.to/stackbit/migrating-from-medium-a-developer-s-guide-3djh) from Stackbit would likely provide useful reference material for anyone who takes this on.

**Comment by jessleenyc** [comment]
Great! I'm actually going to close this issue since this wouldn't be done on platform anymore.

**Comment by Almenon** [comment]
I worked on improving https://github.com/SkillFlowHQ/medium-to-markdown then I realized that 
@ericclemmons already made a better medium exporter here: https://medium-to-markdown.now.sh 

![](https://media.giphy.com/media/14aUO0Mf7dWDXW/giphy.gif)

Note that the link might take a long time to load, just give it a while. Also the textarea where the markdown is outputted can be resized by dragging on the handle.

If both the SkillFlowHQ repo and medium-to-markdown.now.sh fail you can try https://github.com/xdamman/mediumexporter

If you want to go the other way you can use https://github.com/yoshuawuyts/markdown-to-medium
