### ISSUE TITLE
Bad UI/UX: Notification background color after profile save

### ISSUE THREAD

**Issue by gate3** [thepracticaldev/dev.to#733]
## Bug Report
The user profile looks good and everything works fine, but there is a small issue i'd like to point to. After the user has finished saving profile, the notification that comes up has a red backgound which makes the email unreadable and it also seems a lot like an error. I actually felt an error occurred after saving, the color doesn't make it intuitive that it was successful and i need to check my email.  I have attached an image below to show this

### Current Behavior
Red background is not making the email address visible and causes straining the eyes to see it or copying somewhere else.

### Expected Behavior
Another background color to show the text properly and to also show that the action was successful.

### Mobile & Desktop Screenshots/Recordings
<img width="1440" alt="screen shot 2018-09-25 at 12 04 18 pm" src="https://user-images.githubusercontent.com/3597437/46010855-fd8b9200-c0bb-11e8-8962-425238549cee.png">

**Comment by jessleenyc** [comment]
We're open to suggestions here if someone wants to work on this!

**Comment by tterb** [comment]
I'd be interested in working on this if no one's addressed it yet.

**Comment by ganderzz** [comment]
Playing around with this -- thoughts with going with the DEV black background? Matches the color-scheme without introducing a rainbow of colors to the page (and still stands out). Also, matches well with the white text and blue link color.

![screen shot 2018-10-05 at 7 56 59 pm](https://user-images.githubusercontent.com/5566054/46566714-0872cd80-c8d9-11e8-8bb6-ba53cd3924bd.png)

**Comment by tterb** [comment]
My initial thought was something like this, using styles featured on the dashboard/sidebar elements to fit with the overall dev.to UI. Though, it may not stand out as much if you're looking for more of an urgent call to action.  

<img width="941" alt="screen shot 2018-10-05 at 8 11 17 pm" src="https://user-images.githubusercontent.com/16360374/46566828-dcf0e280-c8da-11e8-904e-d5f6b136650f.png">

**Comment by lkopacz** [comment]
I think I like the white background the best! We should probably test the hex values just to be sure that the contrast is accessible for colorblindness :) 

If you want to give me the hex values, I can text them for you.

**Comment by tterb** [comment]
@lkopacz That's a good idea, the hex values are taken directly from the dashboard/sidebar elements.  

background: `#ffffff`
text-color: `#0a0a0a`
border: `#dbdbdb`
link-color: `#557de8` (unchanged from original, but might benefit from a bit more contrast)

**Comment by lkopacz** [comment]
Background and text color are excellent! 19.80:1
The link text needs a little bit of work. It's 3.83:1 and for small text we ideally want 4.5:1. 

How about #436EE5 which against a #ffffff background is 4.56:1 and looks like this
<img width="421" alt="screen shot 2018-10-11 at 7 44 23 pm" src="https://user-images.githubusercontent.com/6540866/46839939-7c581e80-cd8e-11e8-8c25-e989ee1cf00c.png">

(This is just the default text in the contrast checker I use btw). What are your thoughts?

**Comment by tterb** [comment]
I think that proposes a valid accessibility concern. Although, since the link color is universally used throughout dev.to, I think it might make more sense to make a separate issue to address the overall accessibility of the link color rather than independently modifying the link color for the notification.  

@jessleenyc What do you think?

**Comment by gate3** [comment]
I don't think the link colour should be changed since its being used all though the site. What i do think though is that a color be defined for the notification boxes that contrasts well with the link colour. I haven't encountered an error yet, so I don't know what the color for the error notification looks like.

**Comment by lkopacz** [comment]
@gate3 the problem with keeping the link color the same is that people who have colorblindness may not be able to see the link, particularly since there is no differentiation (like bold or underline or even a fancy enhancement) to distinguish the link from normal text. But I do agree this should be a separate issue. I can create that.

Good suggestion @tterb, so long as @jessleenyc agrees - I can create that.

**Comment by maestromac** [comment]
@lkopacz definitely feel free to create a separate issue for that.

Closing. Resolved with #994
