### ISSUE TITLE
Shop URL not getting redirected due to cors error

### ISSUE THREAD

**Issue by jitendra1998** [thepracticaldev/dev.to#7339]
**Describe the bug**

[dev.to/shop ](https://dev.to/shop) is expected to be redirected to [shop.dev.to](https://shop.dev.to), but it renders the error page. In the console, it can be seen that it's because of cors error.

same error for [dev.to/api](https://dev.to/api)

![image](https://user-images.githubusercontent.com/13114810/79494830-478eec80-8041-11ea-8445-63b1fc145a22.png)

**To Reproduce**

1. Clear all cookies for dev.to
2. Go to [dev.to/shop](https://dev.to/shop), it will redirect to [shop.dev.to](https://shop.dev.to) correctly.
3. Now visit [dev.to](https://dev.to)
4. Again visit [dev.to/shop](https://dev.to/shop), it will render error page.

**Expected behavior**

URLs should be redirected correctly, or they can be removed if not in use.

**Desktop (please complete the following information):**

- OS: Ubuntu 16
- Browser: Chrome
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by citizen428** [comment]
Thanks for the issue @jitendra1998! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
I can reproduce it. This is mighty weird as the redirect happens server side but I think it's related to how the service worker doesn't play well with redirects. See #7156
