### ISSUE TITLE
Tweets with poll dont render correctly

### ISSUE THREAD

**Issue by gyandeeps** [thepracticaldev/dev.to#7345]
**Describe the bug**

When I embed tweets using the `{% twitter 1250896975391752195%}` format and if the tweet has poll in it then it not displayed.

**To Reproduce**

1. create a page
1. create a twitter post link with a poll in it
    1. `{% twitter 1250896975391752195%}`
1. Preview it

**Expected behavior**

It should show the poll as part of the tweet body.
Example: https://dev.to/gyandeeps/code-ownership-nmk

Here i have embed html code provided by Twitter.

**Screenshots**

https://dev.to/gyandeeps/code-ownership-nmk

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version: 81

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by citizen428** [comment]
Thanks for the report @gyandeeps. This is what I see with both Firefox and Chromium on macOS as wekk as mobile Safari with iOS:

![Screen Shot 2020-04-17 at 11 05 25](https://user-images.githubusercontent.com/47985/79531070-6c17b280-809b-11ea-9b84-d0d069d77fe2.png)

Seems like the poll is rendering just fine, can you clear your cache and reload please?

**Comment by rhymes** [comment]
I can't see the poll either.

Tested with Firefox 76 

![Screenshot_2020-04-17 test poll](https://user-images.githubusercontent.com/146201/79566307-a476bb00-80b2-11ea-80b2-388dd129baa8.png)

and Chrome 80

![dev to_rhymes_test-poll-5f48-temp-slug-5675555_preview=8cddd665d7d0e619e440ba2c9ad07e255ebcc15c577ceac496ff3e3f395e6d17e9ffca3dff996f0165d0abfd714bd5dc17dbaa20f4c143aff4256521](https://user-images.githubusercontent.com/146201/79566345-afc9e680-80b2-11ea-9d77-8ebdcddae2a9.png)

both on macOS 10.14

**Comment by rhymes** [comment]
I'm closing this in favor of https://github.com/thepracticaldev/dev.to/issues/2955 as it's both a bug and a feature request but that contains more info on how to solve it. 

I'm going to mark the other as both a bug and ready for dev

Thanks @gyandeeps!

**Comment by rhymes** [comment]
Update: I tried to see if the problem lied in our parsing code or note, the issues is that polls are not included in the API response, see https://github.com/thepracticaldev/dev.to/issues/2955#issuecomment-615212983 so this can't be implemented yet
