### ISSUE TITLE
renaming an organisation results in a 503 error

### ISSUE THREAD

**Issue by lukeocodes** [thepracticaldev/dev.to#7355]
I'm attempting to rename an organisation and it returns a 503 error after almost exactly 30s every time.

**To Reproduce**

1. Login via Twitter
2. Click on **Settings** from the user dropdown
3. Click on **Organization**
4. Scroll down to **Organization Details**
5. Change **Username** to new value
6. Click **SUBMIT**

**Expected behaviour**

Updates organisation name to the new value.

**Screenshots**

![image](https://user-images.githubusercontent.com/956290/79551113-2524bf80-8091-11ea-8e8f-1d43aa3780fe.png)

**Desktop (please complete the following information):**

- OS: macOS Version 10.14.6 (18G1012)
- Browser: Chrome
- Version: Version 80.0.3987.163 (Official Build) (64-bit)

**Additional context**

**Comment by Zhao-Andy** [comment]
Thanks for raising this @lukeocodes! We currently do this synchronously, and if your organization has a lot of articles, the request will time out. Think out next step is to move this into a background job.

I'll DM you via DEV connect to follow up.

**Comment by eyewritecode** [comment]
Hey @Zhao-Andy Can i take this on?

**Comment by Zhao-Andy** [comment]
Hey @eyewritecode sure thing! Let me know if you have any questions. You can find examples of our async tasks in `app/workers`.
