### ISSUE TITLE
Ability to make moderated tags private

### ISSUE THREAD

**Issue by jonathan-irvin** [thepracticaldev/dev.to#737]
## Feature Request or Task
If a user is granted moderator status on a tag, they should have the ability to make the tag private for reserved tags

### Definition of Done
Specified tag would have an ACL which only allows certain articles to use the tag.

**Comment by jessleenyc** [comment]
Admins currently have a way to make tags approval-only. For example, if I tag a post w/ 'Special' and its approval-only, the post will still publish but the tag won't appear until an admin approves. I'm assuming this is what you're referring to but brought into mod privileges?

**Comment by jonathan-irvin** [comment]
Yeah, that's right @jessleenyc.

**Comment by jessleenyc** [comment]
Hey @jonathan-irvin, I think our new tag moderation feature (ability for tag moderators to remove inappropriate tags from posts) ultimately accomplishes what you're looking to do here. Closing this for now but feel free to re-open if you think it's different.
