### ISSUE TITLE
Running a single system test is very slow (takes over 40 seconds)

### ISSUE THREAD

**Issue by ledestin** [thepracticaldev/dev.to#7383]
**Is your feature request related to a problem? Please describe.**

I worked on a PR and wrote some system tests. Running a single system test takes 40-50 seconds.

I'm willing to investigate why it's so slow, and potentially fixing it.

**Describe the solution you'd like**

A system test taking ~5 seconds would be great.

**Describe alternatives you've considered**

CI is great, but immediate feedback is often needed.

**Additional context**

```
$time ./bin/rspec spec/system/articles/user_creates_an_article_spec.rb
DEPRECATION WARNING: Default values will be removed in the next minor-release of ENVied (i.e. > v0.9). For more info see https://gitlab.com/envied/envied/tree/0-9-releases#defaults. (called from block in load at /home/ledestin/work/dev.to/Envfile:4)
[Zonebie] Setting timezone: ZONEBIE_TZ="Chatham Is."
..

Finished in 1 minute 0.74 seconds (files took 8.82 seconds to load)
2 examples, 0 failures

Coverage report generated for RSpec to /home/ledestin/work/dev.to/coverage. 2723 / 15816 LOC (17.22%) covered.

real    1m12.136s
user    1m8.128s
sys     0m7.584s
```

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @ledestin, they are slow indeed!

Booting Chrome headless and clicking around with Capybara is not a fast operation.

Do you have any ideas on how to improve that?

**Comment by ledestin** [comment]
Hi @rhymes.

I think it's not Chrome and Capybara that are slow. I have a side project that uses headless Chrome, and running a comparable single test takes ~5 seconds (no Spring either).

It needs to be investigated, where the time is spent. One thing it does is call Webpack to compile JS, but I don't know how expensive that is. It really needs to  be profiled to get the idea where the time is spent.

**Comment by ledestin** [comment]
Update: I've profiled the process, and a lot of signs point to Sprockets as being the culprit. Lots of IO and CPU load caused by Sprockets. I intend to try speeding it up tomorrow.

**Comment by ledestin** [comment]
One reason for slowness is Sprockets and Sassc-rails combo. It processes SASS files on each test run, because Sprockets can't find cached versions. `SassCompressor`'s cache key changes on each run, for whatever reason. **I was able to make the test run 2x faster by using a constant cache key.**

I opened an issue https://github.com/sass/sassc-rails/issues/146, see for more details.

**Comment by citizen428** [comment]
@ledestin Thanks for looking into this! It's very interesting and gave me another idea, adding [`mini_racer`](https://github.com/rubyjs/mini_racer) to our Gemfile, which should be picked up by [`ExecJS`](https://github.com/rails/execjs) automatically. 

Here's the before and after comparison on the same spec you used:
 
```
no mini_racer: 
  Run 1: Finished in 59.24 seconds (files took 21.55 seconds to load)
  Run 2: Finished in 1 minute 4.24 seconds (files took 16.61 seconds to load)
  Run 3: Finished in 56.66 seconds (files took 15.89 seconds to load)

with mini_racer: 
  Run 1: Finished in 24.47 seconds (files took 15.08 seconds to load)
  Run 2: Finished in 28.25 seconds (files took 16.36 seconds to load)
  Run 3: Finished in 27.76 seconds (files took 14.19 seconds to load)
```

While this isn't exactly scientific, it's definitely promising.

**Comment by citizen428** [comment]
I then went on and replaced `sass-rails` with `sassc-rails` in our `Gemfile` (the former was previously only installed as a dependency of the Administrate gem), and I'm not sure which one Sprockets would pick up, so decided to only have one available:

```
mini_racer + sassc
  Run 1: Finished in 18.54 seconds (files took 8.12 seconds to load)
  Run 2: Finished in 21.73 seconds (files took 10.9 seconds to load)
  Run 3: Finished in 22.46 seconds (files took 11.27 seconds to load)
```

**Comment by ledestin** [comment]
With `mini_racer` it takes about 25 seconds to run `./bin/rspec spec/system/articles/user_deletes_an_article_spec.rb `.

The next source of slowness is ElasticSearch IO. I was able to reduce run time to 10 seconds by disabling `Cluster.recreate_indexes`. I'm not familiar with ElasticSearch, perhaps some optimisations can be done here?

https://github.com/thepracticaldev/dev.to/blob/master/app/services/search/cluster.rb#L13

**Comment by citizen428** [comment]
@ledestin Thanks for the pointer.

If you look at `spec/rails_helper.rb` you'll notice that we perform this operation twice, once before the whole test suite, once before specs tagged with `elasticsearch`

```ruby
  config.before(:suite) do
    Search::Cluster.recreate_indexes
  end

  config.around(:each, elasticsearch: true) do |example|
    Search::Cluster.recreate_indexes
    example.run
  end
```

Looking at the implementation of  `Search::Cluster.delete_indexes` it seems to be able to handle non-existant indexes:

```ruby
next unless Search::Client.indices.exists(index: search_class::INDEX_NAME)
```

This makes me wonder if we need the `berfore_suite` block at all, since any index we create there would be removed and recreated as soon as we hit the first spec tagged with `:elasticsearch`.

I experimented with removing `before(:suite)` locally, which shaved off ~10s so the spec now finished in ~16 seconds. I'll throw up a draft PR now to see if it finishes the whole suite without errors.

**Comment by ledestin** [comment]
@citizen428 thanks for doing so much to help!

I've tried various Elasticsearch settings, including `indices.memory.index_buffer_size`, and giving JVM 2-4 Gb of RAM, and none of that has affected indexing speed.

**But moving Elasticsearch data directory to SSD worked magic**, and it went 25 seconds -> 11 seconds for `spec/system/articles/user_deletes_an_article_spec.rb`. A JS spec `spec/system/articles/user_creates_an_article_spec.rb ` takes 19 seconds though.

**Comment by ledestin** [comment]
I was able to further slash ~6 seconds by using `./bin/spring rspec`, instead of `./bin/rspec`. So the JS system spec takes 13 seconds now and the non-JS 6 seconds!

`bin/rspec` isn't binstubbed by `Spring`, should I make a PR to binstub it?

**Comment by canoeberry** [comment]
I was hoping this was my issue. If I run 'rails test' it starts within a couple seconds. If I run 'rails test:system' it takes 20 seconds before it starts doing anything. And it's spending ALL its time in routes.rb.

Yup - the same routes.rb file is very very slow for some rails commands (rails test:system, etc) and quite speedy for other things (rails server, rails console, rails test, etc).

It just ... runs ... slower. The flame graph looks the same either way, it's just slower.
