### ISSUE TITLE
Organization page only shows 8 articles

### ISSUE THREAD

**Issue by kay-is** [thepracticaldev/dev.to#7384]
**Describe the bug**

The organization page did show all articles that were made under it, but now it only shows 8.

**To Reproduce**

Go to an organization page like that one: https://dev.to/moesif

**Expected behavior**

Showing all posts of an organization.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by mstruve** [comment]
Should be fixed by #7389. Deploy heading out now. Will close once the fix is validated in production

**Comment by mstruve** [comment]
Fix deployed and works!
