### ISSUE TITLE
Clicking on the notifications icon when there are new notifications requires reloading a page

### ISSUE THREAD

**Issue by Defman21** [thepracticaldev/dev.to#74]
Whenever I have a new notification and I click on the bell thing, I don't see it until I reload the page manually. I'm not sure if this happens when I haven't visited the notifications page in the current tab session, but If I've visited it and then I have to visit it again, I'm able to reproduce the issue.

**Comment by Zhao-Andy** [comment]
Thanks for the feedback. My preliminary thoughts are that it's a caching issue. Will look into it.

**Comment by Zhao-Andy** [comment]
I'm able to reproduce this if I leave a session/tab open for a long time, but otherwise works fine if it's a shorter time. Unfortunately, I don't know exactly when too long is, or vice versa. Could you confirm if this is the case for you, too? This will help me pinpoint what the issue exactly is.

**Comment by Defman21** [comment]
Sorry for the late reply, I don't get notifications that often so I can't check that. The tab was open for a long time though.

**Comment by Zhao-Andy** [comment]
Should be fixed now; closing. Let us know if you're still getting it.
