### ISSUE TITLE
Add a guide on how to keep forks current [documentation]

### ISSUE THREAD

**Issue by nathansebhastian** [thepracticaldev/dev.to#740]
This is a simple suggestion to add a new section on dev.to README file. How about we add a "maintaining your fork" section like [this one from freecodecamp](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#maintaining-your-fork)? Will be useful for new devs looking to start contributing.

**Comment by jonathan-irvin** [comment]
As in opening a PR from dev.to to your fork?

**Comment by nathansebhastian** [comment]
@jonathan-irvin no, I mean from individual forks to master. This is like setting upstream remote that we pull from to update the fork

**Comment by jonathan-irvin** [comment]
Oh, so you're asking to include documentation on how to add a remote to your local repo?

If you created a fork and cloned it, `origin` would point to your fork on GitHub.
To keep track of where dev.to is going from your local, you would add it as another remote repo.

`git remote add devto git@github.com:thepracticaldev/dev.to.git`

From there, you can merge master into your local and push it back to your fork.  Or, create a PR from dev.to to your fork's master.  It would work the same way.

_While being checked out on your master branch, locally..._
`git merge devto master`

This would sync your branches together, assuming you don't have any deviance.

**Comment by nathansebhastian** [comment]
Yes that's the one. I mean rather than assuming people know about this, why not just lay it out there in the readme files :)

I've created a PR for this section.. but if the reviewers decided that it's not neccessary, please feel free to close it.

**Comment by jonathan-irvin** [comment]
I'll do ya one better.  How about you add a script to package.json that accomplishes this?

**Comment by jonathan-irvin** [comment]
I pulled in your changes into my fork to add those scripts to the README

**Comment by nathansebhastian** [comment]
That's great. I'll close my PR then
