### ISSUE TITLE
Ensure That Special Characters Are Escaped in JSON-LD

### ISSUE THREAD

**Issue by juliannatetreault** [thepracticaldev/dev.to#7403]
We currently use JSON-LD to structure our site's data. While the data structure works, there are a couple of edge cases that have surfaced via Google's Search Console that we have not yet handled. In order to resolve the errors and handle the edge cases, it is important that we ensure that special characters are escaped in the data structure. 

Particular Places Where the Errors Have Been Thrown:
- [ ] Usernames which can be found in the data structure in the `stories_controller.rb`, `name: @user.name`
- [ ] Article titles which can be found in the data structure in `articles/show.html.erb` in `headline: <%= @article.title %>`

**✨ A note to our amazing contributors: this issue will be worked on by a DEV team member and is not up for grabs! ✨**

**Comment by benhalpern** [comment]
Do we need to escape _arbitrary_ special characters, or is it just the `\` that is causing us problems?

these are the identified links that are problematic...

https://dev.to/panchenkodmaspose/save-your-projects-to-project-server-project-online-via-pwa-using-aspose-tasks-c7
https://dev.to/zerquix18
https://dev.to/bjhaid_93

It makes sense that backslash would cause problems.
