### ISSUE TITLE
not able to login in to account

### ISSUE THREAD

**Issue by inventateq** [thepracticaldev/dev.to#7410]
Dear Dev Team,

when ever iam trying to write a post , it is showing Ooooops...
You have encountered an error.

please find attached screenshot and do the needful

<img width="1269" alt="Screenshot 2020-04-21 at 10 51 17 AM" src="https://user-images.githubusercontent.com/19629507/79828343-2d953700-83be-11ea-95c9-d42612bea9c7.png">

iam doing [data science training](https://www.inventateq.com/data-science-training-courses-bangalore.php) and would like to discuss so many things related to data science which is demanded technology in the current market.

**Comment by citizen428** [comment]
Hello @inventateq, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
