### ISSUE TITLE
Many duplicated/spammed posts in latest feed

### ISSUE THREAD

**Issue by codypearce** [thepracticaldev/dev.to#7424]
Tried in private window on Brave Browser and Safari with no extensions, still see the issue.

**Describe the bug**

Seeing many posts from one user that appear to be test posts of the API.

**To Reproduce**

1. Go to home page
2. Click latest
3. Scroll down a few pages

**Expected behavior**

Maybe rate limiting creating posts from one user or API key. Reddit has a rate limit of a post every 8 minutes for new users, which while annoying, does keep feeds pretty clean. 

I know some users like to batch post a few articles, which is fine, but I think there should be a limit so other's feeds aren't completely filled with posts from one author.

**Screenshots**

![screencast 2020-04-21 13-23-46](https://user-images.githubusercontent.com/12564956/79910766-19f4cb00-83d4-11ea-8720-2b2446503cea.gif)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Brave, Safari
- Version: Version 1.5.112 Chromium: 80.0.3987.132 (Official Build) (64-bit)

**Additional context**

Feel free to close this if this is a known issue, thanks!

Edit: Ah I see a few PRs about rate limiting already

**Comment by citizen428** [comment]
@codypearce Thanks a lot for the report! As you pointed out we are aware of the issue and actively working on fixing it. What you experienced yesterday was the result of an overeager pentester :wink:

I'll close the issue as you suggested.
