### ISSUE TITLE
Clicking on tag after listing has been opened should close the modal

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#7433]
When a single listing is opened, clicking on one of the tags will load the filtered listings in the background without closing the modal.

1. go to https://dev.to/connect
1. open any listing with a tag
1. click on one of the tags
1. see the page reconfigure in the background with all listings belonging to such tag

**Expected behavior**

1. open any listing with a tag
1. click on one of the tags
1. single listing should close so that one can access the filtered listings

**Screenshots**

![listings_tags](https://user-images.githubusercontent.com/146201/79971653-e7f76d80-8494-11ea-9a35-f57e5f65a470.gif)

**Comment by sujithnath** [comment]
@rhymes  Can you assign me this issue?

**Comment by rhymes** [comment]
@sujithnath go ahead and thank you!

**Comment by sujithnath** [comment]
> @sujithnath go ahead and thank you!

Hi @rhymes, A quick summary, I am disabling the filter upon clicking the tag instead it should close the model and take the user back to the existing listing. 

A small correction: From your comment, **"go to https://dev.to/connect"** should be  **"https://dev.to/listings"**. :D

**Comment by sujithnath** [comment]
> @sujithnath go ahead and thank you!

Hi @rhymes, just clearing a doubt. Once the user clicks the tag 

1) while closing the modal, should listing be filtered with the selected tag?

**Comment by rhymes** [comment]
@sujithnath yeah, I think clicking the tag should close the modal and filter with the selected tag. (that already happens now in the backgrund)
