### ISSUE TITLE
Users can not remove a deleted Github repo that has been pinned to their profile.

### ISSUE THREAD

**Issue by slbelden** [thepracticaldev/dev.to#745]
### Current Behavior
A Github repository that has been pinned to a user's profile (in the Integrations section of the profile settings) remains pinned when the Github repository is deleted. However, the repository is no longer listed in the user's profile settings, so it can never be removed.

### Expected Behavior
A Github repository that has been pinned to a user's profile is unpinned when the repository is deleted.
**OR**
All pinned Github repositories remain visible in the user profile settings even if they have been deleted, so they can be unpinned manually.

### Mobile & Desktop Screenshots/Recordings
Note the "Ompi-Journal" pinned repo:
![1](https://user-images.githubusercontent.com/11223028/46037558-b2767c80-c0c5-11e8-8db8-878a57f2e367.PNG)

The repo is deleted, so it does not apear in this list, and can not be removed:
![2](https://user-images.githubusercontent.com/11223028/46037577-c02c0200-c0c5-11e8-9e1f-abb939e1f58f.PNG)

The repo is deleted:
![3](https://user-images.githubusercontent.com/11223028/46037580-c3bf8900-c0c5-11e8-9bc2-633b5da3aeea.PNG)

### Additional Info (device/browser, helpful links)
Problem persists across all devices, browsers, and cache flushes.

**Comment by msarit** [comment]
@slbelden I tried to replicate this bug in my local dev, but it's not chirping 😄

Under `User/Settings/Integrations` I selected a few repos to pin. On my profile page, I saw them listed in the bottom-right corner (as expected). Went back into `Integrations` and clicked the "**Remove**" button for some repos. Back on my profile page, the removed repos were gone (as expected).

Are you still experiencing this bug?

**Comment by slbelden** [comment]
@msarit Those steps would not replicate this bug. This bug occurs when you delete the Github repo itself. Here are the steps for replication:

1. Create a new Github repo
2. Pin that repo to your profile
3. Delete the Github repo on Github

**Comment by msarit** [comment]
I misunderstood - thanks for clarifying 😁

**Comment by maestromac** [comment]
Sorry we didn't get to this sooner but thank you for reporting this issue @slbelden ! We went ahead and manually removed that phantom repo for you. This feature needs to be revised to address this issue.

**Comment by Link2Twenty** [comment]
I guess the easiest solution would be to move all selected repositories to the top of the list.

Then you can do something like this
```erb
<% @user.github_repos.where(featured: true).each do |repo| %>
  <div class="github-repo-row github-repo-row-selected">
    <div class="github-repo-row-name">
      <%= repo.name %> <%= "<span class='github-repo-fork'>fork</span>".html_safe if repo.fork %>
      <%= form_for(user_repo) do |f| %>
        <button class="cta">Remove</button>
      <% end %>
    </div>
  </div>
<% end %>
```

and remove this section
https://github.com/thepracticaldev/dev.to/blob/65110550d8c2231f73ff99ae305a46b7b0bcb4f9/app/views/users/_integrations.html.erb#L6-L13

**Comment by Zhao-Andy** [comment]
I like the idea of having the selected repos at the top. We recently merged a fix related to the integrations page and rewrote how it works, but we can sort the selected repos pretty easily.

**Comment by ItsASine** [comment]
I ran into this today, and as a quick fix: 
1. I made an empty public repo with the name of the deleted one in Github
1. Cleared cache on my DEV integrations page since I had already had it open
2. Removed the repo from my pinned stuff in DEV
3. Deleted the empty repo in Github

Hacky, yes, but effective... yes ¯\\\_(ツ)_/¯

**Comment by mattwaler** [comment]
Per @ItsASine's instructions:

I did basically the same thing, created repos with the exact same name as the ones I wanted to remove. 

However, they did not appear in dev.to as selected, so I had to select them, then remove them to get them cleared out.

**Comment by aleixmp** [comment]
The issue has another scenarios. You're unable to remove a repository from dev.to profile when:

1. You unlink the GitHub account.
2. You no longer have access to the GitHub account.

**Comment by ItsASine** [comment]
From a light poking around the code, it looks like it'd need reworked to show your pins and then show your github repos rather than just showing the github repos.     
Because as stated above, if your github changes at all in relation to the pinned repos (they're deleted, you don't have a github anymore...) then your Settings have no way to get to the pinned repos.

**Comment by rhymes** [comment]
Fixed by https://github.com/thepracticaldev/dev.to/pull/6582
