### ISSUE TITLE
Add PayPal support for membership

### ISSUE THREAD

**Issue by Eros** [thepracticaldev/dev.to#749]
## Feature Request or Task
Allow users to pay for membership (or other areas) on the website using PayPal, as far as I know it currently only supports stripe.
### User Story / Description
Reading this thread:
https://dev.to/hugo__df/unlock-more-devto-features--245a
and this comment the user seemed to want to support the website but is concerned regarding their payment information (understandable in some cases). Having paypal support would help a lot of users.
### Definition of Done
Present two options (or more) when going to purchase a sustaining membership, being PayPal or Stripe as the options given.

**Comment by jonathan-irvin** [comment]
@benhalpern do y'all accept crypto for support?

**Comment by Eros** [comment]
@jonathan-irvin pretty sure they're just supporting stripe with credit card payment at the moment.

**Comment by Exadra37** [comment]
The user in the link is me.

From the moment PayPal is accept I will be one of the first to subscribe :)

Why I don't want Stripe?

I know Stripe is a lot used in US but I am in Europe where is not that much used and I am not exposing my billing info to one more provider.

This is nothing against Stripe, but I already have a PayPal account and I am very strict with who I give my card details.

**Comment by jessleenyc** [comment]
Thanks for the request @Eros! We're interested in offering paypal as an option if anyone feels like working on this.

**Comment by angelleye** [comment]
I'm not a Ruby guy, but I can certainly help any questions or concerns about what PayPal API(s) to work with if needed.
