### ISSUE TITLE
Listing filter: Clear Filter not working properly

### ISSUE THREAD

**Issue by sujithnath** [thepracticaldev/dev.to#7499]
**Describe the bug**
With a few selected tags, if you are trying to clear the first tag, it clears the next one too. 

**To Reproduce**
![issue2](https://user-images.githubusercontent.com/6629348/80194997-e070c980-8638-11ea-9a55-a93b0a4dc06b.gif)

**Expected behavior**
Only the selected tag should be cleared. 

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by sujithnath** [comment]
@rhymes let me fix this anyway :-)
