### ISSUE TITLE
Notification of a removed post

### ISSUE THREAD

**Issue by michie1** [thepracticaldev/dev.to#75]
I received a notification of a person reacted to my comment to a discussion. When I follow the link of the notification I see my own comment without any reactions. I assume the reaction is being removed, but I'm not sure because I'm new to dev.to and maybe I'm missing some expand button.

Three possible improvements:
1. Remove notification of a removed reaction.
2. Mark notification it's about a removed reaction.
3. Show reaction without content but with removed mark.

What do you think of this enhancement?

**Comment by jessleenyc** [comment]
Your comment reaction most likely did _not_ get removed. Basically, no one can see reactions on comments yet, only reactions you give others. This is something we're working on since it doesn't really make sense right now 🙃

**Comment by michie1** [comment]
More details with screenshots.
Notifications
![notification](https://user-images.githubusercontent.com/1347371/29182309-ab4e438a-7dfe-11e7-930d-514eec1424a3.png)
The page of the comment.
![comment](https://user-images.githubusercontent.com/1347371/29182323-c296c562-7dfe-11e7-9ab0-41a2f35b0b24.png)
The full discussion without reaction to my comment.
![no_reaction_visible](https://user-images.githubusercontent.com/1347371/29182333-c8afd704-7dfe-11e7-9c87-20053413556d.png)

I'm curious what your reaction is and as I understand there is no way to see it right now?

**Comment by Zhao-Andy** [comment]
Exactly, there's currently no way to see other people's reactions to your comments. As Jess mentioned, it doesn't really make sense so we'll be reworking that soon.

**Comment by Zhao-Andy** [comment]
We've added a counter on comment likes which solves this issue. Thanks again for the feedback.
