### ISSUE TITLE
notifications to webapp

### ISSUE THREAD

**Issue by r-ush** [thepracticaldev/dev.to#7508]
**Is your feature request related to a problem? Please describe.** i get notifications via email and not on the webapp on my phone

 it get the notifications in the notification icon but not the notification on my phone 

**Describe the solution you'd like** android webapp notifications

**Describe alternatives you've considered**

**Additional context**

**Comment by rhymes** [comment]
Hi @r-ush, I'm not sure if you're referencing to the DEV Android app or simply notifications to your Chrome mobile on Android.

In the first case version 1.3 of the Android app with push notifications is currently in beta testing, I believe it will be released soon. See https://github.com/thepracticaldev/DEV-Android/releases/tag/1.3 and keep an eye on future updates to the app.

If you are referring to in browser push notifications we don't currently support them, see [these two issues](https://github.com/thepracticaldev/dev.to/issues?q=is%3Aopen+label%3A%22area%3A+notifications%22+push)
