### ISSUE TITLE
Fix alignment of checkbox + label on "Email Preferences" slide

### ISSUE THREAD

**Issue by lisasy** [thepracticaldev/dev.to#7544]
![Screenshot 2020-04-27 10 31 07](https://user-images.githubusercontent.com/816402/80402238-7b081d00-8872-11ea-8198-324002ecc977.png)

**Comment by vaidehijoshi** [comment]
@lisasy is the issue with this that the text needs to be a bit lower to line up with the checkbox? just want to make sure i understand i have all the context :)

**Comment by vaidehijoshi** [comment]
Also, does this issue also need to be fixed with the code of conduct/terms and conditions boxes on the intro slide?
