### ISSUE TITLE
Direct messages not showing up unless you filter

### ISSUE THREAD

**Issue by teacupwoozy** [thepracticaldev/dev.to#755]
### Current Behavior
When I went to go reply to a direct message this morning, none of my prior messages were showing. I refreshed and nada. If I start typing in a name in the filter, the message thread with that person will appear. Or, if I click on "group,"  the thread will show up but the person's name isn't listed in the left column. 

### Expected Behavior
Previously, I'd click into messages (/connect), and people previously messaged are in the left column and the message thread appears to the right.

### Mobile & Desktop Screenshots/Recordings
![screen shot 2018-09-27 at 8 51 13 am](https://user-images.githubusercontent.com/39562805/46151203-e374bf80-c233-11e8-8bb4-b975fbacc40b.png)
![screen shot 2018-09-27 at 8 56 34 am](https://user-images.githubusercontent.com/39562805/46151238-f7b8bc80-c233-11e8-819f-82bee54f42c0.png)

### Additional Info (device/browser, helpful links)
Mac High Sierra 10.13.6 Chrome 69.0.3497.100 😑

**Comment by benhalpern** [comment]
Hey, thanks for this. Can you let us know what the console is outputting?

**Comment by teacupwoozy** [comment]
Yeah, no problem. Here are screenshots of all of the errors, and the details of the first error. Let me know if you want the details of the rest.
![screen shot 2018-09-27 at 10 53 36 am](https://user-images.githubusercontent.com/39562805/46158626-e37cbb80-c243-11e8-9668-b681ad2a4907.png)
![screen shot 2018-09-27 at 10 53 50 am](https://user-images.githubusercontent.com/39562805/46158627-e37cbb80-c243-11e8-9a69-03ad84ac6eae.png)
![screen shot 2018-09-27 at 10 54 22 am](https://user-images.githubusercontent.com/39562805/46158628-e37cbb80-c243-11e8-8f0e-2069da3d2b36.png)
![screen shot 2018-09-27 at 10 54 31 am](https://user-images.githubusercontent.com/39562805/46158629-e4155200-c243-11e8-8415-19f6cbcd4192.png)

**Comment by mariocsee** [comment]
Hey, just wanted to check in if this is an issue you still experience? And if so, how I can replicate it on my laptop?

**Comment by teacupwoozy** [comment]
@mariocsee Yes, I'm still experiencing this. When I click on the paper airplane to view messages, the page defaults to show all messages. For me, nothing populates and it appears I have no messages. If I click to filter "direct" messages, still nothing populates. Then, if I click "group," it shows a message chain from the most recent percent who I've messaged. I cannot see any other message threads from anyone else.

**Comment by mariocsee** [comment]
@teacupwoozy This only happens occasionally for me. When I first go to /connect by the paper airplane, they populate, but I've been able to replicate your issue by repeatedly trying to reload /connect by clicking on the paper airplane. When it happens for me, I receive this message in console: 
<img width="433" alt="screen shot 2018-12-18 at 12 21 01" src="https://user-images.githubusercontent.com/13403332/50171137-a0b90580-02bf-11e9-8db2-bc942083e3e3.png">

Is the message in your console the same as what you posted in September? If so, do you mind giving me an updated screenshot so I can head to that line in `channels.jsx`?

**Comment by teacupwoozy** [comment]
![Screen Shot 2019-03-20 at 7 25 02 AM](https://user-images.githubusercontent.com/39562805/54687616-a6520180-4ae1-11e9-9c14-240b3a246042.png)
I'm getting different (and fewer) errors now. But the problem persists and I can't see messages without searching for them explicitly.

**Comment by Zhao-Andy** [comment]
Hey @teacupwoozy, could you give a try now? Think there might have been a bug with your account specifically.

**Comment by teacupwoozy** [comment]
@Zhao-Andy Sorry this took me so long to respond to.. But, yes! Everything is showing up as it should. Glad to hear that it was only a problem specific to my account and not a larger issue.
