### ISSUE TITLE
Error while setting up docker setup

### ISSUE THREAD

**Issue by dravitykeeper** [thepracticaldev/dev.to#7557]
**Describe the bug**
Database 'Developer_development' already exists
could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
Couldn't create 'Developer_test' database. Please check your configuration.
rails aborted!
PG::ConnectionBad: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

**Desktop (please complete the following information):**

- OS: Linux Mint
- Browser: Chrome

**Comment by citizen428** [comment]
Thanks for the issue @dravitykeeper! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
@dravitykeeper Was this when you used Docker Compose? I'm a bit surprised by the DB name here, it shouldn't be "Developer_development" but `PracticalDeveloper_development`.

**Comment by steinskeeper** [comment]
Yeah I had changed it because I was already running another database instance with name PracticalDeveloper_development and needed to create another to test some stuffs out. But did that break something?

**Comment by steinskeeper** [comment]
@citizen428  The problem is still there if the database is PracticalDeveloper_development

**Comment by dravitykeeper** [comment]
@citizen428  The problem is still there if the database is named PracticalDeveloper_development

**Comment by citizen428** [comment]
@dravitykeeper I didn't expect this to resolve the issue, but I was surprised that a wrongly named DB was created/previously existed. 

You closed the issue now, is it resolved for you?

**Comment by dravitykeeper** [comment]
@citizen428 I could not resolve it after trying so many things, so I am currently comparing my version of the code and the master branch. If I find what caused the problem or find how to recreate the problem I'll update it.

**Comment by maestromac** [comment]
Hello @dravitykeeper , you happen to be setting and using `DATABASE_URL`? You also need to set `DATABASE_URL_TEST`, it could be the same url. Try that and let me know if it resolved for you.

I also ran into this issue and found that it was due to a recent change (https://github.com/thepracticaldev/dev.to/pull/7437)
