### ISSUE TITLE
Wrong alignment of save button in settings page in mobile

### ISSUE THREAD

**Issue by Rafi993** [thepracticaldev/dev.to#7560]
**Describe the bug**
The save button in mobile in settings page is sticks to the left.
**To Reproduce**
1. Go to [settings](https://dev.to/settings) in mobile browser
2. Scroll down for the the save button

**Expected behavior**

There should be some left and bottom margin for the save button

**Screenshots**

![save-button](https://user-images.githubusercontent.com/8092120/80451665-07cddc00-8942-11ea-8562-4fa54d6cb90f.png)

**Smartphone (please complete the following information):**

- Device: Redmi note 6 pro  
- OS: Android 9
- Browser: Brave
- Version: 1.5.131

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
Same on iOS with Firefox FWIW.

**Comment by Rafi993** [comment]
Hi there if this up for grabs I would like to help

**Comment by Ridhwana** [comment]
Hi @Rafi993 sure thing :) I'll assign you the issue!

**Comment by Rafi993** [comment]
Thank you :)
