### ISSUE TITLE
Clicking icons in the navbar severally yields an empty search that redirects to the search results page

### ISSUE THREAD

**Issue by harunmohamed** [thepracticaldev/dev.to#7578]
Hi Dev,

This is an issue where clicking the notification icon or any other icon in the navbar for a while renders an empty search query and redirects to the search results page. is this intentional or could it be a bug? Either way, it's worth a look.

The twitter link contains a video recording of the said action and the result it yields. 

https://twitter.com/6am6ii/status/1254834119948800002

**Comment by citizen428** [comment]
Is this happening for you reproducibly? I did not manage to reproduce it.

**Comment by rhymes** [comment]
I can't reproduce this either :(

**Comment by harunmohamed** [comment]
Yes. I tried it a couple of times. When clicking the icons idly a couple of times, it redirects to the search results. Any success reproducing the behavior?

**Comment by citizen428** [comment]
No, I never managed to reproduce this.
