### ISSUE TITLE
why are my post not submit

### ISSUE THREAD

**Issue by ZoeyJames** [thepracticaldev/dev.to#7586]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by citizen428** [comment]
Hello @ZoeyJames, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
