### ISSUE TITLE
bin/setup fails with Algolia::AlgoliaProtocolError, claiming "Operations quota exceeded"

### ISSUE THREAD

**Issue by Antrikshy** [thepracticaldev/dev.to#759]
## Bug Report

This is a bug report with the dev environment. It's possible that there is no bug and I'm missing some cleanup step or something else with my Algolia account. I apologize if I'm missing something obvious in the README or other documentation.

### Current Behavior

`bin/setup` fails at:

```
"1/8 Creating Organizations"
"2/8 Creating Users"
rails aborted!
Algolia::AlgoliaProtocolError: Cannot PUT to
https://<my Algolia app ID here>.algolia.net/1/indexes/User_development/settings:
{"message":"Operations quota exceeded, change plan to get more Operations.","status":403} (403)
```

I've added new-line characters for readability and redacted my Algolia app ID in the copy-pasta above.

### Expected Behavior

`bin/setup` works and lets me work on a dev environment like it did the first time I tried it a few days ago.

**Comment by rhymes** [comment]
It happened to me once, you exceeded the free quota. I solved it by logging into the Algolia account and creating a new API key

**Comment by Zhao-Andy** [comment]
Yeah, this happens once you exceed the free quota. As @rhymes said, uou can generate a new key to avoid it, but I think we probably shouldn't hit the limit in development. Thanks for creating this issue.

**Comment by Antrikshy** [comment]
This is strange. Nothing in my Algolia account suggests that I have exceeded any quotas and I even get some errors when trying to list all my API keys for this application. I think it might be an issue on their end. ¯\_(ツ)_/¯

**Comment by maestromac** [comment]
Definitely seems like an Algolia issue. Let us know if similar issue ever comes up again.

Closing!
