### ISSUE TITLE
Write post issue

### ISSUE THREAD

**Issue by LenaCharles** [thepracticaldev/dev.to#7590]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hello @username, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
