### ISSUE TITLE
Figcaption overlap tags

### ISSUE THREAD

**Issue by GMartigny** [thepracticaldev/dev.to#760]
### Current Behavior

When an article start with a `<figcaption>` tag, it overlap with the tags list.

### Expected Behavior

Well, it shouldn't.

### Mobile & Desktop Screenshots/Recordings
Desktop:
![image](https://user-images.githubusercontent.com/2543511/46195159-cb6c7100-c303-11e8-95da-386147afba30.png)

Mobile:
![image](https://user-images.githubusercontent.com/2543511/46195362-6d8c5900-c304-11e8-8f3a-32daacd5aa52.png)

### Additional Info (device/browser, helpful links)

Article:
https://dev.to/idoshamun/most-popular-development-posts-of-the-week-26-september-2018-3ojn

I see a negative `margin-top` CSS rule on figcaption. This rule should only apply when preceded by an image, roughly `img + figcaption {`.

**Comment by Zhao-Andy** [comment]
Good catch, thanks!

**Comment by Snowbell92** [comment]
is anyone working on this? Can I submit a PR? I'm a first-time contributor, so would really appreciate some heads-up.

**Comment by Zhao-Andy** [comment]
Hey Samia, feel free to submit a PR. :)
