### ISSUE TITLE
Clicked "Twitter Auth" in my profile and an error is generated.

### ISSUE THREAD

**Issue by michaelwilde** [thepracticaldev/dev.to#7628]
**Describe the bug**
Per Dev.to's recommendation, I clicked the "connect twitter" feature, and this error is returned.

https://share.getcloudapp.com/xQuWbrZK

**To Reproduce**

If you can sudo to my account, that's fine.. try clicking "connect twitter".  Not sure if you've got that specific data in Honeycomb (around the error--did it 503? not sure), but you might look in Honeycomb.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hi @michaelwilde, thanks a lot for the report! We're shipping shortly a fix for that. I'll notify you when it's available in production!

**Comment by rhymes** [comment]
Sorry @michaelwilde for the late "notification". You should be able to get verify that it works in production. Let us know if it's not the case
