### ISSUE TITLE
DEV Community Github Auth on Android 10

### ISSUE THREAD

**Issue by sjadczak** [thepracticaldev/dev.to#7640]
**Describe the bug**

When attempting to log in to the android application with my github credentials, I get an error about clear text not being permitted. Uninstaller and reinstalling the application does not help. 

**Expected behavior**

Github oauth authentication and logging into my account on the app

**Screenshots**

Error text

Webpage not available
The webpage at http://dev.to/users/auth/github/callback?code=452c88f780c10fd45ca8&state=e887da40ebd91754901610594868fb15a5f7bc83a0eb67ba could not be loaded because:

net::ERR_CLEARTEXT_NOT_PERMITTED
**Smartphone (please complete the following information):**

- Device: Samsung Galaxy S10
- OS: Android 10
- Browser: DEV application

**Additional context**

**Comment by citizen428** [comment]
@sjadczak Thanks for the report! This was also discussed in https://github.com/thepracticaldev/DEV-Android/issues/73 and the fix was merged, so I'll close this issue here.
