### ISSUE TITLE
I cannot post anything

### ISSUE THREAD

**Issue by allnulled** [thepracticaldev/dev.to#7641]
I cannot post after saying something that is truth, and it is that paid universities are criminals, because if they were free, COVID-19 would be controlled and understood nowadays.

**Comment by rhymes** [comment]
Hello @allnulled, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.

**Comment by allnulled** [comment]
Yes, and so I did. I do not fit this world, but I think I can fit your community, because maybe another thing no, but I have contributed to development and programming as a crazy person, without receiving money for it, I think I deserve a minimum of integration in this kind of communities, I still have a lot to say about Microsoft, Github and Npm, and their monopolization and invisibilization of the alive JavaScript ecosystem.

**Comment by allnulled** [comment]
@rhymes I supose this is the polite way of telling me to go to hell. But I am already, I live with these kinda apes that do not let even study and understand the world collectively. Opportunists, opportunists everywhere.

**Comment by allnulled** [comment]
sorry, they let you understand. But you have to have this... divine substance, yeah, money. The slavism tool, the ring to rule them all.

**Comment by rhymes** [comment]
@allnulled that's the standard reply we give to users that have support related issues. I simply think you're off topic airing your grievances in here as this is the repository for the open source project. I think you should contact support and make your case.
