### ISSUE TITLE
Twilio image doesn't have "alt"

### ISSUE THREAD

**Issue by belhassen07** [thepracticaldev/dev.to#7677]
I looked for the Twilio image on the right of the home page. I didn't understand what's that about, I went for alt, like a nerd, and I didn't find an alt. So  it's an accessibility problem I guess but other than that, the usability problem that I really didn't get it, at first I thought it's a sponsor but the good'ol sponsors section is down left.

**Comment by citizen428** [comment]
Thanks for the report @belhassen07. This image was for the Twillio hackathon.

https://dev.to/devteam/announcing-the-twilio-hackathon-on-dev-2lh8

Since we'll announce the winners today the image will go away soon, so I'll close this issue if you don't mind.
