### ISSUE TITLE
Configuration set up is super hard for non-ruby folks

### ISSUE THREAD

**Issue by ahmadawais** [thepracticaldev/dev.to#768]
Thanks for open sourcing Dev.to 🙌 really appreciate that.

I'll be honest, several times me and my friends (three designers and four devs) none of whom including me are aware of the ruby ecosystem — have tried to contribute — but were all scared away of the initial local set up.

E.g. tonight, I had it with a CSS bug I was fighting with and thought I should set the local env and send in a Pull Request.

After over 45 mins into the set up `rbenv` didn't work and I kept getting error of `2.3.3 is not right install 2.5.1` finally `brew install ruby` and then overwriting it helped.

Then `bundle install` led to this error:

```sh
Installing pg 1.0.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/ahmadawais/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pg-1.0.0/ext
/Users/ahmadawais/.rbenv/versions/2.5.1/bin/ruby -r ./siteconf20180930-40441-185v1d5.rb extconf.rb
checking for pg_config... no
No pg_config... trying anyway. If building fails, please try again with
 --with-pg-config=/path/to/pg_config
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/ahmadawais/.rbenv/versions/2.5.1/bin/$(RUBY_BASE_NAME)
	--with-pg
	--without-pg
	--enable-windows-cross
	--disable-windows-cross
	--with-pg-config
	--without-pg-config
	--with-pg_config
	--without-pg_config
	--with-pg-dir
	--without-pg-dir
	--with-pg-include
	--without-pg-include=${pg-dir}/include
	--with-pg-lib
	--without-pg-lib=${pg-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/ahmadawais/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-17/2.5.0-static/pg-1.0.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/ahmadawais/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pg-1.0.0 for inspection.
Results logged to /Users/ahmadawais/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-17/2.5.0-static/pg-1.0.0/gem_make.out

An error occurred while installing pg (1.0.0), and Bundler cannot continue.
Make sure that `gem install pg -v '1.0.0'` succeeds before bundling.

In Gemfile:
  pg

```

Can we have a small Docker-based setup that is easier to use locally instead of installing all this stuff?

I could really help out with many things if the dev/contribution set up would be a bit easy.

Looking forward!

**Comment by ahmadawais** [comment]
Running that last gem install separately does this

```sh
gem install pg -v '1.0.0'
Building native extensions. This could take a while...
ERROR:  Error installing pg:
	ERROR: Failed to build gem native extension.

    current directory: /Users/ahmadawais/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pg-1.0.0/ext
/Users/ahmadawais/.rbenv/versions/2.5.1/bin/ruby -r ./siteconf20180930-58070-15he5qp.rb extconf.rb
checking for pg_config... no
No pg_config... trying anyway. If building fails, please try again with
 --with-pg-config=/path/to/pg_config
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/ahmadawais/.rbenv/versions/2.5.1/bin/$(RUBY_BASE_NAME)
	--with-pg
	--without-pg
	--enable-windows-cross
	--disable-windows-cross
	--with-pg-config
	--without-pg-config
	--with-pg_config
	--without-pg_config
	--with-pg-dir
	--without-pg-dir
	--with-pg-include
	--without-pg-include=${pg-dir}/include
	--with-pg-lib
	--without-pg-lib=${pg-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/ahmadawais/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-17/2.5.0-static/pg-1.0.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/ahmadawais/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pg-1.0.0 for inspection.
Results logged to /Users/ahmadawais/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-17/2.5.0-static/pg-1.0.0/gem_make.out

```

**Comment by rhymes** [comment]
Hi @ahmadawais, let's see if I can help in the meantime. You need to install postgresql: 

`brew install postgresql` or you can use [Postgres.app](https://postgresapp.com/) - check out the installation guide: https://docs.dev.to/installation/mac-os/

then run `bundle install` again.

**Comment by ahmadawais** [comment]
I had the app installed, running, initialized but didn't help. No trying the brew way.

**Comment by ahmadawais** [comment]
OK now stuck at `bin/setup`

```sh
   -> 0.0025s
"1/8 Creating Organizations"
"2/8 Creating Users"
rails aborted!
ActiveRecord::RecordInvalid: Validation failed: Profile image could not download file: execution expired
/Users/ahmadawais/Documents/Web/Sandbox/dev.to/db/seeds.rb:28:in `block in <top (required)>'
/Users/ahmadawais/Documents/Web/Sandbox/dev.to/db/seeds.rb:27:in `times'
/Users/ahmadawais/Documents/Web/Sandbox/dev.to/db/seeds.rb:27:in `<top (required)>'
/Users/ahmadawais/Documents/Web/Sandbox/dev.to/bin/rails:9:in `require'
/Users/ahmadawais/Documents/Web/Sandbox/dev.to/bin/rails:9:in `<top (required)>'
/Users/ahmadawais/Documents/Web/Sandbox/dev.to/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:setup => db:seed
(See full trace by running task with --trace)

== Command ["bin/rails db:setup"] failed ==
```

**Comment by ahmadawais** [comment]
Also the site doesn't work `bin/startup` ⬇️

![image](https://on.ahmda.ws/713a986e6502/c)

**Comment by rhymes** [comment]
> ActiveRecord::RecordInvalid: Validation failed: Profile image could not download file: execution expired

this seems like the attempt to download the generated imaged timed out. can you try again?

> Also the site doesn't work bin/startup ⬇️

yeah, until the setup is done, the startup won't work


Anyhow, it is true that you need some Ruby and Rails knowledge to setup or contribute. Hopefully the Docker setup will lower the barrier for people who don't know this technologies or aren't developers.

**Comment by nickytonline** [comment]
@ahmadawais, I have no Ruby knowledge and it wasn't too bad getting the local dev environment setup. The recommended way of installing ruby for the project is via `rbenv`.

The reason being, at least on a Mac, from what I understand is, that, macOS ships with a version of ruby that if you change it, breaks other things, so `rbenv`, like `nvm` for Node, let's you manage versions a lot easier. 

I also kept it simple, as @rhymes suggests up above, by using the Postgress.app. Pretty much what's in the docs.

**Comment by ahmadawais** [comment]
>I have no Ruby knowledge and it wasn't too bad getting the local dev environment setup. 

@nickytonline so you mean the current setup cannot be improved? I think it can be. A docker based setup would be much appreciated. As you can take a look above I had a fair share of issues.

>The reason being, at least on a Mac, from what I understand is, that, macOS ships with a version of ruby that if you change it, breaks other things, so rbenv, like nvm for Node, let's you manage versions a lot easier.

Yes, I had read that before installing `rbenv` but it didn't work for me, `bundle install` kept asking for latest version but I had already installed it. So, I had to go for `brew`. Not sure why. 

>I also kept it simple, as @rhymes suggests up above, by using the Postgress.app. Pretty much what's in the docs.

Trying again. Let's see.

**Comment by ahmadawais** [comment]
@rhymes I stopped and started the Postgress.app again and `bin/setup` worked it ended with `DEV` ASCII and all.

After that I ran `bin/startup` and finally it seems to have worked.

**Comment by nickytonline** [comment]
@ahmadawais, definitely agree about the Docker setup. I didn't bring it up just because there's already a PR up for it.

**Comment by nickytonline** [comment]
There's no demo account, but creating the Twitter app took a minute or two and then I was using it right away or do up GH like @rhymes was saying.

**Comment by ahmadawais** [comment]
@rhymes you were right! GitHub login worked.

Just sent a PR for some docs improvement on the contribution method.
