### ISSUE TITLE
mute notifications from a specific user

### ISSUE THREAD

**Issue by Glyphack** [thepracticaldev/dev.to#7686]
**Is your feature request related to a problem? Please describe.**
After you follow a user on the platform your notification count increment when user publish contents and if you have a huge list of followings It becomes a lot of notifications and specially the more important notifications like comments could be missed. since you open notifications and see a lot of contents and until you don't click on comments you can't check whether these notifications were comments or not.

**Describe the solution you'd like**
It could be better if you could mute a user. you can mute a user and with users post your notifications count would not increase. when you open notifications you can see a number beside all, comments and posts sections indicate that how many notifications that section has.

**Describe alternatives you've considered**
You could set setting to posts notifications do not increment notifications count but since user might not want to miss some other user posts it is not a good idea.

**Additional context**
posts , comments and all notifications has a check mark beside it. In my opinion left of that check mark is a good place for the count of that sections notifications count.

**Comment by rhymes** [comment]
Hi @Glyphack, I believe this was already raised in https://github.com/thepracticaldev/dev.to/issues/3171 so I'm closing this and redirecting you to that issue.

Thanks for taking the time and let us know if indeed is not a duplicate
