### ISSUE TITLE
Navigation in iOS PWA

### ISSUE THREAD

**Issue by brian-kephart** [thepracticaldev/dev.to#769]
### Current Behavior
When the PWA is added to the home screen in iOS, the app opens without browser features, including navigation. That means no back/forward buttons. The browser's built-in swipe gestures aren't present either.

### Expected Behavior
Swipe right should navigate back, left should navigate forward.
[Update] If swipe isn't feasible, then at least some method of backward navigation should be present.

**Comment by nektro** [comment]
This is part of iOS's current handling of PWAs and if manual swipe gestures were put in, it would interrupt the native gesture when not in HomeScreen mode and be very disruptive to non iOS users

**Comment by brian-kephart** [comment]
What about something implemented conditionally, like the use of `window.navigator.standalone` in [this article](https://www.netguru.co/codestories/few-tips-that-will-make-your-pwa-on-ios-feel-like-native)?

And really, this issue is about navigation, not necessarily swipe, and it can be solved in other ways. For instance, a back button could be added to the app in standalone mode.

**Comment by benhalpern** [comment]
Closing this, as the native app is now the primary replacement for janky iOS PWA.

PWA fans can take heed that we are still primarily a web app and if/when Apple ships new user-friendly PWA features, we're excited to support it.
