### ISSUE TITLE
cannot access to my Dev.to account

### ISSUE THREAD

**Issue by shefalibasu** [thepracticaldev/dev.to#7693]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by Rafi993** [comment]
Is this related to github signin?

**Comment by shefalibasu** [comment]
No, It is related to DEV.To signin.
I am unable to log in my account.

*Thanks & Regards*
*Shefali Basu*
*Technical Writer*
*Facebook <https://www.facebook.com/shefali.basu.7906>|Twitter
<http://twitter.com/shefali_basu>|LinkedIn
<https://www.linkedin.com/in/shefali-basu-0ba09030/> *

**Comment by rhymes** [comment]
Hello @shefalibasu, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
