### ISSUE TITLE
"Github username has already been taken" validation error message being shown when trying to save (unrelated) changes to profile

### ISSUE THREAD

**Issue by blairnangle** [thepracticaldev/dev.to#77]
Upon trying to save my profile after making changes unrelated to GitHub, I am being shown "Github username has already been taken". The change could be updating email, adding text to "Currently learning" section, etc.
![screen shot 2017-08-15 at 09 51 38](https://user-images.githubusercontent.com/8478158/29308882-620cf6e0-819f-11e7-833b-aed8e82ca448.png)

**Comment by Zhao-Andy** [comment]
Thanks for the heads up. This is a bug on our end and we'll be fixing it soon. I can fix this manually for now; could you send an email to yo@dev.to to continue this?

**Comment by Einenlum** [comment]
@Zhao-Andy I have the same issue here. Is it supposed to be solved by now?

**Comment by mmarinez** [comment]
@Zhao-Andy Hello , Im having this same issue, I though it was something I was doing wrong, should I send you an email aswell?

**Comment by jessleenyc** [comment]
@mmarinez an email to yo@dev.to would be great, thanks! Please be sure to include the github & twitter usernames and the emails associated w/ each. @Zhao-Andy

**Comment by nadif-hasan-purno** [comment]
I am currently facing this issue.
