### ISSUE TITLE
Adapt dev env for developing on a remote box

### ISSUE THREAD

**Issue by ledestin** [thepracticaldev/dev.to#7706]
**Is your feature request related to a problem? Please describe.**

I use 2 computers for development. Using Mac as a desktop and Linux as a dev env. I've adapted dev.to to work in my circumstances and would like to contribute those changes.

**Describe the solution you'd like**

1. Update docs to mention that `APP_DOMAIN` variable must be configured. But I have no idea where to put that in the docs.
2. Wepback should run as `./bin/webpack-dev-server --listen-host 0.0.0.0 --host 0.0.0.0`. I'd like to update `Procfile.dev`.

**Describe alternatives you've considered**

**Additional context**

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @ledestin! 

Thanks for the proposal!

`APP_DOMAIN` is in the configuration file, so you might want to add a similar note about how to configure it for a remote box in each of the three guides: https://docs.dev.to/installation/mac/, https://docs.dev.to/installation/windows/ and https://docs.dev.to/installation/linux/

Regarding `Procfile.dev`, as already bind the web server to `0.0.0.0` for local development (since #6147), it should be okay to bind the JS server as well too. 

(cc @jdoss)

**Comment by ledestin** [comment]
@rhymes thanks! One more thing: when developing docs, a change to `docs/.gitdocs.json` is also needed. I guess, it's not possible to use `APP_DOMAIN` there. Also, I'm not sure if it's a good idea to mention that change in the docs.

**Comment by rhymes** [comment]
What problems are you encountering with gitdocs?

**Comment by ledestin** [comment]
It's just that it listens on localhost by default.

**Comment by rhymes** [comment]
I think we can change that, I looked into [gitdocs configuration params](https://github.com/timberio/gitdocs/blob/master/docs/api/config-file.md) and we can change both host and port. 

I tried locally by setting the host to `0.0.0.0` and it seems to be working:

```text
❯ Starting local development server
❯ [✓] Syntax loaded
❯ [✓] Static assets loaded
❯ Generated and hydrated manifest
❯ [✓] Docs are live at http://0.0.0.0:8000
```

![Screenshot 2020-05-10 at 6 23 14 PM](https://user-images.githubusercontent.com/146201/81504761-62c0e500-92eb-11ea-82e9-fe0d2843f257.png)

don't know if it'll work from Docker as well

**Comment by ledestin** [comment]
@rhymes oh cool, thanks! I'm not using Docker, so I'd like to leave Docker compatibility out for now.

**Comment by maestromac** [comment]
Should this be closed since it's partially resolved?

**Comment by ledestin** [comment]
I think so, closing.

**Comment by ledestin** [comment]
There's a problem with `gitdocs serve`. Currently, it doesn't fully work in my setup with `host` set to  `0.0.0.0` in `docs/.gitdocs.json`. I can do the same as in #8232. I'd like not to write the same code in JS, but extract the code that deals with `APP_DOMAIN` host extraction, and call it from `.gitdocs.js` to set `host` on the fly.
https://github.com/thepracticaldev/dev.to/blob/master/.gitdocs.js
