### ISSUE TITLE
Editing an article throws a 500

### ISSUE THREAD

**Issue by buntine** [thepracticaldev/dev.to#771]
## Bug Report

Trying to edit an article throws a 500. I am logged in (and have tried signout+signin). The article in question is: https://dev.to/buntine/the-balanced-ternary-machines-of-soviet-russia

I've tried to edit some other articles and they appear to work correctly.

### Current Behavior

Visiting the edit URL causes a 500: https://dev.to/buntine/the-balanced-ternary-machines-of-soviet-russia/edit

### Expected Behavior

A 200!

**Comment by benhalpern** [comment]
Hmm something we changed in frontmatter parsing broke this. Fixed for the post. Will investigate for other ones.
