### ISSUE TITLE
Dev.to Doesn't work in Microsoft Edge

### ISSUE THREAD

**Issue by Computer-Man497** [thepracticaldev/dev.to#7726]
**Describe the bug**
Alright, this might be a waste of time because I know Edge doesn't work with a lot of stuff, but maybe their might be a way to fix It in the dev.to code.
 Basically, when I log onto Dev from Microsoft Edge. I see this:
<img width="950" alt="Capture" src="https://user-images.githubusercontent.com/47247405/81315113-cb0c8e00-9081-11ea-9bb0-c17453c6771e.PNG">
No feed, my profile picture is not shown and when I go to try and write a post, their is no post button.

**To Reproduce**
1. Clear all web cookies, history, extensions etc...
2. Open up `dev.to` in the search bar
3. Login

**Expected behavior**
It should act like every other browser such as Brave, Chrome etc...

**Screenshots**
Above screenshot should be suitable enough

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Microsoft Edge
- Version: 44.18362.449.0

**Additional context**
Again, I'm not sure if it is possible to fix from DEVs side but it may be worth a shot if possible. Sorry if I wasted anyone's time with this issue.

**Comment by rhymes** [comment]
Hi @Computer-Man497, DEV doesn't support the older version of Edge, only "Edge Chromium" (which is still called Microsoft Edge, but starts from version 80 upwards).

See https://www.theverge.com/2019/11/4/20942038/microsoft-edge-chromium-release-date-new-logo-features

Thanks for taking the time to file this issue!

**Comment by Computer-Man497** [comment]
Great, Thanks @rhymes!
