### ISSUE TITLE
Blacklist certain tags

### ISSUE THREAD

**Issue by web2033** [thepracticaldev/dev.to#7748]
I would suggest adding a feature that allows blacklisting certain tags to keep feed relevant.

Example - I'm Vue.js dev and not interested in React, Angular, Svelte, etc, but they occupy feed space since all of them use "javascript" tag in articles.

**Comment by rhymes** [comment]
Hi @web2033, thanks for taking the time to raising this issue.

I'm closing this as there's already a discussion around https://github.com/thepracticaldev/dev.to/issues/1856

Feel free to weigh in with your thoughts so that that issue will bump up again :)

**Comment by rhymes** [comment]
Duplicate of https://github.com/thepracticaldev/dev.to/issues/1856
