### ISSUE TITLE
The scrollbar is little weird in the user profile

### ISSUE THREAD

**Issue by yg** [thepracticaldev/dev.to#7749]
**Describe the bug**

The scrollbar is little bit weird in the user profile for small screens

**To Reproduce**

1. Open fulfilled user profile (https://dev.to/ben)
2. If your screen is big zoom the profile

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/61746440/81465147-6407ea00-91e5-11ea-9ef8-882eef2a977b.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 19.04
- Browser: Chrome Beta
- Version: 83.0.4103.23 (Official Build) beta (64-bit)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by awasum** [comment]
@yg ..Are you still facing this issue? I have opened a sample profile on Mobile Web Browser and don't seem to find this problem. Please can you provide more details so we understand and see if we can work on this issue? CC @jacobherrington . I will be able to see if I can help fix this when I understand or can replicate this issue. If you not facing this issue again..Maybe we can close it?

**Comment by yg** [comment]
This is working fine now @awasum 🎉

**Comment by awasum** [comment]
If that is the case, then you can close this issue @yg . Thanks for the prompt reply.
