### ISSUE TITLE
If edit org fails it redirects to the org creation page

### ISSUE THREAD

**Issue by yg** [thepracticaldev/dev.to#7750]
**Describe the bug**

If edit org fails it redirects to the org creation page

**To Reproduce**

1. Open Org settings
2. Try changing the username that already exists
3. You will be redirected to the org creation page with error

**Screenshots**

https://www.loom.com/share/07217b93db4f4daf9c9966ee4644277a

**Desktop (please complete the following information):**

- OS: Ubuntu 19.04
- Browser: Chrome Beta
- Version: 83.0.4103.23 (Official Build) beta (64-bit)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).
