### ISSUE TITLE
I'm unable to upload any images into any post i write

### ISSUE THREAD

**Issue by Obsiye** [thepracticaldev/dev.to#7754]
**Describe the bug**

I'm unable to upload any type of image of any size.

I get no error response.

I'm unable to upload any type of image of any size. I've tried small images far less than 4096x4096 pixels and I've tried images that are  4096x4096 pixels. Also, I get no error response.

**To Reproduce**

Create a post, go to images on the bottom left corner, which will redirect you to a page to upload files. Upload a local .jpg or .png image file.

Then click done.

**Expected behavior**

You'll be redirected to the post (in edit form as expected) but there will be no image.

I expected there to be an image link or image embedded into the post.

**Screenshots**
The image is after i've "uploaded" one
![deverror](https://user-images.githubusercontent.com/25043924/81473138-7c333580-91f4-11ea-840e-4f6b8e343aab.png)

**Desktop (please complete the following information):**

- OS: Microsoft
- Browser: Chrome
- Version: Version 81.0.4044.138 (Official Build) (64-bit)

To note:

I've tried creating new posts but the issue persists. I've tried using incognito mode on chrome but to no avail.

I've tried using a link text e.g. "![]()" and that brings back a default broken image icon.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @Obsiye, I just tried with that editor and I was unable to reproduce (the upload went through successfully). Could you try again? To make sure it wasn't a temporary problem?

**Comment by Obsiye** [comment]
Hi @rhymes , I tried again - on and off incognito mode - and it's still not uploading anything or providing me with a link to add to the post. : / The whole issue persists for me even when I create a new post. Yep, still an issue.

**Comment by rhymes** [comment]
@Obsiye sorry to hear that, any info in the JavaScript console which might help us understand what's going on?

**Comment by Obsiye** [comment]
@rhymes Nothing on the console. ✔️ Good news! It's fixed now. My network calls were slow, at the bottom of the network tab called image upload, it was in (pending) mode. 

My misunderstanding, I thought I had to click the 'Done' button to upload it. Instead, I have to **wait** after choosing a file. Especially images that are larger, it'll take longer.

Maybe have a warning label underneath it saying, "Wait for the image to upload before clicking done"

**Comment by rhymes** [comment]
Thank you! We'll make a note about that certainly!

Glad it's working now
