### ISSUE TITLE
Unable to save / update profile & Follow topics not working

### ISSUE THREAD

**Issue by techzax** [thepracticaldev/dev.to#7757]
**Describe the bug**

Hello,
I have been trying to update my profile since weeks, but each time i get a very irritating message.
Somehow, the update profile thing isnt working at all... 

Also neither is the FOLLOW feature seems to work, every time i follow a topic, after refreshing the page its still unfollowed.
Please help.

**To Reproduce**

On updating profile

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by techzax** [comment]
![image](https://user-images.githubusercontent.com/65107175/81495528-7578f100-92ce-11ea-9878-0bf6dd5e9a63.png)

**Comment by rhymes** [comment]
Hello @techzax, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
