### ISSUE TITLE
Unable to save my profile edits

### ISSUE THREAD

**Issue by Marigameo** [thepracticaldev/dev.to#7758]
I tried to edit my profile settings and noticed 500 status in the console.I was new to dev.to.After a couple of attempts I tried to save without editing the username field, it worked.

If this is the case, then why the username field is editable?It shouldn't be right?

So I think the username field can be disabled if it's value is taken from the social signup and not alterable.

Thank you!

**Comment by rhymes** [comment]
@Marigameo could you expand on the title? What errors do you receive from the web app? Do you see anything logged in the console?

Thank you!

**Comment by Marigameo** [comment]
Sorry @rhymes ,I was new to dev.to and thus didn't realise that the report was getting posted this way from the site.

I have edited my comment and hope it helps someway now.Please consider this one, if I'm correct this could be an important one to consider.

Thank you!

**Comment by rhymes** [comment]
Hi @Marigameo, your username is changeable yes, you can't change it to someone else's but you can always change it :-)

Is this - https://dev.to/marigameo - your DEV profile?

**Comment by Marigameo** [comment]
Yes,that's my DEV profile.
I think white is not allowed.But it didn't show me any exception or warning like white space is not allowed.You might have handled that I think.Not sure, but now tried saving with some other name it is working.

**Comment by rhymes** [comment]
Yeah, white space is not allowed. I was able to reproduce the error locally. I'll send a fix as soon as possible. Thank you!
