### ISSUE TITLE
Allow Siteconfig to force all cover images to appear in homefeeds

### ISSUE THREAD

**Issue by leewynne** [thepracticaldev/dev.to#7766]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

As a smaller community that requires a more visual homefeed. I would like to be able to tick a box that will force the cover image to show within the feed. 

**Describe alternatives you've considered**

None, I think manually setting it works best.

**Additional context**

Only to say hi Dev team! Hope that you are well.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by benhalpern** [comment]
I think adding a `SiteConfig` of `feed_image_preference`.... Where the default is `top_card_cover_image`, and we could have additional options of `all_card_cover_image`, `no_card_cover_image` to round out the set. And then if we come up with other variants then we can add those as other options.

How's that sound?

**Comment by leewynne** [comment]
It sounds bloody brilliant!
