### ISSUE TITLE
Force clear the cache for new users

### ISSUE THREAD

**Issue by ludwiczakpawel** [thepracticaldev/dev.to#7789]
Looks like user needs to hit hard refresh to see new styling on first load
https://imgur.com/MlfmndE

**Comment by rhymes** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.

**Comment by benhalpern** [comment]
I'll get this fixed now

**Comment by benhalpern** [comment]
Fixed with #7795
