### ISSUE TITLE
Draft version for published articles

### ISSUE THREAD

**Issue by shimmoril** [thepracticaldev/dev.to#78]
I've got a glossary article that I'll be updating over time, but I'm a compulsive editor and reviewer, so I don't want my changes to apply to the live version until I'm satisfied. 

In the meantime, I created a new unpublished article to tweak and edit, and then I just copy the markdown over to the published version and save it there.

**Comment by Zhao-Andy** [comment]
Hey @shimmoril, thanks for the feedback! We'll be doing a major overhaul of the editor in the future that will include this feature. Closing since we have this in consideration already.
