### ISSUE TITLE
New update breaks Dark Mode and profile popup

### ISSUE THREAD

**Issue by VladimirMikulic** [thepracticaldev/dev.to#7801]
Hi!

I've noticed a big layout change published a few hours.
I guess it's a new DEV layout. (it's good btw :)

Unfortunately, the dashboard/welcome page uses light theme although I have dark mode enabled.
Articles and other DEV pages adjust colours for dark mode, but dashboard remains light.

Is it intentional or is it a bug? 

The second issue is that hovering the profile icon from the dashboard doesn't display a popup.
Again, it works on the other pages. Just like the dark mode.

I've cleared my cache but it doesn't resolve the issue.

[Video](https://streamable.com/ebdexb) is worth a thousand words :)

**Desktop**

- OS: Kubuntu 20.04 LTS
- Browser: Chrome
- Version: 81

Thank you, Vladimir.

**Comment by maestromac** [comment]
Hello @VladimirMikulic , can you give it a try again to see if this issue is still persisting? I switched to dark mode and was unable to reproduce this.

**Comment by VladimirMikulic** [comment]
@maestromac that's strange. The issue is gone now! I've no idea what happened.

**Comment by maestromac** [comment]
@VladimirMikulic that's good to hear! This is because the asset wasn't available/properly loaded yet after the update. Tends to go away after a little bit.
