### ISSUE TITLE
Flare tag text vertical alignment

### ISSUE THREAD

**Issue by Glennmen** [thepracticaldev/dev.to#7808]
**Describe the bug**

The text in a flare tag (I believe that is the correct name for it) isn't vertically aligned anymore. I believe this is because of the font change.

**To Reproduce**

1. Go to home feed
2. Scroll to you find a post with a flare tag

**Expected behavior**

Text should be nicely centered.

**Screenshots**

![image](https://user-images.githubusercontent.com/11406433/81742526-8b3e1000-94a0-11ea-89ae-498af7bced03.png)

**Desktop (please complete the following information):**

- OS: MacOS 10.15.4
- Browser: Brave
- Version: 1.8.95 (Chromium: 81.0.4044.138)

**Additional context**

**Comment by rhymes** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.
