### ISSUE TITLE
Error 429: too many requests in the Follower page when checking multiple users

### ISSUE THREAD

**Issue by reiallenramos** [thepracticaldev/dev.to#7815]
**Describe the bug**

When you're viewing your Follower list, a button is shown beside people who you already follow back. Then when you click it, it scrolls to the top of the page because of `href="#"`

Edit: Did some further investigation: for every user in the Follower page there is a corresponding network call to check if that person is followable or not. Depending on the response, the button is supposed to say 'Follow Back' or 'Following'. But performing a lot of network calls to the same endpoint (cant quantify "a lot" yet) apparently chokes the server and returns error 429 (too many requests)

![Screenshot from 2020-05-13 22-00-35](https://user-images.githubusercontent.com/26242729/81823118-89d71b00-9566-11ea-8a86-9209b21327e9.png)

**To Reproduce**

1. Go to https://dev.to/dashboard/user_followers
2. Find anyone who you follow back

**Expected behavior**

It shouldn't be shown

**Screenshots**
![dev_to_followers_button](https://user-images.githubusercontent.com/26242729/81771908-ea3e6c00-9516-11ea-8c95-11825d873b86.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04
- Browser: Chrome
- Version: 81.0.4044.138 (Official Build) (64-bit)

**Additional context**

Unless this was by design, I suggest we should remove it.
Edit: We dont need to remove it. Instead do something about the too many requests response

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by reiallenramos** [comment]
I'll work on it 👌

**Comment by rhymes** [comment]
@reiallenramos cool, I'll assign you to it!

**Comment by atsmith813** [comment]
Hmmm I thought #7676 was supposed to address this. Is it still happening? Or is this different?

**Comment by atsmith813** [comment]
Closing out in favor of the conversation on https://github.com/thepracticaldev/dev.to/pull/7839
