### ISSUE TITLE
Tags kerning & vertical alignment

### ISSUE THREAD

**Issue by ludwiczakpawel** [thepracticaldev/dev.to#7817]
"the tags are... kerned? too close to the article title on Safari, which definitely looks weird."

[source](https://dev.to/wrldwzrd89/comment/op88)

[https://github.com/thepracticaldev/dev.to/issues/7808](https://github.com/thepracticaldev/dev.to/issues/7808)

**Comment by rhymes** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.
