### ISSUE TITLE
Test reporting 

### ISSUE THREAD

**Issue by snackattas** [thepracticaldev/dev.to#7830]
# **Is your feature request related to a problem? Please describe.**
Across dev.to's rspec test suite, there is some flakiness. However, it's not easy to get a feel for the trend of what's failing.  It would be really helpful if we had some way to aggregate test results across different test runs, to analyze the health of the suite as a whole. 

That would enable us to:
* Systematically tackle flakiness, in the areas that need it most. Then, when the flakiness is tackled, you'd be able to see the difference in your efforts, and feel great! Converting a spec that has a 5% failure rate across 150 runs to having a 0% failure rate is a great feeling :)
* Make the suite faster! Doing this sort of monitoring allows us to tackle the longest running tests first

# **Describe the solution you'd like**
I have thought of 3 possible solutions:

### 1. Send csvs of a run's test times to an s3 bucket (easiest option). The steps:
*  Write a simple custom [RSpec Formatter](https://ieftimov.com/post/how-to-write-rspec-formatters-from-scratch/) that detects if we are in the travis environment, and if we are, it would save test runtimes, test pass/fail, the travisci link, the exception, etc, to a csv file.
* At the end of the run, the csv would be [sent up to an s3 bucket](https://docs.travis-ci.com/user/uploading-artifacts/) that the dev.to core team configures
* The core dev.to team could have a script that pulls down the csvs, combines them into 1 csv for easy analysis

### 2. Configure and deploy a [ReportPortal instance](https://reportportal.io/). 

* I have some experience configuring these, they are pretty simple.  I don't think it would make sense to have this hosted on Heroku, ReportPortal is Docker first so we could deploy it ourselves, and it's a very low maintenance kind of server to run. 

* There is a [gem](https://github.com/reportportal/agent-ruby) we could use to send data to ReportPortal 

* Definitely try the [demo](http://web.demo.reportportal.io/ui/#login) (creds are default/1q2w3e). Here's a gif of me creating a Flaky test dashboard. These are VERY useful for at a glance identifying which tests are the most flaky
![2020-05-13 13 24 10](https://user-images.githubusercontent.com/12533693/81851137-9cc5fd00-951e-11ea-8b76-c1d79bc9125e.gif)

### 3. Use [TestRail](https://www.gurock.com/testrail/). 

* I don't have much experience with TestRail, it's not free though. I would love it if the people who have experience with TestRail add a comment here describing their experience? Was it easy to manage the test cases? 

* It would be VERY simple to set up a repo with TestRail, we could set it up with [this gem](https://github.com/dmitryzuev/rspec-testrail)

* We likely would only be using a slice of its features, only its test tracking and reporting capabilities, not really any of the test case management

**Comment by mstruve** [comment]
Since we are already sending failed screenshots from Travis to S3 I would say option 1 would be the easier and quickest to implement. 

I also started this Epic a while ago to log flaky specs. #4884

**Comment by rhymes** [comment]
Awesome idea, my vote goes to option 1 as well for now.

@mstruve @snackattas would it be possible/doable to eventually integrate option 1 with Datadog?

AFAIK we do have build times on there, but we don't have "test suite running times" and all the other information these formatters are going to collect.

See also my old issue: [Track tests and overall builds time over time](https://github.com/thepracticaldev/dev.to/issues/6232).

**Comment by mstruve** [comment]
Honestly, I think our CI should take care of this. In the past, I have used CircleCI, and all of these kinds of reporting and stats features were available directly in the tool. I think lots of CI/CD providers have that kind of insight built-in.

**Comment by mstruve** [comment]
@rhymes you want to close that issue since we do track times and top level stuff and now that we have this one?

**Comment by mstruve** [comment]
Since we have CSVs now and KnapsackPro for timing, @snackattas should we close this?

**Comment by snackattas** [comment]
Ok I'm fine closing it. The csv solution is sort of annoying but it gets the job done.  Maybe down the line I'll commit my csv combining and parsing script to the repo so that others can do this exercise as well
