### ISSUE TITLE
Replace all hardcoded Twitter Hashtags with the twitter_hashtag site config variable

### ISSUE THREAD

**Issue by Ridhwana** [thepracticaldev/dev.to#7835]
In [this issue](https://github.com/thepracticaldev/dev.to/issues/7254) and [this PR](https://github.com/thepracticaldev/dev.to/pull/7573) the twitter hashtag site config variable was added. 

The next step is to now replace all hardcoded #DEVCommunity references with this dynamic option.

**Comment by Ridhwana** [comment]
To our amazing contributors: This issue is labeled as ready for dev, so it's up for grabs.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

**Comment by icncsx** [comment]
@Ridhwana If this is not taken already, I can take this!

**Comment by lightalloy** [comment]
@icncsx you're welcome to work on this issue :sparkles:

**Comment by icncsx** [comment]
@lightalloy please see the relevant [PR](https://github.com/thepracticaldev/dev.to/pull/7895). 
@Ridhwana thank you for linking the relevant PR and issue.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/7895
