### ISSUE TITLE
Stackbit integration UI is a bit off when active

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#7843]
**Describe the bug**

This is how it looks when the integration between DEV and Stackbit is activated:

![Screenshot_2020-05-14 Settings - DEV Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/81908161-2500dc80-95c9-11ea-9331-3fb0ff8ccd1e.png)

**To Reproduce**

1. Activate the Stackbit's integration on https://dev.to/settings/integrations
1. Go back to https://dev.to/settings/integrations to see the UI

**Desktop (please complete the following information):**

- OS: macOS 10.14.6
- Browser: Firefox
- Version: 77

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by Amorpheuz** [comment]
I would like to take this up! Should I just fix the wonky-ness? or an improved look would be felt welcome? I would love to discuss it if so!

**Comment by Amorpheuz** [comment]
Noticed changes in the Stackbit UI while checking out GitHub integration. Not sure if fixed or still needs changes.

**Screenshot:**
![image](https://user-images.githubusercontent.com/22113778/83047567-2bca2d80-a066-11ea-81ff-13366797bdb7.png)

**Desktop:**
OS: Windows 10
Browser: Firefox Developer Edition and Edge Chromium
Version: 77.09b and 83 respectively

**Comment by rhymes** [comment]
Fixed by https://github.com/thepracticaldev/dev.to/pull/8026

Thanks @Amorpheuz!
