### ISSUE TITLE
Snapshot testing in component displaying time fails locally but succeeds in github

### ISSUE THREAD

**Issue by Rafi993** [thepracticaldev/dev.to#7853]
**Describe the bug**
Snapshot testing in component displaying time fails locally but succeeds in github.

**To Reproduce**
1. run yarn
2. yarn test
3. The test will fail

I suspect this has something to do timezone or timeformat of the local system.

**Expected behavior**

The test should pass
**Screenshots**

![failing_test](https://user-images.githubusercontent.com/8092120/81958772-13045580-962c-11ea-8dbc-2e8ac14bcd3e.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04
- Browser: Brave
- Version:

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by Rafi993** [comment]
Hi there, If this issue is up for grabs I would like to help.

**Comment by Ridhwana** [comment]
@Rafi993 We've redone a lot of the frontend tests this past week as part of the upgrade to Preact X. In the process we've removed some of the snapshots including this one, and replaced them with unit tests. This issue would be obsolete once that PR gets merged in the next day or two, hence I would advise that we close it instead of working on fixing it since the PR is so close to being merged :)

**Comment by Rafi993** [comment]
> @Rafi993 We've redone a lot of the frontend tests this past week as part of the upgrade to Preact X. In the process we've removed some of the snapshots including this one, and replaced them. This issue would be obsolete once that PR gets merged in the next day or two, hence I would advise that we close it instead of working on fixing it since the PR is so close to being merged :)

Awesome
