### ISSUE TITLE
Remove an old issue solvef

### ISSUE THREAD

**Issue by allnulled** [thepracticaldev/dev.to#7881]
I could not write POSTS into your site because you banned me for criminalizing paid universities for saying that, if they were free, COVID-19 would be erradicated at this time already.

YOUR SITE REDIRECTED ME to here in order to share my case.

I would like you to remove this past issue.

And if you could, this one too.

And, by the way, ask you for unbaning me, to be able to write posts again in your site.

I do not know what you have against me. Are you a paid university or something?

Whatever, this was the issue:

[https://github.com/thepracticaldev/dev.to/issues/7641](https://github.com/thepracticaldev/dev.to/issues/7641)

Thank you.

**Comment by rhymes** [comment]
As mentioned in https://github.com/thepracticaldev/dev.to/issues/7641#issuecomment-622405052 the github repo is not the place to appeal on customer support issues, please contact yo@dev.to if necessary.
