### ISSUE TITLE
Liquid syntax error: Tag '{% raw %}' was not properly terminated

### ISSUE THREAD

**Issue by setevoy2** [thepracticaldev/dev.to#7898]
After trying to publish a new post imported via RSS last time - got the "Liquid syntax error: Tag '{% raw %}' was not properly terminated" error:

![Screenshot_20200516_155209](https://user-images.githubusercontent.com/7965314/82120313-c3d63600-978d-11ea-9580-a43402df9294.png)

https://dev.to/setevoy/helm-helm-secrets-sensitive-data-encryption-with-aws-kms-and-use-it-with-jenkins-4bnf-temp-slug-7499446?preview=8575b976dd6763a784936d7443d78aff3cbd60338b0a15e82514d0b84c60b1d028c7a7d88ca17d8a811516eebe6c777ffbee393cfd8eee721bf71001

Can we please deal somehow with the `{ }`?

**Comment by rhymes** [comment]
hi @setevoy2, could you please share the the markdown of the article in a gist file? https://gist.github.com/

this way we can debug what's going on.

Thank you!

**Comment by setevoy2** [comment]
Hi, @rhymes.
Here it is: https://gist.github.com/setevoy2/7078baba2f1176104498d49732e6cfa8
Thanks for your time!

**Comment by rhymes** [comment]
@setevoy2 I believe the error lies here:

<img width="1417" alt="" src="https://user-images.githubusercontent.com/146201/82139269-ecf6d500-9826-11ea-8aff-f6aaa81942c3.png">

the backticks with the `curl`.

If you remove those the article renders. 

I tried to render it as markdown in github too and, although it doesn't break, it has rendering issues as well there:

![Screenshot_2020-05-17 gist 6dcc4647bb4478b9eae4ff6de29c670b](https://user-images.githubusercontent.com/146201/82139326-3b0bd880-9827-11ea-94e3-6999bb016d21.png)


@maestromac as I had to debug this manually from `parsed_markdown.finalize` inside `ArticlesController#preview` to find out what was going on, do you think there's a way we can better surface this error to the reader? `.finalize` here breaks and returns the error message, then the error get inside the html and doesn't bubble up as an error but gets rendered in the body, escaped and stripped of tags, which also hides a useful information. I can write up an issue about it:

<img width="1082" alt="Screenshot 2020-05-17 at 10 18 59 AM" src="https://user-images.githubusercontent.com/146201/82139416-e9178280-9827-11ea-9209-11b53da91b45.png">

which isn't that clear either but it allowed me to save the processed_html on disk and then look for that `{% </a> raw %}` manually and figure out at which line it corresponded... :-(

**Comment by setevoy2** [comment]
Thanks, @rhymes 
For now, I've solved this by importing the post from the Medium RSS, so it's kind of solved.
The problem is that I'm posting to Dev.to from my blog much more often than posting to Medium, and last few times were issues with the brackets, so it will be great to solve it somehow, or at least display the cause somehow so I can fix it myself.

**Comment by maestromac** [comment]
@rhymes I created something similar https://github.com/thepracticaldev/dev.to/issues/1511 but definitely create a new one if it's unrelated
