### ISSUE TITLE
Visiting async_info endpoint redirects to sponsors page

### ISSUE THREAD

**Issue by yg** [thepracticaldev/dev.to#7899]
**Describe the bug**

Visiting [async_info](https://dev.to/async_info) endpoint redirects to sponsors page and user avatar is hidden and dark mode is disabled

**To Reproduce**

1. Load dev.to ones (if not we can't reproduce)
2. Log in to dev.to
3. Visit https://dev.to/async_info
4. You will be redirected to Sponsors page
5. And user avatar is also hidden and dark mode is disabled

**Expected behavior**

Showing 404 or some other status will be fine

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/61746440/82120477-0d318000-97a4-11ea-9413-17080faf5265.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 19.04
- Browser: Chrome Beta
- Version: 83.0.4103.44 (Official Build) beta (64-bit)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
This looks specific to DEV in production, as I can't reproduce it locally. There might be some dynamic redirection in the admin.

**Comment by maestromac** [comment]
Thank you for reporting this! 

This is resolved
