### ISSUE TITLE
Error when sending email via /internal/users

### ISSUE THREAD

**Issue by pkfrank** [thepracticaldev/dev.to#7900]
**Describe the bug**
I hit a spinning robot error after trying to send an email via `/internal/users`

**To Reproduce**
- Open `/internal/users/{user-id}`
- Fill out email form
- Click "send email"
- Land on `internal/users/{user-id}/send_email`
- See spinning robot

**Expected behavior**
- Email sends properly, confirmation message is shown

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by pkfrank** [comment]
This has been resolved.  Closing the issue.
