### ISSUE TITLE
Backtick markdown not working

### ISSUE THREAD

**Issue by anzuj** [thepracticaldev/dev.to#7906]
**Describe the bug**
I'm writing an article about Vuetify's grid system, but when I try to include examples in the post, backticks don't work as intended. and instead of showing the code, there's just ``  

**To Reproduce**
1. Make a post including this markdown: [text.txt](https://github.com/thepracticaldev/dev.to/files/4640826/text.txt)
2. See preview. 
3. See if the code in the 2nd bullet is marked down correctly  `<v-col cols="12" sm="6">`

**Expected behavior**
`<v-col cols="12" sm="6">` appears marked down as code in the post

**Actual behavior**
`<v-col cols="12" sm="6">`  appears as `` in the post

**Screenshots**
Post editor:
<img width="535" alt="post1" src="https://user-images.githubusercontent.com/36598337/82157540-64a61d80-9882-11ea-9d63-250f2e17572d.png">
Preview:
<img width="521" alt="post2" src="https://user-images.githubusercontent.com/36598337/82157541-67a10e00-9882-11ea-9547-de005709a40a.png">

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: Version 81.0.4044.138 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by Ridhwana** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by Ridhwana** [comment]
Hi @anzuj thanks for the issue, I just did a quick test and it seems like escaping your < sign will yield the correct the behaviour so that you can continue writing your article. 
i.e. 
* 2 `v-row` elements make sure the cards are above each other
* Main card takes up the whole screen width on XS (\<600px) screen sizes, but scales down to half width of its parent `v-row` thanks to this: `<v-col cols="12" sm="6">`

**Comment by anzuj** [comment]
@Ridhwana thank you so much for a quick reply! I really did not know to assume that the < was the culprit! Thank you so much, adding \ did the trick. This can be closed I guess :)
