### ISSUE TITLE
Dev.to articles should have contributors functionality 

### ISSUE THREAD

**Issue by krishnadevz** [thepracticaldev/dev.to#7909]
In Dev.to now hackathon is started so some folks are working alone or some are working in teams so for that dev can have add contributors thing like GitHub is having so both members can add and contribute to articles according to their own work in project/hackathon. and hello ben and other developers please think about  I think this is helpful for many folks.
Like this 🔽

![Annotation 2020-05-18 102213](https://user-images.githubusercontent.com/42638797/82175413-783c9d00-98f1-11ea-8909-671d6722927e.png)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @krishnadevz, would this be similar to this https://github.com/thepracticaldev/dev.to/issues/1299 ? The ability to add multiple authors to a post?

**Comment by krishnadevz** [comment]
yes I suggested same feature thankyou @rhymes

**Comment by rhymes** [comment]
Going to close this in favor of that one, then, please feel free to leave your thoughts there! Thank you!
