### ISSUE TITLE
importing hugo posts via RSS, images not working

### ISSUE THREAD

**Issue by paulczar** [thepracticaldev/dev.to#7918]
**Describe the bug**

I set up my dev.to account (paulczar) to import from my blog ( https://tech.paulcz.net/index.xml ) via its RSS, and everything seems to be working fine apart from images.

When I go to the dashboard and preview the post (ex https://dev.to/paulczar/how-to-broadcast-to-twitch-and-zoom-with-obs-2mbn-temp-slug-9435494?preview=753aa106ae275afe5505770a92373267a44ed3ee447411b2f39cb57ac0d90c0b1f45636bd8c7931fc33e1c351ec885d1c04a87ff5d1158e8e26807ae )  I see the text formatted correctly, but the image links are all broken.

I notice the full URL being used by the images is https://res.cloudinary.com/practicaldev/image/fetch/s--meUpGimF--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/v1/obs-basic.png which appears to suggest there's some sort of async process responsible for fetching them?   

**To Reproduce**

set up my blog's RSS feed as a input source

**Expected behavior**

Images should load correctly

**Comment by atsmith813** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by maestromac** [comment]
Hello @paulczar . This is happening because your image's source is pointing directly at a document of the same path, ie `<img src="circle-add-project.png" alt="add project" />`.  

While I'm making the change in our feature to account for that, you should update your feed to use the complete image path to support other RSS readers. I used Feedbro extension to examine your feed and it also does not render your image.
