### ISSUE TITLE
Publishing from RSS - Ignored newlines

### ISSUE THREAD

**Issue by negue** [thepracticaldev/dev.to#7923]
**Describe the bug**

When I imported the post, it had no newlines any more, the whole topic is squished into one blob.

**To Reproduce**

I used this newly generated rss file: https://negue.github.io/devto.xml

As you see the content itself has newlines, do I need to have a different new-line?  `\r\n` ?

Or is the xml file broken?

**Expected behavior**

To be imported with newlines so that headers and everything else "work" :)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by maestromac** [comment]
Hello @negue , that's because your content is completely in markdown and not HTML. The first thing our RSS importer does is convert content from HTML to markdown. `<p>` tag is generally used to separate one paragraph from the other. It's best practice to use HTML in XML feeds.

**Comment by negue** [comment]
Oh, I see :( ,

I saw multiple articles where the rss import would import the markdown, not the rendered HTML - like https://dev.to/thisdotmedia/how-to-automatically-post-from-your-gatsby-site-to-dev-to-1ff8 

I found out that my content didn't had any `<![CDATA[   ]>` around, I thought this would be the cause of it, but re-importing doesn't work :( .
