### ISSUE TITLE
Why i am unable to submit blog on Dev.To

### ISSUE THREAD

**Issue by shefalibasu** [thepracticaldev/dev.to#7945]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hello @shefalibasu, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
