### ISSUE TITLE
Changing email address makes DEV think I'm a new user

### ISSUE THREAD

**Issue by msfjarvis** [thepracticaldev/dev.to#7947]
**Describe the bug**

I've been using my GMail address with dev.to for a while now, and recently migrated to my domain mail. Moments after I confirmed my new address, I received a welcome email which was decidedly weird but I ignored it. Today, I received a newsletter which I most certainly did not re-subscribe for which makes me wonder if any of my setting were reset due to the email change. I can't see anything that has, aside from the email notifications which I have since disabled.

**To Reproduce**

1. login to dev.to
2. go to https://dev.to/settings/profile
3. change your email
4. confirm it through the link you receive
5. you should receive a welcome email once your new email address is confirmed

**Expected behavior**

Changing account email does not send you a welcome email

**Screenshots**

![image](https://user-images.githubusercontent.com/13348378/82326661-cd180a80-99fa-11ea-8585-ccaa92b503a4.png)

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Google Chrome
- Version: 81.0.4044.138

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hi @msfjarvis, thanks a lot for taking the time to file this bug. Unfortunately it's a known one - https://github.com/thepracticaldev/dev.to/issues/193 - let me know if there's anything different in your use case from the one already reported. 

Please add your description in the other issue as well, so we can make sure all use cases are met.
