### ISSUE TITLE
Make dev.to blog posts refer to stackbit blog post as canonical

### ISSUE THREAD

**Issue by emTr0** [thepracticaldev/dev.to#7972]
**Is your feature request related to a problem? Please describe.**

Currently, all posts on a stackbit blog refer to the dev.to post as the canonical source. If the point of the stackbit blog is to make our own site and the content is ours, the "link juice" should also be ours and the dev.to post should refer to the stackbit blog post. There are already "made with stackbit and dev.to" links in the footer.

**Describe the solution you'd like**

For the dev.to blog post to link to the stackbit blog post instead of the reverse.

**Describe alternatives you've considered**

There are none.

**Additional context**

N/A

**Comment by lightalloy** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled "type: bug" are always up for grabs, but for feature requests, please wait until we add a ready for dev before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our contributors' guide.

**Comment by lightalloy** [comment]
Here is an existing issue with more infomation about implementation #4194

**Comment by emTr0** [comment]
#4194 is pretty much the same. I will add a comment/suggestion for implementation to that issue and close this one. Thanks!
