### ISSUE TITLE
Changing email doesn't work

### ISSUE THREAD

**Issue by davidkudera** [thepracticaldev/dev.to#7974]
**Describe the bug**

Verifying email after it is updated is not working.

**To Reproduce**

1. Sign in with Github
2. Open profile settings
3. Change email address
4. Click on the received verification link
5. Email is not updated and message "You have requested a change to ***. Check your inbox for the verification link to finalize the change." persist.

**Expected behavior**

Changing email should work.

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Browser: Google Chrome
- Version:81.0.4044.138

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by theLastOfCats** [comment]
Same for me

OS: Manjaro
Browser: Mozilla Firefox
Version: 76.0.1

**Comment by citizen428** [comment]
@davidkudera @theLastOfCats Is this still an issue for you? I just changed my email address and got the notification. If I remember correctly we had a minor mail issue last week, maybe that's related?

**Comment by davidkudera** [comment]
I didn't have a problem with receiving the verification email. The problem was that the verification link didn't work. Opening the link did nothing.

But it works now, so thanks.

....... There may still be some issues. I just received a welcome email from dev.to (the same email you receive when you sign up for the first time).

**Comment by citizen428** [comment]
@davidkudera Sorry, I had misread that, but good to know it worked for you now.

Resending the welcome mail is a known issue (see #193) and will hopefully be able to implement a fix soon.

I close this issue now feel free to re-open if this happens to you again.
