### ISSUE TITLE
Add merveilles.town to mastodon instance whitelist

### ISSUE THREAD

**Issue by aadilayub** [thepracticaldev/dev.to#7981]
I was trying to link my mastodon profile to my dev.to account, but got an error saying it wasn't in the list of approved instances. The instance I use is [merveilles.town](http://merveilles.town), a group of creative technologists.

For reference, [here](http://github.com/merveilles/The-town) are the instances' rules and values.

**Comment by rhymes** [comment]
Thanks @aadilayub, sent a PR about it: https://github.com/thepracticaldev/dev.to/pull/7983 :-)

**Comment by aadilayub** [comment]
Thanks @rhymes!

**Comment by dar5hak** [comment]
Hello. I'm here to request another instance to be allowed: https://im-in.space/. It's a small, general-purpose instance with [ethical rules](https://im-in.space/about/more) in place. Can we reopen this?

I was having an email conversation with Michael who directed me here. Thanks.

**Comment by rhymes** [comment]
@dar5hak would you care to open a PR about this? It's simple as adding the hostname to https://github.com/forem/forem/blob/master/app/lib/constants/mastodon.rb

**Comment by dar5hak** [comment]
@rhymes Thanks for guiding. Here we go.
