### ISSUE TITLE
Dev digest email links redirect to the frontpage

### ISSUE THREAD

**Issue by Izkda** [thepracticaldev/dev.to#7982]
**Describe the bug**

All the links in the latest digest (except the "unsubscribe") redirect to the front page with a 301.

**To Reproduce**

1. Click in any of the links (for [example](https://dev.to/ahoy/messages/Zu1pRnpnwUrbLXP0igTErMl7zISLA3ey/click?signature=f99119813761ab2048a32b247db251ef30250be7&url=https%3A%2F%2Fdev.to%2Fbitdweller%2Fstop-setting-the-language-of-your-website-based-on-my-location-31h0%3Futm_source%3Ddigest_mailer%26utm_medium%3Demail%26utm_campaign%3Ddigest_email))

**Expected behavior**

The browser shows the article.

**Desktop**

- OS: Windows 10
- Browser: Firefox 76, Chrome 81, Edge 44

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by mtfoley** [comment]
Not a Ruby expert, but my best guess is this deals with the lack of a controller file.  The unsubscribe link looks like this:
https://dev.to/email_subscriptions/unsubscribe?ut=REALLY_LONG_TOKEN

and this file expects a `ut` parameter for the unsubscribe method:
[email_subscriptions_controller.rb](https://github.com/thepracticaldev/dev.to/blob/master/app/controllers/email_subscriptions_controller.rb)

The digest links look like this:
https://dev.to/ahoy/messages/MESSAGE_ID/click?signature=SIGNATURE&url=URI_ENCODED_ARTICLE_URL

but I'm not seeing a `ahoy_controller_erb` file in the same folder. I'd expect to see one with maybe a `messages` method or something to that effect.

**Comment by atsmith813** [comment]
Fixed with https://github.com/thepracticaldev/dev.to/pull/8018
