### ISSUE TITLE
Textarea overflows in user settings

### ISSUE THREAD

**Issue by Rafi993** [thepracticaldev/dev.to#7994]
**Describe the bug**
Textarea in user settings overflows outside the window

**To Reproduce**
1. Go to https://dev.to/settings in your mobile device
2. Scrolldown to "I'm getting into" section
3. You can see the textarea overflow

**Expected behavior**

Textarea should not overflow outside the window

**Screenshots**
![textarea](https://user-images.githubusercontent.com/8092120/82505394-43ac2980-9b1b-11ea-9cbc-5a11a3a4c92c.png)

**Smartphone**

- Device: Readmi note 6 pro
- OS: Android
- Browser: Brave
- Version: 1.8.112

**Comment by Rafi993** [comment]
The text below the textarea also overflows

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
This also happens in the mobile layout simulator in Firefox desktop
