### ISSUE TITLE
After enabling Ten X hacker theme username/email is hidden 

### ISSUE THREAD

**Issue by krishnadevz** [thepracticaldev/dev.to#7998]
**Describe the bug**
hello
I set my theme to Ten X hacker theme my username is hidden because in default theme my username is everything is white except contents ex:-name and articles but after switching to dark theme my is get mixed with that and then that thing is hidden if you guys let me in I can change CSS color properties for showing text it is just a color property thanks 😊

**To Reproduce**

Go the Profile icon then UX but first your theme is set to the default mode and then switch to Ten X hacker theme and then go and see the difference that's all about how to reproduce.

**Expected behavior**

**Screenshots**
![Annotation 2020-05-21 144847](https://user-images.githubusercontent.com/42638797/82544099-366e5980-9b72-11ea-8cb1-e4f52e3b03c0.png)
![Annotation 2020-05-21 144920](https://user-images.githubusercontent.com/42638797/82544141-4b4aed00-9b72-11ea-84da-f75e917bed68.png)
![Annotation 2020-05-21 144948](https://user-images.githubusercontent.com/42638797/82544171-5867dc00-9b72-11ea-81d3-11e11233755b.png)

**Desktop (please complete the following information):**

- OS:Windows 10 X64
- Browser:firefox 
- Version:76.0.1 (64-bit)

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
@krishnadevz Thanks for the report? Were you planning on fixing this? If yes, please assign yourself the issue and open a PR. If not, this is up for grabs for anyone interested.

**Comment by simskij** [comment]
I can have a stab at this. 👍

**Comment by joshpuetz** [comment]
@simskij This issue was fixed in https://github.com/thepracticaldev/dev.to/pull/8001, closing now!

**Comment by simskij** [comment]
Was it? It looked like they didn’t touch the part this issue is refering to but peripheral issues.

**Comment by joshpuetz** [comment]
@simskij I think there's still room for improvement if you want to give it a go, otherwise I'll keep this issue closed. Thanks much!
