### ISSUE TITLE
Authenticate buttons on Navigation page don't work in Firefox

### ISSUE THREAD

**Issue by shimmoril** [thepracticaldev/dev.to#80]
Neither of these buttons do anything when I click on them:
![image](https://user-images.githubusercontent.com/20954533/29721887-4f007008-8984-11e7-97ea-16959f15540a.png)

I am able to use the grid menu options to sign in:
![image](https://user-images.githubusercontent.com/20954533/29721928-75083b3c-8984-11e7-9df0-80f870d9aa0a.png)

v54.0.1 on a Windows 10 machine.

**Comment by Zhao-Andy** [comment]
Thanks for the heads up; we'll take a look into it.

**Comment by Zhao-Andy** [comment]
Tried reproducing this via our virtual browser tester, but it seems to be working. Will try again on an actual Windows machine. @shimmoril could you tell me if there are console messages in the Mozilla developer tools? Thanks :)

**Comment by shimmoril** [comment]
I'm a bad dev! I omitted the fact that I was in an incognito window at the time, since why would that matter? lol

I just tried it again, and in a normal window the buttons work fine, in incognito, nada.

**Comment by Zhao-Andy** [comment]
Hmm strange! Wonder why it didn't work the first time. Don't think incognito would matter either. Gonna close since I can't reproduce.

Also, you figured it out, so definitely not a bad dev; in fact a good dev! 👍
