### ISSUE TITLE
1 error prohibited this article from being previewed

### ISSUE THREAD

**Issue by chuongtrh** [thepracticaldev/dev.to#800]
### Definition of Done

---

## Bug Report

I'm facing issue when I try to preview post

> 1 error prohibited this article from being previewed

Link issue
[https://imgur.com/a/YeOxhil](https://imgur.com/a/YeOxhil)

**Comment by chuongtrh** [comment]
@rhymes Sure 
You can find a screenshot at here [https://imgur.com/a/T9vH87a](https://imgur.com/a/T9vH87a)

@Zhao-Andy thanks, i try but it's not working

**Comment by Zhao-Andy** [comment]
@chuongtrh If you could send an email to yo@dev.to with your Markdown in the email body, I can test the Markdown and see what's going on.

**Comment by chuongtrh** [comment]
@Zhao-Andy done, please check your inbox

**Comment by jessleenyc** [comment]
Sounds like this got moved to support so closing for now. Feel free to open a new issue if it's still a problem.
