### ISSUE TITLE
Edit not working on Firefox

### ISSUE THREAD

**Issue by vepo** [thepracticaldev/dev.to#8019]
**Describe the bug**

Edition with no contents on Firefox

**To Reproduce**

Using 

1. Create a post
2. Save as draft
3. Edit the post

**Expected behavior**

All contents from the last edition should be available, but there is an empty post.

Everything works fine on Chrome.

**Screenshots**

![image](https://user-images.githubusercontent.com/353569/82580177-31ef7400-9b65-11ea-962b-3bf450e13f6e.png)

![image](https://user-images.githubusercontent.com/353569/82580109-1be1b380-9b65-11ea-962e-8cc1ab83deda.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox
- Version: 76.0.1 (64-bits):

**Additional context**

N/A

**Comment by Ridhwana** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by Ridhwana** [comment]
Hi @vepo, thanks for the issue. I tried replicating it on Firefox Version: 76.0.1  and I am able to save a draft and edit each time. 

I then tried to look open up your post in your screenshot to see if I could see the contents, but it said it was not found. Did I get the correct url - https://dev.to/vepo/selecting-an-open-source-project-to-contribute-3idl-temp-slug-1088277/edit? Can you pop the link to the draft article here please?

**Comment by vepo** [comment]
Hi @Ridhwana  

Yes, you took the correct URL. I tried again and the same error occurs. Then I disable all extension, same error, so the problem is not an extension. Then I tried open in a private firefox (no cache) and it works. So I believe the error is something on the cache.

**Comment by vepo** [comment]
I saw there is a lot of items related to the editor on localStorage. 

![image](https://user-images.githubusercontent.com/353569/82667685-ba761f00-9c0e-11ea-9140-4257b7b36557.png)

**Comment by Ridhwana** [comment]
@vepo thanks, it seems I need your preview url instead of the edit one to access the draft post, can you please pop it here for me :) ?

**Comment by vepo** [comment]
@Ridhwana, I believe I was editing when the application was deployed, so I had an intermediary state for my post (different versions for artifacts). I will cleanup my localStorage later to make it work.

https://dev.to/vepo/selecting-an-open-source-project-to-contribute-3idl-temp-slug-1088277?preview=6efc97c5ea1ae6dd0dd67d5a3d68649ec1a19550192f66ea8454734cf2122d4164ff61b2b3353cfcb55734dd005356fa12bb8be9bd2bdc033aaf86ed

**Comment by citizen428** [comment]
@vepo I use Firefox as my main browser and have never experienced this issue. Did you manage to fix in your end by cleaning out the local storage?

**Comment by vepo** [comment]
Yes, It was an issue from the update process.

**Comment by Ridhwana** [comment]
Thanks for the feedback @vepo. Since this is not replicable and seems to be maybe a timing issue, I'll close this. Thanks!
