### ISSUE TITLE
Utilize multiple issue templates feature of Github

### ISSUE THREAD

**Issue by Defman21** [thepracticaldev/dev.to#802]
https://blog.github.com/2018-01-25-multiple-issue-and-pull-request-templates/

**Comment by maestromac** [comment]
@jessleenyc thoughts on this?

**Comment by jessleenyc** [comment]
@Defman21 this doesn't seem super intuitive since you'll need to update the URL to toggle the correct template. What are your experiences with it?

**Comment by tterb** [comment]
@jessleenyc I believe it provides the user the option of selecting one of the templates when opening a new issue/pull request, as shown in the image below.  

<img width="796" alt="screen shot 2018-10-03 at 12 25 50 pm" src="https://user-images.githubusercontent.com/16360374/46434128-90a17900-c707-11e8-8dcb-b41f015f736a.png">

**Comment by nektro** [comment]
@maestromac ah, having the selector requires specific names and including front matter on the templates, see here: https://github.com/nektro/apps.nektro.net/pull/1/files

All the original PR did is setup template URLs, see:
https://github.com/thepracticaldev/dev.to/issues/new?template=Bug.md
https://github.com/thepracticaldev/dev.to/issues/new?template=FeatureRequest.md

**Comment by maestromac** [comment]
Turns out it could be one from the setting tab 😆. Thanks [GitHub Blog](https://blog.github.com/2018-05-02-issue-template-improvements/)
