### ISSUE TITLE
Qutebrowser support

### ISSUE THREAD

**Issue by dhurba87** [thepracticaldev/dev.to#8027]
**Describe the bug**
Homepage not working from **qutebrowser**.

**To Reproduce**
- Open [qutebrowser](https://qutebrowser.org/)
- Go to homepage `https://dev.to`
- You will notice that the article list won't appear.

**Screenshots**

![image](https://user-images.githubusercontent.com/7259726/82648379-5025a480-9c37-11ea-9869-af16ace0b4e8.png)

**Desktop (please complete the following information):**

- OS: macOS 10.15.4
- Browser: qutebrowser
- Version: v1.11.0

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @dhurba87, sorry it's not working with that browser

It looks like by default it uses something called `QtWebEngine` from the Qt library which according to this - https://wiki.qt.io/QtWebEngine - is a fork of Chromium based on version 77.

In theory it should work, mmm.

I tried `brew cask install qutebrowser` which installs version 1.11.1 and I was able to see the homepage correctly:

<img width="1792" alt="Screenshot 2020-05-22 at 11 22 14 AM" src="https://user-images.githubusercontent.com/146201/82652864-9faba680-9c1e-11ea-8071-0e29bf432a43.png">

I then tried to sign in and it worked as well, but I realize that as by not being a new user I wouldn't go through the onboarding, so I did and even though it took me a while to figure out how to change URL again, I did and it worked :)

<img width="1792" alt="Screenshot 2020-05-22 at 11 29 16 AM" src="https://user-images.githubusercontent.com/146201/82653448-822b0c80-9c1f-11ea-9bf6-76ecb595fee7.png">


Could you try again with the newest version? thank you!

**Comment by dhurba87** [comment]
Hi @rhymes thanks for checking the issue. I'll update my browser and try it today evening and update you.

**Comment by dhurba87** [comment]
Hi @rhymes , it didn't work right after I install the latest version `1.11.1`, so I disabled the adblocker and it worked after that. I then enabled ad-blocker again but this time I couldn't replicate the issue. I guess its my device specific issue. Anyways, thanks for helping me out here.

**Comment by rhymes** [comment]
Cool @dhurba87! I'm going to close this issue in the meantime. Let us know if you have other problems!
