### ISSUE TITLE
Decouple oauth user from platform user

### ISSUE THREAD

**Issue by abenettt** [thepracticaldev/dev.to#8029]
**Is your feature request related to a problem? Please describe.**
Currently the information of the github or twitter user is saved in the user object of the platform. Decoupling this information would allow for easier addition of further oauth providers and avoids the bloating of the user object with fields that might never be set. 

**Describe the solution you'd like**
A generic `oauth_user` model that is filled with the provider and user id and information that is common to all providers, this model can then be linked to the appropriate platform user by way of id. This allows an arbitrary number of oauth providers to be connected to a user without the users being filled with dozens new fields.

**Describe alternatives you've considered**

**Additional context**

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
@abenettt we already have that in a sort, our `Identity` model is what you call `oauth_user`: https://github.com/thepracticaldev/dev.to/blob/master/app/models/identity.rb

I do agree that we should restructure the `users` table to move off of it those fields that are tied to authentication.

We've been working slowly on decoupling functionality from authentication, see [my recent PRs about that](https://github.com/thepracticaldev/dev.to/pulls?q=is%3Apr+decouple+is%3Aclosed+author%3Arhymes). It's going be a long process as the `users` table is probably the one with the most columns/fields and critical importance.

We're also in the process of finishing a PR for "Sign in with Apple" - https://github.com/thepracticaldev/dev.to/pull/7952 - as a new authentication provider.

**Comment by abenettt** [comment]
Ah sorry, yes, I didn't pay enough attention there, but it is great that the effort is already underway!

**Comment by citizen428** [comment]
@abenettt In the interest of keeping our issue tracker clean I'll close this now. Thanks for the report!
