### ISSUE TITLE
The button at the end of the listings page has no text

### ISSUE THREAD

**Issue by AthulMuralidhar** [thepracticaldev/dev.to#8047]
**Describe the bug**

- there is a button at the botton end of the listings page of dev.to, it seems to have no text

**To Reproduce**

- Go to dev.to 's homepage

- from the side choose 'listings'

- scroll down to the bottom end of the listings page, you see a button

- the button has no desciption
**Expected behavior**
- It should have at least some text to point people

**Screenshots**
<img width="1396" alt="Screenshot 2020-05-25 at 11 31 00" src="https://user-images.githubusercontent.com/35686547/82800002-38d6f900-9e7b-11ea-9a69-bb7d73160313.png">

**Desktop (please complete the following information):**

- OS: Mac OS catalina 
- Browser: Google chrome
- Version: Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Thanks @AthulMuralidhar! 

Definitely a theming issue as I can confirm the text is there in the default theme:

![Screenshot_2020-05-25 Listings - DEV Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/82800279-b8fd5e80-9e7b-11ea-8a71-b9b1bfbbb569.png)

I'll take a look

**Comment by AthulMuralidhar** [comment]
> Thanks @AthulMuralidhar!
> 
> Definitely a theming issue as I can confirm the text is there in the default theme:
> I'll take a look

I see, thanks!
