### ISSUE TITLE
Posts discussions number not visible

### ISSUE THREAD

**Issue by Bam92** [thepracticaldev/dev.to#8053]
**Describe the bug**
I am wondering if I am the only one to have this, but everytime I open a post I can't see number of comments as before. I can see number of hearts, and others. I tried on Debian GNU/Linux (Chromium) and Windows 10 (Chrome)

**To Reproduce**

**Expected behavior**
![devToExpected](https://user-images.githubusercontent.com/14941675/82885864-fd553100-9f45-11ea-96cd-a80e0bb01e46.PNG)

**Screenshots**
![devto](https://user-images.githubusercontent.com/14941675/82885887-05ad6c00-9f46-11ea-8792-1d6eb87240aa.PNG)

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @Bam92, could you open the developer tools and check if you have any errors in the javascript console? Thank you!

**Comment by Bam92** [comment]
No error.

**Comment by citizen428** [comment]
Hm, the whole sidebar looks a bit off. What resolution are you on @Bam92? I'm asking  because I get this behavior when I resize my browser window horizontally, but not enough for the sidebar to move to the bottom:

Full resolution:

<img width="95" alt="Screen Shot 2020-05-27 at 11 12 04" src="https://user-images.githubusercontent.com/47985/82977129-24296b00-a00b-11ea-9963-cb4ff2b7fad2.png">

Resized horizontally:

<img width="62" alt="Screen Shot 2020-05-27 at 11 12 19" src="https://user-images.githubusercontent.com/47985/82977239-78cce600-a00b-11ea-8a2b-9f33593a5af0.png">

When I resize further the sidebar moves to the bottom.

**Comment by citizen428** [comment]
More context: we have several media queries for `min-width`. Resizing to a width between 1365 to 1439 seems to trigger this for me to (Firefox Developer Edition on macOS).

**Comment by ludwiczakpawel** [comment]
yea, the media queries we use seem to be pretty random/hacky to be honest. i have a PR draft where I introduce much more standard media queries as well as layout updates to other views (including the article view) but it's still quite far away on schedule, probably 3-4 weeks.

Until then, honestly i'm not sure what should be the ideal solution here - i think whatever quick fix we implement here, we will almost certainly end up with another edge case glitch and i don't know if it's worth the effort. At the end of the day, not seeing the number next to "DISCUSS" at this particular breakpoint isn't that huge of a deal I think...

**Comment by Bam92** [comment]
> Hm, the whole sidebar looks a bit off. What resolution are you on @Bam92? I'm asking because I get this behavior when I resize my browser window horizontally, but not enough for the sidebar to move to the bottom:
> 
> Full resolution:
> 
> <img alt="Screen Shot 2020-05-27 at 11 12 04" width="95" src="https://user-images.githubusercontent.com/47985/82977129-24296b00-a00b-11ea-9963-cb4ff2b7fad2.png">
> 
> Resized horizontally:
> 
> <img alt="Screen Shot 2020-05-27 at 11 12 19" width="62" src="https://user-images.githubusercontent.com/47985/82977239-78cce600-a00b-11ea-8a2b-9f33593a5af0.png">
> 
> When I resize further the sidebar moves to the bottom.

1366 x 768 (Windows 10, Chrome Version 81.0.4044.138 (Build officiel) (64 bits))

**Comment by citizen428** [comment]
@ludwiczakpawel Around 2018 1366 x 768 was the most common laptop resolution, especially in the lower price segment. With our current CSS it's just wide enough to make it past the media query at 1365 but not enough to actually show the numbers. 

But I agree if we're currently working on a big overhaul of the media queries, an intermediate fix may not be worth it.

@Bam92 Looking at our current CSS, this is essentially intended behavior. Should we close this issue for now and reopen it if your problem isn't resolved after we get the redesign out the door?

**Comment by Bam92** [comment]
@citizen428: no matter.
