### ISSUE TITLE
Installation via Docker (The engine "node" is incompatible with this module)

### ISSUE THREAD

**Issue by Toxu-ru** [thepracticaldev/dev.to#8056]
Ubuntu 18.04.4 LTS 
Installing Docker software: 

https://docs.dev.to/installation/docker/
https://docs.docker.com/engine/install/ubuntu/

When you install the `docker-setup`. We have:

```
...
(81/98) Installing nodejs (10.19.0-r0)
...
```

```
[1/5] Validating package.json...
error dev.to@1.0.0: The engine "node" is incompatible with this module. Expected  

 version "12.16.x". Got "10.19.0" 

error Found incompatible module.
```
If Dockerfile `nodejs -> nodejs-current` is edited, we get:

```
error dev.to@1.0.0: The engine "node" is incompatible with this module. 

Expected version "12.16.2". Got "12.4.0" 

error Found incompatible module.
```
We of course can now still correct and further, but I think this is not quite true.

Maybe there was some mistake in the beginning?

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by TheRohitSharma** [comment]
I had been getting this as well and ended up adding `--ignore-engine`s to the Dockerfile as a temporary workaround.

**Comment by abhisheksurve45** [comment]
@rhymes  is this up for grabs? Seems like a good first issue for me.

**Comment by citizen428** [comment]
@abhisheksurve45 Normally I'd say that yes, it's up for grabs, but we currently have a big ongoing container refactoring PR (#7747) and it might just be easier if @jdoss takes care of this as part of that work. Let's double check with him.

**Comment by Toxu-ru** [comment]
I managed to install only from: `Switch_Base_Container_to_Fedora`

In master, even using `--ignore-engines`, we come up with an error:

`LoadError: Error relocating /usr/local/bundle/gems/mini_racer-0.2.10...`

From @jdoss

works great.

**Comment by citizen428** [comment]
Nice, I'll close this out for now as the recent PR should address this and other issues.
