### ISSUE TITLE
Ensure that broadcast names are unique

### ISSUE THREAD

**Issue by vaidehijoshi** [thepracticaldev/dev.to#8070]
Currently, for the welcome notifications feature, we look for a broadcast based on its name (and whether or not it is `active` or not), for example: `Broadcast.active.find_by!(title: "bananas")`.

However, as we expand the `Broadcast` model to be used for _other_ types of notifications (such as as site-wide notification feature), there is a possibility for multiple broadcasts to be named similarly.

We should enforce uniqueness on a Broadcasts name, and render an appropriate error message to an admin user who tries to create a broadcast with the same name as another. 

We should also make sure that this is well-tested :)

**Comment by vaidehijoshi** [comment]
A note to our amazing contributors: this issue will be worked on by a DEV team member and is not up for grabs!

**Comment by vaidehijoshi** [comment]
@juliannatetreault I think this would be great for you to work on! Let me know if you're interesting in picking it up 😃

**Comment by juliannatetreault** [comment]
> @juliannatetreault I think this would be great for you to work on! Let me know if you're interesting in picking it up 😃

I'm happy to work on this as well @vaidehijoshi! 😄
