### ISSUE TITLE
Fetching GitHub repos under Integrations results in Error 503

### ISSUE THREAD

**Issue by Amorpheuz** [thepracticaldev/dev.to#8076]
**Describe the bug**
On loading up the `Integrations` tab, the `Pin a few of your GitHub repositories to your profile` returns Error Code 503 after trying to load for ~2 minutes.

**To Reproduce**
1. Login to DEV with GitHub / Have GitHub connected to the account.
2. Open Settings -> Integrations.
3. The `Pin a few of your GitHub repositories to your profile` will show a loading screen initially but time-out after ~2 minutes.

**Expected behavior**
Display the list of User's repositories.

**Screenshots**
![image](https://user-images.githubusercontent.com/22113778/83033494-ce79b080-a054-11ea-8bb9-e2c507c8e60e.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Edge, Chrome and Firefox Developer Edition
- Version: 83, 83, and 77.09b respectively

**Smartphone (please complete the following information):**

- Device: Nokia 6.1
- OS: Android 10
- Browser: Edge
- Version: 45

**Additional context**
Did try this out with another account too, resulting in same error.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by dippas** [comment]
In my case the preloader is an infinite loop. either using Firefox or Chrome (both latest versions) in Windows 10

**Comment by rhymes** [comment]
@dippas the infinite loop possiblity is a great clue! what do you mean by "preloader" though?

**Comment by dippas** [comment]
@rhymes  I'm referring to this: 

![image](https://user-images.githubusercontent.com/10220287/84018741-4494e600-a978-11ea-8991-e23646a8e23c.png)

and no console error whatsoever

**Comment by Amorpheuz** [comment]
I get the same loading animation with timeout later too. The 503 gets printed once the "An error occurred" message pops up. If I try to open https://dev.to/github_repos, I get the same warnings as #8104.

The integration does work on my local env of DEV. The only thing that changed for my pinned repos (in case it could be related to the issue) is that they got archived. I tried the same on the local environment but couldn't replicate the issue.

**Comment by nickytonline** [comment]
Thanks for the additional information. @rhymes is looking into this.

**Comment by rhymes** [comment]
@Amorpheuz it @dippas can you check if it's now working for you as it is for me? thank you! https://dev.to/settings/integrations

**Comment by Amorpheuz** [comment]
It is! Loads instantly too, Woohoo 🎉

**Comment by ExpressGradient** [comment]
# Description
Failed to fetch user's Github repos for User Integrations. This bug is not yet resolved. I am able to reproduce this bug.

# How to reproduce the bug??
Navigate to `settings/integrations` route and see the `Pin a few of your GitHub repositories to your profile`.

# What happens??
A loader is displayed till the content is fetched, since it is failing to fetch content, an error is displayed. There are no console errors in firefox, but a chromium based browser will console error a status code of 503 too.

![image](https://user-images.githubusercontent.com/59659961/89809889-d3310980-db59-11ea-8b7b-1853582bff50.png)

**Comment by rhymes** [comment]
Hi @ExpressGradient, yeah, the bug is not totally resolved. Please move your helpful comment to https://github.com/forem/forem/issues/8904

thank you!

**Comment by ExpressGradient** [comment]
Ohhh, I'm sorry for that, I didn't know about another issues thread. I had just mailed this issue to the dev team and it replied to make a comment here. Yeah I will move this comment there. Thanks.

**Comment by rhymes** [comment]
@ExpressGradient no worries, thank you! :-)
