### ISSUE TITLE
Allow users to dismiss active broadcasts

### ISSUE THREAD

**Issue by vaidehijoshi** [thepracticaldev/dev.to#8091]
Once we implement the feature to render an "active" broadcast throughout the site (https://github.com/thepracticaldev/dev.to/issues/8090), we should also ensure that users can dismiss the currently-active broadcast by `x`-ing out of it.

We probably want to save this in localStorage, similar to how we implement the "close" functionality on the hero banner. This should be broadcast-specific; in other words, if an admin activates _another_ broadcast, the user should still see it, even if they have dismissed a different active broadcast previously.

**Comment by vaidehijoshi** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.

**Comment by benhalpern** [comment]
> We probably want to save this in localStorage, similar to how we implement the "close" functionality on the hero banner. This should be broadcast-specific; in other words, if an admin activates another broadcast, the user should still see it, even if they have dismissed a different active broadcast previously.

Yup, I'd say you can follow the same exact format as the hero banner (and probably generalize that whole function).

Basically store _which_ broadcast has been dismissed and don't show the broadcast if that is stored as such.
