### ISSUE TITLE
Add tracking to welcome notifications

### ISSUE THREAD

**Issue by vaidehijoshi** [thepracticaldev/dev.to#8099]
We'll want to use the `ahoy` gem for this.

Based on [this](https://nimbleindustries.io/2018/08/30/dump-google-analytics-and-use-ahoy-to-track-your-rails-app-traffic) blog post and `ahoy`'s README, I think we'll want to use the `referrer` on the `Visit`.

**Comment by vaidehijoshi** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.

**Comment by vaidehijoshi** [comment]
Hm, I spent some time investigating and playing around with this today (see my branch [here](https://github.com/thepracticaldev/dev.to/tree/vaidehijoshi/add-ahoy)). It seems like Ahoy only interprets a "visit" from hard refreshes or direct URLs. In other words, linking to another part of the site doesn't seem to be considered a "visit".

Another issue: the `Ahoy::Visit` object itself doesn't do a super great job at telling us _where_ the user visited. For example, in snippet below, I was on the `/notifications` page, then clicked a link to the `settings/ux` page. But here's how ahoy interpreted that:
```ruby
#<Ahoy::Visit:0x00007f9fc9d93c60
  id: 12,
  user_id: nil,
  referrer: "http://localhost:3000/notifications",
  referring_domain: "localhost",
  landing_page: "http://localhost:3000/manifest.json",
  # ... more data here...
  started_at: Wed, 27 May 2020 22:19:47 UTC +00:00>
```

I haven't dug into the source code yet to see what's going on, but I wonder if this is a limitation of the "internal tracking" that we're trying to do here.

**Comment by vaidehijoshi** [comment]
Some updates after I dug into the source code and played around with this more. Unfortunately, the documentation doesn't go into much detail and just lays out the methods you can use, so it's hard to know if there is a workaround available for these things or not.

* Ahoy's concept of a "visit" that it can track does not seem to include visits to the site from within the site itself. I threw some breakpoints into the gem source to confirm that this is the case, and `track_visit` never actually gets called. I'm still not entirely clear on _how_ or _when_ the ahoy controller is called, but I'm sure that it's only picking up on visits "externally", so-to-speak. FWIW, the timeout for when the gem creates a "new" visit is based on a default 4-hour time period, which I've also tried tweaking, but I actually don't think is the real issue for the problem we're facing.
* The first controller that we seem to hit is the `ServiceWorkerController`, so every `landing_page` attribute on any "external" `Ahoy::Visit` object always ends up with `"http://localhost:3000/manifest.json"`. I discovered that it was possible to do something like this: `skip_before_action :track_ahoy_visit, only: %i[index manifest]` in the controller, _however_, this results in nothing being tracked (I was hoping that the _next_ controller would try to track it, but obviously and understandably, it does not).

Given these two things, I'm not sure if Ahoy is the right tool for this job (unless someone understands it better than I do and is able to get more out of the source code/limited documentation?). In the context of welcome notifications, the only way to add tracking on a notification is by modifying the HTML on the broadcast itself (check out the broadcasts in the [internal view](https://dev.to/internal/broadcasts) to see what I mean). I've also investigated the [JavaScript library version](https://github.com/ankane/ahoy.js), and I'm not sure that we can use those methods given the current setup of notifications. Maybe that's a flaw of the way notifications were designed (🤷 ?).

Ahoy definitely doesn't seem to work well for what we want to do here, so it seems to me like we might want to explore other libraries for tracking on welcome notifications, or, alternatively, add ahoy and only use it for what it helps us with (general external traffic that visits our site). At least, that's what it seems like to me after spending a couple hours implementing and investigating this :) If I'm missing something obvious, let me know! 

cc @benhalpern @atsmith813 
also cc-ing @rhymes because he generally has good advice and investigative skills when it comes to these things 😄

**Comment by atsmith813** [comment]
Hmmm 🤔 that's tough. I don't feel I have much to add here, but one thing to note is the beautiful DEV buzz word - _caching_ :trollface:.

Any sort of tracking on the "receiving end" is difficult because, on average, 85% of web traffic doesn't hit the origin server to be tracked - the content was found in the cache at the edge (Fastly).

**Comment by rhymes** [comment]
I have to admit that by lacking the context of the effort behind this issue and not being familiar with ahoy at all, I'm not sure what's going on or if the gem is behaving differently from what @vaidehijoshi already described.

It also depends if the goal here is just to track welcome notifications or to start replacing Google Analytics (yay!) with something internal.

> Ahoy's concept of a "visit" that it can track does not seem to include visits to the site from within the site itself. 

This is odd, as internal requests do have the refererr set. 

> The first controller that we seem to hit is the ServiceWorkerController

Yeah, i figured our shell architecture wouldn't play nice with this sort of server side tracking. We also hit the same endpoint twice, don't know if that would complicate our metrics. 

> alternatively, add ahoy and only use it for what it helps us with (general external traffic that visits our site).

maybe this.

What if we ask ahoy's creator? I feel like some of your exploration should land as an inquiry in https://github.com/ankane/ahoy/issues/new before moving on one or or another. The author is very knowledgeable and friendly. I think he's the one to ask about your findings.

We also use a few of his gems (ahoy_email, blazer and strong_migrations).

**Comment by benhalpern** [comment]
I think we can start with Ahoy _events_ at first to start tracking custom things and then move to visits to track general page loads (ala Google Analytics, possibly moving off GA altogether in long run).

That make sense?
