### ISSUE TITLE
Support POSSE on dev.to

### ISSUE THREAD

**Issue by bigblind** [thepracticaldev/dev.to#81]
I like the idea of [POSSE](https://indieweb.org/POSSE), which stats for **P**ost on your **O**wn **S**ite, **S**yndicate **E**lsewhere.  It promotes the idea that you should own your own content. 

I'd love it if there was some way to automatically post to dev.to when I post to my own site. Is there a possibility that you'd create an API endpoint for posting?

I understand that this isn't something you'd consider easily, as it'd open the door for automatically posting all kinds of low-quality content, and I'm not sure how to solve that problem. Still, it'd be cool.

**Comment by Zhao-Andy** [comment]
API endpoints are definitely something we're considering. Good to hear that people are still interested.

We currently have our beta feature that pulls RSS feeds and creates articles for your account; not sure if that's something you've tried yet. You can find it here: https://dev.to/settings/publishing-from-rss

**Comment by bigblind** [comment]
Oh, that's amazing!

**Comment by darol100** [comment]
I am highly interested in this feature as well. I think Medium has done a really good job of documenting their API. What I think is worth looking at what they have done https://github.com/Medium/medium-api-docs.

If you implement APIs, I will be more than welcome to help you writing SDK's in couple different languages.

**Comment by darol100** [comment]
Hey Stale (bot),

As far I know, this feature has not been implemented yet.

**Comment by darol100** [comment]
Good bot!!

**Comment by jessleenyc** [comment]
Hey @darol100 and @bigblind -- sorry for the silence here. We're planning to create an endpoint for posting by the end of this quarter. Was that the request? Not sure if POSSE implies any other needs.

**Comment by Mayeu** [comment]
@jessleenyc If I may, to be able to fully POSSE one need to:
1. Being able to post new articles via the API with support for the canonical origin
2. Being able to collect feedback (comments, reaction, etc.) ideally via something like [webmention](https://indieweb.org/Webmention)
3. Being able to comment via the API

Having (1) will already be awesome, the rest can be split out in other tasks for after :)

**Comment by philnash** [comment]
I believe that the ability to ingest feeds via RSS solves 1. It is a pain that Medium requires you to use a proprietary API in order to post and I think it fits much better with the ethos of the IndieWeb to use easily implementable standards like RSS to enable this and not another new API.

At least, if you do implement an API for posting, please don't remove the RSS ingesting feature.

**Comment by Mayeu** [comment]
@philnash the current RSS ingesting feature does not fully solve 1 since you can't push the post button via the API as far as I know, thus you can’t have a fully automated POSSE setup to dev.to.

Note that I also agree that those API endpoints should not replace the RSS ingesting features :+1:

**Comment by darol100** [comment]
Hey @jessleenyc ,

I think @Mayeu  did an amazing explanation on https://github.com/thepracticaldev/dev.to/issues/81#issuecomment-456707976.
