### ISSUE TITLE
Pin a few of your GitHub repositories to your profile An error occurred issue about sameSite set to none .

### ISSUE THREAD

**Issue by krishnadevz** [thepracticaldev/dev.to#8104]
**hello there when we go to the Settings and then Integrations tab after that I click on the Integrations then I waited till 4 to 5 minutes there then their error occurred like this 🔽**
![Annotation 2020-05-28 100845](https://user-images.githubusercontent.com/42638797/83099544-4a164480-a0cb-11ea-8572-4feb3c5ea212.png)
 and I checked browser description there in console like this 🔽
Cookie “_Dev_Community_Session” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read 👉[mdnDocs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies)

**To Reproduce**

**hello there when we go to the Settings and then Integrations tab after that I click on the Integrations then I waited till 4 to 5 minutes there then their error occurred like this 🔽  **
![Annotation 2020-05-28 100845](https://user-images.githubusercontent.com/42638797/83099544-4a164480-a0cb-11ea-8572-4feb3c5ea212.png)
**Expected behavior**

Not loading any repository there showing error occured .

**Screenshots**

**Desktop (please complete the following information):**

- OS:Windows 10 home 1863 Build
- Browser:firefox ,chrome,edge
- Version:firefox(76.0.1 (64-bit)),chrome(Version 81.0.4044.138 (Official Build) (64-bit))

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Might be related to https://github.com/thepracticaldev/dev.to/issues/8076 - going to check ASAP

**Comment by icyJoseph** [comment]
Bumping. Any pointers on how to fix this?

**Comment by rhymes** [comment]
Hi @icyJoseph, sorry, I just confirmed it's a server side issue, we're investigating. Will let you know when it's fixed

**Comment by rhymes** [comment]
@krishnadevz @icyJoseph can you check if it's now working for you as it is for me? thank you! https://dev.to/settings/integrations

**Comment by icyJoseph** [comment]
@rhymes it does work! Great job!

**Comment by rhymes** [comment]
@icyJoseph to be honest it started working by itself while I was in the midst of debugging it :D I think there was something going on upstream (in the GitHub API's) but hey, let's take this as a win :D
