### ISSUE TITLE
Add Supported Markdown Syntax in Sidebar?

### ISSUE THREAD

**Issue by surjithctly** [thepracticaldev/dev.to#8108]
**Is your feature request related to a problem? Please describe.**

I wish there was a sidebar where it shows available basic markdown syntax, so we don't have to click the `?` link each time. Something like below.

![image](https://user-images.githubusercontent.com/1884712/83137129-40f69900-a106-11ea-8940-9a7a2b6882f8.png)

**Describe the solution you'd like**

As per the image I shared 

**Describe alternatives you've considered**

Clicking `?` link each time when I need something. It shows how to embed something, but not taking about how we can embed Code with Syntax Highlighting. 

eg: ` ```javascript `

**Additional context**

or Either Add Rich Editing Icons in the header which translate to Markdown. It will really help someone is not expert in markdown. Like me. 

![image](https://user-images.githubusercontent.com/1884712/83137493-e27dea80-a106-11ea-95f2-078a752e6328.png)

**Comment by rhymes** [comment]
Hi @surjithctly,

we're close to merging the new editor which has inline info in the sidebar, see https://github.com/thepracticaldev/dev.to/pull/7524

It might still not cover exactly your request though, maybe you can revisit this when it's online? I'll make sure to ping you when it is

**Comment by surjithctly** [comment]
Cool. Looking forward to it.

**Comment by madarsbiss** [comment]
@rhymes @surjithctly nice feature, agree. Especially for new comers, as regular users already know it head to toe xdd

**Comment by surjithctly** [comment]
@rhymes I can see the new UI now. And a lot of whitespace in the right hand side, perfect for our feature. I have gone ahead and created mockup along with a show hide feature (using details /summary) so that its unobstructed and the main area looks clean & minimal by default.

![image](https://user-images.githubusercontent.com/1884712/83322735-d2d1e380-a277-11ea-88e9-e88bdb4d8001.png)

@ludwiczakpawel What do you think of it?

**Comment by ludwiczakpawel** [comment]
We definitely have a plan to add actual toolbar in the editor. Even with that, simple and small help section in the sidebar would be very useful. I'll try to build it as soon as possible but hard to say when either of these will actually happen.
