### ISSUE TITLE
Login via Twitter issue

### ISSUE THREAD

**Issue by shubhamjadhav36** [thepracticaldev/dev.to#8134]
When i try to login via twitter on Dev App it will open up chrome browser, then from browser I'm able to login via twitter nd able to use the Dev on web.
But however when i close the browser and open my Dev app it wont recognise me. It will again asks for login .
If i try to login again then it will open browser and cycle goes on...

**Comment by rhymes** [comment]
@shubhamjadhav36 which dev app? Android or iOS?

**Comment by shubhamjadhav36** [comment]
Android (Dev community)

**Comment by fdoxyz** [comment]
Hello @shubhamjadhav36. Would you be willing to help us by creating an issue over in [the Android app repo](https://github.com/thepracticaldev/DEV-android/issues)?

It really helps if we know your device, OS version, App version and other details. Thank you!

**Comment by shubhamjadhav36** [comment]
Device : samsung galaxy A5
Os version : Android 8.0.0 (samsung experience version 9.0)
App version : 1.3.1

**Comment by fdoxyz** [comment]
Closing in favor of following up [here](https://github.com/thepracticaldev/DEV-Android/issues/82)
