### ISSUE TITLE
No UI indication to confirm pressing of login button.

### ISSUE THREAD

**Issue by vipulbhj** [thepracticaldev/dev.to#817]
**Description**
When you click the login button, then there is no UI chance indicating that the login process has started. This is especially a problem when the network is slow and it takes a few seconds to log in.

**Request**
First of all, I am very new to open source and I am not sure if its a bug or a feature request. So please forgive me if its the other. That being said, I recommend using an overlay loader indicating the process execution. I would like to try and fix this if that okay. Again I am sorry if this is stupid.

**Comment by maestromac** [comment]
Hey @vipulbhj ! This issue is perfectly fine. I think this would be a feature request for UI improvement. @benhalpern might have some thoughts on how the design should be.

**Comment by vipulbhj** [comment]
Hey @maestromac Thank you so much for confirming. Can I work on it if we decide to do this ??

**Comment by vipulbhj** [comment]
I would like to try this if anyone else if not trying it. I am thinking to implement an overlay loader. Can someone discuss designs with me

**Comment by jessleenyc** [comment]
Let's reassess how all login buttons across site work while loading for slower networks.
