### ISSUE TITLE
Trying to pin GitHub repos but getting an error in the network call.

### ISSUE THREAD

**Issue by samrith-s** [thepracticaldev/dev.to#8172]
**Describe the bug**

When in the Integrations page, trying to add GitHub repo it loads forever and then errors out.

**To Reproduce**

1. Go to Integrations.
2. Wait for GitHub repository block to load.
3. It loads for a while, and then errors out with the error message from the screenshot.

**Expected behavior**

Should be able to view repositories and pin the to the profile.

**Screenshots**
![image](https://user-images.githubusercontent.com/9032162/83297302-9f994100-a1f2-11ea-9d28-86fb51c0b59c.png)

**Desktop (please complete the following information):**

- OS: macOS Mojave
- Browser: Chrome
- Version: 84.0.4112.0 (Official Build) canary (64-bit)

**Comment by rhymes** [comment]
Hi @samrith-s, I'm going to close this in favor of https://github.com/thepracticaldev/dev.to/issues/8104 and https://github.com/thepracticaldev/dev.to/issues/8076

Please, feel free to leave a comment there as well.

**Comment by rhymes** [comment]
@samrith-s can you check if it's now working for you as it is for me? thank you! https://dev.to/settings/integrations

**Comment by samrith-s** [comment]
@rhymes works for me too, thanks!
