### ISSUE TITLE
Broken style on Markdown and Liquid tags page

### ISSUE THREAD

**Issue by Cry0nicS** [thepracticaldev/dev.to#8182]
The new design has some odd colors mixed together. As a result, the code displayed on the "Markdown" help page is not visible when using the Night Theme.

Same happens when selecting the "Liquid Tags" help page.

**To Reproduce**

1. Go to "Write a post"
2. Type something in the body until the "Editor Basics" recommendation shows up on the right side
3. Select "Markdown"

**Expectations**

Text color shouldn't be white on white background.

**Screenshots**

![image](https://user-images.githubusercontent.com/29982205/83326269-60fb9900-a27b-11ea-84d5-a64389805075.png)

![image](https://user-images.githubusercontent.com/29982205/83326310-b0da6000-a27b-11ea-9efa-2ab98bbbca20.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Brave
- Version: 1.9.72

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).
