### ISSUE TITLE
Type swapping between tag and tag_list in DEV API

### ISSUE THREAD

**Issue by TaigaMikami** [thepracticaldev/dev.to#8183]
**Describe the bug**

This is about the DEV API.
The tag and tag_list types of articles that can be obtained with `GET /articles` and `GET /articles/:id` seem to have been swapped.

Is this the right behavior?

**To Reproduce**
1. Send get requests `GET /articles` and `GET /articles/:id` with curl.

**Expected behavior**
I think it should be unified into one or the other.

**Screenshots**
`GET /articles`
![スクリーンショット 2020-05-30 20 05 49](https://user-images.githubusercontent.com/25325947/83326727-404e3600-a2b1-11ea-96aa-a2dedc9cc5f0.png)

`GET /articles/:id`
![スクリーンショット 2020-05-30 20 06 05](https://user-images.githubusercontent.com/25325947/83326689-0bda7a00-a2b1-11ea-86da-46c759d7e863.png)

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hi @TaigaMikami, thanks for raising this issue. This is a known problem and it won't likely be fixed until we developed a v1 of the API. 

You can find related discussions here:

- https://github.com/thepracticaldev/dev.to/issues/2996
- https://github.com/thepracticaldev/dev.to/issues/4637

Closing this as a dupe, you're welcome to add your contribution to https://github.com/thepracticaldev/dev.to/issues/4637 :-)
