### ISSUE TITLE
Badges no longer have a transparent background

### ISSUE THREAD

**Issue by emgoto** [thepracticaldev/dev.to#8184]
**Describe the bug**
All badges now have a white background. This is fairly noticeable if you are using DEV in dark mode.

**To Reproduce**

1. Go to a profile.
2. View badges in sidebar of profile.
3. See that badges have a white background.

**Expected behavior**

The badges should have a transparent background.

**Screenshots**

<img width="175" alt="image" src="https://user-images.githubusercontent.com/33337378/83328405-15221180-a2c6-11ea-81ab-4b5d30e1e083.png">

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Firefox, Safari

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Closed by https://github.com/thepracticaldev/dev.to/pull/8226
