### ISSUE TITLE
/settings/integrations can time out if you have too many repos

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/dev.to#822]
**Describe the bug**
If you have too many repos, going to `/settings/integrations` can time out. This prevents you from updating which repos are pinned to your profile.

**Proposed Solution**
We could load the repos asynchronously through a regular `GET` request, and have an endpoint that shows the `current_user`'s repositories.

**Comment by itzsaga** [comment]
Happy to see this open. I've experienced this issue for a while now. Commenting more so I know when it has been fixed :-)

**Comment by itzsaga** [comment]
Looks like it's working. Thanks!
