### ISSUE TITLE
Improve documentation to reference bin/setup

### ISSUE THREAD

**Issue by ledestin** [thepracticaldev/dev.to#8249]
**Is your feature request related to a problem? Please describe.**

After a fork sync, there are steps that always need to be performed, and I'd like that to be automatic.

Namely:
```
bundle
yarn
rake db:migrate
rake data_updates:run
```

**Describe the solution you'd like**

Add a script to run the commands above.

**Describe alternatives you've considered**

I can make a script just for myself, but others wouldn't benefit from that. As for the script's name, I don't have any good ideas.

**Comment by Ridhwana** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by Ridhwana** [comment]
@ledestin do you feel that our `bin/setup` is not sufficient in this case?

**Comment by ledestin** [comment]
@Ridhwana oh, my fault for not knowing `bin/setup` does that. Thanks!

**Comment by Ridhwana** [comment]
No problem 😊

**Comment by ledestin** [comment]
@Ridhwana maybe reference `bin/setup` in docs? https://docs.dev.to/getting-started/workflow/
and https://docs.dev.to/getting-started/syncing/

**Comment by Ridhwana** [comment]
I do see that it is referenced at some points in the doc, but as you mention it's not really in a concise way within the appropriate getting started flow areas. 

I'll open up this issue again, and the person taking on this issue can take a stab at making the documentation more explicit for the `bin/setup`.

**Comment by Ridhwana** [comment]
Feel free to assign yourself if this is something you would like to work on as well :)

**Comment by icncsx** [comment]
I think it's also important to mention the importance of running `bin/startup` + `bin/setup`. The startup command is what fixed #8261 for me, and I didn't think `bin/startup` was mentioned more than once in the docs.
