### ISSUE TITLE
Grammarly isn't working in the updated post editor

### ISSUE THREAD

**Issue by Muhimen123** [thepracticaldev/dev.to#8251]
**Describe the bug**
Since the recent update of the post editor, I am not getting any support from Grammarly. Grammarly worked just fine in the previous editor.  

**To Reproduce**
Have Grammarly browser extension enabled and then open the post editor.

**Expected behavior**
Expected to get spelling correction, phrase suggestion, and all that stuff that Grammarly has to offer.

**Desktop (please complete the following information):**

- OS: Window 10 pro
- Browser: Google chrome
- Version:  83.0.4103.61 (Official Build) (64-bit)

**Comment by Ridhwana** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
It seems like the textarea element has `spellcheck="false"` said and the extension probably respects this.

**Comment by Muhimen123** [comment]
I guess it's an easy fix then.

**Comment by srebalaji** [comment]
Is anyone working on this issue or can I take this?

**Comment by nickytonline** [comment]
Feel free to grab it @srebalaji . I’ll assign the issue to you.

**Comment by Muhimen123** [comment]
Grammarly is now functioning properly for the post editor. Therefore I am closing this issue. Thank you.
