### ISSUE TITLE
Docker installation error (pull access denied for devto-web)

### ISSUE THREAD

**Issue by sachinmukherjee** [thepracticaldev/dev.to#8255]
While running `bin/container-setup` got the following error `ERROR: pull access denied for devto-web, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

OS: Ubuntu 16.04 LTS
Docker version: 19.03.8

**Comment by Ridhwana** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by Ridhwana** [comment]
@citizen428 do you have any ideas on what may be the cause of this?

**Comment by jdoss** [comment]
@sachinmukherjee can you run `docker ps -a` and `docker images` and paste the outputs into this issue?

**Comment by sachinmukherjee** [comment]
@jdoss Please find the output of the `docker ps -a` and `docker images` command in outputlogs.txt file
[outputlogs.txt](https://github.com/thepracticaldev/dev.to/files/4731717/outputlogs.txt)

**Comment by jdoss** [comment]
What happens if you run 


```
docker-compose build
```

**Comment by KartikSoneji** [comment]
@jdoss @Ridhwana 
I can replicate the issue.
```
> docker pull devto-web:latest
Error response from daemon: pull access denied for devto-web, repository does not exist
or may require 'docker login': denied: requested access to the resource is denied
```
https://github.com/thepracticaldev/dev.to/blob/71fba61ae26acdecc6f9026389403bf93407aa44/container-compose.yml#L5

`container-compose.yml` tries to use the `devto-web` image, which either does not exist or is not public.

I checked on docker hub as well but couldn't find it.
https://hub.docker.com/search?q=devto-web&type=image

**Comment by jdoss** [comment]
Hey @KartikSoneji can you pull https://github.com/thepracticaldev/dev.to/tree/jdoss/Fix_8255 and let me know if running `bin/container-setup` works for you now?

**Comment by KartikSoneji** [comment]
@jdoss I am on Windows, so cannot run `bin/container-setup`.  
I can replicate the issue by trying to pull the `devto-web:latest` docker image, which still fails.
```
> docker pull devto-web:latest
Error response from daemon: pull access denied for devto-web, repository does not exist
or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by jdoss** [comment]
@KartikSoneji this isn't on Docker Hub or any kind of container registry. It is built via `docker-compose` or `podman-compose` locally on your computer via the script. The logic for this build step was in the wrong spot so it never got run.

**Comment by KartikSoneji** [comment]
@jdoss Ah, didn't know that.
Sorry, I assumed that it was a registry issue.

Unfortunately I don't have access to any Linux systems right now so cannot test the fix.

**Comment by sachinmukherjee** [comment]
It is working now.

**Comment by jdoss** [comment]
Great to hear @sachinmukherjee!

**Comment by sachinmukherjee** [comment]
I have cloned this repository and when I run docker-compose up I'm getting the same issue

**Comment by jdoss** [comment]
@sachinmukherjee You need to run `docker-compose build` before up if you are not using `bin/container-setup`.

**Comment by akhil-naidu** [comment]
> I have cloned this repository and when I run docker-compose up I'm getting the same issue

Are you able to run your instance without any error?

**Comment by sachinmukherjee** [comment]
Yes

**Comment by akhil-naidu** [comment]
> Yes

Can you guide me, I tried to install in Digital Ocean, AWS, Heroku, and even in my PC and failed. In search of my issue, I somehow landed here. 

My problem is exactly the same as you started this issue.

OS: 18.04
Docker: latest

I'm willing to change my environment if required, I want to have an active instance similar to that of dev.to
