### ISSUE TITLE
Search on article body text not working on local host

### ISSUE THREAD

**Issue by icncsx** [thepracticaldev/dev.to#8261]
**Describe the bug**

Query search for author name and username works but does not work for body text. I'm wondering if it's something we have to configure on our end w/ elasticsearch? For all I know, this could be the intended behavior, so please advise!

**To Reproduce**

Fork master, `bin/setup`. I got an error, so I ran `bin/rails s -p 3000` and everything was fine. Visit localhost:3000. Go search on body text (e.g. Typewriter), and it returns nothing, despite that being a part of the body text of Alan Dach's [the daffodil-sky-minus-voluptas](http://localhost:3000/alandach/the-daffodil-sky-minus-voluptas-i8j).

Note: I also tried Gitpod but got the same behavior.

**Expected behavior**

Something like this:

![expected](https://user-images.githubusercontent.com/60417145/83685795-38dfa300-a5b7-11ea-9fdf-01844f375ac5.png)

But I get:

![reality](https://user-images.githubusercontent.com/60417145/83685815-4006b100-a5b7-11ea-9758-944e5136dd5d.png)

Note that search on author name or user name works fine:

![author-search](https://user-images.githubusercontent.com/60417145/83685878-56147180-a5b7-11ea-8337-1f792208d3c3.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.x
- Browser: Chrome
- Version: 81 on Linux

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by Ridhwana** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
Where did you get the error during setup? Did the docs get indexed to Elasticsearch? You can try it out in a Rails console:

```ruby
article = Article.find_by(...)
article.elasticsearch_doc
```

If you get a 404 error, the document wasn't indexed.

**Comment by icncsx** [comment]
The setup error was unrelated.

```bash
Dumping database schema with fix-db-schema-conflicts gem
Error: The `Layout/AlignHash` cop has been renamed to `Layout/HashAlignment`.
(obsolete configuration found in /home/dhexonian/.rvm/gems/ruby-2.7.1/gems/fix-db-schema-conflicts-3.0.3/.rubocop_schema.53.yml, please update it)
``` 
You were right @citizen428! The articles don't get indexed.

```bash
2020-06-04 08:39:46 -0400: GET http://localhost:9200/feed_content_development_alias/_doc/article_1 [status:404, request:0.007s, query:N/A]
2020-06-04 08:39:46 -0400: < {"_index":"feed_content_development","_type":"_doc","_id":"article_1","found":false}
2020-06-04 08:39:46 -0400: [404] {"_index":"feed_content_development","_type":"_doc","_id":"article_1","found":false}
Search::Errors::Transport::NotFound: [404] {"_index":"feed_content_development","_type":"_doc","_id":"article_1","found":false}
from /home/dhexonian/Work/opensource/dev.to/app/services/search/client.rb:43:in `rescue in request'
Caused by Elasticsearch::Transport::Transport::Errors::NotFound: [404] {"_index":"feed_content_development","_type":"_doc","_id":"article_1","found":false}
from /home/dhexonian/.rvm/gems/ruby-2.7.1/gems/elasticsearch-transport-7.7.0/lib/elasticsearch/transport/transport/base.rb:205:in `__raise_transport_error'
```

This seems to be the situation on Gitpod as well, so it looks like there's something additional a user would have to do for articles + other things to get indexed as well. Do you have any advice?

**Comment by icncsx** [comment]
The setup error I got:

```bash
Dumping database schema with fix-db-schema-conflicts gem
Error: The `Layout/AlignHash` cop has been renamed to `Layout/HashAlignment`.
(obsolete configuration found in /home/dhexonian/.rvm/gems/ruby-2.7.1/gems/fix-db-schema-conflicts-3.0.3/.rubocop_schema.53.yml, please update it)
``` 

I did `bin/rails s -p 3000` to get through that message.

You were right @citizen428! The articles don't get indexed.

```bash
2020-06-04 08:39:46 -0400: GET http://localhost:9200/feed_content_development_alias/_doc/article_1 [status:404, request:0.007s, query:N/A]
2020-06-04 08:39:46 -0400: < {"_index":"feed_content_development","_type":"_doc","_id":"article_1","found":false}
2020-06-04 08:39:46 -0400: [404] {"_index":"feed_content_development","_type":"_doc","_id":"article_1","found":false}
Search::Errors::Transport::NotFound: [404] {"_index":"feed_content_development","_type":"_doc","_id":"article_1","found":false}
from /home/dhexonian/Work/opensource/dev.to/app/services/search/client.rb:43:in `rescue in request'
Caused by Elasticsearch::Transport::Transport::Errors::NotFound: [404] {"_index":"feed_content_development","_type":"_doc","_id":"article_1","found":false}
from /home/dhexonian/.rvm/gems/ruby-2.7.1/gems/elasticsearch-transport-7.7.0/lib/elasticsearch/transport/transport/base.rb:205:in `__raise_transport_error'
```

This seems to be the situation on Gitpod as well. Do you have any advice? :)

**Comment by rhymes** [comment]
@icncsx despite the name, the first is just a warning :D

I think the articles aren't indexed because you only started the web app. You should run `bin/startup` :-)

**Comment by icncsx** [comment]
Closing this issue because I didn't run `bin/startup` - only `bin/setup`. The article get indexed and I am able to search on `body_text`. @rhymes thanks for the help :)

**Comment by citizen428** [comment]
@icncsx Glad it helped :-) Our documentation mentions `bin/startup`:

https://docs.dev.to/getting-started/start-app/

If you think it's unclear or hard to find, we accept PRs for doc issues too 😄
