### ISSUE TITLE
Write a post button overflowing the container

### ISSUE THREAD

**Issue by icncsx** [thepracticaldev/dev.to#8264]
**Describe the bug**

The `button.crayons-btn` is overflowing its container between 650 and 700px. We need to change either the padding or font-size if we want to maintain the navbar height.

![button-overflowing](https://user-images.githubusercontent.com/60417145/83710888-d060e800-a5ef-11ea-9180-f43853255239.png)

**To Reproduce**

Visit [DEV](https://dev.to/). Shrink view-port until you see the "write" button overflowing its container.

**Expected behavior**

The button fits in the container.

**Desktop (please complete the following information):**

- OS: Ubuntu 18.x
- Browser: Chrome
- Version: 81

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

N/A

**Comment by citizen428** [comment]
Thanks for the issue @icncsx! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
Maybe @ludwiczakpawel wants to weigh in here.

**Comment by ludwiczakpawel** [comment]
Yea, I can't really repro this issue on my env but I can think of a quick fix. I'll send a PR soon.
