### ISSUE TITLE
Required node version limitation does not allow for current

### ISSUE THREAD

**Issue by abenettt** [thepracticaldev/dev.to#8270]
**Describe the bug**
The current fixed node version is an old one and doesn't allow for new versions of node.

**To Reproduce**

* Install current (not LTS) node version.  (Current is at time of writing 14.4.0)
* Install yarn
* Run `bin/yarn install`

**Expected behavior**
The js dependencies to be installed

**Screenshots**
```bash
❯ bin/yarn install
yarn install v1.22.4
[1/5] 🔍  Validating package.json...
error dev.to@1.0.0: The engine "node" is incompatible with this module. Expected version "12.16.x". Got "14.4.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
We have presently frozen version 12.16 as our Fedora based containers are based on that version. We probably need to update that before.

In the meantime you should be able to type `nvm use` and activate the right version of Node

cc @jdoss @nickytonline

**Comment by nickytonline** [comment]
@abenettt, we use [nvm](https://github.com/nvm-sh/nvm) to switch between node versions, so if you use Node 14, you can switch when you're in the dev.to repo by running `nvm use` which will pick up the version we use found in `.nvmrc` in the root of our project. There are also other node version managers such as `n` and `asdf` that are also popular.

**Comment by abenettt** [comment]
Ah thanks I didn't know that! Yeah, using nvm it works, thanks!
