### ISSUE TITLE
Showing wrong number in "Reading list"

### ISSUE THREAD

**Issue by Muhimen123** [thepracticaldev/dev.to#8294]
**Describe the bug**
In the right-hand side of the home page, it shows I have 10 posts to read(according to the reading list). And whenever I open the reading the list, it shows 2 posts to read. Point to be noted, the correct answer is 2 not 10. 

The following screenshots might help.

**Screenshots**
The bug.
![readinglist](https://user-images.githubusercontent.com/44261822/83885833-b4cd1d00-a768-11ea-8306-9297d8ca2c40.png)

Now the correct one.
![rdnglist](https://user-images.githubusercontent.com/44261822/83885999-c44c6600-a768-11ea-9892-f46ced79ebef.png)

**Desktop:**

- OS: Windows 10 pro
- Browser: Google chrome
- Version: 83

**Comment by rhymes** [comment]
@Muhimen123 how many items do you have in the archive? unfortunately the first count is the sum of them all. See also https://github.com/thepracticaldev/dev.to/issues/8164

**Comment by Muhimen123** [comment]
Oh, I see. Thanks, problem solved.

**Comment by rhymes** [comment]
Thank you!

Closing this as a duplicate of #8164
