### ISSUE TITLE
Annotations in code snippets gets lower-cased

### ISSUE THREAD

**Issue by jwedel** [thepracticaldev/dev.to#83]
# _BUG_
### Current Behavior

see this comment:

https://dev.to/nishparadox/builder-design-pattern/comments/l6m

Actually, in the markup, it’s “@Builder”, but it gets lower-cased when it gets rendered to “@builder”. I think it assumes it to be a mention.

### Expected Behavior

Everything within tripple back-ticks must not be changed in any way. In this case, the annotation should keep its original case "@Builder".

**Comment by Zhao-Andy** [comment]
Thanks for the heads up, we'll look into it!

**Comment by jwedel** [comment]
Funny side note: The same happens in github... as you can see in this issue description.

**Comment by maestromac** [comment]
This issue should be fixed. Try it out and let me know otherwise!

**Comment by jwedel** [comment]
Yup, its fixed! Seems as if I had to resubmit but maybe that was du to caching.
