### ISSUE TITLE
Integrations page is showing 500 error if dev.to is removed from authorized apps in Github profile.

### ISSUE THREAD

**Issue by analizapandac** [thepracticaldev/dev.to#830]
**Describe the bug**
I've previously granted the site OAuth access to my Github profile however I revoked it. So now whenever I try to access /settings/integrations, it results to a 500 error.

**To Reproduce**
1. Go to Authorized OAuth Apps under your Github profile settings (settings/applications),
2. Revoke access of dev.to application
3. Go back to dev.to and open https://dev.to/settings/integrations
4. See 500 error

*I logged in using my Github profile so it can have access again to my list of repositories again so when I visit the integrations page, it works fine. Revoked the app's access and the error shows again.

**Expected behavior**
If I've revoked the site's access from my Github profile, when viewing /settings/integrations page, there should be a button to reconnect my Github profile if I want to.

**Comment by Zhao-Andy** [comment]
Hey @analizapandac, thanks for this report! We'll take a look into it and add some better error handling.
