### ISSUE TITLE
Display Analytics Information

### ISSUE THREAD

**Issue by leovarmak** [thepracticaldev/dev.to#833]
**Is your feature request related to a problem? Please describe.**
It would be really nice if you can share post analytics information like what are post views. I would really like to know how many people I have reached

**Describe the solution you'd like**
Maybe show stats with article views like github. 

**Describe alternatives you've considered**
I haven't tried any alternatives

**Additional context**
Nothing to mention.

**Comment by maestromac** [comment]
Thanks for this issue @leovarmak. Closing this issue because a duplicate was created and there's a bit more discussion going on there: #227
