### ISSUE TITLE
Multiple <title> tags on every page

### ISSUE THREAD

**Issue by OnArs** [thepracticaldev/dev.to#8331]
**Describe the bug**

I'm working on my website auditing and content tracking tool and for the sake of the test added dev.to domain to crawl. Immediately after the start, I found that there are multiple <title> tags on all pages of the website when must be the one and only <title> on each page. I don’t know how long this happened, but this critical error needs to be fixed asap since it will negatively affect the site’s visibility in search engines, as a result, dev.to will lose traffic and new users.

> Why is it important?
> The title tag gives users and the search engines an idea of what the content of a result is about and how it’s related to the search query. Other than that, titles play a significant role in whether a search result is clicked on or not. This is why you need to make sure your title tags are as informative as possible.
> 
> Should there be more than one <title> tag, it can cause some confusion for search engines with picking the right one for the page. Also, multiple <title> tags might alarm Google’s algorithms as a black-hat SEO trick to target more keywords. 
> 
> If search engines pick up a non-relevant <title> tag, it can mislead users and result in a high bounce rate which, subsequently, is harmful to rankings. Ensure that each of your pages has only one title tag, and it’s relevant to the pages’ content.

If this happened a long time ago, then fixing the error, on the contrary, will become an additional signal to search engines to improve the position and visibility of the site.

**To Reproduce**

1. Go to any page of dev.to
2. Open source code of the page
3. Find <title
4. See 10+ <title> tags

Here is a video of reproducing https://www.loom.com/share/4bf0e2e8aad4481fab69c5939ea2c26e

**Screenshots**

![image](https://user-images.githubusercontent.com/6703684/83973142-1b7b4380-a8ed-11ea-84f7-6f1ea9b0981c.png)

**Comment by citizen428** [comment]
Thanks for the issue @OnArs. 

These `<title>` tags are inside `<svg>` elements, which are not used for the page title. You may need to update your tool and use a more specific XPath or CSS selector, e.g. `//head/title` instead of `//title`.

**Comment by citizen428** [comment]
I read through various SEO discussions on the topic and the general consensus is that search engines are well aware of the difference between SVG `<title>` elements and the ones found in a page's `<head>`. I'll close this issue now.

**Comment by OnArs** [comment]
Oh, I didn't mean to reopen this issue but I'm going to fix it. Thanks @citizen428 for the feedback on this bug.
