### ISSUE TITLE
Neden spama aldınız hesabımı 

### ISSUE THREAD

**Issue by wWw-Gevezeler-Net** [thepracticaldev/dev.to#8336]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by wWw-Gevezeler-Net** [comment]
Neden surekli hesabimi spama alıyorsunuz ki anlamış değilim düzeltin bu hatayı cabuk

**Comment by citizen428** [comment]
Can you elaborate a bit on which account is being spammed?
