### ISSUE TITLE
i am not write new post 

### ISSUE THREAD

**Issue by dharmiktank** [thepracticaldev/dev.to#8340]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hello @dharmiktank, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.

**Comment by dharmiktank** [comment]
But how to solve the problem
