### ISSUE TITLE
Data viz or tear sheet in dashboard which shows basic stats

### ISSUE THREAD

**Issue by icncsx** [thepracticaldev/dev.to#8352]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

It would be great if I could track my progress over time re: reactions and views across all posts. The inspiration for this feature request comes from sites like Twitter and Medium which provide a basic dashboard with time graphs or tear sheets where users can see the evolution of select parameters such as views, reactions and mentions.

Example: Data Visualization (Medium)

![Screenshot from 2020-06-08 13-34-57](https://user-images.githubusercontent.com/60417145/84062016-e45c6f00-a98c-11ea-8ba1-6f486b1a1766.png)

Example: Tear sheet (Twitter)

![Screenshot from 2020-06-08 13-19-20](https://user-images.githubusercontent.com/60417145/84060755-bd9d3900-a98a-11ea-89c0-5b58131ad36d.png)

Happy to lend a hand with this feature :)

**Comment by citizen428** [comment]
Thanks for the report @icncsx. This seems very similar to #6608, would you mind adding a comment over there and closing this issue? It's easier to track things this way.

Also see the following comment: https://github.com/thepracticaldev/dev.to/issues/6608#issuecomment-609945531

**Comment by icncsx** [comment]
Closing this issue because it's near-duplicate.
