### ISSUE TITLE
Unable to unpin GitHub repositories

### ISSUE THREAD

**Issue by acostalima** [thepracticaldev/dev.to#8353]
**Describe the bug**

I'm not being able to unpin GitHub repositories from my profile either because the option does not show up anywhere or it can't be done at the moment.

**To Reproduce**

1. Go to your profile page
2. Verify there is no option to customize pins
3. Click on 'Edit Profile' button
4. Click on 'Integrations' on the left-side menu
5. Wait for the repositories to load and then confirm pinned repositories do not show up

**Expected behavior**

An option to customize current pins should be available somewhere in the profile page.

**Desktop (please complete the following information):**

- OS: macOS Catalina v10.15.4
- Browser: Chrome
- Version: 80.0.3987.163

**Additional context**

I'm not sure whether this may be related or not to the present issue but GitHub repositories are taking a very long time to load and, many times, it even fails to load with HTTP error 503 (visible in the browser's console).

**Comment by jrg94** [comment]
Can confirm that this integration is an issue. I'm having similar issues on my end. See [the discussion](https://dev.to/acostalima/unpinning-github-repositories-3ggk) @acostalima and I had on DEV about it.

I haven't been able to get my repositories to even load to confirm the unpinning issue (https://dev.to/settings/integrations): 

```
An error occurred. Please check your browser console and email yo@dev.to for more help.
```

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
@acostalima can you check if it's now working for you as it is for me? thank you! https://dev.to/settings/integrations

**Comment by acostalima** [comment]
> @acostalima can you check if it's now working for you as it is for me? thank you! [dev.to/settings/integrations](https://dev.to/settings/integrations)

@rhymes yes, it's working now! How can I unpin repositories?

**Comment by rhymes** [comment]
@acostalima there's already is one, I think it's the same problem https://github.com/thepracticaldev/dev.to/issues/7751

Will work on it soon :)
