### ISSUE TITLE
Repositories still appears on profile sidebar after deleted from Github, but doesnt appear on configurations (impossible to remove them from the profile sidebar)

### ISSUE THREAD

**Issue by felippe-regazio** [thepracticaldev/dev.to#8377]
Deleted repositories still appear on integrations list. If you go to my profile https://dev.to/felipperegazio you will see two repositories on right sidebar. there were deleted, so they doesnt appear on configurations > integrations anymore (so i cant remove them from that list), but still appears on the sidebar with a 404 target link.

Try:

1. Integrate with github.
2. Pick a repository to show on your profile.
3. Delete this repository
4. Try to remove the deleted repo from your profile.

**Expected behavior**

The repositories on the sidebar must disappear when deleted from github, or the (remove) action must be linked to the repos already listed on the profile sidebar also.

**Screenshots**

Not needed since the link on the description tells the history.

**Desktop (please complete the following information):**

- OS: Ubuntu 18
- Browser: Chrome
- Version: 80.0.3987.132 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: N/A
- OS: N/A
- Browser: N/A
- Version: N/A

**Additional context**

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
@felippe-regazio could you try again? We shipped #8382 which should help!

**Comment by felippe-regazio** [comment]
Hello @rhymes !

If you visit my profile https://dev.to/felipperegazio and click on any of the repositories on my left side menu, you will see they doenst exist anymore. anyway they still there, and they still are not on the integrations list, so i still cant remove them.

**Comment by rhymes** [comment]
@felippe-regazio if you visit https://dev.to/settings/integrations, wait for the list to load and then visit https://dev.to/felipperegazio - do they disappear?

**Comment by felippe-regazio** [comment]
@rhymes  yes they disappeared, from the `/integrations` and from my profile side menu also now. i think the issue has been solved : )

**Comment by rhymes** [comment]
Thank you @felippe-regazio 

cc @citizen428
