### ISSUE TITLE
Use Fastly-Rails Gem

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/dev.to#838]
**Is your feature request related to a problem? Please describe.**
We have an custom version of clearing our cache through Fastly, that involves URLs. The [fastly-rails gem](https://github.com/fastly/fastly-rails) could streamline our process and make things smoother.

**Describe the solution you'd like**
We decide on whether or not to use the fastly-rails gem.

**Comment by benhalpern** [comment]
We do use Fastly-Rails gem already, but we don't follow it's exact prescribed cache clearing solution, mostly because we couldn't get it to work at first.

I'm in favor of continuing to look into improvements here.

**Comment by Zhao-Andy** [comment]
Believe we still want to do this.

**Comment by rhymes** [comment]
still an issue

**Comment by rhymes** [comment]
This should help [A Guide to Caching Your Rails Application With Fastly](https://thoughtbot.com/blog/a-guide-to-caching-your-rails-application-with-fastly)

**Comment by rhymes** [comment]
I believe we should keep this open. With everything we're learning now, through #4744 and #5543 we'll eventually use [fastly](https://rubygems.org/gems/fastly) and [fastly-rails](https://rubygems.org/gems/fastly-rails) more effectively, instead of manually calling endpoints with `HTTParty`

**Comment by rhymes** [comment]
Adding these resources about Fastly here, they might help who wants to tackle this:

- [Getting started with surrogate keys](https://docs.fastly.com/en/guides/getting-started-with-surrogate-keys)
- [Purging API cache with surrogate keys](https://docs.fastly.com/en/guides/purging-api-cache-with-surrogate-keys)
- [Checking cache](https://docs.fastly.com/en/guides/checking-cache)
- [Understanding cache HIT and MISS headers with shielded services](https://docs.fastly.com/en/guides/understanding-cache-hit-and-miss-headers-with-shielded-services)

**Comment by tannakartikey** [comment]
@rhymes [`fastly-rails`](https://github.com/fastly/fastly-rails) gem is deprecated. I am trying to give Rails update(https://github.com/thepracticaldev/dev.to/issues/2879) a try and stumbled upon your comments there:
https://github.com/fastly/fastly-rails/issues/87#issuecomment-605851817

Should we change the title of this issue to "Use  [fastly-ruby](https://github.com/fastly/fastly-ruby) gem" and then actually use it? `fastly` gem is compatible with Rails 6.

**Comment by rhymes** [comment]
Hi @tannakartikey, thanks for the update! 

Indeed is deprecated. We're in the process of removing the `fastly-rails` gem, see:

- https://github.com/thepracticaldev/dev.to/pull/7070
- https://github.com/thepracticaldev/dev.to/pull/7108
- https://github.com/thepracticaldev/dev.to/pull/7119
- https://github.com/thepracticaldev/dev.to/pull/7145
- https://github.com/thepracticaldev/dev.to/pull/7155

I'd suggest you hold off a bit until we've finished the process and updated `fastly-ruby` and verified everything works in production.

I'm going close this in the meantime as we're going in the opposite direction :)

We do have other blockers I think. If you don't mind I'm going to reserve the Rails 6 upgrade path to the DEV team as we've other blockers likely and we need to verify that everything works with our custom defaults (we don't use all the defaults of Rails 5.2 for example). 

Let me know if you have questions!
