### ISSUE TITLE
Error Page shows up when I try to write a post or change settings

### ISSUE THREAD

**Issue by Oghenebrume50** [thepracticaldev/dev.to#8383]
**Describe the bug**
I see the below error page when I log in to Dev.to try to make a post or try to change a setting(this happens when I click the save button)
![devto](https://user-images.githubusercontent.com/37092867/84248694-b3517b00-ab01-11ea-9f02-02d8fb421242.png)

**To Reproduce**

1. Go to  [Dev.to](https://dev.to/) 
2. Click on 'Sign in with Github' or 'Sign in with Twitter' 
3. Click on 'Write a post' 

**Expected behavior**
It should show the box that allows making a post  as seen in the screenshot below
![devtopost](https://user-images.githubusercontent.com/37092867/84249841-30312480-ab03-11ea-8567-303b3718058b.jpeg)

**Desktop:**

- OS: Linux
- Browser: Chrome and Firefox
- Version: 81.0.4044.129

**Smartphone**

- Device: Samsung S7
- OS: Andriod
- Browser: Chrome
- Version:

**Additional context**
I have done some debugging and I think this is associated with my account, I just do not know why.
1. I tried created another twitter account and signed in with that, it worked fine as expected
2. I asked friends to check with their account and everything seems fine.
3. I gave a friend my login credentials to try with my account from his end on his device and the error showed up again
It is worthy of note that someone else experienced this and said he fixed it with the steps below 
- Logout dev.to
- Flush DNS
- Clear Cache

But these steps did not work for me.

Also, this happens when I try to change my settings too, I noticed when I tried to change the theme.

**Comment by rhymes** [comment]
Hello @Oghenebrume50, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
