### ISSUE TITLE
Cannot change github link

### ISSUE THREAD

**Issue by jvanbruegge** [thepracticaldev/dev.to#84]
# _BUG_
### Current Behavior
Clicking the Gihub button on [this article](https://dev.to/supermanitu/understanding-observables) links to my old github username
### Expected Behavior
I can update my github username to be the current one

**Comment by Zhao-Andy** [comment]
Hey Jan, thanks for the heads up. This is a known bug and we have a separate ticket elsewhere so I'll be closing this issue. I've changed your GitHub username manually though. It might not reflect in the article yet because of caching, but you'll see the change on your profile page.

**Comment by jvanbruegge** [comment]
Weird, I used the search function before posting a new issue.

**Comment by Zhao-Andy** [comment]
Yeah, we've got a private repo since we're not _quite_ at open source level yet. 😅
