### ISSUE TITLE
Mis-alignment of "Select" and "Remove" buttons in Integrations panel

### ISSUE THREAD

**Issue by msarit** [thepracticaldev/dev.to#840]
**Describe the bug**
Related to Issue https://github.com/thepracticaldev/dev.to/pull/836. Initially, the "Select" and "Remove" buttons were aligned as expected (see Screenshot 1). But once I selected a repo to pin, the buttons all shifted out of alignment (see Screenshot 2).

**To Reproduce**

1. Go to https://dev.to/settings/integrations
2. "Select" and "Remove" buttons should appear neatly listed down the right side of the panel
2. Click on one of the "Select" buttons to pin a listed repo
3. "Select" and "Remove" buttons shift out of alignment

**Expected behavior**
I expected the buttons to remain aligned neatly to the right of the column (see Screenshot 1)

**Screenshots**

Screenshot 1 
![Screenshot #1](https://image.ibb.co/hV6Hmz/integrations_after_Changes.png)

Screenshot 2 
![Screenshot #2](https://image.ibb.co/eGmLPK/Screen_Shot_2018_10_05_at_6_58_10_PM.png)

**Desktop (please complete the following information):**

- OS: Mac OSX 10.13
- Browser: Chrome
- Version: 69.0.3497.100

**Smartphone (please complete the following information):**

Not Applicable

**Additional context**
Issue https://github.com/thepracticaldev/dev.to/pull/836 attempted to handle this issue, and this bug was not manifesting on the local dev environment.

**Comment by msarit** [comment]
I welcome any help with this issue, but I would like to tackle it please 🙏

**Comment by nickytonline** [comment]
I haven't looked at the code, but this can probably be fixed using Flexbox with [justify-content](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content) equal to `space-between`.

**Comment by benhalpern** [comment]
Fixed in #836 right? I'll close. Let us know if it needs to be re-opened.
