### ISSUE TITLE
Label Experience Level Scale in User Settings

### ISSUE THREAD

**Issue by michael-tharrington** [thepracticaldev/dev.to#8414]
**Is your feature request related to a problem? Please describe.**

Yes, as a user it's unclear how the 1-5 experience scale (Content Customization) is meant to be interpreted in https://dev.to/settings/ux. It's not clearly stated the 1 is for novices and 5 for experts; folks could misinterpret this and think that is 1 is expert and 5 novice.

**Describe the solution you'd like**

I think we should label each number in the scale to correspond to the labeled scale in our [moderation panel](https://dev.to/devteam/changelog-updated-mod-tooling-1ill) (see figure 1).

**Additional context**

Figure 1:

![mod panel experience level scale](https://user-images.githubusercontent.com/16007075/84413563-c9813900-abde-11ea-8bc2-68c9c8095e90.png)

It might look vaguely like this:

![experience scale in settings](https://user-images.githubusercontent.com/16007075/84413936-4dd3bc00-abdf-11ea-9300-24b70943e836.png)

I think it'd be fine to put the text inside each button or underneath, whichever looks better.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by nickytonline** [comment]
I think labelling these is a good idea to avoid confusion of the scale.

**Comment by Oghenebrume50** [comment]
@rhymes I will like to work on this

**Comment by Ridhwana** [comment]
@Oghenebrume50 I've assigned the issue to you 😊

**Comment by rahuldkjain** [comment]
I would love to work on this issue

**Comment by rhymes** [comment]
@rahuldkjain I've assigned you to the issue :) Thank you!

**Comment by rhymes** [comment]
Wasn't this solved by https://github.com/thepracticaldev/dev.to/pull/8454 ?

cc @Oghenebrume50 @jacobherrington

**Comment by Oghenebrume50** [comment]
Yes it was @rhymes the PR was merged it shows up on the website too :+1:

**Comment by rhymes** [comment]
Thanks @Oghenebrume50!
