### ISSUE TITLE
HTML entities on home feed

### ISSUE THREAD

**Issue by Rafi993** [thepracticaldev/dev.to#8433]
**Describe the bug**
  Escaped HTML entity is rendering on home feed but it renders correctly in other places
  
**To Reproduce**
  Look for an article with HTML entity in the title

**Expected behavior**
  HTML entity should render correctly in the home feed rather than being escaped

**Screenshots**
### Home feed
![feed](https://user-images.githubusercontent.com/8092120/84461275-aeb7ce80-ac89-11ea-8a07-d4ae1d04d3d2.png)
### Search
![search](https://user-images.githubusercontent.com/8092120/84461306-c0997180-ac89-11ea-8c87-4052025c364b.png)
### Main article
![content](https://user-images.githubusercontent.com/8092120/84461334-d73fc880-ac89-11ea-8f9a-744e22356538.png)
### Reading list
![reading_list](https://user-images.githubusercontent.com/8092120/84461346-e0309a00-ac89-11ea-8098-5c54d670ef24.png)

**Desktop:**

- OS: Ubuntu 18.04.4 LTS
- Browser: Brave
- Version: 1.9.80 Chromium: 81.0.4044.138 (Official Build) (64-bit)

**Comment by Rafi993** [comment]
This bug is related to bug https://github.com/thepracticaldev/dev.to/issues/7175

**Comment by Rafi993** [comment]
If this bug is up for grabs I would like to help.

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
Thanks for the issue and offering to help @Rafi993, I assigned you now.

**Comment by Rafi993** [comment]
Thanks @citizen428
