### ISSUE TITLE
Some parts of a markdown file contained in a gist are not readable

### ISSUE THREAD

**Issue by joaofbantunes** [thepracticaldev/dev.to#848]
**Describe the bug**
When adding a gist that contains a markdown file, some parts of the file (in this case, a block of code) are not readable.

**To Reproduce**

1. Go to [this post](https://dev.to/joaofbantunes/episode-002---project-structure-plus-first-application---aspnet-core-from-0-to-overkill-5dlc)
2. Scroll down to the gist after the title "Repository structure"
3. See that the gist that includes a markdown file is not rendered correctly

**Expected behavior**
Better readability of the text.

**Screenshots**
<img width="1260" alt="screenshot 2018-10-07 at 18 13 21" src="https://user-images.githubusercontent.com/3763454/46584570-eace7100-ca5c-11e8-9847-6fc1f66eb330.png">

**Desktop (please complete the following information):**

- OS: MacOS Mojave
- Browser Firefox and Safari
- Version 63.0b12 and 12.0 (14606.1.36.1.9)

**Smartphone (please complete the following information):**

- Device: OnePlus 5T
- OS: Android 8.1
- Browser: installed PWA using Firefox
- Version 62.0.3

**Additional context**
The gist I'm including https://gist.github.com/joaofbantunes/8682c92ccd077d13ab719a2653b8ff55

**Comment by benhalpern** [comment]
Thanks for the issue

**Comment by rpalo** [comment]
I think I've got this one figured out.  Let me double-check and I can create a pull request.
