### ISSUE TITLE
Reporting comments

### ISSUE THREAD

**Issue by Mathiu** [thepracticaldev/dev.to#85]
### User Story
Just saw a comment on https://dev.to/supermanitu/understanding-observables/comments which obviously is an XSS attack and I wanted to report it, but there is no report button beside report abuse under the comments, which have a different purpose I guess.

### Definition of Done
Adding "report" button to each comment would be very useful in this case, but it would add more work to moderate the comments for you, so maybe adding some better filters or validators would be a better solution.

Keep up the good work!

**Comment by Zhao-Andy** [comment]
Hey, thanks for the heads up. :) That's definitely a feature we're considering and working on as of late. We'll keep you updated when we've found the right solution and have it live.
