### ISSUE TITLE
Follow button text is missing

### ISSUE THREAD

**Issue by yokimpillay** [thepracticaldev/dev.to#856]
**Describe the bug**
The button to follow someone back from the Notifications is missing the "Follow" text.

**11/10 Edit:** @M0nica has pointed out the following, and I can confirm that the same is happening on my side:

> I just checked and noticed that my most recent followers in notifications have the "+Follow Back" button but lower down in my notifications similar notifications appear without the button like the screenshot above.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to your Notifications
2. Scroll down and find a notification for a new follower
3. Look at the blue "Follow" button.

**Expected behaviour**
I expected to see the "Follow" text in the button.

**Screenshots**
![screenshot 2018-10-08 at 13 55 11](https://user-images.githubusercontent.com/25602516/46607610-e14b1480-cb01-11e8-884e-c000a0ce38f6.png)

**Desktop (please complete the following information):**

- OS: MacOS Mojave 10.14 Beta (18A377a)
- Browser: Chrome & Firefox
- Version Chrome - 69.0.3497.100, Firefox - 62.0.3

**Comment by benhalpern** [comment]
Interesting, is this happening all the time? Even when you refresh?

**Comment by yokimpillay** [comment]
@benhalpern Yeah, I've tried in normal and 'private' browsing modes on both browsers. I have also just tried on Safari normal & private, and received the same result.

Is there anything else I can try help find for you?

**Comment by yokimpillay** [comment]
I'm going to try and see if the same thing happens on a local development environment today.

**Comment by M0nica** [comment]
I just checked and noticed that my most recent followers in notifications have the "+Follow Back" button but lower down in my notifications similar notifications appear without the button like the screenshot above.

**Comment by yokimpillay** [comment]
@M0nica I've also just noticed the same thing on my side, thanks for bringing it up! I'm going to edit the initial post here with this news.

**Comment by jessleenyc** [comment]
We just made some changes to notifications. Is this still happening?
