### ISSUE TITLE
Spelling Error on Profile Page

### ISSUE THREAD

**Issue by EvanOman** [thepracticaldev/dev.to#86]
# _BUG_
### Current Behavior

"Hacking" is spelled "Haoking" on profile page

### Expected Behavior

"Hacking" should be spelled "Hacking"

### Additional Info (steps to replicate, device/browser, helpful links)

Just check any profile page: https://dev.to/evanoman

### Screenshots

![image](https://user-images.githubusercontent.com/1807879/30120878-b3d0092a-92ef-11e7-8db0-8b66f46ad477.png)

**Comment by Zhao-Andy** [comment]
Hmm strange, it's `Hacking` on my page:
![screen shot 2017-09-06 at 11 55 01 am](https://user-images.githubusercontent.com/17884966/30121641-3e941b0a-92fa-11e7-9baa-92867811e1bc.png)

Could I get your browser version and OS?

**Comment by EvanOman** [comment]
The plot thickens...when I zoom in the "o" turns into a "c"

![image](https://user-images.githubusercontent.com/1807879/30122487-3996ab46-92f4-11e7-9518-71e8b0131aec.png)

Also when I copy the text it comes out as "Hacking"

OS: Windows 10
Browser: Google Chrome Version 61.0.3163.79 (Official Build) (64-bit)

Here are my font settings:

![image](https://user-images.githubusercontent.com/1807879/30122598-99f07f76-92f4-11e7-9fc2-0427e43e22bd.png)

**Comment by Zhao-Andy** [comment]
Not too major of a problem, but it is a funny problem. I'm guessing it's because the default font you have is Times New Roman. 

We're going to close this issue though since it's not a _major_ concern. Thanks for the report again :)
