### ISSUE TITLE
Clicking on "Start a meta discussion" doesn't show "meta" tag autofilled in new post

### ISSUE THREAD

**Issue by ayush-sharma** [thepracticaldev/dev.to#860]
The right-sidebar on dev.to has a new `#meta` box which lists posts tagged with the `meta` tag. The link to START A NEW META DISCUSSION opens a New Post page, but the `tags` in that page does not contain the `meta` text.

**To Reproduce**
1. Click the "START A META DISCUSSION" link in the right sidebar
2. In the New Post window `tags` is empty.

**Expected behavior**
The New Post window should have the `meta` tag in `tags` already.

**Screenshots**
![screenshot from 2018-10-08 22-55-53](https://user-images.githubusercontent.com/9398523/46624071-57c13400-cb4d-11e8-9b23-07d942203f57.png)

**Desktop*

- OS: Debian 9
- Browser: Firefox
- Version: 62.0.3 (64-bit)

**Comment by benhalpern** [comment]
Thanks, fixed!
