### ISSUE TITLE
Generalisation of logo in editor required

### ISSUE THREAD

**Issue by leewynne** [thepracticaldev/dev.to#8678]
**Describe the solution you'd like**

Although in the editor <%= logo_svg %> is implemented, I think it picking up a hardcoded svg located from the 'crayons-article-form__logo' class. This means that the Dev logo is rendered rather than the site logo.

**Additional context**

View showing logo_svg is at app/views/articles/_v2_form.html.erb
Hardcoded Dev logo is pulled in from app/javascript/article-form/components/Header.jsx (crayons-article-form__logo)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).
