### ISSUE TITLE
Brave browser + google translate compatibility issue

### ISSUE THREAD

**Issue by chenge** [thepracticaldev/dev.to#868]
I'm from Chinese. Your site is good, so I tried to use Google translate but failed.

Thanks.

**Comment by jessleenyc** [comment]
Thanks for the request. Are you seeing something similar to this? https://dev.to/mfnkuqcj5s9t/devto-when-google-translate-it-e5k

**Comment by chenge** [comment]
> Thanks for the request. Are you seeing something similar to this? https://dev.to/mfnkuqcj5s9t/devto-when-google-translate-it-e5k

No, it showed a huge icon of Connect, no any text. I tried in three browser. Do you need a screenshot?

**Comment by jessleenyc** [comment]
Yes, can you send a screenshot and tell us your device/make?

**Comment by chenge** [comment]
I use mac air, Brave browser(Chrome, Safari).  And I use lantern to use google. I remember without lantern the result is the same.

![2018-10-11 8 31 32](https://user-images.githubusercontent.com/252333/46773495-4d12c480-cd30-11e8-8548-a0e43d9c998b.png)

**Comment by jessleenyc** [comment]
Updated the title on this to be a little more clear. This issue is approved for anyone who wants to investigate!
