### ISSUE TITLE
Enable selecting view for Codepen Embed

### ISSUE THREAD

**Issue by nathansebhastian** [thepracticaldev/dev.to#869]
**Is your feature request related to a problem? Please describe.**
I want to display Codepen embed in a split view format on load, so that readers can view both code and render result at once. Unfortunately right now the view is hardcoded as `default-tab=result` 
We can add optional parameters like in Glitch embed 

Example:
{% codepen https://codepen.io/twhite96/pen/XKqrJX default-tab=html,result %}

{% codepen https://codepen.io/twhite96/pen/XKqrJX default-tab=js,result %}

If there is no default-tab parameter, assign `result` as default

**Comment by jessleenyc** [comment]
Thanks for the issue. @maestromac feel like you might have some thoughts on this one.

**Comment by benhalpern** [comment]
Definitely the right call to do like Glitch.

My question is do we want `default-tab=` or do we just want that second parameter to _be_ "default tab", so it would look like:

{% codepen https://codepen.io/twhite96/pen/XKqrJX js,result %}

Or something like that.

Are there any other params we may care about?

**Comment by nathansebhastian** [comment]
Hmm I think we can include optional height parameters as well and that's it.

**Comment by nathansebhastian** [comment]
@maestromac @benhalpern please take a look at the PR.

I have added default-tab parameter in creating the codepen embed. Also I think it's alright for `height` to just use the default for now..

**Comment by maestromac** [comment]
Resolved with #880
