### ISSUE TITLE
Search Queries with "%" Error Out

### ISSUE THREAD

**Issue by dvdmuckle** [thepracticaldev/dev.to#87]
Currently, if one searches on dev.to with a "%" in the query, the search will error out, as the "%" is not formatted properly. Expected behavior is that the input will be sanitized and replace the "%" with something else, so "100% coverage" might be formatted as "100%25+coverage."

![](https://i.imgur.com/zG7PeWE.png)

This errors out.

![](http://i.imgur.com/Tm2AxUk.png)

This works fine.

**Comment by Zhao-Andy** [comment]
Thanks for the heads up :)

**Comment by maestromac** [comment]
This is fixed! Let us know if otherwise.
