### ISSUE TITLE
Not able to comment

### ISSUE THREAD

**Issue by necmettin** [thepracticaldev/dev.to#8702]
**Describe the bug**

Commenting does not work (for me, somehow everybody else is able to do that just fine).

When I write a comment and press Submit, I see a 404 for POST https://dev.to/comments in DevTools.

I also can't update my profile as a side note (I'll check if I have signed in using both GitHub and Twitter).

But I can see everybody else able to comment just fine. I am beginning to think I am somehow blocked from DevTo, since this has been going on for months now.

**To Reproduce**

All I do is writing some comment and pressing Submit in any post.

**Expected behavior**

Being able to comment and have my comments appear in posts.

**Screenshots**

![Screen Shot 2020-06-16 at 11 18 52](https://user-images.githubusercontent.com/51944/84750104-88649c80-afc3-11ea-8756-d0ec53d7dc42.png)

**Desktop (please complete the following information):**

- OS: MacOS 10.15.5
- Browser: Firefox
- Version: 77.0.1

**Comment by rhymes** [comment]
Hello @necmettin, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
