### ISSUE TITLE
Feature Request: HTML Support in the Article editor

### ISSUE THREAD

**Issue by gogamic** [thepracticaldev/dev.to#8711]
I mean while writing a post instead of Markdown you can also add HTML it would be nice

THANKS

**Comment by jacobherrington** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
Hi @gogamic, did you try to use HTML tags? From our [editor guide](https://dev.to/p/editor_guide)

> Most of the time, you can write inline HTML directly into your posts.

Here's an example draft post:

https://dev.to/citizen428/test-4jkj-temp-slug-7748822?preview=078228c75e8cdb700aacd84c250129f6902fc4f5d8ad5a7e59ec26199f1f281392df9f0402237dc7f179cabb84e4ed4977029ae8b48cc73859f976cf

The article body I wrote:

```html
<b>Bold</b> and <i>italic</i> and a <a href="http://example.com">link</a>.
```

Can we close this issue?

**Comment by gogamic** [comment]
Ok
