### ISSUE TITLE
Display canonicals consistently on articles

### ISSUE THREAD

**Issue by michael-tharrington** [thepracticaldev/dev.to#8726]
@michael-tharrington commented on [Fri Nov 15 2019](https://github.com/thepracticaldev/tech-private/issues/314)

Currently, we allow folks two main ways of designating canonicals:
1. Publishing via RSS (importing an external blog in your dashboard)
2. Manually writing in the canonical on individual posts

When publishing via RSS, a note is generated beneath the title of the post that says:
"_Originally published at [insert-blog-name-and-link-to-canonical-URL]._"

However, when manually writing in the canonical on individual posts, there is no extra note generated beneath the title of the post.

Both methods should produce the same outcome, providing the noted attribution beneath the title. 

---

@michael-tharrington commented on [Wed Jun 17 2020](https://github.com/thepracticaldev/tech-private/issues/314#issuecomment-565489561)

Just making a note that there's a user, Dvir (https://dev.to/dejavo), who wants to be updated when this goes into place. Some of their articles wouldn't import via RSS, so they manually imported them, but they'd prefer for it to be uniform.

They wrote an issue on their RSS here - https://github.com/thepracticaldev/dev.to/issues/5086

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by ThomasArdal** [comment]
I would love to see this implemented. I cross post on DEV and input the canonical URL manually.

**Comment by citizen428** [comment]
👍 a friend recently got confused by this, as they noticed it on posts imported via RSS but it didn't show up on their posts with an explicit canonical URL set.
