### ISSUE TITLE
New design broken on article info

### ISSUE THREAD

**Issue by viclafouch** [thepracticaldev/dev.to#8729]
**Describe the bug**

## Desktop 
![image](https://user-images.githubusercontent.com/23353836/84914814-5c791200-b0bc-11ea-9725-2f73477ad773.png)

## Mobile
![image](https://user-images.githubusercontent.com/23353836/84915263-dd380e00-b0bc-11ea-8068-693e64f284d6.png)

I'm in chrome incognito, without any extension.. I am the only one ?

And on my mobile, there is responsive.. 

**To Reproduce**

Example with this article : https://dev.to/viclafouch/5-useful-and-modern-custom-hooks-for-your-react-app-3dl

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Catalina
- Browser: Chrome
- Version: 83.0.4103.106 

**Smartphone (please complete the following information):**

- Device: Android Pixel 3
- OS: Android
- Browser: Chrome
- Version: 83.0.4103.106 

**Additional context**

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
@viclafouch can you try to do a force refresh? let us know if that fixes it

**Comment by viclafouch** [comment]
Still broken after a Force refresh on Chrome incognito (without be logged) : 

![image](https://user-images.githubusercontent.com/23353836/84917130-386b0000-b0bf-11ea-94e8-bb1e1b66ef74.png)

**Comment by viclafouch** [comment]
After a Force Refresh on Chrome Incognito (and logged in): 

![image](https://user-images.githubusercontent.com/23353836/84917297-6b14f880-b0bf-11ea-8bf6-106cc3704b12.png)

**Comment by nickytonline** [comment]
This definitely looks like a caching issue. I'd say it's either potentially the service worker of some HTML partials keeping refs to old CSS in the server-side cache

**Comment by jacobherrington** [comment]
Hey @viclafouch, are you still seeing this broken sidebar?

**Comment by viclafouch** [comment]
Hey @jacobherrington , nop, it's fixed ! thanks ! 

![image](https://user-images.githubusercontent.com/23353836/85470990-19cda300-b5b0-11ea-989f-b1e3161f6f39.png)
