### ISSUE TITLE
Profile Image on User Page not updating for some posts

### ISSUE THREAD

**Issue by rrampage** [thepracticaldev/dev.to#873]
**Describe the bug**
Profile picture not updating on some posts on the profile page.

**To Reproduce**

1. Go to my [profile page](https://dev.to/rrampage)
2. Scroll through the posts. Some posts have the correct profile picture while a few have the old profile picture

I have tried the following:
1. Visiting the page usually
2. Visiting with browser extensions disabled
3. Ctrl + F5 with browser extensions disabled
4. Visiting in Incognito mode without signing in to dev.to

The network pane of debug tools in Firefox shows fetches to both the profile pictures being made:
1. [Old Pic](https://res.cloudinary.com/practicaldev/image/fetch/s--UTFqy4-k--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://thepracticaldev.s3.amazonaws.com/uploads/user/profile_image/35035/18fc440e-da54-4b0a-8649-33332dbb9d21.png)
2. [New Pic](https://res.cloudinary.com/practicaldev/image/fetch/s--qBhB59mX--/c_fill,f_auto,fl_progressive,h_320,q_auto,w_320/https://thepracticaldev.s3.amazonaws.com/uploads/user/profile_image/35035/f095885d-5235-4d65-8998-55c42b8764d4.jpg)

**Expected behavior**
All posts in the profile page should have the same profile picture.

**Screenshots**

![devto-profile-pic-bug](https://user-images.githubusercontent.com/1277046/46686378-be118980-cc15-11e8-913c-818633ca2521.png)
**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: Firefox
- Version: 62.0

**Additional context**
I updated my profile picture a few weeks ago. Prior to that, it was the default picture.

**Comment by jessleenyc** [comment]
Interesting. I suspect this has to do w/ the way some articles are cached? Thoughts on this @benhalpern?

**Comment by jessleenyc** [comment]
I believe this was a caching issue that has since been fixed. Closing for now  - if you're still experiencing it, please let us know. Thanks!

**Comment by arsadvc** [comment]
Profile Image not updating even after we change

**Comment by ivanlewaschiw-dextra** [comment]
Seems to be happening again, my profile image is not updating after change

**Comment by ivanlewaschiw-dextra** [comment]
> Seems to be happening again, my profile image is not updating after change

Had to change it twice to update.

**Comment by KGoreczny** [comment]
> > Seems to be happening again, my profile image is not updating after change
> 
> Had to change it twice to update.

Same, 3 years later...
