### ISSUE TITLE
Connect sidecar iframe flashes on re-render

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/dev.to#8748]
Seems like re-render of the whole component is now re-rendering sidecar, including iframe, which causes a flash.

To repoduce:

-> Connect, click channel name -> submit new comment (causing re-render).

In the past the iframe did not re-render in this context.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).
