### ISSUE TITLE
Republishing a post alerts all followers like it was new

### ISSUE THREAD

**Issue by chrisvasqm** [thepracticaldev/dev.to#875]
**Describe the bug**

Users can potentially spam their followers by republishing an old post.

**To Reproduce**

1. The user must be logged in.
2. Have at least 1 published post.
3. Go to Dashboard.
4. Click on an already published post.
5. Set the `published` value to `false`.
6. Save changes.
7. Set the `published` value back to `true`.
8. Saves changes.

And now every follower should receive a notification as if that post was a new one.

**Expected behavior**

I'm not really sure what would be the ideal behaviour since I'm not sure if this was an intended feature, but it might be used inappropriately by some users.

It can be useful if a post was edited, but the way I've seen it happen doesn't involve doing any changes to the post itself, just the `published` value.

**Desktop:**

- OS: MacOS Mojave 10.14
- Browser: Safari
- Version 12

**Comment by chrisvasqm** [comment]
Just noticed the Editor v2 that is currently in Beta doesn't have the `published` field and it's managed via 2 different buttons: `Save Draft` and `Publish`.

I have yet to test if this behaviour is still present, but it would be nice to keep it in mind.

**Comment by theoutlander** [comment]
Do we know if this is working at the moment if you toggle publish? I had tried it earlier and don't think it worked.

**Comment by sagar-gavhane** [comment]
> Do we know if this is working at the moment if you toggle publish? I had tried it earlier and don't think it worked.

Recently, I checked with my previous post. My post has been notified to all my follower. It's weird trick and if anyone finds out, he can misuse it.

**Comment by jessleenyc** [comment]
@Zhao-Andy since we just rewrote the notifications, can you see if this is still an issue?

**Comment by jessleenyc** [comment]
This should be fixed!
