### ISSUE TITLE
Editor's title placeholder is squashed on Safari

### ISSUE THREAD

**Issue by maestromac** [thepracticaldev/dev.to#8751]
**Describe the bug**
The title area in the editor is squashed and I can't see what I'm typing. See the image below.

**To Reproduce**
1. Open Safari and navigate to https://dev.to/new
2. See the title is broken.

**Expected behavior**
The title shouldn't be squashed.

**Screenshots**
![Kapture 2020-06-17 at 16 49 22](https://user-images.githubusercontent.com/15793250/84949119-bb3d8c00-b0ba-11ea-87ed-4e4e726945ff.gif)

**Desktop (please complete the following information):**

- OS: MacOS 10.15.5
- Browser: Safari 
- Version: 13.1.1

**Additional context**
Doesn't happen on any other popular browser

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by maestromac** [comment]
It kind of resolved it self 🤷

**Comment by vaidehijoshi** [comment]
@maestromac you must have recently made a sacrifice to the safari gods 😛  it's the only explanation!! 😉
