### ISSUE TITLE
Can not scroll Editor's textarea on Safari

### ISSUE THREAD

**Issue by maestromac** [thepracticaldev/dev.to#8753]
**Describe the bug**
I can't seem to scroll the texture when using Editor on Safari.

**To Reproduce**
1. Open Safari and navigate to https://dev.to/new
2. Enter multiple lines into the editor.
3. Try scrolling

**Expected behavior**
Scroll shouldn't be broken

**Screenshots**

What's happening here is when I scroll, it's trying to scroll the whole page instead of just the textrea.
![Kapture 2020-06-17 at 16 55 40](https://user-images.githubusercontent.com/15793250/84949560-71a17100-b0bb-11ea-9be1-55b97ea4f361.gif)

**Desktop (please complete the following information):**

- OS: MacOS 10.15.5
- Browser: Safari 
- Version: 13.1.1

**Additional context**
Doesn't happen on any other popular browser

**Comment by ludwiczakpawel** [comment]
Fix is coming!

Also.. Safari is the new IE.
