### ISSUE TITLE
"Send" button in listing does not work 

### ISSUE THREAD

**Issue by Rafi993** [thepracticaldev/dev.to#8762]
**Describe the bug**

When you click on the "Send" button on listing nothing happens (there is no network call shown in chrome dev-tools too)

**To Reproduce**
 1. https://dev.to/listings/
 2. Select an item in listing
 3. Type message in reply box and click send
 4. Nothing happens

**Expected behavior**

The message gets sent

**Screenshots**

![send_button](https://user-images.githubusercontent.com/8092120/84990985-89cccb00-b163-11ea-89cd-bd0eb43e8488.png)

**Desktop:**
- OS: Ubuntu 18.04
- Browser: Brave
- Version: 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by Rafi993** [comment]
Hi there if this issue is not yet taken I would like to help

**Comment by nickytonline** [comment]
So just to be clear what the issue is @Rafi993. The handler for the button is named incorrectly, i.e. the wrong prop is passed in, so nothing happens, correct?

**Comment by Rafi993** [comment]
> So just to be clear what the issue is @Rafi993. The handler for the button is named incorrectly, i.e. the wrong prop is passed in, so nothing happens, correct?

yes

**Comment by Rafi993** [comment]
The handler was passed as **onChange** in the prop but the prop **onChangeDraftingMessage** was being used.
