### ISSUE TITLE
footer display in desktop is awkward

### ISSUE THREAD

**Issue by hashmateteam** [thepracticaldev/dev.to#8770]
![image](https://user-images.githubusercontent.com/22725431/85046011-3e3d1000-b1a9-11ea-85ac-dd8e273a7ea8.png)

**Comment by benhalpern** [comment]
I think this is most likely a caching issue as we have a new footer but there might be some old html mixing with new css. Should go away by tomorrow.

**Comment by citizen428** [comment]
To our amazing contributors: this is probably a caching issue that will most likely resolve itself. If not, issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by jacobherrington** [comment]
I believe this was indeed because of the cache and this issue can probably be closed.
