### ISSUE TITLE
I can't update my user profile

### ISSUE THREAD

**Issue by dev998** [thepracticaldev/dev.to#8771]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

I can't update my user profile

**Comment by maestromac** [comment]
Hello @dev998 , this looks an issue specific to your account. Please email yo@dev.to for more help.
