### ISSUE TITLE
Broadcast Announcement being displayed in Mod Tools.

### ISSUE THREAD

**Issue by ludwiczakpawel** [thepracticaldev/dev.to#8774]
**Describe the bug**

The broadcast announcement is being rendered within mod tools panel. Looks like this panel is using iframe to load mod tools and that's probably the reason.

**To Reproduce**

1. As an admin, go to `/internal`.
2. Create and activate broadcast announcement.
3. As a mod go to any post. (do not dismiss the broadcast panel)
4. Open mod tools (icon in bottom right corner of the screen)
5. See the additional broadcast announcement  right there?

**Expected behavior**

To not have a broadcast announcement in mod tools.

**Screenshots**

[Video](https://d.pr/v/ltCl5Z)

**Desktop (please complete the following information):**

- OS: macOS 10.15.4
- Browser: Chrome
- Version: 83.x

**Comment by vaidehijoshi** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.

**Comment by jacobherrington** [comment]
Continuing the discussion for this issue in places outside of the mod tools (like connect) in https://github.com/thepracticaldev/dev.to/issues/8983
