### ISSUE TITLE
Remove hidden comments from notifications

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#8788]
**Is your feature request related to a problem? Please describe.**
I recently hid a rude comment from one of my articles and did not appreciate seeing it again on my notifications feed. 

**Describe the solution you'd like**
If an author hides a comment on their post, remove that comment from their notifications.

**Additional context**
Just noting that I don't think this is high priority.

**Comment by citizen428** [comment]
To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by Rafi993** [comment]
Hi there, If this issue is not yet taken I would like to help.

**Comment by Ridhwana** [comment]
Thanks @Rafi993 I've assigned you :)
