### ISSUE TITLE
Article Posted Date and Author Card Posted Date do not match

### ISSUE THREAD

**Issue by TerabyteTiger** [thepracticaldev/dev.to#8789]
**Describe the bug**

At the top of [this post](https://dev.to/thagomizer/contact-tracing-and-exposure-notification-2b75) it says "May 27 Originally published at thagomizer.com on May 27, 2020" 

![image](https://user-images.githubusercontent.com/16465776/85161332-9c133b80-b22d-11ea-8979-a6304431ac8a.png)

At the bottom of the post at the Writer Profile it shows as "Posted on Aug 21 '19"

![image](https://user-images.githubusercontent.com/16465776/85161306-93226a00-b22d-11ea-81d9-5b98e77e9e78.png)

**To Reproduce**

1. Go to https://dev.to/thagomizer/contact-tracing-and-exposure-notification-2b75
2. Note the publish date under the post's title
3. Scroll down to About Author Block
4. Note that a different published date is listed.

**Expected behavior**

The date on the author profile card should match the date at the top of the page (which appears to be the correct date, particularly given the contents of this article in particular).

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Edge Beta (Chromium Build)
- Version: 84.0.522.20 (Official build) beta (64-bit)

**Additional context**

This may be submitted already

**Comment by citizen428** [comment]
Thanks for the issue!

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
I'm a bit confused as to how this happens, as all the relevant columns for this article seem to have the right 

<img width="1154" alt="Screen Shot 2020-06-22 at 12 06 44" src="https://user-images.githubusercontent.com/47985/85250469-dc1e2c80-b480-11ea-9529-af48c75271bf.png">

The relevant helpers (`readable_publish_date` in `app/models/article.rb`) and `should_show_crossposted_on?` in `app/helpers/articles_helper.rb`) seem to only use this timestamp, so it's not clear to me where the "Posted on Aug 21 '19" originates.

**Comment by rhymes** [comment]
I see the partial is wrapped within a cache block but it shouldn't matter:

https://github.com/thepracticaldev/dev.to/blob/7d73872afb6a2f3417cd7970166cb0c86f6d7cc0/app/views/articles/show.html.erb#L205-L214

**Comment by maestromac** [comment]
@rhymes I believe that's actually the problem. The cache key `"article-about-author-#{@user.id}-#{@user.updated_at}"` is based on the first article visited (within 100 hours) and reused on all articles by the same author. This bug is happening to my older articles too.

**Comment by rhymes** [comment]
oooh! yeah! I misread `@article.updated_at`. That's definitely it, great catch @maestromac!

**Comment by takmar** [comment]
Hi there. Can I take this? I would like to help.

**Comment by nickytonline** [comment]
I've assigned the issue to you @takmar.

**Comment by takmar** [comment]
@nickytonline 
I tried to fix this. But this is already fixed by https://github.com/thepracticaldev/dev.to/pull/9159.

**Comment by nickytonline** [comment]
Closing as this is fixed in #9159.
