### ISSUE TITLE
support for publications / custom domain mapping

### ISSUE THREAD

**Issue by gokatz** [thepracticaldev/dev.to#88]
# _Feature_
### Request
I'm just wondering if we can have hosted pages/custom domains for us (similar to **medium publication** and map it to my **domain/subdomain**). If we can achieve this, **dev.to** will be a single hub for tech posts, I believe. 

### Definition of Done
Developers can make their own publications page (or even their company's) to host all their tech updates and posts. Eventually, we can map the publication to our own custom domains like when accessing **_writeups.myname.com_** it will serve my own dev.to publication page without URL redirection (URL must be my domain name).

### Notes
suggestions are welcome for improvements.

**Comment by Zhao-Andy** [comment]
Hey @gokatz, thanks for the feedback. This is an idea that we've thought about, but we're going to move away from this direction for now in order to prioritize other tasks (like open sourcing the repo).

**Comment by autoferrit** [comment]
Are there any chances you guys might be considering this again? would love to see this. I would happily pay for it.

**Comment by avelino** [comment]
Is this feature working? Can I put a personal domain to my profile? @benhalpern

**Comment by danielbayerlein** [comment]
Is it now possible?

**Comment by rhymes** [comment]
Hi @danielbayerlein, I don't think this feature exist as of today

**Comment by vmasek** [comment]
I'd love this, we are considering moving from medium and this would be a killer feature
