### ISSUE TITLE
If katex overflows horizontally there is no scroll option

### ISSUE THREAD

**Issue by wayofthepie** [thepracticaldev/dev.to#8812]
**Describe the bug**
If katex overflows horizontally, there is no way to scroll. Here is an example on mobile:
![image](https://user-images.githubusercontent.com/1102174/85228225-2e584280-b3da-11ea-8791-56f107a6264d.png)

On the web version of `dev.to` this looks as follows:
![image](https://user-images.githubusercontent.com/1102174/85228269-711a1a80-b3da-11ea-8a71-91b065e222f9.png)

If there is overflow on the web version there is also no way to scroll horizontally see [this test post](https://dev.to/wayofthepie/test-katex-overflow-56j6-temp-slug-7812927?preview=ce2562f79e095273b5ae803f95fb2eabf6c6bbee4d89f3193ae246251a3b39e5b810bdf8470ed3480c5f8489803e6aa024620fd9b1f9891fbda5d093). 

![image](https://user-images.githubusercontent.com/1102174/85228375-074e4080-b3db-11ea-8b2e-c7cd75a62ec2.png)

**To Reproduce**
Add some katex which will overflow the page horizontally, for example:

```
{% katex %}
\begin{aligned}
(0 * 16 ^5) + (0 * 16 ^4) + (0 * 16 ^3) + (5 * 16 ^2) + (0 * 16 ^1) + (0 * 16 ^0) + (0 * 16 ^0) + (0 * 16 ^0) + (0 * 16 ^0) + (0 * 16 ^0) + (0 * 16 ^0) + (0 * 16 ^0) + (0 * 16 ^0) + (0 * 16 ^0) 
\end{aligned} 
{% endkatex %}
```

**Expected behavior**
When code blocks are longer than the width of the article pane they allow horizontal scrolling. Here is an example code block:
![image](https://user-images.githubusercontent.com/1102174/85228434-572d0780-b3db-11ea-89f3-8a4519fabd25.png)
I would expect the same horizontal scroll bar to appear for katex also.

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Browser: Firefox
- Version: 77.01

**Smartphone (please complete the following information):**

- OS: Android 9
- Browser: Firefox
- Version: 68.9.0

Thanks!

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).
