### ISSUE TITLE
Bad design with timestamp on Connect

### ISSUE THREAD

**Issue by thomasbnt** [thepracticaldev/dev.to#8813]
**Describe the bug**
The timestamp is not really beautiful on two lines. :smiley_cat: 

**To Reproduce**

[See Connect](https://dev.to/connect) on your smartphone.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/14293805/85228663-f86c8b80-b3e4-11ea-8208-69db17e930cc.png)

**Smartphone (please complete the following information):**

- Device: Xiaomi	
- OS: 
- Browser: Directly the App DEV
- Version: 1.4.1

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by ludwiczakpawel** [comment]
There's a PR that fixes this issue here: https://github.com/thepracticaldev/dev.to/pull/8829/files#diff-939505ce9f76e33dcd9c7f67fc871143R717 - should be soon merged and shipped.
