### ISSUE TITLE
facing an issues while login via github

### ISSUE THREAD

**Issue by macandro** [thepracticaldev/dev.to#8822]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hello @macandro, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
