### ISSUE TITLE
Loading bar gets stuck at times

### ISSUE THREAD

**Issue by madarsbiss** [thepracticaldev/dev.to#8830]
**Describe the bug**

Loading bar gets stuck for like 1 of 3 times I want to load DEV main page multiple times in a row.

**To Reproduce**
Try to reload Home by pressing DEV icon on top left multiple times.

**Screenshots**

![aaaa](https://user-images.githubusercontent.com/42511917/85315721-3a203380-b4c4-11ea-8567-26a13f3dc647.gif)

**Expected behavior**
Home page gets loaded and loading bar goes away.

**Desktop:**

- OS: Win10
- Browser: Chrome
- Version: 83.0.4103.106 (64-bit)

**Additional context**

The problem only exists once I'm signed in.
Tested on Firefox 77.0 (64-bit), the same result.

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by ludwiczakpawel** [comment]
Hey @madarsbiss thanks for this report! I've pushed the fix that will hopefully fix it.. Even though, this progress bar is a bit of black magic for me so I'm not sure tbh :D Give it couple more hours till we deploy the fix.

**Comment by madarsbiss** [comment]
@ludwiczakpawel thanks for looking into it :)
