### ISSUE TITLE
Change language for moderating comments to reflect Mod Panel language

### ISSUE THREAD

**Issue by michael-tharrington** [thepracticaldev/dev.to#8832]
**Is your feature request related to a problem? Please describe.**

Yes, the language for our mod tools is unclear when moderating comments (by appending `/mod` to a comment's URL; e.g. - https://dev.to/michaeltharrington/comment/ofm2/mod). Particularly the phrases "Mark As Spam" & "Flag As Abusive" placed beneath each vomit face aren't clear. 

In the mod panel (pic 1 below), we say "Flag to Admins" and "Flag User" which are more true to how the vomit face buttons function. The language for our mod tools should be uniform with what's used in our mod panel.

**Describe the solution you'd like**

We should change the phrase "Mark As Spam" to "Flag to Admins" when moderating comments. Also, we should change "Flag As Abusive" to "Flag User".

**Additional context**

Heads up that this mod functionality is only accessible for folks who have moderator ("trusted") privileges.

**pic 1: Mod panel language**

![Image 2020-06-22 at 2 26 27 PM](https://user-images.githubusercontent.com/16007075/85322550-82bff880-b494-11ea-8f24-30b49fc35577.png)

**pic 2: Language when moderating comments that needs to be replaced**

![Image 2020-06-22 at 2 20 47 PM](https://user-images.githubusercontent.com/16007075/85322180-e269d400-b493-11ea-8961-ba78b73a5393.png)

**Comment by citizen428** [comment]
To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for others please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by adfaris** [comment]
can I start working on this issue?

**Comment by Ridhwana** [comment]
Yes please go ahead :) Ive assigned you to the issue @adfaris.
