### ISSUE TITLE
Incorrect styling of "fork" in the repo list on the "Integrations" tab

### ISSUE THREAD

**Issue by madhavarshney** [thepracticaldev/dev.to#8834]
**Describe the bug**

The label "fork" in the GitHub repositories list in the "Integrations" tab of your settings is styled incorrectly.

**To Reproduce**

1. Make sure you have your GitHub account connected
2. Make sure you have  at least one forked repository
3. Go to the "Integrations" tab in your settings
4. Look at the list of repos

**Expected behavior**

The label "fork" is styled correctly. Seems like it originally looked like this:

![Correctly styled "fork" label](https://user-images.githubusercontent.com/7776/55839473-fd059680-5af5-11e9-9ba8-43789967bdf8.png)

**Screenshots**

<img width="1035" alt="Screen Shot 2020-06-22 at 11 45 08 AM" src="https://user-images.githubusercontent.com/40002855/85324158-2d78ec80-b47e-11ea-92b6-470d97619bd0.png">

**Desktop (please complete the following information):**

N/A

**Smartphone (please complete the following information):**

N/A

**Additional context**

This bug seems to have been introduced by https://github.com/thepracticaldev/dev.to/pull/6823#discussion_r397473497, which broke the following:

https://github.com/thepracticaldev/dev.to/blob/81fff248dd953f873161ed276ddb7f0ab576bcf8/app/javascript/githubRepos/singleRepo.jsx#L13-L15

**Comment by Zhao-Andy** [comment]
@madhavarshney good catch on the PR! I think we can add that code back in. Feel free to open a PR :)
