### ISSUE TITLE
Article stats page is misaligned

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#8848]
**Describe the bug**

The article stats page is not aligned

1. add the `pro` role to your local user
1. create an article
1. go to localhost:3000/article-slug/stats

**Expected behavior**

The page to be centered and to progressively shrink with smaller screens

**Screenshots**

![Screenshot_2020-06-23 Stats for Your Article - DEV Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/85376046-7f317d80-b537-11ea-8d50-070f9d0c3203.png)

**Desktop (please complete the following information):**

- OS: macOS 10.15.5
- Browser: Firefox
- Version:  78b9

**Comment by adfaris** [comment]
can I please work on this issue?

**Comment by rhymes** [comment]
@adfaris sure! I'm assigning you the issue, though I see you've already sent a PR :D
