### ISSUE TITLE
Report SPAMMY comments

### ISSUE THREAD

**Issue by mikgross** [thepracticaldev/dev.to#8850]
**Is your feature request related to a problem? Please describe.**

Recently I have received a SPAM comment coming from Malaysia. I believe this type of long, unrestricted comments shouldn't be accepted on the site.

**Describe the solution you'd like**

A button at the end or start of the message to report the specific comment as Spam or report the user.

**Describe alternatives you've considered**

..

**Additional context**

link to the comment: https://dev.to/mikgross/ultimate-terminal-customization-51c7

**Comment by rhymes** [comment]
@mikgross you can report comments this way (click on the three dots):

<img width="832" alt="Screenshot 2020-06-23 at 11 45 23 AM" src="https://user-images.githubusercontent.com/146201/85388966-17832e80-b547-11ea-918f-1f34cd39be4c.png">

let me know if that's what you were looking for

**Comment by Muhimen123** [comment]
Alternatively, as an author, you have the privilege to hide the comment so no one can see it(although I prefer reporting).

**Comment by mikgross** [comment]
Ah! thanks! I am with the dark theme and in this one the contrast is almost not existent. So I missed it. Maybe this is something that could be fixed in newer release:
![scfeenshot](https://ibb.co/NyRY1wY)

**Comment by rhymes** [comment]
@mikgross can you open a separate issue for that? Thank you!
