### ISSUE TITLE
New Medium stories are not fetched as drafts

### ISSUE THREAD

**Issue by DeJaVoo** [thepracticaldev/dev.to#8867]
**To Reproduce**

1. Click on your profile pic to open the drop down menu
2. Choose settings
3. Choose Publishing from RSS
4. Make sure your Medium feed is defined as follows: _https://medium.com/feed/@your_username_
My rss feed: https://medium.com/feed/@dvirsegal
5. Click on "Fetch feed now" and wait to "Your profile was successfully updated." message
6. Go to dashboard by either click on your profile drop down menu or from rss page hyperlink
 
**Expected behavior**

The new article is fetched and shown as draft

**Desktop (please complete the following information):**

- OS: windows 10
- Browser: Brave \ Chrome
- Version: Version 1.10.93 Chromium: 83.0.4103.106 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: OP3
- OS: Android 10
- Browser: Brave
- Version: 1.10.94

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by DeJaVoo** [comment]
HI, thank you for setting it as a bug and I sure hope it will be fixed soon.
Since I really on it to cross-post my article, at the moment it means some of my new articles from Medium are not being published on the dev community.

Again , thank you!

**Comment by citizen428** [comment]
@DeJaVoo No worries, I actually prioritized this since the ability to crosspost content to DEV is important. I believe I have found the problem now and hopefully will have a fix out shortly.

**Comment by DeJaVoo** [comment]
@citizen428 thank you. I'm actually looking at the code and console log to understand what's the issue. 
I see that: "Found 2 elements with non-unique id #user_feed_url" that it basically means there is a property without a unique id.

See SO answer: https://stackoverflow.com/questions/7017213/jquery-to-get-non-unique-ids-from-the-dom

**Comment by citizen428** [comment]
Thanks @DeJaVoo, but this is not the problem in this case. The issue here is related to our Ruby code for importing the feed and you won't see the exceptions raised there show up in the browser console.

**Comment by DeJaVoo** [comment]
@citizen428  :)
do you mean here:

**Comment by DeJaVoo** [comment]
By mistake

**Comment by citizen428** [comment]
Yes, that one and related classes. Draft PR with first results is up, but it's still not quite working 100%.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/8877
