### ISSUE TITLE
Ability to make collections

### ISSUE THREAD

**Issue by aHudspith** [thepracticaldev/dev.to#8878]
**Is your feature request related to a problem? Please describe.**

I'd love to be able to make collections of posts I like that relate to a particular topic.

**Describe the solution you'd like**

It would be like the reading list but I can make my own and make several of them.

**Describe alternatives you've considered**

I've considered adding them all to my reading list, but it is just to cluttered.

**Comment by rhymes** [comment]
Hi @aHudspith, is this previous request the same as yours ? https://github.com/thepracticaldev/dev.to/issues/710

Let me know, and thank you for opening this!

**Comment by aHudspith** [comment]
Yeah that looks the same 😄

**Comment by citizen428** [comment]
A somewhat wider scoped version of this is also in #1391, which asked for shareable filtered lists and has been approved to be worked on.
