### ISSUE TITLE
Tag limitation

### ISSUE THREAD

**Issue by ludwiczakpawel** [thepracticaldev/dev.to#8884]
**Describe the bug**

I was able to create a tag with only one special character `â` when adding a new post. But the generated page with tag did not work.

**To Reproduce**

1. Write a new post
2. Add a tag with some special character like `â` or `ą` or whatever else.. Technically you can't enter that character by hand (usually with use of `opt` key on keyboard) but you can easily paste it or long press `a` key to see diacritical marks and then you can enter any you one.
3. Post is created. Click on that tag in the post view.
4. Error.

**Video**
[Video](https://d.pr/v/1xSmcP)

**Expected behavior**

Not sure... 🤷 

**Desktop (please complete the following information):**

- OS: macOS X
- Browser: Chrome
- Version: 83.x

**Comment by jacobherrington** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
@ludwiczakpawel we don't support special characters in tags, so I think the expected behavior here is to raise an error

**Comment by ludwiczakpawel** [comment]
@rhymes but then we should be able to enter special characters in the tags field so this page is not being created in the first place.

**Comment by rhymes** [comment]
Yeah, either one of the solutions. I think we need both as JavaScript validation can still be bypassed :)

**Comment by jacobherrington** [comment]
@rhymes @ludwiczakpawel I added much more strict validation https://github.com/thepracticaldev/dev.to/pull/9006

I'm concerned that it's too strict, but it sounds like what we want here.

**Comment by citizen428** [comment]
> we don't support special characters in tags, so I think the expected behavior here is to raise an error

Given that I18n is on our generalization roadmap, we may want to revisit this decision at one point. Sure, it probably means we'd have to encode/decode tag slugs, but we may not get away forever with not supporting accents and umlauts.

**Comment by AfroDevGirl** [comment]
@citizen428 I'm a cloud Forem admin with an international community. We would really appreciate all special characters in tags, but at least ones that are important to different languages, like ñ for example. Have there been discussions recently on the viability of this request?

**Comment by citizen428** [comment]
@AfroDevGirl The last one I personally can remember was in the PR linked to this issue ([see here](https://github.com/forem/forem/pull/9006#discussion_r447362666)), but that may not be the last time it was discussed. Calling on @forem/product to weigh in here please.
