### ISSUE TITLE
Bug in button more, post

### ISSUE THREAD

**Issue by Judionit** [thepracticaldev/dev.to#8892]
When I read a post and Want to click in more button, I can't see the menu, it's in the back

![index](https://user-images.githubusercontent.com/46365844/85608414-b437f000-b65d-11ea-8719-5972ceee6f2d.PNG)

**Comment by jacobherrington** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by jacobherrington** [comment]
Hey @Judionit - do you mind including some browser information here? I'm not able to replicate the issue in Firefox or Chrome on Ubuntu.

What kind of setup are you experiencing this bug on? Is it on every article or just this one? Thanks!

**Comment by nickytonline** [comment]
@jacobherrington, this is a known issue. I reported it to @ludwiczakpawel yesterday or the day before. He'll be working on a fix for this or already has one.

**Comment by Judionit** [comment]
> Hey @Judionit - do you mind including some browser information here? I'm not able to replicate the issue in Firefox or Chrome on Ubuntu.
> 
> What kind of setup are you experiencing this bug on? Is it on every article or just this one? Thanks!

Hey, thank you for your quick reply,
I tested it in chrome browser on windows

**Comment by ludwiczakpawel** [comment]
I'll be looking into this issue today, thanks for reporting!

**Comment by ludwiczakpawel** [comment]
^ I've got [PR](https://github.com/thepracticaldev/dev.to/pull/8903) waiting to be approved. It should fix the issue.
