### ISSUE TITLE
Unable to change displayed github username

### ISSUE THREAD

**Issue by muthuct** [thepracticaldev/dev.to#89]
I changed the username of my github account. But my profile page on dev.to still shows my old username and links to my old github profile page. I revoked access to the dev.to website and again gave access to it via github, even then there is no change. 

My dev.to username: muthuct
My github username: muthuct
My old github username: mac25796

**Comment by Zhao-Andy** [comment]
Hey @muthuct, this was just fixed by @benhalpern. If you try signing out and logging in via GitHub it should work. Let me know if it doesn't.

**Comment by muthuct** [comment]
Thanks. It has changed now. :)
