### ISSUE TITLE
New Dashboard design is clunky on smaller screens and mobile view

### ISSUE THREAD

**Issue by deepu105** [thepracticaldev/dev.to#8906]
**Describe the bug**

The new dashboard design is not very responsive. It looks clunky in smaller screens and on mobile. I liked the old layout better TBH. The new one is ok but I find it less readable especially on mobile

**To Reproduce**

Just open dashboard with some posts on a smaller screen

**Expected behavior**

Responsive screen with proper placement of elements

**Screenshots**

![image](https://user-images.githubusercontent.com/1107223/85704053-3ff26080-b6e0-11ea-9601-e8b315cded2b.png)

![image](https://user-images.githubusercontent.com/1107223/85703462-ab87fe00-b6df-11ea-9918-4ca7369e5f43.png)

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Chrome
- Version: latest

**Smartphone (please complete the following information):**

- Device: Samsung
- OS: Android
- Browser: Chrome
- Version: latest

**Additional context**

**Comment by ludwiczakpawel** [comment]
Fix for this issue and other dashboard updates are coming in literally couple hours (if everything goes smooth).

**Comment by deepu105** [comment]
cool, you folks are fast
