### ISSUE TITLE
Make showing top comments on posts in feed configurable

### ISSUE THREAD

**Issue by deepu105** [thepracticaldev/dev.to#8907]
**Is your feature request related to a problem? Please describe.**

I personally do not want to see top comments on posts on the feed as it makes eyeballing through the feed for interesting topics less pleasant. I can see that there will be people who like this, so it would be nice if I can turn off/on this view from settings or something to improve personal UX preference.

It almost feels like Dev UX is slowly turning into something like Reddit :crying_cat_face: 

**Describe the solution you'd like**

A setting option to turn off/on the comments shown in feed

**Describe alternatives you've considered**

none

**Comment by rhymes** [comment]
Hi @deepu105 I believe your request is a duplicate of https://github.com/thepracticaldev/dev.to/issues/8073

Please confirm and add your valuable POV there as well :)

**Comment by deepu105** [comment]
oh ya. Very sorry I didn't find that when I looked
