### ISSUE TITLE
Ability to style text in comments using hotkeys

### ISSUE THREAD

**Issue by theoutlander** [thepracticaldev/dev.to#891]
**Is your feature request related to a problem? Please describe.**
When writing comments, I'm not able to use hotkeys to do basic things like make bold text or create links similar to how it works here on the GitHub issue box.

**Describe the solution you'd like**
Ability to use hotkeys to make text bold, italic, create links, etc. We will need to think of all the scenarios that we should support.

**Additional context**
This is similar to how GitHub or Medium work. We just need the ability to use hotkeys to style text.

I can work on this issue if it is approved.

**Comment by jessleenyc** [comment]
Cool, this makes sense and is approved

**Comment by theoutlander** [comment]
Great! I’m going to claim this issue.

Sent from my iPhone

On Oct 17, 2018, at 8:45 AM, Jess Lee <notifications@github.com<mailto:notifications@github.com>> wrote:


Cool, this makes sense and is approved

**Comment by theoutlander** [comment]
test
