### ISSUE TITLE
Show/Hide archived link redirects to about:blank#blocked from PWA to Chrome 

### ISSUE THREAD

**Issue by Kvaibhav01** [thepracticaldev/dev.to#8911]
**Describe the bug**
When I want to archive a post. I click on the three dots menu in the dashboard corresponding to the post and hit "Archive post". It archives. The problem arises when I want to show/hide the archive post(s) from the DEV's PWA. The same thing happens, it opens a new tab with "about:blank#blocked" as the URL. It does show me the required archived/unarchived posts when I go back to the PWA but I don't know why it first opens the Chrome browser with that weird link.

**To Reproduce**
In the DEV PWA app,

1. Try to write a test post from "[Write a post](https://dev.to/new)" and save the draft.   
2. Go to your [dashboard](https://dev.to/dashboard).
3. Select the three-dot menu corresponding to the test post and click on "Archive post". The post will now not show up on the list and is archived.
4. Click on the "Show archived" link on the top-left corner of the list and it'll open up the browser with "about:blank#blocked" as the URL.
5. Come back to the PWA app, the archived test post is now visible.

**Expected behavior**
When we click on "Show/Hide archived" link, it should not open up that URL in the browser, instead, it should show the desired posts straightaway in the PWA app.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 
- Browser: Google Chrome 
- Version: Version 83.0.4103.116 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
Not tested.

**Comment by Ridhwana** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by fdoxyz** [comment]
Fixed by recently merged PR (try to hard refresh to update the site JS if the problem persists)

**Comment by Kvaibhav01** [comment]
Cool, it works now. Thanks!
