### ISSUE TITLE
Enable Automatic PR Rebase using Github Action

### ISSUE THREAD

**Issue by awasum** [thepracticaldev/dev.to#8927]
Add ability to automatically rebase PRs when a user comments on the PR. See: https://github.com/marketplace/actions/automatic-rebase

This may reduce time when reviewing and addressing feedback on PRs

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @awasum, I really like the idea! We should probably limit it to team member (and the owner of the PR) I guess to avoid having casual commenters rebasing branches :D

**Comment by awasum** [comment]
@rhymes thats a good idea. I will like to send a PR for this, Please.

**Comment by awasum** [comment]
@rhymes I have sent a PR for this issue: https://github.com/thepracticaldev/dev.to/pull/9018, 
Please let me know if its good enough.
