### ISSUE TITLE
[DOM] Found [N] elements with non-unique id #article_archived

### ISSUE THREAD

**Issue by richardeschloss** [thepracticaldev/dev.to#8941]
**Describe the bug**
In chrome dev tools, I saw this error message. Chrome warns that having non-unique ids could lead to unexpected issues.

"[DOM] Found 15 elements with non-unique id #article_archived"

The issue is observed on my dashboard.

Duplicate IDs are observed on the Dev.to dashboard. In HTML, id's are supposed to be unique, because if they're not, targeting a specific element may not work as expected..

**To Reproduce**

On your dev.to dashboard, archive at least 1 article.  Open Chrome dev tools, inspect the logs after clicking refresh

**Expected behavior**

No console warnings on duplicate ids.

**Screenshots**

![duplicateIds](https://user-images.githubusercontent.com/5906351/85905212-aa2e0280-b7bf-11ea-9092-ba1a56dcd5fc.jpg)

**Desktop (please complete the following information):**

- OS: Windows 10 
- Browser: Chrome 80
- Version:

**Smartphone (please complete the following information):**

Not tested
- Device:
- OS:
- Browser:
- Version:

**Additional context**

It appears as though the elements already have a name "article[archived]" so the use of an id may be extraneous, since there is already a means to properly target the elements. But if it is desired to still use "article_archived" as an identifier, it would be better as a class name, in my opinion.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).
