### ISSUE TITLE
How to highlight text (without word break) in a dev.to article as an editor?

### ISSUE THREAD

**Issue by mudgen** [thepracticaldev/dev.to#8946]
Hello,

I don't really know where to ask this question.

I am just trying to write an article on Dev.to.   Sometimes I like to highlight a word by using backticks.

So I might highlight a word like this:  `myword`.   This works but the problem I run into is that sometimes line breaks happen right in the middle of words that I highlight like this.    So that 'mywor' is at the end of one line and 'd' starts at the beginning of the next line.

How can prevent line breaks happening right in the middle of words I highlight?  Or is there a different way to highlight words in dev.to articles?

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
@mudgen do you have a link? It'd be easier to debug what's going on

**Comment by mudgen** [comment]
@rhymes I don't yet.   But you can reproduce the issue by writing a dev.to article that uses backticks with long words.  Like this:   `` `longwordwithbacticks` ``

**Comment by rhymes** [comment]
@mudgen could it depend on screen resolution? Like if the word happens to be at the end of the line it just gets broken?

**Comment by mudgen** [comment]
@rhymes here is a link: https://dev.to/mudgen/runcss-a-runtime-version-of-tailwindcss-5dic

Notice the words `hover` and `sm` get line breaked right in the middle of them.  How can I fix this?

**Comment by mudgen** [comment]
@rhymes Screen resolution can affect it but words that are not highlighted do not get broken in the middle no matter the screen resolution,  so the screen resolution shouldn't break highlighted words either.

**Comment by rhymes** [comment]
Found the issue, it's `break-all` here:

https://github.com/thepracticaldev/dev.to/blob/8e0972dd330bf9464160b673e4a744897ad736c8/app/assets/stylesheets/views/article.scss#L219-L229

**Comment by mudgen** [comment]
Great!  Is this going to change or what should I do?

**Comment by rhymes** [comment]
@mudgen I sent a PR https://github.com/thepracticaldev/dev.to/pull/8950 - thanks for the report!
