### ISSUE TITLE
Broadcast Announcements are displayed in every iframe

### ISSUE THREAD

**Issue by jacobherrington** [thepracticaldev/dev.to#8983]
**Describe the bug**

Because iframes are essentially their own window, they will render Broadcast Announcements. This is pretty weird and we should address it!

There is additional context in #8981 where @vaidehijoshi proposed a quick solution for this issue in Mod Tools, but @ludwiczakpawel uncovered that it exists pretty much everywhere. :upside_down_face:

![image](https://user-images.githubusercontent.com/11466782/86032854-9c65c080-b9fd-11ea-8ff9-fa9609d9ae29.png)

**To Reproduce**

Create a broadcast announcement, then visit any page with an iframe.

**Expected behavior**

Broadcast announcements shouldn't render in iframes!

**Screenshots**

In Mod Tools (covered by #8774 and #8981)
https://d.pr/v/ltCl5Z

Another example, in connect! :scream: 
https://d.pr/v/boafUi

**Additional context**

We've more or less embraced supporting iframes, so we will need to come up with a robust solution for this or start working on removing the iframes from our app.

**Comment by jacobherrington** [comment]
**Proposed Solutions**

- Rendering Broadcast Announcements conditionally like in #8981. We can compile a list of places we don't want these to show up and use URLs or on-screen elements to stop them from rendering.
- Rendering Broadcast Announcements on specific pages rather than *every* page by pulling the code out of [initializePage.js](https://github.com/thepracticaldev/dev.to/blob/master/app/assets/javascripts/initializePage.js).
- Get rid of iframes! :boom: :boom:

**Comment by vaidehijoshi** [comment]
Thanks for documenting this issue, @jacobherrington!

**Comment by benhalpern** [comment]
There is a `body.hidden-shell` class that gets added in the iframe context.

Here is the code in `scaffold.css`. I think the solution would be to add the announcement class here....

```
body.hidden-shell {
  .top-bar,
  footer {
    display: none;
  }
  .container {
    margin-top: 0px;
  }
  .universal-page-content-wrapper {
    margin-top: calc(var(--header-height) * -1) !important;
    margin-bottom: 30px;
  }
}

**Comment by jacobherrington** [comment]
Closed by https://github.com/thepracticaldev/dev.to/pull/8981
