### ISSUE TITLE
Uploading an image to post on android app

### ISSUE THREAD

**Issue by urielbitton** [thepracticaldev/dev.to#8984]
The bug occurs when attempting to upload an image to a post from an android mobile phone on the dev.to app. The image fails to upload, and the page redirects to the home page. Upon visiting the write a post page again, the image hasn't uploaded and another attempt to upload an image results in the same result.

**To Reproduce**

<!-- 4. Page redirects to home page and image is not uploaded>

**Expected behavior**
The page should produce an image link that is added to the post upon clicking upload image

**Screenshots**

Not really anything to see.

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy s10
- OS: android 10
- Browser: dev app
- Version: latest version of app

**Comment by jacobherrington** [comment]
Issue moved to [thepracticaldev/DEV-Android #91](https://github.com/thepracticaldev/DEV-Android/issues/91) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jacobherrington** [comment]
Thanks for opening an issue!

It's seems like a good idea to move this issue to one of our mobile app repositories, we can continue the discussion there!
