### ISSUE TITLE
Cannot unpublish on V2 Beta

### ISSUE THREAD

**Issue by joelnet** [thepracticaldev/dev.to#899]
**Is your feature request related to a problem? Please describe.**
Accidentally published an article meant to stay in draft on V2 Beta. I could not unpublish the article and had to resort to DELETE.

**Describe the solution you'd like**
An article that is published should have an unpublish button.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Zhao-Andy** [comment]
Ah, good point. Thanks for raising this.
