### ISSUE TITLE
Need a way for admins to search Connect chat channels in /internal

### ISSUE THREAD

**Issue by michael-tharrington** [thepracticaldev/dev.to#8997]
**Is your feature request related to a problem? Please describe.**

Yes, as an admin, I cannot search between our Connect chat channels to manually add new members from https://dev.to/internal/chat_channels. There are many many pages now here and it takes too long to try to find a Connect channel to add new folks.

**Describe the solution you'd like**

I'd like there to be a search option available to search for chat channels by name.

**Describe alternatives you've considered**

It could also be helpful to be able to filter and organize the list by date created, name, private chat channel versus public, if the channel is a mod related channel, etc. (I feel like these could all be options we add later on down the line, but for starters the search by name would be most helpful!)

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by AlbertoPdRF** [comment]
I'll give a shot to this one!

**Comment by michael-tharrington** [comment]
Holy cow, that was quick turnaround! And it's working well. 😀 

Thanks @AlbertoPdRF!

**Comment by AlbertoPdRF** [comment]
You're welcome! 😄
