### ISSUE TITLE
Can scroll under chat on /Connect

### ISSUE THREAD

**Issue by thomasbnt** [thepracticaldev/dev.to#8998]
**Describe the bug**

On Connect, I can scroll literaly and the chat is on top. Too weird.

**To Reproduce**

1. Go to [/connect](https://dev.to/connect) 
2. Scroll down
3. See error 

**Expected behavior**

Can't scroll under chat __but__ only on friends list.

**Screenshots**

![image](https://user-images.githubusercontent.com/14293805/86055556-3eb49100-ba5c-11ea-8695-edaa90aedda8.png)

**Desktop (please complete the following information):**

- OS: Manjaro
- Browser: Google Chrome
- Version: Version 83.0.4103.97 (Build officiel) (64 bits)

**Additional context**

![fkeznfklzentf](https://user-images.githubusercontent.com/14293805/86055911-dca85b80-ba5c-11ea-8987-13a7cc1f07d0.gif)

**Comment by jacobherrington** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by Veggier** [comment]
This is my first time to try to solve the issue, may I try to work on this issue.

**Comment by Veggier** [comment]
I will try to work it one

**Comment by nickytonline** [comment]
@Veggier, I've assigned the issue to you.

**Comment by Veggier** [comment]
@nickytonline sorry, I just unassign myself, may you reassigned me, thanks.

**Comment by jacobherrington** [comment]
Closed by #9042
