### ISSUE TITLE
Embedded Gists affected by theme stylesheet

### ISSUE THREAD

**Issue by jreina** [thepracticaldev/dev.to#90]
# _TASK or Feature_
### Request or User Story
I want the line number cell to use the Gist stylesheet for embedded Gists.

### Definition of Done
Embedded Gists will have the width as specified in the Gist stylesheet.

### Notes
This might not be possible since it appears that TPD uses the minimal theme. I don't know enough about how theming works to say for sure, though.

# _BUG_
### Current Behavior
The line number cell in embedded Gists is styled by the `.container .body table td` CSS selector and has a width value of `1000px`. This makes the line number cell expand to fill up as much space as possible and if there isn't a line of code which takes up a full line width, the code is pushed to the right.

### Expected Behavior
The line number cell should not be affected by the theme stylesheet.

### Additional Info (steps to replicate, device/browser, helpful links)
[Here's an article](https://dev.to/jreina/intro-to-the-zip-function) where I embedded a few Gists. Some of them show up okay because they have really long comments, but the Gists without long comments have an awkward layout.

### Screenshots
![image](https://user-images.githubusercontent.com/2089820/30665709-8d45ac64-9e17-11e7-9050-aa3d49fe17ee.png)
![image](https://user-images.githubusercontent.com/2089820/30665721-9aeb5cec-9e17-11e7-8f94-55e46234d012.png)

**Comment by maestromac** [comment]
Thank you for reporting this! This is fixed.

**Comment by jreina** [comment]
Y'all are the best. Thanks!
