### ISSUE TITLE
Badges are not responsive

### ISSUE THREAD

**Issue by OmarElKhatibCS** [thepracticaldev/dev.to#9013]
Hello The badges are not responsive they go out of the screen.

![!responsive](https://user-images.githubusercontent.com/35725554/86094246-1da46e00-ba65-11ea-90cc-31ae256ae100.PNG)

- OS: Windows 10 x64
- Browser: Firefox

I have the fix to this Issue , I will make a pull request 👍

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by OmarElKhatibCS** [comment]
I claim this Issue and Pull request is pending.
