### ISSUE TITLE
scroll bar keep shown in the profile page

### ISSUE THREAD

**Issue by OmarElKhatibCS** [thepracticaldev/dev.to#9016]
**Describe the bug**
The bug is this scrollbar keep showing all the time it's annoying to the eyes ,
Also mobile have same problem .

**To Reproduce**

Go to profile resize window

**Expected behavior**

**Screenshots**
![profile-responsive](https://user-images.githubusercontent.com/35725554/86106655-acb98200-ba75-11ea-8360-fc9dfd109284.PNG)

Also On mobile it's very very annoying every time I scroll This black shadow camp up

![Screenshot_20200630-184951](https://user-images.githubusercontent.com/35725554/86148174-f69c7980-bb02-11ea-9a77-4968dad6ed82.jpg)

**Desktop (please complete the following information):**

- OS: Windows 10 x64
- Browser: Firefox

**Smartphone (please complete the following information):**

- Device: Huwawei Y7 prime 2018
- OS: Android
- Browser: App
- Version: Latest

**Comment by Ridhwana** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by OmarElKhatibCS** [comment]
I claim this Issue and Pull request is pending.

**Comment by OmarElKhatibCS** [comment]
This issue has been fixed
