### ISSUE TITLE
Spaces hidden in code block if wrapped at end of line

### ISSUE THREAD

**Issue by artis3n** [thepracticaldev/dev.to#9028]
**Describe the bug**

Coming off of #8977 and the PR fix in #8975 , it now appears that spaces in a one-line `code block` are cut off and wrapped, which changes the content. For example:

![image](https://user-images.githubusercontent.com/6969296/86148817-1911a100-bac9-11ea-8b1d-bc6f3a194799.png)

That code line should be `:s/ //g`, which would remove spaces in `vim.` However, the space no longer visually appears.
If I copy the line from my article and paste it here, the space is preserved, it's just how it visually appears in the document.

**To Reproduce**

Have a small one-line code block near the end of the word wrap character limit with a space at the character limit.

**Expected behavior**

Ideally, the full `whatever is in the code line` is moved to the next line so the content remains contiguous and is clear to read.
Alternatively, making sure the grayed background in the code block displays the space at the end of the line where it wraps.

**Screenshots**

Provided above.

**Desktop (please complete the following information):**

- OS: OSX 10.15.5
- Browser: Chrome
- Version: 83.0.4103.116

**Smartphone (please complete the following information):**

N/A

**Additional context**

**Comment by jacobherrington** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by ludwiczakpawel** [comment]
Not sure if this is doable. What would happen if you had 100 characters in your `code` element? It would overflow the container. We had to apply `overflow-wrap: break-word;` to make code elements wrap next line.

In your specific scenario, I'd suggest using non-breakable spaces  instead of regular space: `&nbsp;` in that one code element you were mentioning.

**Comment by artis3n** [comment]
That seems pretty fair

**Comment by ludwiczakpawel** [comment]
Cool, I'll let myself close this issue if you don't mind :)
