### ISSUE TITLE
Occasionally org admins cannot view org dashboard

### ISSUE THREAD

**Issue by michael-tharrington** [thepracticaldev/dev.to#9066]
**Describe the bug**

When a user has been invited to a DEV Organization and made an Admin if they have never created a post they will not see the dropdown to switch to another Organization (screenshot 1) in their dashboard.

**Expected behavior**

All org admins should be able to access their org's dashboard regardless of whether or not they've written a post.

**Screenshots**

Screenshot 1 (_Note: I didn't doctor my "total post views at all_)

![Image 2020-07-01 at 5 55 29 PM](https://user-images.githubusercontent.com/16007075/86295301-42fbbe00-bbc4-11ea-852b-adbf94e333ce.png)

**Additional Context**

Based on feedback [here](https://github.com/thepracticaldev/dev.to/issues/8920#issuecomment-652548734).

**Comment by jacobherrington** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).
