### ISSUE TITLE
Share Link Broken

### ISSUE THREAD

**Issue by JacobMGEvans** [thepracticaldev/dev.to#9092]
**Describe the bug**
When clicking on the share link button, it is attempting to call the dataset prop off a null reference.

Conversation Debugging  w/ @BraveSampson & @benhalpern 
https://twitter.com/JacobMGEvans/status/1278855232773148672
https://twitter.com/BraveSampson/status/1278855506409504768
**To Reproduce**
1. Go to an article
2. Click on share link "**...**"
3. Nothing occurs

**Expected behavior**
After step 2. A popover appears with social media share links.

**Screenshots**

<img width="650" alt="Screen Shot 2020-07-02 at 7 54 59 PM" src="https://user-images.githubusercontent.com/27247160/86421358-621b4e00-bc9f-11ea-8ff9-1e74bcf638ad.png">

**Desktop (please complete the following information):**

- OS: Catalina 10.15.5
- Browser: Brave 
- Version: 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)

resolved by #9091

**Comment by benhalpern** [comment]
Fixed via #9088

**Comment by JacobMGEvans** [comment]
@benhalpern  Is that fix not deployed yet? I am still seeing the issue on the website.
