### ISSUE TITLE
No length-check for summary

### ISSUE THREAD

**Issue by minecrawler** [thepracticaldev/dev.to#91]
# No length-check for summary
### Current Behavior
The summary textarea implements `maxlength=200`, however that limit is never enforced on the server side. The full text is saved in a DB.

### Expected Behavior
Show an error message telling me that the text is too long and cannot be saved.

### Additional Info (steps to replicate, device/browser, helpful links)
See [my profile](https://dev.to/maruru) for an example of a too long text ;)

**Comment by Zhao-Andy** [comment]
Thanks for the heads up.

**Comment by Zhao-Andy** [comment]
This is half done right now. It validates in the backend but there's no error message. Will put that in soon.

**Comment by minecrawler** [comment]
So, why is it closed, then?

**Comment by Zhao-Andy** [comment]
Oops forgot to reopen. That was a misclick from before.

**Comment by Zhao-Andy** [comment]
Fixed now.
