### ISSUE TITLE
Whitelist mastodon.online URL

### ISSUE THREAD

**Issue by creativenull** [thepracticaldev/dev.to#9101]
**Is your feature request related to a problem? Please describe.**

Would it be possible to whitelist [mastodon.online](https://mastodon.online)? According to the about page

>This is a brand new server run by the main developers of the project as a spin-off of mastodon.social 🐘 It is not focused on any particular niche interest - everyone is welcome as long as you follow our code of conduct!

So a new server run by the main developers of mastodon.social

**Describe the solution you'd like**

Add it to the whitelist constants in `app/lib/constants.rb`

**Additional context**

I wouldn't mind adding this myself, but wanted to engage more opinions. Also I made an account there only to find out that it was not on the whitelist of dev.to.

We can either add it to the whitelist or maybe display to the user (in the edit profile page) which mastodon instances are allowed to be added within your profile.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
@creativenull sure, go ahead! :-)

**Comment by creativenull** [comment]
Alright, I will follow up with a PR 🙂

**Comment by nickytonline** [comment]
@creativenull, I've assigned the issue to you.

**Comment by creativenull** [comment]
Merged and I was successfully able to add my mastodon profile to my dev.to profile.
