### ISSUE TITLE
Pro analytics org link should not appear to non pro users

### ISSUE THREAD

**Issue by yg** [thepracticaldev/dev.to#9106]
**Describe the bug**

Pro analytics page return 404

**To Reproduce**

1. Visit https://dev.to/dashboard/pro/org/{org_id}
2. It will return 404

**Expected behavior**

If it is a pro feature it should redirect to the billing page

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
@yg there's current no "billing page" to activate pro analytics so I believe 404 is the correct answer. How did you land up there?

**Comment by yg** [comment]
@rhymes I got this on the dashboard!

![Screenshot](https://user-images.githubusercontent.com/61746440/86532104-dd217600-bee4-11ea-979d-a259c89702d5.png)

**Comment by rhymes** [comment]
Oh got it! 

I see where the bug is, you shouldn't have that link!
