### ISSUE TITLE
GitHub repos list is loading longer than usual and returns an error

### ISSUE THREAD

**Issue by yg** [thepracticaldev/dev.to#9110]
**Describe the bug**

GitHub repos list is loading longer than usual and returns an error

**To Reproduce**

I'm not sure this happens to all

Make sure your dev.to account is connected with GitHub
Go to https://dev.to/settings/integrations
See the error

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/61746440/86503923-61360980-bdd0-11ea-82a5-5c9b91ae66bd.png)

https://www.loom.com/share/46608ff9f88b4db8b1dc0f11d18767f4

**Desktop (please complete the following information):**

- OS: Ubuntu and Windows 10
- Browser: Chrome Stable and Chrome Beta

**Comment by rhymes** [comment]
Yeah, unfortunately this has been a long standing and known issue. I'm going to close it in favor of https://github.com/thepracticaldev/dev.to/issues/8904
