### ISSUE TITLE
Cover Image for an article not responsive 

### ISSUE THREAD

**Issue by ioana-chiorean** [thepracticaldev/dev.to#9115]
**Describe the bug**

The cover image is unreadable in <some> smaller resolutions. 

**To Reproduce**
1) Set your resolution to a smaller one * either use devtools or just make your browser window smaller - i use to like this to have a split screen
2) Go to: https://dev.to/lakatos88/new-personal-site-who-this-55f1
3) Check the cover image

**Expected behavior**
- the image should be clear/mapped.

**Screenshots**

<img width="833" alt="Screen Shot 2020-07-04 at 20 10 30" src="https://user-images.githubusercontent.com/1391451/86517790-3d0c1400-be34-11ea-90dc-6bf3ae9abfb5.png">
<img width="840" alt="Screen Shot 2020-07-04 at 20 11 18" src="https://user-images.githubusercontent.com/1391451/86517792-3f6e6e00-be34-11ea-8397-a04eda932e32.png">

**Desktop (please complete the following information):**

- OS: macOS Catalina 10.15.5
- Browser: Firefox
- Version: 77.0.1

cc @alexlakatos

**Comment by nickytonline** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by nickytonline** [comment]
Hmm, not sure what's up. This is what I see for smaller resolutions

![image](https://user-images.githubusercontent.com/833231/86521131-c0b90700-be1a-11ea-8485-8b5d9c7b29f6.png)

![image](https://user-images.githubusercontent.com/833231/86521147-f5c55980-be1a-11ea-93a5-7bc361d1819c.png)

![image](https://user-images.githubusercontent.com/833231/86521075-05906e00-be1a-11ea-893d-6f1d1c730502.png)

![image](https://user-images.githubusercontent.com/833231/86521079-1b9e2e80-be1a-11ea-922d-b94eb2f698ca.png)

**Comment by subodhk01** [comment]
@ioana-chiorean Sorry I'm also unable to reproduce the issue.

**Comment by ioana-chiorean** [comment]
Oh snap. Thanks for checking @nickytonline and @subodhk01 - maybe was something my browser profile messed up (i did try with a cleaner profile but who knows)
