### ISSUE TITLE
Installation error  curl http://localhost:3000

### ISSUE THREAD

**Issue by Redweiweb** [thepracticaldev/dev.to#9119]
Ubuntu 18.04 LTS 

I tried two methods to install, always the last step error, I do not know where the error is?

1， Installation error  (Installing DEV on Linux):

== Removing old logs and tempfiles ==

== Restarting application server ==
webtest@dream:~/dev.to$ curl http://localhost:3000
curl: (7) Failed to connect to localhost port 3000: Connection refused

Run bin/setup No error

-------------------
2，Install using Docker also error: 

dev_seed         | 2020/07/04 22:10:16 Problem with request: Get http://web:3000: dial tcp 172.18.0.7:3000: connect: connection refused. Sleeping 1s
dev_sidekiq      | 2020/07/04 22:10:16 Problem with request: Get http://web:3000: dial tcp 172.18.0.7:3000: connect: connection refused. Sleeping 1s
^CGracefully stopping... (press Ctrl+C again to force)

Run bin/container-setup No error

**Comment by rhymes** [comment]
@Redweiweb I think you're missing the `bin/startup` step, see https://docs.dev.to/getting-started/start-app/

**Comment by Redweiweb** [comment]
This issue has been resolved:

bin/startup   //I forgot this

curl http://localhost:3000

Thanks for help!
