### ISSUE TITLE
Can't get github_repos integration

### ISSUE THREAD

**Issue by thomasbnt** [thepracticaldev/dev.to#9123]
**Describe the bug**
Hello, https://dev.to/github_repos is very slow and answer me with an error for integrations settings.

**To Reproduce**

1. Go to [settings](https://dev.to/settings/integrations
2. Wait...
3. Nothing is coming

**Expected behavior**
Get this contenu fastly without errors.

**Screenshots**

**Desktop (please complete the following information):**

- OS: All
- Browser: Chrome principaly
- Version:

**Comment by rhymes** [comment]
Hi @thomasbnt, thanks for the report. Closing this in favor of https://github.com/thepracticaldev/dev.to/issues/8904

**Comment by thomasbnt** [comment]
Oh.. I'm sorry 😵
