### ISSUE TITLE
I'm unable to write post even after 2 months on dev.to

### ISSUE THREAD

**Issue by deepanshu1422** [thepracticaldev/dev.to#9143]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by deepanshu1422** [comment]
No

**Comment by rhymes** [comment]
Hello @deepanshu1422, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
