### ISSUE TITLE
Cannot create a community listing, tags throw error

### ISSUE THREAD

**Issue by AlbertoMontalesi** [thepracticaldev/dev.to#9157]
As per image, i'm getting error when creating a listing. What's wrong with the tags?

![image](https://user-images.githubusercontent.com/23130353/86583266-2dfca180-bfad-11ea-8f32-6d49e993cd00.png)

**Comment by nickytonline** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by nickytonline** [comment]
@AlbertoMontalesi, this has already been reported in #9116.
