### ISSUE TITLE
Issue While Write a New Post 

### ISSUE THREAD

**Issue by candidroot** [thepracticaldev/dev.to#9158]
**Describe the bug**

When I tried to Write a Post, It is showing error like this, Please find attached Screenshot. 

**To Reproduce**

 Go to https://dev.to/
 Click on Write a post

**Expected behavior**

Ooooops...
You have encountered an error.

**Screenshots**

Please find attached Screenshot. 

![screenshot-dev to-2020 07 06-17_28_02](https://user-images.githubusercontent.com/39722234/86591243-cfd0be00-bfae-11ea-8d35-4ac303958b16.png)

Thanks,

**Comment by rhymes** [comment]
Hello @candidroot, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
