### ISSUE TITLE
Dark theme code blocks have highlights

### ISSUE THREAD

**Issue by wayofthepie** [thepracticaldev/dev.to#9163]
**Describe the bug**
A recent change has caused dark theme (Night theme) to have highlights in code blocks. I had a look and could not find an issue that was raised for this already, but I may have missed it!

**To Reproduce**
Create a code block and view in Night theme.

**Expected behavior**
Code blocks do not have highlights on code.

**Screenshots**
![image](https://user-images.githubusercontent.com/1102174/86605389-8ed0ad80-bf9e-11ea-931e-42c533cca4c4.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Browser: Firefox
- Version: 78.0.1

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @wayofthepie, weird because I can't reproduce it. I tried both with Ruby and JavaScript and both with the night and the ten X themes:

![Screenshot_2020-07-06 test code block - DEV(local) Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/86614468-5a1b2100-bfb3-11ea-9fec-2289d0e8f4f2.png)

![Screenshot_2020-07-06 test code block - DEV(local) Community 👩‍💻👨‍💻(1)](https://user-images.githubusercontent.com/146201/86614479-5daea800-bfb3-11ea-958f-94440d0dbe7e.png)

I have Firefox 79 beta though. 

Do you have a link to a post?

**Comment by wayofthepie** [comment]
Hmm that is weird! Yip this one https://dev.to/yahaya_hk/handling-asynchronous-operations-in-javascript-1fp2 does it for me. Screen from just now:
![image](https://user-images.githubusercontent.com/1102174/86615557-7ff0f780-bfac-11ea-9d33-37fbe73a1841.png)

**Comment by rhymes** [comment]
It's weird indeed. I don't see it:

![Screenshot_2020-07-06 Handling Asynchronous Operations in Javascript - DEV Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/86616265-e29ac100-bfb5-11ea-83a8-754fbdcefa1d.png)

It's like it autoselects code blocks 🕵️

**Comment by wayofthepie** [comment]
It seems to be this css inherited from the root:

```
--base-a10: rgba(249, 250, 250, 0.1);
```
![image](https://user-images.githubusercontent.com/1102174/86616756-3acdc500-bfae-11ea-8062-12d7eaa302ef.png)


Disabling that it goes away. Not sure where that comes from yet though.

**Comment by nickytonline** [comment]
cc: @ludwiczakpawel

**Comment by wayofthepie** [comment]
Just checked, also an issue on the app.

![Screenshot_20200706-181815](https://user-images.githubusercontent.com/1102174/86620945-348f1700-bfb5-11ea-9bef-3a95554739ff.jpg)

**Comment by ludwiczakpawel** [comment]
Good catch - yea it's a bug with hopefully easy fix. I'll take care of it tomorrow. :)
