### ISSUE TITLE
Article does not show up in tag feeds

### ISSUE THREAD

**Issue by liviulupei** [thepracticaldev/dev.to#9167]
Hi, I created a new account and published an article today:

https://dev.to/liviufromendtest/computer-vision-is-so-fun-4do7

It currently has 1954 views.

But the article does not show up in the feed when looking at the tags:
https://dev.to/t/python
https://dev.to/t/testing
https://dev.to/t/tutorial

Is my article being censored or hidden?

**Comment by jacobherrington** [comment]
Hey @liviulupei, I don't think this post has been censored in any way, but we've got the email you sent to yo@dev.to, so we'll follow-up with you there rather than in this issue.

Thanks!
