### ISSUE TITLE
[Listing] Bug with tags when we create a new listing

### ISSUE THREAD

**Issue by thomasbnt** [thepracticaldev/dev.to#9168]
**Describe the bug**

**To Reproduce**

1. Go to [new listing](https://dev.to/listings/new)
2. Fill title, description and add one or more tag(s)
3. Scroll down and click to save draft

**Expected behavior**
No errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/14293805/86625104-cf432200-bfc4-11ea-92d7-c067cf6c5896.png)

**Desktop :**

- OS: Manjaro
- Browser: Chrome
- Version:

**Comment by jacobherrington** [comment]
Hey @thomasbnt this is a duplicate issue, we've got another instance of the same bug: https://github.com/thepracticaldev/dev.to/issues/9116

You can add context there if you'd like! Thanks!

**Comment by thomasbnt** [comment]
Oooops again.. :c 

*I really have to check the open ones before I open a new one like a savage.*
