### ISSUE TITLE
The syntax for markdown links displayed in the "Write a Post" page is incorrect

### ISSUE THREAD

**Issue by muhdmirzamz** [thepracticaldev/dev.to#9173]
**Description**

When you enter the "Write a Post" page, the syntax for Markdown links is incorrect in the "Editor Basics" section.

**To Reproduce**

1. Go to [https://dev.to](https://dev.to)
2. Click on "Write a post"
3. Click on the body text area to activate the "Editor Basics" section
4. Click on the "commonly used syntax"
5. See error

**Expected behavior**

1. Go to [https://dev.to](https://dev.to)
2. Click on "Write a post"
3. Click on the body text area to activate the "Editor Basics" section
4. Click on the "commonly used syntax"
5. The syntax displays the right syntax

**Screenshots**
<img width="380" alt="Screenshot 2020-07-06 at 12 08 11 PM" src="https://user-images.githubusercontent.com/5539018/86697656-2be42280-c041-11ea-84fa-20f1feb49ed7.png">

**Desktop (please complete the following information):**

- OS: macOS Mojave
- Browser: Safari
- Version: 10.14.6

**Smartphone (please complete the following information):**

- Device: iPhone
- OS: iOS
- Browser: Safari
- Version: v13.5.1

**Comment by rhymes** [comment]
I think this will be fixed by https://github.com/thepracticaldev/dev.to/pull/9176
