### ISSUE TITLE
Editor Basics > Commonly used syntax

### ISSUE THREAD

**Issue by AnnieTaylorCHEN** [thepracticaldev/dev.to#9179]
Currently:

[Link][https://...]      Link

it should be:

[Link]**(https://...)**     Link

**Comment by rhymes** [comment]
Hi @AnnieTaylorCHEN, thanks for the report, this has been just solved by https://github.com/thepracticaldev/dev.to/pull/9176

It'll be online in the afternoon (UTC time)
