### ISSUE TITLE
I can't publish any post

### ISSUE THREAD

**Issue by Mattia2204** [thepracticaldev/dev.to#9185]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hello @Mattia2204, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.
