### ISSUE TITLE
Image breaks out of container on default theme

### ISSUE THREAD

**Issue by GarethTF** [thepracticaldev/dev.to#9186]
**Describe the bug**

Certain Images break out of the container when viewing on the default theme.

**To Reproduce**

Go to https://dev.to/myogeshchavan97/build-an-amazing-job-search-app-using-react-42p

**Expected behavior**

Image to be constrained in the container

**Screenshots**

![devto](https://user-images.githubusercontent.com/56965213/86807433-c78d8700-c071-11ea-823f-e0812e6bec0e.jpg)

**Desktop (please complete the following information):**

- OS: W10
- Browser: Firefox Dev
- Version: 79

**Comment by Zhao-Andy** [comment]
Thanks for reporting this issue! I think it's the same cause as #9189. Since that issue has some traction going already, we'll keep that issue open and close this one.
