### ISSUE TITLE
Some images overflow ouside the article body

### ISSUE THREAD

**Issue by alexandrudanpop** [thepracticaldev/dev.to#9189]
**Describe the bug**
Some images overflow ouside the article body - they don't seem to fit.

**To Reproduce**
1. Go to this article and scroll a little bit down: https://dev.to/alexandrshy/creating-a-template-repository-in-github-1d05

**Expected behavior**
Image fits nice.

**Screenshots**
Ex 1: Chrome on mobile phone:
![image](https://user-images.githubusercontent.com/15979292/86830376-4a2c3b80-c09e-11ea-8277-9b80aac9a200.png)

Ex 2: Firefox desktop
![image](https://user-images.githubusercontent.com/15979292/86830845-d9d1ea00-c09e-11ea-944e-a766edc1a9f8.png)

**Comment by benhalpern** [comment]
Looks like this was an issue with some cached css being out of sync with cached html.

I cleared some caches and it seems to have fixed it.

**Comment by alexandrudanpop** [comment]
checked it again and it seems to work ok now. thank you!
