### ISSUE TITLE
space between flex-wrapped rows in article subheader

### ISSUE THREAD

**Issue by icncsx** [thepracticaldev/dev.to#9196]
**Describe the bug**

At certain viewport widths, the flex-wrap kicks in and the edit and manage buttons get pushed down to another line. I think we should have some breathing room between the two rows to maintain vertical symmetry with the tags.

![Screenshot from 2020-07-07 23-42-57](https://user-images.githubusercontent.com/60417145/86873574-8e263d00-c0ac-11ea-9799-624d5b9cbb4b.png)

To replicate, visit an article you've authored while signed-in. Shrink the view-port until you see the buttons wrap to another row.

**Comment by Ridhwana** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by nickytonline** [comment]
Want to take this on @icncsx?

**Comment by rembrandtreyes** [comment]
I'll be down to pick this up if @icncsx does not end up taking it. 😄

**Comment by icncsx** [comment]
@rembrandtreyes You got it!

**Comment by icncsx** [comment]
@rhymes I think you meant to assign the other gentleman?

**Comment by rhymes** [comment]
@icncsx right, sorry!
