### ISSUE TITLE
I can't write my posts

### ISSUE THREAD

**Issue by Mattia2204** [thepracticaldev/dev.to#9198]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hi @Mattia2204, please contact yo@dev.to as mentioned here yesterday: https://github.com/thepracticaldev/dev.to/issues/9185

Thank you!
