### ISSUE TITLE
"Key Links" very far down

### ISSUE THREAD

**Issue by minecrawler** [thepracticaldev/dev.to#92]
# "Key Links" very far down
### Request or User Story
There is a "Key Links" section, which holds a few important links. I follow a great number of keywords, so the key links are very very far down. I would love to see them on the right side - or alternatively a way to remove or collapse the "hot tags" and "my other tags" sections. 

### Definition of Done
"Key Links" are easily accessible and can be found at the top-ish section of the site.

**Comment by Zhao-Andy** [comment]
Thanks for the feedback. We'll be doing some design changes eventually and will consider this.

**Comment by Zhao-Andy** [comment]
Closing since we've put this in consideration for our future design overhaul. Thanks again for the feedback!
