### ISSUE TITLE
I cannot create new post.

### ISSUE THREAD

**Issue by musti-91** [thepracticaldev/dev.to#9213]
I have read already about blocking the extensions and try again but that actually even didn't work

**Comment by akhil-naidu** [comment]
Yes, I am having similar issues https://github.com/thepracticaldev/dev.to/issues/9160, never got any lead though.

I tried to install in my PC, VPS, Gitpod every time I faced the same issue repeatedly.

**Comment by rhymes** [comment]
Hello @musti-91, thanks for notifying us of this problem, this looks an issue specific to your account.

Please email yo@dev.to for more help.

**Comment by kirananto** [comment]
I am also having similar issues #9465  
I think it might be due to the pack/js/* assets not being loaded.

**Comment by musti-91** [comment]
I removed my account
