### ISSUE TITLE
I can't write any post because there is a problem

### ISSUE THREAD

**Issue by Mattia2204** [thepracticaldev/dev.to#9214]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hi @Mattia2204, as mentioned in https://github.com/thepracticaldev/dev.to/issues/9185 and https://github.com/thepracticaldev/dev.to/issues/9198 you should contact yo@dev.to, thank you!
