### ISSUE TITLE
Can't actually scroll to the bottom of the page

### ISSUE THREAD

**Issue by ardunster** [thepracticaldev/dev.to#9229]
**Describe the bug**

Endless scroll of new topics on the home page prevents user from ever reaching links for help, support, etc on the bottom of the primmer dev.to page.

**To Reproduce**

1. Open dev.to

2. Try to scroll to the bottom (to find a link to report another bug, for example)

3. Watch as you glimpse the footer momentarily, then cry as it's replaced by yet more endless scroll of topics.

**Expected behavior**

To be able to access the bottom of the page without scrolling endlessly, and/or have the links in the footer available somewhere else, instead.

**Desktop (please complete the following information):**

- OS: OSX Catalina 10.15.5
- Browser: Safari
- Version: 13.1.1

**Comment by rhymes** [comment]
Hi @ardunster, thanks for raising the issue. I'm going to close this in favor of the following tickets:

- [please remove infinite scroll](https://github.com/thepracticaldev/dev.to/issues/5670)
- [Footer should be viewable](https://github.com/thepracticaldev/dev.to/issues/9034)
- [Main page <footer> element "Problem".](https://github.com/thepracticaldev/dev.to/issues/8256)

**Comment by ardunster** [comment]
Thanks, I looked for similar issues but apparently my search skills failed me. I left my further comments on the first link.
