### ISSUE TITLE
Improve Docker's speed

### ISSUE THREAD

**Issue by maestromac** [thepracticaldev/dev.to#923]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Currently, it takes about ~3 minutes to load up a homepage from a docker instance on macOS, that's a lot of time 😱. [Docker-sync](http://docker-sync.io) could to be the tool to resolve this issue.

**Describe alternatives you've considered**
Perhaps the culprit of our speed is our poor configuration. 

**Additional context**
n/a

**Comment by benhalpern** [comment]
Anyone with docker knowledge wanting to give this a go is welcome to give it a try.

**Comment by gionaufal** [comment]
Just as a feedback, this really seems to be a macOS specific problem. On ubuntu the homepage loads in 3~4 seconds for the first time.

**Comment by maestromac** [comment]
Thanks for that @gionaufal ! I had a feeling this was the case.

**Comment by j23schoen** [comment]
If it's a mac specific speed issue, [this](https://github.com/docker/compose/issues/3419#issuecomment-221793401)  might help you out. docker-compose was very slow for me on a mac until I modified my `/etc/hosts/` file as described in the comment I linked.

**Comment by maestromac** [comment]
@j23schoen Thanks for that suggestion. I've tried that and it didn't seem to do anything ☹️. Does that solution work for you with our app?

**Comment by j23schoen** [comment]
@maestromac when I have a chance I'll clone it and give it a shot and let you know if it helps at all

**Comment by asfo** [comment]
@gionaufal on windows loads fast too (5 seconds~ for the first time)

**Comment by snuderl** [comment]
The fix for this is very likely to mount the source volume using `delegated` option. This can just be added to docker-compose.yml

More info here https://docs.docker.com/docker-for-mac/osxfs-caching/

**Comment by crawlingcity** [comment]
The way we have our docker setup allows to run several projects at the same time in the same image and it's fast, as in <2 sec TTFB (same network, but external server serving the databases).

Maybe I'm missing something, but what are you trying to load? A dev.to clone?

Also, to be able to help further, can you share the configuration?

**Comment by maestromac** [comment]
@crawlingcity We're sampling trying to load `localhost:3000`. The configuration is in the repository [here](https://github.com/thepracticaldev/dev.to/blob/master/Dockerfile) and [here](https://github.com/thepracticaldev/dev.to/blob/master/docker-compose.yml)
