### ISSUE TITLE
Ability to save all following tags follow weight at once

### ISSUE THREAD

**Issue by markmead** [thepracticaldev/dev.to#9268]
**Is your feature request related to a problem? Please describe.**

Making changes to the following tags follow weight currently requires you to save each change

**Describe the solution you'd like**

A "Save all" button, allowing users to update multiple follow weights at once

**Describe alternatives you've considered**

The current save button sends the updates via AJAX to prevent a full page refresh

**Additional context**

N/A

**Comment by rhymes** [comment]
Hi @markmead, thanks for raising this issue. I'm closing this as a duplicate of https://github.com/thepracticaldev/dev.to/issues/1346 - let me know if that's not the case
