### ISSUE TITLE
Posts on home feed have broken avatars

### ISSUE THREAD

**Issue by Amorpheuz** [thepracticaldev/dev.to#9290]
**Describe the bug**
Broken avatars and links to user profiles on home page. Occurs only when I am logged into DEV. The images appear when I am logged out after a cache clear, but reappear if I log back in. 

On clicking the image, it loads the url `https://dev.to/undefined`. Which also turns out to be someone's user name too! XD

The post correctly loads information about such as picture and author when the post is opened by clicking on the link in title.

**Edit:** Org avatars also seem affected.

A few of the posts seem unaffected.

**To Reproduce**

1. Load https://dev.to/
2. Log In
3. Images are broken on most of the posts.

**Expected behavior**
Avatars appear correctly and link to the correct user.

**Screenshots**
![image](https://user-images.githubusercontent.com/22113778/87314876-6c600680-c541-11ea-9805-a2452b231003.png)
![image](https://user-images.githubusercontent.com/22113778/87315631-41c27d80-c542-11ea-90df-31114759fb2b.png)
![image](https://user-images.githubusercontent.com/22113778/87316147-05435180-c543-11ea-8199-dc540139e9db.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Edge 
- Version: 83.0.478.61 

**Smartphone (please complete the following information):**

- Device: Nokia 6.1
- OS: Android 10
- Browser: Edge
- Version: 45.05.4.5036

**Additional context**
Also broken in the android app!

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).
