### ISSUE TITLE
Make tags on the left removable or collapsible 

### ISSUE THREAD

**Issue by minecrawler** [thepracticaldev/dev.to#93]
# Make tags on the left removable or collapsible 
### Request or User Story
tbh, I don't need them to be visible all the time and they seem to be in my way rather than helpful where they are now. They drown my UX. I'd prefer to customize my experience a little ;)

### Definition of Done
The tags are out of my way when I don't need them.

**Comment by Zhao-Andy** [comment]
Thanks for the input :)

Ties into #92

**Comment by Zhao-Andy** [comment]
Closing since we've put this in consideration for our future design overhaul. Thanks again for the feedback!
