### ISSUE TITLE
Cover Images with Editor v2

### ISSUE THREAD

**Issue by awwsmm** [thepracticaldev/dev.to#932]
**Describe the bug**
Cover images don't seem to be working with the v2 editor.

**To Reproduce**

1. Click "edit post" on any post
2. Click "Images" at the top-right of the post, to the right of the tags
3. "Choose file" and select an image for the header (I used a 5616 × 3744 JPG)
4. Hit "preview" and the article is previewed on top of the image selection screen (see screenshot)
5. Hit "save changes" and nothing saves, there's no header image afterward

**Expected behavior**
Expected an "upload" button or something after image selection, or at least for the image to appear after hitting "save changes". Expected the preview to open in a new window, not on top of the image selection screen.

**Screenshots**
![screenshot 2018-10-16 18 26 00](https://user-images.githubusercontent.com/29188350/47035135-22ca6800-d171-11e8-826c-59ce7acccc84.png)

**Desktop (please complete the following information):**

- OS: macOS High Sierra, Version 10.13.6 (17G65)
- Browser: Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Additional context**
None.

**Comment by jessleenyc** [comment]
@awwsmm we need to add better error messaging to this. Looks like your file size exceeds the limit of: 4096x4096

**Comment by jessleenyc** [comment]
Closing this issue and opening this instead: https://github.com/thepracticaldev/dev.to/issues/936
