### ISSUE TITLE
Add error message for image upload size

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#936]
**Is your feature request related to a problem? Please describe.**
Inspired by [this](https://github.com/thepracticaldev/dev.to/issues/932) issue, we should add better error messages for image uploads if they exceed resolution and/or file size.

**Additional context**
We're using CarrierWave to handle image upload.

**Comment by champagnepappi** [comment]
@jessleenyc  has this been implemented

**Comment by jessleenyc** [comment]
@champagnepappi don't believe so, just added the approved label if you'd like to work on it.

**Comment by champagnepappi** [comment]
@jessleenyc  leme work on it
