### ISSUE TITLE
Spacing issue in close button of the podcast  bottom bar

### ISSUE THREAD

**Issue by anandhumanoj** [thepracticaldev/dev.to#937]
**Describe the bug**
I know it is a silly and minute issue but that's the way opensource(Issue tracking) works right? So the problem is that the close button is broken into two lines 

**Screenshots**
![screenshot_20181017_002308](https://user-images.githubusercontent.com/38727945/47040501-0562c180-d1a4-11e8-90e7-681b5859ff0d.png)

**Desktop :**

- OS: Linux
- Browser FF 
- Version 62.03

**Comment by anandhumanoj** [comment]
I am not being insane but, I can spot another issue with the right panel overflowing the podcast playback

![image](https://user-images.githubusercontent.com/38727945/47041355-2e845180-d1a6-11e8-827c-906cabd5ee97.png)

**Comment by maestromac** [comment]
Thanks for this issue @anandhumanoj ! Our podcast playback definitely needs to be revisited. This could potentially just be a CSS issue.
