### ISSUE TITLE
Consider adding CodeTriage badge to repository

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#957]
**Is your feature request related to a problem? Please describe.**

I submitted this repo to CodeTriage.com: https://www.codetriage.com/thepracticaldev/dev.to

CodeTriage is a website helping developers monitor issues on their favorite repos developed by [scheenms](https://www.schneems.com/), a well known Ruby developer.

I find it useful and another avenue to get help for this project.

**Describe the solution you'd like**

Adding the badge to the repo's README, it looks like this:

[![Open Source Helpers](https://www.codetriage.com/thepracticaldev/dev.to/badges/users.svg)](https://www.codetriage.com/thepracticaldev/dev.to)

**Additional context**

A byproduct of using codetriage are emails like this one for developers who subscribe to the service:

![](https://user-images.githubusercontent.com/146201/47205030-220a1f80-d385-11e8-8bd4-0be46805b8ce.png)

**Comment by maestromac** [comment]
We are a fan of CodeTriage and would be happy to add that badge 👍
