### ISSUE TITLE
Automatically add contributor badges after PRs are merged

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/dev.to#963]
Currently we manually run a rake task occasionally to award the badges. And I think some people have slipped through the cracks.

Everyone will _eventually_ get their badges as we can re-run the whole list at any point, but it would be nice to have this happen automatically.

We should be able to query for contributors and award badges automatically without too much trouble given the existing GitHub integrations in the app.

I think the simplest thing would be to make this into a rake task we could call periodically. An alternative would be to have a webhook which listens for merges. I'd be happy with basically any implementation of this.

**Comment by fredplante** [comment]
Hey Ben,
I could take a stab on this one if you don't mind

**Comment by benhalpern** [comment]
@fredplante Yeah totally.

You'll probably want to check out the `BadgeRewarder` class. And also note: You _can't_ get the same badge twice so no need to check for this if it's inconvenient.

**Comment by maestromac** [comment]
Resolved by https://github.com/thepracticaldev/dev.to/pull/1016
