### ISSUE TITLE
Bug: Styling issue for Total Post Reactions under dashboard when window is too wide

### ISSUE THREAD

**Issue by theoutlander** [thepracticaldev/dev.to#966]
**Describe the bug**
When I go to the dashboard, I'm noticing CSS issues around the **Total Post Reactions** section.

I've tried this on Chrome & FF. I use a 43" 4K monitor, so sometimes my browser windows are wide.

**To Reproduce**

1. Go to dev.to/dashboard
2. Increase the width of the window
3. You will see the CSS issue around Total Post Reactions

**Expected behavior**
The component should handle wide screens

**Screenshots**
![image](https://user-images.githubusercontent.com/749084/47247914-67494400-d3bb-11e8-829f-5a3257975afc.png)

**Desktop (please complete the following information):**

- OS: Latest OSX
- Browser Chrome
- Version 69

**Comment by nickytonline** [comment]
I can take a look at this if no one else is.

**Comment by nickytonline** [comment]
I cleaned things up a bit by using flexbox (no PR yet), but the main issue is this: `font-size: calc(0.77em + 0.22vw);`. As the screen gets wider and wider, the font gets bigger and bigger. This is why @theoutlander was only seeing it on a large screen and the same happens for me when I maximize a browser window on my external monitor.

Is it necessary to make the font bigger as the screen gets wider? I'd probably just go with a font of a certain size for a screen smaller than 800px wide and one for screens larger than or equal to 800px. Or just keep the font the same size.

Here's the line in question, https://github.com/thepracticaldev/dev.to/blob/master/app/assets/stylesheets/dashboard.scss#L77

**Comment by Zhao-Andy** [comment]
Thanks for the detailed info @nickytonline 👍

**Comment by jessleenyc** [comment]
This is no longer an issue since we changed the styling!
