### ISSUE TITLE
Canonical URL missing from editor V2

### ISSUE THREAD

**Issue by robertcoopercode** [thepracticaldev/dev.to#967]
**Describe the bug**
The editor V2 no longer has the ability to add a `canonical URL`. Not sure if this is intentional or not, but it seemed like a nice feature.

**To Reproduce**

1. Start a new post
2. Look for a place to enter a `canonical URL` and realize there isn't one available (or it is well hidden)

**Expected behavior**
Have a place to add a `canonical URL` to a post.

**Screenshots**
![image](https://user-images.githubusercontent.com/16786990/47248187-a20ca580-d3d6-11e8-8c0d-447decb8dd6f.png)

**Desktop (please complete the following information):**

- OS: MacOS Mojave
- Browser: Chrome
- Version: 69

**Comment by benhalpern** [comment]
Yes. TODO on this is to add space for all the additional configs. Likely another button next to images.

We'll get to this soon if anyone has any thoughts on the implementation.
