### ISSUE TITLE
LaTeX support in articles

### ISSUE THREAD

**Issue by martinbeentjes** [thepracticaldev/dev.to#97]
# _Feature_
### User Story
As an author of an article I want to be able to mathematical typesetting using LaTeX so that readers can read the mathematical typesetting better. 

### Definition of Done
 - [ ] The author can add the LaTeX into the article
 - [ ] The reader sees the rendered LaTeX

### Notes
 * I came upon this idea when I saw the article ["Fun with secrets"](https://dev.to/terceranexus6/fun-with-secrets-2p3) by Paula.
* I suggest using [KaTeX](https://khan.github.io/KaTeX/) to implement the rendering of the math text

**Comment by Zhao-Andy** [comment]
Hey @martinbeentjes, thanks for the feedback. Definitely something we're interested in. We're going to make some overall improvements to the editor soon, and this will probably be on the list.

We're going to close the issue for now though since we're focused on open sourcing the repo.

**Comment by martinbeentjes** [comment]
Thanks for the heads up! And good luck with open sourcing the repo!

**Comment by FRosner** [comment]
Now after the repo is open source, let's get to it! 🤣 

I figured out that DEV uses the [redcarpet](https://github.com/vmg/redcarpet) Markdown parser. It seems that people already tried rendering LaTeX equations in redcarpet: https://github.com/vmg/redcarpet/issues/559

To avoid unwanted interactions with the Markdown syntax, the recommendation seems to be to embed the equations into backticks which turns of Markdown rendering and then inside enclose into dollar signs to enable LaTeX.

I'd be happy to give it a shot unless it's already being worked on or not of interest. What do you think @Zhao-Andy?

**Comment by FRosner** [comment]
I'd like to see 

- [ ] layout of existing posts is not broken

as part of the DoD.

**Comment by pkfrank** [comment]
Hey @FRosner — thanks for opening this back up.  @benhalpern will chime in with a few additional notes shortly.

**Comment by Tadaboody** [comment]
AFAIK this hasn't been implemented yet.
I think this is still applicable and would like it to be re-opened.

**Comment by gypsydave5** [comment]
Would be interested in helping

**Comment by FRosner** [comment]
I wanted to do it but when I had time dev.to was closed source. Now it's open source but I don't have time anymore :(

**Comment by maestromac** [comment]
Feel free to give it a whirl @gypsydave5 ! `MarkdownParser.rb` is where all the processing is situated.

**Comment by AleksandrHovhannisyan** [comment]
What about using MathJax? I added it to my Jekyll blog using these two scripts for any posts that need it:

```html
<script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" type="text/javascript"></script>
<script>
  // Ensures that LaTeX figures don't overflow the page horizontally
  window.MathJax = {
    'HTML-CSS': {
      linebreaks: { automatic: true, width: 'container' }
    }
  };
</script>
```

Katex is probably better if you guys can get it to work; it's faster, for one.
