### ISSUE TITLE
Membership cancellation

### ISSUE THREAD

**Issue by marpme** [thepracticaldev/dev.to#971]
**Describe the bug**
After settling a membership (for i.e. 1$ per month), I paid the preconditioned value and wanted to try if the contract keeps staying alive after canceling it (at least for the time I paid for it). 

What I have noticed: although the membership is priced for 1$/mo, the membership status is immediately removed from my account. I would have expected for it to stay until the end of the membership.

**To Reproduce**

1. Enter a new membership contract for i.e. 1$/mo
2. Being redirected, see all features unlocked etc.
3. Now cancel the contract again
4. See all features are already gone although you paid for a month

**Expected behavior**
The contract should stay until the end of this current period.

**Platforms**

applicable to all platforms.

**Additional context**

https://dev.to/membership

**Comment by jessleenyc** [comment]
@marpme sorry for any miscommunication here. It's expected behavior for membership access to be revoked immediately upon cancellation -- this might be something we revisit later. I'm going to close this issue for now. We're happy to provide you a refund if you email yo@dev.to -- thanks!

**Comment by marpme** [comment]
@jessleenyc I would rather wanted to reactive the current subscription as I just wanted to test out some features to search for some bugs or bad behaviors. I will drop you a message on the given email. Thank you :)
