### ISSUE TITLE
Video stuck in transcoding phase for more than 30h

### ISSUE THREAD

**Issue by yamalight** [thepracticaldev/dev.to#972]
**Describe the bug**

A video I've uploaded has been stuck in transcoding phase for more than 30h

**To Reproduce**

This is the first time it's happened so I'm not sure it's reproducible 🤔

**Expected behavior**

Video should've been transcoded after an hour or so

**Desktop (please complete the following information):**

- OS: Win10
- Browser Chrome
- Version 70

**Additional context**

Link to private post if that can help: https://dev.to/yamalight/unpublished-video--3koc-2ii-temp-slug-915673
Let me know if you guys can get anything from it, or if I should just remove it and reupload it again.
Thanks!

**Comment by marpme** [comment]
Maybe you can add some more details about the video itself. Like the resolution, size, framerate, bitrate, format, encodings etc :) 👍

**Comment by yamalight** [comment]
@marpme sure, here's the (partial) output of ffmpeg:

```
→ ffmpeg.exe -i bxjs-33.mp4                                                
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'bxjs-33.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp41isom
  Duration: 01:08:24.87, start: 0.000000, bitrate: 3245 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 3050 kb/s, 30 fps, 30 tbr, 30k tbn, 60 tbc (default)
    Metadata:
      encoder         : AVC Coding
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 192 kb/s (default)
```

I've used the same way / settings for past ~18 episodes without any issues. This last one errored for some weird reason.

**Comment by jessleenyc** [comment]
Thanks for letting us know @yamalight! 
@benhalpern can you take a look at this?

**Comment by maestromac** [comment]
Hey @yamalight, is this still an issue?

**Comment by yamalight** [comment]
@maestromac the new videos have been working without any issues so far. 
the one that I've originally reported is still stuck at that phase - should I remove it? 🤔

**Comment by maestromac** [comment]
@yamalight yeah go ahead and remove it. Let us know if you run into any issue. Closing this issue since it seems like an one-off anomaly.

**Comment by yamalight** [comment]
@maestromac got it, thanks! 👍
