### ISSUE TITLE
Fix login in PWA

### ISSUE THREAD

**Issue by l579** [thepracticaldev/dev.to#978]
When going with the progressive web app it’s not possible to register via the web app. You are always redirected to Safari (using iPhone with GitHub auth). Would be nice if you can fix that so I can browse dev.to posts with the icon on my homescreen instead of going to the browser all the time. It doesn’t have my follows when I’m not logged in (of course)

**Comment by jessleenyc** [comment]
@l579 sorry you have to encounter this. It's a known issue related to apple not fully supporting PWAs. We have another thread going at https://github.com/thepracticaldev/dev.to/issues/202 if you want to follow along. Closing this since it's a duplicate, thanks for flagging though.

**Comment by l579** [comment]
https://medium.com/@jonnykalambay/progressive-web-apps-with-oauth-dont-repeat-my-mistake-16a4063ce113
