### ISSUE TITLE
Allow others to edit my post

### ISSUE THREAD

**Issue by rattanakchea** [thepracticaldev/dev.to#98]
# _TASK or Feature_
### Definition of Done
It would be nice to be able to co-author on a post. Though this feature would add a significant time in development. Maybe make some users with permission to edit posts. This would allow for quick editing for certain typos, or mistakes.

**Comment by pkfrank** [comment]
Hey @rattanakchea thanks for the suggestion.  This is definitely something that's on our roadmap, but we won't be prioritizing it imminently.

In the meantime, you can send other users a "draft" of your post.  Simply keep the post as `published: false` and then hit `save`.  You'll be given a preview URL that you can share with trusted friends / proofreaders.

You can additionally add a co-author to an article.  Here's an [example](https://dev.to/sehurlburt/were-stephanie-hurlburt-and-rich-geldreich-ask-us-anything) — look at the "author line" just under the cover image.  This is a fairly undeveloped feature and an admin currently has to manually add these co-authors; but, if you'd like to do so, just shoot an email to yo@dev.to and we'll get it set up.
