### ISSUE TITLE
Some buttons on /settings/organization are bigger than expected

### ISSUE THREAD

**Issue by pkfrank** [thepracticaldev/dev.to#982]
**Describe the bug**
As a member of an organization with multiple admins, the `revoke admin status` button is much larger than expected.

**To Reproduce**
Ensure that you're an admin of an organization with multiple admins.  Navigate to https://dev.to/settings/organization

**Expected behavior**
The `revoke admin status` button is styled to be more consistent with other information on the page.  Note: we might want some visual indicator that something like `admin` is a current reflection of a role, whereas `make admin` is an action button.

**Screenshots**
![Current big buttons](https://cl.ly/0d43f80af80c/Image%202018-10-22%20at%205.52.09%20PM.png)
![Desired smaller buttons](https://cl.ly/68d72cbc3619/Image%202018-10-22%20at%205.52.00%20PM.png)

**Comment by Zhao-Andy** [comment]
Hmm this is a CSS issue; I think the relevant file would be `settings.scss` if anyone wants to take a look. It might also be the `.cta` class but not sure.

**Comment by Zhao-Andy** [comment]
Oops, it's fixed 🤷‍♂️
