### ISSUE TITLE
Clicking on reactions multiple times shows the wrong count

### ISSUE THREAD

**Issue by gautamkrishnar** [thepracticaldev/dev.to#985]
**Describe the bug**
Clicking on reactions multiple times shows wrong count

**To Reproduce**

1. Open any article
2. Click multiple times on same reaction button.
3. Observe

**Expected behavior**
The react button should be disabled while the API Completes

**Screenshots**
![Preview](https://media.giphy.com/media/1BcB9PzAO9OFnStUPU/giphy.gif)

**Desktop (please complete the following information):**

- OS: Mac OS Mojave 10.14 (18A391)
- Browser Chrome 
- Version: 70.0.3538.67 (Official Build) (64-bit)

I would like to work on this issue. Please let me know whether **disabling the react button** till the last API Call is complete would be an acceptable fix for the issue?

**Comment by jessleenyc** [comment]
@gautamkrishnar that seems like an appropriate fix as long as it's not visible to the user. We have some adjustments that will fix reaction count if it goes out of sync periodically but this would definitely be a better experience. Approving the issue and feel free to work on it!

**Comment by maestromac** [comment]
Resolved by #989
