### ISSUE TITLE
add descriptive tooltips to the reaction-buttons

### ISSUE THREAD

**Issue by guntbert** [thepracticaldev/dev.to#99]
# _TASK or Feature_
### Request or User Story
I am talking about
```
<div class="article-actions" id="article-reaction-actions">  
  <button id="reaction-butt-like" class="article-reaction-butt activated user-activated" data-category="like" alt="heart-emoji">  
 ....
</div>
```
at the end of all articles.

I suggest adding a `title` attribute to every button to create a tooltip with an explanation about the "message" that the author gets when I click on this button.

For someone not versed in the current emoji vocabulary it is difficult to understand what the "meaning" of each button is.
- heart is easy, the emoji name in source code says "like" - ok
- ??, reading the source code: "thinking" - I can guess what it means
- hands: looks like clapping hands (=applause), but the source code says: "raised hands" - ???
- unicorn: - ???
### Definition of Done
All action buttons have explaining and (even for people who don't have English as first language) easily understandable tooltips.

**Comment by Zhao-Andy** [comment]
Hey @guntbert, thanks for the feedback. We've added some titles into the emojis. The emojis are actually meant to be a bit vague and up for interpretation on both sides. While I get that it might be hard to give a proper reaction, the idea is that we want people to have a bit more nuance when using the reactions.

There's actually a discussion thread about this:
https://dev.to/_bigblind/how-do-you-use-each-of-the-emoji-reactions-on-devto

Feel free to chime in there, too. :)
