### ISSUE TITLE
Can One Person Create or Join Only One Organization on Dev.to?

### ISSUE THREAD

**Issue by bauripalash** [thepracticaldev/dev.to#998]
I had a dev.to blog for my company XED Technologies at [@xedtech](https://dev.to/xedtech), and I decided that my another project, **The Cyber** also needs a  organization page, but there's no way to create another or just delete the **@xedtech**

**Comment by Zhao-Andy** [comment]
Thanks for the feature request @bauripalash. We'll definitely want to support deleting your organization in the future, as well as being able to join multiple organizations. Since they're two separate issues, I'll write a new issue for deleting an organization.

**Comment by yashghelani** [comment]
I’d love to be able to create & join multiple organisations :)

**Comment by jlooper** [comment]
I also am excited to be able to join two organizations! thanks!

**Comment by Zhao-Andy** [comment]
Resolved via #2583 and #3041 :)
